Terraria: NPC.AI_003_Fighters
AI_003_Fighters()
void NPC.AI_003_Fighters () inline private
     {
         if (Main.player[target].position.Y + (float)Main.player[target].height == position.Y + (float)height)
         {
             directionY = -1;
         }
         bool flag = false;
         if (type == 624 && AI_003_Gnomes_ShouldTurnToStone())
         {
             int num = (int)(base.Center.X / 16f);
             int num2 = (int)(base.Bottom.Y / 16f);
             position += netOffset;
             int num3 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, Color.White, 0.5f);
             Main.dust[num3].velocity *= 0.2f;
             position -= netOffset;
             if (WorldGen.SolidTileAllowBottomSlope(num, num2))
             {
                 for (int i = 0; i < 5; i++)
                 {
                     position += netOffset;
                     int num4 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, Color.White, 0.5f);
                     Main.dust[num4].velocity *= 0.2f;
                     position -= netOffset;
                 }
                 if (Main.netMode != 1 && TileObject.CanPlace(num, num2 - 1, 567, 0, direction, out var _, onlyCheck: true) && WorldGen.PlaceTile(num, num2 - 1, 567, mute: false, forced: false, -1, Main.rand.Next(5)))
                 {
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendTileSquare(-1, num, num2 - 2, 1, 2);
                     }
                     if (Main.netMode != 1)
                     {
                         if (IsNPCValidForBestiaryKillCredit())
{
                             Main.BestiaryTracker.Kills.RegisterKill(this);
                         }
                         CountKillForBannersAndDropThem();
                     }
                     life = 0;
                     active = false;
                     AchievementsHelper.NotifyProgressionEvent(24);
                     return;
                 }
             }
         }
         if (type == 466)
         {
             int num5 = 200;
             if (ai[2] == 0f)
             {
                 alpha = num5;
                 TargetClosest();
                 if (!Main.player[target].dead && (Main.player[target].Center - base.Center).Length() < 170f)
                 {
                     ai[2] = -16f;
                 }
                 if (velocity.X != 0f || velocity.Y < 0f || velocity.Y > 2f || justHit)
                 {
                     ai[2] = -16f;
                 }
                 return;
             }
             if (ai[2] < 0f)
             {
                 if (alpha > 0)
                 {
                     alpha -= num5 / 16;
                     if (alpha < 0)
                     {
                         alpha = 0;
                     }
                 }
                 ai[2] += 1f;
                 if (ai[2] == 0f)
                 {
                     ai[2] = 1f;
                     velocity.X = direction * 2;
                 }
                 return;
             }
             alpha = 0;
         }
         if (type == 166)
         {
             if (Main.netMode != 1 && Main.rand.Next(240) == 0)
             {
                 ai[2] = Main.rand.Next(-480, -60);
                 netUpdate = true;
             }
             if (ai[2] < 0f)
             {
                 TargetClosest();
                 if (justHit)
                 {
                     ai[2] = 0f;
                 }
                 if (Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                 {
                     ai[2] = 0f;
                 }
             }
             if (ai[2] < 0f)
             {
                 velocity.X *= 0.9f;
                 if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                 {
                     velocity.X = 0f;
                 }
                 ai[2] += 1f;
                 if (ai[2] == 0f)
                 {
                     velocity.X = (float)direction * 0.1f;
                 }
                 return;
             }
         }
         if (type == 461)
         {
             if (wet)
             {
                 knockBackResist = 0f;
                 ai[3] = -0.10101f;
                 noGravity = true;
                 Vector2 center = base.Center;
                 width = 34;
                 height = 24;
                 position.X = center.X - (float)(width / 2);
                 position.Y = center.Y - (float)(height / 2);
                 TargetClosest();
                 if (collideX)
                 {
                     velocity.X = 0f - oldVelocity.X;
                 }
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 if (velocity.X > 0f)
                 {
                     direction = 1;
                 }
                 if (Collision.CanHit(position, width, height, Main.player[target].Center, 1, 1))
                 {
                     Vector2 vector = Main.player[target].Center - base.Center;
                     vector.Normalize();
                     vector *= 5f;
                     velocity = (velocity * 19f + vector) / 20f;
                     return;
                 }
                 float num6 = 5f;
                 if (velocity.Y > 0f)
                 {
                     num6 = 3f;
                 }
                 if (velocity.Y < 0f)
                 {
                     num6 = 8f;
                 }
                 Vector2 vector2 = new Vector2(direction, -1f);
                 vector2.Normalize();
                 vector2 *= num6;
                 if (num6 < 5f)
                 {
                     velocity = (velocity * 24f + vector2) / 25f;
                 }
                 else
                 {
                     velocity = (velocity * 9f + vector2) / 10f;
                 }
                 return;
             }
             knockBackResist = 0.4f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
             noGravity = false;
             Vector2 center2 = base.Center;
             width = 18;
             height = 40;
             position.X = center2.X - (float)(width / 2);
             position.Y = center2.Y - (float)(height / 2);
             if (ai[3] == -0.10101f)
             {
                 ai[3] = 0f;
                 float num7 = velocity.Length();
                 num7 *= 2f;
                 if (num7 > 10f)
                 {
                     num7 = 10f;
                 }
                 velocity.Normalize();
                 velocity *= num7;
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 if (velocity.X > 0f)
                 {
                     direction = 1;
                 }
                 spriteDirection = direction;
             }
         }
         if (type == 586)
         {
             if (alpha == 255)
             {
                 TargetClosest();
                 spriteDirection = direction;
                 velocity.Y = -6f;
                 netUpdate = true;
                 for (int j = 0; j < 35; j++)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 5);
                     dust.velocity *= 1f;
                     dust.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust.velocity += velocity * 0.5f;
                 }
             }
             alpha -= 15;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             position += netOffset;
             if (alpha != 0)
             {
                 for (int k = 0; k < 2; k++)
                 {
                     Dust dust2 = Dust.NewDustDirect(position, width, height, 5);
                     dust2.velocity *= 1f;
                     dust2.scale = 1f + Main.rand.NextFloat() * 0.5f;
                     dust2.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                     dust2.velocity += velocity * 0.3f;
                 }
             }
             if (Main.rand.Next(3) == 0)
             {
                 Dust dust3 = Dust.NewDustDirect(position, width, height, 5);
                 dust3.velocity *= 0f;
                 dust3.alpha = 120;
                 dust3.scale = 0.7f + Main.rand.NextFloat() * 0.5f;
                 dust3.velocity += velocity * 0.3f;
             }
             position -= netOffset;
             if (wet)
             {
                 knockBackResist = 0f;
                 ai[3] = -0.10101f;
                 noGravity = true;
                 Vector2 center3 = base.Center;
                 position.X = center3.X - (float)(width / 2);
                 position.Y = center3.Y - (float)(height / 2);
                 TargetClosest();
                 if (collideX)
                 {
                     velocity.X = 0f - oldVelocity.X;
                 }
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 if (velocity.X > 0f)
                 {
                     direction = 1;
                 }
                 if (Collision.CanHit(position, width, height, Main.player[target].Center, 1, 1))
                 {
                     Vector2 vector3 = Main.player[target].Center - base.Center;
                     vector3.Normalize();
                     float num8 = 1f;
                     num8 += Math.Abs(base.Center.Y - Main.player[target].Center.Y) / 40f;
                     num8 = MathHelper.Clamp(num8, 5f, 20f);
                     vector3 *= num8;
                     if (velocity.Y > 0f)
                     {
                         velocity = (velocity * 29f + vector3) / 30f;
                     }
                     else
                     {
                         velocity = (velocity * 4f + vector3) / 5f;
                     }
                     return;
                 }
                 float num9 = 5f;
                 if (velocity.Y > 0f)
                 {
                     num9 = 3f;
                 }
                 if (velocity.Y < 0f)
                 {
                     num9 = 8f;
                 }
                 Vector2 vector4 = new Vector2(direction, -1f);
                 vector4.Normalize();
                 vector4 *= num9;
                 if (num9 < 5f)
                 {
                     velocity = (velocity * 24f + vector4) / 25f;
                 }
                 else
                 {
                     velocity = (velocity * 9f + vector4) / 10f;
                 }
                 return;
             }
             noGravity = false;
             Vector2 center4 = base.Center;
             position.X = center4.X - (float)(width / 2);
             position.Y = center4.Y - (float)(height / 2);
             if (ai[3] == -0.10101f)
             {
                 ai[3] = 0f;
                 float num10 = velocity.Length();
                 num10 *= 2f;
                 if (num10 > 15f)
                 {
                     num10 = 15f;
                 }
                 velocity.Normalize();
                 velocity *= num10;
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 if (velocity.X > 0f)
                 {
                     direction = 1;
                 }
                 spriteDirection = direction;
             }
         }
         if (type == 379 || type == 380)
         {
             if (ai[3] < 0f)
             {
                 directionY = -1;
                 flag = false;
                 damage = 0;
                 velocity.X *= 0.93f;
                 if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                 {
                     velocity.X = 0f;
                 }
                 int num11 = (int)(0f - ai[3] - 1f);
                 int num12 = Math.Sign(Main.npc[num11].Center.X - base.Center.X);
                 if (num12 != direction)
                 {
                     velocity.X = 0f;
                     direction = num12;
                     netUpdate = true;
                 }
                 if (justHit && Main.netMode != 1 && Main.npc[num11].localAI[0] == 0f)
                 {
                     Main.npc[num11].localAI[0] = 1f;
                 }
                 if (ai[0] < 1000f)
                 {
                     ai[0] = 1000f;
                 }
                 if ((ai[0] += 1f) >= 1300f)
                 {
                     ai[0] = 1000f;
                     netUpdate = true;
                 }
                 return;
             }
             if (ai[0] >= 1000f)
             {
                 ai[0] = 0f;
             }
             damage = defDamage;
         }
         if (type == 383 && ai[2] == 0f && localAI[0] == 0f && Main.netMode != 1)
         {
             int num13 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 384, whoAmI);
             ai[2] = num13 + 1;
             localAI[0] = -1f;
             netUpdate = true;
             Main.npc[num13].ai[0] = whoAmI;
             Main.npc[num13].netUpdate = true;
         }
         if (type == 383)
         {
             int num14 = (int)ai[2] - 1;
             if (num14 != -1 && Main.npc[num14].active && Main.npc[num14].type == 384)
             {
                 dontTakeDamage = true;
             }
             else
             {
                 dontTakeDamage = false;
                 ai[2] = 0f;
                 if (localAI[0] == -1f)
                 {
                     localAI[0] = 180f;
                 }
                 if (localAI[0] > 0f)
                 {
                     localAI[0] -= 1f;
                 }
             }
         }
         if (type == 482)
         {
             int num15 = 300;
             int num16 = 120;
             dontTakeDamage = false;
             if (ai[2] < 0f)
             {
                 dontTakeDamage = true;
                 ai[2] += 1f;
                 velocity.X *= 0.9f;
                 if ((double)Math.Abs(velocity.X) < 0.001)
                 {
                     velocity.X = 0.001f * (float)direction;
                 }
                 if (Math.Abs(velocity.Y) > 1f)
                 {
                     ai[2] += 10f;
                 }
                 if (ai[2] >= 0f)
                 {
                     netUpdate = true;
                     velocity.X += (float)direction * 0.3f;
                 }
                 return;
             }
             if (ai[2] < (float)num15)
             {
                 if (justHit)
                 {
                     ai[2] += 15f;
                 }
                 ai[2] += 1f;
             }
             else if (velocity.Y == 0f)
             {
                 ai[2] = -num16;
                 netUpdate = true;
             }
         }
         if (type == 631)
         {
             if (target < 0 || target == 255 || Main.player[target].dead || !Main.player[target].active)
             {
                 TargetClosest(ai[2] > 0f);
             }
             Player player = Main.player[target];
             bool flag2 = !player.dead && player.active && base.Center.Distance(player.Center) < 320f;
             int num17 = 100;
             int num18 = 32;
             if (ai[2] == 0f)
             {
                 ai[3] = 65f;
                 if (flag2 && Collision.CanHit(player, this))
                 {
                     ai[2] = num17;
                     ai[3] = 0f;
                     velocity.X = (float)direction * 0.01f;
                     netUpdate = true;
                 }
             }
             else
             {
                 if (ai[2] < (float)num17)
                 {
                     ai[2] += 1f;
                     velocity.X *= 0.9f;
                     if ((double)Math.Abs(velocity.X) < 0.001)
                     {
                         velocity.X = 0f;
                     }
                     if (Math.Abs(velocity.Y) > 1f)
                     {
                         ai[2] = 0f;
                     }
                     if (ai[2] == (float)(num17 - num18 / 2) && Main.netMode != 1 && !player.Hitbox.Intersects(base.Hitbox) && Collision.CanHit(player, this))
                     {
                         float num19 = 8f;
                         Vector2 center5 = base.Center;
                         Vector2 vector5 = DirectionTo(Main.player[target].Center) * num19;
                         if (vector5.HasNaNs())
{
                             vector5 = new Vector2((float)direction * num19, 0f);
                         }
                         int num20 = 20;
                         Vector2 v = vector5 + Utils.RandomVector2(Main.rand, -0.8f, 0.8f);
                         v = v.SafeNormalize(Vector2.Zero);
                         v *= num19;
                         Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center5.X, center5.Y, v.X, v.Y, 909, num20, 1f, Main.myPlayer);
                     }
                     if (ai[2] >= (float)num17)
                     {
                         ai[2] = num17;
                         ai[3] = 0f;
                         velocity.X = (float)direction * 0.01f;
                         netUpdate = true;
                     }
                     return;
                 }
                 if (velocity.Y == 0f && flag2 && (player.Hitbox.Intersects(base.Hitbox) || Collision.CanHit(player, this)))
                 {
                     ai[2] = num17 - num18;
                     netUpdate = true;
                 }
             }
         }
         if (type == 480)
         {
             int num21 = 180;
             int num22 = 300;
             int num23 = 180;
             int num24 = 60;
             int num25 = 20;
             if (life < lifeMax / 3)
             {
                 num21 = 120;
                 num22 = 240;
                 num23 = 240;
                 num24 = 90;
             }
             if (ai[2] > 0f)
             {
                 ai[2] -= 1f;
             }
             else if (ai[2] == 0f)
             {
                 if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && velocity.Y == 0f && Distance(Main.player[target].Center) < 900f && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                 {
                     ai[2] = -num23 - num25;
                     netUpdate = true;
                 }
             }
             else
             {
                 if (ai[2] < 0f && ai[2] < (float)(-num23))
                 {
                     position += netOffset;
                     velocity.X *= 0.9f;
                     if (velocity.Y < -2f || velocity.Y > 4f || justHit)
                     {
                         ai[2] = num21;
                     }
                     else
                     {
                         ai[2] += 1f;
                         if (ai[2] == 0f)
{
                             ai[2] = num22;
                         }
                     }
                     float num26 = ai[2] + (float)num23 + (float)num25;
                     if (num26 == 1f)
                     {
                         SoundEngine.PlaySound(4, (int)position.X, (int)position.Y, 17);
                     }
                     if (num26 < (float)num25)
                     {
                         Vector2 vector6 = base.Top + new Vector2(spriteDirection * 6, 6f);
                         float num27 = MathHelper.Lerp(20f, 30f, (num26 * 3f + 50f) / 182f);
                         Main.rand.NextFloat();
                         for (float num28 = 0f; num28 < 2f; num28 += 1f)
{
                             Vector2 vector7 = Vector2.UnitY.RotatedByRandom(6.2831854820251465) * (Main.rand.NextFloat() * 0.5f + 0.5f);
                             Dust obj = Main.dust[Dust.NewDust(vector6, 0, 0, 228)];
                             obj.position = vector6 + vector7 * num27;
                             obj.noGravity = true;
                             obj.velocity = vector7 * 2f;
                             obj.scale = 0.5f + Main.rand.NextFloat() * 0.5f;
                         }
                     }
                     Lighting.AddLight(base.Center, 0.9f, 0.75f, 0.1f);
                     position -= netOffset;
                     return;
                 }
                 if (ai[2] < 0f && ai[2] >= (float)(-num23))
                 {
                     position += netOffset;
                     Lighting.AddLight(base.Center, 0.9f, 0.75f, 0.1f);
                     velocity.X *= 0.9f;
                     if (velocity.Y < -2f || velocity.Y > 4f || justHit)
                     {
                         ai[2] = num21;
                     }
                     else
                     {
                         ai[2] += 1f;
                         if (ai[2] == 0f)
{
                             ai[2] = num22;
                         }
                     }
                     float num29 = ai[2] + (float)num23;
                     if (num29 < 180f && (Main.rand.Next(3) == 0 || ai[2] % 3f == 0f))
                     {
                         Vector2 vector8 = base.Top + new Vector2(spriteDirection * 10, 10f);
                         float num30 = MathHelper.Lerp(20f, 30f, (num29 * 3f + 50f) / 182f);
                         Main.rand.NextFloat();
                         for (float num31 = 0f; num31 < 1f; num31 += 1f)
{
                             Vector2 vector9 = Vector2.UnitY.RotatedByRandom(6.2831854820251465) * (Main.rand.NextFloat() * 0.5f + 0.5f);
                             Dust obj2 = Main.dust[Dust.NewDust(vector8, 0, 0, 228)];
                             obj2.position = vector8 + vector9 * num30;
                             obj2.noGravity = true;
                             obj2.velocity = vector9 * 4f;
                             obj2.scale = 0.5f + Main.rand.NextFloat();
                         }
                     }
                     position -= netOffset;
                     if (Main.netMode == 2)
                     {
                         return;
                     }
                     Player player2 = Main.player[Main.myPlayer];
                     _ = Main.myPlayer;
                     if (player2.dead || !player2.active || player2.FindBuffIndex(156) != -1)
                     {
                         return;
                     }
                     Vector2 vector10 = player2.Center - base.Center;
                     if (!(vector10.Length() < 700f))
                     {
                         return;
                     }
                     bool flag3 = vector10.Length() < 30f;
                     if (!flag3)
                     {
                         float x = ((float)Math.PI / 4f).ToRotationVector2().X;
                         Vector2 vector11 = Vector2.Normalize(vector10);
                         if (vector11.X > x || vector11.X < 0f - x)
{
                             flag3 = true;
                         }
                     }
                     if (((player2.Center.X < base.Center.X && direction < 0 && player2.direction > 0) || (player2.Center.X > base.Center.X && direction > 0 && player2.direction < 0)) && flag3 && (Collision.CanHitLine(base.Center, 1, 1, player2.Center, 1, 1) || Collision.CanHitLine(base.Center - Vector2.UnitY * 16f, 1, 1, player2.Center, 1, 1) || Collision.CanHitLine(base.Center + Vector2.UnitY * 8f, 1, 1, player2.Center, 1, 1)) && !player2.creativeGodMode)
                     {
                         player2.AddBuff(156, num24 + (int)ai[2] * -1);
                     }
                     return;
                 }
             }
         }
         if (type == 471)
         {
             if (ai[3] < 0f)
             {
                 knockBackResist = 0f;
                 defense = (int)((double)defDefense * 1.1);
                 noGravity = true;
                 noTileCollide = true;
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 else if (velocity.X > 0f)
                 {
                     direction = 1;
                 }
                 rotation = velocity.X * 0.1f;
                 if (Main.netMode != 1)
                 {
                     localAI[3] += 1f;
                     if (localAI[3] > (float)Main.rand.Next(20, 180))
                     {
                         localAI[3] = 0f;
                         Vector2 center6 = base.Center;
                         center6 += velocity;
                         NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center6.X, (int)center6.Y, 30);
                     }
                 }
             }
             else
             {
                 localAI[3] = 0f;
                 knockBackResist = 0.35f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
                 rotation *= 0.9f;
                 defense = defDefense;
                 noGravity = false;
                 noTileCollide = false;
             }
             if (ai[3] == 1f)
             {
                 knockBackResist = 0f;
                 defense += 10;
             }
             if (ai[3] == -1f)
             {
                 TargetClosest();
                 float num32 = 8f;
                 float num33 = 40f;
                 Vector2 vector12 = Main.player[target].Center - base.Center;
                 float num34 = vector12.Length();
                 num32 += num34 / 200f;
                 vector12.Normalize();
                 vector12 *= num32;
                 velocity = (velocity * (num33 - 1f) + vector12) / num33;
                 if (num34 < 500f && !Collision.SolidCollision(position, width, height))
                 {
                     ai[3] = 0f;
                     ai[2] = 0f;
                 }
                 return;
             }
             if (ai[3] == -2f)
             {
                 velocity.Y -= 0.2f;
                 if (velocity.Y < -10f)
                 {
                     velocity.Y = -10f;
                 }
                 if (Main.player[target].Center.Y - base.Center.Y > 200f)
                 {
                     TargetClosest();
                     ai[3] = -3f;
                     if (Main.player[target].Center.X > base.Center.X)
                     {
                         ai[2] = 1f;
                     }
                     else
                     {
                         ai[2] = -1f;
                     }
                 }
                 velocity.X *= 0.99f;
                 return;
             }
             if (ai[3] == -3f)
             {
                 if (direction == 0)
                 {
                     TargetClosest();
                 }
                 if (ai[2] == 0f)
                 {
                     ai[2] = direction;
                 }
                 velocity.Y *= 0.9f;
                 velocity.X += ai[2] * 0.3f;
                 if (velocity.X > 10f)
                 {
                     velocity.X = 10f;
                 }
                 if (velocity.X < -10f)
                 {
                     velocity.X = -10f;
                 }
                 float num35 = Main.player[target].Center.X - base.Center.X;
                 if ((ai[2] < 0f && num35 > 300f) || (ai[2] > 0f && num35 < -300f))
                 {
                     ai[3] = -4f;
                     ai[2] = 0f;
                 }
                 else if (Math.Abs(num35) > 800f)
                 {
                     ai[3] = -1f;
                     ai[2] = 0f;
                 }
                 return;
             }
             if (ai[3] == -4f)
             {
                 ai[2] += 1f;
                 velocity.Y += 0.1f;
                 if (velocity.Length() > 4f)
                 {
                     velocity *= 0.9f;
                 }
                 int num36 = (int)base.Center.X / 16;
                 int num37 = (int)(position.Y + (float)height + 12f) / 16;
                 bool flag4 = false;
                 for (int l = num36 - 1; l <= num36 + 1; l++)
                 {
                     if (Main.tile[l, num37] == null)
                     {
                         Main.tile[num36, num37] = new Tile();
                     }
                     if (Main.tile[l, num37].active() && Main.tileSolid[Main.tile[l, num37].type])
                     {
                         flag4 = true;
                     }
                 }
                 if (flag4 && !Collision.SolidCollision(position, width, height))
                 {
                     ai[3] = 0f;
                     ai[2] = 0f;
                 }
                 else if (ai[2] > 300f || base.Center.Y > Main.player[target].Center.Y + 200f)
                 {
                     ai[3] = -1f;
                     ai[2] = 0f;
                 }
             }
             else
             {
                 if (ai[3] == 1f)
                 {
                     Vector2 center7 = base.Center;
                     center7.Y -= 70f;
                     velocity.X *= 0.8f;
                     ai[2] += 1f;
                     if (ai[2] == 60f)
                     {
                         if (Main.netMode != 1)
{
                             NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center7.X, (int)center7.Y + 18, 472);
                         }
                     }
                     else if (ai[2] >= 90f)
                     {
                         ai[3] = -2f;
                         ai[2] = 0f;
                     }
                     for (int m = 0; m < 2; m++)
                     {
                         Vector2 vector13 = center7;
                         Vector2 vector14 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                         vector14.Normalize();
                         vector14 *= (float)Main.rand.Next(0, 100) * 0.1f;
                         Vector2 vector15 = vector13 + vector14;
                         vector14.Normalize();
                         vector14 *= (float)Main.rand.Next(50, 90) * 0.1f;
                         int num38 = Dust.NewDust(vector15, 1, 1, 27);
                         Main.dust[num38].velocity = -vector14 * 0.3f;
                         Main.dust[num38].alpha = 100;
                         if (Main.rand.Next(2) == 0)
{
                             Main.dust[num38].noGravity = true;
                             Main.dust[num38].scale += 0.3f;
                         }
                     }
                     return;
                 }
                 ai[2] += 1f;
                 int num39 = 10;
                 if (velocity.Y == 0f && CountNPCS(472) < num39)
                 {
                     if (ai[2] >= 180f)
                     {
                         ai[2] = 0f;
                         ai[3] = 1f;
                     }
                 }
                 else
                 {
                     if (CountNPCS(472) >= num39)
                     {
                         ai[2] += 1f;
                     }
                     if (ai[2] >= 360f)
                     {
                         ai[2] = 0f;
                         ai[3] = -2f;
                         velocity.Y -= 3f;
                     }
                 }
                 if (target >= 0 && !Main.player[target].dead && (Main.player[target].Center - base.Center).Length() > 800f)
                 {
                     ai[3] = -1f;
                     ai[2] = 0f;
                 }
             }
             if (Main.player[target].dead)
             {
                 TargetClosest();
                 if (Main.player[target].dead)
                 {
                     EncourageDespawn(1);
                 }
             }
         }
         if (type == 419)
         {
             reflectsProjectiles = false;
             takenDamageMultiplier = 1f;
             int num40 = 6;
             int num41 = 10;
             float num42 = 16f;
             if (ai[2] > 0f)
             {
                 ai[2] -= 1f;
             }
             if (ai[2] == 0f)
             {
                 if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                 {
                     ai[2] = -1f;
                     netUpdate = true;
                     TargetClosest();
                 }
             }
             else
             {
                 if (ai[2] < 0f && ai[2] > (float)(-num40))
                 {
                     ai[2] -= 1f;
                     velocity.X *= 0.9f;
                     return;
                 }
                 if (ai[2] == (float)(-num40))
                 {
                     ai[2] -= 1f;
                     TargetClosest();
                     Vector2 vector16 = DirectionTo(Main.player[target].Top + new Vector2(0f, -30f));
                     if (vector16.HasNaNs())
                     {
                         vector16 = Vector2.Normalize(new Vector2(spriteDirection, -1f));
                     }
                     velocity = vector16 * num42;
                     netUpdate = true;
                     return;
                 }
                 if (ai[2] < (float)(-num40))
                 {
                     ai[2] -= 1f;
                     if (velocity.Y == 0f)
                     {
                         ai[2] = 60f;
                     }
                     else if (ai[2] < (float)(-num40 - num41))
                     {
                         velocity.Y += 0.15f;
                         if (velocity.Y > 24f)
{
                             velocity.Y = 24f;
                         }
                     }
                     reflectsProjectiles = true;
                     takenDamageMultiplier = 3f;
                     if (justHit)
                     {
                         ai[2] = 60f;
                         netUpdate = true;
                     }
                     return;
                 }
             }
         }
         if (type == 415)
         {
             int num43 = 42;
             int num44 = 18;
             if (justHit)
             {
                 ai[2] = 120f;
                 netUpdate = true;
             }
             if (ai[2] > 0f)
             {
                 ai[2] -= 1f;
             }
             if (ai[2] == 0f)
             {
                 int num45 = 0;
                 for (int n = 0; n < 200; n++)
                 {
                     if (Main.npc[n].active && Main.npc[n].type == 516)
                     {
                         num45++;
                     }
                 }
                 if (num45 > 6)
                 {
                     ai[2] = 90f;
                 }
                 else if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                 {
                     ai[2] = -1f;
                     netUpdate = true;
                     TargetClosest();
                 }
             }
             else if (ai[2] < 0f && ai[2] > (float)(-num43))
             {
                 ai[2] -= 1f;
                 if (ai[2] == (float)(-num43))
                 {
                     ai[2] = 180 + 30 * Main.rand.Next(10);
                 }
                 velocity.X *= 0.8f;
                 if (ai[2] == (float)(-num44) || ai[2] == (float)(-num44 - 8) || ai[2] == (float)(-num44 - 16))
                 {
                     position += netOffset;
                     for (int num46 = 0; num46 < 20; num46++)
                     {
                         Vector2 vector17 = base.Center + Vector2.UnitX * spriteDirection * 40f;
                         Dust obj3 = Main.dust[Dust.NewDust(vector17, 0, 0, 259)];
                         Vector2 vector18 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                         obj3.position = vector17 + vector18 * 4f;
                         obj3.velocity = vector18 * 2f + Vector2.UnitX * Main.rand.NextFloat() * spriteDirection * 3f;
                         obj3.scale = 0.3f + vector18.X * (float)(-spriteDirection);
                         obj3.fadeIn = 0.7f;
                         obj3.noGravity = true;
                     }
                     position -= netOffset;
                     if (velocity.X > -0.5f && velocity.X < 0.5f)
                     {
                         velocity.X = 0f;
                     }
                     if (Main.netMode != 1)
                     {
                         NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X + spriteDirection * 45, (int)base.Center.Y + 8, 516, 0, 0f, 0f, 0f, 0f, target);
                     }
                 }
                 return;
             }
         }
         if (type == 428)
         {
             localAI[0] += 1f;
             if (localAI[0] >= 300f)
             {
                 int num47 = (int)base.Center.X / 16 - 1;
                 int num48 = (int)base.Center.Y / 16 - 1;
                 if (!Collision.SolidTiles(num47, num47 + 2, num48, num48 + 1) && Main.netMode != 1)
                 {
                     Transform(427);
                     life = lifeMax;
                     localAI[0] = 0f;
                     return;
                 }
             }
             int num49 = 0;
             num49 = ((localAI[0] < 60f) ? 16 : ((localAI[0] < 120f) ? 8 : ((localAI[0] < 180f) ? 4 : ((localAI[0] < 240f) ? 2 : ((!(localAI[0] < 300f)) ? 1 : 1)))));
             if (Main.rand.Next(num49) == 0)
             {
                 position += netOffset;
                 Dust dust4 = Main.dust[Dust.NewDust(position, width, height, 229)];
                 dust4.noGravity = true;
                 dust4.scale = 1f;
                 dust4.noLight = true;
                 dust4.velocity = DirectionFrom(dust4.position) * dust4.velocity.Length();
                 dust4.position -= dust4.velocity * 5f;
                 dust4.position.X += direction * 6;
                 dust4.position.Y += 4f;
                 position -= netOffset;
             }
         }
         if (type == 427)
         {
             localAI[0] += 1f;
             localAI[0] += Math.Abs(velocity.X) / 2f;
             if (localAI[0] >= 1200f && Main.netMode != 1)
             {
                 int num50 = (int)base.Center.X / 16 - 2;
                 int num51 = (int)base.Center.Y / 16 - 3;
                 if (!Collision.SolidTiles(num50, num50 + 4, num51, num51 + 4))
                 {
                     Transform(426);
                     life = lifeMax;
                     localAI[0] = 0f;
                     return;
                 }
             }
             int num52 = 0;
             num52 = ((localAI[0] < 360f) ? 32 : ((localAI[0] < 720f) ? 16 : ((localAI[0] < 1080f) ? 6 : ((localAI[0] < 1440f) ? 2 : ((!(localAI[0] < 1800f)) ? 1 : 1)))));
             if (Main.rand.Next(num52) == 0)
             {
                 position += netOffset;
                 Dust obj4 = Main.dust[Dust.NewDust(position, width, height, 229)];
                 obj4.noGravity = true;
                 obj4.scale = 1f;
                 obj4.noLight = true;
                 position -= netOffset;
             }
         }
         if (type == 590)
         {
             position += netOffset;
             int num53 = (int)(position.Y + 6f) / 16;
             if (spriteDirection < 0)
             {
                 int num54 = (int)(base.Center.X - 22f) / 16;
                 Tile tileSafely = Framing.GetTileSafely(num54, num53);
                 Tile tileSafely2 = Framing.GetTileSafely(num54 + 1, num53);
                 if (WorldGen.InWorld(num54, num53) && tileSafely2.liquid == 0 && tileSafely.liquid == 0)
                 {
                     Lighting.AddLight(num54, num53, 1f, 0.95f, 0.8f);
                     if (Main.rand.Next(30) == 0)
                     {
                         Dust.NewDust(new Vector2(base.Center.X - 22f, position.Y + 6f), 1, 1, 6);
                     }
                 }
             }
             else
             {
                 int num55 = (int)(base.Center.X + 14f) / 16;
                 Tile tileSafely3 = Framing.GetTileSafely(num55, num53);
                 Tile tileSafely4 = Framing.GetTileSafely(num55 - 1, num53);
                 if (WorldGen.InWorld(num55, num53) && tileSafely4.liquid == 0 && tileSafely3.liquid == 0)
                 {
                     Lighting.AddLight(num55, num53, 1f, 0.95f, 0.8f);
                     if (Main.rand.Next(30) == 0)
                     {
                         Dust.NewDust(new Vector2(base.Center.X + 14f, position.Y + 6f), 1, 1, 6);
                     }
                 }
             }
             position -= netOffset;
         }
         else if (type == 591)
         {
             position += netOffset;
             if (!wet)
             {
                 if (spriteDirection < 0)
                 {
                     Lighting.AddLight(new Vector2(base.Center.X - 36f, position.Y + 24f), 1f, 0.95f, 0.8f);
                     if (ai[2] == 0f && Main.rand.Next(30) == 0)
                     {
                         Dust.NewDust(new Vector2(base.Center.X - 36f, position.Y + 24f), 1, 1, 6);
                     }
                 }
                 else
                 {
                     Lighting.AddLight(new Vector2(base.Center.X + 28f, position.Y + 24f), 1f, 0.95f, 0.8f);
                     if (ai[2] == 0f && Main.rand.Next(30) == 0)
                     {
                         Dust.NewDust(new Vector2(base.Center.X + 28f, position.Y + 24f), 1, 1, 6);
                     }
                 }
             }
             position -= netOffset;
         }
         bool flag5 = false;
         bool flag6 = false;
         if (velocity.X == 0f)
         {
             flag6 = true;
         }
         if (justHit)
         {
             flag6 = false;
         }
         if (Main.netMode != 1 && type == 198 && (double)life <= (double)lifeMax * 0.55)
         {
             Transform(199);
         }
         if (Main.netMode != 1 && type == 348 && (double)life <= (double)lifeMax * 0.55)
         {
             Transform(349);
         }
         int num56 = 60;
         if (type == 120)
         {
             num56 = 180;
             if (ai[3] == -120f)
             {
                 velocity *= 0f;
                 ai[3] = 0f;
                 position += netOffset;
                 SoundEngine.PlaySound(SoundID.Item8, position);
                 Vector2 vector19 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num57 = oldPos[2].X + (float)width * 0.5f - vector19.X;
                 float num58 = oldPos[2].Y + (float)height * 0.5f - vector19.Y;
                 float num59 = (float)Math.Sqrt(num57 * num57 + num58 * num58);
                 num59 = 2f / num59;
                 num57 *= num59;
                 num58 *= num59;
                 for (int num60 = 0; num60 < 20; num60++)
                 {
                     int num61 = Dust.NewDust(position, width, height, 71, num57, num58, 200, default(Color), 2f);
                     Main.dust[num61].noGravity = true;
                     Main.dust[num61].velocity.X *= 2f;
                 }
                 for (int num62 = 0; num62 < 20; num62++)
                 {
                     int num63 = Dust.NewDust(oldPos[2], width, height, 71, 0f - num57, 0f - num58, 200, default(Color), 2f);
                     Main.dust[num63].noGravity = true;
                     Main.dust[num63].velocity.X *= 2f;
                 }
                 position -= netOffset;
             }
         }
         bool flag7 = false;
         bool flag8 = true;
         if (type == 343 || type == 47 || type == 67 || type == 109 || type == 110 || type == 111 || type == 120 || type == 163 || type == 164 || type == 239 || type == 168 || type == 199 || type == 206 || type == 214 || type == 215 || type == 216 || type == 217 || type == 218 || type == 219 || type == 220 || type == 226 || type == 243 || type == 251 || type == 257 || type == 258 || type == 290 || type == 291 || type == 292 || type == 293 || type == 305 || type == 306 || type == 307 || type == 308 || type == 309 || type == 348 || type == 349 || type == 350 || type == 351 || type == 379 || (type >= 430 && type <= 436) || type == 591 || type == 380 || type == 381 || type == 382 || type == 383 || type == 386 || type == 391 || (type >= 449 && type <= 452) || type == 466 || type == 464 || type == 166 || type == 469 || type == 468 || type == 471 || type == 470 || type == 480 || type == 481 || type == 482 || type == 411 || type == 424 || type == 409 || (type >= 494 && type <= 506) || type == 425 || type == 427 || type == 426 || type == 428 || type == 580 || type == 508 || type == 415 || type == 419 || type == 520 || (type >= 524 && type <= 527) || type == 528 || type == 529 || type == 530 || type == 532 || type == 582 || type == 624 || type == 631)
         {
             flag8 = false;
         }
         bool flag9 = false;
         int num64 = type;
         if (num64 == 425 || num64 == 471)
         {
             flag9 = true;
         }
         bool flag10 = true;
         switch (type)
         {
         case 110:
         case 111:
         case 206:
         case 214:
         case 215:
         case 216:
         case 291:
         case 292:
         case 293:
         case 350:
         case 379:
         case 380:
         case 381:
         case 382:
         case 409:
         case 411:
         case 424:
         case 426:
         case 466:
         case 498:
         case 499:
         case 500:
         case 501:
         case 502:
         case 503:
         case 504:
         case 505:
         case 506:
         case 520:
             if (ai[2] > 0f)
             {
                 flag10 = false;
             }
             break;
         }
         if (!flag9 && flag10)
         {
             if (velocity.Y == 0f && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
             {
                 flag7 = true;
             }
             if (position.X == oldPosition.X || ai[3] >= (float)num56 || flag7)
             {
                 ai[3] += 1f;
             }
             else if ((double)Math.Abs(velocity.X) > 0.9 && ai[3] > 0f)
             {
                 ai[3] -= 1f;
             }
             if (ai[3] > (float)(num56 * 10))
             {
                 ai[3] = 0f;
             }
             if (justHit)
             {
                 ai[3] = 0f;
             }
             if (ai[3] == (float)num56)
             {
                 netUpdate = true;
             }
             if (Main.player[target].Hitbox.Intersects(base.Hitbox))
             {
                 ai[3] = 0f;
             }
         }
         if (type == 463 && Main.netMode != 1)
         {
             if (localAI[3] > 0f)
             {
                 localAI[3] -= 1f;
             }
             if (justHit && localAI[3] <= 0f && Main.rand.Next(3) == 0)
             {
                 localAI[3] = 30f;
                 int num65 = Main.rand.Next(3, 6);
                 int[] array = new int[num65];
                 int num66 = 0;
                 for (int num67 = 0; num67 < 255; num67++)
                 {
                     if (Main.player[num67].active && !Main.player[num67].dead && Collision.CanHitLine(position, width, height, Main.player[num67].position, Main.player[num67].width, Main.player[num67].height))
                     {
                         array[num66] = num67;
                         num66++;
                         if (num66 == num65)
{
                             break;
                         }
                     }
                 }
                 if (num66 > 1)
                 {
                     for (int num68 = 0; num68 < 100; num68++)
                     {
                         int num69 = Main.rand.Next(num66);
                         int num70;
                         for (num70 = num69; num70 == num69; num70 = Main.rand.Next(num66))
{
                         }
                         int num71 = array[num69];
                         array[num69] = array[num70];
                         array[num70] = num71;
                     }
                 }
                 Vector2 vector20 = new Vector2(-1f, -1f);
                 for (int num72 = 0; num72 < num66; num72++)
                 {
                     Vector2 vector21 = Main.npc[array[num72]].Center - base.Center;
                     vector21.Normalize();
                     vector20 += vector21;
                 }
                 vector20.Normalize();
                 for (int num73 = 0; num73 < num65; num73++)
                 {
                     float num74 = Main.rand.Next(8, 13);
                     Vector2 vector22 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                     vector22.Normalize();
                     if (num66 > 0)
                     {
                         vector22 += vector20;
                         vector22.Normalize();
                     }
                     vector22 *= num74;
                     if (num66 > 0)
                     {
                         num66--;
                         vector22 = Main.player[array[num66]].Center - base.Center;
                         vector22.Normalize();
                         vector22 *= num74;
                     }
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, position.Y + (float)(width / 4), vector22.X, vector22.Y, 498, (int)((double)damage * 0.15), 1f, Main.myPlayer);
                 }
             }
         }
         if (type == 460)
         {
             if (velocity.Y < 0f - gravity || velocity.Y > gravity)
             {
                 knockBackResist = 0f;
             }
             else
             {
                 knockBackResist = 0.25f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
             }
         }
         if (type == 469)
         {
             knockBackResist = 0.45f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
             if (ai[2] == 1f)
             {
                 knockBackResist = 0f;
             }
             bool flag11 = false;
             int num75 = (int)base.Center.X / 16;
             int num76 = (int)base.Center.Y / 16;
             for (int num77 = num75 - 1; num77 <= num75 + 1; num77++)
             {
                 for (int num78 = num76 - 1; num78 <= num76 + 1; num78++)
                 {
                     if (Main.tile[num77, num78] != null && Main.tile[num77, num78].wall > 0)
                     {
                         flag11 = true;
                         break;
                     }
                 }
                 if (flag11)
                 {
                     break;
                 }
             }
             if (ai[2] == 0f && flag11)
             {
                 if (velocity.Y == 0f)
                 {
                     flag = true;
                     velocity.Y = -4.6f;
                     velocity.X *= 1.3f;
                 }
                 else if (velocity.Y > 0f && !Main.player[target].dead)
                 {
                     ai[2] = 1f;
                 }
             }
             if (flag11 && ai[2] == 1f && !Main.player[target].dead && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
             {
                 Vector2 vector23 = Main.player[target].Center - base.Center;
                 float num79 = vector23.Length();
                 vector23.Normalize();
                 vector23 *= 4.5f + num79 / 300f;
                 velocity = (velocity * 29f + vector23) / 30f;
                 noGravity = true;
                 ai[2] = 1f;
                 return;
             }
             noGravity = false;
             ai[2] = 0f;
         }
         if (type == 462 && velocity.Y == 0f && (Main.player[target].Center - base.Center).Length() < 150f && Math.Abs(velocity.X) > 3f && ((velocity.X < 0f && base.Center.X > Main.player[target].Center.X) || (velocity.X > 0f && base.Center.X < Main.player[target].Center.X)))
         {
             flag = true;
             velocity.X *= 1.75f;
             velocity.Y -= 4.5f;
             if (base.Center.Y - Main.player[target].Center.Y > 20f)
             {
                 velocity.Y -= 0.5f;
             }
             if (base.Center.Y - Main.player[target].Center.Y > 40f)
             {
                 velocity.Y -= 1f;
             }
             if (base.Center.Y - Main.player[target].Center.Y > 80f)
             {
                 velocity.Y -= 1.5f;
             }
             if (base.Center.Y - Main.player[target].Center.Y > 100f)
             {
                 velocity.Y -= 1.5f;
             }
             if (Math.Abs(velocity.X) > 7f)
             {
                 if (velocity.X < 0f)
                 {
                     velocity.X = -7f;
                 }
                 else
                 {
                     velocity.X = 7f;
                 }
             }
         }
         if (type == 624 && target < 255)
         {
             if (!Main.remixWorld && !Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 ai[3] = num56;
                 directionY = -1;
                 if (type == 624 && !AI_003_Gnomes_ShouldTurnToStone() && (base.Center - Main.player[target].Center).Length() > 500f)
                 {
                     velocity.X *= 0.95f;
                     if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                     {
                         velocity.X = 0f;
                     }
                     return;
                 }
             }
             else if (Main.player[target].Center.Y > base.Center.Y - 128f)
             {
                 ai[3] = 0f;
             }
         }
         if (ai[3] < (float)num56 && DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged(type, position, this))
         {
             if (shimmerTransparency < 1f)
             {
                 if ((type == 3 || type == 591 || type == 590 || type == 331 || type == 332 || type == 21 || (type >= 449 && type <= 452) || type == 31 || type == 294 || type == 295 || type == 296 || type == 77 || type == 110 || type == 132 || type == 167 || type == 161 || type == 162 || type == 186 || type == 187 || type == 188 || type == 189 || type == 197 || type == 200 || type == 201 || type == 202 || type == 203 || type == 223 || type == 291 || type == 292 || type == 293 || type == 320 || type == 321 || type == 319 || type == 481 || type == 632 || type == 635) && Main.rand.Next(1000) == 0)
                 {
                     SoundEngine.PlaySound(14, (int)position.X, (int)position.Y);
                 }
                 if ((type == 489 || type == 586) && Main.rand.Next(800) == 0)
                 {
                     SoundEngine.PlaySound(14, (int)position.X, (int)position.Y, type);
                 }
                 if ((type == 78 || type == 79 || type == 80 || type == 630) && Main.rand.Next(500) == 0)
                 {
                     SoundEngine.PlaySound(26, (int)position.X, (int)position.Y);
                 }
                 if (type == 159 && Main.rand.Next(500) == 0)
                 {
                     SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 7);
                 }
                 if (type == 162 && Main.rand.Next(500) == 0)
                 {
                     SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 6);
                 }
                 if (type == 181 && Main.rand.Next(500) == 0)
                 {
                     SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 8);
                 }
                 if (type >= 269 && type <= 280 && Main.rand.Next(1000) == 0)
                 {
                     SoundEngine.PlaySound(14, (int)position.X, (int)position.Y);
                 }
             }
             TargetClosest();
             if (directionY > 0 && Main.player[target].Center.Y <= base.Bottom.Y)
             {
                 directionY = -1;
             }
         }
         else if (!(ai[2] > 0f) || !DespawnEncouragement_AIStyle3_Fighters_CanBeBusyWithAction(type))
         {
             if (Main.IsItDay() && (double)(position.Y / 16f) < Main.worldSurface && type != 624 && type != 631)
             {
                 EncourageDespawn(10);
             }
             if (velocity.X == 0f)
             {
                 if (velocity.Y == 0f)
                 {
                     ai[0] += 1f;
                     if (ai[0] >= 2f)
                     {
                         direction *= -1;
                         spriteDirection = direction;
                         ai[0] = 0f;
                     }
                 }
             }
             else
             {
                 ai[0] = 0f;
             }
             if (direction == 0)
             {
                 direction = 1;
             }
         }
         if (type == 159 || type == 349)
         {
             if (type == 159 && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
             {
                 velocity.X *= 0.95f;
             }
             if (velocity.X < -6f || velocity.X > 6f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < 6f && direction == 1)
             {
                 if (velocity.Y == 0f && velocity.X < 0f)
                 {
                     velocity.X *= 0.99f;
                 }
                 velocity.X += 0.07f;
                 if (velocity.X > 6f)
                 {
                     velocity.X = 6f;
                 }
             }
             else if (velocity.X > -6f && direction == -1)
             {
                 if (velocity.Y == 0f && velocity.X > 0f)
                 {
                     velocity.X *= 0.99f;
                 }
                 velocity.X -= 0.07f;
                 if (velocity.X < -6f)
                 {
                     velocity.X = -6f;
                 }
             }
         }
         else if (type == 199)
         {
             if (velocity.X < -4f || velocity.X > 4f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < 4f && direction == 1)
             {
                 if (velocity.Y == 0f && velocity.X < 0f)
                 {
                     velocity.X *= 0.8f;
                 }
                 velocity.X += 0.1f;
                 if (velocity.X > 4f)
                 {
                     velocity.X = 4f;
                 }
             }
             else if (velocity.X > -4f && direction == -1)
             {
                 if (velocity.Y == 0f && velocity.X > 0f)
                 {
                     velocity.X *= 0.8f;
                 }
                 velocity.X -= 0.1f;
                 if (velocity.X < -4f)
                 {
                     velocity.X = -4f;
                 }
             }
         }
         else if (type == 120 || type == 166 || type == 213 || type == 258 || type == 528 || type == 529)
         {
             if (velocity.X < -3f || velocity.X > 3f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < 3f && direction == 1)
             {
                 if (velocity.Y == 0f && velocity.X < 0f)
                 {
                     velocity.X *= 0.99f;
                 }
                 velocity.X += 0.07f;
                 if (velocity.X > 3f)
                 {
                     velocity.X = 3f;
                 }
             }
             else if (velocity.X > -3f && direction == -1)
             {
                 if (velocity.Y == 0f && velocity.X > 0f)
                 {
                     velocity.X *= 0.99f;
                 }
                 velocity.X -= 0.07f;
                 if (velocity.X < -3f)
                 {
                     velocity.X = -3f;
                 }
             }
         }
         else if (type == 461 || type == 27 || type == 77 || type == 104 || type == 163 || type == 162 || type == 196 || type == 197 || type == 212 || type == 257 || type == 326 || type == 343 || type == 348 || type == 351 || (type >= 524 && type <= 527) || type == 530 || type == 236)
         {
             if (velocity.X < -2f || velocity.X > 2f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < 2f && direction == 1)
             {
                 velocity.X += 0.07f;
                 if (velocity.X > 2f)
                 {
                     velocity.X = 2f;
                 }
             }
             else if (velocity.X > -2f && direction == -1)
             {
                 velocity.X -= 0.07f;
                 if (velocity.X < -2f)
                 {
                     velocity.X = -2f;
                 }
             }
         }
         else if (type == 109)
         {
             if (velocity.X < -2f || velocity.X > 2f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < 2f && direction == 1)
             {
                 velocity.X += 0.04f;
                 if (velocity.X > 2f)
                 {
                     velocity.X = 2f;
                 }
             }
             else if (velocity.X > -2f && direction == -1)
             {
                 velocity.X -= 0.04f;
                 if (velocity.X < -2f)
                 {
                     velocity.X = -2f;
                 }
             }
         }
         else if (type == 21 || type == 26 || type == 31 || type == 294 || type == 295 || type == 296 || type == 47 || type == 73 || type == 140 || type == 164 || type == 239 || type == 167 || type == 168 || type == 185 || type == 198 || type == 201 || type == 202 || type == 203 || type == 217 || type == 218 || type == 219 || type == 226 || type == 181 || type == 254 || type == 338 || type == 339 || type == 340 || type == 342 || type == 385 || type == 389 || type == 462 || type == 463 || type == 466 || type == 464 || type == 469 || type == 470 || type == 480 || type == 482 || type == 425 || type == 429 || type == 586 || type == 631 || type == 635)
         {
             float num80 = 1.5f;
             if (type == 181 && Main.remixWorld)
             {
                 num80 = 3.75f;
             }
             else if (type == 294)
             {
                 num80 = 2f;
             }
             else if (type == 295)
             {
                 num80 = 1.75f;
             }
             else if (type == 296)
             {
                 num80 = 1.25f;
             }
             else if (type == 201)
             {
                 num80 = 1.1f;
             }
             else if (type == 202)
             {
                 num80 = 0.9f;
             }
             else if (type == 203)
             {
                 num80 = 1.2f;
             }
             else if (type == 338)
             {
                 num80 = 1.75f;
             }
             else if (type == 339)
             {
                 num80 = 1.25f;
             }
             else if (type == 340)
             {
                 num80 = 2f;
             }
             else if (type == 385)
             {
                 num80 = 1.8f;
             }
             else if (type == 389)
             {
                 num80 = 2.25f;
             }
             else if (type == 462)
             {
                 num80 = 4f;
             }
             else if (type == 463)
             {
                 num80 = 0.75f;
             }
             else if (type == 466)
             {
                 num80 = 3.75f;
             }
             else if (type == 469)
             {
                 num80 = 3.25f;
             }
             else if (type == 480)
             {
                 num80 = 1.5f + (1f - (float)life / (float)lifeMax) * 2f;
             }
             else if (type == 425)
             {
                 num80 = 6f;
             }
             else if (type == 429)
             {
                 num80 = 4f;
             }
             else if (type == 631)
             {
                 num80 = 0.9f;
             }
             else if (type == 586)
             {
                 num80 = 1.5f + (1f - (float)life / (float)lifeMax) * 3.5f;
             }
             if (type == 21 || type == 201 || type == 202 || type == 203 || type == 342 || type == 635)
             {
                 num80 *= 1f + (1f - scale);
             }
             if (velocity.X < 0f - num80 || velocity.X > num80)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < num80 && direction == 1)
             {
                 if (type == 466 && velocity.X < -2f)
                 {
                     velocity.X *= 0.9f;
                 }
                 if (type == 586 && velocity.Y == 0f && velocity.X < -1f)
                 {
                     velocity.X *= 0.9f;
                 }
                 velocity.X += 0.07f;
                 if (velocity.X > num80)
                 {
                     velocity.X = num80;
                 }
             }
             else if (velocity.X > 0f - num80 && direction == -1)
             {
                 if (type == 466 && velocity.X > 2f)
                 {
                     velocity.X *= 0.9f;
                 }
                 if (type == 586 && velocity.Y == 0f && velocity.X > 1f)
                 {
                     velocity.X *= 0.9f;
                 }
                 velocity.X -= 0.07f;
                 if (velocity.X < 0f - num80)
                 {
                     velocity.X = 0f - num80;
                 }
             }
             if (velocity.Y == 0f && type == 462 && ((direction > 0 && velocity.X < 0f) || (direction < 0 && velocity.X > 0f)))
             {
                 velocity.X *= 0.9f;
             }
         }
         else if (type >= 269 && type <= 280)
         {
             float num81 = 1.5f;
             if (type == 269)
             {
                 num81 = 2f;
             }
             if (type == 270)
             {
                 num81 = 1f;
             }
             if (type == 271)
             {
                 num81 = 1.5f;
             }
             if (type == 272)
             {
                 num81 = 3f;
             }
             if (type == 273)
             {
                 num81 = 1.25f;
             }
             if (type == 274)
             {
                 num81 = 3f;
             }
             if (type == 275)
             {
                 num81 = 3.25f;
             }
             if (type == 276)
             {
                 num81 = 2f;
             }
             if (type == 277)
             {
                 num81 = 2.75f;
             }
             if (type == 278)
             {
                 num81 = 1.8f;
             }
             if (type == 279)
             {
                 num81 = 1.3f;
             }
             if (type == 280)
             {
                 num81 = 2.5f;
             }
             num81 *= 1f + (1f - scale);
             if (velocity.X < 0f - num81 || velocity.X > num81)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < num81 && direction == 1)
             {
                 velocity.X += 0.07f;
                 if (velocity.X > num81)
                 {
                     velocity.X = num81;
                 }
             }
             else if (velocity.X > 0f - num81 && direction == -1)
             {
                 velocity.X -= 0.07f;
                 if (velocity.X < 0f - num81)
                 {
                     velocity.X = 0f - num81;
                 }
             }
         }
         else if (type >= 305 && type <= 314)
         {
             float num82 = 1.5f;
             if (type == 305 || type == 310)
             {
                 num82 = 2f;
             }
             if (type == 306 || type == 311)
             {
                 num82 = 1.25f;
             }
             if (type == 307 || type == 312)
             {
                 num82 = 2.25f;
             }
             if (type == 308 || type == 313)
             {
                 num82 = 1.5f;
             }
             if (type == 309 || type == 314)
             {
                 num82 = 1f;
             }
             if (type < 310)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity.X *= 0.85f;
                     if ((double)velocity.X > -0.3 && (double)velocity.X < 0.3)
                     {
                         flag = true;
                         velocity.Y = -7f;
                         velocity.X = num82 * (float)direction;
                     }
                 }
                 else if (spriteDirection == direction)
                 {
                     velocity.X = (velocity.X * 10f + num82 * (float)direction) / 11f;
                 }
             }
             else if (velocity.X < 0f - num82 || velocity.X > num82)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < num82 && direction == 1)
             {
                 velocity.X += 0.07f;
                 if (velocity.X > num82)
                 {
                     velocity.X = num82;
                 }
             }
             else if (velocity.X > 0f - num82 && direction == -1)
             {
                 velocity.X -= 0.07f;
                 if (velocity.X < 0f - num82)
                 {
                     velocity.X = 0f - num82;
                 }
             }
         }
         else if (type == 67 || type == 220 || type == 428)
         {
             if (velocity.X < -0.5f || velocity.X > 0.5f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < 0.5f && direction == 1)
             {
                 velocity.X += 0.03f;
                 if (velocity.X > 0.5f)
                 {
                     velocity.X = 0.5f;
                 }
             }
             else if (velocity.X > -0.5f && direction == -1)
             {
                 velocity.X -= 0.03f;
                 if (velocity.X < -0.5f)
                 {
                     velocity.X = -0.5f;
                 }
             }
         }
         else if (type == 78 || type == 79 || type == 80 || type == 630)
         {
             float num83 = 1f;
             float num84 = 0.05f;
             if (life < lifeMax / 2)
             {
                 num83 = 2f;
                 num84 = 0.1f;
             }
             if (type == 79 || type == 630)
             {
                 num83 *= 1.5f;
             }
             if (velocity.X < 0f - num83 || velocity.X > num83)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < num83 && direction == 1)
             {
                 velocity.X += num84;
                 if (velocity.X > num83)
                 {
                     velocity.X = num83;
                 }
             }
             else if (velocity.X > 0f - num83 && direction == -1)
             {
                 velocity.X -= num84;
                 if (velocity.X < 0f - num83)
                 {
                     velocity.X = 0f - num83;
                 }
             }
         }
         else if (type == 287)
         {
             float num85 = 5f;
             float num86 = 0.2f;
             if (velocity.X < 0f - num85 || velocity.X > num85)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < num85 && direction == 1)
             {
                 velocity.X += num86;
                 if (velocity.X > num85)
                 {
                     velocity.X = num85;
                 }
             }
             else if (velocity.X > 0f - num85 && direction == -1)
             {
                 velocity.X -= num86;
                 if (velocity.X < 0f - num85)
                 {
                     velocity.X = 0f - num85;
                 }
             }
         }
         else if (type == 243)
         {
             float num87 = 1f;
             float num88 = 0.07f;
             num87 += (1f - (float)life / (float)lifeMax) * 1.5f;
             num88 += (1f - (float)life / (float)lifeMax) * 0.15f;
             if (velocity.X < 0f - num87 || velocity.X > num87)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < num87 && direction == 1)
             {
                 velocity.X += num88;
                 if (velocity.X > num87)
                 {
                     velocity.X = num87;
                 }
             }
             else if (velocity.X > 0f - num87 && direction == -1)
             {
                 velocity.X -= num88;
                 if (velocity.X < 0f - num87)
                 {
                     velocity.X = 0f - num87;
                 }
             }
         }
         else if (type == 251)
         {
             float num89 = 1f;
             float num90 = 0.08f;
             num89 += (1f - (float)life / (float)lifeMax) * 2f;
             num90 += (1f - (float)life / (float)lifeMax) * 0.2f;
             if (velocity.X < 0f - num89 || velocity.X > num89)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < num89 && direction == 1)
             {
                 velocity.X += num90;
                 if (velocity.X > num89)
                 {
                     velocity.X = num89;
                 }
             }
             else if (velocity.X > 0f - num89 && direction == -1)
             {
                 velocity.X -= num90;
                 if (velocity.X < 0f - num89)
                 {
                     velocity.X = 0f - num89;
                 }
             }
         }
         else if (type == 386)
         {
             if (ai[2] > 0f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity.X *= 0.8f;
                 }
             }
             else
             {
                 float num91 = 0.15f;
                 float num92 = 1.5f;
                 if (velocity.X < 0f - num92 || velocity.X > num92)
                 {
                     if (velocity.Y == 0f)
                     {
                         velocity *= 0.7f;
                     }
                 }
                 else if (velocity.X < num92 && direction == 1)
                 {
                     velocity.X += num91;
                     if (velocity.X > num92)
                     {
                         velocity.X = num92;
                     }
                 }
                 else if (velocity.X > 0f - num92 && direction == -1)
                 {
                     velocity.X -= num91;
                     if (velocity.X < 0f - num92)
                     {
                         velocity.X = 0f - num92;
                     }
                 }
             }
         }
         else if (type == 460)
         {
             float num93 = 3f;
             float num94 = 0.1f;
             if (Math.Abs(velocity.X) > 2f)
             {
                 num94 *= 0.8f;
             }
             if ((double)Math.Abs(velocity.X) > 2.5)
             {
                 num94 *= 0.8f;
             }
             if (Math.Abs(velocity.X) > 3f)
             {
                 num94 *= 0.8f;
             }
             if ((double)Math.Abs(velocity.X) > 3.5)
             {
                 num94 *= 0.8f;
             }
             if (Math.Abs(velocity.X) > 4f)
             {
                 num94 *= 0.8f;
             }
             if ((double)Math.Abs(velocity.X) > 4.5)
             {
                 num94 *= 0.8f;
             }
             if (Math.Abs(velocity.X) > 5f)
             {
                 num94 *= 0.8f;
             }
             if ((double)Math.Abs(velocity.X) > 5.5)
             {
                 num94 *= 0.8f;
             }
             num93 += (1f - (float)life / (float)lifeMax) * 3f;
             if (velocity.X < 0f - num93 || velocity.X > num93)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.7f;
                 }
             }
             else if (velocity.X < num93 && direction == 1)
             {
                 if (velocity.X < 0f)
                 {
                     velocity.X *= 0.93f;
                 }
                 velocity.X += num94;
                 if (velocity.X > num93)
                 {
                     velocity.X = num93;
                 }
             }
             else if (velocity.X > 0f - num93 && direction == -1)
             {
                 if (velocity.X > 0f)
                 {
                     velocity.X *= 0.93f;
                 }
                 velocity.X -= num94;
                 if (velocity.X < 0f - num93)
                 {
                     velocity.X = 0f - num93;
                 }
             }
         }
         else if (type == 508 || type == 580 || type == 582)
         {
             float num95 = 2.5f;
             float num96 = 10f;
             float num97 = Math.Abs(velocity.X);
             if (type == 582)
             {
                 num95 = 2.25f;
                 num96 = 7f;
                 if (num97 > 2.5f)
                 {
                     num95 = 3f;
                     num96 += 75f;
                 }
                 else if (num97 > 2f)
                 {
                     num95 = 2.75f;
                     num96 += 55f;
                 }
             }
             else if (num97 > 2.75f)
             {
                 num95 = 3.5f;
                 num96 += 80f;
             }
             else if ((double)num97 > 2.25)
             {
                 num95 = 3f;
                 num96 += 60f;
             }
             if ((double)Math.Abs(velocity.Y) < 0.5)
             {
                 if (velocity.X > 0f && direction < 0)
                 {
                     velocity *= 0.95f;
                 }
                 if (velocity.X < 0f && direction > 0)
                 {
                     velocity *= 0.95f;
                 }
             }
             if (Math.Abs(velocity.Y) > gravity)
             {
                 float num98 = 3f;
                 if (type == 582)
                 {
                     num98 = 2f;
                 }
                 num96 *= num98;
             }
             if (velocity.X <= 0f && direction < 0)
             {
                 velocity.X = (velocity.X * num96 - num95) / (num96 + 1f);
             }
             else if (velocity.X >= 0f && direction > 0)
             {
                 velocity.X = (velocity.X * num96 + num95) / (num96 + 1f);
             }
             else if (Math.Abs(base.Center.X - Main.player[target].Center.X) > 20f && Math.Abs(velocity.Y) <= gravity)
             {
                 velocity.X *= 0.99f;
                 velocity.X += (float)direction * 0.025f;
             }
         }
         else if (type == 391 || type == 427 || type == 415 || type == 419 || type == 518 || type == 532)
         {
             float num99 = 5f;
             float num100 = 0.25f;
             float num101 = 0.7f;
             if (type == 427)
             {
                 num99 = 6f;
                 num100 = 0.2f;
                 num101 = 0.8f;
             }
             else if (type == 415)
             {
                 num99 = 4f;
                 num100 = 0.1f;
                 num101 = 0.95f;
             }
             else if (type == 419)
             {
                 num99 = 6f;
                 num100 = 0.15f;
                 num101 = 0.85f;
             }
             else if (type == 518)
             {
                 num99 = 5f;
                 num100 = 0.1f;
                 num101 = 0.95f;
             }
             else if (type == 532)
             {
                 num99 = 5f;
                 num100 = 0.15f;
                 num101 = 0.98f;
             }
             if (velocity.X < 0f - num99 || velocity.X > num99)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= num101;
                 }
             }
             else if (velocity.X < num99 && direction == 1)
             {
                 velocity.X += num100;
                 if (velocity.X > num99)
                 {
                     velocity.X = num99;
                 }
             }
             else if (velocity.X > 0f - num99 && direction == -1)
             {
                 velocity.X -= num100;
                 if (velocity.X < 0f - num99)
                 {
                     velocity.X = 0f - num99;
                 }
             }
         }
         else if ((type >= 430 && type <= 436) || type == 494 || type == 495 || type == 591)
         {
             if (ai[2] == 0f)
             {
                 damage = defDamage;
                 float num102 = 1f;
                 num102 *= 1f + (1f - scale);
                 if (velocity.X < 0f - num102 || velocity.X > num102)
                 {
                     if (velocity.Y == 0f)
                     {
                         velocity *= 0.8f;
                     }
                 }
                 else if (velocity.X < num102 && direction == 1)
                 {
                     velocity.X += 0.07f;
                     if (velocity.X > num102)
                     {
                         velocity.X = num102;
                     }
                 }
                 else if (velocity.X > 0f - num102 && direction == -1)
                 {
                     velocity.X -= 0.07f;
                     if (velocity.X < 0f - num102)
                     {
                         velocity.X = 0f - num102;
                     }
                 }
                 if (velocity.Y == 0f && (!Main.IsItDay() || (double)position.Y > Main.worldSurface * 16.0) && !Main.player[target].dead)
                 {
                     Vector2 vector24 = base.Center - Main.player[target].Center;
                     int num103 = 50;
                     if (type >= 494 && type <= 495)
                     {
                         num103 = 42;
                     }
                     if (vector24.Length() < (float)num103 && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                     {
                         velocity.X *= 0.7f;
                         ai[2] = 1f;
                     }
                 }
             }
             else
             {
                 damage = (int)((double)defDamage * 1.5);
                 ai[3] = 1f;
                 velocity.X *= 0.9f;
                 if ((double)Math.Abs(velocity.X) < 0.1)
                 {
                     velocity.X = 0f;
                 }
                 ai[2] += 1f;
                 if (ai[2] >= 20f || velocity.Y != 0f || (Main.IsItDay() && (double)position.Y < Main.worldSurface * 16.0))
                 {
                     ai[2] = 0f;
                 }
             }
         }
         else if (type != 110 && type != 111 && type != 206 && type != 214 && type != 215 && type != 216 && type != 290 && type != 291 && type != 292 && type != 293 && type != 350 && type != 379 && type != 380 && type != 381 && type != 382 && (type < 449 || type > 452) && type != 468 && type != 481 && type != 411 && type != 409 && (type < 498 || type > 506) && type != 424 && type != 426 && type != 520)
         {
             float num104 = 1f;
             if (type == 624)
             {
                 num104 = 2.5f;
             }
             if (type == 186)
             {
                 num104 = 1.1f;
             }
             if (type == 187)
             {
                 num104 = 0.9f;
             }
             if (type == 188)
             {
                 num104 = 1.2f;
             }
             if (type == 189)
             {
                 num104 = 0.8f;
             }
             if (type == 132)
             {
                 num104 = 0.95f;
             }
             if (type == 200)
             {
                 num104 = 0.87f;
             }
             if (type == 223)
             {
                 num104 = 1.05f;
             }
             if (type == 632)
             {
                 num104 = 0.8f;
             }
             if (type == 489)
             {
                 float num105 = (Main.player[target].Center - base.Center).Length();
                 num105 *= 0.0025f;
                 if ((double)num105 > 1.5)
                 {
                     num105 = 1.5f;
                 }
                 num104 = ((!Main.expertMode) ? (2.5f - num105) : (3f - num105));
                 num104 *= 0.8f;
             }
             if (type == 489 || type == 3 || type == 132 || type == 186 || type == 187 || type == 188 || type == 189 || type == 200 || type == 223 || type == 331 || type == 332)
             {
                 num104 *= 1f + (1f - scale);
             }
             if (velocity.X < 0f - num104 || velocity.X > num104)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity *= 0.8f;
                 }
             }
             else if (velocity.X < num104 && direction == 1)
             {
                 velocity.X += 0.07f;
                 if (velocity.X > num104)
                 {
                     velocity.X = num104;
                 }
             }
             else if (velocity.X > 0f - num104 && direction == -1)
             {
                 velocity.X -= 0.07f;
                 if (velocity.X < 0f - num104)
                 {
                     velocity.X = 0f - num104;
                 }
             }
         }
         if (type >= 277 && type <= 280)
         {
             Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.2f, 0.1f, 0f);
         }
         else if (type == 520)
         {
             Lighting.AddLight(base.Top + new Vector2(0f, 20f), 0.3f, 0.3f, 0.7f);
         }
         else if (type == 525)
         {
             Vector3 rgb = new Vector3(0.7f, 1f, 0.2f) * 0.5f;
             Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb);
         }
         else if (type == 526)
         {
             Vector3 rgb2 = new Vector3(1f, 1f, 0.5f) * 0.4f;
             Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb2);
         }
         else if (type == 527)
         {
             Vector3 rgb3 = new Vector3(0.6f, 0.3f, 1f) * 0.4f;
             Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb3);
         }
         else if (type == 415)
         {
             hide = false;
             for (int num106 = 0; num106 < 200; num106++)
             {
                 if (Main.npc[num106].active && Main.npc[num106].type == 416 && Main.npc[num106].ai[0] == (float)whoAmI)
                 {
                     hide = true;
                     break;
                 }
             }
         }
         else if (type == 258)
         {
             if (velocity.Y != 0f)
             {
                 TargetClosest();
                 spriteDirection = direction;
                 if (Main.player[target].Center.X < position.X && velocity.X > 0f)
                 {
                     velocity.X *= 0.95f;
                 }
                 else if (Main.player[target].Center.X > position.X + (float)width && velocity.X < 0f)
                 {
                     velocity.X *= 0.95f;
                 }
                 if (Main.player[target].Center.X < position.X && velocity.X > -5f)
                 {
                     velocity.X -= 0.1f;
                 }
                 else if (Main.player[target].Center.X > position.X + (float)width && velocity.X < 5f)
                 {
                     velocity.X += 0.1f;
                 }
             }
             else if (Main.player[target].Center.Y + 50f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 flag = true;
                 velocity.Y = -7f;
             }
         }
         else if (type == 425)
         {
             if (localAI[3] == 0f)
             {
                 localAI[3] = 1f;
                 ai[3] = -120f;
             }
             if (velocity.Y == 0f)
             {
                 ai[2] = 0f;
             }
             if (velocity.Y != 0f && ai[2] == 1f)
             {
                 TargetClosest();
                 spriteDirection = -direction;
                 if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     float num107 = 0.3f;
                     float num108 = 8f;
                     float num109 = 0.3f;
                     float num110 = 7f;
                     float num111 = Main.player[target].Center.X - (float)(direction * 300) - base.Center.X;
                     float num112 = Main.player[target].Bottom.Y - base.Bottom.Y;
                     if (num111 < 0f && velocity.X > 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     else if (num111 > 0f && velocity.X < 0f)
                     {
                         velocity.X *= 0.9f;
                     }
                     if (num111 < 0f && velocity.X > 0f - num110)
                     {
                         velocity.X -= num109;
                     }
                     else if (num111 > 0f && velocity.X < num110)
                     {
                         velocity.X += num109;
                     }
                     if (velocity.X > num110)
                     {
                         velocity.X = num110;
                     }
                     if (velocity.X < 0f - num110)
                     {
                         velocity.X = 0f - num110;
                     }
                     if (num112 < -20f && velocity.Y > 0f)
                     {
                         velocity.Y *= 0.8f;
                     }
                     else if (num112 > 20f && velocity.Y < 0f)
                     {
                         velocity.Y *= 0.8f;
                     }
                     if (num112 < -20f && velocity.Y > 0f - num108)
                     {
                         velocity.Y -= num107;
                     }
                     else if (num112 > 20f && velocity.Y < num108)
                     {
                         velocity.Y += num107;
                     }
                 }
                 if (Main.rand.Next(3) == 0)
                 {
                     position += netOffset;
                     Vector2 vector25 = base.Center + new Vector2(direction * -14, -8f) - Vector2.One * 4f;
                     Vector2 vector26 = new Vector2(direction * -6, 12f) * 0.2f + Utils.RandomVector2(Main.rand, -1f, 1f) * 0.1f;
                     Dust obj5 = Main.dust[Dust.NewDust(vector25, 8, 8, 229, vector26.X, vector26.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 0.5f)];
                     obj5.noGravity = true;
                     obj5.velocity = vector26;
                     obj5.customData = this;
                     position -= netOffset;
                 }
                 for (int num113 = 0; num113 < 200; num113++)
                 {
                     if (num113 != whoAmI && Main.npc[num113].active && Main.npc[num113].type == type && Math.Abs(position.X - Main.npc[num113].position.X) + Math.Abs(position.Y - Main.npc[num113].position.Y) < (float)width)
                     {
                         if (position.X < Main.npc[num113].position.X)
{
                             velocity.X -= 0.15f;
                         }
                         else
{
                             velocity.X += 0.15f;
                         }
                         if (position.Y < Main.npc[num113].position.Y)
{
                             velocity.Y -= 0.15f;
                         }
                         else
{
                             velocity.Y += 0.15f;
                         }
                     }
                 }
             }
             else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 flag = true;
                 velocity.Y = -5f;
                 ai[2] = 1f;
             }
             if (ai[3] < 0f)
             {
                 ai[3] += 1f;
             }
             int num114 = 30;
             int num115 = 10;
             int num116 = 180;
             if (ai[3] >= 0f && ai[3] <= (float)num114)
             {
                 Vector2 vector27 = DirectionTo(Main.player[target].Center);
                 bool flag12 = Math.Abs(vector27.Y) <= Math.Abs(vector27.X);
                 bool flag13 = Distance(Main.player[target].Center) < 800f && flag12 && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0);
                 ai[3] = MathHelper.Clamp(ai[3] + (float)flag13.ToDirectionInt(), 0f, num114);
             }
             if (ai[3] >= (float)(num114 + 1) && (ai[3] += 1f) >= (float)(num114 + num115))
             {
                 ai[3] = num114 - num116;
                 netUpdate = true;
             }
             if (Main.netMode != 1 && ai[3] == (float)num114)
             {
                 ai[3] += 1f;
                 netUpdate = true;
                 int num117 = 20;
                 Vector2 chaserPosition = base.Center + new Vector2(direction * 30, 2f);
                 Vector2 vector28 = DirectionTo(Main.player[target].Center) * num117;
                 if (vector28.HasNaNs())
                 {
                     vector28 = new Vector2(direction * num117, 0f);
                 }
                 int num118 = 2;
                 Utils.ChaseResults chaseResults = Utils.GetChaseResults(chaserPosition, num117, Main.player[target].Center, Main.player[target].velocity * 0.5f / num118);
                 if (chaseResults.InterceptionHappens)
                 {
                     Vector2 vector29 = chaseResults.ChaserVelocity / num118;
                     vector28.X = vector29.X;
                     vector28.Y = vector29.Y;
                 }
                 int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(75f, 50f);
                 for (int num119 = 0; num119 < 4; num119++)
                 {
                     Vector2 vector30 = vector28 + Utils.RandomVector2(Main.rand, -0.8f, 0.8f) * ((num119 != 0) ? 1 : 0);
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition.X, chaserPosition.Y, vector30.X, vector30.Y, 577, attackDamage_ForProjectiles, 1f, Main.myPlayer);
                 }
             }
         }
         else if (type == 427)
         {
             if (velocity.Y == 0f)
             {
                 ai[2] = 0f;
                 rotation = 0f;
             }
             else
             {
                 rotation = velocity.X * 0.1f;
             }
             if (velocity.Y != 0f && ai[2] == 1f)
             {
                 TargetClosest();
                 spriteDirection = -direction;
                 if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     float num120 = Main.player[target].Center.X - base.Center.X;
                     float num121 = Main.player[target].Center.Y - base.Center.Y;
                     if (num120 < 0f && velocity.X > 0f)
                     {
                         velocity.X *= 0.98f;
                     }
                     else if (num120 > 0f && velocity.X < 0f)
                     {
                         velocity.X *= 0.98f;
                     }
                     if (num120 < -20f && velocity.X > -6f)
                     {
                         velocity.X -= 0.015f;
                     }
                     else if (num120 > 20f && velocity.X < 6f)
                     {
                         velocity.X += 0.015f;
                     }
                     if (velocity.X > 6f)
                     {
                         velocity.X = 6f;
                     }
                     if (velocity.X < -6f)
                     {
                         velocity.X = -6f;
                     }
                     if (num121 < -20f && velocity.Y > 0f)
                     {
                         velocity.Y *= 0.98f;
                     }
                     else if (num121 > 20f && velocity.Y < 0f)
                     {
                         velocity.Y *= 0.98f;
                     }
                     if (num121 < -20f && velocity.Y > -6f)
                     {
                         velocity.Y -= 0.15f;
                     }
                     else if (num121 > 20f && velocity.Y < 6f)
                     {
                         velocity.Y += 0.15f;
                     }
                 }
                 for (int num122 = 0; num122 < 200; num122++)
                 {
                     if (num122 != whoAmI && Main.npc[num122].active && Main.npc[num122].type == type && Math.Abs(position.X - Main.npc[num122].position.X) + Math.Abs(position.Y - Main.npc[num122].position.Y) < (float)width)
                     {
                         if (position.X < Main.npc[num122].position.X)
{
                             velocity.X -= 0.05f;
                         }
                         else
{
                             velocity.X += 0.05f;
                         }
                         if (position.Y < Main.npc[num122].position.Y)
{
                             velocity.Y -= 0.05f;
                         }
                         else
{
                             velocity.Y += 0.05f;
                         }
                     }
                 }
             }
             else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 flag = true;
                 velocity.Y = -5f;
                 ai[2] = 1f;
             }
         }
         else if (type == 426)
         {
             float num123 = 6f;
             float num124 = 0.2f;
             float num125 = 6f;
             if (ai[1] > 0f && velocity.Y > 0f)
             {
                 velocity.Y *= 0.85f;
                 if (velocity.Y == 0f)
                 {
                     velocity.Y = -0.4f;
                 }
             }
             if (velocity.Y != 0f)
             {
                 TargetClosest();
                 spriteDirection = direction;
                 if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     float num126 = Main.player[target].Center.X - (float)(direction * 300) - base.Center.X;
                     if (num126 < 40f && velocity.X > 0f)
                     {
                         velocity.X *= 0.98f;
                     }
                     else if (num126 > 40f && velocity.X < 0f)
                     {
                         velocity.X *= 0.98f;
                     }
                     if (num126 < 40f && velocity.X > 0f - num123)
                     {
                         velocity.X -= num124;
                     }
                     else if (num126 > 40f && velocity.X < num123)
                     {
                         velocity.X += num124;
                     }
                     if (velocity.X > num123)
                     {
                         velocity.X = num123;
                     }
                     if (velocity.X < 0f - num123)
                     {
                         velocity.X = 0f - num123;
                     }
                 }
             }
             else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 flag = true;
                 velocity.Y = 0f - num125;
             }
             for (int num127 = 0; num127 < 200; num127++)
             {
                 if (num127 != whoAmI && Main.npc[num127].active && Main.npc[num127].type == type && Math.Abs(position.X - Main.npc[num127].position.X) + Math.Abs(position.Y - Main.npc[num127].position.Y) < (float)width)
                 {
                     if (position.X < Main.npc[num127].position.X)
                     {
                         velocity.X -= 0.1f;
                     }
                     else
                     {
                         velocity.X += 0.1f;
                     }
                     if (position.Y < Main.npc[num127].position.Y)
                     {
                         velocity.Y -= 0.1f;
                     }
                     else
                     {
                         velocity.Y += 0.1f;
                     }
                 }
             }
             if (Main.rand.Next(6) == 0 && ai[1] <= 20f)
             {
                 position += netOffset;
                 Dust obj6 = Main.dust[Dust.NewDust(base.Center + new Vector2((spriteDirection == 1) ? 8 : (-20), -20f), 8, 8, 229, velocity.X, velocity.Y, 100)];
                 obj6.velocity = obj6.velocity / 4f + velocity / 2f;
                 obj6.scale = 0.6f;
                 obj6.noLight = true;
                 position -= netOffset;
             }
             if (ai[1] >= 57f)
             {
                 position += netOffset;
                 int num128 = Utils.SelectRandom<int>(Main.rand, 161, 229);
                 Dust obj7 = Main.dust[Dust.NewDust(base.Center + new Vector2((spriteDirection == 1) ? 8 : (-20), -20f), 8, 8, num128, velocity.X, velocity.Y, 100)];
                 obj7.velocity = obj7.velocity / 4f + DirectionTo(Main.player[target].Top);
                 obj7.scale = 1.2f;
                 obj7.noLight = true;
                 position -= netOffset;
             }
             if (Main.rand.Next(6) == 0)
             {
                 position += netOffset;
                 Dust dust5 = Main.dust[Dust.NewDust(base.Center, 2, 2, 229)];
                 dust5.position = base.Center + new Vector2((spriteDirection == 1) ? 26 : (-26), 24f);
                 dust5.velocity.X = 0f;
                 if (dust5.velocity.Y < 0f)
                 {
                     dust5.velocity.Y = 0f;
                 }
                 dust5.noGravity = true;
                 dust5.scale = 1f;
                 dust5.noLight = true;
                 position -= netOffset;
             }
         }
         else if (type == 185)
         {
             if (velocity.Y == 0f)
             {
                 rotation = 0f;
                 localAI[0] = 0f;
             }
             else if (localAI[0] == 1f)
             {
                 rotation += velocity.X * 0.05f;
             }
         }
         else if (type == 428)
         {
             if (velocity.Y == 0f)
             {
                 rotation = 0f;
             }
             else
             {
                 rotation += velocity.X * 0.08f;
             }
         }
         if (type == 159 && Main.netMode != 1)
         {
             Vector2 vector31 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num129 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector31.X;
             float num130 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector31.Y;
             if ((float)Math.Sqrt(num129 * num129 + num130 * num130) > 300f)
             {
                 Transform(158);
             }
         }
         if (Main.netMode != 1)
         {
             if (Main.expertMode && target >= 0 && (type == 163 || type == 238 || type == 236 || type == 237) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
             {
                 localAI[0] += 1f;
                 if (justHit)
                 {
                     localAI[0] -= Main.rand.Next(20, 60);
                     if (localAI[0] < 0f)
                     {
                         localAI[0] = 0f;
                     }
                 }
                 if (localAI[0] > (float)Main.rand.Next(180, 900))
                 {
                     localAI[0] = 0f;
                     Vector2 vector32 = Main.player[target].Center - base.Center;
                     vector32.Normalize();
                     vector32 *= 8f;
                     int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(18f, 18f);
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, vector32.X, vector32.Y, 472, attackDamage_ForProjectiles2, 0f, Main.myPlayer);
                 }
             }
             if (velocity.Y == 0f)
             {
                 int num131 = -1;
                 switch (type)
                 {
                 case 164:
                     num131 = 165;
                     break;
                 case 236:
                     num131 = 237;
                     break;
                 case 163:
                     num131 = 238;
                     break;
                 case 239:
                     num131 = 240;
                     break;
                 case 530:
                     num131 = 531;
                     break;
                 }
                 if (num131 != -1 && NPCCanStickToWalls())
                 {
                     Transform(num131);
                 }
             }
         }
         if (type == 243)
         {
             if (justHit && Main.rand.Next(3) == 0)
             {
                 ai[2] -= Main.rand.Next(30);
             }
             if (ai[2] < 0f)
             {
                 ai[2] = 0f;
             }
             if (confused)
             {
                 ai[2] = 0f;
             }
             ai[2] += 1f;
             float num132 = Main.rand.Next(30, 900);
             num132 *= (float)life / (float)lifeMax;
             num132 += 30f;
             if (Main.netMode != 1 && ai[2] >= num132 && velocity.Y == 0f && !Main.player[target].dead && !Main.player[target].frozen && ((direction > 0 && base.Center.X < Main.player[target].Center.X) || (direction < 0 && base.Center.X > Main.player[target].Center.X)) && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 Vector2 vector33 = new Vector2(position.X + (float)width * 0.5f, position.Y + 20f);
                 vector33.X += 10 * direction;
                 float num133 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector33.X;
                 float num134 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector33.Y;
                 num133 += (float)Main.rand.Next(-40, 41);
                 num134 += (float)Main.rand.Next(-40, 41);
                 float num135 = (float)Math.Sqrt(num133 * num133 + num134 * num134);
                 netUpdate = true;
                 num135 = 15f / num135;
                 num133 *= num135;
                 num134 *= num135;
                 int num136 = 32;
                 int num137 = 257;
                 vector33.X += num133 * 3f;
                 vector33.Y += num134 * 3f;
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector33.X, vector33.Y, num133, num134, num137, num136, 0f, Main.myPlayer);
                 ai[2] = 0f;
             }
         }
         if (type == 251)
         {
             if (justHit)
             {
                 ai[2] -= Main.rand.Next(30);
             }
             if (ai[2] < 0f)
             {
                 ai[2] = 0f;
             }
             if (confused)
             {
                 ai[2] = 0f;
             }
             ai[2] += 1f;
             float num138 = Main.rand.Next(60, 1800);
             num138 *= (float)life / (float)lifeMax;
             num138 += 15f;
             if (Main.netMode != 1 && ai[2] >= num138 && velocity.Y == 0f && !Main.player[target].dead && !Main.player[target].frozen && ((direction > 0 && base.Center.X < Main.player[target].Center.X) || (direction < 0 && base.Center.X > Main.player[target].Center.X)) && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 Vector2 vector34 = new Vector2(position.X + (float)width * 0.5f, position.Y + 12f);
                 vector34.X += 6 * direction;
                 float num139 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector34.X;
                 float num140 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector34.Y;
                 num139 += (float)Main.rand.Next(-40, 41);
                 num140 += (float)Main.rand.Next(-30, 0);
                 float num141 = (float)Math.Sqrt(num139 * num139 + num140 * num140);
                 netUpdate = true;
                 num141 = 15f / num141;
                 num139 *= num141;
                 num140 *= num141;
                 int num142 = 30;
                 int num143 = 83;
                 vector34.X += num139 * 3f;
                 vector34.Y += num140 * 3f;
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector34.X, vector34.Y, num139, num140, num143, num142, 0f, Main.myPlayer);
                 ai[2] = 0f;
             }
         }
         if (type == 386)
         {
             if (confused)
             {
                 ai[2] = -60f;
             }
             else
             {
                 if (ai[2] < 60f)
                 {
                     ai[2] += 1f;
                 }
                 if (ai[2] > 0f && CountNPCS(387) >= 4 * CountNPCS(386))
                 {
                     ai[2] = 0f;
                 }
                 if (justHit)
                 {
                     ai[2] = -30f;
                 }
                 if (ai[2] == 30f)
                 {
                     int num144 = (int)position.X / 16;
                     int num145 = (int)position.Y / 16;
                     int num146 = (int)position.X / 16;
                     int num147 = (int)position.Y / 16;
                     int num148 = 5;
                     int num149 = 0;
                     bool flag14 = false;
                     int num150 = 2;
                     int num151 = 0;
                     while (!flag14 && num149 < 100)
                     {
                         num149++;
                         int num152 = Main.rand.Next(num144 - num148, num144 + num148);
                         for (int num153 = Main.rand.Next(num145 - num148, num145 + num148); num153 < num145 + num148; num153++)
{
                             if ((num153 < num145 - num150 || num153 > num145 + num150 || num152 < num144 - num150 || num152 > num144 + num150) && (num153 < num147 - num151 || num153 > num147 + num151 || num152 < num146 - num151 || num152 > num146 + num151) && Main.tile[num152, num153].nactive())
{
                                 bool flag15 = true;
                                 if (Main.tile[num152, num153 - 1].lava())
{
                                     flag15 = false;
                                 }
                                 if (flag15 && Main.tileSolid[Main.tile[num152, num153].type] && !Collision.SolidTiles(num152 - 1, num152 + 1, num153 - 4, num153 - 1))
{
                                     int num154 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), num152 * 16 - width / 2, num153 * 16, 387);
                                     Main.npc[num154].position.Y = num153 * 16 - Main.npc[num154].height;
                                     flag14 = true;
                                     netUpdate = true;
                                     break;
                                 }
                             }
                         }
                     }
                 }
                 if (ai[2] == 60f)
                 {
                     ai[2] = -120f;
                 }
             }
         }
         if (type == 389)
         {
             if (confused)
             {
                 ai[2] = -60f;
             }
             else
             {
                 if (ai[2] < 20f)
                 {
                     ai[2] += 1f;
                 }
                 if (justHit)
                 {
                     ai[2] = -30f;
                 }
                 if (ai[2] == 20f && Main.netMode != 1)
                 {
                     ai[2] = -10 + Main.rand.Next(3) * -10;
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y + 8f, direction * 6, 0f, 437, 25, 1f, Main.myPlayer);
                 }
             }
         }
         if (type == 110 || type == 111 || type == 206 || type == 214 || type == 215 || type == 216 || type == 290 || type == 291 || type == 292 || type == 293 || type == 350 || type == 379 || type == 380 || type == 381 || type == 382 || (type >= 449 && type <= 452) || type == 468 || type == 481 || type == 411 || type == 409 || (type >= 498 && type <= 506) || type == 424 || type == 426 || type == 520)
         {
             bool flag16 = type == 381 || type == 382 || type == 520;
             bool flag17 = type == 426;
             bool flag18 = true;
             int num155 = -1;
             int num156 = -1;
             if (type == 411)
             {
                 flag16 = true;
                 num155 = 120;
                 num156 = 120;
                 if (ai[1] <= 220f)
                 {
                     flag18 = false;
                 }
             }
             if (ai[1] > 0f)
             {
                 ai[1] -= 1f;
             }
             if (justHit)
             {
                 ai[1] = 30f;
                 ai[2] = 0f;
             }
             int num157 = 70;
             if (type == 379 || type == 380)
             {
                 num157 = 80;
             }
             if (type == 381 || type == 382)
             {
                 num157 = 80;
             }
             if (type == 520)
             {
                 num157 = 15;
             }
             if (type == 350)
             {
                 num157 = 110;
             }
             if (type == 291)
             {
                 num157 = 200;
             }
             if (type == 292)
             {
                 num157 = 120;
             }
             if (type == 293)
             {
                 num157 = 90;
             }
             if (type == 111)
             {
                 num157 = 180;
             }
             if (type == 206)
             {
                 num157 = 50;
             }
             if (type == 481)
             {
                 num157 = 100;
             }
             if (type == 214)
             {
                 num157 = 40;
             }
             if (type == 215)
             {
                 num157 = 80;
             }
             if (type == 290)
             {
                 num157 = 30;
             }
             if (type == 411)
             {
                 num157 = 330;
             }
             if (type == 409)
             {
                 num157 = 60;
             }
             if (type == 424)
             {
                 num157 = 180;
             }
             if (type == 426)
             {
                 num157 = 60;
             }
             bool flag19 = false;
             if (type == 216)
             {
                 if (localAI[2] >= 20f)
                 {
                     flag19 = true;
                 }
                 num157 = ((!flag19) ? 8 : 60);
             }
             int num158 = num157 / 2;
             if (type == 424)
             {
                 num158 = num157 - 1;
             }
             if (type == 426)
             {
                 num158 = num157 - 1;
             }
             if (type == 411)
             {
                 num158 = 220;
             }
             if (confused)
             {
                 ai[2] = 0f;
             }
             if (ai[2] > 0f)
             {
                 if (flag18)
                 {
                     TargetClosest();
                 }
                 if (ai[1] == (float)num158)
                 {
                     if (type == 216)
                     {
                         localAI[2] += 1f;
                     }
                     float num159 = 11f;
                     if (type == 111)
                     {
                         num159 = 9f;
                     }
                     if (type == 206)
                     {
                         num159 = 7f;
                     }
                     if (type == 290)
                     {
                         num159 = 9f;
                     }
                     if (type == 293)
                     {
                         num159 = 4f;
                     }
                     if (type == 214)
                     {
                         num159 = 14f;
                     }
                     if (type == 215)
                     {
                         num159 = 16f;
                     }
                     if (type == 382)
                     {
                         num159 = 7f;
                     }
                     if (type == 520)
                     {
                         num159 = 8f;
                     }
                     if (type == 409)
                     {
                         num159 = 4f;
                     }
                     if (type >= 449 && type <= 452)
                     {
                         num159 = 7f;
                     }
                     if (type == 481)
                     {
                         num159 = 8f;
                     }
                     if (type == 468)
                     {
                         num159 = 7.5f;
                     }
                     if (type == 411)
                     {
                         num159 = 1f;
                     }
                     if (type >= 498 && type <= 506)
                     {
                         num159 = 7f;
                     }
                     Vector2 chaserPosition2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                     if (type == 481)
                     {
                         chaserPosition2.Y -= 14f;
                     }
                     if (type == 206)
                     {
                         chaserPosition2.Y -= 10f;
                     }
                     if (type == 290)
                     {
                         chaserPosition2.Y -= 10f;
                     }
                     if (type == 381 || type == 382)
                     {
                         chaserPosition2.Y += 6f;
                     }
                     if (type == 520)
                     {
                         chaserPosition2.Y = position.Y + 20f;
                     }
                     if (type >= 498 && type <= 506)
                     {
                         chaserPosition2.Y -= 8f;
                     }
                     if (type == 426)
                     {
                         chaserPosition2 += new Vector2(spriteDirection * 2, -12f);
                         num159 = 7f;
                     }
                     float num160 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - chaserPosition2.X;
                     float num161 = Math.Abs(num160) * 0.1f;
                     if (type == 291 || type == 292)
                     {
                         num161 = 0f;
                     }
                     if (type == 215)
                     {
                         num161 = Math.Abs(num160) * 0.08f;
                     }
                     if (type == 214 || (type == 216 && !flag19))
                     {
                         num161 = 0f;
                     }
                     if (type == 381 || type == 382 || type == 520)
                     {
                         num161 = 0f;
                     }
                     if (type >= 449 && type <= 452)
                     {
                         num161 = Math.Abs(num160) * (float)Main.rand.Next(10, 50) * 0.01f;
                     }
                     if (type == 468)
                     {
                         num161 = Math.Abs(num160) * (float)Main.rand.Next(10, 50) * 0.01f;
                     }
                     if (type == 481)
                     {
                         num161 = Math.Abs(num160) * (float)Main.rand.Next(-10, 11) * 0.0035f;
                     }
                     if (type >= 498 && type <= 506)
                     {
                         num161 = Math.Abs(num160) * (float)Main.rand.Next(1, 11) * 0.0025f;
                     }
                     float num162 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - chaserPosition2.Y - num161;
                     if (type == 291)
                     {
                         num160 += (float)Main.rand.Next(-40, 41) * 0.2f;
                         num162 += (float)Main.rand.Next(-40, 41) * 0.2f;
                     }
                     else if (type == 381 || type == 382 || type == 520)
                     {
                         num160 += (float)Main.rand.Next(-100, 101) * 0.4f;
                         num162 += (float)Main.rand.Next(-100, 101) * 0.4f;
                         num160 *= (float)Main.rand.Next(85, 116) * 0.01f;
                         num162 *= (float)Main.rand.Next(85, 116) * 0.01f;
                         if (type == 520)
{
                             num160 += (float)Main.rand.Next(-100, 101) * 0.6f;
                             num162 += (float)Main.rand.Next(-100, 101) * 0.6f;
                             num160 *= (float)Main.rand.Next(85, 116) * 0.015f;
                             num162 *= (float)Main.rand.Next(85, 116) * 0.015f;
                         }
                     }
                     else if (type == 481)
                     {
                         num160 += (float)Main.rand.Next(-40, 41) * 0.4f;
                         num162 += (float)Main.rand.Next(-40, 41) * 0.4f;
                     }
                     else if (type >= 498 && type <= 506)
                     {
                         num160 += (float)Main.rand.Next(-40, 41) * 0.3f;
                         num162 += (float)Main.rand.Next(-40, 41) * 0.3f;
                     }
                     else if (type == 426)
                     {
                         num160 += (float)Main.rand.Next(-30, 31) * 0.3f;
                         num162 += (float)Main.rand.Next(-30, 31) * 0.3f;
                     }
                     else if (type != 292)
                     {
                         num160 += (float)Main.rand.Next(-40, 41);
                         num162 += (float)Main.rand.Next(-40, 41);
                     }
                     float num163 = (float)Math.Sqrt(num160 * num160 + num162 * num162);
                     netUpdate = true;
                     num163 = num159 / num163;
                     num160 *= num163;
                     num162 *= num163;
                     int num164 = 35;
                     int num165 = 82;
                     if (type == 111)
                     {
                         num164 = 11;
                     }
                     if (type == 206)
                     {
                         num164 = 37;
                     }
                     if (type == 379 || type == 380)
                     {
                         num164 = 40;
                     }
                     if (type == 350)
                     {
                         num164 = 45;
                     }
                     if (type == 468)
                     {
                         num164 = 50;
                     }
                     if (type == 111)
                     {
                         num165 = 81;
                     }
                     if (type == 379 || type == 380)
                     {
                         num165 = 81;
                     }
                     if (type == 381)
                     {
                         num165 = 436;
                         num164 = 24;
                     }
                     if (type == 382)
                     {
                         num165 = 438;
                         num164 = 30;
                     }
                     if (type == 520)
                     {
                         num165 = 592;
                         num164 = 35;
                     }
                     if (type >= 449 && type <= 452)
                     {
                         num165 = 471;
                         num164 = 15;
                     }
                     if (type >= 498 && type <= 506)
                     {
                         num165 = 572;
                         num164 = 14;
                     }
                     if (type == 481)
                     {
                         num165 = 508;
                         num164 = 18;
                     }
                     if (type == 206)
                     {
                         num165 = 177;
                     }
                     if (type == 468)
                     {
                         num165 = 501;
                     }
                     if (type == 411)
                     {
                         num165 = 537;
                         num164 = GetAttackDamage_ForProjectiles(60f, 45f);
                     }
                     if (type == 424)
                     {
                         num165 = 573;
                         num164 = GetAttackDamage_ForProjectiles(60f, 45f);
                     }
                     if (type == 426)
                     {
                         num165 = 581;
                         num164 = GetAttackDamage_ForProjectiles(60f, 45f);
                     }
                     if (type == 291)
                     {
                         num165 = 302;
                         num164 = 100;
                     }
                     if (type == 290)
                     {
                         num165 = 300;
                         num164 = 60;
                     }
                     if (type == 293)
                     {
                         num165 = 303;
                         num164 = 60;
                     }
                     if (type == 214)
                     {
                         num165 = 180;
                         num164 = 25;
                     }
                     if (type == 215)
                     {
                         num165 = 82;
                         num164 = 40;
                     }
                     if (type == 292)
                     {
                         num164 = 50;
                         num165 = 180;
                     }
                     if (type == 216)
                     {
                         num165 = 180;
                         num164 = 30;
                         if (flag19)
{
                             num164 = 100;
                             num165 = 240;
                             localAI[2] = 0f;
                         }
                     }
                     Player player3 = Main.player[target];
                     Vector2? vector35 = null;
                     if (type == 426)
                     {
                         vector35 = Main.rand.NextVector2FromRectangle(player3.Hitbox);
                     }
                     if (vector35.HasValue)
                     {
                         Utils.ChaseResults chaseResults2 = Utils.GetChaseResults(chaserPosition2, num159, vector35.Value, player3.velocity);
                         if (chaseResults2.InterceptionHappens)
{
                             Vector2 vector36 = Utils.FactorAcceleration(chaseResults2.ChaserVelocity, chaseResults2.InterceptionTime, new Vector2(0f, 0.1f), 15);
                             num160 = vector36.X;
                             num162 = vector36.Y;
                         }
                     }
                     chaserPosition2.X += num160;
                     chaserPosition2.Y += num162;
                     if (type == 290)
                     {
                         num164 = GetAttackDamage_ForProjectiles(num164, (float)num164 * 0.75f);
                     }
                     if (type >= 381 && type <= 392)
                     {
                         num164 = GetAttackDamage_ForProjectiles(num164, (float)num164 * 0.8f);
                     }
                     if (Main.netMode != 1)
                     {
                         if (type == 292)
{
                             for (int num166 = 0; num166 < 4; num166++)
{
                                 num160 = player3.position.X + (float)player3.width * 0.5f - chaserPosition2.X;
                                 num162 = player3.position.Y + (float)player3.height * 0.5f - chaserPosition2.Y;
                                 num163 = (float)Math.Sqrt(num160 * num160 + num162 * num162);
                                 num163 = 12f / num163;
                                 num160 = (num160 += (float)Main.rand.Next(-40, 41));
                                 num162 = (num162 += (float)Main.rand.Next(-40, 41));
                                 num160 *= num163;
                                 num162 *= num163;
                                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num160, num162, num165, num164, 0f, Main.myPlayer);
                             }
                         }
                         else if (type == 411)
{
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num160, num162, num165, num164, 0f, Main.myPlayer, 0f, whoAmI);
                         }
                         else if (type == 424)
{
                             for (int num167 = 0; num167 < 4; num167++)
{
                                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X - (float)(spriteDirection * 4), base.Center.Y + 6f, (float)(-3 + 2 * num167) * 0.15f, (float)(-Main.rand.Next(0, 3)) * 0.2f - 0.1f, num165, num164, 0f, Main.myPlayer, 0f, whoAmI);
                             }
                         }
                         else if (type == 409)
{
                             int num168 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 410, whoAmI);
                             Main.npc[num168].velocity = new Vector2(num160, -6f + num162);
                         }
                         else
{
                             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num160, num162, num165, num164, 0f, Main.myPlayer);
                         }
                     }
                     if (Math.Abs(num162) > Math.Abs(num160) * 2f)
                     {
                         if (num162 > 0f)
{
                             ai[2] = 1f;
                         }
                         else
{
                             ai[2] = 5f;
                         }
                     }
                     else if (Math.Abs(num160) > Math.Abs(num162) * 2f)
                     {
                         ai[2] = 3f;
                     }
                     else if (num162 > 0f)
                     {
                         ai[2] = 2f;
                     }
                     else
                     {
                         ai[2] = 4f;
                     }
                 }
                 if ((velocity.Y != 0f && !flag17) || ai[1] <= 0f)
                 {
                     ai[2] = 0f;
                     ai[1] = 0f;
                 }
                 else if (!flag16 || (num155 != -1 && ai[1] >= (float)num155 && ai[1] < (float)(num155 + num156) && (!flag17 || velocity.Y == 0f)))
                 {
                     velocity.X *= 0.9f;
                     spriteDirection = direction;
                 }
             }
             if (type == 468 && !Main.eclipse)
             {
                 flag16 = true;
             }
             else if ((ai[2] <= 0f || flag16) && (velocity.Y == 0f || flag17) && ai[1] <= 0f && !Main.player[target].dead)
             {
                 bool flag20 = Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height);
                 if (type == 520)
                 {
                     flag20 = Collision.CanHitLine(base.Top + new Vector2(0f, 20f), 0, 0, Main.player[target].position, Main.player[target].width, Main.player[target].height);
                 }
                 if (Main.player[target].stealth == 0f && Main.player[target].itemAnimation == 0)
                 {
                     flag20 = false;
                 }
                 if (flag20)
                 {
                     float num169 = 10f;
                     Vector2 vector37 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                     float num170 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector37.X;
                     float num171 = Math.Abs(num170) * 0.1f;
                     float num172 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector37.Y - num171;
                     num170 += (float)Main.rand.Next(-40, 41);
                     num172 += (float)Main.rand.Next(-40, 41);
                     float num173 = (float)Math.Sqrt(num170 * num170 + num172 * num172);
                     float num174 = 700f;
                     if (type == 214)
                     {
                         num174 = 550f;
                     }
                     if (type == 215)
                     {
                         num174 = 800f;
                     }
                     if (type >= 498 && type <= 506)
                     {
                         num174 = 190f;
                     }
                     if (type >= 449 && type <= 452)
                     {
                         num174 = 200f;
                     }
                     if (type == 481)
                     {
                         num174 = 400f;
                     }
                     if (type == 468)
                     {
                         num174 = 400f;
                     }
                     if (num173 < num174)
                     {
                         netUpdate = true;
                         velocity.X *= 0.5f;
                         num173 = num169 / num173;
                         num170 *= num173;
                         num172 *= num173;
                         ai[2] = 3f;
                         ai[1] = num157;
                         if (Math.Abs(num172) > Math.Abs(num170) * 2f)
{
                             if (num172 > 0f)
{
                                 ai[2] = 1f;
                             }
                             else
{
                                 ai[2] = 5f;
                             }
                         }
                         else if (Math.Abs(num170) > Math.Abs(num172) * 2f)
{
                             ai[2] = 3f;
                         }
                         else if (num172 > 0f)
{
                             ai[2] = 2f;
                         }
                         else
{
                             ai[2] = 4f;
                         }
                     }
                 }
             }
             if (ai[2] <= 0f || (flag16 && (num155 == -1 || !(ai[1] >= (float)num155) || !(ai[1] < (float)(num155 + num156)))))
             {
                 float num175 = 1f;
                 float num176 = 0.07f;
                 float num177 = 0.8f;
                 if (type == 214)
                 {
                     num175 = 2f;
                     num176 = 0.09f;
                 }
                 else if (type == 215)
                 {
                     num175 = 1.5f;
                     num176 = 0.08f;
                 }
                 else if (type == 381 || type == 382)
                 {
                     num175 = 2f;
                     num176 = 0.5f;
                 }
                 else if (type == 520)
                 {
                     num175 = 4f;
                     num176 = 1f;
                     num177 = 0.7f;
                 }
                 else if (type == 411)
                 {
                     num175 = 2f;
                     num176 = 0.5f;
                 }
                 else if (type == 409)
                 {
                     num175 = 2f;
                     num176 = 0.5f;
                 }
                 else if (type == 426)
                 {
                     num175 = 4f;
                     num176 = 0.6f;
                     num177 = 0.95f;
                 }
                 bool flag21 = false;
                 if ((type == 381 || type == 382) && Vector2.Distance(base.Center, Main.player[target].Center) < 300f && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     flag21 = true;
                     ai[3] = 0f;
                 }
                 if (type == 520 && Vector2.Distance(base.Center, Main.player[target].Center) < 400f && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     flag21 = true;
                     ai[3] = 0f;
                 }
                 if (velocity.X < 0f - num175 || velocity.X > num175 || flag21)
                 {
                     if (velocity.Y == 0f)
                     {
                         velocity *= num177;
                     }
                 }
                 else if (velocity.X < num175 && direction == 1)
                 {
                     velocity.X += num176;
                     if (velocity.X > num175)
                     {
                         velocity.X = num175;
                     }
                 }
                 else if (velocity.X > 0f - num175 && direction == -1)
                 {
                     velocity.X -= num176;
                     if (velocity.X < 0f - num175)
                     {
                         velocity.X = 0f - num175;
                     }
                 }
             }
             if (type == 520)
             {
                 localAI[2] += 1f;
                 if (localAI[2] >= 6f)
                 {
                     localAI[2] = 0f;
                     localAI[3] = Main.player[target].DirectionFrom(base.Top + new Vector2(0f, 20f)).ToRotation();
                 }
             }
         }
         if (type == 109 && Main.netMode != 1 && !Main.player[target].dead)
         {
             if (justHit)
             {
                 ai[2] = 0f;
             }
             ai[2] += 1f;
             if (ai[2] > 60f)
             {
                 Vector2 vector38 = new Vector2(position.X + (float)width * 0.5f - (float)(direction * 24), position.Y + 4f);
                 if (Main.rand.Next(5) != 0 || AnyNPCs(378))
                 {
                     int num178 = Main.rand.Next(3, 8) * direction;
                     int num179 = Main.rand.Next(-8, -5);
                     int num180 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector38.X, vector38.Y, num178, num179, 75, 80, 0f, Main.myPlayer);
                     Main.projectile[num180].timeLeft = 300;
                     ai[2] = 0f;
                 }
                 else
                 {
                     ai[2] = -120f;
                     int number = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector38.X, (int)vector38.Y, 378);
                     NetMessage.SendData(23, -1, -1, null, number);
                 }
             }
         }
         if (velocity.Y == 0f || flag)
         {
             int num181 = (int)(position.Y + (float)height + 7f) / 16;
             int num182 = (int)(position.Y - 9f) / 16;
             int num183 = (int)position.X / 16;
             int num184 = (int)(position.X + (float)width) / 16;
             int num185 = (int)(position.X + 8f) / 16;
             int num186 = (int)(position.X + (float)width - 8f) / 16;
             bool flag22 = false;
             for (int num187 = num185; num187 <= num186; num187++)
             {
                 if (num187 >= num183 && num187 <= num184 && Main.tile[num187, num181] == null)
                 {
                     flag22 = true;
                     continue;
                 }
                 if (Main.tile[num187, num182] != null && Main.tile[num187, num182].nactive() && Main.tileSolid[Main.tile[num187, num182].type])
                 {
                     flag5 = false;
                     break;
                 }
                 if (!flag22 && num187 >= num183 && num187 <= num184 && Main.tile[num187, num181].nactive() && Main.tileSolid[Main.tile[num187, num181].type])
                 {
                     flag5 = true;
                 }
             }
             if (!flag5 && velocity.Y < 0f)
             {
                 velocity.Y = 0f;
             }
             if (flag22)
             {
                 return;
             }
         }
         if (type == 428)
         {
             flag5 = false;
         }
         if (velocity.Y >= 0f && (type != 580 || directionY != 1))
         {
             int num188 = 0;
             if (velocity.X < 0f)
             {
                 num188 = -1;
             }
             if (velocity.X > 0f)
             {
                 num188 = 1;
             }
             Vector2 vector39 = position;
             vector39.X += velocity.X;
             int num189 = (int)((vector39.X + (float)(width / 2) + (float)((width / 2 + 1) * num188)) / 16f);
             int num190 = (int)((vector39.Y + (float)height - 1f) / 16f);
             if (WorldGen.InWorld(num189, num190, 4))
             {
                 if (Main.tile[num189, num190] == null)
                 {
                     Main.tile[num189, num190] = new Tile();
                 }
                 if (Main.tile[num189, num190 - 1] == null)
                 {
                     Main.tile[num189, num190 - 1] = new Tile();
                 }
                 if (Main.tile[num189, num190 - 2] == null)
                 {
                     Main.tile[num189, num190 - 2] = new Tile();
                 }
                 if (Main.tile[num189, num190 - 3] == null)
                 {
                     Main.tile[num189, num190 - 3] = new Tile();
                 }
                 if (Main.tile[num189, num190 + 1] == null)
                 {
                     Main.tile[num189, num190 + 1] = new Tile();
                 }
                 if (Main.tile[num189 - num188, num190 - 3] == null)
                 {
                     Main.tile[num189 - num188, num190 - 3] = new Tile();
                 }
                 if ((float)(num189 * 16) < vector39.X + (float)width && (float)(num189 * 16 + 16) > vector39.X && ((Main.tile[num189, num190].nactive() && !Main.tile[num189, num190].topSlope() && !Main.tile[num189, num190 - 1].topSlope() && Main.tileSolid[Main.tile[num189, num190].type] && !Main.tileSolidTop[Main.tile[num189, num190].type]) || (Main.tile[num189, num190 - 1].halfBrick() && Main.tile[num189, num190 - 1].nactive())) && (!Main.tile[num189, num190 - 1].nactive() || !Main.tileSolid[Main.tile[num189, num190 - 1].type] || Main.tileSolidTop[Main.tile[num189, num190 - 1].type] || (Main.tile[num189, num190 - 1].halfBrick() && (!Main.tile[num189, num190 - 4].nactive() || !Main.tileSolid[Main.tile[num189, num190 - 4].type] || Main.tileSolidTop[Main.tile[num189, num190 - 4].type]))) && (!Main.tile[num189, num190 - 2].nactive() || !Main.tileSolid[Main.tile[num189, num190 - 2].type] || Main.tileSolidTop[Main.tile[num189, num190 - 2].type]) && (!Main.tile[num189, num190 - 3].nactive() || !Main.tileSolid[Main.tile[num189, num190 - 3].type] || Main.tileSolidTop[Main.tile[num189, num190 - 3].type]) && (!Main.tile[num189 - num188, num190 - 3].nactive() || !Main.tileSolid[Main.tile[num189 - num188, num190 - 3].type]))
                 {
                     float num191 = num190 * 16;
                     if (Main.tile[num189, num190].halfBrick())
                     {
                         num191 += 8f;
                     }
                     if (Main.tile[num189, num190 - 1].halfBrick())
                     {
                         num191 -= 8f;
                     }
                     if (num191 < vector39.Y + (float)height)
                     {
                         float num192 = vector39.Y + (float)height - num191;
                         float num193 = 16.1f;
                         if (type == 163 || type == 164 || type == 236 || type == 239 || type == 530)
{
                             num193 += 8f;
                         }
                         if (num192 <= num193)
{
                             gfxOffY += position.Y + (float)height - num191;
                             position.Y = num191 - (float)height;
                             if (num192 < 9f)
{
                                 stepSpeed = 1f;
                             }
                             else
{
                                 stepSpeed = 2f;
                             }
                         }
                     }
                 }
             }
         }
         if (flag5)
         {
             int num194 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
             int num195 = (int)((position.Y + (float)height - 15f) / 16f);
             if (type == 109 || type == 163 || type == 164 || type == 199 || type == 236 || type == 239 || type == 257 || type == 258 || type == 290 || type == 391 || type == 425 || type == 427 || type == 426 || type == 580 || type == 508 || type == 415 || type == 530 || type == 532 || type == 582)
             {
                 num194 = (int)((position.X + (float)(width / 2) + (float)((width / 2 + 16) * direction)) / 16f);
             }
             if (Main.tile[num194, num195] == null)
             {
                 Main.tile[num194, num195] = new Tile();
             }
             if (Main.tile[num194, num195 - 1] == null)
             {
                 Main.tile[num194, num195 - 1] = new Tile();
             }
             if (Main.tile[num194, num195 - 2] == null)
             {
                 Main.tile[num194, num195 - 2] = new Tile();
             }
             if (Main.tile[num194, num195 - 3] == null)
             {
                 Main.tile[num194, num195 - 3] = new Tile();
             }
             if (Main.tile[num194, num195 + 1] == null)
             {
                 Main.tile[num194, num195 + 1] = new Tile();
             }
             if (Main.tile[num194 + direction, num195 - 1] == null)
             {
                 Main.tile[num194 + direction, num195 - 1] = new Tile();
             }
             if (Main.tile[num194 + direction, num195 + 1] == null)
             {
                 Main.tile[num194 + direction, num195 + 1] = new Tile();
             }
             if (Main.tile[num194 - direction, num195 + 1] == null)
             {
                 Main.tile[num194 - direction, num195 + 1] = new Tile();
             }
             Main.tile[num194, num195 + 1].halfBrick();
             if (Main.tile[num194, num195 - 1].nactive() && (Main.tile[num194, num195 - 1].type == 10 || Main.tile[num194, num195 - 1].type == 388) && flag8)
             {
                 ai[2] += 1f;
                 ai[3] = 0f;
                 if (ai[2] >= 60f)
                 {
                     bool flag23 = type == 3 || type == 430 || type == 590 || type == 331 || type == 332 || type == 132 || type == 161 || type == 186 || type == 187 || type == 188 || type == 189 || type == 200 || type == 223 || type == 320 || type == 321 || type == 319 || type == 21 || type == 324 || type == 323 || type == 322 || type == 44 || type == 196 || type == 167 || type == 77 || type == 197 || type == 202 || type == 203 || type == 449 || type == 450 || type == 451 || type == 452 || type == 481 || type == 201 || type == 635;
                     bool flag24 = Main.player[target].ZoneGraveyard && Main.rand.Next(60) == 0;
                     if ((!Main.bloodMoon || Main.getGoodWorld) && !flag24 && flag23)
                     {
                         ai[1] = 0f;
                     }
                     velocity.X = 0.5f * (float)(-direction);
                     int num196 = 5;
                     if (Main.tile[num194, num195 - 1].type == 388)
                     {
                         num196 = 2;
                     }
                     ai[1] += num196;
                     if (type == 27)
                     {
                         ai[1] += 1f;
                     }
                     if (type == 31 || type == 294 || type == 295 || type == 296)
                     {
                         ai[1] += 6f;
                     }
                     ai[2] = 0f;
                     bool flag25 = false;
                     if (ai[1] >= 10f)
                     {
                         flag25 = true;
                         ai[1] = 10f;
                     }
                     if (type == 460)
                     {
                         flag25 = true;
                     }
                     WorldGen.KillTile(num194, num195 - 1, fail: true);
                     if ((Main.netMode != 1 || !flag25) && flag25 && Main.netMode != 1)
                     {
                         if (type == 26)
{
                             WorldGen.KillTile(num194, num195 - 1);
                             if (Main.netMode == 2)
{
                                 NetMessage.SendData(17, -1, -1, null, 0, num194, num195 - 1);
                             }
                         }
                         else
{
                             if (Main.tile[num194, num195 - 1].type == 10)
{
                                 bool flag26 = WorldGen.OpenDoor(num194, num195 - 1, direction);
                                 if (!flag26)
{
                                     ai[3] = num56;
                                     netUpdate = true;
                                 }
                                 if (Main.netMode == 2 && flag26)
{
                                     NetMessage.SendData(19, -1, -1, null, 0, num194, num195 - 1, direction);
                                 }
                             }
                             if (Main.tile[num194, num195 - 1].type == 388)
{
                                 bool flag27 = WorldGen.ShiftTallGate(num194, num195 - 1, closing: false);
                                 if (!flag27)
{
                                     ai[3] = num56;
                                     netUpdate = true;
                                 }
                                 if (Main.netMode == 2 && flag27)
{
                                     NetMessage.SendData(19, -1, -1, null, 4, num194, num195 - 1);
                                 }
                             }
                         }
                     }
                 }
             }
             else
             {
                 int num197 = spriteDirection;
                 if (type == 425)
                 {
                     num197 *= -1;
                 }
                 if ((velocity.X < 0f && num197 == -1) || (velocity.X > 0f && num197 == 1))
                 {
                     if (height >= 32 && Main.tile[num194, num195 - 2].nactive() && Main.tileSolid[Main.tile[num194, num195 - 2].type])
                     {
                         if (Main.tile[num194, num195 - 3].nactive() && Main.tileSolid[Main.tile[num194, num195 - 3].type])
{
                             velocity.Y = -8f;
                             netUpdate = true;
                         }
                         else
{
                             velocity.Y = -7f;
                             netUpdate = true;
                         }
                     }
                     else if (Main.tile[num194, num195 - 1].nactive() && Main.tileSolid[Main.tile[num194, num195 - 1].type])
                     {
                         if (type == 624)
{
                             velocity.Y = -8f;
                             int num198 = (int)(position.Y + (float)height) / 16;
                             if (WorldGen.SolidTile((int)base.Center.X / 16, num198 - 8))
{
                                 direction *= -1;
                                 spriteDirection = direction;
                                 velocity.X = 3 * direction;
                             }
                         }
                         else
{
                             velocity.Y = -6f;
                         }
                         netUpdate = true;
                     }
                     else if (position.Y + (float)height - (float)(num195 * 16) > 20f && Main.tile[num194, num195].nactive() && !Main.tile[num194, num195].topSlope() && Main.tileSolid[Main.tile[num194, num195].type])
                     {
                         velocity.Y = -5f;
                         netUpdate = true;
                     }
                     else if (directionY < 0 && type != 67 && (!Main.tile[num194, num195 + 1].nactive() || !Main.tileSolid[Main.tile[num194, num195 + 1].type]) && (!Main.tile[num194 + direction, num195 + 1].nactive() || !Main.tileSolid[Main.tile[num194 + direction, num195 + 1].type]))
                     {
                         velocity.Y = -8f;
                         velocity.X *= 1.5f;
                         netUpdate = true;
                     }
                     else if (flag8)
                     {
                         ai[1] = 0f;
                         ai[2] = 0f;
                     }
                     if (velocity.Y == 0f && flag6 && ai[3] == 1f)
                     {
                         velocity.Y = -5f;
                     }
                     if (velocity.Y == 0f && (Main.expertMode || type == 586) && Main.player[target].Bottom.Y < base.Top.Y && Math.Abs(base.Center.X - Main.player[target].Center.X) < (float)(Main.player[target].width * 3) && Collision.CanHit(this, Main.player[target]))
                     {
                         if (type == 586)
{
                             int num199 = (int)((base.Bottom.Y - 16f - Main.player[target].Bottom.Y) / 16f);
                             if (num199 < 14 && Collision.CanHit(this, Main.player[target]))
{
                                 if (num199 < 7)
{
                                     velocity.Y = -8.8f;
                                 }
                                 else if (num199 < 8)
{
                                     velocity.Y = -9.2f;
                                 }
                                 else if (num199 < 9)
{
                                     velocity.Y = -9.7f;
                                 }
                                 else if (num199 < 10)
{
                                     velocity.Y = -10.3f;
                                 }
                                 else if (num199 < 11)
{
                                     velocity.Y = -10.6f;
                                 }
                                 else
{
                                     velocity.Y = -11f;
                                 }
                             }
                         }
                         if (velocity.Y == 0f)
{
                             int num200 = 6;
                             if (Main.player[target].Bottom.Y > base.Top.Y - (float)(num200 * 16))
{
                                 velocity.Y = -7.9f;
                             }
                             else
{
                                 int num201 = (int)(base.Center.X / 16f);
                                 int num202 = (int)(base.Bottom.Y / 16f) - 1;
                                 for (int num203 = num202; num203 > num202 - num200; num203--)
{
                                     if (Main.tile[num201, num203].nactive() && TileID.Sets.Platforms[Main.tile[num201, num203].type])
{
                                         velocity.Y = -7.9f;
                                         break;
                                     }
                                 }
                             }
                         }
                     }
                 }
                 if ((type == 31 || type == 294 || type == 295 || type == 296 || type == 47 || type == 77 || type == 104 || type == 168 || type == 196 || type == 385 || type == 389 || type == 464 || type == 470 || (type >= 524 && type <= 527)) && velocity.Y == 0f)
                 {
                     int num204 = 100;
                     int num205 = 50;
                     if (type == 586)
                     {
                         num204 = 150;
                         num205 = 150;
                     }
                     if (Math.Abs(position.X + (float)(width / 2) - (Main.player[target].position.X + (float)(Main.player[target].width / 2))) < (float)num204 && Math.Abs(position.Y + (float)(height / 2) - (Main.player[target].position.Y + (float)(Main.player[target].height / 2))) < (float)num205 && ((direction > 0 && velocity.X >= 1f) || (direction < 0 && velocity.X <= -1f)))
                     {
                         if (type == 586)
{
                             velocity.X += direction;
                             velocity.X *= 2f;
                             if (velocity.X > 8f)
{
                                 velocity.X = 8f;
                             }
                             if (velocity.X < -8f)
{
                                 velocity.X = -8f;
                             }
                             velocity.Y = -4.5f;
                             if (position.Y > Main.player[target].position.Y + 40f)
{
                                 velocity.Y -= 2f;
                             }
                             if (position.Y > Main.player[target].position.Y + 80f)
{
                                 velocity.Y -= 2f;
                             }
                             if (position.Y > Main.player[target].position.Y + 120f)
{
                                 velocity.Y -= 2f;
                             }
                         }
                         else
{
                             velocity.X *= 2f;
                             if (velocity.X > 3f)
{
                                 velocity.X = 3f;
                             }
                             if (velocity.X < -3f)
{
                                 velocity.X = -3f;
                             }
                             velocity.Y = -4f;
                         }
                         netUpdate = true;
                     }
                 }
                 if (type == 120 && velocity.Y < 0f)
                 {
                     velocity.Y *= 1.1f;
                 }
                 if (type == 287 && velocity.Y == 0f && Math.Abs(position.X + (float)(width / 2) - (Main.player[target].position.X + (float)(Main.player[target].width / 2))) < 150f && Math.Abs(position.Y + (float)(height / 2) - (Main.player[target].position.Y + (float)(Main.player[target].height / 2))) < 50f && ((direction > 0 && velocity.X >= 1f) || (direction < 0 && velocity.X <= -1f)))
                 {
                     velocity.X = 8 * direction;
                     velocity.Y = -4f;
                     netUpdate = true;
                 }
                 if (type == 287 && velocity.Y < 0f)
                 {
                     velocity.X *= 1.2f;
                     velocity.Y *= 1.1f;
                 }
                 if (type == 460 && velocity.Y < 0f)
                 {
                     velocity.X *= 1.3f;
                     velocity.Y *= 1.1f;
                 }
             }
         }
         else if (flag8)
         {
             ai[1] = 0f;
             ai[2] = 0f;
         }
         if (Main.netMode != 1 && type == 120 && ai[3] >= (float)num56)
         {
             int targetTileX = (int)Main.player[target].Center.X / 16;
             int targetTileY = (int)Main.player[target].Center.Y / 16;
             Vector2 chosenTile = Vector2.Zero;
             if (AI_AttemptToFindTeleportSpot(ref chosenTile, targetTileX, targetTileY, 20, 9))
             {
                 position.X = chosenTile.X * 16f - (float)(width / 2);
                 position.Y = chosenTile.Y * 16f - (float)height;
                 ai[3] = -120f;
                 netUpdate = true;
             }
         }
     }
References Entity.active, Tile.active(), Player.AddBuff(), Lighting.AddLight(), ai, AI_003_Gnomes_ShouldTurnToStone(), AI_AttemptToFindTeleportSpot(), Dust.alpha, alpha, AnyNPCs(), Main.BestiaryTracker, Main.bloodMoon, Entity.Bottom, Collision.CanHit(), Collision.CanHitLine(), TileObject.CanPlace(), Entity.Center, Utils.ChaseResults.ChaserVelocity, collideX, Color, confused, CountKillForBannersAndDropThem(), CountNPCS(), Player.creativeGodMode, Dust.customData, damage, Player.dead, defDamage, defDefense, defense, DespawnEncouragement_AIStyle3_Fighters_CanBeBusyWithAction(), DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged(), Entity.direction, Entity.DirectionFrom(), Entity.DirectionTo(), directionY, Entity.Distance(), dontTakeDamage, Main.dust, Main.eclipse, EncourageDespawn(), Main.expertMode, Utils.FactorAcceleration(), Dust.fadeIn, Player.FindBuffIndex(), Player.frozen, Main.GameModeInfo, GetAttackDamage_ForProjectiles(), Utils.GetChaseResults(), Main.getGoodWorld, GetSpawnSource_ForProjectile(), GetSpawnSourceForNPCFromNPCAI(), Framing.GetTileSafely(), gfxOffY, gravity, Tile.halfBrick(), Entity.height, hide, Entity.Hitbox, WorldGen.InWorld(), Main.IsItDay(), IsNPCValidForBestiaryKillCredit(), SoundID.Item8, Player.itemAnimation, justHit, BestiaryUnlocksTracker.Kills, WorldGen.KillTile(), knockBackResist, GameModeData.KnockbackToEnemiesMultiplier, Tile.lava(), life, lifeMax, Tile.liquid, localAI, Main.myPlayer, Tile.nactive(), Main.netMode, netOffset, netUpdate, Dust.NewDust(), Dust.NewDustDirect(), NewNPC(), Projectile.NewProjectile(), UnifiedRandom.Next(), Dust.noGravity, noGravity, Dust.noLight, AchievementsHelper.NotifyProgressionEvent(), noTileCollide, Main.npc, NPCCanStickToWalls(), oldPos, Entity.oldPosition, Entity.oldVelocity, WorldGen.OpenDoor(), WorldGen.PlaceTile(), TileID.Sets.Platforms, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.projectile, Main.rand, Utils.RandomVector2(), reflectsProjectiles, NPCKillsTracker.RegisterKill(), Main.remixWorld, rotation, Dust.scale, scale, NetMessage.SendData(), NetMessage.SendTileSquare(), WorldGen.ShiftTallGate(), shimmerTransparency, Collision.SolidCollision(), WorldGen.SolidTile(), WorldGen.SolidTileAllowBottomSlope(), Collision.SolidTiles(), spriteDirection, Player.stealth, stepSpeed, takenDamageMultiplier, target, TargetClosest(), Tile, Main.tile, Main.tileSolid, Main.tileSolidTop, Projectile.timeLeft, Entity.Top, Tile.topSlope(), Transform(), type, Tile.type, Dust.velocity, Entity.velocity, Tile.wall, Entity.wet, Entity.whoAmI, Entity.width, Main.worldSurface, and Player.ZoneGraveyard.
Referenced by AI().