Terraria: NPC.SetDefaultsFromNetId
SetDefaultsFromNetId()
void NPC.SetDefaultsFromNetId (int id, NPCSpawnParams spawnparams = default(NPCSpawnParams)) inline private
     {
         bool flag = false;
         int num = NPCID.FromNetId(id);
         SetDefaults(0);
         switch (id)
         {
         case -1:
             SetDefaults_ForNetId(num, 0.6f);
             flag = true;
             damage = 45;
             defense = 10;
             life = 90;
             knockBackResist *= 1.2f;
             value = 100f;
             break;
         case -2:
             SetDefaults_ForNetId(num, 0.9f);
             flag = true;
             damage = 45;
             defense = 20;
             life = 90;
             knockBackResist *= 1.2f;
             value = 100f;
             break;
         case -3:
             SetDefaults_ForNetId(num, 0.9f);
             flag = true;
             damage = 6;
             defense = 0;
             life = 14;
             knockBackResist *= 1.2f;
             color = new Color(0, 220, 40, 100);
             value = 3f;
             break;
         case -4:
             SetDefaults_ForNetId(num, 0.6f);
             flag = true;
             damage = 5;
             defense = 5;
             life = 150;
             knockBackResist *= 1.4f;
             color = new Color(250, 30, 90, 90);
             value = 10000f;
             rarity = 2;
             break;
         case -5:
             SetDefaults_ForNetId(num, 0.9f);
             flag = true;
             damage = 13;
             defense = 4;
             life = 30;
             knockBackResist *= 0.95f;
             alpha = 120;
             color = new Color(0, 0, 0, 50);
             value = 10f;
             break;
         case -6:
             SetDefaults_ForNetId(num, 1.05f);
             flag = true;
             damage = 15;
             defense = 4;
             life = 45;
             color = new Color(0, 0, 0, 50);
             value = 20f;
             break;
         case -7:
             SetDefaults_ForNetId(num, 1.2f);
             flag = true;
             damage = 12;
             defense = 6;
             life = 40;
             knockBackResist *= 0.9f;
             color = new Color(200, 0, 255, 150);
             value = 10f;
             break;
         case -8:
             SetDefaults_ForNetId(num, 1.025f);
             flag = true;
             damage = 12;
             defense = 4;
             life = 35;
             color = new Color(255, 30, 0, 100);
             value = 8f;
             break;
         case -9:
             SetDefaults_ForNetId(num, 1.2f);
             flag = true;
             damage = 15;
             defense = 7;
             life = 45;
             color = new Color(255, 255, 0, 100);
             value = 10f;
             break;
         case -10:
             SetDefaults_ForNetId(num, 1.1f);
             flag = true;
             damage = 18;
             defense = 6;
             life = 60;
             color = new Color(143, 215, 93, 100);
             value = 500f;
             break;
         case -11:
         {
             float num5 = 0.85f;
             if (Main.remixWorld)
             {
                 num5 *= 1.3f;
             }
             SetDefaults_ForNetId(num, spawnparams, num5);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         }
         case -12:
         {
             float num4 = 1.15f;
             if (Main.remixWorld || Main.getGoodWorld)
             {
                 num4 *= 1.3f;
             }
             SetDefaults_ForNetId(num, spawnparams, num4);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         }
         case -13:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             break;
         case -14:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((double)((float)damage * scale) * 1.1);
             life = (int)((double)((float)life * scale) * 1.1);
             value = (int)(value * scale);
             npcSlots = 2f;
             knockBackResist *= 2f - scale;
             break;
         case -15:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((double)((float)damage * scale) * 1.1);
             life = 400;
             value = (int)(value * scale);
             npcSlots = 2f;
             knockBackResist *= 2f - scale;
             height = 44;
             break;
         case -16:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -17:
             SetDefaults_ForNetId(num, spawnparams, 1.2f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -18:
             SetDefaults_ForNetId(num, spawnparams, 0.8f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -19:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -20:
             SetDefaults_ForNetId(num, 1.1f);
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -21:
             SetDefaults_ForNetId(num, spawnparams, 1.2f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -22:
         {
             float num3 = 0.85f;
             if (Main.remixWorld)
             {
                 num3 *= 1.3f;
             }
             SetDefaults_ForNetId(num, spawnparams, num3);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         }
         case -23:
         {
             float num2 = 1.15f;
             if (Main.remixWorld)
             {
                 num2 *= 1.3f;
             }
             SetDefaults_ForNetId(num, spawnparams, num2);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         }
         case -24:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -25:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -26:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -27:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -28:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -29:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -30:
             SetDefaults_ForNetId(num, spawnparams, 0.93f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -31:
             SetDefaults_ForNetId(num, spawnparams, 1.13f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -32:
             SetDefaults_ForNetId(num, spawnparams, 0.89f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -33:
             SetDefaults_ForNetId(num, spawnparams, 1.11f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -34:
             SetDefaults_ForNetId(num, spawnparams, 0.87f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -35:
             SetDefaults_ForNetId(num, spawnparams, 1.13f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -36:
             SetDefaults_ForNetId(num, spawnparams, 0.92f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -37:
             SetDefaults_ForNetId(num, spawnparams, 1.08f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -38:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -39:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -40:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -41:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -42:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -43:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -44:
             SetDefaults_ForNetId(num, spawnparams, 0.87f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -45:
             SetDefaults_ForNetId(num, spawnparams, 1.05f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -46:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -47:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -48:
             SetDefaults_ForNetId(num, spawnparams, 0.93f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -49:
             SetDefaults_ForNetId(num, spawnparams, 1.07f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -50:
             SetDefaults_ForNetId(num, spawnparams, 0.87f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -51:
             SetDefaults_ForNetId(num, spawnparams, 1.13f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -52:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -53:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -54:
             SetDefaults_ForNetId(num, spawnparams, 0.9f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -55:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -56:
             SetDefaults_ForNetId(num, spawnparams, 0.85f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -57:
             SetDefaults_ForNetId(num, spawnparams, 1.25f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -58:
             SetDefaults_ForNetId(num, spawnparams, 0.8f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -59:
             SetDefaults_ForNetId(num, spawnparams, 1.15f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -60:
             SetDefaults_ForNetId(num, spawnparams, 0.92f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -61:
             SetDefaults_ForNetId(num, spawnparams, 1.1f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -62:
             SetDefaults_ForNetId(num, spawnparams, 0.78f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -63:
             SetDefaults_ForNetId(num, spawnparams, 1.16f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -64:
             SetDefaults_ForNetId(num, spawnparams, 0.87f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         case -65:
             SetDefaults_ForNetId(num, spawnparams, 1.21f);
             flag = false;
             defense = (int)((float)defense * scale);
             damage = (int)((float)damage * scale);
             life = (int)((float)life * scale);
             value = (int)(value * scale);
             npcSlots *= scale;
             knockBackResist *= 2f - scale;
             break;
         default:
             return;
         }
         netID = id;
         lifeMax = life;
         defDamage = damage;
         defDefense = defense;
         if (flag)
         {
             ScaleStats(spawnparams.playerCountForMultiplayerDifficultyOverride, spawnparams.gameModeData, spawnparams.strengthMultiplierOverride);
             life = lifeMax;
         }
     }
References alpha, Color, color, damage, defDamage, defDefense, defense, NPCID.FromNetId(), Main.getGoodWorld, Entity.height, knockBackResist, life, lifeMax, netID, npcSlots, rarity, Main.remixWorld, scale, ScaleStats(), SetDefaults(), SetDefaults_ForNetId(), and value.
Referenced by SetDefaults().