Terraria: NPC.AI_122_PirateGhost
AI_122_PirateGhost()
void NPC.AI_122_PirateGhost () inline
     {
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             SoundEngine.PlaySound(SoundID.NPCHit6, position);
         }
         NPCAimedTarget targetData = GetTargetData();
         if (targetData.Invalid)
         {
             TargetClosest();
             targetData = GetTargetData();
         }
         if (targetData.Invalid)
         {
             velocity *= 0.9f;
             alpha = Utils.Clamp(alpha + 5, 0, 255);
             if (alpha >= 255)
             {
                 StrikeNPCNoInteraction(9999, 0f, 0);
             }
             return;
         }
         alpha = Utils.Clamp(alpha - 5, 0, 255);
         Vector2 targetPosition = Vector2.Zero.MoveTowards(targetData.Center - base.Center, 4f);
         velocity = velocity.MoveTowards(targetPosition, 2f / 15f);
         for (int i = 0; i < 200; i++)
         {
             if (Main.npc[i].active && Main.npc[i].type == type && i != whoAmI)
             {
                 Vector2 vector = Main.npc[i].Center - base.Center;
                 if (vector.Length() < 50f)
                 {
                     vector.Normalize();
                     vector *= 0.1f;
                     velocity -= vector;
                     velocity.X -= vector.X * 1f;
                 }
             }
         }
     }
References Entity.active, alpha, NPCAimedTarget.Center, Entity.Center, GetTargetData(), NPCAimedTarget.Invalid, localAI, Utils.MoveTowards(), Main.npc, SoundID.NPCHit6, SoundEngine.PlaySound(), Entity.position, StrikeNPCNoInteraction(), TargetClosest(), type, Entity.velocity, and Entity.whoAmI.
Referenced by AI().