Terraria: NPC.SpawnMechQueen
SpawnMechQueen()
static bool NPC.SpawnMechQueen (int onWhichPlayer) inline static
     {
         if (AnyNPCs(127) || AnyNPCs(134) || AnyNPCs(125) || AnyNPCs(126))
         {
             return false;
         }
         if (!Main.remixWorld && !Main.getGoodWorld)
         {
             return false;
         }
         if (Main.netMode == 1)
         {
             NetMessage.SendData(61, -1, -1, null, onWhichPlayer, -16f);
         }
         else
         {
             mechQueen = -2;
             SpawnOnPlayer(onWhichPlayer, 127);
             mechQueen = FindFirstNPC(127);
             NewNPC(GetBossSpawnSource(onWhichPlayer), (int)Main.npc[mechQueen].Center.X, (int)Main.npc[mechQueen].Center.Y, 125, 1);
             NewNPC(GetBossSpawnSource(onWhichPlayer), (int)Main.npc[mechQueen].Center.X, (int)Main.npc[mechQueen].Center.Y, 126, 1);
             int num = NewNPC(GetBossSpawnSource(onWhichPlayer), (int)Main.npc[mechQueen].Center.X, (int)Main.npc[mechQueen].Center.Y, 134, 1);
             NewNPC(GetBossSpawnSource(onWhichPlayer), (int)Main.npc[mechQueen].Center.X, (int)Main.npc[mechQueen].Center.Y, 139, 1, 0f, 0f, num, -1f);
             NewNPC(GetBossSpawnSource(onWhichPlayer), (int)Main.npc[mechQueen].Center.X, (int)Main.npc[mechQueen].Center.Y, 139, 1, 0f, 0f, num, 1f);
         }
         return true;
     }
References AnyNPCs(), Entity.Center, FindFirstNPC(), GetBossSpawnSource(), Main.getGoodWorld, mechQueen, Main.netMode, NewNPC(), Main.npc, Main.remixWorld, NetMessage.SendData(), and SpawnOnPlayer().
Referenced by MessageBuffer.GetData(), Player.ItemCheck_UseBossSpawners(), and Main.UpdateTime().