Terraria: NPC.HaveDryadDoStardewAnimation
HaveDryadDoStardewAnimation()
static void NPC.HaveDryadDoStardewAnimation () inline static
     {
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             if (!nPC.active || nPC.type != 20)
             {
                 continue;
             }
             nPC.localAI[2] = 480f;
             nPC.ai[0] = 24f;
             nPC.ai[1] = 480f;
             nPC.ai[2] = 0f;
             nPC.localAI[3] = 0f;
             nPC.netUpdate = true;
             nPC.direction = 1;
             nPC.spriteDirection = 1;
             Vector2 vector = nPC.Bottom + new Vector2(100f, 0f);
             Point p = vector.ToTileCoordinates();
             p.Y = Utils.Clamp(p.Y - 10, 10, Main.maxTilesY - 10);
             int y = p.Y;
             int num = 15;
             int num2 = p.Y + num;
             bool flag = false;
             for (int j = p.Y; j < num2; j++)
             {
                 Tile tile = Main.tile[p.X, j];
                 p.Y = j;
                 if (tile.active() && Main.tileSolid[tile.type])
                 {
                     if (j == y)
                     {
                         flag = true;
                     }
                     break;
                 }
             }
             Vector2 vector2 = new Vector2(0f, -52f);
             Vector2 vector3 = p.ToWorldCoordinates(8f, 0f);
             if (flag)
             {
                 vector3 = vector;
             }
             Projectile.NewProjectile(new EntitySource_DebugCommand(), vector3 + vector2, Vector2.Zero, 995, 0, 0f, Main.myPlayer);
             break;
         }
     }
References Entity.active, Tile.active(), ai, Entity.Bottom, Entity.direction, localAI, Main.maxTilesY, Main.myPlayer, netUpdate, Projectile.NewProjectile(), Main.npc, spriteDirection, Main.tile, Main.tileSolid, type, and Tile.type.
Referenced by MessageBuffer.GetData(), and Main.GUIChatDrawInner().