Terraria: NPC.StrikeNPCNoInteraction
StrikeNPCNoInteraction()
double NPC.StrikeNPCNoInteraction (int Damage, float knockBack, int hitDirection, bool crit = false, bool noEffect = false, bool fromNet = false) inline
     {
         if (Main.netMode == 0)
         {
             ignorePlayerInteractions++;
         }
         return StrikeNPC(Damage, knockBack, hitDirection, crit, noEffect, fromNet);
     }
References Damage, and Main.netMode.
Referenced by AI(), AI_007_TownEntities(), AI_047_GolemFist(), AI_122_PirateGhost(), BeHurtByOtherNPC(), Item.CheckLavaDeath(), Projectile.Damage(), Main.DoUpdateInWorld(), and UpdateNPC_BuffApplyDOTs().