Terraria: NPC.AI_002_FloatingEye
AI_002_FloatingEye()
void NPC.AI_002_FloatingEye () inline private
     {
         if ((type == 170 || type == 171 || type == 180) && Main.rand.Next(1000) == 0)
         {
             SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 9);
         }
         noGravity = true;
         if (!noTileCollide)
         {
             if (collideX)
             {
                 velocity.X = oldVelocity.X * -0.5f;
                 if (direction == -1 && velocity.X > 0f && velocity.X < 2f)
                 {
                     velocity.X = 2f;
                 }
                 if (direction == 1 && velocity.X < 0f && velocity.X > -2f)
                 {
                     velocity.X = -2f;
                 }
             }
             if (collideY)
             {
                 velocity.Y = oldVelocity.Y * -0.5f;
                 if (velocity.Y > 0f && velocity.Y < 1f)
                 {
                     velocity.Y = 1f;
                 }
                 if (velocity.Y < 0f && velocity.Y > -1f)
                 {
                     velocity.Y = -1f;
                 }
             }
         }
         if (DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged(type, position, target))
         {
             EncourageDespawn(10);
             directionY = -1;
             if (velocity.Y > 0f)
             {
                 direction = 1;
             }
             direction = -1;
             if (velocity.X > 0f)
             {
                 direction = 1;
             }
         }
         else
         {
             TargetClosest();
         }
         if (type == 170 || type == 171 || type == 180)
         {
             if (Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
             {
                 if (ai[1] > 0f && !Collision.SolidCollision(position, width, height))
                 {
                     ai[1] = 0f;
                     ai[0] = 0f;
                     netUpdate = true;
                 }
             }
             else if (ai[1] == 0f)
             {
                 ai[0] += 1f;
             }
             if (ai[0] >= 300f)
             {
                 ai[1] = 1f;
                 ai[0] = 0f;
                 netUpdate = true;
             }
             if (ai[1] == 0f)
             {
                 alpha = 0;
                 noTileCollide = false;
             }
             else
             {
                 wet = false;
                 alpha = 200;
                 noTileCollide = true;
             }
             rotation = velocity.Y * 0.1f * (float)direction;
             TargetClosest();
             if (direction == -1 && velocity.X > -4f && position.X > Main.player[target].position.X + (float)Main.player[target].width)
             {
                 velocity.X -= 0.08f;
                 if (velocity.X > 4f)
                 {
                     velocity.X -= 0.04f;
                 }
                 else if (velocity.X > 0f)
                 {
                     velocity.X -= 0.2f;
                 }
                 if (velocity.X < -4f)
                 {
                     velocity.X = -4f;
                 }
             }
             else if (direction == 1 && velocity.X < 4f && position.X + (float)width < Main.player[target].position.X)
             {
                 velocity.X += 0.08f;
                 if (velocity.X < -4f)
                 {
                     velocity.X += 0.04f;
                 }
                 else if (velocity.X < 0f)
                 {
                     velocity.X += 0.2f;
                 }
                 if (velocity.X > 4f)
                 {
                     velocity.X = 4f;
                 }
             }
             if (directionY == -1 && (double)velocity.Y > -2.5 && position.Y > Main.player[target].position.Y + (float)Main.player[target].height)
             {
                 velocity.Y -= 0.1f;
                 if ((double)velocity.Y > 2.5)
                 {
                     velocity.Y -= 0.05f;
                 }
                 else if (velocity.Y > 0f)
                 {
                     velocity.Y -= 0.15f;
                 }
                 if ((double)velocity.Y < -2.5)
                 {
                     velocity.Y = -2.5f;
                 }
             }
             else if (directionY == 1 && (double)velocity.Y < 2.5 && position.Y + (float)height < Main.player[target].position.Y)
             {
                 velocity.Y += 0.1f;
                 if ((double)velocity.Y < -2.5)
                 {
                     velocity.Y += 0.05f;
                 }
                 else if (velocity.Y < 0f)
                 {
                     velocity.Y += 0.15f;
                 }
                 if ((double)velocity.Y > 2.5)
                 {
                     velocity.Y = 2.5f;
                 }
             }
         }
         else if (type == 116)
         {
             TargetClosest();
             Lighting.AddLight((int)(position.X + (float)(width / 2)) / 16, (int)(position.Y + (float)(height / 2)) / 16, 0.3f, 0.2f, 0.1f);
             if (direction == -1 && velocity.X > -6f)
             {
                 velocity.X -= 0.1f;
                 if (velocity.X > 6f)
                 {
                     velocity.X -= 0.1f;
                 }
                 else if (velocity.X > 0f)
                 {
                     velocity.X -= 0.2f;
                 }
                 if (velocity.X < -6f)
                 {
                     velocity.X = -6f;
                 }
             }
             else if (direction == 1 && velocity.X < 6f)
             {
                 velocity.X += 0.1f;
                 if (velocity.X < -6f)
                 {
                     velocity.X += 0.1f;
                 }
                 else if (velocity.X < 0f)
                 {
                     velocity.X += 0.2f;
                 }
                 if (velocity.X > 6f)
                 {
                     velocity.X = 6f;
                 }
             }
             if (directionY == -1 && (double)velocity.Y > -2.5)
             {
                 velocity.Y -= 0.04f;
                 if ((double)velocity.Y > 2.5)
                 {
                     velocity.Y -= 0.05f;
                 }
                 else if (velocity.Y > 0f)
                 {
                     velocity.Y -= 0.15f;
                 }
                 if ((double)velocity.Y < -2.5)
                 {
                     velocity.Y = -2.5f;
                 }
             }
             else if (directionY == 1 && (double)velocity.Y < 1.5)
             {
                 velocity.Y += 0.04f;
                 if ((double)velocity.Y < -2.5)
                 {
                     velocity.Y += 0.05f;
                 }
                 else if (velocity.Y < 0f)
                 {
                     velocity.Y += 0.15f;
                 }
                 if ((double)velocity.Y > 2.5)
                 {
                     velocity.Y = 2.5f;
                 }
             }
             if (Main.rand.Next(40) == 0)
             {
                 position += netOffset;
                 int num = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), 5, velocity.X, 2f);
                 Main.dust[num].velocity.X *= 0.5f;
                 Main.dust[num].velocity.Y *= 0.1f;
                 position -= netOffset;
             }
         }
         else if (type == 133)
         {
             if ((double)life < (double)lifeMax * 0.5)
             {
                 if (direction == -1 && velocity.X > -6f)
                 {
                     velocity.X -= 0.1f;
                     if (velocity.X > 6f)
                     {
                         velocity.X -= 0.1f;
                     }
                     else if (velocity.X > 0f)
                     {
                         velocity.X += 0.05f;
                     }
                     if (velocity.X < -6f)
                     {
                         velocity.X = -6f;
                     }
                 }
                 else if (direction == 1 && velocity.X < 6f)
                 {
                     velocity.X += 0.1f;
                     if (velocity.X < -6f)
                     {
                         velocity.X += 0.1f;
                     }
                     else if (velocity.X < 0f)
                     {
                         velocity.X -= 0.05f;
                     }
                     if (velocity.X > 6f)
                     {
                         velocity.X = 6f;
                     }
                 }
                 if (directionY == -1 && velocity.Y > -4f)
                 {
                     velocity.Y -= 0.1f;
                     if (velocity.Y > 4f)
                     {
                         velocity.Y -= 0.1f;
                     }
                     else if (velocity.Y > 0f)
                     {
                         velocity.Y += 0.05f;
                     }
                     if (velocity.Y < -4f)
                     {
                         velocity.Y = -4f;
                     }
                 }
                 else if (directionY == 1 && velocity.Y < 4f)
                 {
                     velocity.Y += 0.1f;
                     if (velocity.Y < -4f)
                     {
                         velocity.Y += 0.1f;
                     }
                     else if (velocity.Y < 0f)
                     {
                         velocity.Y -= 0.05f;
                     }
                     if (velocity.Y > 4f)
                     {
                         velocity.Y = 4f;
                     }
                 }
             }
             else
             {
                 if (direction == -1 && velocity.X > -4f)
                 {
                     velocity.X -= 0.1f;
                     if (velocity.X > 4f)
                     {
                         velocity.X -= 0.1f;
                     }
                     else if (velocity.X > 0f)
                     {
                         velocity.X += 0.05f;
                     }
                     if (velocity.X < -4f)
                     {
                         velocity.X = -4f;
                     }
                 }
                 else if (direction == 1 && velocity.X < 4f)
                 {
                     velocity.X += 0.1f;
                     if (velocity.X < -4f)
                     {
                         velocity.X += 0.1f;
                     }
                     else if (velocity.X < 0f)
                     {
                         velocity.X -= 0.05f;
                     }
                     if (velocity.X > 4f)
                     {
                         velocity.X = 4f;
                     }
                 }
                 if (directionY == -1 && (double)velocity.Y > -1.5)
                 {
                     velocity.Y -= 0.04f;
                     if ((double)velocity.Y > 1.5)
                     {
                         velocity.Y -= 0.05f;
                     }
                     else if (velocity.Y > 0f)
                     {
                         velocity.Y += 0.03f;
                     }
                     if ((double)velocity.Y < -1.5)
                     {
                         velocity.Y = -1.5f;
                     }
                 }
                 else if (directionY == 1 && (double)velocity.Y < 1.5)
                 {
                     velocity.Y += 0.04f;
                     if ((double)velocity.Y < -1.5)
                     {
                         velocity.Y += 0.05f;
                     }
                     else if (velocity.Y < 0f)
                     {
                         velocity.Y -= 0.03f;
                     }
                     if ((double)velocity.Y > 1.5)
                     {
                         velocity.Y = 1.5f;
                     }
                 }
             }
         }
         else
         {
             float num2 = 4f;
             float num3 = 1.5f;
             num2 *= 1f + (1f - scale);
             num3 *= 1f + (1f - scale);
             if (direction == -1 && velocity.X > 0f - num2)
             {
                 velocity.X -= 0.1f;
                 if (velocity.X > num2)
                 {
                     velocity.X -= 0.1f;
                 }
                 else if (velocity.X > 0f)
                 {
                     velocity.X += 0.05f;
                 }
                 if (velocity.X < 0f - num2)
                 {
                     velocity.X = 0f - num2;
                 }
             }
             else if (direction == 1 && velocity.X < num2)
             {
                 velocity.X += 0.1f;
                 if (velocity.X < 0f - num2)
                 {
                     velocity.X += 0.1f;
                 }
                 else if (velocity.X < 0f)
                 {
                     velocity.X -= 0.05f;
                 }
                 if (velocity.X > num2)
                 {
                     velocity.X = num2;
                 }
             }
             if (directionY == -1 && velocity.Y > 0f - num3)
             {
                 velocity.Y -= 0.04f;
                 if (velocity.Y > num3)
                 {
                     velocity.Y -= 0.05f;
                 }
                 else if (velocity.Y > 0f)
                 {
                     velocity.Y += 0.03f;
                 }
                 if (velocity.Y < 0f - num3)
                 {
                     velocity.Y = 0f - num3;
                 }
             }
             else if (directionY == 1 && velocity.Y < num3)
             {
                 velocity.Y += 0.04f;
                 if (velocity.Y < 0f - num3)
                 {
                     velocity.Y += 0.05f;
                 }
                 else if (velocity.Y < 0f)
                 {
                     velocity.Y -= 0.03f;
                 }
                 if (velocity.Y > num3)
                 {
                     velocity.Y = num3;
                 }
             }
         }
         if ((type == 2 || type == 133 || type == 190 || type == 191 || type == 192 || type == 193 || type == 194) && Main.rand.Next(40) == 0)
         {
             position += netOffset;
             int num4 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), 5, velocity.X, 2f);
             Main.dust[num4].velocity.X *= 0.5f;
             Main.dust[num4].velocity.Y *= 0.1f;
             position -= netOffset;
         }
         if (wet && type != 170 && type != 171 && type != 172)
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y *= 0.95f;
             }
             velocity.Y -= 0.5f;
             if (velocity.Y < -4f)
             {
                 velocity.Y = -4f;
             }
             TargetClosest();
         }
     }
References Lighting.AddLight(), ai, alpha, Collision.CanHit(), collideX, collideY, DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged(), Entity.direction, directionY, Main.dust, EncourageDespawn(), Entity.height, life, lifeMax, netOffset, netUpdate, Dust.NewDust(), UnifiedRandom.Next(), noGravity, noTileCollide, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, rotation, scale, Collision.SolidCollision(), target, TargetClosest(), type, Dust.velocity, Entity.velocity, Entity.wet, and Entity.width.
Referenced by AI().