Terraria: NPC.ReflectProjectile
ReflectProjectile()
void NPC.ReflectProjectile (Projectile proj) inline
     {
         SoundEngine.PlaySound(SoundID.Item150, proj.position);
         for (int i = 0; i < 3; i++)
         {
             int num = Dust.NewDust(proj.position, proj.width, proj.height, 31);
             Main.dust[num].velocity *= 0.3f;
         }
         proj.reflected = true;
         proj.hostile = true;
         proj.friendly = false;
         Vector2 vector = Main.player[proj.owner].Center - proj.Center;
         vector.Normalize();
         vector *= proj.oldVelocity.Length();
         proj.velocity = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
         proj.velocity.Normalize();
         proj.velocity *= vector.Length();
         proj.velocity += vector * 20f;
         proj.velocity.Normalize();
         proj.velocity *= vector.Length();
         proj.damage /= 2;
         proj.damage /= 2;
         proj.penetrate = 1;
     }
References Entity.Center, Projectile.damage, Main.dust, Projectile.friendly, Entity.height, Projectile.hostile, SoundID.Item150, Dust.NewDust(), UnifiedRandom.Next(), Entity.oldVelocity, Projectile.owner, Projectile.penetrate, Main.player, SoundEngine.PlaySound(), Entity.position, Main.rand, Projectile.reflected, Dust.velocity, Entity.velocity, and Entity.width.
Referenced by Projectile.Damage(), and ReflectProjectiles().