Terraria: NPC.AI_123_Deerclops_ShootRubbleUp
AI_123_Deerclops_ShootRubbleUp()
void NPC.AI_123_Deerclops_ShootRubbleUp (ref NPCAimedTarget targetData, ref Point sourceTileCoords, int howMany, int distancedByThisManyTiles, float upBiasPerSpike, int whichOne) inline private
     {
         int num = 18;
         int num2 = whichOne * distancedByThisManyTiles;
         for (int i = 0; i < 35; i++)
         {
             int num3 = sourceTileCoords.X + num2 * direction;
             int num4 = sourceTileCoords.Y + i;
             if (WorldGen.SolidTile(num3, num4))
             {
                 Vector2 vector = targetData.Center + new Vector2(num2 * direction * 20, (0f - upBiasPerSpike) * (float)howMany + (float)num2 * upBiasPerSpike / (float)distancedByThisManyTiles);
                 Vector2 vector2 = new Vector2(num3 * 16 + 8, num4 * 16 + 8);
                 Vector2 vector3 = (vector - vector2).SafeNormalize(-Vector2.UnitY);
                 vector3 = new Vector2(0f, -1f).RotatedBy((float)(whichOne * direction) * 0.7f * ((float)Math.PI / 4f / (float)howMany));
                 int num5 = Main.rand.Next(Main.projFrames[962] * 4);
                 num5 = 6 + Main.rand.Next(6);
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), new Vector2(num3 * 16 + 8, num4 * 16 - 8), vector3 * (8f + Main.rand.NextFloat() * 8f), 962, num, 0f, Main.myPlayer, 0f, num5);
                 break;
             }
         }
     }
References Entity.direction, GetSpawnSource_ForProjectile(), Main.myPlayer, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.projFrames, Main.rand, and WorldGen.SolidTile().
Referenced by AI_123_Deerclops().