Terraria: NPC.BloodNautilus_CallForHelp
BloodNautilus_CallForHelp()
void NPC.BloodNautilus_CallForHelp () inline private
     {
         if (Main.netMode == 1 || !Main.player[target].active || Main.player[target].dead || Distance(Main.player[target].Center) > 2000f || CountNPCS(619) >= 3)
         {
             return;
         }
         Point point = base.Center.ToTileCoordinates();
         Point point2 = point;
         int num = 20;
         int num2 = 3;
         int num3 = 8;
         int num4 = 2;
         int num5 = 0;
         bool flag = false;
         while (!flag && num5 < 100)
         {
             num5++;
             int num6 = Main.rand.Next(point2.X - num, point2.X + num + 1);
             int num7 = Main.rand.Next(point2.Y - num, point2.Y + num + 1);
             if ((num7 < point2.Y - num3 || num7 > point2.Y + num3 || num6 < point2.X - num3 || num6 > point2.X + num3) && (num7 < point.Y - num2 || num7 > point.Y + num2 || num6 < point.X - num2 || num6 > point.X + num2) && !Main.tile[num6, num7].nactive())
             {
                 bool flag2 = true;
                 if (flag2 && Main.tile[num6, num7].lava())
                 {
                     flag2 = false;
                 }
                 if (flag2 && Collision.SolidTiles(num6 - num4, num6 + num4, num7 - num4, num7 + num4))
                 {
                     flag2 = false;
                 }
                 if (flag2 && !Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                 {
                     flag2 = false;
                 }
                 if (flag2)
                 {
                     Projectile.NewProjectile(GetSpawnSource_ForProjectile(), num6 * 16 + 8, num7 * 16 + 8, 0f, 0f, 813, 0, 0f, Main.myPlayer);
                     flag = true;
                     break;
                 }
             }
         }
     }
References Entity.active, Collision.CanHitLine(), Entity.Center, CountNPCS(), Player.dead, Entity.Distance(), GetSpawnSource_ForProjectile(), Tile.lava(), Main.myPlayer, Tile.nactive(), Main.netMode, Projectile.NewProjectile(), UnifiedRandom.Next(), Main.player, Main.rand, Collision.SolidTiles(), target, and Main.tile.
Referenced by AI_117_BloodNautilus().