Terraria: NPC.AI_007_FindGoodRestingSpot
AI_007_FindGoodRestingSpot()
void NPC.AI_007_FindGoodRestingSpot (int myTileX, int myTileY, out int floorX, out int floorY) inline private
     {
         floorX = homeTileX;
         floorY = homeTileY;
         if (floorX == -1 || floorY == -1)
         {
             return;
         }
         while (!WorldGen.SolidOrSlopedTile(floorX, floorY) && floorY < Main.maxTilesY - 20)
         {
             floorY++;
         }
         if (Main.dayTime || (ai[0] == 5f && Math.Abs(myTileX - floorX) < 7 && Math.Abs(myTileY - floorY) < 7))
         {
             return;
         }
         Point point = new Point(floorX, floorY);
         Point point2 = new Point(-1, -1);
         int num = -1;
         if (type == 638 || type == 656 || NPCID.Sets.IsTownSlime[type] || ai[0] == 5f)
         {
             return;
         }
         int num2 = 7;
         int num3 = 6;
         int num4 = 2;
         int num5 = 1;
         int num6 = 2;
         for (int i = point.X - num2; i <= point.X + num2; i += num5)
         {
             for (int num7 = point.Y + num4; num7 >= point.Y - num3; num7 -= num6)
             {
                 Tile tile = Main.tile[i, num7];
                 if (tile != null && tile.active() && TileID.Sets.CanBeSatOnForNPCs[tile.type] && (tile.frameY % 40 != 0 || num7 + 1 <= point.Y + num4))
                 {
                     int num8 = Math.Abs(i - point.X) + Math.Abs(num7 - point.Y);
                     if (num == -1 || num8 < num)
                     {
                         num = num8;
                         point2.X = i;
                         point2.Y = num7;
                     }
                 }
             }
         }
         if (num == -1)
         {
             return;
         }
         Tile tile2 = Main.tile[point2.X, point2.Y];
         if (tile2.type == 497 || tile2.type == 15)
         {
             if (tile2.frameY % 40 != 0)
             {
                 point2.Y--;
             }
             point2.Y += 2;
         }
         for (int j = 0; j < 200; j++)
         {
             if (Main.npc[j].active && Main.npc[j].aiStyle == 7 && Main.npc[j].townNPC && Main.npc[j].ai[0] == 5f && (Main.npc[j].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point2)
             {
                 return;
             }
         }
         floorX = point2.X;
         floorY = point2.Y;
     }
References Entity.active, Tile.active(), ai, aiStyle, Entity.Bottom, TileID.Sets.CanBeSatOnForNPCs, Main.dayTime, Tile.frameY, homeTileX, homeTileY, NPCID.Sets.IsTownSlime, Main.maxTilesY, Main.npc, WorldGen.SolidOrSlopedTile(), Main.tile, townNPC, type, and Tile.type.
Referenced by AI_007_TownEntities().