Terraria: NPC.CheckProgressFrostMoon
CheckProgressFrostMoon()
void NPC.CheckProgressFrostMoon () inline private
     {
         if (!Main.snowMoon)
         {
             return;
         }
         int num = 0;
         NetworkText networkText = NetworkText.Empty;
         num = MoonEventRequiredPointsPerWaveLookup[waveNumber];
         switch (waveNumber)
         {
         case 1:
             networkText = Lang.GetInvasionWaveText(2, 338, 350);
             break;
         case 2:
             networkText = Lang.GetInvasionWaveText(3, 338, 350, 342, 348);
             break;
         case 3:
             networkText = Lang.GetInvasionWaveText(4, 344, 338, 350, 342);
             break;
         case 4:
             networkText = Lang.GetInvasionWaveText(5, 344, 338, 350, 348);
             break;
         case 5:
             networkText = Lang.GetInvasionWaveText(6, 344, 350, 348, 347);
             break;
         case 6:
             networkText = Lang.GetInvasionWaveText(7, 346, 342, 350, 338);
             break;
         case 7:
             networkText = Lang.GetInvasionWaveText(8, 346, 347, 350, 348, 351);
             break;
         case 8:
             networkText = Lang.GetInvasionWaveText(9, 346, 344, 348, 347, 342);
             break;
         case 9:
             networkText = Lang.GetInvasionWaveText(10, 346, 344, 351, 338, 347);
             break;
         case 10:
             networkText = Lang.GetInvasionWaveText(11, 345, 352, 338, 342);
             break;
         case 11:
             networkText = Lang.GetInvasionWaveText(12, 345, 344, 342, 343, 338);
             break;
         case 12:
             networkText = Lang.GetInvasionWaveText(13, 345, 346, 342, 352, 343, 347);
             break;
         case 13:
             networkText = Lang.GetInvasionWaveText(14, 345, 346, 344, 343, 351);
             break;
         case 14:
             networkText = Lang.GetInvasionWaveText(15, 345, 346, 344, 343, 347);
             break;
         case 15:
             networkText = Lang.GetInvasionWaveText(16, 345, 346, 344, 343, 352);
             break;
         case 16:
             networkText = Lang.GetInvasionWaveText(17, 345, 346, 344, 343, 351, 347);
             break;
         case 17:
             networkText = Lang.GetInvasionWaveText(18, 345, 346, 344, 343, 348, 351);
             break;
         case 18:
             networkText = Lang.GetInvasionWaveText(19, 345, 346, 344, 343);
             break;
         case 19:
             networkText = Lang.GetInvasionWaveText(-1, 345, 346, 344);
             break;
         }
         float num2 = 0f;
         switch (type)
         {
         case 338:
         case 339:
         case 340:
             num2 = 1f;
             break;
         case 341:
             num2 = 20f;
             break;
         case 342:
             num2 = 2f;
             break;
         case 343:
             num2 = 18f;
             break;
         case 344:
             num2 = 50f;
             break;
         case 345:
             num2 = 150f;
             break;
         case 346:
             num2 = 100f;
             break;
         case 347:
             num2 = 8f;
             break;
         case 348:
         case 349:
             num2 = 4f;
             break;
         case 350:
             num2 = 3f;
             break;
         case 351:
             num2 = 10f;
             break;
         case 352:
             num2 = 5f;
             break;
         }
         num2 *= GetMoonEventPointScalar();
         float num3 = waveKills;
         waveKills += num2;
         totalInvasionPoints += num2;
         if (waveKills >= (float)num && num != 0)
         {
             waveKills = 0f;
             waveNumber++;
             num = MoonEventRequiredPointsPerWaveLookup[waveNumber];
             if (networkText != NetworkText.Empty)
             {
                 if (Main.netMode == 0)
                 {
                     Main.NewText(networkText.ToString(), 175, 75);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(networkText, new Color(175, 75, 255));
                 }
                 if (waveNumber == 15)
                 {
                     AchievementsHelper.NotifyProgressionEvent(14);
                 }
             }
         }
         if (waveKills != num3 && num2 != 0f)
         {
             if (Main.netMode != 1)
             {
                 Main.ReportInvasionProgress((int)waveKills, num, 1, waveNumber);
             }
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, 1f, waveNumber);
             }
         }
     }
References ChatHelper.BroadcastChatMessage(), Color, NetworkText.Empty, Lang.GetInvasionWaveText(), GetMoonEventPointScalar(), Main.invasionProgress, Main.invasionProgressMax, MoonEventRequiredPointsPerWaveLookup, Main.netMode, Main.NewText(), AchievementsHelper.NotifyProgressionEvent(), Main.ReportInvasionProgress(), NetMessage.SendData(), Main.snowMoon, NetworkText.ToString(), totalInvasionPoints, type, waveKills, and waveNumber.
Referenced by checkDead().