Terraria: NPC.FairyEffects
FairyEffects()
static void NPC.FairyEffects (Vector2 Position, int type) inline static
     {
         Color value = Color.HotPink;
         Color value2 = Color.LightPink;
         int num = 4;
         if (type == 1)
         {
             value = Color.LimeGreen;
             value2 = Color.LightSeaGreen;
         }
         if (type == 2)
         {
             value = Color.RoyalBlue;
             value2 = Color.LightBlue;
         }
         for (int i = 0; i < 40; i++)
         {
             Dust dust = Dust.NewDustDirect(Position - new Vector2(num) * 0.5f, num + 4, num + 4, 278, 0f, 0f, 200, Color.Lerp(value, value2, Main.rand.NextFloat()), 0.65f);
             dust.velocity *= 1.5f;
             if (i >= 30)
             {
                 dust.velocity *= 3.5f;
             }
             else if (i >= 20)
             {
                 dust.velocity *= 2f;
             }
             dust.fadeIn = (float)Main.rand.Next(0, 17) * 0.1f;
             dust.noGravity = true;
         }
         SoundEngine.PlaySound(SoundID.Item4, (int)Position.X, (int)Position.Y);
     }
References Color, Dust.fadeIn, SoundID.Item4, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlaySound(), Main.rand, type, value, and Dust.velocity.
Referenced by AI_112_FairyCritter(), and MessageBuffer.GetData().