Terraria: NPC.AnyDanger
AnyDanger()
static bool NPC.AnyDanger (bool quickBossNPCCheck = false, bool ignorePillarsAndMoonlordCountdown = false) inline static
     {
         bool flag = false;
         if (!ignorePillarsAndMoonlordCountdown && MoonLordCountdown > 0)
         {
             flag = true;
         }
         if (Main.invasionType > 0)
         {
             flag = true;
         }
         if (Main.snowMoon || Main.pumpkinMoon || DD2Event.Ongoing)
         {
             flag = true;
         }
         if (!flag)
         {
             if (quickBossNPCCheck)
             {
                 flag |= Main.CurrentFrameFlags.AnyActiveBossNPC;
             }
             else
             {
                 for (int i = 0; i < 200; i++)
                 {
                     if (!Main.npc[i].active || (!Main.npc[i].boss && !NPCID.Sets.DangerThatPreventsOtherDangers[Main.npc[i].type]))
                     {
                         continue;
                     }
                     if (ignorePillarsAndMoonlordCountdown)
                     {
                         switch (Main.npc[i].type)
{
                         case 422:
                         case 493:
                         case 507:
                         case 517:
                             continue;
                         }
                     }
                     flag = true;
                 }
             }
         }
         return flag;
     }
References Entity.active, Main.CurrentFrameFlags.AnyActiveBossNPC, boss, NPCID.Sets.DangerThatPreventsOtherDangers, Main.invasionType, Main.npc, DD2Event.Ongoing, Main.pumpkinMoon, Main.snowMoon, and type.
Referenced by PlayerSleepingHelper.DoesPlayerHaveReasonToActUpInBed(), PlayerDrawLayers.DrawPlayer_Head_GetTVScreen(), MessageBuffer.GetData(), TeleportPylonsSystem.HandleTeleportRequest(), Player.ItemCheck_CheckCanUse(), Player.ItemCheck_UseEventItems(), CultistRitual.UpdateTime(), and Main.UpdateTime().