Terraria: NPC.DoDeathEvents
DoDeathEvents()
void NPC.DoDeathEvents (Player closestPlayer) inline private
     {
         DoDeathEvents_AdvanceSlimeRain(closestPlayer);
         DoDeathEvents_SummonDungeonSpirit(closestPlayer);
         if (Main.remixWorld && !downedSlimeKing && AnyInteractions() && Main.AnyPlayerReadyToFightKingSlime() && type == 1 && !AnyNPCs(50) && Main.rand.Next(200) == 0)
         {
             SpawnOnPlayer(closestPlayer.whoAmI, 50);
         }
         switch (type)
         {
         case 216:
             SpawnBoss((int)position.X, (int)position.Y, 662, target);
             break;
         case 327:
             if (Main.pumpkinMoon)
             {
                 SetEventFlagCleared(ref downedHalloweenKing, 5);
             }
             break;
         case 325:
             if (Main.pumpkinMoon)
             {
                 SetEventFlagCleared(ref downedHalloweenTree, 4);
             }
             break;
         case 344:
             if (Main.snowMoon)
             {
                 SetEventFlagCleared(ref downedChristmasTree, 21);
             }
             break;
         case 345:
             if (Main.snowMoon)
             {
                 SetEventFlagCleared(ref downedChristmasIceQueen, 20);
             }
             break;
         case 346:
             if (Main.snowMoon)
             {
                 SetEventFlagCleared(ref downedChristmasSantank, 22);
             }
             break;
         case 552:
         case 553:
         case 554:
             if (DD2Event.Ongoing)
             {
                 DD2Event.AnnounceGoblinDeath(this);
                 if (DD2Event.ShouldDropCrystals())
                 {
                     Item.NewItem(GetItemSource_Loot(), position, base.Size, 3822);
                 }
             }
             break;
         case 555:
         case 556:
         case 557:
         case 558:
         case 559:
         case 560:
         case 561:
         case 562:
         case 563:
         case 564:
         case 565:
         case 568:
         case 569:
         case 570:
         case 571:
         case 572:
         case 573:
         case 574:
         case 575:
         case 576:
         case 577:
         case 578:
             if (DD2Event.ShouldDropCrystals())
             {
                 Item.NewItem(GetItemSource_Loot(), position, base.Size, 3822);
             }
             break;
         case 412:
         case 413:
         case 414:
         case 415:
         case 416:
         case 417:
         case 418:
         case 419:
         case 518:
             if (ShieldStrengthTowerSolar > 0)
             {
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, FindFirstNPC(517));
             }
             break;
         case 425:
         case 426:
         case 427:
         case 429:
             if (ShieldStrengthTowerVortex > 0)
             {
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, FindFirstNPC(422));
             }
             break;
         case 420:
         case 421:
         case 423:
         case 424:
             if (ShieldStrengthTowerNebula > 0)
             {
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, FindFirstNPC(507));
             }
             break;
         case 402:
         case 405:
         case 407:
         case 409:
         case 411:
             if (ShieldStrengthTowerStardust > 0)
             {
                 Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, FindFirstNPC(493));
             }
             break;
         case 517:
             downedTowerSolar = true;
             TowerActiveSolar = false;
             WorldGen.UpdateLunarApocalypse();
             WorldGen.MessageLunarApocalypse();
             break;
         case 422:
             downedTowerVortex = true;
             TowerActiveVortex = false;
             WorldGen.UpdateLunarApocalypse();
             WorldGen.MessageLunarApocalypse();
             break;
         case 507:
             downedTowerNebula = true;
             TowerActiveNebula = false;
             WorldGen.UpdateLunarApocalypse();
             WorldGen.MessageLunarApocalypse();
             break;
         case 493:
             downedTowerStardust = true;
             TowerActiveStardust = false;
             WorldGen.UpdateLunarApocalypse();
             WorldGen.MessageLunarApocalypse();
             break;
         case 245:
             SetEventFlagCleared(ref downedGolemBoss, 6);
             break;
         case 370:
             SetEventFlagCleared(ref downedFishron, 7);
             break;
         case 636:
             SetEventFlagCleared(ref downedEmpressOfLight, 23);
             break;
         case 668:
             SetEventFlagCleared(ref downedDeerclops, 25);
             break;
         case 657:
             SetEventFlagCleared(ref downedQueenSlime, 24);
             break;
         case 22:
             if (Collision.LavaCollision(position, width, height))
             {
                 SpawnWOF(position);
             }
             break;
         case 614:
         {
             int num2 = 175;
             if (SpawnedFromStatue)
             {
                 num2 = 0;
             }
             Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 281, num2, 0f, Main.myPlayer, -2f, releaseOwner + 1);
             break;
         }
         case 109:
             if (!downedClown)
             {
                 downedClown = true;
                 if (Main.netMode == 2)
                 {
                     NetMessage.SendData(7);
                 }
             }
             break;
         case 222:
             SetEventFlagCleared(ref downedQueenBee, 8);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(7);
             }
             break;
         case 439:
             SetEventFlagCleared(ref downedAncientCultist, 9);
             WorldGen.TriggerLunarApocalypse();
             break;
         case 398:
             SetEventFlagCleared(ref downedMoonlord, 10);
             LunarApocalypseIsUp = false;
             break;
         case 50:
             if (Main.slimeRain)
             {
                 Main.StopSlimeRain();
                 AchievementsHelper.NotifyProgressionEvent(16);
             }
             if (Main.netMode != 1 && !unlockedSlimeBlueSpawn)
             {
                 unlockedSlimeBlueSpawn = true;
                 ViolentlySpawnNerdySlime();
             }
             SetEventFlagCleared(ref downedSlimeKing, 11);
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(7);
             }
             break;
         case 125:
         case 126:
             if (boss)
             {
                 SetEventFlagCleared(ref downedMechBoss2, 17);
                 downedMechBossAny = true;
             }
             break;
         case 262:
         {
             bool num3 = downedPlantBoss;
             SetEventFlagCleared(ref downedPlantBoss, 12);
             if (!num3)
             {
                 if (Main.netMode == 0)
                 {
                     Main.NewText(Lang.misc[33].Value, 50, byte.MaxValue, 130);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[33].Key), new Color(50, 255, 130));
                 }
             }
             break;
         }
         case 4:
             SetEventFlagCleared(ref downedBoss1, 13);
             break;
         case 13:
         case 14:
         case 15:
         case 266:
             if (boss)
             {
                 if (!downedBoss2 || Main.rand.Next(2) == 0)
                 {
                     WorldGen.spawnMeteor = true;
                 }
                 SetEventFlagCleared(ref downedBoss2, 14);
             }
             break;
         case 35:
             if (boss)
             {
                 SetEventFlagCleared(ref downedBoss3, 15);
             }
             break;
         case 127:
             if (boss)
             {
                 SetEventFlagCleared(ref downedMechBoss3, 18);
                 downedMechBossAny = true;
             }
             break;
         case 134:
             if (boss)
             {
                 SetEventFlagCleared(ref downedMechBoss1, 16);
                 downedMechBossAny = true;
             }
             break;
         case 113:
         {
             if (Main.netMode == 1)
             {
                 break;
             }
             CreateBrickBoxForWallOfFlesh();
             bool eventFlag = Main.hardMode;
             WorldGen.StartHardmode();
             if (downedMechBoss1 && downedMechBoss2 && downedMechBoss3 && !eventFlag)
             {
                 if (Main.netMode == 0)
                 {
                     Main.NewText(Lang.misc[32].Value, 50, byte.MaxValue, 130);
                 }
                 else if (Main.netMode == 2)
                 {
                     ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[32].Key), new Color(50, 255, 130));
                 }
             }
             SetEventFlagCleared(ref eventFlag, 19);
             break;
         }
         case 661:
             if (Main.netMode != 1 && GetWereThereAnyInteractions())
             {
                 int num = 636;
                 if (!AnyNPCs(num))
                 {
                     Vector2 vector = base.Center + new Vector2(0f, -200f) + Main.rand.NextVector2Circular(50f, 50f);
                     SpawnBoss((int)vector.X, (int)vector.Y, num, closestPlayer.whoAmI);
                 }
             }
             break;
         }
         if (boss)
         {
             DoDeathEvents_DropBossPotionsAndHearts();
             DoDeathEvents_CelebrateBossDeath();
             if (Main.netMode == 2)
             {
                 NetMessage.SendData(7);
             }
         }
     }
References DD2Event.AnnounceGoblinDeath(), AnyInteractions(), AnyNPCs(), Main.AnyPlayerReadyToFightKingSlime(), boss, ChatHelper.BroadcastChatMessage(), Color, CreateBrickBoxForWallOfFlesh(), DoDeathEvents_AdvanceSlimeRain(), DoDeathEvents_CelebrateBossDeath(), DoDeathEvents_DropBossPotionsAndHearts(), DoDeathEvents_SummonDungeonSpirit(), downedAncientCultist, downedBoss1, downedBoss2, downedBoss3, downedChristmasIceQueen, downedChristmasSantank, downedChristmasTree, downedClown, downedDeerclops, downedEmpressOfLight, downedFishron, downedGolemBoss, downedHalloweenKing, downedHalloweenTree, downedMechBoss1, downedMechBoss2, downedMechBoss3, downedMechBossAny, downedMoonlord, downedPlantBoss, downedQueenBee, downedQueenSlime, downedSlimeKing, downedTowerNebula, downedTowerSolar, downedTowerStardust, downedTowerVortex, FindFirstNPC(), NetworkText.FromKey(), GetItemSource_Loot(), GetSpawnSource_ForProjectile(), GetWereThereAnyInteractions(), Main.hardMode, Entity.height, LocalizedText.Key, Collision.LavaCollision(), LunarApocalypseIsUp, WorldGen.MessageLunarApocalypse(), Lang.misc, Main.myPlayer, Main.netMode, Item.NewItem(), Projectile.NewProjectile(), Main.NewText(), UnifiedRandom.Next(), AchievementsHelper.NotifyProgressionEvent(), DD2Event.Ongoing, Entity.position, Main.pumpkinMoon, Main.rand, releaseOwner, Main.remixWorld, NetMessage.SendData(), SetEventFlagCleared(), ShieldStrengthTowerNebula, ShieldStrengthTowerSolar, ShieldStrengthTowerStardust, ShieldStrengthTowerVortex, DD2Event.ShouldDropCrystals(), Main.slimeRain, Main.snowMoon, SpawnBoss(), SpawnedFromStatue, WorldGen.spawnMeteor, SpawnOnPlayer(), SpawnWOF(), WorldGen.StartHardmode(), Main.StopSlimeRain(), target, TowerActiveNebula, TowerActiveSolar, TowerActiveStardust, TowerActiveVortex, WorldGen.TriggerLunarApocalypse(), type, unlockedSlimeBlueSpawn, WorldGen.UpdateLunarApocalypse(), LocalizedText.Value, ViolentlySpawnNerdySlime(), Entity.whoAmI, and Entity.width.
Referenced by NPCLoot().