Terraria: NPC.RequestBuffRemoval
RequestBuffRemoval()
void NPC.RequestBuffRemoval (int buffTypeToRemove) inline
     {
         if (buffTypeToRemove < 0 || buffTypeToRemove >= BuffID.Count || !BuffID.Sets.CanBeRemovedByNetMessage[buffTypeToRemove])
         {
             return;
         }
         int num = FindBuffIndex(buffTypeToRemove);
         if (num != -1)
         {
             DelBuff(num);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(137, -1, -1, null, whoAmI, buffTypeToRemove);
             }
         }
     }
References BuffID.Sets.CanBeRemovedByNetMessage, BuffID.Count, Main.netMode, and NetMessage.SendData().
Referenced by Projectile.Damage(), and MessageBuffer.GetData().