Terraria: NPC.GetFairyTreasureCoords
GetFairyTreasureCoords()
bool NPC.GetFairyTreasureCoords (out Point treasureCoords) inline private
     {
         treasureCoords = default(Point);
         Point point = base.Center.ToTileCoordinates();
         Rectangle value = new Rectangle(point.X, point.Y, 1, 1);
         value.Inflate(75, 50);
         int num = 40;
         Rectangle value2 = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
         value2.Inflate(-num, -num);
         value = Rectangle.Intersect(value, value2);
         int num2 = -1;
         float num3 = -1f;
         for (int i = value.Left; i <= value.Right; i++)
         {
             for (int j = value.Top; j <= value.Bottom; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile == null || !tile.active() || !TileID.Sets.FriendlyFairyCanLureTo[tile.type] || !SceneMetrics.IsValidForOreFinder(tile))
                 {
                     continue;
                 }
                 short num4 = Main.tileOreFinderPriority[tile.type];
                 if (TileID.Sets.Ore[tile.type])
                 {
                     int num5 = 3;
                     int num6 = 3;
                     int num7 = 40;
                     int num8 = 0;
                     for (int k = i - num5; k <= i + num5; k++)
                     {
                         for (int l = j - num6; l <= j + num6; l++)
{
                             if (Main.tile[k, l].active() && Main.tile[k, l].type == tile.type)
{
                                 num8++;
                             }
                         }
                     }
                     if (num8 < num7)
                     {
                         num4 = -1;
                     }
                 }
                 if (num2 <= num4)
                 {
                     float num9 = Distance(new Vector2(i * 16 + 8, j * 16 + 8));
                     if (num2 != num4 || !(num9 >= num3))
                     {
                         num2 = num4;
                         num3 = num9;
                         treasureCoords.X = i;
                         treasureCoords.Y = j;
                     }
                 }
             }
         }
         return num2 != -1;
     }
References Tile.active(), Entity.Distance(), TileID.Sets.FriendlyFairyCanLureTo, SceneMetrics.IsValidForOreFinder(), Main.maxTilesX, Main.maxTilesY, TileID.Sets.Ore, Main.tile, Main.tileOreFinderPriority, Tile.type, and value.
Referenced by AI_112_FairyCritter().