Terraria: NPC.AI_116_WaterStriders
AI_116_WaterStriders()
void NPC.AI_116_WaterStriders () inline private
     {
         bool flag = false;
         if (Collision.GetWaterLine(base.Center.ToTileCoordinates(), out var waterLineHeight))
         {
             float num = base.Bottom.Y - 1f;
             if (base.Center.Y > waterLineHeight)
             {
                 velocity.Y -= 0.8f;
                 if (velocity.Y < -4f)
                 {
                     velocity.Y = -4f;
                 }
                 if (num + velocity.Y < waterLineHeight)
                 {
                     velocity.Y = waterLineHeight - num;
                 }
             }
             else
             {
                 velocity.Y = MathHelper.Min(velocity.Y, waterLineHeight - num);
                 flag = true;
             }
         }
         else if (wet)
         {
             velocity.Y -= 0.2f;
         }
         if ((int)ai[0] != 0)
         {
             return;
         }
         ai[1] += 1f;
         velocity.X *= 0.9f;
         if (velocity.Y == 0f)
         {
             velocity.X *= 0.6f;
         }
         bool flag2 = wet || flag;
         bool flag3 = flag2 || velocity.Y == 0f;
         int num2 = Main.rand.Next(120, 241);
         if (!flag2)
         {
             num2 = Main.rand.Next(60, 241);
         }
         if (!flag3 || !(ai[1] >= (float)num2))
         {
             return;
         }
         ai[1] = 0f;
         velocity.X = Main.rand.NextFloatDirection() * 5f;
         netUpdate = true;
         if (!flag2)
         {
             if (velocity.Y == 0f)
             {
                 velocity.Y = -2f;
             }
             ai[1] = 60f;
         }
     }
References ai, Collision.GetWaterLine(), netUpdate, UnifiedRandom.Next(), Main.rand, Entity.velocity, and Entity.wet.
Referenced by AI().