Terraria: NPC.Collision_MoveSlopesAndStairFall
Collision_MoveSlopesAndStairFall()
void NPC.Collision_MoveSlopesAndStairFall (bool fall) inline private
     {
         if (fall)
         {
             stairFall = true;
         }
         if (aiStyle == 7)
         {
             int num = (int)base.Center.X / 16;
             int num2 = (int)position.Y / 16;
             if (WorldGen.InWorld(num, num2))
             {
                 int num3 = 16;
                 bool flag = false;
                 if (Main.tile[num, num2] != null && Main.tile[num, num2].active() && Main.tileSolid[Main.tile[num, num2].type])
                 {
                     flag = true;
                 }
                 if (!townNPC)
                 {
                     flag = false;
                 }
                 if (!Main.dayTime || Main.eclipse)
                 {
                     flag = true;
                 }
                 else
                 {
                     int num4 = (int)(position.Y + (float)height) / 16;
                     if (homeTileY - num4 > num3)
                     {
                         flag = true;
                     }
                 }
                 if (flag)
                 {
                     if ((position.Y + (float)height - 8f) / 16f < (float)homeTileY)
                     {
                         stairFall = true;
                     }
                     else
                     {
                         stairFall = false;
                     }
                 }
             }
         }
         GetTileCollisionParameters(out var cPosition, out var cWidth, out var cHeight);
         Vector2 vector = position - cPosition;
         Vector4 vector2 = Collision.SlopeCollision(cPosition, velocity, cWidth, cHeight, gravity, stairFall);
         if (Collision.stairFall)
         {
             stairFall = true;
         }
         else if (!fall)
         {
             stairFall = false;
         }
         if (Collision.stair && Math.Abs(vector2.Y - position.Y) > 8f)
         {
             gfxOffY -= vector2.Y - position.Y;
             stepSpeed = 2f;
         }
         position.X = vector2.X;
         position.Y = vector2.Y;
         velocity.X = vector2.Z;
         velocity.Y = vector2.W;
         position += vector;
     }
References Tile.active(), Main.dayTime, Main.eclipse, WorldGen.InWorld(), Collision.SlopeCollision(), Collision.stair, Collision.stairFall, Main.tile, Main.tileSolid, and Tile.type.