Terraria: NPC.AI_000_TransformBoundNPC
AI_000_TransformBoundNPC()
void NPC.AI_000_TransformBoundNPC (int playerID, int npcType) inline
     {
         Transform(npcType);
         Main.BestiaryTracker.Chats.RegisterChatStartWith(this);
         Main.player[playerID].SetTalkNPC(whoAmI);
         if (Main.netMode == 2)
         {
             NetMessage.SendData(40, -1, -1, null, playerID);
         }
     }
References Main.BestiaryTracker, BestiaryUnlocksTracker.Chats, Main.netMode, Main.player, NPCWasChatWithTracker.RegisterChatStartWith(), NetMessage.SendData(), Player.SetTalkNPC(), Transform(), and Entity.whoAmI.
Referenced by AI().