Terraria: NPC.AI_125_ClumsySlimeBalloon
AI_125_ClumsySlimeBalloon()
void NPC.AI_125_ClumsySlimeBalloon () inline private
     {
         if (localAI[0] == 0f && Main.netMode != 1)
         {
             TargetClosest();
             localAI[0] = 1f;
             netUpdate = true;
         }
         spriteDirection = direction;
         rotation = velocity.X * 0.05f;
         NPCAimedTarget targetData = GetTargetData();
         float num = float.PositiveInfinity;
         int num2 = 0;
         Vector2 zero = Vector2.Zero;
         if (!targetData.Invalid)
         {
             zero = targetData.Center - base.Bottom;
             if (zero.Y < 0f)
             {
                 num2 = (int)zero.Y / -16;
             }
             num = zero.Length();
             if (direction != Math.Sign(zero.X))
             {
                 num2 = 0;
             }
         }
         if (wet || collideX || (collideY && oldVelocity.Y < 0f))
         {
             float num3 = oldVelocity.X + (float)(direction * 8);
             position.X -= num3;
             TargetClosest(faceTarget: false);
             direction *= -1;
             velocity.X = direction * 2;
             life = -1;
             HitEffect();
             active = false;
             netUpdate = true;
             SoundEngine.PlaySound(DeathSound, position);
             return;
         }
         if (collideY)
         {
             velocity.Y = ((oldVelocity.Y > 0f) ? 1 : (-1));
             TargetClosest(faceTarget: false);
         }
         float num4 = 3f + Math.Abs(Main.windSpeedTarget) * 2f;
         if (Math.Sign(velocity.X) != direction || Math.Abs(velocity.X) < num4)
         {
             velocity.X += (float)direction * 0.04f;
             if (velocity.X * (float)direction < 0f)
             {
                 if (Math.Abs(velocity.X) > num4)
                 {
                     velocity.X += (float)direction * 0.15f;
                 }
                 else
                 {
                     velocity.X += (float)direction * 0.1f;
                 }
             }
             else if (Math.Abs(velocity.X) > num4)
             {
                 velocity.X = (float)direction * num4;
             }
         }
         int num5 = (int)((position.X + (float)(width / 2)) / 16f) + direction;
         int num6 = (int)((position.Y + (float)height) / 16f);
         bool flag = true;
         int num7 = 8 + num2;
         bool flag2 = false;
         for (int i = num6; i < num6 + num7; i++)
         {
             if (Main.tile[num5, i] == null)
             {
                 Main.tile[num5, i] = new Tile();
             }
             if ((Main.tile[num5, i].nactive() && Main.tileSolid[Main.tile[num5, i].type]) || Main.tile[num5, i].liquid > 0)
             {
                 if (i < num6 + 5 + num2)
                 {
                     flag2 = true;
                 }
                 flag = false;
                 break;
             }
         }
         if (num < 400f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
         {
             float num8 = 2f;
             float num9 = 0.035f;
             if (base.Center.Y + (float)(height / 4) > Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y > 0f - num8)
             {
                 velocity.Y -= num9;
                 if (velocity.Y > 0f)
                 {
                     velocity.Y -= num9;
                 }
             }
             else if (base.Center.Y + (float)(height / 4) < Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y < num8)
             {
                 velocity.Y += num9;
                 if (velocity.Y < 0f)
                 {
                     velocity.Y += num9;
                 }
             }
         }
         else
         {
             if (flag)
             {
                 velocity.Y += 0.05f;
             }
             else
             {
                 velocity.Y -= 0.1f;
             }
             if (flag2)
             {
                 velocity.Y -= 0.2f;
             }
             if (velocity.Y > 2f)
             {
                 velocity.Y = 2f;
             }
             if (velocity.Y < -4f)
             {
                 velocity.Y = -4f;
             }
         }
     }
References Entity.active, Collision.CanHit(), NPCAimedTarget.Center, collideX, collideY, DeathSound, Entity.direction, GetTargetData(), Entity.height, HitEffect(), NPCAimedTarget.Invalid, life, Tile.liquid, localAI, Tile.nactive(), Main.netMode, netUpdate, Entity.oldVelocity, Main.player, SoundEngine.PlaySound(), Entity.position, rotation, spriteDirection, target, TargetClosest(), Tile, Main.tile, Main.tileSolid, Tile.type, Entity.velocity, Entity.wet, Entity.width, and Main.windSpeedTarget.
Referenced by AI().