Terraria: System.Text.Json.Utf8JsonWriter.WriteStringIndented
WriteStringIndented() [4/12]
void System.Text.Json.Utf8JsonWriter.WriteStringIndented (ReadOnlySpan< byte > escapedPropertyName, ReadOnlySpan< byte > escapedValue) inline private
Definition at line 3822 of file Utf8JsonWriter.cs.
    {
        int indentation = Indentation;
        int num = indentation + escapedPropertyName.Length + escapedValue.Length + 6;
        int num2 = num + 1 + s_newLineLength;
        if (_memory.Length - BytesPending < num2)
        {
            Grow(num2);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        if (_tokenType != 0)
        {
            WriteNewLine(span);
        }
        JsonWriterHelper.WriteIndentation(span.Slice(BytesPending), indentation);
        BytesPending += indentation;
        span[BytesPending++] = 34;
        escapedPropertyName.CopyTo(span.Slice(BytesPending));
        BytesPending += escapedPropertyName.Length;
        span[BytesPending++] = 34;
        span[BytesPending++] = 58;
        span[BytesPending++] = 32;
        span[BytesPending++] = 34;
        escapedValue.CopyTo(span.Slice(BytesPending));
        BytesPending += escapedValue.Length;
        span[BytesPending++] = 34;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.Grow(), System.Text.Json.Utf8JsonWriter.Indentation, System.Memory< T >.Length, System.Text.Json.Utf8JsonWriter.s_newLineLength, System.Memory< T >.Span, System.Text.Json.JsonWriterHelper.WriteIndentation(), and System.Text.Json.Utf8JsonWriter.WriteNewLine().