Terraria: System.Text.Json.Utf8JsonWriter.WriteStringByOptionsPropertyName
WriteStringByOptionsPropertyName() [2/2]
void System.Text.Json.Utf8JsonWriter.WriteStringByOptionsPropertyName (ReadOnlySpan< char > propertyName) inline private
Definition at line 2961 of file Utf8JsonWriter.cs.
    {
        ValidateWritingProperty();
        if (_options.Indented)
        {
            WriteStringIndentedPropertyName(propertyName);
        }
        else
        {
            WriteStringMinimizedPropertyName(propertyName);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Indented, System.Text.Json.Utf8JsonWriter.ValidateWritingProperty(), System.Text.Json.Utf8JsonWriter.WriteStringIndentedPropertyName(), and System.Text.Json.Utf8JsonWriter.WriteStringMinimizedPropertyName().
Referenced by System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyName(), System.Text.Json.Utf8JsonWriter.WritePropertyNameHelper(), System.Text.Json.Utf8JsonWriter.WritePropertyNameUnescaped(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), and System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty().