Terraria: System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty
WriteNumberEscapeProperty() [7/10]
void System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty (ReadOnlySpan< char > propertyName, double value, int firstEscapeIndexProp) inline private
Definition at line 1568 of file Utf8JsonWriter.cs.
    {
        char[] array = null;
        int maxEscapedLength = JsonWriterHelper.GetMaxEscapedLength(propertyName.Length, firstEscapeIndexProp);
        Span<char> span = ((maxEscapedLength > 128) ? ((Span<char>)(array = ArrayPool<char>.Shared.Rent(maxEscapedLength))) : stackalloc char[128]);
        Span<char> destination = span;
        JsonWriterHelper.EscapeString(propertyName, destination, firstEscapeIndexProp, _options.Encoder, out var written);
        WriteNumberByOptions(destination.Slice(0, written), value);
        if (array != null)
        {
            ArrayPool<char>.Shared.Return(array);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.array, System.destination, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Encoder, System.Text.Json.JsonWriterHelper.EscapeString(), System.Text.Json.JsonWriterHelper.GetMaxEscapedLength(), System.Buffers.ArrayPool< T >.Shared, System.value, and System.Text.Json.Utf8JsonWriter.WriteNumberByOptions().