Terraria: System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem
SetFlagToAddListSeparatorBeforeNextItem()
void System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem () inline private
Definition at line 620 of file Utf8JsonWriter.cs.
    {
        _currentDepth |= int.MinValue;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth.
Referenced by System.Text.Json.Utf8JsonWriter.WriteBase64String(), System.Text.Json.Utf8JsonWriter.WriteBase64String(), System.Text.Json.Utf8JsonWriter.WriteBase64String(), System.Text.Json.Utf8JsonWriter.WriteBase64StringValue(), System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteBooleanValue(), System.Text.Json.Utf8JsonWriter.WriteEnd(), System.Text.Json.Utf8JsonWriter.WriteLiteralHelper(), System.Text.Json.Utf8JsonWriter.WriteNull(), System.Text.Json.Utf8JsonWriter.WriteNull(), System.Text.Json.Utf8JsonWriter.WriteNullSection(), System.Text.Json.Utf8JsonWriter.WriteNullValue(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValue(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsStringUnescaped(), System.Text.Json.Utf8JsonWriter.WriteRawValueCore(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteStringHelper(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), and System.Text.Json.Utf8JsonWriter.WriteStringValue().