Terraria: System.Text.Json.Utf8JsonWriter.WriteNumberValueAsStringUnescaped
WriteNumberValueAsStringUnescaped()
void System.Text.Json.Utf8JsonWriter.WriteNumberValueAsStringUnescaped (ReadOnlySpan< byte > utf8Value) inline package
Definition at line 5388 of file Utf8JsonWriter.cs.
    {
        WriteStringByOptions(utf8Value);
        SetFlagToAddListSeparatorBeforeNextItem();
        _tokenType = JsonTokenType.String;
    }
References System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), and System.Text.Json.Utf8JsonWriter.WriteStringByOptions().
Referenced by System.Text.Json.Utf8JsonWriter.WriteFloatingPointConstant(), System.Text.Json.Utf8JsonWriter.WriteFloatingPointConstant(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), and System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString().