Terraria: System.Text.Json.Utf8JsonWriter.WriteNumberByOptions
WriteNumberByOptions() [6/10]
void System.Text.Json.Utf8JsonWriter.WriteNumberByOptions (ReadOnlySpan< char > propertyName, decimal value) inline private
Definition at line 1372 of file Utf8JsonWriter.cs.
    {
        ValidateWritingProperty();
        if (_options.Indented)
        {
            WriteNumberIndented(propertyName, value);
        }
        else
        {
            WriteNumberMinimized(propertyName, value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Indented, System.Text.Json.Utf8JsonWriter.ValidateWritingProperty(), System.value, System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), and System.Text.Json.Utf8JsonWriter.WriteNumberMinimized().
Referenced by System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscape(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty(), and System.Text.Json.Utf8JsonWriter.WriteNumberEscapeProperty().