Terraria: System.Text.Json.Utf8JsonWriter.WriteString
WriteString() [12/28]
void System.Text.Json.Utf8JsonWriter.WriteString (ReadOnlySpan< byte > utf8PropertyName, ReadOnlySpan< byte > utf8Value) inline
Definition at line 3190 of file Utf8JsonWriter.cs.
    {
        JsonWriterHelper.ValidatePropertyAndValue(utf8PropertyName, utf8Value);
        WriteStringEscape(utf8PropertyName, utf8Value);
        SetFlagToAddListSeparatorBeforeNextItem();
        _tokenType = JsonTokenType.String;
    }
References System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), System.Text.Json.JsonWriterHelper.ValidatePropertyAndValue(), and System.Text.Json.Utf8JsonWriter.WriteStringEscape().