Terraria: System.Text.Json.Utf8JsonWriter.WriteNumberValue
WriteNumberValue() [5/8]
void System.Text.Json.Utf8JsonWriter.WriteNumberValue (long value) inline
Definition at line 5104 of file Utf8JsonWriter.cs.
    {
        if (!_options.SkipValidation)
        {
            ValidateWritingValue();
        }
        if (_options.Indented)
        {
            WriteNumberValueIndented(value);
        }
        else
        {
            WriteNumberValueMinimized(value);
        }
        SetFlagToAddListSeparatorBeforeNextItem();
        _tokenType = JsonTokenType.Number;
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.JsonWriterOptions.Indented, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), System.Text.Json.JsonWriterOptions.SkipValidation, System.Text.Json.Utf8JsonWriter.ValidateWritingValue(), System.value, System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), and System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized().