Terraria: System.Text.Json.Utf8JsonWriter.TranscodeAndWrite
TranscodeAndWrite()
void System.Text.Json.Utf8JsonWriter.TranscodeAndWrite (ReadOnlySpan< char > escapedPropertyName, Span< byte > output) inline private
Definition at line 2334 of file Utf8JsonWriter.cs.
    {
        ReadOnlySpan<byte> utf16Source = MemoryMarshal.AsBytes(escapedPropertyName);
        int bytesConsumed;
        int bytesWritten;
        OperationStatus operationStatus = JsonWriterHelper.ToUtf8(utf16Source, output.Slice(BytesPending), out bytesConsumed, out bytesWritten);
        BytesPending += bytesWritten;
    }
References System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, and System.Text.Json.JsonWriterHelper.ToUtf8().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteLiteralIndented(), System.Text.Json.Utf8JsonWriter.WriteLiteralMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WritePropertyNameIndented(), System.Text.Json.Utf8JsonWriter.WritePropertyNameMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndentedPropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), and System.Text.Json.Utf8JsonWriter.WriteStringMinimizedPropertyName().