Terraria: System.Text.Json.Utf8JsonWriter.WriteEnd
WriteEnd()
void System.Text.Json.Utf8JsonWriter.WriteEnd (byte token) inline private
Definition at line 468 of file Utf8JsonWriter.cs.
    {
        if (_options.IndentedOrNotSkipValidation)
        {
            WriteEndSlow(token);
        }
        else
        {
            WriteEndMinimized(token);
        }
        SetFlagToAddListSeparatorBeforeNextItem();
        if (CurrentDepth != 0)
        {
            _currentDepth--;
        }
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Utf8JsonWriter.CurrentDepth, System.Text.Json.JsonWriterOptions.IndentedOrNotSkipValidation, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), System.Text.Json.Utf8JsonWriter.WriteEndMinimized(), and System.Text.Json.Utf8JsonWriter.WriteEndSlow().
Referenced by System.Text.Json.Utf8JsonWriter.WriteEndArray(), and System.Text.Json.Utf8JsonWriter.WriteEndObject().