Terraria: System.Text.Json.Utf8JsonWriter.WriteBase64EscapeProperty
WriteBase64EscapeProperty() [1/2]
void System.Text.Json.Utf8JsonWriter.WriteBase64EscapeProperty (ReadOnlySpan< byte > utf8PropertyName, ReadOnlySpan< byte > bytes, int firstEscapeIndexProp) inline private
Definition at line 695 of file Utf8JsonWriter.cs.
    {
        byte[] array = null;
        int maxEscapedLength = JsonWriterHelper.GetMaxEscapedLength(utf8PropertyName.Length, firstEscapeIndexProp);
        Span<byte> span = ((maxEscapedLength > 256) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(maxEscapedLength))) : stackalloc byte[256]);
        Span<byte> destination = span;
        JsonWriterHelper.EscapeString(utf8PropertyName, destination, firstEscapeIndexProp, _options.Encoder, out var written);
        WriteBase64ByOptions(destination.Slice(0, written), bytes);
        if (array != null)
        {
            ArrayPool<byte>.Shared.Return(array);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.array, System.bytes, System.destination, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Encoder, System.Text.Json.JsonWriterHelper.EscapeString(), System.Text.Json.JsonWriterHelper.GetMaxEscapedLength(), System.Buffers.ArrayPool< T >.Shared, and System.Text.Json.Utf8JsonWriter.WriteBase64ByOptions().