Terraria: System.Text.Json.Utf8JsonWriter.WriteCommentByOptions
WriteCommentByOptions() [2/2]
void System.Text.Json.Utf8JsonWriter.WriteCommentByOptions (ReadOnlySpan< char > value) inline private
Definition at line 4253 of file Utf8JsonWriter.cs.
    {
        if (_options.Indented)
        {
            WriteCommentIndented(value);
        }
        else
        {
            WriteCommentMinimized(value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.JsonWriterOptions.Indented, System.value, System.Text.Json.Utf8JsonWriter.WriteCommentIndented(), and System.Text.Json.Utf8JsonWriter.WriteCommentMinimized().
Referenced by System.Text.Json.Utf8JsonWriter.WriteCommentValue(), and System.Text.Json.Utf8JsonWriter.WriteCommentValue().