Terraria: System.Text.Json.Utf8JsonWriter.Base64EncodeAndWrite
Base64EncodeAndWrite()
void System.Text.Json.Utf8JsonWriter.Base64EncodeAndWrite (ReadOnlySpan< byte > bytes, Span< byte > output, int encodingLength) inline private
Definition at line 4909 of file Utf8JsonWriter.cs.
    {
        byte[] array = null;
        Span<byte> span = ((encodingLength > 256) ? ((Span<byte>)(array = ArrayPool<byte>.Shared.Rent(encodingLength))) : stackalloc byte[256]);
        Span<byte> utf = span;
        int bytesConsumed;
        int bytesWritten;
        OperationStatus operationStatus = Base64.EncodeToUtf8(bytes, utf, out bytesConsumed, out bytesWritten);
        utf = utf.Slice(0, bytesWritten);
        Span<byte> destination = output.Slice(BytesPending);
        utf.Slice(0, bytesWritten).CopyTo(destination);
        BytesPending += bytesWritten;
        if (array != null)
        {
            ArrayPool<byte>.Shared.Return(array);
        }
    }
References System.array, System.bytes, System.Text.Json.Utf8JsonWriter.BytesPending, System.destination, System.Text.Json.Dictionary, System.Buffers.Text.Base64.EncodeToUtf8(), System.Buffers.ArrayPool< T >.Shared, and System.Span< T >.Slice().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), and System.Text.Json.Utf8JsonWriter.WriteBase64Minimized().