Terraria: System.Text.Json.Utf8JsonWriter.WriteRawValueCore
WriteRawValueCore()
void System.Text.Json.Utf8JsonWriter.WriteRawValueCore (ReadOnlySpan< byte > utf8Json, bool skipInputValidation) inline private
Definition at line 5065 of file Utf8JsonWriter.cs.
    {
        int length = utf8Json.Length;
        if (length == 0)
        {
            ThrowHelper.ThrowArgumentException(System.SR.ExpectedJsonTokens);
        }
        if (skipInputValidation)
        {
            _tokenType = JsonTokenType.String;
        }
        else
        {
            Utf8JsonReader utf8JsonReader = new Utf8JsonReader(utf8Json);
            while (utf8JsonReader.Read())
            {
            }
            _tokenType = utf8JsonReader.TokenType;
        }
        int num = length + 1;
        if (_memory.Length - BytesPending < num)
        {
            Grow(num);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        utf8Json.CopyTo(span.Slice(BytesPending));
        BytesPending += length;
        SetFlagToAddListSeparatorBeforeNextItem();
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.SR.ExpectedJsonTokens, System.Text.Json.Utf8JsonWriter.Grow(), System.length, System.Memory< T >.Length, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), System.Memory< T >.Span, and System.Text.Json.ThrowHelper.ThrowArgumentException().
Referenced by System.Text.Json.Utf8JsonWriter.TranscodeAndWriteRawValue(), and System.Text.Json.Utf8JsonWriter.WriteRawValue().