Terraria: System.Text.Json.Utf8JsonWriter.WriteLiteralEscape
WriteLiteralEscape() [2/2]
void System.Text.Json.Utf8JsonWriter.WriteLiteralEscape (ReadOnlySpan< char > propertyName, ReadOnlySpan< byte > value) inline private
Definition at line 2432 of file Utf8JsonWriter.cs.
    {
        int num = JsonWriterHelper.NeedsEscaping(propertyName, _options.Encoder);
        if (num != -1)
        {
            WriteLiteralEscapeProperty(propertyName, value, num);
        }
        else
        {
            WriteLiteralByOptions(propertyName, value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Encoder, System.Text.Json.JsonWriterHelper.NeedsEscaping(), System.value, System.Text.Json.Utf8JsonWriter.WriteLiteralByOptions(), and System.Text.Json.Utf8JsonWriter.WriteLiteralEscapeProperty().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteBoolean(), System.Text.Json.Utf8JsonWriter.WriteNull(), and System.Text.Json.Utf8JsonWriter.WriteNull().