Terraria: System.Text.Json.Utf8JsonWriter.Grow
Grow()
void System.Text.Json.Utf8JsonWriter.Grow (int requiredSize) inline private
Definition at line 580 of file Utf8JsonWriter.cs.
    {
        if (_memory.Length == 0)
        {
            FirstCallToGetMemory(requiredSize);
            return;
        }
        int num = Math.Max(4096, requiredSize);
        if (_stream != null)
        {
            int num2 = BytesPending + num;
            JsonHelpers.ValidateInt32MaxArrayLength((uint)num2);
            _memory = _arrayBufferWriter.GetMemory(num2);
            return;
        }
        _output.Advance(BytesPending);
        BytesCommitted += BytesPending;
        BytesPending = 0;
        _memory = _output.GetMemory(num);
        if (_memory.Length < num)
        {
            ThrowHelper.ThrowInvalidOperationException_NeedLargerSpan();
        }
    }
References System.Text.Json.Utf8JsonWriter._arrayBufferWriter, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._output, System.Text.Json.Utf8JsonWriter._stream, System.Buffers.IBufferWriter< T >.Advance(), System.Text.Json.Utf8JsonWriter.BytesCommitted, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.FirstCallToGetMemory(), System.Buffers.ArrayBufferWriter< T >.GetMemory(), System.Buffers.IBufferWriter< T >.GetMemory(), System.Memory< T >.Length, System.Math.Max(), System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NeedLargerSpan(), and System.Text.Json.JsonHelpers.ValidateInt32MaxArrayLength().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Indented(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteBase64Minimized(), System.Text.Json.Utf8JsonWriter.WriteCommentIndented(), System.Text.Json.Utf8JsonWriter.WriteCommentIndented(), System.Text.Json.Utf8JsonWriter.WriteCommentMinimized(), System.Text.Json.Utf8JsonWriter.WriteCommentMinimized(), System.Text.Json.Utf8JsonWriter.WriteEndIndented(), System.Text.Json.Utf8JsonWriter.WriteEndMinimized(), System.Text.Json.Utf8JsonWriter.WriteLiteralIndented(), System.Text.Json.Utf8JsonWriter.WriteLiteralIndented(), System.Text.Json.Utf8JsonWriter.WriteLiteralIndented(), System.Text.Json.Utf8JsonWriter.WriteLiteralMinimized(), System.Text.Json.Utf8JsonWriter.WriteLiteralMinimized(), System.Text.Json.Utf8JsonWriter.WriteLiteralMinimized(), System.Text.Json.Utf8JsonWriter.WriteLiteralSection(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), System.Text.Json.Utf8JsonWriter.WritePropertyNameIndented(), System.Text.Json.Utf8JsonWriter.WritePropertyNameIndented(), System.Text.Json.Utf8JsonWriter.WritePropertyNameMinimized(), System.Text.Json.Utf8JsonWriter.WritePropertyNameMinimized(), System.Text.Json.Utf8JsonWriter.WriteRawValueCore(), System.Text.Json.Utf8JsonWriter.WriteStartIndented(), System.Text.Json.Utf8JsonWriter.WriteStartMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndented(), System.Text.Json.Utf8JsonWriter.WriteStringIndentedPropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringIndentedPropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringMinimizedPropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringMinimizedPropertyName(), System.Text.Json.Utf8JsonWriter.WriteStringPropertyNameSection(), System.Text.Json.Utf8JsonWriter.WriteStringValueIndented(), System.Text.Json.Utf8JsonWriter.WriteStringValueIndented(), System.Text.Json.Utf8JsonWriter.WriteStringValueIndented(), System.Text.Json.Utf8JsonWriter.WriteStringValueMinimized(), System.Text.Json.Utf8JsonWriter.WriteStringValueMinimized(), and System.Text.Json.Utf8JsonWriter.WriteStringValueMinimized().