Terraria: System.Text.Json.Utf8JsonWriter.WriteStringEscape
WriteStringEscape() [3/12]
void System.Text.Json.Utf8JsonWriter.WriteStringEscape (ReadOnlySpan< byte > utf8PropertyName, Guid value) inline private
Definition at line 2001 of file Utf8JsonWriter.cs.
    {
        int num = JsonWriterHelper.NeedsEscaping(utf8PropertyName, _options.Encoder);
        if (num != -1)
        {
            WriteStringEscapeProperty(utf8PropertyName, value, num);
        }
        else
        {
            WriteStringByOptions(utf8PropertyName, value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Encoder, System.Text.Json.JsonWriterHelper.NeedsEscaping(), System.value, System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), and System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty().