Terraria: System.Text.Json.Utf8JsonWriter.TryFormatDouble
TryFormatDouble()
static bool System.Text.Json.Utf8JsonWriter.TryFormatDouble (double value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 4636 of file Utf8JsonWriter.cs.
    {
        return Utf8Formatter.TryFormat(value, destination, out bytesWritten);
    }
References System.destination, System.Text.Json.Dictionary, System.Buffers.Text.Utf8Formatter.TryFormat(), and System.value.
Referenced by System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberMinimized(), System.Text.Json.Utf8JsonWriter.WriteNumberValueAsString(), System.Text.Json.Utf8JsonWriter.WriteNumberValueIndented(), System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(), and System.Text.Json.Utf8JsonWriter.WritePropertyName().