Terraria: System.Text.Json.Utf8JsonWriter.WriteCommentIndented
WriteCommentIndented() [1/2]
void System.Text.Json.Utf8JsonWriter.WriteCommentIndented (ReadOnlySpan< byte > utf8Value) inline private
Definition at line 4348 of file Utf8JsonWriter.cs.
    {
        int indentation = Indentation;
        int num = indentation + utf8Value.Length + 4;
        int num2 = num + s_newLineLength;
        if (_memory.Length - BytesPending < num2)
        {
            Grow(num2);
        }
        Span<byte> span = _memory.Span;
        if (_tokenType != JsonTokenType.PropertyName)
        {
            if (_tokenType != 0)
            {
                WriteNewLine(span);
            }
            JsonWriterHelper.WriteIndentation(span.Slice(BytesPending), indentation);
            BytesPending += indentation;
        }
        span[BytesPending++] = 47;
        span[BytesPending++] = 42;
        utf8Value.CopyTo(span.Slice(BytesPending));
        BytesPending += utf8Value.Length;
        span[BytesPending++] = 42;
        span[BytesPending++] = 47;
    }
References System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.Grow(), System.Text.Json.Utf8JsonWriter.Indentation, System.Memory< T >.Length, System.Text.Json.Utf8JsonWriter.s_newLineLength, System.Memory< T >.Span, System.Text.Json.JsonWriterHelper.WriteIndentation(), and System.Text.Json.Utf8JsonWriter.WriteNewLine().