Terraria: System.Text.Json.Utf8JsonWriter.FlushAsync
FlushAsync()
async Task System.Text.Json.Utf8JsonWriter.FlushAsync (CancellationToken cancellationToken = default(CancellationToken)) inline
Definition at line 182 of file Utf8JsonWriter.cs.
    {
        CheckNotDisposed();
        _memory = default(Memory<byte>);
        if (_stream != null)
        {
            if (BytesPending != 0)
            {
                _arrayBufferWriter.Advance(BytesPending);
                BytesPending = 0;
                await _stream.WriteAsync(_arrayBufferWriter.WrittenMemory, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                BytesCommitted += _arrayBufferWriter.WrittenCount;
                _arrayBufferWriter.Clear();
            }
            await _stream.FlushAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        else if (BytesPending != 0)
        {
            _output.Advance(BytesPending);
            BytesCommitted += BytesPending;
            BytesPending = 0;
        }
    }
References System.Text.Json.Utf8JsonWriter._arrayBufferWriter, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._output, System.Text.Json.Utf8JsonWriter._stream, System.Buffers.ArrayBufferWriter< T >.Advance(), System.Buffers.IBufferWriter< T >.Advance(), System.Text.Json.Utf8JsonWriter.BytesCommitted, System.Text.Json.Utf8JsonWriter.BytesPending, System.cancellationToken, System.Text.Json.Utf8JsonWriter.CheckNotDisposed(), System.Buffers.ArrayBufferWriter< T >.Clear(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Text.Json.Dictionary, System.IO.Stream.FlushAsync(), System.IO.Stream.WriteAsync(), System.Buffers.ArrayBufferWriter< T >.WrittenCount, and System.Buffers.ArrayBufferWriter< T >.WrittenMemory.
Referenced by System.Text.Json.Utf8JsonWriter.DisposeAsync().