Terraria: System.Net.Http.HttpConnectionBase.TraceConnection
TraceConnection()
void System.Net.Http.HttpConnectionBase.TraceConnection (Stream stream) inline protected inherited
Definition at line 44 of file HttpConnectionBase.cs.
    {
        if (stream is SslStream sslStream)
        {
            Trace($"{this}. SslProtocol:{sslStream.SslProtocol}, NegotiatedApplicationProtocol:{sslStream.NegotiatedApplicationProtocol}, NegotiatedCipherSuite:{sslStream.NegotiatedCipherSuite}, CipherAlgorithm:{sslStream.CipherAlgorithm}, CipherStrength:{sslStream.CipherStrength}, HashAlgorithm:{sslStream.HashAlgorithm}, HashStrength:{sslStream.HashStrength}, KeyExchangeAlgorithm:{sslStream.KeyExchangeAlgorithm}, KeyExchangeStrength:{sslStream.KeyExchangeStrength}, LocalCertificate:{sslStream.LocalCertificate}, RemoteCertificate:{sslStream.RemoteCertificate}", "TraceConnection");
        }
        else
        {
            Trace($"{this}", "TraceConnection");
        }
    }
References System.stream, and System.Net.Http.HttpConnectionBase.Trace().
Referenced by System.Net.Http.Http2Connection.Http2Connection(), and System.Net.Http.HttpConnection.HttpConnection().