Terraria: System.Text.Json.Utf8JsonWriter.WriteStringByOptions
WriteStringByOptions() [7/12]
void System.Text.Json.Utf8JsonWriter.WriteStringByOptions (ReadOnlySpan< char > propertyName, DateTime value) inline private
Definition at line 924 of file Utf8JsonWriter.cs.
    {
        ValidateWritingProperty();
        if (_options.Indented)
        {
            WriteStringIndented(propertyName, value);
        }
        else
        {
            WriteStringMinimized(propertyName, value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Indented, System.Text.Json.Utf8JsonWriter.ValidateWritingProperty(), System.value, System.Text.Json.Utf8JsonWriter.WriteStringIndented(), and System.Text.Json.Utf8JsonWriter.WriteStringMinimized().
Referenced by System.Text.Json.Utf8JsonWriter.WriteNumberValueAsStringUnescaped(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscape(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOnly(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOnly(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOrValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOrValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOrValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapePropertyOrValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeValue(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeValueOnly(), System.Text.Json.Utf8JsonWriter.WriteStringEscapeValueOnly(), System.Text.Json.Utf8JsonWriter.WriteStringHelper(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeProperty(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue(), System.Text.Json.Utf8JsonWriter.WriteStringHelperEscapeValue(), and System.Text.Json.Utf8JsonWriter.WriteStringValue().