Terraria: System.Text.Json.Utf8JsonWriter.WriteNumber
WriteNumber() [1/28]
void System.Text.Json.Utf8JsonWriter.WriteNumber (JsonEncodedText propertyName, decimal value) inline
Definition at line 1289 of file Utf8JsonWriter.cs.
    {
        ReadOnlySpan<byte> encodedUtf8Bytes = propertyName.EncodedUtf8Bytes;
        WriteNumberByOptions(encodedUtf8Bytes, value);
        SetFlagToAddListSeparatorBeforeNextItem();
        _tokenType = JsonTokenType.Number;
    }
References System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.SetFlagToAddListSeparatorBeforeNextItem(), System.value, and System.Text.Json.Utf8JsonWriter.WriteNumberByOptions().
Referenced by System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), System.Text.Json.Utf8JsonWriter.WriteNumber(), and System.Text.Json.Utf8JsonWriter.WriteNumber().