Terraria: System.Text.Json.Utf8JsonWriter.FirstCallToGetMemory
FirstCallToGetMemory()
void System.Text.Json.Utf8JsonWriter.FirstCallToGetMemory (int requiredSize) inline private
Definition at line 605 of file Utf8JsonWriter.cs.
    {
        int num = Math.Max(256, requiredSize);
        if (_stream != null)
        {
            _memory = _arrayBufferWriter.GetMemory(num);
            return;
        }
        _memory = _output.GetMemory(num);
        if (_memory.Length < num)
        {
            ThrowHelper.ThrowInvalidOperationException_NeedLargerSpan();
        }
    }
References System.Text.Json.Utf8JsonWriter._arrayBufferWriter, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._output, System.Text.Json.Utf8JsonWriter._stream, System.Text.Json.Dictionary, System.Buffers.ArrayBufferWriter< T >.GetMemory(), System.Buffers.IBufferWriter< T >.GetMemory(), System.Memory< T >.Length, System.Math.Max(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NeedLargerSpan().
Referenced by System.Text.Json.Utf8JsonWriter.Grow().