Terraria: System.Text.Json.Utf8JsonWriter.ResetHelper
ResetHelper()
void System.Text.Json.Utf8JsonWriter.ResetHelper () inline private
Definition at line 115 of file Utf8JsonWriter.cs.
    {
        BytesPending = 0;
        BytesCommitted = 0L;
        _memory = default(Memory<byte>);
        _inObject = false;
        _tokenType = JsonTokenType.None;
        _currentDepth = 0;
        _bitStack = default(BitStack);
    }
References System.Text.Json.Utf8JsonWriter._bitStack, System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._inObject, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesCommitted, System.Text.Json.Utf8JsonWriter.BytesPending, and System.L.
Referenced by System.Text.Json.Utf8JsonWriter.Dispose(), System.Text.Json.Utf8JsonWriter.DisposeAsync(), System.Text.Json.Utf8JsonWriter.Reset(), System.Text.Json.Utf8JsonWriter.Reset(), and System.Text.Json.Utf8JsonWriter.Reset().