Terraria: System.Text.Json.Utf8JsonWriter.WriteStringByOptions
WriteStringByOptions() [1/12]
void System.Text.Json.Utf8JsonWriter.WriteStringByOptions (ReadOnlySpan< byte > utf8PropertyName, DateTime value) inline private
Definition at line 937 of file Utf8JsonWriter.cs.
    {
        ValidateWritingProperty();
        if (_options.Indented)
        {
            WriteStringIndented(utf8PropertyName, value);
        }
        else
        {
            WriteStringMinimized(utf8PropertyName, value);
        }
    }
References System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Dictionary, System.Text.Json.JsonWriterOptions.Indented, System.Text.Json.Utf8JsonWriter.ValidateWritingProperty(), System.value, System.Text.Json.Utf8JsonWriter.WriteStringIndented(), and System.Text.Json.Utf8JsonWriter.WriteStringMinimized().