Terraria: System.Text.Json.Utf8JsonWriter.WriteStringValueIndented
WriteStringValueIndented() [1/3]
void System.Text.Json.Utf8JsonWriter.WriteStringValueIndented (DateTime value) inline private
Definition at line 4411 of file Utf8JsonWriter.cs.
    {
        int indentation = Indentation;
        int num = indentation + 33 + 3 + s_newLineLength;
        if (_memory.Length - BytesPending < num)
        {
            Grow(num);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        if (_tokenType != JsonTokenType.PropertyName)
        {
            if (_tokenType != 0)
            {
                WriteNewLine(span);
            }
            JsonWriterHelper.WriteIndentation(span.Slice(BytesPending), indentation);
            BytesPending += indentation;
        }
        span[BytesPending++] = 34;
        JsonWriterHelper.WriteDateTimeTrimmed(span.Slice(BytesPending), value, out var bytesWritten);
        BytesPending += bytesWritten;
        span[BytesPending++] = 34;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.Grow(), System.Text.Json.Utf8JsonWriter.Indentation, System.Memory< T >.Length, System.Text.Json.Utf8JsonWriter.s_newLineLength, System.Memory< T >.Span, System.value, System.Text.Json.JsonWriterHelper.WriteDateTimeTrimmed(), System.Text.Json.JsonWriterHelper.WriteIndentation(), and System.Text.Json.Utf8JsonWriter.WriteNewLine().
Referenced by System.Text.Json.Utf8JsonWriter.WriteStringValue(), System.Text.Json.Utf8JsonWriter.WriteStringValue(), and System.Text.Json.Utf8JsonWriter.WriteStringValue().