Terraria: System.Text.Json.Utf8JsonWriter.Reset
Reset() [3/3]
void System.Text.Json.Utf8JsonWriter.Reset (Stream utf8Json) inline
Definition at line 82 of file Utf8JsonWriter.cs.
    {
        CheckNotDisposed();
        if (utf8Json == null)
        {
            throw new ArgumentNullException("utf8Json");
        }
        if (!utf8Json.CanWrite)
        {
            throw new ArgumentException(System.SR.StreamNotWritable);
        }
        _stream = utf8Json;
        if (_arrayBufferWriter == null)
        {
            _arrayBufferWriter = new ArrayBufferWriter<byte>();
        }
        else
        {
            _arrayBufferWriter.Clear();
        }
        _output = null;
        ResetHelper();
    }
References System.Text.Json.Utf8JsonWriter._arrayBufferWriter, System.Text.Json.Utf8JsonWriter._output, System.Text.Json.Utf8JsonWriter._stream, System.Text.Json.Utf8JsonWriter.CheckNotDisposed(), System.Buffers.ArrayBufferWriter< T >.Clear(), System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.ResetHelper(), and System.SR.StreamNotWritable.