Terraria: System.Text.Json.Utf8JsonWriter.WriteCommentValue
WriteCommentValue() [1/3]
void System.Text.Json.Utf8JsonWriter.WriteCommentValue (ReadOnlySpan< byte > utf8Value) inline
Definition at line 4310 of file Utf8JsonWriter.cs.
    {
        JsonWriterHelper.ValidateValue(utf8Value);
        if (utf8Value.IndexOf(SingleLineCommentDelimiterUtf8) != -1)
        {
            ThrowHelper.ThrowArgumentException_InvalidCommentValue();
        }
        WriteCommentByOptions(utf8Value);
    }
References System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.SingleLineCommentDelimiterUtf8, System.Text.Json.ThrowHelper.ThrowArgumentException_InvalidCommentValue(), System.Text.Json.JsonWriterHelper.ValidateValue(), and System.Text.Json.Utf8JsonWriter.WriteCommentByOptions().