Terraria: System.Text.Json.Utf8JsonWriter.ValidateEnd
ValidateEnd()
void System.Text.Json.Utf8JsonWriter.ValidateEnd (byte token) inline private
Definition at line 511 of file Utf8JsonWriter.cs.
    {
        if (_bitStack.CurrentDepth <= 0 || _tokenType == JsonTokenType.PropertyName)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.MismatchedObjectArray, 0, token, _tokenType);
        }
        if (token == 93)
        {
            if (_inObject)
            {
                ThrowHelper.ThrowInvalidOperationException(ExceptionResource.MismatchedObjectArray, 0, token, _tokenType);
            }
        }
        else if (!_inObject)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.MismatchedObjectArray, 0, token, _tokenType);
        }
        _inObject = _bitStack.Pop();
    }
References System.Text.Json.Utf8JsonWriter._bitStack, System.Text.Json.Utf8JsonWriter._inObject, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.BitStack.CurrentDepth, System.Text.Json.BitStack.Pop(), and System.Text.Json.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Text.Json.Utf8JsonWriter.WriteEndSlow().