Terraria: System.Text.Json.Utf8JsonWriter.ValidateWritingProperty
ValidateWritingProperty() [1/2]
void System.Text.Json.Utf8JsonWriter.ValidateWritingProperty () inline private
Definition at line 2216 of file Utf8JsonWriter.cs.
    {
        if (!_options.SkipValidation && (!_inObject || _tokenType == JsonTokenType.PropertyName))
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.CannotWritePropertyWithinArray, 0, 0, _tokenType);
        }
    }
References System.Text.Json.Utf8JsonWriter._inObject, System.Text.Json.Utf8JsonWriter._options, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.JsonWriterOptions.SkipValidation, and System.Text.Json.ThrowHelper.ThrowInvalidOperationException().
Referenced by System.Text.Json.Utf8JsonWriter.WriteBase64ByOptions(), System.Text.Json.Utf8JsonWriter.WriteBase64ByOptions(), System.Text.Json.Utf8JsonWriter.WriteLiteralByOptions(), System.Text.Json.Utf8JsonWriter.WriteLiteralByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteNumberByOptions(), System.Text.Json.Utf8JsonWriter.WriteStartByOptions(), System.Text.Json.Utf8JsonWriter.WriteStartByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptionsPropertyName(), and System.Text.Json.Utf8JsonWriter.WriteStringByOptionsPropertyName().