Terraria: System.Text.Json.Utf8JsonWriter.WriteBase64Minimized
WriteBase64Minimized() [1/3]
void System.Text.Json.Utf8JsonWriter.WriteBase64Minimized (ReadOnlySpan< byte > bytes) inline private
Definition at line 4192 of file Utf8JsonWriter.cs.
    {
        int maxEncodedToUtf8Length = Base64.GetMaxEncodedToUtf8Length(bytes.Length);
        int num = maxEncodedToUtf8Length + 3;
        if (_memory.Length - BytesPending < num)
        {
            Grow(num);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        span[BytesPending++] = 34;
        Base64EncodeAndWrite(bytes, span, maxEncodedToUtf8Length);
        span[BytesPending++] = 34;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter.Base64EncodeAndWrite(), System.bytes, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length(), System.Text.Json.Utf8JsonWriter.Grow(), System.Memory< T >.Length, and System.Memory< T >.Span.