Terraria: System.Text.Json.Utf8JsonWriter.WriteNull
WriteNull() [1/4]
void System.Text.Json.Utf8JsonWriter.WriteNull (JsonEncodedText propertyName) inline
Definition at line 2343 of file Utf8JsonWriter.cs.
    {
        WriteLiteralHelper(propertyName.EncodedUtf8Bytes, JsonConstants.NullValue);
        _tokenType = JsonTokenType.Null;
    }
References System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Dictionary, System.Text.Json.JsonConstants.NullValue, and System.Text.Json.Utf8JsonWriter.WriteLiteralHelper().
Referenced by System.Text.Json.Utf8JsonWriter.WriteNull(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), System.Text.Json.Utf8JsonWriter.WriteString(), and System.Text.Json.Utf8JsonWriter.WriteString().