Terraria: System.Text.Json.Utf8JsonWriter.WriteNumberIndented
WriteNumberIndented() [9/10]
void System.Text.Json.Utf8JsonWriter.WriteNumberIndented (ReadOnlySpan< char > escapedPropertyName, long value) inline private
Definition at line 2813 of file Utf8JsonWriter.cs.
    {
        int indentation = Indentation;
        int num = indentation + escapedPropertyName.Length * 3 + 20 + 5 + s_newLineLength;
        if (_memory.Length - BytesPending < num)
        {
            Grow(num);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        if (_tokenType != 0)
        {
            WriteNewLine(span);
        }
        JsonWriterHelper.WriteIndentation(span.Slice(BytesPending), indentation);
        BytesPending += indentation;
        span[BytesPending++] = 34;
        TranscodeAndWrite(escapedPropertyName, span);
        span[BytesPending++] = 34;
        span[BytesPending++] = 58;
        span[BytesPending++] = 32;
        int bytesWritten;
        bool flag = Utf8Formatter.TryFormat(value, span.Slice(BytesPending), out bytesWritten);
        BytesPending += bytesWritten;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter._tokenType, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.Grow(), System.Text.Json.Utf8JsonWriter.Indentation, System.Memory< T >.Length, System.Text.Json.Utf8JsonWriter.s_newLineLength, System.Memory< T >.Span, System.Text.Json.Utf8JsonWriter.TranscodeAndWrite(), System.Buffers.Text.Utf8Formatter.TryFormat(), System.value, System.Text.Json.JsonWriterHelper.WriteIndentation(), and System.Text.Json.Utf8JsonWriter.WriteNewLine().