Terraria: System.Net.Http.HttpConnectionBase.LogExceptions
LogExceptions()
void System.Net.Http.HttpConnectionBase.LogExceptions (Task task) inline package inherited
Definition at line 100 of file HttpConnectionBase.cs.
    {
        if (task.IsCompleted)
        {
            if (task.IsFaulted)
            {
                LogFaulted(this, task);
            }
        }
        else
        {
            task.ContinueWith(delegate(Task t, object state)
            {
                LogFaulted((HttpConnectionBase)state, t);
            }, this, CancellationToken.None, TaskContinuationOptions.OnlyOnFaulted | TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
        }
        static void LogFaulted(HttpConnectionBase connection, Task task)
        {
            Exception innerException = task.Exception.InnerException;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                connection.Trace($"Exception from asynchronous processing: {innerException}", "LogExceptions");
            }
        }
    }
References System.Exception.Exception(), System.Threading.Tasks.TaskScheduler.Default, System.Net.NetEventSource.Log, System.Threading.CancellationToken.None, System.state, System.task, and System.Net.Http.HttpConnectionBase.Trace().
Referenced by System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AjdustWindowStatic(), System.Net.Http.Http2Connection.ExtendWindow(), System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), System.Net.Http.Http2Connection.ProcessPingFrame(), System.Net.Http.Http2Connection.ProcessSettingsFrame(), System.Net.Http.Http3RequestStream.SendAsync(), System.Net.Http.Http2Connection.SendAsync(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(), and System.Net.Http.Http2Connection.Http2Stream.SendReset().