Terraria: System.Text.Json.Utf8JsonWriter.WriteStringMinimized
WriteStringMinimized() [7/12]
void System.Text.Json.Utf8JsonWriter.WriteStringMinimized (ReadOnlySpan< char > escapedPropertyName, DateTime value) inline private
Definition at line 950 of file Utf8JsonWriter.cs.
    {
        int num = escapedPropertyName.Length * 3 + 33 + 6;
        if (_memory.Length - BytesPending < num)
        {
            Grow(num);
        }
        Span<byte> span = _memory.Span;
        if (_currentDepth < 0)
        {
            span[BytesPending++] = 44;
        }
        span[BytesPending++] = 34;
        TranscodeAndWrite(escapedPropertyName, span);
        span[BytesPending++] = 34;
        span[BytesPending++] = 58;
        span[BytesPending++] = 34;
        JsonWriterHelper.WriteDateTimeTrimmed(span.Slice(BytesPending), value, out var bytesWritten);
        BytesPending += bytesWritten;
        span[BytesPending++] = 34;
    }
References System.Text.Json.Utf8JsonWriter._currentDepth, System.Text.Json.Utf8JsonWriter._memory, System.Text.Json.Utf8JsonWriter.BytesPending, System.Text.Json.Dictionary, System.Text.Json.Utf8JsonWriter.Grow(), System.Memory< T >.Length, System.Memory< T >.Span, System.Text.Json.Utf8JsonWriter.TranscodeAndWrite(), System.value, and System.Text.Json.JsonWriterHelper.WriteDateTimeTrimmed().
Referenced by System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), System.Text.Json.Utf8JsonWriter.WriteStringByOptions(), and System.Text.Json.Utf8JsonWriter.WriteStringByOptions().