Terraria: System.Diagnostics.Metrics.MeterListener.Dispose
Dispose()
void System.Diagnostics.Metrics.MeterListener.Dispose () inline
Implements System.IDisposable.
Definition at line 194 of file MeterListener.cs.
    {
        Dictionary<Instrument, object> dictionary = null;
        Action<Instrument, object> measurementsCompleted = MeasurementsCompleted;
        lock (Instrument.SyncObject)
        {
            if (_disposed)
            {
                return;
            }
            _disposed = true;
            s_allStartedListeners.Remove(this);
            DiagNode<Instrument> diagNode = _enabledMeasurementInstruments.First;
            if (diagNode != null && measurementsCompleted != null)
            {
                dictionary = new Dictionary<Instrument, object>();
                do
                {
                    object value = diagNode.Value.DisableMeasurements(this);
                    dictionary.Add(diagNode.Value, value);
                    diagNode = diagNode.Next;
                }
                while (diagNode != null);
                _enabledMeasurementInstruments.Clear();
            }
        }
        if (dictionary == null)
        {
            return;
        }
        foreach (KeyValuePair<Instrument, object> item in dictionary)
        {
            measurementsCompleted?.Invoke(item.Key, item.Value);
        }
    }
References System.Diagnostics.Metrics.MeterListener._disposed, System.Diagnostics.Metrics.MeterListener._enabledMeasurementInstruments, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.dictionary, System.item, System.Diagnostics.Metrics.MeterListener.MeasurementsCompleted, System.Diagnostics.Metrics.MeterListener.s_allStartedListeners, System.Diagnostics.Metrics.Instrument< T >.SyncObject, and System.value.
Referenced by System.Diagnostics.Metrics.AggregationManager.Dispose().