Terraria: System.Net.Http.Headers.MediaTypeHeaderParser.SingleValueParser
SingleValueParser
readonly MediaTypeHeaderParser System.Net.Http.Headers.MediaTypeHeaderParser.SingleValueParser = new MediaTypeHeaderParser(supportsMultipleValues: false, CreateMediaType) static package
Definition at line 7 of file MediaTypeHeaderParser.cs.
Referenced by System.Net.Http.Headers.KnownHeaders.KnownHeaders(), System.Net.Http.Headers.MediaTypeHeaderValue.Parse(), and System.Net.Http.Headers.MediaTypeHeaderValue.TryParse().