Terraria: CaptureInterface.ModeChangeSettings.Draw
Draw()
override void CaptureInterface.ModeChangeSettings.Draw (SpriteBatch sb) inline virtual
Implements CaptureInterface.CaptureInterfaceMode.
         {
             if (!Selected)
             {
                 return;
             }
             sb.End();
             sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.CurrentWantedZoomMatrix);
             PlayerInput.SetZoom_Context();
             ((ModeDragBounds)Modes[1]).currentAim = -1;
             ((ModeDragBounds)Modes[1]).DrawMarkedArea(sb);
             sb.End();
             sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
             PlayerInput.SetZoom_UI();
             Rectangle rect = GetRect();
             Utils.DrawInvBG(sb, rect, new Color(63, 65, 151, 255) * 0.485f);
             for (int i = 0; i < 7; i++)
             {
                 string key = "";
                 string value = "";
                 ButtonDraw(i, ref key, ref value);
                 Color baseColor = Color.White;
                 if (i == hoveredButton)
                 {
                     baseColor = Color.Gold;
                 }
                 ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.ItemStack.Value, key, rect.TopLeft() + new Vector2(20f, 20 + 20 * i), baseColor, 0f, Vector2.Zero, Vector2.One);
                 ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.ItemStack.Value, value, rect.TopRight() + new Vector2(-20f, 20 + 20 * i), baseColor, 0f, FontAssets.ItemStack.Value.MeasureString(value) * Vector2.UnitX, Vector2.One);
             }
             DrawWaterChoices(sb, (rect.TopLeft() + new Vector2(rect.Width / 2 - 84, 90f)).ToPoint(), Main.MouseScreen.ToPoint());
         }
References CaptureInterface.ModeChangeSettings.ButtonDraw(), Color, Main.CurrentWantedZoomMatrix, ChatManager.DrawColorCodedStringWithShadow(), Utils.DrawInvBG(), CaptureInterface.ModeChangeSettings.DrawWaterChoices(), CaptureInterface.ModeChangeSettings.GetRect(), CaptureInterface.ModeChangeSettings.hoveredButton, FontAssets.ItemStack, CaptureInterface.Modes, Main.MouseScreen, CaptureInterface.CaptureInterfaceMode.Selected, PlayerInput.SetZoom_Context(), PlayerInput.SetZoom_UI(), Main.UIScaleMatrix, and Asset< T >.Value.