Terraria: TEFoodPlatter.OnPlayerInteraction
OnPlayerInteraction()
static void TEFoodPlatter.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
     {
         if (FitsFoodPlatter(player.inventory[player.selectedItem]) && !player.inventory[player.selectedItem].favorited)
         {
             player.GamepadEnableGrappleCooldown();
             PlaceItemInFrame(player, clickX, clickY);
             Recipe.FindRecipes();
             return;
         }
         int num = Find(clickX, clickY);
         if (num != -1 && ((TEFoodPlatter)TileEntity.ByID[num]).item.stack > 0)
         {
             player.GamepadEnableGrappleCooldown();
             WorldGen.KillTile(clickX, clickY, fail: true);
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(17, -1, -1, null, 0, clickX, clickY, 1f);
             }
         }
     }
References TileEntity.ByID, Item.favorited, Find(), Recipe.FindRecipes(), FitsFoodPlatter(), Player.GamepadEnableGrappleCooldown(), Player.inventory, WorldGen.KillTile(), Main.netMode, PlaceItemInFrame(), Player.selectedItem, and NetMessage.SendData().
Referenced by Player.TileInteractionsUse().