Terraria: MS.Internal.Xml.Cache.XPathNode.GetParent
GetParent()
int MS.Internal.Xml.Cache.XPathNode.GetParent (out XPathNode[] pageNode) inline
Definition at line 121 of file XPathNode.cs.
    {
        pageNode = _info.ParentPage;
        return _idxParent;
    }
References MS.Internal.Xml.Cache.XPathNode._idxParent, MS.Internal.Xml.Cache.XPathNode._info, and MS.Internal.Xml.Cache.XPathNodeInfoAtom.ParentPage.
Referenced by MS.Internal.Xml.Cache.XPathNodeHelper.GetInScopeNamespaces(), MS.Internal.Xml.Cache.XPathNodeHelper.GetNonDescendant(), MS.Internal.Xml.Cache.XPathNodeHelper.GetParent(), MS.Internal.Xml.Cache.XPathNodeHelper.GetPreviousContentSibling(), MS.Internal.Xml.Cache.XPathDocumentNavigator.MoveToNextNamespace(), and MS.Internal.Xml.Cache.XPathDocumentBuilder.WriteEndElement().