Terraria: MS.Internal.Xml.Cache.XPathNode.GetSibling
GetSibling()
int MS.Internal.Xml.Cache.XPathNode.GetSibling (out XPathNode[] pageNode) inline
Definition at line 127 of file XPathNode.cs.
    {
        pageNode = _info.SiblingPage;
        return _idxSibling;
    }
References MS.Internal.Xml.Cache.XPathNode._idxSibling, MS.Internal.Xml.Cache.XPathNode._info, and MS.Internal.Xml.Cache.XPathNodeInfoAtom.SiblingPage.
Referenced by MS.Internal.Xml.Cache.XPathNodeHelper.GetContentSibling(), MS.Internal.Xml.Cache.XPathNodeHelper.GetContentSibling(), MS.Internal.Xml.Cache.XPathNodeHelper.GetElementSibling(), MS.Internal.Xml.Cache.XPathNodeHelper.GetNextAttribute(), and MS.Internal.Xml.Cache.XPathNodeHelper.GetNonDescendant().