Terraria: System.Security.Cryptography.ECDsaCng.GenerateKey
GenerateKey()
override void System.Security.Cryptography.ECDsaCng.GenerateKey (ECCurve curve) inline virtual
Reimplemented from System.Security.Cryptography.ECDsa.
Definition at line 190 of file ECDsaCng.cs.
    {
        curve.Validate();
        _core.DisposeKey();
        if (curve.IsNamed)
        {
            if (string.IsNullOrEmpty(curve.Oid.FriendlyName))
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_InvalidCurveOid, curve.Oid.Value));
            }
            CngAlgorithm cngAlgorithm = CngKey.EcdsaCurveNameToAlgorithm(curve.Oid.FriendlyName);
            if (CngKey.IsECNamedCurve(cngAlgorithm.Algorithm))
            {
                CngKey orGenerateKey = _core.GetOrGenerateKey(curve);
                ForceSetKeySize(orGenerateKey.KeySize);
                return;
            }
            int num = 0;
            if (cngAlgorithm == CngAlgorithm.ECDsaP256)
            {
                num = 256;
            }
            else if (cngAlgorithm == CngAlgorithm.ECDsaP384)
            {
                num = 384;
            }
            else
            {
                if (!(cngAlgorithm == CngAlgorithm.ECDsaP521))
                {
                    throw new ArgumentException(System.SR.Cryptography_InvalidKeySize);
                }
                num = 521;
            }
            _core.GetOrGenerateKey(num, cngAlgorithm);
            ForceSetKeySize(num);
        }
        else
        {
            if (!curve.IsExplicit)
            {
                throw new PlatformNotSupportedException(System.SR.Format(System.SR.Cryptography_CurveNotSupported, curve.CurveType.ToString()));
            }
            CngKey orGenerateKey2 = _core.GetOrGenerateKey(curve);
            ForceSetKeySize(orGenerateKey2.KeySize);
        }
    }
References System.Security.Cryptography.ECDsaCng._core, System.Security.Cryptography.CngAlgorithm.Algorithm, System.SR.Cryptography_CurveNotSupported, System.SR.Cryptography_InvalidCurveOid, System.SR.Cryptography_InvalidKeySize, System.Security.Cryptography.ECCurve.CurveType, Internal.Cryptography.CngAlgorithmCore.DisposeKey(), System.Security.Cryptography.CngKey.EcdsaCurveNameToAlgorithm(), System.Security.Cryptography.CngAlgorithm.ECDsaP256, System.Security.Cryptography.CngAlgorithm.ECDsaP384, System.Security.Cryptography.CngAlgorithm.ECDsaP521, System.Security.Cryptography.ECDsaCng.ForceSetKeySize(), System.SR.Format(), System.Security.Cryptography.Oid.FriendlyName, Internal.Cryptography.CngAlgorithmCore.GetOrGenerateKey(), System.Security.Cryptography.CngKey.IsECNamedCurve(), System.Security.Cryptography.ECCurve.IsExplicit, System.Security.Cryptography.ECCurve.IsNamed, System.Security.Cryptography.CngKey.KeySize, System.Security.Cryptography.ECCurve.Oid, System.Security.Cryptography.ECCurve.Validate(), and System.Security.Cryptography.Oid.Value.
Referenced by System.Security.Cryptography.ECDsaCng.ECDsaCng().