Terraria: System.Security.Cryptography.ECDsaCng.ProcessPkcs8Response
ProcessPkcs8Response()
void System.Security.Cryptography.ECDsaCng.ProcessPkcs8Response (System::Security::Cryptography::CngPkcs8::Pkcs8Response response) inline private
Definition at line 367 of file ECDsaCng.cs.
    {
        string algorithmGroup = response.GetAlgorithmGroup();
        if (algorithmGroup == "ECDSA" || algorithmGroup == "ECDH")
        {
            AcceptImport(response);
            return;
        }
        response.FreeKey();
        throw new CryptographicException(System.SR.Cryptography_NotValidPublicOrPrivateKey);
    }
References System.Security.Cryptography.ECDsaCng.AcceptImport(), and System.SR.Cryptography_NotValidPublicOrPrivateKey.
Referenced by System.Security.Cryptography.ECDsaCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsaCng.ImportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.ECDsaCng.ImportPkcs8PrivateKey().