Terraria: System.Security.Cryptography.ECDsaCng._core
_core
CngAlgorithmCore System.Security.Cryptography.ECDsaCng._core = new CngAlgorithmCore("ECDsaCng") private
Definition at line 9 of file ECDsaCng.cs.
Referenced by System.Security.Cryptography.ECDsaCng.Dispose(), System.Security.Cryptography.ECDsaCng.DisposeKey(), System.Security.Cryptography.ECDsaCng.GenerateKey(), System.Security.Cryptography.ECDsaCng.GetKey(), and System.Security.Cryptography.ECDsaCng.ThrowIfDisposed().