Terraria: System.Empty.Value
Value
readonly Empty System.Empty.Value = new Empty() static
Definition at line 5 of file Empty.cs.
Referenced by System.DefaultBinder.BindToField(), System.RuntimeType.InvokeMember(), and System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone().