Terraria: System.Net.Security.SslStreamCertificateContext.Create
Create() [3/3]
static SslStreamCertificateContext System.Net.Security.SslStreamCertificateContext.Create (X509Certificate2 target, X509Certificate2Collection? additionalCertificates, bool offline = false, SslCertificateTrust? trust = null) inline static
Definition at line 20 of file SslStreamCertificateContext.cs.
    {
        if (!target.HasPrivateKey)
        {
            throw new NotSupportedException(System.SR.net_ssl_io_no_server_cert);
        }
        X509Certificate2[] array = Array.Empty<X509Certificate2>();
        using (X509Chain x509Chain = new X509Chain())
        {
            if (additionalCertificates != null)
            {
                foreach (X509Certificate2 additionalCertificate in additionalCertificates)
                {
                    x509Chain.ChainPolicy.ExtraStore.Add((X509Certificate)additionalCertificate);
                }
            }
            x509Chain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllFlags;
            x509Chain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            x509Chain.ChainPolicy.DisableCertificateDownloads = offline;
            if (!x509Chain.Build(target) && System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(null, $"Failed to build chain for {target.Subject}", "Create");
            }
            int num = x509Chain.ChainElements.Count - 1;
            if (num >= 0)
            {
                if (num > 0 && x509Chain.ChainElements.Count > 1)
                {
                    array = new X509Certificate2[num];
                    for (int i = 0; i < num; i++)
                    {
                        array[i] = x509Chain.ChainElements[i + 1].Certificate;
                    }
                }
                x509Chain.ChainElements[0].Certificate.Dispose();
                for (int j = num + 1; j < x509Chain.ChainElements.Count; j++)
                {
                    x509Chain.ChainElements[j].Certificate.Dispose();
                }
            }
        }
        return new SslStreamCertificateContext(target, array, trust);
    }
References System.Net.Security.SslStreamCertificateContext.SslStreamCertificateContext(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Add(), System.array, System.Security.Cryptography.X509Certificates.X509Chain.Build(), System.Security.Cryptography.X509Certificates.X509Chain.ChainElements, System.Security.Cryptography.X509Certificates.X509Chain.ChainPolicy, System.Security.Cryptography.X509Certificates.X509ChainElementCollection.Count, System.Net.NetEventSource.Error(), System.Security.Cryptography.X509Certificates.X509ChainPolicy.ExtraStore, System.Security.Cryptography.X509Certificates.X509Certificate2.HasPrivateKey, System.Net.NetEventSource.Log, and System.SR.net_ssl_io_no_server_cert.