Terraria: System.Net.LazyAsyncResult.Complete
Complete() [3/3]
virtual void System.Net.LazyAsyncResult.Complete (IntPtr userToken) inline protected virtual inherited
Reimplemented in System.Net.ContextAwareResult, and System.Net.ContextAwareResult.
Definition at line 182 of file LazyAsyncResult.cs.
    {
        bool flag = false;
        ThreadContext currentThreadContext = CurrentThreadContext;
        try
        {
            currentThreadContext._nestedIOCount++;
            if (_asyncCallback != null)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, "Invoking callback", "Complete");
                }
                if (currentThreadContext._nestedIOCount >= 50)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(this, "*** OFFLOADED the user callback ****", "Complete");
                    }
                    Task.Factory.StartNew(delegate(object s)
                    {
                        WorkerThreadComplete(s);
                    }, this, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
                    flag = true;
                }
                else
                {
                    _asyncCallback(this);
                }
            }
            else if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Info(this, "No callback to invoke", "Complete");
            }
        }
        finally
        {
            currentThreadContext._nestedIOCount--;
            if (!flag)
            {
                Cleanup();
            }
        }
    }
References System.Net.LazyAsyncResult._asyncCallback, System.Net.LazyAsyncResult.Cleanup(), System.Net.LazyAsyncResult.CurrentThreadContext, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Net.NetEventSource.Info(), System.Net.NetEventSource.Log, System.Threading.CancellationToken.None, System.s, and System.Net.LazyAsyncResult.WorkerThreadComplete().