Terraria: System.Net.LazyAsyncResult.WaitForCompletion
WaitForCompletion() [3/3]
object System.Net.LazyAsyncResult.WaitForCompletion (bool snap) inline private inherited
Definition at line 249 of file LazyAsyncResult.cs.
    {
        ManualResetEvent waitHandle = null;
        bool flag = false;
        if (!(snap ? IsCompleted : InternalPeekCompleted))
        {
            waitHandle = (ManualResetEvent)_event;
            if (waitHandle == null)
            {
                flag = LazilyCreateEvent(out waitHandle);
            }
        }
        if (waitHandle != null)
        {
            try
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    System.Net.NetEventSource.Info(this, $"Waiting for completion event {waitHandle}", "WaitForCompletion");
                }
                waitHandle.WaitOne(-1);
            }
            catch (ObjectDisposedException)
            {
            }
            finally
            {
                if (flag && !_userEvent)
                {
                    ManualResetEvent manualResetEvent = (ManualResetEvent)_event;
                    _event = null;
                    if (!_userEvent)
                    {
                        manualResetEvent?.Dispose();
                    }
                }
            }
        }
        SpinWait spinWait = default(SpinWait);
        while (_result == DBNull.Value)
        {
            spinWait.SpinOnce();
        }
        return _result;
    }
References System.Net.LazyAsyncResult._event, System.Net.LazyAsyncResult._result, System.Net.LazyAsyncResult._userEvent, System.Threading.WaitHandle.Dispose(), System.Net.NetEventSource.Info(), System.Net.LazyAsyncResult.InternalPeekCompleted, System.Net.LazyAsyncResult.IsCompleted, System.Net.LazyAsyncResult.LazilyCreateEvent(), System.Net.NetEventSource.Log, System.Threading.SpinWait.SpinOnce(), System.DBNull.Value, and System.Threading.WaitHandle.WaitOne().