Terraria: System.Net.LazyAsyncResult.ProtectedInvokeCallback
ProtectedInvokeCallback() [3/3]
void System.Net.LazyAsyncResult.ProtectedInvokeCallback (object result, IntPtr userToken) inline protected inherited
Definition at line 144 of file LazyAsyncResult.cs.
    {
        if (result == DBNull.Value)
        {
            throw new ArgumentNullException("result");
        }
        if (((uint)_intCompleted & 0x7FFFFFFFu) != 0 || (Interlocked.Increment(ref _intCompleted) & 0x7FFFFFFF) != 1)
        {
            return;
        }
        if (_result == DBNull.Value)
        {
            _result = result;
        }
        ManualResetEvent manualResetEvent = (ManualResetEvent)_event;
        if (manualResetEvent != null)
        {
            try
            {
                manualResetEvent.Set();
            }
            catch (ObjectDisposedException)
            {
            }
        }
        Complete(userToken);
    }
References System.Net.LazyAsyncResult._event, System.Net.LazyAsyncResult._intCompleted, System.Net.LazyAsyncResult._result, System.Net.LazyAsyncResult.Complete(), System.Threading.Interlocked.Increment(), System.Threading.EventWaitHandle.Set(), and System.DBNull.Value.