Terraria: System.Net.LazyAsyncResult.InternalCleanup
InternalCleanup()
void System.Net.LazyAsyncResult.InternalCleanup () inline package inherited
Definition at line 321 of file LazyAsyncResult.cs.
    {
        if ((_intCompleted & 0x7FFFFFFF) == 0 && (Interlocked.Increment(ref _intCompleted) & 0x7FFFFFFF) == 1)
        {
            _result = null;
            Cleanup();
        }
    }
References System.Net.LazyAsyncResult._intCompleted, System.Net.LazyAsyncResult._result, System.Net.LazyAsyncResult.Cleanup(), and System.Threading.Interlocked.Increment().
Referenced by System.Net.HttpRequestStream.BeginReadCore(), and System.Net.HttpResponseStream.BeginWriteCore().