Terraria: System.Xml.XmlBinaryReaderSession.Add
Add()
XmlDictionaryString System.Xml.XmlBinaryReaderSession.Add (int id, string value) inline
Definition at line 15 of file XmlBinaryReaderSession.cs.
    {
        if (id < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("id", System.SR.XmlInvalidID));
        }
        if (value == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("value");
        }
        if (TryLookup(id, out XmlDictionaryString result))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlIDDefined));
        }
        result = new XmlDictionaryString(this, value, id);
        if (id >= 2048)
        {
            if (_stringDict == null)
            {
                _stringDict = new Dictionary<int, XmlDictionaryString>();
            }
            _stringDict.Add(id, result);
        }
        else
        {
            if (_strings == null)
            {
                _strings = new XmlDictionaryString[Math.Max(id + 1, 16)];
            }
            else if (id >= _strings.Length)
            {
                XmlDictionaryString[] array = new XmlDictionaryString[Math.Min(Math.Max(id + 1, _strings.Length * 2), 2048)];
                Array.Copy(_strings, array, _strings.Length);
                _strings = array;
            }
            _strings[id] = result;
        }
        return result;
    }
References System.Xml.XmlBinaryReaderSession._stringDict, System.Xml.XmlBinaryReaderSession._strings, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Array.Copy(), System.Xml.Dictionary, System.Math.Max(), System.Math.Min(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlBinaryReaderSession.TryLookup(), System.value, System.SR.XmlIDDefined, and System.SR.XmlInvalidID.