Terraria: System.Xml.XmlBinaryReaderSession.TryLookup
TryLookup() [1/3]
bool System.Xml.XmlBinaryReaderSession.TryLookup (int key, [NotNullWhen(true)] out XmlDictionaryString? result) inline
Implements System.Xml.IXmlDictionary.
Definition at line 55 of file XmlBinaryReaderSession.cs.
    {
        if (_strings != null && key >= 0 && key < _strings.Length)
        {
            result = _strings[key];
            return result != null;
        }
        if (key >= 2048 && _stringDict != null)
        {
            return _stringDict.TryGetValue(key, out result);
        }
        result = null;
        return false;
    }
References System.Xml.XmlBinaryReaderSession._stringDict, System.Xml.XmlBinaryReaderSession._strings, System.key, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Xml.XmlBinaryReaderSession.Add(), and System.Xml.XmlBufferReader.ReadDictionaryKey().