Terraria: System.Linq.Expressions.Interpreter.LabelInfo.ValidateJump
ValidateJump()
void System.Linq.Expressions.Interpreter.LabelInfo.ValidateJump (LabelScopeInfo reference) inline private
Definition at line 67 of file LabelInfo.cs.
    {
        for (LabelScopeInfo labelScopeInfo = reference; labelScopeInfo != null; labelScopeInfo = labelScopeInfo.Parent)
        {
            if (DefinedIn(labelScopeInfo))
            {
                return;
            }
            if (labelScopeInfo.Kind == LabelScopeKind.Finally || labelScopeInfo.Kind == LabelScopeKind.Filter)
            {
                break;
            }
        }
        _acrossBlockJump = true;
        if (_node != null && _node.Type != typeof(void))
        {
            throw Error.NonLocalJumpWithValue(_node.Name);
        }
        if (HasMultipleDefinitions)
        {
            throw Error.AmbiguousJump(_node.Name);
        }
        LabelScopeInfo labelScopeInfo2 = FirstDefinition();
        LabelScopeInfo labelScopeInfo3 = CommonNode(labelScopeInfo2, reference, (LabelScopeInfo b) => b.Parent);
        for (LabelScopeInfo labelScopeInfo4 = reference; labelScopeInfo4 != labelScopeInfo3; labelScopeInfo4 = labelScopeInfo4.Parent)
        {
            if (labelScopeInfo4.Kind == LabelScopeKind.Finally)
            {
                throw Error.ControlCannotLeaveFinally();
            }
            if (labelScopeInfo4.Kind == LabelScopeKind.Filter)
            {
                throw Error.ControlCannotLeaveFilterTest();
            }
        }
        for (LabelScopeInfo labelScopeInfo5 = labelScopeInfo2; labelScopeInfo5 != labelScopeInfo3; labelScopeInfo5 = labelScopeInfo5.Parent)
        {
            if (!labelScopeInfo5.CanJumpInto)
            {
                if (labelScopeInfo5.Kind == LabelScopeKind.Expression)
                {
                    throw Error.ControlCannotEnterExpression();
                }
                throw Error.ControlCannotEnterTry();
            }
        }
    }
References System.Linq.Expressions.Interpreter.LabelInfo._acrossBlockJump, System.Linq.Expressions.Interpreter.LabelInfo._node, System.Linq.Expressions.Error.AmbiguousJump(), System.Linq.Expressions.Error.ControlCannotEnterExpression(), System.Linq.Expressions.Error.ControlCannotEnterTry(), System.Linq.Expressions.Error.ControlCannotLeaveFilterTest(), System.Linq.Expressions.Error.ControlCannotLeaveFinally(), System.Linq.Expressions.Interpreter.LabelInfo.DefinedIn(), System.Linq.Expressions.Interpreter.LabelInfo.FirstDefinition(), System.Linq.Expressions.Interpreter.LabelInfo.HasMultipleDefinitions, System.Linq.Expressions.LabelTarget.Name, System.Linq.Expressions.Error.NonLocalJumpWithValue(), and System.Linq.Expressions.LabelTarget.Type.
Referenced by System.Linq.Expressions.Interpreter.LabelInfo.Define(), and System.Linq.Expressions.Interpreter.LabelInfo.Reference().