Terraria: UIReportsPage.BuildPage
BuildPage()
void UIReportsPage.BuildPage () inline private
     {
         RemoveAllChildren();
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.8f);
         uIElement.MaxWidth.Set(500f, 0f);
         uIElement.MinWidth.Set(300f, 0f);
         uIElement.Top.Set(230f, 0f);
         uIElement.Height.Set(0f - uIElement.Top.Pixels, 1f);
         uIElement.HAlign = 0.5f;
         Append(uIElement);
         UIPanel uIPanel = new UIPanel();
         uIPanel.Width.Set(0f, 1f);
         uIPanel.Height.Set(-110f, 1f);
         uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
         uIElement.Append(uIPanel);
         UIElement uIElement2 = new UIElement
         {
             Width = StyleDimension.Fill,
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f)
         };
         uIPanel.Append(uIElement2);
         UIElement uIElement3 = new UIElement
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(28f, 0f)
         };
         uIElement3.SetPadding(0f);
         uIElement2.Append(uIElement3);
         UIText uIText = new UIText(Language.GetTextValue("UI.ReportsPage"), 0.7f, large: true);
         uIText.HAlign = 0.5f;
         uIText.VAlign = 0f;
         uIElement3.Append(uIText);
         UIElement uIElement4 = new UIElement
         {
             HAlign = 0.5f,
             VAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(-40f, 1f),
             Top = new StyleDimension(-2f, 0f)
         };
         uIElement2.Append(uIElement4);
         _container = uIElement4;
         float num = 0f;
         UISlicedImage uISlicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1))
         {
             HAlign = 0.5f,
             VAlign = 1f,
             Width = StyleDimension.FromPixelsAndPercent((0f - num) * 2f, 1f),
             Left = StyleDimension.FromPixels(0f - num),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Top = StyleDimension.FromPixels(2f)
         };
         uISlicedImage.SetSliceDepths(10);
         uISlicedImage.Color = Color.LightGray * 0.5f;
         uIElement4.Append(uISlicedImage);
         UIList uIList = new UIList
         {
             HAlign = 0.5f,
             VAlign = 0f,
             Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             PaddingRight = 20f
         };
         uIList.ListPadding = 40f;
         uIList.ManualSortMethod = ManualIfnoSortingMethod;
         UIElement item = new UIElement();
         uIList.Add(item);
         PopulateLogs(uIList);
         uIElement4.Append(uIList);
         _list = uIList;
         UIScrollbar uIScrollbar = new UIScrollbar();
         uIScrollbar.SetView(100f, 1000f);
         uIScrollbar.Height.Set(0f, 1f);
         uIScrollbar.HAlign = 1f;
         _scrollbar = uIScrollbar;
         uIList.SetScrollbar(uIScrollbar);
         uIScrollbar.GoToBottom();
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
         uITextPanel.Width.Set(-10f, 0.5f);
         uITextPanel.Height.Set(50f, 0f);
         uITextPanel.VAlign = 1f;
         uITextPanel.HAlign = 0.5f;
         uITextPanel.Top.Set(-45f, 0f);
         uITextPanel.OnMouseOver += FadedMouseOver;
         uITextPanel.OnMouseOut += FadedMouseOut;
         uITextPanel.OnLeftClick += GoBackClick;
         uITextPanel.SetSnapPoint("GoBack", 0);
         uIElement.Append(uITextPanel);
     }
References UIElement.UIElement(), _container, _list, _scrollbar, UIList.Add(), UIElement.Append(), Main.Assets, UIPanel.BackgroundColor, UISlicedImage.Color, Color, FadedMouseOut(), FadedMouseOver(), StyleDimension.Fill, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), Language.GetTextValue(), GoBackClick(), UIScrollbar.GoToBottom(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIList.ListPadding, ManualIfnoSortingMethod(), UIList.ManualSortMethod, UIElement.MaxWidth, UIElement.MinWidth, UIElement.PaddingRight, StyleDimension.Pixels, PopulateLogs(), UIElement.RemoveAllChildren(), StyleDimension.Set(), UIElement.SetPadding(), UIList.SetScrollbar(), UISlicedImage.SetSliceDepths(), UIScrollbar.SetView(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by OnInitialize().