Terraria: System.Xml.XmlLoader.LoadDefaultAttribute
LoadDefaultAttribute()
XmlAttribute System.Xml.XmlLoader.LoadDefaultAttribute () inline private
Definition at line 247 of file XmlLoader.cs.
    {
        XmlReader reader = _reader;
        XmlAttribute xmlAttribute = _doc.CreateDefaultAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
        IXmlSchemaInfo schemaInfo = reader.SchemaInfo;
        if (schemaInfo != null)
        {
            xmlAttribute.XmlName = _doc.AddAttrXmlName(xmlAttribute.Prefix, xmlAttribute.LocalName, xmlAttribute.NamespaceURI, schemaInfo);
        }
        LoadAttributeValue(xmlAttribute, direct: false);
        if (xmlAttribute is XmlUnspecifiedAttribute xmlUnspecifiedAttribute)
        {
            xmlUnspecifiedAttribute.SetSpecified(f: false);
        }
        return xmlAttribute;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlDocument.AddAttrXmlName(), System.Xml.XmlDocument.CreateDefaultAttribute(), System.Xml.Dictionary, System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.Prefix, and System.Xml.XmlReader.SchemaInfo.
Referenced by System.Xml.XmlLoader.LoadAttributeNode().