Terraria: System.Xml.XmlLoader.GetContext
GetContext()
XmlParserContext System.Xml.XmlLoader.GetContext (XmlNode node) inline private
Definition at line 564 of file XmlLoader.cs.
    {
        string text = null;
        XmlSpace xmlSpace = XmlSpace.None;
        XmlDocumentType documentType = _doc.DocumentType;
        string baseURI = _doc.BaseURI;
        HashSet<string> hashSet = new HashSet<string>();
        XmlNameTable nameTable = _doc.NameTable;
        XmlNamespaceManager xmlNamespaceManager = new XmlNamespaceManager(nameTable);
        bool flag = false;
        while (node != null && node != _doc)
        {
            if (node is XmlElement { HasAttributes: not false } xmlElement)
            {
                xmlNamespaceManager.PushScope();
                foreach (XmlAttribute attribute in xmlElement.Attributes)
                {
                    if (attribute.Prefix == _doc.strXmlns && !hashSet.Contains(attribute.LocalName))
                    {
                        hashSet.Add(attribute.LocalName);
                        xmlNamespaceManager.AddNamespace(attribute.LocalName, attribute.Value);
                    }
                    else if (!flag && attribute.Prefix.Length == 0 && attribute.LocalName == _doc.strXmlns)
                    {
                        xmlNamespaceManager.AddNamespace(string.Empty, attribute.Value);
                        flag = true;
                    }
                    else if (xmlSpace == XmlSpace.None && attribute.Prefix == _doc.strXml && attribute.LocalName == _doc.strSpace)
                    {
                        if (attribute.Value == "default")
{
                            xmlSpace = XmlSpace.Default;
                        }
                        else if (attribute.Value == "preserve")
{
                            xmlSpace = XmlSpace.Preserve;
                        }
                    }
                    else if (text == null && attribute.Prefix == _doc.strXml && attribute.LocalName == _doc.strLang)
                    {
                        text = attribute.Value;
                    }
                }
            }
            node = node.ParentNode;
        }
        return new XmlParserContext(nameTable, xmlNamespaceManager, documentType?.Name, documentType?.PublicId, documentType?.SystemId, documentType?.InternalSubset, baseURI, text, xmlSpace);
    }
References System.Xml.XmlLoader._doc, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.XmlDocument.BaseURI, System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Dictionary, System.Xml.XmlDocument.DocumentType, System.Xml.Name, System.Xml.XmlDocument.NameTable, System.Xml.XmlDocument.strLang, System.Xml.XmlDocument.strSpace, System.Xml.XmlDocument.strXml, System.Xml.XmlDocument.strXmlns, and System.text.
Referenced by System.Xml.XmlLoader.ParsePartialContent().