Terraria: System.Xml.XmlLoader.ParsePartialContent
ParsePartialContent()
XmlNamespaceManager System.Xml.XmlLoader.ParsePartialContent (XmlNode parentNode, string innerxmltext, XmlNodeType nt) inline package
Definition at line 613 of file XmlLoader.cs.
    {
        _doc = parentNode.OwnerDocument;
        XmlParserContext context = GetContext(parentNode);
        _reader = CreateInnerXmlReader(innerxmltext, nt, context, _doc);
        try
        {
            _preserveWhitespace = true;
            bool isLoading = _doc.IsLoading;
            _doc.IsLoading = true;
            if (nt == XmlNodeType.Entity)
            {
                XmlNode xmlNode = null;
                while (_reader.Read() && (xmlNode = LoadNodeDirect()) != null)
                {
                    parentNode.AppendChildForLoad(xmlNode, _doc);
                }
            }
            else
            {
                XmlNode xmlNode2 = null;
                while (_reader.Read() && (xmlNode2 = LoadNode(skipOverWhitespace: true)) != null)
                {
                    parentNode.AppendChildForLoad(xmlNode2, _doc);
                }
            }
            _doc.IsLoading = isLoading;
        }
        finally
        {
            _reader.Close();
        }
        return context.NamespaceManager;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._preserveWhitespace, System.Xml.XmlLoader._reader, System.Xml.XmlNode.AppendChildForLoad(), System.Xml.XmlReader.Close(), System.Xml.XmlLoader.CreateInnerXmlReader(), System.Xml.Dictionary, System.Xml.XmlLoader.GetContext(), System.Xml.XmlDocument.IsLoading, System.Xml.XmlLoader.LoadNode(), System.Xml.XmlLoader.LoadNodeDirect(), System.Xml.XmlParserContext.NamespaceManager, System.Xml.XmlNode.OwnerDocument, and System.Xml.XmlReader.Read().
Referenced by System.Xml.XmlLoader.ExpandEntity(), System.Xml.XmlLoader.ExpandEntityReference(), System.Xml.XmlLoader.LoadInnerXmlAttribute(), and System.Xml.XmlLoader.LoadInnerXmlElement().