Terraria: System.Xml.XmlLoader.ParseDocumentType
ParseDocumentType() [1/2]
void System.Xml.XmlLoader.ParseDocumentType (XmlDocumentType dtNode) inline package
Definition at line 478 of file XmlLoader.cs.
    {
        XmlDocument ownerDocument = dtNode.OwnerDocument;
        if (ownerDocument.HasSetResolver)
        {
            ParseDocumentType(dtNode, bUseResolver: true, ownerDocument.GetResolver());
        }
        else
        {
            ParseDocumentType(dtNode, bUseResolver: false, null);
        }
    }
References System.Xml.XmlLoader.ParseDocumentType().
Referenced by System.Xml.XmlLoader.LoadDocumentTypeNode(), and System.Xml.XmlLoader.ParseDocumentType().