Terraria: System.Xml.XmlLoader.LoadNodeDirect
LoadNodeDirect()
XmlNode System.Xml.XmlLoader.LoadNodeDirect () inline private
Definition at line 379 of file XmlLoader.cs.
    {
        XmlReader reader = _reader;
        XmlNode xmlNode = null;
        do
        {
            XmlNode xmlNode2 = null;
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
            {
                bool isEmptyElement = _reader.IsEmptyElement;
                XmlElement xmlElement = new XmlElement(_reader.Prefix, _reader.LocalName, _reader.NamespaceURI, _doc);
                xmlElement.IsEmpty = isEmptyElement;
                if (_reader.MoveToFirstAttribute())
                {
                    XmlAttributeCollection attributes = xmlElement.Attributes;
                    do
                    {
                        XmlAttribute node = LoadAttributeNodeDirect();
                        attributes.Append(node);
                    }
                    while (reader.MoveToNextAttribute());
                }
                if (!isEmptyElement)
                {
                    xmlNode.AppendChildForLoad(xmlElement, _doc);
                    xmlNode = xmlElement;
                    continue;
                }
                xmlNode2 = xmlElement;
                break;
            }
            case XmlNodeType.EndElement:
                if (xmlNode.ParentNode == null)
                {
                    return xmlNode;
                }
                xmlNode = xmlNode.ParentNode;
                continue;
            case XmlNodeType.EntityReference:
                xmlNode2 = LoadEntityReferenceNode(direct: true);
                break;
            case XmlNodeType.Attribute:
                xmlNode2 = LoadAttributeNodeDirect();
                break;
            case XmlNodeType.SignificantWhitespace:
                xmlNode2 = new XmlSignificantWhitespace(_reader.Value, _doc);
                break;
            case XmlNodeType.Whitespace:
                if (_preserveWhitespace)
                {
                    xmlNode2 = new XmlWhitespace(_reader.Value, _doc);
                    break;
                }
                continue;
            case XmlNodeType.Text:
                xmlNode2 = new XmlText(_reader.Value, _doc);
                break;
            case XmlNodeType.CDATA:
                xmlNode2 = new XmlCDataSection(_reader.Value, _doc);
                break;
            case XmlNodeType.ProcessingInstruction:
                xmlNode2 = new XmlProcessingInstruction(_reader.Name, _reader.Value, _doc);
                break;
            case XmlNodeType.Comment:
                xmlNode2 = new XmlComment(_reader.Value, _doc);
                break;
            default:
                throw UnexpectedNodeType(_reader.NodeType);
            case XmlNodeType.EndEntity:
                continue;
            }
            if (xmlNode != null)
            {
                xmlNode.AppendChildForLoad(xmlNode2, _doc);
                continue;
            }
            return xmlNode2;
        }
        while (reader.Read());
        return null;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._preserveWhitespace, System.Xml.XmlLoader._reader, System.Xml.XmlAttributeCollection.Append(), System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlLoader.LoadAttributeNodeDirect(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.XmlLoader.UnexpectedNodeType(), System.Xml.XmlReader.Value, and System.Xml.XmlText.
Referenced by System.Xml.XmlLoader.LoadEntityReferenceNode(), and System.Xml.XmlLoader.ParsePartialContent().