Terraria: System.Xml.XmlLoader.LoadAttributeValue
LoadAttributeValue()
void System.Xml.XmlLoader.LoadAttributeValue (XmlNode parent, bool direct) inline private
Definition at line 264 of file XmlLoader.cs.
    {
        XmlReader reader = _reader;
        while (reader.ReadAttributeValue())
        {
            XmlNode xmlNode;
            switch (reader.NodeType)
            {
            case XmlNodeType.Text:
                xmlNode = (direct ? new XmlText(reader.Value, _doc) : _doc.CreateTextNode(reader.Value));
                break;
            case XmlNodeType.EndEntity:
                return;
            case XmlNodeType.EntityReference:
                xmlNode = (direct ? new XmlEntityReference(_reader.LocalName, _doc) : _doc.CreateEntityReference(_reader.LocalName));
                if (reader.CanResolveEntity)
                {
                    reader.ResolveEntity();
                    LoadAttributeValue(xmlNode, direct);
                    if (xmlNode.FirstChild == null)
                    {
                        xmlNode.AppendChildForLoad(direct ? new XmlText(string.Empty) : _doc.CreateTextNode(string.Empty), _doc);
                    }
                }
                break;
            default:
                throw UnexpectedNodeType(reader.NodeType);
            }
            parent.AppendChildForLoad(xmlNode, _doc);
        }
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlNode.AppendChildForLoad(), System.Xml.XmlReader.CanResolveEntity, System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.Xml.XmlLoader.UnexpectedNodeType(), System.Xml.XmlReader.Value, and System.Xml.XmlText.
Referenced by System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeNodeDirect(), System.Xml.XmlLoader.LoadAttributeValue(), and System.Xml.XmlLoader.LoadDefaultAttribute().