Terraria: System.Xml.XmlLoader.RemoveDuplicateNamespace
RemoveDuplicateNamespace()
void System.Xml.XmlLoader.RemoveDuplicateNamespace (XmlElement elem, XmlNamespaceManager mgr, bool fCheckElemAttrs) inline private
Definition at line 662 of file XmlLoader.cs.
    {
        mgr.PushScope();
        XmlAttributeCollection attributes = elem.Attributes;
        int count = attributes.Count;
        if (fCheckElemAttrs && count > 0)
        {
            for (int num = count - 1; num >= 0; num--)
            {
                XmlAttribute xmlAttribute = attributes[num];
                if (xmlAttribute.Prefix == _doc.strXmlns)
                {
                    string text = mgr.LookupNamespace(xmlAttribute.LocalName);
                    if (text != null)
                    {
                        if (xmlAttribute.Value == text)
{
                            elem.Attributes.RemoveNodeAt(num);
                        }
                    }
                    else
                    {
                        mgr.AddNamespace(xmlAttribute.LocalName, xmlAttribute.Value);
                    }
                }
                else if (xmlAttribute.Prefix.Length == 0 && xmlAttribute.LocalName == _doc.strXmlns)
                {
                    string defaultNamespace = mgr.DefaultNamespace;
                    if (defaultNamespace != null)
                    {
                        if (xmlAttribute.Value == defaultNamespace)
{
                            elem.Attributes.RemoveNodeAt(num);
                        }
                    }
                    else
                    {
                        mgr.AddNamespace(xmlAttribute.LocalName, xmlAttribute.Value);
                    }
                }
            }
        }
        for (XmlNode xmlNode = elem.FirstChild; xmlNode != null; xmlNode = xmlNode.NextSibling)
        {
            if (xmlNode is XmlElement elem2)
            {
                RemoveDuplicateNamespace(elem2, mgr, fCheckElemAttrs: true);
            }
        }
        mgr.PopScope();
    }
References System.Xml.XmlLoader._doc, System.count, System.Xml.XmlAttributeCollection.Count, System.Xml.XmlLoader.RemoveDuplicateNamespace(), System.Xml.XmlDocument.strXmlns, and System.text.
Referenced by System.Xml.XmlLoader.LoadInnerXmlElement(), and System.Xml.XmlLoader.RemoveDuplicateNamespace().