Terraria: System.Xml.XmlLoader.LoadAttributeNode
LoadAttributeNode()
XmlAttribute System.Xml.XmlLoader.LoadAttributeNode () inline private
Definition at line 206 of file XmlLoader.cs.
    {
        XmlReader reader = _reader;
        if (reader.IsDefault)
        {
            return LoadDefaultAttribute();
        }
        XmlAttribute xmlAttribute = _doc.CreateAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
        IXmlSchemaInfo schemaInfo = reader.SchemaInfo;
        if (schemaInfo != null)
        {
            xmlAttribute.XmlName = _doc.AddAttrXmlName(xmlAttribute.Prefix, xmlAttribute.LocalName, xmlAttribute.NamespaceURI, schemaInfo);
        }
        while (reader.ReadAttributeValue())
        {
            XmlNode xmlNode;
            switch (reader.NodeType)
            {
            case XmlNodeType.Text:
                xmlNode = _doc.CreateTextNode(reader.Value);
                break;
            case XmlNodeType.EntityReference:
                xmlNode = _doc.CreateEntityReference(reader.LocalName);
                if (reader.CanResolveEntity)
                {
                    reader.ResolveEntity();
                    LoadAttributeValue(xmlNode, direct: false);
                    if (xmlNode.FirstChild == null)
                    {
                        xmlNode.AppendChildForLoad(_doc.CreateTextNode(string.Empty), _doc);
                    }
                }
                break;
            default:
                throw UnexpectedNodeType(reader.NodeType);
            }
            xmlAttribute.AppendChildForLoad(xmlNode, _doc);
        }
        return xmlAttribute;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlDocument.AddAttrXmlName(), System.Xml.XmlReader.CanResolveEntity, System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlReader.IsDefault, System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.XmlLoader.LoadDefaultAttribute(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.Xml.XmlReader.SchemaInfo, System.Xml.XmlLoader.UnexpectedNodeType(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlLoader.LoadNode().