Terraria: System.Xml.XmlLoader.LoadEntityReferenceNode
LoadEntityReferenceNode()
XmlEntityReference System.Xml.XmlLoader.LoadEntityReferenceNode (bool direct) inline private
Definition at line 296 of file XmlLoader.cs.
    {
        XmlEntityReference xmlEntityReference = (direct ? new XmlEntityReference(_reader.Name, _doc) : _doc.CreateEntityReference(_reader.Name));
        if (_reader.CanResolveEntity)
        {
            _reader.ResolveEntity();
            while (_reader.Read() && _reader.NodeType != XmlNodeType.EndEntity)
            {
                XmlNode xmlNode = (direct ? LoadNodeDirect() : LoadNode(skipOverWhitespace: false));
                if (xmlNode != null)
                {
                    xmlEntityReference.AppendChildForLoad(xmlNode, _doc);
                }
            }
            if (xmlEntityReference.LastChild == null)
            {
                xmlEntityReference.AppendChildForLoad(_doc.CreateTextNode(string.Empty), _doc);
            }
        }
        return xmlEntityReference;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlReader.CanResolveEntity, System.Xml.XmlDocument.CreateEntityReference(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlLoader.LoadNode(), System.Xml.XmlLoader.LoadNodeDirect(), System.Xml.XmlReader.Name, System.Xml.XmlReader.Read(), and System.Xml.XmlReader.ResolveEntity().
Referenced by System.Xml.XmlLoader.LoadNode(), and System.Xml.XmlLoader.LoadNodeDirect().