Terraria: System.Xml.XmlLoader.LoadDocumentType
LoadDocumentType()
void System.Xml.XmlLoader.LoadDocumentType (IDtdInfo dtdInfo, XmlDocumentType dtNode) inline private
Definition at line 507 of file XmlLoader.cs.
    {
        if (!(dtdInfo is SchemaInfo schemaInfo))
        {
            throw new XmlException(System.SR.Xml_InternalError, string.Empty);
        }
        dtNode.DtdSchemaInfo = schemaInfo;
        if (schemaInfo == null)
        {
            return;
        }
        _doc.DtdSchemaInfo = schemaInfo;
        if (schemaInfo.Notations != null)
        {
            foreach (SchemaNotation value3 in schemaInfo.Notations.Values)
            {
                dtNode.Notations.SetNamedItem(new XmlNotation(value3.Name.Name, value3.Pubid, value3.SystemLiteral, _doc));
            }
        }
        if (schemaInfo.GeneralEntities != null)
        {
            foreach (SchemaEntity value4 in schemaInfo.GeneralEntities.Values)
            {
                XmlEntity xmlEntity = new XmlEntity(value4.Name.Name, value4.Text, value4.Pubid, value4.Url, value4.NData.IsEmpty ? null : value4.NData.Name, _doc);
                xmlEntity.SetBaseURI(value4.DeclaredURI);
                dtNode.Entities.SetNamedItem(xmlEntity);
            }
        }
        if (schemaInfo.ParameterEntities != null)
        {
            foreach (SchemaEntity value5 in schemaInfo.ParameterEntities.Values)
            {
                XmlEntity xmlEntity2 = new XmlEntity(value5.Name.Name, value5.Text, value5.Pubid, value5.Url, value5.NData.IsEmpty ? null : value5.NData.Name, _doc);
                xmlEntity2.SetBaseURI(value5.DeclaredURI);
                dtNode.Entities.SetNamedItem(xmlEntity2);
            }
        }
        _doc.Entities = dtNode.Entities;
        foreach (KeyValuePair<XmlQualifiedName, SchemaElementDecl> elementDecl in schemaInfo.ElementDecls)
        {
            SchemaElementDecl value = elementDecl.Value;
            if (value.AttDefs == null)
            {
                continue;
            }
            foreach (KeyValuePair<XmlQualifiedName, SchemaAttDef> attDef in value.AttDefs)
            {
                SchemaAttDef value2 = attDef.Value;
                if (value2.Datatype.TokenizedType == XmlTokenizedType.ID)
                {
                    _doc.AddIdInfo(_doc.AddXmlName(value.Prefix, value.Name.Name, string.Empty, null), _doc.AddAttrXmlName(value2.Prefix, value2.Name.Name, string.Empty, null));
                    break;
                }
            }
        }
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlDocument.AddAttrXmlName(), System.Xml.XmlDocument.AddIdInfo(), System.Xml.XmlDocument.AddXmlName(), System.Xml.Dictionary, System.value, System.Collections.Generic.Dictionary< TKey, TValue >.Values, System.SR.Xml_InternalError, and System.Xml.XmlException.
Referenced by System.Xml.XmlLoader.LoadDocumentTypeNode(), and System.Xml.XmlLoader.ParseDocumentType().