Terraria: System.Xml.XmlLoader.LoadNode
LoadNode()
XmlNode System.Xml.XmlLoader.LoadNode (bool skipOverWhitespace) inline private
Definition at line 88 of file XmlLoader.cs.
    {
        XmlReader reader = _reader;
        XmlNode xmlNode = null;
        do
        {
            XmlNode xmlNode2 = null;
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
            {
                bool isEmptyElement = reader.IsEmptyElement;
                XmlElement xmlElement2 = _doc.CreateElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                xmlElement2.IsEmpty = isEmptyElement;
                if (reader.MoveToFirstAttribute())
                {
                    XmlAttributeCollection attributes = xmlElement2.Attributes;
                    do
                    {
                        XmlAttribute node = LoadAttributeNode();
                        attributes.Append(node);
                    }
                    while (reader.MoveToNextAttribute());
                    reader.MoveToElement();
                }
                if (!isEmptyElement)
                {
                    xmlNode?.AppendChildForLoad(xmlElement2, _doc);
                    xmlNode = xmlElement2;
                    continue;
                }
                IXmlSchemaInfo schemaInfo = reader.SchemaInfo;
                if (schemaInfo != null)
                {
                    xmlElement2.XmlName = _doc.AddXmlName(xmlElement2.Prefix, xmlElement2.LocalName, xmlElement2.NamespaceURI, schemaInfo);
                }
                xmlNode2 = xmlElement2;
                break;
            }
            case XmlNodeType.EndElement:
            {
                if (xmlNode == null)
                {
                    return null;
                }
                IXmlSchemaInfo schemaInfo = reader.SchemaInfo;
                if (schemaInfo != null && xmlNode is XmlElement xmlElement)
                {
                    xmlElement.XmlName = _doc.AddXmlName(xmlElement.Prefix, xmlElement.LocalName, xmlElement.NamespaceURI, schemaInfo);
                }
                if (xmlNode.ParentNode == null)
                {
                    return xmlNode;
                }
                xmlNode = xmlNode.ParentNode;
                continue;
            }
            case XmlNodeType.EntityReference:
                xmlNode2 = LoadEntityReferenceNode(direct: false);
                break;
            case XmlNodeType.EndEntity:
                return null;
            case XmlNodeType.Attribute:
                xmlNode2 = LoadAttributeNode();
                break;
            case XmlNodeType.Text:
                xmlNode2 = _doc.CreateTextNode(reader.Value);
                break;
            case XmlNodeType.SignificantWhitespace:
                xmlNode2 = _doc.CreateSignificantWhitespace(reader.Value);
                break;
            case XmlNodeType.Whitespace:
                if (_preserveWhitespace)
                {
                    xmlNode2 = _doc.CreateWhitespace(reader.Value);
                    break;
                }
                if (xmlNode == null && !skipOverWhitespace)
                {
                    return null;
                }
                continue;
            case XmlNodeType.CDATA:
                xmlNode2 = _doc.CreateCDataSection(reader.Value);
                break;
            case XmlNodeType.XmlDeclaration:
                xmlNode2 = LoadDeclarationNode();
                break;
            case XmlNodeType.ProcessingInstruction:
                xmlNode2 = _doc.CreateProcessingInstruction(reader.Name, reader.Value);
                break;
            case XmlNodeType.Comment:
                xmlNode2 = _doc.CreateComment(reader.Value);
                break;
            case XmlNodeType.DocumentType:
                xmlNode2 = LoadDocumentTypeNode();
                break;
            default:
                throw UnexpectedNodeType(reader.NodeType);
            }
            if (xmlNode != null)
            {
                xmlNode.AppendChildForLoad(xmlNode2, _doc);
                continue;
            }
            return xmlNode2;
        }
        while (reader.Read());
        if (xmlNode != null)
        {
            while (xmlNode.ParentNode != null)
            {
                xmlNode = xmlNode.ParentNode;
            }
        }
        return xmlNode;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._preserveWhitespace, System.Xml.XmlLoader._reader, System.Xml.XmlDocument.AddXmlName(), System.Xml.XmlAttributeCollection.Append(), System.Xml.XmlDocument.CreateCDataSection(), System.Xml.XmlDocument.CreateComment(), System.Xml.XmlDocument.CreateElement(), System.Xml.XmlDocument.CreateProcessingInstruction(), System.Xml.XmlDocument.CreateSignificantWhitespace(), System.Xml.XmlDocument.CreateTextNode(), System.Xml.XmlDocument.CreateWhitespace(), System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadDeclarationNode(), System.Xml.XmlLoader.LoadDocumentTypeNode(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.XmlReader.SchemaInfo, System.Xml.XmlLoader.UnexpectedNodeType(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlLoader.LoadDocSequence(), System.Xml.XmlLoader.LoadEntityReferenceNode(), System.Xml.XmlLoader.ParsePartialContent(), and System.Xml.XmlLoader.ReadCurrentNode().