Terraria: System.Xml.XmlLoader.ExpandEntityReference
ExpandEntityReference()
void System.Xml.XmlLoader.ExpandEntityReference (XmlEntityReference eref) inline package
Definition at line 724 of file XmlLoader.cs.
    {
        _doc = eref.OwnerDocument;
        bool isLoading = _doc.IsLoading;
        _doc.IsLoading = true;
        switch (eref.Name)
        {
        case "lt":
            eref.AppendChildForLoad(_doc.CreateTextNode("<"), _doc);
            _doc.IsLoading = isLoading;
            return;
        case "gt":
            eref.AppendChildForLoad(_doc.CreateTextNode(">"), _doc);
            _doc.IsLoading = isLoading;
            return;
        case "amp":
            eref.AppendChildForLoad(_doc.CreateTextNode("&"), _doc);
            _doc.IsLoading = isLoading;
            return;
        case "apos":
            eref.AppendChildForLoad(_doc.CreateTextNode("'"), _doc);
            _doc.IsLoading = isLoading;
            return;
        case "quot":
            eref.AppendChildForLoad(_doc.CreateTextNode("\""), _doc);
            _doc.IsLoading = isLoading;
            return;
        }
        XmlNamedNodeMap entities = _doc.Entities;
        foreach (XmlEntity item in entities)
        {
            if (Ref.Equal(item.Name, eref.Name))
            {
                ParsePartialContent(eref, EntitizeName(eref.Name), XmlNodeType.EntityReference);
                return;
            }
        }
        if (!_doc.ActualLoadingStatus)
        {
            eref.AppendChildForLoad(_doc.CreateTextNode(""), _doc);
            _doc.IsLoading = isLoading;
            return;
        }
        _doc.IsLoading = isLoading;
        throw new XmlException(System.SR.Xml_UndeclaredParEntity, eref.Name);
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlDocument.ActualLoadingStatus, System.Xml.XmlDocument.CreateTextNode(), System.Xml.Dictionary, System.Xml.XmlDocument.Entities, System.Xml.XmlLoader.EntitizeName(), System.Xml.Ref.Equal(), System.Xml.XmlDocument.IsLoading, System.item, System.Xml.XmlLoader.ParsePartialContent(), System.SR.Xml_UndeclaredParEntity, and System.Xml.XmlException.