Terraria: System.Xml.XmlLoader.UnexpectedNodeType
UnexpectedNodeType()
static Exception System.Xml.XmlLoader.UnexpectedNodeType (XmlNodeType nodetype) inline static package
Definition at line 841 of file XmlLoader.cs.
    {
        return new InvalidOperationException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.Xml_UnexpectedNodeType, nodetype.ToString()));
    }
References System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, and System.SR.Xml_UnexpectedNodeType.
Referenced by System.Xml.Schema.Parser.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeNode(), System.Xml.XmlLoader.LoadAttributeValue(), System.Xml.Schema.Parser.LoadEntityReferenceInAttribute(), System.Xml.XmlLoader.LoadNode(), and System.Xml.XmlLoader.LoadNodeDirect().