Terraria: System.Xml.XmlLoader.LoadDocumentTypeNode
LoadDocumentTypeNode()
XmlDocumentType System.Xml.XmlLoader.LoadDocumentTypeNode () inline private
Definition at line 345 of file XmlLoader.cs.
    {
        string publicId = null;
        string systemId = null;
        string value = _reader.Value;
        string localName = _reader.LocalName;
        while (_reader.MoveToNextAttribute())
        {
            string name = _reader.Name;
            if (!(name == "PUBLIC"))
            {
                if (name == "SYSTEM")
                {
                    systemId = _reader.Value;
                }
            }
            else
            {
                publicId = _reader.Value;
            }
        }
        XmlDocumentType xmlDocumentType = _doc.CreateDocumentType(localName, publicId, systemId, value);
        IDtdInfo dtdInfo = _reader.DtdInfo;
        if (dtdInfo != null)
        {
            LoadDocumentType(dtdInfo, xmlDocumentType);
        }
        else
        {
            ParseDocumentType(xmlDocumentType);
        }
        return xmlDocumentType;
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlDocument.CreateDocumentType(), System.Xml.Dictionary, System.Xml.XmlReader.DtdInfo, System.Xml.XmlLoader.LoadDocumentType(), System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlLoader.ParseDocumentType(), System.value, and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlLoader.LoadNode().