Terraria: System.Xml.XmlLoader.LoadDeclarationNode
LoadDeclarationNode()
XmlDeclaration System.Xml.XmlLoader.LoadDeclarationNode () inline private
Definition at line 318 of file XmlLoader.cs.
    {
        string version = null;
        string encoding = null;
        string standalone = null;
        while (_reader.MoveToNextAttribute())
        {
            switch (_reader.Name)
            {
            case "version":
                version = _reader.Value;
                break;
            case "encoding":
                encoding = _reader.Value;
                break;
            case "standalone":
                standalone = _reader.Value;
                break;
            }
        }
        if (version == null)
        {
            ParseXmlDeclarationValue(_reader.Value, out version, out encoding, out standalone);
        }
        return _doc.CreateXmlDeclaration(version, encoding, standalone);
    }
References System.Xml.XmlLoader._doc, System.Xml.XmlLoader._reader, System.Xml.XmlDocument.CreateXmlDeclaration(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlLoader.ParseXmlDeclarationValue(), and System.Xml.XmlReader.Value.
Referenced by System.Xml.XmlLoader.LoadNode().