Terraria: UIResourcePackSelectionMenu.PopulatePackList
PopulatePackList()
void UIResourcePackSelectionMenu.PopulatePackList () inline private
     {
         _availablePacksList.Clear();
         _enabledPacksList.Clear();
         CleanUpResourcePackPriority();
         IEnumerable<ResourcePack> enabledPacks = _packsList.EnabledPacks;
         IEnumerable<ResourcePack> disabledPacks = _packsList.DisabledPacks;
         int num = 0;
         foreach (ResourcePack item in disabledPacks)
         {
             UIResourcePack uIResourcePack = new UIResourcePack(item, num)
             {
                 Width = StyleDimension.FromPixelsAndPercent(0f, 1f)
             };
             UIElement uIElement = CreatePackToggleButton(item);
             uIElement.OnUpdate += EnablePackUpdate;
             uIElement.SetSnapPoint("ToggleToOn", num);
             uIResourcePack.ContentPanel.Append(uIElement);
             uIElement = CreatePackInfoButton(item);
             uIElement.OnUpdate += SeeInfoUpdate;
             uIElement.SetSnapPoint("InfoOff", num);
             uIResourcePack.ContentPanel.Append(uIElement);
             _availablePacksList.Add(uIResourcePack);
             num++;
         }
         num = 0;
         foreach (ResourcePack item2 in enabledPacks)
         {
             UIResourcePack uIResourcePack2 = new UIResourcePack(item2, num)
             {
                 Width = StyleDimension.FromPixelsAndPercent(0f, 1f)
             };
             if (item2.IsEnabled)
             {
                 UIElement uIElement2 = CreatePackToggleButton(item2);
                 uIElement2.Left = new StyleDimension(0f, 0f);
                 uIElement2.Width = new StyleDimension(0f, 0.5f);
                 uIElement2.OnUpdate += DisablePackUpdate;
                 uIElement2.SetSnapPoint("ToggleToOff", num);
                 uIResourcePack2.ContentPanel.Append(uIElement2);
                 uIElement2 = CreatePackInfoButton(item2);
                 uIElement2.OnUpdate += SeeInfoUpdate;
                 uIElement2.Left = new StyleDimension(0f, 0.5f);
                 uIElement2.Width = new StyleDimension(0f, 1f / 6f);
                 uIElement2.SetSnapPoint("InfoOn", num);
                 uIResourcePack2.ContentPanel.Append(uIElement2);
                 uIElement2 = CreateOffsetButton(item2, -1);
                 uIElement2.Left = new StyleDimension(0f, 2f / 3f);
                 uIElement2.Width = new StyleDimension(0f, 1f / 6f);
                 uIElement2.SetSnapPoint("OrderUp", num);
                 uIResourcePack2.ContentPanel.Append(uIElement2);
                 uIElement2 = CreateOffsetButton(item2, 1);
                 uIElement2.Left = new StyleDimension(0f, 0.8333334f);
                 uIElement2.Width = new StyleDimension(0f, 1f / 6f);
                 uIElement2.SetSnapPoint("OrderDown", num);
                 uIResourcePack2.ContentPanel.Append(uIElement2);
             }
             _enabledPacksList.Add(uIResourcePack2);
             num++;
         }
         UpdateTitles();
     }
References _availablePacksList, _enabledPacksList, _packsList, UIList.Add(), UIElement.Append(), CleanUpResourcePackPriority(), UIList.Clear(), UIResourcePack.ContentPanel, CreateOffsetButton(), CreatePackInfoButton(), CreatePackToggleButton(), ResourcePackList.DisabledPacks, DisablePackUpdate(), ResourcePackList.EnabledPacks, EnablePackUpdate(), StyleDimension.FromPixelsAndPercent(), ResourcePack.IsEnabled, UIElement.Left, UIElement.OnUpdate, SeeInfoUpdate(), UIElement.SetSnapPoint(), UpdateTitles(), and UIElement.Width.
Referenced by UIResourcePackSelectionMenu(), CreateOffsetButton(), and CreatePackToggleButton().