Terraria: UIResourcePackSelectionMenu.CreatePackToggleButton
CreatePackToggleButton()
UIElement UIResourcePackSelectionMenu.CreatePackToggleButton (ResourcePack resourcePack) inline private
     {
         Language.GetText(resourcePack.IsEnabled ? "GameUI.Enabled" : "GameUI.Disabled");
         GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(option: true, null, null, Color.White, null, 0.8f);
         groupOptionButton.Left = StyleDimension.FromPercent(0.5f);
         groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(0f, 0.5f);
         groupOptionButton.Height = StyleDimension.Fill;
         groupOptionButton.SetColorsBasedOnSelectionState(Color.LightGreen, Color.PaleVioletRed, 0.7f, 0.7f);
         groupOptionButton.SetCurrentOption(resourcePack.IsEnabled);
         groupOptionButton.ShowHighlightWhenSelected = false;
         groupOptionButton.SetPadding(0f);
         Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/TexturePackButtons", (AssetRequestMode)1);
         UIImageFramed element = new UIImageFramed(obj, obj.Frame(2, 2, (!resourcePack.IsEnabled) ? 1 : 0, 1))
         {
             HAlign = 0.5f,
             VAlign = 0.5f,
             IgnoresMouseInteraction = true
         };
         groupOptionButton.Append(element);
         groupOptionButton.OnMouseOver += delegate
         {
             SoundEngine.PlaySound(12);
         };
         groupOptionButton.OnLeftClick += delegate
         {
             SoundEngine.PlaySound(12);
             resourcePack.IsEnabled = !resourcePack.IsEnabled;
             SetResourcePackAsTopPriority(resourcePack);
             PopulatePackList();
             Main.instance.ResetAllContentBasedRenderTargets();
         };
         return groupOptionButton;
     }
References UIElement.Append(), Main.Assets, Color, StyleDimension.Fill, StyleDimension.FromPercent(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, Main.instance, ResourcePack.IsEnabled, UIElement.Left, UIElement.OnLeftClick, UIElement.OnMouseOver, SoundEngine.PlaySound(), PopulatePackList(), Main.ResetAllContentBasedRenderTargets(), GroupOptionButton< T >.SetColorsBasedOnSelectionState(), GroupOptionButton< T >.SetCurrentOption(), UIElement.SetPadding(), SetResourcePackAsTopPriority(), GroupOptionButton< T >.ShowHighlightWhenSelected, UIElement.VAlign, and UIElement.Width.
Referenced by PopulatePackList().