Terraria: UIResourcePackSelectionMenu.BuildPage
BuildPage()
void UIResourcePackSelectionMenu.BuildPage () inline private
     {
         RemoveAllChildren();
         UIElement uIElement = new UIElement();
         uIElement.Width.Set(0f, 0.8f);
         uIElement.MaxWidth.Set(800f, 0f);
         uIElement.MinWidth.Set(600f, 0f);
         uIElement.Top.Set(240f, 0f);
         uIElement.Height.Set(-240f, 1f);
         uIElement.HAlign = 0.5f;
         Append(uIElement);
         UIPanel uIPanel = new UIPanel
         {
             Width = StyleDimension.Fill,
             Height = new StyleDimension(-110f, 1f),
             BackgroundColor = new Color(33, 43, 79) * 0.8f,
             PaddingRight = 0f,
             PaddingLeft = 0f
         };
         uIElement.Append(uIPanel);
         int num = 35;
         int num2 = num;
         int num3 = 30;
         UIElement uIElement2 = new UIElement
         {
             Width = StyleDimension.Fill,
             Height = StyleDimension.FromPixelsAndPercent(-(num3 + 4 + 5), 1f),
             VAlign = 1f
         };
         uIElement2.SetPadding(0f);
         uIPanel.Append(uIElement2);
         UIElement uIElement3 = new UIElement
         {
             Width = new StyleDimension(-20f, 0.5f),
             Height = new StyleDimension(0f, 1f),
             Left = new StyleDimension(10f, 0f)
         };
         uIElement3.SetPadding(0f);
         uIElement2.Append(uIElement3);
         UIElement uIElement4 = new UIElement
         {
             Width = new StyleDimension(-20f, 0.5f),
             Height = new StyleDimension(0f, 1f),
             Left = new StyleDimension(-10f, 0f),
             HAlign = 1f
         };
         uIElement4.SetPadding(0f);
         uIElement2.Append(uIElement4);
         UIList uIList = new UIList
         {
             Width = new StyleDimension(-25f, 1f),
             Height = new StyleDimension(0f, 1f),
             ListPadding = 5f,
             HAlign = 1f
         };
         uIElement3.Append(uIList);
         _availablePacksList = uIList;
         UIList uIList2 = new UIList
         {
             Width = new StyleDimension(-25f, 1f),
             Height = new StyleDimension(0f, 1f),
             ListPadding = 5f,
             HAlign = 0f,
             Left = new StyleDimension(0f, 0f)
         };
         uIElement4.Append(uIList2);
         _enabledPacksList = uIList2;
         uIPanel.Append(_titleAvailable = new UIText(Language.GetText("UI.AvailableResourcePacksTitle"))
         {
             HAlign = 0f,
             Left = new StyleDimension(25f, 0f),
             Width = new StyleDimension(-25f, 0.5f),
             VAlign = 0f,
             Top = new StyleDimension(10f, 0f)
         });
         uIPanel.Append(_titleEnabled = new UIText(Language.GetText("UI.EnabledResourcePacksTitle"))
         {
             HAlign = 1f,
             Left = new StyleDimension(-25f, 0f),
             Width = new StyleDimension(-25f, 0.5f),
             VAlign = 0f,
             Top = new StyleDimension(10f, 0f)
         });
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.ResourcePacks"), 1f, large: true)
         {
             HAlign = 0.5f,
             VAlign = 0f,
             Top = new StyleDimension(-44f, 0f),
             BackgroundColor = new Color(73, 94, 171)
         };
         uITextPanel.SetPadding(13f);
         uIElement.Append(uITextPanel);
         UIScrollbar uIScrollbar = new UIScrollbar
         {
             Height = new StyleDimension(0f, 1f),
             HAlign = 0f,
             Left = new StyleDimension(0f, 0f)
         };
         uIElement3.Append(uIScrollbar);
         _availablePacksList.SetScrollbar(uIScrollbar);
         UIVerticalSeparator element = new UIVerticalSeparator
         {
             Height = new StyleDimension(-12f, 1f),
             HAlign = 0.5f,
             VAlign = 1f,
             Color = new Color(89, 116, 213, 255) * 0.9f
         };
         uIPanel.Append(element);
         new UIHorizontalSeparator
         {
             Width = new StyleDimension(-num2, 0.5f),
             VAlign = 0f,
             HAlign = 0f,
             Color = new Color(89, 116, 213, 255) * 0.9f,
             Top = new StyleDimension(num3, 0f),
             Left = new StyleDimension(num, 0f)
         };
         new UIHorizontalSeparator
         {
             Width = new StyleDimension(-num2, 0.5f),
             VAlign = 0f,
             HAlign = 1f,
             Color = new Color(89, 116, 213, 255) * 0.9f,
             Top = new StyleDimension(num3, 0f),
             Left = new StyleDimension(-num, 0f)
         };
         UIScrollbar uIScrollbar2 = new UIScrollbar
         {
             Height = new StyleDimension(0f, 1f),
             HAlign = 1f
         };
         uIElement4.Append(uIScrollbar2);
         _enabledPacksList.SetScrollbar(uIScrollbar2);
         AddBackAndFolderButtons(uIElement);
     }
References UIElement.UIElement(), _availablePacksList, _enabledPacksList, _titleAvailable, _titleEnabled, AddBackAndFolderButtons(), UIElement.Append(), Color, StyleDimension.Fill, StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.Left, UIElement.MaxWidth, UIElement.MinWidth, UIElement.PaddingLeft, UIElement.PaddingRight, UIElement.RemoveAllChildren(), StyleDimension.Set(), UIElement.SetPadding(), UIList.SetScrollbar(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by UIResourcePackSelectionMenu().