Terraria: UIResourcePackSelectionMenu.HandleBackButtonUsage
HandleBackButtonUsage()
void UIResourcePackSelectionMenu.HandleBackButtonUsage () inline
Implements IHaveBackButtonCommand.
     {
         SoundEngine.PlaySound(11);
         ApplyListChanges();
         Main.SaveSettings();
         if (_uiStateToGoBackTo != null)
         {
             Main.MenuUI.SetState(_uiStateToGoBackTo);
             return;
         }
         Main.menuMode = 0;
         IngameFancyUI.Close();
     }
References _uiStateToGoBackTo, ApplyListChanges(), IngameFancyUI.Close(), Main.menuMode, Main.MenuUI, SoundEngine.PlaySound(), Main.SaveSettings(), and UserInterface.SetState().
Referenced by GoBackClick().