Terraria: UIResourcePackSelectionMenu.AddBackAndFolderButtons
AddBackAndFolderButtons()
void UIResourcePackSelectionMenu.AddBackAndFolderButtons (UIElement outerContainer) inline private
     {
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
         {
             Width = new StyleDimension(-8f, 0.5f),
             Height = new StyleDimension(50f, 0f),
             VAlign = 1f,
             HAlign = 0f,
             Top = new StyleDimension(-45f, 0f)
         };
         uITextPanel.OnMouseOver += FadedMouseOver;
         uITextPanel.OnMouseOut += FadedMouseOut;
         uITextPanel.OnLeftClick += GoBackClick;
         uITextPanel.SetSnapPoint("GoBack", 0);
         outerContainer.Append(uITextPanel);
         UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("GameUI.OpenFileFolder"), 0.7f, large: true)
         {
             Width = new StyleDimension(-8f, 0.5f),
             Height = new StyleDimension(50f, 0f),
             VAlign = 1f,
             HAlign = 1f,
             Top = new StyleDimension(-45f, 0f)
         };
         uITextPanel2.OnMouseOver += FadedMouseOver;
         uITextPanel2.OnMouseOut += FadedMouseOut;
         uITextPanel2.OnLeftClick += OpenFoldersClick;
         uITextPanel2.SetSnapPoint("OpenFolder", 0);
         outerContainer.Append(uITextPanel2);
     }
References UIElement.Append(), FadedMouseOut(), FadedMouseOver(), Language.GetText(), GoBackClick(), UIElement.HAlign, UIElement.Height, OpenFoldersClick(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().