Terraria: System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer
CreateBuffer()
override global.Interop.WebSocket.? Buffer System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CreateBuffer (ArraySegment< byte >? buffer) inline protected virtual
Reimplemented from System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation.
Definition at line 220 of file WebSocketBase.cs.
            {
                _webSocket.ThrowIfDisposed();
                _webSocket.ThrowIfPendingException();
                if (CloseStatus == WebSocketCloseStatus.Empty)
                {
                    return null;
                }
                global::Interop.WebSocket.Buffer value = default(global::Interop.WebSocket.Buffer);
                if (CloseReason != null)
                {
                    byte[] bytes = Encoding.UTF8.GetBytes(CloseReason);
                    ArraySegment<byte> payload = new ArraySegment<byte>(bytes, 0, Math.Min(123, bytes.Length));
                    _webSocket._internalBuffer.PinSendBuffer(payload, out _BufferHasBeenPinned);
                    value.CloseStatus.ReasonData = _webSocket._internalBuffer.ConvertPinnedSendPayloadToNative(payload);
                    value.CloseStatus.ReasonLength = (uint)payload.Count;
                }
                value.CloseStatus.CloseStatus = (ushort)CloseStatus;
                return value;
            }
References System.Net.WebSockets.WebSocketBase.WebSocketOperation.SendOperation._BufferHasBeenPinned, System.Net.WebSockets.WebSocketBase._internalBuffer, System.Net.WebSockets.WebSocketBase.WebSocketOperation._webSocket, System.bytes, System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CloseReason, System.Net.WebSockets.WebSocketBase.WebSocketOperation.CloseOutputOperation.CloseStatus, System.Net.WebSockets.WebSocketBuffer.ConvertPinnedSendPayloadToNative(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Math.Min(), System.Net.WebSockets.WebSocketBuffer.PinSendBuffer(), System.Net.WebSockets.WebSocketBase.ThrowIfDisposed(), System.Net.WebSockets.WebSocketBase.ThrowIfPendingException(), System.Text.Encoding.UTF8, and System.value.