Terraria: System.OleAutBinder.ChangeType
ChangeType() [1/2]
override object System.OleAutBinder.ChangeType (object value, Type type, CultureInfo cultureInfo) inline
Definition at line 9 of file OleAutBinder.cs.
    {
        Variant source = new Variant(value);
        if (cultureInfo == null)
        {
            cultureInfo = CultureInfo.CurrentCulture;
        }
        if (type.IsByRef)
        {
            type = type.GetElementType();
        }
        if (!type.IsPrimitive && type.IsInstanceOfType(value))
        {
            return value;
        }
        Type type2 = value.GetType();
        if (type.IsEnum && type2.IsPrimitive)
        {
            return Enum.Parse(type, value.ToString());
        }
        try
        {
            return OAVariantLib.ChangeType(source, type, 16, cultureInfo).ToObject();
        }
        catch (NotSupportedException)
        {
            throw new COMException(SR.Interop_COM_TypeMismatch, -2147352571);
        }
    }
References Microsoft.Win32.OAVariantLib.ChangeType(), System.Globalization.CultureInfo.CurrentCulture, System.Type.GetType(), System.SR.Interop_COM_TypeMismatch, System.Type.IsPrimitive, System.Enum.Parse(), System.source, System.type, and System.value.