Terraria: System.Security.Cryptography.Asn1.CurveAsn.DecodeCore
DecodeCore() [2/2]
static void System.Security.Cryptography.Asn1.CurveAsn.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory< byte > rebind, out System::Security::Cryptography::Asn1::CurveAsn decoded) inline static private
Definition at line 47 of file CurveAsn.cs.
    {
        decoded = default(System.Security.Cryptography.Asn1.CurveAsn);
        System.Formats.Asn1.AsnValueReader asnValueReader = reader.ReadSequence(expectedTag);
        ReadOnlySpan<byte> span = rebind.Span;
        int elementOffset;
        if (asnValueReader.TryReadPrimitiveOctetString(out var value))
        {
            decoded.A = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.A = asnValueReader.ReadOctetString();
        }
        if (asnValueReader.TryReadPrimitiveOctetString(out value))
        {
            decoded.B = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
        }
        else
        {
            decoded.B = asnValueReader.ReadOctetString();
        }
        if (asnValueReader.HasData && asnValueReader.PeekTag().HasSameClassAndValue(Asn1Tag.PrimitiveBitString))
        {
            if (asnValueReader.TryReadPrimitiveBitString(out var unusedBitCount, out value))
            {
                decoded.Seed = (span.Overlaps(value, out elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
            }
            else
            {
                decoded.Seed = asnValueReader.ReadBitString(out unusedBitCount);
            }
        }
        asnValueReader.ThrowIfNotEmpty();
    }
References System.Formats.Asn1.AsnValueReader.HasData, System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.AsnValueReader.PeekTag(), System.Formats.Asn1.Asn1Tag.PrimitiveBitString, System.Formats.Asn1.AsnValueReader.ReadBitString(), System.Formats.Asn1.AsnValueReader.ReadOctetString(), System.Formats.Asn1.AsnValueReader.ReadSequence(), System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, System.Formats.Asn1.AsnValueReader.ThrowIfNotEmpty(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveBitString(), System.Formats.Asn1.AsnValueReader.TryReadPrimitiveOctetString(), and System.value.