namespace System.Runtime.InteropServices.ComTypes;

[Flags]
public enum ADVF
{
	ADVF_NODATA = 1,
	ADVF_PRIMEFIRST = 2,
	ADVF_ONLYONCE = 4,
	ADVF_DATAONSTOP = 0x40,
	ADVFCACHE_NOHANDLER = 8,
	ADVFCACHE_FORCEBUILTIN = 0x10,
	ADVFCACHE_ONSAVE = 0x20
}
