Terraria: Terraria.GameContent.AmbientWindSystem.Update
Update()
void Terraria.GameContent.AmbientWindSystem.Update () inline
    {
        if (!Main.LocalPlayer.ZoneGraveyard)
        {
            return;
        }
        _updatesCounter++;
        Rectangle tileWorkSpace = GetTileWorkSpace();
        int num = tileWorkSpace.X + tileWorkSpace.Width;
        int num2 = tileWorkSpace.Y + tileWorkSpace.Height;
        for (int i = tileWorkSpace.X; i < num; i++)
        {
            for (int j = tileWorkSpace.Y; j < num2; j++)
            {
                TrySpawningWind(i, j);
            }
        }
        if (_updatesCounter % 30 == 0)
        {
            SpawnAirborneWind();
        }
    }
References Terraria.GameContent.AmbientWindSystem._updatesCounter, Terraria.GameContent.AmbientWindSystem.GetTileWorkSpace(), Terraria.Main.LocalPlayer, Terraria.GameContent.AmbientWindSystem.SpawnAirborneWind(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), and Terraria.Player.ZoneGraveyard.
Referenced by Terraria.Main.DoUpdateInWorld().