Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportKeyBlob
ImportKeyBlob()
void System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportKeyBlob (byte[] ecKeyBlob, string curveName, bool includePrivateParameters) inline private
Definition at line 57 of file ECDsaImplementation.cs.
        {
            string blobType = (includePrivateParameters ? "ECCPRIVATEBLOB" : "ECCPUBLICBLOB");
            SafeNCryptKeyHandle keyHandle = CngKeyLite.ImportKeyBlob(blobType, ecKeyBlob, curveName);
            _key.SetHandle(keyHandle, ECCng.EcdsaCurveNameToAlgorithm(curveName));
            ForceSetKeySize(_key.KeySize);
        }
References System.Security.Cryptography.ECDsaImplementation.ECDsaCng._key, System.Security.Cryptography.ECCng.EcdsaCurveNameToAlgorithm(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ForceSetKeySize(), System.Security.Cryptography.CngKeyLite.ImportKeyBlob(), System.Security.Cryptography.ECCngKey.KeySize, and System.Security.Cryptography.ECCngKey.SetHandle().
Referenced by System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportParameters().