Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.VerifyHashCore
VerifyHashCore()
unsafe override bool System.Security.Cryptography.ECDsaImplementation.ECDsaCng.VerifyHashCore (ReadOnlySpan< byte > hash, ReadOnlySpan< byte > signature, DSASignatureFormat signatureFormat) inline protected virtual
Reimplemented from System.Security.Cryptography.ECDsa.
Definition at line 375 of file ECDsaImplementation.cs.
        {
            if (signatureFormat != 0)
            {
                signature = this.ConvertSignatureToIeeeP1363(signatureFormat, signature);
            }
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            return keyHandle.VerifyHash(hash, signature, global::Interop.NCrypt.AsymmetricPaddingMode.None, null);
        }
References System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetDuplicatedKeyHandle().
Referenced by System.Security.Cryptography.ECDsaImplementation.ECDsaCng.VerifyHash(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.VerifyHash().