Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportEncryptedPkcs8
ExportEncryptedPkcs8()
byte[] System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportEncryptedPkcs8 (ReadOnlySpan< char > pkcs8Password, int kdfCount) inline private
Definition at line 79 of file ECDsaImplementation.cs.
        {
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            return CngKeyLite.ExportPkcs8KeyBlob(keyHandle, pkcs8Password, kdfCount);
        }
References System.Security.Cryptography.CngKeyLite.ExportPkcs8KeyBlob(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetDuplicatedKeyHandle().
Referenced by System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportEncryptedPkcs8PrivateKey().