Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ThrowIfDisposed
ThrowIfDisposed()
void System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ThrowIfDisposed () inline private
Definition at line 44 of file ECDsaImplementation.cs.
        {
            _key.ThrowIfDisposed();
        }
References System.Security.Cryptography.ECDsaImplementation.ECDsaCng._key, and System.Security.Cryptography.ECCngKey.ThrowIfDisposed().
Referenced by System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportEncryptedPkcs8PrivateKey(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportParameters(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ImportPkcs8PrivateKey().