Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportParameters
ExportParameters()
override ECParameters System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportParameters (bool includePrivateParameters) inline virtual
Reimplemented from System.Security.Cryptography.ECDsa.
Definition at line 212 of file ECDsaImplementation.cs.
        {
            ECParameters ecParams = default(ECParameters);
            string oidValue;
            string curveName = GetCurveName(out oidValue);
            if (string.IsNullOrEmpty(curveName))
            {
                byte[] ecBlob = ExportFullKeyBlob(includePrivateParameters);
                ECCng.ExportPrimeCurveParameters(ref ecParams, ecBlob, includePrivateParameters);
            }
            else
            {
                byte[] ecBlob2 = ExportKeyBlob(includePrivateParameters);
                ECCng.ExportNamedCurveParameters(ref ecParams, ecBlob2, includePrivateParameters);
                ecParams.Curve = ECCurve.CreateFromOid(new Oid(oidValue, curveName));
            }
            return ecParams;
        }
References System.Security.Cryptography.ECCurve.CreateFromOid(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportFullKeyBlob(), System.Security.Cryptography.ECDsaImplementation.ECDsaCng.ExportKeyBlob(), System.Security.Cryptography.ECCng.ExportNamedCurveParameters(), System.Security.Cryptography.ECCng.ExportPrimeCurveParameters(), and System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetCurveName().