Terraria: System.Security.Cryptography.ECDsaImplementation.ECDsaCng.TrySignHashCore
TrySignHashCore()
unsafe override bool System.Security.Cryptography.ECDsaImplementation.ECDsaCng.TrySignHashCore (ReadOnlySpan< byte > hash, Span< byte > destination, DSASignatureFormat signatureFormat, out int bytesWritten) inline protected virtual
Reimplemented from System.Security.Cryptography.ECDsa.
Definition at line 339 of file ECDsaImplementation.cs.
        {
            using (SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle())
            {
                if (!keyHandle.TrySignHash(hash, destination, global::Interop.NCrypt.AsymmetricPaddingMode.None, null, out bytesWritten))
                {
                    bytesWritten = 0;
                    return false;
                }
            }
            return signatureFormat switch
            {
                DSASignatureFormat.IeeeP1363FixedFieldConcatenation => true,
                DSASignatureFormat.Rfc3279DerSequence => AsymmetricAlgorithmHelpers.TryConvertIeee1363ToDer(destination.Slice(0, bytesWritten), destination, out bytesWritten),
                _ => throw new CryptographicException(System.SR.Cryptography_UnknownSignatureFormat, signatureFormat.ToString()),
            };
        }
References System.SR.Cryptography_UnknownSignatureFormat, System.destination, System.Security.Cryptography.ECDsaImplementation.ECDsaCng.GetDuplicatedKeyHandle(), and Internal.Cryptography.AsymmetricAlgorithmHelpers.TryConvertIeee1363ToDer().
Referenced by System.Security.Cryptography.ECDsaImplementation.ECDsaCng.TrySignHash().