Terraria: System.Threading.Tasks.Dataflow.BatchedJoinBlock.BatchedJoinBlock
BatchedJoinBlock() [4/4]
System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >.BatchedJoinBlock (int batchSize, GroupingDataflowBlockOptions dataflowBlockOptions) inline
Definition at line 275 of file BatchedJoinBlock.cs.
    {
        if (batchSize < 1)
        {
            throw new ArgumentOutOfRangeException("batchSize", System.SR.ArgumentOutOfRange_GenericPositive);
        }
        if (dataflowBlockOptions == null)
        {
            throw new ArgumentNullException("dataflowBlockOptions");
        }
        if (!dataflowBlockOptions.Greedy || dataflowBlockOptions.BoundedCapacity != -1)
        {
            throw new ArgumentException(System.SR.Argument_NonGreedyNotSupported, "dataflowBlockOptions");
        }
        _batchSize = batchSize;
        dataflowBlockOptions = dataflowBlockOptions.DefaultOrClone();
        _source = new SourceCore<Tuple<IList<T1>, IList<T2>, IList<T3>>>(this, dataflowBlockOptions, delegate(ISourceBlock<Tuple<IList<T1>, IList<T2>, IList<T3>>> owningSource)
        {
            ((BatchedJoinBlock<T1, T2, T3>)owningSource).CompleteEachTarget();
        });
        Action createBatchAction = delegate
        {
            if (_target1.Count > 0 || _target2.Count > 0 || _target3.Count > 0)
            {
                _source.AddMessage(Tuple.Create(_target1.GetAndEmptyMessages(), _target2.GetAndEmptyMessages(), _target3.GetAndEmptyMessages()));
            }
        };
        _sharedResources = new BatchedJoinBlockTargetSharedResources(batchSize, dataflowBlockOptions, createBatchAction, delegate
        {
            createBatchAction();
            _source.Complete();
        }, _source.AddException, Complete);
        _target1 = new BatchedJoinBlockTarget<T1>(_sharedResources);
        _target2 = new BatchedJoinBlockTarget<T2>(_sharedResources);
        _target3 = new BatchedJoinBlockTarget<T3>(_sharedResources);
        _source.Completion.ContinueWith(delegate(Task completed, object state)
        {
            IDataflowBlock dataflowBlock = (BatchedJoinBlock<T1, T2, T3>)state;
            dataflowBlock.Fault(completed.Exception);
        }, this, CancellationToken.None, Common.GetContinuationOptions() | TaskContinuationOptions.OnlyOnFaulted, TaskScheduler.Default);
        Common.WireCancellationToComplete(dataflowBlockOptions.CancellationToken, _source.Completion, delegate(object state)
        {
            ((BatchedJoinBlock<T1, T2, T3>)state).CompleteEachTarget();
        }, this);
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.DataflowBlockCreated(this, dataflowBlockOptions);
        }
    }
References System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._batchSize, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._sharedResources, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._source, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._target1, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._target2, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >._target3, System.SR.Argument_NonGreedyNotSupported, System.SR.ArgumentOutOfRange_GenericPositive, System.Threading.Tasks.Dataflow.BatchedJoinBlock< T1, T2, T3 >.Complete(), System.Threading.Tasks.Dataflow.Internal.BatchedJoinBlockTarget< T >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Dataflow.Internal.BatchedJoinBlockTarget< T >.GetAndEmptyMessages(), System.Threading.Tasks.Dataflow.Internal.Common.GetContinuationOptions(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.CancellationToken.None, System.state, and System.Threading.Tasks.Dataflow.Internal.Common.WireCancellationToComplete().