Terraria: System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias
ReplaceNamespaceAlias()
void System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias (Compiler compiler) inline package
Definition at line 223 of file Stylesheet.cs.
    {
        if (_modeManagers != null)
        {
            IDictionaryEnumerator enumerator = _modeManagers.GetEnumerator();
            while (enumerator.MoveNext())
            {
                TemplateManager templateManager = (TemplateManager)enumerator.Value;
                if (templateManager.templates != null)
                {
                    for (int i = 0; i < templateManager.templates.Count; i++)
                    {
                        TemplateAction templateAction = (TemplateAction)templateManager.templates[i];
                        templateAction.ReplaceNamespaceAlias(compiler);
                    }
                }
            }
        }
        if (_templateNameTable != null)
        {
            IDictionaryEnumerator enumerator2 = _templateNameTable.GetEnumerator();
            while (enumerator2.MoveNext())
            {
                TemplateAction templateAction2 = (TemplateAction)enumerator2.Value;
                templateAction2.ReplaceNamespaceAlias(compiler);
            }
        }
        if (_imports != null)
        {
            for (int num = _imports.Count - 1; num >= 0; num--)
            {
                Stylesheet stylesheet = (Stylesheet)_imports[num];
                stylesheet.ReplaceNamespaceAlias(compiler);
            }
        }
    }
References System.Xml.Xsl.XsltOld.Stylesheet._imports, System.Xml.Xsl.XsltOld.Stylesheet._modeManagers, System.Xml.Xsl.XsltOld.Stylesheet._templateNameTable, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Collections.Hashtable.GetEnumerator(), and System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias().
Referenced by System.Xml.Xsl.XsltOld.Compiler.Compile(), and System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias().