Terraria: System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates
ProcessTemplates()
void System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates () inline package
Definition at line 202 of file Stylesheet.cs.
    {
        if (_modeManagers != null)
        {
            IDictionaryEnumerator enumerator = _modeManagers.GetEnumerator();
            while (enumerator.MoveNext())
            {
                TemplateManager templateManager = (TemplateManager)enumerator.Value;
                templateManager.ProcessTemplates();
            }
        }
        if (_imports != null)
        {
            for (int num = _imports.Count - 1; num >= 0; num--)
            {
                Stylesheet stylesheet = (Stylesheet)_imports[num];
                stylesheet.ProcessTemplates();
            }
        }
    }
References System.Xml.Xsl.XsltOld.Stylesheet._imports, System.Xml.Xsl.XsltOld.Stylesheet._modeManagers, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Collections.Hashtable.GetEnumerator(), and System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates().
Referenced by System.Xml.Xsl.XsltOld.Compiler.Compile(), and System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates().