Terraria: System.Xml.Xsl.XsltOld.Stylesheet.PreserveWhiteSpace
PreserveWhiteSpace()
bool System.Xml.Xsl.XsltOld.Stylesheet.PreserveWhiteSpace (Processor proc, XPathNavigator node) inline package
Definition at line 120 of file Stylesheet.cs.
    {
        if (_whitespaceList != null)
        {
            int num = _whitespaceList.Count - 1;
            while (0 <= num)
            {
                WhitespaceElement whitespaceElement = (WhitespaceElement)_whitespaceList[num];
                if (proc.Matches(node, whitespaceElement.Key))
                {
                    return whitespaceElement.PreserveSpace;
                }
                num--;
            }
        }
        if (_imports != null)
        {
            for (int num2 = _imports.Count - 1; num2 >= 0; num2--)
            {
                Stylesheet stylesheet = (Stylesheet)_imports[num2];
                if (!stylesheet.PreserveWhiteSpace(proc, node))
                {
                    return false;
                }
            }
        }
        return true;
    }
References System.Xml.Xsl.XsltOld.Stylesheet._imports, System.Xml.Xsl.XsltOld.Stylesheet._whitespaceList, System.Collections.ArrayList.Count, System.Xml.Dictionary, and System.Xml.Xsl.XsltOld.Stylesheet.PreserveWhiteSpace().
Referenced by System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), System.Xml.Xsl.XsltOld.Stylesheet.PreserveWhiteSpace(), and System.Xml.Xsl.XsltOld.XsltCompileContext.PreserveWhitespace().