Terraria: System.Xml.Xsl.XsltOld.Stylesheet.SortWhiteSpace
SortWhiteSpace()
void System.Xml.Xsl.XsltOld.Stylesheet.SortWhiteSpace () inline package
Definition at line 86 of file Stylesheet.cs.
    {
        if (_queryKeyTable != null)
        {
            for (int i = 0; i < _whitespaceList.Count; i++)
            {
                for (int num = _whitespaceList.Count - 1; num > i; num--)
                {
                    WhitespaceElement whitespaceElement = (WhitespaceElement)_whitespaceList[num - 1];
                    WhitespaceElement whitespaceElement2 = (WhitespaceElement)_whitespaceList[num];
                    if (whitespaceElement2.Priority < whitespaceElement.Priority)
                    {
                        _whitespaceList[num - 1] = whitespaceElement2;
                        _whitespaceList[num] = whitespaceElement;
                    }
                }
            }
            _whitespace = true;
        }
        if (_imports == null)
        {
            return;
        }
        for (int num2 = _imports.Count - 1; num2 >= 0; num2--)
        {
            Stylesheet stylesheet = (Stylesheet)_imports[num2];
            if (stylesheet.Whitespace)
            {
                stylesheet.SortWhiteSpace();
                _whitespace = true;
            }
        }
    }
References System.Xml.Xsl.XsltOld.Stylesheet._imports, System.Xml.Xsl.XsltOld.Stylesheet._queryKeyTable, System.Xml.Xsl.XsltOld.Stylesheet._whitespace, System.Xml.Xsl.XsltOld.Stylesheet._whitespaceList, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Stylesheet.SortWhiteSpace(), and System.Xml.Xsl.XsltOld.Stylesheet.Whitespace.
Referenced by System.Xml.Xsl.XsltOld.Compiler.Compile(), and System.Xml.Xsl.XsltOld.Stylesheet.SortWhiteSpace().