Terraria: Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing
BeforeDrawing()
void Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing (ref GameAnimationSegment info, ref DrawData drawData) inline
Implements Segments.SpriteSegment.IShaderEffect.
             {
                 info.SpriteBatch.End();
                 info.SpriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Main.Rasterizer, null, _fetchMatrix());
                 MiscShaderData miscShaderData = GameShaders.Misc[_shaderKey];
                 miscShaderData.UseShaderSpecificData(new Vector4(y: (float)(info.TimeInAnimation / _verticalFrameWait % _verticalFrameCount) / (float)_verticalFrameCount, x: 1f / (float)_verticalFrameCount, z: _panX.GetPanAmount(info.TimeInAnimation), w: _panY.GetPanAmount(info.TimeInAnimation)));
                 miscShaderData.Apply(drawData);
             }
References Segments.SpriteSegment.MaskedFadeEffect._fetchMatrix, Segments.SpriteSegment.MaskedFadeEffect._panX, Segments.SpriteSegment.MaskedFadeEffect._panY, Segments.SpriteSegment.MaskedFadeEffect._shaderKey, Segments.SpriteSegment.MaskedFadeEffect._verticalFrameCount, Segments.SpriteSegment.MaskedFadeEffect._verticalFrameWait, MiscShaderData.Apply(), Segments.Panning.GetPanAmount(), GameShaders.Misc, Main.Rasterizer, and MiscShaderData.UseShaderSpecificData().