Terraria: System.Xml.Xsl.XsltOld.Stylesheet.AddTemplate
AddTemplate()
void System.Xml.Xsl.XsltOld.Stylesheet.AddTemplate (TemplateAction template) inline package
Definition at line 165 of file Stylesheet.cs.
    {
        XmlQualifiedName xmlQualifiedName = template.Mode;
        if (template.Name != null)
        {
            if (_templateNameTable.ContainsKey(template.Name))
            {
                throw XsltException.Create(System.SR.Xslt_DupTemplateName, template.Name.ToString());
            }
            _templateNameTable[template.Name] = template;
        }
        if (template.MatchKey == -1)
        {
            return;
        }
        if (_modeManagers == null)
        {
            _modeManagers = new Hashtable();
        }
        if (xmlQualifiedName == null)
        {
            xmlQualifiedName = XmlQualifiedName.Empty;
        }
        TemplateManager templateManager = (TemplateManager)_modeManagers[xmlQualifiedName];
        if (templateManager == null)
        {
            templateManager = new TemplateManager(this, xmlQualifiedName);
            _modeManagers[xmlQualifiedName] = templateManager;
            if (xmlQualifiedName.IsEmpty)
            {
                _templates = templateManager;
            }
        }
        template.TemplateId = ++_templateCount;
        templateManager.AddTemplate(template);
    }
References System.Xml.Xsl.XsltOld.Stylesheet._modeManagers, System.Xml.Xsl.XsltOld.Stylesheet._templateCount, System.Xml.Xsl.XsltOld.Stylesheet._templateNameTable, System.Xml.Xsl.XsltOld.Stylesheet._templates, System.Collections.Hashtable.ContainsKey(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Name, and System.SR.Xslt_DupTemplateName.
Referenced by System.Xml.Xsl.XsltOld.Compiler.AddTemplate().