Terraria: System.Net.Http.Headers.ProductHeaderValue.GetProductLength
GetProductLength()
static int System.Net.Http.Headers.ProductHeaderValue.GetProductLength (string input, int startIndex, out ProductHeaderValue parsedValue) inline static package
Definition at line 87 of file ProductHeaderValue.cs.
    {
        parsedValue = null;
        if (string.IsNullOrEmpty(input) || startIndex >= input.Length)
        {
            return 0;
        }
        int tokenLength = HttpRuleParser.GetTokenLength(input, startIndex);
        if (tokenLength == 0)
        {
            return 0;
        }
        string name = input.Substring(startIndex, tokenLength);
        int num = startIndex + tokenLength;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        if (num == input.Length || input[num] != '/')
        {
            parsedValue = new ProductHeaderValue(name);
            return num - startIndex;
        }
        num++;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        int tokenLength2 = HttpRuleParser.GetTokenLength(input, num);
        if (tokenLength2 == 0)
        {
            return 0;
        }
        string version = input.Substring(num, tokenLength2);
        num += tokenLength2;
        num += HttpRuleParser.GetWhitespaceLength(input, num);
        parsedValue = new ProductHeaderValue(name, version);
        return num - startIndex;
    }
References System.Net.Http.Headers.ProductHeaderValue.ProductHeaderValue(), System.Net.Http.HttpRuleParser.GetTokenLength(), System.Net.Http.HttpRuleParser.GetWhitespaceLength(), System.input, and System.startIndex.
Referenced by System.Net.Http.Headers.ProductInfoHeaderValue.GetProductInfoLength(), and System.Net.Http.Headers.GenericHeaderParser.ParseProduct().