Terraria: System.ComponentModel.TypeConverter.GetConvertToException
GetConvertToException()
Exception System.ComponentModel.TypeConverter.GetConvertToException (object? value, Type destinationType) inline protected inherited
Definition at line 248 of file TypeConverter.cs.
    {
        string p = ((value == null) ? System.SR.Null : value.GetType().FullName);
        throw new NotSupportedException(System.SR.Format(System.SR.ConvertToException, GetType().Name, p, destinationType.FullName));
    }
References System.SR.ConvertToException, System.SR.Format(), System.Type.FullName, System.Name, System.SR.Null, and System.value.
Referenced by System.ComponentModel.TypeConverter.ConvertTo(), and System.UriTypeConverter.ConvertTo().