Terraria: System.ComponentModel.TypeConverter.ConvertToString
ConvertToString() [3/3]
string? System.ComponentModel.TypeConverter.ConvertToString (object? value) inline inherited
Definition at line 217 of file TypeConverter.cs.
    {
        return (string)ConvertTo(null, CultureInfo.CurrentCulture, value, typeof(string));
    }
References System.ComponentModel.TypeConverter.ConvertTo(), System.Globalization.CultureInfo.CurrentCulture, and System.value.
Referenced by System.ComponentModel.ReferenceConverter.ReferenceComparer.Compare(), System.Drawing.PointConverter.ConvertTo(), System.Drawing.RectangleConverter.ConvertTo(), System.Drawing.SizeConverter.ConvertTo(), System.Drawing.SizeFConverter.ConvertTo(), System.ComponentModel.TypeConverter.ConvertToInvariantString(), and System.ComponentModel.TypeConverter.ConvertToInvariantString().