Terraria: UIVirtualKeyboard.TextIsValidForSubmit
TextIsValidForSubmit()
bool UIVirtualKeyboard.TextIsValidForSubmit () inline private
     {
         if (CustomTextValidationForUpdate != null)
         {
             return CustomTextValidationForUpdate(Text);
         }
         if (Text.Trim().Length <= 0 && !_edittingSign && !_edittingChest)
         {
             return _allowEmpty;
         }
         return true;
     }
References _allowEmpty, _edittingChest, _edittingSign, CustomTextValidationForUpdate, and Text.
Referenced by UIVirtualKeyboard(), InternalSubmit(), and ValidateText().