Terraria: UIVirtualKeyboard.DrawSelf
DrawSelf()
override void UIVirtualKeyboard.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (Main.gameMenu)
         {
             if (ShouldShowKeyboard())
             {
                 outerLayer2.Remove();
                 if (!Elements.Contains(outerLayer1))
                 {
                     Append(outerLayer1);
                 }
                 outerLayer1.Activate();
                 outerLayer2.Deactivate();
                 Recalculate();
                 RecalculateChildren();
                 if (_labelHeight != 0f)
                 {
                     _textBox.Top.Pixels = _textBoxHeight;
                     _label.Top.Pixels = _labelHeight;
                     _textBox.Recalculate();
                     _label.Recalculate();
                     _labelHeight = (_textBoxHeight = 0f);
                     UserInterface.ActiveInstance.ResetLasts();
                 }
             }
             else
             {
                 outerLayer1.Remove();
                 if (!Elements.Contains(outerLayer2))
                 {
                     Append(outerLayer2);
                 }
                 outerLayer2.Activate();
                 outerLayer1.Deactivate();
                 Recalculate();
                 RecalculateChildren();
                 if (_textBoxHeight == 0f)
                 {
                     _textBoxHeight = _textBox.Top.Pixels;
                     _labelHeight = _label.Top.Pixels;
                     _textBox.Top.Pixels += 50f;
                     _label.Top.Pixels += 50f;
                     _textBox.Recalculate();
                     _label.Recalculate();
                     UserInterface.ActiveInstance.ResetLasts();
                 }
             }
         }
         if (!Main.editSign && _edittingSign)
         {
             IngameFancyUI.Close();
             return;
         }
         if (!Main.editChest && _edittingChest)
         {
             IngameFancyUI.Close();
             return;
         }
         base.DrawSelf(spriteBatch);
         UpdateOffsetDown();
         OffsetDown = 0;
         ShouldHideText = false;
         SetupGamepadPoints(spriteBatch);
         PlayerInput.WritingText = true;
         Main.instance.HandleIME();
         Vector2 position = new Vector2(Main.screenWidth / 2, _textBox.GetDimensions().ToRectangle().Bottom + 32);
         Main.instance.DrawWindowsIMEPanel(position, 0.5f);
         string text = Main.GetInputText(Text, _edittingSign);
         if (_edittingSign && Main.inputTextEnter)
         {
             text += "\n";
         }
         else
         {
             if (_edittingChest && Main.inputTextEnter)
             {
                 ChestUI.RenameChestSubmit(Main.player[Main.myPlayer]);
                 IngameFancyUI.Close();
                 return;
             }
             if (Main.inputTextEnter && CanSubmit)
             {
                 Submit();
             }
             else if (_edittingChest && Main.player[Main.myPlayer].chest < 0)
             {
                 ChestUI.RenameChestCancel();
             }
             else if (Main.inputTextEscape && TryEscapingMenu())
             {
                 return;
             }
         }
         if (IngameFancyUI.CanShowVirtualKeyboard(_keyboardContext))
         {
             if (text != Text)
             {
                 if (CustomTextValidationForUpdate == null || CustomTextValidationForUpdate(text))
                 {
                     Text = text;
                 }
                 else
                 {
                     SoundEngine.PlaySound(11);
                 }
             }
             if (_edittingSign)
             {
                 CopyTextToSign();
             }
             if (_edittingChest)
             {
                 CopyTextToChest();
             }
         }
         byte b = (byte)((255 + Main.tileColor.R * 2) / 3);
         Color value = new Color(b, b, b, 255);
         _textBox.TextColor = Color.Lerp(Color.White, value, 0.2f);
         _label.TextColor = Color.Lerp(Color.White, value, 0.2f);
         position = new Vector2(Main.screenWidth / 2, _textBox.GetDimensions().ToRectangle().Bottom + 32);
         Main.instance.DrawWindowsIMEPanel(position, 0.5f);
     }
References _edittingChest, _edittingSign, _keyboardContext, _label, _labelHeight, _textBox, _textBoxHeight, UIElement.Activate(), UserInterface.ActiveInstance, UIElement.Append(), IngameFancyUI.CanShowVirtualKeyboard(), CanSubmit, Player.chest, IngameFancyUI.Close(), Color, CopyTextToChest(), CopyTextToSign(), CustomTextValidationForUpdate, UIElement.Deactivate(), Main.DrawWindowsIMEPanel(), Main.editChest, Main.editSign, UIElement.Elements, Main.gameMenu, Main.GetInputText(), Main.HandleIME(), Main.inputTextEnter, Main.inputTextEscape, Main.instance, Main.myPlayer, OffsetDown, outerLayer1, outerLayer2, StyleDimension.Pixels, Main.player, SoundEngine.PlaySound(), UIText.Recalculate(), UITextPanel< T >.Recalculate(), UIElement.Recalculate(), UIElement.RecalculateChildren(), UIElement.Remove(), ChestUI.RenameChestCancel(), ChestUI.RenameChestSubmit(), UserInterface.ResetLasts(), Main.screenWidth, SetupGamepadPoints(), ShouldHideText, ShouldShowKeyboard(), Submit(), Text, UIText.TextColor, UITextPanel< T >.TextColor, Main.tileColor, UIElement.Top, TryEscapingMenu(), UpdateOffsetDown(), and PlayerInput.WritingText.