Terraria: System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter.OnTryRead
OnTryRead()
override bool System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.OnTryRead (ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options, ref ReadStack state, [MaybeNullWhen(false)] out T value) inline sealed package inherited
Definition at line 13 of file ObjectWithParameterizedConstructorConverter.cs.
    {
        ArgumentState ctorArgumentState = state.Current.CtorArgumentState;
        object obj;
        if (state.UseFastPath)
        {
            ReadOnlySpan<byte> originalSpan = reader.OriginalSpan;
            ReadConstructorArguments(ref state, ref reader, options);
            obj = (T)CreateObject(ref state.Current);
            if (obj is IJsonOnDeserializing jsonOnDeserializing)
            {
                jsonOnDeserializing.OnDeserializing();
            }
            if (ctorArgumentState.FoundPropertyCount > 0)
            {
                (JsonPropertyInfo, JsonReaderState, long, byte[], string)[] foundProperties = ctorArgumentState.FoundProperties;
                for (int i = 0; i < ctorArgumentState.FoundPropertyCount; i++)
                {
                    JsonPropertyInfo item = foundProperties[i].Item1;
                    long item2 = foundProperties[i].Item3;
                    byte[] item3 = foundProperties[i].Item4;
                    string item4 = foundProperties[i].Item5;
                    Utf8JsonReader reader2 = new Utf8JsonReader(originalSpan.Slice(checked((int)item2)), isFinalBlock: true, foundProperties[i].Item2);
                    state.Current.JsonPropertyName = item3;
                    state.Current.JsonPropertyInfo = item;
                    state.Current.NumberHandling = item.NumberHandling;
                    bool flag = item4 != null;
                    if (flag)
                    {
                        state.Current.JsonPropertyNameAsString = item4;
                        JsonSerializer.CreateDataExtensionProperty(obj, item, options);
                    }
                    ObjectDefaultConverter<T>.ReadPropertyValue(obj, ref state, ref reader2, item, flag);
                }
                (JsonPropertyInfo, JsonReaderState, long, byte[], string)[] foundProperties2 = ctorArgumentState.FoundProperties;
                ctorArgumentState.FoundProperties = null;
                ArrayPool<(JsonPropertyInfo, JsonReaderState, long, byte[], string)>.Shared.Return(foundProperties2, clearArray: true);
            }
        }
        else
        {
            if (state.Current.ObjectState == StackFrameObjectState.None)
            {
                state.Current.ObjectState = StackFrameObjectState.StartToken;
                BeginRead(ref state, ref reader, options);
            }
            if (!ReadConstructorArgumentsWithContinuation(ref state, ref reader, options))
            {
                value = default(T);
                return false;
            }
            obj = (T)CreateObject(ref state.Current);
            if (obj is IJsonOnDeserializing jsonOnDeserializing2)
            {
                jsonOnDeserializing2.OnDeserializing();
            }
            if (ctorArgumentState.FoundPropertyCount > 0)
            {
                for (int j = 0; j < ctorArgumentState.FoundPropertyCount; j++)
                {
                    JsonPropertyInfo item5 = ctorArgumentState.FoundPropertiesAsync[j].Item1;
                    object item6 = ctorArgumentState.FoundPropertiesAsync[j].Item2;
                    string item7 = ctorArgumentState.FoundPropertiesAsync[j].Item3;
                    if (item7 == null)
                    {
                        item5.SetExtensionDictionaryAsObject(obj, item6);
                        continue;
                    }
                    JsonSerializer.CreateDataExtensionProperty(obj, item5, options);
                    object valueAsObject = item5.GetValueAsObject(obj);
                    if (valueAsObject is IDictionary<string, JsonElement> dictionary)
                    {
                        dictionary[item7] = (JsonElement)item6;
                    }
                    else
                    {
                        ((IDictionary<string, object>)valueAsObject)[item7] = item6;
                    }
                }
                (JsonPropertyInfo, object, string)[] foundPropertiesAsync = ctorArgumentState.FoundPropertiesAsync;
                ctorArgumentState.FoundPropertiesAsync = null;
                ArrayPool<(JsonPropertyInfo, object, string)>.Shared.Return(foundPropertiesAsync, clearArray: true);
            }
        }
        if (obj is IJsonOnDeserialized jsonOnDeserialized)
        {
            jsonOnDeserialized.OnDeserialized();
        }
        EndRead(ref state);
        value = (T)obj;
        if (state.Current.PropertyRefCache != null)
        {
            state.Current.JsonTypeInfo.UpdateSortedPropertyCache(ref state.Current);
        }
        if (ctorArgumentState.ParameterRefCache != null)
        {
            state.Current.JsonTypeInfo.UpdateSortedParameterCache(ref state.Current);
        }
        return true;
    }
References System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.BeginRead(), System.Text.Json.JsonSerializer.CreateDataExtensionProperty(), System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.CreateObject(), System.dictionary, System.Text.Json.Dictionary, System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.EndRead(), System.item, System.Text.Json.Serialization.JsonElement, System.obj, System.options, System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArguments(), System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArgumentsWithContinuation(), System.Buffers.ArrayPool< T >.Return(), System.state, System.T, and System.value.