Terraria: UIVirtualKeyboard.SetupGamepadPoints
SetupGamepadPoints()
void UIVirtualKeyboard.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 6;
         UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS = 1;
         int num = 3002;
         int num2 = num;
         int num3 = 5;
         int num4 = 10;
         int num5 = num4 * num3 - 1;
         int num6 = num4 * (num3 - 1);
         UILinkPointNavigator.SetPosition(3000, _cancelButton.GetDimensions().Center());
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[3000];
         uILinkPoint.Unlink();
         uILinkPoint.Right = 3001;
         uILinkPoint.Up = num + num6;
         UILinkPointNavigator.SetPosition(3001, _submitButton.GetDimensions().Center());
         uILinkPoint = UILinkPointNavigator.Points[3001];
         uILinkPoint.Unlink();
         uILinkPoint.Left = 3000;
         uILinkPoint.Up = num + num5;
         for (int i = 0; i < num3; i++)
         {
             for (int j = 0; j < num4; j++)
             {
                 int num7 = i * num4 + j;
                 num2 = num + num7;
                 if (_keyList[num7] != null)
                 {
                     UILinkPointNavigator.SetPosition(num2, _keyList[num7].GetDimensions().Center());
                     uILinkPoint = UILinkPointNavigator.Points[num2];
                     uILinkPoint.Unlink();
                     int num8 = j - 1;
                     while (num8 >= 0 && _keyList[i * num4 + num8] == _keyList[num7])
                     {
                         num8--;
                     }
                     if (num8 != -1)
                     {
                         uILinkPoint.Left = i * num4 + num8 + num;
                     }
                     else
                     {
                         uILinkPoint.Left = i * num4 + (num4 - 1) + num;
                     }
                     int k;
                     for (k = j + 1; k <= num4 - 1 && _keyList[i * num4 + k] == _keyList[num7]; k++)
                     {
                     }
                     if (k != num4 && _keyList[num7] != _keyList[k])
                     {
                         uILinkPoint.Right = i * num4 + k + num;
                     }
                     else
                     {
                         uILinkPoint.Right = i * num4 + num;
                     }
                     if (i != 0)
                     {
                         uILinkPoint.Up = num2 - num4;
                     }
                     if (i != num3 - 1)
                     {
                         uILinkPoint.Down = num2 + num4;
                     }
                     else
                     {
                         uILinkPoint.Down = ((j < num3) ? 3000 : 3001);
                     }
                 }
             }
         }
     }
References _cancelButton, _keyList, _submitButton, UILinkPointNavigator.Shortcuts.BackButtonCommand, CalculatedStyle.Center(), UILinkPoint.Down, UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS, UIElement.GetDimensions(), UILinkPoint.Left, UILinkPointNavigator.Points, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), UILinkPoint.Unlink(), and UILinkPoint.Up.
Referenced by DrawSelf().