Terraria: UIVirtualKeyboard.BuildSpaceBarArea
BuildSpaceBarArea()
void UIVirtualKeyboard.BuildSpaceBarArea (UIPanel mainPanel) inline private
     {
         Action createTheseTwo = delegate
         {
             bool flag = CanRestore();
             int x = (flag ? 4 : 5);
             bool edittingSign = _edittingSign;
             int num = ((flag && edittingSign) ? 2 : 3);
             UITextPanel<object> uITextPanel = CreateKeyboardButton(Language.GetText("UI.SpaceButton"), 2, 4, (_edittingSign || (_edittingChest && flag)) ? num : 6);
             uITextPanel.OnLeftClick += delegate
             {
                 PressSpace();
             };
             mainPanel.Append(uITextPanel);
             _spacebarButton = uITextPanel;
             if (edittingSign)
             {
                 UITextPanel<object> uITextPanel2 = CreateKeyboardButton(Language.GetText("UI.EnterButton"), x, 4, num);
                 uITextPanel2.OnLeftClick += delegate
                 {
                     SoundEngine.PlaySound(12);
                     _textBox.Write("\n");
                     ValidateText();
                 };
                 mainPanel.Append(uITextPanel2);
                 _enterButton = uITextPanel2;
             }
         };
         createTheseTwo();
         if (CanRestore())
         {
             UITextPanel<object> restoreBar = CreateKeyboardButton(Language.GetText("UI.RestoreButton"), 6, 4, 2);
             restoreBar.OnLeftClick += delegate
             {
                 SoundEngine.PlaySound(12);
                 RestoreCanceledInput(_keyboardContext);
                 ValidateText();
                 restoreBar.Remove();
                 _enterButton.Remove();
                 _spacebarButton.Remove();
                 createTheseTwo();
             };
             mainPanel.Append(restoreBar);
             _restoreButton = restoreBar;
         }
     }
References _edittingChest, _edittingSign, _enterButton, _keyboardContext, _restoreButton, _spacebarButton, _textBox, UIElement.Append(), CanRestore(), CreateKeyboardButton(), Language.GetText(), SoundEngine.PlaySound(), PressSpace(), RestoreCanceledInput(), ValidateText(), and UITextBox.Write().
Referenced by UIVirtualKeyboard().