Terraria: System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter.ReadConstructorArguments
ReadConstructorArguments()
void System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArguments (ref ReadStack state, ref Utf8JsonReader reader, JsonSerializerOptions options) inline private inherited
Definition at line 121 of file ObjectWithParameterizedConstructorConverter.cs.
    {
        BeginRead(ref state, ref reader, options);
        while (true)
        {
            reader.ReadWithVerify();
            JsonTokenType tokenType = reader.TokenType;
            if (tokenType == JsonTokenType.EndObject)
            {
                break;
            }
            if (TryLookupConstructorParameter(ref state, ref reader, options, out var jsonParameterInfo))
            {
                reader.ReadWithVerify();
                if (!jsonParameterInfo.ShouldDeserialize)
                {
                    reader.Skip();
                    state.Current.EndConstructorParameter();
                }
                else
                {
                    ReadAndCacheConstructorArgument(ref state, ref reader, jsonParameterInfo);
                    state.Current.EndConstructorParameter();
                }
                continue;
            }
            ReadOnlySpan<byte> propertyName = JsonSerializer.GetPropertyName(ref state, ref reader, options);
            bool useExtensionProperty;
            JsonPropertyInfo jsonPropertyInfo = JsonSerializer.LookupProperty(null, propertyName, ref state, options, out useExtensionProperty, createExtensionProperty: false);
            if (jsonPropertyInfo.ShouldDeserialize)
            {
                ArgumentState ctorArgumentState = state.Current.CtorArgumentState;
                if (ctorArgumentState.FoundProperties == null)
                {
                    ctorArgumentState.FoundProperties = ArrayPool<(JsonPropertyInfo, JsonReaderState, long, byte[], string)>.Shared.Rent(Math.Max(1, state.Current.JsonTypeInfo.PropertyCache.Count));
                }
                else if (ctorArgumentState.FoundPropertyCount == ctorArgumentState.FoundProperties.Length)
                {
                    (JsonPropertyInfo, JsonReaderState, long, byte[], string)[] array = ArrayPool<(JsonPropertyInfo, JsonReaderState, long, byte[], string)>.Shared.Rent(ctorArgumentState.FoundProperties.Length * 2);
                    ctorArgumentState.FoundProperties.CopyTo(array, 0);
                    (JsonPropertyInfo, JsonReaderState, long, byte[], string)[] foundProperties = ctorArgumentState.FoundProperties;
                    ctorArgumentState.FoundProperties = array;
                    ArrayPool<(JsonPropertyInfo, JsonReaderState, long, byte[], string)>.Shared.Return(foundProperties, clearArray: true);
                }
                ctorArgumentState.FoundProperties[ctorArgumentState.FoundPropertyCount++] = (jsonPropertyInfo, reader.CurrentState, reader.BytesConsumed, state.Current.JsonPropertyName, state.Current.JsonPropertyNameAsString);
            }
            reader.Skip();
            state.Current.EndProperty();
        }
    }
References System.array, System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.BeginRead(), System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Text.Json.Dictionary, System.Text.Json.JsonSerializer.GetPropertyName(), System.Text.Json.JsonSerializer.LookupProperty(), System.Math.Max(), System.options, System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadAndCacheConstructorArgument(), System.Buffers.ArrayPool< T >.Rent(), System.Buffers.ArrayPool< T >.Return(), System.Buffers.ArrayPool< T >.Shared, System.state, and System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.TryLookupConstructorParameter().
Referenced by System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.OnTryRead().