Terraria: UIVirtualKeyboard.UpdateOffsetDown
UpdateOffsetDown()
void UIVirtualKeyboard.UpdateOffsetDown () inline private
     {
         _textBox.HideSelf = ShouldHideText;
         int num = OffsetDown - _lastOffsetDown;
         int num2 = num;
         if (Math.Abs(num) < 10)
         {
             num2 = num;
         }
         _lastOffsetDown += num2;
         if (num2 != 0)
         {
             Top.Pixels += num2;
             Recalculate();
         }
     }
References _lastOffsetDown, _textBox, UITextBox.HideSelf, OffsetDown, StyleDimension.Pixels, UIElement.Recalculate(), ShouldHideText, and UIElement.Top.
Referenced by UIVirtualKeyboard(), and DrawSelf().