Terraria: System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter.TryLookupConstructorParameter
TryLookupConstructorParameter()
virtual bool System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.TryLookupConstructorParameter (ref ReadStack state, ref Utf8JsonReader reader, JsonSerializerOptions options, out JsonParameterInfo jsonParameterInfo) inline protected virtual inherited
Definition at line 321 of file ObjectWithParameterizedConstructorConverter.cs.
    {
        ReadOnlySpan<byte> propertyName = JsonSerializer.GetPropertyName(ref state, ref reader, options);
        jsonParameterInfo = state.Current.JsonTypeInfo.GetParameter(propertyName, ref state.Current, out var utf8PropertyName);
        state.Current.CtorArgumentState.ParameterIndex++;
        state.Current.JsonPropertyName = utf8PropertyName;
        state.Current.CtorArgumentState.JsonParameterInfo = jsonParameterInfo;
        state.Current.NumberHandling = jsonParameterInfo?.NumberHandling;
        return jsonParameterInfo != null;
    }
References System.Text.Json.Dictionary, System.Text.Json.JsonSerializer.GetPropertyName(), System.options, and System.state.
Referenced by System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArguments(), and System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter< T >.ReadConstructorArgumentsWithContinuation().