Terraria: UIVirtualKeyboard.ValidateText
ValidateText()
void UIVirtualKeyboard.ValidateText () inline private
     {
         if (TextIsValidForSubmit())
         {
             _canSubmit = true;
             _submitButton.TextColor = Color.White;
             if (_submitButton.IsMouseHovering)
             {
                 _submitButton.BackgroundColor = new Color(73, 94, 171);
             }
             else
             {
                 _submitButton.BackgroundColor = new Color(63, 82, 151) * 0.7f;
             }
         }
         else
         {
             _canSubmit = false;
             _submitButton.TextColor = Color.Gray;
             if (_submitButton.IsMouseHovering)
             {
                 _submitButton.BackgroundColor = new Color(180, 60, 60) * 0.85f;
             }
             else
             {
                 _submitButton.BackgroundColor = new Color(150, 40, 40) * 0.85f;
             }
         }
     }
References _canSubmit, _submitButton, Color, UITextPanel< T >.TextColor, and TextIsValidForSubmit().
Referenced by UIVirtualKeyboard(), BackSpace(), BuildSpaceBarArea(), PressSpace(), TypeText(), and Write().