Terraria: UIVirtualKeyboard.TryEscapingMenu
TryEscapingMenu()
bool UIVirtualKeyboard.TryEscapingMenu () inline private
     {
         if (CustomEscapeAttempt != null)
         {
             return CustomEscapeAttempt();
         }
         if (_edittingSign)
         {
             Main.InputTextSignCancel();
         }
         if (_edittingChest)
         {
             ChestUI.RenameChestCancel();
         }
         if (Main.gameMenu && _cancelAction != null)
         {
             Cancel();
         }
         else
         {
             IngameFancyUI.Close();
         }
         return true;
     }
References _cancelAction, _edittingChest, _edittingSign, Cancel(), IngameFancyUI.Close(), CustomEscapeAttempt, Main.gameMenu, Main.InputTextSignCancel(), and ChestUI.RenameChestCancel().
Referenced by DrawSelf().