Terraria: System.Data.SqlTypes.SqlInt16.ReadXml
ReadXml()
void IXmlSerializable. System.Data.SqlTypes.SqlInt16.ReadXml (XmlReader reader) inline
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 540 of file SqlInt16.cs.
    {
        string attribute = reader.GetAttribute("nil", "http://www.w3.org/2001/XMLSchema-instance");
        if (attribute != null && XmlConvert.ToBoolean(attribute))
        {
            reader.ReadElementString();
            m_fNotNull = false;
        }
        else
        {
            m_value = XmlConvert.ToInt16(reader.ReadElementString());
            m_fNotNull = true;
        }
    }
References System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Data.SqlTypes.SqlInt16.m_fNotNull, System.Data.SqlTypes.SqlInt16.m_value, System.Xml.XmlReader.ReadElementString(), System.Xml.XmlConvert.ToBoolean(), and System.Xml.XmlConvert.ToInt16().