Terraria: System.Data.SqlTypes.SqlInt16.Null
Null
readonly SqlInt16 System.Data.SqlTypes.SqlInt16.Null = new SqlInt16(fNull: true) static
Definition at line 19 of file SqlInt16.cs.
Referenced by System.Data.Common.SqlConvert.ConvertToSqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator SqlInt16(), System.Data.SqlTypes.SqlInt16.operator%(), System.Data.SqlTypes.SqlInt16.operator&(), System.Data.SqlTypes.SqlInt16.operator*(), System.Data.SqlTypes.SqlInt16.operator+(), System.Data.SqlTypes.SqlInt16.operator-(), System.Data.SqlTypes.SqlInt16.operator-(), System.Data.SqlTypes.SqlInt16.operator/(), System.Data.SqlTypes.SqlInt16.operator^(), System.Data.SqlTypes.SqlInt16.operator|(), System.Data.SqlTypes.SqlInt16.operator~(), and System.Data.SqlTypes.SqlInt16.Parse().