Terraria: WorkshopSocialModule.RefreshSubscriptionsAndPublishings
RefreshSubscriptionsAndPublishings()
void WorkshopSocialModule.RefreshSubscriptionsAndPublishings () inline private
     {
         _downloader.Refresh(base.IssueReporter);
         _publishedItems.Refresh();
     }
References _downloader, and _publishedItems.
Referenced by Forget(), Initialize(), and LoadEarlyContent().