Terraria: WorkshopSocialModule.PublishWorld
PublishWorld() [2/2]
override void WorkshopSocialModule.PublishWorld (WorldFileData world, WorkshopItemPublishSettings settings) inline
     {
         string name = world.Name;
         string textForWorld = GetTextForWorld(world);
         string[] usedTagsInternalNames = settings.GetUsedTagsInternalNames();
         string text = GetTemporaryFolderPath() + world.GetFileName(includeExtension: false);
         if (MakeTemporaryFolder(text))
         {
             WorkshopHelper.UGCBased.WorldPublisherInstance worldPublisherInstance = new WorkshopHelper.UGCBased.WorldPublisherInstance(world);
             _publisherInstances.Add(worldPublisherInstance);
             worldPublisherInstance.PublishContent(_publishedItems, base.IssueReporter, Forget, name, textForWorld, text, settings.PreviewImagePath, settings.Publicity, usedTagsInternalNames);
         }
     }
References _publishedItems, _publisherInstances, Forget(), FileData.GetFileName(), GetTemporaryFolderPath(), GetTextForWorld(), WorkshopItemPublishSettings.GetUsedTagsInternalNames(), MakeTemporaryFolder(), FileData.Name, WorkshopItemPublishSettings.PreviewImagePath, and WorkshopItemPublishSettings.Publicity.