Terraria: Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement
Hook_AfterPlacement()
static int Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement (int x, int y, int type = 423, int style = 0, int direction = 1, int alternate = 0) inline static
    {
        bool on;
        LogicCheckType logicCheckType = FigureCheckType(x, y, out on);
        GetFrame(x, y, logicCheckType, on);
        if (Main.netMode == 1)
        {
            NetMessage.SendTileSquare(Main.myPlayer, x, y);
            NetMessage.SendData(87, -1, -1, null, x, y, (int)_myEntityID);
            return -1;
        }
        int num = Place(x, y);
        ((TELogicSensor)TileEntity.ByID[num]).FigureCheckState();
        return num;
    }
References Terraria.GameContent.Tile_Entities.TELogicSensor.TELogicSensor(), Terraria.GameContent.Tile_Entities.TELogicSensor._myEntityID, Terraria.DataStructures.TileEntity.ByID, Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType(), Terraria.GameContent.Tile_Entities.TELogicSensor.GetFrame(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.Tile_Entities.TELogicSensor.Place(), Terraria.NetMessage.SendData(), and Terraria.NetMessage.SendTileSquare().
Referenced by Terraria.ObjectData.TileObjectData.Initialize().