Terraria: Terraria.DataStructures.PlayerDrawSet.BoringSetup
BoringSetup()
void Terraria.DataStructures.PlayerDrawSet.BoringSetup (Player player, List< DrawData > drawData, List< int > dust, List< int > gore, Vector2 drawPosition, float shadowOpacity, float rotation, Vector2 rotationOrigin) inline
Definition at line 251 of file PlayerDrawSet.cs.
    {
        DrawDataCache = drawData;
        DustCache = dust;
        GoreCache = gore;
        drawPlayer = player;
        shadow = shadowOpacity;
        this.rotation = rotation;
        this.rotationOrigin = rotationOrigin;
        heldItem = player.lastVisualizedSelectedItem;
        cHead = drawPlayer.cHead;
        cBody = drawPlayer.cBody;
        cLegs = drawPlayer.cLegs;
        if (drawPlayer.wearsRobe)
        {
            cLegs = cBody;
        }
        cHandOn = drawPlayer.cHandOn;
        cHandOff = drawPlayer.cHandOff;
        cBack = drawPlayer.cBack;
        cFront = drawPlayer.cFront;
        cShoe = drawPlayer.cShoe;
        cFlameWaker = drawPlayer.cFlameWaker;
        cWaist = drawPlayer.cWaist;
        cShield = drawPlayer.cShield;
        cNeck = drawPlayer.cNeck;
        cFace = drawPlayer.cFace;
        cBalloon = drawPlayer.cBalloon;
        cWings = drawPlayer.cWings;
        cCarpet = drawPlayer.cCarpet;
        cPortableStool = drawPlayer.cPortableStool;
        cFloatingTube = drawPlayer.cFloatingTube;
        cUnicornHorn = drawPlayer.cUnicornHorn;
        cAngelHalo = drawPlayer.cAngelHalo;
        cLeinShampoo = drawPlayer.cLeinShampoo;
        cBackpack = drawPlayer.cBackpack;
        cTail = drawPlayer.cTail;
        cFaceHead = drawPlayer.cFaceHead;
        cFaceFlower = drawPlayer.cFaceFlower;
        cBalloonFront = drawPlayer.cBalloonFront;
        cBeard = drawPlayer.cBeard;
        isSitting = drawPlayer.sitting.isSitting;
        seatYOffset = 0f;
        sittingIndex = 0;
        Vector2 posOffset = Vector2.Zero;
        drawPlayer.sitting.GetSittingOffsetInfo(drawPlayer, out posOffset, out seatYOffset);
        if (isSitting)
        {
            sittingIndex = drawPlayer.sitting.sittingIndex;
        }
        if (drawPlayer.mount.Active && drawPlayer.mount.Type == 17)
        {
            isSitting = true;
        }
        if (drawPlayer.mount.Active && drawPlayer.mount.Type == 23)
        {
            isSitting = true;
        }
        if (drawPlayer.mount.Active && drawPlayer.mount.Type == 45)
        {
            isSitting = true;
        }
        isSleeping = drawPlayer.sleeping.isSleeping;
        Position = drawPosition;
        Position += new Vector2(drawPlayer.MountXOffset * (float)drawPlayer.direction, 0f);
        if (isSitting)
        {
            torsoOffset = seatYOffset;
            Position += posOffset;
        }
        else
        {
            sittingIndex = -1;
        }
        if (isSleeping)
        {
            this.rotationOrigin = player.Size / 2f;
            drawPlayer.sleeping.GetSleepingOffsetInfo(drawPlayer, out var posOffset2);
            Position += posOffset2;
        }
        weaponDrawOrder = WeaponDrawOrder.BehindFrontArm;
        if (heldItem.type == 4952)
        {
            weaponDrawOrder = WeaponDrawOrder.BehindBackArm;
        }
        if (GolfHelper.IsPlayerHoldingClub(player) && player.itemAnimation > player.itemAnimationMax)
        {
            weaponDrawOrder = WeaponDrawOrder.OverFrontArm;
        }
        projectileDrawPosition = -1;
        ItemLocation = Position + (drawPlayer.itemLocation - drawPlayer.position);
        armorAdjust = 0;
        missingHand = false;
        missingArm = false;
        heldProjOverHand = false;
        skinVar = drawPlayer.skinVariant;
        if (drawPlayer.body == 77 || drawPlayer.body == 103 || drawPlayer.body == 41 || drawPlayer.body == 100 || drawPlayer.body == 10 || drawPlayer.body == 11 || drawPlayer.body == 12 || drawPlayer.body == 13 || drawPlayer.body == 14 || drawPlayer.body == 43 || drawPlayer.body == 15 || drawPlayer.body == 16 || drawPlayer.body == 20 || drawPlayer.body == 39 || drawPlayer.body == 50 || drawPlayer.body == 38 || drawPlayer.body == 40 || drawPlayer.body == 57 || drawPlayer.body == 44 || drawPlayer.body == 52 || drawPlayer.body == 53 || drawPlayer.body == 68 || drawPlayer.body == 81 || drawPlayer.body == 85 || drawPlayer.body == 88 || drawPlayer.body == 98 || drawPlayer.body == 86 || drawPlayer.body == 87 || drawPlayer.body == 99 || drawPlayer.body == 165 || drawPlayer.body == 166 || drawPlayer.body == 167 || drawPlayer.body == 171 || drawPlayer.body == 45 || drawPlayer.body == 168 || drawPlayer.body == 169 || drawPlayer.body == 42 || drawPlayer.body == 180 || drawPlayer.body == 181 || drawPlayer.body == 183 || drawPlayer.body == 186 || drawPlayer.body == 187 || drawPlayer.body == 188 || drawPlayer.body == 64 || drawPlayer.body == 189 || drawPlayer.body == 191 || drawPlayer.body == 192 || drawPlayer.body == 198 || drawPlayer.body == 199 || drawPlayer.body == 202 || drawPlayer.body == 203 || drawPlayer.body == 58 || drawPlayer.body == 59 || drawPlayer.body == 60 || drawPlayer.body == 61 || drawPlayer.body == 62 || drawPlayer.body == 63 || drawPlayer.body == 36 || drawPlayer.body == 104 || drawPlayer.body == 184 || drawPlayer.body == 74 || drawPlayer.body == 78 || drawPlayer.body == 185 || drawPlayer.body == 196 || drawPlayer.body == 197 || drawPlayer.body == 182 || drawPlayer.body == 87 || drawPlayer.body == 76 || drawPlayer.body == 209 || drawPlayer.body == 168 || drawPlayer.body == 210 || drawPlayer.body == 211 || drawPlayer.body == 213)
        {
            missingHand = true;
        }
        int body = drawPlayer.body;
        if (body == 83)
        {
            missingArm = false;
        }
        else
        {
            missingArm = true;
        }
        if (drawPlayer.heldProj >= 0 && shadow == 0f)
        {
            body = Main.projectile[drawPlayer.heldProj].type;
            if (body == 460 || body == 535 || body == 600)
            {
                heldProjOverHand = true;
            }
        }
        drawPlayer.GetHairSettings(out fullHair, out hatHair, out hideHair, out backHairDraw, out drawsBackHairWithoutHeadgear);
        hairDyePacked = PlayerDrawHelper.PackShader(drawPlayer.hairDye, PlayerDrawHelper.ShaderConfiguration.HairShader);
        if (drawPlayer.head == 0 && drawPlayer.hairDye == 0)
        {
            hairDyePacked = PlayerDrawHelper.PackShader(1, PlayerDrawHelper.ShaderConfiguration.HairShader);
        }
        skinDyePacked = player.skinDyePacked;
        if (drawPlayer.mount.Active && drawPlayer.mount.Type == 52)
        {
            AdjustmentsForWolfMount();
        }
        if (drawPlayer.isDisplayDollOrInanimate)
        {
            Point point = Center.ToTileCoordinates();
            if (Main.InSmartCursorHighlightArea(point.X, point.Y, out var actuallySelected))
            {
                Color color = Lighting.GetColor(point.X, point.Y);
                int num = (color.R + color.G + color.B) / 3;
                if (num > 10)
                {
                    selectionGlowColor = Colors.GetSelectionGlowColor(actuallySelected, num);
                }
            }
        }
        mountOffSet = drawPlayer.HeightOffsetVisual;
        Position.Y -= mountOffSet;
        if (drawPlayer.mount.Active)
        {
            Mount.currentShader = (drawPlayer.mount.Cart ? drawPlayer.cMinecart : drawPlayer.cMount);
        }
        else
        {
            Mount.currentShader = 0;
        }
        playerEffect = SpriteEffects.None;
        itemEffect = SpriteEffects.FlipHorizontally;
        colorHair = drawPlayer.GetImmuneAlpha(drawPlayer.GetHairColor(), shadow);
        colorEyeWhites = drawPlayer.GetImmuneAlpha(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.25) / 16.0), Color.White), shadow);
        colorEyes = drawPlayer.GetImmuneAlpha(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.25) / 16.0), drawPlayer.eyeColor), shadow);
        colorHead = drawPlayer.GetImmuneAlpha(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.25) / 16.0), drawPlayer.skinColor), shadow);
        colorBodySkin = drawPlayer.GetImmuneAlpha(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.5) / 16.0), drawPlayer.skinColor), shadow);
        colorLegs = drawPlayer.GetImmuneAlpha(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.75) / 16.0), drawPlayer.skinColor), shadow);
        colorShirt = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.5) / 16.0), drawPlayer.shirtColor), shadow);
        colorUnderShirt = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.5) / 16.0), drawPlayer.underShirtColor), shadow);
        colorPants = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.75) / 16.0), drawPlayer.pantsColor), shadow);
        colorShoes = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)(((double)Position.Y + (double)drawPlayer.height * 0.75) / 16.0), drawPlayer.shoeColor), shadow);
        colorArmorHead = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)Position.Y + (double)drawPlayer.height * 0.25) / 16, Color.White), shadow);
        colorArmorBody = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)Position.Y + (double)drawPlayer.height * 0.5) / 16, Color.White), shadow);
        colorMount = colorArmorBody;
        colorArmorLegs = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)Position.Y + (double)drawPlayer.height * 0.75) / 16, Color.White), shadow);
        floatingTubeColor = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)Position.Y + (double)drawPlayer.height * 0.75) / 16, Color.White), shadow);
        colorElectricity = new Color(255, 255, 255, 100);
        colorDisplayDollSkin = colorBodySkin;
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        int num5 = 0;
        headGlowMask = -1;
        bodyGlowMask = -1;
        armGlowMask = -1;
        legsGlowMask = -1;
        headGlowColor = Color.Transparent;
        bodyGlowColor = Color.Transparent;
        armGlowColor = Color.Transparent;
        legsGlowColor = Color.Transparent;
        switch (drawPlayer.head)
        {
        case 169:
            num2++;
            break;
        case 170:
            num3++;
            break;
        case 171:
            num4++;
            break;
        case 189:
            num5++;
            break;
        }
        switch (drawPlayer.body)
        {
        case 175:
            num2++;
            break;
        case 176:
            num3++;
            break;
        case 177:
            num4++;
            break;
        case 190:
            num5++;
            break;
        }
        switch (drawPlayer.legs)
        {
        case 110:
            num2++;
            break;
        case 111:
            num3++;
            break;
        case 112:
            num4++;
            break;
        case 130:
            num5++;
            break;
        }
        num2 = 3;
        num3 = 3;
        num4 = 3;
        num5 = 3;
        ArkhalisColor = drawPlayer.underShirtColor;
        ArkhalisColor.A = 180;
        if (drawPlayer.head == 169)
        {
            headGlowMask = 15;
            byte b = (byte)(62.5f * (float)(1 + num2));
            headGlowColor = new Color(b, b, b, 0);
        }
        else if (drawPlayer.head == 216)
        {
            headGlowMask = 256;
            byte b2 = 127;
            headGlowColor = new Color(b2, b2, b2, 0);
        }
        else if (drawPlayer.head == 210)
        {
            headGlowMask = 242;
            byte b3 = 127;
            headGlowColor = new Color(b3, b3, b3, 0);
        }
        else if (drawPlayer.head == 214)
        {
            headGlowMask = 245;
            headGlowColor = ArkhalisColor;
        }
        else if (drawPlayer.head == 240)
        {
            headGlowMask = 273;
            headGlowColor = new Color(230, 230, 230, 60);
        }
        else if (drawPlayer.head == 267)
        {
            headGlowMask = 301;
            headGlowColor = new Color(230, 230, 230, 60);
        }
        else if (drawPlayer.head == 268)
        {
            headGlowMask = 302;
            float num6 = (float)(int)Main.mouseTextColor / 255f;
            num6 *= num6;
            headGlowColor = new Color(255, 255, 255) * num6;
        }
        else if (drawPlayer.head == 269)
        {
            headGlowMask = 304;
            headGlowColor = new Color(200, 200, 200);
        }
        else if (drawPlayer.head == 270)
        {
            headGlowMask = 305;
            headGlowColor = new Color(200, 200, 200, 150);
        }
        else if (drawPlayer.head == 271)
        {
            headGlowMask = 309;
            headGlowColor = Color.White;
        }
        else if (drawPlayer.head == 170)
        {
            headGlowMask = 16;
            byte b4 = (byte)(62.5f * (float)(1 + num3));
            headGlowColor = new Color(b4, b4, b4, 0);
        }
        else if (drawPlayer.head == 189)
        {
            headGlowMask = 184;
            byte b5 = (byte)(62.5f * (float)(1 + num5));
            headGlowColor = new Color(b5, b5, b5, 0);
            colorArmorHead = drawPlayer.GetImmuneAlphaPure(new Color(b5, b5, b5, 255), shadow);
        }
        else if (drawPlayer.head == 171)
        {
            byte b6 = (byte)(62.5f * (float)(1 + num4));
            colorArmorHead = drawPlayer.GetImmuneAlphaPure(new Color(b6, b6, b6, 255), shadow);
        }
        else if (drawPlayer.head == 175)
        {
            headGlowMask = 41;
            headGlowColor = new Color(255, 255, 255, 0);
        }
        else if (drawPlayer.head == 193)
        {
            headGlowMask = 209;
            headGlowColor = new Color(255, 255, 255, 127);
        }
        else if (drawPlayer.head == 109)
        {
            headGlowMask = 208;
            headGlowColor = new Color(255, 255, 255, 0);
        }
        else if (drawPlayer.head == 178)
        {
            headGlowMask = 96;
            headGlowColor = new Color(255, 255, 255, 0);
        }
        if (drawPlayer.body == 175)
        {
            if (drawPlayer.Male)
            {
                bodyGlowMask = 13;
            }
            else
            {
                bodyGlowMask = 18;
            }
            byte b7 = (byte)(62.5f * (float)(1 + num2));
            bodyGlowColor = new Color(b7, b7, b7, 0);
        }
        else if (drawPlayer.body == 208)
        {
            if (drawPlayer.Male)
            {
                bodyGlowMask = 246;
            }
            else
            {
                bodyGlowMask = 247;
            }
            armGlowMask = 248;
            bodyGlowColor = ArkhalisColor;
            armGlowColor = ArkhalisColor;
        }
        else if (drawPlayer.body == 227)
        {
            bodyGlowColor = new Color(230, 230, 230, 60);
            armGlowColor = new Color(230, 230, 230, 60);
        }
        else if (drawPlayer.body == 237)
        {
            float num7 = (float)(int)Main.mouseTextColor / 255f;
            num7 *= num7;
            bodyGlowColor = new Color(255, 255, 255) * num7;
        }
        else if (drawPlayer.body == 238)
        {
            bodyGlowColor = new Color(255, 255, 255);
            armGlowColor = new Color(255, 255, 255);
        }
        else if (drawPlayer.body == 239)
        {
            bodyGlowColor = new Color(200, 200, 200, 150);
            armGlowColor = new Color(200, 200, 200, 150);
        }
        else if (drawPlayer.body == 190)
        {
            if (drawPlayer.Male)
            {
                bodyGlowMask = 185;
            }
            else
            {
                bodyGlowMask = 186;
            }
            armGlowMask = 188;
            byte b8 = (byte)(62.5f * (float)(1 + num5));
            bodyGlowColor = new Color(b8, b8, b8, 0);
            armGlowColor = new Color(b8, b8, b8, 0);
            colorArmorBody = drawPlayer.GetImmuneAlphaPure(new Color(b8, b8, b8, 255), shadow);
        }
        else if (drawPlayer.body == 176)
        {
            if (drawPlayer.Male)
            {
                bodyGlowMask = 14;
            }
            else
            {
                bodyGlowMask = 19;
            }
            armGlowMask = 12;
            byte b9 = (byte)(62.5f * (float)(1 + num3));
            bodyGlowColor = new Color(b9, b9, b9, 0);
            armGlowColor = new Color(b9, b9, b9, 0);
        }
        else if (drawPlayer.body == 194)
        {
            bodyGlowMask = 210;
            armGlowMask = 211;
            bodyGlowColor = new Color(255, 255, 255, 127);
            armGlowColor = new Color(255, 255, 255, 127);
        }
        else if (drawPlayer.body == 177)
        {
            byte b10 = (byte)(62.5f * (float)(1 + num4));
            colorArmorBody = drawPlayer.GetImmuneAlphaPure(new Color(b10, b10, b10, 255), shadow);
        }
        else if (drawPlayer.body == 179)
        {
            if (drawPlayer.Male)
            {
                bodyGlowMask = 42;
            }
            else
            {
                bodyGlowMask = 43;
            }
            armGlowMask = 44;
            bodyGlowColor = new Color(255, 255, 255, 0);
            armGlowColor = new Color(255, 255, 255, 0);
        }
        if (drawPlayer.legs == 111)
        {
            legsGlowMask = 17;
            byte b11 = (byte)(62.5f * (float)(1 + num3));
            legsGlowColor = new Color(b11, b11, b11, 0);
        }
        else if (drawPlayer.legs == 157)
        {
            legsGlowMask = 249;
            legsGlowColor = ArkhalisColor;
        }
        else if (drawPlayer.legs == 158)
        {
            legsGlowMask = 250;
            legsGlowColor = ArkhalisColor;
        }
        else if (drawPlayer.legs == 210)
        {
            legsGlowMask = 274;
            legsGlowColor = new Color(230, 230, 230, 60);
        }
        else if (drawPlayer.legs == 222)
        {
            legsGlowMask = 303;
            float num8 = (float)(int)Main.mouseTextColor / 255f;
            num8 *= num8;
            legsGlowColor = new Color(255, 255, 255) * num8;
        }
        else if (drawPlayer.legs == 225)
        {
            legsGlowMask = 306;
            legsGlowColor = new Color(200, 200, 200, 150);
        }
        else if (drawPlayer.legs == 226)
        {
            legsGlowMask = 307;
            legsGlowColor = new Color(200, 200, 200, 150);
        }
        else if (drawPlayer.legs == 110)
        {
            legsGlowMask = 199;
            byte b12 = (byte)(62.5f * (float)(1 + num2));
            legsGlowColor = new Color(b12, b12, b12, 0);
        }
        else if (drawPlayer.legs == 112)
        {
            byte b13 = (byte)(62.5f * (float)(1 + num4));
            colorArmorLegs = drawPlayer.GetImmuneAlphaPure(new Color(b13, b13, b13, 255), shadow);
        }
        else if (drawPlayer.legs == 134)
        {
            legsGlowMask = 212;
            legsGlowColor = new Color(255, 255, 255, 127);
        }
        else if (drawPlayer.legs == 130)
        {
            byte b14 = (byte)(127 * (1 + num5));
            legsGlowMask = 187;
            legsGlowColor = new Color(b14, b14, b14, 0);
            colorArmorLegs = drawPlayer.GetImmuneAlphaPure(new Color(b14, b14, b14, 255), shadow);
        }
        float alphaReduction = shadow;
        headGlowColor = drawPlayer.GetImmuneAlphaPure(headGlowColor, alphaReduction);
        bodyGlowColor = drawPlayer.GetImmuneAlphaPure(bodyGlowColor, alphaReduction);
        armGlowColor = drawPlayer.GetImmuneAlphaPure(armGlowColor, alphaReduction);
        legsGlowColor = drawPlayer.GetImmuneAlphaPure(legsGlowColor, alphaReduction);
        if (drawPlayer.head > 0 && drawPlayer.head < ArmorIDs.Head.Count)
        {
            Main.instance.LoadArmorHead(drawPlayer.head);
            int num9 = ArmorIDs.Head.Sets.FrontToBackID[drawPlayer.head];
            if (num9 >= 0)
            {
                Main.instance.LoadArmorHead(num9);
            }
        }
        if (drawPlayer.body > 0 && drawPlayer.body < ArmorIDs.Body.Count)
        {
            Main.instance.LoadArmorBody(drawPlayer.body);
        }
        if (drawPlayer.legs > 0 && drawPlayer.legs < ArmorIDs.Legs.Count)
        {
            Main.instance.LoadArmorLegs(drawPlayer.legs);
        }
        if (drawPlayer.handon > 0 && drawPlayer.handon < ArmorIDs.HandOn.Count)
        {
            Main.instance.LoadAccHandsOn(drawPlayer.handon);
        }
        if (drawPlayer.handoff > 0 && drawPlayer.handoff < ArmorIDs.HandOff.Count)
        {
            Main.instance.LoadAccHandsOff(drawPlayer.handoff);
        }
        if (drawPlayer.back > 0 && drawPlayer.back < ArmorIDs.Back.Count)
        {
            Main.instance.LoadAccBack(drawPlayer.back);
        }
        if (drawPlayer.front > 0 && drawPlayer.front < ArmorIDs.Front.Count)
        {
            Main.instance.LoadAccFront(drawPlayer.front);
        }
        if (drawPlayer.shoe > 0 && drawPlayer.shoe < ArmorIDs.Shoe.Count)
        {
            Main.instance.LoadAccShoes(drawPlayer.shoe);
        }
        if (drawPlayer.waist > 0 && drawPlayer.waist < ArmorIDs.Waist.Count)
        {
            Main.instance.LoadAccWaist(drawPlayer.waist);
        }
        if (drawPlayer.shield > 0 && drawPlayer.shield < ArmorIDs.Shield.Count)
        {
            Main.instance.LoadAccShield(drawPlayer.shield);
        }
        if (drawPlayer.neck > 0 && drawPlayer.neck < ArmorIDs.Neck.Count)
        {
            Main.instance.LoadAccNeck(drawPlayer.neck);
        }
        if (drawPlayer.face > 0 && drawPlayer.face < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.face);
        }
        if (drawPlayer.balloon > 0 && drawPlayer.balloon < ArmorIDs.Balloon.Count)
        {
            Main.instance.LoadAccBalloon(drawPlayer.balloon);
        }
        if (drawPlayer.backpack > 0 && drawPlayer.backpack < ArmorIDs.Back.Count)
        {
            Main.instance.LoadAccBack(drawPlayer.backpack);
        }
        if (drawPlayer.tail > 0 && drawPlayer.tail < ArmorIDs.Back.Count)
        {
            Main.instance.LoadAccBack(drawPlayer.tail);
        }
        if (drawPlayer.faceHead > 0 && drawPlayer.faceHead < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.faceHead);
        }
        if (drawPlayer.faceFlower > 0 && drawPlayer.faceFlower < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.faceFlower);
        }
        if (drawPlayer.balloonFront > 0 && drawPlayer.balloonFront < ArmorIDs.Balloon.Count)
        {
            Main.instance.LoadAccBalloon(drawPlayer.balloonFront);
        }
        if (drawPlayer.beard > 0 && drawPlayer.beard < ArmorIDs.Beard.Count)
        {
            Main.instance.LoadAccBeard(drawPlayer.beard);
        }
        Main.instance.LoadHair(drawPlayer.hair);
        if (drawPlayer.eyebrellaCloud)
        {
            Main.instance.LoadProjectile(238);
        }
        if (drawPlayer.isHatRackDoll)
        {
            colorLegs = Color.Transparent;
            colorBodySkin = Color.Transparent;
            colorHead = Color.Transparent;
            colorHair = Color.Transparent;
            colorEyes = Color.Transparent;
            colorEyeWhites = Color.Transparent;
        }
        if (drawPlayer.isDisplayDollOrInanimate)
        {
            if (drawPlayer.isFullbright)
            {
                colorHead = Color.White;
                colorBodySkin = Color.White;
                colorLegs = Color.White;
                colorEyes = Color.White;
                colorEyeWhites = Color.White;
                colorArmorHead = Color.White;
                colorArmorBody = Color.White;
                colorArmorLegs = Color.White;
                colorDisplayDollSkin = PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR;
            }
            else
            {
                colorDisplayDollSkin = drawPlayer.GetImmuneAlphaPure(Lighting.GetColorClamped((int)((double)Position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)Position.Y + (double)drawPlayer.height * 0.5) / 16, PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR), shadow);
            }
        }
        if (!drawPlayer.isDisplayDollOrInanimate)
        {
            if ((drawPlayer.head == 78 || drawPlayer.head == 79 || drawPlayer.head == 80) && drawPlayer.body == 51 && drawPlayer.legs == 47)
            {
                float num10 = (float)(int)Main.mouseTextColor / 200f - 0.3f;
                if (shadow != 0f)
                {
                    num10 = 0f;
                }
                colorArmorHead.R = (byte)((float)(int)colorArmorHead.R * num10);
                colorArmorHead.G = (byte)((float)(int)colorArmorHead.G * num10);
                colorArmorHead.B = (byte)((float)(int)colorArmorHead.B * num10);
                colorArmorBody.R = (byte)((float)(int)colorArmorBody.R * num10);
                colorArmorBody.G = (byte)((float)(int)colorArmorBody.G * num10);
                colorArmorBody.B = (byte)((float)(int)colorArmorBody.B * num10);
                colorArmorLegs.R = (byte)((float)(int)colorArmorLegs.R * num10);
                colorArmorLegs.G = (byte)((float)(int)colorArmorLegs.G * num10);
                colorArmorLegs.B = (byte)((float)(int)colorArmorLegs.B * num10);
            }
            if (drawPlayer.head == 193 && drawPlayer.body == 194 && drawPlayer.legs == 134)
            {
                float num11 = 0.6f - drawPlayer.ghostFade * 0.3f;
                if (shadow != 0f)
                {
                    num11 = 0f;
                }
                colorArmorHead.R = (byte)((float)(int)colorArmorHead.R * num11);
                colorArmorHead.G = (byte)((float)(int)colorArmorHead.G * num11);
                colorArmorHead.B = (byte)((float)(int)colorArmorHead.B * num11);
                colorArmorBody.R = (byte)((float)(int)colorArmorBody.R * num11);
                colorArmorBody.G = (byte)((float)(int)colorArmorBody.G * num11);
                colorArmorBody.B = (byte)((float)(int)colorArmorBody.B * num11);
                colorArmorLegs.R = (byte)((float)(int)colorArmorLegs.R * num11);
                colorArmorLegs.G = (byte)((float)(int)colorArmorLegs.G * num11);
                colorArmorLegs.B = (byte)((float)(int)colorArmorLegs.B * num11);
            }
            if (shadow > 0f)
            {
                colorLegs = Color.Transparent;
                colorBodySkin = Color.Transparent;
                colorHead = Color.Transparent;
                colorHair = Color.Transparent;
                colorEyes = Color.Transparent;
                colorEyeWhites = Color.Transparent;
            }
        }
        float num12 = 1f;
        float num13 = 1f;
        float num14 = 1f;
        float num15 = 1f;
        if (drawPlayer.honey && Main.rand.Next(30) == 0 && shadow == 0f)
        {
            Dust dust2 = Dust.NewDustDirect(Position, drawPlayer.width, drawPlayer.height, 152, 0f, 0f, 150);
            dust2.velocity.Y = 0.3f;
            dust2.velocity.X *= 0.1f;
            dust2.scale += (float)Main.rand.Next(3, 4) * 0.1f;
            dust2.alpha = 100;
            dust2.noGravity = true;
            dust2.velocity += drawPlayer.velocity * 0.1f;
            DustCache.Add(dust2.dustIndex);
        }
        if (drawPlayer.dryadWard && drawPlayer.velocity.X != 0f && Main.rand.Next(4) == 0)
        {
            Dust dust3 = Dust.NewDustDirect(new Vector2(drawPlayer.position.X - 2f, drawPlayer.position.Y + (float)drawPlayer.height - 2f), drawPlayer.width + 4, 4, 163, 0f, 0f, 100, default(Color), 1.5f);
            dust3.noGravity = true;
            dust3.noLight = true;
            dust3.velocity *= 0f;
            DustCache.Add(dust3.dustIndex);
        }
        if (drawPlayer.poisoned)
        {
            if (Main.rand.Next(50) == 0 && shadow == 0f)
            {
                Dust dust4 = Dust.NewDustDirect(Position, drawPlayer.width, drawPlayer.height, 46, 0f, 0f, 150, default(Color), 0.2f);
                dust4.noGravity = true;
                dust4.fadeIn = 1.9f;
                DustCache.Add(dust4.dustIndex);
            }
            num12 *= 0.65f;
            num14 *= 0.75f;
        }
        if (drawPlayer.venom)
        {
            if (Main.rand.Next(10) == 0 && shadow == 0f)
            {
                Dust dust5 = Dust.NewDustDirect(Position, drawPlayer.width, drawPlayer.height, 171, 0f, 0f, 100, default(Color), 0.5f);
                dust5.noGravity = true;
                dust5.fadeIn = 1.5f;
                DustCache.Add(dust5.dustIndex);
            }
            num13 *= 0.45f;
            num12 *= 0.75f;
        }
        if (drawPlayer.onFire)
        {
            if (Main.rand.Next(4) == 0 && shadow == 0f)
            {
                Dust dust6 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 6, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 3f);
                dust6.noGravity = true;
                dust6.velocity *= 1.8f;
                dust6.velocity.Y -= 0.5f;
                DustCache.Add(dust6.dustIndex);
            }
            num14 *= 0.6f;
            num13 *= 0.7f;
        }
        if (drawPlayer.onFire3)
        {
            if (Main.rand.Next(4) == 0 && shadow == 0f)
            {
                Dust dust7 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 6, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 3f);
                dust7.noGravity = true;
                dust7.velocity *= 1.8f;
                dust7.velocity.Y -= 0.5f;
                DustCache.Add(dust7.dustIndex);
            }
            num14 *= 0.6f;
            num13 *= 0.7f;
        }
        if (drawPlayer.dripping && shadow == 0f && Main.rand.Next(4) != 0)
        {
            Vector2 position = Position;
            position.X -= 2f;
            position.Y -= 2f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust8 = Dust.NewDustDirect(position, drawPlayer.width + 4, drawPlayer.height + 2, 211, 0f, 0f, 50, default(Color), 0.8f);
                if (Main.rand.Next(2) == 0)
                {
                    dust8.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust8.alpha += 25;
                }
                dust8.noLight = true;
                dust8.velocity *= 0.2f;
                dust8.velocity.Y += 0.2f;
                dust8.velocity += drawPlayer.velocity;
                DustCache.Add(dust8.dustIndex);
            }
            else
            {
                Dust dust9 = Dust.NewDustDirect(position, drawPlayer.width + 8, drawPlayer.height + 8, 211, 0f, 0f, 50, default(Color), 1.1f);
                if (Main.rand.Next(2) == 0)
                {
                    dust9.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust9.alpha += 25;
                }
                dust9.noLight = true;
                dust9.noGravity = true;
                dust9.velocity *= 0.2f;
                dust9.velocity.Y += 1f;
                dust9.velocity += drawPlayer.velocity;
                DustCache.Add(dust9.dustIndex);
            }
        }
        if (drawPlayer.drippingSlime)
        {
            int alpha = 175;
            Color newColor = new Color(0, 80, 255, 100);
            if (Main.rand.Next(4) != 0 && shadow == 0f)
            {
                Vector2 position2 = Position;
                position2.X -= 2f;
                position2.Y -= 2f;
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust10 = Dust.NewDustDirect(position2, drawPlayer.width + 4, drawPlayer.height + 2, 4, 0f, 0f, alpha, newColor, 1.4f);
                    if (Main.rand.Next(2) == 0)
                    {
                        dust10.alpha += 25;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        dust10.alpha += 25;
                    }
                    dust10.noLight = true;
                    dust10.velocity *= 0.2f;
                    dust10.velocity.Y += 0.2f;
                    dust10.velocity += drawPlayer.velocity;
                    DustCache.Add(dust10.dustIndex);
                }
            }
            num12 *= 0.8f;
            num13 *= 0.8f;
        }
        if (drawPlayer.drippingSparkleSlime)
        {
            int alpha2 = 100;
            if (Main.rand.Next(4) != 0 && shadow == 0f)
            {
                Vector2 position3 = Position;
                position3.X -= 2f;
                position3.Y -= 2f;
                if (Main.rand.Next(4) == 0)
                {
                    Color newColor2 = Main.hslToRgb(0.7f + 0.2f * Main.rand.NextFloat(), 1f, 0.5f);
                    newColor2.A /= 2;
                    Dust dust11 = Dust.NewDustDirect(position3, drawPlayer.width + 4, drawPlayer.height + 2, 4, 0f, 0f, alpha2, newColor2, 0.65f);
                    if (Main.rand.Next(2) == 0)
                    {
                        dust11.alpha += 25;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        dust11.alpha += 25;
                    }
                    dust11.noLight = true;
                    dust11.velocity *= 0.2f;
                    dust11.velocity += drawPlayer.velocity * 0.7f;
                    dust11.fadeIn = 0.8f;
                    DustCache.Add(dust11.dustIndex);
                }
                if (Main.rand.Next(30) == 0)
                {
                    Color color2 = Main.hslToRgb(0.7f + 0.2f * Main.rand.NextFloat(), 1f, 0.5f);
                    color2.A /= 2;
                    Dust dust12 = Dust.NewDustDirect(position3, drawPlayer.width + 4, drawPlayer.height + 2, 43, 0f, 0f, 254, new Color(127, 127, 127, 0), 0.45f);
                    dust12.noLight = true;
                    dust12.velocity.X *= 0f;
                    dust12.velocity *= 0.03f;
                    dust12.fadeIn = 0.6f;
                    DustCache.Add(dust12.dustIndex);
                }
            }
            num12 *= 0.94f;
            num13 *= 0.82f;
        }
        if (drawPlayer.ichor)
        {
            num14 = 0f;
        }
        if (drawPlayer.electrified && shadow == 0f && Main.rand.Next(3) == 0)
        {
            Dust dust13 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 226, 0f, 0f, 100, default(Color), 0.5f);
            dust13.velocity *= 1.6f;
            dust13.velocity.Y -= 1f;
            dust13.position = Vector2.Lerp(dust13.position, drawPlayer.Center, 0.5f);
            DustCache.Add(dust13.dustIndex);
        }
        if (drawPlayer.burned)
        {
            if (shadow == 0f)
            {
                Dust dust14 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 6, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 2f);
                dust14.noGravity = true;
                dust14.velocity *= 1.8f;
                dust14.velocity.Y -= 0.75f;
                DustCache.Add(dust14.dustIndex);
            }
            num12 = 1f;
            num14 *= 0.6f;
            num13 *= 0.7f;
        }
        if (drawPlayer.onFrostBurn)
        {
            if (Main.rand.Next(4) == 0 && shadow == 0f)
            {
                Dust dust15 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 135, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 3f);
                dust15.noGravity = true;
                dust15.velocity *= 1.8f;
                dust15.velocity.Y -= 0.5f;
                DustCache.Add(dust15.dustIndex);
            }
            num12 *= 0.5f;
            num13 *= 0.7f;
        }
        if (drawPlayer.onFrostBurn2)
        {
            if (Main.rand.Next(4) == 0 && shadow == 0f)
            {
                Dust dust16 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 135, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 3f);
                dust16.noGravity = true;
                dust16.velocity *= 1.8f;
                dust16.velocity.Y -= 0.5f;
                DustCache.Add(dust16.dustIndex);
            }
            num12 *= 0.5f;
            num13 *= 0.7f;
        }
        if (drawPlayer.onFire2)
        {
            if (Main.rand.Next(4) == 0 && shadow == 0f)
            {
                Dust dust17 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 75, drawPlayer.velocity.X * 0.4f, drawPlayer.velocity.Y * 0.4f, 100, default(Color), 3f);
                dust17.noGravity = true;
                dust17.velocity *= 1.8f;
                dust17.velocity.Y -= 0.5f;
                DustCache.Add(dust17.dustIndex);
            }
            num14 *= 0.6f;
            num13 *= 0.7f;
        }
        if (drawPlayer.noItems)
        {
            num13 *= 0.8f;
            num12 *= 0.65f;
        }
        if (drawPlayer.blind)
        {
            num13 *= 0.65f;
            num12 *= 0.7f;
        }
        if (drawPlayer.bleed)
        {
            num13 *= 0.9f;
            num14 *= 0.9f;
            if (!drawPlayer.dead && Main.rand.Next(30) == 0 && shadow == 0f)
            {
                Dust dust18 = Dust.NewDustDirect(Position, drawPlayer.width, drawPlayer.height, 5);
                dust18.velocity.Y += 0.5f;
                dust18.velocity *= 0.25f;
                DustCache.Add(dust18.dustIndex);
            }
        }
        if (shadow == 0f && drawPlayer.palladiumRegen && drawPlayer.statLife < drawPlayer.statLifeMax2 && Main.instance.IsActive && !Main.gamePaused && drawPlayer.miscCounter % 10 == 0 && shadow == 0f)
        {
            Vector2 position4 = default(Vector2);
            position4.X = Position.X + (float)Main.rand.Next(drawPlayer.width);
            position4.Y = Position.Y + (float)Main.rand.Next(drawPlayer.height);
            position4.X = Position.X + (float)(drawPlayer.width / 2) - 6f;
            position4.Y = Position.Y + (float)(drawPlayer.height / 2) - 6f;
            position4.X -= Main.rand.Next(-10, 11);
            position4.Y -= Main.rand.Next(-20, 21);
            int item = Gore.NewGore(position4, new Vector2((float)Main.rand.Next(-10, 11) * 0.1f, (float)Main.rand.Next(-20, -10) * 0.1f), 331, (float)Main.rand.Next(80, 120) * 0.01f);
            GoreCache.Add(item);
        }
        if (shadow == 0f && drawPlayer.loveStruck && Main.instance.IsActive && !Main.gamePaused && Main.rand.Next(5) == 0)
        {
            Vector2 vector = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
            vector.Normalize();
            vector.X *= 0.66f;
            int num16 = Gore.NewGore(Position + new Vector2(Main.rand.Next(drawPlayer.width + 1), Main.rand.Next(drawPlayer.height + 1)), vector * Main.rand.Next(3, 6) * 0.33f, 331, (float)Main.rand.Next(40, 121) * 0.01f);
            Main.gore[num16].sticky = false;
            Main.gore[num16].velocity *= 0.4f;
            Main.gore[num16].velocity.Y -= 0.6f;
            GoreCache.Add(num16);
        }
        if (drawPlayer.stinky && Main.instance.IsActive && !Main.gamePaused)
        {
            num12 *= 0.7f;
            num14 *= 0.55f;
            if (Main.rand.Next(5) == 0 && shadow == 0f)
            {
                Vector2 vector2 = new Vector2(Main.rand.Next(-10, 11), Main.rand.Next(-10, 11));
                vector2.Normalize();
                vector2.X *= 0.66f;
                vector2.Y = Math.Abs(vector2.Y);
                Vector2 vector3 = vector2 * Main.rand.Next(3, 5) * 0.25f;
                int num17 = Dust.NewDust(Position, drawPlayer.width, drawPlayer.height, 188, vector3.X, vector3.Y * 0.5f, 100, default(Color), 1.5f);
                Main.dust[num17].velocity *= 0.1f;
                Main.dust[num17].velocity.Y -= 0.5f;
                DustCache.Add(num17);
            }
        }
        if (drawPlayer.slowOgreSpit && Main.instance.IsActive && !Main.gamePaused)
        {
            num12 *= 0.6f;
            num14 *= 0.45f;
            if (Main.rand.Next(5) == 0 && shadow == 0f)
            {
                int type = Utils.SelectRandom<int>(Main.rand, 4, 256);
                Dust dust19 = Main.dust[Dust.NewDust(Position, drawPlayer.width, drawPlayer.height, type, 0f, 0f, 100)];
                dust19.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                dust19.fadeIn = 0.5f;
                dust19.velocity *= 0.05f;
                dust19.noLight = true;
                if (dust19.type == 4)
                {
                    dust19.color = new Color(80, 170, 40, 120);
                }
                DustCache.Add(dust19.dustIndex);
            }
            if (Main.rand.Next(5) == 0 && shadow == 0f)
            {
                int num18 = Gore.NewGore(Position + new Vector2(Main.rand.NextFloat(), Main.rand.NextFloat()) * drawPlayer.Size, Vector2.Zero, Utils.SelectRandom<int>(Main.rand, 1024, 1025, 1026), 0.65f);
                Main.gore[num18].velocity *= 0.05f;
                GoreCache.Add(num18);
            }
        }
        if (Main.instance.IsActive && !Main.gamePaused && shadow == 0f)
        {
            float num19 = (float)drawPlayer.miscCounter / 180f;
            float num20 = 0f;
            float num21 = 10f;
            int type2 = 90;
            int num22 = 0;
            for (int i = 0; i < 3; i++)
            {
                switch (i)
                {
                case 0:
                    if (drawPlayer.nebulaLevelLife < 1)
                    {
                        continue;
                    }
                    num20 = (float)Math.PI * 2f / (float)drawPlayer.nebulaLevelLife;
                    num22 = drawPlayer.nebulaLevelLife;
                    break;
                case 1:
                    if (drawPlayer.nebulaLevelMana < 1)
                    {
                        continue;
                    }
                    num20 = (float)Math.PI * -2f / (float)drawPlayer.nebulaLevelMana;
                    num22 = drawPlayer.nebulaLevelMana;
                    num19 = (float)(-drawPlayer.miscCounter) / 180f;
                    num21 = 20f;
                    type2 = 88;
                    break;
                case 2:
                    if (drawPlayer.nebulaLevelDamage < 1)
                    {
                        continue;
                    }
                    num20 = (float)Math.PI * 2f / (float)drawPlayer.nebulaLevelDamage;
                    num22 = drawPlayer.nebulaLevelDamage;
                    num19 = (float)drawPlayer.miscCounter / 180f;
                    num21 = 30f;
                    type2 = 86;
                    break;
                }
                for (int j = 0; j < num22; j++)
                {
                    Dust dust20 = Dust.NewDustDirect(Position, drawPlayer.width, drawPlayer.height, type2, 0f, 0f, 100, default(Color), 1.5f);
                    dust20.noGravity = true;
                    dust20.velocity = Vector2.Zero;
                    dust20.position = drawPlayer.Center + Vector2.UnitY * drawPlayer.gfxOffY + (num19 * ((float)Math.PI * 2f) + num20 * (float)j).ToRotationVector2() * num21;
                    dust20.customData = drawPlayer;
                    DustCache.Add(dust20.dustIndex);
                }
            }
        }
        if (drawPlayer.witheredArmor && Main.instance.IsActive && !Main.gamePaused)
        {
            num13 *= 0.5f;
            num12 *= 0.75f;
        }
        if (drawPlayer.witheredWeapon && drawPlayer.itemAnimation > 0 && heldItem.damage > 0 && Main.instance.IsActive && !Main.gamePaused && Main.rand.Next(3) == 0)
        {
            Dust dust21 = Dust.NewDustDirect(new Vector2(Position.X - 2f, Position.Y - 2f), drawPlayer.width + 4, drawPlayer.height + 4, 272, 0f, 0f, 50, default(Color), 0.5f);
            dust21.velocity *= 1.6f;
            dust21.velocity.Y -= 1f;
            dust21.position = Vector2.Lerp(dust21.position, drawPlayer.Center, 0.5f);
            DustCache.Add(dust21.dustIndex);
        }
        _ = drawPlayer.shimmering;
        if (num12 != 1f || num13 != 1f || num14 != 1f || num15 != 1f)
        {
            if (drawPlayer.onFire || drawPlayer.onFire2 || drawPlayer.onFrostBurn || drawPlayer.onFire3 || drawPlayer.onFrostBurn2)
            {
                colorEyeWhites = drawPlayer.GetImmuneAlpha(Color.White, shadow);
                colorEyes = drawPlayer.GetImmuneAlpha(drawPlayer.eyeColor, shadow);
                colorHair = drawPlayer.GetImmuneAlpha(drawPlayer.GetHairColor(useLighting: false), shadow);
                colorHead = drawPlayer.GetImmuneAlpha(drawPlayer.skinColor, shadow);
                colorBodySkin = drawPlayer.GetImmuneAlpha(drawPlayer.skinColor, shadow);
                colorShirt = drawPlayer.GetImmuneAlpha(drawPlayer.shirtColor, shadow);
                colorUnderShirt = drawPlayer.GetImmuneAlpha(drawPlayer.underShirtColor, shadow);
                colorPants = drawPlayer.GetImmuneAlpha(drawPlayer.pantsColor, shadow);
                colorLegs = drawPlayer.GetImmuneAlpha(drawPlayer.skinColor, shadow);
                colorShoes = drawPlayer.GetImmuneAlpha(drawPlayer.shoeColor, shadow);
                colorArmorHead = drawPlayer.GetImmuneAlpha(Color.White, shadow);
                colorArmorBody = drawPlayer.GetImmuneAlpha(Color.White, shadow);
                colorArmorLegs = drawPlayer.GetImmuneAlpha(Color.White, shadow);
                if (drawPlayer.isDisplayDollOrInanimate)
                {
                    colorDisplayDollSkin = drawPlayer.GetImmuneAlpha(PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, shadow);
                }
            }
            else
            {
                colorEyeWhites = Main.buffColor(colorEyeWhites, num12, num13, num14, num15);
                colorEyes = Main.buffColor(colorEyes, num12, num13, num14, num15);
                colorHair = Main.buffColor(colorHair, num12, num13, num14, num15);
                colorHead = Main.buffColor(colorHead, num12, num13, num14, num15);
                colorBodySkin = Main.buffColor(colorBodySkin, num12, num13, num14, num15);
                colorShirt = Main.buffColor(colorShirt, num12, num13, num14, num15);
                colorUnderShirt = Main.buffColor(colorUnderShirt, num12, num13, num14, num15);
                colorPants = Main.buffColor(colorPants, num12, num13, num14, num15);
                colorLegs = Main.buffColor(colorLegs, num12, num13, num14, num15);
                colorShoes = Main.buffColor(colorShoes, num12, num13, num14, num15);
                colorArmorHead = Main.buffColor(colorArmorHead, num12, num13, num14, num15);
                colorArmorBody = Main.buffColor(colorArmorBody, num12, num13, num14, num15);
                colorArmorLegs = Main.buffColor(colorArmorLegs, num12, num13, num14, num15);
                if (drawPlayer.isDisplayDollOrInanimate)
                {
                    colorDisplayDollSkin = Main.buffColor(PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, num12, num13, num14, num15);
                }
            }
        }
        if (drawPlayer.socialGhost)
        {
            colorEyeWhites = Color.Transparent;
            colorEyes = Color.Transparent;
            colorHair = Color.Transparent;
            colorHead = Color.Transparent;
            colorBodySkin = Color.Transparent;
            colorShirt = Color.Transparent;
            colorUnderShirt = Color.Transparent;
            colorPants = Color.Transparent;
            colorShoes = Color.Transparent;
            colorLegs = Color.Transparent;
            if (colorArmorHead.A > Main.gFade)
            {
                colorArmorHead.A = Main.gFade;
            }
            if (colorArmorBody.A > Main.gFade)
            {
                colorArmorBody.A = Main.gFade;
            }
            if (colorArmorLegs.A > Main.gFade)
            {
                colorArmorLegs.A = Main.gFade;
            }
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = Color.Transparent;
            }
        }
        if (drawPlayer.socialIgnoreLight)
        {
            float num23 = 1f;
            colorEyeWhites = Color.White * num23;
            colorEyes = drawPlayer.eyeColor * num23;
            colorHair = GameShaders.Hair.GetColor(drawPlayer.hairDye, drawPlayer, Color.White);
            colorHead = drawPlayer.skinColor * num23;
            colorBodySkin = drawPlayer.skinColor * num23;
            colorShirt = drawPlayer.shirtColor * num23;
            colorUnderShirt = drawPlayer.underShirtColor * num23;
            colorPants = drawPlayer.pantsColor * num23;
            colorShoes = drawPlayer.shoeColor * num23;
            colorLegs = drawPlayer.skinColor * num23;
            colorArmorHead = Color.White;
            colorArmorBody = Color.White;
            colorArmorLegs = Color.White;
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR * num23;
            }
        }
        if (drawPlayer.opacityForAnimation != 1f)
        {
            shadow = 1f - drawPlayer.opacityForAnimation;
            float opacityForAnimation = drawPlayer.opacityForAnimation;
            opacityForAnimation *= opacityForAnimation;
            colorEyeWhites = Color.White * opacityForAnimation;
            colorEyes = drawPlayer.eyeColor * opacityForAnimation;
            colorHair = GameShaders.Hair.GetColor(drawPlayer.hairDye, drawPlayer, Color.White) * opacityForAnimation;
            colorHead = drawPlayer.skinColor * opacityForAnimation;
            colorBodySkin = drawPlayer.skinColor * opacityForAnimation;
            colorShirt = drawPlayer.shirtColor * opacityForAnimation;
            colorUnderShirt = drawPlayer.underShirtColor * opacityForAnimation;
            colorPants = drawPlayer.pantsColor * opacityForAnimation;
            colorShoes = drawPlayer.shoeColor * opacityForAnimation;
            colorLegs = drawPlayer.skinColor * opacityForAnimation;
            colorArmorHead = drawPlayer.GetImmuneAlpha(Color.White, shadow);
            colorArmorBody = drawPlayer.GetImmuneAlpha(Color.White, shadow);
            colorArmorLegs = drawPlayer.GetImmuneAlpha(Color.White, shadow);
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR * opacityForAnimation;
            }
        }
        stealth = 1f;
        if (heldItem.type == 3106)
        {
            float num24 = drawPlayer.stealth;
            if ((double)num24 < 0.03)
            {
                num24 = 0.03f;
            }
            float num25 = (1f + num24 * 10f) / 11f;
            if (num24 < 0f)
            {
                num24 = 0f;
            }
            if (!(num24 < 1f - shadow) && shadow > 0f)
            {
                num24 = shadow * 0.5f;
            }
            stealth = num25;
            colorArmorHead = new Color((byte)((float)(int)colorArmorHead.R * num24), (byte)((float)(int)colorArmorHead.G * num24), (byte)((float)(int)colorArmorHead.B * num25), (byte)((float)(int)colorArmorHead.A * num24));
            colorArmorBody = new Color((byte)((float)(int)colorArmorBody.R * num24), (byte)((float)(int)colorArmorBody.G * num24), (byte)((float)(int)colorArmorBody.B * num25), (byte)((float)(int)colorArmorBody.A * num24));
            colorArmorLegs = new Color((byte)((float)(int)colorArmorLegs.R * num24), (byte)((float)(int)colorArmorLegs.G * num24), (byte)((float)(int)colorArmorLegs.B * num25), (byte)((float)(int)colorArmorLegs.A * num24));
            num24 *= num24;
            colorEyeWhites = Color.Multiply(colorEyeWhites, num24);
            colorEyes = Color.Multiply(colorEyes, num24);
            colorHair = Color.Multiply(colorHair, num24);
            colorHead = Color.Multiply(colorHead, num24);
            colorBodySkin = Color.Multiply(colorBodySkin, num24);
            colorShirt = Color.Multiply(colorShirt, num24);
            colorUnderShirt = Color.Multiply(colorUnderShirt, num24);
            colorPants = Color.Multiply(colorPants, num24);
            colorShoes = Color.Multiply(colorShoes, num24);
            colorLegs = Color.Multiply(colorLegs, num24);
            colorMount = Color.Multiply(colorMount, num24);
            headGlowColor = Color.Multiply(headGlowColor, num24);
            bodyGlowColor = Color.Multiply(bodyGlowColor, num24);
            armGlowColor = Color.Multiply(armGlowColor, num24);
            legsGlowColor = Color.Multiply(legsGlowColor, num24);
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = Color.Multiply(colorDisplayDollSkin, num24);
            }
        }
        else if (drawPlayer.shroomiteStealth)
        {
            float num26 = drawPlayer.stealth;
            if ((double)num26 < 0.03)
            {
                num26 = 0.03f;
            }
            float num27 = (1f + num26 * 10f) / 11f;
            if (num26 < 0f)
            {
                num26 = 0f;
            }
            if (!(num26 < 1f - shadow) && shadow > 0f)
            {
                num26 = shadow * 0.5f;
            }
            stealth = num27;
            colorArmorHead = new Color((byte)((float)(int)colorArmorHead.R * num26), (byte)((float)(int)colorArmorHead.G * num26), (byte)((float)(int)colorArmorHead.B * num27), (byte)((float)(int)colorArmorHead.A * num26));
            colorArmorBody = new Color((byte)((float)(int)colorArmorBody.R * num26), (byte)((float)(int)colorArmorBody.G * num26), (byte)((float)(int)colorArmorBody.B * num27), (byte)((float)(int)colorArmorBody.A * num26));
            colorArmorLegs = new Color((byte)((float)(int)colorArmorLegs.R * num26), (byte)((float)(int)colorArmorLegs.G * num26), (byte)((float)(int)colorArmorLegs.B * num27), (byte)((float)(int)colorArmorLegs.A * num26));
            num26 *= num26;
            colorEyeWhites = Color.Multiply(colorEyeWhites, num26);
            colorEyes = Color.Multiply(colorEyes, num26);
            colorHair = Color.Multiply(colorHair, num26);
            colorHead = Color.Multiply(colorHead, num26);
            colorBodySkin = Color.Multiply(colorBodySkin, num26);
            colorShirt = Color.Multiply(colorShirt, num26);
            colorUnderShirt = Color.Multiply(colorUnderShirt, num26);
            colorPants = Color.Multiply(colorPants, num26);
            colorShoes = Color.Multiply(colorShoes, num26);
            colorLegs = Color.Multiply(colorLegs, num26);
            colorMount = Color.Multiply(colorMount, num26);
            headGlowColor = Color.Multiply(headGlowColor, num26);
            bodyGlowColor = Color.Multiply(bodyGlowColor, num26);
            armGlowColor = Color.Multiply(armGlowColor, num26);
            legsGlowColor = Color.Multiply(legsGlowColor, num26);
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = Color.Multiply(colorDisplayDollSkin, num26);
            }
        }
        else if (drawPlayer.setVortex)
        {
            float num28 = drawPlayer.stealth;
            if ((double)num28 < 0.03)
            {
                num28 = 0.03f;
            }
            if (num28 < 0f)
            {
                num28 = 0f;
            }
            if (!(num28 < 1f - shadow) && shadow > 0f)
            {
                num28 = shadow * 0.5f;
            }
            stealth = num28;
            Color secondColor = new Color(Vector4.Lerp(Vector4.One, new Vector4(0f, 0.12f, 0.16f, 0f), 1f - num28));
            colorArmorHead = colorArmorHead.MultiplyRGBA(secondColor);
            colorArmorBody = colorArmorBody.MultiplyRGBA(secondColor);
            colorArmorLegs = colorArmorLegs.MultiplyRGBA(secondColor);
            num28 *= num28;
            colorEyeWhites = Color.Multiply(colorEyeWhites, num28);
            colorEyes = Color.Multiply(colorEyes, num28);
            colorHair = Color.Multiply(colorHair, num28);
            colorHead = Color.Multiply(colorHead, num28);
            colorBodySkin = Color.Multiply(colorBodySkin, num28);
            colorShirt = Color.Multiply(colorShirt, num28);
            colorUnderShirt = Color.Multiply(colorUnderShirt, num28);
            colorPants = Color.Multiply(colorPants, num28);
            colorShoes = Color.Multiply(colorShoes, num28);
            colorLegs = Color.Multiply(colorLegs, num28);
            colorMount = Color.Multiply(colorMount, num28);
            headGlowColor = Color.Multiply(headGlowColor, num28);
            bodyGlowColor = Color.Multiply(bodyGlowColor, num28);
            armGlowColor = Color.Multiply(armGlowColor, num28);
            legsGlowColor = Color.Multiply(legsGlowColor, num28);
            if (drawPlayer.isDisplayDollOrInanimate)
            {
                colorDisplayDollSkin = Color.Multiply(colorDisplayDollSkin, num28);
            }
        }
        if (hideEntirePlayer)
        {
            stealth = 1f;
            colorDisplayDollSkin = (legsGlowColor = (armGlowColor = (bodyGlowColor = (headGlowColor = (colorLegs = (colorShoes = (colorPants = (colorUnderShirt = (colorShirt = (colorBodySkin = (colorHead = (colorHair = (colorEyes = (colorEyeWhites = (colorArmorLegs = (colorArmorBody = (colorArmorHead = Color.Transparent)))))))))))))))));
        }
        if (drawPlayer.gravDir == 1f)
        {
            if (drawPlayer.direction == 1)
            {
                playerEffect = SpriteEffects.None;
                itemEffect = SpriteEffects.None;
            }
            else
            {
                playerEffect = SpriteEffects.FlipHorizontally;
                itemEffect = SpriteEffects.FlipHorizontally;
            }
            if (!drawPlayer.dead)
            {
                drawPlayer.legPosition.Y = 0f;
                drawPlayer.headPosition.Y = 0f;
                drawPlayer.bodyPosition.Y = 0f;
            }
        }
        else
        {
            if (drawPlayer.direction == 1)
            {
                playerEffect = SpriteEffects.FlipVertically;
                itemEffect = SpriteEffects.FlipVertically;
            }
            else
            {
                playerEffect = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
                itemEffect = SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
            }
            if (!drawPlayer.dead)
            {
                drawPlayer.legPosition.Y = 6f;
                drawPlayer.headPosition.Y = 6f;
                drawPlayer.bodyPosition.Y = 6f;
            }
        }
        switch (heldItem.type)
        {
        case 3182:
        case 3184:
        case 3185:
        case 3782:
            itemEffect ^= SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
            break;
        case 5118:
            if (player.gravDir < 0f)
            {
                itemEffect ^= SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
            }
            break;
        }
        legVect = new Vector2((float)drawPlayer.legFrame.Width * 0.5f, (float)drawPlayer.legFrame.Height * 0.75f);
        bodyVect = new Vector2((float)drawPlayer.legFrame.Width * 0.5f, (float)drawPlayer.legFrame.Height * 0.5f);
        headVect = new Vector2((float)drawPlayer.legFrame.Width * 0.5f, (float)drawPlayer.legFrame.Height * 0.4f);
        if ((drawPlayer.merman || drawPlayer.forceMerman) && !drawPlayer.hideMerman)
        {
            drawPlayer.headRotation = drawPlayer.velocity.Y * (float)drawPlayer.direction * 0.1f;
            if ((double)drawPlayer.headRotation < -0.3)
            {
                drawPlayer.headRotation = -0.3f;
            }
            if ((double)drawPlayer.headRotation > 0.3)
            {
                drawPlayer.headRotation = 0.3f;
            }
        }
        else if (!drawPlayer.dead)
        {
            drawPlayer.headRotation = 0f;
        }
        Rectangle bodyFrame = drawPlayer.bodyFrame;
        bodyFrame = drawPlayer.bodyFrame;
        bodyFrame.Y -= 336;
        if (bodyFrame.Y < 0)
        {
            bodyFrame.Y = 0;
        }
        hairFrontFrame = bodyFrame;
        hairBackFrame = bodyFrame;
        if (hideHair)
        {
            hairFrontFrame.Height = 0;
            hairBackFrame.Height = 0;
        }
        else if (backHairDraw)
        {
            int height = 26;
            hairFrontFrame.Height = height;
        }
        hidesTopSkin = drawPlayer.body == 82 || drawPlayer.body == 83 || drawPlayer.body == 93 || drawPlayer.body == 21 || drawPlayer.body == 22;
        hidesBottomSkin = drawPlayer.body == 93 || drawPlayer.legs == 20 || drawPlayer.legs == 21;
        drawFloatingTube = drawPlayer.hasFloatingTube && !hideEntirePlayer;
        drawUnicornHorn = drawPlayer.hasUnicornHorn;
        drawAngelHalo = drawPlayer.hasAngelHalo;
        drawFrontAccInNeckAccLayer = false;
        if (drawPlayer.bodyFrame.Y / drawPlayer.bodyFrame.Height == 5)
        {
            drawFrontAccInNeckAccLayer = drawPlayer.front > 0 && drawPlayer.front < ArmorIDs.Front.Count && ArmorIDs.Front.Sets.DrawsInNeckLayer[drawPlayer.front];
        }
        hairOffset = drawPlayer.GetHairDrawOffset(drawPlayer.hair, hatHair);
        helmetOffset = drawPlayer.GetHelmetDrawOffset();
        legsOffset = drawPlayer.GetLegsDrawOffset();
        CreateCompositeData();
    }
References Terraria.Mount.Active, Terraria.DataStructures.PlayerDrawSet.AdjustmentsForWolfMount(), Terraria.DataStructures.PlayerDrawSet.ArkhalisColor, Terraria.DataStructures.PlayerDrawSet.armGlowColor, Terraria.DataStructures.PlayerDrawSet.armGlowMask, Terraria.DataStructures.PlayerDrawSet.armorAdjust, Terraria.Player.back, Terraria.DataStructures.PlayerDrawSet.backHairDraw, Terraria.Player.backpack, Terraria.Player.balloon, Terraria.Player.balloonFront, Terraria.Player.beard, Terraria.Player.bleed, Terraria.Player.blind, Terraria.Player.body, Terraria.Player.bodyFrame, Terraria.DataStructures.PlayerDrawSet.bodyGlowColor, Terraria.DataStructures.PlayerDrawSet.bodyGlowMask, Terraria.DataStructures.PlayerDrawSet.bodyVect, Terraria.Main.buffColor(), Terraria.Player.burned, Terraria.DataStructures.PlayerDrawSet.cAngelHalo, Terraria.Player.cAngelHalo, Terraria.DataStructures.PlayerDrawSet.cBack, Terraria.Player.cBack, Terraria.DataStructures.PlayerDrawSet.cBackpack, Terraria.Player.cBackpack, Terraria.DataStructures.PlayerDrawSet.cBalloon, Terraria.Player.cBalloon, Terraria.DataStructures.PlayerDrawSet.cBalloonFront, Terraria.Player.cBalloonFront, Terraria.DataStructures.PlayerDrawSet.cBeard, Terraria.Player.cBeard, Terraria.DataStructures.PlayerDrawSet.cBody, Terraria.Player.cBody, Terraria.DataStructures.PlayerDrawSet.cCarpet, Terraria.Player.cCarpet, Terraria.DataStructures.PlayerDrawSet.Center, Terraria.Entity.Center, Terraria.DataStructures.PlayerDrawSet.cFace, Terraria.Player.cFace, Terraria.DataStructures.PlayerDrawSet.cFaceFlower, Terraria.Player.cFaceFlower, Terraria.DataStructures.PlayerDrawSet.cFaceHead, Terraria.Player.cFaceHead, Terraria.DataStructures.PlayerDrawSet.cFlameWaker, Terraria.Player.cFlameWaker, Terraria.DataStructures.PlayerDrawSet.cFloatingTube, Terraria.Player.cFloatingTube, Terraria.DataStructures.PlayerDrawSet.cFront, Terraria.Player.cFront, Terraria.DataStructures.PlayerDrawSet.cHandOff, Terraria.Player.cHandOff, Terraria.DataStructures.PlayerDrawSet.cHandOn, Terraria.Player.cHandOn, Terraria.DataStructures.PlayerDrawSet.cHead, Terraria.Player.cHead, Terraria.DataStructures.PlayerDrawSet.cLegs, Terraria.Player.cLegs, Terraria.DataStructures.PlayerDrawSet.cLeinShampoo, Terraria.Player.cLeinShampoo, Terraria.Player.cMount, Terraria.DataStructures.PlayerDrawSet.cNeck, Terraria.Player.cNeck, Terraria.DataStructures.PlayerDrawSet.colorArmorBody, Terraria.DataStructures.PlayerDrawSet.colorArmorHead, Terraria.DataStructures.PlayerDrawSet.colorArmorLegs, Terraria.DataStructures.PlayerDrawSet.colorBodySkin, Terraria.DataStructures.PlayerDrawSet.colorDisplayDollSkin, Terraria.DataStructures.PlayerDrawSet.colorElectricity, Terraria.DataStructures.PlayerDrawSet.colorEyes, Terraria.DataStructures.PlayerDrawSet.colorEyeWhites, Terraria.DataStructures.PlayerDrawSet.colorHair, Terraria.DataStructures.PlayerDrawSet.colorHead, Terraria.DataStructures.PlayerDrawSet.colorLegs, Terraria.DataStructures.PlayerDrawSet.colorMount, Terraria.DataStructures.PlayerDrawSet.colorPants, Terraria.DataStructures.PlayerDrawSet.colorShirt, Terraria.DataStructures.PlayerDrawSet.colorShoes, Terraria.DataStructures.PlayerDrawSet.colorUnderShirt, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Body.Count, Terraria.ID.ArmorIDs.Legs.Count, Terraria.ID.ArmorIDs.HandOn.Count, Terraria.ID.ArmorIDs.HandOff.Count, Terraria.ID.ArmorIDs.Back.Count, Terraria.ID.ArmorIDs.Front.Count, Terraria.ID.ArmorIDs.Shoe.Count, Terraria.ID.ArmorIDs.Waist.Count, Terraria.ID.ArmorIDs.Shield.Count, Terraria.ID.ArmorIDs.Neck.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Balloon.Count, Terraria.ID.ArmorIDs.Beard.Count, Terraria.DataStructures.PlayerDrawSet.cPortableStool, Terraria.Player.cPortableStool, Terraria.DataStructures.PlayerDrawSet.CreateCompositeData(), Terraria.DataStructures.PlayerDrawSet.cShield, Terraria.Player.cShield, Terraria.DataStructures.PlayerDrawSet.cShoe, Terraria.Player.cShoe, Terraria.DataStructures.PlayerDrawSet.cTail, Terraria.Player.cTail, Terraria.DataStructures.PlayerDrawSet.cUnicornHorn, Terraria.Player.cUnicornHorn, Terraria.DataStructures.PlayerDrawSet.cWaist, Terraria.Player.cWaist, Terraria.DataStructures.PlayerDrawSet.cWings, Terraria.Player.cWings, Terraria.Item.damage, Terraria.Player.dead, Terraria.Entity.direction, Terraria.DataStructures.PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Terraria.DataStructures.PlayerDrawSet.drawAngelHalo, Terraria.DataStructures.PlayerDrawSet.DrawDataCache, Terraria.DataStructures.PlayerDrawSet.drawFloatingTube, Terraria.DataStructures.PlayerDrawSet.drawFrontAccInNeckAccLayer, Terraria.DataStructures.PlayerDrawSet.drawPlayer, Terraria.DataStructures.PlayerDrawSet.drawsBackHairWithoutHeadgear, Terraria.ID.ArmorIDs.Front.Sets.DrawsInNeckLayer, Terraria.DataStructures.PlayerDrawSet.drawUnicornHorn, Terraria.Player.dripping, Terraria.Player.drippingSlime, Terraria.Player.drippingSparkleSlime, Terraria.Player.dryadWard, Terraria.Main.dust, Terraria.DataStructures.PlayerDrawSet.DustCache, Terraria.Dust.dustIndex, Terraria.Player.electrified, Terraria.Player.eyebrellaCloud, Terraria.Player.eyeColor, Terraria.Player.face, Terraria.Player.faceFlower, Terraria.Player.faceHead, Terraria.DataStructures.PlayerDrawSet.floatingTubeColor, Terraria.Player.forceMerman, Terraria.Player.front, Terraria.ID.ArmorIDs.Head.Sets.FrontToBackID, Terraria.DataStructures.PlayerDrawSet.fullHair, Terraria.Main.gamePaused, Terraria.Lighting.GetColor(), Terraria.Graphics.Shaders.HairShaderDataSet.GetColor(), Terraria.Lighting.GetColorClamped(), Terraria.Player.GetHairColor(), Terraria.Player.GetHairDrawOffset(), Terraria.Player.GetHairSettings(), Terraria.Player.GetHelmetDrawOffset(), Terraria.Player.GetImmuneAlpha(), Terraria.Player.GetImmuneAlphaPure(), Terraria.Player.GetLegsDrawOffset(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.Main.gFade, Terraria.Main.gore, Terraria.DataStructures.PlayerDrawSet.GoreCache, Terraria.Player.gravDir, Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Player.hair, Terraria.DataStructures.PlayerDrawSet.hairBackFrame, Terraria.Player.hairDye, Terraria.DataStructures.PlayerDrawSet.hairDyePacked, Terraria.DataStructures.PlayerDrawSet.hairFrontFrame, Terraria.DataStructures.PlayerDrawSet.hairOffset, Terraria.Player.handoff, Terraria.Player.handon, Terraria.Player.hasAngelHalo, Terraria.Player.hasUnicornHorn, Terraria.DataStructures.PlayerDrawSet.hatHair, Terraria.Player.head, Terraria.DataStructures.PlayerDrawSet.headGlowColor, Terraria.DataStructures.PlayerDrawSet.headGlowMask, Terraria.Player.headRotation, Terraria.DataStructures.PlayerDrawSet.headVect, Terraria.Entity.height, Terraria.Player.HeightOffsetVisual, Terraria.DataStructures.PlayerDrawSet.heldItem, Terraria.Player.heldProj, Terraria.DataStructures.PlayerDrawSet.heldProjOverHand, Terraria.DataStructures.PlayerDrawSet.helmetOffset, Terraria.DataStructures.PlayerDrawSet.hideEntirePlayer, Terraria.DataStructures.PlayerDrawSet.hideHair, Terraria.Player.hideMerman, Terraria.DataStructures.PlayerDrawSet.hidesBottomSkin, Terraria.DataStructures.PlayerDrawSet.hidesTopSkin, Terraria.Player.honey, Terraria.Main.hslToRgb(), Terraria.Player.ichor, Terraria.Main.InSmartCursorHighlightArea(), Terraria.Main.instance, Terraria.Player.isDisplayDollOrInanimate, Terraria.Player.isFullbright, Terraria.Player.isHatRackDoll, Terraria.GameContent.Golf.GolfHelper.IsPlayerHoldingClub(), Terraria.DataStructures.PlayerDrawSet.isSitting, Terraria.DataStructures.PlayerDrawSet.isSleeping, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.DataStructures.PlayerDrawSet.itemEffect, Terraria.DataStructures.PlayerDrawSet.ItemLocation, Terraria.Player.lastVisualizedSelectedItem, Terraria.Player.legFrame, Terraria.Player.legs, Terraria.DataStructures.PlayerDrawSet.legsGlowColor, Terraria.DataStructures.PlayerDrawSet.legsGlowMask, Terraria.DataStructures.PlayerDrawSet.legsOffset, Terraria.DataStructures.PlayerDrawSet.legVect, Terraria.Main.LoadAccBack(), Terraria.Main.LoadAccBalloon(), Terraria.Main.LoadAccBeard(), Terraria.Main.LoadAccFace(), Terraria.Main.LoadAccFront(), Terraria.Main.LoadAccHandsOff(), Terraria.Main.LoadAccHandsOn(), Terraria.Main.LoadAccNeck(), Terraria.Main.LoadAccShield(), Terraria.Main.LoadAccShoes(), Terraria.Main.LoadAccWaist(), Terraria.Main.LoadArmorBody(), Terraria.Main.LoadArmorHead(), Terraria.Main.LoadArmorLegs(), Terraria.Main.LoadHair(), Terraria.Main.LoadProjectile(), Terraria.Player.loveStruck, Terraria.Player.Male, Terraria.Player.merman, Terraria.Player.miscCounter, Terraria.DataStructures.PlayerDrawSet.missingArm, Terraria.DataStructures.PlayerDrawSet.missingHand, Terraria.Player.mount, Terraria.DataStructures.PlayerDrawSet.mountOffSet, Terraria.Player.MountXOffset, Terraria.Player.nebulaLevelDamage, Terraria.Player.nebulaLevelLife, Terraria.Player.nebulaLevelMana, Terraria.Player.neck, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Player.noItems, Terraria.Player.onFire, Terraria.Player.onFire2, Terraria.Player.onFire3, Terraria.Player.onFrostBurn, Terraria.Player.onFrostBurn2, Terraria.Player.opacityForAnimation, Terraria.DataStructures.PlayerDrawHelper.PackShader(), Terraria.Player.palladiumRegen, Terraria.Player.pantsColor, Terraria.DataStructures.PlayerDrawSet.playerEffect, Terraria.Player.poisoned, Terraria.DataStructures.PlayerDrawSet.Position, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projectile, Terraria.DataStructures.PlayerDrawSet.projectileDrawPosition, Terraria.Main.rand, Terraria.DataStructures.PlayerDrawSet.rotation, Terraria.DataStructures.PlayerDrawSet.rotationOrigin, Terraria.DataStructures.PlayerDrawSet.seatYOffset, Terraria.DataStructures.PlayerDrawSet.selectionGlowColor, Terraria.Player.setVortex, Terraria.DataStructures.PlayerDrawSet.shadow, Terraria.Player.shield, Terraria.Player.shimmering, Terraria.Player.shirtColor, Terraria.Player.shoe, Terraria.Player.shoeColor, Terraria.Player.shroomiteStealth, Terraria.Player.sitting, Terraria.DataStructures.PlayerDrawSet.sittingIndex, Terraria.Entity.Size, Terraria.Player.skinColor, Terraria.DataStructures.PlayerDrawSet.skinDyePacked, Terraria.Player.skinDyePacked, Terraria.DataStructures.PlayerDrawSet.skinVar, Terraria.Player.skinVariant, Terraria.Player.sleeping, Terraria.Player.slowOgreSpit, Terraria.Player.socialGhost, Terraria.Player.socialIgnoreLight, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.DataStructures.PlayerDrawSet.stealth, Terraria.Player.stealth, Terraria.Gore.sticky, Terraria.Player.stinky, Terraria.Player.tail, Terraria.DataStructures.PlayerDrawSet.torsoOffset, Terraria.Item.type, Terraria.Mount.Type, Terraria.Projectile.type, Terraria.Player.underShirtColor, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, Terraria.Player.venom, Terraria.Player.waist, Terraria.DataStructures.PlayerDrawSet.weaponDrawOrder, Terraria.Player.wearsRobe, Terraria.Entity.width, Terraria.Player.witheredArmor, and Terraria.Player.witheredWeapon.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer().