Terraria: System.Collections.Generic.GenericArraySortHelper.LessThan
LessThan() [1/2]
static bool System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.LessThan (ref T left, ref T right) inline static private
Definition at line 265 of file GenericArraySortHelper.cs.
    {
        if (typeof(T) == typeof(byte))
        {
            if ((byte)(object)left >= (byte)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(sbyte))
        {
            if ((sbyte)(object)left >= (sbyte)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(ushort))
        {
            if ((ushort)(object)left >= (ushort)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(short))
        {
            if ((short)(object)left >= (short)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(uint))
        {
            if ((uint)(object)left >= (uint)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(int))
        {
            if ((int)(object)left >= (int)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(ulong))
        {
            if ((ulong)(object)left >= (ulong)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(long))
        {
            if ((long)(object)left >= (long)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(UIntPtr))
        {
            if ((nuint)(UIntPtr)(object)left >= (nuint)(UIntPtr)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(IntPtr))
        {
            if ((nint)(IntPtr)(object)left >= (nint)(IntPtr)(object)right)
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(float))
        {
            if (!((float)(object)left < (float)(object)right))
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(double))
        {
            if (!((double)(object)left < (double)(object)right))
            {
                return false;
            }
            return true;
        }
        if (typeof(T) == typeof(Half))
        {
            if (!((Half)(object)left < (Half)(object)right))
            {
                return false;
            }
            return true;
        }
        if (left.CompareTo(right) >= 0)
        {
            return false;
        }
        return true;
    }
Referenced by System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.DownHeap(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.DownHeap(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.InsertionSort(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.InsertionSort(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.PickPivotAndPartition(), and System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.PickPivotAndPartition().