Terraria: System.Collections.Generic.GenericArraySortHelper.PickPivotAndPartition
PickPivotAndPartition() [2/2]
static int System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.PickPivotAndPartition (Span< TKey > keys, Span< TValue > values) inline static private
Definition at line 594 of file GenericArraySortHelper.cs.
    {
        int num = keys.Length - 1;
        int num2 = num >> 1;
        SwapIfGreaterWithValues(keys, values, 0, num2);
        SwapIfGreaterWithValues(keys, values, 0, num);
        SwapIfGreaterWithValues(keys, values, num2, num);
        TKey left = keys[num2];
        Swap(keys, values, num2, num - 1);
        int num3 = 0;
        int num4 = num - 1;
        while (num3 < num4)
        {
            if (left == null)
            {
                while (num3 < num - 1 && keys[++num3] == null)
                {
                }
                while (num4 > 0 && keys[--num4] != null)
                {
                }
            }
            else
            {
                while (GreaterThan(ref left, ref keys[++num3]))
                {
                }
                while (LessThan(ref left, ref keys[--num4]))
                {
                }
            }
            if (num3 >= num4)
            {
                break;
            }
            Swap(keys, values, num3, num4);
        }
        if (num3 != num - 1)
        {
            Swap(keys, values, num3, num - 1);
        }
        return num3;
    }
References System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.GreaterThan(), System.keys, System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.LessThan(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Swap(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.SwapIfGreaterWithValues(), and System.values.