Terraria: System.Collections.Generic.GenericArraySortHelper.Sort
Sort() [1/4]
void System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort (Span< T > keys, IComparer< T > comparer) inline
Definition at line 10 of file GenericArraySortHelper.cs.
    {
        try
        {
            if (comparer == null || comparer == Comparer<T>.Default)
            {
                if (keys.Length <= 1)
                {
                    return;
                }
                if (typeof(T) == typeof(double) || typeof(T) == typeof(float) || typeof(T) == typeof(Half))
                {
                    int num = SortUtils.MoveNansToFront(keys, default(Span<byte>));
                    if (num == keys.Length)
                    {
                        return;
                    }
                    keys = keys.Slice(num);
                }
                IntroSort(keys, 2 * (BitOperations.Log2((uint)keys.Length) + 1));
            }
            else
            {
                ArraySortHelper<T>.IntrospectiveSort(keys, comparer.Compare);
            }
        }
        catch (IndexOutOfRangeException)
        {
            ThrowHelper.ThrowArgumentException_BadComparer(comparer);
        }
        catch (Exception e)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_IComparerFailed, e);
        }
    }
References System.comparer, System.Default, System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.IntroSort(), System.keys, System.Numerics.BitOperations.Log2(), System.ThrowHelper.ThrowArgumentException_BadComparer(), and System.ThrowHelper.ThrowInvalidOperationException().