Terraria: System.Collections.Generic.GenericArraySortHelper.Sort
Sort() [4/4]
void System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Sort (Span< TKey > keys, Span< TValue > values, IComparer< TKey > comparer) inline
Implements System.Collections.Generic.IArraySortHelper< TKey, TValue >.
Definition at line 494 of file GenericArraySortHelper.cs.
    {
        try
        {
            if (comparer == null || comparer == Comparer<TKey>.Default)
            {
                if (keys.Length <= 1)
                {
                    return;
                }
                if (typeof(TKey) == typeof(double) || typeof(TKey) == typeof(float) || typeof(TKey) == typeof(Half))
                {
                    int num = SortUtils.MoveNansToFront(keys, values);
                    if (num == keys.Length)
                    {
                        return;
                    }
                    keys = keys.Slice(num);
                    values = values.Slice(num);
                }
                IntroSort(keys, values, 2 * (BitOperations.Log2((uint)keys.Length) + 1));
            }
            else
            {
                ArraySortHelper<TKey, TValue>.IntrospectiveSort(keys, values, comparer);
            }
        }
        catch (IndexOutOfRangeException)
        {
            ThrowHelper.ThrowArgumentException_BadComparer(comparer);
        }
        catch (Exception e)
        {
            ThrowHelper.ThrowInvalidOperationException(ExceptionResource.InvalidOperation_IComparerFailed, e);
        }
    }
References System.comparer, System.Default, System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.IntroSort(), System.keys, System.Numerics.BitOperations.Log2(), System.ThrowHelper.ThrowArgumentException_BadComparer(), System.ThrowHelper.ThrowInvalidOperationException(), and System.values.