Terraria: System.Collections.Generic.GenericArraySortHelper.PickPivotAndPartition
PickPivotAndPartition() [1/2]
static int System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.PickPivotAndPartition (Span< T > keys) inline static private
Definition at line 145 of file GenericArraySortHelper.cs.
    {
        ref T reference = ref MemoryMarshal.GetReference(keys);
        ref T j = ref Unsafe.Add(ref reference, keys.Length - 1);
        ref T reference2 = ref Unsafe.Add(ref reference, keys.Length - 1 >> 1);
        SwapIfGreater(ref reference, ref reference2);
        SwapIfGreater(ref reference, ref j);
        SwapIfGreater(ref reference2, ref j);
        ref T reference3 = ref Unsafe.Add(ref reference, keys.Length - 2);
        T left = reference2;
        Swap(ref reference2, ref reference3);
        ref T reference4 = ref reference;
        ref T reference5 = ref reference3;
        while (Unsafe.IsAddressLessThan(ref reference4, ref reference5))
        {
            if (left == null)
            {
                while (Unsafe.IsAddressLessThan(ref reference4, ref reference3))
                {
                    ref T reference6 = ref Unsafe.Add(ref reference4, 1);
                    reference4 = ref reference6;
                    if (reference6 != null)
                    {
                        break;
                    }
                }
                while (Unsafe.IsAddressGreaterThan(ref reference5, ref reference))
                {
                    ref T reference7 = ref Unsafe.Add(ref reference5, -1);
                    reference5 = ref reference7;
                    if (reference7 == null)
                    {
                        break;
                    }
                }
            }
            else
            {
                while (Unsafe.IsAddressLessThan(ref reference4, ref reference3))
                {
                    ref T reference8 = ref Unsafe.Add(ref reference4, 1);
                    reference4 = ref reference8;
                    if (!GreaterThan(ref left, ref reference8))
                    {
                        break;
                    }
                }
                while (Unsafe.IsAddressGreaterThan(ref reference5, ref reference))
                {
                    ref T reference9 = ref Unsafe.Add(ref reference5, -1);
                    reference5 = ref reference9;
                    if (!LessThan(ref left, ref reference9))
                    {
                        break;
                    }
                }
            }
            if (!Unsafe.IsAddressLessThan(ref reference4, ref reference5))
            {
                break;
            }
            Swap(ref reference4, ref reference5);
        }
        if (!Unsafe.AreSame(ref reference4, ref reference3))
        {
            Swap(ref reference4, ref reference3);
        }
        return (int)((nint)Unsafe.ByteOffset(ref reference, ref reference4) / Unsafe.SizeOf<T>());
    }
References System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.GreaterThan(), System.keys, System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.LessThan(), System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.Swap(), and System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.SwapIfGreater().
Referenced by System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.IntroSort(), and System.Collections.Generic.GenericArraySortHelper< TKey, TValue >.IntroSort().