Terraria: System.Reflection.MdFieldInfo.CacheEquals
CacheEquals()
override bool System.Reflection.MdFieldInfo.CacheEquals (object o) inline package virtual
Reimplemented from System.Reflection.MemberInfo.
Definition at line 57 of file MdFieldInfo.cs.
    {
        if (o is MdFieldInfo mdFieldInfo && mdFieldInfo.m_tkField == m_tkField)
        {
            return m_declaringType.GetTypeHandleInternal().GetModuleHandle().Equals(mdFieldInfo.m_declaringType.GetTypeHandleInternal().GetModuleHandle());
        }
        return false;
    }
References System.ModuleHandle.Equals(), System.RuntimeTypeHandle.GetModuleHandle(), System.Type.GetTypeHandleInternal(), System.Reflection.RuntimeFieldInfo.m_declaringType, and System.Reflection.MdFieldInfo.m_tkField.