Terraria: System.Diagnostics.DebugProvider.FailCore
FailCore()
static void System.Diagnostics.DebugProvider.FailCore (string stackTrace, string? message, string? detailMessage, string errorSource) inline static inherited
Definition at line 108 of file DebugProvider.cs.
    {
        if (s_FailCore != null)
        {
            s_FailCore(stackTrace, message, detailMessage, errorSource);
            return;
        }
        if (Debugger.IsAttached)
        {
            Debugger.Break();
            return;
        }
        DebugAssertException ex = new DebugAssertException(message, detailMessage, stackTrace);
        Environment.FailFast(ex.Message, ex, errorSource);
    }
References System.Diagnostics.Debugger.Break(), System.Environment.FailFast(), System.Diagnostics.Debugger.IsAttached, System.Exception.Message, and System.Diagnostics.DebugProvider.s_FailCore.
Referenced by System.Diagnostics.Debug.ContractFailure(), System.Diagnostics.DefaultTraceListener.Fail(), and System.Diagnostics.DebugProvider.Fail().