Terraria: System.Diagnostics.DebugProvider.Write
Write() [2/2]
virtual void System.Diagnostics.DebugProvider.Write (string? message) inline virtual inherited
Definition at line 62 of file DebugProvider.cs.
    {
        lock (s_lock)
        {
            if (message == null)
            {
                WriteCore(string.Empty);
                return;
            }
            if (_needIndent)
            {
                message = GetIndentString() + message;
                _needIndent = false;
            }
            WriteCore(message);
            if (message.EndsWith("\r\n", StringComparison.Ordinal))
            {
                _needIndent = true;
            }
        }
    }
References System.Diagnostics.DebugProvider._needIndent, System.Diagnostics.DebugProvider.GetIndentString(), System.Diagnostics.DebugProvider.s_lock, and System.Diagnostics.DebugProvider.WriteCore().
Referenced by System.Diagnostics.DebugProvider.WriteLine().