Terraria: System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder.StateMachineBox.ReturnToCache
ReturnToCache()
void System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.ReturnToCache () inline private inherited
Definition at line 171 of file PoolingAsyncValueTaskMethodBuilder.cs.
        {
            ClearStateUponCompletion();
            _valueTaskSource.Reset();
            if (t_tlsCache == null)
            {
                t_tlsCache = this;
                return;
            }
            ref StateMachineBox<TStateMachine> perCoreCacheSlot = ref PerCoreCacheSlot;
            if (perCoreCacheSlot == null)
            {
                Volatile.Write(ref perCoreCacheSlot, this);
            }
        }
References System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >._valueTaskSource, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.ClearStateUponCompletion(), System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.PerCoreCacheSlot, System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.t_tlsCache, and System.Threading.Volatile.Write().
Referenced by System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder< TResult >.StateMachineBox< TStateMachine >.GetResult().