Terraria: System.Diagnostics.DebugProvider.WriteCore
WriteCore()
static void System.Diagnostics.DebugProvider.WriteCore (string message) inline static inherited
Definition at line 124 of file DebugProvider.cs.
    {
        if (s_WriteCore != null)
        {
            s_WriteCore(message);
            return;
        }
        lock (s_ForLock)
        {
            if (message.Length <= 4091)
            {
                WriteToDebugger(message);
                return;
            }
            int i;
            for (i = 0; i < message.Length - 4091; i += 4091)
            {
                WriteToDebugger(message.Substring(i, 4091));
            }
            WriteToDebugger(message.Substring(i));
        }
    }
References System.Diagnostics.DebugProvider.s_ForLock, System.Diagnostics.DebugProvider.s_WriteCore, and System.Diagnostics.DebugProvider.WriteToDebugger().
Referenced by System.Diagnostics.DefaultTraceListener.Write(), and System.Diagnostics.DebugProvider.Write().