Terraria: System.Globalization.FormatProvider.FormatBigInteger
FormatBigInteger()
static unsafe void System.Globalization.FormatProvider.FormatBigInteger (ref System::Text::ValueStringBuilder sb, int precision, int scale, bool sign, ReadOnlySpan< char > format, NumberFormatInfo numberFormatInfo, char[] digits, int startIndex) inline static package
Definition at line 1208 of file FormatProvider.cs.
    {
        fixed (char* ptr = digits)
        {
            Number.NumberBuffer number = default(Number.NumberBuffer);
            number.overrideDigits = ptr + startIndex;
            number.precision = precision;
            number.scale = scale;
            number.sign = sign;
            int digits2;
            char c = Number.ParseFormatSpecifier(format, out digits2);
            if (c != 0)
            {
                Number.NumberToString(ref sb, ref number, c, digits2, numberFormatInfo, isDecimal: false);
            }
            else
            {
                Number.NumberToStringFormat(ref sb, ref number, format, numberFormatInfo);
            }
        }
    }
References System.format, System.Globalization.FormatProvider.Number.NumberToString(), System.Globalization.FormatProvider.Number.NumberToStringFormat(), System.Globalization.FormatProvider.Number.ParseFormatSpecifier(), and System.startIndex.
Referenced by System.Numerics.BigNumber.FormatBigInteger().