Terraria: System.Buffers.Text.ParserHelpers.IsDigit
IsDigit()
static bool System.Buffers.Text.ParserHelpers.IsDigit (int i) inline static
Definition at line 11 of file ParserHelpers.cs.
    {
        return (uint)(i - 48) <= 9u;
    }
Referenced by System.Buffers.Text.Utf8Parser.TryParseByteD(), System.Buffers.Text.Utf8Parser.TryParseByteN(), System.Buffers.Text.Utf8Parser.TryParseInt16D(), System.Buffers.Text.Utf8Parser.TryParseInt16N(), System.Buffers.Text.Utf8Parser.TryParseInt32D(), System.Buffers.Text.Utf8Parser.TryParseInt32N(), System.Buffers.Text.Utf8Parser.TryParseInt64N(), System.Buffers.Text.Utf8Parser.TryParseSByteD(), System.Buffers.Text.Utf8Parser.TryParseSByteN(), System.Buffers.Text.Utf8Parser.TryParseUInt16D(), System.Buffers.Text.Utf8Parser.TryParseUInt16N(), System.Buffers.Text.Utf8Parser.TryParseUInt32D(), System.Buffers.Text.Utf8Parser.TryParseUInt32N(), and System.Buffers.Text.Utf8Parser.TryParseUInt64N().