Terraria: System.Data.InternalDataCollectionBase.NamesEqual
NamesEqual()
int System.Data.InternalDataCollectionBase.NamesEqual (string s1, string s2, bool fCaseSensitive, CultureInfo locale) inline package
Definition at line 35 of file InternalDataCollectionBase.cs.
    {
        if (fCaseSensitive)
        {
            if (string.Compare(s1, s2, ignoreCase: false, locale) != 0)
            {
                return 0;
            }
            return 1;
        }
        if (locale.CompareInfo.Compare(s1, s2, CompareOptions.IgnoreCase | CompareOptions.IgnoreKanaType | CompareOptions.IgnoreWidth) == 0)
        {
            if (string.Compare(s1, s2, ignoreCase: false, locale) != 0)
            {
                return -1;
            }
            return 1;
        }
        return 0;
    }
References System.Globalization.CompareInfo.Compare(), and System.Globalization.CultureInfo.CompareInfo.
Referenced by System.Data.DataTableCollection.BaseAdd(), System.Data.DataTableCollection.Contains(), System.Data.DataTableCollection.Contains(), System.Data.DataColumnCollection.IndexOfCaseInsensitive(), System.Data.ConstraintCollection.InternalIndexOf(), System.Data.DataRelationCollection.InternalIndexOf(), System.Data.DataTableCollection.InternalIndexOf(), System.Data.DataTableCollection.InternalIndexOf(), System.Data.DataColumnCollection.RegisterColumnName(), System.Data.ConstraintCollection.RegisterName(), System.Data.DataRelationCollection.RegisterName(), System.Data.DataTableCollection.RegisterName(), System.Data.ConstraintCollection.UnregisterName(), System.Data.DataColumnCollection.UnregisterName(), System.Data.DataRelationCollection.UnregisterName(), and System.Data.DataTableCollection.UnregisterName().