Terraria: System.Buffers.Text.ParserHelpers.TryParseThrowFormatException
TryParseThrowFormatException()
static bool System.Buffers.Text.ParserHelpers.TryParseThrowFormatException (out int bytesConsumed) inline static
Definition at line 16 of file ParserHelpers.cs.
    {
        bytesConsumed = 0;
        ThrowHelper.ThrowFormatException_BadFormatSpecifier();
        return false;
    }
References System.ThrowHelper.ThrowFormatException_BadFormatSpecifier().
Referenced by System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParse(), System.Buffers.Text.Utf8Parser.TryParseNormalAsFloatingPoint(), and System.Buffers.Text.ParserHelpers.TryParseThrowFormatException< T >().