Terraria: CreativePowers.APerPlayerTogglePower.DeserializeNetMessage
DeserializeNetMessage()
void CreativePowers.APerPlayerTogglePower.DeserializeNetMessage (BinaryReader reader, int userId) inline inherited
Implements ICreativePower.
         {
             switch ((SubMessageType)reader.ReadByte())
             {
             case SubMessageType.SyncEveryone:
                 Deserialize_SyncEveryone(reader, userId);
                 break;
             case SubMessageType.SyncOnePlayer:
             {
                 int playerIndex = reader.ReadByte();
                 bool state = reader.ReadBoolean();
                 if (Main.netMode == 2)
                 {
                     playerIndex = userId;
                     if (!CreativePowersHelper.IsAvailableForPlayer(this, playerIndex))
                     {
                         break;
                     }
                 }
                 SetEnabledState(playerIndex, state);
                 break;
             }
             }
         }
References CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), CreativePowersHelper.IsAvailableForPlayer(), Main.netMode, and CreativePowers.APerPlayerTogglePower.SetEnabledState().