Terraria: Terraria.WindowsLaunch.Main
Main()
static void Terraria.WindowsLaunch.Main (string[] args) inline static private
Definition at line 54 of file WindowsLaunch.cs.
    {
        AppDomain.CurrentDomain.AssemblyResolve += delegate(object sender, ResolveEventArgs sargs)
        {
            string resourceName = new AssemblyName(sargs.Name).Name + ".dll";
            string text = Array.Find(typeof(Program).Assembly.GetManifestResourceNames(), (string element) => element.EndsWith(resourceName));
            if (text == null)
            {
                return (Assembly)null;
            }
            using Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(text);
            byte[] array = new byte[stream.Length];
            stream.Read(array, 0, array.Length);
            return Assembly.Load(array);
        };
        Program.LaunchGame(args);
    }
References System.array, System.Reflection.Assembly.GetExecutingAssembly(), System.Reflection.Assembly.GetManifestResourceNames(), Terraria.Program.LaunchGame(), System.Reflection.Assembly.Load(), System.Reflection.AssemblyName.Name, System.ResolveEventArgs.Name, System.stream, and System.text.