Terraria: System.Net.Http.RedirectHandler.GetUriForRedirect
GetUriForRedirect()
Uri System.Net.Http.RedirectHandler.GetUriForRedirect (Uri requestUri, HttpResponseMessage response) inline private
Definition at line 64 of file RedirectHandler.cs.
    {
        HttpStatusCode statusCode = response.StatusCode;
        if ((uint)(statusCode - 300) > 3u && (uint)(statusCode - 307) > 1u)
        {
            return null;
        }
        Uri uri = response.Headers.Location;
        if (uri == null)
        {
            return null;
        }
        if (!uri.IsAbsoluteUri)
        {
            uri = new Uri(requestUri, uri);
        }
        string fragment = requestUri.Fragment;
        if (!string.IsNullOrEmpty(fragment))
        {
            string fragment2 = uri.Fragment;
            if (string.IsNullOrEmpty(fragment2))
            {
                uri = new UriBuilder(uri)
                {
                    Fragment = fragment
                }.Uri;
            }
        }
        if (HttpUtilities.IsSupportedSecureScheme(requestUri.Scheme) && !HttpUtilities.IsSupportedSecureScheme(uri.Scheme))
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                TraceError($"Insecure https to http redirect from '{requestUri}' to '{uri}' blocked.", response.RequestMessage.GetHashCode(), "GetUriForRedirect");
            }
            return null;
        }
        return uri;
    }
References System.Uri.Fragment, System.Fragment, System.Net.Http.HttpResponseMessage.Headers, System.Uri.IsAbsoluteUri, System.Net.Http.HttpUtilities.IsSupportedSecureScheme(), System.Net.NetEventSource.Log, System.Net.Http.HttpResponseMessage.RequestMessage, System.Uri.Scheme, System.Net.Http.HttpResponseMessage.StatusCode, and System.Net.Http.RedirectHandler.TraceError().
Referenced by System.Net.Http.RedirectHandler.SendAsync().