Terraria: System.Net.Http.RedirectHandler.SendAsync
SendAsync() [1/2]
override async ValueTask< HttpResponseMessage > System.Net.Http.RedirectHandler.SendAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline package
Definition at line 22 of file RedirectHandler.cs.
    {
        HttpResponseMessage httpResponseMessage = await _initialInnerHandler.SendAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        uint redirectCount = 0u;
        Uri uriForRedirect;
        while ((uriForRedirect = GetUriForRedirect(request.RequestUri, httpResponseMessage)) != null)
        {
            redirectCount++;
            if (redirectCount > _maxAutomaticRedirections)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    TraceError($"Exceeded max number of redirects. Redirect from {request.RequestUri} to {uriForRedirect} blocked.", request.GetHashCode(), "SendAsync");
                }
                break;
            }
            httpResponseMessage.Dispose();
            request.Headers.Authorization = null;
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"Redirecting from {request.RequestUri} to {uriForRedirect} in response to status code {httpResponseMessage.StatusCode} '{httpResponseMessage.StatusCode}'.", request.GetHashCode(), "SendAsync");
            }
            request.RequestUri = uriForRedirect;
            if (RequestRequiresForceGet(httpResponseMessage.StatusCode, request.Method))
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace($"Modified request from {request.Method} to {HttpMethod.Get} in response to status code {httpResponseMessage.StatusCode} '{httpResponseMessage.StatusCode}'.", request.GetHashCode(), "SendAsync");
                }
                request.Method = HttpMethod.Get;
                request.Content = null;
                if (request.Headers.TransferEncodingChunked == true)
                {
                    request.Headers.TransferEncodingChunked = false;
                }
            }
            request.MarkAsRedirected();
            httpResponseMessage = await _redirectInnerHandler.SendAsync(request, async, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        }
        return httpResponseMessage;
    }
References System.Net.Http.RedirectHandler._initialInnerHandler, System.Net.Http.RedirectHandler._maxAutomaticRedirections, System.Net.Http.RedirectHandler._redirectInnerHandler, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Http.HttpResponseMessage.Dispose(), System.Net.Http.HttpMethod.Get, System.Net.Http.RedirectHandler.GetUriForRedirect(), System.Net.Http.HttpRequestMessage.Headers, System.Net.NetEventSource.Log, System.Net.Http.HttpRequestMessage.MarkAsRedirected(), System.Net.Http.HttpRequestMessage.Method, System.Net.Http.RedirectHandler.RequestRequiresForceGet(), System.Net.Http.HttpRequestMessage.RequestUri, System.Net.Http.HttpMessageHandlerStage.SendAsync(), System.Net.Http.HttpResponseMessage.StatusCode, System.Net.Http.RedirectHandler.Trace(), and System.Net.Http.RedirectHandler.TraceError().