Terraria: System.IO.StreamBuffer.Write
Write()
void System.IO.StreamBuffer.Write (ReadOnlySpan< byte > buffer) inline
Definition at line 142 of file StreamBuffer.cs.
    {
        if (buffer.Length == 0)
        {
            return;
        }
        while (true)
        {
            var (flag, start) = TryWriteToBuffer(buffer);
            if (flag)
            {
                buffer = buffer.Slice(start);
                _writeTaskSource.Wait();
                continue;
            }
            break;
        }
    }
References System.IO.StreamBuffer._writeTaskSource, System.buffer, System.start, System.IO.StreamBuffer.TryWriteToBuffer(), and System.IO.StreamBuffer.ResettableValueTaskSource.Wait().
Referenced by System.Net.Quic.Implementations.Mock.MockStream.Write().