Terraria: System.IO.StreamBuffer.TryReadFromBuffer
TryReadFromBuffer()
bool int bytesRead System.IO.StreamBuffer.TryReadFromBuffer (Span< byte > buffer) inline private
Definition at line 193 of file StreamBuffer.cs.
    {
        lock (SyncObject)
        {
            if (_readAborted)
            {
                return (wait: false, bytesRead: 0);
            }
            if (!_buffer.IsEmpty)
            {
                int num = Math.Min(buffer.Length, _buffer.ActiveMemory.Length);
                _buffer.ActiveMemory.Slice(0, num).CopyTo(buffer);
                _buffer.Discard(num);
                _writeTaskSource.SignalWaiter();
                return (wait: false, bytesRead: num);
            }
            if (_writeEnded)
            {
                return (wait: false, bytesRead: 0);
            }
            _readTaskSource.Reset();
            return (wait: true, bytesRead: 0);
        }
    }
References System.IO.StreamBuffer._buffer, System.IO.StreamBuffer._readAborted, System.IO.StreamBuffer._readTaskSource, System.IO.StreamBuffer._writeEnded, System.IO.StreamBuffer._writeTaskSource, System.Net.MultiArrayBuffer.ActiveMemory, System.buffer, System.Net.MultiArrayBuffer.Discard(), System.Net.MultiArrayBuffer.IsEmpty, System.Math.Min(), System.IO.StreamBuffer.ResettableValueTaskSource.Reset(), System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter(), System.IO.StreamBuffer.SyncObject, and System.IO.StreamBuffer.wait.
Referenced by System.IO.StreamBuffer.Read(), and System.IO.StreamBuffer.ReadAsync().