Terraria: System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForWrite
RequiresMemberAccessForWrite()
bool System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForWrite (SecurityException securityException) inline package
Definition at line 1498 of file CollectionDataContract.cs.
    {
        if (!DataContract.IsTypeVisible(base.UnderlyingType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractTypeNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (ItemType != null && !DataContract.IsTypeVisible(ItemType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractTypeNotPublic, DataContract.GetClrTypeFullName(ItemType)), securityException));
            }
            return true;
        }
        return false;
    }
References System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.SR.PartialTrustCollectionContractTypeNotPublic, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().