Terraria: System.Runtime.Serialization.CollectionDataContract.GetCollectionMethods
GetCollectionMethods()
static void System.Runtime.Serialization.CollectionDataContract.GetCollectionMethods ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)] Type interfaceType, Type[] addMethodTypeArray, bool addMethodOnInterface, out MethodInfo getEnumeratorMethod, out MethodInfo addMethod) inline static private
Definition at line 1360 of file CollectionDataContract.cs.
    {
        addMethod = (getEnumeratorMethod = null);
        if (addMethodOnInterface)
        {
            addMethod = type.GetMethod("Add", BindingFlags.Instance | BindingFlags.Public, addMethodTypeArray);
            if (addMethod == null || addMethod.GetParameters()[0].ParameterType != addMethodTypeArray[0])
            {
                FindCollectionMethodsOnInterface(type, interfaceType, ref addMethod, ref getEnumeratorMethod);
                if (addMethod == null)
                {
                    Type[] interfaces = interfaceType.GetInterfaces();
                    Array.Sort(interfaces, (Type x, Type y) => string.Compare(x.FullName, y.FullName));
                    Type[] array = interfaces;
                    foreach (Type type2 in array)
                    {
                        if (IsKnownInterface(type2))
{
                            FindCollectionMethodsOnInterface(type, type2, ref addMethod, ref getEnumeratorMethod);
                            if (addMethod == null)
{
                                break;
                            }
                        }
                    }
                }
            }
        }
        else
        {
            addMethod = type.GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, addMethodTypeArray);
        }
        if (!(getEnumeratorMethod == null))
        {
            return;
        }
        getEnumeratorMethod = type.GetMethod("GetEnumerator", BindingFlags.Instance | BindingFlags.Public, Type.EmptyTypes);
        if (getEnumeratorMethod == null || !Globals.TypeOfIEnumerator.IsAssignableFrom(getEnumeratorMethod.ReturnType))
        {
            Type type3 = (from t in interfaceType.GetInterfaces()
                where t.FullName.StartsWith("System.Collections.Generic.IEnumerable")
                select t).FirstOrDefault();
            if (type3 == null)
            {
                type3 = Globals.TypeOfIEnumerable;
            }
            getEnumeratorMethod = GetIEnumerableGetEnumeratorMethod(type, type3);
        }
    }
References System.array, System.Runtime.Serialization.Dictionary, System.Type.EmptyTypes, System.Runtime.Serialization.CollectionDataContract.FindCollectionMethodsOnInterface(), System.Type.FullName, System.Runtime.Serialization.CollectionDataContract.GetIEnumerableGetEnumeratorMethod(), System.Runtime.Serialization.CollectionDataContract.IsKnownInterface(), System.Array.Sort(), System.type, System.Runtime.Serialization.Globals.TypeOfIEnumerable, and System.Runtime.Serialization.Globals.TypeOfIEnumerator.
Referenced by System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate().