Terraria: System.Runtime.Serialization.CollectionDataContract.GetTargetMethodWithName
GetTargetMethodWithName()
static MethodInfo System.Runtime.Serialization.CollectionDataContract.GetTargetMethodWithName (string name, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type type, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods)] Type interfaceType) inline static package
Definition at line 1093 of file CollectionDataContract.cs.
    {
        return (from it in type.GetInterfaces()
            where it.Equals(interfaceType)
            select it).FirstOrDefault()?.GetMethod(name);
    }
References System.type.
Referenced by System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.GetCollectionElementType(), System.Runtime.Serialization.CollectionDataContract.GetIEnumerableGetEnumeratorMethod(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().