Terraria: System.Runtime.Serialization.CollectionDataContract.TryCreateGetOnlyCollectionDataContract
TryCreateGetOnlyCollectionDataContract()
static bool System.Runtime.Serialization.CollectionDataContract.TryCreateGetOnlyCollectionDataContract (Type type, [NotNullWhen(true)] out DataContract dataContract) inline static package
Definition at line 1071 of file CollectionDataContract.cs.
    {
        dataContract = DataContract.GetDataContractFromGeneratedAssembly(type);
        if (dataContract == null)
        {
            if (type.IsArray)
            {
                dataContract = new CollectionDataContract(type);
                return true;
            }
            Type itemType;
            return IsCollectionOrTryCreate(type, tryCreate: true, out dataContract, out itemType, constructorRequired: false);
        }
        if (dataContract is CollectionDataContract)
        {
            return true;
        }
        dataContract = null;
        return false;
    }
References System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.DataContract.GetDataContractFromGeneratedAssembly(), System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(), and System.type.
Referenced by System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateGetOnlyCollectionDataContract().