Terraria: System.Runtime.Serialization.CollectionDataContract.InitCollectionDataContract
InitCollectionDataContract()
void System.Runtime.Serialization.CollectionDataContract.InitCollectionDataContract (DataContract sharedTypeContract) inline private
Definition at line 951 of file CollectionDataContract.cs.
    {
        _helper = base.Helper as CollectionDataContractCriticalHelper;
        _collectionItemName = _helper.CollectionItemName;
        if (_helper.Kind == CollectionKind.Dictionary || _helper.Kind == CollectionKind.GenericDictionary)
        {
            _itemContract = _helper.ItemContract;
        }
        _helper.SharedTypeContract = sharedTypeContract;
    }
References System.Runtime.Serialization.CollectionDataContract._collectionItemName, System.Runtime.Serialization.CollectionDataContract._helper, System.Runtime.Serialization.CollectionDataContract._itemContract, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.CollectionItemName, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.ItemContract, and System.Runtime.Serialization.CollectionDataContract.CollectionDataContractCriticalHelper.Kind.
Referenced by System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), and System.Runtime.Serialization.CollectionDataContract.CollectionDataContract().