Terraria: System.IO.StreamBuffer.TryWriteToBuffer
TryWriteToBuffer()
bool int bytesWritten System.IO.StreamBuffer.TryWriteToBuffer (ReadOnlySpan< byte > buffer) inline private
Definition at line 112 of file StreamBuffer.cs.
    {
        lock (SyncObject)
        {
            if (_writeEnded)
            {
                throw new InvalidOperationException();
            }
            if (_readAborted)
            {
                return (wait: false, bytesWritten: buffer.Length);
            }
            _buffer.EnsureAvailableSpaceUpToLimit(buffer.Length, _maxBufferSize);
            int num = Math.Min(buffer.Length, _buffer.AvailableMemory.Length);
            if (num > 0)
            {
                _buffer.AvailableMemory.CopyFrom(buffer.Slice(0, num));
                _buffer.Commit(num);
                _readTaskSource.SignalWaiter();
            }
            buffer = buffer.Slice(num);
            if (buffer.Length == 0)
            {
                return (wait: false, bytesWritten: num);
            }
            _writeTaskSource.Reset();
            return (wait: true, bytesWritten: num);
        }
    }
References System.IO.StreamBuffer._buffer, System.IO.StreamBuffer._maxBufferSize, System.IO.StreamBuffer._readAborted, System.IO.StreamBuffer._readTaskSource, System.IO.StreamBuffer._writeEnded, System.IO.StreamBuffer._writeTaskSource, System.Net.MultiArrayBuffer.AvailableMemory, System.buffer, System.Net.MultiArrayBuffer.Commit(), System.Net.MultiArrayBuffer.EnsureAvailableSpaceUpToLimit(), System.Math.Min(), System.IO.StreamBuffer.ResettableValueTaskSource.Reset(), System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter(), System.IO.StreamBuffer.SyncObject, and System.IO.StreamBuffer.wait.
Referenced by System.IO.StreamBuffer.Write(), and System.IO.StreamBuffer.WriteAsync().