Terraria: System.IO.StreamBuffer.Read
Read()
int System.IO.StreamBuffer.Read (Span< byte > buffer) inline
Definition at line 218 of file StreamBuffer.cs.
    {
        if (buffer.Length == 0)
        {
            return 0;
        }
        int result;
        bool flag;
        (flag, result) = TryReadFromBuffer(buffer);
        if (flag)
        {
            _readTaskSource.Wait();
            (flag, result) = TryReadFromBuffer(buffer);
        }
        return result;
    }
References System.IO.StreamBuffer._readTaskSource, System.buffer, System.IO.StreamBuffer.TryReadFromBuffer(), and System.IO.StreamBuffer.ResettableValueTaskSource.Wait().
Referenced by System.Net.Quic.Implementations.Mock.MockStream.Read().