Terraria: System.IO.StreamBuffer.AbortRead
AbortRead()
void System.IO.StreamBuffer.AbortRead () inline
Definition at line 253 of file StreamBuffer.cs.
    {
        lock (SyncObject)
        {
            if (!_readAborted)
            {
                _readAborted = true;
                _buffer.DiscardAll();
                _readTaskSource.SignalWaiter();
                _writeTaskSource.SignalWaiter();
            }
        }
    }
References System.IO.StreamBuffer._buffer, System.IO.StreamBuffer._readAborted, System.IO.StreamBuffer._readTaskSource, System.IO.StreamBuffer._writeTaskSource, System.Net.MultiArrayBuffer.DiscardAll(), System.IO.StreamBuffer.ResettableValueTaskSource.SignalWaiter(), and System.IO.StreamBuffer.SyncObject.
Referenced by System.Net.Quic.Implementations.Mock.MockStream.AbortRead(), and System.IO.StreamBuffer.Dispose().