Terraria: System.Runtime.Serialization.CollectionDataContract.HandleIfInvalidCollection
HandleIfInvalidCollection()
static bool System.Runtime.Serialization.CollectionDataContract.HandleIfInvalidCollection (Type type, bool tryCreate, bool hasCollectionDataContract, bool createContractWithException, string message, string param, ref DataContract dataContract) inline static private
Definition at line 1311 of file CollectionDataContract.cs.
    {
        if (hasCollectionDataContract)
        {
            if (tryCreate)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(GetInvalidCollectionMessage(message, System.SR.Format(System.SR.InvalidCollectionDataContract, DataContract.GetClrTypeFullName(type)), param)));
            }
            return true;
        }
        if (createContractWithException)
        {
            if (tryCreate)
            {
                dataContract = new CollectionDataContract(type, GetInvalidCollectionMessage(message, System.SR.Format(System.SR.InvalidCollectionType, DataContract.GetClrTypeFullName(type)), param));
            }
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.CollectionDataContract.CollectionDataContract(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.CollectionDataContract.GetInvalidCollectionMessage(), System.SR.InvalidCollectionDataContract, System.SR.InvalidCollectionType, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate().