Terraria: System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface
IsCollectionInterface()
static bool System.Runtime.Serialization.CollectionDataContract.IsCollectionInterface (Type type) inline static package
Definition at line 1010 of file CollectionDataContract.cs.
    {
        if (type.IsGenericType)
        {
            type = type.GetGenericTypeDefinition();
        }
        return ((ICollection<Type>)KnownInterfaces).Contains(type);
    }
References System.Runtime.Serialization.CollectionDataContract.KnownInterfaces, and System.type.
Referenced by System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetBuiltInDataContract(), System.Runtime.Serialization.DataContractSerializer.GetDataContract(), System.Runtime.Serialization.ClassDataContract.IsNonAttributedTypeValidForSerialization(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.SerializeWithXsiTypeAtTopLevel(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(), System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType(), and System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface().