Terraria: System.IO.StreamBuffer.WriteAsync
WriteAsync()
async ValueTask System.IO.StreamBuffer.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline
Definition at line 161 of file StreamBuffer.cs.
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (buffer.Length == 0)
        {
            return;
        }
        while (true)
        {
            var (flag, start) = TryWriteToBuffer(buffer.Span);
            if (flag)
            {
                buffer = buffer.Slice(start);
                await _writeTaskSource.WaitAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                continue;
            }
            break;
        }
    }
References System.IO.StreamBuffer._writeTaskSource, System.buffer, System.cancellationToken, System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.start, System.IO.StreamBuffer.TryWriteToBuffer(), and System.IO.StreamBuffer.ResettableValueTaskSource.WaitAsync().
Referenced by System.Net.Quic.Implementations.Mock.MockStream.WriteAsync().