Terraria: System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForRead
RequiresMemberAccessForRead()
bool System.Runtime.Serialization.CollectionDataContract.RequiresMemberAccessForRead (SecurityException securityException) inline package
Definition at line 1461 of file CollectionDataContract.cs.
    {
        if (!DataContract.IsTypeVisible(base.UnderlyingType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractTypeNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (ItemType != null && !DataContract.IsTypeVisible(ItemType))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractTypeNotPublic, DataContract.GetClrTypeFullName(ItemType)), securityException));
            }
            return true;
        }
        if (DataContract.ConstructorRequiresMemberAccess(Constructor))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractNoPublicConstructor, DataContract.GetClrTypeFullName(base.UnderlyingType)), securityException));
            }
            return true;
        }
        if (DataContract.MethodRequiresMemberAccess(AddMethod))
        {
            if (securityException != null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new SecurityException(System.SR.Format(System.SR.PartialTrustCollectionContractAddMethodNotPublic, DataContract.GetClrTypeFullName(base.UnderlyingType), AddMethod.Name), securityException));
            }
            return true;
        }
        return false;
    }
References System.Runtime.Serialization.CollectionDataContract.AddMethod, System.Runtime.Serialization.CollectionDataContract.Constructor, System.Runtime.Serialization.DataContract.ConstructorRequiresMemberAccess(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.IsTypeVisible(), System.Runtime.Serialization.DataContract.MethodRequiresMemberAccess(), System.Reflection.MemberInfo.Name, System.SR.PartialTrustCollectionContractAddMethodNotPublic, System.SR.PartialTrustCollectionContractNoPublicConstructor, System.SR.PartialTrustCollectionContractTypeNotPublic, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().