Terraria: Terraria.GameContent.BackgroundChangeFlashInfo.UpdateCache
UpdateCache()
void Terraria.GameContent.BackgroundChangeFlashInfo.UpdateCache () inline
Definition at line 11 of file BackgroundChangeFlashInfo.cs.
    {
        UpdateVariation(0, WorldGen.treeBG1);
        UpdateVariation(1, WorldGen.treeBG2);
        UpdateVariation(2, WorldGen.treeBG3);
        UpdateVariation(3, WorldGen.treeBG4);
        UpdateVariation(4, WorldGen.corruptBG);
        UpdateVariation(5, WorldGen.jungleBG);
        UpdateVariation(6, WorldGen.snowBG);
        UpdateVariation(7, WorldGen.hallowBG);
        UpdateVariation(8, WorldGen.crimsonBG);
        UpdateVariation(9, WorldGen.desertBG);
        UpdateVariation(10, WorldGen.oceanBG);
        UpdateVariation(11, WorldGen.mushroomBG);
        UpdateVariation(12, WorldGen.underworldBG);
    }
References Terraria.WorldGen.corruptBG, Terraria.WorldGen.crimsonBG, Terraria.WorldGen.desertBG, Terraria.WorldGen.hallowBG, Terraria.WorldGen.jungleBG, Terraria.WorldGen.mushroomBG, Terraria.WorldGen.oceanBG, Terraria.WorldGen.snowBG, Terraria.WorldGen.treeBG1, Terraria.WorldGen.treeBG2, Terraria.WorldGen.treeBG3, Terraria.WorldGen.treeBG4, Terraria.WorldGen.underworldBG, and Terraria.GameContent.BackgroundChangeFlashInfo.UpdateVariation().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer().