Terraria: System.Xml.Xsl.XsltOld.Compiler.Compile
Compile()
void System.Xml.Xsl.XsltOld.Compiler.Compile (NavigatorInput input, XmlResolver xmlResolver) inline package
Definition at line 174 of file Compiler.cs.
    {
        _xmlResolver = xmlResolver;
        PushInputDocument(input);
        _rootScope = _scopeManager.PushScope();
        _queryStore = new List<TheQuery>();
        try
        {
            rootStylesheet = new Stylesheet();
            PushStylesheet(rootStylesheet);
            try
            {
                CreateRootAction();
            }
            catch (XsltCompileException)
            {
                throw;
            }
            catch (Exception inner)
            {
                throw new XsltCompileException(inner, Input.BaseURI, Input.LineNumber, Input.LinePosition);
            }
            stylesheet.ProcessTemplates();
            _rootAction.PorcessAttributeSets(rootStylesheet);
            stylesheet.SortWhiteSpace();
            if (_globalNamespaceAliasTable != null)
            {
                stylesheet.ReplaceNamespaceAlias(this);
                _rootAction.ReplaceNamespaceAlias(this);
            }
        }
        finally
        {
            PopInputDocument();
        }
    }
References System.Xml.Xsl.XsltOld.Compiler._globalNamespaceAliasTable, System.Xml.Xsl.XsltOld.Compiler._queryStore, System.Xml.Xsl.XsltOld.Compiler._rootAction, System.Xml.Xsl.XsltOld.Compiler._rootScope, System.Xml.Xsl.XsltOld.Compiler._scopeManager, System.Xml.Xsl.XsltOld.Compiler._xmlResolver, System.Xml.Xsl.XsltOld.Compiler.CreateRootAction(), System.Xml.Dictionary, System.input, System.Xml.Xsl.XsltOld.Compiler.PopInputDocument(), System.Xml.Xsl.XsltOld.RootAction.PorcessAttributeSets(), System.Xml.Xsl.XsltOld.Stylesheet.ProcessTemplates(), System.Xml.Xsl.XsltOld.Compiler.PushInputDocument(), System.Xml.Xsl.XsltOld.InputScopeManager.PushScope(), System.Xml.Xsl.XsltOld.Compiler.PushStylesheet(), System.Xml.Xsl.XsltOld.ContainerAction.ReplaceNamespaceAlias(), System.Xml.Xsl.XsltOld.Stylesheet.ReplaceNamespaceAlias(), System.Xml.Xsl.XsltOld.Compiler.rootStylesheet, System.Xml.Xsl.XsltOld.Stylesheet.SortWhiteSpace(), and System.Xml.Xsl.XsltOld.Compiler.stylesheet.