Terraria: System.Xml.Xsl.XsltOld.Compiler.ResolveDocument
ResolveDocument()
NavigatorInput System.Xml.Xsl.XsltOld.Compiler.ResolveDocument (Uri absoluteUri) inline package
Definition at line 487 of file Compiler.cs.
    {
        object entity = _xmlResolver.GetEntity(absoluteUri, null, null);
        string text = absoluteUri.ToString();
        if (entity is Stream)
        {
            XmlTextReaderImpl xmlTextReaderImpl = new XmlTextReaderImpl(text, (Stream)entity);
            xmlTextReaderImpl.XmlResolver = _xmlResolver;
            return new NavigatorInput(LoadDocument(xmlTextReaderImpl).CreateNavigator(), text, _rootScope);
        }
        if (entity is XPathNavigator)
        {
            return new NavigatorInput((XPathNavigator)entity, text, _rootScope);
        }
        throw XsltException.Create(System.SR.Xslt_CantResolve, text);
    }
References System.Xml.Xsl.XsltOld.Compiler._rootScope, System.Xml.Xsl.XsltOld.Compiler._xmlResolver, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.XmlResolver.GetEntity(), System.Xml.Xsl.XsltOld.Compiler.LoadDocument(), System.text, and System.SR.Xslt_CantResolve.