Terraria: Dust.NewDustPerfect
NewDustPerfect()
static Dust Dust.NewDustPerfect (Vector2 Position, int Type, Vector2? Velocity = null, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
References Main.dust, NewDust(), position, and velocity.
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_007_TownEntities(), Projectile.AI_016(), NPC.AI_026_Unicorns(), NPC.AI_047_GolemFist(), Projectile.AI_075(), NPC.AI_107_ImprovedWalkers(), NPC.AI_111_DD2LightningBug(), NPC.AI_120_HallowBoss_DoMagicEffect(), Projectile.AI_147_Explosion(), Projectile.AI_150_GolfClubHelper(), Projectile.AI_157_SharpTears(), Projectile.AI_162_TigerPounce(), Projectile.AI_168_FirstFractal(), Projectile.AI_171_HallowBossRainbowStreak(), Projectile.AI_179_FairyQueenLance(), Projectile.AI_181_FairyQueenRangedItemShot(), Projectile.AI_188_LightsBane(), Projectile.AI_189_Volcano(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Projectile.AI_192_JuminoAnimation(), Projectile.AI_195_JimsDrone(), ParticleOrchestrator.CopperSlimeEffect(), Mount.DoConfettiMinecartEffect(), Mount.DoExhaustMinecartEffect(), Mount.DoGemMinecartEffect(), Mount.DoSteamMinecartEffect(), ParticleOrchestrator.ElderSlimeEffect(), GolfHelper.ContactListener.EmitGolfballExplosion(), GolfHelper.ContactListener.EmitGolfballExplosion_v1(), DelegateMethods.EmitGolfCartDust_StopForSolids(), Player.ItemCheck(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_ApplyUseStyle(), Player.ItemCheck_EmitDrinkParticles(), Player.ItemCheck_EmitFoodParticles(), Player.ItemCheck_EmitHeldItemLight(), Player.ItemCheck_EmitUseVisuals(), Projectile.Kill(), Projectile.LightDisc_Bounce(), Projectile.MakeBoulderOfEarthExplosion(), ParticleOrchestrator.NerdySlimeEffect(), GolfHelper.ContactListener.OnCollision(), ParticleOrchestrator.Spawn_AshTreeShake(), ParticleOrchestrator.Spawn_Excalibur(), ParticleOrchestrator.Spawn_LoadOutChange(), ParticleOrchestrator.Spawn_ShimmerArrow(), ParticleOrchestrator.Spawn_TerraBlade(), ParticleOrchestrator.Spawn_TrueExcalibur(), ParticleOrchestrator.Spawn_TrueNightsEdge(), DelegateMethods.Minecart.SpawnFartCloud(), FinalFractalHelper.FinalFractalProfile.StripDust(), Main.TeleportEffect(), Mount.UpdateEffects(), Item.UpdateItem_VisualEffects(), and Player.WingFrame().