Terraria: System.Data.ForeignKeyConstraint.CanEnableConstraint
CanEnableConstraint()
override bool System.Data.ForeignKeyConstraint.CanEnableConstraint () inline package
Definition at line 258 of file ForeignKeyConstraint.cs.
    {
        if (Table.DataSet == null || !Table.DataSet.EnforceConstraints)
        {
            return true;
        }
        Index sortIndex = _childKey.GetSortIndex();
        object[] uniqueKeyValues = sortIndex.GetUniqueKeyValues();
        Index sortIndex2 = _parentKey.GetSortIndex();
        for (int i = 0; i < uniqueKeyValues.Length; i++)
        {
            object[] array = (object[])uniqueKeyValues[i];
            if (!IsKeyNull(array) && !sortIndex2.IsKeyInIndex(array))
            {
                return false;
            }
        }
        return true;
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.ForeignKeyConstraint._parentKey, System.array, System.Data.DataTable.DataSet, System.Data.DataSet.EnforceConstraints, System.Data.DataKey.GetSortIndex(), System.Data.Index.GetUniqueKeyValues(), System.Data.Index.IsKeyInIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), and System.Data.ForeignKeyConstraint.Table.
Referenced by System.Data.ConstraintCollection.AddForeignKeyConstraint().