Terraria: System.Data.ForeignKeyConstraint.CheckConstraint
CheckConstraint() [2/2]
override void System.Data.ForeignKeyConstraint.CheckConstraint (DataRow childRow, DataRowAction action) inline package
Definition at line 552 of file ForeignKeyConstraint.cs.
    {
        if ((action != DataRowAction.Change && action != DataRowAction.Add && action != DataRowAction.Rollback) || Table.DataSet == null || !Table.DataSet.EnforceConstraints || !childRow.HasKeyChanged(_childKey))
        {
            return;
        }
        DataRowVersion dataRowVersion = ((action == DataRowAction.Rollback) ? DataRowVersion.Original : DataRowVersion.Current);
        object[] keyValues = childRow.GetKeyValues(_childKey);
        if (childRow.HasVersion(dataRowVersion))
        {
            DataRow parentRow = DataRelation.GetParentRow(ParentKey, ChildKey, childRow, dataRowVersion);
            if (parentRow != null && parentRow._inCascade)
            {
                object[] keyValues2 = parentRow.GetKeyValues(_parentKey, (action == DataRowAction.Rollback) ? dataRowVersion : DataRowVersion.Default);
                int num = childRow.Table.NewRecord();
                childRow.Table.SetKeyValues(_childKey, keyValues2, num);
                if (_childKey.RecordsEqual(childRow._tempRecord, num))
                {
                    return;
                }
            }
        }
        object[] keyValues3 = childRow.GetKeyValues(_childKey);
        if (IsKeyNull(keyValues3))
        {
            return;
        }
        Index sortIndex = _parentKey.GetSortIndex();
        if (sortIndex.IsKeyInIndex(keyValues3))
        {
            return;
        }
        if (_childKey.Table == _parentKey.Table && childRow._tempRecord != -1)
        {
            int num2 = 0;
            for (num2 = 0; num2 < keyValues3.Length; num2++)
            {
                DataColumn dataColumn = _parentKey.ColumnsReference[num2];
                object value = dataColumn.ConvertValue(keyValues3[num2]);
                if (dataColumn.CompareValueTo(childRow._tempRecord, value) != 0)
                {
                    break;
                }
            }
            if (num2 == keyValues3.Length)
            {
                return;
            }
        }
        throw ExceptionBuilder.ForeignKeyViolation(ConstraintName, keyValues);
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.DataRow._inCascade, System.Data.ForeignKeyConstraint._parentKey, System.Data.DataRow._tempRecord, System.action, System.Data.ForeignKeyConstraint.ChildKey, System.Data.DataKey.ColumnsReference, System.Data.DataColumn.CompareValueTo(), System.Data.Constraint.ConstraintName, System.Data.DataColumn.ConvertValue(), System.Data.DataTable.DataSet, System.Data.DataSet.EnforceConstraints, System.Data.ExceptionBuilder.ForeignKeyViolation(), System.Data.DataRow.GetKeyValues(), System.Data.DataRelation.GetParentRow(), System.Data.DataKey.GetSortIndex(), System.Data.DataRow.HasKeyChanged(), System.Data.DataRow.HasVersion(), System.Data.Index.IsKeyInIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), System.Data.DataTable.NewRecord(), System.Data.ForeignKeyConstraint.ParentKey, System.Data.DataKey.RecordsEqual(), System.Data.DataTable.SetKeyValues(), System.Data.DataKey.Table, System.Data.DataRow.Table, System.Data.ForeignKeyConstraint.Table, and System.value.