Terraria: Dust.UpdateDust
UpdateDust()
static void Dust.UpdateDust () inline static
     {
         int num = 0;
         lavaBubbles = 0;
         Main.snowDust = 0;
         SandStormCount = 0;
         bool flag = Sandstorm.ShouldSandstormDustPersist();
         for (int i = 0; i < 6000; i++)
         {
             Dust dust = Main.dust[i];
             if (i < Main.maxDustToDraw)
             {
                 if (!dust.active)
                 {
                     continue;
                 }
                 dCount += 1f;
                 if (dust.scale > 10f)
                 {
                     dust.active = false;
                 }
                 if (dust.firstFrame && !ChildSafety.Disabled && ChildSafety.DangerousDust(dust.type))
                 {
                     if (Main.rand.Next(2) == 0)
                     {
                         dust.firstFrame = false;
                         dust.type = 16;
                         dust.scale = Main.rand.NextFloat() * 1.6f + 0.3f;
                         dust.color = Color.Transparent;
                         dust.frame.X = 10 * dust.type;
                         dust.frame.Y = 10 * Main.rand.Next(3);
                         dust.shader = null;
                         dust.customData = null;
                         int num2 = dust.type / 100;
                         dust.frame.X -= 1000 * num2;
                         dust.frame.Y += 30 * num2;
                         dust.noGravity = true;
                     }
                     else
                     {
                         dust.active = false;
                     }
                 }
                 int num3 = dust.type;
                 if ((uint)(num3 - 299) <= 2u || num3 == 305)
                 {
                     dust.scale *= 0.96f;
                     dust.velocity.Y -= 0.01f;
                 }
                 if (dust.type == 35)
                 {
                     lavaBubbles++;
                 }
                 dust.position += dust.velocity;
                 if (dust.type == 258)
                 {
                     dust.noGravity = true;
                     dust.scale += 0.015f;
                 }
                 if (dust.type == 309)
                 {
                     float r = (float)(int)dust.color.R / 255f * dust.scale;
                     float g = (float)(int)dust.color.G / 255f * dust.scale;
                     float b = (float)(int)dust.color.B / 255f * dust.scale;
                     Lighting.AddLight(dust.position, r, g, b);
                     dust.scale *= 0.97f;
                 }
                 if (((dust.type >= 86 && dust.type <= 92) || dust.type == 286) && !dust.noLight && !dust.noLightEmittence)
                 {
                     float num4 = dust.scale * 0.6f;
                     if (num4 > 1f)
                     {
                         num4 = 1f;
                     }
                     int num5 = dust.type - 85;
                     float num6 = num4;
                     float num7 = num4;
                     float num8 = num4;
                     switch (num5)
                     {
                     case 3:
                         num6 *= 0f;
                         num7 *= 0.1f;
                         num8 *= 1.3f;
                         break;
                     case 5:
                         num6 *= 1f;
                         num7 *= 0.1f;
                         num8 *= 0.1f;
                         break;
                     case 4:
                         num6 *= 0f;
                         num7 *= 1f;
                         num8 *= 0.1f;
                         break;
                     case 1:
                         num6 *= 0.9f;
                         num7 *= 0f;
                         num8 *= 0.9f;
                         break;
                     case 6:
                         num6 *= 1.3f;
                         num7 *= 1.3f;
                         num8 *= 1.3f;
                         break;
                     case 2:
                         num6 *= 0.9f;
                         num7 *= 0.9f;
                         num8 *= 0f;
                         break;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num4 * num6, num4 * num7, num4 * num8);
                 }
                 if ((dust.type >= 86 && dust.type <= 92) || dust.type == 286)
                 {
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player = (Player)dust.customData;
                         dust.position += player.position - player.oldPosition;
                     }
                     else if (dust.customData != null && dust.customData is Projectile)
                     {
                         Projectile projectile = (Projectile)dust.customData;
                         if (projectile.active)
{
                             dust.position += projectile.position - projectile.oldPosition;
                         }
                     }
                 }
                 if (dust.type == 262 && !dust.noLight)
                 {
                     Vector3 rgb = new Vector3(0.9f, 0.6f, 0f) * dust.scale * 0.6f;
                     Lighting.AddLight(dust.position, rgb);
                 }
                 if (dust.type == 240 && dust.customData != null && dust.customData is Projectile)
                 {
                     Projectile projectile2 = (Projectile)dust.customData;
                     if (projectile2.active)
                     {
                         dust.position += projectile2.position - projectile2.oldPosition;
                     }
                 }
                 if ((dust.type == 259 || dust.type == 6 || dust.type == 158 || dust.type == 135) && dust.customData != null && dust.customData is int)
                 {
                     if ((int)dust.customData == 0)
                     {
                         if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
{
                             dust.scale *= 0.9f;
                             dust.velocity *= 0.25f;
                         }
                     }
                     else if ((int)dust.customData == 1)
                     {
                         dust.scale *= 0.98f;
                         dust.velocity.Y *= 0.98f;
                         if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
{
                             dust.scale *= 0.9f;
                             dust.velocity *= 0.25f;
                         }
                     }
                 }
                 if (dust.type == 263 || dust.type == 264)
                 {
                     if (!dust.noLight)
                     {
                         Vector3 rgb2 = dust.color.ToVector3() * dust.scale * 0.4f;
                         Lighting.AddLight(dust.position, rgb2);
                     }
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player2 = (Player)dust.customData;
                         dust.position += player2.position - player2.oldPosition;
                         dust.customData = null;
                     }
                     else if (dust.customData != null && dust.customData is Projectile)
                     {
                         Projectile projectile3 = (Projectile)dust.customData;
                         dust.position += projectile3.position - projectile3.oldPosition;
                     }
                 }
                 if (dust.type == 230)
                 {
                     float num9 = dust.scale * 0.6f;
                     float num10 = num9;
                     float num11 = num9;
                     float num12 = num9;
                     num10 *= 0.5f;
                     num11 *= 0.9f;
                     num12 *= 1f;
                     dust.scale += 0.02f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num9 * num10, num9 * num11, num9 * num12);
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Vector2 center = ((Player)dust.customData).Center;
                         Vector2 vector = dust.position - center;
                         float num13 = vector.Length();
                         vector /= num13;
                         dust.scale = Math.Min(dust.scale, num13 / 24f - 1f);
                         dust.velocity -= vector * (100f / Math.Max(50f, num13));
                     }
                 }
                 if (dust.type == 154 || dust.type == 218)
                 {
                     dust.rotation += dust.velocity.X * 0.3f;
                     dust.scale -= 0.03f;
                 }
                 if (dust.type == 172)
                 {
                     float num14 = dust.scale * 0.5f;
                     if (num14 > 1f)
                     {
                         num14 = 1f;
                     }
                     float num15 = num14;
                     float num16 = num14;
                     float num17 = num14;
                     num15 *= 0f;
                     num16 *= 0.25f;
                     num17 *= 1f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num14 * num15, num14 * num16, num14 * num17);
                 }
                 if (dust.type == 182)
                 {
                     dust.rotation += 1f;
                     if (!dust.noLight)
                     {
                         float num18 = dust.scale * 0.25f;
                         if (num18 > 1f)
{
                             num18 = 1f;
                         }
                         float num19 = num18;
                         float num20 = num18;
                         float num21 = num18;
                         num19 *= 1f;
                         num20 *= 0.2f;
                         num21 *= 0.1f;
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num18 * num19, num18 * num20, num18 * num21);
                     }
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player3 = (Player)dust.customData;
                         dust.position += player3.position - player3.oldPosition;
                         dust.customData = null;
                     }
                 }
                 if (dust.type == 261)
                 {
                     if (!dust.noLight && !dust.noLightEmittence)
                     {
                         float num22 = dust.scale * 0.3f;
                         if (num22 > 1f)
{
                             num22 = 1f;
                         }
                         Lighting.AddLight(dust.position, new Vector3(0.4f, 0.6f, 0.7f) * num22);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     dust.velocity *= new Vector2(0.97f, 0.99f);
                     dust.scale -= 0.0025f;
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player4 = (Player)dust.customData;
                         dust.position += player4.position - player4.oldPosition;
                     }
                 }
                 if (dust.type == 254)
                 {
                     float num23 = dust.scale * 0.35f;
                     if (num23 > 1f)
                     {
                         num23 = 1f;
                     }
                     float num24 = num23;
                     float num25 = num23;
                     float num26 = num23;
                     num24 *= 0.9f;
                     num25 *= 0.1f;
                     num26 *= 0.75f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num23 * num24, num23 * num25, num23 * num26);
                 }
                 if (dust.type == 255)
                 {
                     float num27 = dust.scale * 0.25f;
                     if (num27 > 1f)
                     {
                         num27 = 1f;
                     }
                     float num28 = num27;
                     float num29 = num27;
                     float num30 = num27;
                     num28 *= 0.9f;
                     num29 *= 0.1f;
                     num30 *= 0.75f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num27 * num28, num27 * num29, num27 * num30);
                 }
                 if (dust.type == 211 && dust.noLight && Collision.SolidCollision(dust.position, 4, 4))
                 {
                     dust.active = false;
                 }
                 if (dust.type == 284 && Collision.SolidCollision(dust.position - Vector2.One * 4f, 8, 8) && dust.fadeIn == 0f)
                 {
                     dust.velocity *= 0.25f;
                 }
                 if (dust.type == 213 || dust.type == 260)
                 {
                     dust.rotation = 0f;
                     float num31 = dust.scale / 2.5f * 0.2f;
                     Vector3 vector2 = Vector3.Zero;
                     switch (dust.type)
                     {
                     case 213:
                         vector2 = new Vector3(255f, 217f, 48f);
                         break;
                     case 260:
                         vector2 = new Vector3(255f, 48f, 48f);
                         break;
                     }
                     vector2 /= 255f;
                     if (num31 > 1f)
                     {
                         num31 = 1f;
                     }
                     vector2 *= num31;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), vector2.X, vector2.Y, vector2.Z);
                 }
                 if (dust.type == 157)
                 {
                     float num32 = dust.scale * 0.2f;
                     float num33 = num32;
                     float num34 = num32;
                     float num35 = num32;
                     num33 *= 0.25f;
                     num34 *= 1f;
                     num35 *= 0.5f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num32 * num33, num32 * num34, num32 * num35);
                 }
                 if (dust.type == 206)
                 {
                     dust.scale -= 0.1f;
                     float num36 = dust.scale * 0.4f;
                     float num37 = num36;
                     float num38 = num36;
                     float num39 = num36;
                     num37 *= 0.1f;
                     num38 *= 0.6f;
                     num39 *= 1f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num36 * num37, num36 * num38, num36 * num39);
                 }
                 if (dust.type == 163)
                 {
                     float num40 = dust.scale * 0.25f;
                     float num41 = num40;
                     float num42 = num40;
                     float num43 = num40;
                     num41 *= 0.25f;
                     num42 *= 1f;
                     num43 *= 0.05f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num40 * num41, num40 * num42, num40 * num43);
                 }
                 if (dust.type == 205)
                 {
                     float num44 = dust.scale * 0.25f;
                     float num45 = num44;
                     float num46 = num44;
                     float num47 = num44;
                     num45 *= 1f;
                     num46 *= 0.05f;
                     num47 *= 1f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num44 * num45, num44 * num46, num44 * num47);
                 }
                 if (dust.type == 170)
                 {
                     float num48 = dust.scale * 0.5f;
                     float num49 = num48;
                     float num50 = num48;
                     float num51 = num48;
                     num49 *= 1f;
                     num50 *= 1f;
                     num51 *= 0.05f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num48 * num49, num48 * num50, num48 * num51);
                 }
                 if (dust.type == 156)
                 {
                     float num52 = dust.scale * 0.6f;
                     _ = dust.type;
                     float num53 = num52;
                     float num54 = num52;
                     num53 *= 0.9f;
                     num54 *= 1f;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 12, num52);
                 }
                 if (dust.type == 234)
                 {
                     float lightAmount = dust.scale * 0.6f;
                     _ = dust.type;
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 13, lightAmount);
                 }
                 if (dust.type == 175)
                 {
                     dust.scale -= 0.05f;
                 }
                 if (dust.type == 174)
                 {
                     dust.scale -= 0.01f;
                     float num55 = dust.scale * 1f;
                     if (num55 > 0.6f)
                     {
                         num55 = 0.6f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num55, num55 * 0.4f, 0f);
                 }
                 if (dust.type == 235)
                 {
                     Vector2 vector3 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                     vector3.Normalize();
                     vector3 *= 15f;
                     dust.scale -= 0.01f;
                 }
                 else if (dust.type == 228 || dust.type == 279 || dust.type == 229 || dust.type == 6 || dust.type == 242 || dust.type == 135 || dust.type == 127 || dust.type == 187 || dust.type == 75 || dust.type == 169 || dust.type == 29 || (dust.type >= 59 && dust.type <= 65) || dust.type == 158 || dust.type == 293 || dust.type == 294 || dust.type == 295 || dust.type == 296 || dust.type == 297 || dust.type == 298 || dust.type == 302 || dust.type == 307 || dust.type == 310)
                 {
                     if (!dust.noGravity)
                     {
                         dust.velocity.Y += 0.05f;
                     }
                     if (dust.type == 229 || dust.type == 228 || dust.type == 279)
                     {
                         if (dust.customData != null && dust.customData is NPC)
{
                             NPC nPC = (NPC)dust.customData;
                             dust.position += nPC.position - nPC.oldPos[1];
                         }
                         else if (dust.customData != null && dust.customData is Player)
{
                             Player player5 = (Player)dust.customData;
                             dust.position += player5.position - player5.oldPosition;
                         }
                         else if (dust.customData != null && dust.customData is Vector2)
{
                             Vector2 vector4 = (Vector2)dust.customData - dust.position;
                             if (vector4 != Vector2.Zero)
{
                                 vector4.Normalize();
                             }
                             dust.velocity = (dust.velocity * 4f + vector4 * dust.velocity.Length()) / 5f;
                         }
                     }
                     if (!dust.noLight && !dust.noLightEmittence)
                     {
                         float num56 = dust.scale * 1.4f;
                         if (dust.type == 29)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56 * 0.1f, num56 * 0.4f, num56);
                         }
                         else if (dust.type == 75)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             if (dust.customData is float)
{
                                 Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 8, num56 * (float)dust.customData);
                             }
                             else
{
                                 Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 8, num56);
                             }
                         }
                         else if (dust.type == 169)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 11, num56);
                         }
                         else if (dust.type == 135)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 9, num56);
                         }
                         else if (dust.type == 158)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 10, num56);
                         }
                         else if (dust.type == 228)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56 * 0.7f, num56 * 0.65f, num56 * 0.3f);
                         }
                         else if (dust.type == 229)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56 * 0.3f, num56 * 0.65f, num56 * 0.7f);
                         }
                         else if (dust.type == 242)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 15, num56);
                         }
                         else if (dust.type == 293)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             num56 *= 0.95f;
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 16, num56);
                         }
                         else if (dust.type == 294)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 17, num56);
                         }
                         else if (dust.type >= 59 && dust.type <= 65)
{
                             if (num56 > 0.8f)
{
                                 num56 = 0.8f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 1 + dust.type - 59, num56);
                         }
                         else if (dust.type == 127)
{
                             num56 *= 1.3f;
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56, num56 * 0.45f, num56 * 0.2f);
                         }
                         else if (dust.type == 187)
{
                             num56 *= 1.3f;
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56 * 0.2f, num56 * 0.45f, num56);
                         }
                         else if (dust.type == 295)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 18, num56);
                         }
                         else if (dust.type == 296)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 19, num56);
                         }
                         else if (dust.type == 297)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 20, num56);
                         }
                         else if (dust.type == 298)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 21, num56);
                         }
                         else if (dust.type == 307)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 22, num56);
                         }
                         else if (dust.type == 310)
{
                             if (num56 > 1f)
{
                                 num56 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 23, num56);
                         }
                         else
{
                             if (num56 > 0.6f)
{
                                 num56 = 0.6f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num56, num56 * 0.65f, num56 * 0.4f);
                         }
                     }
                 }
                 else if (dust.type == 306)
                 {
                     if (!dust.noGravity)
                     {
                         dust.velocity.Y += 0.05f;
                     }
                     dust.scale -= 0.04f;
                     if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
                     {
                         dust.scale *= 0.9f;
                         dust.velocity *= 0.25f;
                     }
                 }
                 else if (dust.type == 269)
                 {
                     if (!dust.noLight)
                     {
                         float num57 = dust.scale * 1.4f;
                         if (num57 > 1f)
{
                             num57 = 1f;
                         }
                         Lighting.AddLight(rgb: new Vector3(0.7f, 0.65f, 0.3f) * num57, position: dust.position);
                     }
                     if (dust.customData != null && dust.customData is Vector2)
                     {
                         Vector2 vector5 = (Vector2)dust.customData - dust.position;
                         dust.velocity.X += 1f * (float)Math.Sign(vector5.X) * dust.scale;
                     }
                 }
                 else if (dust.type == 159)
                 {
                     float num58 = dust.scale * 1.3f;
                     if (num58 > 1f)
                     {
                         num58 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num58, num58, num58 * 0.1f);
                     if (dust.noGravity)
                     {
                         if (dust.scale < 0.7f)
{
                             dust.velocity *= 1.075f;
                         }
                         else if (Main.rand.Next(2) == 0)
{
                             dust.velocity *= -0.95f;
                         }
                         else
{
                             dust.velocity *= 1.05f;
                         }
                         dust.scale -= 0.03f;
                     }
                     else
                     {
                         dust.scale += 0.005f;
                         dust.velocity *= 0.9f;
                         dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.02f;
                         dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.02f;
                         if (Main.rand.Next(5) == 0)
{
                             int num59 = NewDust(dust.position, 4, 4, dust.type);
                             Main.dust[num59].noGravity = true;
                             Main.dust[num59].scale = dust.scale * 2.5f;
                         }
                     }
                 }
                 else if (dust.type == 164)
                 {
                     float num60 = dust.scale;
                     if (num60 > 1f)
                     {
                         num60 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num60, num60 * 0.1f, num60 * 0.8f);
                     if (dust.noGravity)
                     {
                         if (dust.scale < 0.7f)
{
                             dust.velocity *= 1.075f;
                         }
                         else if (Main.rand.Next(2) == 0)
{
                             dust.velocity *= -0.95f;
                         }
                         else
{
                             dust.velocity *= 1.05f;
                         }
                         dust.scale -= 0.03f;
                     }
                     else
                     {
                         dust.scale -= 0.005f;
                         dust.velocity *= 0.9f;
                         dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.02f;
                         dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.02f;
                         if (Main.rand.Next(5) == 0)
{
                             int num61 = NewDust(dust.position, 4, 4, dust.type);
                             Main.dust[num61].noGravity = true;
                             Main.dust[num61].scale = dust.scale * 2.5f;
                         }
                     }
                 }
                 else if (dust.type == 173)
                 {
                     float num62 = dust.scale;
                     if (num62 > 1f)
                     {
                         num62 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num62 * 0.4f, num62 * 0.1f, num62);
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.8f;
                         dust.velocity.X += (float)Main.rand.Next(-20, 21) * 0.01f;
                         dust.velocity.Y += (float)Main.rand.Next(-20, 21) * 0.01f;
                         dust.scale -= 0.01f;
                     }
                     else
                     {
                         dust.scale -= 0.015f;
                         dust.velocity *= 0.8f;
                         dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.005f;
                         dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.005f;
                         if (Main.rand.Next(10) == 10)
{
                             int num63 = NewDust(dust.position, 4, 4, dust.type);
                             Main.dust[num63].noGravity = true;
                             Main.dust[num63].scale = dust.scale;
                         }
                     }
                 }
                 else if (dust.type == 304)
                 {
                     dust.velocity.Y = (float)Math.Sin(dust.rotation) / 5f;
                     dust.rotation += 0.015f;
                     if (dust.scale < 1.15f)
                     {
                         dust.alpha = Math.Max(0, dust.alpha - 20);
                         dust.scale += 0.0015f;
                     }
                     else
                     {
                         dust.alpha += 6;
                         if (dust.alpha >= 255)
{
                             dust.active = false;
                         }
                     }
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player6 = (Player)dust.customData;
                         float num64 = Utils.Remap(dust.scale, 1f, 1.05f, 1f, 0f);
                         if (num64 > 0f)
{
                             dust.position += player6.velocity * num64;
                         }
                         float num65 = player6.Center.X - dust.position.X;
                         if (Math.Abs(num65) > 20f)
{
                             float value = num65 * 0.01f;
                             dust.velocity.X = MathHelper.Lerp(dust.velocity.X, value, num64 * 0.2f);
                         }
                     }
                 }
                 else if (dust.type == 184)
                 {
                     if (!dust.noGravity)
                     {
                         dust.velocity *= 0f;
                         dust.scale -= 0.01f;
                     }
                 }
                 else if (dust.type == 160 || dust.type == 162)
                 {
                     float num66 = dust.scale * 1.3f;
                     if (num66 > 1f)
                     {
                         num66 = 1f;
                     }
                     if (dust.type == 162)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num66, num66 * 0.7f, num66 * 0.1f);
                     }
                     else
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num66 * 0.1f, num66, num66);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.8f;
                         dust.velocity.X += (float)Main.rand.Next(-20, 21) * 0.04f;
                         dust.velocity.Y += (float)Main.rand.Next(-20, 21) * 0.04f;
                         dust.scale -= 0.1f;
                     }
                     else
                     {
                         dust.scale -= 0.1f;
                         dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.02f;
                         dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.02f;
                         if ((double)dust.scale > 0.3 && Main.rand.Next(50) == 0)
{
                             int num67 = NewDust(new Vector2(dust.position.X - 4f, dust.position.Y - 4f), 1, 1, dust.type);
                             Main.dust[num67].noGravity = true;
                             Main.dust[num67].scale = dust.scale * 1.5f;
                         }
                     }
                 }
                 else if (dust.type == 168)
                 {
                     float num68 = dust.scale * 0.8f;
                     if ((double)num68 > 0.55)
                     {
                         num68 = 0.55f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num68, 0f, num68 * 0.8f);
                     dust.scale += 0.03f;
                     dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.02f;
                     dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.02f;
                     dust.velocity *= 0.99f;
                 }
                 else if (dust.type >= 139 && dust.type < 143)
                 {
                     dust.velocity.X *= 0.98f;
                     dust.velocity.Y *= 0.98f;
                     if (dust.velocity.Y < 1f)
                     {
                         dust.velocity.Y += 0.05f;
                     }
                     dust.scale += 0.009f;
                     dust.rotation -= dust.velocity.X * 0.4f;
                     if (dust.velocity.X > 0f)
                     {
                         dust.rotation += 0.005f;
                     }
                     else
                     {
                         dust.rotation -= 0.005f;
                     }
                 }
                 else if (dust.type == 14 || dust.type == 16 || dust.type == 31 || dust.type == 46 || dust.type == 124 || dust.type == 186 || dust.type == 188 || dust.type == 303)
                 {
                     dust.velocity.Y *= 0.98f;
                     dust.velocity.X *= 0.98f;
                     if (dust.type == 31)
                     {
                         if (dust.customData != null && dust.customData is float)
{
                             float num69 = (float)dust.customData;
                             dust.velocity.Y += num69;
                         }
                         if (dust.customData != null && dust.customData is NPC)
{
                             NPC nPC2 = (NPC)dust.customData;
                             dust.position += nPC2.position - nPC2.oldPosition;
                             if (dust.noGravity)
{
                                 dust.velocity *= 1.02f;
                             }
                             dust.alpha -= 70;
                             if (dust.alpha < 0)
{
                                 dust.alpha = 0;
                             }
                             dust.scale *= 0.97f;
                             if (dust.scale <= 0.01f)
{
                                 dust.scale = 0.0001f;
                                 dust.alpha = 255;
                             }
                         }
                         else if (dust.noGravity)
{
                             dust.velocity *= 1.02f;
                             dust.scale += 0.02f;
                             dust.alpha += 4;
                             if (dust.alpha > 255)
{
                                 dust.scale = 0.0001f;
                                 dust.alpha = 255;
                             }
                         }
                     }
                     if (dust.type == 303 && dust.noGravity)
                     {
                         dust.velocity *= 1.02f;
                         dust.scale += 0.03f;
                         if (dust.alpha < 90)
{
                             dust.alpha = 90;
                         }
                         dust.alpha += 4;
                         if (dust.alpha > 255)
{
                             dust.scale = 0.0001f;
                             dust.alpha = 255;
                         }
                     }
                 }
                 else if (dust.type == 32)
                 {
                     dust.scale -= 0.01f;
                     dust.velocity.X *= 0.96f;
                     if (!dust.noGravity)
                     {
                         dust.velocity.Y += 0.1f;
                     }
                 }
                 else if (dust.type >= 244 && dust.type <= 247)
                 {
                     dust.rotation += 0.1f * dust.scale;
                     Color color = Lighting.GetColor((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f));
                     byte num70 = (byte)((color.R + color.G + color.B) / 3);
                     float num71 = ((float)(int)num70 / 270f + 1f) / 2f;
                     float num72 = ((float)(int)num70 / 270f + 1f) / 2f;
                     float num73 = ((float)(int)num70 / 270f + 1f) / 2f;
                     num71 *= dust.scale * 0.9f;
                     num72 *= dust.scale * 0.9f;
                     num73 *= dust.scale * 0.9f;
                     if (dust.alpha < 255)
                     {
                         dust.scale += 0.09f;
                         if (dust.scale >= 1f)
{
                             dust.scale = 1f;
                             dust.alpha = 255;
                         }
                     }
                     else
                     {
                         if ((double)dust.scale < 0.8)
{
                             dust.scale -= 0.01f;
                         }
                         if ((double)dust.scale < 0.5)
{
                             dust.scale -= 0.01f;
                         }
                     }
                     float num74 = 1f;
                     if (dust.type == 244)
                     {
                         num71 *= 0.8862745f;
                         num72 *= 0.4627451f;
                         num73 *= 0.29803923f;
                         num74 = 0.9f;
                     }
                     else if (dust.type == 245)
                     {
                         num71 *= 0.5137255f;
                         num72 *= 0.6745098f;
                         num73 *= 0.6784314f;
                         num74 = 1f;
                     }
                     else if (dust.type == 246)
                     {
                         num71 *= 0.8f;
                         num72 *= 0.70980394f;
                         num73 *= 24f / 85f;
                         num74 = 1.1f;
                     }
                     else if (dust.type == 247)
                     {
                         num71 *= 0.6f;
                         num72 *= 0.6745098f;
                         num73 *= 37f / 51f;
                         num74 = 1.2f;
                     }
                     num71 *= num74;
                     num72 *= num74;
                     num73 *= num74;
                     if (!dust.noLightEmittence)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num71, num72, num73);
                     }
                 }
                 else if (dust.type == 43)
                 {
                     dust.rotation += 0.1f * dust.scale;
                     Color color2 = Lighting.GetColor((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f));
                     float num75 = (float)(int)color2.R / 270f;
                     float num76 = (float)(int)color2.G / 270f;
                     float num77 = (float)(int)color2.B / 270f;
                     float num78 = (float)(int)dust.color.R / 255f;
                     float num79 = (float)(int)dust.color.G / 255f;
                     float num80 = (float)(int)dust.color.B / 255f;
                     num75 *= dust.scale * 1.07f * num78;
                     num76 *= dust.scale * 1.07f * num79;
                     num77 *= dust.scale * 1.07f * num80;
                     if (dust.alpha < 255)
                     {
                         dust.scale += 0.09f;
                         if (dust.scale >= 1f)
{
                             dust.scale = 1f;
                             dust.alpha = 255;
                         }
                     }
                     else
                     {
                         if ((double)dust.scale < 0.8)
{
                             dust.scale -= 0.01f;
                         }
                         if ((double)dust.scale < 0.5)
{
                             dust.scale -= 0.01f;
                         }
                     }
                     if ((double)num75 < 0.05 && (double)num76 < 0.05 && (double)num77 < 0.05)
                     {
                         dust.active = false;
                     }
                     else if (!dust.noLightEmittence)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num75, num76, num77);
                     }
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player7 = (Player)dust.customData;
                         dust.position += player7.position - player7.oldPosition;
                     }
                 }
                 else if (dust.type == 15 || dust.type == 57 || dust.type == 58 || dust.type == 274 || dust.type == 292)
                 {
                     dust.velocity.Y *= 0.98f;
                     dust.velocity.X *= 0.98f;
                     if (!dust.noLightEmittence)
                     {
                         float num81 = dust.scale;
                         if (dust.type != 15)
{
                             num81 = dust.scale * 0.8f;
                         }
                         if (dust.noLight)
{
                             dust.velocity *= 0.95f;
                         }
                         if (num81 > 1f)
{
                             num81 = 1f;
                         }
                         if (dust.type == 15)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num81 * 0.45f, num81 * 0.55f, num81);
                         }
                         else if (dust.type == 57)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num81 * 0.95f, num81 * 0.95f, num81 * 0.45f);
                         }
                         else if (dust.type == 58)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num81, num81 * 0.55f, num81 * 0.75f);
                         }
                     }
                 }
                 else if (dust.type == 204)
                 {
                     if (dust.fadeIn > dust.scale)
                     {
                         dust.scale += 0.02f;
                     }
                     else
                     {
                         dust.scale -= 0.02f;
                     }
                     dust.velocity *= 0.95f;
                 }
                 else if (dust.type == 110)
                 {
                     float num82 = dust.scale * 0.1f;
                     if (num82 > 1f)
                     {
                         num82 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num82 * 0.2f, num82, num82 * 0.5f);
                 }
                 else if (dust.type == 111)
                 {
                     float num83 = dust.scale * 0.125f;
                     if (num83 > 1f)
                     {
                         num83 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num83 * 0.2f, num83 * 0.7f, num83);
                 }
                 else if (dust.type == 112)
                 {
                     float num84 = dust.scale * 0.1f;
                     if (num84 > 1f)
                     {
                         num84 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num84 * 0.8f, num84 * 0.2f, num84 * 0.8f);
                 }
                 else if (dust.type == 113)
                 {
                     float num85 = dust.scale * 0.1f;
                     if (num85 > 1f)
                     {
                         num85 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num85 * 0.2f, num85 * 0.3f, num85 * 1.3f);
                 }
                 else if (dust.type == 114)
                 {
                     float num86 = dust.scale * 0.1f;
                     if (num86 > 1f)
                     {
                         num86 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num86 * 1.2f, num86 * 0.5f, num86 * 0.4f);
                 }
                 else if (dust.type == 311)
                 {
                     float num87 = dust.scale * 0.1f;
                     if (num87 > 1f)
                     {
                         num87 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 16, num87);
                 }
                 else if (dust.type == 312)
                 {
                     float num88 = dust.scale * 0.1f;
                     if (num88 > 1f)
                     {
                         num88 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 9, num88);
                 }
                 else if (dust.type == 313)
                 {
                     float num89 = dust.scale * 0.25f;
                     if (num89 > 1f)
                     {
                         num89 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num89 * 1f, num89 * 0.8f, num89 * 0.6f);
                 }
                 else if (dust.type == 66)
                 {
                     if (dust.velocity.X < 0f)
                     {
                         dust.rotation -= 1f;
                     }
                     else
                     {
                         dust.rotation += 1f;
                     }
                     dust.velocity.Y *= 0.98f;
                     dust.velocity.X *= 0.98f;
                     dust.scale += 0.02f;
                     float num90 = dust.scale;
                     if (dust.type != 15)
                     {
                         num90 = dust.scale * 0.8f;
                     }
                     if (num90 > 1f)
                     {
                         num90 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num90 * ((float)(int)dust.color.R / 255f), num90 * ((float)(int)dust.color.G / 255f), num90 * ((float)(int)dust.color.B / 255f));
                 }
                 else if (dust.type == 267)
                 {
                     if (dust.velocity.X < 0f)
                     {
                         dust.rotation -= 1f;
                     }
                     else
                     {
                         dust.rotation += 1f;
                     }
                     dust.velocity.Y *= 0.98f;
                     dust.velocity.X *= 0.98f;
                     dust.scale += 0.02f;
                     float num91 = dust.scale * 0.8f;
                     if (num91 > 1f)
                     {
                         num91 = 1f;
                     }
                     if (dust.noLight)
                     {
                         dust.noLight = false;
                     }
                     if (!dust.noLight && !dust.noLightEmittence)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num91 * ((float)(int)dust.color.R / 255f), num91 * ((float)(int)dust.color.G / 255f), num91 * ((float)(int)dust.color.B / 255f));
                     }
                 }
                 else if (dust.type == 20 || dust.type == 21 || dust.type == 231)
                 {
                     dust.scale += 0.005f;
                     dust.velocity.Y *= 0.94f;
                     dust.velocity.X *= 0.94f;
                     float num92 = dust.scale * 0.8f;
                     if (num92 > 1f)
                     {
                         num92 = 1f;
                     }
                     if (dust.type == 21 && !dust.noLightEmittence)
                     {
                         num92 = dust.scale * 0.4f;
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num92 * 0.8f, num92 * 0.3f, num92);
                     }
                     else if (dust.type == 231)
                     {
                         num92 = dust.scale * 0.4f;
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num92, num92 * 0.5f, num92 * 0.3f);
                     }
                     else
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num92 * 0.3f, num92 * 0.6f, num92);
                     }
                 }
                 else if (dust.type == 27 || dust.type == 45)
                 {
                     if (dust.type == 27 && dust.fadeIn >= 100f)
                     {
                         if ((double)dust.scale >= 1.5)
{
                             dust.scale -= 0.01f;
                         }
                         else
{
                             dust.scale -= 0.05f;
                         }
                         if ((double)dust.scale <= 0.5)
{
                             dust.scale -= 0.05f;
                         }
                         if ((double)dust.scale <= 0.25)
{
                             dust.scale -= 0.05f;
                         }
                     }
                     dust.velocity *= 0.94f;
                     dust.scale += 0.002f;
                     float num93 = dust.scale;
                     if (dust.noLight)
                     {
                         num93 *= 0.1f;
                         dust.scale -= 0.06f;
                         if (dust.scale < 1f)
{
                             dust.scale -= 0.06f;
                         }
                         if (Main.player[Main.myPlayer].wet)
{
                             dust.position += Main.player[Main.myPlayer].velocity * 0.5f;
                         }
                         else
{
                             dust.position += Main.player[Main.myPlayer].velocity;
                         }
                     }
                     if (num93 > 1f)
                     {
                         num93 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num93 * 0.6f, num93 * 0.2f, num93);
                 }
                 else if (dust.type == 55 || dust.type == 56 || dust.type == 73 || dust.type == 74)
                 {
                     dust.velocity *= 0.98f;
                     if (!dust.noLightEmittence)
                     {
                         float num94 = dust.scale * 0.8f;
                         if (dust.type == 55)
{
                             if (num94 > 1f)
{
                                 num94 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num94, num94, num94 * 0.6f);
                         }
                         else if (dust.type == 73)
{
                             if (num94 > 1f)
{
                                 num94 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num94, num94 * 0.35f, num94 * 0.5f);
                         }
                         else if (dust.type == 74)
{
                             if (num94 > 1f)
{
                                 num94 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num94 * 0.35f, num94, num94 * 0.5f);
                         }
                         else
{
                             num94 = dust.scale * 1.2f;
                             if (num94 > 1f)
{
                                 num94 = 1f;
                             }
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num94 * 0.35f, num94 * 0.5f, num94);
                         }
                     }
                 }
                 else if (dust.type == 71 || dust.type == 72)
                 {
                     dust.velocity *= 0.98f;
                     float num95 = dust.scale;
                     if (num95 > 1f)
                     {
                         num95 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num95 * 0.2f, 0f, num95 * 0.1f);
                 }
                 else if (dust.type == 76)
                 {
                     Main.snowDust++;
                     dust.scale += 0.009f;
                     float y = Main.player[Main.myPlayer].velocity.Y;
                     if (y > 0f && dust.fadeIn == 0f && dust.velocity.Y < y)
                     {
                         dust.velocity.Y = MathHelper.Lerp(dust.velocity.Y, y, 0.04f);
                     }
                     if (!dust.noLight && y > 0f)
                     {
                         dust.position.Y += Main.player[Main.myPlayer].velocity.Y * 0.2f;
                     }
                     if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
                     {
                         dust.scale *= 0.9f;
                         dust.velocity *= 0.25f;
                     }
                 }
                 else if (dust.type == 270)
                 {
                     dust.velocity *= 1.0050251f;
                     dust.scale += 0.01f;
                     dust.rotation = 0f;
                     if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
                     {
                         dust.scale *= 0.95f;
                         dust.velocity *= 0.25f;
                     }
                     else
                     {
                         dust.velocity.Y = (float)Math.Sin(dust.position.X * 0.0043982295f) * 2f;
                         dust.velocity.Y -= 3f;
                         dust.velocity.Y /= 20f;
                     }
                 }
                 else if (dust.type == 271)
                 {
                     dust.velocity *= 1.0050251f;
                     dust.scale += 0.003f;
                     dust.rotation = 0f;
                     dust.velocity.Y -= 4f;
                     dust.velocity.Y /= 6f;
                 }
                 else if (dust.type == 268)
                 {
                     SandStormCount++;
                     dust.velocity *= 1.0050251f;
                     dust.scale += 0.01f;
                     if (!flag)
                     {
                         dust.scale -= 0.05f;
                     }
                     dust.rotation = 0f;
                     float y2 = Main.player[Main.myPlayer].velocity.Y;
                     if (y2 > 0f && dust.fadeIn == 0f && dust.velocity.Y < y2)
                     {
                         dust.velocity.Y = MathHelper.Lerp(dust.velocity.Y, y2, 0.04f);
                     }
                     if (!dust.noLight && y2 > 0f)
                     {
                         dust.position.Y += y2 * 0.2f;
                     }
                     if (Collision.SolidCollision(dust.position - Vector2.One * 5f, 10, 10) && dust.fadeIn == 0f)
                     {
                         dust.scale *= 0.9f;
                         dust.velocity *= 0.25f;
                     }
                     else
                     {
                         dust.velocity.Y = (float)Math.Sin(dust.position.X * 0.0043982295f) * 2f;
                         dust.velocity.Y += 3f;
                     }
                 }
                 else if (!dust.noGravity && dust.type != 41 && dust.type != 44 && dust.type != 309)
                 {
                     if (dust.type == 107)
                     {
                         dust.velocity *= 0.9f;
                     }
                     else
                     {
                         dust.velocity.Y += 0.1f;
                     }
                 }
                 if (dust.type == 5 || (dust.type == 273 && dust.noGravity))
                 {
                     dust.scale -= 0.04f;
                 }
                 if (dust.type == 308 || dust.type == 33 || dust.type == 52 || dust.type == 266 || dust.type == 98 || dust.type == 99 || dust.type == 100 || dust.type == 101 || dust.type == 102 || dust.type == 103 || dust.type == 104 || dust.type == 105 || dust.type == 123 || dust.type == 288)
                 {
                     if (dust.velocity.X == 0f)
                     {
                         if (Collision.SolidCollision(dust.position, 2, 2))
{
                             dust.scale = 0f;
                         }
                         dust.rotation += 0.5f;
                         dust.scale -= 0.01f;
                     }
                     if (Collision.WetCollision(new Vector2(dust.position.X, dust.position.Y), 4, 4))
                     {
                         dust.alpha += 20;
                         dust.scale -= 0.1f;
                     }
                     dust.alpha += 2;
                     dust.scale -= 0.005f;
                     if (dust.alpha > 255)
                     {
                         dust.scale = 0f;
                     }
                     if (dust.velocity.Y > 4f)
                     {
                         dust.velocity.Y = 4f;
                     }
                     if (dust.noGravity)
                     {
                         if (dust.velocity.X < 0f)
{
                             dust.rotation -= 0.2f;
                         }
                         else
{
                             dust.rotation += 0.2f;
                         }
                         dust.scale += 0.03f;
                         dust.velocity.X *= 1.05f;
                         dust.velocity.Y += 0.15f;
                     }
                 }
                 if (dust.type == 35 && dust.noGravity)
                 {
                     dust.scale += 0.03f;
                     if (dust.scale < 1f)
                     {
                         dust.velocity.Y += 0.075f;
                     }
                     dust.velocity.X *= 1.08f;
                     if (dust.velocity.X > 0f)
                     {
                         dust.rotation += 0.01f;
                     }
                     else
                     {
                         dust.rotation -= 0.01f;
                     }
                     float num96 = dust.scale * 0.6f;
                     if (num96 > 1f)
                     {
                         num96 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f + 1f), num96, num96 * 0.3f, num96 * 0.1f);
                 }
                 else if (dust.type == 152 && dust.noGravity)
                 {
                     dust.scale += 0.03f;
                     if (dust.scale < 1f)
                     {
                         dust.velocity.Y += 0.075f;
                     }
                     dust.velocity.X *= 1.08f;
                     if (dust.velocity.X > 0f)
                     {
                         dust.rotation += 0.01f;
                     }
                     else
                     {
                         dust.rotation -= 0.01f;
                     }
                 }
                 else if (dust.type == 67 || dust.type == 92)
                 {
                     float num97 = dust.scale;
                     if (num97 > 1f)
                     {
                         num97 = 1f;
                     }
                     if (dust.noLight)
                     {
                         num97 *= 0.1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), 0f, num97 * 0.8f, num97);
                 }
                 else if (dust.type == 185)
                 {
                     float num98 = dust.scale;
                     if (num98 > 1f)
                     {
                         num98 = 1f;
                     }
                     if (dust.noLight)
                     {
                         num98 *= 0.1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num98 * 0.1f, num98 * 0.7f, num98);
                 }
                 else if (dust.type == 107)
                 {
                     float num99 = dust.scale * 0.5f;
                     if (num99 > 1f)
                     {
                         num99 = 1f;
                     }
                     if (!dust.noLightEmittence)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num99 * 0.1f, num99, num99 * 0.4f);
                     }
                 }
                 else if (dust.type == 34 || dust.type == 35 || dust.type == 152)
                 {
                     if (!Collision.WetCollision(new Vector2(dust.position.X, dust.position.Y - 8f), 4, 4))
                     {
                         dust.scale = 0f;
                     }
                     else
                     {
                         dust.alpha += Main.rand.Next(2);
                         if (dust.alpha > 255)
{
                             dust.scale = 0f;
                         }
                         dust.velocity.Y = -0.5f;
                         if (dust.type == 34)
{
                             dust.scale += 0.005f;
                         }
                         else
{
                             dust.alpha++;
                             dust.scale -= 0.01f;
                             dust.velocity.Y = -0.2f;
                         }
                         dust.velocity.X += (float)Main.rand.Next(-10, 10) * 0.002f;
                         if ((double)dust.velocity.X < -0.25)
{
                             dust.velocity.X = -0.25f;
                         }
                         if ((double)dust.velocity.X > 0.25)
{
                             dust.velocity.X = 0.25f;
                         }
                     }
                     if (dust.type == 35)
                     {
                         float num100 = dust.scale * 0.3f + 0.4f;
                         if (num100 > 1f)
{
                             num100 = 1f;
                         }
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num100, num100 * 0.5f, num100 * 0.3f);
                     }
                 }
                 if (dust.type == 68)
                 {
                     float num101 = dust.scale * 0.3f;
                     if (num101 > 1f)
                     {
                         num101 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num101 * 0.1f, num101 * 0.2f, num101);
                 }
                 if (dust.type == 70)
                 {
                     float num102 = dust.scale * 0.3f;
                     if (num102 > 1f)
                     {
                         num102 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num102 * 0.5f, 0f, num102);
                 }
                 if (dust.type == 41)
                 {
                     dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.01f;
                     dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.01f;
                     if ((double)dust.velocity.X > 0.75)
                     {
                         dust.velocity.X = 0.75f;
                     }
                     if ((double)dust.velocity.X < -0.75)
                     {
                         dust.velocity.X = -0.75f;
                     }
                     if ((double)dust.velocity.Y > 0.75)
                     {
                         dust.velocity.Y = 0.75f;
                     }
                     if ((double)dust.velocity.Y < -0.75)
                     {
                         dust.velocity.Y = -0.75f;
                     }
                     dust.scale += 0.007f;
                     float num103 = dust.scale * 0.7f;
                     if (num103 > 1f)
                     {
                         num103 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num103 * 0.4f, num103 * 0.9f, num103);
                 }
                 else if (dust.type == 44)
                 {
                     dust.velocity.X += (float)Main.rand.Next(-10, 11) * 0.003f;
                     dust.velocity.Y += (float)Main.rand.Next(-10, 11) * 0.003f;
                     if ((double)dust.velocity.X > 0.35)
                     {
                         dust.velocity.X = 0.35f;
                     }
                     if ((double)dust.velocity.X < -0.35)
                     {
                         dust.velocity.X = -0.35f;
                     }
                     if ((double)dust.velocity.Y > 0.35)
                     {
                         dust.velocity.Y = 0.35f;
                     }
                     if ((double)dust.velocity.Y < -0.35)
                     {
                         dust.velocity.Y = -0.35f;
                     }
                     dust.scale += 0.0085f;
                     float num104 = dust.scale * 0.7f;
                     if (num104 > 1f)
                     {
                         num104 = 1f;
                     }
                     Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num104 * 0.7f, num104, num104 * 0.8f);
                 }
                 else if (dust.type != 304)
                 {
                     dust.velocity.X *= 0.99f;
                 }
                 if (dust.type == 322 && !dust.noGravity)
                 {
                     dust.scale *= 0.98f;
                 }
                 if (dust.type != 79 && dust.type != 268 && dust.type != 304)
                 {
                     dust.rotation += dust.velocity.X * 0.5f;
                 }
                 if (dust.fadeIn > 0f && dust.fadeIn < 100f)
                 {
                     if (dust.type == 235)
                     {
                         dust.scale += 0.007f;
                         int num105 = (int)dust.fadeIn - 1;
                         if (num105 >= 0 && num105 <= 255)
{
                             Vector2 vector6 = dust.position - Main.player[num105].Center;
                             float num106 = vector6.Length();
                             num106 = 100f - num106;
                             if (num106 > 0f)
{
                                 dust.scale -= num106 * 0.0015f;
                             }
                             vector6.Normalize();
                             float num107 = (1f - dust.scale) * 20f;
                             vector6 *= 0f - num107;
                             dust.velocity = (dust.velocity * 4f + vector6) / 5f;
                         }
                     }
                     else if (dust.type == 46)
                     {
                         dust.scale += 0.1f;
                     }
                     else if (dust.type == 213 || dust.type == 260)
                     {
                         dust.scale += 0.1f;
                     }
                     else
                     {
                         dust.scale += 0.03f;
                     }
                     if (dust.scale > dust.fadeIn)
                     {
                         dust.fadeIn = 0f;
                     }
                 }
                 else if (dust.type != 304)
                 {
                     if (dust.type == 213 || dust.type == 260)
                     {
                         dust.scale -= 0.2f;
                     }
                     else
                     {
                         dust.scale -= 0.01f;
                     }
                 }
                 if (dust.type >= 130 && dust.type <= 134)
                 {
                     float num108 = dust.scale;
                     if (num108 > 1f)
                     {
                         num108 = 1f;
                     }
                     if (dust.type == 130)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num108 * 1f, num108 * 0.5f, num108 * 0.4f);
                     }
                     if (dust.type == 131)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num108 * 0.4f, num108 * 1f, num108 * 0.6f);
                     }
                     if (dust.type == 132)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num108 * 0.3f, num108 * 0.5f, num108 * 1f);
                     }
                     if (dust.type == 133)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num108 * 0.9f, num108 * 0.9f, num108 * 0.3f);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     else if (dust.type == 131)
                     {
                         dust.velocity *= 0.98f;
                         dust.velocity.Y -= 0.1f;
                         dust.scale += 0.0025f;
                     }
                     else
                     {
                         dust.velocity *= 0.95f;
                         dust.scale -= 0.0025f;
                     }
                 }
                 else if (dust.type == 278)
                 {
                     float num109 = dust.scale;
                     if (num109 > 1f)
                     {
                         num109 = 1f;
                     }
                     if (!dust.noLight && !dust.noLightEmittence)
                     {
                         Lighting.AddLight(dust.position, dust.color.ToVector3() * num109);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     else
                     {
                         dust.velocity *= 0.95f;
                         dust.scale -= 0.0025f;
                     }
                     if (WorldGen.SolidTile(Framing.GetTileSafely(dust.position)) && dust.fadeIn == 0f && !dust.noGravity)
                     {
                         dust.scale *= 0.9f;
                         dust.velocity *= 0.25f;
                     }
                 }
                 else if (dust.type >= 219 && dust.type <= 223)
                 {
                     float num110 = dust.scale;
                     if (num110 > 1f)
                     {
                         num110 = 1f;
                     }
                     if (!dust.noLight)
                     {
                         if (dust.type == 219)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num110 * 1f, num110 * 0.5f, num110 * 0.4f);
                         }
                         if (dust.type == 220)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num110 * 0.4f, num110 * 1f, num110 * 0.6f);
                         }
                         if (dust.type == 221)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num110 * 0.3f, num110 * 0.5f, num110 * 1f);
                         }
                         if (dust.type == 222)
{
                             Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num110 * 0.9f, num110 * 0.9f, num110 * 0.3f);
                         }
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     dust.velocity *= new Vector2(0.97f, 0.99f);
                     dust.scale -= 0.0025f;
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player8 = (Player)dust.customData;
                         dust.position += player8.position - player8.oldPosition;
                     }
                 }
                 else if (dust.type == 226)
                 {
                     float num111 = dust.scale;
                     if (num111 > 1f)
                     {
                         num111 = 1f;
                     }
                     if (!dust.noLight)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num111 * 0.2f, num111 * 0.7f, num111 * 1f);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     dust.velocity *= new Vector2(0.97f, 0.99f);
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player9 = (Player)dust.customData;
                         dust.position += player9.position - player9.oldPosition;
                     }
                     dust.scale -= 0.01f;
                 }
                 else if (dust.type == 272)
                 {
                     float num112 = dust.scale;
                     if (num112 > 1f)
                     {
                         num112 = 1f;
                     }
                     if (!dust.noLight)
                     {
                         Lighting.AddLight((int)(dust.position.X / 16f), (int)(dust.position.Y / 16f), num112 * 0.5f, num112 * 0.2f, num112 * 0.8f);
                     }
                     if (dust.noGravity)
                     {
                         dust.velocity *= 0.93f;
                         if (dust.fadeIn == 0f)
{
                             dust.scale += 0.0025f;
                         }
                     }
                     dust.velocity *= new Vector2(0.97f, 0.99f);
                     if (dust.customData != null && dust.customData is Player)
                     {
                         Player player10 = (Player)dust.customData;
                         dust.position += player10.position - player10.oldPosition;
                     }
                     if (dust.customData != null && dust.customData is NPC)
                     {
                         NPC nPC3 = (NPC)dust.customData;
                         dust.position += nPC3.position - nPC3.oldPosition;
                     }
                     dust.scale -= 0.01f;
                 }
                 else if (dust.type != 304 && dust.noGravity)
                 {
                     dust.velocity *= 0.92f;
                     if (dust.fadeIn == 0f)
                     {
                         dust.scale -= 0.04f;
                     }
                 }
                 if (dust.position.Y > Main.screenPosition.Y + (float)Main.screenHeight)
                 {
                     dust.active = false;
                 }
                 float num113 = 0.1f;
                 if ((double)dCount == 0.5)
                 {
                     dust.scale -= 0.001f;
                 }
                 if ((double)dCount == 0.6)
                 {
                     dust.scale -= 0.0025f;
                 }
                 if ((double)dCount == 0.7)
                 {
                     dust.scale -= 0.005f;
                 }
                 if ((double)dCount == 0.8)
                 {
                     dust.scale -= 0.01f;
                 }
                 if ((double)dCount == 0.9)
                 {
                     dust.scale -= 0.02f;
                 }
                 if ((double)dCount == 0.5)
                 {
                     num113 = 0.11f;
                 }
                 if ((double)dCount == 0.6)
                 {
                     num113 = 0.13f;
                 }
                 if ((double)dCount == 0.7)
                 {
                     num113 = 0.16f;
                 }
                 if ((double)dCount == 0.8)
                 {
                     num113 = 0.22f;
                 }
                 if ((double)dCount == 0.9)
                 {
                     num113 = 0.25f;
                 }
                 if (dust.scale < num113)
                 {
                     dust.active = false;
                 }
             }
             else
             {
                 dust.active = false;
             }
         }
         int num114 = num;
         if ((double)num114 > (double)Main.maxDustToDraw * 0.9)
         {
             dCount = 0.9f;
         }
         else if ((double)num114 > (double)Main.maxDustToDraw * 0.8)
         {
             dCount = 0.8f;
         }
         else if ((double)num114 > (double)Main.maxDustToDraw * 0.7)
         {
             dCount = 0.7f;
         }
         else if ((double)num114 > (double)Main.maxDustToDraw * 0.6)
         {
             dCount = 0.6f;
         }
         else if ((double)num114 > (double)Main.maxDustToDraw * 0.5)
         {
             dCount = 0.5f;
         }
         else
         {
             dCount = 0f;
         }
     }
References active, Entity.active, Lighting.AddLight(), alpha, Entity.Center, Color, color, customData, ChildSafety.DangerousDust(), dCount, ChildSafety.Disabled, Main.dust, fadeIn, firstFrame, frame, Lighting.GetColor(), Framing.GetTileSafely(), lavaBubbles, Main.maxDustToDraw, Main.myPlayer, NewDust(), UnifiedRandom.Next(), noGravity, noLight, noLightEmittence, NPC, NPC.oldPos, Entity.oldPosition, Player, Main.player, position, Entity.position, Main.rand, Utils.Remap(), rotation, SandStormCount, scale, Main.screenHeight, Main.screenPosition, shader, Sandstorm.ShouldSandstormDustPersist(), Main.snowDust, Collision.SolidCollision(), WorldGen.SolidTile(), type, velocity, Entity.velocity, Entity.wet, and Collision.WetCollision().
Referenced by Main.DoUpdateInWorld().