Terraria: System.Data.ForeignKeyConstraint.CascadeCommit
CascadeCommit()
void System.Data.ForeignKeyConstraint.CascadeCommit (DataRow row) inline package
Definition at line 278 of file ForeignKeyConstraint.cs.
    {
        if (row.RowState == DataRowState.Detached || _acceptRejectRule != AcceptRejectRule.Cascade)
        {
            return;
        }
        Index sortIndex = _childKey.GetSortIndex((row.RowState == DataRowState.Deleted) ? DataViewRowState.Deleted : DataViewRowState.CurrentRows);
        object[] keyValues = row.GetKeyValues(_parentKey, (row.RowState == DataRowState.Deleted) ? DataRowVersion.Original : DataRowVersion.Default);
        if (IsKeyNull(keyValues))
        {
            return;
        }
        Range range = sortIndex.FindRecords(keyValues);
        if (range.IsNull)
        {
            return;
        }
        DataRow[] rows = sortIndex.GetRows(range);
        DataRow[] array = rows;
        foreach (DataRow dataRow in array)
        {
            if (DataRowState.Detached != dataRow.RowState && !dataRow._inCascade)
            {
                dataRow.AcceptChanges();
            }
        }
    }
References System.Data.ForeignKeyConstraint._acceptRejectRule, System.Data.ForeignKeyConstraint._childKey, System.Data.DataRow._inCascade, System.Data.ForeignKeyConstraint._parentKey, System.Data.DataRow.AcceptChanges(), System.array, System.Data.Index.FindRecords(), System.Data.DataRow.GetKeyValues(), System.Data.Index.GetRows(), System.Data.DataKey.GetSortIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), System.Data.Range.IsNull, and System.Data.DataRow.RowState.
Referenced by System.Data.ForeignKeyConstraint.CheckCascade().