Terraria: System.Data.ForeignKeyConstraint.CheckCanAddToCollection
CheckCanAddToCollection()
override void System.Data.ForeignKeyConstraint.CheckCanAddToCollection (ConstraintCollection constraints) inline package
Definition at line 206 of file ForeignKeyConstraint.cs.
    {
        if (Table != constraints.Table)
        {
            throw ExceptionBuilder.ConstraintAddFailed(constraints.Table);
        }
        if (Table.Locale.LCID != RelatedTable.Locale.LCID || Table.CaseSensitive != RelatedTable.CaseSensitive)
        {
            throw ExceptionBuilder.CaseLocaleMismatch();
        }
    }
References System.Data.ExceptionBuilder.CaseLocaleMismatch(), System.Data.DataTable.CaseSensitive, System.Data.ExceptionBuilder.ConstraintAddFailed(), System.Data.DataTable.Locale, System.Data.ForeignKeyConstraint.RelatedTable, System.Data.ConstraintCollection.Table, and System.Data.ForeignKeyConstraint.Table.
Referenced by System.Data.ConstraintCollection.AddForeignKeyConstraint().