Terraria: Terraria.WorldBuilding.GenCondition.AreaOr
AreaOr()
GenCondition Terraria.WorldBuilding.GenCondition.AreaOr (int width, int height) inline inherited
    {
        _areaType = AreaType.Or;
        _width = width;
        _height = height;
        return this;
    }
References Terraria.WorldBuilding.GenCondition._areaType, Terraria.WorldBuilding.GenCondition._height, and Terraria.WorldBuilding.GenCondition._width.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindSideExit(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FindVerticalExit(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), and Terraria.GameContent.Biomes.MahoganyTreeBiome.Place().