Terraria: System.Xml.NameTable.AddEntry
AddEntry()
string System.Xml.NameTable.AddEntry (string str, int hashCode) inline private
Definition at line 142 of file NameTable.cs.
    {
        int num = hashCode & _mask;
        Entry entry = new Entry(str, hashCode, _entries[num]);
        _entries[num] = entry;
        if (_count++ == _mask)
        {
            Grow();
        }
        return entry.str;
    }
References System.Xml.NameTable._count, System.Xml.NameTable._entries, System.Xml.NameTable._mask, System.Xml.Dictionary, System.Xml.NameTable.Grow(), and System.str.
Referenced by System.Xml.NameTable.Add(), System.Xml.NameTable.Add(), and System.Xml.NameTable.GetOrAddEntry().