Terraria: System.Xml.Xsl.XsltOld.Compiler.AddQuery
AddQuery() [2/2]
int System.Xml.Xsl.XsltOld.Compiler.AddQuery (string xpathQuery, bool allowVar, bool allowKey, bool isPattern) inline package
Definition at line 577 of file Compiler.cs.
    {
        CompiledXpathExpr compiledQuery;
        try
        {
            compiledQuery = new CompiledXpathExpr(isPattern ? _queryBuilder.BuildPatternQuery(xpathQuery, allowVar, allowKey) : _queryBuilder.Build(xpathQuery, allowVar, allowKey), xpathQuery, needContext: false);
        }
        catch (XPathException inner)
        {
            if (!ForwardCompatibility)
            {
                throw XsltException.Create(System.SR.Xslt_InvalidXPath, new string[1] { xpathQuery }, inner);
            }
            compiledQuery = new ErrorXPathExpression(xpathQuery, Input.BaseURI, Input.LineNumber, Input.LinePosition);
        }
        _queryStore.Add(new TheQuery(compiledQuery, _scopeManager));
        return _queryStore.Count - 1;
    }
References System.Xml.Xsl.XsltOld.Compiler._queryBuilder, MS.Internal.Xml.XPath.QueryBuilder.Build(), MS.Internal.Xml.XPath.QueryBuilder.BuildPatternQuery(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Compiler.ForwardCompatibility, and System.SR.Xslt_InvalidXPath.