Terraria: System.Xml.Xsl.XsltOld.Compiler.PushNamespaceScope
PushNamespaceScope()
void System.Xml.Xsl.XsltOld.Compiler.PushNamespaceScope () inline package
Definition at line 259 of file Compiler.cs.
    {
        _scopeManager.PushScope();
        NavigatorInput input = Input;
        if (input.MoveToFirstNamespace())
        {
            do
            {
                _scopeManager.PushNamespace(input.LocalName, input.Value);
            }
            while (input.MoveToNextNamespace());
            input.ToParent();
        }
    }
References System.Xml.Xsl.XsltOld.Compiler._scopeManager, System.input, System.Xml.Xsl.XsltOld.Compiler.Input, System.Xml.Xsl.XsltOld.InputScopeManager.PushNamespace(), and System.Xml.Xsl.XsltOld.InputScopeManager.PushScope().
Referenced by System.Xml.Xsl.XsltOld.Compiler.PushLiteralScope().