Terraria: System.Data.ForeignKeyConstraint.CascadeUpdate
CascadeUpdate()
void System.Data.ForeignKeyConstraint.CascadeUpdate (DataRow row) inline package
Definition at line 425 of file ForeignKeyConstraint.cs.
    {
        if (-1 == row._newRecord)
        {
            return;
        }
        object[] keyValues = row.GetKeyValues(_parentKey, DataRowVersion.Current);
        if (!Table.DataSet._fInReadXml && IsKeyNull(keyValues))
        {
            return;
        }
        Index sortIndex = _childKey.GetSortIndex();
        switch (UpdateRule)
        {
        case Rule.None:
            if (row.Table.DataSet.EnforceConstraints && !sortIndex.FindRecords(keyValues).IsNull)
            {
                throw ExceptionBuilder.FailedCascadeUpdate(ConstraintName);
            }
            break;
        case Rule.Cascade:
        {
            Range range3 = sortIndex.FindRecords(keyValues);
            if (!range3.IsNull)
            {
                object[] keyValues2 = row.GetKeyValues(_parentKey, DataRowVersion.Proposed);
                DataRow[] rows3 = sortIndex.GetRows(range3);
                for (int m = 0; m < rows3.Length; m++)
                {
                    rows3[m].SetKeyValues(_childKey, keyValues2);
                }
            }
            break;
        }
        case Rule.SetNull:
        {
            object[] array2 = new object[_childKey.ColumnsReference.Length];
            for (int k = 0; k < _childKey.ColumnsReference.Length; k++)
            {
                array2[k] = DBNull.Value;
            }
            Range range2 = sortIndex.FindRecords(keyValues);
            if (!range2.IsNull)
            {
                DataRow[] rows2 = sortIndex.GetRows(range2);
                for (int l = 0; l < rows2.Length; l++)
                {
                    rows2[l].SetKeyValues(_childKey, array2);
                }
            }
            break;
        }
        case Rule.SetDefault:
        {
            object[] array = new object[_childKey.ColumnsReference.Length];
            for (int i = 0; i < _childKey.ColumnsReference.Length; i++)
            {
                array[i] = _childKey.ColumnsReference[i].DefaultValue;
            }
            Range range = sortIndex.FindRecords(keyValues);
            if (!range.IsNull)
            {
                DataRow[] rows = sortIndex.GetRows(range);
                for (int j = 0; j < rows.Length; j++)
                {
                    rows[j].SetKeyValues(_childKey, array);
                }
            }
            break;
        }
        }
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.DataSet._fInReadXml, System.Data.DataRow._newRecord, System.Data.ForeignKeyConstraint._parentKey, System.array, System.Data.DataKey.ColumnsReference, System.Data.Constraint.ConstraintName, System.Data.DataTable.DataSet, System.Data.DataColumn.DefaultValue, System.Data.DataSet.EnforceConstraints, System.Data.ExceptionBuilder.FailedCascadeUpdate(), System.Data.Index.FindRecords(), System.Data.DataRow.GetKeyValues(), System.Data.Index.GetRows(), System.Data.DataKey.GetSortIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), System.Data.Range.IsNull, System.Data.DataRow.SetKeyValues(), System.Data.DataRow.Table, System.Data.ForeignKeyConstraint.Table, System.Data.ForeignKeyConstraint.UpdateRule, and System.DBNull.Value.
Referenced by System.Data.ForeignKeyConstraint.CheckCascade().