Terraria: System.Data.ForeignKeyConstraint.Create
Create()
void System.Data.ForeignKeyConstraint.Create (string relationName, DataColumn[] parentColumns, DataColumn[] childColumns) inline private
Definition at line 727 of file ForeignKeyConstraint.cs.
    {
        if (parentColumns.Length == 0 || childColumns.Length == 0)
        {
            throw ExceptionBuilder.KeyLengthZero();
        }
        if (parentColumns.Length != childColumns.Length)
        {
            throw ExceptionBuilder.KeyLengthMismatch();
        }
        for (int i = 0; i < parentColumns.Length; i++)
        {
            if (parentColumns[i].Computed)
            {
                throw ExceptionBuilder.ExpressionInConstraint(parentColumns[i]);
            }
            if (childColumns[i].Computed)
            {
                throw ExceptionBuilder.ExpressionInConstraint(childColumns[i]);
            }
        }
        _parentKey = new DataKey(parentColumns, copyColumns: true);
        _childKey = new DataKey(childColumns, copyColumns: true);
        ConstraintName = relationName;
        NonVirtualCheckState();
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.ForeignKeyConstraint._parentKey, System.Data.Constraint.ConstraintName, System.Data.ExceptionBuilder.ExpressionInConstraint(), System.Data.ExceptionBuilder.KeyLengthMismatch(), System.Data.ExceptionBuilder.KeyLengthZero(), and System.Data.ForeignKeyConstraint.NonVirtualCheckState().
Referenced by System.Data.ForeignKeyConstraint.ForeignKeyConstraint(), and System.Data.ForeignKeyConstraint.ForeignKeyConstraint().