Terraria: System.Data.ForeignKeyConstraint.NonVirtualCheckState
NonVirtualCheckState()
void System.Data.ForeignKeyConstraint.NonVirtualCheckState () inline private
Definition at line 604 of file ForeignKeyConstraint.cs.
    {
        if (_DataSet != null)
        {
            return;
        }
        _parentKey.CheckState();
        _childKey.CheckState();
        if (_parentKey.Table.DataSet != _childKey.Table.DataSet)
        {
            throw ExceptionBuilder.TablesInDifferentSets();
        }
        for (int i = 0; i < _parentKey.ColumnsReference.Length; i++)
        {
            if (_parentKey.ColumnsReference[i].DataType != _childKey.ColumnsReference[i].DataType || (_parentKey.ColumnsReference[i].DataType == typeof(DateTime) && _parentKey.ColumnsReference[i].DateTimeMode != _childKey.ColumnsReference[i].DateTimeMode && (_parentKey.ColumnsReference[i].DateTimeMode & _childKey.ColumnsReference[i].DateTimeMode) != DataSetDateTime.Unspecified))
            {
                throw ExceptionBuilder.ColumnsTypeMismatch();
            }
        }
        if (_childKey.ColumnsEqual(_parentKey))
        {
            throw ExceptionBuilder.KeyColumnsIdentical();
        }
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.Constraint._DataSet, System.Data.ForeignKeyConstraint._parentKey, System.Data.DataKey.CheckState(), System.Data.DataKey.ColumnsEqual(), System.Data.DataKey.ColumnsReference, System.Data.ExceptionBuilder.ColumnsTypeMismatch(), System.Data.DataTable.DataSet, System.Data.DataColumn.DataType, System.Data.DataColumn.DateTimeMode, System.Data.ExceptionBuilder.KeyColumnsIdentical(), System.Data.DataKey.Table, and System.Data.ExceptionBuilder.TablesInDifferentSets().
Referenced by System.Data.ForeignKeyConstraint.CheckState(), and System.Data.ForeignKeyConstraint.Create().