Terraria: System.Xml.NameTable.Add
Add() [2/2]
override string System.Xml.NameTable.Add (string key) inline
Definition at line 33 of file NameTable.cs.
    {
        if (key == null)
        {
            throw new ArgumentNullException("key");
        }
        if (key.Length == 0)
        {
            return string.Empty;
        }
        int num = ComputeHash32(key);
        for (Entry entry = _entries[num & _mask]; entry != null; entry = entry.next)
        {
            if (entry.hashCode == num && entry.str.Equals(key))
            {
                return entry.str;
            }
        }
        return AddEntry(key, num);
    }
References System.Xml.NameTable._entries, System.Xml.NameTable._mask, System.Xml.NameTable.AddEntry(), System.Xml.NameTable.ComputeHash32(), System.Xml.Dictionary, System.key, and System.Xml.NameTable.Entry.next.
Referenced by System.Xml.Schema.XmlSchemaCollection.Add(), System.Xml.Xsl.IlGen.XmlILElementAnalyzer.AnalyzeAttributeCtor(), System.Xml.DocumentXPathNavigator.LookupNamespace(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToNextSibling(), and System.Xml.XmlReader.ReadToNextSibling().