Terraria: Dust.NewDust
NewDust()
static int Dust.NewDust (Vector2 Position, int Width, int Height, int Type, float SpeedX = 0f, float SpeedY = 0f, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
     {
         if (Main.gameMenu)
         {
             return 6000;
         }
         if (Main.rand == null)
         {
             Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
         }
         if (Main.gamePaused)
         {
             return 6000;
         }
         if (WorldGen.gen)
         {
             return 6000;
         }
         if (Main.netMode == 2)
         {
             return 6000;
         }
         int num = (int)(400f * (1f - dCount));
         Rectangle rectangle = new Rectangle((int)(Main.screenPosition.X - (float)num), (int)(Main.screenPosition.Y - (float)num), Main.screenWidth + num * 2, Main.screenHeight + num * 2);
         Rectangle value = new Rectangle((int)Position.X, (int)Position.Y, 10, 10);
         if (!rectangle.Intersects(value))
         {
             return 6000;
         }
         int result = 6000;
         for (int i = 0; i < 6000; i++)
         {
             Dust dust = Main.dust[i];
             if (dust.active)
             {
                 continue;
             }
             if ((double)i > (double)Main.maxDustToDraw * 0.9)
             {
                 if (Main.rand.Next(4) != 0)
                 {
                     return 6000;
                 }
             }
             else if ((double)i > (double)Main.maxDustToDraw * 0.8)
             {
                 if (Main.rand.Next(3) != 0)
                 {
                     return 6000;
                 }
             }
             else if ((double)i > (double)Main.maxDustToDraw * 0.7)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     return 6000;
                 }
             }
             else if ((double)i > (double)Main.maxDustToDraw * 0.6)
             {
                 if (Main.rand.Next(4) == 0)
                 {
                     return 6000;
                 }
             }
             else if ((double)i > (double)Main.maxDustToDraw * 0.5)
             {
                 if (Main.rand.Next(5) == 0)
                 {
                     return 6000;
                 }
             }
             else
             {
                 dCount = 0f;
             }
             int num2 = Width;
             int num3 = Height;
             if (num2 < 5)
             {
                 num2 = 5;
             }
             if (num3 < 5)
             {
                 num3 = 5;
             }
             result = i;
             dust.fadeIn = 0f;
             dust.active = true;
             dust.type = Type;
             dust.noGravity = false;
             dust.color = newColor;
             dust.alpha = Alpha;
             dust.position.X = Position.X + (float)Main.rand.Next(num2 - 4) + 4f;
             dust.position.Y = Position.Y + (float)Main.rand.Next(num3 - 4) + 4f;
             dust.velocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedX;
             dust.velocity.Y = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedY;
             dust.frame.X = 10 * Type;
             dust.frame.Y = 10 * Main.rand.Next(3);
             dust.shader = null;
             dust.customData = null;
             dust.noLightEmittence = false;
             int num4 = Type;
             while (num4 >= 100)
             {
                 num4 -= 100;
                 dust.frame.X -= 1000;
                 dust.frame.Y += 30;
             }
             dust.frame.Width = 8;
             dust.frame.Height = 8;
             dust.rotation = 0f;
             dust.scale = 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
             dust.scale *= Scale;
             dust.noLight = false;
             dust.firstFrame = true;
             if (dust.type == 228 || dust.type == 279 || dust.type == 269 || dust.type == 135 || dust.type == 6 || dust.type == 242 || dust.type == 75 || dust.type == 169 || dust.type == 29 || (dust.type >= 59 && dust.type <= 65) || dust.type == 158 || dust.type == 293 || dust.type == 294 || dust.type == 295 || dust.type == 296 || dust.type == 297 || dust.type == 298 || dust.type == 302 || dust.type == 307 || dust.type == 310)
             {
                 dust.velocity.Y = (float)Main.rand.Next(-10, 6) * 0.1f;
                 dust.velocity.X *= 0.3f;
                 dust.scale *= 0.7f;
             }
             if (dust.type == 127 || dust.type == 187)
             {
                 dust.velocity *= 0.3f;
                 dust.scale *= 0.7f;
             }
             if (dust.type == 308)
             {
                 dust.velocity *= 0.5f;
                 dust.velocity.Y += 1f;
             }
             if (dust.type == 33 || dust.type == 52 || dust.type == 266 || dust.type == 98 || dust.type == 99 || dust.type == 100 || dust.type == 101 || dust.type == 102 || dust.type == 103 || dust.type == 104 || dust.type == 105)
             {
                 dust.alpha = 170;
                 dust.velocity *= 0.5f;
                 dust.velocity.Y += 1f;
             }
             if (dust.type == 41)
             {
                 dust.velocity *= 0f;
             }
             if (dust.type == 80)
             {
                 dust.alpha = 50;
             }
             if (dust.type == 34 || dust.type == 35 || dust.type == 152)
             {
                 dust.velocity *= 0.1f;
                 dust.velocity.Y = -0.5f;
                 if (dust.type == 34 && !Collision.WetCollision(new Vector2(dust.position.X, dust.position.Y - 8f), 4, 4))
                 {
                     dust.active = false;
                 }
             }
             break;
         }
         return result;
     }
References active, alpha, color, customData, dCount, Main.dust, fadeIn, firstFrame, frame, Main.gameMenu, Main.gamePaused, WorldGen.gen, Main.maxDustToDraw, Main.netMode, UnifiedRandom.Next(), noGravity, noLight, noLightEmittence, position, Main.rand, rotation, scale, Main.screenHeight, Main.screenPosition, Main.screenWidth, shader, type, velocity, and Collision.WetCollision().
Referenced by NPC.AI(), Projectile.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_006_Worms(), Projectile.AI_009_MagicMissiles(), Projectile.AI_009_MagicMissiles_Old(), Projectile.AI_010(), Projectile.AI_015_Flails_Dust(), Projectile.AI_016(), Projectile.AI_019_Spears(), Projectile.AI_019_Spears_Old(), Projectile.AI_026(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), NPC.AI_045_Golem(), Projectile.AI_061_FishingBobber_DoASplash(), Projectile.AI_062(), NPC.AI_065_Butterflies(), Projectile.AI_067_FreakingPirates(), NPC.AI_069_DukeFishron(), Projectile.AI_075(), Projectile.AI_099_2(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), Projectile.AI_111_DryadsWard(), NPC.AI_117_BloodNautilus(), NPC.AI_120_HallowBoss(), Projectile.AI_120_StardustGuardian(), NPC.AI_121_QueenSlime(), Projectile.AI_121_StardustDragon(), Projectile.AI_135_OgreStomp(), Projectile.AI_145_BookStaffStorm(), Projectile.AI_147_Celeb2Rocket(), Projectile.AI_147_Explosion(), Projectile.AI_162_TigerPounce(), Projectile.AI_165_Whip(), Projectile.AI_177_IceWhipSlicer(), Projectile.AI_178_FireExplosion(), Projectile.AI_184_BadTorchLuck(), Projectile.AI_186_PrincessWeapon(), NPC.BigMimicSpawnSmoke(), PlayerDrawSet.BoringSetup(), NPC.CheckDrowning(), Player.CheckDrowning(), CloneDust(), NPC.Collision_WaterCollision(), Player.CommandForbiddenStorm(), Player.DashMovement(), Item.DespawnIfMeetingConditions(), Projectile.DoRainbowCrystalStaffExplosion(), Mount.DoSpawnDust(), Player.DoubleJumpVisuals(), TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Main.DrawItem(), Main.DrawNPCDirect(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), TileDrawing.DrawSingleTile(), TileDrawing.DrawTiles_EmitParticles(), TileDrawing.DrawVineStrip(), TileDrawing.EmitAlchemyHerbParticles(), Sandstorm.EmitDust(), Projectile.EmitEnchantmentVisualsAt(), Player.EmitMaxManaEffect(), NPC.FindFrame(), MessageBuffer.GetData(), Gore.Gore_UpdateLeaf(), Projectile.HandleMovement(), NPC.HitEffect(), Player.Hurt(), LiquidRenderer.InternalPrepareDraw(), Player.ItemCheck(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_ApplyUseStyle(), Player.ItemCheck_EmitHeldItemLight(), Player.ItemCheck_EmitUseVisuals(), Player.ItemCheck_GetMeleeHitbox(), Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Player.JumpMovement(), Projectile.Kill(), WorldGen.KillActuator(), Player.KillMe(), WorldGen.KillTile_MakeTileDust(), WorldGen.KillWall_MakeWallDust(), WorldGen.KillWire(), WorldGen.KillWire2(), WorldGen.KillWire3(), WorldGen.KillWire4(), Player.MakeFloorDust(), NPC.MakeTransitionEffectsForTextureChanges(), NPC.moneyPing(), Item.MoveInWorld(), NewDustDirect(), NewDustPerfect(), Player.NinjaDodge(), Main.oldDrawWater(), WorldGen.paintCoatEffect(), WorldGen.paintEffect(), WorldGen.PlaceTile(), Player.PlayerFrame(), Utils.PoofOfSmoke(), QuickDust(), NPC.ReflectProjectile(), Item.ShimmerEffect(), Main.snowing(), DelegateMethods.Minecart.Sparks(), DelegateMethods.Minecart.SparksFart(), DelegateMethods.Minecart.SparksMech(), DelegateMethods.Minecart.SparksMeow(), DelegateMethods.Minecart.SparksTerraFart(), ParticleOrchestrator.Spawn_Digestion(), ParticleOrchestrator.Spawn_PaladinsHammer(), ParticleOrchestrator.Spawn_PrincessWeapon(), ParticleOrchestrator.Spawn_RainbowRodHit(), ParticleOrchestrator.Spawn_ShimmerTownNPC(), ParticleOrchestrator.Spawn_StardustPunch(), Player.SpawnFastRunParticles(), TeleportPylonsSystem.SpawnInWorldDust(), Player.StickyMovement(), Collision.StickyTiles(), Main.TeleportEffect(), DelegateMethods.TestDust(), NPC.TransformVisuals(), WaterfallManager.TrySparkling(), Chest.Unlock(), WorldGen.UnlockDoor(), Gore.Update(), Rain.Update(), Player.Update(), Projectile.Update(), Player.UpdateArmorSets(), UpdateDust(), Mount.UpdateEffects(), Mount.UpdateFrame(), Player.UpdateHairDyeDust(), Item.UpdateItem(), Item.UpdateItem_VisualEffects(), Player.UpdateLifeRegen(), Player.UpdateManaRegen(), Player.UpdateMinionTarget(), NPC.UpdateNPC(), NPC.UpdateNPC_CastLights(), NPC.UpdateNPC_SoulDrainDebuff(), NPC.UpdateNPC_TeleportVisuals(), Player.UpdateTeleportVisuals(), Mount.UseDrill(), Player.WallslideMovement(), Player.WingAirVisuals(), Player.WingFrame(), and Player.Yoraiz0rEye().