Terraria: System.Data.ForeignKeyConstraint.IsConstraintViolated
IsConstraintViolated()
override bool System.Data.ForeignKeyConstraint.IsConstraintViolated () inline package
Definition at line 235 of file ForeignKeyConstraint.cs.
    {
        Index sortIndex = _childKey.GetSortIndex();
        object[] uniqueKeyValues = sortIndex.GetUniqueKeyValues();
        bool result = false;
        Index sortIndex2 = _parentKey.GetSortIndex();
        for (int i = 0; i < uniqueKeyValues.Length; i++)
        {
            object[] array = (object[])uniqueKeyValues[i];
            if (!IsKeyNull(array) && !sortIndex2.IsKeyInIndex(array))
            {
                DataRow[] rows = sortIndex.GetRows(sortIndex.FindRecords(array));
                string rowError = System.SR.Format(System.SR.DataConstraint_ForeignKeyViolation, ConstraintName, ExceptionBuilder.KeysToString(array));
                for (int j = 0; j < rows.Length; j++)
                {
                    rows[j].RowError = rowError;
                }
                result = true;
            }
        }
        return result;
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.ForeignKeyConstraint._parentKey, System.array, System.Data.Constraint.ConstraintName, System.SR.DataConstraint_ForeignKeyViolation, System.Data.Index.FindRecords(), System.SR.Format(), System.Data.Index.GetRows(), System.Data.DataKey.GetSortIndex(), System.Data.Index.GetUniqueKeyValues(), System.Data.Index.IsKeyInIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), System.Data.ExceptionBuilder.KeysToString(), and System.Data.DataRow.RowError.