Terraria: System.Xml.Xsl.XsltOld.Compiler.ResolvePrefixes
ResolvePrefixes()
string[] System.Xml.Xsl.XsltOld.Compiler.ResolvePrefixes (string tokens) inline private
Definition at line 363 of file Compiler.cs.
    {
        if (tokens == null || tokens.Length == 0)
        {
            return null;
        }
        string[] array = XmlConvert.SplitString(tokens);
        try
        {
            for (int i = 0; i < array.Length; i++)
            {
                string text = array[i];
                array[i] = _scopeManager.ResolveXmlNamespace((text == "#default") ? string.Empty : text);
            }
            return array;
        }
        catch (XsltException)
        {
            if (!ForwardCompatibility)
            {
                throw;
            }
            return null;
        }
    }
References System.Xml.Xsl.XsltOld.Compiler._scopeManager, System.array, System.Xml.Xsl.XsltOld.Compiler.ForwardCompatibility, System.Xml.Xsl.XsltOld.InputScopeManager.ResolveXmlNamespace(), System.Xml.XmlConvert.SplitString(), and System.text.
Referenced by System.Xml.Xsl.XsltOld.Compiler.InsertExcludedNamespace(), and System.Xml.Xsl.XsltOld.Compiler.InsertExtensionNamespace().