Terraria: System.Data.ForeignKeyConstraint.CheckCascade
CheckCascade()
void System.Data.ForeignKeyConstraint.CheckCascade (DataRow row, DataRowAction action) inline package
Definition at line 515 of file ForeignKeyConstraint.cs.
    {
        if (row._inCascade)
        {
            return;
        }
        row._inCascade = true;
        try
        {
            switch (action)
            {
            case DataRowAction.Change:
                if (row.HasKeyChanged(_parentKey))
                {
                    CascadeUpdate(row);
                }
                break;
            case DataRowAction.Delete:
                CascadeDelete(row);
                break;
            case DataRowAction.Commit:
                CascadeCommit(row);
                break;
            case DataRowAction.Rollback:
                CascadeRollback(row);
                break;
            default:
                _ = 16;
                break;
            }
        }
        finally
        {
            row._inCascade = false;
        }
    }
References System.Data.DataRow._inCascade, System.Data.ForeignKeyConstraint._parentKey, System.action, System.Data.ForeignKeyConstraint.CascadeCommit(), System.Data.ForeignKeyConstraint.CascadeDelete(), System.Data.ForeignKeyConstraint.CascadeRollback(), System.Data.ForeignKeyConstraint.CascadeUpdate(), and System.Data.DataRow.HasKeyChanged().