Terraria: System.Xml.Xsl.XsltOld.Compiler.PopScope
PopScope()
virtual void System.Xml.Xsl.XsltOld.Compiler.PopScope () inline package virtual
Definition at line 274 of file Compiler.cs.
    {
        _currentTemplate.ReleaseVariableSlots(_scopeManager.CurrentScope.GetVeriablesCount());
        _scopeManager.PopScope();
    }
References System.Xml.Xsl.XsltOld.Compiler._currentTemplate, System.Xml.Xsl.XsltOld.Compiler._scopeManager, System.Xml.Xsl.XsltOld.InputScopeManager.CurrentScope, System.Xml.Xsl.XsltOld.InputScope.GetVeriablesCount(), System.Xml.Xsl.XsltOld.InputScopeManager.PopScope(), and System.Xml.Xsl.XsltOld.TemplateBaseAction.ReleaseVariableSlots().