Terraria: Dust.NewDustDirect
NewDustDirect()
static Dust Dust.NewDustDirect (Vector2 Position, int Width, int Height, int Type, float SpeedX = 0f, float SpeedY = 0f, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline static
References Main.dust, NewDust(), and velocity.
Referenced by NPC.AI(), Projectile.AI_001(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), Projectile.AI_009_MagicMissiles(), Projectile.AI_009_MagicMissiles_Old(), Projectile.AI_015_Flails_Dust(), Projectile.AI_016(), Projectile.AI_019_Spears(), Projectile.AI_019_Spears_Old(), Projectile.AI_026(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_109_DarkMage(), NPC.AI_111_DD2LightningBug(), NPC.AI_112_FairyCritter(), NPC.AI_117_BloodNautilus(), NPC.AI_123_Deerclops(), Projectile.AI_130_FlameBurstTower(), Projectile.AI_131_FlameBurstShot(), Projectile.AI_136_BetsyBreath(), Projectile.AI_137_LightningAura(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_142_MonkStaffT2And3(), Projectile.AI_143_MonkStaffT2Ghast(), Projectile.AI_144_DD2Pet(), Projectile.AI_145_BookStaffStorm(), Projectile.AI_151_SuperStar(), Projectile.AI_152_SuperStarSlash(), Projectile.AI_153_ToiletPop(), Projectile.AI_155_MysticSnakeCoil(), Projectile.AI_155_SpawnRopeIn(), Projectile.AI_165_Whip(), Projectile.AI_169_Smolstars(), Projectile.AI_177_IceWhipSlicer(), Projectile.AI_192_JuminoAnimation(), Projectile.AI_193_Flamethrower(), Projectile.AI_194_HorsemanPumpkin(), PlayerDrawSet.BoringSetup(), SpelunkerProjectileHelper.CheckSpot(), Projectile.CreateImpactExplosion2_FlailTileCollision(), Projectile.CreateImpactExplosion2_SleepyOctopod(), Mount.DoSpawnDust(), Main.DrawNPCExtras(), TileDrawing.DrawTiles_EmitParticles(), DD2Film.DryadPortalFade(), Mount.EmitGolfCartSmoke(), NPC.FairyEffects(), NPC.FindFrame(), NPC.HitEffect(), Player.ItemCheck_EmitUseVisuals(), Projectile.Kill(), NPC.MakeTransitionEffectsForTextureChanges(), Player.MowTheLawn(), Player.RocketBootVisuals(), ParticleOrchestrator.Spawn_FlameWaders(), ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), Player.SpawnFastRunParticles(), PotionOfReturnGateHelper.SpawnReturnPortalDust(), VoidLensHelper.SpawnVoidLensDust(), DelegateMethods.SpreadDirt(), DelegateMethods.SpreadDry(), DelegateMethods.SpreadHoney(), DelegateMethods.SpreadLava(), DelegateMethods.SpreadWater(), Main.TeleportEffect(), WorldGen.TreeGrowFX_AshShake(), Player.Update(), NPC.UpdateNPC_BuffApplyVFX(), Player.WingAirVisuals(), and Player.WingFrame().