Terraria: System.Data.ForeignKeyConstraint.CascadeDelete
CascadeDelete()
void System.Data.ForeignKeyConstraint.CascadeDelete (DataRow row) inline package
Definition at line 306 of file ForeignKeyConstraint.cs.
    {
        if (-1 == row._newRecord)
        {
            return;
        }
        object[] keyValues = row.GetKeyValues(_parentKey, DataRowVersion.Current);
        if (IsKeyNull(keyValues))
        {
            return;
        }
        Index sortIndex = _childKey.GetSortIndex();
        switch (DeleteRule)
        {
        case Rule.None:
            if (row.Table.DataSet.EnforceConstraints)
            {
                Range range2 = sortIndex.FindRecords(keyValues);
                if (!range2.IsNull && (range2.Count != 1 || sortIndex.GetRow(range2.Min) != row))
                {
                    throw ExceptionBuilder.FailedCascadeDelete(ConstraintName);
                }
            }
            break;
        case Rule.Cascade:
        {
            object[] keyValues2 = row.GetKeyValues(_parentKey, DataRowVersion.Default);
            Range range4 = sortIndex.FindRecords(keyValues2);
            if (range4.IsNull)
            {
                break;
            }
            DataRow[] rows3 = sortIndex.GetRows(range4);
            foreach (DataRow dataRow in rows3)
            {
                if (!dataRow._inCascade)
                {
                    dataRow.Table.DeleteRow(dataRow);
                }
            }
            break;
        }
        case Rule.SetNull:
        {
            object[] array2 = new object[_childKey.ColumnsReference.Length];
            for (int k = 0; k < _childKey.ColumnsReference.Length; k++)
            {
                array2[k] = DBNull.Value;
            }
            Range range3 = sortIndex.FindRecords(keyValues);
            if (range3.IsNull)
            {
                break;
            }
            DataRow[] rows2 = sortIndex.GetRows(range3);
            for (int l = 0; l < rows2.Length; l++)
            {
                if (row != rows2[l])
                {
                    rows2[l].SetKeyValues(_childKey, array2);
                }
            }
            break;
        }
        case Rule.SetDefault:
        {
            object[] array = new object[_childKey.ColumnsReference.Length];
            for (int i = 0; i < _childKey.ColumnsReference.Length; i++)
            {
                array[i] = _childKey.ColumnsReference[i].DefaultValue;
            }
            Range range = sortIndex.FindRecords(keyValues);
            if (range.IsNull)
            {
                break;
            }
            DataRow[] rows = sortIndex.GetRows(range);
            for (int j = 0; j < rows.Length; j++)
            {
                if (row != rows[j])
                {
                    rows[j].SetKeyValues(_childKey, array);
                }
            }
            break;
        }
        }
    }
References System.Data.ForeignKeyConstraint._childKey, System.Data.DataRow._inCascade, System.Data.DataRow._newRecord, System.Data.ForeignKeyConstraint._parentKey, System.array, System.Data.DataKey.ColumnsReference, System.Data.Constraint.ConstraintName, System.Data.Range.Count, System.Data.DataTable.DataSet, System.Data.DataColumn.DefaultValue, System.Data.DataTable.DeleteRow(), System.Data.ForeignKeyConstraint.DeleteRule, System.Data.DataSet.EnforceConstraints, System.Data.ExceptionBuilder.FailedCascadeDelete(), System.Data.Index.FindRecords(), System.Data.DataRow.GetKeyValues(), System.Data.Index.GetRow(), System.Data.Index.GetRows(), System.Data.DataKey.GetSortIndex(), System.Data.ForeignKeyConstraint.IsKeyNull(), System.Data.Range.IsNull, System.Data.Range.Min, System.Data.DataRow.SetKeyValues(), System.Data.DataRow.Table, and System.DBNull.Value.
Referenced by System.Data.ForeignKeyConstraint.CheckCascade().