Terraria: Dust.dustWater
dustWater()
static int Dust.dustWater () inline static
     {
         return Main.waterStyle switch
         {
             2 => 98,
             3 => 99,
             4 => 100,
             5 => 101,
             6 => 102,
             7 => 103,
             8 => 104,
             9 => 105,
             10 => 123,
             12 => 288,
             _ => 33,
         };
     }
References Main.waterStyle.
Referenced by Projectile.AI_016(), Projectile.AI_061_FishingBobber_DoASplash(), NPC.Collision_WaterCollision(), Player.ItemCheck(), Projectile.Kill(), Item.MoveInWorld(), DelegateMethods.SpreadWater(), Main.TeleportEffect(), Rain.Update(), Player.Update(), and Projectile.Update().