Terraria: System.Xml.Xsl.Qil.QilExpression.QilExpression
QilExpression()
System.Xml.Xsl.Qil.QilExpression.QilExpression (QilNodeType nodeType, QilNode root, QilFactory factory) inline
Definition at line 178 of file QilExpression.cs.
        : base(nodeType)
    {
        _factory = factory;
        _isDebug = factory.False();
        _defWSet = factory.LiteralObject(new XmlWriterSettings
        {
            ConformanceLevel = ConformanceLevel.Auto
        });
        _wsRules = factory.LiteralObject(new List<WhitespaceRule>());
        _gloVars = factory.GlobalVariableList();
        _gloParams = factory.GlobalParameterList();
        _earlBnd = factory.LiteralObject(new List<EarlyBoundInfo>());
        _funList = factory.FunctionList();
        _rootNod = root;
    }
References System.Xml.Xsl.Qil.QilExpression._defWSet, System.Xml.Xsl.Qil.QilExpression._earlBnd, System.Xml.Xsl.Qil.QilExpression._factory, System.Xml.Xsl.Qil.QilExpression._funList, System.Xml.Xsl.Qil.QilExpression._gloParams, System.Xml.Xsl.Qil.QilExpression._gloVars, System.Xml.Xsl.Qil.QilExpression._isDebug, System.Xml.Xsl.Qil.QilExpression._rootNod, System.Xml.Xsl.Qil.QilExpression._wsRules, System.Xml.Dictionary, System.Xml.Xsl.Qil.QilFactory.False(), System.Xml.Xsl.Qil.QilFactory.FunctionList(), System.Xml.Xsl.Qil.QilFactory.GlobalParameterList(), System.Xml.Xsl.Qil.QilFactory.GlobalVariableList(), and System.Xml.Xsl.Qil.QilFactory.LiteralObject().