Terraria: System.Diagnostics.Tracing.TraceLoggingTypeInfo.WriteData
WriteData()
void System.Diagnostics.Tracing.TraceLoggingTypeInfo.WriteData (PropertyValue value) abstract
Referenced by System.Diagnostics.Tracing.ArrayTypeInfo.WriteData(), System.Diagnostics.Tracing.EnumerableTypeInfo.WriteData(), System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(), and System.Diagnostics.Tracing.NullableTypeInfo.WriteData().