Terraria: System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions
WriteObjectHandleExceptions() [2/2]
void System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions (XmlWriterDelegator writer, object graph, DataContractResolver dataContractResolver) inline package inherited
Definition at line 95 of file XmlObjectSerializer.cs.
    {
        try
        {
            CheckNull(writer, "writer");
            InternalWriteObject(writer, graph, dataContractResolver);
        }
        catch (XmlException innerException)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorSerializing, GetSerializeType(graph), innerException), innerException));
        }
        catch (FormatException innerException2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorSerializing, GetSerializeType(graph), innerException2), innerException2));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorSerializing, System.Runtime.Serialization.XmlObjectSerializer.GetSerializeType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.writer.