Terraria: System.Runtime.Serialization.XmlObjectSerializer.ReadObject
ReadObject() [1/5]
virtual ? object System.Runtime.Serialization.XmlObjectSerializer.ReadObject (Stream stream) inline virtual
Reimplemented in System.Runtime.Serialization.Json.DataContractJsonSerializer.
Definition at line 256 of file XmlObjectSerializer.cs.
    {
        CheckNull(stream, "stream");
        return ReadObject(XmlDictionaryReader.CreateTextReader(stream, XmlDictionaryReaderQuotas.Max));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Xml.XmlDictionaryReader.CreateTextReader(), System.Xml.XmlDictionaryReaderQuotas.Max, System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), and System.stream.
Referenced by System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), and System.Runtime.Serialization.XmlObjectSerializer.ReadObject().