Terraria: System.Runtime.Serialization.XmlObjectSerializer.CheckNull
CheckNull()
static void System.Runtime.Serialization.XmlObjectSerializer.CheckNull (object obj, string name) inline static package inherited
Definition at line 413 of file XmlObjectSerializer.cs.
    {
        if (obj == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException(name));
        }
    }
References System.obj, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.XmlReaderDelegator(), System.Runtime.Serialization.XmlWriterDelegator.XmlWriterDelegator(), System.Runtime.Serialization.DataContractSerializer.Initialize(), System.Runtime.Serialization.Json.DataContractJsonSerializer.Initialize(), System.Runtime.Serialization.XmlObjectSerializer.IsStartObject(), System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions(), System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObject(), System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObject(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObjectHandleExceptions(), System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(), System.Runtime.Serialization.XmlObjectSerializer.WriteObject(), System.Runtime.Serialization.XmlObjectSerializer.WriteObject(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContent(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteStartObject(), and System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions().