Terraria: System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions
IsStartObjectHandleExceptions()
bool System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions (XmlReaderDelegator reader) inline package inherited
Definition at line 338 of file XmlObjectSerializer.cs.
    {
        try
        {
            CheckNull(reader, "reader");
            return InternalIsStartObject(reader);
        }
        catch (XmlException innerException)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorIsStartObject, GetDeserializeType(), innerException), innerException));
        }
        catch (FormatException innerException2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorIsStartObject, GetDeserializeType(), innerException2), innerException2));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorIsStartObject, System.Runtime.Serialization.XmlObjectSerializer.GetDeserializeType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.XmlObjectSerializer.InternalIsStartObject(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.IsStartObject(), System.Runtime.Serialization.DataContractSerializer.IsStartObject(), System.Runtime.Serialization.Json.DataContractJsonSerializer.IsStartObject(), and System.Runtime.Serialization.DataContractSerializer.IsStartObject().