Terraria: System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError
GetTypeInfoError()
static string System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError (string errorMessage, Type type, Exception innerException) inline static package inherited
Definition at line 451 of file XmlObjectSerializer.cs.
    {
        string p = ((type == null) ? string.Empty : System.SR.Format(System.SR.ErrorTypeInfo, DataContract.GetClrTypeFullName(type)));
        string p2 = ((innerException == null) ? string.Empty : innerException.Message);
        return System.SR.Format(errorMessage, p, p2);
    }
References System.SR.ErrorTypeInfo, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), and System.type.
Referenced by System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObjectHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(), and System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions().