Terraria: System.Runtime.Serialization.XmlObjectSerializer.ReadObject
ReadObject() [4/5]
virtual ? object System.Runtime.Serialization.XmlObjectSerializer.ReadObject (XmlReader reader) inline virtual
Reimplemented in System.Runtime.Serialization.Json.DataContractJsonSerializer, and System.Runtime.Serialization.DataContractSerializer.
Definition at line 263 of file XmlObjectSerializer.cs.
    {
        CheckNull(reader, "reader");
        return ReadObject(XmlDictionaryReader.CreateDictionaryReader(reader));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Xml.XmlDictionaryReader.CreateDictionaryReader(), and System.Runtime.Serialization.XmlObjectSerializer.ReadObject().