Terraria: System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions
WriteObjectContentHandleExceptions()
void System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions (XmlWriterDelegator writer, object graph) inline package inherited
Definition at line 163 of file XmlObjectSerializer.cs.
    {
        try
        {
            CheckNull(writer, "writer");
            if (writer.WriteState != WriteState.Element)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(System.SR.Format(System.SR.XmlWriterMustBeInElement, writer.WriteState)));
            }
            InternalWriteObjectContent(writer, graph);
        }
        catch (XmlException innerException)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorSerializing, GetSerializeType(graph), innerException), innerException));
        }
        catch (FormatException innerException2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorSerializing, GetSerializeType(graph), innerException2), innerException2));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorSerializing, System.SR.Format(), System.Runtime.Serialization.XmlObjectSerializer.GetSerializeType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.writer, and System.SR.XmlWriterMustBeInElement.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObjectContent(), System.Runtime.Serialization.DataContractSerializer.WriteObjectContent(), System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObjectContent(), and System.Runtime.Serialization.DataContractSerializer.WriteObjectContent().