Terraria: System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException
CreateSerializationException() [1/2]
static SerializationException System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException (string errorMessage) inline static package inherited
Definition at line 440 of file XmlObjectSerializer.cs.
    {
        return CreateSerializationException(errorMessage, null);
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException().
Referenced by System.Runtime.Serialization.HybridObjectCache.Add(), System.Runtime.Serialization.XmlReaderDelegator.CheckActualArrayLength(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CheckEndOfArray(), System.Runtime.Serialization.Json.DataContractJsonSerializer.CheckIfTypeIsReference(), System.Runtime.Serialization.XmlSerializableReader.Close(), System.Runtime.Serialization.XmlSerializableWriter.Close(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.CreateSerializationException(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationExceptionWithReaderDetails(), System.Runtime.Serialization.XmlSerializableWriter.EndWrite(), System.Runtime.Serialization.XmlObjectSerializerReadContext.EnsureArraySize< T >(), System.Runtime.Serialization.ObjectToIdCache.FindElement(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObject(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetExistingObjectOrExtensionData(), System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetISerializableConstructor(), System.Runtime.Serialization.XmlObjectSerializerReadContext.GetRealObject(), System.Runtime.Serialization.XmlObjectSerializerContext.IncrementItemCount(), System.Runtime.Serialization.CodeGenerator.InternalConvert(), System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(), System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeInSharedTypeMode(), System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(), System.Runtime.Serialization.DataContractSerializer.InternalReadObject(), System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(), System.Runtime.Serialization.XmlObjectSerializer.IsStartObjectHandleExceptions(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldelem(), System.Runtime.Serialization.CodeGenerator.LoadMember(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.OnHandleReference(), System.Runtime.Serialization.XPathQueryGenerator.ProcessClassDataContract(), System.Runtime.Serialization.XPathQueryGenerator.ProcessDataContract(), System.Runtime.Serialization.XmlObjectSerializerReadContext.Read(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadAndResolveUnknownXmlData(), System.Runtime.Serialization.Attributes.ReadArraySize(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.EnumDataContract.ReadEnumValue(), System.Runtime.Serialization.Attributes.ReadId(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.Json.JsonObjectDataContract.ReadJsonValueCore(), System.Runtime.Serialization.XmlSerializableServices.ReadNodes(), System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(), System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadPrimitiveExtensionDataValue(), System.Runtime.Serialization.Attributes.ReadRef(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownCollectionData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadUnknownXmlData(), System.Runtime.Serialization.ObjectDataContract.ReadXmlValue(), System.Runtime.Serialization.ObjectToIdCache.RemoveAt(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReplaceDeserializedObject(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(), System.Runtime.Serialization.CodeGenerator.Stelem(), System.Runtime.Serialization.CodeGenerator.Store(), System.Runtime.Serialization.CodeGenerator.StoreMember(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowArrayExceededSizeException(), System.Runtime.Serialization.CodeGenerator.ThrowMismatchException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowNullValueReturnedForGetOnlyCollectionException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ThrowRequiredMemberMissingException(), System.Runtime.Serialization.XmlObjectSerializerReadContext.TryHandleNullOrRef(), System.Runtime.Serialization.PrimitiveDataContract.TryReadNullAtTopLevel(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyObjectCompatibilityWithInterface(), System.Runtime.Serialization.CodeGenerator.VerifyParameterCount(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.VerifyType(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat(), System.Runtime.Serialization.XmlSerializableWriter.WriteEndElement(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObjectHandleExceptions(), System.Runtime.Serialization.EnumDataContract.WriteEnumValue(), System.Runtime.Serialization.XmlSerializableWriter.WriteFullEndElement(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteISerializable(), System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteIXmlSerializable(), System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson.WriteJsonISerializable(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectContentHandleExceptions(), System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(), and System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions().