Terraria: System.Runtime.Serialization.XmlObjectSerializer.IsRootElement
IsRootElement()
bool System.Runtime.Serialization.XmlObjectSerializer.IsRootElement (XmlReaderDelegator reader, DataContract contract, XmlDictionaryString name, XmlDictionaryString ns) inline package inherited
Definition at line 374 of file XmlObjectSerializer.cs.
    {
        reader.MoveToElement();
        if (name != null)
        {
            return reader.IsStartElement(name, ns ?? XmlDictionaryString.Empty);
        }
        if (!contract.HasRoot)
        {
            return reader.IsStartElement();
        }
        if (reader.IsStartElement(contract.TopLevelElementName, contract.TopLevelElementNamespace))
        {
            return true;
        }
        ClassDataContract classDataContract = contract as ClassDataContract;
        if (classDataContract != null)
        {
            classDataContract = classDataContract.BaseContract;
        }
        while (classDataContract != null)
        {
            if (reader.IsStartElement(classDataContract.TopLevelElementName, classDataContract.TopLevelElementNamespace))
            {
                return true;
            }
            classDataContract = classDataContract.BaseContract;
        }
        if (classDataContract == null)
        {
            DataContract primitiveDataContract = PrimitiveDataContract.GetPrimitiveDataContract(Globals.TypeOfObject);
            if (reader.IsStartElement(primitiveDataContract.TopLevelElementName, primitiveDataContract.TopLevelElementNamespace))
            {
                return true;
            }
        }
        return false;
    }
References System.Xml.XmlDictionaryString.Empty, System.Runtime.Serialization.PrimitiveDataContract.GetPrimitiveDataContract(), System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), System.Runtime.Serialization.XmlReaderDelegator.MoveToElement(), and System.Runtime.Serialization.Globals.TypeOfObject.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalIsStartObject(), and System.Runtime.Serialization.DataContractSerializer.InternalIsStartObject().