Terraria: System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions
ReadObjectHandleExceptions() [2/2]
object System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions (XmlReaderDelegator reader, bool verifyObjectName, DataContractResolver dataContractResolver) inline package inherited
Definition at line 320 of file XmlObjectSerializer.cs.
    {
        try
        {
            CheckNull(reader, "reader");
            return InternalReadObject(reader, verifyObjectName, dataContractResolver);
        }
        catch (XmlException innerException)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorDeserializing, GetDeserializeType(), innerException), innerException));
        }
        catch (FormatException innerException2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorDeserializing, GetDeserializeType(), innerException2), innerException2));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorDeserializing, System.Runtime.Serialization.XmlObjectSerializer.GetDeserializeType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().