Terraria: System.Runtime.Serialization.XmlObjectSerializer.WriteObject
WriteObject() [1/3]
virtual void System.Runtime.Serialization.XmlObjectSerializer.WriteObject (Stream stream, object? graph) inline virtual
Reimplemented in System.Runtime.Serialization.Json.DataContractJsonSerializer.
Definition at line 46 of file XmlObjectSerializer.cs.
    {
        CheckNull(stream, "stream");
        XmlDictionaryWriter xmlDictionaryWriter = XmlDictionaryWriter.CreateTextWriter(stream, Encoding.UTF8, ownsStream: false);
        WriteObject(xmlDictionaryWriter, graph);
        xmlDictionaryWriter.Flush();
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Xml.XmlDictionaryWriter.CreateTextWriter(), System.stream, System.Text.Encoding.UTF8, and System.Runtime.Serialization.XmlObjectSerializer.WriteObject().
Referenced by System.Runtime.Serialization.XmlObjectSerializer.WriteObject(), and System.Runtime.Serialization.XmlObjectSerializer.WriteObject().