Terraria: System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions
WriteStartObjectHandleExceptions()
void System.Runtime.Serialization.XmlObjectSerializer.WriteStartObjectHandleExceptions (XmlWriterDelegator writer, object graph) inline package inherited
Definition at line 145 of file XmlObjectSerializer.cs.
    {
        try
        {
            CheckNull(writer, "writer");
            InternalWriteStartObject(writer, graph);
        }
        catch (XmlException innerException)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorWriteStartObject, GetSerializeType(graph), innerException), innerException));
        }
        catch (FormatException innerException2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(CreateSerializationException(GetTypeInfoError(System.SR.ErrorWriteStartObject, GetSerializeType(graph), innerException2), innerException2));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ErrorWriteStartObject, System.Runtime.Serialization.XmlObjectSerializer.GetSerializeType(), System.Runtime.Serialization.XmlObjectSerializer.GetTypeInfoError(), System.Runtime.Serialization.XmlObjectSerializer.InternalWriteStartObject(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.writer.
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteStartObject(), System.Runtime.Serialization.DataContractSerializer.WriteStartObject(), System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteStartObject(), and System.Runtime.Serialization.DataContractSerializer.WriteStartObject().