Terraria: System.Runtime.Serialization.XmlObjectSerializer.WriteEndObject
WriteEndObject() [2/2]
virtual void System.Runtime.Serialization.XmlObjectSerializer.WriteEndObject (XmlWriter writer) inline virtual
Reimplemented in System.Runtime.Serialization.Json.DataContractJsonSerializer, and System.Runtime.Serialization.DataContractSerializer.
Definition at line 76 of file XmlObjectSerializer.cs.
    {
        CheckNull(writer, "writer");
        WriteEndObject(XmlDictionaryWriter.CreateDictionaryWriter(writer));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CheckNull(), System.Xml.XmlDictionaryWriter.CreateDictionaryWriter(), System.Runtime.Serialization.XmlObjectSerializer.WriteEndObject(), and System.writer.