Terraria: System.Runtime.Serialization.XmlSerializableServices.ReadNodes
ReadNodes()
static XmlNode[] System.Runtime.Serialization.XmlSerializableServices.ReadNodes (XmlReader xmlReader) inline static
Definition at line 11 of file XmlSerializableServices.cs.
    {
        if (xmlReader == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("xmlReader");
        }
        XmlDocument xmlDocument = new XmlDocument();
        List<XmlNode> list = new List<XmlNode>();
        if (xmlReader.MoveToFirstAttribute())
        {
            do
            {
                if (IsValidAttribute(xmlReader))
                {
                    XmlNode xmlNode = xmlDocument.ReadNode(xmlReader);
                    if (xmlNode == null)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.UnexpectedEndOfFile));
                    }
                    list.Add(xmlNode);
                }
            }
            while (xmlReader.MoveToNextAttribute());
        }
        xmlReader.MoveToElement();
        if (!xmlReader.IsEmptyElement)
        {
            int depth = xmlReader.Depth;
            xmlReader.Read();
            while (xmlReader.Depth > depth && xmlReader.NodeType != XmlNodeType.EndElement)
            {
                XmlNode xmlNode2 = xmlDocument.ReadNode(xmlReader);
                if (xmlNode2 == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.UnexpectedEndOfFile));
                }
                list.Add(xmlNode2);
            }
        }
        return list.ToArray();
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.XmlSerializableServices.IsValidAttribute(), System.list, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.UnexpectedEndOfFile.
Referenced by System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadIXmlSerializable().