Terraria: System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run
Run()
override void System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run (Task task, bool canInlineContinuationTask) inline sealed package
Definition at line 23 of file SynchronizationContextAwaitTaskContinuation.cs.
    {
        if (canInlineContinuationTask && m_syncContext == SynchronizationContext.Current)
        {
            RunCallback(AwaitTaskContinuation.GetInvokeActionCallback(), m_action, ref Task.t_currentTask);
            return;
        }
        TplEventSource log = TplEventSource.Log;
        if (log.IsEnabled())
        {
            m_continuationId = Task.NewId();
            log.AwaitTaskContinuationScheduled((task.ExecutingTaskScheduler ?? TaskScheduler.Default).Id, task.Id, m_continuationId);
        }
        RunCallback(GetPostActionCallback(), this, ref Task.t_currentTask);
    }
References System.Threading.Tasks.TplEventSource.AwaitTaskContinuationScheduled(), System.Threading.SynchronizationContext.Current, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.AwaitTaskContinuation.GetInvokeActionCallback(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.GetPostActionCallback(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Threading.Tasks.TplEventSource.Log, System.Threading.Tasks.AwaitTaskContinuation.m_action, System.Threading.Tasks.AwaitTaskContinuation.m_continuationId, System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.m_syncContext, System.Threading.Tasks.Task< TResult >.NewId(), System.Threading.Tasks.AwaitTaskContinuation.RunCallback(), System.Threading.Tasks.Task< TResult >.t_currentTask, and System.task.