Terraria: Terraria.GameInput.TriggersSet.GetNavigatorDirections
GetNavigatorDirections()
Vector2 Terraria.GameInput.TriggersSet.GetNavigatorDirections () inline
    {
        bool flag = Main.gameMenu || Main.ingameOptionsWindow || Main.editChest || Main.editSign || ((Main.playerInventory || Main.LocalPlayer.talkNPC != -1) && PlayerInput.CurrentProfile.UsingDpadMovekeys());
        bool value = Up || (flag && MenuUp);
        bool value2 = Right || (flag && MenuRight);
        bool value3 = Down || (flag && MenuDown);
        bool value4 = Left || (flag && MenuLeft);
        return new Vector2(value2.ToInt() - value4.ToInt(), value3.ToInt() - value.ToInt());
    }
References Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.TriggersSet.Down, Terraria.GameInput.TriggersSet.Left, Terraria.GameInput.TriggersSet.MenuDown, Terraria.GameInput.TriggersSet.MenuLeft, Terraria.GameInput.TriggersSet.MenuRight, Terraria.GameInput.TriggersSet.MenuUp, Terraria.GameInput.TriggersSet.Right, Terraria.GameInput.TriggersSet.Up, and Terraria.GameInput.PlayerInputProfile.UsingDpadMovekeys().
Referenced by Terraria.UI.Gamepad.UILinkPointNavigator.ForceMovementCooldown(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), and Terraria.UI.Gamepad.UILinkPointNavigator.Update().