Terraria: System.Xml.XmlWriter.WriteAttributesAsync
WriteAttributesAsync()
virtual async Task System.Xml.XmlWriter.WriteAttributesAsync (XmlReader reader, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, and System.Xml.XmlRawWriter.
Definition at line 737 of file XmlWriter.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        if (reader.NodeType == XmlNodeType.Element || reader.NodeType == XmlNodeType.XmlDeclaration)
        {
            if (reader.MoveToFirstAttribute())
            {
                await WriteAttributesAsync(reader, defattr).ConfigureAwait(continueOnCapturedContext: false);
                reader.MoveToElement();
            }
            return;
        }
        if (reader.NodeType != XmlNodeType.Attribute)
        {
            throw new XmlException(System.SR.Xml_InvalidPosition, string.Empty);
        }
        do
        {
            if (!defattr && reader.IsDefaultInternal)
            {
                continue;
            }
            await WriteStartAttributeAsync(reader.Prefix, reader.LocalName, reader.NamespaceURI).ConfigureAwait(continueOnCapturedContext: false);
            while (reader.ReadAttributeValue())
            {
                if (reader.NodeType == XmlNodeType.EntityReference)
                {
                    await WriteEntityRefAsync(reader.Name).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    await WriteStringAsync(reader.Value).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            await WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
        }
        while (reader.MoveToNextAttribute());
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.XmlReader.IsDefaultInternal, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.Value, System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteEndAttributeAsync(), System.Xml.XmlWriter.WriteEntityRefAsync(), System.Xml.XmlWriter.WriteStartAttributeAsync(), System.Xml.XmlWriter.WriteStringAsync(), System.SR.Xml_InvalidPosition, and System.Xml.XmlException.
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteAttributesAsync(), System.Xml.XmlAsyncCheckWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), and System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader().