Terraria: System.Xml.XmlWriter.Close
Close()
virtual void System.Xml.XmlWriter.Close () inline virtual
Reimplemented in System.Data.DataTextWriter, System.Runtime.Serialization.Json.XmlJsonWriter, System.Runtime.Serialization.XmlSerializableWriter, System.Xml.XmlBaseWriter, System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.XmlDictionaryWriter, System.Xml.Linq.XNodeBuilder, MS.Internal.Xml.Cache.XPathDocumentBuilder, System.Xml.Xsl.Runtime.XmlAttributeCache, System.Xml.Xsl.Runtime.XmlQueryOutput, System.Xml.Xsl.Runtime.XmlRawWriterWrapper, System.Xml.DocumentXmlWriter, System.Xml.QueryOutputWriter, System.Xml.QueryOutputWriterV1, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlAutoDetectWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlEventCache, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 110 of file XmlWriter.cs.
    {
    }
Referenced by System.Data.DataTextWriter.Close(), System.Diagnostics.XmlWriterTraceListener.Close(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.Close(), System.Xml.QueryOutputWriterV1.Close(), System.Xml.XmlAsyncCheckWriter.Close(), System.Xml.XmlWellFormedWriter.Close(), System.Xml.XmlWrappingWriter.Close(), System.Xml.XmlRawWriter.Close(), and System.Xml.XmlWriter.Dispose().