Terraria: System.Xml.XmlWriter.WriteProcessingInstruction
WriteProcessingInstruction() [2/2]
void System.Xml.XmlWriter.WriteProcessingInstruction (string name, string? text) abstract inherited
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone(), System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Data.DataTextWriter.WriteProcessingInstruction(), System.Runtime.Serialization.XmlSerializableWriter.WriteProcessingInstruction(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteProcessingInstruction(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteProcessingInstruction(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteProcessingInstruction(), System.Xml.QueryOutputWriter.WriteProcessingInstruction(), System.Xml.QueryOutputWriterV1.WriteProcessingInstruction(), System.Xml.XmlAsyncCheckWriter.WriteProcessingInstruction(), System.Xml.XmlAutoDetectWriter.WriteProcessingInstruction(), System.Xml.XmlCharCheckingWriter.WriteProcessingInstruction(), System.Xml.XmlWellFormedWriter.WriteProcessingInstruction(), and System.Xml.XmlWrappingWriter.WriteProcessingInstruction().