Terraria: System.Xml.XmlWriter.WriteStartAttribute
WriteStartAttribute() [2/4]
void System.Xml.XmlWriter.WriteStartAttribute (string localName, string? ns) inline inherited
Definition at line 67 of file XmlWriter.cs.
    {
        WriteStartAttribute(null, localName, ns);
    }
References System.Xml.XmlWriter.WriteStartAttribute().
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Xml.Xsl.Runtime.XmlAttributeCache.FlushAttributes(), System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWellFormedWriter.WriteEndAttribute(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWellFormedWriter.WriteStartAttribute(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteStartAttribute(), System.Data.DataTextWriter.WriteStartAttribute(), System.Runtime.Serialization.XmlSerializableWriter.WriteStartAttribute(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartAttribute(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteStartAttribute(), System.Xml.QueryOutputWriter.WriteStartAttribute(), System.Xml.QueryOutputWriterV1.WriteStartAttribute(), System.Xml.XmlAsyncCheckWriter.WriteStartAttribute(), System.Xml.XmlAutoDetectWriter.WriteStartAttribute(), System.Xml.XmlCharCheckingWriter.WriteStartAttribute(), System.Xml.XmlWrappingWriter.WriteStartAttribute(), and System.Runtime.Serialization.XmlWriterDelegator.WriteStartAttribute().