Terraria: System.Xml.XmlWriter.Dispose
Dispose() [1/2]
void System.Xml.XmlWriter.Dispose () inline inherited
Implements System.IDisposable.
Definition at line 437 of file XmlWriter.cs.
    {
        Dispose(disposing: true);
    }
References System.Xml.Dictionary, and System.Xml.XmlWriter.Dispose().
Referenced by System.Xml.XmlDictionaryWriter.XmlWrappedWriter.Close(), System.Xml.XmlWriter.Dispose(), System.Xml.XmlAsyncCheckWriter.Dispose(), System.Xml.XmlWriter.DisposeAsync(), and System.Xml.XmlWriter.DisposeAsyncCore().