Terraria: System.Xml.XmlWriter.WriteEndAttributeAsync
WriteEndAttributeAsync()
virtual Task System.Xml.XmlWriter.WriteEndAttributeAsync () inline package virtual inherited
Reimplemented in System.Xml.XmlBaseWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 633 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteAttributeStringAsyncHelper(), System.Xml.XmlAsyncCheckWriter.WriteEndAttributeAsync(), System.Xml.XmlWrappingWriter.WriteEndAttributeAsync(), System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_NoAdvance(), System.Xml.XmlWellFormedWriter.WriteEndAttributeAsync_SepcialAtt(), and System.Xml.XmlWriter.WriteNodeAsync().