Terraria: System.Xml.XmlWriter.WriteWhitespace
WriteWhitespace() [2/2]
void System.Xml.XmlWriter.WriteWhitespace (string? ws) abstract inherited
Referenced by System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlReader.WriteNodeAsync(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteWhitespace(), System.Data.DataTextWriter.WriteWhitespace(), System.Runtime.Serialization.XmlSerializableWriter.WriteWhitespace(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteWhitespace(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteWhitespace(), System.Xml.QueryOutputWriterV1.WriteWhitespace(), System.Xml.XmlAsyncCheckWriter.WriteWhitespace(), System.Xml.XmlCharCheckingWriter.WriteWhitespace(), System.Xml.XmlWellFormedWriter.WriteWhitespace(), and System.Xml.XmlWrappingWriter.WriteWhitespace().