Terraria: System.Xml.XmlWriter.WriteNodeAsync
WriteNodeAsync() [2/2]
virtual async Task System.Xml.XmlWriter.WriteNodeAsync (XPathNavigator navigator, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckWriter, and System.Xml.XmlRawWriter.
Definition at line 916 of file XmlWriter.cs.
    {
        if (navigator == null)
        {
            throw new ArgumentNullException("navigator");
        }
        int iLevel = 0;
        navigator = navigator.Clone();
        while (true)
        {
            bool mayHaveChildren = false;
            switch (navigator.NodeType)
            {
            case XPathNodeType.Element:
                await WriteStartElementAsync(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI).ConfigureAwait(continueOnCapturedContext: false);
                if (navigator.MoveToFirstAttribute())
                {
                    do
                    {
                        IXmlSchemaInfo schemaInfo = navigator.SchemaInfo;
                        if (defattr || schemaInfo == null || !schemaInfo.IsDefault)
{
                            await WriteStartAttributeAsync(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI).ConfigureAwait(continueOnCapturedContext: false);
                            await WriteStringAsync(navigator.Value).ConfigureAwait(continueOnCapturedContext: false);
                            await WriteEndAttributeAsync().ConfigureAwait(continueOnCapturedContext: false);
                        }
                    }
                    while (navigator.MoveToNextAttribute());
                    navigator.MoveToParent();
                }
                if (navigator.MoveToFirstNamespace(XPathNamespaceScope.Local))
                {
                    await WriteLocalNamespacesAsync(navigator).ConfigureAwait(continueOnCapturedContext: false);
                    navigator.MoveToParent();
                }
                mayHaveChildren = true;
                break;
            case XPathNodeType.Text:
                await WriteStringAsync(navigator.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XPathNodeType.SignificantWhitespace:
            case XPathNodeType.Whitespace:
                await WriteWhitespaceAsync(navigator.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XPathNodeType.Root:
                mayHaveChildren = true;
                break;
            case XPathNodeType.Comment:
                await WriteCommentAsync(navigator.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XPathNodeType.ProcessingInstruction:
                await WriteProcessingInstructionAsync(navigator.LocalName, navigator.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            }
            if (mayHaveChildren)
            {
                if (navigator.MoveToFirstChild())
                {
                    iLevel++;
                    continue;
                }
                if (navigator.NodeType == XPathNodeType.Element)
                {
                    if (!navigator.IsEmptyElement)
                    {
                        await WriteFullEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                    else
                    {
                        await WriteEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
            }
            while (true)
            {
                if (iLevel == 0)
                {
                    return;
                }
                if (navigator.MoveToNext())
                {
                    break;
                }
                iLevel--;
                navigator.MoveToParent();
                if (navigator.NodeType == XPathNodeType.Element)
                {
                    await WriteFullEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
        }
    }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.Schema.IXmlSchemaInfo.IsDefault, System.Xml.XmlWriter.WriteCommentAsync(), System.Xml.XmlWriter.WriteEndAttributeAsync(), System.Xml.XmlWriter.WriteEndElementAsync(), System.Xml.XmlWriter.WriteFullEndElementAsync(), System.Xml.XmlWriter.WriteLocalNamespacesAsync(), System.Xml.XmlWriter.WriteProcessingInstructionAsync(), System.Xml.XmlWriter.WriteStartAttributeAsync(), System.Xml.XmlWriter.WriteStartElementAsync(), System.Xml.XmlWriter.WriteStringAsync(), and System.Xml.XmlWriter.WriteWhitespaceAsync().