Terraria: System.Xml.XmlWriter.WriteFullEndElement
WriteFullEndElement()
void System.Xml.XmlWriter.WriteFullEndElement () abstract
Referenced by System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Data.DataTextWriter.WriteFullEndElement(), System.Runtime.Serialization.XmlSerializableWriter.WriteFullEndElement(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteFullEndElement(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteFullEndElement(), System.Xml.Linq.ElementWriter.WriteFullEndElement(), System.Xml.QueryOutputWriterV1.WriteFullEndElement(), System.Xml.XmlAsyncCheckWriter.WriteFullEndElement(), System.Xml.XmlWellFormedWriter.WriteFullEndElement(), System.Xml.XmlWrappingWriter.WriteFullEndElement(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteFullEndElement(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), and System.Xml.XmlWriter.WriteNode().