Terraria: System.Xml.XmlWriter.WriteSurrogateCharEntityAsync
WriteSurrogateCharEntityAsync()
virtual Task System.Xml.XmlWriter.WriteSurrogateCharEntityAsync (char lowChar, char highChar) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlEncodedRawTextWriterIndent, System.Xml.XmlRawWriter, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlUtf8RawTextWriterIndent, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 673 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlAsyncCheckWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlCharCheckingWriter.WriteSurrogateCharEntityAsync(), System.Xml.XmlWellFormedWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlWrappingWriter.WriteSurrogateCharEntityAsync().