Terraria: System.Xml.XmlWriter.WriteRawAsync
WriteRawAsync() [1/2]
virtual Task System.Xml.XmlWriter.WriteRawAsync (char[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlEncodedRawTextWriterIndent, System.Xml.XmlRawWriter, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlUtf8RawTextWriterIndent, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 683 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), System.Xml.XmlWrappingWriter.WriteRawAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlAsyncCheckWriter.WriteRawAsync(), System.Xml.XmlWellFormedWriter.WriteRawAsync(), and System.Xml.XmlWrappingWriter.WriteRawAsync().