Terraria: System.Xml.XmlWriter.WriteNmTokenAsync
WriteNmTokenAsync()
virtual Task System.Xml.XmlWriter.WriteNmTokenAsync (string name) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, and System.Xml.XmlRawWriter.
Definition at line 708 of file XmlWriter.cs.
    {
        if (name == null || name.Length == 0)
        {
            throw new ArgumentException(System.SR.Xml_EmptyName);
        }
        return WriteStringAsync(XmlConvert.VerifyNMTOKEN(name, ExceptionType.ArgumentException));
    }
References System.Xml.ArgumentException, System.Xml.XmlConvert.VerifyNMTOKEN(), System.Xml.XmlWriter.WriteStringAsync(), and System.SR.Xml_EmptyName.
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteNmTokenAsync(), System.Xml.XmlAsyncCheckWriter.WriteNmTokenAsync(), and System.Xml.XmlCharCheckingWriter.WriteNmTokenAsync().