Terraria: System.Xml.XmlWriter.WriteEntityRef
WriteEntityRef()
void System.Xml.XmlWriter.WriteEntityRef (string name) abstract
Referenced by System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlDictionaryWriter.WriteElementNode(), System.Data.DataTextWriter.WriteEntityRef(), System.Runtime.Serialization.XmlSerializableWriter.WriteEntityRef(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEntityRef(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteEntityRef(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteEntityRef(), System.Xml.QueryOutputWriter.WriteEntityRef(), System.Xml.QueryOutputWriterV1.WriteEntityRef(), System.Xml.XmlAsyncCheckWriter.WriteEntityRef(), System.Xml.XmlAutoDetectWriter.WriteEntityRef(), System.Xml.XmlCharCheckingWriter.WriteEntityRef(), System.Xml.XmlWellFormedWriter.WriteEntityRef(), System.Xml.XmlWrappingWriter.WriteEntityRef(), System.Xml.XmlDictionaryWriter.WriteNode(), and System.Xml.XmlWriter.WriteNode().