Terraria: System.Xml.XmlWriter.WriteEntityRefAsync
WriteEntityRefAsync()
virtual Task System.Xml.XmlWriter.WriteEntityRefAsync (string name) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlEncodedRawTextWriterIndent, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlUtf8RawTextWriterIndent, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 653 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEntityRefAsync(), System.Xml.XmlAsyncCheckWriter.WriteEntityRefAsync(), System.Xml.XmlCharCheckingWriter.WriteEntityRefAsync(), System.Xml.XmlWellFormedWriter.WriteEntityRefAsync(), System.Xml.XmlWrappingWriter.WriteEntityRefAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), and System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader().