Terraria: System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader
WriteNodeAsync_CallAsyncReader()
async Task System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader (XmlReader reader, bool defattr) inline package inherited
Definition at line 854 of file XmlWriter.cs.
    {
        bool canReadChunk = reader.CanReadValueChunk;
        int d = ((reader.NodeType == XmlNodeType.None) ? (-1) : reader.Depth);
        do
        {
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
                await WriteStartElementAsync(reader.Prefix, reader.LocalName, reader.NamespaceURI).ConfigureAwait(continueOnCapturedContext: false);
                await WriteAttributesAsync(reader, defattr).ConfigureAwait(continueOnCapturedContext: false);
                if (reader.IsEmptyElement)
                {
                    await WriteEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            case XmlNodeType.Text:
                if (canReadChunk)
                {
                    if (_writeNodeBuffer == null)
                    {
                        _writeNodeBuffer = new char[1024];
                    }
                    int count;
                    while ((count = await reader.ReadValueChunkAsync(_writeNodeBuffer, 0, 1024).ConfigureAwait(continueOnCapturedContext: false)) > 0)
                    {
                        await WriteCharsAsync(_writeNodeBuffer, 0, count).ConfigureAwait(continueOnCapturedContext: false);
                    }
                }
                else
                {
                    await WriteStringAsync(await reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)).ConfigureAwait(continueOnCapturedContext: false);
                }
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                await WriteWhitespaceAsync(await reader.GetValueAsync().ConfigureAwait(continueOnCapturedContext: false)).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.CDATA:
                await WriteCDataAsync(reader.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.EntityReference:
                await WriteEntityRefAsync(reader.Name).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.XmlDeclaration:
                await WriteProcessingInstructionAsync(reader.Name, reader.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.DocumentType:
                await WriteDocTypeAsync(reader.Name, reader.GetAttribute("PUBLIC"), reader.GetAttribute("SYSTEM"), reader.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.Comment:
                await WriteCommentAsync(reader.Value).ConfigureAwait(continueOnCapturedContext: false);
                break;
            case XmlNodeType.EndElement:
                await WriteFullEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
                break;
            }
        }
        while (await reader.ReadAsync().ConfigureAwait(continueOnCapturedContext: false) && (d < reader.Depth || (d == reader.Depth && reader.NodeType == XmlNodeType.EndElement)));
    }
References System.Xml.XmlWriter._writeNodeBuffer, System.Xml.XmlReader.CanReadValueChunk, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.GetValueAsync(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAsync(), System.Xml.XmlReader.ReadValueChunkAsync(), System.Xml.XmlReader.Value, System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteCDataAsync(), System.Xml.XmlWriter.WriteCharsAsync(), System.Xml.XmlWriter.WriteCommentAsync(), System.Xml.XmlWriter.WriteDocTypeAsync(), System.Xml.XmlWriter.WriteEndElementAsync(), System.Xml.XmlWriter.WriteEntityRefAsync(), System.Xml.XmlWriter.WriteFullEndElementAsync(), System.Xml.XmlWriter.WriteProcessingInstructionAsync(), System.Xml.XmlWriter.WriteStartElementAsync(), System.Xml.XmlWriter.WriteStringAsync(), and System.Xml.XmlWriter.WriteWhitespaceAsync().
Referenced by System.Xml.XmlWriter.WriteNodeAsync().