Terraria: System.Xml.XmlWriter.WriteComment
WriteComment() [2/2]
void System.Xml.XmlWriter.WriteComment (string? text) abstract inherited
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone(), System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Data.DataTextWriter.WriteComment(), System.Runtime.Serialization.XmlSerializableWriter.WriteComment(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteComment(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteComment(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteComment(), System.Xml.QueryOutputWriter.WriteComment(), System.Xml.QueryOutputWriterV1.WriteComment(), System.Xml.XmlAsyncCheckWriter.WriteComment(), System.Xml.XmlAutoDetectWriter.WriteComment(), System.Xml.XmlCharCheckingWriter.WriteComment(), System.Xml.XmlWellFormedWriter.WriteComment(), System.Xml.XmlWrappingWriter.WriteComment(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), and System.Xml.XmlWriter.WriteNode().