Terraria: System.Xml.XmlWriter.LookupPrefix
LookupPrefix()
string? System.Xml.XmlWriter.LookupPrefix (string ns) abstract
Referenced by System.Xml.Serialization.XmlSerializationWriter.GetQualifiedName(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.LookupPrefix(), System.Data.DataTextWriter.LookupPrefix(), System.Runtime.Serialization.XmlSerializableWriter.LookupPrefix(), System.Runtime.Serialization.XmlWriterDelegator.LookupPrefix(), System.Xml.XmlDictionaryAsyncCheckWriter.LookupPrefix(), System.Xml.QueryOutputWriterV1.LookupPrefix(), System.Xml.XmlAsyncCheckWriter.LookupPrefix(), System.Xml.XmlWrappingWriter.LookupPrefix(), System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(), System.Xml.XmlWriter.WriteQualifiedName(), System.Xml.XmlWriter.WriteQualifiedNameAsync(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteXmlnsAttribute(), and System.Xml.XmlDictionaryWriter.WriteXmlnsAttribute().