Terraria: System.Xml.XmlWriter.WriteCData
WriteCData() [2/2]
void System.Xml.XmlWriter.WriteCData (string? text) abstract inherited
Referenced by System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Data.DataTextWriter.WriteCData(), System.Runtime.Serialization.XmlSerializableWriter.WriteCData(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteCData(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteCData(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteCData(), System.Xml.QueryOutputWriterV1.WriteCData(), System.Xml.XmlAsyncCheckWriter.WriteCData(), System.Xml.XmlCharCheckingWriter.WriteCData(), System.Xml.XmlWellFormedWriter.WriteCData(), System.Xml.XmlWrappingWriter.WriteCData(), System.Xml.QueryOutputWriterV1.WriteChars(), System.Xml.XmlDictionaryWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.QueryOutputWriterV1.WriteRaw(), System.Xml.QueryOutputWriterV1.WriteRaw(), System.Xml.QueryOutputWriterV1.WriteString(), and System.Xml.QueryOutputWriterV1.WriteWhitespace().