Terraria: System.Xml.XmlWriter.WriteNode
WriteNode() [2/2]
virtual void System.Xml.XmlWriter.WriteNode (XPathNavigator navigator, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlAsyncCheckWriter, and System.Xml.XmlRawWriter.
Definition at line 319 of file XmlWriter.cs.
    {
        if (navigator == null)
        {
            throw new ArgumentNullException("navigator");
        }
        int num = 0;
        navigator = navigator.Clone();
        while (true)
        {
            bool flag = false;
            switch (navigator.NodeType)
            {
            case XPathNodeType.Element:
                WriteStartElement(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
                if (navigator.MoveToFirstAttribute())
                {
                    do
                    {
                        IXmlSchemaInfo schemaInfo = navigator.SchemaInfo;
                        if (defattr || schemaInfo == null || !schemaInfo.IsDefault)
{
                            WriteStartAttribute(navigator.Prefix, navigator.LocalName, navigator.NamespaceURI);
                            WriteString(navigator.Value);
                            WriteEndAttribute();
                        }
                    }
                    while (navigator.MoveToNextAttribute());
                    navigator.MoveToParent();
                }
                if (navigator.MoveToFirstNamespace(XPathNamespaceScope.Local))
                {
                    WriteLocalNamespaces(navigator);
                    navigator.MoveToParent();
                }
                flag = true;
                break;
            case XPathNodeType.Text:
                WriteString(navigator.Value);
                break;
            case XPathNodeType.SignificantWhitespace:
            case XPathNodeType.Whitespace:
                WriteWhitespace(navigator.Value);
                break;
            case XPathNodeType.Root:
                flag = true;
                break;
            case XPathNodeType.Comment:
                WriteComment(navigator.Value);
                break;
            case XPathNodeType.ProcessingInstruction:
                WriteProcessingInstruction(navigator.LocalName, navigator.Value);
                break;
            }
            if (flag)
            {
                if (navigator.MoveToFirstChild())
                {
                    num++;
                    continue;
                }
                if (navigator.NodeType == XPathNodeType.Element)
                {
                    if (navigator.IsEmptyElement)
                    {
                        WriteEndElement();
                    }
                    else
                    {
                        WriteFullEndElement();
                    }
                }
            }
            while (true)
            {
                if (num == 0)
                {
                    return;
                }
                if (navigator.MoveToNext())
                {
                    break;
                }
                num--;
                navigator.MoveToParent();
                if (navigator.NodeType == XPathNodeType.Element)
                {
                    WriteFullEndElement();
                }
            }
        }
    }
References System.Xml.Dictionary, System.Xml.Schema.IXmlSchemaInfo.IsDefault, System.Xml.XmlWriter.WriteComment(), System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteFullEndElement(), System.Xml.XmlWriter.WriteLocalNamespaces(), System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), and System.Xml.XmlWriter.WriteWhitespace().