Terraria: System.Xml.XmlWriter.WriteQualifiedName
WriteQualifiedName() [2/3]
virtual void System.Xml.XmlWriter.WriteQualifiedName (string localName, string? ns) inline virtual inherited
Definition at line 132 of file XmlWriter.cs.
    {
        if (ns != null && ns.Length > 0)
        {
            string text = LookupPrefix(ns);
            if (text == null)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Xml_UndefNamespace, ns));
            }
            WriteString(text);
            WriteString(":");
        }
        WriteString(localName);
    }
References System.Xml.ArgumentException, System.SR.Format(), System.Xml.XmlWriter.LookupPrefix(), System.text, System.Xml.XmlWriter.WriteString(), and System.SR.Xml_UndefNamespace.
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedNameValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeQualifiedNameValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteQualifiedName(), System.Data.DataTextWriter.WriteQualifiedName(), System.Runtime.Serialization.XmlSerializableWriter.WriteQualifiedName(), System.Runtime.Serialization.XmlWriterDelegator.WriteQualifiedName(), System.Xml.XmlAsyncCheckWriter.WriteQualifiedName(), System.Xml.XmlCharCheckingWriter.WriteQualifiedName(), and System.Runtime.Serialization.XmlWriterDelegator.WriteQualifiedName().