Terraria: System.Xml.XmlWriter.WriteName
WriteName()
virtual void System.Xml.XmlWriter.WriteName (string name) inline virtual inherited
Reimplemented in System.Data.DataTextWriter, System.Runtime.Serialization.XmlSerializableWriter, System.Xml.XmlBaseWriter, System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, and System.Xml.XmlRawWriter.
Definition at line 127 of file XmlWriter.cs.
    {
        WriteString(XmlConvert.VerifyQName(name, ExceptionType.ArgumentException));
    }
References System.Xml.XmlConvert.VerifyQName(), and System.Xml.XmlWriter.WriteString().
Referenced by System.Data.DataTextWriter.WriteName(), System.Runtime.Serialization.XmlSerializableWriter.WriteName(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteName(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteName(), System.Xml.XmlAsyncCheckWriter.WriteName(), and System.Xml.XmlCharCheckingWriter.WriteName().