Terraria: System.Xml.XmlWriter.WriteElementString
WriteElementString() [1/3]
void System.Xml.XmlWriter.WriteElementString (string localName, string? ns, string? value) inline inherited
Definition at line 417 of file XmlWriter.cs.
    {
        WriteStartElement(localName, ns);
        if (value != null && value.Length != 0)
        {
            WriteString(value);
        }
        WriteEndElement();
    }
References System.value, System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteStartElement(), and System.Xml.XmlWriter.WriteString().