Terraria: System.Xml.XmlWriter.WriteAttributes
WriteAttributes()
virtual void System.Xml.XmlWriter.WriteAttributes (XmlReader reader, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.XmlAsyncCheckWriter, and System.Xml.XmlRawWriter.
Definition at line 211 of file XmlWriter.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        if (reader.NodeType == XmlNodeType.Element || reader.NodeType == XmlNodeType.XmlDeclaration)
        {
            if (reader.MoveToFirstAttribute())
            {
                WriteAttributes(reader, defattr);
                reader.MoveToElement();
            }
            return;
        }
        if (reader.NodeType != XmlNodeType.Attribute)
        {
            throw new XmlException(System.SR.Xml_InvalidPosition, string.Empty);
        }
        do
        {
            if (!defattr && reader.IsDefaultInternal)
            {
                continue;
            }
            WriteStartAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
            while (reader.ReadAttributeValue())
            {
                if (reader.NodeType == XmlNodeType.EntityReference)
                {
                    WriteEntityRef(reader.Name);
                }
                else
                {
                    WriteString(reader.Value);
                }
            }
            WriteEndAttribute();
        }
        while (reader.MoveToNextAttribute());
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsDefaultInternal, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToFirstAttribute(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.Value, System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlWriter.WriteEntityRef(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWriter.WriteString(), System.SR.Xml_InvalidPosition, and System.Xml.XmlException.
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteAttributes(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteAttributes(), System.Xml.XmlAsyncCheckWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributes(), and System.Xml.XmlWriter.WriteNode().