Terraria: System.Xml.XmlWriter.WriteNmToken
WriteNmToken()
virtual void System.Xml.XmlWriter.WriteNmToken (string name) inline virtual inherited
Reimplemented in System.Data.DataTextWriter, System.Runtime.Serialization.XmlSerializableWriter, System.Xml.XmlBaseWriter, System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, and System.Xml.XmlRawWriter.
Definition at line 118 of file XmlWriter.cs.
    {
        if (name == null || name.Length == 0)
        {
            throw new ArgumentException(System.SR.Xml_EmptyName);
        }
        WriteString(XmlConvert.VerifyNMTOKEN(name, ExceptionType.ArgumentException));
    }
References System.Xml.ArgumentException, System.Xml.XmlConvert.VerifyNMTOKEN(), System.Xml.XmlWriter.WriteString(), and System.SR.Xml_EmptyName.
Referenced by System.Data.DataTextWriter.WriteNmToken(), System.Runtime.Serialization.XmlSerializableWriter.WriteNmToken(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteNmToken(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteNmToken(), System.Xml.XmlAsyncCheckWriter.WriteNmToken(), and System.Xml.XmlCharCheckingWriter.WriteNmToken().