Terraria: System.Xml.XmlWriter.WriteNode
WriteNode() [1/2]
virtual void System.Xml.XmlWriter.WriteNode (XmlReader reader, bool defattr) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.XmlDictionaryWriter, System.Xml.XmlAsyncCheckWriter, and System.Xml.XmlRawWriter.
Definition at line 253 of file XmlWriter.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        bool canReadValueChunk = reader.CanReadValueChunk;
        int num = ((reader.NodeType == XmlNodeType.None) ? (-1) : reader.Depth);
        do
        {
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
                WriteStartElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                WriteAttributes(reader, defattr);
                if (reader.IsEmptyElement)
                {
                    WriteEndElement();
                }
                break;
            case XmlNodeType.Text:
                if (canReadValueChunk)
                {
                    if (_writeNodeBuffer == null)
                    {
                        _writeNodeBuffer = new char[1024];
                    }
                    int count;
                    while ((count = reader.ReadValueChunk(_writeNodeBuffer, 0, 1024)) > 0)
                    {
                        WriteChars(_writeNodeBuffer, 0, count);
                    }
                }
                else
                {
                    WriteString(reader.Value);
                }
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                WriteWhitespace(reader.Value);
                break;
            case XmlNodeType.CDATA:
                WriteCData(reader.Value);
                break;
            case XmlNodeType.EntityReference:
                WriteEntityRef(reader.Name);
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.XmlDeclaration:
                WriteProcessingInstruction(reader.Name, reader.Value);
                break;
            case XmlNodeType.DocumentType:
                WriteDocType(reader.Name, reader.GetAttribute("PUBLIC"), reader.GetAttribute("SYSTEM"), reader.Value);
                break;
            case XmlNodeType.Comment:
                WriteComment(reader.Value);
                break;
            case XmlNodeType.EndElement:
                WriteFullEndElement();
                break;
            }
        }
        while (reader.Read() && (num < reader.Depth || (num == reader.Depth && reader.NodeType == XmlNodeType.EndElement)));
    }
References System.Xml.XmlWriter._writeNodeBuffer, System.Xml.XmlReader.CanReadValueChunk, System.count, System.Xml.XmlReader.Depth, System.Xml.Dictionary, System.Xml.XmlReader.GetAttribute(), System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.Name, System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadValueChunk(), System.Xml.XmlReader.Value, System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteCData(), System.Xml.XmlWriter.WriteChars(), System.Xml.XmlWriter.WriteComment(), System.Xml.XmlWriter.WriteDocType(), System.Xml.XmlWriter.WriteEndElement(), System.Xml.XmlWriter.WriteEntityRef(), System.Xml.XmlWriter.WriteFullEndElement(), System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), and System.Xml.XmlWriter.WriteWhitespace().
Referenced by System.Diagnostics.XmlWriterTraceListener.WriteData(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteNode(), System.Xml.XmlAsyncCheckWriter.WriteNode(), and System.Xml.XmlAsyncCheckWriter.WriteNode().