Terraria: System.Xml.XmlWriter.WriteEndElement
WriteEndElement()
void System.Xml.XmlWriter.WriteEndElement () abstract
Referenced by System.Data.NewDiffgramGen.GenerateColumn(), System.Data.NewDiffgramGen.GenerateRow(), System.Data.NewDiffgramGen.GenerateTableErrors(), System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Data.NewDiffgramGen.Save(), System.Data.XmlDataTreeWriter.Save(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), System.Xml.Serialization.XmlSerializationWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.XmlDictionaryWriter.WriteArray(), System.Xml.Serialization.XmlSerializationWriter.WriteElement(), System.Xml.XmlDictionaryWriter.WriteElementNode(), System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.XmlWriter.WriteElementString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementString(), System.Xml.XmlWriter.WriteElementString(), System.Xml.XmlDictionaryWriter.WriteElementString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteEmptyTag(), System.Data.DataTextWriter.WriteEndElement(), System.Runtime.Serialization.XmlSerializableWriter.WriteEndElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteEndElement(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEndElement(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteEndElement(), System.Xml.Linq.ElementWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteEndElement(), System.Xml.QueryOutputWriterV1.WriteEndElement(), System.Xml.XmlAsyncCheckWriter.WriteEndElement(), System.Xml.XmlWellFormedWriter.WriteEndElement(), System.Xml.XmlWrappingWriter.WriteEndElement(), System.Xml.Serialization.XmlSerializationWriter.WriteEndElement(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteEndElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteEndElementPrimitive(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagEncoded(), System.Xml.Serialization.XmlSerializationWriter.WriteNullTagLiteral(), System.Xml.Serialization.XmlSerializationWriter.WritePotentiallyReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencedElement(), System.Xml.Serialization.XmlSerializationWriter.WriteReferencingElement(), System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().