Terraria: System.Xml.XmlWriter.WriteCharsAsync
WriteCharsAsync()
virtual Task System.Xml.XmlWriter.WriteCharsAsync (char[] buffer, int index, int count) inline virtual inherited
Reimplemented in System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlCharCheckingWriter, System.Xml.XmlEncodedRawTextWriter, System.Xml.XmlEncodedRawTextWriterIndent, System.Xml.XmlRawWriter, System.Xml.XmlUtf8RawTextWriter, System.Xml.XmlUtf8RawTextWriterIndent, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 678 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteCharsAsync(), System.Xml.XmlAsyncCheckWriter.WriteCharsAsync(), System.Xml.XmlCharCheckingWriter.WriteCharsAsync(), System.Xml.XmlWellFormedWriter.WriteCharsAsync(), System.Xml.XmlWrappingWriter.WriteCharsAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), and System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader().