Terraria: System.Xml.XmlWriter.WriteRaw
WriteRaw() [1/2]
void System.Xml.XmlWriter.WriteRaw (char[] buffer, int index, int count) abstract
Referenced by System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Runtime.Serialization.XmlWriterDelegator.WriteGuid(), System.Data.DataTextWriter.WriteRaw(), System.Runtime.Serialization.XmlSerializableWriter.WriteRaw(), System.Runtime.Serialization.XmlWriterDelegator.WriteRaw(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteRaw(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteRaw(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteRaw(), System.Xml.QueryOutputWriterV1.WriteRaw(), System.Xml.XmlAsyncCheckWriter.WriteRaw(), System.Xml.XmlWellFormedWriter.WriteRaw(), System.Xml.XmlWrappingWriter.WriteRaw(), System.Data.DataTextWriter.WriteRaw(), System.Runtime.Serialization.XmlSerializableWriter.WriteRaw(), System.Runtime.Serialization.XmlWriterDelegator.WriteRaw(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteRaw(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteRaw(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteRaw(), System.Xml.QueryOutputWriterV1.WriteRaw(), System.Xml.XmlAsyncCheckWriter.WriteRaw(), System.Xml.XmlWellFormedWriter.WriteRaw(), System.Xml.XmlWrappingWriter.WriteRaw(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), and System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedLong().