Terraria: System.Xml.XmlWriter.WriteStringAsync
WriteStringAsync()
virtual Task System.Xml.XmlWriter.WriteStringAsync (string? text) inline virtual inherited
Definition at line 668 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlWriter.WriteAttributesAsync(), System.Xml.XmlWriter.WriteAttributeStringAsync(), System.Xml.XmlWriter.WriteAttributeStringAsyncHelper(), System.Xml.XmlRawWriter.WriteCDataAsync(), System.Xml.XmlRawWriter.WriteCharEntityAsync(), System.Xml.XmlRawWriter.WriteCharsAsync(), System.Xml.Linq.ElementWriter.WriteElementAsync(), System.Xml.XmlWriter.WriteElementStringAsync(), System.Xml.XmlWriter.WriteNameAsync(), System.Xml.XmlWriter.WriteNmTokenAsync(), System.Xml.XmlWriter.WriteNodeAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader(), System.Xml.XmlWriter.WriteQualifiedNameAsync(), System.Xml.XmlRawWriter.WriteQualifiedNameAsync(), System.Xml.XmlRawWriter.WriteRawAsync(), System.Xml.XmlRawWriter.WriteRawAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStringAsync(), System.Xml.XmlAsyncCheckWriter.WriteStringAsync(), System.Xml.XmlCharCheckingWriter.WriteStringAsync(), System.Xml.XmlWrappingWriter.WriteStringAsync(), System.Xml.XmlWellFormedWriter.WriteStringAsync_NoAdvanceState(), System.Xml.XmlRawWriter.WriteSurrogateCharEntityAsync(), and System.Xml.XmlRawWriter.WriteWhitespaceAsync().