Terraria: System.Xml.XmlWriter.WriteString
WriteString() [2/2]
void System.Xml.XmlWriter.WriteString (string? text) abstract inherited
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Xml.Xsl.Runtime.XmlAttributeCache.FlushAttributes(), System.Data.NewDiffgramGen.GenerateColumn(), System.Xml.Xsl.Runtime.NavigatorConstructor.GetNavigator(), System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone(), System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Xml.XmlWriter.WriteAttributes(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteAttributeString(), System.Xml.XmlWriter.WriteAttributeString(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeStringValue(), System.Xml.XmlRawWriter.WriteCData(), System.Xml.XmlRawWriter.WriteCharEntity(), System.Xml.XmlRawWriter.WriteChars(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTime(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat(), System.Xml.Linq.ElementWriter.WriteElement(), System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.XmlWriter.WriteElementString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementString(), System.Xml.XmlWriter.WriteElementString(), System.Xml.XmlWriter.WriteName(), System.Xml.XmlWriter.WriteNmToken(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlReader.WriteNodeAsync(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteQName(), System.Xml.XmlWriter.WriteQualifiedName(), System.Xml.XmlRawWriter.WriteQualifiedName(), System.Xml.XmlRawWriter.WriteRaw(), System.Xml.XmlRawWriter.WriteRaw(), System.Data.DataTextWriter.WriteString(), System.Runtime.Serialization.XmlSerializableWriter.WriteString(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteString(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteString(), System.Xml.QueryOutputWriter.WriteString(), System.Xml.QueryOutputWriterV1.WriteString(), System.Xml.XmlAsyncCheckWriter.WriteString(), System.Xml.XmlAutoDetectWriter.WriteString(), System.Xml.XmlCharCheckingWriter.WriteString(), System.Xml.XmlWellFormedWriter.WriteString(), System.Xml.XmlWrappingWriter.WriteString(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.WriteString(), System.Xml.XmlRawWriter.WriteSurrogateCharEntity(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), System.Runtime.Serialization.XmlWriterDelegator.WriteUri(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlRawWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlRawWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlRawWriter.WriteValue(), System.Xml.Serialization.XmlSerializationWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlRawWriter.WriteWhitespace(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().