Terraria: System.Xml.XmlWriter.Create
Create() [3/10]
static XmlWriter System.Xml.XmlWriter.Create (string outputFileName) inline static inherited
Definition at line 468 of file XmlWriter.cs.
    {
        if (outputFileName == null)
        {
            throw new ArgumentNullException("outputFileName");
        }
        FileStream fileStream = new FileStream(outputFileName, FileMode.Create, FileAccess.Write, FileShare.Read);
        try
        {
            XmlWriterSettings settings = new XmlWriterSettings
            {
                CloseOutput = true
            };
            XmlWriter writer = new XmlEncodedRawTextWriter(fileStream, settings);
            return new XmlWellFormedWriter(writer, settings);
        }
        catch
        {
            fileStream.Dispose();
            throw;
        }
    }
References System.Xml.Dictionary, and System.writer.
Referenced by System.Data.SqlTypes.SqlXml.CreateMemoryStreamFromXmlReader(), System.Xml.XmlAutoDetectWriter.CreateWrappedWriter(), System.Xml.Linq.XContainer.CreateWriter(), System.Xml.Serialization.XmlSchemas.Dump(), System.Xml.Linq.XNode.GetXmlString(), System.Xml.Linq.XStreamingElement.GetXmlString(), System.Xml.Xsl.Runtime.XsltFunctions.OuterXml(), System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.Save(), System.Xml.Linq.XElement.Save(), System.Xml.Linq.XStreamingElement.Save(), System.Xml.Linq.XDocument.SaveAsync(), System.Xml.Linq.XElement.SaveAsync(), System.Xml.Linq.XDocument.SaveAsync(), System.Xml.Linq.XElement.SaveAsync(), System.Xml.Serialization.XmlSerializer.Serialize(), System.Xml.Serialization.XmlSerializer.Serialize(), System.Xml.Linq.XAttribute.ToString(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), System.Xml.Xsl.XslCompiledTransform.Transform(), and System.Xml.Xsl.XslCompiledTransform.Transform().