Terraria: System.Xml.XmlWriter.Flush
Flush()
void System.Xml.XmlWriter.Flush () abstract
Referenced by System.Xml.XmlWellFormedWriter.Close(), System.Data.DataTextWriter.Flush(), System.Runtime.Serialization.XmlSerializableWriter.Flush(), System.Runtime.Serialization.XmlWriterDelegator.Flush(), System.Xml.XmlDictionaryAsyncCheckWriter.Flush(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.Flush(), System.Xml.Xsl.Runtime.XmlAttributeCache.Flush(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.Flush(), System.Xml.QueryOutputWriter.Flush(), System.Xml.QueryOutputWriterV1.Flush(), System.Xml.XmlAsyncCheckWriter.Flush(), System.Xml.XmlAutoDetectWriter.Flush(), System.Xml.XmlWellFormedWriter.Flush(), System.Xml.XmlWrappingWriter.Flush(), System.Data.NewDiffgramGen.Save(), System.Data.XmlDataTreeWriter.Save(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), and System.Xml.Xsl.XsltOld.WriterOutput.TheEnd().