Terraria: System.Xml.XmlWriter.WriteStartElement
WriteStartElement() [2/4]
void System.Xml.XmlWriter.WriteStartElement (string localName, string? ns) inline inherited
Definition at line 30 of file XmlWriter.cs.
    {
        WriteStartElement(null, localName, ns);
    }
References System.Xml.XmlWriter.WriteStartElement().
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Data.NewDiffgramGen.GenerateColumn(), System.Data.NewDiffgramGen.GenerateRow(), System.Data.NewDiffgramGen.GenerateTableErrors(), System.Xml.Xsl.XsltOld.NavigatorOutput.RecordDone(), System.Xml.Xsl.XsltOld.WriterOutput.RecordDone(), System.Data.NewDiffgramGen.Save(), System.Data.XmlDataTreeWriter.Save(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), System.Xml.Serialization.XmlSerializationWriter.WriteElement(), System.Xml.Serialization.XmlSerializationWriter.WriteElementQualifiedName(), System.Xml.XmlWriter.WriteElementString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementString(), System.Xml.XmlWriter.WriteElementString(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.Serialization.XmlSerializationWriter.WriteElementStringRaw(), System.Xml.XmlWriter.WriteNode(), System.Xml.XmlWriter.WriteNode(), System.Xml.Serialization.XmlSerializationWriter.WriteSerializable(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.Serialization.XmlSerializationWriter.WriteStartElement(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteStartElement(), System.Data.DataTextWriter.WriteStartElement(), System.Runtime.Serialization.XmlSerializableWriter.WriteStartElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartElement(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteStartElement(), System.Xml.QueryOutputWriter.WriteStartElement(), System.Xml.QueryOutputWriterV1.WriteStartElement(), System.Xml.XmlAsyncCheckWriter.WriteStartElement(), System.Xml.XmlAutoDetectWriter.WriteStartElement(), System.Xml.XmlCharCheckingWriter.WriteStartElement(), System.Xml.XmlWellFormedWriter.WriteStartElement(), System.Xml.XmlWrappingWriter.WriteStartElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartElement(), System.Runtime.Serialization.XmlWriterDelegator.WriteStartElementPrimitive(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), and System.Data.XmlDataTreeWriter.XmlDataRowWriter().