Terraria: System.Xml.XmlWriter.WriteQualifiedNameAsync
WriteQualifiedNameAsync() [2/3]
virtual async Task System.Xml.XmlWriter.WriteQualifiedNameAsync (string localName, string? ns) inline virtual inherited
Definition at line 722 of file XmlWriter.cs.
    {
        if (ns != null && ns.Length > 0)
        {
            string text = LookupPrefix(ns);
            if (text == null)
            {
                throw new ArgumentException(System.SR.Format(System.SR.Xml_UndefNamespace, ns));
            }
            await WriteStringAsync(text).ConfigureAwait(continueOnCapturedContext: false);
            await WriteStringAsync(":").ConfigureAwait(continueOnCapturedContext: false);
        }
        await WriteStringAsync(localName).ConfigureAwait(continueOnCapturedContext: false);
    }
References System.Xml.ArgumentException, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.SR.Format(), System.Xml.XmlWriter.LookupPrefix(), System.text, System.Xml.XmlWriter.WriteStringAsync(), and System.SR.Xml_UndefNamespace.
Referenced by System.Xml.XmlDictionaryAsyncCheckWriter.WriteQualifiedNameAsync(), System.Xml.XmlAsyncCheckWriter.WriteQualifiedNameAsync(), and System.Xml.XmlCharCheckingWriter.WriteQualifiedNameAsync().