Terraria: System.Xml.XmlWriter.WriteValue
WriteValue() [9/10]
virtual void System.Xml.XmlWriter.WriteValue (object value) inline virtual inherited
Reimplemented in System.Runtime.Serialization.Json.XmlJsonWriter, System.Xml.XmlBaseWriter, System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlDictionaryWriter.XmlWrappedWriter, System.Xml.Xsl.Runtime.XmlAttributeCache, System.Xml.Xsl.Runtime.XmlRawWriterWrapper, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlAutoDetectWriter, System.Xml.XmlEventCache, System.Xml.XmlRawWriter, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 147 of file XmlWriter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        WriteString(XmlUntypedConverter.Untyped.ToString(value, null));
    }
References System.Xml.Schema.XmlUntypedConverter.Untyped, System.value, and System.Xml.XmlWriter.WriteString().
Referenced by System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeBoolValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeIntValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteAttributeStringValue(), System.Runtime.Serialization.XmlWriterDelegator.WriteBoolean(), System.Runtime.Serialization.XmlWriterDelegator.WriteChar(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteDateTimeInDefaultFormat(), System.Runtime.Serialization.XmlWriterDelegator.WriteDecimal(), System.Runtime.Serialization.XmlWriterDelegator.WriteDouble(), System.Runtime.Serialization.XmlWriterDelegator.WriteFloat(), System.Runtime.Serialization.XmlWriterDelegator.WriteInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteLong(), System.Runtime.Serialization.XmlWriterDelegator.WriteShort(), System.Runtime.Serialization.XmlWriterDelegator.WriteSignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteString(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedByte(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedInt(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedShort(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), System.Xml.XmlWrappingWriter.WriteValue(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteValue(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteValue(), System.Xml.XmlAsyncCheckWriter.WriteValue(), System.Xml.XmlWellFormedWriter.WriteValue(), and System.Xml.XmlWrappingWriter.WriteValue().