Terraria: System.Xml.XmlWriter.WriteStartDocument
WriteStartDocument() [1/2]
void System.Xml.XmlWriter.WriteStartDocument () abstract
Referenced by System.Xml.QueryOutputWriterV1.QueryOutputWriterV1(), System.Data.XmlTreeGen.SchemaTree(), System.Data.DataTextWriter.WriteStartDocument(), System.Runtime.Serialization.XmlSerializableWriter.WriteStartDocument(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteStartDocument(), System.Xml.Serialization.XmlSerializationWriter.WriteStartDocument(), System.Xml.QueryOutputWriterV1.WriteStartDocument(), System.Xml.XmlAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlWrappingWriter.WriteStartDocument(), System.Data.DataTextWriter.WriteStartDocument(), System.Runtime.Serialization.XmlSerializableWriter.WriteStartDocument(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteStartDocument(), System.Xml.QueryOutputWriterV1.WriteStartDocument(), System.Xml.XmlAsyncCheckWriter.WriteStartDocument(), System.Xml.XmlWrappingWriter.WriteStartDocument(), and System.Xml.XmlWellFormedWriter.WriteStartDocumentImpl().