Terraria: System.Xml.XmlWriter.WriteChars
WriteChars()
void System.Xml.XmlWriter.WriteChars (char[] buffer, int index, int count) abstract
Referenced by System.Data.DataTextWriter.WriteChars(), System.Runtime.Serialization.XmlSerializableWriter.WriteChars(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteChars(), System.Xml.XmlDictionaryWriter.XmlWrappedWriter.WriteChars(), System.Xml.Xsl.Runtime.XmlRawWriterWrapper.WriteChars(), System.Xml.QueryOutputWriterV1.WriteChars(), System.Xml.XmlAsyncCheckWriter.WriteChars(), System.Xml.XmlCharCheckingWriter.WriteChars(), System.Xml.XmlWellFormedWriter.WriteChars(), System.Xml.XmlWrappingWriter.WriteChars(), and System.Xml.XmlWriter.WriteNode().