Terraria: System.Xml.XmlWriter.WriteEndElementAsync
WriteEndElementAsync()
virtual Task System.Xml.XmlWriter.WriteEndElementAsync () inline virtual inherited
Reimplemented in System.Xml.XmlBaseWriter, System.Xml.XmlDictionaryAsyncCheckWriter, System.Xml.XmlAsyncCheckWriter, System.Xml.XmlRawWriter, System.Xml.XmlWellFormedWriter, and System.Xml.XmlWrappingWriter.
Definition at line 601 of file XmlWriter.cs.
    {
        throw new NotImplementedException();
    }
Referenced by System.Xml.XmlWriter.WriteElementStringAsync(), System.Xml.XmlDictionaryAsyncCheckWriter.WriteEndElementAsync(), System.Xml.XmlAsyncCheckWriter.WriteEndElementAsync(), System.Xml.XmlWrappingWriter.WriteEndElementAsync(), System.Xml.Linq.ElementWriter.WriteEndElementAsync(), System.Xml.XmlWellFormedWriter.WriteEndElementAsync_NoAdvanceState(), System.Xml.XmlWriter.WriteNodeAsync(), System.Xml.XmlWriter.WriteNodeAsync_CallAsyncReader(), and System.Xml.XmlWriter.WriteNodeAsync_CallSyncReader().