Terraria: System.Diagnostics.Tracing.IncrementingPollingCounter.WritePayload
WritePayload()
override void System.Diagnostics.Tracing.IncrementingPollingCounter.WritePayload (float intervalSec, int pollingIntervalMillisec) inline package
Definition at line 51 of file IncrementingPollingCounter.cs.
    {
        UpdateMetric();
        lock (this)
        {
            IncrementingCounterPayload incrementingCounterPayload = new IncrementingCounterPayload();
            incrementingCounterPayload.Name = base.Name;
            incrementingCounterPayload.DisplayName = base.DisplayName ?? "";
            incrementingCounterPayload.DisplayRateTimeScale = ((DisplayRateTimeScale == TimeSpan.Zero) ? "" : DisplayRateTimeScale.ToString("c"));
            incrementingCounterPayload.IntervalSec = intervalSec;
            incrementingCounterPayload.Series = $"Interval={pollingIntervalMillisec}";
            incrementingCounterPayload.CounterType = "Sum";
            incrementingCounterPayload.Metadata = GetMetadataString();
            incrementingCounterPayload.Increment = _increment - _prevIncrement;
            incrementingCounterPayload.DisplayUnits = base.DisplayUnits ?? "";
            base.EventSource.Write("EventCounters", new EventSourceOptions
            {
                Level = EventLevel.LogAlways
            }, new IncrementingPollingCounterPayloadType(incrementingCounterPayload));
        }
    }
References System.Diagnostics.Tracing.IncrementingPollingCounter._increment, System.Diagnostics.Tracing.IncrementingPollingCounter._prevIncrement, System.Diagnostics.Tracing.IncrementingPollingCounter.DisplayRateTimeScale, System.Diagnostics.Tracing.DiagnosticCounter.GetMetadataString(), System.TimeSpan.ToString(), System.Diagnostics.Tracing.IncrementingPollingCounter.UpdateMetric(), and System.TimeSpan.Zero.