Terraria: System.Data.DataView.IndexListChanged
IndexListChanged()
virtual void System.Data.DataView.IndexListChanged (object sender, ListChangedEventArgs e) inline protected virtual inherited
Definition at line 1137 of file DataView.cs.
    {
        if (e.ListChangedType != 0)
        {
            OnListChanged(e);
        }
        if (_addNewRow != null && _index.RecordCount == 0)
        {
            FinishAddNew(success: false);
        }
        if (e.ListChangedType == ListChangedType.Reset)
        {
            OnListChanged(e);
        }
    }
References System.Data.DataView._addNewRow, System.Data.DataView._index, System.Data.DataView.FinishAddNew(), System.ComponentModel.ListChangedEventArgs.ListChangedType, System.Data.DataView.OnListChanged(), and System.Data.Index.RecordCount.
Referenced by System.Data.DataView.IndexListChangedInternal().