Terraria: System.Data.DataView.AddNew
AddNew() [1/2]
virtual DataRowView System.Data.DataView.AddNew () inline virtual inherited
Implements System.ComponentModel.IBindingList.
Reimplemented in System.Data.RelatedView.
Definition at line 544 of file DataView.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataView.AddNew|API> {0}", ObjectID);
        try
        {
            CheckOpen();
            if (!AllowNew)
            {
                throw ExceptionBuilder.AddNewNotAllowNull();
            }
            if (_addNewRow != null)
            {
                _rowViewCache[_addNewRow].EndEdit();
            }
            _addNewRow = _table.NewRow();
            DataRowView dataRowView = new DataRowView(this, _addNewRow);
            _rowViewCache.Add(_addNewRow, dataRowView);
            OnListChanged(new ListChangedEventArgs(ListChangedType.ItemAdded, IndexOf(dataRowView)));
            return dataRowView;
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataView._addNewRow, System.Data.DataView._rowViewCache, System.Data.DataView._table, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExceptionBuilder.AddNewNotAllowNull(), System.Data.DataView.AllowNew, System.Data.DataView.CheckOpen(), System.Data.DataView.IndexOf(), System.Data.DataCommonEventSource.Log, System.Data.DataTable.NewRow(), System.Data.DataView.ObjectID, and System.Data.DataView.OnListChanged().
Referenced by System.Data.DataView.Add(), and System.Data.DataView.AddNew().