Terraria: System.Data.DataView.GetRecord
GetRecord()
int System.Data.DataView.GetRecord (int recordIndex) inline private inherited
Definition at line 1100 of file DataView.cs.
    {
        if ((uint)Count <= (uint)recordIndex)
        {
            throw ExceptionBuilder.RowOutOfRange(recordIndex);
        }
        if (recordIndex != _index.RecordCount)
        {
            return _index.GetRecord(recordIndex);
        }
        return _addNewRow.GetDefaultRecord();
    }
References System.Data.DataView._addNewRow, System.Data.DataView._index, System.Data.DataView.Count, System.Data.DataRow.GetDefaultRecord(), System.Data.Index.GetRecord(), System.Data.Index.RecordCount, and System.Data.ExceptionBuilder.RowOutOfRange().
Referenced by System.Data.DataView.GetRow().