Terraria: System.Data.DataView.ResetRowViewCache
ResetRowViewCache()
void System.Data.DataView.ResetRowViewCache () inline package inherited
Definition at line 1274 of file DataView.cs.
    {
        Dictionary<DataRow, DataRowView> dictionary = new Dictionary<DataRow, DataRowView>(CountFromIndex, DataRowReferenceComparer.s_default);
        DataRowView value;
        if (_index != null)
        {
            RBTree<int>.RBTreeEnumerator enumerator = _index.GetEnumerator(0);
            while (enumerator.MoveNext())
            {
                DataRow dataRow = _table._recordManager[enumerator.Current];
                if (!_rowViewCache.TryGetValue(dataRow, out value))
                {
                    value = new DataRowView(this, dataRow);
                }
                dictionary.Add(dataRow, value);
            }
        }
        if (_addNewRow != null)
        {
            _rowViewCache.TryGetValue(_addNewRow, out value);
            dictionary.Add(_addNewRow, value);
        }
        _rowViewCache = dictionary;
    }
References System.Data.DataView._addNewRow, System.Data.DataView._index, System.Data.DataTable._recordManager, System.Data.DataView._rowViewCache, System.Data.DataView._table, System.Data.DataView.CountFromIndex, System.dictionary, System.Data.Index.GetEnumerator(), System.Data.DataView.DataRowReferenceComparer.s_default, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Data.RelatedView.RelatedView(), System.Data.RelatedView.RelatedView(), System.Data.DataView.MaintainDataView(), and System.Data.DataView.UpdateIndex().