Terraria: System.Data.DataView.GetFindIndex
GetFindIndex()
Index System.Data.DataView.GetFindIndex (string column, bool keepIndex) inline package inherited
Definition at line 876 of file DataView.cs.
    {
        if (_findIndexes == null)
        {
            _findIndexes = new Dictionary<string, Index>();
        }
        if (_findIndexes.TryGetValue(column, out var value))
        {
            if (!keepIndex)
            {
                _findIndexes.Remove(column);
                value.RemoveRef();
                if (value.RefCount == 1)
                {
                    value.RemoveRef();
                }
            }
        }
        else if (keepIndex)
        {
            value = _table.GetIndex(column, _recordStates, GetFilter());
            _findIndexes[column] = value;
            value.AddRef();
        }
        return value;
    }
References System.Data.DataView._findIndexes, System.Data.DataView._recordStates, System.Data.DataView._table, System.Data.DataView.GetFilter(), System.Data.DataTable.GetIndex(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Data.DataView.AddIndex(), and System.Data.DataView.RemoveIndex().