Terraria: System.IO.UnmanagedMemoryStream.SetLength
SetLength()
unsafe override void System.IO.UnmanagedMemoryStream.SetLength (long value) inline inherited
Definition at line 455 of file UnmanagedMemoryStream.cs.
    {
        if (value < 0)
        {
            throw new ArgumentOutOfRangeException("value", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (_buffer != null)
        {
            throw new NotSupportedException(SR.NotSupported_UmsSafeBuffer);
        }
        EnsureNotClosed();
        EnsureWriteable();
        if (value > _capacity)
        {
            throw new IOException(SR.IO_FixedCapacity);
        }
        long num = Interlocked.Read(ref _position);
        long num2 = Interlocked.Read(ref _length);
        if (value > num2)
        {
            Buffer.ZeroMemory(_mem + num2, (nuint)(value - num2));
        }
        Interlocked.Exchange(ref _length, value);
        if (num > value)
        {
            Interlocked.Exchange(ref _position, value);
        }
    }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._capacity, System.IO.UnmanagedMemoryStream._length, System.IO.UnmanagedMemoryStream._mem, System.IO.UnmanagedMemoryStream._position, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureWriteable(), System.Threading.Interlocked.Exchange(), System.SR.IO_FixedCapacity, System.SR.NotSupported_UmsSafeBuffer, System.Threading.Interlocked.Read(), System.value, and System.Buffer.ZeroMemory().