Terraria: System.Data.DataView.Find
Find() [3/3]
int IBindingList. System.Data.DataView.Find (PropertyDescriptor property, object key) inline private inherited
Implements System.ComponentModel.IBindingList.
Definition at line 927 of file DataView.cs.
    {
        if (property != null)
        {
            bool flag = false;
            Index value = null;
            try
            {
                if (_findIndexes == null || !_findIndexes.TryGetValue(property.Name, out value))
                {
                    flag = true;
                    value = _table.GetIndex(property.Name, _recordStates, GetFilter());
                    value.AddRef();
                }
                Range range = value.FindRecords(key);
                if (!range.IsNull)
                {
                    return _index.GetIndex(value.GetRecord(range.Min));
                }
            }
            finally
            {
                if (flag && value != null)
                {
                    value.RemoveRef();
                    if (value.RefCount == 1)
                    {
                        value.RemoveRef();
                    }
                }
            }
        }
        return -1;
    }
References System.Data.DataView._findIndexes, System.Data.DataView._index, System.Data.DataView._recordStates, System.Data.DataView._table, System.Data.Index.AddRef(), System.Data.DataView.GetFilter(), System.Data.DataTable.GetIndex(), System.Data.Index.GetIndex(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.