Terraria: System.Data.DataView.MaintainDataView
MaintainDataView()
void System.Data.DataView.MaintainDataView (ListChangedType changedType, DataRow row, bool trackAddRemove) inline package inherited
Definition at line 1165 of file DataView.cs.
    {
        DataRowView value = null;
        switch (changedType)
        {
        case ListChangedType.ItemAdded:
            if (trackAddRemove && _rowViewBuffer.TryGetValue(row, out value))
            {
                bool flag = _rowViewBuffer.Remove(row);
            }
            if (row == _addNewRow)
            {
                int newIndex = IndexOfDataRowView(_rowViewCache[_addNewRow]);
                _addNewRow = null;
                _addNewMoved = new ListChangedEventArgs(ListChangedType.ItemMoved, newIndex, Count - 1);
            }
            else if (!_rowViewCache.ContainsKey(row))
            {
                _rowViewCache.Add(row, value ?? new DataRowView(this, row));
            }
            break;
        case ListChangedType.ItemDeleted:
            if (trackAddRemove)
            {
                _rowViewCache.TryGetValue(row, out value);
                if (value != null)
                {
                    _rowViewBuffer.Add(row, value);
                }
            }
            _rowViewCache.Remove(row);
            break;
        case ListChangedType.Reset:
            ResetRowViewCache();
            break;
        case ListChangedType.ItemMoved:
        case ListChangedType.ItemChanged:
        case ListChangedType.PropertyDescriptorAdded:
        case ListChangedType.PropertyDescriptorDeleted:
        case ListChangedType.PropertyDescriptorChanged:
            break;
        }
    }
References System.Data.DataView._addNewMoved, System.Data.DataView._addNewRow, System.Data.DataView._rowViewBuffer, System.Data.DataView._rowViewCache, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Data.DataView.Count, System.Data.DataView.IndexOfDataRowView(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Data.DataView.ResetRowViewCache(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.