Terraria: System.Data.DataView.ApplySort
ApplySort() [1/2]
void IBindingListView. System.Data.DataView.ApplySort (ListSortDescriptionCollection sorts) inline private inherited
Implements System.ComponentModel.IBindingListView.
Definition at line 973 of file DataView.cs.
    {
        if (sorts == null)
        {
            throw ExceptionBuilder.ArgumentNull("sorts");
        }
        StringBuilder stringBuilder = new StringBuilder();
        bool flag = false;
        foreach (ListSortDescription item in (IEnumerable)sorts)
        {
            if (item == null)
            {
                throw ExceptionBuilder.ArgumentContainsNull("sorts");
            }
            PropertyDescriptor propertyDescriptor = item.PropertyDescriptor;
            if (propertyDescriptor == null)
            {
                throw ExceptionBuilder.ArgumentNull("PropertyDescriptor");
            }
            if (!_table.Columns.Contains(propertyDescriptor.Name))
            {
                throw ExceptionBuilder.ColumnToSortIsOutOfRange(propertyDescriptor.Name);
            }
            ListSortDirection sortDirection = item.SortDirection;
            if (flag)
            {
                stringBuilder.Append(',');
            }
            stringBuilder.Append(CreateSortString(propertyDescriptor, sortDirection));
            if (!flag)
            {
                flag = true;
            }
        }
        Sort = stringBuilder.ToString();
    }
References System.Data.DataView._table, System.Data.ExceptionBuilder.ArgumentContainsNull(), System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataTable.Columns, System.Data.ExceptionBuilder.ColumnToSortIsOutOfRange(), System.Data.DataColumnCollection.Contains(), System.Data.DataView.CreateSortString(), System.item, and System.Data.DataView.Sort.