Terraria: System.Data.DataView.FinishAddNew
FinishAddNew()
void System.Data.DataView.FinishAddNew (bool success) inline package inherited
Definition at line 775 of file DataView.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataView.FinishAddNew|INFO> {0}, success={1}", ObjectID, success);
        DataRow addNewRow = _addNewRow;
        if (success)
        {
            if (DataRowState.Detached == addNewRow.RowState)
            {
                _table.Rows.Add(addNewRow);
            }
            else
            {
                addNewRow.EndEdit();
            }
        }
        if (addNewRow == _addNewRow)
        {
            bool flag = _rowViewCache.Remove(_addNewRow);
            _addNewRow = null;
            if (!success)
            {
                addNewRow.CancelEdit();
            }
            OnListChanged(new ListChangedEventArgs(ListChangedType.ItemDeleted, Count));
        }
    }
References System.Data.DataView._addNewRow, System.Data.DataView._rowViewCache, System.Data.DataView._table, System.Data.DataRowCollection.Add(), System.Data.DataView.Count, System.Data.DataCommonEventSource.Log, System.Data.DataView.ObjectID, System.Data.DataView.OnListChanged(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Data.DataTable.Rows.
Referenced by System.Data.DataRowView.CancelEdit(), System.Data.DataView.Delete(), System.Data.DataRowView.EndEdit(), and System.Data.DataView.IndexListChanged().