Terraria: System.Data.DataView.CopyTo
CopyTo() [1/3]
void System.Data.DataView.CopyTo (Array array, int index) inline inherited
Implements System.Collections.ICollection.
Definition at line 637 of file DataView.cs.
    {
        if (_index != null)
        {
            RBTree<int>.RBTreeEnumerator enumerator = _index.GetEnumerator(0);
            while (enumerator.MoveNext())
            {
                array.SetValue(GetRowView(enumerator.Current), index);
                index = checked(index + 1);
            }
        }
        if (_addNewRow != null)
        {
            array.SetValue(_rowViewCache[_addNewRow], index);
        }
    }
References System.Data.DataView._addNewRow, System.Data.DataView._index, System.Data.DataView._rowViewCache, System.array, System.Data.Index.GetEnumerator(), System.Data.DataView.GetRowView(), and System.index.
Referenced by System.Data.DataView.GetEnumerator().