Terraria: System.Data.DataView.EndInit
EndInit()
void System.Data.DataView.EndInit () inline inherited
Implements System.ComponentModel.ISupportInitialize.
Definition at line 576 of file DataView.cs.
    {
        if (_delayedTable != null && _delayedTable.fInitInProgress)
        {
            _delayedTable._delayedViews.Add(this);
            return;
        }
        _fInitInProgress = false;
        _fEndInitInProgress = true;
        if (_delayedTable != null)
        {
            Table = _delayedTable;
            _delayedTable = null;
        }
        if (_delayedSort != null)
        {
            Sort = _delayedSort;
            _delayedSort = null;
        }
        if (_delayedRowFilter != null)
        {
            RowFilter = _delayedRowFilter;
            _delayedRowFilter = null;
        }
        if (_delayedRecordStates != (DataViewRowState)(-1))
        {
            RowStateFilter = _delayedRecordStates;
            _delayedRecordStates = (DataViewRowState)(-1);
        }
        _fEndInitInProgress = false;
        SetIndex(Sort, RowStateFilter, _rowFilter);
        OnInitialized();
    }
References System.Data.DataView._delayedRecordStates, System.Data.DataView._delayedRowFilter, System.Data.DataView._delayedSort, System.Data.DataView._delayedTable, System.Data.DataTable._delayedViews, System.Data.DataView._fEndInitInProgress, System.Data.DataView._fInitInProgress, System.Data.DataView._rowFilter, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.DataTable.fInitInProgress, System.Data.DataView.OnInitialized(), System.Data.DataView.RowFilter, System.Data.DataView.RowStateFilter, System.Data.DataView.SetIndex(), System.Data.DataView.Sort, and System.Data.DataView.Table.