Terraria: System.Data.DataView.OnListChanged
OnListChanged()
virtual void System.Data.DataView.OnListChanged (ListChangedEventArgs e) inline protected virtual inherited
Definition at line 1209 of file DataView.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataView.OnListChanged|INFO> {0}, ListChangedType={1}", ObjectID, e.ListChangedType);
        try
        {
            DataColumn dataColumn = null;
            string text = null;
            switch (e.ListChangedType)
            {
            case ListChangedType.ItemMoved:
            case ListChangedType.ItemChanged:
                if (0 <= e.NewIndex)
                {
                    DataRow row = GetRow(e.NewIndex);
                    if (row.HasPropertyChanged)
                    {
                        dataColumn = row.LastChangedColumn;
                        text = ((dataColumn != null) ? dataColumn.ColumnName : string.Empty);
                    }
                }
                break;
            }
            if (_onListChanged != null)
            {
                if (dataColumn != null && e.NewIndex == e.OldIndex)
                {
                    ListChangedEventArgs e2 = new ListChangedEventArgs(e.ListChangedType, e.NewIndex, new DataColumnPropertyDescriptor(dataColumn));
                    _onListChanged(this, e2);
                }
                else
                {
                    _onListChanged(this, e);
                }
            }
            if (text != null)
            {
                this[e.NewIndex].RaisePropertyChangedEvent(text);
            }
        }
        catch (Exception e3) when (ADP.IsCatchableExceptionType(e3))
        {
            ExceptionBuilder.TraceExceptionWithoutRethrow(e3);
        }
    }
References System.Data.DataView._onListChanged, System.Data.DataView.GetRow(), System.Data.Common.ADP.IsCatchableExceptionType(), System.ComponentModel.ListChangedEventArgs.ListChangedType, System.Data.DataCommonEventSource.Log, System.ComponentModel.ListChangedEventArgs.NewIndex, System.Data.DataView.ObjectID, System.ComponentModel.ListChangedEventArgs.OldIndex, System.text, and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().
Referenced by System.Data.DataView.AddNew(), System.Data.DataView.ChildRelationCollectionChanged(), System.Data.DataView.ColumnCollectionChanged(), System.Data.DataView.FinishAddNew(), System.Data.DataView.IndexListChanged(), System.Data.DataView.ParentRelationCollectionChanged(), and System.Data.DataView.UpdateIndex().