Terraria: System.Data.DataView.SetDataViewManager
SetDataViewManager()
void System.Data.DataView.SetDataViewManager (DataViewManager dataViewManager) inline package inherited
Definition at line 1299 of file DataView.cs.
    {
        if (_table == null)
        {
            throw ExceptionBuilder.CanNotUse();
        }
        if (_dataViewManager == dataViewManager)
        {
            return;
        }
        if (dataViewManager != null)
        {
            dataViewManager._nViews--;
        }
        _dataViewManager = dataViewManager;
        if (dataViewManager != null)
        {
            dataViewManager._nViews++;
            DataViewSetting dataViewSetting = dataViewManager.DataViewSettings[_table];
            try
            {
                _applyDefaultSort = dataViewSetting.ApplyDefaultSort;
                DataExpression newRowFilter = CreateDataExpressionFromDataViewSettings(dataViewSetting);
                SetIndex(dataViewSetting.Sort, dataViewSetting.RowStateFilter, newRowFilter);
            }
            catch (Exception e) when (ADP.IsCatchableExceptionType(e))
            {
                ExceptionBuilder.TraceExceptionWithoutRethrow(e);
            }
            _locked = true;
        }
        else
        {
            SetIndex("", DataViewRowState.CurrentRows, null);
        }
    }
References System.Data.DataView._applyDefaultSort, System.Data.DataView._dataViewManager, System.Data.DataView._locked, System.Data.DataView._table, System.Data.ExceptionBuilder.CanNotUse(), System.Data.DataView.CreateDataExpressionFromDataViewSettings(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataView.SetIndex(), and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().
Referenced by System.Data.DataRowView.CreateChildView(), and System.Data.DataViewManagerListItemTypeDescriptor.GetDataView().