Terraria: System.Data.DataView.Delete
Delete() [1/2]
void System.Data.DataView.Delete (DataRow row) inline package inherited
Definition at line 676 of file DataView.cs.
    {
        if (row == null)
        {
            return;
        }
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataView.Delete|API> {0}, row={1}", ObjectID, row._objectID);
        try
        {
            CheckOpen();
            if (row == _addNewRow)
            {
                FinishAddNew(success: false);
                return;
            }
            if (!AllowDelete)
            {
                throw ExceptionBuilder.CanNotDelete();
            }
            row.Delete();
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataView._addNewRow, System.Data.DataView.AllowDelete, System.Data.ExceptionBuilder.CanNotDelete(), System.Data.DataView.CheckOpen(), System.Data.DataView.FinishAddNew(), System.Data.DataCommonEventSource.Log, and System.Data.DataView.ObjectID.