Terraria: System.IO.UnmanagedMemoryStream.EnsureNotClosed
EnsureNotClosed()
void System.IO.UnmanagedMemoryStream.EnsureNotClosed () inline private inherited
Definition at line 250 of file UnmanagedMemoryStream.cs.
    {
        if (!_isOpen)
        {
            ThrowHelper.ThrowObjectDisposedException_StreamClosed(null);
        }
    }
References System.IO.UnmanagedMemoryStream._isOpen, and System.ThrowHelper.ThrowObjectDisposedException_StreamClosed().
Referenced by System.IO.UnmanagedMemoryStream.Flush(), System.IO.UnmanagedMemoryStream.ReadByte(), System.IO.UnmanagedMemoryStream.ReadCore(), System.IO.UnmanagedMemoryStream.Seek(), System.IO.UnmanagedMemoryStream.SetLength(), System.IO.UnmanagedMemoryStream.WriteByte(), and System.IO.UnmanagedMemoryStream.WriteCore().