Terraria: System.Data.DataView.DataView
DataView() [4/5]
System.Data.DataView.DataView (DataTable table, string? RowFilter, string? Sort, DataViewRowState RowState) inline
Definition at line 488 of file DataView.cs.
    {
        GC.SuppressFinalize(this);
        DataCommonEventSource.Log.Trace("<ds.DataView.DataView|API> {0}, table={1}, RowFilter='{2}', Sort='{3}', RowState={4}", ObjectID, table?.ObjectID ?? 0, RowFilter, Sort, RowState);
        if (table == null)
        {
            throw ExceptionBuilder.CanNotUse();
        }
        _dvListener = new DataViewListener(this);
        _locked = false;
        _table = table;
        _dvListener.RegisterMetaDataEvents(_table);
        if (((uint)RowState & 0xFFFFFFC1u) != 0)
        {
            throw ExceptionBuilder.RecordStateRange();
        }
        if ((RowState & DataViewRowState.ModifiedOriginal) != 0 && (RowState & DataViewRowState.ModifiedCurrent) != 0)
        {
            throw ExceptionBuilder.SetRowStateFilter();
        }
        if (Sort == null)
        {
            Sort = string.Empty;
        }
        if (RowFilter == null)
        {
            RowFilter = string.Empty;
        }
        DataExpression newRowFilter = new DataExpression(table, RowFilter);
        SetIndex(Sort, RowState, newRowFilter);
    }
References System.Data.DataView._dvListener, System.Data.DataView._locked, System.Data.DataView._table, System.Data.ExceptionBuilder.CanNotUse(), System.Data.DataCommonEventSource.Log, System.Data.DataView.ObjectID, System.Data.ExceptionBuilder.RecordStateRange(), System.Data.DataViewListener.RegisterMetaDataEvents(), System.Data.DataView.RowFilter, System.Data.DataView.SetIndex(), System.Data.ExceptionBuilder.SetRowStateFilter(), System.Data.DataView.Sort, and System.GC.SuppressFinalize().