Terraria: System.Data.DataView.ToTable
ToTable() [4/4]
DataTable System.Data.DataView.ToTable (string? tableName, bool distinct, params string[] columnNames) inline inherited
Definition at line 1472 of file DataView.cs.
    {
        DataCommonEventSource.Log.Trace("<ds.DataView.ToTable|API> {0}, TableName='{1}', distinct={2}", ObjectID, tableName, distinct);
        if (columnNames == null)
        {
            throw ExceptionBuilder.ArgumentNull("columnNames");
        }
        DataTable dataTable = new DataTable();
        dataTable.Locale = _table.Locale;
        dataTable.CaseSensitive = _table.CaseSensitive;
        dataTable.TableName = ((tableName != null) ? tableName : _table.TableName);
        dataTable.Namespace = _table.Namespace;
        dataTable.Prefix = _table.Prefix;
        if (columnNames.Length == 0)
        {
            columnNames = new string[Table.Columns.Count];
            for (int i = 0; i < columnNames.Length; i++)
            {
                columnNames[i] = Table.Columns[i].ColumnName;
            }
        }
        int[] array = new int[columnNames.Length];
        List<object[]> list = new List<object[]>();
        for (int j = 0; j < columnNames.Length; j++)
        {
            DataColumn dataColumn = Table.Columns[columnNames[j]];
            if (dataColumn == null)
            {
                throw ExceptionBuilder.ColumnNotInTheUnderlyingTable(columnNames[j], Table.TableName);
            }
            dataTable.Columns.Add(dataColumn.Clone());
            array[j] = Table.Columns.IndexOf(dataColumn);
        }
        IEnumerator enumerator = GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                DataRowView dataRowView = (DataRowView)enumerator.Current;
                object[] array2 = new object[columnNames.Length];
                for (int k = 0; k < array.Length; k++)
                {
                    array2[k] = dataRowView[array[k]];
                }
                if (!distinct || !RowExist(list, array2))
                {
                    dataTable.Rows.Add(array2);
                    list.Add(array2);
                }
            }
            return dataTable;
        }
        finally
        {
            IDisposable disposable = enumerator as IDisposable;
            if (disposable != null)
            {
                disposable.Dispose();
            }
        }
    }
References System.Data.DataView._table, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Data.ExceptionBuilder.ArgumentNull(), System.array, System.Data.DataTable.CaseSensitive, System.Data.ExceptionBuilder.ColumnNotInTheUnderlyingTable(), System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Data.DataView.GetEnumerator(), System.Data.DataColumnCollection.IndexOf(), System.list, System.Data.DataTable.Locale, System.Data.DataCommonEventSource.Log, System.Data.DataTable.Namespace, System.Data.DataView.ObjectID, System.Data.DataTable.Prefix, System.Data.DataView.RowExist(), System.Data.DataView.Table, and System.Data.DataTable.TableName.