Terraria: System.Data.DataView.DataView
DataView() [5/5]
System.Data.DataView.DataView (DataTable table, Predicate< DataRow > predicate, Comparison< DataRow > comparison, DataViewRowState RowState) inline package
Definition at line 520 of file DataView.cs.
    {
        GC.SuppressFinalize(this);
        DataCommonEventSource.Log.Trace("<ds.DataView.DataView|API> %d#, table=%d, RowState=%d{ds.DataViewRowState}\n", ObjectID, table?.ObjectID ?? 0, (int)RowState);
        if (table == null)
        {
            throw ExceptionBuilder.CanNotUse();
        }
        _dvListener = new DataViewListener(this);
        _locked = false;
        _table = table;
        _dvListener.RegisterMetaDataEvents(table);
        if (((uint)RowState & 0xFFFFFFC1u) != 0)
        {
            throw ExceptionBuilder.RecordStateRange();
        }
        if ((RowState & DataViewRowState.ModifiedOriginal) != 0 && (RowState & DataViewRowState.ModifiedCurrent) != 0)
        {
            throw ExceptionBuilder.SetRowStateFilter();
        }
        _comparison = comparison;
        SetIndex2("", RowState, (predicate != null) ? new RowPredicateFilter(predicate) : null, fireEvent: true);
    }
References System.Data.DataView._comparison, System.Data.DataView._dvListener, System.Data.DataView._locked, System.Data.DataView._table, System.Data.ExceptionBuilder.CanNotUse(), System.comparison, System.Data.DataCommonEventSource.Log, System.Data.DataView.ObjectID, System.Data.ExceptionBuilder.RecordStateRange(), System.Data.DataViewListener.RegisterMetaDataEvents(), System.Data.DataView.SetIndex2(), System.Data.ExceptionBuilder.SetRowStateFilter(), and System.GC.SuppressFinalize().