Terraria: System.Data.DataView.UpdateIndex
UpdateIndex() [3/3]
void System.Data.DataView.UpdateIndex (bool force, bool fireEvent) inline package inherited
Definition at line 1387 of file DataView.cs.
    {
        long scopeId = DataCommonEventSource.Log.EnterScope("<ds.DataView.UpdateIndex|INFO> {0}, force={1}", ObjectID, force);
        try
        {
            if (!(_open != _shouldOpen || force))
            {
                return;
            }
            _open = _shouldOpen;
            Index index = null;
            if (_open && _table != null)
            {
                if (SortComparison != null)
                {
                    index = new Index(_table, SortComparison, _recordStates, GetFilter());
                    index.AddRef();
                }
                else
                {
                    index = _table.GetIndex(Sort, _recordStates, GetFilter());
                }
            }
            if (_index != index)
            {
                if (_index != null)
                {
                    _dvListener.UnregisterListChangedEvent();
                }
                _index = index;
                if (_index != null)
                {
                    _dvListener.RegisterListChangedEvent(_index);
                }
                ResetRowViewCache();
                if (fireEvent)
                {
                    OnListChanged(s_resetEventArgs);
                }
            }
        }
        finally
        {
            DataCommonEventSource.Log.ExitScope(scopeId);
        }
    }
References System.Data.DataView._dvListener, System.Data.DataView._index, System.Data.DataView._open, System.Data.DataView._recordStates, System.Data.DataView._shouldOpen, System.Data.DataView._table, System.Data.DataView.GetFilter(), System.Data.DataTable.GetIndex(), System.index, System.Data.DataCommonEventSource.Log, System.Data.DataView.ObjectID, System.Data.DataView.OnListChanged(), System.Data.DataViewListener.RegisterListChangedEvent(), System.Data.DataView.ResetRowViewCache(), System.Data.DataView.s_resetEventArgs, System.Data.DataView.Sort, System.Data.DataView.SortComparison, and System.Data.DataViewListener.UnregisterListChangedEvent().