Terraria: ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SteelSeriesDeviceGroup
SteelSeriesDeviceGroup()
ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SteelSeriesDeviceGroup (VendorColorProfile colorProfiles, string gameNameIdInAllCaps, string gameDisplayName, IconColor iconColor) inline
Definition at line 45 of file SteelSeriesDeviceGroup.cs.
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Expected O, but got Unknown
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        _gameSenseConnection = new GameSenseConnection
        {
            GameName = gameNameIdInAllCaps,
            GameDisplayName = gameDisplayName,
            IconColor = iconColor
        };
        _colorProfiles = colorProfiles;
        GameSenseConnection gameSenseConnection = _gameSenseConnection;
        gameSenseConnection.OnConnectionBecameActive = (GameSenseConnection.ClientStateEvent)Delegate.Combine(gameSenseConnection.OnConnectionBecameActive, new GameSenseConnection.ClientStateEvent(_gameSenseConnection_OnConnectionBecameActive));
        GameSenseConnection gameSenseConnection2 = _gameSenseConnection;
        gameSenseConnection2.OnConnectionBecameInactive = (GameSenseConnection.ClientStateEvent)Delegate.Combine(gameSenseConnection2.OnConnectionBecameInactive, new GameSenseConnection.ClientStateEvent(_gameSenseConnection_OnConnectionBecameInactive));
        _gameSenseConnection.SetEvents();
    }
References ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._colorProfiles, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._gameSenseConnection, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._gameSenseConnection_OnConnectionBecameActive(), ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup._gameSenseConnection_OnConnectionBecameInactive(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.ClientStateEvent(), System.Delegate.Combine(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SetEvents().