Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource.RunCompletionAction
RunCompletionAction()
void System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.RunCompletionAction (Action< object > completionAction, object completionActionState, bool runAsync) inline private
Definition at line 237 of file DataflowBlock.cs.
        {
            GC.SuppressFinalize(this);
            if (_cancellationState != 0)
            {
                _cancellationRegistration.Dispose();
            }
            if (runAsync)
            {
                System.Threading.Tasks.Task.Factory.StartNew(completionAction, completionActionState, CancellationToken.None, Common.GetCreationOptionsForTask(), TaskScheduler.Default);
            }
            else
            {
                completionAction(completionActionState);
            }
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._cancellationRegistration, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._cancellationState, System.Threading.Tasks.TaskScheduler.Default, System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.CancellationToken.None, and System.GC.SuppressFinalize().
Referenced by System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsAccepted(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsCanceled(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsDeclined(), and System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsFaulted().