Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource.OfferToTarget
OfferToTarget()
void System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.OfferToTarget () inline package
Definition at line 271 of file DataflowBlock.cs.
        {
            try
            {
                bool flag = _cancellationState != 0;
                switch (_target.OfferMessage(Common.SingleMessageHeader, _messageValue, this, flag))
                {
                case DataflowMessageStatus.Accepted:
                    if (!flag)
                    {
                        CompleteAsAccepted(runAsync: false);
                    }
                    break;
                case DataflowMessageStatus.Declined:
                case DataflowMessageStatus.DecliningPermanently:
                    CompleteAsDeclined(runAsync: false);
                    break;
                case DataflowMessageStatus.Postponed:
                case DataflowMessageStatus.NotAvailable:
                    break;
                }
            }
            catch (Exception ex)
            {
                Common.StoreDataflowMessageValueIntoExceptionData(ex, _messageValue);
                CompleteAsFaulted(ex, runAsync: false);
            }
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._cancellationState, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._messageValue, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._target, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsAccepted(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsDeclined(), System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CompleteAsFaulted(), System.Threading.Tasks.Dataflow.ITargetBlock< in TInput >.OfferMessage(), and System.Threading.Tasks.Dataflow.Internal.Common.SingleMessageHeader.