Terraria: System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource.ReleaseReservation
ReleaseReservation()
void ISourceBlock< TOutput >. System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.ReleaseReservation (DataflowMessageHeader messageHeader, ITargetBlock< TOutput > target) inline private
Definition at line 354 of file DataflowBlock.cs.
        {
            if (!messageHeader.IsValid)
            {
                throw new ArgumentException(System.SR.Argument_InvalidMessageHeader, "messageHeader");
            }
            if (target == null)
            {
                throw new ArgumentNullException("target");
            }
            if (messageHeader.Id != 1)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_MessageNotReservedByTarget);
            }
            if (base.Task.IsCompleted)
            {
                return;
            }
            if (_cancellationState != 0)
            {
                if (Interlocked.CompareExchange(ref _cancellationState, 1, 2) != 2)
                {
                    throw new InvalidOperationException(System.SR.InvalidOperation_MessageNotReservedByTarget);
                }
                if (_cancellationToken.IsCancellationRequested)
                {
                    CancellationHandler(new WeakReference<SendAsyncSource<TOutput>>(this));
                }
            }
            OfferToTargetAsync();
        }
References System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._cancellationState, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >._cancellationToken, System.SR.Argument_InvalidMessageHeader, System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.CancellationHandler(), System.Threading.Interlocked.CompareExchange(), System.SR.InvalidOperation_MessageNotReservedByTarget, System.Threading.CancellationToken.IsCancellationRequested, and System.Threading.Tasks.Dataflow.DataflowBlock.SendAsyncSource< TOutput >.OfferToTargetAsync().