Terraria: System.Net.NetEventSource.Log
Log [1/2]
static readonly System Net NetEventSource System.Net.NetEventSource.Log = new System.Net.NetEventSource() static
Definition at line 20 of file NetEventSource.cs.
Referenced by System.Net.Http.CreditManager.CreditManager(), System.Net.HttpListener.DisconnectAsyncResult.DisconnectAsyncResult(), System.Net.FtpDataStream.FtpDataStream(), System.Net.FtpWebRequest.FtpWebRequest(), System.Net.Http.Http2Connection.Http2Connection(), System.Net.Http.Http2Connection.Http2StreamWindowManager.Http2StreamWindowManager(), System.Net.Http.HttpConnection.HttpConnection(), System.Net.Http.HttpConnectionPool.HttpConnectionPool(), System.Net.Http.HttpContent.HttpContent(), System.Net.HttpListenerContext.HttpListenerContext(), System.Net.HttpListenerException.HttpListenerException(), System.Net.HttpListenerException.HttpListenerException(), System.Net.HttpListenerException.HttpListenerException(), System.Net.HttpListenerException.HttpListenerException(), System.Net.HttpListenerRequest.HttpListenerRequest(), System.Net.HttpListenerResponse.HttpListenerResponse(), System.Net.HttpListenerResponse.HttpListenerResponse(), System.Net.Http.HttpMessageHandler.HttpMessageHandler(), System.Net.Http.HttpMessageInvoker.HttpMessageInvoker(), System.Net.HttpRequestStream.HttpRequestStream(), System.Net.HttpResponseStream.HttpResponseStream(), System.Net.HttpResponseStreamAsyncResult.HttpResponseStreamAsyncResult(), System.Net.Http.HttpWindowsProxy.HttpWindowsProxy(), System.Net.LazyAsyncResult.LazyAsyncResult(), System.Net.Mail.MailMessage.MailMessage(), System.Net.Mail.MailMessage.MailMessage(), System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.MsQuicApi(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.MsQuicConnection(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.MsQuicListener(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.MsQuicStream(), System.Net.Http.HttpConnection.RawConnectionStream.RawConnectionStream(), System.Net.Security.SecureChannel.SecureChannel(), System.Net.SecurityPackageInfoClass.SecurityPackageInfoClass(), System.Net.Sockets.Socket.Socket(), System.Net.Sockets.SocketException.SocketException(), System.Net.Security.SslAuthenticationOptions.SslAuthenticationOptions(), System.Net.Security.SslStream.SslStream(), System.Net.Security.SslStreamCertificateContext.SslStreamCertificateContext(), System.Net.Sockets.TcpClient.TcpClient(), System.Net.Sockets.TcpClient.TcpClient(), System.Net.Sockets.TcpClient.TcpClient(), System.Net.Sockets.TcpListener.TcpListener(), System.Net.Sockets.TcpListener.TcpListener(), System.Net.TimerThread.TimerNode.TimerNode(), System.Net.WebSockets.WebSocketBase.WebSocketBase(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.WebSocketHttpListenerDuplexStream(), System.Net.Http.WinInetProxyHelper.WinInetProxyHelper(), System.Net.Http.Http2Connection.Http2Stream.Http2ReadStream.~Http2ReadStream(), System.Net.HttpListener.Abort(), System.Net.FtpWebRequest.Abort(), System.Net.Http.Http2Connection.Abort(), System.Net.Http.Http3Connection.Abort(), System.Net.CommandStream.Abort(), System.Net.Sockets.Socket.Accept(), System.Net.Sockets.SocketPal.Accept(), System.Net.NetEventSource.Accepted(), System.Net.SSPIWrapper.AcceptSecurityContext(), System.Net.SSPIWrapper.AcceptSecurityContext(), System.Net.WebSockets.HttpWebSocket.AcceptWebSocketAsyncCore(), System.Net.Security.SecureChannel.AcquireClientCredentials(), System.Net.SSPIWrapper.AcquireCredentialsHandle(), System.Net.SSPIWrapper.AcquireCredentialsHandle(), System.Net.SSPIWrapper.AcquireCredentialsHandle(), System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(), System.Net.Security.SafeFreeCredentials.AcquireCredentialsHandle(), System.Net.Security.SafeFreeCredentials.AcquireCredentialsHandle(), System.Net.SSPIWrapper.AcquireCredentialsHandle(), System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(), System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(), System.Net.SSPIWrapper.AcquireDefaultCredential(), System.Net.Security.SafeFreeCredentials.AcquireDefaultCredential(), System.Net.Security.SafeFreeCredentials.AcquireDefaultCredential(), System.Net.SSPIWrapper.AcquireDefaultCredential(), System.Net.Security.SecureChannel.AcquireServerCredentials(), System.Net.CredentialCache.Add(), System.Net.ServiceNameStore.Add(), System.Net.CredentialCache.Add(), System.Net.HttpListener.AddChallenge(), System.Net.HttpListenerResponse.AddHeader(), System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(), System.Net.HttpListenerRequestUriBuilder.AddPercentEncodedOctetToRawOctetsList(), System.Net.HttpListener.AddPrefix(), System.Net.HttpListener.AddPrefixCore(), System.Net.NetworkInformation.NetworkChange.AddressChangeListener.AddressChangedCallback(), System.Net.Http.CreditManager.AdjustCredit(), System.Net.Http.Http2Connection.Http2StreamWindowManager.AdjustWindowDynamic(), System.Net.HttpListenerResponse.AppendCookie(), System.Net.HttpListenerResponse.AppendHeader(), System.Net.HttpListenerRequestUriBuilder.AppendUnicodeCodePointValuePercentEncoded(), System.Net.SSPIWrapper.ApplyControlToken(), System.Net.Security.SafeDeleteContext.ApplyControlToken(), System.Net.NetEventSource.Associate(), System.Net.FtpWebRequest.AsyncRequestCallback(), System.Net.FtpWebRequest.AttemptedRecovery(), System.Net.NetEventSource.AuthenticationError(), System.Net.NetEventSource.AuthenticationInfo(), System.Net.HttpListenerRequest.BeginGetClientCertificate(), System.Net.HttpListenerRequest.BeginGetClientCertificateCore(), System.Net.Mail.SmtpTransport.BeginGetConnection(), System.Net.HttpListener.BeginGetContext(), System.Net.FtpWebRequest.BeginGetRequestStream(), System.Net.FtpWebRequest.BeginGetResponse(), System.Net.HttpRequestStream.BeginRead(), System.Net.HttpRequestStream.BeginReadCore(), System.Net.Sockets.Socket.BeginReceiveMessageFrom(), System.Net.Sockets.Socket.BeginSendFile(), System.Net.HttpResponseStream.BeginWrite(), System.Net.HttpResponseStream.BeginWriteCore(), System.Net.Sockets.Socket.Bind(), System.Net.HttpListener.BuildChallenge(), System.Net.FtpControlStream.BuildCommandsList(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingCookedPath(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Net.HttpListenerRequestUriBuilder.BuildRequestUriUsingRawPath(), System.Net.Security.SslSessionsCache.CacheCredential(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.Security.SSPIHandleCache.CacheCredential(), System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.Callback(), System.Net.HttpResponseStreamAsyncResult.Callback(), System.Net.Http.Http2Connection.Http2Stream.Cancel(), System.Net.TimerThread.TimerNode.Cancel(), System.Net.ContextAwareResult.CaptureOrComplete(), System.Net.Http.Http2Connection.ChangeInitialWindowSize(), System.Net.Http.Http2Connection.ChangeMaxConcurrentStreams(), System.Net.Http.Http3Connection.CheckForShutdown(), System.Net.HttpListener.CheckSpn(), System.Net.Http.HttpContent.CheckTaskNotNull(), System.Net.FtpControlStream.CheckValid(), System.Net.Http.HttpConnectionPool.CleanCacheAndDisposeIfUnused(), System.Net.ContextAwareResult.Cleanup(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.State.Cleanup(), System.Net.HttpListener.CleanupV2Config(), System.Net.HttpListener.Close(), System.Net.HttpListenerResponse.Close(), System.Net.Sockets.Socket.Close(), System.Net.HttpListenerResponse.Close(), System.Net.Sockets.Socket.Close(), System.Net.Sockets.SafeSocketHandle.CloseAsIs(), System.Net.WebSockets.WebSocketBase.CloseAsyncCore(), System.Net.FtpDataStream.CloseEx(), System.Net.Sockets.SafeSocketHandle.CloseHandle(), System.Net.HttpListenerSession.CloseRequestQueueHandle(), System.Net.Http.Http2Connection.Http2Stream.Complete(), System.Net.Mail.SmtpClient.Complete(), System.Net.LazyAsyncResult.Complete(), System.Net.ContextAwareResult.Complete(), System.Net.SSPIWrapper.CompleteAuthToken(), System.Net.Security.SafeDeleteContext.CompleteAuthToken(), System.Net.Security.SafeDeleteContext.CompleteAuthToken(), System.Net.SSPIWrapper.CompleteAuthToken(), System.Net.ContextAwareResult.CompleteCallback(), System.Net.Security.SslStream.CompleteHandshake(), System.Net.Http.HttpConnection.CompleteResponse(), System.Net.HttpListenerResponse.ComputeCookies(), System.Net.HttpListenerResponse.ComputeHeaders(), System.Net.HttpResponseStream.ComputeLeftToWrite(), System.Net.Sockets.Socket.Connect(), System.Net.Sockets.Socket.ConnectAsync(), System.Net.NetEventSource.Connected(), System.Net.NetEventSource.ConnectedAsyncDns(), System.Net.Http.HttpConnectionPool.ConstructSslOptions(), System.Net.Http.Headers.HttpHeaders.ContainsNewLine(), System.Net.NetEventSource.ContentNull(), System.Net.CommandStream.ContinueCommandPipeline(), System.Net.CookieContainer.CookieCutter(), System.Net.HttpListenerResponse.CopyFrom(), System.Net.Http.HttpConnection.CopyFromBufferAsync(), System.Net.Security.SslStreamCertificateContext.Create(), System.Net.Http.MultipartContent.CreateContentReadStreamAsyncCore(), System.Net.Security.SecureChannel.CreateFatalHandshakeAlertToken(), System.Net.Security.SecureChannel.CreateShutdownToken(), System.Net.Sockets.SocketPal.CreateSocket(), System.Net.Sockets.SocketPal.CreateSocket(), System.Net.Security.NegotiateStreamPal.Decrypt(), System.Net.Security.SecureChannel.Decrypt(), System.Net.Security.NegotiateStreamPal.DecryptNtlm(), System.Net.HttpListener.DetachRequestQueueFromUrlGroup(), System.Net.Http.HttpConnectionPool.DisableHttp2Connection(), System.Net.Sockets.Socket.Disconnect(), System.Net.Http.Http2Connection.Dispose(), System.Net.Http.HttpConnectionPool.Dispose(), System.Net.HttpListener.Dispose(), System.Net.Sockets.Socket.Dispose(), System.Net.Http.HttpConnection.Dispose(), System.Net.HttpRequestStream.Dispose(), System.Net.HttpResponseStream.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.Dispose(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.Dispose(), System.Net.CommandStream.Dispose(), System.Net.Sockets.Socket.Dispose(), System.Net.Sockets.UdpClient.Dispose(), System.Net.HttpResponseStream.DisposeCore(), System.Net.Http.StreamToStreamCopy.DisposeSource(), System.Net.Sockets.SafeSocketHandle.DoCloseHandle(), System.Net.Sockets.Socket.DoConnect(), System.Net.Http.Http3RequestStream.DrainContentLength0Frames(), System.Net.Http.HttpConnection.HttpContentReadStream.DrainOnDisposeAsync(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.DumpBuffer(), System.Net.HttpListenerRequestUriBuilder.EmptyDecodeAndAppendRawOctetsList(), System.Net.Sockets.Socket.EnableReuseUnicastPort(), System.Net.Security.SecureChannel.Encrypt(), System.Net.Security.NegotiateStreamPal.Encrypt(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Net.Security.SslStreamPal.EncryptMessage(), System.Net.HttpListenerRequest.EndGetClientCertificate(), System.Net.HttpListener.EndGetContext(), System.Net.FtpWebRequest.EndGetRequestStream(), System.Net.FtpWebRequest.EndGetResponse(), System.Net.HttpRequestStream.EndRead(), System.Net.Dns.EndResolve(), System.Net.HttpResponseStream.EndWrite(), System.Net.HttpResponseStream.EndWriteCore(), System.Net.FtpWebRequest.EnsureFtpWebResponse(), System.Net.CertificateValidationPal.EnsureStoreOpened(), System.Net.SSPIWrapper.EnumerateSecurityPackages(), System.Net.SSPIAuthType.EnumerateSecurityPackages(), System.Net.SSPISecureChannelType.EnumerateSecurityPackages(), System.Net.SSPIAuthType.EnumerateSecurityPackages(), System.Net.SSPISecureChannelType.EnumerateSecurityPackages(), System.Net.SSPIWrapper.EnumerateSecurityPackages(), System.Net.CredentialKey.Equals(), System.Net.CredentialHostKey.Equals(), System.Net.NetEventSource.Error(), System.Net.NetEventSource.Error(), System.Net.Http.Http2Connection.ExtendWindow(), System.Net.Http.HttpConnection.FillAsync(), System.Net.Http.Http2Connection.FinalTeardown(), System.Net.Security.SecureChannel.FindCertificateWithPrivateKey(), System.Net.WebSockets.WebSocketBase.FinishOnCloseReceived(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationFailure(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.HttpListenerAsyncEventArgs.FinishOperationSuccess(), System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(), System.Net.FtpWebRequest.FinishRequestStage(), System.Net.TimerThread.TimerNode.Fire(), System.Net.Http.Http2Connection.FlushOutgoingBytesAsync(), System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), System.Net.NegotiationInfoClass.GetAuthenticationPackageName(), System.Net.HttpListener.GetChannelBinding(), System.Net.HttpListener.GetChannelBindingFromTls(), System.Net.HttpListenerRequest.GetClientCertificate(), System.Net.HttpListenerRequest.GetClientCertificateCore(), System.Net.HttpListenerRequest.GetClientCertificateErrorCore(), System.Net.NTAuthentication.GetClientSpecifiedSpn(), System.Net.Mail.SmtpTransport.GetConnection(), System.Net.HttpListener.GetContext(), System.Net.CredentialCache.GetCredential(), System.Net.CredentialCache.GetCredential(), System.Net.Http.AuthenticationHelper.GetDigestTokenForCredential(), System.Net.Security.CertificateHelper.GetEligibleClientCertificate(), System.Net.Mail.SmtpClient.GetFileMailWriter(), System.Net.Dns.GetHostAddresses(), System.Net.Dns.GetHostByAddress(), System.Net.Dns.GetHostByAddress(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntry(), System.Net.Dns.GetHostEntryAsync(), System.Net.Dns.GetHostEntryAsync(), System.Net.Dns.GetHostEntryOrAddressesCore(), System.Net.Dns.GetHostEntryOrAddressesCore(), System.Net.Dns.GetHostEntryOrAddressesCoreAsync(), System.Net.Dns.GetHostName(), System.Net.NameResolutionPal.GetHostName(), System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(), System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(), System.Net.Sockets.Socket.GetIPv6MulticastOpt(), Interop.HttpApi.GetKnownHeader(), System.Net.HttpListenerContext.GetKnownMethod(), System.Net.Sockets.Socket.GetLingerOpt(), System.Net.Sockets.Socket.GetMulticastOpt(), System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(), System.Net.NTAuthentication.GetOutgoingBlob(), System.Net.NTAuthentication.GetOutgoingBlob(), System.Net.Http.WinInetProxyHelper.GetProxyForUrl(), System.Net.Http.Headers.HeaderUtilities.GetQuality(), System.Net.Sockets.Socket.GetRawSocketOption(), System.Net.CertificateValidationPal.GetRemoteCertificate(), System.Net.UnmanagedCertificateContext.GetRemoteCertificatesFromStoreContext(), System.Net.CertificateValidationPal.GetRequestCertificateAuthorities(), System.Net.FtpWebRequest.GetRequestStream(), System.Net.FtpWebRequest.GetResponse(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Sockets.Socket.GetSocketOption(), System.Net.Http.Http3RequestStream.GetStaticQPackHeader(), System.Net.Http.RedirectHandler.GetUriForRedirect(), System.Net.SSPIWrapper.GetVerifyPackageInfo(), System.Net.SSPIWrapper.GetVerifyPackageInfo(), System.Net.HttpListener.HandleAuthentication(), System.Net.HttpListener.DisconnectAsyncResult.HandleDisconnect(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventPeerCertificateReceived(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventPeerSendShutdown(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventRecv(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(), System.Net.Http.HttpClient.HandleFailure(), System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(), System.Net.Http.HttpConnectionPool.HandleHttp11Downgrade(), System.Net.Http.HttpConnectionPool.HandleHttp2ConnectionFailure(), System.Net.Http.Http2Connection.HeartBeat(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.Info(), System.Net.Http.HttpConnection.InitialFillAsync(), System.Net.Mail.SmtpClient.Initialize(), System.Net.NTAuthentication.Initialize(), System.Net.NTAuthentication.Initialize(), System.Net.Http.Http2Connection.Http2Stream.Initialize(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnection(), System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.InitializeConnectionCallback(), System.Net.Http.StreamContent.InitializeContent(), System.Net.Sockets.SocketAsyncEventArgs.InitializeInternals(), System.Net.SSPIWrapper.InitializeSecurityContext(), System.Net.SSPIWrapper.InitializeSecurityContext(), System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable(), System.Net.Sockets.Socket.InternalSetBlocking(), System.Net.Http.HttpConnectionPool.InvalidateHttp2Connection(), System.Net.HttpListener.DisconnectAsyncResult.IOCompleted(), System.Net.HttpRequestStream.HttpRequestStreamAsyncResult.IOCompleted(), System.Net.HttpResponseStreamAsyncResult.IOCompleted(), System.Net.ListenerAsyncResult.IOCompleted(), System.Net.ListenerClientCertAsyncResult.IOCompleted(), System.Net.Sockets.Socket.IOControl(), System.Net.Security.CertificateHelper.IsValidClientCertificate(), System.Net.Sockets.Socket.Listen(), System.Net.Http.HttpContent.LoadIntoBuffer(), System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(), System.Net.Security.SecureChannel.LogCertificateValidation(), System.Net.Http.HttpConnectionBase.LogExceptions(), System.Net.CredentialKey.Match(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(), System.Net.Quic.Implementations.MsQuic.MsQuicListener.NativeCallbackHandler(), System.Net.Security.SecureChannel.NextMessage(), System.Net.WebSockets.WebSocketBase.OnBackgroundTaskException(), System.Net.Http.Http2Connection.RttEstimator.OnDataOrHeadersReceived(), System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http3RequestStream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnHeader(), System.Net.Http.Http2Connection.Http2Stream.OnHeadersComplete(), System.Net.Http.Http2Connection.RttEstimator.OnPingAckReceived(), System.Net.Http.Http2Connection.Http2Stream.OnReset(), System.Net.Http.Http3Connection.OnServerGoAway(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStaticIndexedHeader(), System.Net.Http.Http2Connection.Http2Stream.OnStatus(), System.Net.HttpListenerRequest.ParseCookies(), System.Net.Http.HttpConnection.ParseHeaderNameValue(), System.Net.Http.Headers.HttpHeaders.ParseMultipleRawHeaderValues(), System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(), System.Net.FtpControlStream.PipelineCallback(), System.Net.Sockets.Socket.Poll(), System.Net.Http.HttpConnection.PrepareForReuse(), System.Net.Http.Http2Connection.ProcessAltSvcFrame(), System.Net.Http.Http2Connection.ProcessGoAwayFrame(), System.Net.Http.Http2Connection.ProcessHeadersFrame(), System.Net.Http.Http2Connection.ProcessIncomingFramesAsync(), System.Net.Http.Http2Connection.ProcessOutgoingFramesAsync(), System.Net.Http.Http2Connection.ProcessPingFrame(), System.Net.Http.CookieHelper.ProcessReceivedCookies(), System.Net.Http.Http2Connection.ProcessRstStreamFrame(), System.Net.Http.Http3Connection.ProcessServerStreamAsync(), System.Net.Http.Http2Connection.ProcessWindowUpdateFrame(), System.Net.SSPIWrapper.QueryBlittableContextAttributes< T >(), System.Net.SSPIWrapper.QueryBlittableContextAttributes< T >(), System.Net.SSPIWrapper.QueryBlittableContextAttributes< T >(), System.Net.SSPIWrapper.QueryBlittableContextAttributes< T >(), System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_ISSUER_LIST_EX(), System.Net.SSPIWrapper.QueryContextAttributes_SECPKG_ATTR_REMOTE_CERT_CONTEXT(), System.Net.SSPIWrapper.QueryContextChannelBinding(), System.Net.SSPIWrapper.QueryStringContextAttributes(), System.Net.SSPIWrapper.QueryStringContextAttributes(), System.Net.ListenerAsyncResult.QueueBeginGetContext(), System.Net.FtpControlStream.QueueOrCreateDataConection(), System.Net.HttpRequestStream.Read(), System.Net.Http.HttpConnection.Read(), System.Net.Http.HttpConnection.ReadAsync(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.ReadAsync(), System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >(), System.Net.Http.HttpConnection.ReadBuffered(), System.Net.Http.HttpConnection.ReadBufferedAsyncCore(), System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadChunkFromConnectionBuffer(), System.Net.HttpRequestStream.ReadCore(), System.Net.Http.Http2Connection.ReadFrameAsync(), System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(), System.Net.Http.Http3RequestStream.ReadHeadersAsync(), System.Net.Http.Http3RequestStream.ReadResponseAsync(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.Sockets.Socket.Receive(), System.Net.WebSockets.WebSocketBase.ReceiveAsyncCore(), System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >(), System.Net.CommandStream.ReceiveCommandResponseCallback(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.Sockets.Socket.ReceiveMessageFrom(), System.Net.HttpListenerResponse.Redirect(), System.Net.Http.Http2Connection.RttEstimator.RefreshRtt(), System.Net.Http.HttpConnection.RegisterCancellation(), System.Net.NameResolutionPal.GetAddrInfoExState.RegisterForCancellation(), System.Net.HttpListener.RegisterForDisconnectNotification(), System.Net.Sockets.SocketAsyncEventArgs.RegisterToCancelPendingIO(), System.Net.Sockets.SafeSocketHandle.ReleaseHandle(), System.Net.Http.Http2Connection.ReleaseStream(), System.Net.ServiceNameStore.Remove(), System.Net.CredentialCache.Remove(), System.Net.CredentialCache.Remove(), System.Net.HttpListener.RemovePrefix(), System.Net.Http.Http2Connection.RemoveStream(), System.Net.Quic.Implementations.MsQuic.MsQuicConnection.State.RemoveStream(), System.Net.Http.CreditManager.RequestCreditAsync(), System.Net.Dns.Resolve(), System.Net.Http.HttpConnection.ReturnConnectionToPool(), System.Net.Http.HttpConnectionPool.ReturnHttp11Connection(), System.Net.Http.HttpConnectionPool.ReturnHttp2Connection(), System.Net.Sockets.SocketPal.Select(), System.Net.Sockets.Socket.Send(), System.Net.Sockets.Socket.Send(), System.Net.Mail.SmtpClient.Send(), System.Net.Sockets.Socket.Send(), System.Net.Http.HttpConnectionPoolManager.SendAsync(), System.Net.Http.Http2Connection.SendAsync(), System.Net.Http.RedirectHandler.SendAsync(), System.Net.Mail.SmtpClient.SendAsync(), System.Net.WebSockets.WebSocketBase.SendAsyncCore(), System.Net.Http.HttpConnection.SendAsyncCore(), System.Net.Http.Http2Connection.SendEndStreamAsync(), System.Net.HttpListener.SendError(), System.Net.Sockets.Socket.SendFile(), System.Net.HttpListenerResponse.SendHeaders(), System.Net.Http.Http2Connection.SendHeadersAsync(), System.Net.Http.Http2Connection.SendPingAsync(), System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(), System.Net.Http.HttpConnection.SendRequestContentAsync(), System.Net.Http.HttpConnection.SendRequestContentWithExpect100ContinueAsync(), System.Net.Http.Http2Connection.Http2Stream.SendReset(), System.Net.Http.Http2Connection.SendRstStreamAsync(), System.Net.Http.Http2Connection.SendSettingsAckAsync(), System.Net.Http.Http2Connection.SendStreamDataAsync(), System.Net.Sockets.Socket.SendTo(), System.Net.Http.Http2Connection.SendWindowUpdateAsync(), System.Net.Http.AuthenticationHelper.SendWithAuthAsync(), System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(), System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(), System.Net.HttpListenerResponse.SerializeHeaders(), System.Net.Http.MultipartContent.SerializeToStream(), System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(), System.Net.HttpListenerResponse.SetCookie(), System.Net.FtpWebRequest.SetException(), System.Net.HttpListenerContext.SetIdentity(), System.Net.Sockets.Socket.SetIPv6MulticastOption(), System.Net.Sockets.Socket.SetLingerOption(), System.Net.Sockets.Socket.SetMulticastOption(), System.Net.Sockets.Socket.SetRawSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetSocketOption(), System.Net.Sockets.Socket.SetToConnected(), System.Net.Sockets.Socket.SetToDisconnected(), System.Net.Http.Http2Connection.SetupAsync(), System.Net.HttpListener.SetupV2Config(), System.Net.HttpListener.SetUrlGroupProperty(), System.Net.Http.Http2Connection.Shutdown(), System.Net.Sockets.Socket.Shutdown(), System.Net.Http.Http2Connection.SignalAvailableStreamsWaiter(), System.Net.Http.Http2Connection.SignalShutdownWaiter(), System.Net.HttpListener.Start(), System.Net.HttpListener.Stop(), System.Net.FtpWebRequest.SubmitRequest(), System.Net.HttpRequestStream.SwitchToOpaqueMode(), System.Net.HttpResponseStream.SwitchToOpaqueMode(), System.Net.WebSockets.WebSocketHttpListenerDuplexStream.SwitchToOpaqueMode(), System.Net.FtpWebRequest.SyncRequestCallback(), System.Net.TimerThread.ThreadProc(), System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(), System.Net.FtpWebRequest.TimerCallback(), System.Net.Http.Http2Connection.Trace(), System.Net.Http.Http3Connection.Trace(), System.Net.Http.HttpConnection.Trace(), System.Net.Http.HttpConnectionPool.Trace(), System.Net.Http.RedirectHandler.Trace(), System.Net.Http.RedirectHandler.TraceError(), System.Net.Security.SslSessionsCache.TryCachedCredential(), System.Net.Http.HttpWindowsProxy.TryCreate(), System.Net.Http.AuthenticationHelper.TryGetAuthenticationChallenge(), System.Net.Http.AuthenticationHelper.TryGetValidAuthenticationChallengeForScheme(), System.Net.Http.Headers.ByteArrayHeaderParser.TryParseValue(), System.Net.Http.CreditManager.TryRequestCreditNoLock(), System.Net.Http.AuthenticationHelper.TrySetDigestAuthToken(), System.Net.HttpRequestStream.UpdateAfterRead(), System.Net.HttpResponseStream.UpdateAfterWrite(), System.Net.Sockets.Socket.UpdateStatusAfterSocketError(), System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(), System.Net.NetEventSource.UriBaseAddress(), System.Net.NetEventSource.Verbose(), System.Net.CertificateValidation.Verify(), System.Net.Security.SecureChannel.VerifyRemoteCertificate(), System.Net.HttpListener.DisconnectAsyncResult.WaitCallback(), System.Net.ListenerClientCertAsyncResult.WaitCallback(), System.Net.Http.Http2Connection.Http2Stream.WaitFor100ContinueAsync(), System.Net.LazyAsyncResult.WaitForCompletion(), System.Net.Sockets.Socket.WildcardBindForConnectIfNecessary(), System.Net.HttpResponseStream.Write(), System.Net.Http.Http2Connection.WriteBytes(), System.Net.HttpResponseStream.WriteCore(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.NetEventSource.WriteEvent(), System.Net.Http.Http2Connection.WriteHeaderCollection(), System.Net.Http.Http2Connection.WriteHeaders(), System.Net.Http.Http2Connection.WriteIndexedHeader(), System.Net.Http.Http2Connection.WriteIndexedHeader(), System.Net.Http.Http2Connection.WriteLiteralHeader(), System.Net.Http.Http2Connection.WriteLiteralHeaderValue(), System.Net.Http.Http2Connection.WriteLiteralHeaderValues(), System.Net.Http.HttpConnection.WriteToStream(), and System.Net.Http.HttpConnection.WriteToStreamAsync().