Terraria: System.Net.NetEventSource.SentFrame
SentFrame() [1/2]
void System.Net.NetEventSource.SentFrame (SslStream sslStream, ReadOnlySpan< byte > frame) inline
Definition at line 397 of file NetEventSource.cs.
    {
        if (IsEnabled())
        {
            TlsFrameHelper.TlsFrameInfo info = default(TlsFrameHelper.TlsFrameInfo);
            bool flag = TlsFrameHelper.TryGetFrameInfo(frame, ref info);
            SentFrame(IdOf(sslStream), info.ToString(), flag ? 1 : 0);
        }
    }
References System.Net.NetEventSource.IdOf(), System.info, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Net.NetEventSource.SentFrame(), and System.Net.Security.TlsFrameHelper.TryGetFrameInfo().
Referenced by System.Net.NetEventSource.SentFrame().