Terraria: System.Net.NetEventSource.WriteEvent
WriteEvent() [6/45]
unsafe void System.Net.NetEventSource.WriteEvent (int eventId, int arg1, int arg2, int arg3, string arg4, string arg5) inline private
Definition at line 90 of file NetEventSource.cs.
    {
        //The blocks IL_0046 are reachable both inside and outside the pinned region starting at IL_0043. ILSpy has duplicated these blocks in order to place them both within and outside the `fixed` statement.
        if (!IsEnabled())
        {
            return;
        }
        if (arg4 == null)
        {
            arg4 = "";
        }
        if (arg5 == null)
        {
            arg5 = "";
        }
        fixed (char* ptr3 = arg4)
        {
            char* intPtr;
            EventData* intPtr2;
            nint num;
            nint num2;
            nint num3;
            nint num4;
            if (arg5 == null)
            {
                char* ptr;
                intPtr = (ptr = null);
                EventData* ptr2 = stackalloc EventData[5];
                intPtr2 = ptr2;
                *intPtr2 = new EventData
                {
                    DataPointer = (IntPtr)(&arg1),
                    Size = 4
                };
                num = (nint)(ptr2 + 1);
                *(EventData*)num = new EventData
                {
                    DataPointer = (IntPtr)(&arg2),
                    Size = 4
                };
                num2 = (nint)(ptr2 + 2);
                *(EventData*)num2 = new EventData
                {
                    DataPointer = (IntPtr)(&arg3),
                    Size = 4
                };
                num3 = (nint)(ptr2 + 3);
                *(EventData*)num3 = new EventData
                {
                    DataPointer = (IntPtr)ptr3,
                    Size = (arg4.Length + 1) * 2
                };
                num4 = (nint)(ptr2 + 4);
                *(EventData*)num4 = new EventData
                {
                    DataPointer = (IntPtr)ptr,
                    Size = (arg5.Length + 1) * 2
                };
                WriteEventCore(eventId, 5, ptr2);
                return;
            }
            fixed (char* ptr4 = &arg5.GetPinnableReference())
            {
                char* ptr;
                intPtr = (ptr = ptr4);
                EventData* ptr2 = stackalloc EventData[5];
                intPtr2 = ptr2;
                *intPtr2 = new EventData
                {
                    DataPointer = (IntPtr)(&arg1),
                    Size = 4
                };
                num = (nint)(ptr2 + 1);
                *(EventData*)num = new EventData
                {
                    DataPointer = (IntPtr)(&arg2),
                    Size = 4
                };
                num2 = (nint)(ptr2 + 2);
                *(EventData*)num2 = new EventData
                {
                    DataPointer = (IntPtr)(&arg3),
                    Size = 4
                };
                num3 = (nint)(ptr2 + 3);
                *(EventData*)num3 = new EventData
                {
                    DataPointer = (IntPtr)ptr3,
                    Size = (arg4.Length + 1) * 2
                };
                num4 = (nint)(ptr2 + 4);
                *(EventData*)num4 = new EventData
                {
                    DataPointer = (IntPtr)ptr,
                    Size = (arg5.Length + 1) * 2
                };
                WriteEventCore(eventId, 5, ptr2);
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.Diagnostics.Tracing.EventSource.WriteEventCore().
Referenced by System.Net.NetEventSource.Accepted(), System.Net.NetEventSource.AcceptSecurityContext(), System.Net.NetEventSource.AcquireCredentialsHandle(), System.Net.NetEventSource.AcquireDefaultCredential(), System.Net.NetEventSource.Associate(), System.Net.NetEventSource.AttemptingRestartUsingCert(), System.Net.NetEventSource.AuthenticationError(), System.Net.NetEventSource.AuthenticationInfo(), System.Net.NetEventSource.CertificateFromDelegate(), System.Net.NetEventSource.CertIsType2(), System.Net.NetEventSource.CertsAfterFiltering(), System.Net.NetEventSource.Connected(), System.Net.NetEventSource.ConnectedAsyncDns(), System.Net.NetEventSource.ContentNull(), System.Net.NetEventSource.DumpBuffer(), System.Net.NetEventSource.EnumerateSecurityPackages(), System.Net.NetEventSource.ErrorMessage(), System.Net.NetEventSource.FindingMatchingCerts(), System.Net.NetEventSource.FoundCertInStore(), System.Net.NetEventSource.HandlerMessage(), System.Net.NetEventSource.HandlerMessageError(), System.Net.NetEventSource.HeadersInvalidValue(), System.Net.NetEventSource.Info(), System.Net.NetEventSource.InitializeSecurityContext(), System.Net.NetEventSource.LocatingPrivateKey(), System.Net.NetEventSource.LookForMatchingCerts(), System.Net.NetEventSource.NoDelegateButClientCert(), System.Net.NetEventSource.NoDelegateNoClientCert(), System.Net.NetEventSource.NoIssuersTryAllCerts(), System.Net.NetEventSource.NotFoundCertInStore(), System.Net.NetEventSource.OperationReturnedSomething(), System.Net.NetEventSource.ReceivedFrame(), System.Net.NetEventSource.RemoteCertDeclaredValid(), System.Net.NetEventSource.RemoteCertHasNoErrors(), System.Net.NetEventSource.RemoteCertificate(), System.Net.NetEventSource.RemoteCertificateError(), System.Net.NetEventSource.RemoteCertUserDeclaredInvalid(), System.Net.NetEventSource.SecureChannelCtor(), System.Net.NetEventSource.SecurityContextInputBuffers(), System.Net.NetEventSource.SelectedCert(), System.Net.NetEventSource.SentFrame(), System.Net.NetEventSource.SslStreamCtor(), System.Net.NetEventSource.SspiPackageNotFound(), System.Net.NetEventSource.SspiSelectedCipherSuite(), System.Net.NetEventSource.UriBaseAddress(), and System.Net.NetEventSource.UsingCachedCredential().