Terraria: CrashWatcher.Inititialize
Inititialize()
static void CrashWatcher.Inititialize () inline static
     {
         Console.WriteLine("Error Logging Enabled.");
         AppDomain.CurrentDomain.FirstChanceException += delegate(object sender, FirstChanceExceptionEventArgs exceptionArgs)
         {
             if (LogAllExceptions && 0 == 0)
             {
                 string text2 = PrintException(exceptionArgs.Exception);
                 Console.Write(string.Concat("================\r\n" + $"{DateTime.Now}: First-Chance Exception\r\nThread: {Thread.CurrentThread.ManagedThreadId} [{Thread.CurrentThread.Name}]\r\nCulture: {Thread.CurrentThread.CurrentCulture.Name}\r\nException: {text2}\r\n", "================\r\n\r\n"));
             }
         };
         AppDomain.CurrentDomain.UnhandledException += delegate(object sender, UnhandledExceptionEventArgs exceptionArgs)
         {
             string text = PrintException((Exception)exceptionArgs.ExceptionObject);
             Console.Write(string.Concat("================\r\n" + $"{DateTime.Now}: Unhandled Exception\r\nThread: {Thread.CurrentThread.ManagedThreadId} [{Thread.CurrentThread.Name}]\r\nCulture: {Thread.CurrentThread.CurrentCulture.Name}\r\nException: {text}\r\n", "================\r\n"));
             if (DumpOnCrash)
             {
                 CrashDump.WriteException(CrashDumpOptions, DumpPath);
             }
         };
     }
References CrashDumpOptions, DumpOnCrash, DumpPath, LogAllExceptions, PrintException(), and CrashDump.WriteException().
Referenced by Program.SetupLogging().