Terraria: System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin
ParallelQueryBegin() [1/2]
void System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin (int queryId) inline package
Definition at line 34 of file PlinqEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Informational, EventKeywords.All))
        {
            int valueOrDefault = Task.CurrentId.GetValueOrDefault();
            ParallelQueryBegin(s_defaultSchedulerId, valueOrDefault, queryId);
        }
    }
References System.Threading.Tasks.Task< TResult >.CurrentId, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin(), and System.Linq.Parallel.PlinqEtwProvider.s_defaultSchedulerId.
Referenced by System.Linq.Parallel.PlinqEtwProvider.ParallelQueryBegin().