Terraria: System.Data.XMLSchema.GenUniqueColumnName
GenUniqueColumnName()
static string System.Data.XMLSchema.GenUniqueColumnName (string proposedName, DataTable table) inline static package inherited
Definition at line 97 of file XMLSchema.cs.
    {
        if (table.Columns.IndexOf(proposedName) >= 0)
        {
            for (int i = 0; i <= table.Columns.Count; i++)
            {
                string text = proposedName + "_" + i.ToString(CultureInfo.InvariantCulture);
                if (table.Columns.IndexOf(text) < 0)
                {
                    return text;
                }
            }
        }
        return proposedName;
    }
References System.Data.DataTable.Columns, System.Data.InternalDataCollectionBase.Count, System.Xml.Dictionary, System.Data.DataColumnCollection.IndexOf(), System.Globalization.CultureInfo.InvariantCulture, and System.text.
Referenced by System.Data.DataTable.AddForeignKey(), System.Data.DataTable.AddUniqueKey(), and System.Data.XDRSchema.HandleColumn().