Terraria: System.Data.XMLSchema.FEqualIdentity
FEqualIdentity()
static bool System.Data.XMLSchema.FEqualIdentity (XmlNode node, string name, string ns) inline static package inherited
Definition at line 68 of file XMLSchema.cs.
    {
        if (node != null && node.LocalName == name && node.NamespaceURI == ns)
        {
            return true;
        }
        return false;
    }
References System.Xml.Dictionary.
Referenced by System.Data.XDRSchema.FindTypeNode(), System.Data.XmlTreeGen.FindTypeNode(), System.Data.XDRSchema.GetInstanceName(), System.Data.XDRSchema.HandleColumn(), System.Data.XSDSchema.HandleRelations(), System.Data.XDRSchema.HandleTypeNode(), System.Data.XDRSchema.IsXDRField(), and System.Data.XDRSchema.LoadSchema().