Terraria: System.Data.XMLSchema.SetProperties
SetProperties() [2/2]
static void System.Data.XMLSchema.SetProperties (object instance, XmlAttributeCollection attrs) inline static package inherited
Definition at line 18 of file XMLSchema.cs.
    {
        for (int i = 0; i < attrs.Count; i++)
        {
            if (!(attrs[i].NamespaceURI == "urn:schemas-microsoft-com:xml-msdata"))
            {
                continue;
            }
            string localName = attrs[i].LocalName;
            string value = attrs[i].Value;
            switch (localName)
            {
            case "Expression":
                if (instance is DataColumn)
                {
                    continue;
                }
                break;
            case "DefaultValue":
            case "RemotingFormat":
                continue;
            }
            PropertyDescriptor propertyDescriptor = TypeDescriptor.GetProperties(instance)[localName];
            if (propertyDescriptor == null)
            {
                continue;
            }
            Type propertyType = propertyDescriptor.PropertyType;
            TypeConverter converter = GetConverter(propertyType);
            object value2;
            if (converter.CanConvertFrom(typeof(string)))
            {
                value2 = converter.ConvertFromInvariantString(value);
            }
            else if (propertyType == typeof(Type))
            {
                value2 = DataStorage.GetType(value);
            }
            else
            {
                if (!(propertyType == typeof(CultureInfo)))
                {
                    throw ExceptionBuilder.CannotConvert(value, propertyType.FullName);
                }
                value2 = new CultureInfo(value);
            }
            propertyDescriptor.SetValue(instance, value2);
        }
    }
References System.Data.ExceptionBuilder.CannotConvert(), System.converter, System.Xml.Dictionary, System.Data.XMLSchema.GetConverter(), System.ComponentModel.TypeDescriptor.GetProperties(), System.Data.Common.DataStorage.GetType(), and System.value.
Referenced by System.Data.XDRSchema.HandleColumn(), System.Data.XDRSchema.InstantiateSimpleTable(), and System.Data.XDRSchema.InstantiateTable().