Terraria: System.Reflection.Metadata.GuidHandle.FromIndex
FromIndex()
static GuidHandle System.Reflection.Metadata.GuidHandle.FromIndex (int heapIndex) inline static package
Definition at line 18 of file GuidHandle.cs.
    {
        return new GuidHandle(heapIndex);
    }
References System.Reflection.Metadata.GuidHandle.GuidHandle().
Referenced by System.Reflection.Metadata.Ecma335.ModuleTableReader.GetEncBaseId(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetEncId(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetHashAlgorithm(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.GetKind(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetLanguage(), System.Reflection.Metadata.Ecma335.ModuleTableReader.GetMvid(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetNewGuidHandle(), and System.Reflection.Metadata.Ecma335.MetadataTokens.GuidHandle().