Terraria: System.Reflection.Metadata.ImportDefinitionCollection.Enumerator.MoveNext
MoveNext()
bool System.Reflection.Metadata.ImportDefinitionCollection.Enumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 26 of file ImportDefinitionCollection.cs.
        {
            if (_reader.RemainingBytes == 0)
            {
                return false;
            }
            ImportDefinitionKind importDefinitionKind = (ImportDefinitionKind)_reader.ReadByte();
            switch (importDefinitionKind)
            {
            case ImportDefinitionKind.ImportType:
            {
                Handle typeOrNamespace = _reader.ReadTypeHandle();
                _current = new ImportDefinition(importDefinitionKind, default(BlobHandle), default(AssemblyReferenceHandle), typeOrNamespace);
                break;
            }
            case ImportDefinitionKind.ImportNamespace:
            {
                Handle typeOrNamespace = MetadataTokens.BlobHandle(_reader.ReadCompressedInteger());
                _current = new ImportDefinition(importDefinitionKind, default(BlobHandle), default(AssemblyReferenceHandle), typeOrNamespace);
                break;
            }
            case ImportDefinitionKind.ImportAssemblyNamespace:
            {
                AssemblyReferenceHandle assembly = MetadataTokens.AssemblyReferenceHandle(_reader.ReadCompressedInteger());
                Handle typeOrNamespace = MetadataTokens.BlobHandle(_reader.ReadCompressedInteger());
                _current = new ImportDefinition(importDefinitionKind, default(BlobHandle), assembly, typeOrNamespace);
                break;
            }
            case ImportDefinitionKind.ImportAssemblyReferenceAlias:
                _current = new ImportDefinition(importDefinitionKind, MetadataTokens.BlobHandle(_reader.ReadCompressedInteger()));
                break;
            case ImportDefinitionKind.AliasAssemblyReference:
                _current = new ImportDefinition(importDefinitionKind, MetadataTokens.BlobHandle(_reader.ReadCompressedInteger()), MetadataTokens.AssemblyReferenceHandle(_reader.ReadCompressedInteger()));
                break;
            case ImportDefinitionKind.AliasType:
            {
                BlobHandle alias2 = MetadataTokens.BlobHandle(_reader.ReadCompressedInteger());
                Handle typeOrNamespace = _reader.ReadTypeHandle();
                _current = new ImportDefinition(importDefinitionKind, alias2, default(AssemblyReferenceHandle), typeOrNamespace);
                break;
            }
            case ImportDefinitionKind.ImportXmlNamespace:
            case ImportDefinitionKind.AliasNamespace:
            {
                BlobHandle alias = MetadataTokens.BlobHandle(_reader.ReadCompressedInteger());
                Handle typeOrNamespace = MetadataTokens.BlobHandle(_reader.ReadCompressedInteger());
                _current = new ImportDefinition(importDefinitionKind, alias, default(AssemblyReferenceHandle), typeOrNamespace);
                break;
            }
            case ImportDefinitionKind.AliasAssemblyNamespace:
                _current = new ImportDefinition(importDefinitionKind, MetadataTokens.BlobHandle(_reader.ReadCompressedInteger()), MetadataTokens.AssemblyReferenceHandle(_reader.ReadCompressedInteger()), MetadataTokens.BlobHandle(_reader.ReadCompressedInteger()));
                break;
            default:
                throw new BadImageFormatException(System.SR.Format(System.SR.InvalidImportDefinitionKind, importDefinitionKind));
            }
            return true;
        }
References System.Reflection.Metadata.ImportDefinitionCollection.Enumerator._current, System.Reflection.Metadata.ImportDefinitionCollection.Enumerator._reader, System.Reflection.Metadata.Ecma335.MetadataTokens.AssemblyReferenceHandle(), System.Reflection.Metadata.Ecma335.MetadataTokens.BlobHandle(), System.SR.Format(), System.SR.InvalidImportDefinitionKind, System.Reflection.Metadata.BlobReader.ReadByte(), System.Reflection.Metadata.BlobReader.ReadCompressedInteger(), System.Reflection.Metadata.BlobReader.ReadTypeHandle(), and System.Reflection.Metadata.BlobReader.RemainingBytes.