Terraria: System.Data.DataTableReaderListener.SubscribeEvents
SubscribeEvents()
void System.Data.DataTableReaderListener.SubscribeEvents () inline private
Definition at line 47 of file DataTableReaderListener.cs.
    {
        if (_currentDataTable != null && !_isSubscribed)
        {
            _currentDataTable.Columns.ColumnPropertyChanged += SchemaChanged;
            _currentDataTable.Columns.CollectionChanged += SchemaChanged;
            _currentDataTable.RowChanged += DataChanged;
            _currentDataTable.RowDeleted += DataChanged;
            _currentDataTable.TableCleared += DataTableCleared;
            _isSubscribed = true;
        }
    }
References System.Data.DataTableReaderListener._currentDataTable, System.Data.DataTableReaderListener._isSubscribed, System.Data.DataTableReaderListener.DataChanged(), System.Data.DataTableReaderListener.DataTableCleared(), and System.Data.DataTableReaderListener.SchemaChanged().
Referenced by System.Data.DataTableReaderListener.DataTableReaderListener(), and System.Data.DataTableReaderListener.UpdataTable().