Terraria: System.Data.DataTableReaderListener.UpdataTable
UpdataTable()
void System.Data.DataTableReaderListener.UpdataTable (DataTable datatable) inline package
Definition at line 36 of file DataTableReaderListener.cs.
    {
        if (datatable == null)
        {
            throw ExceptionBuilder.ArgumentNull("DataTable");
        }
        UnSubscribeEvents();
        _currentDataTable = datatable;
        SubscribeEvents();
    }
References System.Data.DataTableReaderListener._currentDataTable, System.Data.ExceptionBuilder.ArgumentNull(), System.Data.DataTableReaderListener.SubscribeEvents(), and System.Data.DataTableReaderListener.UnSubscribeEvents().
Referenced by System.Data.DataTableReader.NextResult().