Terraria: Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea
PlaceClustersArea()
static void Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea (DesertDescription description, ClusterGroup clusters, Rectangle area, PostPlacementEffect postEffectMap[,], Point postEffectMapOffset) inline static private
    {
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        FastRandom fastRandom = new FastRandom(Main.ActiveWorldFileData.Seed).WithModifier(57005uL);
        Vector2D val = default(Vector2D);
        ((Vector2D)(ref val))._002Ector((double)description.Hive.Width, (double)description.Hive.Height);
        Vector2D val2 = default(Vector2D);
        ((Vector2D)(ref val2))._002Ector((double)clusters.Width, (double)clusters.Height);
        Vector2D val3 = description.BlockScale / 2.0;
        for (int i = area.Left; i < area.Right; i++)
        {
            for (int j = area.Top; j < area.Bottom; j++)
            {
                byte liquid = Main.tile[i, j].liquid;
                if (!WorldGen.InWorld(i, j, 1))
                {
                    continue;
                }
                double num = 0.0;
                int num2 = -1;
                double num3 = 0.0;
                ushort type = 53;
                if (fastRandom.Next(3) == 0)
                {
                    type = 397;
                }
                int num4 = i - description.Hive.X;
                int num5 = j - description.Hive.Y;
                Vector2D val4 = (new Vector2D((double)num4, (double)num5) - val3) / val * val2;
                for (int k = 0; k < clusters.Count; k++)
                {
                    Cluster cluster = clusters[k];
                    if (Math.Abs(cluster[0].Position.X - val4.X) > 10.0 || Math.Abs(cluster[0].Position.Y - val4.Y) > 10.0)
                    {
                        continue;
                    }
                    double num6 = 0.0;
                    foreach (Block item in cluster)
                    {
                        num6 += 1.0 / Vector2D.DistanceSquared(item.Position, val4);
                    }
                    if (num6 > num)
                    {
                        if (num > num3)
{
                            num3 = num;
                        }
                        num = num6;
                        num2 = k;
                    }
                    else if (num6 > num3)
                    {
                        num3 = num6;
                    }
                }
                double num7 = num + num3;
                Tile tile = Main.tile[i, j];
                Vector2D val5 = (new Vector2D((double)num4, (double)num5) - val3) / val * 2.0 - Vector2D.One;
                bool flag = ((Vector2D)(ref val5)).Length() >= 0.8;
                PostPlacementEffect postPlacementEffect = PostPlacementEffect.None;
                bool flag2 = true;
                if (num7 > 3.5)
                {
                    postPlacementEffect = PostPlacementEffect.Smooth;
                    tile.ClearEverything();
                    if (!WorldGen.remixWorldGen || !((double)j > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)))
                    {
                        tile.wall = 187;
                        if (num2 % 15 == 2)
{
                            tile.ResetToType(404);
                        }
                    }
                }
                else if (num7 > 1.8)
                {
                    if (!WorldGen.remixWorldGen || !((double)j > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)))
                    {
                        tile.wall = 187;
                    }
                    if ((double)j < Main.worldSurface)
                    {
                        tile.liquid = 0;
                    }
                    else if (!WorldGen.remixWorldGen)
                    {
                        tile.lava(lava: true);
                    }
                    if (!flag || tile.active())
                    {
                        tile.ResetToType(396);
                        postPlacementEffect = PostPlacementEffect.Smooth;
                    }
                }
                else if (num7 > 0.7 || !flag)
                {
                    if (!WorldGen.remixWorldGen || !((double)j > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)))
                    {
                        tile.wall = 216;
                        tile.liquid = 0;
                    }
                    if (!flag || tile.active())
                    {
                        tile.ResetToType(type);
                        postPlacementEffect = PostPlacementEffect.Smooth;
                    }
                }
                else if (num7 > 0.25)
                {
                    FastRandom fastRandom2 = fastRandom.WithModifier(num4, num5);
                    double num8 = (num7 - 0.25) / 0.45;
                    if (fastRandom2.NextDouble() < num8)
                    {
                        if (!WorldGen.remixWorldGen || !((double)j > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)))
{
                            tile.wall = 187;
                        }
                        if ((double)j < Main.worldSurface)
{
                            tile.liquid = 0;
                        }
                        else if (!WorldGen.remixWorldGen)
{
                            tile.lava(lava: true);
                        }
                        if (tile.active())
{
                            tile.ResetToType(type);
                            postPlacementEffect = PostPlacementEffect.Smooth;
                        }
                    }
                }
                else
                {
                    flag2 = false;
                }
                if (flag2)
                {
                    WorldGen.UpdateDesertHiveBounds(i, j);
                }
                postEffectMap[i - area.X + postEffectMapOffset.X, j - area.Y + postEffectMapOffset.Y] = postPlacementEffect;
                if (WorldGen.remixWorldGen)
                {
                    Main.tile[i, j].liquid = liquid;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Main.ActiveWorldFileData, Terraria.Tile.ClearEverything(), ReLogic.Utilities.Vector2D.DistanceSquared(), Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Height, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.WorldGen.InWorld(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextDouble(), ReLogic.Utilities.Vector2D.One, Terraria.GameContent.Biomes.Desert.DesertHive.Block.Position, Terraria.WorldGen.remixWorldGen, Terraria.Tile.ResetToType(), Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.WorldGen.UpdateDesertHiveBounds(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Width, Terraria.Utilities.FastRandom.WithModifier(), Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters().