Terraria: Microsoft.Xna.Framework.Matrix.CreateBillboard
CreateBillboard() [1/2]
static void Microsoft.Xna.Framework.Matrix.CreateBillboard (ref Vector3 objectPosition, ref Vector3 cameraPosition, ref Vector3 cameraUpVector, Vector3? cameraForwardVector, out Matrix result) inline static
Definition at line 268 of file Matrix.cs.
    {
        Vector3 value = default(Vector3);
        value.X = objectPosition.X - cameraPosition.X;
        value.Y = objectPosition.Y - cameraPosition.Y;
        value.Z = objectPosition.Z - cameraPosition.Z;
        float num = value.LengthSquared();
        if (num < 0.0001f)
        {
            value = (cameraForwardVector.HasValue ? (-cameraForwardVector.Value) : Vector3.Forward);
        }
        else
        {
            Vector3.Multiply(ref value, 1f / (float)Math.Sqrt(num), out value);
        }
        Vector3.Cross(ref cameraUpVector, ref value, out var result2);
        result2.Normalize();
        Vector3.Cross(ref value, ref result2, out var result3);
        result.M11 = result2.X;
        result.M12 = result2.Y;
        result.M13 = result2.Z;
        result.M14 = 0f;
        result.M21 = result3.X;
        result.M22 = result3.Y;
        result.M23 = result3.Z;
        result.M24 = 0f;
        result.M31 = value.X;
        result.M32 = value.Y;
        result.M33 = value.Z;
        result.M34 = 0f;
        result.M41 = objectPosition.X;
        result.M42 = objectPosition.Y;
        result.M43 = objectPosition.Z;
        result.M44 = 1f;
    }
References Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Forward, Microsoft.Xna.Framework.Vector3.Multiply(), System.Math.Sqrt(), System.value, and Microsoft.Xna.Framework.Vector3.X.