Terraria: Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard
CreateConstrainedBillboard() [2/2]
static Matrix Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard (Vector3 objectPosition, Vector3 cameraPosition, Vector3 rotateAxis, Vector3? cameraForwardVector, Vector3? objectForwardVector) inline static
Definition at line 304 of file Matrix.cs.
    {
        Vector3 value = default(Vector3);
        value.X = objectPosition.X - cameraPosition.X;
        value.Y = objectPosition.Y - cameraPosition.Y;
        value.Z = objectPosition.Z - cameraPosition.Z;
        float num = value.LengthSquared();
        if (num < 0.0001f)
        {
            value = (cameraForwardVector.HasValue ? (-cameraForwardVector.Value) : Vector3.Forward);
        }
        else
        {
            Vector3.Multiply(ref value, 1f / (float)Math.Sqrt(num), out value);
        }
        Vector3 vector = rotateAxis;
        Vector3.Dot(ref rotateAxis, ref value, out var result);
        Vector3 result2;
        Vector3 result3;
        if (Math.Abs(result) > 0.99825466f)
        {
            if (objectForwardVector.HasValue)
            {
                result2 = objectForwardVector.Value;
                Vector3.Dot(ref rotateAxis, ref result2, out result);
                if (Math.Abs(result) > 0.99825466f)
                {
                    result = rotateAxis.X * Vector3.Forward.X + rotateAxis.Y * Vector3.Forward.Y + rotateAxis.Z * Vector3.Forward.Z;
                    result2 = ((Math.Abs(result) > 0.99825466f) ? Vector3.Right : Vector3.Forward);
                }
            }
            else
            {
                result = rotateAxis.X * Vector3.Forward.X + rotateAxis.Y * Vector3.Forward.Y + rotateAxis.Z * Vector3.Forward.Z;
                result2 = ((Math.Abs(result) > 0.99825466f) ? Vector3.Right : Vector3.Forward);
            }
            Vector3.Cross(ref rotateAxis, ref result2, out result3);
            result3.Normalize();
            Vector3.Cross(ref result3, ref rotateAxis, out result2);
            result2.Normalize();
        }
        else
        {
            Vector3.Cross(ref rotateAxis, ref value, out result3);
            result3.Normalize();
            Vector3.Cross(ref result3, ref vector, out result2);
            result2.Normalize();
        }
        Matrix result4 = default(Matrix);
        result4.M11 = result3.X;
        result4.M12 = result3.Y;
        result4.M13 = result3.Z;
        result4.M14 = 0f;
        result4.M21 = vector.X;
        result4.M22 = vector.Y;
        result4.M23 = vector.Z;
        result4.M24 = 0f;
        result4.M31 = result2.X;
        result4.M32 = result2.Y;
        result4.M33 = result2.Z;
        result4.M34 = 0f;
        result4.M41 = objectPosition.X;
        result4.M42 = objectPosition.Y;
        result4.M43 = objectPosition.Z;
        result4.M44 = 1f;
        return result4;
    }
References System.Math.Abs(), Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Dot(), Microsoft.Xna.Framework.Vector3.Forward, Microsoft.Xna.Framework.Vector3.Multiply(), Microsoft.Xna.Framework.Vector3.Right, System.Math.Sqrt(), System.value, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.