Terraria: Microsoft.Xna.Framework.Matrix.CreateBillboard
CreateBillboard() [2/2]
static Matrix Microsoft.Xna.Framework.Matrix.CreateBillboard (Vector3 objectPosition, Vector3 cameraPosition, Vector3 cameraUpVector, Vector3? cameraForwardVector) inline static
Definition at line 230 of file Matrix.cs.
    {
        Vector3 value = default(Vector3);
        value.X = objectPosition.X - cameraPosition.X;
        value.Y = objectPosition.Y - cameraPosition.Y;
        value.Z = objectPosition.Z - cameraPosition.Z;
        float num = value.LengthSquared();
        if (num < 0.0001f)
        {
            value = (cameraForwardVector.HasValue ? (-cameraForwardVector.Value) : Vector3.Forward);
        }
        else
        {
            Vector3.Multiply(ref value, 1f / (float)Math.Sqrt(num), out value);
        }
        Vector3.Cross(ref cameraUpVector, ref value, out var result);
        result.Normalize();
        Vector3.Cross(ref value, ref result, out var result2);
        Matrix result3 = default(Matrix);
        result3.M11 = result.X;
        result3.M12 = result.Y;
        result3.M13 = result.Z;
        result3.M14 = 0f;
        result3.M21 = result2.X;
        result3.M22 = result2.Y;
        result3.M23 = result2.Z;
        result3.M24 = 0f;
        result3.M31 = value.X;
        result3.M32 = value.Y;
        result3.M33 = value.Z;
        result3.M34 = 0f;
        result3.M41 = objectPosition.X;
        result3.M42 = objectPosition.Y;
        result3.M43 = objectPosition.Z;
        result3.M44 = 1f;
        return result3;
    }
References Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Forward, Microsoft.Xna.Framework.Vector3.Multiply(), System.Math.Sqrt(), System.value, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.