Terraria: Microsoft.Xna.Framework.Matrix.CreateLookAt
CreateLookAt() [2/2]
static Matrix Microsoft.Xna.Framework.Matrix.CreateLookAt (Vector3 cameraPosition, Vector3 cameraTarget, Vector3 cameraUpVector) inline static
Definition at line 1084 of file Matrix.cs.
    {
        Vector3 vector = Vector3.Normalize(cameraPosition - cameraTarget);
        Vector3 vector2 = Vector3.Normalize(Vector3.Cross(cameraUpVector, vector));
        Vector3 vector3 = Vector3.Cross(vector, vector2);
        Matrix result = default(Matrix);
        result.M11 = vector2.X;
        result.M12 = vector3.X;
        result.M13 = vector.X;
        result.M14 = 0f;
        result.M21 = vector2.Y;
        result.M22 = vector3.Y;
        result.M23 = vector.Y;
        result.M24 = 0f;
        result.M31 = vector2.Z;
        result.M32 = vector3.Z;
        result.M33 = vector.Z;
        result.M34 = 0f;
        result.M41 = 0f - Vector3.Dot(vector2, cameraPosition);
        result.M42 = 0f - Vector3.Dot(vector3, cameraPosition);
        result.M43 = 0f - Vector3.Dot(vector, cameraPosition);
        result.M44 = 1f;
        return result;
    }
References Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Dot(), Microsoft.Xna.Framework.Vector3.Normalize(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.