Terraria: Microsoft.Xna.Framework.Matrix.CreateRotationZ
CreateRotationZ() [1/2]
static Matrix Microsoft.Xna.Framework.Matrix.CreateRotationZ (float radians) inline static
Definition at line 746 of file Matrix.cs.
    {
        float num = (float)Math.Cos(radians);
        float num2 = (float)Math.Sin(radians);
        Matrix result = default(Matrix);
        result.M11 = num;
        result.M12 = num2;
        result.M13 = 0f;
        result.M14 = 0f;
        result.M21 = 0f - num2;
        result.M22 = num;
        result.M23 = 0f;
        result.M24 = 0f;
        result.M31 = 0f;
        result.M32 = 0f;
        result.M33 = 1f;
        result.M34 = 0f;
        result.M41 = 0f;
        result.M42 = 0f;
        result.M43 = 0f;
        result.M44 = 1f;
        return result;
    }
References System.Math.Cos(), and System.Math.Sin().
Referenced by Terraria.Mount.DoSpawnDust(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData(), Terraria.NPC.HitEffect(), Microsoft.Xna.Framework.Graphics.SpriteFont.InternalDraw(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), Terraria.Player.RotatedRelativePointOld(), and Terraria.Minecart.TrackCollision().