Terraria: System.Security.Cryptography.X509Certificates.X509Certificate.ToString
ToString() [2/2]
virtual string System.Security.Cryptography.X509Certificates.X509Certificate.ToString (bool fVerbose) inline virtual
Reimplemented in System.Security.Cryptography.X509Certificates.X509Certificate2.
Definition at line 511 of file X509Certificate.cs.
    {
        if (!fVerbose || Pal == null)
        {
            return GetType().ToString();
        }
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("[Subject]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(Subject);
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Issuer]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(Issuer);
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Serial Number]");
        stringBuilder.Append("  ");
        byte[] serialNumber = GetSerialNumber();
        Array.Reverse(serialNumber);
        stringBuilder.Append(serialNumber.ToHexArrayUpper());
        stringBuilder.AppendLine();
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Not Before]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(FormatDate(GetNotBefore()));
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Not After]");
        stringBuilder.Append("  ");
        stringBuilder.AppendLine(FormatDate(GetNotAfter()));
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("[Thumbprint]");
        stringBuilder.Append("  ");
        stringBuilder.Append(GetRawCertHash().ToHexArrayUpper());
        stringBuilder.AppendLine();
        return stringBuilder.ToString();
    }
References System.Runtime.Serialization.Dictionary, System.Security.Cryptography.X509Certificates.X509Certificate.FormatDate(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotAfter(), System.Security.Cryptography.X509Certificates.X509Certificate.GetNotBefore(), System.Security.Cryptography.X509Certificates.X509Certificate.GetRawCertHash(), System.Security.Cryptography.X509Certificates.X509Certificate.GetSerialNumber(), System.Security.Cryptography.X509Certificates.X509Certificate.Issuer, System.Array.Reverse(), and System.Security.Cryptography.X509Certificates.X509Certificate.Subject.