Terraria: System.Security.Cryptography.X509Certificates.X509Certificate.ValidateKeyStorageFlags
ValidateKeyStorageFlags()
static void System.Security.Cryptography.X509Certificates.X509Certificate.ValidateKeyStorageFlags (X509KeyStorageFlags keyStorageFlags) inline static package inherited
Definition at line 634 of file X509Certificate.cs.
    {
        if (((uint)keyStorageFlags & 0xFFFFFFC0u) != 0)
        {
            throw new ArgumentException(System.SR.Argument_InvalidFlag, "keyStorageFlags");
        }
        X509KeyStorageFlags x509KeyStorageFlags = keyStorageFlags & (X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.EphemeralKeySet);
        if (x509KeyStorageFlags == (X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.EphemeralKeySet))
        {
            throw new ArgumentException(System.SR.Format(System.SR.Cryptography_X509_InvalidFlagCombination, x509KeyStorageFlags), "keyStorageFlags");
        }
    }
References System.SR.Argument_InvalidFlag, System.SR.Cryptography_X509_InvalidFlagCombination, System.Runtime.Serialization.Dictionary, and System.SR.Format().
Referenced by System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(), System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(), and System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import().