Terraria: System.Linq.Parallel.SortHelper.Sort
Sort() [2/2]
override TInputOutput[] System.Linq.Parallel.SortHelper< TInputOutput, TKey >.Sort () inline package
Definition at line 98 of file SortHelper.cs.
    {
        GrowingArray<TKey> keys = null;
        List<TInputOutput> values = null;
        BuildKeysFromSource(ref keys, ref values);
        QuickSortIndicesInPlace(keys, values, _indexState);
        if (_partitionCount > 1)
        {
            MergeSortCooperatively();
        }
        return _sharedValues[_partitionIndex];
    }
References System.Linq.Parallel.SortHelper< TInputOutput, TKey >._indexState, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._partitionCount, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._partitionIndex, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._sharedValues, System.Linq.Parallel.SortHelper< TInputOutput, TKey >.BuildKeysFromSource(), System.keys, System.Linq.Parallel.SortHelper< TInputOutput, TKey >.MergeSortCooperatively(), System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSortIndicesInPlace(), and System.values.