Terraria: System.Linq.Parallel.SortHelper.QuickSort
QuickSort()
void System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSort (int left, int right, TKey[] keys, int[] indices, CancellationToken cancelToken) inline private
Definition at line 317 of file SortHelper.cs.
    {
        if (right - left > 63)
        {
            cancelToken.ThrowIfCancellationRequested();
        }
        do
        {
            int num = left;
            int num2 = right;
            int num3 = indices[num + (num2 - num >> 1)];
            TKey y = keys[num3];
            while (true)
            {
                if (_keyComparer.Compare(keys[indices[num]], y) < 0)
                {
                    num++;
                    continue;
                }
                while (_keyComparer.Compare(keys[indices[num2]], y) > 0)
                {
                    num2--;
                }
                if (num > num2)
                {
                    break;
                }
                if (num < num2)
                {
                    int num4 = indices[num];
                    indices[num] = indices[num2];
                    indices[num2] = num4;
                }
                num++;
                num2--;
                if (num > num2)
                {
                    break;
                }
            }
            if (num2 - left <= right - num)
            {
                if (left < num2)
                {
                    QuickSort(left, num2, keys, indices, cancelToken);
                }
                left = num;
            }
            else
            {
                if (num < right)
                {
                    QuickSort(num, right, keys, indices, cancelToken);
                }
                right = num2;
            }
        }
        while (left < right);
    }
References System.Linq.Parallel.SortHelper< TInputOutput, TKey >._keyComparer, System.Collections.Generic.IComparer< in T >.Compare(), System.indices, System.keys, and System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSort().
Referenced by System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSort(), and System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSortIndicesInPlace().