Terraria: System.Linq.Parallel.SortHelper.QuickSortIndicesInPlace
QuickSortIndicesInPlace()
void System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSortIndicesInPlace (GrowingArray< TKey > keys, List< TInputOutput > values, OrdinalIndexState ordinalIndexState) inline private
Definition at line 146 of file SortHelper.cs.
    {
        int[] array = new int[values.Count];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = i;
        }
        if (array.Length > 1 && ordinalIndexState.IsWorseThan(OrdinalIndexState.Increasing))
        {
            QuickSort(0, array.Length - 1, keys.InternalArray, array, _groupState.CancellationState.MergedCancellationToken);
        }
        if (_partitionCount == 1)
        {
            TInputOutput[] array2 = new TInputOutput[values.Count];
            for (int j = 0; j < array.Length; j++)
            {
                array2[j] = values[array[j]];
            }
            _sharedValues[_partitionIndex] = array2;
        }
        else
        {
            _sharedIndices[_partitionIndex] = array;
            _sharedKeys[_partitionIndex] = keys;
            _sharedValues[_partitionIndex] = new TInputOutput[values.Count];
            values.CopyTo(_sharedValues[_partitionIndex]);
        }
    }
References System.Linq.Parallel.SortHelper< TInputOutput, TKey >._groupState, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._partitionCount, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._partitionIndex, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._sharedIndices, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._sharedKeys, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._sharedValues, System.array, System.Linq.Parallel.QueryTaskGroupState.CancellationState, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.keys, System.Linq.Parallel.CancellationState.MergedCancellationToken, System.Linq.Parallel.SortHelper< TInputOutput, TKey >.QuickSort(), and System.values.
Referenced by System.Linq.Parallel.SortHelper< TInputOutput, TKey >.Sort().