Terraria: System.Linq.Parallel.SortHelper.BuildKeysFromSource
BuildKeysFromSource()
void System.Linq.Parallel.SortHelper< TInputOutput, TKey >.BuildKeysFromSource (ref GrowingArray< TKey > keys, ref List< TInputOutput > values) inline private
Definition at line 111 of file SortHelper.cs.
    {
        values = new List<TInputOutput>();
        CancellationToken mergedCancellationToken = _groupState.CancellationState.MergedCancellationToken;
        try
        {
            TInputOutput currentElement = default(TInputOutput);
            TKey currentKey = default(TKey);
            bool flag = _source.MoveNext(ref currentElement, ref currentKey);
            if (keys == null)
            {
                keys = new GrowingArray<TKey>();
            }
            if (!flag)
            {
                return;
            }
            int num = 0;
            do
            {
                if ((num++ & 0x3F) == 0)
                {
                    mergedCancellationToken.ThrowIfCancellationRequested();
                }
                keys.Add(currentKey);
                values.Add(currentElement);
            }
            while (_source.MoveNext(ref currentElement, ref currentKey));
        }
        finally
        {
            _source.Dispose();
        }
    }
References System.Linq.Parallel.SortHelper< TInputOutput, TKey >._groupState, System.Linq.Parallel.SortHelper< TInputOutput, TKey >._source, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Linq.Parallel.QueryTaskGroupState.CancellationState, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.Dispose(), System.keys, System.Linq.Parallel.CancellationState.MergedCancellationToken, System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), and System.values.
Referenced by System.Linq.Parallel.SortHelper< TInputOutput, TKey >.Sort().