Terraria: RazerKeyboard.Present
Present()
override void RazerKeyboard.Present () inline virtual
Implements RgbDevice.
     {
         //IL_0046: Unknown result type (might be due to invalid IL or missing references)
         for (int i = 0; i < _effect.Color.Length; i++)
         {
             _effect.Color[i] = 0u;
             _effect.Key[i] = 0u;
         }
         for (int j = 0; j < base.LedCount; j++)
         {
             _effect.Color[j] = RazerHelper.Vector4ToDeviceColor(GetProcessedLedColor(j));
             _effect.Key[j] = _effect.Color[j] & 0xFFFFFFu;
         }
         for (int k = 0; k < _pendingKeys.Count; k++)
         {
             int item = (int)_pendingKeys[k].Item1;
             item = (item >> 8) * 22 + (item & 0xFF);
             _effect.Key[item] = _pendingKeys[k].Item2 | 0x1000000u;
         }
         _pendingKeys.Clear();
         _handle.SetAsKeyboardEffect(ref _effect);
         _handle.Apply();
     }
References _effect, _handle, _pendingKeys, EffectHandle.Apply(), RgbDevice.GetProcessedLedColor(), EffectHandle.SetAsKeyboardEffect(), and RazerHelper.Vector4ToDeviceColor().