Terraria: System.Threading.ReaderWriterLockSlim.SpinLock.EnterSpin
EnterSpin()
void System.Threading.ReaderWriterLockSlim.SpinLock.EnterSpin (EnterSpinLockReason reason) inline private
Definition at line 116 of file ReaderWriterLockSlim.cs.
        {
            int enterDeprioritizationStateChange = GetEnterDeprioritizationStateChange(reason);
            if (enterDeprioritizationStateChange != 0)
            {
                Interlocked.Add(ref _enterDeprioritizationState, enterDeprioritizationStateChange);
            }
            int processorCount = Environment.ProcessorCount;
            int num = 0;
            while (true)
            {
                if (num < 10 && processorCount > 1)
                {
                    Thread.SpinWait(20 * (num + 1));
                }
                else if (num < 15)
                {
                    Thread.Sleep(0);
                }
                else
                {
                    Thread.Sleep(1);
                }
                if (!IsEnterDeprioritized(reason))
                {
                    if (_isLocked == 0 && TryEnter())
                    {
                        break;
                    }
                }
                else if (num >= 20)
                {
                    reason |= EnterSpinLockReason.Wait;
                    num = -1;
                }
                num++;
            }
            if (enterDeprioritizationStateChange != 0)
            {
                Interlocked.Add(ref _enterDeprioritizationState, -enterDeprioritizationStateChange);
            }
        }
References System.Threading.ReaderWriterLockSlim.SpinLock._enterDeprioritizationState, System.Threading.ReaderWriterLockSlim.SpinLock._isLocked, System.Threading.Interlocked.Add(), System.Threading.ReaderWriterLockSlim.SpinLock.GetEnterDeprioritizationStateChange(), System.Threading.ReaderWriterLockSlim.SpinLock.IsEnterDeprioritized(), System.Environment.ProcessorCount, System.Threading.Thread.Sleep(), System.Threading.Thread.SpinWait(), and System.Threading.ReaderWriterLockSlim.SpinLock.TryEnter().
Referenced by System.Threading.ReaderWriterLockSlim.SpinLock.Enter().