Terraria: System.Threading.ReaderWriterLockSlim.SpinLock.Enter
Enter()
void System.Threading.ReaderWriterLockSlim.SpinLock.Enter (EnterSpinLockReason reason) inline
Definition at line 108 of file ReaderWriterLockSlim.cs.
        {
            if (!TryEnter())
            {
                EnterSpin(reason);
            }
        }
References System.Threading.ReaderWriterLockSlim.SpinLock.EnterSpin(), and System.Threading.ReaderWriterLockSlim.SpinLock.TryEnter().
Referenced by System.Threading.ReaderWriterLockSlim.ExitReadLock(), System.Threading.ReaderWriterLockSlim.ExitUpgradeableReadLock(), System.Threading.ReaderWriterLockSlim.ExitWriteLock(), System.Threading.ReaderWriterLockSlim.LazyCreateEvent(), System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(), System.Threading.ReaderWriterLockSlim.TryEnterUpgradeableReadLockCore(), System.Threading.ReaderWriterLockSlim.TryEnterWriteLockCore(), and System.Threading.ReaderWriterLockSlim.WaitOnEvent().