Terraria: System.Diagnostics.ProcessThreadCollection.Dispose
Dispose()
void System.Diagnostics.ProcessThreadCollection.Dispose () inline package
Definition at line 48 of file ProcessThreadCollection.cs.
    {
        IEnumerator enumerator = GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                ProcessThread processThread = (ProcessThread)enumerator.Current;
                processThread.Dispose();
            }
        }
        finally
        {
            IDisposable disposable = enumerator as IDisposable;
            if (disposable != null)
            {
                disposable.Dispose();
            }
        }
    }
References System.Collections.IEnumerator.Current, System.ComponentModel.Component.Dispose(), System.IDisposable.Dispose(), System.Collections.ReadOnlyCollectionBase.GetEnumerator(), and System.Collections.IEnumerator.MoveNext().
Referenced by System.Diagnostics.Process.Refresh().