Terraria: Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.RefreshStats
RefreshStats()
void Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.RefreshStats (GameModeData gameModeFound, NPC instance) inline private
Definition at line 43 of file NPCStatsReportInfoElement.cs.
    {
        instance.SetDefaults(NpcId, new NPCSpawnParams
        {
            gameModeData = gameModeFound,
            strengthMultiplierOverride = null
        });
        Damage = instance.damage;
        LifeMax = instance.lifeMax;
        MonetaryValue = instance.value;
        Defense = instance.defense;
        KnockbackResist = instance.knockBackResist;
        if (this.OnRefreshStats != null)
        {
            this.OnRefreshStats(this);
        }
    }
References Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.Damage, Terraria.NPC.damage, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.Defense, Terraria.NPC.defense, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.KnockbackResist, Terraria.NPC.knockBackResist, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.LifeMax, Terraria.NPC.lifeMax, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.MonetaryValue, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.NpcId, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.OnRefreshStats, Terraria.NPC.SetDefaults(), and Terraria.NPC.value.
Referenced by Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.NPCStatsReportInfoElement(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement(), and Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.UpdateBeforeSorting().