Terraria: System.Reflection.Emit.OpCode.Equals
Equals() [1/3]
override bool System.Reflection.Emit.OpCode.Equals ([NotNullWhen(true)] object? obj) inline
Definition at line 78 of file OpCode.cs.
    {
        if (obj is OpCode obj2)
        {
            return Equals(obj2);
        }
        return false;
    }
References System.Reflection.Emit.OpCode.Equals(), and System.obj.
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCall(), System.Reflection.Emit.ILGenerator.EmitCall(), System.Xml.Xsl.IlGen.GenerateHelper.EmitUnconditionalBranch(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.DispatchProxyGenerator.ProxyBuilder.Ldind(), System.Reflection.Emit.OpCode.operator==(), and System.Reflection.DispatchProxyGenerator.ProxyBuilder.Stind().