Terraria: IItemDropRule.ReportDroprates
ReportDroprates()
void IItemDropRule.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo)
Implemented in SlimeBodyItemDropRule, OneFromRulesRule, OneFromOptionsNotScaledWithLuckDropRule, OneFromOptionsDropRule, MechBossSpawnersDropRule, LeadingConditionRule, ItemDropWithConditionRule, FromOptionsWithoutRepeatsDropRule, DropOneByOne, DropNothing, DropBasedOnMasterMode, DropBasedOnMasterAndExpertMode, DropBasedOnExpertMode, CommonDropWithRerolls, and CommonDrop.
Referenced by BestiaryDatabase.ExtractDropsForNPC(), Chains.TryIfFailedRandomRoll.ReportDroprates(), Chains.TryIfSucceeded.ReportDroprates(), Chains.TryIfDoesntFillConditions.ReportDroprates(), DropBasedOnExpertMode.ReportDroprates(), DropBasedOnMasterAndExpertMode.ReportDroprates(), DropBasedOnMasterMode.ReportDroprates(), and OneFromRulesRule.ReportDroprates().