Terraria: System.Collections.Concurrent.ConcurrentBag.WorkStealingQueue.LocalPush
LocalPush()
void System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.LocalPush (T item, ref long emptyToNonEmptyListTransitionCount) inline package
Definition at line 53 of file ConcurrentBag.cs.
        {
            bool lockTaken = false;
            try
            {
                Interlocked.Exchange(ref _currentOp, 1);
                int num = _tailIndex;
                if (num == int.MaxValue)
                {
                    _currentOp = 0;
                    lock (this)
                    {
                        _headIndex &= _mask;
                        num = (_tailIndex = num & _mask);
                        Interlocked.Exchange(ref _currentOp, 1);
                    }
                }
                int headIndex = _headIndex;
                if (!_frozen && headIndex - (num - 1) < 0 && num - (headIndex + _mask) < 0)
                {
                    _array[num & _mask] = item;
                    _tailIndex = num + 1;
                }
                else
                {
                    _currentOp = 0;
                    Monitor.Enter(this, ref lockTaken);
                    headIndex = _headIndex;
                    int num2 = num - headIndex;
                    if (num2 >= _mask)
                    {
                        T[] array = new T[_array.Length << 1];
                        int num3 = headIndex & _mask;
                        if (num3 == 0)
{
                            Array.Copy(_array, array, _array.Length);
                        }
                        else
{
                            Array.Copy(_array, num3, array, 0, _array.Length - num3);
                            Array.Copy(_array, 0, array, _array.Length - num3, num3);
                        }
                        _array = array;
                        _headIndex = 0;
                        num = (_tailIndex = num2);
                        _mask = (_mask << 1) | 1;
                    }
                    _array[num & _mask] = item;
                    _tailIndex = num + 1;
                    if (num2 == 0)
                    {
                        Interlocked.Increment(ref emptyToNonEmptyListTransitionCount);
                    }
                    _addTakeCount -= _stealCount;
                    _stealCount = 0;
                }
                checked
                {
                    _addTakeCount++;
                }
            }
            finally
            {
                _currentOp = 0;
                if (lockTaken)
                {
                    Monitor.Exit(this);
                }
            }
        }
References System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._addTakeCount, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._array, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._currentOp, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._frozen, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._headIndex, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._mask, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._stealCount, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._tailIndex, System.array, System.Array.Copy(), System.Threading.Monitor.Enter(), System.Threading.Interlocked.Exchange(), System.Threading.Monitor.Exit(), System.Threading.Interlocked.Increment(), and System.item.