Terraria: System.Collections.Concurrent.ConcurrentBag.WorkStealingQueue.TryLocalPop
TryLocalPop()
bool System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue.TryLocalPop ([MaybeNullWhen(false)] out T result) inline package
Definition at line 137 of file ConcurrentBag.cs.
        {
            int tailIndex = _tailIndex;
            if (_headIndex - tailIndex >= 0)
            {
                result = default(T);
                return false;
            }
            bool lockTaken = false;
            try
            {
                _currentOp = 2;
                Interlocked.Exchange(ref _tailIndex, --tailIndex);
                if (!_frozen && _headIndex - tailIndex < 0)
                {
                    int num = tailIndex & _mask;
                    result = _array[num];
                    if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
                    {
                        _array[num] = default(T);
                    }
                    _addTakeCount--;
                    return true;
                }
                _currentOp = 0;
                Monitor.Enter(this, ref lockTaken);
                if (_headIndex - tailIndex <= 0)
                {
                    int num2 = tailIndex & _mask;
                    result = _array[num2];
                    if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
                    {
                        _array[num2] = default(T);
                    }
                    _addTakeCount--;
                    return true;
                }
                _tailIndex = tailIndex + 1;
                result = default(T);
                return false;
            }
            finally
            {
                _currentOp = 0;
                if (lockTaken)
                {
                    Monitor.Exit(this);
                }
            }
        }
References System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._addTakeCount, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._array, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._currentOp, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._frozen, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._headIndex, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._mask, System.Collections.Concurrent.ConcurrentBag< T >.WorkStealingQueue._tailIndex, System.Threading.Monitor.Enter(), System.Threading.Interlocked.Exchange(), and System.Threading.Monitor.Exit().