Terraria: System.Transactions.ContextData.LookupContextData
LookupContextData()
static ContextData System.Transactions.ContextData.LookupContextData (TxLookup defaultLookup) inline static package
Definition at line 53 of file ContextData.cs.
    {
        ContextData currentData = null;
        if (CallContextCurrentData.TryGetCurrentData(out currentData))
        {
            if (currentData.CurrentScope == null && currentData.CurrentTransaction == null && defaultLookup != TxLookup.DefaultCallContext)
            {
                CallContextCurrentData.ClearCurrentData(null, removeContextData: true);
                return TLSCurrentData;
            }
            return currentData;
        }
        return TLSCurrentData;
    }
References System.Transactions.CallContextCurrentData.ClearCurrentData(), System.Transactions.ContextData.CurrentScope, System.Transactions.ContextData.CurrentTransaction, System.Transactions.ContextData.TLSCurrentData, and System.Transactions.CallContextCurrentData.TryGetCurrentData().
Referenced by System.Transactions.Transaction.GetCurrentTransactionAndScope().