Terraria: System.Data.DataRelationCollection.DataSetRelationCollection.AddCore
AddCore()
override void System.Data.DataRelationCollection.DataSetRelationCollection.AddCore (DataRelation relation) inline protected virtual
Reimplemented from System.Data.DataRelationCollection.
Definition at line 255 of file DataRelationCollection.cs.
        {
            base.AddCore(relation);
            if (relation.ChildTable.DataSet != _dataSet || relation.ParentTable.DataSet != _dataSet)
            {
                throw ExceptionBuilder.ForeignRelation();
            }
            relation.CheckState();
            if (relation.Nested)
            {
                relation.CheckNestedRelations();
            }
            if (relation._relationName.Length == 0)
            {
                relation._relationName = AssignName();
            }
            else
            {
                RegisterName(relation._relationName);
            }
            DataKey childKey = relation.ChildKey;
            for (int i = 0; i < _relations.Count; i++)
            {
                if (childKey.ColumnsEqual(((DataRelation)_relations[i]).ChildKey) && relation.ParentKey.ColumnsEqual(((DataRelation)_relations[i]).ParentKey))
                {
                    throw ExceptionBuilder.RelationAlreadyExists();
                }
            }
            _relations.Add(relation);
            ((DataTableRelationCollection)relation.ParentTable.ChildRelations).Add(relation);
            ((DataTableRelationCollection)relation.ChildTable.ParentRelations).Add(relation);
            relation.SetDataSet(_dataSet);
            relation.ChildKey.GetSortIndex().AddRef();
            if (relation.Nested)
            {
                relation.ChildTable.CacheNestedParent();
            }
            ForeignKeyConstraint foreignKeyConstraint = relation.ChildTable.Constraints.FindForeignKeyConstraint(relation.ParentColumnsReference, relation.ChildColumnsReference);
            if (relation._createConstraints && foreignKeyConstraint == null)
            {
                relation.ChildTable.Constraints.Add(foreignKeyConstraint = new ForeignKeyConstraint(relation.ParentColumnsReference, relation.ChildColumnsReference));
                try
                {
                    foreignKeyConstraint.ConstraintName = relation.RelationName;
                }
                catch (Exception e) when (ADP.IsCatchableExceptionType(e))
                {
                    ExceptionBuilder.TraceExceptionWithoutRethrow(e);
                }
            }
            UniqueConstraint parentKeyConstraint = relation.ParentTable.Constraints.FindKeyConstraint(relation.ParentColumnsReference);
            relation.SetParentKeyConstraint(parentKeyConstraint);
            relation.SetChildKeyConstraint(foreignKeyConstraint);
        }
References System.Data.DataRelation._createConstraints, System.Data.DataRelationCollection.DataSetRelationCollection._dataSet, System.Data.DataRelation._relationName, System.Data.DataRelationCollection.DataSetRelationCollection._relations, System.Data.ConstraintCollection.Add(), System.Collections.ArrayList.Add(), System.Data.Index.AddRef(), System.Data.DataRelationCollection.AssignName(), System.Data.DataTable.CacheNestedParent(), System.Data.DataRelation.CheckNestedRelations(), System.Data.DataRelation.CheckState(), System.Data.DataRelation.ChildColumnsReference, System.Data.DataRelation.ChildKey, System.Data.DataTable.ChildRelations, System.Data.DataRelation.ChildTable, System.Data.DataKey.ColumnsEqual(), System.Data.DataTable.Constraints, System.Collections.ArrayList.Count, System.Data.DataTable.DataSet, System.Data.ConstraintCollection.FindForeignKeyConstraint(), System.Data.ConstraintCollection.FindKeyConstraint(), System.Data.ExceptionBuilder.ForeignRelation(), System.Data.DataKey.GetSortIndex(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.DataRelation.Nested, System.Data.DataRelation.ParentColumnsReference, System.Data.DataRelation.ParentKey, System.Data.DataTable.ParentRelations, System.Data.DataRelation.ParentTable, System.Data.DataRelationCollection.RegisterName(), System.Data.ExceptionBuilder.RelationAlreadyExists(), System.Data.DataRelation.RelationName, System.Data.DataRelation.SetChildKeyConstraint(), System.Data.DataRelation.SetDataSet(), System.Data.DataRelation.SetParentKeyConstraint(), and System.Data.ExceptionBuilder.TraceExceptionWithoutRethrow().