Terraria: System.Diagnostics.ProcessManager.GetProcessInfo
GetProcessInfo()
static ProcessInfo System.Diagnostics.ProcessManager.GetProcessInfo (int processId, string machineName) inline static
Definition at line 50 of file ProcessManager.cs.
    {
        if (IsRemoteMachine(machineName))
        {
            ProcessInfo[] processInfos = NtProcessManager.GetProcessInfos(machineName, isRemoteMachine: true);
            ProcessInfo[] array = processInfos;
            foreach (ProcessInfo processInfo in array)
            {
                if (processInfo.ProcessId == processId)
                {
                    return processInfo;
                }
            }
        }
        else
        {
            ProcessInfo[] processInfos2 = NtProcessInfoHelper.GetProcessInfos(processId);
            if (processInfos2.Length == 1)
            {
                return processInfos2[0];
            }
        }
        return null;
    }
References System.array, System.Diagnostics.NtProcessInfoHelper.GetProcessInfos(), System.Diagnostics.NtProcessManager.GetProcessInfos(), System.Diagnostics.ProcessManager.IsRemoteMachine(), and System.Diagnostics.ProcessInfo.ProcessId.
Referenced by System.Diagnostics.Process.EnsureState(), and System.Diagnostics.Process.ToString().