Terraria: System.Diagnostics.ProcessManager.IsRemoteMachine
IsRemoteMachine()
static bool System.Diagnostics.ProcessManager.IsRemoteMachine (string machineName) inline static
Definition at line 10 of file ProcessManager.cs.
    {
        if (machineName == null)
        {
            throw new ArgumentNullException("machineName");
        }
        if (machineName.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.InvalidParameter, "machineName", machineName));
        }
        return IsRemoteMachineCore(machineName);
    }
References System.SR.Format(), System.SR.InvalidParameter, and System.Diagnostics.ProcessManager.IsRemoteMachineCore().
Referenced by System.Diagnostics.Process.GetProcessById(), System.Diagnostics.Process.GetProcesses(), System.Diagnostics.ProcessManager.GetProcessIds(), System.Diagnostics.ProcessManager.GetProcessInfo(), System.Diagnostics.ProcessManager.GetProcessInfos(), System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.Init(), and System.Diagnostics.ProcessManager.IsProcessRunning().