Terraria: System.Diagnostics.ProcessManager.OpenThread
OpenThread()
static SafeThreadHandle System.Diagnostics.ProcessManager.OpenThread (int threadId, int access) inline static
Definition at line 156 of file ProcessManager.cs.
    {
        SafeThreadHandle safeThreadHandle = global::Interop.Kernel32.OpenThread(access, inherit: false, threadId);
        int lastWin32Error = Marshal.GetLastWin32Error();
        if (safeThreadHandle.IsInvalid)
        {
            if (lastWin32Error == 87)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.ThreadExited, threadId.ToString()));
            }
            throw new Win32Exception(lastWin32Error);
        }
        return safeThreadHandle;
    }
References System.SR.Format(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Microsoft.Win32.SafeHandles.SafeThreadHandle.IsInvalid, and System.SR.ThreadExited.
Referenced by System.Diagnostics.ProcessThread.OpenThreadHandle().