Terraria: System.Diagnostics.ProcessManager.OpenProcess
OpenProcess()
static SafeProcessHandle System.Diagnostics.ProcessManager.OpenProcess (int processId, int access, bool throwIfExited) inline static
Definition at line 133 of file ProcessManager.cs.
    {
        SafeProcessHandle safeProcessHandle = global::Interop.Kernel32.OpenProcess(access, inherit: false, processId);
        int lastWin32Error = Marshal.GetLastWin32Error();
        if (!safeProcessHandle.IsInvalid)
        {
            return safeProcessHandle;
        }
        if (processId == 0)
        {
            throw new Win32Exception(5);
        }
        if (lastWin32Error != 5 && !IsProcessRunning(processId))
        {
            if (throwIfExited)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.ProcessHasExited, processId.ToString()));
            }
            return SafeProcessHandle.InvalidHandle;
        }
        throw new Win32Exception(lastWin32Error);
    }
References System.SR.Format(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), Microsoft.Win32.SafeHandles.SafeProcessHandle.InvalidHandle, Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.Diagnostics.ProcessManager.IsProcessRunning(), and System.SR.ProcessHasExited.
Referenced by System.Diagnostics.NtProcessManager.GetModules(), and System.Diagnostics.Process.GetProcessHandle().