Terraria: System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore
DecodeCore() [2/2]
static void System.Security.Cryptography.Asn1.Pbkdf2SaltChoice.DecodeCore (ref System::Formats::Asn1::AsnValueReader reader, ReadOnlyMemory< byte > rebind, out System::Security::Cryptography::Asn1::Pbkdf2SaltChoice decoded) inline static private
Definition at line 23 of file Pbkdf2SaltChoice.cs.
    {
        decoded = default(System.Security.Cryptography.Asn1.Pbkdf2SaltChoice);
        Asn1Tag asn1Tag = reader.PeekTag();
        ReadOnlySpan<byte> span = rebind.Span;
        if (asn1Tag.HasSameClassAndValue(Asn1Tag.PrimitiveOctetString))
        {
            if (reader.TryReadPrimitiveOctetString(out var value))
            {
                decoded.Specified = (span.Overlaps(value, out var elementOffset) ? rebind.Slice(elementOffset, value.Length) : ((ReadOnlyMemory<byte>)value.ToArray()));
            }
            else
            {
                decoded.Specified = reader.ReadOctetString();
            }
            return;
        }
        if (asn1Tag.HasSameClassAndValue(Asn1Tag.Sequence))
        {
            System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(ref reader, rebind, out var decoded2);
            decoded.OtherSource = decoded2;
            return;
        }
        throw new CryptographicException();
    }
References System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.Formats.Asn1.Asn1Tag.HasSameClassAndValue(), System.Formats.Asn1.Asn1Tag.PrimitiveOctetString, System.Formats.Asn1.Asn1Tag.Sequence, System.ReadOnlyMemory< T >.Slice(), System.ReadOnlyMemory< T >.Span, and System.value.