Terraria: System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync
CopyToAsync() [4/4]
override async Task System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 235 of file DecompressionHandler.cs.
                {
                    Stream.ValidateCopyToArguments(destination, bufferSize);
                    if (_firstByteStatus == FirstByteStatus.Available)
                    {
                        await destination.WriteAsync(new byte[1] { _firstByte }, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                        _firstByteStatus = FirstByteStatus.Consumed;
                    }
                    await _stream.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
References System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._firstByte, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._firstByteStatus, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._stream, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.destination, and System.IO.Stream.ValidateCopyToArguments().