Terraria: System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByteAsync
PeekFirstByteAsync()
async ValueTask< int > System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream.PeekFirstByteAsync (CancellationToken cancellationToken) inline
Definition at line 192 of file DecompressionHandler.cs.
                {
                    byte[] buffer = new byte[1];
                    if (await _stream.ReadAsync(buffer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false) == 0)
                    {
                        _firstByteStatus = FirstByteStatus.Consumed;
                        return -1;
                    }
                    _firstByte = buffer[0];
                    _firstByteStatus = FirstByteStatus.Available;
                    return buffer[0];
                }
References System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._firstByte, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._firstByteStatus, System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.PeekFirstByteReadStream._stream, System.buffer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), and System.IO.Stream.ReadAsync().
Referenced by System.Net.Http.DecompressionHandler.DeflateDecompressedContent.ZLibOrDeflateStream.CopyToAsync().