Terraria: LucyAxeMessage.Create
Create()
static void LucyAxeMessage.Create (MessageSource source, Vector2 position, Vector2 velocity) inline static
     {
         if (Main.netMode != 2)
         {
             GiveIdleMessageCooldown();
             SpawnPopupText(source, _variation, position, velocity);
             PlaySound(source, position);
             SpawnEmoteBubble();
             if (Main.netMode == 1)
             {
                 NetMessage.SendData(141, -1, -1, null, (int)source, (int)_variation, velocity.X, velocity.Y, (int)position.X, (int)position.Y);
             }
             _variation++;
         }
     }
References _variation, GiveIdleMessageCooldown(), Main.netMode, PlaySound(), NetMessage.SendData(), SpawnEmoteBubble(), and SpawnPopupText().
Referenced by Player.DropSelectedItem(), Player.GetItem_FillEmptyInventorySlot(), Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), ItemSlot_OnItemTransferred(), TryCreatingMessageWithCooldown(), and TryPlayingIdleMessage().