Terraria: LucyAxeMessage.ItemSlot_OnItemTransferred
ItemSlot_OnItemTransferred()
static void LucyAxeMessage.ItemSlot_OnItemTransferred (ItemSlot.ItemTransferInfo info) inline static private
     {
         if (info.ItemType != 5095)
         {
             return;
         }
         bool flag = CountsAsStorage(info.FromContenxt);
         bool flag2 = CountsAsStorage(info.ToContext);
         if (flag != flag2)
         {
             MessageSource messageSource = ((!flag) ? MessageSource.Storage : MessageSource.PickedUp);
             if (_messageCooldownsByType[(int)messageSource] <= 0)
             {
                 PutMessageTypeOnCooldown(messageSource, 420);
                 Player localPlayer = Main.LocalPlayer;
                 Create(messageSource, localPlayer.Top, new Vector2(localPlayer.direction * 7, -2f));
             }
         }
     }
References _messageCooldownsByType, CountsAsStorage(), Create(), Entity.direction, Main.LocalPlayer, PutMessageTypeOnCooldown(), and Entity.Top.
Referenced by Initialize().