Terraria: LucyAxeMessage.Initialize
Initialize()
static void LucyAxeMessage.Initialize () inline static
     {
         ItemSlot.OnItemTransferred += ItemSlot_OnItemTransferred;
         Player.Hooks.OnEnterWorld += Hooks_OnEnterWorld;
     }
References Hooks_OnEnterWorld(), ItemSlot_OnItemTransferred(), Player.Hooks.OnEnterWorld, and ItemSlot.OnItemTransferred.
Referenced by Main.Initialize_AlmostEverything().