Terraria: LucyAxeMessage.PlaySound
PlaySound()
static void LucyAxeMessage.PlaySound (MessageSource source, Vector2 position) inline static private
     {
         SoundEngine.PlaySound(SoundID.LucyTheAxeTalk, position);
     }
References SoundID.LucyTheAxeTalk, and SoundEngine.PlaySound().
Referenced by Create(), and CreateFromNet().