Terraria: System.Data.DataTableExtensions.LoadTableFromEnumerable< T >
LoadTableFromEnumerable< T >()
static DataTable System.Data.DataTableExtensions.LoadTableFromEnumerable< T > (IEnumerable< T > source, DataTable table, LoadOption? options, FillErrorEventHandler errorHandler) inline static private
Type Constraints
T : DataRow
Definition at line 34 of file DataTableExtensions.cs.
                                                                                                                                                                 : DataRow
    {
        if (options.HasValue)
        {
            LoadOption value = options.Value;
            if ((uint)(value - 1) > 2u)
            {
                throw DataSetUtil.InvalidLoadOption(options.Value);
            }
        }
        using (IEnumerator<T> enumerator = source.GetEnumerator())
        {
            if (!enumerator.MoveNext())
            {
                return table ?? throw DataSetUtil.InvalidOperation(System.SR.DataSetLinq_EmptyDataRowSource);
            }
            if (table == null)
            {
                DataRow current = enumerator.Current;
                if (current == null)
                {
                    throw DataSetUtil.InvalidOperation(System.SR.DataSetLinq_NullDataRow);
                }
                table = new DataTable
                {
                    Locale = CultureInfo.CurrentCulture
                };
                foreach (DataColumn column in current.Table.Columns)
                {
                    table.Columns.Add(column.ColumnName, column.DataType);
                }
            }
            table.BeginLoadData();
            try
            {
                do
                {
                    DataRow current = enumerator.Current;
                    if (current == null)
                    {
                        continue;
                    }
                    object[] values = null;
                    try
                    {
                        switch (current.RowState)
{
                        case DataRowState.Detached:
                            if (!current.HasVersion(DataRowVersion.Proposed))
{
                                throw DataSetUtil.InvalidOperation(System.SR.DataSetLinq_CannotLoadDetachedRow);
                            }
                            goto case DataRowState.Unchanged;
                        case DataRowState.Unchanged:
                        case DataRowState.Added:
                        case DataRowState.Modified:
                            values = current.ItemArray;
                            if (options.HasValue)
{
                                table.LoadDataRow(values, options.Value);
                            }
                            else
{
                                table.LoadDataRow(values, fAcceptChanges: true);
                            }
                            break;
                        case DataRowState.Deleted:
                            throw DataSetUtil.InvalidOperation(System.SR.DataSetLinq_CannotLoadDeletedRow);
                        default:
                            throw DataSetUtil.InvalidDataRowState(current.RowState);
                        }
                    }
                    catch (Exception ex)
                    {
                        if (!DataSetUtil.IsCatchableExceptionType(ex))
{
                            throw;
                        }
                        FillErrorEventArgs fillErrorEventArgs = null;
                        if (errorHandler != null)
{
                            fillErrorEventArgs = new FillErrorEventArgs(table, values)
{
                                Errors = ex
                            };
                            errorHandler(enumerator, fillErrorEventArgs);
                        }
                        if (fillErrorEventArgs == null)
{
                            throw;
                        }
                        if (!fillErrorEventArgs.Continue)
{
                            if ((fillErrorEventArgs.Errors ?? ex) == ex)
{
                                throw;
                            }
                            throw fillErrorEventArgs.Errors;
                        }
                    }
                }
                while (enumerator.MoveNext());
            }
            finally
            {
                table.EndLoadData();
            }
        }
        return table;
    }
References System.Data.DataColumnCollection.Add(), System.Data.DataTable.Columns, System.SR.DataSetLinq_CannotLoadDeletedRow, System.SR.DataSetLinq_CannotLoadDetachedRow, System.SR.DataSetLinq_EmptyDataRowSource, System.SR.DataSetLinq_NullDataRow, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.Data.DataRow.HasVersion(), DataSetUtil.InvalidDataRowState(), DataSetUtil.InvalidLoadOption(), DataSetUtil.InvalidOperation(), DataSetUtil.IsCatchableExceptionType(), System.Data.DataRow.ItemArray, System.options, System.Data.DataRow.RowState, System.source, System.value, and System.values.