Terraria: System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read
Read()
void System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read (BinaryParser input) inline
Definition at line 47 of file SerializationHeaderRecord.cs.
    {
        byte[] array = input.ReadBytes(17);
        if (array.Length < 17)
        {
            throw new EndOfStreamException(System.SR.IO_EOF_ReadBeyondEOF);
        }
        _majorVersion = GetInt32(array, 9);
        if (_majorVersion > 1)
        {
            throw new SerializationException(System.SR.Format(System.SR.Serialization_InvalidFormat, BitConverter.ToString(array)));
        }
        _binaryHeaderEnum = (BinaryHeaderEnum)array[0];
        _topId = GetInt32(array, 1);
        _headerId = GetInt32(array, 5);
        _minorVersion = GetInt32(array, 13);
    }
References System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord._binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord._headerId, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord._majorVersion, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord._minorVersion, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord._topId, System.array, System.SR.Format(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.GetInt32(), System.input, System.SR.IO_EOF_ReadBeyondEOF, System.SR.Serialization_InvalidFormat, and System.BitConverter.ToString().