Terraria: System.Net.FileWebRequest.Abort
Abort()
override void System.Net.FileWebRequest.Abort () inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 320 of file FileWebRequest.cs.
    {
        if (Interlocked.Increment(ref _aborted) == 1)
        {
            _stream?.Abort();
            _response?.Close();
        }
    }
References System.Net.FileWebRequest._aborted, System.Net.FileWebRequest._response, System.Net.FileWebRequest._stream, System.Net.WebFileStream.Abort(), System.Net.WebResponse.Close(), System.Runtime.Serialization.Dictionary, and System.Threading.Interlocked.Increment().