Terraria: System.Net.FileWebRequest.CheckAndMarkAsyncGetRequestStreamPending
CheckAndMarkAsyncGetRequestStreamPending()
void System.Net.FileWebRequest.CheckAndMarkAsyncGetRequestStreamPending () inline private
Definition at line 155 of file FileWebRequest.cs.
    {
        if (Aborted)
        {
            throw CreateRequestAbortedException();
        }
        if (string.Equals(_method, "GET", StringComparison.OrdinalIgnoreCase) || string.Equals(_method, "HEAD", StringComparison.OrdinalIgnoreCase))
        {
            throw new ProtocolViolationException(System.SR.net_nouploadonget);
        }
        if (_response != null)
        {
            throw new InvalidOperationException(System.SR.net_reqsubmitted);
        }
        lock (this)
        {
            if (_writePending)
            {
                throw new InvalidOperationException(System.SR.net_repcall);
            }
            _writePending = true;
        }
    }
References System.Net.FileWebRequest._method, System.Net.FileWebRequest._response, System.Net.FileWebRequest._writePending, System.Net.FileWebRequest.Aborted, System.Net.FileWebRequest.CreateRequestAbortedException(), System.Runtime.Serialization.Dictionary, System.Net.Equals, System.SR.net_nouploadonget, System.SR.net_repcall, and System.SR.net_reqsubmitted.
Referenced by System.Net.FileWebRequest.BeginGetRequestStream(), and System.Net.FileWebRequest.GetRequestStreamAsync().