Terraria: System.Net.FileWebRequest.BeginGetResponse
BeginGetResponse()
override IAsyncResult System.Net.FileWebRequest.BeginGetResponse (AsyncCallback? callback, object? state) inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 255 of file FileWebRequest.cs.
    {
        CheckAndMarkAsyncGetResponsePending();
        Task<WebResponse> task = Task.Factory.StartNew((object s) => ((FileWebRequest)s).CreateResponse(), this, CancellationToken.None, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
        return System.Threading.Tasks.TaskToApm.Begin(task, callback, state);
    }
References System.Threading.Tasks.TaskToApm.Begin(), System.Net.FileWebRequest.CheckAndMarkAsyncGetResponsePending(), System.Net.FileWebRequest.CreateResponse(), System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Threading.CancellationToken.None, System.s, System.state, and System.task.
Referenced by System.Net.FileWebRequest.GetResponse().