Terraria: System.Net.FileWebRequest.GetRequestStream
GetRequestStream()
override Stream System.Net.FileWebRequest.GetRequestStream () inline virtual
Reimplemented from System.Net.WebRequest.
Definition at line 288 of file FileWebRequest.cs.
    {
        IAsyncResult asyncResult = BeginGetRequestStream(null, null);
        if (Timeout != -1 && !asyncResult.IsCompleted && (!asyncResult.AsyncWaitHandle.WaitOne(Timeout, exitContext: false) || !asyncResult.IsCompleted))
        {
            _stream?.Close();
            throw new WebException(System.SR.net_webstatus_Timeout, WebExceptionStatus.Timeout);
        }
        return EndGetRequestStream(asyncResult);
    }
References System.Net.FileWebRequest._stream, System.asyncResult, System.Net.FileWebRequest.BeginGetRequestStream(), System.IO.Stream.Close(), System.Runtime.Serialization.Dictionary, System.Net.FileWebRequest.EndGetRequestStream(), and System.SR.net_webstatus_Timeout.