Terraria: System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode
CopyShallowNode()
bool System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode (XPathNavigator nav) inline private
Definition at line 120 of file XmlMergeSequenceWriter.cs.
    {
        bool result = false;
        switch (nav.NodeType)
        {
        case XPathNodeType.Element:
            _xwrt.WriteStartElement(nav.Prefix, nav.LocalName, nav.NamespaceURI);
            result = true;
            break;
        case XPathNodeType.Attribute:
            _xwrt.WriteStartAttribute(nav.Prefix, nav.LocalName, nav.NamespaceURI);
            _xwrt.WriteString(nav.Value);
            _xwrt.WriteEndAttribute();
            break;
        case XPathNodeType.Text:
            _xwrt.WriteString(nav.Value);
            break;
        case XPathNodeType.SignificantWhitespace:
        case XPathNodeType.Whitespace:
            _xwrt.WriteWhitespace(nav.Value);
            break;
        case XPathNodeType.Root:
            result = true;
            break;
        case XPathNodeType.Comment:
            _xwrt.WriteComment(nav.Value);
            break;
        case XPathNodeType.ProcessingInstruction:
            _xwrt.WriteProcessingInstruction(nav.LocalName, nav.Value);
            break;
        case XPathNodeType.Namespace:
            _xwrt.WriteNamespaceDeclaration(nav.LocalName, nav.Value);
            break;
        }
        return result;
    }
References System.Xml.Xsl.Runtime.XmlMergeSequenceWriter._xwrt, System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, System.Xml.XPath.XPathNavigator.Prefix, System.Xml.XPath.XPathItem.Value, System.Xml.XmlWriter.WriteComment(), System.Xml.XmlWriter.WriteEndAttribute(), System.Xml.XmlRawWriter.WriteNamespaceDeclaration(), System.Xml.XmlWriter.WriteProcessingInstruction(), System.Xml.XmlWriter.WriteStartAttribute(), System.Xml.XmlWriter.WriteStartElement(), System.Xml.XmlWriter.WriteString(), and System.Xml.XmlRawWriter.WriteWhitespace().
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode().