Terraria: System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode
CopyNode()
void System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode (XPathNavigator nav) inline private
Definition at line 63 of file XmlMergeSequenceWriter.cs.
    {
        int num = 0;
        while (true)
        {
            if (CopyShallowNode(nav))
            {
                XPathNodeType nodeType = nav.NodeType;
                if (nodeType == XPathNodeType.Element)
                {
                    if (nav.MoveToFirstAttribute())
                    {
                        do
{
                            CopyShallowNode(nav);
                        }
                        while (nav.MoveToNextAttribute());
                        nav.MoveToParent();
                    }
                    XPathNamespaceScope xPathNamespaceScope = ((num == 0) ? XPathNamespaceScope.ExcludeXml : XPathNamespaceScope.Local);
                    if (nav.MoveToFirstNamespace(xPathNamespaceScope))
                    {
                        CopyNamespaces(nav, xPathNamespaceScope);
                        nav.MoveToParent();
                    }
                    _xwrt.StartElementContent();
                }
                if (nav.MoveToFirstChild())
                {
                    num++;
                    continue;
                }
                if (nav.NodeType == XPathNodeType.Element)
                {
                    _xwrt.WriteEndElement(nav.Prefix, nav.LocalName, nav.NamespaceURI);
                }
            }
            while (true)
            {
                if (num == 0)
                {
                    return;
                }
                if (nav.MoveToNext())
                {
                    break;
                }
                num--;
                nav.MoveToParent();
                if (nav.NodeType == XPathNodeType.Element)
                {
                    _xwrt.WriteFullEndElement(nav.Prefix, nav.LocalName, nav.NamespaceURI);
                }
            }
        }
    }
References System.Xml.Xsl.Runtime.XmlMergeSequenceWriter._xwrt, System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNamespaces(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyShallowNode(), System.Xml.Dictionary, System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, System.Xml.XPath.XPathNavigator.Prefix, System.Xml.XmlRawWriter.StartElementContent(), System.Xml.XmlRawWriter.WriteEndElement(), and System.Xml.XmlRawWriter.WriteFullEndElement().
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.WriteItem().