Terraria: System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.WriteString
WriteString()
void System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.WriteString (string value) inline private
Definition at line 50 of file XmlMergeSequenceWriter.cs.
    {
        if (_lastItemWasAtomic)
        {
            _xwrt.WriteWhitespace(" ");
        }
        else
        {
            _lastItemWasAtomic = true;
        }
        _xwrt.WriteString(value);
    }
References System.Xml.Xsl.Runtime.XmlMergeSequenceWriter._lastItemWasAtomic, System.Xml.Xsl.Runtime.XmlMergeSequenceWriter._xwrt, System.value, System.Xml.XmlWriter.WriteString(), and System.Xml.XmlRawWriter.WriteWhitespace().
Referenced by System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.WriteItem().