Terraria: System.Text.DecoderExceptionFallbackBuffer.Throw
Throw()
static void System.Text.DecoderExceptionFallbackBuffer.Throw (byte[] bytesUnknown, int index) inline static private
Definition at line 26 of file DecoderExceptionFallbackBuffer.cs.
    {
        if (bytesUnknown == null)
        {
            bytesUnknown = Array.Empty<byte>();
        }
        StringBuilder stringBuilder = new StringBuilder(bytesUnknown.Length * 4);
        for (int i = 0; i < bytesUnknown.Length && i < 20; i++)
        {
            StringBuilder stringBuilder2 = stringBuilder;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder2);
            handler.AppendLiteral("[");
            handler.AppendFormatted(bytesUnknown[i], "X2");
            handler.AppendLiteral("]");
            stringBuilder2.Append(ref handler);
        }
        if (bytesUnknown.Length > 20)
        {
            stringBuilder.Append(" ...");
        }
        throw new DecoderFallbackException(SR.Format(SR.Argument_InvalidCodePageBytesIndex, stringBuilder, index), bytesUnknown, index);
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.SR.Argument_InvalidCodePageBytesIndex, System.SR.Format(), and System.index.
Referenced by System.Text.DecoderExceptionFallbackBuffer.Fallback().