Terraria: MS.Internal.Xml.Cache.XPathNodeInfoAtom.ToString
ToString()
override string MS.Internal.Xml.Cache.XPathNodeInfoAtom.ToString () inline
Definition at line 142 of file XPathNodeInfoAtom.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.Append("hash=");
        stringBuilder.Append(GetHashCode());
        stringBuilder.Append(", ");
        if (_localName.Length != 0)
        {
            stringBuilder.Append('{');
            stringBuilder.Append(_namespaceUri);
            stringBuilder.Append('}');
            if (_prefix.Length != 0)
            {
                stringBuilder.Append(_prefix);
                stringBuilder.Append(':');
            }
            stringBuilder.Append(_localName);
            stringBuilder.Append(", ");
        }
        if (_pageParent != null)
        {
            stringBuilder.Append("parent=");
            stringBuilder.Append(_pageParent[0].PageInfo.PageNumber);
            stringBuilder.Append(", ");
        }
        if (_pageSibling != null)
        {
            stringBuilder.Append("sibling=");
            stringBuilder.Append(_pageSibling[0].PageInfo.PageNumber);
            stringBuilder.Append(", ");
        }
        if (_pageSimilar != null)
        {
            stringBuilder.Append("similar=");
            stringBuilder.Append(_pageSimilar[0].PageInfo.PageNumber);
            stringBuilder.Append(", ");
        }
        stringBuilder.Append("lineNum=");
        stringBuilder.Append(_lineNumBase);
        stringBuilder.Append(", ");
        stringBuilder.Append("linePos=");
        stringBuilder.Append(_linePosBase);
        return stringBuilder.ToString();
    }
References MS.Internal.Xml.Cache.XPathNodeInfoAtom._lineNumBase, MS.Internal.Xml.Cache.XPathNodeInfoAtom._linePosBase, MS.Internal.Xml.Cache.XPathNodeInfoAtom._localName, MS.Internal.Xml.Cache.XPathNodeInfoAtom._namespaceUri, MS.Internal.Xml.Cache.XPathNodeInfoAtom._pageParent, MS.Internal.Xml.Cache.XPathNodeInfoAtom._pageSibling, MS.Internal.Xml.Cache.XPathNodeInfoAtom._pageSimilar, MS.Internal.Xml.Cache.XPathNodeInfoAtom._prefix, System.Text.StringBuilder.Append(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.GetHashCode(), MS.Internal.Xml.Cache.XPathNodeInfoAtom.PageInfo, MS.Internal.Xml.Cache.XPathNodePageInfo.PageNumber, and System.Text.StringBuilder.ToString().