Terraria: AmbientWindSystem.TestAirCloud
TestAirCloud()
void AmbientWindSystem.TestAirCloud (int x, int y) inline private
     {
         if (_random.Next(120000) != 0)
         {
             return;
         }
         for (int i = -2; i <= 2; i++)
         {
             if (i != 0)
             {
                 Tile t = Main.tile[x + i, y];
                 if (!DoesTileAllowWind(t))
                 {
                     return;
                 }
                 t = Main.tile[x, y + i];
                 if (!DoesTileAllowWind(t))
                 {
                     return;
                 }
             }
         }
         _spotsForAirboneWind.Add(new Point(x, y));
     }
References _random, _spotsForAirboneWind, DoesTileAllowWind(), UnifiedRandom.Next(), and Main.tile.
Referenced by TrySpawningWind().