Terraria: AmbientWindSystem.SpawnAirborneCloud
SpawnAirborneCloud()
void AmbientWindSystem.SpawnAirborneCloud (int x, int y) inline private
     {
         int num = _random.Next(2, 6);
         float num2 = 1.1f;
         float num3 = 2.2f;
         float num4 = 0.023561945f * _random.NextFloatDirection();
         float num5 = 0.023561945f * _random.NextFloatDirection();
         while (num5 > -0.011780973f && num5 < 0.011780973f)
         {
             num5 = 0.023561945f * _random.NextFloatDirection();
         }
         if (_random.Next(4) == 0)
         {
             num = _random.Next(9, 16);
             num2 = 1.1f;
             num3 = 1.2f;
         }
         else if (_random.Next(4) == 0)
         {
             num = _random.Next(9, 16);
             num2 = 1.1f;
             num3 = 0.2f;
         }
         Vector2 vector = new Vector2(-10f, 0f);
         Vector2 vector2 = new Point(x, y).ToWorldCoordinates();
         num4 -= num5 * (float)num * 0.5f;
         float num6 = num4;
         for (int i = 0; i < num; i++)
         {
             if (Main.rand.Next(10) == 0)
             {
                 num5 *= _random.NextFloatDirection();
             }
             Vector2 vector3 = _random.NextVector2Circular(4f, 4f);
             int type = 1091 + _random.Next(2) * 2;
             float num7 = 1.4f;
             float num8 = num2 + _random.NextFloat() * num3;
             float num9 = num6 + num5;
             Vector2 vector4 = Vector2.UnitX.RotatedBy(num9) * num7;
             Gore.NewGorePerfect(vector2 + vector3 - vector, vector4 * Main.WindForVisuals, type, num8);
             vector2 += vector4 * 6.5f * num8;
             num6 = num9;
         }
     }
References _random, Gore.NewGorePerfect(), UnifiedRandom.Next(), Main.rand, and Main.WindForVisuals.
Referenced by SpawnAirborneWind().