Terraria: Projectile.AI_150_GolfClubHelper
AI_150_GolfClubHelper()
void Projectile.AI_150_GolfClubHelper () inline private
     {
         Player player = Main.player[owner];
         if (!player.active)
         {
             Kill();
             return;
         }
         if (player.gravDir == -1f)
         {
             player.SetDummyItemTime(0);
             Kill();
             return;
         }
         bool flag = false;
         Rectangle rectangle = Utils.CenteredRectangle(player.Center, new Vector2(500f, 500f));
         for (int i = 0; i < 1000; i++)
         {
             Projectile projectile = Main.projectile[i];
             if (projectile.active && projectile.owner == Main.myPlayer && ProjectileID.Sets.IsAGolfBall[projectile.type] && rectangle.Contains(projectile.Center.ToPoint()))
             {
                 flag = true;
                 break;
             }
         }
         if (!flag && owner == Main.myPlayer && ai[0] == 0f)
         {
             player.TryPlacingAGolfBallNearANearbyTee(Main.player[owner].Center);
         }
         if (!player.channel && ai[0] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item1, player.Center);
             for (int j = 0; j < 1000; j++)
             {
                 Projectile projectile2 = Main.projectile[j];
                 Vector2 shotVector = Main.MouseWorld - projectile2.Center;
                 if (!projectile2.active || !ProjectileID.Sets.IsAGolfBall[projectile2.type] || projectile2.owner != owner || !GolfHelper.ValidateShot(projectile2, player, ref shotVector))
                 {
                     continue;
                 }
                 float num = Main.rand.NextFloatDirection();
                 for (float num2 = 0f; num2 < 1f; num2 += 0.1f)
                 {
                     Dust dust = Dust.NewDustPerfect(projectile2.Center, 31, ((float)Math.PI * 2f * num2 + num).ToRotationVector2() * 0.8f, 127);
                     dust.fadeIn = 0f;
                     if (num2 % 0.2f == 0f)
                     {
                         dust.velocity *= 0.4f;
                     }
                 }
                 SoundEngine.PlaySound(SoundID.Item126, projectile2.Center);
                 if (owner == Main.myPlayer)
                 {
                     GolfHelper.ShotStrength shotStrength = GolfHelper.CalculateShotStrength(this, projectile2);
                     Vector2 vector = Vector2.Normalize(shotVector) * shotStrength.AbsoluteStrength;
                     GolfHelper.HitGolfBall(projectile2, vector, shotStrength.RoughLandResistance);
                     NetMessage.SendData(27, -1, -1, null, j);
                 }
             }
             ai[0] = 1f;
             ai[1] = 0f;
             netUpdate = true;
         }
         if (ai[0] == 1f)
         {
             ai[1] += 1f;
             float num3 = player.HeldItem.useAnimation + 30;
             if (ai[1] >= num3)
             {
                 Kill();
                 return;
             }
             velocity = Vector2.Zero;
             player.ChangeDir(direction);
             player.heldProj = whoAmI;
             int num4 = player.HeldItem.useAnimation - (int)ai[1];
             if (num4 < 2)
             {
                 num4 = 2;
             }
             player.SetDummyItemTime(num4);
         }
         if (ai[0] != 0f)
         {
             return;
         }
         if (owner == Main.myPlayer)
         {
             Vector2 mouseWorld = Main.MouseWorld;
             if (mouseWorld != base.Center)
             {
                 netUpdate = true;
                 base.Center = mouseWorld;
             }
             if (Main.mouseRight && Main.mouseRightRelease)
             {
                 Kill();
                 player.mouseInterface = true;
                 Main.blockMouse = true;
                 player.SetItemTime(0);
                 player.itemAnimation = 0;
                 player.itemAnimationMax = 0;
                 player.reuseDelay = 0;
                 return;
             }
         }
         if (position != oldPosition)
         {
             if (base.Center.X - player.Center.X > 0f)
             {
                 direction = 1;
             }
             else
             {
                 direction = -1;
             }
         }
         velocity = Vector2.Zero;
         player.ChangeDir(direction);
         player.heldProj = whoAmI;
         ai[1] += 1f;
         int num5 = player.HeldItem.useAnimation * 4;
         if (ai[1] > (float)(num5 * 3))
         {
             ai[1] = num5;
         }
         int num6 = player.HeldItem.useAnimation + Math.Min(num5, (int)ai[1]);
         if (num6 < 2)
         {
             num6 = 2;
         }
         player.SetDummyItemTime(num6);
     }
References GolfHelper.ShotStrength.AbsoluteStrength, Entity.active, Main.blockMouse, GolfHelper.CalculateShotStrength(), Entity.Center, Utils.CenteredRectangle(), Player.ChangeDir(), Player.channel, Dust.fadeIn, Player.gravDir, Player.HeldItem, Player.heldProj, GolfHelper.HitGolfBall(), ProjectileID.Sets.IsAGolfBall, SoundID.Item1, SoundID.Item126, Player.itemAnimation, Player.itemAnimationMax, Player.mouseInterface, Main.mouseRight, Main.mouseRightRelease, Main.MouseWorld, Main.myPlayer, Dust.NewDustPerfect(), owner, Main.player, SoundEngine.PlaySound(), Main.projectile, Main.rand, Player.reuseDelay, NetMessage.SendData(), Player.SetDummyItemTime(), Player.SetItemTime(), Player.TryPlacingAGolfBallNearANearbyTee(), type, Item.useAnimation, GolfHelper.ValidateShot(), and Dust.velocity.