Terraria: Projectile.AI_153_ToiletPop
AI_153_ToiletPop()
void Projectile.AI_153_ToiletPop () inline private
     {
         Vector2 center = base.Center;
         float speedY = -2f;
         int num = 0;
         int num2 = 0;
         if (ai[0] == 0f)
         {
             num = 6;
             num2 = 1;
         }
         else
         {
             if (!(ai[0] <= 10f))
             {
                 Kill();
                 return;
             }
             if (Main.rand.Next(5) == 0)
             {
                 num2 = 1;
             }
             num = 2;
         }
         ai[0] += 1f;
         for (int i = 0; i < num; i++)
         {
             Dust dust = Dust.NewDustDirect(center, 3, 6, 216, 0f, speedY);
             dust.velocity.X *= 0.5f;
             dust.velocity.Y = 0f - Math.Abs(dust.velocity.Y);
             dust.position -= dust.velocity;
             dust.scale = 0.8f;
         }
         for (int j = 0; j < num2; j++)
         {
             Gore gore = Gore.NewGoreDirect(center, Vector2.UnitY * -3f + Main.rand.NextVector2Circular(1f, 1f), Main.rand.Next(580, 583));
             gore.velocity.Y = 0f - Math.Abs(gore.velocity.Y);
         }
     }
References Dust.NewDustDirect(), Gore.NewGoreDirect(), UnifiedRandom.Next(), Dust.position, Main.rand, Dust.scale, Dust.velocity, and Gore.velocity.