Terraria: Projectile.AI_140_MonkStaffT1
AI_140_MonkStaffT1()
void Projectile.AI_140_MonkStaffT1 () inline private
     {
         //IL_0505: Unknown result type (might be due to invalid IL or missing references)
         //IL_0518: Unknown result type (might be due to invalid IL or missing references)
         float num = 50f;
         float num2 = 2f;
         float num3 = 20f;
         Player player = Main.player[owner];
         float num4 = -(float)Math.PI / 4f;
         Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
         Vector2 vector2 = Vector2.Zero;
         if (player.dead)
         {
             Kill();
             return;
         }
         if (type == 697)
         {
             int num5 = damage * 3;
             int num6 = Math.Sign(velocity.X);
             velocity = new Vector2(num6, 0f);
             if (ai[0] == 0f)
             {
                 rotation = new Vector2(num6, 0f - player.gravDir).ToRotation() + num4 + (float)Math.PI;
                 if (velocity.X < 0f)
                 {
                     rotation -= (float)Math.PI / 2f;
                 }
             }
             alpha -= 128;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             float num7 = ai[0] / num;
             float num8 = 1f;
             ai[0] += num8;
             rotation += (float)Math.PI * 2f * num2 / num * (float)num6;
             bool flag = ai[0] == (float)(int)(num / 2f);
             if (ai[0] >= num || (flag && !player.controlUseItem))
             {
                 Kill();
                 player.reuseDelay = 10;
             }
             else if (flag)
             {
                 Vector2 mouseWorld = Main.MouseWorld;
                 int num9 = ((player.DirectionTo(mouseWorld).X > 0f) ? 1 : (-1));
                 if ((float)num9 != velocity.X)
                 {
                     player.ChangeDir(num9);
                     velocity = new Vector2(num9, 0f);
                     netUpdate = true;
                     rotation -= (float)Math.PI;
                 }
             }
             float num10 = rotation - (float)Math.PI / 4f * (float)num6;
             vector2 = (num10 + ((num6 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * (ai[0] / num) * num3;
             Vector2 vector3 = base.Center + (num10 + ((num6 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * 30f;
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 31, player.velocity.X, player.velocity.Y, 150);
                 dust.velocity = DirectionTo(dust.position) * 0.1f + dust.velocity * 0.1f;
             }
             if (num7 >= 0.75f)
             {
                 Dust dust2 = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 55, player.velocity.X, player.velocity.Y, 50);
                 dust2.velocity = DirectionTo(dust2.position) * 0.1f + dust2.velocity * 0.1f;
                 dust2.noGravity = true;
                 dust2.color = new Color(20, 255, 100, 160);
             }
             if (ai[0] >= num - 8f && ai[0] < num - 2f)
             {
                 for (int i = 0; i < 5; i++)
                 {
                     Dust dust3 = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 55, player.velocity.X, player.velocity.Y, 50);
                     dust3.velocity *= 1.2f;
                     dust3.noGravity = true;
                     dust3.scale += 0.1f;
                     dust3.color = new Color(20, 255, 100, 160);
                 }
             }
             if (ai[0] == num - 3f && owner == Main.myPlayer)
             {
                 if (localAI[1] == 1f || WorldUtils.Find(vector3.ToTileCoordinates(), Searches.Chain(new Searches.Down(4), _cachedConditions_notNull, _cachedConditions_solid), out var _))
                 {
                     NewProjectile(GetProjectileSource_FromThis(), vector3 + new Vector2(num6 * 20, -60f), Vector2.Zero, 698, num5, 0f, owner);
                     SoundEngine.PlayTrackedSound(SoundID.DD2_MonkStaffGroundImpact, base.Center);
                 }
                 else
                 {
                     SoundEngine.PlayTrackedSound(SoundID.DD2_MonkStaffGroundMiss, base.Center);
                 }
             }
         }
         if (type == 707)
         {
             Lighting.AddLight(player.Center, 0.75f, 0.9f, 1.15f);
             int num11 = Math.Sign(velocity.X);
             velocity = new Vector2(num11, 0f);
             if (ai[0] == 0f)
             {
                 rotation = new Vector2(num11, 0f - player.gravDir).ToRotation() + num4 + (float)Math.PI;
                 if (velocity.X < 0f)
                 {
                     rotation -= (float)Math.PI / 2f;
                 }
             }
             alpha -= 128;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             _ = ai[0] / num;
             float num12 = 1f;
             ai[0] += num12;
             rotation += (float)Math.PI * 2f * num2 / num * (float)num11;
             bool flag2 = ai[0] == (float)(int)(num / 2f);
             if (ai[0] >= num || (flag2 && !player.controlUseItem))
             {
                 Kill();
                 player.reuseDelay = 2;
             }
             else if (flag2)
             {
                 Vector2 mouseWorld2 = Main.MouseWorld;
                 int num13 = ((player.DirectionTo(mouseWorld2).X > 0f) ? 1 : (-1));
                 if ((float)num13 != velocity.X)
                 {
                     player.ChangeDir(num13);
                     velocity = new Vector2(num13, 0f);
                     netUpdate = true;
                     rotation -= (float)Math.PI;
                 }
             }
             if ((ai[0] == num12 || (ai[0] == (float)(int)(num / 2f) && active)) && owner == Main.myPlayer)
             {
                 Vector2 mouseWorld3 = Main.MouseWorld;
                 _ = player.DirectionTo(mouseWorld3) * 0f;
             }
             float num14 = rotation - (float)Math.PI / 4f * (float)num11;
             vector2 = (num14 + ((num11 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * (ai[0] / num) * num3;
             Vector2 vector4 = base.Center + (num14 + ((num11 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * 30f;
             Vector2 vector5 = num14.ToRotationVector2();
             Vector2 vector6 = vector5.RotatedBy((float)Math.PI / 2f * (float)spriteDirection);
             if (Main.rand.Next(2) == 0)
             {
                 Dust dust4 = Dust.NewDustDirect(vector4 - new Vector2(5f), 10, 10, 31, player.velocity.X, player.velocity.Y, 150);
                 dust4.velocity = DirectionTo(dust4.position) * 0.1f + dust4.velocity * 0.1f;
             }
             for (int j = 0; j < 4; j++)
             {
                 float num15 = 1f;
                 float num16 = 1f;
                 switch (j)
                 {
                 case 1:
                     num16 = -1f;
                     break;
                 case 2:
                     num16 = 1.25f;
                     num15 = 0.5f;
                     break;
                 case 3:
                     num16 = -1.25f;
                     num15 = 0.5f;
                     break;
                 }
                 if (Main.rand.Next(6) != 0)
                 {
                     Dust dust5 = Dust.NewDustDirect(position, 0, 0, 226, 0f, 0f, 100);
                     dust5.position = base.Center + vector5 * (60f + Main.rand.NextFloat() * 20f) * num16;
                     dust5.velocity = vector6 * (4f + 4f * Main.rand.NextFloat()) * num16 * num15;
                     dust5.noGravity = true;
                     dust5.noLight = true;
                     dust5.scale = 0.5f;
                     dust5.customData = this;
                     if (Main.rand.Next(4) == 0)
                     {
                         dust5.noGravity = false;
                     }
                 }
             }
         }
         position = vector - base.Size / 2f;
         position += vector2;
         spriteDirection = direction;
         timeLeft = 2;
         player.ChangeDir(direction);
         player.heldProj = whoAmI;
         player.SetDummyItemTime(2);
         player.itemRotation = MathHelper.WrapAngle(rotation);
     }
References Lighting.AddLight(), Entity.Center, Searches.Chain(), Player.ChangeDir(), Color, Dust.color, Player.controlUseItem, Dust.customData, SoundID.DD2_MonkStaffGroundImpact, SoundID.DD2_MonkStaffGroundMiss, Player.dead, Entity.DirectionTo(), WorldUtils.Find(), Player.gravDir, Player.heldProj, Player.itemRotation, Player.MountedCenter, Main.MouseWorld, Main.myPlayer, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.player, SoundEngine.PlayTrackedSound(), Dust.position, Main.rand, Player.reuseDelay, Player.RotatedRelativePoint(), Dust.scale, Player.SetDummyItemTime(), Dust.velocity, and Entity.velocity.