Terraria: Projectile.AI_152_SuperStarSlash
AI_152_SuperStarSlash()
void Projectile.AI_152_SuperStarSlash () inline private
     {
         float num = (float)Math.PI / 2f;
         bool flag = true;
         if (type == 976)
         {
             flag = false;
         }
         if (flag)
         {
             alpha -= 10;
             int num2 = 100;
             if (alpha < num2)
             {
                 alpha = num2;
             }
         }
         if (soundDelay == 0)
         {
             if (type == 977)
             {
                 soundDelay = -1;
                 SoundEngine.PlaySound(SoundID.Item1, position);
             }
             else if (type == 976)
             {
                 soundDelay = -1;
             }
             else
             {
                 soundDelay = 20 + Main.rand.Next(40);
                 SoundEngine.PlaySound(SoundID.Item9, position);
             }
         }
         if (ai[0] != 0f)
         {
             if (type == 976)
             {
                 velocity = velocity.RotatedBy(ai[0]);
             }
             else
             {
                 int num3 = 10 * MaxUpdates;
                 velocity = velocity.RotatedBy(ai[0] / (float)num3);
             }
         }
         if (type == 977)
         {
             velocity *= 0.96f;
             if (Main.rand.Next(8) == 0)
             {
                 Dust dust = Dust.NewDustDirect(base.Center, 0, 0, 172, velocity.X * 0.1f, velocity.Y * 0.1f, 100, default(Color), 0.9f);
                 dust.noGravity = true;
                 dust.position = base.Center;
                 dust.velocity = Main.rand.NextVector2Circular(1f, 1f) + velocity * 0.5f;
             }
         }
         if (type == 976)
         {
             if (Collision.LavaCollision(position, width, height))
             {
                 Kill();
                 return;
             }
             if (++frameCounter >= 2)
             {
                 frameCounter = 0;
                 if (++frame >= 7)
                 {
                     frame = 0;
                 }
             }
             float fromValue = 60 - timeLeft;
             float fromMax = ai[1] + 20f;
             float num4 = Utils.Remap(fromValue, ai[1], fromMax, 0f, 1f) * Utils.Remap(fromValue, ai[1], ai[1] + 60f, 1f, 0f);
             velocity = velocity.SafeNormalize(Vector2.UnitY) * (4f + 12f * (1f - num4));
             Opacity = Utils.Remap(fromValue, 0f, 10f, 0f, 1f) * Utils.Remap(fromValue, 30f, 60f, 1f, 0f);
             num = 0f;
             if (Main.rand.Next(3) == 0)
             {
                 Dust dust2 = Dust.NewDustDirect(position, width, height, 40, 0f, 0f, 0, default(Color), 1.2f);
                 dust2.noGravity = true;
                 dust2.velocity = velocity * 0.5f;
             }
             if (localAI[1] == 0f)
             {
                 localAI[1] = 1f;
                 for (int i = 0; i < 10; i++)
                 {
                     Dust.NewDustDirect(position, width, height, 40, 0f, 0f, 0, default(Color), 0.7f).velocity = velocity.SafeNormalize(Vector2.UnitY).RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.25f) * (Main.rand.NextFloat() * 3f);
                 }
             }
         }
         rotation = velocity.ToRotation() + num;
         tileCollide = false;
     }
References ai, alpha, Color, frame, frameCounter, Entity.height, SoundID.Item1, SoundID.Item9, Kill(), Collision.LavaCollision(), localAI, MaxUpdates, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Opacity, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.rand, Utils.Remap(), rotation, soundDelay, tileCollide, timeLeft, type, Dust.velocity, Entity.velocity, and Entity.width.