Terraria: Projectile.AI_189_Volcano
AI_189_Volcano()
void Projectile.AI_189_Volcano () inline private
     {
         if (soundDelay == 0)
         {
             soundDelay = -1;
             SoundEngine.PlaySound(SoundID.DD2_ExplosiveTrapExplode, base.Center);
         }
         alpha = (int)(255f * (1f - Utils.Remap(ai[0], 0f, 2f, 0f, 1f) * Utils.Remap(ai[0], 6f, 10f, 1f, 0f)));
         float num = width / 2;
         float num2 = height / 2;
         num = (num2 = 8f);
         scale = 1f + 1f * (ai[0] / 15f);
         if (++frameCounter >= 2)
         {
             frameCounter = 0;
             if (++frame >= 5)
             {
                 Kill();
                 return;
             }
         }
         ai[0] += 1f;
         if (ai[0] == 1f)
         {
             for (int i = 0; i < 20; i++)
             {
                 int num3 = Utils.SelectRandom<int>(Main.rand, 6, 259, 158);
                 Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(num, num2), num3, velocity.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 4f) * 0.6f) * (2f + 5f * Main.rand.NextFloat()), 200, default(Color), 1f + Main.rand.NextFloat()).customData = 0;
             }
             int num4 = Main.rand.Next(3, 7);
             for (int j = 0; j < num4 * 5; j++)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(num, num2), 31, velocity.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 4f) * 0.6f) * (2f + 5f * Main.rand.NextFloat()), 50, default(Color), 1f + Main.rand.NextFloat());
                 dust.noGravity = true;
                 dust.velocity *= 3f;
             }
             for (int k = 0; k < num4; k++)
             {
                 Gore.NewGorePerfect(base.Center + Main.rand.NextVector2Circular(num, num2) - new Vector2(16f, 16f), velocity.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 4f) * 0.6f) * (0f + 4f * Main.rand.NextFloat()), 61 + Main.rand.Next(3));
             }
         }
         for (int l = 0; l < 2; l++)
         {
             if (Main.rand.Next(3) < 2)
             {
                 Dust dust2 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(num, num2), 6, velocity.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 4f)) * (1.5f + 2f * Main.rand.NextFloat()), 90, default(Color), 2.5f);
                 dust2.noGravity = true;
                 dust2.fadeIn = 1f;
                 if (Main.rand.Next(6) < 3)
                 {
                     dust2.noGravity = false;
                     dust2.noLight = true;
                     dust2.fadeIn = 0.4f;
                     dust2.scale *= 0.3f;
                 }
                 else
                 {
                     dust2.velocity = DirectionFrom(dust2.position) * dust2.velocity.Length() * 0.25f;
                 }
                 dust2.customData = 0;
             }
         }
         for (int m = 0; m < 2; m++)
         {
             if (!(Main.rand.NextFloat() < 0.5f))
             {
                 int num5 = Utils.SelectRandom<int>(Main.rand, 6, 259, 158);
                 Dust dust3 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(num, num2), num5, velocity.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI / 4f) * 0.5f) * (1f + 2f * Main.rand.NextFloat()), 200, default(Color), 1f + Main.rand.NextFloat());
                 dust3.velocity *= new Vector2(0.6f, 1.5f);
                 dust3.customData = 0;
             }
         }
     }
References Color, Dust.customData, SoundID.DD2_ExplosiveTrapExplode, Dust.fadeIn, Dust.NewDustPerfect(), Gore.NewGorePerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, SoundEngine.PlaySound(), Dust.position, Main.rand, Utils.Remap(), Dust.scale, and Dust.velocity.