Terraria: Projectile.AI_190_NightsEdge
AI_190_NightsEdge()
void Projectile.AI_190_NightsEdge () inline private
     {
         if (localAI[0] == 0f && type == 984)
         {
             SoundEffectInstance soundEffectInstance = SoundEngine.PlaySound(SoundID.Item60, position);
             if (soundEffectInstance != null)
             {
                 soundEffectInstance.Volume *= 0.65f;
             }
         }
         localAI[0] += 1f;
         Player player = Main.player[owner];
         float num = localAI[0] / ai[1];
         float num2 = ai[0];
         float num3 = velocity.ToRotation();
         float num4 = (float)Math.PI * num2 * num + num3 + num2 * (float)Math.PI + player.fullRotation;
         rotation = num4;
         float num5 = 0.2f;
         float num6 = 1f;
         switch (type)
         {
         case 982:
             num5 = 0.6f;
             break;
         case 997:
             num5 = 0.6f;
             break;
         case 983:
             num5 = 1f;
             num6 = 1.2f;
             break;
         case 984:
             num5 = 0.6f;
             break;
         }
         base.Center = player.RotatedRelativePoint(player.MountedCenter) - velocity;
         scale = num6 + num * num5;
         if (type == 972)
         {
             if (Math.Abs(num2) < 0.2f)
             {
                 rotation += (float)Math.PI * 4f * num2 * 10f * num;
                 float num7 = Utils.Remap(localAI[0], 10f, ai[1] - 5f, 0f, 1f);
                 position += velocity.SafeNormalize(Vector2.Zero) * (45f * num7);
                 scale += num7 * 0.4f;
             }
             if (Main.rand.Next(2) == 0)
             {
                 float f = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
                 Vector2 vector = base.Center + f.ToRotationVector2() * 84f * scale;
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust dust = Dust.NewDustPerfect(vector, 14, null, 150, default(Color), 1.4f);
                     dust.noLight = (dust.noLightEmittence = true);
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     Dust.NewDustPerfect(vector, 27, new Vector2(player.velocity.X * 0.2f + (float)(player.direction * 3), player.velocity.Y * 0.2f), 100, default(Color), 1.4f).noGravity = true;
                 }
             }
         }
         if (type == 982)
         {
             float num8 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
             Vector2 vector2 = base.Center + num8.ToRotationVector2() * 84f * scale;
             Vector2 vector3 = (num8 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
             if (Main.rand.NextFloat() * 2f < Opacity)
             {
                 Dust dust2 = Dust.NewDustPerfect(base.Center + num8.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector3 * 1f, 100, Color.Lerp(Color.Gold, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                 dust2.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                 dust2.noGravity = true;
             }
             if (Main.rand.NextFloat() * 1.5f < Opacity)
             {
                 Dust.NewDustPerfect(vector2, 43, vector3 * 1f, 100, Color.White * Opacity, 1.2f * Opacity);
             }
         }
         if (type == 997)
         {
             float num9 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
             _ = base.Center + num9.ToRotationVector2() * 84f * scale;
             Vector2 vector4 = (num9 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
             if (Main.rand.NextFloat() * 2f < Opacity)
             {
                 Dust dust3 = Dust.NewDustPerfect(base.Center + num9.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 6, vector4 * 4f, 0, default(Color), 0.4f);
                 dust3.noGravity = true;
                 dust3.scale = 1.4f;
             }
         }
         if (type == 983)
         {
             float num10 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
             Vector2 vector5 = base.Center + num10.ToRotationVector2() * 84f * scale;
             Vector2 vector6 = (num10 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
             if (Main.rand.NextFloat() < Opacity)
             {
                 Dust dust4 = Dust.NewDustPerfect(base.Center + num10.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector6 * 1f, 100, Color.Lerp(Color.HotPink, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                 dust4.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                 dust4.noGravity = true;
             }
             if (Main.rand.NextFloat() * 1.5f < Opacity)
             {
                 Dust.NewDustPerfect(vector5, 43, vector6 * 1f, 100, Color.White * Opacity, 1.2f * Opacity);
             }
         }
         if (type == 984)
         {
             float num11 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
             Vector2 vector7 = base.Center + num11.ToRotationVector2() * 85f * scale;
             Vector2 vector8 = (num11 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
             Color value = new Color(64, 220, 96);
             Color value2 = new Color(15, 84, 125);
             Lighting.AddLight(base.Center, value2.ToVector3());
             if (Main.rand.NextFloat() * 2f < Opacity)
             {
                 Color value3 = Color.Lerp(value2, value, Utils.Remap(num, 0f, 0.6f, 0f, 1f));
                 value3 = Color.Lerp(value3, Color.White, Utils.Remap(num, 0.6f, 0.8f, 0f, 0.5f));
                 Dust dust5 = Dust.NewDustPerfect(base.Center + num11.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector8 * 1f, 100, Color.Lerp(value3, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                 dust5.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                 dust5.noGravity = true;
             }
             if (Main.rand.NextFloat() < Opacity)
             {
                 Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(num, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(num, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                 Dust dust6 = Dust.NewDustPerfect(vector7, 107, vector8 * 3f, 100, default(Color) * Opacity, 0.8f * Opacity);
                 dust6.velocity += player.velocity * 0.1f;
                 dust6.velocity += new Vector2(player.direction, 0f);
                 dust6.position -= dust6.velocity * 6f;
             }
         }
         scale *= ai[2];
         if (localAI[0] >= ai[1])
         {
             Kill();
         }
     }
References Lighting.AddLight(), Color, Entity.direction, Dust.fadeIn, Player.fullRotation, SoundID.Item60, Player.MountedCenter, Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.player, SoundEngine.PlaySound(), Dust.position, Main.rand, Utils.Remap(), Player.RotatedRelativePoint(), Dust.scale, Dust.velocity, and Entity.velocity.