Terraria: Projectile.CutTiles
CutTiles()
void Projectile.CutTiles () inline private
     {
         if (!CanCutTiles())
         {
             return;
         }
         AchievementsHelper.CurrentlyMining = true;
         bool flag = true;
         bool[] tileCutIgnorance = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
         DelegateMethods.tilecut_0 = TileCuttingContext.AttackProjectile;
         DelegateMethods.tileCutIgnore = tileCutIgnorance;
         Rectangle extensionBox;
         if (type == 461 || type == 632 || type == 642)
         {
             Utils.PlotTileLine(base.Center, base.Center + velocity * localAI[1], (float)width * scale, DelegateMethods.CutTiles);
         }
         else if (ProjectileID.Sets.IsAWhip[type])
         {
             flag = false;
             WhipPointsForCollision.Clear();
             FillWhipControlPoints(this, WhipPointsForCollision);
             Vector2 vector = new Vector2((float)width * scale / 2f, 0f);
             for (int i = 0; i < WhipPointsForCollision.Count; i++)
             {
                 Utils.PlotTileLine(WhipPointsForCollision[i] - vector, WhipPointsForCollision[i] + vector, (float)height * scale, DelegateMethods.CutTiles);
             }
         }
         else if (type == 756)
         {
             Utils.PlotTileLine(base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 200f * scale, 22f * scale, DelegateMethods.CutTiles);
         }
         else if (type == 927)
         {
             Vector2 end = base.Center + velocity.SafeNormalize(Vector2.UnitX) * 220f * scale;
             Utils.PlotTileLine(base.Center, end, 80f * scale, DelegateMethods.CutTiles);
         }
         else if (type == 802 || type == 842 || type == 938 || type == 939 || type == 940 || type == 941 || type == 942 || type == 943 || type == 944 || type == 945)
         {
             Utils.PlotTileLine(base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 10f, 10f * scale, DelegateMethods.CutTiles);
         }
         else if (type == 611)
         {
             Utils.PlotTileLine(base.Center, base.Center + velocity + velocity.SafeNormalize(Vector2.Zero) * 48f, (float)width * scale, DelegateMethods.CutTiles);
         }
         else if (type == 697 || type == 707)
         {
             float num = 40f;
             if (type == 707)
             {
                 num = 60f;
             }
             float f = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X);
             Utils.PlotTileLine(base.Center + f.ToRotationVector2() * (0f - num), base.Center + f.ToRotationVector2() * num, (float)width * scale, DelegateMethods.CutTiles);
         }
         else if (aiStyle == 190 || aiStyle == 191)
         {
             flag = false;
             Vector2 vector2 = (rotation - (float)Math.PI / 4f).ToRotationVector2() * 60f * scale;
             Vector2 vector3 = (rotation + (float)Math.PI / 4f).ToRotationVector2() * 60f * scale;
             float num2 = 60f * scale;
             Utils.PlotTileLine(base.Center + vector2, base.Center + vector3, num2, DelegateMethods.CutTiles);
         }
         else if (aiStyle == 19 && AI_019_Spears_GetExtensionHitbox(out extensionBox))
         {
             CutTilesAt(extensionBox.TopLeft(), extensionBox.Width, extensionBox.Height);
         }
         if (flag)
         {
             CutTilesAt(position, width, height);
         }
         AchievementsHelper.CurrentlyMining = false;
     }
References AI_019_Spears_GetExtensionHitbox(), aiStyle, CanCutTiles(), AchievementsHelper.CurrentlyMining, DelegateMethods.CutTiles(), CutTilesAt(), FillWhipControlPoints(), Player.GetTileCutIgnorance(), Entity.height, ProjectileID.Sets.IsAWhip, localAI, owner, Main.player, Utils.PlotTileLine(), Entity.position, rotation, scale, DelegateMethods.tilecut_0, DelegateMethods.tileCutIgnore, trap, type, Entity.velocity, WhipPointsForCollision, and Entity.width.
Referenced by Damage().