Terraria: Projectile.Damage
Damage()
void Projectile.Damage () inline
     {
         if (type == 18 || type == 72 || type == 86 || type == 87 || aiStyle == 31 || aiStyle == 32 || type == 226 || type == 378 || type == 613 || type == 650 || type == 882 || type == 888 || type == 895 || type == 896 || (type == 434 && localAI[0] != 0f) || type == 439 || type == 444 || (type == 451 && ((int)(ai[0] - 1f) / penetrate == 0 || ai[1] < 5f) && ai[0] != 0f) || type == 500 || type == 653 || type == 1018 || type == 460 || type == 633 || type == 600 || type == 601 || type == 602 || type == 535 || (type == 631 && localAI[1] == 0f) || (type == 537 && localAI[0] <= 30f) || type == 651 || (type == 188 && localAI[0] < 5f) || (aiStyle == 137 && ai[0] != 0f) || aiStyle == 138 || (type == 261 && velocity.Length() < 1.5f) || (type == 818 && ai[0] < 1f) || type == 831 || type == 970 || (type == 833 && ai[0] == 4f) || (type == 834 && ai[0] == 4f) || (type == 835 && ai[0] == 4f) || (type == 281 && ai[0] == -3f) || ((type == 598 || type == 636 || type == 614 || type == 971 || type == 975) && ai[0] == 1f) || (type == 923 && localAI[0] <= 60f) || (type == 919 && localAI[0] <= 60f) || (aiStyle == 15 && ai[0] == 0f && localAI[1] <= 12f) || type == 861 || (type >= 511 && type <= 513 && ai[1] >= 1f) || type == 1007 || (aiStyle == 93 && ai[0] != 0f && ai[0] != 2f) || (aiStyle == 10 && localAI[1] == -1f) || (type == 85 && localAI[0] >= 54f) || (Main.projPet[type] && type != 266 && type != 407 && type != 317 && (type != 388 || ai[0] != 2f) && (type < 390 || type > 392) && (type < 393 || type > 395) && (type != 533 || !(ai[0] >= 6f) || !(ai[0] <= 8f)) && (type < 625 || type > 628) && (type != 755 || ai[0] == 0f) && (type != 946 || ai[0] == 0f) && type != 758 && type != 951 && type != 963 && (type != 759 || frame == Main.projFrames[type] - 1) && type != 833 && type != 834 && type != 835 && type != 864 && (type != 623 || ai[0] != 2f)))
         {
             return;
         }
         Rectangle rectangle = Damage_GetHitbox();
         if (friendly && Main.getGoodWorld && aiStyle == 16 && Main.netMode == 1 && owner != Main.myPlayer && !npcProj)
         {
             BombsHurtPlayers(rectangle, Main.myPlayer);
             return;
         }
         if (friendly && owner == Main.myPlayer && !npcProj)
         {
             BombsHurtPlayers(rectangle, owner);
             if (!minion)
             {
                 CutTiles();
             }
         }
         if (owner == Main.myPlayer)
         {
             float num = 1f;
             if (ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy[type] && timeLeft > 3)
             {
                 num *= 2f;
             }
             if (ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary[type] && velocity.Length() < 0.5f)
             {
                 num *= 3f;
             }
             if (type == 34 && penetrate == 1)
             {
                 num *= 1f;
             }
             if (aiStyle == 15 && ai[0] == 0f)
             {
                 num *= 1.2f;
             }
             if (aiStyle == 15 && (ai[0] == 1f || ai[0] == 2f))
             {
                 num *= 2f;
             }
             if (type == 877 || type == 879 || type == 878)
             {
                 num = 0.1f + Main.player[owner].velocity.Length() / 7f * 0.9f;
             }
             if (type == 968)
             {
                 num = 1f;
                 switch ((int)ai[1])
                 {
                 case 0:
                     num = 1.5f;
                     break;
                 case 1:
                     num = 1f;
                     break;
                 case 2:
                     num = 1.5f;
                     break;
                 case 3:
                     num = 0.1f;
                     break;
                 case 4:
                     num = 1f;
                     break;
                 case 5:
                     num = 1f;
                     break;
                 case 6:
                     num = 1f;
                     break;
                 case 7:
                     num = 0.25f;
                     break;
                 case 8:
                     num = 1f;
                     break;
                 case 9:
                     num = 0.75f;
                     break;
                 case 10:
                     num = 0.5f;
                     break;
                 case 11:
                     num = 0.5f;
                     break;
                 case 12:
                     num = 0.5f;
                     break;
                 case 13:
                     num = 0.5f;
                     break;
                 case 14:
                     num = 0.5f;
                     break;
                 case 15:
                     num = 0.5f;
                     break;
                 case 16:
                     num = 0.5f;
                     break;
                 case 17:
                     num = 1.5f;
                     break;
                 case 18:
                     num = 1.6f;
                     break;
                 case 19:
                     num = 1.8f;
                     break;
                 case 20:
                     num = 1.9f;
                     break;
                 case 21:
                     num = 1.7f;
                     break;
                 case 22:
                     num = 2f;
                     break;
                 case 23:
                     num = 1.9f;
                     break;
                 }
             }
             if (type == 533 && localAI[2] >= 40f)
             {
                 num *= 0.5f;
             }
             bool flag = !npcProj && !trap;
             bool flag2 = usesOwnerMeleeHitCD && flag && owner < 255;
             bool flag3 = damage > 0;
             if (flag3)
             {
                 int[] array = localNPCImmunity;
                 if (type == 626 || type == 627 || type == 628)
                 {
                     Projectile projectile = FindStardustDragonHeadOfOwner();
                     if (projectile != null)
                     {
                         array = projectile.localNPCImmunity;
                     }
                 }
                 bool flag4 = true;
                 for (int i = 0; i < 200 && flag4; i++)
                 {
                     if (!Main.npc[i].active)
                     {
                         continue;
                     }
                     bool flag5 = (!usesLocalNPCImmunity && !usesIDStaticNPCImmunity) || (usesLocalNPCImmunity && array[i] == 0) || (usesIDStaticNPCImmunity && IsNPCIndexImmuneToProjectileType(type, i));
                     if (flag2 && !Main.player[owner].CanHitNPCWithMeleeHit(i))
                     {
                         flag5 = false;
                     }
                     if (!((!Main.npc[i].dontTakeDamage || NPCID.Sets.ZappingJellyfish[Main.npc[i].type]) && flag5) || (Main.npc[i].aiStyle == 112 && Main.npc[i].ai[2] > 1f))
                     {
                         continue;
                     }
                     Main.npc[i].position += Main.npc[i].netOffset;
                     bool flag6 = !Main.npc[i].friendly;
                     flag6 |= type == 318;
                     flag6 |= Main.npc[i].type == 22 && owner < 255 && Main.player[owner].killGuide;
                     flag6 |= Main.npc[i].type == 54 && owner < 255 && Main.player[owner].killClothier;
                     if (owner < 255 && !Main.player[owner].CanNPCBeHitByPlayerOrPlayerProjectile(Main.npc[i], this))
                     {
                         flag6 = false;
                     }
                     bool flag7 = Main.npc[i].friendly && !Main.npc[i].dontTakeDamageFromHostiles;
                     if ((friendly && (flag6 || NPCID.Sets.ZappingJellyfish[Main.npc[i].type])) || (hostile && flag7))
                     {
                         bool flag8 = maxPenetrate == 1 && !usesLocalNPCImmunity && !usesIDStaticNPCImmunity;
                         if (owner < 0 || Main.npc[i].immune[owner] == 0 || flag8)
{
                             bool flag9 = false;
                             if (type == 11 && (Main.npc[i].type == 47 || Main.npc[i].type == 57))
{
                                 flag9 = true;
                             }
                             else if (type == 31 && Main.npc[i].type == 69)
{
                                 flag9 = true;
                             }
                             else if (Main.npc[i].trapImmune && trap)
{
                                 flag9 = true;
                             }
                             else if (Main.npc[i].immortal && npcProj)
{
                                 flag9 = true;
                             }
                             if (!flag9 && (Main.npc[i].noTileCollide || !ownerHitCheck || CanHitWithMeleeWeapon(Main.npc[i])))
{
                                 bool flag10 = false;
                                 if (Main.npc[i].type == 414)
{
                                     Rectangle rect = Main.npc[i].getRect();
                                     int num2 = 8;
                                     rect.X -= num2;
                                     rect.Y -= num2;
                                     rect.Width += num2 * 2;
                                     rect.Height += num2 * 2;
                                     flag10 = Colliding(rectangle, rect);
                                 }
                                 else
{
                                     flag10 = Colliding(rectangle, Main.npc[i].getRect());
                                 }
                                 if (flag10)
{
                                     NPC nPC = Main.npc[i];
                                     if (NPCID.Sets.ZappingJellyfish[nPC.type])
{
                                         if ((nPC.dontTakeDamage || !Main.player[owner].CanNPCBeHitByPlayerOrPlayerProjectile(nPC, this)) && (aiStyle == 19 || aiStyle == 161 || aiStyle == 75 || aiStyle == 140 || ProjectileID.Sets.IsAWhip[type] || ProjectileID.Sets.AllowsContactDamageFromJellyfish[type]))
{
                                             Main.player[owner].TakeDamageFromJellyfish(i);
                                         }
                                         if (nPC.dontTakeDamage || !flag6)
{
                                             continue;
                                         }
                                     }
                                     if (type == 876)
{
                                         Vector2 vector = position;
                                         if (Main.rand.Next(20) == 0)
{
                                             tileCollide = false;
                                             position.X += Main.rand.Next(-256, 257);
                                         }
                                         if (Main.rand.Next(20) == 0)
{
                                             tileCollide = false;
                                             position.Y += Main.rand.Next(-256, 257);
                                         }
                                         if (Main.rand.Next(2) == 0)
{
                                             tileCollide = false;
                                         }
                                         if (Main.rand.Next(3) != 0)
{
                                             vector = position;
                                             position -= velocity * Main.rand.Next(0, 40);
                                             if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                 position = vector;
                                                 position -= velocity * Main.rand.Next(0, 40);
                                                 if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                     position = vector;
                                                 }
                                             }
                                         }
                                         velocity *= 0.6f;
                                         if (Main.rand.Next(7) == 0)
{
                                             velocity.X += (float)Main.rand.Next(30, 31) * 0.01f;
                                         }
                                         if (Main.rand.Next(7) == 0)
{
                                             velocity.Y += (float)Main.rand.Next(30, 31) * 0.01f;
                                         }
                                         damage = (int)((double)damage * 0.9);
                                         knockBack *= 0.9f;
                                         if (Main.rand.Next(20) == 0)
{
                                             knockBack *= 10f;
                                         }
                                         if (Main.rand.Next(50) == 0)
{
                                             damage *= 10;
                                         }
                                         if (Main.rand.Next(7) == 0)
{
                                             vector = position;
                                             position.X += Main.rand.Next(-64, 65);
                                             if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                 position = vector;
                                             }
                                         }
                                         if (Main.rand.Next(7) == 0)
{
                                             vector = position;
                                             position.Y += Main.rand.Next(-64, 65);
                                             if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                 position = vector;
                                             }
                                         }
                                         if (Main.rand.Next(14) == 0)
{
                                             velocity.X *= -1f;
                                         }
                                         if (Main.rand.Next(14) == 0)
{
                                             velocity.Y *= -1f;
                                         }
                                         if (Main.rand.Next(10) == 0)
{
                                             velocity *= (float)Main.rand.Next(1, 201) * 0.0005f;
                                         }
                                         if (tileCollide)
{
                                             ai[1] = 0f;
                                         }
                                         else
{
                                             ai[1] = 1f;
                                         }
                                         netUpdate = true;
                                     }
                                     bool flag11 = nPC.reflectsProjectiles;
                                     if (Main.getGoodWorld && NPCID.Sets.ReflectStarShotsInForTheWorthy[Main.npc[i].type] && (type == 955 || type == 728))
{
                                         flag11 = true;
                                     }
                                     if (flag11 && CanBeReflected() && nPC.CanReflectProjectile(this))
{
                                         nPC.ReflectProjectile(this);
                                         Main.npc[i].position -= Main.npc[i].netOffset;
                                         return;
                                     }
                                     if (type == 604)
{
                                         Main.player[owner].Counterweight(nPC.Center, damage, knockBack);
                                     }
                                     float num3 = knockBack;
                                     bool flag12 = false;
                                     int num4 = Main.player[owner].armorPenetration;
                                     float armorPenetrationPercent = 0f;
                                     bool flag13 = false;
                                     switch (type)
{
                                     case 442:
                                         flag13 = true;
                                         break;
                                     case 410:
                                         if (Main.remixWorld)
{
                                             num4 += 20;
                                         }
                                         break;
                                     case 864:
                                         num4 += 25;
                                         break;
                                     case 916:
                                         num4 += 50;
                                         break;
                                     case 917:
                                         num4 += 30;
                                         break;
                                     case 595:
                                         num4 += 20;
                                         break;
                                     case 493:
                                     case 494:
                                         num4 += 10;
                                         break;
                                     case 150:
                                     case 151:
                                     case 152:
                                         num4 += 10;
                                         break;
                                     case 189:
                                         num4 += 10;
                                         if (flag && Main.player[owner].strongBees)
{
                                             num4 += 5;
                                         }
                                         break;
                                     case 723:
                                     case 724:
                                     case 725:
                                     case 726:
                                         num4 += 25;
                                         break;
                                     case 532:
                                         num4 += 25;
                                         break;
                                     case 964:
                                         num4 += 20;
                                         break;
                                     case 969:
                                         num4 += 10;
                                         break;
                                     case 85:
                                         num4 += 15;
                                         break;
                                     case 877:
                                     case 878:
                                     case 879:
                                         num3 *= Main.player[owner].velocity.Length() / 7f;
                                         break;
                                     case 963:
                                         num3 *= 0.25f;
                                         break;
                                     case 976:
                                         num4 += 20;
                                         break;
                                     case 974:
                                         num4 += 5;
                                         break;
                                     case 977:
                                         num4 += 5;
                                         break;
                                     }
                                     if (flag13)
{
                                         Kill();
                                         return;
                                     }
                                     int num5 = (int)((float)damage * num);
                                     int num6 = 0;
                                     if (type > 0 && type < ProjectileID.Count && ProjectileID.Sets.StardustDragon[type])
{
                                         float value = (scale - 1f) * 100f;
                                         value = Utils.Clamp(value, 0f, 50f);
                                         num5 = (int)((float)num5 * (1f + value * 0.23f));
                                     }
                                     if (type > 0 && type < ProjectileID.Count && ProjectileID.Sets.StormTiger[type])
{
                                         int num7 = Math.Max(0, Main.player[owner].ownedProjectileCounts[831] - 1);
                                         num5 = (int)((float)num5 * (1f + (float)num7 * 0.4f));
                                     }
                                     if (type == 818)
{
                                         int num8 = Math.Max(0, Main.player[owner].ownedProjectileCounts[831] - 1);
                                         num5 = (int)((float)num5 * (1.5f + (float)num8 * 0.4f));
                                     }
                                     if (type == 963)
{
                                         int num9 = Math.Max(0, Main.player[owner].ownedProjectileCounts[970] - 1);
                                         int num10 = 3 + num9 / 2;
                                         if (CountEnemiesWhoAreImmuneToMeRightNow(num10) >= num10)
{
                                             return;
                                         }
                                         float num11 = 0.55f;
                                         if (Main.hardMode)
{
                                             num11 = 1.3f;
                                         }
                                         num5 = (int)((float)num5 * (1f + (float)num9 * num11));
                                     }
                                     if (flag && type == 189 && Main.player[owner].strongBees)
{
                                         num5 += 5;
                                     }
                                     if (flag)
{
                                         if (melee && Main.rand.Next(1, 101) <= Main.player[owner].meleeCrit)
{
                                             flag12 = true;
                                         }
                                         if (ranged && Main.rand.Next(1, 101) <= Main.player[owner].rangedCrit)
{
                                             flag12 = true;
                                         }
                                         if (magic && Main.rand.Next(1, 101) <= Main.player[owner].magicCrit)
{
                                             flag12 = true;
                                         }
                                         int num12 = type;
                                         if ((uint)(num12 - 688) <= 2u)
{
                                             if (Main.player[owner].setMonkT3)
{
                                                 if (Main.rand.Next(4) == 0)
{
                                                     flag12 = true;
                                                 }
                                             }
                                             else if (Main.player[owner].setMonkT2 && Main.rand.Next(6) == 0)
{
                                                 flag12 = true;
                                             }
                                         }
                                     }
                                     float num13 = 1f;
                                     if (type == 864)
{
                                         num13 = 0.75f;
                                     }
                                     if (type == 688 || type == 689 || type == 690)
{
                                         num13 /= 2f;
                                     }
                                     if (flag && (minion || ProjectileID.Sets.MinionShot[type] || sentry || ProjectileID.Sets.SentryShot[type]))
{
                                         bool flag14 = false;
                                         bool flag15 = false;
                                         bool flag16 = false;
                                         bool flag17 = false;
                                         bool flag18 = false;
                                         bool flag19 = false;
                                         bool flag20 = false;
                                         bool flag21 = false;
                                         bool flag22 = false;
                                         for (int j = 0; j < NPC.maxBuffs; j++)
{
                                             if (nPC.buffTime[j] >= 1)
{
                                                 switch (nPC.buffType[j])
{
                                                 case 307:
                                                     flag14 = true;
                                                     break;
                                                 case 309:
                                                     flag15 = true;
                                                     break;
                                                 case 313:
                                                     flag16 = true;
                                                     break;
                                                 case 310:
                                                     flag17 = true;
                                                     break;
                                                 case 315:
                                                     flag18 = true;
                                                     break;
                                                 case 326:
                                                     flag19 = true;
                                                     break;
                                                 case 319:
                                                     flag21 = true;
                                                     break;
                                                 case 316:
                                                     flag22 = true;
                                                     break;
                                                 case 340:
                                                     flag20 = true;
                                                     break;
                                                 }
                                             }
                                         }
                                         if (flag14)
{
                                             num6 += 4;
                                         }
                                         if (flag18)
{
                                             num6 += 6;
                                         }
                                         if (flag19)
{
                                             num6 += 7;
                                         }
                                         if (flag20)
{
                                             num6 += 6;
                                         }
                                         if (flag15)
{
                                             num6 += 9;
                                         }
                                         if (flag21)
{
                                             num6 += 8;
                                             if (Main.rand.Next(100) < 12)
{
                                                 flag12 = true;
                                             }
                                         }
                                         if (flag17)
{
                                             int num14 = 10;
                                             num6 += num14;
                                             int num15 = NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 916, (int)((float)num14 * num13), 0f, owner);
                                             Main.projectile[num15].localNPCImmunity[i] = -1;
                                             EmitBlackLightningParticles(nPC);
                                         }
                                         if (flag22)
{
                                             int num16 = 20;
                                             num6 += num16;
                                             if (Main.rand.Next(10) == 0)
{
                                                 flag12 = true;
                                             }
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
{
                                                 PositionInWorld = base.Center
                                             });
                                         }
                                         if (flag16)
{
                                             nPC.RequestBuffRemoval(313);
                                             int num17 = (int)((float)num5 * 1.75f);
                                             int num18 = NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 918, num17, 0f, owner);
                                             Main.projectile[num18].localNPCImmunity[i] = -1;
                                             num6 += num17;
                                         }
                                     }
                                     num6 = (int)((float)num6 * num13);
                                     num5 += num6;
                                     int num19 = ((!flag) ? Main.DamageVar(num5) : Main.DamageVar(num5, Main.player[owner].luck));
                                     if (type == 1002)
{
                                         num19 /= 2;
                                     }
                                     if (trap && NPCID.Sets.BelongsToInvasionOldOnesArmy[nPC.type])
{
                                         num19 /= 2;
                                     }
                                     if (type == 482 && (nPC.aiStyle == 6 || nPC.aiStyle == 37))
{
                                         num19 /= 2;
                                     }
                                     if (flag)
{
                                         Vector2 positionInWorld = Main.rand.NextVector2FromRectangle(nPC.Hitbox);
                                         ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
                                         particleOrchestraSettings.PositionInWorld = positionInWorld;
                                         ParticleOrchestraSettings settings = particleOrchestraSettings;
                                         switch (type)
{
                                         case 972:
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.NightsEdge, settings, owner);
                                             break;
                                         case 973:
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TrueNightsEdge, settings, owner);
                                             break;
                                         case 984:
                                         case 985:
                                             settings.MovementVector = velocity;
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TerraBlade, settings, owner);
                                             break;
                                         case 982:
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.Excalibur, settings, owner);
                                             break;
                                         case 983:
                                             ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TrueExcalibur, settings, owner);
                                             break;
                                         }
                                     }
                                     if (type == 604)
{
                                         friendly = false;
                                         ai[1] = 1000f;
                                     }
                                     if ((type == 400 || type == 401 || type == 402) && nPC.type >= 13 && nPC.type <= 15)
{
                                         num19 = (int)((double)num19 * 0.65);
                                         if (penetrate > 1)
{
                                             penetrate--;
                                         }
                                     }
                                     if (type == 710 && !WorldUtils.Find(base.Center.ToTileCoordinates(), Searches.Chain(new Searches.Down(12), _cachedConditions_notNull, _cachedConditions_solid), out var _))
{
                                         num19 = (int)((float)num19 * 1.5f);
                                     }
                                     if (type == 504 || type == 954 || type == 979)
{
                                         float num20 = (60f - ai[0]) / 2f;
                                         ai[0] += num20;
                                     }
                                     if (aiStyle == 3 && type != 301 && type != 866 && type != 902)
{
                                         if (ai[0] == 0f)
{
                                             if (type == 106)
{
                                                 LightDisc_Bounce(base.Center + velocity.SafeNormalize(Vector2.UnitX) * 8f, (-velocity).SafeNormalize(Vector2.UnitX));
                                             }
                                             velocity.X = 0f - velocity.X;
                                             velocity.Y = 0f - velocity.Y;
                                             netUpdate = true;
                                         }
                                         ai[0] = 1f;
                                     }
                                     else if (type == 951)
{
                                         Vector2 vector2 = (nPC.Center - base.Center).SafeNormalize(Vector2.Zero);
                                         vector2.X += (-0.5f + Main.rand.NextFloat()) * 13f;
                                         vector2.Y = -5f;
                                         velocity.X = vector2.X;
                                         velocity.Y = vector2.Y;
                                         netUpdate = true;
                                     }
                                     else if (type == 582 || type == 902)
{
                                         if (ai[0] != 0f)
{
                                             direction *= -1;
                                         }
                                     }
                                     else if (type == 612 || type == 953 || type == 978)
{
                                         direction = Main.player[owner].direction;
                                     }
                                     else if (type == 624)
{
                                         float num21 = 1f;
                                         if (nPC.knockBackResist > 0f)
{
                                             num21 = 1f / nPC.knockBackResist;
                                         }
                                         knockBack = 4f * num21;
                                         num3 = knockBack;
                                         if (nPC.Center.X < base.Center.X)
{
                                             direction = 1;
                                         }
                                         else
{
                                             direction = -1;
                                         }
                                     }
                                     else if (aiStyle == 16)
{
                                         if (timeLeft > 3)
{
                                             timeLeft = 3;
                                         }
                                         if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                     }
                                     else if (aiStyle == 68)
{
                                         if (timeLeft > 3)
{
                                             timeLeft = 3;
                                         }
                                         if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                     }
                                     else if (aiStyle == 50)
{
                                         if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                     }
                                     else if (type == 908)
{
                                         if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                     }
                                     if (type == 509)
{
                                         int num22 = Main.rand.Next(2, 6);
                                         for (int k = 0; k < num22; k++)
{
                                             Vector2 vector3 = new Vector2(Main.rand.Next(-100, 101), Main.rand.Next(-100, 101));
                                             vector3 += velocity * 3f;
                                             vector3.Normalize();
                                             vector3 *= (float)Main.rand.Next(35, 81) * 0.1f;
                                             int num23 = (int)((double)damage * 0.5);
                                             NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector3.X, vector3.Y, 504, num23, knockBack * 0.2f, owner);
                                         }
                                     }
                                     if ((type == 476 || type == 950) && !npcProj)
{
                                         float x = Main.player[owner].Center.X;
                                         if (nPC.Center.X < x)
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                     }
                                     if (type == 598 || type == 636 || type == 614 || type == 971 || type == 975)
{
                                         ai[0] = 1f;
                                         ai[1] = i;
                                         velocity = (nPC.Center - base.Center) * 0.75f;
                                         netUpdate = true;
                                     }
                                     if (type >= 511 && type <= 513)
{
                                         ai[1] += 1f;
                                         netUpdate = true;
                                     }
                                     if (type == 659)
{
                                         timeLeft = 0;
                                     }
                                     if (type == 524)
{
                                         netUpdate = true;
                                         ai[0] += 50f;
                                     }
                                     if ((type == 688 || type == 689 || type == 690) && nPC.type != 68 && nPC.defense < 999)
{
                                         armorPenetrationPercent = 1f;
                                     }
                                     if (aiStyle == 39)
{
                                         if (ai[1] == 0f)
{
                                             ai[1] = i + 1;
                                             netUpdate = true;
                                         }
                                         if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) < position.X + (float)(width / 2))
{
                                             direction = 1;
                                         }
                                         else
{
                                             direction = -1;
                                         }
                                     }
                                     if (type == 41 && timeLeft > 1)
{
                                         timeLeft = 1;
                                     }
                                     if (aiStyle == 99)
{
                                         Main.player[owner].Counterweight(nPC.Center, damage, knockBack);
                                         if (nPC.Center.X < Main.player[owner].Center.X)
{
                                             direction = -1;
                                         }
                                         else
{
                                             direction = 1;
                                         }
                                         if (ai[0] >= 0f)
{
                                             Vector2 vector4 = base.Center - nPC.Center;
                                             vector4.Normalize();
                                             float num24 = 16f;
                                             velocity *= -0.5f;
                                             velocity += vector4 * num24;
                                             netUpdate = true;
                                             localAI[0] += 20f;
                                             if (!Collision.CanHit(position, width, height, Main.player[owner].position, Main.player[owner].width, Main.player[owner].height))
{
                                                 localAI[0] += 40f;
                                                 num19 = (int)((double)num19 * 0.75);
                                             }
                                         }
                                     }
                                     if (type == 856 && !Collision.CanHit(position, width, height, Main.player[owner].position, Main.player[owner].width, Main.player[owner].height))
{
                                         num19 = (int)((double)num19 * 0.75);
                                     }
                                     if (aiStyle == 93)
{
                                         if (ai[0] == 0f)
{
                                             ai[1] = 0f;
                                             int num25 = -i - 1;
                                             ai[0] = num25;
                                             velocity = nPC.Center - base.Center;
                                         }
                                         num19 = ((ai[0] != 2f) ? ((int)((double)num19 * 0.15)) : ((int)((double)num19 * 1.35)));
                                     }
                                     if (flag)
{
                                         int num26 = Item.NPCtoBanner(nPC.BannerID());
                                         if (num26 >= 0)
{
                                             Main.player[Main.myPlayer].lastCreatureHit = num26;
                                         }
                                     }
                                     if (Main.netMode != 2 && flag)
{
                                         int num27 = Item.NPCtoBanner(nPC.BannerID());
                                         if (num27 > 0 && Main.player[owner].HasNPCBannerBuff(num27))
{
                                             num19 = ((!Main.expertMode) ? ((int)((float)num19 * ItemID.Sets.BannerStrength[Item.BannerToItem(num27)].NormalDamageDealt)) : ((int)((float)num19 * ItemID.Sets.BannerStrength[Item.BannerToItem(num27)].ExpertDamageDealt)));
                                         }
                                     }
                                     if (Main.expertMode)
{
                                         if ((type == 30 || type == 397 || type == 517 || type == 28 || type == 37 || type == 516 || type == 29 || type == 470 || type == 637 || type == 108 || type == 281 || type == 588 || type == 519 || type == 773 || type == 183 || type == 181 || type == 566 || type == 1002) && nPC.type >= 13 && nPC.type <= 15)
{
                                             num19 /= 5;
                                         }
                                         if (type == 280 && ((nPC.type >= 134 && nPC.type <= 136) || nPC.type == 139))
{
                                             num19 = (int)((double)num19 * 0.75);
                                         }
                                     }
                                     if (Main.netMode != 2 && nPC.type == 439 && type >= 0 && type <= ProjectileID.Count && ProjectileID.Sets.CultistIsResistantTo[type])
{
                                         num19 = (int)((float)num19 * 0.75f);
                                     }
                                     if (type == 497 && penetrate != 1)
{
                                         ai[0] = 25f;
                                         float num28 = velocity.Length();
                                         Vector2 vector5 = nPC.Center - base.Center;
                                         vector5.Normalize();
                                         vector5 *= num28;
                                         velocity = -vector5 * 0.9f;
                                         netUpdate = true;
                                     }
                                     if (type == 323 && (nPC.type == 159 || nPC.type == 158))
{
                                         num19 *= 10;
                                     }
                                     if (type == 981 && nPC.type == 104)
{
                                         num19 *= 3;
                                     }
                                     if (type == 294)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 265)
{
                                         damage = (int)((double)damage * 0.75);
                                     }
                                     if (type == 355)
{
                                         damage = (int)((double)damage * 0.75);
                                     }
                                     if (type == 114)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 76 || type == 78 || type == 77)
{
                                         damage = (int)((double)damage * 0.95);
                                     }
                                     if (type == 85)
{
                                         damage = (int)((double)damage * 0.85);
                                     }
                                     if (type == 866)
{
                                         damage = (int)((double)damage * 0.8);
                                     }
                                     if (type == 841)
{
                                         damage = (int)((double)damage * 0.5);
                                     }
                                     if (type == 914)
{
                                         damage = (int)((double)damage * 0.6);
                                     }
                                     if (type == 952)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 913)
{
                                         damage = (int)((double)damage * 0.66);
                                     }
                                     if (type == 912)
{
                                         damage = (int)((double)damage * 0.7);
                                     }
                                     if (type == 847)
{
                                         damage = (int)((double)damage * 0.8);
                                     }
                                     if (type == 848)
{
                                         damage = (int)((double)damage * 0.95);
                                     }
                                     if (type == 849)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 915)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 931)
{
                                         damage = (int)((double)damage * 0.8);
                                     }
                                     if (type == 242)
{
                                         damage = (int)((double)damage * 0.85);
                                     }
                                     if (type == 323)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 5)
{
                                         damage = (int)((double)damage * 0.9);
                                     }
                                     if (type == 4)
{
                                         damage = (int)((double)damage * 0.95);
                                     }
                                     if (type == 309)
{
                                         damage = (int)((double)damage * 0.85);
                                     }
                                     if (type == 132)
{
                                         damage = (int)((double)damage * 0.85);
                                     }
                                     if (type == 985)
{
                                         damage = (int)((double)damage * 0.75);
                                     }
                                     if (type == 950)
{
                                         damage = (int)((double)damage * 0.98);
                                     }
                                     if (type == 964)
{
                                         damage = (int)((double)damage * 0.85);
                                     }
                                     if (type == 477 && penetrate > 1)
{
                                         int[] array2 = new int[10];
                                         int num29 = 0;
                                         int num30 = 700;
                                         int num31 = 20;
                                         for (int l = 0; l < 200; l++)
{
                                             if (l == i || !Main.npc[l].CanBeChasedBy(this))
{
                                                 continue;
                                             }
                                             float num32 = (base.Center - Main.npc[l].Center).Length();
                                             if (num32 > (float)num31 && num32 < (float)num30 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[l].Center, 1, 1))
{
                                                 array2[num29] = l;
                                                 num29++;
                                                 if (num29 >= 9)
{
                                                     break;
                                                 }
                                             }
                                         }
                                         if (num29 > 0)
{
                                             num29 = Main.rand.Next(num29);
                                             Vector2 vector6 = Main.npc[array2[num29]].Center - base.Center;
                                             float num33 = velocity.Length();
                                             vector6.Normalize();
                                             velocity = vector6 * num33;
                                             netUpdate = true;
                                         }
                                     }
                                     if (type == 261 && velocity.Length() < 3.5f)
{
                                         num19 /= 2;
                                         num3 /= 2f;
                                     }
                                     if (flag && melee && Main.player[owner].parryDamageBuff && !ProjectileID.Sets.DontApplyParryDamageBuff[type])
{
                                         num19 *= 5;
                                         Main.player[owner].parryDamageBuff = false;
                                         Main.player[owner].ClearBuff(198);
                                     }
                                     StatusNPC(i);
                                     if (flag && nPC.life > 5)
{
                                         TryDoingOnHitEffects(nPC);
                                     }
                                     if (ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags[type])
{
                                         nPC.UpdateNPC_BuffSetFlags(lowerBuffTime: false);
                                     }
                                     if (type == 317)
{
                                         ai[1] = -1f;
                                         netUpdate = true;
                                     }
                                     int num34 = direction;
                                     switch (type)
{
                                     case 697:
                                     case 699:
                                     case 707:
                                     case 708:
                                     case 759:
                                         num34 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                         break;
                                     }
                                     if (aiStyle == 188 || aiStyle == 189 || aiStyle == 190 || aiStyle == 191)
{
                                         num34 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                     }
                                     if (aiStyle == 15)
{
                                         num34 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                         if (ai[0] == 0f)
{
                                             num3 *= 0.35f;
                                         }
                                         if (ai[0] == 6f)
{
                                             num3 *= 0.5f;
                                         }
                                     }
                                     if (flag && !hostile)
{
                                         num19 += nPC.checkArmorPenetration(num4, armorPenetrationPercent);
                                     }
                                     NPCKillAttempt attempt = new NPCKillAttempt(nPC);
                                     int num35 = ((!flag) ? ((int)nPC.StrikeNPCNoInteraction(num19, num3, num34, flag12)) : ((int)nPC.StrikeNPC(num19, num3, num34, flag12)));
                                     if (flag && attempt.DidNPCDie())
{
                                         Main.player[owner].OnKillNPC(ref attempt, this);
                                     }
                                     if (flag && Main.player[owner].accDreamCatcher)
{
                                         Main.player[owner].addDPS(num35);
                                     }
                                     bool flag23 = !nPC.immortal;
                                     bool flag24 = num35 > 0 && nPC.lifeMax > 5 && friendly && !hostile && aiStyle != 59;
                                     bool flag25 = false;
                                     if (flag23 && active && timeLeft > 10 && nPC.active && nPC.type == 676 && CanBeReflected())
{
                                         nPC.ReflectProjectile(this);
                                         penetrate++;
                                     }
                                     if (flag && flag23)
{
                                         if (type == 997 && (!nPC.immortal || flag25) && !nPC.SpawnedFromStatue && !NPCID.Sets.CountsAsCritter[nPC.type])
{
                                             Main.player[owner].HorsemansBlade_SpawnPumpkin(i, (int)((float)damage * 1f), knockBack);
                                         }
                                         if (type == 756 && penetrate == 1)
{
                                             damage = 0;
                                             penetrate = -1;
                                             flag4 = false;
                                         }
                                         if ((flag25 || nPC.value > 0f) && Main.player[owner].hasLuckyCoin && Main.rand.Next(5) == 0)
{
                                             int num36 = 71;
                                             if (Main.rand.Next(10) == 0)
{
                                                 num36 = 72;
                                             }
                                             if (Main.rand.Next(100) == 0)
{
                                                 num36 = 73;
                                             }
                                             int num37 = Item.NewItem(GetItemSource_OnHit(nPC, 2), (int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height, num36);
                                             Main.item[num37].stack = Main.rand.Next(1, 11);
                                             Main.item[num37].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                                             Main.item[num37].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num34;
                                             Main.item[num37].timeLeftInWhichTheItemCannotBeTakenByEnemies = 60;
                                             if (Main.netMode == 1)
{
                                                 NetMessage.SendData(148, -1, -1, null, num37);
                                             }
                                         }
                                         if (type == 999 && owner == Main.myPlayer && Main.rand.Next(3) == 0)
{
                                             Player player = Main.player[owner];
                                             Vector2 vector7 = (base.Center - nPC.Center).SafeNormalize(Vector2.Zero) * 0.25f;
                                             int dmg = damage / 2;
                                             float kB = knockBack;
                                             int num38 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector7.X, vector7.Y, player.beeType(), player.beeDamage(dmg), player.beeKB(kB), owner);
                                             Main.projectile[num38].melee = true;
                                         }
                                         if (flag24)
{
                                             if (type == 304 && !Main.player[owner].moonLeech)
{
                                                 vampireHeal(num35, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                             }
                                             if (nPC.canGhostHeal || flag25)
{
                                                 if (Main.player[owner].ghostHeal && !Main.player[owner].moonLeech)
{
                                                     ghostHeal(num35, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                                 }
                                                 if (Main.player[owner].ghostHurt)
{
                                                     ghostHurt(num35, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                                 }
                                                 if (magic && Main.player[owner].setNebula && Main.player[owner].nebulaCD == 0 && Main.rand.Next(3) == 0)
{
                                                     Main.player[owner].nebulaCD = 30;
                                                     int num39 = Utils.SelectRandom<int>(Main.rand, 3453, 3454, 3455);
                                                     int num40 = Item.NewItem(GetItemSource_OnHit(nPC, 1), (int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height, num39);
                                                     Main.item[num40].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                                                     Main.item[num40].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num34;
                                                     if (Main.netMode == 1)
{
                                                         NetMessage.SendData(21, -1, -1, null, num40);
                                                     }
                                                 }
                                             }
                                             if (melee && Main.player[owner].beetleOffense && (!nPC.immortal || flag25))
{
                                                 if (Main.player[owner].beetleOrbs == 0)
{
                                                     Main.player[owner].beetleCounter += num35 * 3;
                                                 }
                                                 else if (Main.player[owner].beetleOrbs == 1)
{
                                                     Main.player[owner].beetleCounter += num35 * 2;
                                                 }
                                                 else
{
                                                     Main.player[owner].beetleCounter += num35;
                                                 }
                                                 Main.player[owner].beetleCountdown = 0;
                                             }
                                             if (arrow && type != 631 && Main.player[owner].phantasmTime > 0)
{
                                                 Vector2 source = Main.player[owner].position + Main.player[owner].Size * Utils.RandomVector2(Main.rand, 0f, 1f);
                                                 Vector2 vector8 = nPC.DirectionFrom(source) * 6f;
                                                 int num41 = (int)((float)damage * 0.3f);
                                                 NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num41, 0f, owner, i);
                                                 NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num41, 0f, owner, i, 15f);
                                                 NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num41, 0f, owner, i, 30f);
                                             }
                                             Player player2 = Main.player[owner];
                                             switch (type)
{
                                             case 914:
                                                 player2.AddBuff(314, 180);
                                                 break;
                                             case 847:
                                                 player2.AddBuff(308, 180);
                                                 break;
                                             case 849:
                                                 player2.AddBuff(311, 180);
                                                 break;
                                             case 912:
{
                                                 int num42 = 15;
                                                 if (!player2.coolWhipBuff)
{
                                                     NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 917, num42, 0f, owner);
                                                     player2.coolWhipBuff = true;
                                                 }
                                                 player2.AddBuff(312, 180);
                                                 break;
                                             }
                                             }
                                         }
                                     }
                                     if (flag && (melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant == 7)
{
                                         NewProjectile(GetProjectileSource_FromThis(), nPC.Center.X, nPC.Center.Y, nPC.velocity.X, nPC.velocity.Y, 289, 0, 0f, owner);
                                     }
                                     if (flag && type == 913)
{
                                         localAI[0] = 1f;
                                     }
                                     if (Main.netMode != 0)
{
                                         if (flag12)
{
                                             NetMessage.SendData(28, -1, -1, null, i, num19, num3, num34, 1);
                                         }
                                         else
{
                                             NetMessage.SendData(28, -1, -1, null, i, num19, num3, num34);
                                         }
                                     }
                                     if (type == 916)
{
                                         EmitBlackLightningParticles(nPC);
                                     }
                                     if (type >= 390 && type <= 392)
{
                                         localAI[1] = 20f;
                                     }
                                     if (usesIDStaticNPCImmunity)
{
                                         if (penetrate != 1 || appliesImmunityTimeOnSingleHits)
{
                                             nPC.immune[owner] = 0;
                                             perIDStaticNPCImmunity[type][i] = Main.GameUpdateCount + (uint)idStaticNPCHitCooldown;
                                         }
                                     }
                                     else if (type == 434)
{
                                         numUpdates = 0;
                                     }
                                     else if (type == 598 || type == 636 || type == 614)
{
                                         Point[] bufferForScan = _javelinsMax6;
                                         if (type == 636)
{
                                             bufferForScan = _javelinsMax8;
                                         }
                                         if (type == 614)
{
                                             bufferForScan = _javelinsMax10;
                                         }
                                         KillOldestJavelin(whoAmI, type, i, bufferForScan);
                                     }
                                     else if (type == 632)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 514)
{
                                         nPC.immune[owner] = 1;
                                     }
                                     else if (type == 611)
{
                                         if (localAI[1] <= 0f)
{
                                             NewProjectile(GetProjectileSource_FromThis(), nPC.Center.X, nPC.Center.Y, 0f, 0f, 612, damage, 10f, owner, 0f, 0.85f + Main.rand.NextFloat() * 1.15f);
                                         }
                                         localAI[1] = 4f;
                                     }
                                     else if (type == 595 || type == 735)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 927)
{
                                         nPC.immune[owner] = 4;
                                     }
                                     else if (type == 286)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 443)
{
                                         nPC.immune[owner] = 8;
                                     }
                                     else if (type >= 424 && type <= 426)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 634 || type == 635)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 659)
{
                                         nPC.immune[owner] = 5;
                                     }
                                     else if (type == 246)
{
                                         nPC.immune[owner] = 7;
                                     }
                                     else if (type == 249)
{
                                         nPC.immune[owner] = 7;
                                     }
                                     else if (type == 16)
{
                                         nPC.immune[owner] = 8;
                                     }
                                     else if (type == 409)
{
                                         nPC.immune[owner] = 6;
                                     }
                                     else if (type == 311)
{
                                         nPC.immune[owner] = 7;
                                     }
                                     else if (type == 582 || type == 902)
{
                                         nPC.immune[owner] = 7;
                                         if (ai[0] != 1f)
{
                                             ai[0] = 1f;
                                             netUpdate = true;
                                         }
                                     }
                                     else
{
                                         if (type == 451)
{
                                             if (ai[0] == 0f)
{
                                                 ai[0] += penetrate;
                                             }
                                             else
{
                                                 ai[0] -= penetrate + 1;
                                             }
                                             ai[1] = 0f;
                                             netUpdate = true;
                                             Main.npc[i].position -= Main.npc[i].netOffset;
                                             break;
                                         }
                                         if (type == 864)
{
                                             array[i] = 10;
                                             nPC.immune[owner] = 0;
                                             if (ai[0] > 0f)
{
                                                 ai[0] = -1f;
                                                 ai[1] = 0f;
                                                 netUpdate = true;
                                             }
                                         }
                                         else if (type == 661 || type == 856)
{
                                             array[i] = 8;
                                             nPC.immune[owner] = 0;
                                         }
                                         else if (type == 866)
{
                                             array[i] = -1;
                                             nPC.immune[owner] = 0;
                                             penetrate--;
                                             if (penetrate == 0)
{
                                                 penetrate = 1;
                                                 damage = 0;
                                                 ai[1] = -1f;
                                                 netUpdate = true;
                                                 Main.npc[i].position -= Main.npc[i].netOffset;
                                                 break;
                                             }
                                             if (owner == Main.myPlayer)
{
                                                 int num43 = FindTargetWithLineOfSight();
                                                 float num44 = ai[1];
                                                 ai[1] = num43;
                                                 if (ai[1] != num44)
{
                                                     netUpdate = true;
                                                 }
                                                 if (num43 != -1)
{
                                                     velocity = velocity.Length() * DirectionTo(Main.npc[num43].Center);
                                                 }
                                             }
                                         }
                                         else if (usesLocalNPCImmunity && localNPCHitCooldown != -2)
{
                                             nPC.immune[owner] = 0;
                                             array[i] = localNPCHitCooldown;
                                         }
                                         else if (penetrate != 1 || appliesImmunityTimeOnSingleHits)
{
                                             nPC.immune[owner] = 10;
                                         }
                                     }
                                     if (type == 710)
{
                                         BetsySharpnel(i);
                                     }
                                     if (penetrate > 0 && type != 317 && type != 866)
{
                                         if (type == 357)
{
                                             damage = (int)((double)damage * 0.8);
                                         }
                                         penetrate--;
                                         if (penetrate == 0)
{
                                             Main.npc[i].position -= Main.npc[i].netOffset;
                                             if (stopsDealingDamageAfterPenetrateHits)
{
                                                 penetrate = -1;
                                                 damage = 0;
                                             }
                                             flag4 = false;
                                         }
                                     }
                                     if (aiStyle == 7)
{
                                         ai[0] = 1f;
                                         damage = 0;
                                         netUpdate = true;
                                     }
                                     else if (aiStyle == 13)
{
                                         ai[0] = 1f;
                                         netUpdate = true;
                                     }
                                     else if (aiStyle == 69)
{
                                         ai[0] = 1f;
                                         netUpdate = true;
                                     }
                                     else if (type == 607)
{
                                         ai[0] = 1f;
                                         netUpdate = true;
                                         friendly = false;
                                     }
                                     else if (type == 638 || type == 639 || type == 640)
{
                                         array[i] = -1;
                                         nPC.immune[owner] = 0;
                                         damage = (int)((double)damage * 0.96);
                                     }
                                     else if (type == 617)
{
                                         array[i] = 8;
                                         nPC.immune[owner] = 0;
                                     }
                                     else if (type == 656)
{
                                         array[i] = 8;
                                         nPC.immune[owner] = 0;
                                         localAI[0] += 1f;
                                     }
                                     else if (type == 618)
{
                                         array[i] = 20;
                                         nPC.immune[owner] = 0;
                                     }
                                     else if (type == 642)
{
                                         array[i] = 10;
                                         nPC.immune[owner] = 0;
                                     }
                                     else if (type == 857)
{
                                         array[i] = 10;
                                         nPC.immune[owner] = 0;
                                     }
                                     else if (type == 611 || type == 612)
{
                                         array[i] = 6;
                                         nPC.immune[owner] = 4;
                                     }
                                     else if (type == 645)
{
                                         array[i] = -1;
                                         nPC.immune[owner] = 0;
                                         if (ai[1] != -1f)
{
                                             ai[0] = 0f;
                                             ai[1] = -1f;
                                             netUpdate = true;
                                         }
                                     }
                                     numHits++;
                                     if (type == 697)
{
                                         if (ai[0] >= 42f)
{
                                             localAI[1] = 1f;
                                         }
                                     }
                                     else if (type == 699)
{
                                         SummonMonkGhast();
                                     }
                                     else if (type == 706)
{
                                         damage = (int)((float)damage * 0.95f);
                                     }
                                     else if (type == 728)
{
                                         SummonSuperStarSlash(nPC.Center);
                                     }
                                     else if (type == 34)
{
                                         if (ai[0] == -1f)
{
                                             ai[1] = -1f;
                                             netUpdate = true;
                                         }
                                     }
                                     else if (type == 79)
{
                                         if (ai[0] == -1f)
{
                                             ai[1] = -1f;
                                             netUpdate = true;
                                         }
                                         ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
{
                                             PositionInWorld = nPC.Center,
                                             MovementVector = velocity
                                         });
                                     }
                                     else if (type == 931)
{
                                         int num45 = FindTargetWithLineOfSight();
                                         if (num45 != -1)
{
                                             ai[0] = num45;
                                             netUpdate = true;
                                         }
                                     }
                                     else if (aiStyle == 165)
{
                                         if (nPC.active)
{
                                             Main.player[owner].MinionAttackTargetNPC = i;
                                         }
                                     }
                                     else if (type == 623)
{
                                         ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.StardustPunch, new ParticleOrchestraSettings
{
                                             PositionInWorld = Vector2.Lerp(base.Center, nPC.Hitbox.ClosestPointInRect(base.Center), 0.5f) + new Vector2(0f, Main.rand.NextFloatDirection() * 10f),
                                             MovementVector = new Vector2(direction, Main.rand.NextFloatDirection() * 0.5f) * (3f + 3f * Main.rand.NextFloat())
                                         });
                                     }
                                     if (flag2)
{
                                         Main.player[owner].SetMeleeHitCooldown(i, Main.player[owner].itemAnimation);
                                     }
                                 }
                             }
                         }
                     }
                     Main.npc[i].position -= Main.npc[i].netOffset;
                 }
             }
             if (flag3 && Main.player[Main.myPlayer].hostile)
             {
                 for (int m = 0; m < 255; m++)
                 {
                     if (m == owner)
                     {
                         continue;
                     }
                     Player player3 = Main.player[m];
                     if (!player3.active || player3.dead || player3.immune || !player3.hostile || playerImmune[m] > 0 || (Main.player[Main.myPlayer].team != 0 && Main.player[Main.myPlayer].team == player3.team))
                     {
                         continue;
                     }
                     bool flag26 = !ownerHitCheck;
                     if (ownerHitCheck)
                     {
                         flag26 |= CanHitWithMeleeWeapon(player3);
                     }
                     if (!flag26 || !Colliding(rectangle, player3.getRect()))
                     {
                         continue;
                     }
                     if (aiStyle == 3)
                     {
                         if (ai[0] == 0f)
{
                             velocity.X = 0f - velocity.X;
                             velocity.Y = 0f - velocity.Y;
                             netUpdate = true;
                         }
                         ai[0] = 1f;
                     }
                     else if (aiStyle == 16)
                     {
                         if (timeLeft > 3)
{
                             timeLeft = 3;
                         }
                         if (player3.position.X + (float)(player3.width / 2) < position.X + (float)(width / 2))
{
                             direction = -1;
                         }
                         else
{
                             direction = 1;
                         }
                     }
                     else if (aiStyle == 68)
                     {
                         if (timeLeft > 3)
{
                             timeLeft = 3;
                         }
                         if (player3.position.X + (float)(player3.width / 2) < position.X + (float)(width / 2))
{
                             direction = -1;
                         }
                         else
{
                             direction = 1;
                         }
                     }
                     int playerIndex = owner;
                     if (ProjectileID.Sets.IsAGravestone[type])
                     {
                         playerIndex = (int)ai[0];
                     }
                     PlayerDeathReason playerDeathReason = PlayerDeathReason.ByProjectile(playerIndex, whoAmI);
                     if (type == 41 && timeLeft > 1)
                     {
                         timeLeft = 1;
                     }
                     bool flag27 = false;
                     if (melee && Main.rand.Next(1, 101) <= Main.player[owner].meleeCrit)
                     {
                         flag27 = true;
                     }
                     int num46 = Main.DamageVar((int)((float)damage * num), Main.player[owner].luck);
                     bool dodgeable = IsDamageDodgable();
                     if (!player3.immune)
                     {
                         StatusPvP(m);
                     }
                     TryDoingOnHitEffects(player3);
                     int num47 = (int)player3.Hurt(playerDeathReason, num46, direction, pvp: true, quiet: false, flag27, -1, dodgeable);
                     if (num47 > 0 && Main.player[owner].ghostHeal && friendly && !hostile)
                     {
                         ghostHeal(num47, new Vector2(player3.Center.X, player3.Center.Y), player3);
                     }
                     if (type == 304 && num47 > 0)
                     {
                         vampireHeal(num47, new Vector2(player3.Center.X, player3.Center.Y), player3);
                     }
                     if ((melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant == 7)
                     {
                         NewProjectile(GetProjectileSource_FromThis(), player3.Center.X, player3.Center.Y, player3.velocity.X, player3.velocity.Y, 289, 0, 0f, owner);
                     }
                     if (Main.netMode != 0)
                     {
                         NetMessage.SendPlayerHurt(m, playerDeathReason, num46, direction, flag27, pvp: true, -1);
                     }
                     playerImmune[m] = 40;
                     if (penetrate > 0)
                     {
                         penetrate--;
                         if (penetrate == 0)
{
                             break;
                         }
                     }
                     if (aiStyle == 7)
                     {
                         ai[0] = 1f;
                         damage = 0;
                         netUpdate = true;
                     }
                     else if (aiStyle == 13)
                     {
                         ai[0] = 1f;
                         netUpdate = true;
                     }
                     else if (aiStyle == 69)
                     {
                         ai[0] = 1f;
                         netUpdate = true;
                     }
                 }
             }
         }
         if (type == 10 && Main.netMode != 1)
         {
             for (int n = 0; n < 200; n++)
             {
                 NPC nPC2 = Main.npc[n];
                 if (!nPC2.active)
                 {
                     continue;
                 }
                 if (nPC2.type == 534)
                 {
                     if (rectangle.Intersects(nPC2.Hitbox))
                     {
                         nPC2.Transform(441);
                     }
                 }
                 else
                 {
                     if (nPC2.type != 687 || !rectangle.Intersects(nPC2.Hitbox))
                     {
                         continue;
                     }
                     nPC2.Transform(683);
                     Vector2 vector9 = nPC2.Center - new Vector2(20f);
                     Utils.PoofOfSmoke(vector9);
                     if (Main.netMode == 2)
                     {
                         NetMessage.SendData(106, -1, -1, null, (int)vector9.X, vector9.Y);
                     }
                     if (!NPC.unlockedSlimeYellowSpawn)
                     {
                         NPC.unlockedSlimeYellowSpawn = true;
                         if (Main.netMode == 2)
{
                             NetMessage.SendData(7);
                         }
                     }
                 }
             }
         }
         if ((type == 11 || type == 463) && Main.netMode != 1)
         {
             bool crimson = type == 463;
             for (int num48 = 0; num48 < 200; num48++)
             {
                 if (Main.npc[num48].active)
                 {
                     Rectangle value2 = new Rectangle((int)Main.npc[num48].position.X, (int)Main.npc[num48].position.Y, Main.npc[num48].width, Main.npc[num48].height);
                     if (rectangle.Intersects(value2))
                     {
                         Main.npc[num48].AttemptToConvertNPCToEvil(crimson);
                     }
                 }
             }
         }
         if (Main.netMode == 2 || !hostile || Main.myPlayer >= 255 || damage <= 0)
         {
             return;
         }
         int num49 = -1;
         switch (type)
         {
         case 452:
         case 454:
         case 455:
         case 462:
             num49 = 1;
             break;
         case 871:
         case 872:
         case 873:
         case 874:
         case 919:
         case 923:
         case 924:
             num49 = 1;
             break;
         }
         int myPlayer = Main.myPlayer;
         bool flag28 = Main.player[myPlayer].active && !Main.player[myPlayer].dead && (!Main.player[myPlayer].immune || num49 != -1);
         if (flag28 && type == 281)
         {
             flag28 = ai[1] - 1f == (float)myPlayer;
         }
         if (Main.getGoodWorld && type == 281)
         {
             flag28 = true;
         }
         if (!flag28 || !Colliding(rectangle, Main.player[myPlayer].getRect()))
         {
             return;
         }
         int num50 = direction;
         num50 = ((!(Main.player[myPlayer].position.X + (float)(Main.player[myPlayer].width / 2) < position.X + (float)(width / 2))) ? 1 : (-1));
         if (!Main.player[myPlayer].CanParryAgainst(Main.player[myPlayer].Hitbox, base.Hitbox, velocity))
         {
             int num51 = Main.DamageVar(damage, 0f - Main.player[owner].luck);
             int num52 = bannerIdToRespondTo;
             if (num52 > 0 && Main.player[myPlayer].HasNPCBannerBuff(num52))
             {
                 ItemID.BannerEffect bannerEffect = ItemID.Sets.BannerStrength[Item.BannerToItem(num52)];
                 num51 = ((!Main.expertMode) ? ((int)((float)num51 * bannerEffect.NormalDamageReceived)) : ((int)((float)num51 * bannerEffect.ExpertDamageReceived)));
             }
             if (Main.player[myPlayer].resistCold && coldDamage)
             {
                 num51 = (int)((float)num51 * 0.7f);
             }
             if (!reflected)
             {
                 float num53 = Main.GameModeInfo.EnemyDamageMultiplier;
                 if (Main.GameModeInfo.IsJourneyMode)
                 {
                     CreativePowers.DifficultySliderPower power = CreativePowerManager.Instance.GetPower<CreativePowers.DifficultySliderPower>();
                     if (power.GetIsUnlocked())
                     {
                         num53 = power.StrengthMultiplierToGiveNPCs;
                     }
                 }
                 num51 = (int)((float)num51 * num53);
             }
             int num54 = num51 * 2;
             if (type == 961)
             {
                 if (penetrate == 1)
                 {
                     damage = 0;
                     penetrate = -1;
                 }
                 else
                 {
                     damage = (int)((double)damage * 0.7);
                 }
             }
             bool dodgeable2 = IsDamageDodgable();
             int playerIndex2 = -1;
             if (ProjectileID.Sets.IsAGravestone[type])
             {
                 playerIndex2 = (int)ai[0];
             }
             if (Main.player[myPlayer].Hurt(PlayerDeathReason.ByProjectile(playerIndex2, whoAmI), num54, num50, pvp: false, quiet: false, Crit: false, num49, dodgeable2) > 0.0 && !Main.player[myPlayer].dead)
             {
                 StatusPlayer(myPlayer);
             }
             if (trap)
             {
                 Main.player[myPlayer].trapDebuffSource = true;
                 if (Main.player[myPlayer].dead)
                 {
                     AchievementsHelper.HandleSpecialEvent(Main.player[myPlayer], 4);
                 }
             }
         }
         if (true)
         {
             if (type == 435 || type == 682)
             {
                 penetrate--;
             }
             if (type == 436)
             {
                 penetrate--;
             }
             if (type == 681)
             {
                 timeLeft = 0;
             }
             if (type == 437)
             {
                 penetrate--;
             }
         }
     }
References _cachedConditions_notNull, _cachedConditions_solid, _javelinsMax10, _javelinsMax6, _javelinsMax8, Player.accDreamCatcher, Entity.active, Player.AddBuff(), Player.addDPS(), NPC.ai, ai, NPC.aiStyle, aiStyle, ProjectileID.Sets.AllowsContactDamageFromJellyfish, appliesImmunityTimeOnSingleHits, Player.armorPenetration, arrow, NPC.AttemptToConvertNPCToEvil(), NPC.BannerID(), bannerIdToRespondTo, ItemID.Sets.BannerStrength, Item.BannerToItem(), Player.beeDamage(), Player.beeKB(), Player.beetleCountdown, Player.beetleCounter, Player.beetleOffense, Player.beetleOrbs, Player.beeType(), NPCID.Sets.BelongsToInvasionOldOnesArmy, BetsySharpnel(), BombsHurtPlayers(), NPC.buffTime, NPC.buffType, PlayerDeathReason.ByProjectile(), NPC.CanBeChasedBy(), CanBeReflected(), NPC.canGhostHeal, Collision.CanHit(), Collision.CanHitLine(), Player.CanHitNPCWithMeleeHit(), CanHitWithMeleeWeapon(), Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Player.CanParryAgainst(), NPC.CanReflectProjectile(), Entity.Center, Searches.Chain(), NPC.checkArmorPenetration(), Player.ClearBuff(), coldDamage, Colliding(), Player.coolWhipBuff, ProjectileID.Count, CountEnemiesWhoAreImmuneToMeRightNow(), Player.Counterweight(), NPCID.Sets.CountsAsCritter, ProjectileID.Sets.CultistIsResistantTo, CutTiles(), damage, Damage_GetHitbox(), Main.DamageVar(), Player.dead, NPC.defense, NPCKillAttempt.DidNPCDie(), Entity.direction, Entity.DirectionFrom(), Entity.DirectionTo(), ProjectileID.Sets.DontApplyParryDamageBuff, NPC.dontTakeDamage, NPC.dontTakeDamageFromHostiles, EmitBlackLightningParticles(), GameModeData.EnemyDamageMultiplier, ItemID.BannerEffect.ExpertDamageDealt, Main.expertMode, WorldUtils.Find(), FindStardustDragonHeadOfOwner(), FindTargetWithLineOfSight(), frame, NPC.friendly, friendly, Main.GameModeInfo, Main.GameUpdateCount, Main.getGoodWorld, GetItemSource_OnHit(), GetProjectileSource_FromThis(), NPC.getRect(), Player.getRect(), Player.ghostHeal, ghostHeal(), Player.ghostHurt, ghostHurt(), AchievementsHelper.HandleSpecialEvent(), Main.hardMode, Player.hasLuckyCoin, Player.HasNPCBannerBuff(), Entity.height, Entity.Hitbox, Player.HorsemansBlade_SpawnPumpkin(), Player.hostile, hostile, Player.Hurt(), idStaticNPCHitCooldown, ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags, NPC.immortal, NPC.immune, Player.immune, CreativePowerManager.Instance, ProjectileID.Sets.IsAGravestone, ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary, ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy, ProjectileID.Sets.IsAWhip, IsDamageDodgable(), GameModeData.IsJourneyMode, IsNPCIndexImmuneToProjectileType(), Main.item, Player.itemAnimation, Kill(), Player.killClothier, Player.killGuide, KillOldestJavelin(), knockBack, NPC.knockBackResist, Player.lastCreatureHit, NPC.life, NPC.lifeMax, LightDisc_Bounce(), localAI, localNPCHitCooldown, localNPCImmunity, Player.luck, magic, Player.magicCrit, NPC.maxBuffs, maxPenetrate, melee, Player.meleeCrit, Player.meleeEnchant, minion, Player.MinionAttackTargetNPC, ProjectileID.Sets.MinionShot, Player.moonLeech, ParticleOrchestraSettings.MovementVector, Main.myPlayer, Player.nebulaCD, Main.netMode, NPC.netOffset, netUpdate, Item.NewItem(), NewProjectile(), UnifiedRandom.Next(), ItemID.BannerEffect.NormalDamageDealt, NPC.noTileCollide, Main.npc, npcProj, Item.NPCtoBanner(), numHits, numUpdates, Player.OnKillNPC(), Player.ownedProjectileCounts, owner, ownerHitCheck, Player.parryDamageBuff, penetrate, perIDStaticNPCImmunity, Player.phantasmTime, Main.player, playerImmune, Utils.PoofOfSmoke(), Entity.position, ParticleOrchestraSettings.PositionInWorld, Main.projectile, Main.projFrames, Main.projPet, Main.rand, Utils.RandomVector2(), ranged, Player.rangedCrit, reflected, NPC.ReflectProjectile(), NPC.reflectsProjectiles, NPCID.Sets.ReflectStarShotsInForTheWorthy, Main.remixWorld, NPC.RequestBuffRemoval(), ParticleOrchestrator.RequestParticleSpawn(), Player.resistCold, scale, NetMessage.SendData(), NetMessage.SendPlayerHurt(), sentry, ProjectileID.Sets.SentryShot, Player.SetMeleeHitCooldown(), Player.setMonkT2, Player.setMonkT3, Player.setNebula, Entity.Size, Collision.SolidTiles(), NPC.SpawnedFromStatue, Item.stack, ProjectileID.Sets.StardustDragon, StatusNPC(), StatusPlayer(), StatusPvP(), stopsDealingDamageAfterPenetrateHits, ProjectileID.Sets.StormTiger, CreativePowers.DifficultySliderPower.StrengthMultiplierToGiveNPCs, NPC.StrikeNPC(), NPC.StrikeNPCNoInteraction(), Player.strongBees, SummonMonkGhast(), SummonSuperStarSlash(), Player.TakeDamageFromJellyfish(), Player.team, tileCollide, timeLeft, Item.timeLeftInWhichTheItemCannotBeTakenByEnemies, NPC.Transform(), trap, Player.trapDebuffSource, NPC.trapImmune, TryDoingOnHitEffects(), NPC.type, type, NPC.unlockedSlimeYellowSpawn, NPC.UpdateNPC_BuffSetFlags(), usesIDStaticNPCImmunity, usesLocalNPCImmunity, usesOwnerMeleeHitCD, NPC.value, vampireHeal(), Entity.velocity, Entity.whoAmI, Entity.width, and NPCID.Sets.ZappingJellyfish.
Referenced by AI_100_Medusa(), Mount.CastSuperCartLaser(), HandleMovement(), NewProjectile(), and Update().