Terraria: Projectile.AI_135_OgreStomp
AI_135_OgreStomp()
void Projectile.AI_135_OgreStomp () inline private
     {
         float num = 40f;
         if (type == 922)
         {
             num = 30f;
         }
         ai[0] += 1f;
         if (ai[0] > 9f)
         {
             Kill();
             return;
         }
         velocity = Vector2.Zero;
         position = base.Center;
         base.Size = new Vector2(16f, 16f) * MathHelper.Lerp(5f, num, Utils.GetLerpValue(0f, 9f, ai[0]));
         base.Center = position;
         Point point = base.TopLeft.ToTileCoordinates();
         Point point2 = base.BottomRight.ToTileCoordinates();
         int num2 = point.X / 2 + point2.X / 2;
         int num3 = width / 2;
         if ((int)ai[0] % 3 != 0)
         {
             return;
         }
         int num4 = (int)ai[0] / 3;
         for (int i = point.X; i <= point2.X; i++)
         {
             for (int j = point.Y; j <= point2.Y; j++)
             {
                 if (Vector2.Distance(base.Center, new Vector2(i * 16, j * 16)) > (float)num3)
                 {
                     continue;
                 }
                 Tile tileSafely = Framing.GetTileSafely(i, j);
                 if (!tileSafely.active() || !Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type] || Main.tileFrameImportant[tileSafely.type])
                 {
                     continue;
                 }
                 Tile tileSafely2 = Framing.GetTileSafely(i, j - 1);
                 if (tileSafely2.active() && Main.tileSolid[tileSafely2.type] && !Main.tileSolidTop[tileSafely2.type])
                 {
                     continue;
                 }
                 int num5 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely);
                 for (int k = 0; k < num5; k++)
                 {
                     Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                     obj.velocity.Y -= 3f + (float)num4 * 1.5f;
                     obj.velocity.Y *= Main.rand.NextFloat();
                     obj.velocity.Y *= 0.75f;
                     obj.scale += (float)num4 * 0.03f;
                 }
                 if (num4 >= 2)
                 {
                     if (type == 922)
                     {
                         Color newColor = NPC.AI_121_QueenSlime_GetDustColor();
                         newColor.A = 150;
                         for (int l = 0; l < num5 - 1; l++)
{
                             int num6 = Dust.NewDust(position, 12, 12, 4, 0f, 0f, 50, newColor, 1.5f);
                             Main.dust[num6].velocity.Y -= 0.1f + (float)num4 * 0.5f;
                             Main.dust[num6].velocity.Y *= Main.rand.NextFloat();
                             Main.dust[num6].velocity.X *= Main.rand.NextFloatDirection() * 3f;
                             Main.dust[num6].position = new Vector2(i * 16 + Main.rand.Next(16), j * 16 + Main.rand.Next(16));
                             if (Main.rand.Next(3) != 0)
{
                                 Main.dust[num6].velocity *= 0.5f;
                                 Main.dust[num6].noGravity = true;
                             }
                         }
                     }
                     else
                     {
                         for (int m = 0; m < num5 - 1; m++)
{
                             Dust obj2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                             obj2.velocity.Y -= 1f + (float)num4;
                             obj2.velocity.Y *= Main.rand.NextFloat();
                             obj2.velocity.Y *= 0.75f;
                         }
                     }
                 }
                 if (num5 <= 0 || Main.rand.Next(3) == 0)
                 {
                     continue;
                 }
                 float num7 = (float)Math.Abs(num2 - i) / (num / 2f);
                 if (type == 922)
                 {
                     Color newColor2 = NPC.AI_121_QueenSlime_GetDustColor();
                     newColor2.A = 150;
                     for (int n = 0; n < 3; n++)
                     {
                         int num8 = Dust.NewDust(position, width, height, 31, 0f, 0f, 50, newColor2, 2f - (float)num4 * 0.15f + num7 * 0.5f);
                         Main.dust[num8].velocity.Y -= 0.1f + (float)num4 * 0.5f + num7 * (float)num4 * 1f;
                         Main.dust[num8].velocity.Y *= Main.rand.NextFloat();
                         Main.dust[num8].velocity.X *= Main.rand.NextFloatDirection() * 3f;
                         Main.dust[num8].position = new Vector2(i * 16 + 20, j * 16 + 20);
                         if (Main.rand.Next(3) != 0)
{
                             Main.dust[num8].velocity *= 0.5f;
                             Main.dust[num8].noGravity = true;
                         }
                     }
                 }
                 else
                 {
                     Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num4 * 0.15f + num7 * 0.5f);
                     gore.velocity.Y -= 0.1f + (float)num4 * 0.5f + num7 * (float)num4 * 1f;
                     gore.velocity.Y *= Main.rand.NextFloat();
                     gore.position = new Vector2(i * 16 + 20, j * 16 + 20);
                 }
             }
         }
     }
References Tile.active(), NPC.AI_121_QueenSlime_GetDustColor(), Color, Main.dust, Utils.GetLerpValue(), Framing.GetTileSafely(), WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), Dust.NewDust(), Gore.NewGoreDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.position, Gore.position, Main.rand, Dust.scale, Main.tileFrameImportant, Main.tileSolid, Main.tileSolidTop, Tile.type, Dust.velocity, and Gore.velocity.