Terraria: Projectile.NewProjectile
NewProjectile() [2/2]
static int Projectile.NewProjectile (IEntitySource spawnSource, Vector2 position, Vector2 velocity, int Type, int Damage, float KnockBack, int Owner = -1, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f) inline static
     {
         return NewProjectile(spawnSource, position.X, position.Y, velocity.X, velocity.Y, Type, Damage, KnockBack, Owner, ai0, ai1, ai2);
     }
References Damage(), Entity.position, and Entity.velocity.
Referenced by PortalHelper.AddPortal(), NPC.AI(), NPC.AI_001_Slimes(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_007_TownEntities(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), NPC.AI_069_DukeFishron(), NPC.AI_084_LunaticCultist(), NPC.AI_107_ImprovedWalkers(), NPC.AI_109_DarkMage(), NPC.AI_110_Betsy(), NPC.AI_111_DD2LightningBug(), NPC.AI_117_BloodNautilus(), NPC.AI_119_Dandelion(), NPC.AI_120_HallowBoss(), NPC.AI_121_QueenSlime(), NPC.AI_123_Deerclops(), NPC.AI_123_Deerclops_ShootRubbleUp(), NPC.AI_123_Deerclops_TryMakingSpike(), Player.ApplyNPCOnHitEffects(), Player.BloodButcherer_TryButchering(), NPC.BloodNautilus_CallForHelp(), Player.BuffHandle_SpawnPetIfNeeded(), Mount.CastSuperCartLaser(), WorldGen.Check2x2(), NPC.checkDead(), WorldGen.CheckSuper(), Player.CommandForbiddenStorm(), Player.Counterweight(), DSTFilm.CreateChester(), Damage(), Player.DashMovement(), NPC.DoDeathEvents(), Main.DrawWallOfStars(), Player.DropTombstone(), NPC.DropTombstoneTownNPC(), WorldGen.ExplodeMine(), Wiring.GeyserTrap(), ghostHeal(), ghostHurt(), HandleMovement(), NPC.HaveDryadDoStardewAnimation(), NPC.HitEffect(), Wiring.HitWireSingle(), Player.HorsemansBlade_SpawnPumpkin(), Player.Hurt(), Player.ItemCheck_EmitHammushProjectiles(), Player.ItemCheck_MeleeHitPVP(), Player.ItemCheck_OwnerOnlyCode(), Player.ItemCheck_Shoot(), WorldGen.KillTile(), Player.LaunchMinecartHook(), WorldGen.LaunchRocket(), WorldGen.LaunchRocketSmall(), Player.OnHit(), Player.QuickGrapple(), WorldGen.ShakeTree(), WorldGen.ShootFromCannon(), WorldGen.SpawnFallingBlockProjectile(), Player.SpawnHallucination(), Player.SpawnMinionOnCursor(), NPC.SpawnPassiveShadowHands(), NPC.SpawnStardustMark_StardustTower(), NPC.SpawnStardustMark_StardustWorm(), WorldGen.SpawnThingsFromPot(), Player.SporeSac(), Mount.StartAbilityCharge(), NPC.StingerExplosion(), SummonMonkGhast(), SummonSuperStarSlash(), Player.TentacleSpike_TrySpiking(), Player.TileInteractionsUse(), Player.TorchAttack(), Player.TryPlacingAGolfBallNearANearbyTee(), Player.UpdateAbigailStatus(), Player.UpdateArmorSets(), Player.UpdateBuffs(), Player.UpdateStormTigerStatus(), WorldGen.UpdateWorld(), Mount.UseAbility(), vampireHeal(), Player.VolatileGelatin(), and Player.Volcano_TrySpawningVolcano().