Terraria: Projectile.AI_131_FlameBurstShot
AI_131_FlameBurstShot()
void Projectile.AI_131_FlameBurstShot () inline private
     {
         //IL_0051: Unknown result type (might be due to invalid IL or missing references)
         if (type != 664 && type != 666 && type != 668)
         {
             return;
         }
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             SoundEngine.PlayTrackedSound(SoundID.DD2_FlameburstTowerShot, base.Center);
         }
         if (alpha > 0)
         {
             alpha -= 25;
             if (alpha < 0)
             {
                 alpha = 0;
             }
         }
         int num = 1;
         if (type == 666)
         {
             num = 2;
         }
         if (type == 668)
         {
             num = 3;
         }
         for (int i = 0; i < num; i++)
         {
             if (Main.rand.Next(2) != 0)
             {
                 Dust dust = Dust.NewDustDirect(position, width, height, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
                 dust.noGravity = true;
                 dust.velocity *= 0.3f;
                 if (Main.rand.Next(1) == 0)
                 {
                     dust.velocity.Y += (float)Math.Sign(dust.velocity.Y) * 1.2f;
                     dust.fadeIn += 0.5f;
                 }
             }
         }
         rotation = velocity.ToRotation() + (float)Math.PI / 2f;
     }
References Color, SoundID.DD2_FlameburstTowerShot, Dust.fadeIn, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, SoundEngine.PlayTrackedSound(), Main.rand, and Dust.velocity.