Terraria: Projectile.AI_172_GetPelletStormInfo
AI_172_GetPelletStormInfo()
HallowBossPelletStormInfo Projectile.AI_172_GetPelletStormInfo (int stormIndex) inline
     {
         float from = 0f + (float)stormIndex * 10f;
         float to = 90f + (float)stormIndex * 10f;
         HallowBossPelletStormInfo result = default(HallowBossPelletStormInfo);
         result.StartAngle = (float)stormIndex * ((float)Math.PI / 3f) - (float)Math.PI / 2f + (float)stormIndex * ((float)Math.PI / 5f);
         result.AnglePerBullet = (float)Math.PI * 2f / 3f;
         result.BulletsInStorm = 3;
         result.BulletsProgressInStormStartNormalized = Utils.GetLerpValue(from, to, localAI[0]);
         result.BulletsProgressInStormBonusByIndexNormalized = 0f;
         result.StormTotalRange = 500f;
         result.BulletSize = new Vector2(16f, 16f);
         return result;
     }
References Utils.GetLerpValue(), and Projectile.HallowBossPelletStormInfo.StartAngle.
Referenced by Colliding(), and Main.DrawProjDirect().