Terraria: System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters
FetchNonReturnParameters()
ParameterInfo[] System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters () inline private
Definition at line 196 of file RuntimeMethodInfo.cs.
    {
        return m_parameters ?? (m_parameters = RuntimeParameterInfo.GetParameters(this, this, Signature));
    }
References System.Reflection.RuntimeParameterInfo.GetParameters(), and System.Reflection.RuntimeMethodInfo.m_parameters.
Referenced by System.Reflection.RuntimeMethodInfo.GetParameters(), and System.Reflection.RuntimeMethodInfo.GetParametersNoCopy().