Terraria: Projectile.LightDisc_Bounce
LightDisc_Bounce()
void Projectile.LightDisc_Bounce (Vector2 hitPoint, Vector2 normal) inline private
     {
         Vector2 spinningpoint = Vector2.Reflect(velocity, normal);
         for (int i = 0; i < 4; i++)
         {
             Dust dust = Dust.NewDustPerfect(hitPoint, 306, spinningpoint.RotatedBy((float)Math.PI / 4f * Main.rand.NextFloatDirection()) * 0.6f * Main.rand.NextFloat(), 200, default(Color), 1.6f);
             dust.color = Color.Lerp(new Color(219, 253, 0), Color.Cyan, Main.rand.NextFloat());
             Dust dust2 = Dust.CloneDust(dust);
             dust2.color = Color.White;
             dust2.scale = 1f;
             dust2.alpha = 50;
         }
     }
References Dust.alpha, Dust.CloneDust(), Color, Dust.color, Dust.NewDustPerfect(), Main.rand, Dust.scale, and Entity.velocity.
Referenced by Damage(), and HandleMovement().