Terraria: Projectile.ExplodeCrackedTiles
ExplodeCrackedTiles()
void Projectile.ExplodeCrackedTiles (Vector2 compareSpot, int radius, int minI, int maxI, int minJ, int maxJ) inline
     {
         AchievementsHelper.CurrentlyMining = true;
         for (int i = minI; i <= maxI; i++)
         {
             for (int j = minJ; j <= maxJ; j++)
             {
                 float num = Math.Abs((float)i - compareSpot.X / 16f);
                 float num2 = Math.Abs((float)j - compareSpot.Y / 16f);
                 if (Math.Sqrt(num * num + num2 * num2) < (double)radius && Main.tile[i, j] != null && Main.tile[i, j].active() && TileID.Sets.CrackedBricks[Main.tile[i, j].type])
                 {
                     WorldGen.KillTile(i, j);
                     if (!Main.tile[i, j].active() && Main.netMode != 0)
                     {
                         NetMessage.SendData(17, -1, -1, null, 20, i, j);
                     }
                 }
             }
         }
         AchievementsHelper.CurrentlyMining = false;
     }
References Tile.active(), TileID.Sets.CrackedBricks, AchievementsHelper.CurrentlyMining, WorldGen.KillTile(), Main.netMode, NetMessage.SendData(), Main.tile, and Tile.type.