Terraria: Projectile.SetDefaults
SetDefaults()
void Projectile.SetDefaults (int Type) inline
References Entity.active, ai, aiStyle, alpha, appliesImmunityTimeOnSingleHits, arrow, bannerIdToRespondTo, bobber, coldDamage, counterweight, damage, decidesManualFallThrough, DefaultToSpray(), DefaultToWhip(), extraUpdates, frame, frameCounter, friendly, Main.getGoodWorld, glowMask, Entity.height, hide, hostile, identity, idStaticNPCHitCooldown, ignoreWater, isAPreviewDummy, knockBack, Entity.lavaWet, light, localAI, localNPCHitCooldown, magic, manualDirectionChange, maxAI, maxPenetrate, MaxUpdates, melee, minion, minionSlots, miscText, netImportant, netSpam, netUpdate, netUpdate2, UnifiedRandom.Next(), noDropItem, noEnchantments, noEnchantmentVisuals, npcProj, numHits, numUpdates, oldPos, oldRot, oldSpriteDirection, Opacity, originalDamage, originatedFromActivableTile, owner, ownerHitCheck, ownerHitCheckDistance, penetrate, playerImmune, Entity.position, projUUID, Main.rand, ranged, reflected, Main.remixWorld, ResetLocalNPCHitImmunity(), restrikeDelay, rotation, scale, sentry, shouldFallThrough, soundDelay, spriteDirection, stopsDealingDamageAfterPenetrateHits, tileCollide, timeLeft, ProjectileID.Sets.TrailCacheLength, trap, type, usesIDStaticNPCImmunity, usesLocalNPCImmunity, usesOwnerMeleeHitCD, Entity.velocity, Entity.wet, Entity.wetCount, and Entity.width.
Referenced by MessageBuffer.GetData(), ContentSamples.Initialize(), Main.Initialize_AlmostEverything(), NewProjectile(), and UICharacter.PreparePetProjectiles_CreatePetProjectileDummy().