Terraria: Projectile.AI_015_HandleMovementCollision
AI_015_HandleMovementCollision()
void Projectile.AI_015_HandleMovementCollision (ref Vector2 wetVelocity, ref Vector2 lastVelocity) inline private
     {
         int num = 10;
         int num2 = 0;
         Vector2 vector = velocity;
         float num3 = 0.2f;
         if (ai[0] == 1f || ai[0] == 5f)
         {
             num3 = 0.4f;
         }
         if (ai[0] == 6f)
         {
             num3 = 0f;
         }
         if (lastVelocity.X != velocity.X)
         {
             if (Math.Abs(lastVelocity.X) > 4f)
             {
                 num2 = 1;
             }
             velocity.X = (0f - lastVelocity.X) * num3;
             localAI[0] += 1f;
         }
         if (lastVelocity.Y != velocity.Y)
         {
             if (Math.Abs(lastVelocity.Y) > 4f)
             {
                 num2 = 1;
             }
             velocity.Y = (0f - lastVelocity.Y) * num3;
             localAI[0] += 1f;
         }
         if (ai[0] == 1f)
         {
             ai[0] = 5f;
             localNPCHitCooldown = num;
             netUpdate = true;
             Point scanAreaStart = base.TopLeft.ToTileCoordinates();
             Point scanAreaEnd = base.BottomRight.ToTileCoordinates();
             num2 = 2;
             CreateImpactExplosion(2, base.Center, ref scanAreaStart, ref scanAreaEnd, width, out var causedShockwaves);
             CreateImpactExplosion2_FlailTileCollision(base.Center, causedShockwaves, vector);
             position -= vector;
         }
         if (num2 > 0)
         {
             netUpdate = true;
             for (int i = 0; i < num2; i++)
             {
                 Collision.HitTiles(position, vector, width, height);
             }
             SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
         }
         if (ai[0] != 3f && ai[0] != 0f && ai[0] != 5f && ai[0] != 6f && localAI[0] >= 10f)
         {
             ai[0] = 4f;
             netUpdate = true;
         }
         if (wet)
         {
             wetVelocity = velocity;
         }
     }
References Collision.HitTiles(), and SoundEngine.PlaySound().
Referenced by HandleMovement().