Terraria: Projectile.AI_147_Celeb2Rocket
AI_147_Celeb2Rocket()
void Projectile.AI_147_Celeb2Rocket () inline private
     {
         int num = 0;
         int num2 = 1;
         int num3 = 1;
         localAI[num] += 1f;
         alpha = 0;
         rotation = velocity.ToRotation() + (float)Math.PI / 2f;
         int num4 = (int)ai[0];
         Lighting.AddLight(base.Center, GetCeleb2Color().ToVector3() * 0.5f);
         switch (num4)
         {
         case 0:
             if (localAI[num] >= 20f)
             {
                 velocity.Y += 0.12f;
                 penetrate = (maxPenetrate = -1);
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             if (localAI[num] > 20f && localAI[num] % 20f == 0f)
             {
                 AI_147_Explosion();
             }
             break;
         case 1:
         {
             if (localAI[num] == 10f)
             {
                 velocity.Y -= 10f;
             }
             if (localAI[num] >= 10f)
             {
                 velocity.Y += 0.25f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             if (!(localAI[num] >= 10f))
             {
                 break;
             }
             scale += 0.015f;
             if (scale > 2.5f)
             {
                 scale = 2.5f;
             }
             if (localAI[num] % 10f != 0f)
             {
                 break;
             }
             _ = velocity.Y;
             _ = 0f;
             for (float num5 = 0f; num5 < 1f; num5 += 0.12f)
             {
                 Vector2 spinningpoint = Vector2.UnitX * -8f;
                 spinningpoint += -Vector2.UnitY.RotatedBy(num5 * ((float)Math.PI * 2f)) * new Vector2(2f, 4f);
                 spinningpoint = spinningpoint.RotatedBy(rotation - (float)Math.PI / 2f);
                 int num6 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, Color.Lerp(GetCeleb2Color(), Color.White, Main.rand.NextFloat() * 0.3f));
                 Main.dust[num6].scale = 0.9f;
                 Main.dust[num6].fadeIn = 1.1f;
                 Main.dust[num6].noGravity = true;
                 Main.dust[num6].position = base.Center + spinningpoint;
                 Main.dust[num6].velocity = -velocity * 0.35f + spinningpoint * 0.35f;
                 Main.dust[num6].velocity *= scale;
                 if (localAI[num] == 10f)
                 {
                     Main.dust[num6].velocity = spinningpoint.RotatedBy(velocity.ToRotation()) * 0.3f;
                 }
             }
             break;
         }
         case 2:
             if (localAI[num] >= 60f)
             {
                 velocity.Y += 0.15f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             break;
         case 3:
         {
             float num7 = localAI[num2];
             if (num7 == 0f)
             {
                 float num8 = velocity.Length();
                 localAI[num2] = num8;
                 num7 = num8;
             }
             if (localAI[num] >= 25f && ai[num3] == 0f)
             {
                 if (localAI[num] >= 20f)
                 {
                     velocity.Y += 0.15f;
                 }
                 if (velocity.Y > 16f)
                 {
                     velocity.Y = 16f;
                 }
             }
             if (!(localAI[num] >= 20f))
             {
                 break;
             }
             float num9 = position.X;
             float num10 = position.Y;
             float num11 = 800f;
             bool flag = false;
             int num12 = 0;
             if (ai[num3] == 0f)
             {
                 for (int i = 0; i < 200; i++)
                 {
                     if (Main.npc[i].CanBeChasedBy(this) && (ai[num3] == 0f || ai[num3] == (float)(i + 1)))
                     {
                         float num13 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                         float num14 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                         float num15 = Math.Abs(position.X + (float)(width / 2) - num13) + Math.Abs(position.Y + (float)(height / 2) - num14);
                         if (num15 < num11 && Collision.CanHit(new Vector2(position.X + (float)(width / 2), position.Y + (float)(height / 2)), 1, 1, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height))
{
                             num11 = num15;
                             num9 = num13;
                             num10 = num14;
                             flag = true;
                             num12 = i;
                         }
                     }
                 }
                 if (flag)
                 {
                     ai[1] = num12 + 1;
                 }
                 flag = false;
             }
             if (ai[num3] != 0f)
             {
                 int num16 = (int)(ai[num3] - 1f);
                 if (Main.npc[num16].active && Main.npc[num16].CanBeChasedBy(this, ignoreDontTakeDamage: true))
                 {
                     float num17 = Main.npc[num16].position.X + (float)(Main.npc[num16].width / 2);
                     float num18 = Main.npc[num16].position.Y + (float)(Main.npc[num16].height / 2);
                     if (Math.Abs(position.X + (float)(width / 2) - num17) + Math.Abs(position.Y + (float)(height / 2) - num18) < 1000f)
                     {
                         flag = true;
                         num9 = Main.npc[num16].position.X + (float)(Main.npc[num16].width / 2);
                         num10 = Main.npc[num16].position.Y + (float)(Main.npc[num16].height / 2);
                     }
                 }
             }
             if (!friendly)
             {
                 flag = false;
             }
             if (flag)
             {
                 float num19 = num7;
                 Vector2 vector2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                 float num20 = num9 - vector2.X;
                 float num21 = num10 - vector2.Y;
                 float num22 = (float)Math.Sqrt(num20 * num20 + num21 * num21);
                 num22 = num19 / num22;
                 num20 *= num22;
                 num21 *= num22;
                 int num23 = 8;
                 velocity.X = (velocity.X * (float)(num23 - 1) + num20) / (float)num23;
                 velocity.Y = (velocity.Y * (float)(num23 - 1) + num21) / (float)num23;
             }
             break;
         }
         case 4:
         {
             if (localAI[num] == 1f && ai[1] == 1f)
             {
                 localAI[num] += 45f;
             }
             float x = velocity.SafeNormalize(Vector2.Zero).RotatedBy(localAI[num] * ((float)Math.PI / 45f)).X;
             Vector2 vector = velocity.SafeNormalize(Vector2.Zero).RotatedBy(1.5707963705062866);
             position += vector * x * 3f;
             scale = 2f;
             if (localAI[num] >= 10f)
             {
                 velocity.Y += 0.04f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             break;
         }
         case 5:
             if (localAI[num] >= 40f)
             {
                 velocity.Y += 0.08f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             break;
         case 6:
             if (localAI[num] >= 30f)
             {
                 velocity.Y += 0.1f;
             }
             if (velocity.Y > 16f)
             {
                 velocity.Y = 16f;
             }
             break;
         }
     }
References Entity.active, Lighting.AddLight(), NPC.CanBeChasedBy(), Collision.CanHit(), Color, Main.dust, Dust.fadeIn, Entity.height, Dust.NewDust(), Dust.noGravity, Main.npc, Dust.position, Entity.position, Main.rand, Dust.scale, Dust.velocity, and Entity.width.