Terraria: Projectile.AI_195_JimsDrone
AI_195_JimsDrone()
void Projectile.AI_195_JimsDrone () inline private
     {
         //IL_0240: Unknown result type (might be due to invalid IL or missing references)
         //IL_027c: Unknown result type (might be due to invalid IL or missing references)
         //IL_0281: Unknown result type (might be due to invalid IL or missing references)
         //IL_0293: Unknown result type (might be due to invalid IL or missing references)
         Player player = Main.player[owner];
         bool flag = false;
         if (player.dead)
         {
             flag = true;
         }
         if (owner == Main.myPlayer)
         {
             if (position.Y - (float)height <= (float)(16 * Main.offScreenRange / 2))
             {
                 Kill();
                 return;
             }
             if (player.HeldItem.type != 5451)
             {
                 flag = true;
             }
             bool flag2 = player.gravDir == -1f;
             BitsByte bitsByte = (byte)0;
             Player.DirectionalInputSyncCache localInputCache = player.LocalInputCache;
             bitsByte[0] = localInputCache.controlLeft ^ flag2;
             bitsByte[1] = localInputCache.controlRight ^ flag2;
             bitsByte[2] = localInputCache.controlUp;
             bitsByte[3] = localInputCache.controlDown;
             float num = (int)(byte)bitsByte;
             if (ai[0] != num)
             {
                 ai[0] = num;
                 netUpdate = true;
             }
             Main.DroneCameraTracker.Track(this);
         }
         if (flag)
         {
             Kill();
             return;
         }
         BitsByte bitsByte2 = (byte)ai[0];
         rotation = ai[1];
         bool flag3 = bitsByte2[0];
         bool flag4 = bitsByte2[1];
         bool flag5 = bitsByte2[2];
         _ = bitsByte2[3];
         localAI[0] += 1f;
         if (!flag3 && !flag4)
         {
             localAI[0] = 0f;
         }
         bool flag6 = velocity.Y == 0f;
         int num2 = 0;
         if (!flag6)
         {
             num2 = 10;
         }
         if (flag5)
         {
             num2 = 100;
         }
         localAI[1] = MathHelper.Lerp(localAI[1], num2, 0.2f);
         float num3 = Utils.Remap(localAI[0], 0f, 5f, 0f, 1f) * Utils.Remap(localAI[0], 5f, 15f, 1f, 0f);
         float num4 = Utils.Clamp(MathHelper.Max(Utils.Remap(localAI[1], 0f, 100f, 0f, 25f), num3 * 12f), 0f, 100f);
         ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
         if (activeSound == null && num4 != 0f)
         {
             float[] array = localAI;
             SlotId val = SoundEngine.PlayTrackedLoopedSound(SoundID.JimsDrone, base.Center, new ProjectileAudioTracker(this).IsActiveAndInGame);
             array[2] = ((SlotId)(ref val)).ToFloat();
             activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
         }
         if (activeSound != null)
         {
             activeSound.Volume = num4;
             activeSound.Position = base.Center;
             activeSound.Pitch = Utils.Clamp(Utils.Remap(localAI[1], 0f, 100f, -1f, 1f) + num3, -1f, 1f);
         }
         float num5 = 0.15f;
         if (flag6)
         {
             rotation = MathHelper.WrapAngle(rotation) * 0.7f;
             velocity.X *= 0.97f;
             if (flag5)
             {
                 Vector2 vector = (rotation - (float)Math.PI / 2f).ToRotationVector2();
                 velocity += vector * 0.5f;
                 num5 = 0.05f;
             }
         }
         else
         {
             float num6 = (float)Math.PI / 15f;
             num6 = Utils.Remap(localAI[0], 0f, 10f, num6 * 0.1f, num6);
             int num7 = flag4.ToInt() - flag3.ToInt();
             rotation += (float)num7 * num6;
             if (flag5)
             {
                 Vector2 vector2 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
                 velocity.X *= 0.97f;
                 velocity += vector2 * 0.5f;
             }
         }
         velocity.Y += num5;
         ai[1] = rotation;
         if (!flag5 && velocity.Y > 12f)
         {
             velocity.Y *= 0.95f;
         }
         if (velocity.Length() > 16f)
         {
             velocity *= 16f / velocity.Length();
         }
         Lighting.AddLight(base.Center, Vector3.One * 0.3f);
         timeLeft = 2;
         if (!flag6)
         {
             Vector2 vector3 = position;
             float num8 = 0f;
             int num9 = 3;
             int num10 = 16 * num9;
             for (int i = 0; i < num9; i++)
             {
                 Vector2 vector4 = new Vector2(0f, 16f);
                 Vector2 vector5 = Collision.TileCollision(vector3 + vector4 * i, vector4, width, height);
                 num8 += vector5.Y;
                 if (vector5 != vector4)
                 {
                     break;
                 }
             }
             if (num8 != (float)num10)
             {
                 for (int j = 0; j < 2; j++)
                 {
                     if (!(Main.rand.NextFloat() < 0.66f))
                     {
                         Vector2 vector6 = vector3 + new Vector2(0f, num8) + new Vector2((float)width / 2f, height);
                         Vector2 value = Main.rand.NextVector2CircularEdge(2.5f, 1f) * 0.5f;
                         if (value.Y > 0f)
{
                             value.Y *= -1f;
                         }
                         Dust.NewDustPerfect(vector6, (Main.rand.Next(2) == 0) ? 31 : 16, value, 127);
                     }
                 }
             }
         }
         if (Main.netMode == 2 && Main.player.IndexInRange(owner) && Main.player[owner].active)
         {
             RemoteClient.CheckSection(owner, position);
         }
     }
References Entity.active, Lighting.AddLight(), RemoteClient.CheckSection(), Player.dead, Main.DroneCameraTracker, SlotId.FromFloat(), SoundEngine.GetActiveSound(), Player.gravDir, Player.HeldItem, ProjectileAudioTracker.IsActiveAndInGame(), SoundID.JimsDrone, Player.LocalInputCache, Main.myPlayer, Main.netMode, Dust.NewDustPerfect(), UnifiedRandom.Next(), Main.offScreenRange, ActiveSound.Pitch, Main.player, SoundEngine.PlayTrackedLoopedSound(), ActiveSound.Position, Main.rand, Utils.Remap(), Collision.TileCollision(), Utils.ToRotationVector2(), DroneCameraTracker.Track(), Item.type, and ActiveSound.Volume.