Terraria: Projectile.AI_181_FairyQueenRangedItemShot
AI_181_FairyQueenRangedItemShot()
void Projectile.AI_181_FairyQueenRangedItemShot () inline private
     {
         ai[0] += 1f;
         alpha = (int)MathHelper.Lerp(255f, 0f, Utils.GetLerpValue(0f, 10f, ai[0], clamped: true));
         rotation = velocity.ToRotation();
         if (Main.rand.Next(6) == 0)
         {
             Dust dust = Dust.NewDustPerfect(base.Center, 267);
             dust.fadeIn = 1f;
             dust.noGravity = true;
             dust.alpha = 100;
             dust.color = GetFairyQueenWeaponsColor(1f, Main.rand.NextFloat() * 0.4f);
             dust.noLightEmittence = true;
             dust.scale *= 1.5f;
         }
     }
References Dust.alpha, Dust.color, Dust.fadeIn, Utils.GetLerpValue(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLightEmittence, Main.rand, and Dust.scale.