Terraria: Projectile.AI_062
AI_062()
void Projectile.AI_062 () inline private
     {
         float num = 0f;
         float num2 = 0f;
         float num3 = 20f;
         float num4 = 40f;
         float num5 = 0.69f;
         if (type == 963)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].abigailMinion = false;
             }
             if (Main.player[owner].abigailMinion)
             {
                 timeLeft = 2;
             }
             originalDamage = Main.player[owner].highestAbigailCounterOriginalDamage;
             num2 = Main.player[owner].ownedProjectileCounts[970] - 1;
             num3 = Math.Max(4f, 18f - num2 * 1.75f);
             num = 1.4f;
             num4 = Math.Max(5f, num4 - num2 * 4f);
             num5 = Math.Min(1f, num5 + num2 * 0.03f);
         }
         if (type == 423)
         {
             num4 = 5f;
         }
         if (type == 373)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].hornetMinion = false;
             }
             if (Main.player[owner].hornetMinion)
             {
                 timeLeft = 2;
             }
         }
         if (type == 375)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].impMinion = false;
             }
             if (Main.player[owner].impMinion)
             {
                 timeLeft = 2;
             }
         }
         if (type == 407)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].sharknadoMinion = false;
             }
             if (Main.player[owner].sharknadoMinion)
             {
                 timeLeft = 2;
             }
         }
         if (type == 423)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].UFOMinion = false;
             }
             if (Main.player[owner].UFOMinion)
             {
                 timeLeft = 2;
             }
         }
         if (type == 613)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].stardustMinion = false;
             }
             if (Main.player[owner].stardustMinion)
             {
                 timeLeft = 2;
             }
             Lighting.AddLight(base.Center, 0.2f, 0.6f, 0.7f);
             if (localAI[1] > 0f)
             {
                 localAI[1] -= 1f;
             }
         }
         if (type == 423)
         {
             if (ai[0] == 2f)
             {
                 ai[1] -= 1f;
                 tileCollide = false;
                 if (ai[1] > 3f)
                 {
                     int num6 = Dust.NewDust(base.Center, 0, 0, 220 + Main.rand.Next(2), velocity.X, velocity.Y, 100);
                     Main.dust[num6].scale = 0.5f + (float)Main.rand.NextDouble() * 0.3f;
                     Main.dust[num6].velocity /= 2.5f;
                     Main.dust[num6].noGravity = true;
                     Main.dust[num6].noLight = true;
                     Main.dust[num6].frame.Y = 80;
                 }
                 if (ai[1] != 0f)
                 {
                     return;
                 }
                 ai[1] = 30f;
                 ai[0] = 0f;
                 velocity /= 5f;
                 velocity.Y = 0f;
                 extraUpdates = 0;
                 numUpdates = 0;
                 netUpdate = true;
                 extraUpdates = 0;
                 numUpdates = 0;
             }
             if (extraUpdates > 1)
             {
                 extraUpdates = 0;
             }
             if (numUpdates > 1)
             {
                 numUpdates = 0;
             }
         }
         if (type == 613)
         {
             if (ai[0] == 2f)
             {
                 ai[1] -= 1f;
                 tileCollide = false;
                 if (ai[1] > 3f)
                 {
                     if (numUpdates < 20)
                     {
                         for (int i = 0; i < 3; i++)
{
                             Dust obj = Main.dust[Dust.NewDust(position, width, height, 229)];
                             obj.noGravity = true;
                             obj.position = base.Center;
                             obj.velocity *= 3f;
                             obj.velocity += velocity * 3f;
                             obj.fadeIn = 1f;
                         }
                     }
                     float num7 = 2f - (float)numUpdates / 30f;
                     if (scale > 0f)
                     {
                         float num8 = 2f;
                         for (int j = 0; (float)j < num8; j++)
{
                             Dust obj2 = Main.dust[Dust.NewDust(position, width, height, 229)];
                             obj2.noGravity = true;
                             obj2.position = base.Center + Vector2.UnitY.RotatedBy((float)numUpdates * ((float)Math.PI / 30f) + (float)whoAmI * ((float)Math.PI / 4f) + (float)Math.PI / 2f) * (height / 2) - velocity * ((float)j / num8);
                             obj2.velocity = velocity / 3f;
                             obj2.fadeIn = num7 / 2f;
                             obj2.scale = num7;
                         }
                     }
                 }
                 if (ai[1] != 0f)
                 {
                     return;
                 }
                 ai[1] = 30f;
                 ai[0] = 0f;
                 velocity /= 5f;
                 velocity.Y = 0f;
                 extraUpdates = 0;
                 numUpdates = 0;
                 netUpdate = true;
                 float num9 = 15f;
                 for (int k = 0; (float)k < num9; k++)
                 {
                     Dust dust = Main.dust[Dust.NewDust(position, width, height, 229)];
                     dust.noGravity = true;
                     dust.position = base.Center - velocity * 5f;
                     dust.velocity *= 3f;
                     dust.velocity += velocity * 3f;
                     dust.fadeIn = 1f;
                     if (Main.rand.Next(3) != 0)
                     {
                         dust.fadeIn = 2f;
                         dust.scale = 2f;
                         dust.velocity /= 8f;
                     }
                 }
                 for (int l = 0; (float)l < num9; l++)
                 {
                     Dust dust2 = Main.dust[Dust.NewDust(position, width, height, 229)];
                     dust2.noGravity = true;
                     dust2.position = base.Center;
                     dust2.velocity *= 3f;
                     dust2.velocity += velocity * 3f;
                     dust2.fadeIn = 1f;
                     if (Main.rand.Next(3) != 0)
                     {
                         dust2.fadeIn = 2f;
                         dust2.scale = 2f;
                         dust2.velocity /= 8f;
                     }
                 }
                 extraUpdates = 0;
                 numUpdates = 0;
             }
             if (extraUpdates > 1)
             {
                 extraUpdates = 0;
             }
             if (numUpdates > 1)
             {
                 numUpdates = 0;
             }
         }
         if (type == 423 && localAI[0] > 0f)
         {
             localAI[0] -= 1f;
         }
         if (type == 613 && localAI[0] > 0f)
         {
             localAI[0] -= 1f;
         }
         float num10 = 0.05f;
         float num11 = width;
         if (type == 407)
         {
             num10 = 0.1f;
             num11 *= 2f;
         }
         for (int m = 0; m < 1000; m++)
         {
             if (m != whoAmI && Main.projectile[m].active && Main.projectile[m].owner == owner && Main.projectile[m].type == type && Math.Abs(position.X - Main.projectile[m].position.X) + Math.Abs(position.Y - Main.projectile[m].position.Y) < num11)
             {
                 if (position.X < Main.projectile[m].position.X)
                 {
                     velocity.X -= num10;
                 }
                 else
                 {
                     velocity.X += num10;
                 }
                 if (position.Y < Main.projectile[m].position.Y)
                 {
                     velocity.Y -= num10;
                 }
                 else
                 {
                     velocity.Y += num10;
                 }
             }
         }
         Vector2 vector = position;
         float num12 = 400f;
         if (type == 423)
         {
             num12 = 300f;
         }
         if (type == 613)
         {
             num12 = 300f;
         }
         num12 = 2000f;
         if (type == 963)
         {
             num12 = 700f;
         }
         bool flag = false;
         int num13 = -1;
         tileCollide = true;
         if (type == 963)
         {
             tileCollide = false;
         }
         if (type == 407)
         {
             tileCollide = false;
             if (Collision.SolidCollision(position, width, height))
             {
                 alpha += 20;
                 if (alpha > 150)
                 {
                     alpha = 150;
                 }
             }
             else
             {
                 alpha -= 50;
                 if (alpha < 60)
                 {
                     alpha = 60;
                 }
             }
         }
         if (type == 407 || type == 613 || type == 423)
         {
             Vector2 center = Main.player[owner].Center;
             Vector2 vector2 = new Vector2(0.5f);
             if (type == 423)
             {
                 vector2.Y = 0f;
             }
             NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
             if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
             {
                 Vector2 vector3 = ownerMinionAttackTargetNPC.position + ownerMinionAttackTargetNPC.Size * vector2;
                 float num14 = num12 * 3f;
                 float num15 = Vector2.Distance(vector3, center);
                 if (num15 < num14 && !flag && Collision.CanHitLine(position, width, height, ownerMinionAttackTargetNPC.position, ownerMinionAttackTargetNPC.width, ownerMinionAttackTargetNPC.height))
                 {
                     num12 = num15;
                     vector = vector3;
                     flag = true;
                     num13 = ownerMinionAttackTargetNPC.whoAmI;
                 }
             }
             if (!flag)
             {
                 for (int n = 0; n < 200; n++)
                 {
                     NPC nPC = Main.npc[n];
                     if (nPC.CanBeChasedBy(this))
                     {
                         Vector2 vector4 = nPC.position + nPC.Size * vector2;
                         float num16 = Vector2.Distance(vector4, center);
                         if (!(num16 >= num12) && Collision.CanHitLine(position, width, height, nPC.position, nPC.width, nPC.height))
{
                             num12 = num16;
                             vector = vector4;
                             flag = true;
                             num13 = n;
                         }
                     }
                 }
             }
         }
         else
         {
             NPC ownerMinionAttackTargetNPC2 = OwnerMinionAttackTargetNPC;
             if (ownerMinionAttackTargetNPC2 != null && ownerMinionAttackTargetNPC2.CanBeChasedBy(this))
             {
                 float num17 = Vector2.Distance(ownerMinionAttackTargetNPC2.Center, base.Center);
                 float num18 = num12 * 3f;
                 if (num17 < num18 && !flag)
                 {
                     bool flag2 = false;
                     if ((type != 963) ? Collision.CanHitLine(position, width, height, ownerMinionAttackTargetNPC2.position, ownerMinionAttackTargetNPC2.width, ownerMinionAttackTargetNPC2.height) : Collision.CanHit(base.Center, 1, 1, ownerMinionAttackTargetNPC2.Center, 1, 1))
                     {
                         num12 = num17;
                         vector = ownerMinionAttackTargetNPC2.Center;
                         flag = true;
                         num13 = ownerMinionAttackTargetNPC2.whoAmI;
                     }
                 }
             }
             if (!flag)
             {
                 for (int num19 = 0; num19 < 200; num19++)
                 {
                     NPC nPC2 = Main.npc[num19];
                     if (!nPC2.CanBeChasedBy(this))
                     {
                         continue;
                     }
                     float num20 = Vector2.Distance(nPC2.Center, base.Center);
                     if (!(num20 >= num12))
                     {
                         bool flag3 = false;
                         if ((type != 963) ? Collision.CanHitLine(position, width, height, nPC2.position, nPC2.width, nPC2.height) : Collision.CanHit(base.Center, 1, 1, nPC2.Center, 1, 1))
{
                             num12 = num20;
                             vector = nPC2.Center;
                             flag = true;
                             num13 = num19;
                         }
                     }
                 }
             }
         }
         int num21 = 500;
         if (type == 963)
         {
             num21 = 800;
         }
         if (flag)
         {
             num21 = 1000;
         }
         if (flag && type == 423)
         {
             num21 = 1200;
         }
         if (flag && type == 613)
         {
             num21 = 1350;
         }
         Player player = Main.player[owner];
         if (Vector2.Distance(player.Center, base.Center) > (float)num21)
         {
             ai[0] = 1f;
             netUpdate = true;
         }
         if (ai[0] == 1f)
         {
             tileCollide = false;
         }
         bool flag4 = false;
         if (type == 963)
         {
             flag4 = true;
         }
         if (flag4)
         {
             if (ai[0] <= 1f && localAI[1] <= 0f)
             {
                 localAI[1] = -1f;
             }
             else
             {
                 localAI[1] = Utils.Clamp(localAI[1] + 0.05f, 0f, 1f);
                 if (localAI[1] == 1f)
                 {
                     localAI[1] = -1f;
                 }
             }
         }
         if (type == 963 && velocity.Length() > 0.1f && Main.rand.Next(1500) == 0)
         {
             SoundEngine.PlaySound(SoundID.AbigailCry, base.Center);
         }
         bool flag5 = false;
         if (type == 423 || type == 407)
         {
             flag5 = true;
         }
         if (ai[0] >= 2f)
         {
             if (ai[0] == 2f && type == 963)
             {
                 SoundEngine.PlaySound(SoundID.AbigailAttack, base.Center);
             }
             ai[0] += 1f;
             if (flag4)
             {
                 localAI[1] = ai[0] / num4;
             }
             if (!flag)
             {
                 ai[0] += 1f;
             }
             if (ai[0] > num4)
             {
                 ai[0] = 0f;
                 netUpdate = true;
                 if (flag && type == 963 && (vector - base.Center).Length() < 50f)
                 {
                     ai[0] = 2f;
                 }
             }
             velocity *= num5;
         }
         else if (flag && (flag5 || ai[0] == 0f))
         {
             Vector2 v = vector - base.Center;
             float num22 = v.Length();
             v = v.SafeNormalize(Vector2.Zero);
             if (type == 423)
             {
                 v = vector - Vector2.UnitY * 80f;
                 int num23 = (int)v.Y / 16;
                 if (num23 < 0)
                 {
                     num23 = 0;
                 }
                 Tile tile = Main.tile[(int)v.X / 16, num23];
                 if (tile != null && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
                 {
                     v += Vector2.UnitY * 16f;
                     tile = Main.tile[(int)v.X / 16, (int)v.Y / 16];
                     if (tile != null && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
                     {
                         v += Vector2.UnitY * 16f;
                     }
                 }
                 v -= base.Center;
                 num22 = v.Length();
                 v = v.SafeNormalize(Vector2.Zero);
                 if (num22 > 300f && num22 <= 800f && localAI[0] == 0f)
                 {
                     ai[0] = 2f;
                     ai[1] = (int)(num22 / 10f);
                     extraUpdates = (int)ai[1];
                     velocity = v * 10f;
                     localAI[0] = 60f;
                     return;
                 }
             }
             if (type == 613)
             {
                 v = vector;
                 Vector2 vector5 = base.Center - v;
                 if (vector5 == Vector2.Zero)
                 {
                     vector5 = -Vector2.UnitY;
                 }
                 vector5 = vector5.SafeNormalize(Vector2.Zero);
                 v += vector5 * 60f;
                 int num24 = (int)v.Y / 16;
                 if (num24 < 0)
                 {
                     num24 = 0;
                 }
                 Tile tile2 = Main.tile[(int)v.X / 16, num24];
                 if (tile2 != null && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
                 {
                     v += Vector2.UnitY * 16f;
                     tile2 = Main.tile[(int)v.X / 16, (int)v.Y / 16];
                     if (tile2 != null && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
                     {
                         v += Vector2.UnitY * 16f;
                     }
                 }
                 v -= base.Center;
                 num22 = v.Length();
                 v = v.SafeNormalize(Vector2.Zero);
                 if (num22 > 400f && num22 <= 800f && localAI[0] == 0f)
                 {
                     ai[0] = 2f;
                     ai[1] = (int)(num22 / 10f);
                     extraUpdates = (int)ai[1];
                     velocity = v * 10f;
                     localAI[0] = 60f;
                     return;
                 }
             }
             if (type == 407)
             {
                 if (num22 > 400f)
                 {
                     float num25 = 3f;
                     v *= num25;
                     velocity = (velocity * 20f + v) / 21f;
                 }
                 else
                 {
                     velocity *= 0.96f;
                 }
             }
             if (num22 > 200f)
             {
                 float num26 = 6f + num2 * num;
                 v *= num26;
                 float num27 = num3 * 2f;
                 velocity.X = (velocity.X * num27 + v.X) / (num27 + 1f);
                 velocity.Y = (velocity.Y * num27 + v.Y) / (num27 + 1f);
             }
             else if (type == 963)
             {
                 if (num22 < 50f)
                 {
                     velocity *= 0.5f;
                     ai[0] = 2f;
                     netUpdate = true;
                 }
                 else
                 {
                     float num28 = 4f + num2 * num;
                     v *= num28;
                     velocity = (velocity * num3 + v) / (num3 + 1f);
                 }
             }
             else if (type == 423 || type == 613)
             {
                 if (num22 > 70f && num22 < 130f)
                 {
                     float num29 = 7f;
                     if (num22 < 100f)
                     {
                         num29 = -3f;
                     }
                     v *= num29;
                     velocity = (velocity * 20f + v) / 21f;
                     if (Math.Abs(v.X) > Math.Abs(v.Y))
                     {
                         velocity.X = (velocity.X * 10f + v.X) / 11f;
                     }
                 }
                 else
                 {
                     velocity *= 0.97f;
                 }
             }
             else if (type == 375)
             {
                 if (num22 < 150f)
                 {
                     float num30 = 4f;
                     v *= 0f - num30;
                     velocity.X = (velocity.X * 40f + v.X) / 41f;
                     velocity.Y = (velocity.Y * 40f + v.Y) / 41f;
                 }
                 else
                 {
                     velocity *= 0.97f;
                 }
             }
             else if (velocity.Y > -1f)
             {
                 velocity.Y -= 0.1f;
             }
         }
         else
         {
             if (type != 963 && !Collision.CanHitLine(base.Center, 1, 1, Main.player[owner].Center, 1, 1))
             {
                 ai[0] = 1f;
             }
             float num31 = 6f;
             if (ai[0] == 1f)
             {
                 num31 = 15f;
             }
             if (type == 407)
             {
                 num31 = 9f;
             }
             if (type == 963)
             {
                 num31 *= 0.8f;
             }
             Vector2 center2 = base.Center;
             Vector2 v2 = player.Center - center2 + new Vector2(0f, -60f);
             if (type == 407)
             {
                 v2 += new Vector2(0f, 40f);
             }
             if (type == 963)
             {
                 v2 += new Vector2(-40 * Main.player[owner].direction, 40f);
             }
             if (type == 375)
             {
                 ai[1] = 80f;
                 netUpdate = true;
                 v2 = player.Center - center2;
                 int num32 = 1;
                 for (int num33 = 0; num33 < whoAmI; num33++)
                 {
                     if (Main.projectile[num33].active && Main.projectile[num33].owner == owner && Main.projectile[num33].type == type)
                     {
                         num32++;
                     }
                 }
                 v2.X -= 10 * Main.player[owner].direction;
                 v2.X -= num32 * 40 * Main.player[owner].direction;
                 v2.Y -= 10f;
             }
             float num34 = v2.Length();
             if (num34 > 200f && num31 < 9f)
             {
                 num31 = 9f;
             }
             if ((type == 423 || type == 407) && num34 > 300f && num31 < 12f)
             {
                 num31 = 12f;
             }
             if (type == 375)
             {
                 num31 = (int)((double)num31 * 0.75);
             }
             if (num34 < 100f && ai[0] == 1f && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 netUpdate = true;
             }
             if (num34 > 2000f)
             {
                 position.X = Main.player[owner].Center.X - (float)(width / 2);
                 position.Y = Main.player[owner].Center.Y - (float)(width / 2);
             }
             if (type == 375 || type == 963)
             {
                 if (num34 > 10f)
                 {
                     v2 = v2.SafeNormalize(Vector2.Zero);
                     if (num34 < 50f)
                     {
                         num31 /= 2f;
                     }
                     v2 *= num31;
                     velocity = (velocity * 20f + v2) / 21f;
                 }
                 else
                 {
                     direction = Main.player[owner].direction;
                     velocity *= 0.9f;
                 }
             }
             else if (type == 407)
             {
                 if (Math.Abs(v2.X) > 40f || Math.Abs(v2.Y) > 10f)
                 {
                     v2 = v2.SafeNormalize(Vector2.Zero);
                     v2 *= num31;
                     v2 *= new Vector2(1.25f, 0.65f);
                     velocity = (velocity * 20f + v2) / 21f;
                 }
                 else
                 {
                     if (velocity.X == 0f && velocity.Y == 0f)
                     {
                         velocity.X = -0.15f;
                         velocity.Y = -0.05f;
                     }
                     velocity *= 1.01f;
                 }
             }
             else if (num34 > 70f)
             {
                 v2 = v2.SafeNormalize(Vector2.Zero);
                 v2 *= num31;
                 velocity = (velocity * 20f + v2) / 21f;
             }
             else
             {
                 if (velocity.X == 0f && velocity.Y == 0f)
                 {
                     velocity.X = -0.15f;
                     velocity.Y = -0.05f;
                 }
                 velocity *= 1.01f;
             }
             if (num34 > 250f && (type == 423 || type == 407))
             {
                 float x = Main.player[owner].velocity.X;
                 float y = Main.player[owner].velocity.Y;
                 if ((velocity.X < 0f && x >= 0f) || (velocity.X >= 0f && x < 0f))
                 {
                     velocity.X *= 0.95f;
                 }
                 else
                 {
                     velocity.X += x * 0.125f;
                 }
                 if ((velocity.Y < 0f && y >= 0f) || (velocity.Y >= 0f && y < 0f))
                 {
                     velocity.Y *= 0.95f;
                 }
                 else
                 {
                     velocity.Y += y * 0.125f;
                 }
                 if (velocity.Length() > num31)
                 {
                     velocity = velocity.SafeNormalize(Vector2.Zero) * num31;
                 }
             }
         }
         rotation = velocity.X * 0.05f;
         frameCounter++;
         if (type == 373)
         {
             if (frameCounter > 1)
             {
                 frame++;
                 frameCounter = 0;
             }
             if (frame > 2)
             {
                 frame = 0;
             }
         }
         if (type == 963)
         {
             if (ai[0] >= 2f)
             {
                 int num35 = 12;
                 if (frame < 8)
                 {
                     frameCounter = 0;
                 }
                 frameCounter++;
                 frame = frameCounter / num35;
                 if (frame > 6)
                 {
                     frameCounter = 0;
                     frame = 5;
                 }
                 switch (frame)
                 {
                 case 0:
                 case 1:
                 case 2:
                     frame = 8 + frame;
                     break;
                 case 3:
                 case 5:
                 case 7:
                     frame = 11;
                     break;
                 default:
                     frame = 12;
                     break;
                 }
                 if (Main.rand.Next(2) == 0)
                 {
                     float num36 = 1.1f + Main.rand.NextFloat() * 0.3f;
                     float num37 = 1.4f + Main.rand.NextFloat() * 0.4f;
                     Vector2 vector6 = Main.rand.NextVector2CircularEdge((float)width * num36, (0f - (float)height) * 0.25f * num36);
                     float num38 = vector6.ToRotation() + (float)Math.PI / 2f;
                     int num39 = Dust.NewDust(base.Bottom + vector6, 1, 1, 303, 0f, 0f, 50, Color.GhostWhite, num37);
                     Main.dust[num39].velocity = vector6 * 0.0125f + new Vector2(1f, 0f).RotatedBy(num38, Vector2.Zero);
                     Main.dust[num39].noGravity = true;
                 }
             }
             else
             {
                 if (frame > 7)
                 {
                     frame = 0;
                     frameCounter = 0;
                 }
                 if (frameCounter > 6)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame > 7)
                     {
                         frame = 0;
                     }
                 }
             }
         }
         if (type == 375)
         {
             if (frameCounter >= 16)
             {
                 frameCounter = 0;
             }
             frame = frameCounter / 4;
             if (ai[1] > 0f && ai[1] < 16f)
             {
                 frame += 4;
             }
             if (Main.rand.Next(6) == 0)
             {
                 int num40 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                 Main.dust[num40].velocity *= 0.3f;
                 Main.dust[num40].noGravity = true;
                 Main.dust[num40].noLight = true;
             }
         }
         if (type == 407)
         {
             int num41 = 2;
             if (frameCounter >= 6 * num41)
             {
                 frameCounter = 0;
             }
             frame = frameCounter / num41;
             if (Main.rand.Next(5) == 0)
             {
                 int num42 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 217, 0f, 0f, 100, default(Color), 2f);
                 Main.dust[num42].velocity *= 0.3f;
                 Main.dust[num42].noGravity = true;
                 Main.dust[num42].noLight = true;
             }
         }
         if (type == 423 || type == 613)
         {
             int num43 = 3;
             if (frameCounter >= 4 * num43)
             {
                 frameCounter = 0;
             }
             frame = frameCounter / num43;
         }
         if (velocity.X > 0f)
         {
             spriteDirection = (direction = -1);
         }
         else if (velocity.X < 0f)
         {
             spriteDirection = (direction = 1);
         }
         if (type == 963)
         {
             spriteDirection = (direction *= -1);
             if (!flag && Math.Abs(velocity.X) < 0.1f)
             {
                 spriteDirection = ((Main.player[owner].Center.X > base.Center.X) ? 1 : (-1));
             }
         }
         if (type == 373)
         {
             if (ai[1] > 0f)
             {
                 ai[1] += Main.rand.Next(1, 4);
             }
             int num44 = 90;
             if (Main.player[owner].strongBees)
             {
                 num44 = 70;
             }
             if (ai[1] > (float)num44)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         else if (type == 375)
         {
             if (ai[1] > 0f)
             {
                 ai[1] += 1f;
                 if (Main.rand.Next(3) == 0)
                 {
                     ai[1] += 1f;
                 }
             }
             if (ai[1] > 90f)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         else if (type == 407)
         {
             if (ai[1] > 0f)
             {
                 ai[1] += 1f;
                 if (Main.rand.Next(3) != 0)
                 {
                     ai[1] += 1f;
                 }
             }
             if (ai[1] > 50f)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         else if (type == 423)
         {
             if (ai[1] > 0f)
             {
                 ai[1] += 1f;
                 if (Main.rand.Next(3) != 0)
                 {
                     ai[1] += 1f;
                 }
             }
             if (ai[1] > 40f)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         else if (type == 613)
         {
             if (ai[1] > 0f)
             {
                 ai[1] += 1f;
                 if (Main.rand.Next(3) != 0)
                 {
                     ai[1] += 1f;
                 }
             }
             if (ai[1] > 60f)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
         }
         if (!flag5 && ai[0] != 0f)
         {
             return;
         }
         float num45 = 0f;
         int num46 = 0;
         if (type == 373)
         {
             num45 = 10f;
             num46 = 374;
         }
         else if (type == 375)
         {
             num45 = 11f;
             num46 = 376;
         }
         else if (type == 407)
         {
             num45 = 20f;
             num46 = 408;
         }
         else if (type == 423)
         {
             num45 = 4f;
             num46 = 433;
         }
         else if (type == 613)
         {
             num45 = 14f;
             num46 = 614;
         }
         if (!flag)
         {
             return;
         }
         if (type == 375)
         {
             if ((vector - base.Center).X > 0f)
             {
                 spriteDirection = (direction = -1);
             }
             else if ((vector - base.Center).X < 0f)
             {
                 spriteDirection = (direction = 1);
             }
         }
         if (type == 407 && Collision.SolidCollision(position, width, height))
         {
             return;
         }
         if (type == 423)
         {
             if (Math.Abs((vector - base.Center).ToRotation() - (float)Math.PI / 2f) > (float)Math.PI / 4f)
             {
                 velocity += (vector - base.Center - Vector2.UnitY * 80f).SafeNormalize(Vector2.Zero);
             }
             if (!((vector - base.Center).Length() > 400f) && ai[1] == 0f)
             {
                 ai[1] += 1f;
                 if (Main.myPlayer == owner)
                 {
                     Vector2 v3 = vector - base.Center;
                     v3 = v3.SafeNormalize(Vector2.Zero);
                     v3 *= num45;
                     NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v3.X, v3.Y, num46, damage, knockBack, Main.myPlayer);
                     netUpdate = true;
                 }
             }
         }
         else if (ai[1] == 0f && type == 613)
         {
             if ((vector - base.Center).Length() > 500f || ai[1] != 0f)
             {
                 return;
             }
             ai[1] += 1f;
             if (Main.myPlayer == owner)
             {
                 Vector2 v4 = vector - base.Center;
                 v4 = v4.SafeNormalize(Vector2.Zero);
                 v4 *= num45;
                 int num47 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v4.X, v4.Y, num46, damage, knockBack, Main.myPlayer, 0f, num13);
                 Main.projectile[num47].timeLeft = 300;
                 Main.projectile[num47].netUpdate = true;
                 velocity -= v4 / 3f;
                 netUpdate = true;
             }
             for (int num48 = 0; num48 < 5; num48++)
             {
                 int num49 = width / 4;
                 _ = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2() * Main.rand.Next(24, 41) / 8f;
                 int num50 = Dust.NewDust(base.Center - Vector2.One * num49, num49 * 2, num49 * 2, 88);
                 Dust dust3 = Main.dust[num50];
                 Vector2 vector7 = (dust3.position - base.Center).SafeNormalize(Vector2.Zero);
                 dust3.position = base.Center + vector7 * num49 * scale - new Vector2(4f);
                 if (num48 < 30)
                 {
                     dust3.velocity = vector7 * dust3.velocity.Length() * 2f;
                 }
                 else
                 {
                     dust3.velocity = 2f * vector7 * Main.rand.Next(45, 91) / 10f;
                 }
                 dust3.noGravity = true;
                 dust3.scale = 0.7f + Main.rand.NextFloat();
             }
         }
         else if (ai[1] == 0f)
         {
             Vector2 v5 = vector - base.Center;
             ai[1] += 1f;
             if (Main.myPlayer == owner)
             {
                 v5 = v5.SafeNormalize(Vector2.Zero);
                 v5 *= num45;
                 int num51 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v5.X, v5.Y, num46, damage, knockBack, Main.myPlayer);
                 Main.projectile[num51].timeLeft = 300;
                 Main.projectile[num51].netUpdate = true;
                 netUpdate = true;
             }
         }
     }
References SoundID.AbigailAttack, SoundID.AbigailCry, Player.abigailMinion, Entity.active, Tile.active(), Lighting.AddLight(), NPC.CanBeChasedBy(), Collision.CanHit(), Collision.CanHitLine(), Entity.Center, Color, Player.dead, Entity.direction, Entity.Distance(), Main.dust, Dust.fadeIn, Dust.frame, Entity.height, Player.highestAbigailCounterOriginalDamage, Player.hornetMinion, Player.impMinion, Main.myPlayer, netUpdate, Dust.NewDust(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, Dust.noLight, Main.npc, Player.ownedProjectileCounts, owner, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.projectile, Main.rand, Dust.scale, Player.sharknadoMinion, Entity.Size, Collision.SolidCollision(), Player.stardustMinion, Player.strongBees, Main.tile, Main.tileSolid, Main.tileSolidTop, timeLeft, type, Tile.type, Player.UFOMinion, Dust.velocity, Entity.velocity, Entity.whoAmI, and Entity.width.