Terraria: Projectile.AI_168_FirstFractal
AI_168_FirstFractal()
void Projectile.AI_168_FirstFractal () inline private
     {
         float num = 60f;
         if ((localAI[0] += 1f) >= num - 1f)
         {
             Kill();
             return;
         }
         if (frameCounter == 0)
         {
             frameCounter = 1;
             frame = Main.rand.Next(15);
         }
         velocity = velocity.RotatedBy(ai[0]);
         Opacity = Utils.GetLerpValue(0f, 12f, localAI[0], clamped: true) * Utils.GetLerpValue(num, num - 12f, localAI[0], clamped: true);
         direction = ((velocity.X > 0f) ? 1 : (-1));
         spriteDirection = direction;
         rotation = (float)Math.PI / 4f * (float)spriteDirection + velocity.ToRotation();
         if (spriteDirection == -1)
         {
             rotation += (float)Math.PI;
         }
         if (localAI[0] > 7f)
         {
             int num2 = 5;
             _ = base.Center - new Vector2(num2);
             if (Main.rand.Next(15) == 0)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center, 278, null, 100, Color.Lerp(GetFirstFractalColor(), Color.White, Main.rand.NextFloat() * 0.3f));
                 dust.scale = 0.7f;
                 dust.noGravity = true;
                 dust.velocity *= 0.5f;
                 dust.velocity += velocity * 2f;
             }
         }
     }
References Color, Utils.GetLerpValue(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Main.rand, Dust.scale, and Dust.velocity.