Terraria: Projectile.AI_121_StardustDragon
AI_121_StardustDragon()
void Projectile.AI_121_StardustDragon () inline private
     {
         Player player = Main.player[owner];
         if ((int)Main.timeForVisualEffects % 120 == 0)
         {
             netUpdate = true;
         }
         if (!player.active)
         {
             active = false;
             return;
         }
         bool num = type == 625;
         bool flag = type == 625 || type == 626 || type == 627 || type == 628;
         int num2 = 10;
         if (flag)
         {
             if (player.dead)
             {
                 player.stardustDragon = false;
             }
             if (player.stardustDragon)
             {
                 timeLeft = 2;
             }
             num2 = 30;
             if (Main.rand.Next(30) == 0)
             {
                 int num3 = Dust.NewDust(position, width, height, 135, 0f, 0f, 0, default(Color), 2f);
                 Main.dust[num3].noGravity = true;
                 Main.dust[num3].fadeIn = 2f;
                 Point point = Main.dust[num3].position.ToTileCoordinates();
                 if (WorldGen.InWorld(point.X, point.Y, 5) && WorldGen.SolidTile(point.X, point.Y))
                 {
                     Main.dust[num3].noLight = true;
                 }
             }
         }
         if (num)
         {
             Vector2 center = player.Center;
             float num4 = 700f;
             float num5 = 1000f;
             int num6 = -1;
             if (Distance(center) > 2000f)
             {
                 base.Center = center;
                 netUpdate = true;
             }
             if (true)
             {
                 NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
                 if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
                 {
                     float num7 = Distance(ownerMinionAttackTargetNPC.Center);
                     if (num7 < num4 * 2f)
                     {
                         num6 = ownerMinionAttackTargetNPC.whoAmI;
                         if (ownerMinionAttackTargetNPC.boss)
{
                             _ = ownerMinionAttackTargetNPC.whoAmI;
                         }
                         else
{
                             _ = ownerMinionAttackTargetNPC.whoAmI;
                         }
                     }
                 }
                 if (num6 < 0)
                 {
                     for (int i = 0; i < 200; i++)
                     {
                         NPC nPC = Main.npc[i];
                         if (nPC.CanBeChasedBy(this) && player.Distance(nPC.Center) < num5)
{
                             float num8 = Distance(nPC.Center);
                             if (num8 < num4)
{
                                 num6 = i;
                                 _ = nPC.boss;
                             }
                         }
                     }
                 }
             }
             if (num6 != -1)
             {
                 NPC nPC2 = Main.npc[num6];
                 Vector2 vector = nPC2.Center - base.Center;
                 (vector.X > 0f).ToDirectionInt();
                 (vector.Y > 0f).ToDirectionInt();
                 float num9 = 0.4f;
                 if (vector.Length() < 600f)
                 {
                     num9 = 0.6f;
                 }
                 if (vector.Length() < 300f)
                 {
                     num9 = 0.8f;
                 }
                 if (vector.Length() > nPC2.Size.Length() * 0.75f)
                 {
                     velocity += Vector2.Normalize(vector) * num9 * 1.5f;
                     if (Vector2.Dot(velocity, vector) < 0.25f)
                     {
                         velocity *= 0.8f;
                     }
                 }
                 float num10 = 30f;
                 if (velocity.Length() > num10)
                 {
                     velocity = Vector2.Normalize(velocity) * num10;
                 }
             }
             else
             {
                 float num11 = 0.2f;
                 Vector2 vector2 = center - base.Center;
                 if (vector2.Length() < 200f)
                 {
                     num11 = 0.12f;
                 }
                 if (vector2.Length() < 140f)
                 {
                     num11 = 0.06f;
                 }
                 if (vector2.Length() > 100f)
                 {
                     if (Math.Abs(center.X - base.Center.X) > 20f)
                     {
                         velocity.X += num11 * (float)Math.Sign(center.X - base.Center.X);
                     }
                     if (Math.Abs(center.Y - base.Center.Y) > 10f)
                     {
                         velocity.Y += num11 * (float)Math.Sign(center.Y - base.Center.Y);
                     }
                 }
                 else if (velocity.Length() > 2f)
                 {
                     velocity *= 0.96f;
                 }
                 if (Math.Abs(velocity.Y) < 1f)
                 {
                     velocity.Y -= 0.1f;
                 }
                 float num12 = 15f;
                 if (velocity.Length() > num12)
                 {
                     velocity = Vector2.Normalize(velocity) * num12;
                 }
             }
             rotation = velocity.ToRotation() + (float)Math.PI / 2f;
             int num13 = direction;
             direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
             if (num13 != direction)
             {
                 netUpdate = true;
             }
             float num14 = MathHelper.Clamp(localAI[0], 0f, 50f);
             position = base.Center;
             scale = 1f + num14 * 0.01f;
             width = (height = (int)((float)num2 * scale));
             base.Center = position;
             if (alpha > 0)
             {
                 for (int j = 0; j < 2; j++)
                 {
                     int num15 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, 0f, 0f, 100, default(Color), 2f);
                     Main.dust[num15].noGravity = true;
                     Main.dust[num15].noLight = true;
                 }
                 alpha -= 42;
                 if (alpha < 0)
                 {
                     alpha = 0;
                 }
             }
         }
         else
         {
             bool flag2 = false;
             Vector2 vector3 = Vector2.Zero;
             _ = Vector2.Zero;
             float num16 = 0f;
             float num17 = 0f;
             float num18 = 1f;
             if (ai[1] == 1f)
             {
                 ai[1] = 0f;
                 netUpdate = true;
             }
             int byUUID = GetByUUID(owner, (int)ai[0]);
             if (Main.projectile.IndexInRange(byUUID))
             {
                 Projectile projectile = Main.projectile[byUUID];
                 if (flag && projectile.active && (projectile.type == 625 || projectile.type == 626 || projectile.type == 627))
                 {
                     flag2 = true;
                     vector3 = projectile.Center;
                     _ = projectile.velocity;
                     num16 = projectile.rotation;
                     num18 = MathHelper.Clamp(projectile.scale, 0f, 50f);
                     num17 = 16f;
                     _ = projectile.alpha;
                     projectile.localAI[0] = localAI[0] + 1f;
                     if (projectile.type != 625)
                     {
                         projectile.localAI[1] = whoAmI;
                     }
                     if (owner == Main.myPlayer && type == 628 && projectile.type == 625)
                     {
                         projectile.Kill();
                         Kill();
                         return;
                     }
                 }
             }
             if (!flag2)
             {
                 for (int k = 0; k < 1000; k++)
                 {
                     Projectile projectile2 = Main.projectile[k];
                     if (projectile2.active && projectile2.owner == owner && ProjectileID.Sets.StardustDragon[projectile2.type] && projectile2.localAI[1] == ai[0])
                     {
                         ai[0] = projectile2.projUUID;
                         projectile2.localAI[1] = whoAmI;
                         netUpdate = true;
                     }
                 }
                 return;
             }
             if (alpha > 0)
             {
                 for (int l = 0; l < 2; l++)
                 {
                     int num19 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100, default(Color), 2f);
                     Main.dust[num19].noGravity = true;
                     Main.dust[num19].noLight = true;
                 }
             }
             alpha -= 42;
             if (alpha < 0)
             {
                 alpha = 0;
             }
             velocity = Vector2.Zero;
             Vector2 vector4 = vector3 - base.Center;
             if (num16 != rotation)
             {
                 float num20 = MathHelper.WrapAngle(num16 - rotation);
                 vector4 = vector4.RotatedBy(num20 * 0.1f);
             }
             rotation = vector4.ToRotation() + (float)Math.PI / 2f;
             position = base.Center;
             scale = num18;
             width = (height = (int)((float)num2 * scale));
             base.Center = position;
             if (vector4 != Vector2.Zero)
             {
                 base.Center = vector3 - Vector2.Normalize(vector4) * num17 * num18;
             }
             spriteDirection = ((vector4.X > 0f) ? 1 : (-1));
         }
         position.X = MathHelper.Clamp(position.X, 160f, Main.maxTilesX * 16 - 160);
         position.Y = MathHelper.Clamp(position.Y, 160f, Main.maxTilesY * 16 - 160);
     }
References Entity.active, alpha, NPC.boss, NPC.CanBeChasedBy(), Entity.Center, Color, Player.dead, Entity.Distance(), Main.dust, Dust.fadeIn, WorldGen.InWorld(), Kill(), localAI, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, owner, Main.player, Dust.position, Main.projectile, projUUID, Main.rand, rotation, scale, Entity.Size, WorldGen.SolidTile(), ProjectileID.Sets.StardustDragon, Player.stardustDragon, Main.timeForVisualEffects, type, Entity.velocity, and Entity.whoAmI.