Terraria: Projectile.AI_187_ShadowHand
AI_187_ShadowHand()
void Projectile.AI_187_ShadowHand () inline private
     {
         //IL_0041: Unknown result type (might be due to invalid IL or missing references)
         //IL_002a: Unknown result type (might be due to invalid IL or missing references)
         //IL_002f: Unknown result type (might be due to invalid IL or missing references)
         //IL_0058: Unknown result type (might be due to invalid IL or missing references)
         //IL_005d: Unknown result type (might be due to invalid IL or missing references)
         AI_187_ShadowHand_GetVariation(out var variation, out var fakeCounter, out var counterMax);
         float fromValue = fakeCounter / counterMax;
         SlotId val;
         if (fakeCounter == 0f)
         {
             float[] array = localAI;
             val = SoundEngine.PlayTrackedSound(SoundID.DD2_GhastlyGlaiveImpactGhost, base.Center);
             array[1] = ((SlotId)(ref val)).ToFloat();
         }
         ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
         if (activeSound == null)
         {
             float[] array2 = localAI;
             val = SlotId.Invalid;
             array2[1] = ((SlotId)(ref val)).ToFloat();
         }
         else
         {
             activeSound.Position = base.Center;
         }
         float num = counterMax - 15f;
         if (fakeCounter > num)
         {
             alpha += 25;
             if (alpha > 255)
             {
                 alpha = 255;
             }
         }
         else
         {
             alpha -= 25;
             if (alpha < 50)
             {
                 alpha = 50;
             }
         }
         if (fakeCounter >= counterMax - 1f)
         {
             Kill();
             return;
         }
         if (variation == 0)
         {
             velocity *= 0.98f;
             direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
             rotation = velocity.ToRotation();
             if (spriteDirection == -1)
             {
                 rotation += (float)Math.PI;
             }
         }
         if (variation == 1)
         {
             float num2 = 70f;
             direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
             if (velocity.Length() > 0.1f)
             {
                 velocity *= 0.95f;
             }
             num2 *= (float)direction;
             Vector2 vector = base.Center - rotation.ToRotationVector2() * num2;
             float num3 = Utils.Remap(fromValue, 0.3f, 0.5f, 0f, 1f) * Utils.Remap(fromValue, 0.45f, 0.5f, 1f, 0f);
             float num4 = Utils.Remap(fromValue, 0.5f, 0.55f, 0f, 1f) * Utils.Remap(fromValue, 0.5f, 1f, 1f, 0f);
             float num5 = num3 * (float)Math.PI * 1f / 60f;
             num5 += num4 * -(float)Math.PI * 8f / 60f;
             rotation += num5 * (float)(-direction);
             rotation = MathHelper.WrapAngle(rotation);
             base.Center = vector + rotation.ToRotationVector2() * num2;
         }
         if (variation == 2)
         {
             float f = ai[1];
             float num6 = Utils.Remap(fromValue, 0f, 0.4f, 1f, 0f);
             float num7 = Utils.Remap(fromValue, 0.3f, 0.4f, 0f, 1f) * Utils.Remap(fromValue, 0.4f, 1f, 1f, 0f);
             float num8 = num6 * 2f + num7 * 8f + 0.01f;
             velocity = f.ToRotationVector2() * num8;
             direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
             rotation = velocity.ToRotation();
             if (spriteDirection == -1)
             {
                 rotation += (float)Math.PI;
             }
         }
         if (variation == 3)
         {
             float num9 = ai[1];
             velocity = velocity.RotatedBy(num9);
             direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
             rotation = velocity.ToRotation();
             if (spriteDirection == -1)
             {
                 rotation += (float)Math.PI;
             }
         }
         ai[0] += 1f;
     }
References SoundID.DD2_GhastlyGlaiveImpactGhost, SlotId.FromFloat(), SoundEngine.GetActiveSound(), SlotId.Invalid, SoundEngine.PlayTrackedSound(), ActiveSound.Position, and Utils.Remap().