Terraria: Projectile.CutTilesAt
CutTilesAt()
void Projectile.CutTilesAt (Vector2 boxPosition, int boxWidth, int boxHeight) inline private
     {
         int num = (int)(boxPosition.X / 16f);
         int num2 = (int)((boxPosition.X + (float)boxWidth) / 16f) + 1;
         int num3 = (int)(boxPosition.Y / 16f);
         int num4 = (int)((boxPosition.Y + (float)boxHeight) / 16f) + 1;
         if (num < 0)
         {
             num = 0;
         }
         if (num2 > Main.maxTilesX)
         {
             num2 = Main.maxTilesX;
         }
         if (num3 < 0)
         {
             num3 = 0;
         }
         if (num4 > Main.maxTilesY)
         {
             num4 = Main.maxTilesY;
         }
         bool[] tileCutIgnorance = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
         for (int i = num; i < num2; i++)
         {
             for (int j = num3; j < num4; j++)
             {
                 if (Main.tile[i, j] != null && Main.tileCut[Main.tile[i, j].type] && !tileCutIgnorance[Main.tile[i, j].type] && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackProjectile))
                 {
                     WorldGen.KillTile(i, j);
                     if (Main.netMode != 0)
                     {
                         NetMessage.SendData(17, -1, -1, null, 0, i, j);
                     }
                 }
             }
         }
     }
References WorldGen.CanCutTile(), Player.GetTileCutIgnorance(), WorldGen.KillTile(), Main.maxTilesX, Main.maxTilesY, Main.netMode, owner, Main.player, NetMessage.SendData(), Main.tile, Main.tileCut, trap, and Tile.type.
Referenced by CutTiles().