Terraria: System.Reflection.RuntimeMethodInfo.InvokeOneParameter
InvokeOneParameter()
object System.Reflection.RuntimeMethodInfo.InvokeOneParameter (object obj, BindingFlags invokeAttr, Binder binder, object parameter, CultureInfo culture) inline package
Definition at line 474 of file RuntimeMethodInfo.cs.
    {
        if ((InvocationFlags & (INVOCATION_FLAGS.INVOCATION_FLAGS_NO_INVOKE | INVOCATION_FLAGS.INVOCATION_FLAGS_CONTAINS_STACK_POINTERS)) != 0)
        {
            ThrowNoInvokeException();
        }
        CheckConsistency(obj);
        Signature signature = Signature;
        if (signature.Arguments.Length != 1)
        {
            throw new TargetParameterCountException(SR.Arg_ParmCnt);
        }
        StackAllocedArguments stackArgs = default(StackAllocedArguments);
        Span<object> arguments = CheckArguments(ref stackArgs, new ReadOnlySpan<object>(ref parameter, 1), binder, invokeAttr, culture, signature);
        bool wrapExceptions = (invokeAttr & BindingFlags.DoNotWrapExceptions) == 0;
        return RuntimeMethodHandle.InvokeMethod(obj, in arguments, Signature, constructor: false, wrapExceptions);
    }
References System.SR.Arg_ParmCnt, System.Reflection.MethodBase.CheckArguments(), System.Reflection.RuntimeMethodInfo.CheckConsistency(), System.culture, System.Reflection.RuntimeMethodInfo.InvocationFlags, System.RuntimeMethodHandle.InvokeMethod(), System.obj, System.Reflection.RuntimeMethodInfo.Signature, and System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException().