Terraria: Projectile.AI_147_Explosion
AI_147_Explosion()
void Projectile.AI_147_Explosion () inline private
     {
         switch ((int)ai[0])
         {
         case 0:
         {
             for (int k = 0; k < 4; k++)
             {
                 Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
             }
             for (int l = 0; l < 20; l++)
             {
                 int num5 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 130, 0f, 0f, 200, default(Color), 1.2f);
                 Main.dust[num5].noGravity = true;
                 Main.dust[num5].velocity *= 3f;
                 num5 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 130, 0f, 0f, 200, default(Color), 0.5f);
                 Main.dust[num5].velocity *= 1.2f;
                 Main.dust[num5].noGravity = true;
             }
             for (int m = 0; m < 1; m++)
             {
                 int num6 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num6].velocity *= 0.3f;
                 Main.gore[num6].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num6].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
             break;
         }
         case 1:
         {
             Color celeb2Color2 = GetCeleb2Color();
             Vector2 center2 = base.Center;
             Main.rand.NextFloat();
             for (float num7 = 0f; num7 < 1f; num7 += 0.0125f)
             {
                 Dust dust4 = Dust.NewDustPerfect(center2, 278, null, 200, Color.Lerp(celeb2Color2, Color.White, Main.rand.NextFloat() * 0.6f));
                 dust4.scale = 1.1f;
                 dust4.fadeIn = 1.3f;
                 dust4.velocity *= Main.rand.NextFloat() * 2f + 2f;
                 if (dust4.velocity.Y > 0f)
                 {
                     dust4.velocity *= 0.3f;
                 }
                 dust4.velocity *= 2f;
             }
             for (int n = 0; n < 3; n++)
             {
                 int num8 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num8].velocity *= 0.3f;
                 Main.gore[num8].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num8].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
             int fluff = 20;
             int distFluff = 100;
             int layerStart = 2;
             int layerEnd = 10;
             int layerJump = 2;
             CreateGroundExplosion(40f, fluff, distFluff, layerStart, layerEnd, layerJump);
             break;
         }
         case 2:
         {
             Vector2 center3 = base.Center;
             Color celeb2Color3 = GetCeleb2Color();
             float num9 = 0.05f;
             float num10 = 0.13f;
             bool flag = Main.rand.Next(4) == 0;
             if (flag)
             {
                 num9 = 0.1f;
                 num10 = 0.1f;
             }
             float num11 = Main.rand.NextFloatDirection();
             for (float num12 = 0f; num12 < 5f; num12 += 1f)
             {
                 Vector2 spinningpoint = new Vector2(0f, -100f);
                 Vector2 vector4 = center3 + spinningpoint.RotatedBy(num11 + num12 * ((float)Math.PI * 2f / 5f));
                 Vector2 vector5 = center3 + spinningpoint.RotatedBy(num11 + (num12 + 1f) * ((float)Math.PI * 2f / 5f));
                 Vector2 vector6 = center3 + spinningpoint.RotatedBy(num11 + (num12 + 0.5f) * ((float)Math.PI * 2f / 5f)) * 0.4f;
                 for (int num13 = 0; num13 < 2; num13++)
                 {
                     Vector2 value = vector4;
                     Vector2 value2 = vector6;
                     if (num13 == 1)
                     {
                         value = vector6;
                         value2 = vector5;
                     }
                     for (float num14 = 0f; num14 < 1f; num14 += num10)
                     {
                         Vector2 vector7 = Vector2.Lerp(value, value2, num14);
                         Vector2 vector8 = Vector2.Lerp(vector7, center3, 0.9f);
                         Vector2 vector9 = (vector7 - vector8).SafeNormalize(Vector2.Zero);
                         Dust dust5 = Dust.NewDustPerfect(vector8, 267, Vector2.Zero, 0, celeb2Color3, 0.5f);
                         dust5.fadeIn = 1.2f;
                         dust5.noGravity = true;
                         dust5.velocity = vector9 * Vector2.Distance(vector7, vector8) * num9;
                     }
                 }
             }
             if (flag)
             {
                 for (int num15 = 0; num15 < 4; num15++)
                 {
                     Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                 }
                 for (int num16 = 0; num16 < 60; num16++)
                 {
                     int num17 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 200, default(Color), 2.5f);
                     Main.dust[num17].noGravity = true;
                     Main.dust[num17].velocity *= 8f;
                     num17 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 200, default(Color), 1.5f);
                     Main.dust[num17].velocity *= 4.2f;
                     Main.dust[num17].noGravity = true;
                 }
                 for (int num18 = 0; num18 < 1; num18++)
                 {
                     int num19 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                     Main.gore[num19].velocity *= 0.3f;
                     Main.gore[num19].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                     Main.gore[num19].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
                 }
             }
             else
             {
                 for (int num20 = 0; num20 < 4; num20++)
                 {
                     Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                 }
                 for (int num21 = 0; num21 < 40; num21++)
                 {
                     int num22 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 200, default(Color), 2.5f);
                     Main.dust[num22].noGravity = true;
                     Main.dust[num22].velocity *= 4f;
                     num22 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 200, default(Color), 1.5f);
                     Main.dust[num22].velocity *= 2.2f;
                     Main.dust[num22].noGravity = true;
                 }
                 for (int num23 = 0; num23 < 1; num23++)
                 {
                     int num24 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                     Main.gore[num24].velocity *= 0.3f;
                     Main.gore[num24].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                     Main.gore[num24].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
                 }
             }
             break;
         }
         case 3:
         {
             Color celeb2Color5 = GetCeleb2Color();
             Vector2 center4 = base.Center;
             for (int num27 = 0; num27 < 4; num27++)
             {
                 Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
             }
             float num28 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
             for (int num29 = 0; num29 < 40; num29++)
             {
                 Dust dust6 = Dust.NewDustPerfect(center4, 278, null, 100, Color.Lerp(celeb2Color5, Color.White, Main.rand.NextFloat() * 0.3f));
                 dust6.scale = 1.3f * (dust6.velocity.Length() / 2f);
                 dust6.fadeIn = 1.5f * (dust6.velocity.Length() / 2f);
                 dust6.noGravity = true;
                 dust6.velocity *= 6f;
                 if (Math.Abs(dust6.velocity.X) > Math.Abs(dust6.velocity.Y))
                 {
                     dust6.velocity.Y *= 0.1f;
                 }
                 else
                 {
                     dust6.velocity.X *= 0.1f;
                 }
                 dust6.velocity = dust6.velocity.RotatedBy(num28);
             }
             for (int num30 = 0; num30 < 1; num30++)
             {
                 int num31 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num31].velocity *= 0.3f;
                 Main.gore[num31].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num31].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
             break;
         }
         case 4:
         {
             GetCeleb2Color();
             Vector2 center5 = base.Center;
             Main.rand.NextFloat();
             for (float num32 = 0f; num32 < 1f; num32 += 0.025f)
             {
                 Dust dust7 = Dust.NewDustPerfect(center5, 132, null, 200);
                 dust7.scale = 1.1f;
                 dust7.fadeIn = 1.5f;
                 dust7.velocity *= Main.rand.NextFloat() * 2f + 2f;
                 if (dust7.velocity.Y > 0f)
                 {
                     dust7.velocity *= 0.3f;
                 }
                 dust7.velocity *= 2f;
             }
             for (int num33 = 0; num33 < 3; num33++)
             {
                 int num34 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num34].velocity *= 0.3f;
                 Main.gore[num34].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num34].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
             break;
         }
         case 5:
         {
             Color celeb2Color4 = GetCeleb2Color();
             _ = base.Center;
             for (int num25 = 0; num25 < 20; num25++)
             {
                 int num26 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 278, 0f, 0f, 200, Color.Lerp(celeb2Color4, Color.White, Main.rand.NextFloat() * 0.4f), 2.5f);
                 Main.dust[num26].fadeIn = 1.3f;
                 Main.dust[num26].scale = 1.1f;
                 Main.dust[num26].velocity *= 2f;
                 num26 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 27, 0f, 0f, 200, celeb2Color4, 2.5f);
                 Main.dust[num26].velocity *= 1.2f;
                 Main.dust[num26].noGravity = true;
             }
             break;
         }
         case 6:
         {
             Color celeb2Color = GetCeleb2Color();
             Vector2 center = base.Center;
             for (int i = 0; i < 4; i++)
             {
                 Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
             }
             for (float num = 0f; num < 1f; num += 0.015f)
             {
                 Vector2 vector = Vector2.UnitY.RotatedBy(num * ((float)Math.PI * 2f)) * (1f + Main.rand.NextFloatDirection() * 0.1f);
                 Dust dust = Dust.NewDustPerfect(center + vector, 134, Vector2.Zero, 0, celeb2Color);
                 dust.scale = 1.4f;
                 dust.velocity = vector * 5f;
                 dust.velocity.Y += -3f;
                 dust.velocity *= 2f;
             }
             for (float num2 = 0f; num2 < 1f; num2 += 0.025f)
             {
                 Vector2 vector2 = Vector2.UnitY.RotatedBy(num2 * ((float)Math.PI * 2f)) * (1f + Main.rand.NextFloatDirection() * 0.2f);
                 Dust dust2 = Dust.NewDustPerfect(center + vector2, 267, Vector2.Zero, 0, celeb2Color);
                 dust2.noGravity = true;
                 dust2.scale = 0.4f;
                 dust2.fadeIn = 1.2f;
                 dust2.velocity = vector2 * 4f;
                 dust2.velocity.Y += -3f;
                 dust2.velocity *= 2f;
             }
             for (float num3 = 0f; num3 < 1f; num3 += 0.07f)
             {
                 Vector2 vector3 = Vector2.UnitY.RotatedBy(num3 * ((float)Math.PI * 2f)) * (1f + Main.rand.NextFloatDirection() * 0.3f);
                 Dust dust3 = Dust.NewDustPerfect(center + vector3, 267, Vector2.Zero, 0, celeb2Color);
                 dust3.noGravity = true;
                 dust3.scale = 0.4f;
                 dust3.fadeIn = 1.3f;
                 dust3.velocity = vector3 * 7f;
                 dust3.velocity.Y += -3f;
                 dust3.velocity *= 2f;
             }
             for (int j = 0; j < 1; j++)
             {
                 int num4 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num4].velocity *= 0.3f;
                 Main.gore[num4].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num4].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
             break;
         }
         }
     }
References Color, Main.dust, Dust.fadeIn, Main.gore, Dust.NewDust(), Dust.NewDustPerfect(), Gore.NewGore(), UnifiedRandom.Next(), Dust.noGravity, Main.rand, Dust.scale, Dust.velocity, and Gore.velocity.