Terraria: Projectile.AI_184_BadTorchLuck
AI_184_BadTorchLuck()
void Projectile.AI_184_BadTorchLuck () inline private
     {
         owner = 255;
         if (Main.player[Main.myPlayer].unlockedBiomeTorches)
         {
             damage = 0;
         }
         if (localAI[0] == 0f)
         {
             localAI[0] = 1f;
             SoundEngine.PlaySound(SoundID.Item8, base.Center);
         }
         if (ai[1] > 0f)
         {
             ai[1] -= velocity.Length();
         }
         else
         {
             tileCollide = true;
         }
         int num = (int)ai[0];
         float num2 = 4f;
         for (float num3 = 0f; num3 < num2; num3 += 1f)
         {
             int num4 = Dust.NewDust(position + velocity / num2 * num3, 4, 4, num, 0f, 0f, 100);
             if (Main.rand.Next(3) != 0)
             {
                 Main.dust[num4].noGravity = true;
             }
             Main.dust[num4].velocity *= 0.3f;
             if (num == 66)
             {
                 Main.dust[num4].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                 Main.dust[num4].noGravity = true;
             }
         }
     }
References Color, Dust.color, Main.DiscoB, Main.DiscoG, Main.DiscoR, Main.dust, SoundID.Item8, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Dust.noGravity, Main.player, SoundEngine.PlaySound(), Main.rand, Player.unlockedBiomeTorches, and Dust.velocity.