Terraria: Projectile.FindTargetWithLineOfSight
FindTargetWithLineOfSight()
int Projectile.FindTargetWithLineOfSight (float maxRange = 800f) inline
     {
         float num = maxRange;
         int result = -1;
         for (int i = 0; i < 200; i++)
         {
             NPC nPC = Main.npc[i];
             bool flag = nPC.CanBeChasedBy(this);
             if (localNPCImmunity[i] != 0)
             {
                 flag = false;
             }
             if (flag)
             {
                 float num2 = Distance(Main.npc[i].Center);
                 if (num2 < num && Collision.CanHit(position, width, height, nPC.position, nPC.width, nPC.height))
                 {
                     num = num2;
                     result = i;
                 }
             }
         }
         return result;
     }
References NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Entity.height, Main.npc, Entity.position, and Entity.width.
Referenced by AI(), Damage(), and HandleMovement().