Terraria: System.Reflection.RuntimeMethodInfo.ToString
ToString()
override string System.Reflection.RuntimeMethodInfo.ToString () inline
Definition at line 239 of file RuntimeMethodInfo.cs.
    {
        if (m_toString == null)
        {
            ValueStringBuilder sbParamList = new ValueStringBuilder(100);
            sbParamList.Append(ReturnType.FormatTypeName());
            sbParamList.Append(' ');
            sbParamList.Append(Name);
            if (IsGenericMethod)
            {
                sbParamList.Append(RuntimeMethodHandle.ConstructInstantiation(this, TypeNameFormatFlags.FormatBasic));
            }
            sbParamList.Append('(');
            MethodBase.AppendParameters(ref sbParamList, GetParameterTypes(), CallingConvention);
            sbParamList.Append(')');
            m_toString = sbParamList.ToString();
        }
        return m_toString;
    }
References System.Reflection.MethodBase.AppendParameters(), System.RuntimeMethodHandle.ConstructInstantiation(), System.Reflection.MethodBase.GetParameterTypes(), System.Reflection.RuntimeMethodInfo.IsGenericMethod, System.Reflection.RuntimeMethodInfo.m_toString, System.Reflection.RuntimeMethodInfo.Name, and System.Reflection.RuntimeMethodInfo.ReturnType.