Terraria: Projectile.AI_191_TrueNightsEdge
AI_191_TrueNightsEdge()
void Projectile.AI_191_TrueNightsEdge () inline private
     {
         float num = 50f;
         float num2 = 15f;
         float num3 = ai[1] + num;
         float num4 = num3 + num2;
         float num5 = 77f;
         if (type == 985)
         {
             num = 0f;
             num3 = ai[1];
             num4 = ai[1] + 25f;
             num5 = num4;
         }
         if (localAI[0] == 0f && type == 973)
         {
             SoundEngine.PlaySound(SoundID.Item8, base.position);
         }
         localAI[0] += 1f;
         if (type == 985 && localAI[1] == 1f)
         {
             localAI[0] += 2f;
         }
         if (type == 973 && damage == 0 && localAI[0] < MathHelper.Lerp(num3, num4, 0.5f))
         {
             localAI[0] += 6f;
         }
         Opacity = Utils.Remap(localAI[0], 0f, ai[1], 0f, 1f) * Utils.Remap(localAI[0], num3, num4, 1f, 0f);
         if (localAI[0] >= num4)
         {
             localAI[1] = 1f;
             Kill();
             return;
         }
         Player player = Main.player[owner];
         float fromValue = localAI[0] / ai[1];
         float num6 = Utils.Remap(localAI[0], ai[1] * 0.4f, num4, 0f, 1f);
         direction = (spriteDirection = (int)ai[0]);
         if (type == 973)
         {
             int num7 = 3;
             if (damage != 0 && localAI[0] >= num5 + (float)num7)
             {
                 damage = 0;
             }
             if (damage != 0)
             {
                 int num8 = 80;
                 bool flag = false;
                 float num9 = velocity.ToRotation();
                 for (float num10 = -1f; num10 <= 1f; num10 += 0.5f)
                 {
                     Vector2 position = base.Center + (num9 + num10 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num8 * 0.5f * scale;
                     Vector2 position2 = base.Center + (num9 + num10 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num8 * scale;
                     if (!Collision.SolidTiles(base.Center, 0, 0) && Collision.CanHit(position, 0, 0, position2, 0, 0))
                     {
                         flag = true;
                         break;
                     }
                 }
                 if (!flag)
                 {
                     damage = 0;
                 }
             }
             fromValue = localAI[0] / ai[1];
             localAI[1] += 1f;
             num6 = Utils.Remap(localAI[1], ai[1] * 0.4f, num4, 0f, 1f);
             base.Center = player.RotatedRelativePoint(player.MountedCenter) - velocity + velocity * num6 * num6 * num5;
             rotation += ai[0] * ((float)Math.PI * 2f) * (4f + Opacity * 4f) / 90f;
             scale = Utils.Remap(localAI[0], ai[1] + 2f, num4, 1.12f, 1f) * ai[2];
             float f = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
             Vector2 vector = base.Center + f.ToRotationVector2() * 84f * scale;
             if (Main.rand.Next(5) == 0)
             {
                 Dust dust = Dust.NewDustPerfect(vector, 14, null, 150, default(Color), 1.4f);
                 dust.noLight = (dust.noLightEmittence = true);
             }
             for (int i = 0; (float)i < 3f * Opacity; i++)
             {
                 Vector2 vector2 = velocity.SafeNormalize(Vector2.UnitX);
                 int num11 = ((Main.rand.NextFloat() < Opacity) ? 75 : 27);
                 Dust dust2 = Dust.NewDustPerfect(vector, num11, velocity * 0.2f + vector2 * 3f, 100, default(Color), 1.4f);
                 dust2.noGravity = true;
                 dust2.customData = Opacity * 0.2f;
             }
         }
         if (type != 985)
         {
             return;
         }
         ownerHitCheck = localAI[0] <= 6f;
         if (localAI[0] >= MathHelper.Lerp(num3, num4, 0.65f))
         {
             damage = 0;
         }
         float fromValue2 = 1f - (1f - num6) * (1f - num6);
         rotation = velocity.ToRotation();
         scale = Utils.Remap(fromValue2, 0f, 1f, 1.5f, 1f) * ai[2];
         num6 = Utils.Remap(localAI[0], ai[1] / 2f, num4, 0f, 1f);
         Opacity = Utils.Remap(localAI[0], 0f, ai[1] * 0.5f, 0f, 1f) * Utils.Remap(localAI[0], num4 - 12f, num4, 1f, 0f);
         if (velocity.Length() > 8f)
         {
             velocity *= 0.94f;
             new Vector2(32f, 32f);
             float num12 = Utils.Remap(fromValue, 0.7f, 1f, 110f, 110f);
             if (localAI[1] == 0f)
             {
                 bool flag2 = false;
                 for (float num13 = -1f; num13 <= 1f; num13 += 0.5f)
                 {
                     Vector2 position3 = base.Center + (rotation + num13 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num12 * 0.5f * scale;
                     Vector2 position4 = base.Center + (rotation + num13 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num12 * scale;
                     if (Collision.CanHit(position3, 0, 0, position4, 0, 0))
                     {
                         flag2 = true;
                         break;
                     }
                 }
                 if (!flag2)
                 {
                     localAI[1] = 1f;
                 }
             }
             if (localAI[1] == 1f && velocity.Length() > 8f)
             {
                 velocity *= 0.8f;
             }
             if (localAI[1] == 1f)
             {
                 velocity *= 0.88f;
             }
         }
         float num14 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.9f;
         Vector2 vector3 = base.Center + num14.ToRotationVector2() * 85f * scale;
         (num14 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
         Color value = new Color(64, 220, 96);
         Color value2 = new Color(15, 84, 125);
         Lighting.AddLight(base.Center + rotation.ToRotationVector2() * 85f * scale, value.ToVector3());
         for (int j = 0; j < 3; j++)
         {
             if (Main.rand.NextFloat() < Opacity + 0.1f)
             {
                 Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(fromValue, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(fromValue, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                 Dust dust3 = Dust.NewDustPerfect(vector3, 107, velocity * 0.7f, 100, default(Color) * Opacity, 0.8f * Opacity);
                 dust3.scale *= 0.7f;
                 dust3.velocity += player.velocity * 0.1f;
                 dust3.position -= dust3.velocity * 6f;
             }
         }
         if (damage == 0)
         {
             localAI[0] += 3f;
             velocity *= 0.76f;
         }
         if (localAI[0] < 10f && (localAI[1] == 1f || damage == 0))
         {
             localAI[0] += 1f;
             velocity *= 0.85f;
             for (int k = 0; k < 4; k++)
             {
                 float num15 = Main.rand.NextFloatDirection();
                 float num16 = 1f - Math.Abs(num15);
                 num14 = rotation + num15 * ((float)Math.PI / 2f) * 0.9f;
                 vector3 = base.Center + num14.ToRotationVector2() * 85f * scale;
                 Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(fromValue, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(fromValue, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                 Dust dust4 = Dust.NewDustPerfect(vector3, 107, velocity.RotatedBy(num15 * ((float)Math.PI / 4f)) * 0.2f * Main.rand.NextFloat(), 100, default(Color), 1.4f * num16);
                 dust4.velocity += player.velocity * 0.1f;
                 dust4.position -= dust4.velocity * Main.rand.NextFloat() * 3f;
             }
         }
     }
References Lighting.AddLight(), Collision.CanHit(), Color, Dust.customData, SoundID.Item8, Player.MountedCenter, Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.player, SoundEngine.PlaySound(), Dust.position, Main.rand, Utils.Remap(), Player.RotatedRelativePoint(), Dust.scale, Collision.SolidTiles(), Dust.velocity, and Entity.velocity.