Terraria: Projectile.Update
Update()
void Projectile.Update (int i) inline
     {
         if (!active)
         {
             return;
         }
         if (Main.netMode == 1 && (ProjectileID.Sets.IsAGolfBall[type] || type == 820))
         {
             int num = (int)(position.X + (float)(width / 2)) / 16;
             int num2 = (int)(position.Y + (float)(height / 2)) / 16;
             if (Main.tile[num, num2] == null)
             {
                 return;
             }
         }
         numUpdates = extraUpdates;
         while (numUpdates >= 0)
         {
             numUpdates--;
             if (type == 640 && ai[1] > 0f)
             {
                 ai[1] -= 1f;
                 continue;
             }
             if (position.X <= Main.leftWorld || position.X + (float)width >= Main.rightWorld || position.Y <= Main.topWorld || position.Y + (float)height >= Main.bottomWorld)
             {
                 active = false;
                 return;
             }
             if (!noEnchantmentVisuals)
             {
                 UpdateEnchantmentVisuals();
             }
             if (numUpdates == -1 && (minion || sentry))
             {
                 Player player = Main.player[owner];
                 damage = (int)((float)originalDamage * player.minionDamage + 5E-06f);
             }
             if (minion && numUpdates == -1 && type != 625 && type != 628)
             {
                 minionPos = Main.player[owner].numMinions;
                 if (Main.player[owner].slotsMinions + minionSlots > (float)Main.player[owner].maxMinions && owner == Main.myPlayer)
                 {
                     if ((type == 627 || type == 626) && owner == Main.myPlayer)
                     {
                         int byUUID = GetByUUID(owner, ai[0]);
                         if (byUUID != -1)
{
                             Projectile projectile = Main.projectile[byUUID];
                             if (projectile.type != 625)
{
                                 projectile.localAI[1] = localAI[1];
                             }
                             projectile = Main.projectile[(int)localAI[1]];
                             projectile.ai[0] = ai[0];
                             projectile.ai[1] = 1f;
                             projectile.netUpdate = true;
                         }
                     }
                     Kill();
                 }
                 else
                 {
                     Main.player[owner].numMinions++;
                     Main.player[owner].slotsMinions += minionSlots;
                 }
             }
             float num3 = 1f + Math.Abs(velocity.X) / 3f;
             if (gfxOffY > 0f)
             {
                 gfxOffY -= num3 * stepSpeed;
                 if (gfxOffY < 0f)
                 {
                     gfxOffY = 0f;
                 }
             }
             else if (gfxOffY < 0f)
             {
                 gfxOffY += num3 * stepSpeed;
                 if (gfxOffY > 0f)
                 {
                     gfxOffY = 0f;
                 }
             }
             if (gfxOffY > 16f)
             {
                 gfxOffY = 16f;
             }
             if (gfxOffY < -16f)
             {
                 gfxOffY = -16f;
             }
             Vector2 wetVelocity = velocity;
             oldVelocity = velocity;
             whoAmI = i;
             if (soundDelay > 0)
             {
                 soundDelay--;
             }
             netUpdate = false;
             for (int j = 0; j < 255; j++)
             {
                 if (playerImmune[j] > 0)
                 {
                     playerImmune[j]--;
                 }
             }
             if (usesLocalNPCImmunity)
             {
                 for (int k = 0; k < 200; k++)
                 {
                     if (localNPCImmunity[k] > 0)
                     {
                         localNPCImmunity[k]--;
                     }
                 }
             }
             AI();
             if (ShouldUseWindPhysics() && (double)base.Center.Y < Main.worldSurface * 16.0 && Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16] != null && Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16].wall == 0 && ((velocity.X > 0f && Main.windSpeedCurrent < 0f) || (velocity.X < 0f && Main.windSpeedCurrent > 0f) || Math.Abs(velocity.X) < Math.Abs(Main.windSpeedCurrent * Main.windPhysicsStrength) * 180f) && Math.Abs(velocity.X) < 16f)
             {
                 velocity.X += Main.windSpeedCurrent * Main.windPhysicsStrength;
                 MathHelper.Clamp(velocity.X, -16f, 16f);
             }
             if (owner < 255 && !Main.player[owner].active)
             {
                 Kill();
             }
             if (type == 242 || type == 302 || type == 638)
             {
                 wet = false;
             }
             if (!ignoreWater)
             {
                 bool flag;
                 bool flag2;
                 try
                 {
                     flag = Collision.LavaCollision(position, width, height);
                     flag2 = Collision.WetCollision(position, width, height);
                     if (flag)
                     {
                         lavaWet = true;
                     }
                     if (Collision.honey)
                     {
                         honeyWet = true;
                     }
                     if (Collision.shimmer)
                     {
                         shimmerWet = true;
                     }
                 }
                 catch
                 {
                     active = false;
                     return;
                 }
                 if (wet && !lavaWet)
                 {
                     if (type == 85 || type == 15 || type == 188)
                     {
                         Kill();
                     }
                     if (type == 2)
                     {
                         type = 1;
                         light = 0f;
                     }
                 }
                 if (type == 34)
                 {
                     if (wet && !lavaWet)
                     {
                         Kill();
                     }
                     if (lavaWet)
                     {
                         flag2 = (wet = (lavaWet = false));
                     }
                 }
                 if (type == 80)
                 {
                     flag2 = false;
                     wet = false;
                     if (flag && ai[0] >= 0f)
                     {
                         Kill();
                     }
                 }
                 if (flag2)
                 {
                     if (type != 155 && wetCount == 0 && !wet)
                     {
                         if (!flag)
{
                             if (shimmerWet)
{
                                 for (int l = 0; l < 10; l++)
{
                                     int num4 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                     Main.dust[num4].velocity.Y -= 4f;
                                     Main.dust[num4].velocity.X *= 2.5f;
                                     Main.dust[num4].scale = 1.3f;
                                     Main.dust[num4].noGravity = true;
                                     switch (Main.rand.Next(6))
{
                                     case 0:
                                         Main.dust[num4].color = new Color(255, 255, 210);
                                         break;
                                     case 1:
                                         Main.dust[num4].color = new Color(190, 245, 255);
                                         break;
                                     case 2:
                                         Main.dust[num4].color = new Color(255, 150, 255);
                                         break;
                                     default:
                                         Main.dust[num4].color = new Color(190, 175, 255);
                                         break;
                                     }
                                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 4);
                                 }
                             }
                             else if (honeyWet)
{
                                 for (int m = 0; m < 10; m++)
{
                                     int num5 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                     Main.dust[num5].velocity.Y -= 1f;
                                     Main.dust[num5].velocity.X *= 2.5f;
                                     Main.dust[num5].scale = 1.3f;
                                     Main.dust[num5].alpha = 100;
                                     Main.dust[num5].noGravity = true;
                                 }
                                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                             }
                             else
{
                                 for (int n = 0; n < 10; n++)
{
                                     int num6 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                                     Main.dust[num6].velocity.Y -= 4f;
                                     Main.dust[num6].velocity.X *= 2.5f;
                                     Main.dust[num6].scale = 1.3f;
                                     Main.dust[num6].alpha = 100;
                                     Main.dust[num6].noGravity = true;
                                 }
                                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                             }
                         }
                         else
{
                             for (int num7 = 0; num7 < 10; num7++)
{
                                 int num8 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                 Main.dust[num8].velocity.Y -= 1.5f;
                                 Main.dust[num8].velocity.X *= 2.5f;
                                 Main.dust[num8].scale = 1.3f;
                                 Main.dust[num8].alpha = 100;
                                 Main.dust[num8].noGravity = true;
                             }
                             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                         }
                     }
                     wet = true;
                 }
                 else if (wet)
                 {
                     wet = false;
                     if (type == 155)
                     {
                         velocity.Y *= 0.5f;
                     }
                     else if (wetCount == 0)
                     {
                         wetCount = 10;
                         if (!lavaWet)
{
                             if (shimmerWet)
{
                                 for (int num9 = 0; num9 < 10; num9++)
{
                                     int num10 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                     Main.dust[num10].velocity.Y -= 4f;
                                     Main.dust[num10].velocity.X *= 2.5f;
                                     Main.dust[num10].scale = 1.3f;
                                     Main.dust[num10].noGravity = true;
                                     switch (Main.rand.Next(6))
{
                                     case 0:
                                         Main.dust[num10].color = new Color(255, 255, 210);
                                         break;
                                     case 1:
                                         Main.dust[num10].color = new Color(190, 245, 255);
                                         break;
                                     case 2:
                                         Main.dust[num10].color = new Color(255, 150, 255);
                                         break;
                                     default:
                                         Main.dust[num10].color = new Color(190, 175, 255);
                                         break;
                                     }
                                     SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 5);
                                 }
                             }
                             else if (honeyWet)
{
                                 for (int num11 = 0; num11 < 10; num11++)
{
                                     int num12 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                     Main.dust[num12].velocity.Y -= 1f;
                                     Main.dust[num12].velocity.X *= 2.5f;
                                     Main.dust[num12].scale = 1.3f;
                                     Main.dust[num12].alpha = 100;
                                     Main.dust[num12].noGravity = true;
                                 }
                                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                             }
                             else
{
                                 for (int num13 = 0; num13 < 10; num13++)
{
                                     int num14 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, Dust.dustWater());
                                     Main.dust[num14].velocity.Y -= 4f;
                                     Main.dust[num14].velocity.X *= 2.5f;
                                     Main.dust[num14].scale = 1.3f;
                                     Main.dust[num14].alpha = 100;
                                     Main.dust[num14].noGravity = true;
                                 }
                                 SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                             }
                         }
                         else
{
                             for (int num15 = 0; num15 < 10; num15++)
{
                                 int num16 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                 Main.dust[num16].velocity.Y -= 1.5f;
                                 Main.dust[num16].velocity.X *= 2.5f;
                                 Main.dust[num16].scale = 1.3f;
                                 Main.dust[num16].alpha = 100;
                                 Main.dust[num16].noGravity = true;
                             }
                             SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                         }
                     }
                 }
                 if (!wet)
                 {
                     lavaWet = false;
                     honeyWet = false;
                     shimmerWet = false;
                 }
                 if (wetCount > 0)
                 {
                     wetCount--;
                 }
             }
             if (shimmerWet)
             {
                 Shimmer();
             }
             oldPosition = position;
             oldDirection = direction;
             HandleMovement(wetVelocity, out var _, out var _);
             if (AutomaticallyChangesDirection())
             {
                 if (velocity.X < 0f)
                 {
                     direction = -1;
                 }
                 else
                 {
                     direction = 1;
                 }
             }
             if (!active)
             {
                 return;
             }
             ProjLight();
             if (!npcProj && friendly && Main.player[owner].magicQuiver && extraUpdates < 1 && arrow)
             {
                 extraUpdates = 1;
             }
             if (type == 2 || type == 82)
             {
                 Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100);
             }
             else if (type == 172)
             {
                 Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, 0f, 0f, 100);
             }
             else if (type == 103)
             {
                 int num17 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 75, 0f, 0f, 100);
                 if (Main.rand.Next(2) == 0)
                 {
                     Main.dust[num17].noGravity = true;
                     Main.dust[num17].scale *= 2f;
                 }
             }
             else if (type == 278)
             {
                 int num18 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 169, 0f, 0f, 100);
                 if (Main.rand.Next(2) == 0)
                 {
                     Main.dust[num18].noGravity = true;
                     Main.dust[num18].scale *= 1.5f;
                 }
             }
             else if (type == 4)
             {
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 150, default(Color), 1.1f);
                 }
             }
             else if (type == 5)
             {
                 int num19 = Main.rand.Next(3);
                 Dust.NewDust(position, width, height, num19 switch
                 {
                     0 => 15,
                     1 => 57,
                     _ => 58,
                 }, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 1.2f);
             }
             Damage();
             if (type == 434 && localAI[0] == 0f && numUpdates == 0)
             {
                 extraUpdates = 1;
                 velocity = Vector2.Zero;
                 localAI[0] = 1f;
                 localAI[1] = 0.9999f;
                 netUpdate = true;
             }
             if (Main.netMode != 1 && (type == 99 || type == 1013 || type == 655 || type == 727 || type == 1014 || type == 1021))
             {
                 Collision.SwitchTiles(position, width, height, oldPosition, 3);
             }
             if (ProjectileID.Sets.TrailingMode[type] == 0)
             {
                 for (int num20 = oldPos.Length - 1; num20 > 0; num20--)
                 {
                     oldPos[num20] = oldPos[num20 - 1];
                 }
                 oldPos[0] = position;
             }
             else if (ProjectileID.Sets.TrailingMode[type] == 1)
             {
                 if (frameCounter == 0 || oldPos[0] == Vector2.Zero)
                 {
                     for (int num21 = oldPos.Length - 1; num21 > 0; num21--)
                     {
                         oldPos[num21] = oldPos[num21 - 1];
                     }
                     oldPos[0] = position;
                     if (velocity == Vector2.Zero && type == 466)
                     {
                         float num22 = rotation + (float)Math.PI / 2f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                         float num23 = (float)Main.rand.NextDouble() * 2f + 2f;
                         Vector2 vector = new Vector2((float)Math.Cos(num22) * num23, (float)Math.Sin(num22) * num23);
                         int num24 = Dust.NewDust(oldPos[oldPos.Length - 1], 0, 0, 229, vector.X, vector.Y);
                         Main.dust[num24].noGravity = true;
                         Main.dust[num24].scale = 1.7f;
                     }
                     if (velocity == Vector2.Zero && type == 580)
                     {
                         float num25 = rotation + (float)Math.PI / 2f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                         float num26 = (float)Main.rand.NextDouble() * 2f + 2f;
                         Vector2 vector2 = new Vector2((float)Math.Cos(num25) * num26, (float)Math.Sin(num25) * num26);
                         int num27 = Dust.NewDust(oldPos[oldPos.Length - 1], 0, 0, 229, vector2.X, vector2.Y);
                         Main.dust[num27].noGravity = true;
                         Main.dust[num27].scale = 1.7f;
                     }
                 }
             }
             else if (ProjectileID.Sets.TrailingMode[type] == 2)
             {
                 for (int num28 = oldPos.Length - 1; num28 > 0; num28--)
                 {
                     oldPos[num28] = oldPos[num28 - 1];
                     oldRot[num28] = oldRot[num28 - 1];
                     oldSpriteDirection[num28] = oldSpriteDirection[num28 - 1];
                 }
                 oldPos[0] = position;
                 oldRot[0] = rotation;
                 oldSpriteDirection[0] = spriteDirection;
             }
             else if (ProjectileID.Sets.TrailingMode[type] == 3)
             {
                 for (int num29 = oldPos.Length - 1; num29 > 0; num29--)
                 {
                     oldPos[num29] = oldPos[num29 - 1];
                     oldRot[num29] = oldRot[num29 - 1];
                     oldSpriteDirection[num29] = oldSpriteDirection[num29 - 1];
                 }
                 oldPos[0] = position;
                 oldRot[0] = rotation;
                 oldSpriteDirection[0] = spriteDirection;
                 float amount = 0.65f;
                 int num30 = 1;
                 for (int num31 = 0; num31 < num30; num31++)
                 {
                     for (int num32 = oldPos.Length - 1; num32 > 0; num32--)
                     {
                         if (!(oldPos[num32] == Vector2.Zero))
{
                             if (oldPos[num32].Distance(oldPos[num32 - 1]) > 2f)
{
                                 oldPos[num32] = Vector2.Lerp(oldPos[num32], oldPos[num32 - 1], amount);
                             }
                             oldRot[num32] = (oldPos[num32 - 1] - oldPos[num32]).SafeNormalize(Vector2.Zero).ToRotation();
                         }
                     }
                 }
             }
             else if (ProjectileID.Sets.TrailingMode[type] == 4)
             {
                 Vector2 vector3 = Main.player[owner].position - Main.player[owner].oldPosition;
                 for (int num33 = oldPos.Length - 1; num33 > 0; num33--)
                 {
                     oldPos[num33] = oldPos[num33 - 1];
                     oldRot[num33] = oldRot[num33 - 1];
                     oldSpriteDirection[num33] = oldSpriteDirection[num33 - 1];
                     if (numUpdates == 0 && oldPos[num33] != Vector2.Zero)
                     {
                         oldPos[num33] += vector3;
                     }
                 }
                 oldPos[0] = position;
                 oldRot[0] = rotation;
                 oldSpriteDirection[0] = spriteDirection;
             }
             else if (ProjectileID.Sets.TrailingMode[type] == 5)
             {
                 for (int num34 = oldPos.Length - 1; num34 > 0; num34--)
                 {
                     oldPos[num34] = oldPos[num34 - 1];
                     oldRot[num34] = oldRot[num34 - 1];
                     oldSpriteDirection[num34] = oldSpriteDirection[num34 - 1];
                 }
                 oldPos[0] = position;
                 oldRot[0] = velocity.ToRotation();
                 oldSpriteDirection[0] = spriteDirection;
             }
             if (ProjectileID.Sets.IsADD2Turret[type] && DD2Event.Ongoing)
             {
                 timeLeft++;
             }
             timeLeft--;
             if (timeLeft <= 0)
             {
                 Kill();
             }
             if (penetrate == 0)
             {
                 Kill();
             }
             if (!active || owner != Main.myPlayer)
             {
                 continue;
             }
             if (netUpdate2)
             {
                 netUpdate = true;
             }
             if (!active)
             {
                 netSpam = 0;
             }
             if (netUpdate)
             {
                 if (netSpam < 60)
                 {
                     netSpam += 5;
                     NetMessage.SendData(27, -1, -1, null, i);
                     netUpdate2 = false;
                 }
                 else
                 {
                     netUpdate2 = true;
                 }
             }
             if (netSpam > 0)
             {
                 netSpam--;
             }
         }
         netUpdate = false;
     }
References Entity.active, ai, AI(), Dust.alpha, arrow, AutomaticallyChangesDirection(), Main.bottomWorld, Color, Dust.color, damage, Damage(), Entity.direction, Entity.Distance(), Main.dust, Dust.dustWater(), E, extraUpdates, frameCounter, friendly, GetByUUID(), gfxOffY, HandleMovement(), Entity.height, Collision.honey, Entity.honeyWet, ignoreWater, ProjectileID.Sets.IsADD2Turret, ProjectileID.Sets.IsAGolfBall, Kill(), Collision.LavaCollision(), Entity.lavaWet, Main.leftWorld, light, localAI, localNPCImmunity, Player.magicQuiver, Player.maxMinions, minion, Player.minionDamage, minionPos, minionSlots, Main.myPlayer, Main.netMode, netSpam, netUpdate, netUpdate2, Dust.NewDust(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), noEnchantmentVisuals, Dust.noGravity, npcProj, Player.numMinions, numUpdates, Entity.oldDirection, oldPos, Entity.oldPosition, oldRot, oldSpriteDirection, Entity.oldVelocity, DD2Event.Ongoing, originalDamage, owner, penetrate, Main.player, playerImmune, SoundEngine.PlaySound(), Entity.position, Main.projectile, ProjLight(), Main.rand, Main.rightWorld, rotation, Dust.scale, NetMessage.SendData(), sentry, Collision.shimmer, Shimmer(), Entity.shimmerWet, ShouldUseWindPhysics(), Player.slotsMinions, soundDelay, spriteDirection, stepSpeed, Collision.SwitchTiles(), Main.tile, timeLeft, Main.topWorld, ProjectileID.Sets.TrailingMode, type, UpdateEnchantmentVisuals(), usesLocalNPCImmunity, Dust.velocity, Entity.velocity, Tile.wall, Entity.wet, Collision.WetCollision(), Entity.wetCount, Entity.whoAmI, Entity.width, Main.windPhysicsStrength, Main.windSpeedCurrent, and Main.worldSurface.
Referenced by Main.DoUpdateInWorld(), and Main.DrawWallOfStars().