Terraria: System.Reflection.RuntimeMethodInfo.MakeGenericMethod
MakeGenericMethod()
override MethodInfo System.Reflection.RuntimeMethodInfo.MakeGenericMethod (params Type[] methodInstantiation) inline virtual
Reimplemented from System.Reflection.MethodInfo.
Definition at line 551 of file RuntimeMethodInfo.cs.
    {
        if (methodInstantiation == null)
        {
            throw new ArgumentNullException("methodInstantiation");
        }
        RuntimeType[] array = new RuntimeType[methodInstantiation.Length];
        if (!IsGenericMethodDefinition)
        {
            throw new InvalidOperationException(SR.Format(SR.Arg_NotGenericMethodDefinition, this));
        }
        for (int i = 0; i < methodInstantiation.Length; i++)
        {
            Type type = methodInstantiation[i];
            if (type == null)
            {
                throw new ArgumentNullException();
            }
            RuntimeType runtimeType = type as RuntimeType;
            if (runtimeType == null)
            {
                Type[] array2 = new Type[methodInstantiation.Length];
                for (int j = 0; j < methodInstantiation.Length; j++)
                {
                    array2[j] = methodInstantiation[j];
                }
                methodInstantiation = array2;
                return MethodBuilderInstantiation.MakeGenericMethod(this, methodInstantiation);
            }
            array[i] = runtimeType;
        }
        RuntimeType[] genericArgumentsInternal = GetGenericArgumentsInternal();
        RuntimeType.SanityCheckGenericArguments(array, genericArgumentsInternal);
        MethodInfo methodInfo = null;
        try
        {
            return RuntimeType.GetMethodBase(ReflectedTypeInternal, RuntimeMethodHandle.GetStubIfNeeded(new RuntimeMethodHandleInternal(m_handle), m_declaringType, array)) as MethodInfo;
        }
        catch (VerificationException e)
        {
            RuntimeType.ValidateGenericArguments(this, array, e);
            throw;
        }
    }
References System.SR.Arg_NotGenericMethodDefinition, System.array, System.SR.Format(), System.Reflection.RuntimeMethodInfo.GetGenericArgumentsInternal(), System.RuntimeType.GetMethodBase(), System.RuntimeMethodHandle.GetStubIfNeeded(), System.Reflection.RuntimeMethodInfo.IsGenericMethodDefinition, System.Reflection.RuntimeMethodInfo.m_declaringType, System.Reflection.RuntimeMethodInfo.m_handle, System.Reflection.Emit.MethodBuilderInstantiation.MakeGenericMethod(), System.Reflection.RuntimeMethodInfo.ReflectedTypeInternal, System.RuntimeType.SanityCheckGenericArguments(), System.type, and System.RuntimeType.ValidateGenericArguments().