Terraria: Projectile.AI_130_FlameBurstTower
AI_130_FlameBurstTower()
void Projectile.AI_130_FlameBurstTower () inline private
     {
         float num = 900f;
         float angleRatioMax = 1f;
         Vector2 vector = base.Center;
         int num2 = 664;
         int num3 = 12;
         float num4 = 12f;
         int num5 = 1;
         int num6 = 6;
         int num7 = 4;
         int num8 = 80;
         switch (type)
         {
         case 663:
         {
             Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f));
             Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f));
             vector = base.Bottom + new Vector2(direction * 6, -40f);
             if ((localAI[0] += 1f) >= 300f)
             {
                 localAI[0] = 0f;
             }
             Rectangle r3 = new Rectangle((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 3, 6);
             if (direction == 1)
             {
                 r3.X -= width / 4;
             }
             for (int m = 0; m < 1; m++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Dust dust5 = Dust.NewDustDirect(r3.TopLeft() + new Vector2(-2f, -2f), r3.Width + 4, r3.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                     dust5.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                     dust5.scale = 0.4f;
                     dust5.noGravity = true;
                     dust5.noLight = true;
                     dust5.velocity = Vector2.Zero;
                     dust5.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust5.fadeIn;
                 }
             }
             r3 = new Rectangle((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
             if (direction == -1)
             {
                 r3.X -= r3.Width;
             }
             r3.X += direction * 4;
             r3.Y -= height - 10;
             for (int n = 0; n < 1; n++)
             {
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust dust6 = Dust.NewDustDirect(r3.TopLeft(), r3.Width, r3.Height, 6);
                     dust6.fadeIn = 1f;
                     dust6.scale = 1f;
                     dust6.noGravity = true;
                     dust6.noLight = true;
                     dust6.velocity *= 2f;
                 }
             }
             break;
         }
         case 665:
         {
             Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f) * 1.2f);
             Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f) * 1.2f);
             num8 = 70;
             num4 += 3f;
             num6 = 8;
             num2 = 666;
             vector = base.Bottom + new Vector2(direction * 6, -44f);
             if ((localAI[0] += 1f) >= 300f)
             {
                 localAI[0] = 0f;
             }
             Rectangle r2 = new Rectangle((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 2, 6);
             if (direction == 1)
             {
                 r2.X -= width / 4;
             }
             for (int k = 0; k < 1; k++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Dust dust3 = Dust.NewDustDirect(r2.TopLeft() + new Vector2(-2f, -2f), r2.Width + 4, r2.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                     dust3.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                     dust3.scale = 0.4f;
                     dust3.noGravity = true;
                     dust3.noLight = true;
                     dust3.velocity = Vector2.Zero;
                     dust3.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust3.fadeIn;
                 }
             }
             r2 = new Rectangle((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
             if (direction == -1)
             {
                 r2.X -= r2.Width;
             }
             r2.X += direction * 4;
             r2.Y -= height - 10;
             for (int l = 0; l < 2; l++)
             {
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust dust4 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, 6);
                     dust4.fadeIn = 1f;
                     dust4.scale = 1f;
                     dust4.noGravity = true;
                     dust4.noLight = true;
                     dust4.velocity *= 2f;
                 }
             }
             break;
         }
         case 667:
         {
             Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f) * 1.5f);
             Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f) * 1.5f);
             num8 = 60;
             num4 += 6f;
             num6 = 8;
             num2 = 668;
             vector = base.Bottom + new Vector2(direction * 6, -46f);
             if ((localAI[0] += 1f) >= 300f)
             {
                 localAI[0] = 0f;
             }
             Rectangle r = new Rectangle((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 2, 6);
             if (direction == 1)
             {
                 r.X -= width / 4;
             }
             for (int i = 0; i < 1; i++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Dust dust = Dust.NewDustDirect(r.TopLeft() + new Vector2(-2f, -2f), r.Width + 4, r.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                     dust.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                     dust.scale = 0.4f;
                     dust.noGravity = true;
                     dust.noLight = true;
                     dust.velocity = Vector2.Zero;
                     dust.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust.fadeIn;
                 }
             }
             r = new Rectangle((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
             if (direction == -1)
             {
                 r.X -= r.Width;
             }
             r.X += direction * 4;
             r.Y -= height - 10;
             for (int j = 0; j < 3; j++)
             {
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust dust2 = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 6);
                     dust2.fadeIn = 1.1f;
                     dust2.scale = 1f;
                     dust2.noGravity = true;
                     dust2.noLight = true;
                     dust2.velocity *= 2.4f;
                 }
             }
             break;
         }
         }
         if (Main.player[owner].setApprenticeT2)
         {
             angleRatioMax = 0.1f;
             num *= 1.5f;
             num4 *= 1.4f;
         }
         if (ai[0] == 0f)
         {
             direction = (spriteDirection = Main.player[owner].direction);
             ai[0] = 1f;
             ai[1] = 0f;
             netUpdate = true;
         }
         if (ai[0] == 1f)
         {
             frame = 0;
             bool flag = false;
             if (ai[1] > 0f)
             {
                 ai[1] -= 1f;
             }
             else
             {
                 flag = true;
             }
             if (flag && owner == Main.myPlayer)
             {
                 int num9 = AI_130_FlameBurstTower_FindTarget(num, angleRatioMax, vector);
                 if (num9 != -1)
                 {
                     direction = Math.Sign(DirectionTo(Main.npc[num9].Center).X);
                     ai[0] = 2f;
                     ai[1] = 0f;
                     netUpdate = true;
                 }
             }
         }
         else if (ai[0] == 2f)
         {
             frame = num5 + (int)(ai[1] / (float)num7);
             if (ai[1] == (float)num3)
             {
                 Vector2 vector2 = new Vector2(direction, 0f);
                 int num10 = AI_130_FlameBurstTower_FindTarget(num, angleRatioMax, vector, canChangeDirection: false);
                 if (num10 != -1)
                 {
                     vector2 = (Main.npc[num10].Center - vector).SafeNormalize(Vector2.UnitX * direction);
                 }
                 Vector2 vector3 = vector2 * num4;
                 if (owner == Main.myPlayer)
                 {
                     NewProjectile(GetProjectileSource_FromThis(), vector, vector3, num2, damage, knockBack, owner);
                 }
             }
             if ((ai[1] += 1f) >= (float)(num6 * num7))
             {
                 ai[0] = 1f;
                 ai[1] = num8;
             }
         }
         spriteDirection = direction;
         tileCollide = true;
         velocity.Y += 0.2f;
     }
References Lighting.AddLight(), Entity.Center, Color, Entity.direction, Dust.fadeIn, Main.myPlayer, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.npc, Main.player, Main.rand, Dust.scale, Player.setApprenticeT2, and Dust.velocity.