Terraria: Projectile.Shimmer
Shimmer()
void Projectile.Shimmer () inline private
     {
         if (hostile || (aiStyle == 99 && ai[0] == -1f) || (aiStyle == 15 && (ai[0] == 2f || ai[0] == 4f)))
         {
             return;
         }
         if (type == 502)
         {
             velocity.Y -= 0.4f;
             timeLeft -= 5;
         }
         else if (type == 469 || type == 181)
         {
             velocity.Y -= 0.2f;
             if (type == 469 && velocity.Y < 0f)
             {
                 Kill();
             }
         }
         else if (type == 819 || type == 117 || type == 474 || type == 225 || type == 103 || type == 2 || type == 82 || type == 120 || type == 172 || type == 41 || type == 91 || type == 278 || type == 5 || type == 639 || type == 631 || type == 495 || type == 4 || type == 282 || type == 1 || type == 81)
         {
             velocity.Y -= 0.4f;
         }
         else if (aiStyle == 1 || aiStyle == 16 || aiStyle == 40)
         {
             int num = (int)(base.Center.X / 16f);
             int num2 = (int)(position.Y / 16f);
             if (WorldGen.InWorld(num, num2) && Main.tile[num, num2] != null && Main.tile[num, num2].liquid == byte.MaxValue && Main.tile[num, num2].shimmer() && WorldGen.InWorld(num, num2 - 1) && Main.tile[num, num2 - 1] != null && Main.tile[num, num2 - 1].liquid > 0 && Main.tile[num, num2 - 1].shimmer())
             {
                 Kill();
             }
             else if (velocity.Y > 0f)
             {
                 velocity.Y *= -1f;
                 netUpdate = true;
                 if (timeLeft > 600)
                 {
                     timeLeft = 600;
                 }
                 timeLeft -= 60;
                 shimmerWet = false;
                 wet = false;
             }
         }
         else if (aiStyle == 5 || aiStyle == 8 || aiStyle == 21 || aiStyle == 28 || aiStyle == 29 || aiStyle == 33 || aiStyle == 36 || aiStyle == 47 || aiStyle == 93 || aiStyle == 115 || aiStyle == 151 || aiStyle == 152)
         {
             int num3 = (int)(base.Center.X / 16f);
             int num4 = (int)(position.Y / 16f);
             if (WorldGen.InWorld(num3, num4) && Main.tile[num3, num4] != null && Main.tile[num3, num4].liquid == byte.MaxValue && Main.tile[num3, num4].shimmer() && WorldGen.InWorld(num3, num4 - 1) && Main.tile[num3, num4 - 1] != null && Main.tile[num3, num4 - 1].liquid > 0 && Main.tile[num3, num4 - 1].shimmer())
             {
                 Kill();
             }
             else if (velocity.Y > 0f)
             {
                 velocity.Y *= -1f;
                 netUpdate = true;
                 shimmerWet = false;
                 wet = false;
             }
         }
         else if (aiStyle == 15)
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y *= -1f;
                 netUpdate = true;
             }
             velocity.Y -= 0.4f;
             if (velocity.Y < -8f)
             {
                 velocity.Y = -8f;
             }
         }
         else if (aiStyle == 99)
         {
             if (velocity.Y > 0f)
             {
                 velocity.Y *= -1f;
                 netUpdate = true;
                 shimmerWet = false;
                 wet = false;
             }
             if (velocity.Y > -8f)
             {
                 velocity.Y = -8f;
             }
         }
         else if (aiStyle == 7 || aiStyle == 9 || aiStyle == 13 || aiStyle == 35 || aiStyle == 53 || aiStyle == 130 || aiStyle == 134 || aiStyle == 137 || aiStyle == 138 || aiStyle == 149 || aiStyle == 160)
         {
             Kill();
         }
         else if (aiStyle == 2)
         {
             velocity.Y -= 0.7f;
             if (type == 936 && !NPC.unlockedSlimeRainbowSpawn && velocity.Y < 0f)
             {
                 if (timeLeft > 5)
                 {
                     timeLeft = 5;
                 }
                 if (Main.netMode != 1)
                 {
                     NPC.unlockedSlimeRainbowSpawn = true;
                     NetMessage.SendData(7);
                     int num5 = NPC.NewNPC(GetNPCSource_FromThis(), (int)base.Center.X + 4, (int)base.Center.Y, 681);
                     NPC obj = Main.npc[num5];
                     obj.velocity = velocity;
                     obj.netUpdate = true;
                     WorldGen.CheckAchievement_RealEstateAndTownSlimes();
                 }
             }
             else
             {
                 timeLeft -= 20;
             }
         }
         else if (aiStyle == 14 || aiStyle == 16)
         {
             if (timeLeft > 3000)
             {
                 timeLeft -= 60;
             }
             velocity.Y -= 0.5f;
         }
         else if (aiStyle == 25 || aiStyle == 17)
         {
             if (velocity.Y > 10f)
             {
                 velocity.Y *= 0.97f;
             }
             velocity.Y -= 0.7f;
             if (velocity.Y < -10f)
             {
                 velocity.Y = -10f;
             }
         }
     }
References ai, aiStyle, WorldGen.CheckAchievement_RealEstateAndTownSlimes(), GetNPCSource_FromThis(), hostile, WorldGen.InWorld(), Kill(), Tile.liquid, Main.netMode, NPC.netUpdate, netUpdate, NPC.NewNPC(), Main.npc, Entity.position, NetMessage.SendData(), Tile.shimmer(), Entity.shimmerWet, Main.tile, timeLeft, type, NPC.unlockedSlimeRainbowSpawn, Entity.velocity, and Entity.wet.
Referenced by Update().