Terraria: Projectile.AI_172_HallowBossRainbowPelletStorm
AI_172_HallowBossRainbowPelletStorm()
void Projectile.AI_172_HallowBossRainbowPelletStorm () inline private
     {
         if (localAI[1] <= 90f)
         {
             localAI[1] += 1f;
             scale = 0.5f;
             Opacity = 0.5f;
             float lerpValue = Utils.GetLerpValue(0f, 90f, localAI[1]);
             scale = MathHelper.Lerp(5f, 1f, lerpValue);
             Opacity = 1f - (1f - lerpValue * lerpValue);
             return;
         }
         scale = 1f;
         Opacity = 1f;
         float num = 150f + 10f * (float)AI_172_GetPelletStormsCount();
         localAI[0] += 1f;
         if (localAI[0] >= num)
         {
             Kill();
             return;
         }
         velocity = Vector2.Zero;
         rotation = 0f;
         int num2 = AI_172_GetPelletStormsCount();
         for (int i = 0; i < num2; i++)
         {
             HallowBossPelletStormInfo hallowBossPelletStormInfo = AI_172_GetPelletStormInfo(i);
             for (int j = 0; j < hallowBossPelletStormInfo.BulletsInStorm; j++)
             {
                 if (hallowBossPelletStormInfo.IsValid(j))
                 {
                     hallowBossPelletStormInfo.GetBulletPosition(j, base.Center);
                 }
             }
         }
     }
References Projectile.HallowBossPelletStormInfo.BulletsInStorm, Projectile.HallowBossPelletStormInfo.GetBulletPosition(), Utils.GetLerpValue(), and Projectile.HallowBossPelletStormInfo.IsValid().