Terraria: Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks
Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks()
void Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks (Point pt, float size, Utils.TileActionAttempt plot) inline
     {
         Tile tile = Main.tile[pt.X, pt.Y];
         if (tile != null && tile.active() && tile.halfBrick())
         {
             int num = pt.Y - 1;
             if (num >= 0)
             {
                 tile = Main.tile[pt.X, num];
                 if (!WorldGen.SolidOrSlopedTile(tile))
                 {
                     pt.Y--;
                 }
             }
         }
         DelegateMethods.v2_1 = pt.ToVector2();
         DelegateMethods.f_1 = size;
         Utils.PlotTileArea(pt.X, pt.Y, plot);
     }
References Tile.active(), DelegateMethods.f_1, Tile.halfBrick(), Utils.PlotTileArea(), WorldGen.SolidOrSlopedTile(), Main.tile, and DelegateMethods.v2_1.