Terraria: Projectile.CanHitWithMeleeWeapon
CanHitWithMeleeWeapon()
bool Projectile.CanHitWithMeleeWeapon (Entity ent) inline
     {
         if (Distance(ent.Center) > ownerHitCheckDistance)
         {
             return false;
         }
         if (!Collision.CanHit(Main.player[owner].position, Main.player[owner].width, Main.player[owner].height, ent.position, ent.width, ent.height) && !Collision.CanHitLine(Main.player[owner].Center + new Vector2(Main.player[owner].direction * Main.player[owner].width / 2, Main.player[owner].gravDir * (float)(-Main.player[owner].height) / 3f), 0, 0, ent.Center + new Vector2(0f, -ent.height / 3), 0, 0) && !Collision.CanHitLine(Main.player[owner].Center + new Vector2(Main.player[owner].direction * Main.player[owner].width / 2, Main.player[owner].gravDir * (float)(-Main.player[owner].height) / 3f), 0, 0, ent.Center, 0, 0))
         {
             return Collision.CanHitLine(Main.player[owner].Center + new Vector2(Main.player[owner].direction * Main.player[owner].width / 2, 0f), 0, 0, ent.Center + new Vector2(0f, ent.height / 3), 0, 0);
         }
         return true;
     }
References Collision.CanHit(), Collision.CanHitLine(), Entity.Center, Entity.direction, Entity.Distance(), Player.gravDir, Entity.height, owner, ownerHitCheckDistance, Main.player, Entity.position, and Entity.width.
Referenced by BombsHurtPlayers(), and Damage().