Terraria: Projectile.AI_026
AI_026()
void Projectile.AI_026 () inline private
     {
         if (!Main.player[owner].active)
         {
             active = false;
             return;
         }
         bool flag = false;
         bool flag2 = false;
         bool flag3 = false;
         bool flag4 = false;
         bool flag5 = false;
         int num = 85;
         bool flag6 = type >= 191 && type <= 194;
         if (type == 324)
         {
             num = 120;
         }
         if (type == 112)
         {
             num = 100;
         }
         if (type == 127)
         {
             num = 50;
         }
         switch (type)
         {
         case 816:
         case 821:
         case 825:
         case 854:
         case 858:
         case 859:
         case 860:
         case 885:
         case 889:
         case 891:
         case 897:
         case 899:
         case 900:
         case 934:
             num = 95;
             break;
         case 884:
         case 890:
             num = 80;
             break;
         case 881:
             num = 95;
             if (Main.player[owner].ownedProjectileCounts[881] > 0)
             {
                 num = 120;
             }
             break;
         }
         if (type == 960)
         {
             Main.CurrentFrameFlags.HadAnActiveInteractibleProjectile = true;
             flag = true;
         }
         if (flag6)
         {
             if (lavaWet)
             {
                 ai[0] = 1f;
                 ai[1] = 0f;
             }
             num = 60 + 30 * minionPos;
         }
         else if (type == 266)
         {
             num = 60 + 30 * minionPos;
         }
         bool flag7 = ai[0] == -1f || ai[0] == -2f;
         bool num2 = ai[0] == -1f;
         bool flag8 = ai[0] == -2f;
         if (type == 111)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].bunny = false;
             }
             if (Main.player[owner].bunny)
             {
                 timeLeft = 2;
             }
         }
         if (type == 112)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].penguin = false;
             }
             if (Main.player[owner].penguin)
             {
                 timeLeft = 2;
             }
         }
         if (type == 334)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].puppy = false;
             }
             if (Main.player[owner].puppy)
             {
                 timeLeft = 2;
             }
         }
         if (type == 353)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].grinch = false;
             }
             if (Main.player[owner].grinch)
             {
                 timeLeft = 2;
             }
         }
         if (type == 127)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].turtle = false;
             }
             if (Main.player[owner].turtle)
             {
                 timeLeft = 2;
             }
         }
         if (type == 175)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].eater = false;
             }
             if (Main.player[owner].eater)
             {
                 timeLeft = 2;
             }
         }
         if (type == 197)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].skeletron = false;
             }
             if (Main.player[owner].skeletron)
             {
                 timeLeft = 2;
             }
         }
         if (type == 198)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].hornet = false;
             }
             if (Main.player[owner].hornet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 199)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].tiki = false;
             }
             if (Main.player[owner].tiki)
             {
                 timeLeft = 2;
             }
         }
         if (type == 200)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].lizard = false;
             }
             if (Main.player[owner].lizard)
             {
                 timeLeft = 2;
             }
         }
         if (type == 208)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].parrot = false;
             }
             if (Main.player[owner].parrot)
             {
                 timeLeft = 2;
             }
         }
         if (type == 209)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].truffle = false;
             }
             if (Main.player[owner].truffle)
             {
                 timeLeft = 2;
             }
         }
         if (type == 210)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].sapling = false;
             }
             if (Main.player[owner].sapling)
             {
                 timeLeft = 2;
             }
         }
         if (type == 324)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].cSapling = false;
             }
             if (Main.player[owner].cSapling)
             {
                 timeLeft = 2;
             }
         }
         if (type == 313)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].spider = false;
             }
             if (Main.player[owner].spider)
             {
                 timeLeft = 2;
             }
         }
         if (type == 314)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].squashling = false;
             }
             if (Main.player[owner].squashling)
             {
                 timeLeft = 2;
             }
         }
         if (type == 211)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].wisp = false;
             }
             if (Main.player[owner].wisp)
             {
                 timeLeft = 2;
             }
         }
         if (type == 236)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].dino = false;
             }
             if (Main.player[owner].dino)
             {
                 timeLeft = 2;
             }
         }
         if (type == 499)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].babyFaceMonster = false;
             }
             if (Main.player[owner].babyFaceMonster)
             {
                 timeLeft = 2;
             }
         }
         if (type == 765)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagSugarGlider = false;
             }
             if (Main.player[owner].petFlagSugarGlider)
             {
                 timeLeft = 2;
             }
         }
         if (type == 266)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].slime = false;
             }
             if (Main.player[owner].slime)
             {
                 timeLeft = 2;
             }
         }
         if (type == 268)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].eyeSpring = false;
             }
             if (Main.player[owner].eyeSpring)
             {
                 timeLeft = 2;
             }
         }
         if (type == 269)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].snowman = false;
             }
             if (Main.player[owner].snowman)
             {
                 timeLeft = 2;
             }
         }
         if (type == 319)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].blackCat = false;
             }
             if (Main.player[owner].blackCat)
             {
                 timeLeft = 2;
             }
         }
         if (type == 380)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].zephyrfish = false;
             }
             if (Main.player[owner].zephyrfish)
             {
                 timeLeft = 2;
             }
         }
         if (type == 774)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBabyShark = false;
             }
             if (Main.player[owner].petFlagBabyShark)
             {
                 timeLeft = 2;
             }
         }
         if (type == 815)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagLilHarpy = false;
             }
             if (Main.player[owner].petFlagLilHarpy)
             {
                 timeLeft = 2;
             }
         }
         if (type == 816)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagFennecFox = false;
             }
             if (Main.player[owner].petFlagFennecFox)
             {
                 timeLeft = 2;
             }
         }
         if (type == 817)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagGlitteryButterfly = false;
             }
             if (Main.player[owner].petFlagGlitteryButterfly)
             {
                 timeLeft = 2;
             }
         }
         if (type == 821)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBabyImp = false;
             }
             if (Main.player[owner].petFlagBabyImp)
             {
                 timeLeft = 2;
             }
         }
         if (type == 825)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBabyRedPanda = false;
             }
             if (Main.player[owner].petFlagBabyRedPanda)
             {
                 timeLeft = 2;
             }
         }
         if (type == 854)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagPlantero = false;
             }
             if (Main.player[owner].petFlagPlantero)
             {
                 timeLeft = 2;
             }
         }
         if (type == 858)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagDynamiteKitten = false;
             }
             if (Main.player[owner].petFlagDynamiteKitten)
             {
                 timeLeft = 2;
             }
         }
         if (type == 859)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBabyWerewolf = false;
             }
             if (Main.player[owner].petFlagBabyWerewolf)
             {
                 timeLeft = 2;
             }
         }
         if (type == 860)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagShadowMimic = false;
             }
             if (Main.player[owner].petFlagShadowMimic)
             {
                 timeLeft = 2;
             }
         }
         if (type == 875)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagVoltBunny = false;
             }
             if (Main.player[owner].petFlagVoltBunny)
             {
                 timeLeft = 2;
             }
         }
         if (type == 881)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagKingSlimePet = false;
             }
             if (Main.player[owner].petFlagKingSlimePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 884)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBrainOfCthulhuPet = false;
             }
             if (Main.player[owner].petFlagBrainOfCthulhuPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 885)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagSkeletronPet = false;
             }
             if (Main.player[owner].petFlagSkeletronPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 886)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagQueenBeePet = false;
             }
             if (Main.player[owner].petFlagQueenBeePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 889)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagSkeletronPrimePet = false;
             }
             if (Main.player[owner].petFlagSkeletronPrimePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 890)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagPlanteraPet = false;
             }
             if (Main.player[owner].petFlagPlanteraPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 891)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagGolemPet = false;
             }
             if (Main.player[owner].petFlagGolemPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 892)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagDukeFishronPet = false;
             }
             if (Main.player[owner].petFlagDukeFishronPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 894)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagMoonLordPet = false;
             }
             if (Main.player[owner].petFlagMoonLordPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 897)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagEverscreamPet = false;
             }
             if (Main.player[owner].petFlagEverscreamPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 899)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagMartianPet = false;
             }
             if (Main.player[owner].petFlagMartianPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 900)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagDD2OgrePet = false;
             }
             if (Main.player[owner].petFlagDD2OgrePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 901)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagDD2BetsyPet = false;
             }
             if (Main.player[owner].petFlagDD2BetsyPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 934)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagQueenSlimePet = false;
             }
             if (Main.player[owner].petFlagQueenSlimePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 956)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBerniePet = false;
             }
             if (Main.player[owner].petFlagBerniePet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 958)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagDeerclopsPet = false;
             }
             if (Main.player[owner].petFlagDeerclopsPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 959)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagPigPet = false;
             }
             if (Main.player[owner].petFlagPigPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 960)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagChesterPet = false;
             }
             if (Main.player[owner].petFlagChesterPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 994)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagJunimoPet = false;
             }
             if (Main.player[owner].petFlagJunimoPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 998)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagBlueChickenPet = false;
             }
             if (Main.player[owner].petFlagBlueChickenPet)
             {
                 timeLeft = 2;
             }
         }
         if (type == 1003)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagSpiffo = false;
             }
             if (Main.player[owner].petFlagSpiffo)
             {
                 timeLeft = 2;
             }
         }
         if (type == 1004)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].petFlagCaveling = false;
             }
             if (Main.player[owner].petFlagCaveling)
             {
                 timeLeft = 2;
             }
         }
         if (flag6)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].pygmy = false;
             }
             if (Main.player[owner].pygmy)
             {
                 timeLeft = Main.rand.Next(2, 10);
             }
         }
         if (type >= 390 && type <= 392)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].spiderMinion = false;
             }
             if (Main.player[owner].spiderMinion)
             {
                 timeLeft = 2;
             }
         }
         if (type == 398)
         {
             if (Main.player[owner].dead)
             {
                 Main.player[owner].miniMinotaur = false;
             }
             if (Main.player[owner].miniMinotaur)
             {
                 timeLeft = 2;
             }
         }
         if (flag7)
         {
             timeLeft = 2;
         }
         if (flag6 || type == 266 || (type >= 390 && type <= 392))
         {
             num = 10;
             int num3 = 40 * (minionPos + 1) * Main.player[owner].direction;
             if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) < position.X + (float)(width / 2) - (float)num + (float)num3)
             {
                 flag2 = true;
             }
             else if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) > position.X + (float)(width / 2) + (float)num + (float)num3)
             {
                 flag3 = true;
             }
         }
         else if (type == 891)
         {
             num = 30;
             float num4 = -50 * -Main.player[owner].direction;
             float num5 = Main.player[owner].Center.X + num4;
             if (num5 < position.X + (float)(width / 2) - (float)num)
             {
                 flag2 = true;
             }
             else if (num5 > position.X + (float)(width / 2) + (float)num)
             {
                 flag3 = true;
             }
         }
         else if (type == 960 && !flag7)
         {
             num = 10;
             Player player = Main.player[owner];
             int num6 = ((player.Center.X - base.Center.X > 0f) ? 1 : (-1));
             if (player.velocity.X != 0f)
             {
                 num6 = player.direction;
             }
             float num7 = -70 * num6;
             float num8 = player.Center.X + num7;
             if (num8 < base.Center.X - (float)num)
             {
                 flag2 = true;
             }
             else if (num8 > base.Center.X + (float)num)
             {
                 flag3 = true;
             }
         }
         else if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) < position.X + (float)(width / 2) - (float)num)
         {
             flag2 = true;
         }
         else if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) > position.X + (float)(width / 2) + (float)num)
         {
             flag3 = true;
         }
         if (num2)
         {
             flag2 = false;
             flag3 = true;
             num = 30;
         }
         if (flag8)
         {
             flag2 = false;
             flag3 = false;
         }
         if (type == 175)
         {
             float num9 = 0.1f;
             tileCollide = false;
             int num10 = 300;
             Vector2 vector = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num11 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector.X;
             float num12 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector.Y;
             if (type == 127)
             {
                 num12 = Main.player[owner].position.Y - vector.Y;
             }
             float num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
             float num14 = 7f;
             float num15 = 2000f;
             bool num16 = num13 > num15;
             if (num13 < (float)num10 && Main.player[owner].velocity.Y == 0f && position.Y + (float)height <= Main.player[owner].position.Y + (float)Main.player[owner].height && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             if (num13 < 150f)
             {
                 if (Math.Abs(velocity.X) > 2f || Math.Abs(velocity.Y) > 2f)
                 {
                     velocity *= 0.99f;
                 }
                 num9 = 0.01f;
                 if (num11 < -2f)
                 {
                     num11 = -2f;
                 }
                 if (num11 > 2f)
                 {
                     num11 = 2f;
                 }
                 if (num12 < -2f)
                 {
                     num12 = -2f;
                 }
                 if (num12 > 2f)
                 {
                     num12 = 2f;
                 }
             }
             else
             {
                 if (num13 > 300f)
                 {
                     num9 = 0.2f;
                 }
                 num13 = num14 / num13;
                 num11 *= num13;
                 num12 *= num13;
             }
             if (num16)
             {
                 int num17 = 17;
                 for (int i = 0; i < 12; i++)
                 {
                     float speedX = 1f - Main.rand.NextFloat() * 2f;
                     float speedY = 1f - Main.rand.NextFloat() * 2f;
                     int num18 = Dust.NewDust(position, width, height, num17, speedX, speedY);
                     Main.dust[num18].noLightEmittence = true;
                     Main.dust[num18].noGravity = true;
                 }
                 base.Center = Main.player[owner].Center;
                 velocity = Vector2.Zero;
                 if (Main.myPlayer == owner)
                 {
                     netUpdate = true;
                 }
             }
             if (Math.Abs(num11) > Math.Abs(num12) || num9 == 0.05f)
             {
                 if (velocity.X < num11)
                 {
                     velocity.X += num9;
                     if (num9 > 0.05f && velocity.X < 0f)
                     {
                         velocity.X += num9;
                     }
                 }
                 if (velocity.X > num11)
                 {
                     velocity.X -= num9;
                     if (num9 > 0.05f && velocity.X > 0f)
                     {
                         velocity.X -= num9;
                     }
                 }
             }
             if (Math.Abs(num11) <= Math.Abs(num12) || num9 == 0.05f)
             {
                 if (velocity.Y < num12)
                 {
                     velocity.Y += num9;
                     if (num9 > 0.05f && velocity.Y < 0f)
                     {
                         velocity.Y += num9;
                     }
                 }
                 if (velocity.Y > num12)
                 {
                     velocity.Y -= num9;
                     if (num9 > 0.05f && velocity.Y > 0f)
                     {
                         velocity.Y -= num9;
                     }
                 }
             }
             rotation = (float)Math.Atan2(velocity.Y, velocity.X) - 1.57f;
             frameCounter++;
             if (frameCounter > 6)
             {
                 frame++;
                 frameCounter = 0;
             }
             if (frame > 1)
             {
                 frame = 0;
             }
             return;
         }
         if (type == 197)
         {
             float num19 = 0.1f;
             tileCollide = false;
             int num20 = 300;
             Vector2 vector2 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num21 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector2.X;
             float num22 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector2.Y;
             if (type == 127)
             {
                 num22 = Main.player[owner].position.Y - vector2.Y;
             }
             float num23 = (float)Math.Sqrt(num21 * num21 + num22 * num22);
             float num24 = 3f;
             if (num23 > 500f)
             {
                 localAI[0] = 10000f;
             }
             if (localAI[0] >= 10000f)
             {
                 num24 = 14f;
             }
             float num25 = 2000f;
             bool num26 = num23 > num25;
             if (num23 < (float)num20 && Main.player[owner].velocity.Y == 0f && position.Y + (float)height <= Main.player[owner].position.Y + (float)Main.player[owner].height && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             if (num23 < 150f)
             {
                 if (Math.Abs(velocity.X) > 2f || Math.Abs(velocity.Y) > 2f)
                 {
                     velocity *= 0.99f;
                 }
                 num19 = 0.01f;
                 if (num21 < -2f)
                 {
                     num21 = -2f;
                 }
                 if (num21 > 2f)
                 {
                     num21 = 2f;
                 }
                 if (num22 < -2f)
                 {
                     num22 = -2f;
                 }
                 if (num22 > 2f)
                 {
                     num22 = 2f;
                 }
             }
             else
             {
                 if (num23 > 300f)
                 {
                     num19 = 0.2f;
                 }
                 num23 = num24 / num23;
                 num21 *= num23;
                 num22 *= num23;
             }
             if (num26)
             {
                 int num27 = 26;
                 for (int j = 0; j < 12; j++)
                 {
                     float speedX2 = 1f - Main.rand.NextFloat() * 2f;
                     float speedY2 = 1f - Main.rand.NextFloat() * 2f;
                     int num28 = Dust.NewDust(position, width, height, num27, speedX2, speedY2);
                     Main.dust[num28].noLightEmittence = true;
                     Main.dust[num28].noGravity = true;
                 }
                 base.Center = Main.player[owner].Center;
                 velocity = Vector2.Zero;
                 if (Main.myPlayer == owner)
                 {
                     netUpdate = true;
                 }
             }
             if (velocity.X < num21)
             {
                 velocity.X += num19;
                 if (num19 > 0.05f && velocity.X < 0f)
                 {
                     velocity.X += num19;
                 }
             }
             if (velocity.X > num21)
             {
                 velocity.X -= num19;
                 if (num19 > 0.05f && velocity.X > 0f)
                 {
                     velocity.X -= num19;
                 }
             }
             if (velocity.Y < num22)
             {
                 velocity.Y += num19;
                 if (num19 > 0.05f && velocity.Y < 0f)
                 {
                     velocity.Y += num19;
                 }
             }
             if (velocity.Y > num22)
             {
                 velocity.Y -= num19;
                 if (num19 > 0.05f && velocity.Y > 0f)
                 {
                     velocity.Y -= num19;
                 }
             }
             localAI[0] += Main.rand.Next(10);
             if (localAI[0] > 10000f)
             {
                 if (localAI[1] == 0f)
                 {
                     if (velocity.X < 0f)
                     {
                         localAI[1] = -1f;
                     }
                     else
                     {
                         localAI[1] = 1f;
                     }
                 }
                 rotation += 0.25f * localAI[1];
                 if (localAI[0] > 12000f)
                 {
                     localAI[0] = 0f;
                 }
             }
             else
             {
                 localAI[1] = 0f;
                 float num29 = velocity.X * 0.1f;
                 if (rotation > num29)
                 {
                     rotation -= (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
                     if (rotation < num29)
                     {
                         rotation = num29;
                     }
                 }
                 if (rotation < num29)
                 {
                     rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
                     if (rotation > num29)
                     {
                         rotation = num29;
                     }
                 }
             }
             if ((double)rotation > 6.28)
             {
                 rotation -= 6.28f;
             }
             if ((double)rotation < -6.28)
             {
                 rotation += 6.28f;
             }
             return;
         }
         if (type == 198 || type == 380 || type == 774 || type == 815 || type == 817 || type == 886 || type == 892 || type == 894 || type == 901)
         {
             float num30 = 0.4f;
             if (type == 380)
             {
                 num30 = 0.3f;
             }
             if (type == 774)
             {
                 num30 = 0.3f;
             }
             tileCollide = false;
             int num31 = 100;
             float num32 = 50f;
             float num33 = 400f;
             float num34 = num33 / 2f;
             float num35 = 2000f;
             bool flag9 = false;
             Vector2 vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num36 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector3.X;
             float num37 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector3.Y;
             if (type == 774)
             {
                 num32 = 2f;
                 float num38 = (float)Math.Sin((float)Math.PI * 2f * ((float)Main.player[owner].miscCounter / 60f));
                 float num39 = Utils.GetLerpValue(0.5f, 1f, num38, clamped: true);
                 if (new Vector2(num36 - (float)(70 * Main.player[owner].direction), num37 - 60f).Length() > 50f)
                 {
                     num38 = 0f;
                     num39 = 0f;
                 }
                 num37 += -60f + num39 * -8f + num38 * 8f;
                 num36 += (float)(70 * -Main.player[owner].direction);
             }
             else
             {
                 if (type != 892 && type != 894)
                 {
                     num37 += (float)Main.rand.Next(-10, 21);
                     num36 += (float)Main.rand.Next(-10, 21);
                 }
                 num36 += (float)(60 * -Main.player[owner].direction);
                 num37 -= 60f;
             }
             Vector2 vector4 = new Vector2(num36, num37);
             if (type == 127)
             {
                 num37 = Main.player[owner].position.Y - vector3.Y;
             }
             float num40 = (float)Math.Sqrt(num36 * num36 + num37 * num37);
             float num41 = num40;
             float num42 = 14f;
             if (type == 380)
             {
                 num42 = 6f;
             }
             if (type == 815 || type == 817)
             {
                 num42 = ((!(num40 < num33)) ? 10f : 6f);
             }
             if (type == 892 || type == 894 || type == 901)
             {
                 if (num40 < num34)
                 {
                     num42 = 6f;
                 }
                 num42 = ((!(num40 < num33)) ? 12f : 9f);
             }
             if (type == 774)
             {
                 num42 = 5f;
             }
             if (num40 < (float)num31 && Main.player[owner].velocity.Y == 0f && position.Y + (float)height <= Main.player[owner].position.Y + (float)Main.player[owner].height && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             if (num40 < num32)
             {
                 if (Math.Abs(velocity.X) > 2f || Math.Abs(velocity.Y) > 2f)
                 {
                     if (type == 892 || type == 892)
                     {
                         velocity *= 0.95f;
                     }
                     else
                     {
                         velocity *= 0.99f;
                     }
                 }
                 num30 = 0.01f;
             }
             else
             {
                 if (type == 892 || type == 894 || type == 901)
                 {
                     if (num40 < 100f)
                     {
                         num30 = 0.1f;
                     }
                     if (num40 > num35)
                     {
                         flag9 = true;
                     }
                     else if (num40 > num33)
                     {
                         num30 = 0.7f;
                     }
                     else if (num40 > num34)
                     {
                         num30 = 0.5f;
                     }
                 }
                 else if (type == 815 || type == 817)
                 {
                     if (num40 < 100f)
                     {
                         num30 = 0.1f;
                     }
                     if (num40 > num35)
                     {
                         flag9 = true;
                     }
                     else if (type != 815 && num40 > num33)
                     {
                         num30 = 0.5f;
                     }
                 }
                 else if (type == 380)
                 {
                     if (num40 < 100f)
                     {
                         num30 = 0.1f;
                     }
                     if (num40 > 300f)
                     {
                         num30 = 0.4f;
                     }
                     if (num40 > num35)
                     {
                         flag9 = true;
                     }
                 }
                 else if (type == 198 || type == 886)
                 {
                     if (num40 < 100f)
                     {
                         num30 = 0.1f;
                     }
                     if (num40 > 300f)
                     {
                         num30 = 0.6f;
                     }
                     if (num40 > num35)
                     {
                         flag9 = true;
                     }
                 }
                 else if (type == 774)
                 {
                     if (num40 < 40f)
                     {
                         num30 = 0.1f;
                     }
                     if (num40 > 300f)
                     {
                         num30 = 0.6f;
                     }
                     if (num40 > num35)
                     {
                         flag9 = true;
                     }
                 }
                 num40 = num42 / num40;
                 num36 *= num40;
                 num37 *= num40;
             }
             if (velocity.X < num36)
             {
                 velocity.X += num30;
                 if (num30 > 0.05f && velocity.X < 0f)
                 {
                     velocity.X += num30;
                 }
             }
             if (velocity.X > num36)
             {
                 velocity.X -= num30;
                 if (num30 > 0.05f && velocity.X > 0f)
                 {
                     velocity.X -= num30;
                 }
             }
             if (velocity.Y < num37)
             {
                 velocity.Y += num30;
                 if (num30 > 0.05f && velocity.Y < 0f)
                 {
                     velocity.Y += num30 * 2f;
                 }
             }
             if (velocity.Y > num37)
             {
                 velocity.Y -= num30;
                 if (num30 > 0.05f && velocity.Y > 0f)
                 {
                     velocity.Y -= num30 * 2f;
                 }
             }
             if ((double)velocity.X > 0.25)
             {
                 direction = -1;
             }
             else if ((double)velocity.X < -0.25)
             {
                 direction = 1;
             }
             spriteDirection = direction;
             rotation = velocity.X * 0.05f;
             if (flag9)
             {
                 int num43 = 33;
                 if (type == 198 || type == 886)
                 {
                     num43 = 147;
                 }
                 if (type == 815)
                 {
                     num43 = 31;
                 }
                 if (type == 817)
                 {
                     num43 = 21;
                 }
                 for (int k = 0; k < 12; k++)
                 {
                     float speedX3 = 1f - Main.rand.NextFloat() * 2f;
                     float speedY3 = 1f - Main.rand.NextFloat() * 2f;
                     int num44 = Dust.NewDust(position, width, height, num43, speedX3, speedY3);
                     Main.dust[num44].noLightEmittence = true;
                     Main.dust[num44].noGravity = true;
                 }
                 base.Center = Main.player[owner].Center;
                 velocity = Vector2.Zero;
                 if (Main.myPlayer == owner)
                 {
                     netUpdate = true;
                 }
             }
             bool flag10 = false;
             int num45 = 3;
             int num46 = 0;
             int num47 = 3;
             if (type == 380)
             {
                 num45 = 6;
             }
             if (type == 815)
             {
                 num45 = 5;
                 num46 = 0;
                 num47 = 5;
                 if (num41 > num33)
                 {
                     num46 = 6;
                     num47 = 9;
                 }
             }
             if (type == 817)
             {
                 num45 = 5;
                 num46 = 0;
                 num47 = 2;
                 flag10 = true;
             }
             if (type == 901)
             {
                 num45 = 4;
                 num46 = 0;
                 num47 = 5;
                 if (num41 > num33 / 2f)
                 {
                     num45 = 3;
                     num46 = 6;
                     num47 = 11;
                 }
             }
             if (type == 892)
             {
                 num45 = 6;
                 num46 = 0;
                 num47 = Main.projFrames[type] - 1;
             }
             if (type == 886 || type == 894)
             {
                 num45 = 4;
                 num46 = 0;
                 num47 = Main.projFrames[type] - 1;
             }
             if (type == 774)
             {
                 if (Main.player[owner].velocity.Length() < 2f && vector4.Length() < 10f)
                 {
                     direction = -Main.player[owner].direction;
                     spriteDirection = direction;
                 }
                 num45 = 6;
                 if (!wet)
                 {
                     num46 += 4;
                     num47 += 4;
                 }
                 rotation = velocity.X * 0.05f + Math.Abs(velocity.Y * -0.05f);
             }
             if (flag10)
             {
                 int num48 = num45 * (num47 - num46) * 2;
                 frameCounter++;
                 if (frameCounter >= num48)
                 {
                     frameCounter = 0;
                 }
                 frame = frameCounter / num45;
                 if (frame > num47)
                 {
                     frame = num47 + (num47 - frame);
                 }
                 frame = (int)MathHelper.Clamp(frame, num46, num47);
             }
             else if (++frameCounter >= num45)
             {
                 frameCounter = 0;
                 frame++;
                 if (frame < num46 || frame > num47)
                 {
                     frame = num46;
                 }
             }
             return;
         }
         if (type == 211)
         {
             float num49 = 0.2f;
             float num50 = 5f;
             tileCollide = false;
             Vector2 vector5 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num51 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector5.X;
             float num52 = Main.player[owner].position.Y + Main.player[owner].gfxOffY + (float)(Main.player[owner].height / 2) - vector5.Y;
             if (Main.player[owner].controlLeft)
             {
                 num51 -= 120f;
             }
             else if (Main.player[owner].controlRight)
             {
                 num51 += 120f;
             }
             if (Main.player[owner].controlDown)
             {
                 num52 += 120f;
             }
             else
             {
                 if (Main.player[owner].controlUp)
                 {
                     num52 -= 120f;
                 }
                 num52 -= 60f;
             }
             float num53 = (float)Math.Sqrt(num51 * num51 + num52 * num52);
             if (num53 > 1000f)
             {
                 position.X += num51;
                 position.Y += num52;
             }
             if (localAI[0] == 1f)
             {
                 if (num53 < 10f)
                 {
                     Player player2 = Main.player[owner];
                     if (Math.Abs(player2.velocity.X) + Math.Abs(player2.velocity.Y) < num50 && (player2.velocity.Y == 0f || (player2.mount.Active && player2.mount.CanFly())))
                     {
                         localAI[0] = 0f;
                     }
                 }
                 num50 = 12f;
                 if (num53 < num50)
                 {
                     velocity.X = num51;
                     velocity.Y = num52;
                 }
                 else
                 {
                     num53 = num50 / num53;
                     velocity.X = num51 * num53;
                     velocity.Y = num52 * num53;
                 }
                 if ((double)velocity.X > 0.5)
                 {
                     direction = -1;
                 }
                 else if ((double)velocity.X < -0.5)
                 {
                     direction = 1;
                 }
                 spriteDirection = direction;
                 rotation -= (0.2f + Math.Abs(velocity.X) * 0.025f) * (float)direction;
                 frameCounter++;
                 if (frameCounter > 3)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 5)
                 {
                     frame = 5;
                 }
                 if (frame > 9)
                 {
                     frame = 5;
                 }
                 for (int l = 0; l < 2; l++)
                 {
                     int num54 = Dust.NewDust(new Vector2(position.X + 3f, position.Y + 4f), 14, 14, 156);
                     Main.dust[num54].velocity *= 0.2f;
                     Main.dust[num54].noGravity = true;
                     Main.dust[num54].scale = 1.25f;
                     Main.dust[num54].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cLight, Main.player[owner]);
                 }
                 return;
             }
             if (num53 > 200f)
             {
                 localAI[0] = 1f;
             }
             if ((double)velocity.X > 0.5)
             {
                 direction = -1;
             }
             else if ((double)velocity.X < -0.5)
             {
                 direction = 1;
             }
             spriteDirection = direction;
             if (num53 < 10f)
             {
                 velocity.X = num51;
                 velocity.Y = num52;
                 rotation = velocity.X * 0.05f;
                 if (num53 < num50)
                 {
                     position += velocity;
                     velocity *= 0f;
                     num49 = 0f;
                 }
                 direction = -Main.player[owner].direction;
             }
             num53 = num50 / num53;
             num51 *= num53;
             num52 *= num53;
             if (velocity.X < num51)
             {
                 velocity.X += num49;
                 if (velocity.X < 0f)
                 {
                     velocity.X *= 0.99f;
                 }
             }
             if (velocity.X > num51)
             {
                 velocity.X -= num49;
                 if (velocity.X > 0f)
                 {
                     velocity.X *= 0.99f;
                 }
             }
             if (velocity.Y < num52)
             {
                 velocity.Y += num49;
                 if (velocity.Y < 0f)
                 {
                     velocity.Y *= 0.99f;
                 }
             }
             if (velocity.Y > num52)
             {
                 velocity.Y -= num49;
                 if (velocity.Y > 0f)
                 {
                     velocity.Y *= 0.99f;
                 }
             }
             if (velocity.X != 0f || velocity.Y != 0f)
             {
                 rotation = velocity.X * 0.05f;
             }
             frameCounter++;
             if (frameCounter > 3)
             {
                 frame++;
                 frameCounter = 0;
             }
             if (frame > 4)
             {
                 frame = 0;
             }
             return;
         }
         if (type == 199)
         {
             float num55 = 0.1f;
             tileCollide = false;
             int num56 = 200;
             Vector2 vector6 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num57 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector6.X;
             float num58 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector6.Y;
             num58 -= 60f;
             num57 -= 2f;
             if (type == 127)
             {
                 num58 = Main.player[owner].position.Y - vector6.Y;
             }
             float num59 = (float)Math.Sqrt(num57 * num57 + num58 * num58);
             float num60 = 4f;
             float num61 = num59;
             float num62 = 2000f;
             bool num63 = num59 > num62;
             if (num59 < (float)num56 && Main.player[owner].velocity.Y == 0f && position.Y + (float)height <= Main.player[owner].position.Y + (float)Main.player[owner].height && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             if (num59 < 4f)
             {
                 velocity.X = num57;
                 velocity.Y = num58;
                 num55 = 0f;
             }
             else
             {
                 if (num59 > 350f)
                 {
                     num55 = 0.2f;
                     num60 = 10f;
                 }
                 num59 = num60 / num59;
                 num57 *= num59;
                 num58 *= num59;
             }
             if (num63)
             {
                 int num64 = 2;
                 for (int m = 0; m < 12; m++)
                 {
                     float speedX4 = 1f - Main.rand.NextFloat() * 2f;
                     float speedY4 = 1f - Main.rand.NextFloat() * 2f;
                     int num65 = Dust.NewDust(position, width, height, num64, speedX4, speedY4);
                     Main.dust[num65].noLightEmittence = true;
                     Main.dust[num65].noGravity = true;
                 }
                 base.Center = Main.player[owner].Center;
                 velocity = Vector2.Zero;
                 if (Main.myPlayer == owner)
                 {
                     netUpdate = true;
                 }
             }
             if (velocity.X < num57)
             {
                 velocity.X += num55;
                 if (velocity.X < 0f)
                 {
                     velocity.X += num55;
                 }
             }
             if (velocity.X > num57)
             {
                 velocity.X -= num55;
                 if (velocity.X > 0f)
                 {
                     velocity.X -= num55;
                 }
             }
             if (velocity.Y < num58)
             {
                 velocity.Y += num55;
                 if (velocity.Y < 0f)
                 {
                     velocity.Y += num55;
                 }
             }
             if (velocity.Y > num58)
             {
                 velocity.Y -= num55;
                 if (velocity.Y > 0f)
                 {
                     velocity.Y -= num55;
                 }
             }
             direction = -Main.player[owner].direction;
             spriteDirection = 1;
             rotation = velocity.Y * 0.05f * (float)(-direction);
             if (num61 >= 50f)
             {
                 frameCounter++;
                 if (frameCounter <= 6)
                 {
                     return;
                 }
                 frameCounter = 0;
                 if (velocity.X < 0f)
                 {
                     if (frame < 2)
                     {
                         frame++;
                     }
                     if (frame > 2)
                     {
                         frame--;
                     }
                 }
                 else
                 {
                     if (frame < 6)
                     {
                         frame++;
                     }
                     if (frame > 6)
                     {
                         frame--;
                     }
                 }
             }
             else
             {
                 frameCounter++;
                 if (frameCounter > 6)
                 {
                     frame += direction;
                     frameCounter = 0;
                 }
                 if (frame > 7)
                 {
                     frame = 0;
                 }
                 if (frame < 0)
                 {
                     frame = 7;
                 }
             }
             return;
         }
         if (type == 885 || type == 889)
         {
             Player player3 = Main.player[owner];
             float num66 = 0.15f;
             tileCollide = false;
             int num67 = 150;
             Vector2 center = base.Center;
             float num68 = player3.Center.X - center.X;
             float num69 = player3.Center.Y - center.Y;
             num69 -= 65f;
             num68 -= (float)(30 * player3.direction);
             float num70 = (float)Math.Sqrt(num68 * num68 + num69 * num69);
             float num71 = 8f;
             float num72 = num70;
             float num73 = 2000f;
             bool num74 = num70 > num73;
             if (num70 < (float)num67 && player3.velocity.Y == 0f && position.Y + (float)height <= player3.position.Y + (float)player3.height && !Collision.SolidCollision(position, width, height) && velocity.Y < -6f)
             {
                 velocity.Y = -6f;
             }
             if (num70 < 10f)
             {
                 velocity *= 0.9f;
                 if (velocity.Length() < 0.5f)
                 {
                     velocity = Vector2.Zero;
                 }
                 num66 = 0f;
             }
             else
             {
                 if (num70 > (float)num67)
                 {
                     num66 = 0.2f;
                     num71 = 12f;
                 }
                 num70 = num71 / num70;
                 num68 *= num70;
                 num69 *= num70;
             }
             if (num74)
             {
                 int num75 = 234;
                 if (type == 889)
                 {
                     num75 = 60;
                 }
                 for (int n = 0; n < 12; n++)
                 {
                     float speedX5 = 1f - Main.rand.NextFloat() * 2f;
                     float speedY5 = 1f - Main.rand.NextFloat() * 2f;
                     int num76 = Dust.NewDust(position, width, height, num75, speedX5, speedY5);
                     Main.dust[num76].noLightEmittence = true;
                     Main.dust[num76].noGravity = true;
                 }
                 base.Center = player3.Center;
                 velocity = Vector2.Zero;
                 if (Main.myPlayer == owner)
                 {
                     netUpdate = true;
                 }
             }
             if (velocity.X < num68)
             {
                 velocity.X += num66;
                 if (velocity.X < 0f)
                 {
                     velocity.X += num66;
                 }
             }
             if (velocity.X > num68)
             {
                 velocity.X -= num66;
                 if (velocity.X > 0f)
                 {
                     velocity.X -= num66;
                 }
             }
             if (velocity.Y < num69)
             {
                 velocity.Y += num66;
                 if (velocity.Y < 0f)
                 {
                     velocity.Y += num66;
                 }
             }
             if (velocity.Y > num69)
             {
                 velocity.Y -= num66;
                 if (velocity.Y > 0f)
                 {
                     velocity.Y -= num66;
                 }
             }
             direction = -player3.direction;
             spriteDirection = -direction;
             int num77 = 100;
             if (num72 >= (float)num67)
             {
                 rotation += 0.5f;
                 if (rotation > (float)Math.PI * 2f)
                 {
                     rotation -= (float)Math.PI * 2f;
                 }
                 frame = 6;
                 frameCounter = 0;
                 if (type == 885)
                 {
                     localAI[0] = 0f;
                 }
                 if (type == 889)
                 {
                     localAI[0] += 3f;
                     if (localAI[0] > (float)num77)
                     {
                         localAI[0] = num77;
                     }
                 }
                 return;
             }
             rotation *= 0.95f;
             if (rotation < 0.05f)
             {
                 rotation = 0f;
             }
             frameCounter++;
             if (type == 885)
             {
                 switch (frameCounter)
                 {
                 case 10:
                     localAI[0] = 0f;
                     break;
                 case 20:
                     localAI[0] = 1f;
                     break;
                 case 30:
                     localAI[0] = 2f;
                     break;
                 case 40:
                     localAI[0] = 1f;
                     break;
                 }
             }
             if (type == 889)
             {
                 localAI[0] -= 3f;
                 if (localAI[0] < 0f)
                 {
                     localAI[0] = 0f;
                 }
             }
             if (frameCounter % 5 == 0)
             {
                 frame++;
                 if (frame > 5)
                 {
                     frame = 0;
                 }
             }
             if (frameCounter >= 40)
             {
                 frameCounter = 0;
             }
             return;
         }
         bool flag11 = ai[1] == 0f;
         if (flag)
         {
             flag11 = true;
         }
         if (flag11)
         {
             int num78 = 500;
             if (type == 127)
             {
                 num78 = 200;
             }
             if (type == 208)
             {
                 num78 = 300;
             }
             switch (type)
             {
             case 816:
             case 825:
             case 854:
             case 858:
             case 859:
             case 860:
             case 881:
             case 884:
             case 890:
             case 891:
             case 897:
             case 900:
             case 934:
                 num78 = 400;
                 break;
             case 821:
             case 899:
                 num78 = 500;
                 break;
             }
             if (flag6 || type == 266 || (type >= 390 && type <= 392))
             {
                 num78 += 40 * minionPos;
                 if (localAI[0] > 0f)
                 {
                     num78 += 500;
                 }
                 if (type == 266 && localAI[0] > 0f)
                 {
                     num78 += 100;
                 }
                 if (type >= 390 && type <= 392 && localAI[0] > 0f)
                 {
                     num78 += 400;
                 }
             }
             if (Main.player[owner].rocketDelay2 > 0)
             {
                 ai[0] = 1f;
             }
             Vector2 vector7 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num79 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector7.X;
             float num80 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector7.Y;
             float num81 = (float)Math.Sqrt(num79 * num79 + num80 * num80);
             if (!flag7)
             {
                 if (num81 > 2000f)
                 {
                     position.X = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - (float)(width / 2);
                     position.Y = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - (float)(height / 2);
                 }
                 else if (num81 > (float)num78 || (Math.Abs(num80) > 300f && ((!flag6 && type != 266 && (type < 390 || type > 392)) || !(localAI[0] > 0f))))
                 {
                     if (type != 324)
                     {
                         if (num80 > 0f && velocity.Y < 0f)
{
                             velocity.Y = 0f;
                         }
                         if (num80 < 0f && velocity.Y > 0f)
{
                             velocity.Y = 0f;
                         }
                     }
                     ai[0] = 1f;
                 }
             }
         }
         if ((type == 209 || type == 956) && ai[0] != 0f)
         {
             if (Main.player[owner].velocity.Y == 0f && alpha >= 100)
             {
                 position.X = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - (float)(width / 2);
                 position.Y = Main.player[owner].position.Y + (float)Main.player[owner].height - (float)height;
                 ai[0] = 0f;
             }
             else
             {
                 velocity.X = 0f;
                 velocity.Y = 0f;
                 if (type == 956 && alpha < 100)
                 {
                     int num82 = Dust.NewDust(position, width, height, 6, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                     Main.dust[num82].velocity.X += Main.rand.NextFloat() - 0.5f;
                     Main.dust[num82].velocity.Y += (Main.rand.NextFloat() + 0.5f) * -1f;
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num82].noGravity = true;
                     }
                 }
                 alpha += 5;
                 if (alpha > 255)
                 {
                     alpha = 255;
                 }
             }
         }
         else if (ai[0] != 0f && !flag7)
         {
             float num83 = 0.2f;
             int num84 = 200;
             if (type == 127)
             {
                 num84 = 100;
             }
             if (flag6 || type == 816 || type == 821 || type == 825 || type == 854 || type == 858 || type == 859 || type == 860)
             {
                 num83 = 0.5f;
                 num84 = 100;
             }
             if (type == 875)
             {
                 num83 = 2f;
                 num84 = 100;
             }
             tileCollide = false;
             Vector2 vector8 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
             float num85 = Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - vector8.X;
             if (flag6 || type == 266 || (type >= 390 && type <= 392))
             {
                 num85 -= (float)(40 * Main.player[owner].direction);
                 float num86 = 700f;
                 if (flag6)
                 {
                     num86 += 100f;
                 }
                 bool flag12 = false;
                 int num87 = -1;
                 for (int num88 = 0; num88 < 200; num88++)
                 {
                     if (!Main.npc[num88].CanBeChasedBy(this))
                     {
                         continue;
                     }
                     float num89 = Main.npc[num88].position.X + (float)(Main.npc[num88].width / 2);
                     float num90 = Main.npc[num88].position.Y + (float)(Main.npc[num88].height / 2);
                     if (Math.Abs(Main.player[owner].position.X + (float)(Main.player[owner].width / 2) - num89) + Math.Abs(Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - num90) < num86)
                     {
                         if (Collision.CanHit(position, width, height, Main.npc[num88].position, Main.npc[num88].width, Main.npc[num88].height))
{
                             num87 = num88;
                         }
                         flag12 = true;
                         break;
                     }
                 }
                 if (!flag12)
                 {
                     num85 -= (float)(40 * minionPos * Main.player[owner].direction);
                 }
                 if (flag12 && num87 >= 0)
                 {
                     ai[0] = 0f;
                 }
             }
             float num91 = Main.player[owner].position.Y + (float)(Main.player[owner].height / 2) - vector8.Y;
             if (type == 127)
             {
                 num91 = Main.player[owner].position.Y - vector8.Y;
             }
             float num92 = (float)Math.Sqrt(num85 * num85 + num91 * num91);
             float num93 = num92;
             float num94 = 10f;
             float num95 = num92;
             if (type == 111)
             {
                 num94 = 11f;
             }
             if (type == 127)
             {
                 num94 = 9f;
             }
             if (type == 875)
             {
                 num83 = 1.8f;
                 num94 = 16f;
             }
             if (type == 324)
             {
                 num94 = 20f;
             }
             if (flag6 || type == 816 || type == 821 || type == 825 || type == 854 || type == 858 || type == 859 || type == 860 || type == 956 || type == 958 || type == 959 || type == 960 || type == 994 || type == 998 || type == 1003 || type == 1004)
             {
                 num83 = 0.4f;
                 num94 = 12f;
                 if (flag6)
                 {
                     num83 = 0.8f;
                 }
                 if (num94 < Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y))
                 {
                     num94 = Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y);
                 }
             }
             if (type == 208 && Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y) > 4f)
             {
                 num84 = -1;
             }
             if (num92 < (float)num84 && Main.player[owner].velocity.Y == 0f && position.Y + (float)height <= Main.player[owner].position.Y + (float)Main.player[owner].height && !Collision.SolidCollision(position, width, height))
             {
                 ai[0] = 0f;
                 if (velocity.Y < -6f)
                 {
                     velocity.Y = -6f;
                 }
             }
             if (num92 < 60f)
             {
                 num85 = velocity.X;
                 num91 = velocity.Y;
             }
             else
             {
                 num92 = num94 / num92;
                 num85 *= num92;
                 num91 *= num92;
             }
             if (type == 324)
             {
                 if (num95 > 1000f)
                 {
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num94 - 1.25)
                     {
                         velocity *= 1.025f;
                     }
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) > (double)num94 + 1.25)
                     {
                         velocity *= 0.975f;
                     }
                 }
                 else if (num95 > 600f)
                 {
                     if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num94 - 1f)
                     {
                         velocity *= 1.05f;
                     }
                     if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) > num94 + 1f)
                     {
                         velocity *= 0.95f;
                     }
                 }
                 else if (num95 > 400f)
                 {
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num94 - 0.5)
                     {
                         velocity *= 1.075f;
                     }
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) > (double)num94 + 0.5)
                     {
                         velocity *= 0.925f;
                     }
                 }
                 else
                 {
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num94 - 0.25)
                     {
                         velocity *= 1.1f;
                     }
                     if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) > (double)num94 + 0.25)
                     {
                         velocity *= 0.9f;
                     }
                 }
                 velocity.X = (velocity.X * 34f + num85) / 35f;
                 velocity.Y = (velocity.Y * 34f + num91) / 35f;
             }
             else if (type == 875)
             {
                 if (num93 < (float)num84)
                 {
                     if (velocity.X < num85)
                     {
                         velocity.X += num83;
                     }
                     else if (velocity.X > num85)
                     {
                         velocity.X -= num83;
                     }
                     if (velocity.Y < num91)
                     {
                         velocity.Y += num83;
                     }
                     else if (velocity.Y > num91)
                     {
                         velocity.Y -= num83;
                     }
                 }
                 else
                 {
                     velocity = Vector2.Lerp(velocity, new Vector2(num85, num91), 0.75f);
                 }
             }
             else
             {
                 if (velocity.X < num85)
                 {
                     velocity.X += num83;
                     if (velocity.X < 0f)
                     {
                         velocity.X += num83 * 1.5f;
                     }
                 }
                 if (velocity.X > num85)
                 {
                     velocity.X -= num83;
                     if (velocity.X > 0f)
                     {
                         velocity.X -= num83 * 1.5f;
                     }
                 }
                 if (velocity.Y < num91)
                 {
                     velocity.Y += num83;
                     if (velocity.Y < 0f)
                     {
                         velocity.Y += num83 * 1.5f;
                     }
                 }
                 if (velocity.Y > num91)
                 {
                     velocity.Y -= num83;
                     if (velocity.Y > 0f)
                     {
                         velocity.Y -= num83 * 1.5f;
                     }
                 }
             }
             if (type == 111)
             {
                 frame = 7;
             }
             if (flag6 && frame < 12)
             {
                 frame = Main.rand.Next(12, 18);
                 frameCounter = 0;
             }
             if (type != 313)
             {
                 if ((double)velocity.X > 0.5)
                 {
                     spriteDirection = -1;
                 }
                 else if ((double)velocity.X < -0.5)
                 {
                     spriteDirection = 1;
                 }
             }
             if (type == 112)
             {
                 frameCounter++;
                 if (frame < 3)
                 {
                     frame = 3;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 3;
                     }
                 }
                 rotation = velocity.X * 0.125f;
             }
             else if (type == 900)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frameCounter++;
                 if (frame < 10)
                 {
                     frame = 10;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 10;
                     }
                 }
                 rotation = velocity.X * 0.125f;
             }
             else if (type == 899)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frameCounter++;
                 if (frame < 10)
                 {
                     frame = 10;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 10;
                     }
                 }
                 Vector2 v = velocity;
                 v.Normalize();
                 rotation = v.ToRotation();
                 if (velocity.X < 0f)
                 {
                     rotation += (float)Math.PI;
                 }
             }
             else if (type == 897)
             {
                 spriteDirection = 1;
                 frameCounter++;
                 if (frame < 8)
                 {
                     frame = 8;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 8;
                     }
                 }
                 Vector2 v2 = velocity;
                 v2.Normalize();
                 rotation = v2.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 891)
             {
                 spriteDirection = 1;
                 frameCounter++;
                 if (frame < 9)
                 {
                     frame = 9;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 9;
                     }
                 }
                 Vector2 v3 = velocity;
                 v3.Normalize();
                 rotation = v3.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 890)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frameCounter++;
                 if (frame < 9)
                 {
                     frame = 9;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 9;
                     }
                 }
                 rotation = velocity.X * 0.025f;
             }
             else if (type == 884)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frameCounter++;
                 if (frame < 9)
                 {
                     frame = 9;
                     frameCounter = 0;
                 }
                 if (frameCounter > 3)
                 {
                     frameCounter = 0;
                     frame++;
                     if (frame >= Main.projFrames[type])
                     {
                         frame = 9;
                     }
                 }
                 Vector2 v4 = velocity;
                 v4.Normalize();
                 rotation = v4.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 881 || type == 934)
             {
                 int num96 = 1226;
                 if (type == 934)
                 {
                     num96 = 1261;
                 }
                 if (frame < 6 || frame > 11)
                 {
                     Gore.NewGore(new Vector2(base.Center.X, position.Y), velocity * 0.5f, num96);
                 }
                 frameCounter++;
                 if (frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 6 || frame > 11)
                 {
                     frame = 6;
                 }
                 Vector2 v5 = velocity;
                 v5.Normalize();
                 rotation = v5.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 875)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 7 || frame > 10)
                 {
                     frame = 7;
                 }
                 Vector2 v6 = velocity;
                 v6.Normalize();
                 rotation = v6.ToRotation() + ((spriteDirection == -1) ? 0f : ((float)Math.PI));
             }
             else if (type == 825)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 21 || frame > 25)
                 {
                     frame = 21;
                 }
                 rotation = velocity.X * 0.025f;
             }
             else if (type == 854)
             {
                 if (frame < 13)
                 {
                     Gore.NewGore(new Vector2(base.Center.X, position.Y), velocity * 0.5f, 1269);
                 }
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 13 || frame > 18)
                 {
                     frame = 13;
                 }
                 Vector2 v7 = velocity;
                 v7.Normalize();
                 rotation = v7.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 858)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 10 || frame > 13)
                 {
                     frame = 10;
                 }
                 Vector2 v8 = velocity;
                 v8.Normalize();
                 rotation = v8.ToRotation() + ((spriteDirection == -1) ? 0f : ((float)Math.PI));
             }
             else if (type == 859)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 18 || frame > 23)
                 {
                     frame = 18;
                 }
                 rotation = velocity.X * 0.025f;
             }
             else if (type == 860)
             {
                 if (frame < 6)
                 {
                     frame = 8;
                     frameCounter = 0;
                 }
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 13)
                 {
                     frame = 6;
                 }
                 Vector2 v9 = velocity;
                 v9.Normalize();
                 rotation = v9.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 816)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 11 || frame > 16)
                 {
                     frame = 11;
                 }
                 rotation = velocity.X * 0.025f;
             }
             else if (type == 821)
             {
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 19 || frame > 22)
                 {
                     frame = 19;
                 }
                 rotation = velocity.X * 0.025f;
             }
             else if (type == 958)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 if (frame < 13)
                 {
                     frame = 13;
                     frameCounter = 0;
                 }
                 if (++frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 16)
                 {
                     frame = 13;
                 }
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.4f, 0.4f);
             }
             else if (type == 960)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frame = 4;
                 frameCounter = 0;
                 Vector2 v10 = velocity;
                 v10.Normalize();
                 rotation = v10.ToRotation() + (float)Math.PI / 2f;
             }
             else if (type == 959)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frame = 11;
                 frameCounter = 0;
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.4f, 0.4f);
                 float num97 = Vector2.Dot(velocity.SafeNormalize(Vector2.UnitX), new Vector2(0f, -1f));
                 if (num97 > 0f && Main.rand.NextFloat() < 0.3f + num97 * 0.3f)
                 {
                     Dust dust = Dust.NewDustDirect(position, width, height, 16, velocity.X * 0.7f, velocity.Y * 1.2f, 150, default(Color), 0.6f);
                     dust.noGravity = true;
                     dust.fadeIn = 1f;
                     dust.velocity.X = velocity.X * 0.3f;
                     dust.position = base.Top + new Vector2(0f, -10f) + new Vector2(Main.rand.NextFloatDirection() * 30f, Main.rand.NextFloatDirection() * 10f);
                     dust.velocity *= 0.7f;
                     dust.position += dust.velocity * 2f;
                 }
             }
             else if (type == 994)
             {
                 spriteDirection = -1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = 1;
                 }
                 frameCounter++;
                 if (frameCounter > 5)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 13 || frame > 15)
                 {
                     frame = 13;
                 }
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.4f, 0.4f);
             }
             else if (type == 998)
             {
                 spriteDirection = 1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = -1;
                 }
                 frameCounter++;
                 if (frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 6 || frame > 9)
                 {
                     frame = 6;
                 }
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.4f, 0.4f);
             }
             else if (type == 1003)
             {
                 spriteDirection = 1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = -1;
                 }
                 frameCounter++;
                 if (frameCounter > 3)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 12 || frame > 15)
                 {
                     frame = 12;
                 }
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.35f, 0.35f);
             }
             else if (type == 1004)
             {
                 spriteDirection = 1;
                 if (velocity.X > 0f)
                 {
                     spriteDirection = -1;
                 }
                 frameCounter++;
                 if (frameCounter > 3)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 10 || frame > 14)
                 {
                     frame = 10;
                 }
                 rotation = MathHelper.Clamp(velocity.X * 0.025f, -0.35f, 0.35f);
             }
             else if (type == 112)
             {
                 if (spriteDirection == -1)
                 {
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                 }
                 else
                 {
                     rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
                 }
             }
             else if (type >= 390 && type <= 392)
             {
                 int num98 = (int)(base.Center.X / 16f);
                 int num99 = (int)(base.Center.Y / 16f);
                 if (Main.tile[num98, num99] != null && Main.tile[num98, num99].wall > 0)
                 {
                     rotation = velocity.ToRotation() + (float)Math.PI / 2f;
                     frameCounter += (int)(Math.Abs(velocity.X) + Math.Abs(velocity.Y));
                     if (frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 7)
                     {
                         frame = 4;
                     }
                     if (frame < 4)
                     {
                         frame = 7;
                     }
                 }
                 else
                 {
                     frameCounter++;
                     if (frameCounter > 2)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 8 || frame > 10)
                     {
                         frame = 8;
                     }
                     rotation = velocity.X * 0.1f;
                 }
             }
             else if (type == 334)
             {
                 frameCounter++;
                 if (frameCounter > 1)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 7 || frame > 10)
                 {
                     frame = 7;
                 }
                 rotation = velocity.X * 0.1f;
             }
             else if (type == 353)
             {
                 frameCounter++;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 10 || frame > 13)
                 {
                     frame = 10;
                 }
                 rotation = velocity.X * 0.05f;
             }
             else if (type == 127)
             {
                 frameCounter += 3;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame <= 5 || frame > 15)
                 {
                     frame = 6;
                 }
                 rotation = velocity.X * 0.1f;
             }
             else if (type == 269)
             {
                 if (frame == 6)
                 {
                     frameCounter = 0;
                 }
                 else if (frame < 4 || frame > 6)
                 {
                     frameCounter = 0;
                     frame = 4;
                 }
                 else
                 {
                     frameCounter++;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                 }
                 rotation = velocity.X * 0.05f;
             }
             else if (type == 266)
             {
                 frameCounter++;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 2 || frame > 5)
                 {
                     frame = 2;
                 }
                 rotation = velocity.X * 0.1f;
             }
             else if (type == 324)
             {
                 frameCounter++;
                 if (frameCounter > 1)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 6 || frame > 9)
                 {
                     frame = 6;
                 }
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.58f;
                 Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.9f, 0.6f, 0.2f);
                 for (int num100 = 0; num100 < 2; num100++)
                 {
                     int num101 = 4;
                     int num102 = Dust.NewDust(new Vector2(base.Center.X - (float)num101, base.Center.Y - (float)num101) - velocity * 0f, num101 * 2, num101 * 2, 6, 0f, 0f, 100);
                     Main.dust[num102].scale *= 1.8f + (float)Main.rand.Next(10) * 0.1f;
                     Main.dust[num102].velocity *= 0.2f;
                     if (num100 == 1)
                     {
                         Main.dust[num102].position -= velocity * 0.5f;
                     }
                     Main.dust[num102].noGravity = true;
                     num102 = Dust.NewDust(new Vector2(base.Center.X - (float)num101, base.Center.Y - (float)num101) - velocity * 0f, num101 * 2, num101 * 2, 31, 0f, 0f, 100, default(Color), 0.5f);
                     Main.dust[num102].fadeIn = 1f + (float)Main.rand.Next(5) * 0.1f;
                     Main.dust[num102].velocity *= 0.05f;
                     if (num100 == 1)
                     {
                         Main.dust[num102].position -= velocity * 0.5f;
                     }
                 }
             }
             else if (type == 268)
             {
                 frameCounter++;
                 if (frameCounter > 4)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 6 || frame > 7)
                 {
                     frame = 6;
                 }
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.58f;
             }
             else if (type == 200)
             {
                 frameCounter += 3;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame <= 5 || frame > 9)
                 {
                     frame = 6;
                 }
                 rotation = velocity.X * 0.1f;
             }
             else if (type == 208)
             {
                 rotation = velocity.X * 0.075f;
                 frameCounter++;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 4)
                 {
                     frame = 1;
                 }
                 if (frame < 1)
                 {
                     frame = 1;
                 }
             }
             else if (type == 236)
             {
                 rotation = velocity.Y * 0.05f * (float)direction;
                 if (velocity.Y < 0f)
                 {
                     frameCounter += 2;
                 }
                 else
                 {
                     frameCounter++;
                 }
                 if (frameCounter >= 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 12)
                 {
                     frame = 9;
                 }
                 if (frame < 9)
                 {
                     frame = 9;
                 }
             }
             else if (type == 499)
             {
                 rotation = velocity.Y * 0.05f * (float)direction;
                 if (velocity.Y < 0f)
                 {
                     frameCounter += 2;
                 }
                 else
                 {
                     frameCounter++;
                 }
                 if (frameCounter >= 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame >= 12)
                 {
                     frame = 8;
                 }
                 if (frame < 8)
                 {
                     frame = 8;
                 }
             }
             else if (type == 765)
             {
                 rotation = velocity.Y * 0.05f * (float)direction;
                 frameCounter++;
                 if (frameCounter >= 8)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame >= 10)
                 {
                     frame = 8;
                 }
                 if (frame < 6)
                 {
                     frame = 6;
                 }
             }
             else if (type == 314)
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.58f;
                 frameCounter++;
                 if (frameCounter >= 3)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 12)
                 {
                     frame = 7;
                 }
                 if (frame < 7)
                 {
                     frame = 7;
                 }
             }
             else if (type == 319)
             {
                 rotation = velocity.X * 0.05f;
                 frameCounter++;
                 if (frameCounter >= 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 10)
                 {
                     frame = 6;
                 }
                 if (frame < 6)
                 {
                     frame = 6;
                 }
             }
             else if (type == 210)
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.58f;
                 frameCounter += 3;
                 if (frameCounter > 6)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame > 11)
                 {
                     frame = 7;
                 }
                 if (frame < 7)
                 {
                     frame = 7;
                 }
             }
             else if (type == 313)
             {
                 position.Y += height;
                 height = 54;
                 position.Y -= height;
                 position.X += width / 2;
                 width = 54;
                 position.X -= width / 2;
                 rotation += velocity.X * 0.01f;
                 frameCounter = 0;
                 frame = 11;
             }
             else if (type == 398)
             {
                 if ((double)velocity.X > 0.5)
                 {
                     spriteDirection = 1;
                 }
                 else if ((double)velocity.X < -0.5)
                 {
                     spriteDirection = -1;
                 }
                 frameCounter++;
                 if (frameCounter > 1)
                 {
                     frame++;
                     frameCounter = 0;
                 }
                 if (frame < 6 || frame > 9)
                 {
                     frame = 6;
                 }
                 rotation = velocity.X * 0.1f;
             }
             else if (spriteDirection == -1)
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X);
             }
             else
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 3.14f;
             }
             if (!flag6 && type != 499 && type != 765 && type != 816 && type != 821 && type != 825 && type != 859 && type != 881 && type != 884 && type != 890 && type != 891 && type != 900 && type != 934 && type != 958 && type != 959 && type != 960 && type != 994 && type != 998 && type != 1003 && type != 1004)
             {
                 if (type == 899)
                 {
                     int num103 = 6;
                     if (Main.rand.Next(4) == 0)
                     {
                         num103 = 31;
                     }
                     int num104 = Dust.NewDust(base.Center + new Vector2(-8f, 0f) - velocity * 0.25f, 15, 15, num103, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 0, default(Color), 1.3f);
                     Main.dust[num104].velocity.X = Main.dust[num104].velocity.X * 0.2f;
                     Main.dust[num104].velocity.Y = Main.dust[num104].velocity.Y * 0.2f - 0.2f;
                     Main.dust[num104].noGravity = true;
                 }
                 else if (type == 897)
                 {
                     int num105 = 6;
                     if (Main.rand.Next(4) == 0)
                     {
                         num105 = 31;
                     }
                     int num106 = Dust.NewDust(base.Center + new Vector2(-8f, -8f) - velocity * 0.25f, 15, 15, num105, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 0, default(Color), 1.3f);
                     Main.dust[num106].velocity.X = Main.dust[num106].velocity.X * 0.2f;
                     Main.dust[num106].velocity.Y = Main.dust[num106].velocity.Y * 0.2f - 0.2f;
                     Main.dust[num106].noGravity = true;
                 }
                 else if (type == 875)
                 {
                     if (Main.rand.Next(3) == 0)
                     {
                         Gore.NewGorePerfect(base.Center + new Vector2(-10f + (float)Main.rand.Next(-20, 20) * 0.5f, -10f + (float)Main.rand.Next(-20, 20) * 0.5f), velocity * 0.1f, 1225, 0.5f + Main.rand.NextFloat() * 1f);
                         Vector2 vector9 = Main.rand.NextVector2CircularEdge(2f, 2f) + velocity * -0.5f;
                         vector9 *= 0.5f;
                         int num107 = Dust.NewDust(base.Center - velocity * 1.5f - new Vector2(7f, 7f), 15, 15, 226, vector9.X, vector9.Y, 0, default(Color), 0.65f);
                         Main.dust[num107].noGravity = true;
                     }
                 }
                 else if (type == 860)
                 {
                     int num108 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) - 4f, position.Y + (float)(height / 2) - 4f) + velocity, 8, 8, 27, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f);
                     Main.dust[num108].velocity.X = Main.dust[num108].velocity.X * 0.2f;
                     Main.dust[num108].velocity.Y = Main.dust[num108].velocity.Y * 0.2f - 0.2f;
                     Main.dust[num108].velocity += new Vector2((float)Main.rand.Next(-10, 10) * 0.4f, (float)Main.rand.Next(-10, 10) * 0.4f) * 0.5f;
                     Main.dust[num108].noGravity = true;
                 }
                 else if (type == 858)
                 {
                     int num109 = 6;
                     if (Main.rand.Next(4) == 0)
                     {
                         num109 = 31;
                     }
                     int num110 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) - 4f, position.Y + (float)(height / 2) - 4f) - velocity, 10, 10, num109, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 0, default(Color), 1.3f);
                     Main.dust[num110].velocity.X = Main.dust[num110].velocity.X * 0.2f;
                     Main.dust[num110].velocity.Y = Main.dust[num110].velocity.Y * 0.2f - 0.2f;
                     Main.dust[num110].noGravity = true;
                 }
                 else if (type == 112)
                 {
                     int num111 = 6;
                     if (Main.rand.Next(4) == 0)
                     {
                         num111 = 31;
                     }
                     int num112 = Dust.NewDust(base.Center + new Vector2(12 * spriteDirection, 4f).RotatedBy(rotation) + new Vector2(-5f, -5f), 10, 10, num111, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 0, default(Color), 1.3f);
                     Main.dust[num112].velocity.X = Main.dust[num112].velocity.X * 0.2f;
                     Main.dust[num112].velocity.Y = Main.dust[num112].velocity.Y * 0.2f - 0.2f;
                     Main.dust[num112].noGravity = true;
                 }
                 else if (type == 854)
                 {
                     if (Main.rand.Next(6) == 0)
                     {
                         Vector2 vector10 = base.Center / 16f;
                         int i2 = (int)vector10.X;
                         int num113 = (int)vector10.Y;
                         Tile tileSafely = Framing.GetTileSafely(i2, num113 + 1);
                         if (!WorldGen.SolidTile(tileSafely) && tileSafely.liquid == 0)
{
                             Gore gore = Gore.NewGorePerfect(base.Center + new Vector2((float)Main.rand.Next(-30, 30) * 0.5f, (float)Main.rand.Next(-30, 30) * 0.5f), velocity * -0.2f, 910);
                             gore.Frame.CurrentColumn = 0;
                             gore.timeLeft = 1;
                         }
                     }
                 }
                 else if (type != 398 && type != 390 && type != 391 && type != 392 && type != 127 && type != 200 && type != 208 && type != 210 && type != 236 && type != 266 && type != 268 && type != 269 && type != 313 && type != 314 && type != 319 && type != 324 && type != 334 && type != 353)
                 {
                     int num114 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) - 4f, position.Y + (float)(height / 2) - 4f) - velocity, 8, 8, 16, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.7f);
                     Main.dust[num114].velocity.X = Main.dust[num114].velocity.X * 0.2f;
                     Main.dust[num114].velocity.Y = Main.dust[num114].velocity.Y * 0.2f;
                     Main.dust[num114].noGravity = true;
                 }
             }
         }
         else
         {
             if (flag6)
             {
                 float num115 = 40 * minionPos;
                 int num116 = 30;
                 int num117 = 60;
                 localAI[0] -= 1f;
                 if (localAI[0] < 0f)
                 {
                     localAI[0] = 0f;
                 }
                 if (ai[1] > 0f)
                 {
                     ai[1] -= 1f;
                 }
                 else
                 {
                     float num118 = position.X;
                     float num119 = position.Y;
                     float num120 = 100000f;
                     float num121 = num120;
                     int num122 = -1;
                     float num123 = 20f;
                     NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
                     if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
                     {
                         float num124 = ownerMinionAttackTargetNPC.position.X + (float)(ownerMinionAttackTargetNPC.width / 2);
                         float num125 = ownerMinionAttackTargetNPC.position.Y + (float)(ownerMinionAttackTargetNPC.height / 2);
                         float num126 = Math.Abs(position.X + (float)(width / 2) - num124) + Math.Abs(position.Y + (float)(height / 2) - num125);
                         if (num126 < num120)
{
                             if (num122 == -1 && num126 <= num121)
{
                                 num121 = num126;
                                 num118 = num124;
                                 num119 = num125;
                             }
                             if (Collision.CanHit(position, width, height, ownerMinionAttackTargetNPC.position, ownerMinionAttackTargetNPC.width, ownerMinionAttackTargetNPC.height))
{
                                 num120 = num126;
                                 num118 = num124;
                                 num119 = num125;
                                 num122 = ownerMinionAttackTargetNPC.whoAmI;
                             }
                         }
                     }
                     if (num122 == -1)
                     {
                         for (int num127 = 0; num127 < 200; num127++)
{
                             if (!Main.npc[num127].CanBeChasedBy(this))
{
                                 continue;
                             }
                             float num128 = Main.npc[num127].position.X + (float)(Main.npc[num127].width / 2);
                             float num129 = Main.npc[num127].position.Y + (float)(Main.npc[num127].height / 2);
                             float num130 = Math.Abs(position.X + (float)(width / 2) - num128) + Math.Abs(position.Y + (float)(height / 2) - num129);
                             if (num130 < num120)
{
                                 if (num122 == -1 && num130 <= num121)
{
                                     num121 = num130;
                                     num118 = num128 + Main.npc[num127].velocity.X * num123;
                                     num119 = num129 + Main.npc[num127].velocity.Y * num123;
                                 }
                                 if (Collision.CanHit(position, width, height, Main.npc[num127].position, Main.npc[num127].width, Main.npc[num127].height))
{
                                     num120 = num130;
                                     num118 = num128 + Main.npc[num127].velocity.X * num123;
                                     num119 = num129 + Main.npc[num127].velocity.Y * num123;
                                     num122 = num127;
                                 }
                             }
                         }
                     }
                     if (num122 == -1 && num121 < num120)
                     {
                         num120 = num121;
                     }
                     float num131 = 400f;
                     if ((double)position.Y > Main.worldSurface * 16.0)
                     {
                         num131 = 200f;
                     }
                     if (num120 < num131 + num115 && num122 == -1)
                     {
                         float num132 = num118 - (position.X + (float)(width / 2));
                         if (num132 < -5f)
{
                             flag2 = true;
                             flag3 = false;
                         }
                         else if (num132 > 5f)
{
                             flag3 = true;
                             flag2 = false;
                         }
                     }
                     else if (num122 >= 0 && num120 < 800f + num115)
                     {
                         localAI[0] = num117;
                         float num133 = num118 - (position.X + (float)(width / 2));
                         if (num133 > 450f || num133 < -450f)
{
                             if (num133 < -50f)
{
                                 flag2 = true;
                                 flag3 = false;
                             }
                             else if (num133 > 50f)
{
                                 flag3 = true;
                                 flag2 = false;
                             }
                         }
                         else if (owner == Main.myPlayer)
{
                             ai[1] = num116;
                             Vector2 vector11 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)(height / 2) - 8f);
                             float num134 = num118 - vector11.X + (float)Main.rand.Next(-20, 21);
                             float num135 = Math.Abs(num134) * 0.1f;
                             num135 = num135 * (float)Main.rand.Next(0, 100) * 0.001f;
                             float num136 = num119 - vector11.Y + (float)Main.rand.Next(-20, 21) - num135;
                             float num137 = (float)Math.Sqrt(num134 * num134 + num136 * num136);
                             num137 = 11f / num137;
                             num134 *= num137;
                             num136 *= num137;
                             int num138 = damage;
                             int num139 = 195;
                             int num140 = NewProjectile(GetProjectileSource_FromThis(), vector11.X, vector11.Y, num134, num136, num139, num138, knockBack, Main.myPlayer);
                             Main.projectile[num140].timeLeft = 300;
                             if (num134 < 0f)
{
                                 direction = -1;
                             }
                             if (num134 > 0f)
{
                                 direction = 1;
                             }
                             netUpdate = true;
                         }
                     }
                 }
             }
             bool flag13 = false;
             Vector2 vector12 = Vector2.Zero;
             bool flag14 = false;
             if (type == 266 || (type >= 390 && type <= 392))
             {
                 float num141 = 40 * minionPos;
                 int num142 = 60;
                 localAI[0] -= 1f;
                 if (localAI[0] < 0f)
                 {
                     localAI[0] = 0f;
                 }
                 if (ai[1] > 0f)
                 {
                     ai[1] -= 1f;
                 }
                 else
                 {
                     float num143 = position.X;
                     float num144 = position.Y;
                     float num145 = 100000f;
                     float num146 = num145;
                     int num147 = -1;
                     NPC ownerMinionAttackTargetNPC2 = OwnerMinionAttackTargetNPC;
                     if (ownerMinionAttackTargetNPC2 != null && ownerMinionAttackTargetNPC2.CanBeChasedBy(this))
                     {
                         float x = ownerMinionAttackTargetNPC2.Center.X;
                         float y = ownerMinionAttackTargetNPC2.Center.Y;
                         float num148 = Math.Abs(position.X + (float)(width / 2) - x) + Math.Abs(position.Y + (float)(height / 2) - y);
                         if (num148 < num145)
{
                             if (num147 == -1 && num148 <= num146)
{
                                 num146 = num148;
                                 num143 = x;
                                 num144 = y;
                             }
                             if (Collision.CanHit(position, width, height, ownerMinionAttackTargetNPC2.position, ownerMinionAttackTargetNPC2.width, ownerMinionAttackTargetNPC2.height))
{
                                 num145 = num148;
                                 num143 = x;
                                 num144 = y;
                                 num147 = ownerMinionAttackTargetNPC2.whoAmI;
                             }
                         }
                     }
                     if (num147 == -1)
                     {
                         for (int num149 = 0; num149 < 200; num149++)
{
                             if (!Main.npc[num149].CanBeChasedBy(this))
{
                                 continue;
                             }
                             float num150 = Main.npc[num149].position.X + (float)(Main.npc[num149].width / 2);
                             float num151 = Main.npc[num149].position.Y + (float)(Main.npc[num149].height / 2);
                             float num152 = Math.Abs(position.X + (float)(width / 2) - num150) + Math.Abs(position.Y + (float)(height / 2) - num151);
                             if (num152 < num145)
{
                                 if (num147 == -1 && num152 <= num146)
{
                                     num146 = num152;
                                     num143 = num150;
                                     num144 = num151;
                                 }
                                 if (Collision.CanHit(position, width, height, Main.npc[num149].position, Main.npc[num149].width, Main.npc[num149].height))
{
                                     num145 = num152;
                                     num143 = num150;
                                     num144 = num151;
                                     num147 = num149;
                                 }
                             }
                         }
                     }
                     if (type >= 390 && type <= 392 && !Collision.SolidCollision(position, width, height))
                     {
                         tileCollide = true;
                     }
                     if (num147 == -1 && num146 < num145)
                     {
                         num145 = num146;
                     }
                     else if (num147 >= 0)
                     {
                         flag13 = true;
                         vector12 = new Vector2(num143, num144) - base.Center;
                         if (type >= 390 && type <= 392)
{
                             if (Main.npc[num147].position.Y > position.Y + (float)height)
{
                                 int num153 = (int)(base.Center.X / 16f);
                                 int num154 = (int)((position.Y + (float)height + 1f) / 16f);
                                 if (Main.tile[num153, num154] != null && Main.tile[num153, num154].active() && TileID.Sets.Platforms[Main.tile[num153, num154].type])
{
                                     tileCollide = false;
                                 }
                             }
                             Rectangle rectangle = new Rectangle((int)position.X, (int)position.Y, width, height);
                             Rectangle value = new Rectangle((int)Main.npc[num147].position.X, (int)Main.npc[num147].position.Y, Main.npc[num147].width, Main.npc[num147].height);
                             int num155 = 10;
                             value.X -= num155;
                             value.Y -= num155;
                             value.Width += num155 * 2;
                             value.Height += num155 * 2;
                             if (rectangle.Intersects(value))
{
                                 flag14 = true;
                                 Vector2 vector13 = Main.npc[num147].Center - base.Center;
                                 if (velocity.Y > 0f && vector13.Y < 0f)
{
                                     velocity.Y *= 0.5f;
                                 }
                                 if (velocity.Y < 0f && vector13.Y > 0f)
{
                                     velocity.Y *= 0.5f;
                                 }
                                 if (velocity.X > 0f && vector13.X < 0f)
{
                                     velocity.X *= 0.5f;
                                 }
                                 if (velocity.X < 0f && vector13.X > 0f)
{
                                     velocity.X *= 0.5f;
                                 }
                                 if (vector13.Length() > 14f)
{
                                     vector13.Normalize();
                                     vector13 *= 14f;
                                 }
                                 rotation = (rotation * 5f + vector13.ToRotation() + (float)Math.PI / 2f) / 6f;
                                 velocity = (velocity * 9f + vector13) / 10f;
                                 for (int num156 = 0; num156 < 1000; num156++)
{
                                     if (whoAmI != num156 && owner == Main.projectile[num156].owner && Main.projectile[num156].type >= 390 && Main.projectile[num156].type <= 392 && (Main.projectile[num156].Center - base.Center).Length() < 15f)
{
                                         float num157 = 0.5f;
                                         if (base.Center.Y > Main.projectile[num156].Center.Y)
{
                                             Main.projectile[num156].velocity.Y -= num157;
                                             velocity.Y += num157;
                                         }
                                         else
{
                                             Main.projectile[num156].velocity.Y += num157;
                                             velocity.Y -= num157;
                                         }
                                         if (base.Center.X > Main.projectile[num156].Center.X)
{
                                             velocity.X += num157;
                                             Main.projectile[num156].velocity.X -= num157;
                                         }
                                         else
{
                                             velocity.X -= num157;
                                             Main.projectile[num156].velocity.Y += num157;
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     float num158 = 300f;
                     if ((double)position.Y > Main.worldSurface * 16.0)
                     {
                         num158 = 150f;
                     }
                     if (type >= 390 && type <= 392)
                     {
                         num158 = 500f;
                         if ((double)position.Y > Main.worldSurface * 16.0)
{
                             num158 = 250f;
                         }
                     }
                     if (num145 < num158 + num141 && num147 == -1)
                     {
                         float num159 = num143 - (position.X + (float)(width / 2));
                         if (num159 < -5f)
{
                             flag2 = true;
                             flag3 = false;
                         }
                         else if (num159 > 5f)
{
                             flag3 = true;
                             flag2 = false;
                         }
                     }
                     bool flag15 = false;
                     if (type >= 390 && type <= 392 && localAI[1] > 0f)
                     {
                         flag15 = true;
                         localAI[1] -= 1f;
                     }
                     if (num147 >= 0 && num145 < 800f + num141)
                     {
                         friendly = true;
                         localAI[0] = num142;
                         float num160 = num143 - (position.X + (float)(width / 2));
                         if (num160 < -10f)
{
                             flag2 = true;
                             flag3 = false;
                         }
                         else if (num160 > 10f)
{
                             flag3 = true;
                             flag2 = false;
                         }
                         if (num144 < base.Center.Y - 100f && num160 > -50f && num160 < 50f && velocity.Y == 0f)
{
                             float num161 = Math.Abs(num144 - base.Center.Y);
                             if (num161 < 120f)
{
                                 velocity.Y = -10f;
                             }
                             else if (num161 < 210f)
{
                                 velocity.Y = -13f;
                             }
                             else if (num161 < 270f)
{
                                 velocity.Y = -15f;
                             }
                             else if (num161 < 310f)
{
                                 velocity.Y = -17f;
                             }
                             else if (num161 < 380f)
{
                                 velocity.Y = -18f;
                             }
                         }
                         if (flag15)
{
                             friendly = false;
                             if (velocity.X < 0f)
{
                                 flag2 = true;
                             }
                             else if (velocity.X > 0f)
{
                                 flag3 = true;
                             }
                         }
                     }
                     else
                     {
                         friendly = false;
                     }
                 }
             }
             if (ai[1] != 0f)
             {
                 flag2 = false;
                 flag3 = false;
             }
             else if (flag6 && localAI[0] == 0f)
             {
                 direction = Main.player[owner].direction;
             }
             else if (type >= 390 && type <= 392)
             {
                 int num162 = (int)(base.Center.X / 16f);
                 int num163 = (int)(base.Center.Y / 16f);
                 if (Main.tile[num162, num163] != null && Main.tile[num162, num163].wall > 0)
                 {
                     flag2 = (flag3 = false);
                 }
             }
             if (type == 127)
             {
                 if ((double)rotation > -0.1 && (double)rotation < 0.1)
                 {
                     rotation = 0f;
                 }
                 else if (rotation < 0f)
                 {
                     rotation += 0.1f;
                 }
                 else
                 {
                     rotation -= 0.1f;
                 }
             }
             else if (type != 313 && !flag14)
             {
                 rotation = 0f;
             }
             if (type < 390 || type > 392)
             {
                 tileCollide = true;
             }
             float num164 = 0.08f;
             float num165 = 6.5f;
             if (type == 127)
             {
                 num165 = 2f;
                 num164 = 0.04f;
             }
             if (type == 112)
             {
                 num165 = 6f;
                 num164 = 0.06f;
             }
             if (type == 334)
             {
                 num165 = 8f;
                 num164 = 0.08f;
             }
             if (type == 268)
             {
                 num165 = 8f;
                 num164 = 0.4f;
             }
             if (type == 324)
             {
                 num164 = 0.1f;
                 num165 = 3f;
             }
             if (type == 858)
             {
                 num164 = 0.3f;
                 num165 = 7f;
             }
             if (flag6 || type == 266 || (type >= 390 && type <= 392) || type == 816 || type == 821 || type == 825 || type == 859 || type == 860 || type == 881 || type == 884 || type == 890 || type == 891 || type == 897 || type == 899 || type == 900 || type == 934 || type == 956 || type == 958 || type == 959 || type == 960 || type == 994 || type == 998 || type == 1003 || type == 1004)
             {
                 num165 = 6f;
                 num164 = 0.2f;
                 if (num165 < Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y))
                 {
                     num165 = Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y);
                     num164 = 0.3f;
                 }
                 if (flag6)
                 {
                     num164 *= 2f;
                 }
             }
             if (type == 875)
             {
                 num165 = 7f;
                 num164 = 0.25f;
                 if (num165 < Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y))
                 {
                     num165 = Math.Abs(Main.player[owner].velocity.X) + Math.Abs(Main.player[owner].velocity.Y);
                     num164 = 0.35f;
                 }
             }
             if (type >= 390 && type <= 392)
             {
                 num164 *= 2f;
             }
             if (flag7)
             {
                 num165 = 6f;
             }
             if (flag2)
             {
                 if ((double)velocity.X > -3.5)
                 {
                     velocity.X -= num164;
                 }
                 else
                 {
                     velocity.X -= num164 * 0.25f;
                 }
             }
             else if (flag3)
             {
                 if ((double)velocity.X < 3.5)
                 {
                     velocity.X += num164;
                 }
                 else
                 {
                     velocity.X += num164 * 0.25f;
                 }
             }
             else
             {
                 velocity.X *= 0.9f;
                 if (velocity.X >= 0f - num164 && velocity.X <= num164)
                 {
                     velocity.X = 0f;
                 }
             }
             if (type == 208)
             {
                 velocity.X *= 0.95f;
                 if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                 {
                     velocity.X = 0f;
                 }
                 flag2 = false;
                 flag3 = false;
             }
             if (flag2 || flag3)
             {
                 int num166 = (int)(position.X + (float)(width / 2)) / 16;
                 int j2 = (int)(position.Y + (float)(height / 2)) / 16;
                 if (type == 236)
                 {
                     num166 += direction;
                 }
                 if (flag2)
                 {
                     num166--;
                 }
                 if (flag3)
                 {
                     num166++;
                 }
                 num166 += (int)velocity.X;
                 if (WorldGen.SolidTile(num166, j2))
                 {
                     flag5 = true;
                 }
             }
             if (Main.player[owner].position.Y + (float)Main.player[owner].height - 8f > position.Y + (float)height)
             {
                 flag4 = true;
             }
             if (type == 268 && frameCounter < 10)
             {
                 flag5 = false;
             }
             if (type == 860 && velocity.X != 0f)
             {
                 flag5 = true;
             }
             if ((type == 881 || type == 934) && velocity.X != 0f)
             {
                 flag5 = true;
             }
             Collision.StepUp(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY);
             if (velocity.Y == 0f || type == 200)
             {
                 if (!flag4 && (velocity.X < 0f || velocity.X > 0f))
                 {
                     int num167 = (int)(position.X + (float)(width / 2)) / 16;
                     int j3 = (int)(position.Y + (float)(height / 2)) / 16 + 1;
                     if (flag2)
                     {
                         num167--;
                     }
                     if (flag3)
                     {
                         num167++;
                     }
                     WorldGen.SolidTile(num167, j3);
                 }
                 if (flag5)
                 {
                     int num168 = (int)(position.X + (float)(width / 2)) / 16;
                     int num169 = (int)(position.Y + (float)height) / 16;
                     if (WorldGen.SolidTileAllowBottomSlope(num168, num169) || Main.tile[num168, num169].halfBrick() || Main.tile[num168, num169].slope() > 0 || type == 200)
                     {
                         if (type == 200)
{
                             velocity.Y = -3.1f;
                         }
                         else
{
                             try
{
                                 num168 = (int)(position.X + (float)(width / 2)) / 16;
                                 num169 = (int)(position.Y + (float)(height / 2)) / 16;
                                 if (flag2)
{
                                     num168--;
                                 }
                                 if (flag3)
{
                                     num168++;
                                 }
                                 num168 += (int)velocity.X;
                                 if (!WorldGen.SolidTile(num168, num169 - 1) && !WorldGen.SolidTile(num168, num169 - 2))
{
                                     velocity.Y = -5.1f;
                                 }
                                 else if (!WorldGen.SolidTile(num168, num169 - 2))
{
                                     velocity.Y = -7.1f;
                                 }
                                 else if (WorldGen.SolidTile(num168, num169 - 5))
{
                                     velocity.Y = -11.1f;
                                 }
                                 else if (WorldGen.SolidTile(num168, num169 - 4))
{
                                     velocity.Y = -10.1f;
                                 }
                                 else
{
                                     velocity.Y = -9.1f;
                                 }
                             }
                             catch
{
                                 velocity.Y = -9.1f;
                             }
                         }
                         if (type == 127)
{
                             ai[0] = 1f;
                         }
                     }
                 }
                 else if (type == 266 && (flag2 || flag3))
                 {
                     velocity.Y -= 6f;
                 }
             }
             if (velocity.X > num165)
             {
                 velocity.X = num165;
             }
             if (velocity.X < 0f - num165)
             {
                 velocity.X = 0f - num165;
             }
             if (velocity.X < 0f)
             {
                 direction = -1;
             }
             if (velocity.X > 0f)
             {
                 direction = 1;
             }
             if (velocity.X > num164 && flag3)
             {
                 direction = 1;
             }
             if (velocity.X < 0f - num164 && flag2)
             {
                 direction = -1;
             }
             if (type != 313)
             {
                 if (direction == -1)
                 {
                     spriteDirection = 1;
                 }
                 if (direction == 1)
                 {
                     spriteDirection = -1;
                 }
             }
             if (type == 398 || type == 958 || type == 960 || type == 956 || type == 959 || type == 994)
             {
                 spriteDirection = direction;
             }
             bool flag16 = position.X - oldPosition.X == 0f;
             if (type == 956)
             {
                 if (alpha > 0)
                 {
                     int num170 = Dust.NewDust(position, width, height, 6, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                     Main.dust[num170].velocity.X += Main.rand.NextFloat() - 0.5f;
                     Main.dust[num170].velocity.Y += (Main.rand.NextFloat() + 0.5f) * -1f;
                     if (Main.rand.Next(3) != 0)
                     {
                         Main.dust[num170].noGravity = true;
                     }
                     alpha -= 5;
                     if (alpha < 0)
                     {
                         alpha = 0;
                     }
                 }
                 if (velocity.Y != 0f)
                 {
                     frame = 10;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num171 = velocity.Length();
                     frameCounter += (int)num171;
                     if (frameCounter > 7)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 1 || frame > 9)
                     {
                         frame = 1;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 958)
             {
                 if (velocity.Y != 0f)
                 {
                     localAI[0] = 0f;
                     frame = 4;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     localAI[0] += 1f;
                     if (localAI[0] > 200f)
                     {
                         frame = 1 + (int)(localAI[0] - 200f) / 6;
                         if (localAI[0] >= 218f)
{
                             frame = 0;
                             localAI[0] = Main.rand.Next(100);
                         }
                     }
                     else
                     {
                         frame = 0;
                     }
                 }
                 else
                 {
                     localAI[0] = 0f;
                     float num172 = velocity.Length();
                     frameCounter += (int)num172;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 5 || frame > 12)
                     {
                         frame = 5;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 959)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = ((velocity.Y > 0f) ? 10 : 9);
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num173 = velocity.Length();
                     frameCounter += (int)num173;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 1 || frame > 8)
                     {
                         frame = 1;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 998)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num174 = velocity.Length();
                     frameCounter += (int)num174;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 0 || frame > 5)
                     {
                         frame = 0;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 1003)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num175 = velocity.Length();
                     frameCounter += (int)num175;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 2 || frame > 11)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 1004)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num176 = velocity.Length();
                     frameCounter += (int)num176;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 2 || frame > 9)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 994)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 4;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frameCounter++;
                     if (frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 3)
                     {
                         frame = 0;
                     }
                 }
                 else
                 {
                     float num177 = velocity.Length();
                     frameCounter += (int)num177;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 5 || frame > 12)
                     {
                         frame = 5;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 960)
             {
                 _ = Main.player[owner];
                 if (velocity.Y != 0f)
                 {
                     localAI[0] = 0f;
                     localAI[1] = 0f;
                     frameCounter = 0;
                     frame = 4;
                 }
                 else if (flag16)
                 {
                     if (!flag7)
                     {
                         spriteDirection = 1;
                         if (Main.player[owner].Center.X < base.Center.X)
{
                             spriteDirection = -1;
                         }
                     }
                     if (frame >= 5 && frame < 12)
                     {
                         frameCounter++;
                         if (frameCounter > 3)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 12)
{
                             frame = 0;
                         }
                     }
                     else if (Chester_IsAnyPlayerTrackingThisProjectile())
                     {
                         if (localAI[0] == 0f)
{
                             if (localAI[1] == 0f)
{
                                 localAI[1] = 1f;
                                 frameCounter = 0;
                             }
                             frame = 13;
                             frameCounter++;
                             if (frameCounter > 6)
{
                                 localAI[0] = 1f;
                                 frame = 14;
                                 frameCounter = 0;
                             }
                         }
                         else
{
                             frameCounter++;
                             if (frameCounter > 6)
{
                                 frame++;
                                 if (frame > 18)
{
                                     frame = 14;
                                 }
                                 frameCounter = 0;
                             }
                         }
                     }
                     else
                     {
                         localAI[0] = 0f;
                         if (localAI[1] == 1f)
{
                             localAI[1] = 0f;
                             frameCounter = 0;
                         }
                         if (frame >= 12 && frame <= 19)
{
                             frame = 19;
                             frameCounter++;
                             if (frameCounter > 6)
{
                                 frame = 0;
                                 frameCounter = 0;
                             }
                         }
                         else
{
                             frameCounter++;
                             if (frameCounter >= 24)
{
                                 frameCounter = 0;
                             }
                             frame = frameCounter / 6;
                         }
                     }
                 }
                 else
                 {
                     localAI[0] = 0f;
                     localAI[1] = 0f;
                     float val = velocity.Length();
                     frameCounter += (int)Math.Max(2f, val);
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 5 || frame > 12)
                     {
                         frame = 5;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 816)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 4;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     if (++frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 0 || frame > 3)
                     {
                         frame = 0;
                     }
                 }
                 else
                 {
                     int num178 = 5;
                     float num179 = velocity.Length();
                     if (num179 > 4f)
                     {
                         num178 = 3;
                     }
                     else if (num179 > 2f)
                     {
                         num178 = 4;
                     }
                     if (++frameCounter > num178)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 4 || frame > 10)
                     {
                         frame = 4;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             if (type == 860)
             {
                 if (velocity.Y != 0f)
                 {
                     localAI[0] = 0f;
                     if (frame >= 5)
                     {
                         frame = 5;
                         frameCounter = 0;
                     }
                     else if (++frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                 }
                 else if (Math.Abs(velocity.X) < 1f)
                 {
                     if (localAI[0] > 800f)
                     {
                         frameCounter++;
                         if (frameCounter > 3)
{
                             frameCounter = 0;
                             frame++;
                             if (frame > 3)
{
                                 frame = 3;
                             }
                         }
                         localAI[0] += 1f;
                         if (localAI[0] > 850f)
{
                             localAI[0] = 0f;
                         }
                         if (frame == 3 && localAI[0] == 820f)
{
                             for (int num180 = 0; num180 < 3 + Main.rand.Next(3); num180++)
{
                                 int num181 = Gore.NewGore(new Vector2(position.X, base.Center.Y - 10f), Vector2.Zero, 1218);
                                 Main.gore[num181].velocity = new Vector2((float)Main.rand.Next(1, 10) * 0.3f * (float)(-spriteDirection), 0f - (2f + (float)Main.rand.Next(4) * 0.3f));
                             }
                         }
                     }
                     else if (frame == 0)
                     {
                         localAI[0] += 1f;
                         frame = 0;
                         frameCounter = 0;
                     }
                     else
                     {
                         localAI[0] = 0f;
                         if (frame > 5)
{
                             frame = 5;
                             frameCounter = 0;
                         }
                         if (++frameCounter > 4)
{
                             frame--;
                             frameCounter = 0;
                         }
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             if (type == 859)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 4;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     if (frame == 6)
                     {
                         if (++frameCounter > 5)
{
                             frame = 0;
                             frameCounter = 0;
                         }
                     }
                     else if (frame > 3)
                     {
                         frame = 6;
                         frameCounter = 0;
                     }
                     else
                     {
                         if (++frameCounter > 5)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame < 0 || frame > 3)
{
                             frame = 0;
                         }
                     }
                 }
                 else
                 {
                     float num182 = velocity.Length();
                     int num183 = 8;
                     if (num182 < 3f)
                     {
                         num183 = 4;
                     }
                     if (num182 < 1f)
                     {
                         num183 = 2;
                     }
                     frameCounter += (int)num182;
                     if (frameCounter > num183)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 5 || frame > 17)
                     {
                         frame = 5;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 858)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     frame = 0;
                 }
                 else
                 {
                     float num184 = velocity.Length();
                     frameCounter += (int)num184;
                     if (frameCounter > 3)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 2 || frame > 9)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 900)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.3f);
                     if (frame < 2)
                     {
                         frame = 2;
                         frameCounter = 0;
                     }
                     if (frameCounter > 4)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 9)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 899)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.3f);
                     if (frame < 2)
                     {
                         frame = 2;
                         frameCounter = 0;
                     }
                     if (frameCounter > 4)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 9)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 897)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.3f);
                     if (frame < 2)
                     {
                         frame = 2;
                         frameCounter = 0;
                     }
                     if (frameCounter > 4)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 7)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 891)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = Main.player[owner].direction;
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.3f);
                     if (frame < 2)
                     {
                         frame = 2;
                         frameCounter = 0;
                     }
                     if (frameCounter > 4)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 8)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 890)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     frame = 1;
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.3f);
                     if (frame < 2)
                     {
                         frame = 2;
                         frameCounter = 0;
                     }
                     if (frameCounter > 4)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 7)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 884)
             {
                 spriteDirection = direction;
                 if (velocity.Y != 0f)
                 {
                     if (velocity.Y < 0f)
                     {
                         frame = 9;
                     }
                     else
                     {
                         frame = 1;
                     }
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = 1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = -1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.5f);
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 8)
                     {
                         frame = 2;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 881 || type == 934)
             {
                 spriteDirection = 1;
                 if (Main.player[owner].Center.X < base.Center.X)
                 {
                     spriteDirection = -1;
                 }
                 if (velocity.Y > 0f)
                 {
                     frameCounter++;
                     if (frameCounter > 2)
                     {
                         frame++;
                         if (frame >= 2)
{
                             frame = 2;
                         }
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter++;
                     if (frameCounter > 2)
                     {
                         frame++;
                         if (frame >= 5)
{
                             frame = 0;
                         }
                         frameCounter = 0;
                     }
                 }
                 else if (frame == 0)
                 {
                     frame = 0;
                 }
                 else if (++frameCounter > 3)
                 {
                     frame++;
                     if (frame >= 6)
                     {
                         frame = 0;
                     }
                     frameCounter = 0;
                 }
                 if (wet && Main.player[owner].position.Y + (float)Main.player[owner].height < position.Y + (float)height && localAI[0] == 0f)
                 {
                     if (velocity.Y > -4f)
                     {
                         velocity.Y -= 0.2f;
                     }
                     if (velocity.Y > 0f)
                     {
                         velocity.Y *= 0.95f;
                     }
                 }
                 else
                 {
                     velocity.Y += 0.4f;
                 }
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 875)
             {
                 if (velocity.Y != 0f)
                 {
                     if (velocity.Y < 0f)
                     {
                         frame = 3;
                     }
                     else
                     {
                         frame = 6;
                     }
                     frameCounter = 0;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     frame = 0;
                     frameCounter = 0;
                 }
                 else
                 {
                     frameCounter += 1 + (int)Math.Abs(velocity.X * 0.75f);
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 6)
                     {
                         frame = 0;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 854)
             {
                 if (velocity.Y != 0f)
                 {
                     frame = 7;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     if (++frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 0 || frame > 3)
                     {
                         frame = 0;
                     }
                 }
                 else
                 {
                     int num185 = 3;
                     float num186 = velocity.Length();
                     if (num186 > 4f)
                     {
                         num185 = 1;
                     }
                     else if (num186 > 2f)
                     {
                         num185 = 2;
                     }
                     if (++frameCounter > num185)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 4 || frame > 12)
                     {
                         frame = 4;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 825)
             {
                 if (velocity.Y != 0f)
                 {
                     localAI[0] = 0f;
                     frame = 12;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     if (frame >= 1 && frame <= 2)
                     {
                         localAI[0] = 0f;
                         if (++frameCounter > 5)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 2)
{
                             frame = 0;
                         }
                     }
                     else if (frame >= 3 && frame <= 11)
                     {
                         localAI[0] = 0f;
                         if (++frameCounter > 5)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 11)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         if (frame == 13)
{
                             if (++frameCounter > 8)
{
                                 frame++;
                                 frameCounter = 0;
                             }
                             if (frame == 14)
{
                                 frame = 0;
                             }
                         }
                         if (frame != 0)
{
                             frame = 13;
                         }
                         else
{
                             frame = 0;
                         }
                         if (frame == 0)
{
                             localAI[0] += 1f;
                             if (localAI[0] > 300f && Main.rand.Next(50) == 0)
{
                                 switch (Main.rand.Next(2))
{
                                 case 0:
                                     frame = 1;
                                     break;
                                 case 1:
                                     frame = 3;
                                     break;
                                 }
                             }
                         }
                     }
                 }
                 else
                 {
                     localAI[0] = 0f;
                     int num187 = 3;
                     float num188 = velocity.Length();
                     if (num188 > 4f)
                     {
                         num187 = 2;
                     }
                     else if (num188 > 2f)
                     {
                         num187 = 1;
                     }
                     if (++frameCounter > num187)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame < 13)
                     {
                         frame = 13;
                     }
                     if (frame > 19)
                     {
                         frame = 14;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 821)
             {
                 if (velocity.Y != 0f)
                 {
                     localAI[0] = 0f;
                     frame = 12;
                 }
                 else if (flag16)
                 {
                     spriteDirection = -1;
                     if (Main.player[owner].Center.X < base.Center.X)
                     {
                         spriteDirection = 1;
                     }
                     localAI[0] += 1f;
                     if (localAI[0] > 400f)
                     {
                         int num189 = 7;
                         if (frame == 9)
{
                             num189 = 25;
                         }
                         if (++frameCounter > num189)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame < 5)
{
                             frame = 5;
                         }
                         if (frame > 11)
{
                             localAI[0] = 0f;
                             frame = 0;
                         }
                     }
                     else
                     {
                         if (++frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame < 0 || frame > 4)
{
                             frame = 0;
                         }
                     }
                 }
                 else
                 {
                     localAI[0] = 0f;
                     int num190 = 4;
                     float num191 = velocity.Length();
                     if (num191 > 3f)
                     {
                         num190 = 3;
                     }
                     if (num191 > 5f)
                     {
                         num190 = 2;
                     }
                     if (++frameCounter > num190)
                     {
                         frame++;
                         if (num190 == 0)
{
                             frame++;
                         }
                         frameCounter = 0;
                     }
                     if (frame < 13 || frame > 18)
                     {
                         frame = 13;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (flag6)
             {
                 if (ai[1] > 0f)
                 {
                     if (localAI[1] == 0f)
                     {
                         localAI[1] = 1f;
                         frame = 1;
                     }
                     if (frame != 0)
                     {
                         frameCounter++;
                         if (frameCounter > 4)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 4)
{
                             frame = 0;
                         }
                     }
                 }
                 else if (velocity.Y == 0f)
                 {
                     localAI[1] = 0f;
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame < 5)
{
                             frame = 5;
                         }
                         if (frame >= 11)
{
                             frame = 5;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter = 0;
                     frame = 4;
                 }
                 else if (velocity.Y > 0f)
                 {
                     frameCounter = 0;
                     frame = 4;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
                 _ = velocity;
             }
             else if (type == 268)
             {
                 if (velocity.Y == 0f)
                 {
                     if (frame > 5)
                     {
                         frameCounter = 0;
                     }
                     if (flag16)
                     {
                         int num192 = 3;
                         frameCounter++;
                         if (frameCounter < num192)
{
                             frame = 0;
                         }
                         else if (frameCounter < num192 * 2)
{
                             frame = 1;
                         }
                         else if (frameCounter < num192 * 3)
{
                             frame = 2;
                         }
                         else if (frameCounter < num192 * 4)
{
                             frame = 3;
                         }
                         else
{
                             frameCounter = num192 * 4;
                         }
                     }
                     else
                     {
                         velocity.X *= 0.8f;
                         frameCounter++;
                         int num193 = 3;
                         if (frameCounter < num193)
{
                             frame = 0;
                         }
                         else if (frameCounter < num193 * 2)
{
                             frame = 1;
                         }
                         else if (frameCounter < num193 * 3)
{
                             frame = 2;
                         }
                         else if (frameCounter < num193 * 4)
{
                             frame = 3;
                         }
                         else if (flag2 || flag3)
{
                             velocity.X *= 2f;
                             frame = 4;
                             velocity.Y = -6.1f;
                             frameCounter = 0;
                             for (int num194 = 0; num194 < 4; num194++)
{
                                 int num195 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), width, 4, 5);
                                 Main.dust[num195].velocity += velocity;
                                 Main.dust[num195].velocity *= 0.4f;
                             }
                         }
                         else
{
                             frameCounter = num193 * 4;
                         }
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter = 0;
                     frame = 5;
                 }
                 else
                 {
                     frame = 4;
                     frameCounter = 3;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 269)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         int num196 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), width, 6, 76);
                         Main.dust[num196].noGravity = true;
                         Main.dust[num196].velocity *= 0.3f;
                         Main.dust[num196].noLight = true;
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 3)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 2;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 313)
             {
                 int i3 = (int)(base.Center.X / 16f);
                 int num197 = (int)(base.Center.Y / 16f);
                 int num198 = 0;
                 Tile tileSafely2 = Framing.GetTileSafely(i3, num197);
                 Tile tileSafely3 = Framing.GetTileSafely(i3, num197 - 1);
                 Tile tileSafely4 = Framing.GetTileSafely(i3, num197 + 1);
                 if (tileSafely2.wall > 0)
                 {
                     num198++;
                 }
                 if (tileSafely3.wall > 0)
                 {
                     num198++;
                 }
                 if (tileSafely4.wall > 0)
                 {
                     num198++;
                 }
                 if (num198 > 1)
                 {
                     position.Y += height;
                     height = 34;
                     position.Y -= height;
                     position.X += width / 2;
                     width = 34;
                     position.X -= width / 2;
                     Vector2 vector14 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                     float num199 = Main.player[owner].Center.X - vector14.X;
                     float num200 = Main.player[owner].Center.Y - vector14.Y;
                     float num201 = (float)Math.Sqrt(num199 * num199 + num200 * num200);
                     float num202 = 4f / num201;
                     num199 *= num202;
                     num200 *= num202;
                     if (num201 < 120f)
                     {
                         velocity.X *= 0.9f;
                         velocity.Y *= 0.9f;
                         if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < 0.1)
{
                             velocity *= 0f;
                         }
                     }
                     else
                     {
                         velocity.X = (velocity.X * 9f + num199) / 10f;
                         velocity.Y = (velocity.Y * 9f + num200) / 10f;
                     }
                     if (num201 >= 120f)
                     {
                         spriteDirection = direction;
                         rotation = (float)Math.Atan2(velocity.Y * (float)(-direction), velocity.X * (float)(-direction));
                     }
                     frameCounter += (int)(Math.Abs(velocity.X) + Math.Abs(velocity.Y));
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 10)
                     {
                         frame = 5;
                     }
                     if (frame < 5)
                     {
                         frame = 10;
                     }
                 }
                 else
                 {
                     rotation = 0f;
                     if (direction == -1)
                     {
                         spriteDirection = 1;
                     }
                     if (direction == 1)
                     {
                         spriteDirection = -1;
                     }
                     position.Y += height;
                     height = 30;
                     position.Y -= height;
                     position.X += width / 2;
                     width = 30;
                     position.X -= width / 2;
                     if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                     {
                         if (flag16)
{
                             frame = 0;
                             frameCounter = 0;
                         }
                         else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
{
                             frameCounter += (int)Math.Abs(velocity.X);
                             frameCounter++;
                             if (frameCounter > 6)
{
                                 frame++;
                                 frameCounter = 0;
                             }
                             if (frame > 3)
{
                                 frame = 0;
                             }
                         }
                         else
{
                             frame = 0;
                             frameCounter = 0;
                         }
                     }
                     else
                     {
                         frameCounter = 0;
                         frame = 4;
                     }
                     velocity.Y += 0.4f;
                     if (velocity.Y > 10f)
                     {
                         velocity.Y = 10f;
                     }
                 }
             }
             else if (type >= 390 && type <= 392)
             {
                 int i4 = (int)(base.Center.X / 16f);
                 int num203 = (int)(base.Center.Y / 16f);
                 int num204 = 0;
                 Tile tileSafely5 = Framing.GetTileSafely(i4, num203);
                 Tile tileSafely6 = Framing.GetTileSafely(i4, num203 - 1);
                 Tile tileSafely7 = Framing.GetTileSafely(i4, num203 + 1);
                 if (tileSafely5.wall > 0)
                 {
                     num204++;
                 }
                 if (tileSafely6.wall > 0)
                 {
                     num204++;
                 }
                 if (tileSafely7.wall > 0)
                 {
                     num204++;
                 }
                 if (num204 > 1)
                 {
                     position.Y += height;
                     height = 34;
                     position.Y -= height;
                     position.X += width / 2;
                     width = 34;
                     position.X -= width / 2;
                     float num205 = 9f;
                     float num206 = 40 * (minionPos + 1);
                     Vector2 v11 = Main.player[owner].Center - base.Center;
                     if (flag13)
                     {
                         v11 = vector12;
                         num206 = 10f;
                     }
                     else if (!Collision.CanHitLine(base.Center, 1, 1, Main.player[owner].Center, 1, 1))
                     {
                         ai[0] = 1f;
                     }
                     if (v11.Length() < num206)
                     {
                         velocity *= 0.9f;
                         if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < 0.1)
{
                             velocity *= 0f;
                         }
                     }
                     else if (v11.Length() < 800f || !flag13)
                     {
                         velocity = (velocity * 9f + v11.SafeNormalize(Vector2.Zero) * num205) / 10f;
                     }
                     if (v11.Length() >= num206)
                     {
                         spriteDirection = direction;
                         rotation = velocity.ToRotation() + (float)Math.PI / 2f;
                     }
                     else
                     {
                         rotation = v11.ToRotation() + (float)Math.PI / 2f;
                     }
                     frameCounter += (int)(Math.Abs(velocity.X) + Math.Abs(velocity.Y));
                     if (frameCounter > 5)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 7)
                     {
                         frame = 4;
                     }
                     if (frame < 4)
                     {
                         frame = 7;
                     }
                 }
                 else
                 {
                     if (!flag14)
                     {
                         rotation = 0f;
                     }
                     if (direction == -1)
                     {
                         spriteDirection = 1;
                     }
                     if (direction == 1)
                     {
                         spriteDirection = -1;
                     }
                     position.Y += height;
                     height = 30;
                     position.Y -= height;
                     position.X += width / 2;
                     width = 30;
                     position.X -= width / 2;
                     if (!flag13 && !Collision.CanHitLine(base.Center, 1, 1, Main.player[owner].Center, 1, 1))
                     {
                         ai[0] = 1f;
                     }
                     if (!flag14 && frame >= 4 && frame <= 7)
                     {
                         Vector2 vector15 = Main.player[owner].Center - base.Center;
                         if (flag13)
{
                             vector15 = vector12;
                         }
                         float num207 = 0f - vector15.Y;
                         if (!(vector15.Y > 0f))
{
                             if (num207 < 120f)
{
                                 velocity.Y = -10f;
                             }
                             else if (num207 < 210f)
{
                                 velocity.Y = -13f;
                             }
                             else if (num207 < 270f)
{
                                 velocity.Y = -15f;
                             }
                             else if (num207 < 310f)
{
                                 velocity.Y = -17f;
                             }
                             else if (num207 < 380f)
{
                                 velocity.Y = -18f;
                             }
                         }
                     }
                     if (flag14)
                     {
                         frameCounter++;
                         if (frameCounter > 3)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 8)
{
                             frame = 4;
                         }
                         if (frame <= 3)
{
                             frame = 7;
                         }
                     }
                     else if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                     {
                         if (flag16)
{
                             frame = 0;
                             frameCounter = 0;
                         }
                         else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
{
                             frameCounter += (int)Math.Abs(velocity.X);
                             frameCounter++;
                             if (frameCounter > 5)
{
                                 frame++;
                                 frameCounter = 0;
                             }
                             if (frame > 2)
{
                                 frame = 0;
                             }
                         }
                         else
{
                             frame = 0;
                             frameCounter = 0;
                         }
                     }
                     else
                     {
                         frameCounter = 0;
                         frame = 3;
                     }
                     velocity.Y += 0.4f;
                     if (velocity.Y > 10f)
                     {
                         velocity.Y = 10f;
                     }
                 }
             }
             else if (type == 314)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 6)
{
                             frame = 1;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 7;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 319)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 8)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 5)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 236)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         if (frame < 2)
{
                             frame = 2;
                         }
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 8)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 499)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         if (frame < 2)
{
                             frame = 2;
                         }
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 8)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 765)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         if (frame < 1)
{
                             frame = 1;
                         }
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 6)
{
                             frame = 1;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frame = 0;
                     frameCounter = 0;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 266)
             {
                 if (velocity.Y >= 0f && (double)velocity.Y <= 0.8)
                 {
                     if (flag16)
                     {
                         frameCounter++;
                     }
                     else
                     {
                         frameCounter += 3;
                     }
                 }
                 else
                 {
                     frameCounter += 5;
                 }
                 if (frameCounter >= 20)
                 {
                     frameCounter -= 20;
                     frame++;
                 }
                 if (frame > 1)
                 {
                     frame = 0;
                 }
                 if (wet && Main.player[owner].position.Y + (float)Main.player[owner].height < position.Y + (float)height && localAI[0] == 0f)
                 {
                     if (velocity.Y > -4f)
                     {
                         velocity.Y -= 0.2f;
                     }
                     if (velocity.Y > 0f)
                     {
                         velocity.Y *= 0.95f;
                     }
                 }
                 else
                 {
                     velocity.Y += 0.4f;
                 }
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 334)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         if (frame > 0)
{
                             frameCounter += 2;
                             if (frameCounter > 6)
{
                                 frame++;
                                 frameCounter = 0;
                             }
                             if (frame >= 7)
{
                                 frame = 0;
                             }
                         }
                         else
{
                             frame = 0;
                             frameCounter = 0;
                         }
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs((double)velocity.X * 0.75);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 7 || frame < 1)
{
                             frame = 1;
                         }
                     }
                     else if (frame > 0)
                     {
                         frameCounter += 2;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 7)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter = 0;
                     frame = 2;
                 }
                 else if (velocity.Y > 0f)
                 {
                     frameCounter = 0;
                     frame = 4;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 353)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 9)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 else if (velocity.Y > 0f)
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 111)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 7)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y < 0f)
                 {
                     frameCounter = 0;
                     frame = 4;
                 }
                 else if (velocity.Y > 0f)
                 {
                     frameCounter = 0;
                     frame = 6;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 112)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 3)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y != 0f)
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 127)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.1 || (double)velocity.X > 0.1)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 5)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frame = 0;
                     frameCounter = 0;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 200)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.1 || (double)velocity.X > 0.1)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 5)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     rotation = velocity.X * 0.1f;
                     frameCounter++;
                     if (velocity.Y < 0f)
                     {
                         frameCounter += 2;
                     }
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 9)
                     {
                         frame = 6;
                     }
                     if (frame < 6)
                     {
                         frame = 6;
                     }
                 }
                 velocity.Y += 0.1f;
                 if (velocity.Y > 4f)
                 {
                     velocity.Y = 4f;
                 }
             }
             else if (type == 208)
             {
                 if (velocity.Y == 0f && flag16)
                 {
                     if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) < position.X + (float)(width / 2))
                     {
                         direction = -1;
                     }
                     else if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) > position.X + (float)(width / 2))
                     {
                         direction = 1;
                     }
                     rotation = 0f;
                     frame = 0;
                 }
                 else
                 {
                     rotation = velocity.X * 0.075f;
                     frameCounter++;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 4)
                     {
                         frame = 1;
                     }
                     if (frame < 1)
                     {
                         frame = 1;
                     }
                 }
                 velocity.Y += 0.1f;
                 if (velocity.Y > 4f)
                 {
                     velocity.Y = 4f;
                 }
             }
             else if (type == 209)
             {
                 if (alpha > 0)
                 {
                     alpha -= 5;
                     if (alpha < 0)
                     {
                         alpha = 0;
                     }
                 }
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.1 || (double)velocity.X > 0.1)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 11)
{
                             frame = 2;
                         }
                         if (frame < 2)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frame = 1;
                     frameCounter = 0;
                     rotation = 0f;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 324)
             {
                 if (velocity.Y == 0f)
                 {
                     if ((double)velocity.X < -0.1 || (double)velocity.X > 0.1)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 5)
{
                             frame = 2;
                         }
                         if (frame < 2)
{
                             frame = 2;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     frameCounter = 0;
                     frame = 1;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 14f)
                 {
                     velocity.Y = 14f;
                 }
             }
             else if (type == 210)
             {
                 if (velocity.Y == 0f)
                 {
                     if ((double)velocity.X < -0.1 || (double)velocity.X > 0.1)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame > 6)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else
                 {
                     rotation = velocity.X * 0.05f;
                     frameCounter++;
                     if (frameCounter > 6)
                     {
                         frame++;
                         frameCounter = 0;
                     }
                     if (frame > 11)
                     {
                         frame = 7;
                     }
                     if (frame < 7)
                     {
                         frame = 7;
                     }
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
             else if (type == 398)
             {
                 if (velocity.Y == 0f)
                 {
                     if (flag16)
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                     else if ((double)velocity.X < -0.8 || (double)velocity.X > 0.8)
                     {
                         frameCounter += (int)Math.Abs(velocity.X);
                         frameCounter++;
                         if (frameCounter > 6)
{
                             frame++;
                             frameCounter = 0;
                         }
                         if (frame >= 5)
{
                             frame = 0;
                         }
                     }
                     else
                     {
                         frame = 0;
                         frameCounter = 0;
                     }
                 }
                 else if (velocity.Y != 0f)
                 {
                     frameCounter = 0;
                     frame = 5;
                 }
                 velocity.Y += 0.4f;
                 if (velocity.Y > 10f)
                 {
                     velocity.Y = 10f;
                 }
             }
         }
         if (type == 891)
         {
             _ = Main.player[owner];
             DelegateMethods.v3_1 = new Vector3(1f, 0.61f, 0.16f) * 1.5f;
             Utils.PlotTileLine(base.Center, base.Center + velocity * 6f, 20f, DelegateMethods.CastLightOpen);
             Utils.PlotTileLine(base.Left, base.Right, 20f, DelegateMethods.CastLightOpen);
         }
     }
References Entity.active, Mount.Active, Tile.active(), Lighting.AddLight(), GameShaders.Armor, Player.babyFaceMonster, Player.blackCat, Player.bunny, NPC.CanBeChasedBy(), Mount.CanFly(), Collision.CanHit(), Collision.CanHitLine(), DelegateMethods.CastLightOpen(), Entity.Center, Player.cLight, Color, Player.controlDown, Player.controlLeft, Player.controlRight, Player.controlUp, Player.cSapling, SpriteFrame.CurrentColumn, Player.dead, Player.dino, Entity.direction, Main.dust, Player.eater, Player.eyeSpring, Dust.fadeIn, Gore.Frame, Utils.GetLerpValue(), ArmorShaderDataSet.GetSecondaryShader(), Framing.GetTileSafely(), Player.gfxOffY, Main.gore, Player.grinch, Main.CurrentFrameFlags.HadAnActiveInteractibleProjectile, Tile.halfBrick(), Entity.height, Player.hornet, Tile.liquid, Player.lizard, Player.miniMinotaur, Player.miscCounter, Player.mount, Main.myPlayer, Dust.NewDust(), Dust.NewDustDirect(), Gore.NewGore(), Gore.NewGorePerfect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Main.npc, Player.ownedProjectileCounts, owner, Player.parrot, Player.penguin, Player.petFlagBabyImp, Player.petFlagBabyRedPanda, Player.petFlagBabyShark, Player.petFlagBabyWerewolf, Player.petFlagBerniePet, Player.petFlagBlueChickenPet, Player.petFlagBrainOfCthulhuPet, Player.petFlagCaveling, Player.petFlagChesterPet, Player.petFlagDD2BetsyPet, Player.petFlagDD2OgrePet, Player.petFlagDeerclopsPet, Player.petFlagDukeFishronPet, Player.petFlagDynamiteKitten, Player.petFlagEverscreamPet, Player.petFlagFennecFox, Player.petFlagGlitteryButterfly, Player.petFlagGolemPet, Player.petFlagJunimoPet, Player.petFlagKingSlimePet, Player.petFlagLilHarpy, Player.petFlagMartianPet, Player.petFlagMoonLordPet, Player.petFlagPigPet, Player.petFlagPlanteraPet, Player.petFlagPlantero, Player.petFlagQueenBeePet, Player.petFlagQueenSlimePet, Player.petFlagShadowMimic, Player.petFlagSkeletronPet, Player.petFlagSkeletronPrimePet, Player.petFlagSpiffo, Player.petFlagSugarGlider, Player.petFlagVoltBunny, TileID.Sets.Platforms, Main.player, Utils.PlotTileLine(), Dust.position, Entity.position, Main.projectile, Main.projFrames, Player.puppy, Player.pygmy, Main.rand, Player.rocketDelay2, Player.sapling, Dust.scale, Dust.shader, Player.skeletron, Player.slime, Tile.slope(), Player.snowman, Collision.SolidCollision(), WorldGen.SolidTile(), WorldGen.SolidTileAllowBottomSlope(), Player.spider, Player.spiderMinion, Player.squashling, Collision.StepUp(), Player.tiki, Main.tile, Gore.timeLeft, timeLeft, Player.truffle, Player.turtle, type, Tile.type, DelegateMethods.v3_1, Dust.velocity, Entity.velocity, Gore.velocity, Tile.wall, Entity.whoAmI, Entity.width, Player.wisp, Main.worldSurface, and Player.zephyrfish.