Terraria: System.Reflection.RuntimeMethodInfo.GetParentDefinition
GetParentDefinition()
RuntimeMethodInfo System.Reflection.RuntimeMethodInfo.GetParentDefinition () inline package
Definition at line 215 of file RuntimeMethodInfo.cs.
    {
        if (!base.IsVirtual || m_declaringType.IsInterface)
        {
            return null;
        }
        RuntimeType runtimeType = (RuntimeType)m_declaringType.BaseType;
        if (runtimeType == null)
        {
            return null;
        }
        int slot = RuntimeMethodHandle.GetSlot(this);
        if (RuntimeTypeHandle.GetNumVirtuals(runtimeType) <= slot)
        {
            return null;
        }
        return (RuntimeMethodInfo)RuntimeType.GetMethodBase(runtimeType, RuntimeTypeHandle.GetMethodAt(runtimeType, slot));
    }
References System.RuntimeType.BaseType, System.RuntimeTypeHandle.GetMethodAt(), System.RuntimeType.GetMethodBase(), System.RuntimeTypeHandle.GetNumVirtuals(), System.RuntimeMethodHandle.GetSlot(), System.Type.IsInterface, and System.Reflection.RuntimeMethodInfo.m_declaringType.
Referenced by System.Reflection.CustomAttribute.GetCustomAttributes(), and System.Reflection.CustomAttribute.IsDefined().