Terraria: Projectile.AI_120_StardustGuardian
AI_120_StardustGuardian()
void Projectile.AI_120_StardustGuardian () inline private
     {
         Player player = Main.player[owner];
         if (!player.active)
         {
             active = false;
             return;
         }
         bool flag = type == 623;
         Vector2 vector = player.Center;
         float num = 100f;
         float num2 = 500f;
         float num3 = 500f;
         float num4 = 100f;
         bool flag2 = true;
         if (flag)
         {
             if (player.dead)
             {
                 player.stardustGuardian = false;
             }
             if (player.stardustGuardian)
             {
                 timeLeft = 2;
             }
             num = 150f;
             vector.X -= (5 + player.width / 2) * player.direction;
             vector.Y -= 25f;
             Lighting.AddLight(base.Center, 0.9f, 0.9f, 0.7f);
             if (ai[0] != 3f && alpha == 255)
             {
                 alpha = 0;
                 for (int i = 0; i < 30; i++)
                 {
                     int num5 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                     Main.dust[num5].noGravity = true;
                     Main.dust[num5].velocity *= 3f;
                     Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                     num5 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                     Main.dust[num5].velocity *= 2f;
                     Main.dust[num5].noGravity = true;
                     Main.dust[num5].fadeIn = 2.5f;
                     Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                 }
             }
         }
         if (ai[0] != 0f)
         {
             Main.player[owner].tankPet = whoAmI;
             Main.player[owner].tankPetReset = false;
         }
         if (ai[0] == 0f)
         {
             base.Center = Vector2.Lerp(base.Center, vector, 0.05f);
             velocity *= 0.5f;
             direction = (spriteDirection = player.direction);
             if (flag && ++frameCounter >= 9)
             {
                 frameCounter = 0;
                 if (++frame >= 8)
                 {
                     frame = 0;
                 }
             }
             int targetNPCIndex = -1;
             float distanceToClosestTarget = num2;
             bool flag3 = flag2;
             if (flag && Math.Abs(base.Center.X - vector.X) > num + 20f)
             {
                 flag3 = false;
             }
             if (flag3)
             {
                 AI_120_StardustGuardian_FindTarget(num2, ref targetNPCIndex, ref distanceToClosestTarget);
             }
             if (targetNPCIndex != -1)
             {
                 NPC nPC = Main.npc[targetNPCIndex];
                 direction = (spriteDirection = (nPC.Center.X > base.Center.X).ToDirectionInt());
                 float num6 = Math.Abs(vector.X - base.Center.X);
                 float num7 = Math.Abs(nPC.Center.X - base.Center.X);
                 float num8 = Math.Abs(vector.Y - base.Center.Y);
                 float num9 = Math.Abs(nPC.Center.Y - base.Bottom.Y);
                 float num10 = (nPC.Center.Y > base.Bottom.Y).ToDirectionInt();
                 if ((num6 < num || (vector.X - base.Center.X) * (float)direction < 0f) && num7 > 20f && num7 < num - num6 + 100f)
                 {
                     velocity.X += 0.1f * (float)direction;
                 }
                 else
                 {
                     velocity.X *= 0.7f;
                 }
                 if ((num8 < num4 || (vector.Y - base.Bottom.Y) * num10 < 0f) && num9 > 10f && num9 < num4 - num8 + 10f)
                 {
                     velocity.Y += 0.1f * num10;
                 }
                 else
                 {
                     velocity.Y *= 0.7f;
                 }
                 if (owner == Main.myPlayer && num7 < num3)
                 {
                     ai[0] = 2f;
                     ai[1] = targetNPCIndex;
                     netUpdate = true;
                 }
             }
         }
         else if (ai[0] == 1f)
         {
             if (player.HasMinionRestTarget)
             {
                 vector = player.MinionRestTargetPoint;
             }
             else
             {
                 ai[0] = 0f;
                 netUpdate = true;
             }
             int targetNPCIndex2 = -1;
             float distanceToClosestTarget2 = num2;
             bool flag4 = true;
             if (flag && Math.Abs(base.Center.X - vector.X) > num + 20f)
             {
                 flag4 = false;
             }
             if (flag4)
             {
                 AI_120_StardustGuardian_FindTarget(num2, ref targetNPCIndex2, ref distanceToClosestTarget2);
             }
             if (targetNPCIndex2 != -1)
             {
                 NPC nPC2 = Main.npc[targetNPCIndex2];
                 direction = (spriteDirection = (nPC2.Center.X > base.Center.X).ToDirectionInt());
                 float num11 = Math.Abs(vector.X - base.Center.X);
                 float num12 = Math.Abs(nPC2.Center.X - base.Center.X);
                 float num13 = Math.Abs(vector.Y - base.Center.Y);
                 float num14 = Math.Abs(nPC2.Center.Y - base.Bottom.Y);
                 float num15 = (nPC2.Center.Y > base.Bottom.Y).ToDirectionInt();
                 if ((num11 < num || (vector.X - base.Center.X) * (float)direction < 0f) && num12 > 20f && num12 < num - num11 + 100f)
                 {
                     velocity.X += 0.1f * (float)direction;
                 }
                 else
                 {
                     velocity.X *= 0.7f;
                 }
                 if ((num13 < num4 || (vector.Y - base.Bottom.Y) * num15 < 0f) && num14 > 10f && num14 < num4 - num13 + 10f)
                 {
                     velocity.Y += 0.1f * num15;
                 }
                 else
                 {
                     velocity.Y *= 0.7f;
                 }
                 if (owner == Main.myPlayer && num12 < num3)
                 {
                     ai[0] = 2f;
                     ai[1] = targetNPCIndex2;
                     netUpdate = true;
                 }
             }
             else
             {
                 if (Math.Abs(vector.X - base.Center.X) > num + 40f)
                 {
                     ai[0] = 3f;
                     netUpdate = true;
                 }
                 else if (Math.Abs(vector.X - base.Center.X) > 20f)
                 {
                     direction = (spriteDirection = (vector.X > base.Center.X).ToDirectionInt());
                     velocity.X += 0.06f * (float)direction;
                 }
                 else
                 {
                     velocity.X *= 0.8f;
                     direction = (spriteDirection = (player.Center.X < base.Center.X).ToDirectionInt());
                 }
                 if (Math.Abs(vector.Y - base.Center.Y) > num4)
                 {
                     ai[0] = 3f;
                     netUpdate = true;
                 }
                 else if (Math.Abs(vector.Y - base.Center.Y) > 10f)
                 {
                     velocity.Y += 0.06f * (float)Math.Sign(vector.Y - base.Center.Y);
                 }
                 else
                 {
                     velocity.Y *= 0.8f;
                 }
             }
             if (flag && ++frameCounter >= 9)
             {
                 frameCounter = 0;
                 if (++frame >= Main.projFrames[type] - 4)
                 {
                     frame = 0;
                 }
             }
         }
         else if (ai[0] == 2f)
         {
             if (flag)
             {
                 int num16 = 3;
                 if (frame < 12)
                 {
                     frame = 12;
                 }
                 if (frame == 12 || frame == 13)
                 {
                     num16 = 8;
                 }
                 if (++frameCounter >= num16)
                 {
                     frameCounter = 0;
                     if (++frame >= 19)
                     {
                         frame = 14;
                     }
                 }
             }
             bool flag5 = false;
             if (flag2)
             {
                 flag5 = Distance(player.Center) < num2;
             }
             NPC nPC3 = null;
             int num17 = (int)ai[1];
             if (Main.npc.IndexInRange(num17))
             {
                 nPC3 = Main.npc[num17];
                 if (!nPC3.CanBeChasedBy(this) || Distance(nPC3.Center) > num3)
                 {
                     nPC3 = null;
                 }
             }
             if (!flag5 || nPC3 == null)
             {
                 ai[1] = 0f;
                 ai[0] = 0f;
                 netUpdate = true;
                 if (frame < 18)
                 {
                     frame = 18;
                 }
             }
             else
             {
                 int num18 = (((nPC3.Center - player.Center).X > 1f) ? 1 : (-1));
                 Vector2 targetPosition = nPC3.Center + new Vector2((float)(-num18) * ((float)nPC3.width * 0.5f + 70f), -10f) - base.Center;
                 float maxAmountAllowedToMove = 6f * Utils.Remap(targetPosition.Length(), 50f, 400f, 1f, 4f);
                 int num19 = 32;
                 Vector2 targetPosition2 = Vector2.Zero.MoveTowards(targetPosition, maxAmountAllowedToMove);
                 velocity = velocity.MoveTowards(targetPosition2, num19);
                 direction = (spriteDirection = num18);
                 if (localAI[0]++ >= 3f)
                 {
                     localAI[0] = 0f;
                     int targetNPCIndex3 = -1;
                     float distanceToClosestTarget3 = -1f;
                     AI_120_StardustGuardian_FindTarget(num2, ref targetNPCIndex3, ref distanceToClosestTarget3);
                     if (targetNPCIndex3 != -1)
                     {
                         ai[1] = targetNPCIndex3;
                         netUpdate = true;
                     }
                 }
             }
         }
         else
         {
             _ = ai[0];
             _ = 2f;
         }
         if (ai[0] != 3f)
         {
             return;
         }
         if (player.HasMinionRestTarget)
         {
             vector = player.MinionRestTargetPoint;
         }
         else
         {
             ai[0] = 0f;
             netUpdate = true;
         }
         if (alpha == 0)
         {
             alpha = 255;
             for (int j = 0; j < 30; j++)
             {
                 int num20 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                 Main.dust[num20].noGravity = true;
                 Main.dust[num20].velocity *= 3f;
                 Main.dust[num20].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                 num20 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                 Main.dust[num20].velocity *= 2f;
                 Main.dust[num20].noGravity = true;
                 Main.dust[num20].fadeIn = 2.5f;
                 Main.dust[num20].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
             }
         }
         else
         {
             for (int k = 0; k < 2; k++)
             {
                 int num21 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                 Main.dust[num21].noGravity = true;
                 Main.dust[num21].velocity *= 3f;
                 Main.dust[num21].noLight = true;
                 Main.dust[num21].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                 num21 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                 Main.dust[num21].velocity *= 2f;
                 Main.dust[num21].noGravity = true;
                 Main.dust[num21].fadeIn = 2.5f;
                 Main.dust[num21].noLight = true;
                 Main.dust[num21].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
             }
         }
         velocity *= 0.7f;
         base.Center = Vector2.Lerp(base.Center, vector, 0.2f);
         if (Distance(vector) < 10f)
         {
             ai[0] = 1f;
             netUpdate = true;
         }
     }
References Entity.active, Lighting.AddLight(), GameShaders.Armor, NPC.CanBeChasedBy(), Entity.Center, Color, Player.cPet, Player.dead, Entity.direction, Main.dust, Dust.fadeIn, ArmorShaderDataSet.GetSecondaryShader(), Player.HasMinionRestTarget, Player.MinionRestTargetPoint, Main.myPlayer, Dust.NewDust(), Dust.noGravity, Dust.noLight, Main.npc, Main.player, Main.projFrames, Utils.Remap(), Dust.shader, Player.stardustGuardian, Player.tankPet, Player.tankPetReset, Dust.velocity, Entity.width, and X.