Terraria: Projectile.AI_138_ExplosiveTrap
AI_138_ExplosiveTrap()
void Projectile.AI_138_ExplosiveTrap () inline private
     {
         //IL_0173: Unknown result type (might be due to invalid IL or missing references)
         spriteDirection = (direction = 1);
         int num = 694;
         int num2 = 48;
         int explosiveTrapCooldown = GetExplosiveTrapCooldown(Main.player[owner]);
         switch (type)
         {
         case 692:
             num = 695;
             break;
         case 693:
             num = 696;
             break;
         }
         Lighting.AddLight(base.Center, 0.6f, 0.5f, 0.3f);
         if (++frameCounter >= 12)
         {
             frameCounter = 0;
             if (++frame >= Main.projFrames[type])
             {
                 frame = 0;
             }
         }
         if (localAI[0] > 0f)
         {
             localAI[0] -= 1f;
         }
         if (localAI[0] <= 0f && owner == Main.myPlayer)
         {
             localAI[0] = 3f;
             bool flag = false;
             Rectangle rectangle = Utils.CenteredRectangle(base.Center + new Vector2(0f, -num2), new Vector2(num2 * 3));
             for (int i = 0; i < 200; i++)
             {
                 NPC nPC = Main.npc[i];
                 if (nPC.CanBeChasedBy(this) && rectangle.Intersects(nPC.Hitbox))
                 {
                     flag = true;
                     break;
                 }
             }
             if (flag)
             {
                 SoundEngine.PlayTrackedSound(SoundID.DD2_ExplosiveTrapExplode);
                 localAI[0] = explosiveTrapCooldown;
                 NewProjectile(GetProjectileSource_FromThis(), base.Center + new Vector2(0f, -num2), Vector2.Zero, num, damage, knockBack, owner);
             }
         }
         tileCollide = true;
         velocity.Y += 0.2f;
     }
References Lighting.AddLight(), NPC.CanBeChasedBy(), Utils.CenteredRectangle(), SoundID.DD2_ExplosiveTrapExplode, Entity.Hitbox, Main.myPlayer, Main.npc, Main.player, SoundEngine.PlayTrackedSound(), and Main.projFrames.