Terraria: Projectile.AI_016
AI_016()
void Projectile.AI_016 () inline private
     {
         if (wet && (type == 799 || type == 800 || type == 801 || type == 810 || type == 906 || type == 784 || type == 785 || type == 786 || type == 805 || type == 903 || type == 787 || type == 788 || type == 789 || type == 806 || type == 904 || type == 790 || type == 791 || type == 792 || type == 807 || type == 905))
         {
             timeLeft = 1;
         }
         if (type == 108 || type == 164 || type == 1002)
         {
             ai[0] += 1f;
             if (ai[0] > 3f)
             {
                 Kill();
             }
         }
         if (type == 102)
         {
             int num = (int)(base.Center.X / 16f);
             int num2 = (int)(base.Center.Y / 16f);
             if (WorldGen.InWorld(num, num2))
             {
                 Tile tile = Main.tile[num, num2];
                 if (tile != null && tile.active() && (TileID.Sets.Platforms[tile.type] || tile.type == 380))
                 {
                     Kill();
                     return;
                 }
             }
         }
         if (type == 75)
         {
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(66, (int)position.X, (int)position.Y);
             }
             for (int i = 0; i < 255; i++)
             {
                 if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost && (base.Center - Main.player[i].Center).Length() < 40f)
                 {
                     Kill();
                     return;
                 }
             }
         }
         bool flag = false;
         if (type == 37 || type == 397 || type == 470 || type == 519 || type == 773 || type == 911)
         {
             try
             {
                 int num3 = (int)(position.X / 16f) - 1;
                 int num4 = (int)((position.X + (float)width) / 16f) + 2;
                 int num5 = (int)(position.Y / 16f) - 1;
                 int num6 = (int)((position.Y + (float)height) / 16f) + 2;
                 if (num3 < 0)
                 {
                     num3 = 0;
                 }
                 if (num4 > Main.maxTilesX)
                 {
                     num4 = Main.maxTilesX;
                 }
                 if (num5 < 0)
                 {
                     num5 = 0;
                 }
                 if (num6 > Main.maxTilesY)
                 {
                     num6 = Main.maxTilesY;
                 }
                 Vector2 vector = default(Vector2);
                 for (int j = num3; j < num4; j++)
                 {
                     for (int k = num5; k < num6; k++)
                     {
                         if (Main.tile[j, k] == null || !Main.tile[j, k].nactive() || !Main.tileSolid[Main.tile[j, k].type] || Main.tileSolidTop[Main.tile[j, k].type])
{
                             continue;
                         }
                         vector.X = j * 16;
                         vector.Y = k * 16;
                         if (!(position.X + (float)width - 4f > vector.X) || !(position.X + 4f < vector.X + 16f) || !(position.Y + (float)height - 4f > vector.Y) || !(position.Y + 4f < vector.Y + 16f))
{
                             continue;
                         }
                         if (type == 911 && owner == Main.myPlayer && localAI[0] == 0f)
{
                             float num7 = 12f;
                             Vector2 value = vector + new Vector2(8f, 8f);
                             if (Vector2.Distance(base.Center, value) < num7)
{
                                 base.Center += velocity.SafeNormalize(Vector2.Zero) * -4f;
                             }
                             localAI[0] = 1f;
                             netUpdate = true;
                         }
                         velocity.X = 0f;
                         velocity.Y = -0.2f;
                         flag = true;
                     }
                 }
             }
             catch
             {
             }
         }
         if (flag && type == 911)
         {
             Point p = base.Center.ToTileCoordinates();
             if (WorldGen.SolidOrSlopedTile(Framing.GetTileSafely(p.X, p.Y)))
             {
                 Vector2 v = p.ToWorldCoordinates() - base.Center;
                 base.Center += v.SafeNormalize(Vector2.Zero) * -4f;
             }
         }
         if (flag && type == 773)
         {
             Player player = Main.player[owner];
             Vector2 v2 = DirectionTo(player.Center).SafeNormalize(Vector2.UnitX * player.direction);
             float num8 = rotation;
             float num9 = v2.ToRotation() + (float)Math.PI / 2f;
             rotation = rotation.AngleLerp(num9, 0.2f);
             rotation = rotation.AngleTowards(num9, 0.05f);
             Vector2 vector2 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
             if (Main.rand.Next(3) == 0)
             {
                 Dust dust = Dust.NewDustPerfect(base.Center + vector2 * 10f, 59, vector2 * 2f + Main.rand.NextVector2Circular(0.25f, 0.25f), 0, default(Color), 2f);
                 dust.noGravity = true;
                 if (Main.rand.Next(3) == 0)
                 {
                     dust.velocity *= 1.5f;
                     dust.noGravity = false;
                     dust.scale /= 2f;
                 }
             }
             if (Main.rand.Next(3) == 0)
             {
                 Point scarabBombDigDirectionSnap = GetScarabBombDigDirectionSnap8();
                 Dust.NewDustPerfect(base.Center + vector2 * -10f, 59, scarabBombDigDirectionSnap.ToVector2() * 1.5f, 0, default(Color), 2f).noGravity = true;
             }
             if (Main.rand.Next(15) == 0)
             {
                 Dust dust2 = Dust.NewDustPerfect(base.Center + vector2 * 10f, 88, vector2 * 3f + Main.rand.NextVector2Circular(0.25f, 0.25f), 0, default(Color), 2f);
                 dust2.noGravity = true;
                 if (Main.rand.Next(3) == 0)
                 {
                     dust2.velocity *= 1.5f;
                 }
             }
             bool flag2 = Main.rand.Next(30) == 0;
             if (num8 != rotation && Main.rand.Next(40) == 0)
             {
                 flag2 = true;
             }
             if (flag2)
             {
                 float num10 = (float)Math.PI * 2f * Main.rand.NextFloat();
                 for (float num11 = 0f; num11 < 1f; num11 += 1f / 7f)
                 {
                     Vector2 spinningpoint = (num11 * ((float)Math.PI * 2f) + num10).ToRotationVector2();
                     spinningpoint *= new Vector2(1f, 0.3f);
                     spinningpoint = spinningpoint.RotatedBy(num9);
                     Dust dust3 = Dust.NewDustPerfect(base.Center + spinningpoint + vector2 * 8f, 59, vector2 * 3f + spinningpoint);
                     dust3.noGravity = true;
                     dust3.fadeIn = 1.6f;
                 }
             }
             if (++frameCounter >= 3)
             {
                 frameCounter = 0;
                 if (++frame >= 4)
                 {
                     frame = 0;
                 }
             }
         }
         if (type == 519)
         {
             localAI[1] += 1f;
             float num12 = 180f - localAI[1];
             if (num12 < 0f)
             {
                 num12 = 0f;
             }
             frameCounter++;
             if (num12 < 15f)
             {
                 frameCounter++;
             }
             if ((float)frameCounter >= (num12 / 10f + 6f) / 2f)
             {
                 frame++;
                 frameCounter = 0;
                 if (frame >= Main.projFrames[type])
                 {
                     frame = 0;
                 }
             }
         }
         if (type == 681 && localAI[1] == 0f)
         {
             localAI[1] = 1f;
         }
         int num13 = 6;
         if (type == 776 || type == 780 || type == 803 || type == 804)
         {
             num13 = 228;
         }
         else if (type == 784 || type == 805)
         {
             num13 = ((Main.rand.Next(3) == 0) ? 6 : Dust.dustWater());
         }
         else if (type == 787 || type == 806)
         {
             num13 = ((Main.rand.Next(3) == 0) ? 6 : 35);
         }
         else if (type == 790 || type == 807)
         {
             num13 = ((Main.rand.Next(3) == 0) ? 6 : 152);
         }
         if (type == 102)
         {
             if (velocity.Y > 10f)
             {
                 velocity.Y = 10f;
             }
             if (localAI[0] == 0f)
             {
                 localAI[0] = 1f;
                 SoundEngine.PlaySound(SoundID.Item10, position);
             }
             frameCounter++;
             if (frameCounter > 3)
             {
                 frame++;
                 frameCounter = 0;
             }
             if (frame > 1)
             {
                 frame = 0;
             }
             if (velocity.Y == 0f)
             {
                 position.X += width / 2;
                 position.Y += height / 2;
                 width = 128;
                 height = 128;
                 position.X -= width / 2;
                 position.Y -= height / 2;
                 damage = 40;
                 knockBack = 8f;
                 timeLeft = 3;
                 netUpdate = true;
             }
         }
         if (type == 303 && timeLeft <= 3 && hostile)
         {
             position.X += width / 2;
             position.Y += height / 2;
             width = 128;
             height = 128;
             position.X -= width / 2;
             position.Y -= height / 2;
         }
         if (owner == Main.myPlayer && timeLeft <= 3)
         {
             PrepareBombToBlow();
         }
         else
         {
             if (type != 30 && type != 75 && type != 517 && type != 681 && type != 588 && type != 397 && type != 108 && type != 1002 && type != 133 && type != 134 && type != 135 && type != 136 && type != 137 && type != 138 && type != 139 && type != 140 && type != 141 && type != 142 && type != 143 && type != 144 && type != 164 && type != 303 && type != 338 && type != 339 && type != 340 && type != 341 && (type < 776 || type > 801) && (type < 803 || type > 810) && type != 862 && type != 863 && type != 930)
             {
                 damage = 0;
             }
             if (type == 338 || type == 339 || type == 340 || type == 341 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
             {
                 localAI[1] += 1f;
                 if (localAI[1] > 6f)
                 {
                     alpha = 0;
                 }
                 else
                 {
                     alpha = (int)(255f - 42f * localAI[1]) + 100;
                     if (alpha > 255)
                     {
                         alpha = 255;
                     }
                 }
                 for (int l = 0; l < 2; l++)
                 {
                     float num14 = 0f;
                     float num15 = 0f;
                     if (l == 1)
                     {
                         num14 = velocity.X * 0.5f;
                         num15 = velocity.Y * 0.5f;
                     }
                     if (!(localAI[1] > 9f))
                     {
                         continue;
                     }
                     if (Main.rand.Next(2) == 0)
                     {
                         int num16 = Dust.NewDust(new Vector2(position.X + 3f + num14, position.Y + 3f + num15) - velocity * 0.5f, width - 8, height - 8, num13, 0f, 0f, 100);
                         Main.dust[num16].scale *= 1.4f + (float)Main.rand.Next(10) * 0.1f;
                         Main.dust[num16].velocity *= 0.2f;
                         Main.dust[num16].noGravity = true;
                         if (Main.dust[num16].type == 152)
{
                             Main.dust[num16].scale *= 0.5f;
                             Main.dust[num16].velocity += velocity * 0.1f;
                         }
                         else if (Main.dust[num16].type == 35)
{
                             Main.dust[num16].scale *= 0.5f;
                             Main.dust[num16].velocity += velocity * 0.1f;
                         }
                         else if (Main.dust[num16].type == Dust.dustWater())
{
                             Main.dust[num16].scale *= 0.65f;
                             Main.dust[num16].velocity += velocity * 0.1f;
                         }
                         if (type == 808 || type == 809)
{
                             Dust dust4 = Main.dust[num16];
                             if (dust4.dustIndex != 6000)
{
                                 dust4 = Dust.NewDustPerfect(dust4.position, dust4.type, dust4.velocity, dust4.alpha, dust4.color, dust4.scale + 0.5f);
                                 dust4.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                 dust4.noGravity = true;
                             }
                             if (dust4.dustIndex != 6000)
{
                                 dust4 = Dust.NewDustPerfect(dust4.position, dust4.type, dust4.velocity, dust4.alpha, dust4.color, dust4.scale + 0.5f);
                                 dust4.velocity = ((float)Math.PI * 2f * ((float)timeLeft / 20f)).ToRotationVector2() * 3f;
                                 dust4.noGravity = true;
                             }
                         }
                     }
                     if (Main.rand.Next(2) == 0)
                     {
                         int num17 = Dust.NewDust(new Vector2(position.X + 3f + num14, position.Y + 3f + num15) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                         Main.dust[num17].fadeIn = 0.5f + (float)Main.rand.Next(5) * 0.1f;
                         Main.dust[num17].velocity *= 0.05f;
                     }
                 }
                 float x = position.X;
                 float y = position.Y;
                 float num18 = 600f;
                 if (type == 930)
                 {
                     num18 = 650f;
                 }
                 bool flag3 = false;
                 ai[0] += 1f;
                 if (ai[0] > 30f)
                 {
                     ai[0] = 30f;
                     for (int m = 0; m < 200; m++)
                     {
                         if (Main.npc[m].CanBeChasedBy(this))
{
                             float num19 = Main.npc[m].position.X + (float)(Main.npc[m].width / 2);
                             float num20 = Main.npc[m].position.Y + (float)(Main.npc[m].height / 2);
                             float num21 = Math.Abs(position.X + (float)(width / 2) - num19) + Math.Abs(position.Y + (float)(height / 2) - num20);
                             if (num21 < num18 && Collision.CanHit(position, width, height, Main.npc[m].position, Main.npc[m].width, Main.npc[m].height))
{
                                 num18 = num21;
                                 x = num19;
                                 y = num20;
                                 flag3 = true;
                             }
                         }
                     }
                 }
                 if (!flag3)
                 {
                     x = position.X + (float)(width / 2) + velocity.X * 100f;
                     y = position.Y + (float)(height / 2) + velocity.Y * 100f;
                 }
                 float num22 = 16f;
                 if (type == 930)
                 {
                     num22 = 12f;
                 }
                 Vector2 value2 = (new Vector2(x, y) - base.Center).SafeNormalize(-Vector2.UnitY) * num22;
                 velocity = Vector2.Lerp(velocity, value2, 1f / 12f);
             }
             else if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790)
             {
                 if (Math.Abs(velocity.X) >= 8f || Math.Abs(velocity.Y) >= 8f)
                 {
                     for (int n = 0; n < 2; n++)
                     {
                         float num23 = 0f;
                         float num24 = 0f;
                         if (n == 1)
{
                             num23 = velocity.X * 0.5f;
                             num24 = velocity.Y * 0.5f;
                         }
                         int num25 = Dust.NewDust(new Vector2(position.X + 3f + num23, position.Y + 3f + num24) - velocity * 0.5f, width - 8, height - 8, num13, 0f, 0f, 100);
                         Main.dust[num25].scale *= 2f + (float)Main.rand.Next(10) * 0.1f;
                         Main.dust[num25].velocity *= 0.2f;
                         Main.dust[num25].noGravity = true;
                         if (Main.dust[num25].type == 152)
{
                             Main.dust[num25].scale *= 0.5f;
                             Main.dust[num25].velocity += velocity * 0.1f;
                         }
                         else if (Main.dust[num25].type == 35)
{
                             Main.dust[num25].scale *= 0.5f;
                             Main.dust[num25].velocity += velocity * 0.1f;
                         }
                         else if (Main.dust[num25].type == Dust.dustWater())
{
                             Main.dust[num25].scale *= 0.65f;
                             Main.dust[num25].velocity += velocity * 0.1f;
                         }
                         if (type == 793 || type == 796)
{
                             Dust dust5 = Main.dust[num25];
                             if (dust5.dustIndex != 6000)
{
                                 dust5 = Dust.NewDustPerfect(dust5.position, dust5.type, dust5.velocity, dust5.alpha, dust5.color, dust5.scale);
                                 dust5.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                 dust5.noGravity = true;
                             }
                             if (dust5.dustIndex != 6000)
{
                                 dust5 = Dust.NewDustPerfect(dust5.position, dust5.type, dust5.velocity, dust5.alpha, dust5.color, dust5.scale);
                                 dust5.velocity = ((float)Math.PI * 2f * ((float)timeLeft / 20f)).ToRotationVector2() * 3f;
                                 dust5.noGravity = true;
                             }
                         }
                         num25 = Dust.NewDust(new Vector2(position.X + 3f + num23, position.Y + 3f + num24) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                         Main.dust[num25].fadeIn = 1f + (float)Main.rand.Next(5) * 0.1f;
                         Main.dust[num25].velocity *= 0.05f;
                     }
                 }
                 if (Math.Abs(velocity.X) < 15f && Math.Abs(velocity.Y) < 15f)
                 {
                     velocity *= 1.1f;
                 }
             }
             else if (type == 133 || type == 136 || type == 139 || type == 142 || type == 777 || type == 781 || type == 794 || type == 797 || type == 800 || type == 785 || type == 788 || type == 791)
             {
                 int num26 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100);
                 Main.dust[num26].scale *= 1f + (float)Main.rand.Next(10) * 0.1f;
                 Main.dust[num26].velocity *= 0.2f;
                 Main.dust[num26].noGravity = true;
             }
             else if (type == 135 || type == 138 || type == 141 || type == 144 || type == 778 || type == 782 || type == 795 || type == 798 || type == 801 || type == 786 || type == 789 || type == 792)
             {
                 if ((double)velocity.X > -0.2 && (double)velocity.X < 0.2 && (double)velocity.Y > -0.2 && (double)velocity.Y < 0.2)
                 {
                     alpha += 2;
                     if (alpha > 200)
                     {
                         alpha = 200;
                     }
                 }
                 else
                 {
                     alpha = 0;
                     int num27 = Dust.NewDust(new Vector2(position.X + 3f, position.Y + 3f) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100);
                     Main.dust[num27].scale *= 1.6f + (float)Main.rand.Next(5) * 0.1f;
                     Main.dust[num27].velocity *= 0.05f;
                     Main.dust[num27].noGravity = true;
                 }
             }
             else if (type == 779 || type == 783 || type == 862 || type == 863)
             {
                 if (Main.rand.Next(25) == 0)
                 {
                     Dust dust6 = Dust.NewDustDirect(position, width, height, 228, (0f - velocity.X) / 10f, (0f - velocity.Y) / 10f, 100);
                     dust6.noGravity = true;
                     dust6.velocity *= 0f;
                     dust6.scale = 1.3f;
                 }
                 if (Main.rand.Next(5) == 0)
                 {
                     Dust dust7 = Dust.NewDustDirect(position, width, height, 31, (0f - velocity.X) / 10f, (0f - velocity.Y) / 10f, 100);
                     dust7.noGravity = true;
                     dust7.velocity *= 0f;
                     dust7.scale = 1.3f;
                 }
                 if (frameCounter == 0)
                 {
                     frameCounter = 1;
                     frame = Main.rand.Next(4);
                 }
             }
             else if (type != 30 && type != 517 && type != 681 && type != 397 && type != 519 && type != 588 && type != 779 && type != 783 && type != 862 && type != 863 && Main.rand.Next(2) == 0)
             {
                 int num28 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100);
                 Main.dust[num28].scale = 0.1f + (float)Main.rand.Next(5) * 0.1f;
                 Main.dust[num28].fadeIn = 1.5f + (float)Main.rand.Next(5) * 0.1f;
                 Main.dust[num28].noGravity = true;
                 Main.dust[num28].position = base.Center + new Vector2(0f, -height / 2).RotatedBy(rotation) * 1.1f;
                 int num29 = 6;
                 if (type == 773)
                 {
                     num29 = 59;
                 }
                 if (type == 903)
                 {
                     num29 = Dust.dustWater();
                 }
                 if (type == 904)
                 {
                     num29 = 35;
                 }
                 if (type == 905)
                 {
                     num29 = 152;
                 }
                 if (type == 910 || type == 911)
                 {
                     num29 = 0;
                 }
                 Dust dust8 = Dust.NewDustDirect(position, width, height, num29, 0f, 0f, 100);
                 dust8.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                 dust8.noGravity = true;
                 dust8.position = base.Center + new Vector2(0f, -height / 2 - 6).RotatedBy(rotation) * 1.1f;
             }
             else if (type == 681)
             {
                 Dust dust9 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100);
                 dust9.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                 dust9.noGravity = true;
                 dust9.position = base.Center + new Vector2(6 * Math.Sign(velocity.X), -height / 2 - 6).RotatedBy(rotation) * 1.1f;
             }
         }
         ai[0] += 1f;
         if (type == 338 || type == 339 || type == 340 || type == 341 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
         {
             if (velocity.X < 0f)
             {
                 spriteDirection = -1;
                 rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X) - 1.57f;
             }
             else
             {
                 spriteDirection = 1;
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             }
         }
         else if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790)
         {
             if (velocity != Vector2.Zero)
             {
                 rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
             }
         }
         else if (type == 135 || type == 138 || type == 141 || type == 144 || type == 778 || type == 782 || type == 795 || type == 798 || type == 801 || type == 786 || type == 789 || type == 792)
         {
             velocity.Y += 0.2f;
             velocity *= 0.97f;
             if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
             {
                 velocity.X = 0f;
             }
             if ((double)velocity.Y > -0.1 && (double)velocity.Y < 0.1)
             {
                 velocity.Y = 0f;
             }
         }
         else if (type == 133 || type == 136 || type == 139 || type == 142 || type == 777 || type == 781 || type == 794 || type == 797 || type == 800 || type == 785 || type == 788 || type == 791)
         {
             if (ai[0] > 15f)
             {
                 if (velocity.Y == 0f)
                 {
                     velocity.X *= 0.95f;
                 }
                 velocity.Y += 0.2f;
             }
         }
         else if (((type == 30 || type == 397 || type == 517 || type == 681 || type == 588 || type == 779 || type == 783 || type == 862 || type == 863) && ai[0] > 10f) || (type != 30 && type != 397 && type != 517 && type != 588 && type != 779 && type != 783 && type != 862 && type != 863 && ai[0] > 5f))
         {
             ai[0] = 10f;
             if (velocity.Y == 0f && velocity.X != 0f)
             {
                 velocity.X *= 0.97f;
                 if (type == 29 || type == 470 || type == 637)
                 {
                     velocity.X *= 0.99f;
                 }
                 if ((double)velocity.X > -0.01 && (double)velocity.X < 0.01)
                 {
                     velocity.X = 0f;
                     netUpdate = true;
                 }
             }
             velocity.Y += 0.2f;
             if (type == 911)
             {
                 velocity.X = MathHelper.Clamp(velocity.X, -8f, 8f);
                 velocity.Y = MathHelper.Clamp(velocity.Y, -8f, 8f);
             }
         }
         if (type == 519)
         {
             rotation += velocity.X * 0.06f;
         }
         else if (type != 134 && type != 137 && type != 140 && type != 143 && type != 303 && (type < 338 || type > 341) && type != 776 && type != 780 && type != 793 && type != 796 && type != 799 && type != 784 && type != 787 && type != 790 && type != 803 && type != 804 && type != 808 && type != 809 && type != 810 && type != 805 && type != 806 && type != 807 && type != 930)
         {
             rotation += velocity.X * 0.1f;
         }
     }
References Entity.active, Tile.active(), Dust.alpha, NPC.CanBeChasedBy(), Collision.CanHit(), Entity.Center, Color, Dust.color, Player.dead, Entity.direction, Main.dust, Dust.dustIndex, Dust.dustWater(), Dust.fadeIn, Framing.GetTileSafely(), Player.ghost, Entity.height, WorldGen.InWorld(), SoundID.Item10, Main.maxTilesX, Main.maxTilesY, Main.myPlayer, Tile.nactive(), Dust.NewDust(), Dust.NewDustDirect(), Dust.NewDustPerfect(), UnifiedRandom.Next(), Dust.noGravity, Main.npc, TileID.Sets.Platforms, Main.player, SoundEngine.PlaySound(), Dust.position, Entity.position, Main.projFrames, Main.rand, Dust.scale, WorldGen.SolidOrSlopedTile(), Main.tile, Main.tileSolid, Main.tileSolidTop, Dust.type, Tile.type, Dust.velocity, and Entity.width.