Terraria: Projectile.CreateImpactExplosion
CreateImpactExplosion()
void Projectile.CreateImpactExplosion (int dustAmountMultiplier, Vector2 explosionOrigin, ref Point scanAreaStart, ref Point scanAreaEnd, int explosionRange, out bool causedShockwaves) inline private
     {
         causedShockwaves = false;
         int num = 4;
         for (int i = scanAreaStart.X; i <= scanAreaEnd.X; i++)
         {
             for (int j = scanAreaStart.Y; j <= scanAreaEnd.Y; j++)
             {
                 if (Vector2.Distance(explosionOrigin, new Vector2(i * 16, j * 16)) > (float)explosionRange)
                 {
                     continue;
                 }
                 Tile tileSafely = Framing.GetTileSafely(i, j);
                 if (!tileSafely.active() || !Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type] || Main.tileFrameImportant[tileSafely.type])
                 {
                     continue;
                 }
                 Tile tileSafely2 = Framing.GetTileSafely(i, j - 1);
                 if (tileSafely2.active() && Main.tileSolid[tileSafely2.type] && !Main.tileSolidTop[tileSafely2.type])
                 {
                     continue;
                 }
                 int num2 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely) * dustAmountMultiplier;
                 for (int k = 0; k < num2; k++)
                 {
                     Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                     obj.velocity.Y -= 3f + (float)num * 1.5f;
                     obj.velocity.Y *= Main.rand.NextFloat();
                     obj.scale += (float)num * 0.03f;
                 }
                 if (num >= 2)
                 {
                     for (int l = 0; l < num2 - 1; l++)
                     {
                         Dust obj2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                         obj2.velocity.Y -= 1f + (float)num;
                         obj2.velocity.Y *= Main.rand.NextFloat();
                     }
                 }
                 if (num2 > 0)
                 {
                     causedShockwaves = true;
                 }
             }
         }
     }
References Tile.active(), Main.dust, Framing.GetTileSafely(), WorldGen.KillTile_GetTileDustAmount(), WorldGen.KillTile_MakeTileDust(), Main.rand, Dust.scale, Main.tileFrameImportant, Main.tileSolid, Main.tileSolidTop, Tile.type, and Dust.velocity.