Terraria: Projectile.ghostHurt
ghostHurt()
void Projectile.ghostHurt (int dmg, Vector2 Position, Entity victim) inline
     {
         if (!magic || damage <= 0)
         {
             return;
         }
         int num = damage;
         if (dmg <= 1)
         {
             return;
         }
         int num2 = -1;
         int num3 = 1500;
         if (Main.player[Main.myPlayer].ghostDmg > (float)num3)
         {
             return;
         }
         Main.player[Main.myPlayer].ghostDmg += num;
         int[] array = new int[200];
         int num4 = 0;
         _ = new int[200];
         int num5 = 0;
         for (int i = 0; i < 200; i++)
         {
             if (!Main.npc[i].CanBeChasedBy(this))
             {
                 continue;
             }
             float num6 = Math.Abs(Main.npc[i].position.X + (float)(Main.npc[i].width / 2) - position.X + (float)(width / 2)) + Math.Abs(Main.npc[i].position.Y + (float)(Main.npc[i].height / 2) - position.Y + (float)(height / 2));
             if (num6 < 800f)
             {
                 if (Collision.CanHit(position, 1, 1, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height) && num6 > 50f)
                 {
                     array[num5] = i;
                     num5++;
                 }
                 else if (num5 == 0)
                 {
                     array[num4] = i;
                     num4++;
                 }
             }
         }
         if (num4 != 0 || num5 != 0)
         {
             num2 = ((num5 <= 0) ? array[Main.rand.Next(num4)] : array[Main.rand.Next(num5)]);
             float num7 = Main.rand.Next(-100, 101);
             float num8 = Main.rand.Next(-100, 101);
             float num9 = (float)Math.Sqrt(num7 * num7 + num8 * num8);
             num9 = 4f / num9;
             num7 *= num9;
             num8 *= num9;
             NewProjectile(GetProjectileSource_OnHit(victim, 16), Position.X, Position.Y, num7, num8, 356, num, 0f, owner, num2);
         }
     }
References NPC.CanBeChasedBy(), Collision.CanHit(), damage, GetProjectileSource_OnHit(), Player.ghostDmg, Entity.height, magic, Main.myPlayer, NewProjectile(), UnifiedRandom.Next(), Main.npc, owner, Main.player, Entity.position, Main.rand, and Entity.width.
Referenced by Damage().