Terraria: Projectile.AI_182_FinalFractal
AI_182_FinalFractal()
void Projectile.AI_182_FinalFractal () inline private
     {
         if (type == 933 && localAI[1] == 0f)
         {
             localAI[1] = 1f;
             SoundEngine.PlaySound(SoundID.Item169, base.Center);
         }
         Player player = Main.player[owner];
         Vector2 mountedCenter = player.MountedCenter;
         float lerpValue = Utils.GetLerpValue(900f, 0f, velocity.Length() * 2f, clamped: true);
         float num = MathHelper.Lerp(0.7f, 2f, lerpValue);
         localAI[0] += num;
         if (localAI[0] >= 120f)
         {
             Kill();
             return;
         }
         float lerpValue2 = Utils.GetLerpValue(0f, 1f, localAI[0] / 60f, clamped: true);
         float num2 = localAI[0] / 60f;
         float num3 = ai[0];
         float num4 = velocity.ToRotation();
         float num5 = (float)Math.PI;
         float num6 = ((velocity.X > 0f) ? 1 : (-1));
         float num7 = num5 + num6 * lerpValue2 * ((float)Math.PI * 2f);
         float num8 = velocity.Length() + Utils.GetLerpValue(0.5f, 1f, lerpValue2, clamped: true) * 40f;
         float num9 = 60f;
         if (num8 < num9)
         {
             num8 = num9;
         }
         Vector2 vector = mountedCenter + velocity;
         Vector2 spinningpoint = new Vector2(1f, 0f).RotatedBy(num7) * new Vector2(num8, num3 * MathHelper.Lerp(2f, 1f, lerpValue));
         Vector2 vector2 = vector + spinningpoint.RotatedBy(num4);
         Vector2 vector3 = (1f - Utils.GetLerpValue(0f, 0.5f, lerpValue2, clamped: true)) * new Vector2((float)((velocity.X > 0f) ? 1 : (-1)) * (0f - num8) * 0.1f, (0f - ai[0]) * 0.3f);
         float num10 = num7 + num4;
         rotation = num10 + (float)Math.PI / 2f;
         base.Center = vector2 + vector3;
         spriteDirection = (direction = ((velocity.X > 0f) ? 1 : (-1)));
         if (num3 < 0f)
         {
             rotation = num5 + num6 * lerpValue2 * ((float)Math.PI * -2f) + num4;
             rotation += (float)Math.PI / 2f;
             spriteDirection = (direction = ((!(velocity.X > 0f)) ? 1 : (-1)));
         }
         if (num2 < 1f)
         {
             FinalFractalHelper.FinalFractalProfile finalFractalProfile = FinalFractalHelper.GetFinalFractalProfile((int)ai[1]);
             Vector2 vector4 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
             Vector2 center = base.Center;
             int num11 = 1 + (int)(velocity.Length() / 100f);
             num11 = (int)((float)num11 * Utils.GetLerpValue(0f, 0.5f, lerpValue2, clamped: true) * Utils.GetLerpValue(1f, 0.5f, lerpValue2, clamped: true));
             if (num11 < 1)
             {
                 num11 = 1;
             }
             for (int i = 0; i < num11; i++)
             {
                 finalFractalProfile.dustMethod(center + vector4 * finalFractalProfile.trailWidth * MathHelper.Lerp(0.5f, 1f, Main.rand.NextFloat()), rotation - (float)Math.PI / 2f + (float)Math.PI / 2f * (float)spriteDirection, player.velocity);
             }
             Vector3 vector5 = finalFractalProfile.trailColor.ToVector3();
             Vector3 vector6 = Vector3.Lerp(Vector3.One, vector5, 0.7f);
             Lighting.AddLight(base.Center, vector5 * 0.5f * Opacity);
             Lighting.AddLight(mountedCenter, vector6 * Opacity * 0.15f);
         }
         Opacity = Utils.GetLerpValue(0f, 5f, localAI[0], clamped: true) * Utils.GetLerpValue(120f, 115f, localAI[0], clamped: true);
     }
References Lighting.AddLight(), FinalFractalHelper.FinalFractalProfile.dustMethod, FinalFractalHelper.GetFinalFractalProfile(), Utils.GetLerpValue(), SoundID.Item169, Player.MountedCenter, Main.player, SoundEngine.PlaySound(), Main.rand, and Entity.velocity.