Terraria: Projectile.GetLastPrismHue
GetLastPrismHue()
float Projectile.GetLastPrismHue (float laserIndex, ref float laserLuminance, ref float laserAlphaMultiplier) inline
     {
         if (Main.player[owner].active)
         {
             double timeForVisualEffects = Main.timeForVisualEffects;
             switch (Main.player[owner].name)
             {
             case "Cenx":
             {
                 float amount2 = Utils.PingPongFrom01To010(laserIndex / 6f);
                 amount2 = MathHelper.SmoothStep(0f, 1f, amount2);
                 amount2 = MathHelper.SmoothStep(0f, 1f, amount2);
                 return Main.rgbToHsl(Color.Lerp(new Color(0.3f, 1f, 0.2f), Color.HotPink, amount2)).X;
             }
             case "Crowno":
                 laserLuminance = MathHelper.Lerp(0.25f, 0.4f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.5f;
                 return MathHelper.Lerp(127f / 180f, 47f / 60f, Utils.Turn01ToCyclic010(laserIndex / 6f));
             case "Tsuki":
             case "Yoraiz0r":
                 return 0.92f;
             case "Lazure":
                 return MathHelper.Lerp(8f / 15f, 83f / 90f, Utils.Turn01ToCyclic010(laserIndex / 6f));
             case "Jaxrud":
                 return MathHelper.Lerp(13f / 72f, 0.43611112f, Utils.Turn01ToCyclic010(laserIndex / 6f));
             case "Ghostar":
                 laserLuminance = MathHelper.Lerp(0.4f, 0.7f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.3f;
                 return 0.66f;
             case "Devalaous":
                 return 0.66f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.1f;
             case "Leinfors":
                 return 0.73f + (float)Math.Cos(timeForVisualEffects / 3.0 * 6.2831854820251465) * 0.03f;
             case "Aeroblop":
                 return 0.25f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.1f;
             case "Doylee":
                 return 0.84f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.16f;
             case "Darkhalis":
             case "Arkhalis":
                 return 0.75f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.07f;
             case "Nike Leon":
                 return 0.07f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.04f;
             case "Suweeka":
                 return 0.5f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.18f;
             case "W1K":
                 return 0.75f + (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465) * 0.05f;
             case "Grox The Great":
                 return 0.41f + (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465) * 0.1f;
             case "Acamaeda":
                 return 0.18f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.1f;
             case "Alchemystics":
                 return 0.73f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.18f;
             case "Antithesis":
                 laserLuminance = 0.25f;
                 laserAlphaMultiplier = 0.4f;
                 return 0.7f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.05f;
             case "Aurora3500":
                 laserLuminance = MathHelper.Lerp(0f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.25f;
                 return 0.35f;
             case "Bame":
             {
                 float amount = Utils.PingPongFrom01To010(laserIndex / 6f);
                 amount = MathHelper.SmoothStep(0f, 1f, amount);
                 amount = MathHelper.SmoothStep(0f, 1f, amount);
                 return Main.rgbToHsl(Color.Lerp(Color.Yellow, new Color(0.2f, 0f, 0.7f), amount)).X;
             }
             case "Criddle":
                 return 0.91f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.19f;
             case "Darthkitten":
                 laserLuminance = MathHelper.Lerp(0.4f, 0.9f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.3f;
                 return 1f;
             case "darthmorf":
                 laserLuminance = MathHelper.Lerp(0f, 0.2f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.4f;
                 return 0f;
             case "Discipile":
                 laserLuminance = MathHelper.Lerp(0f, 0.4f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.35f;
                 return 0.55f;
             case "Jenosis":
                 return 0.66f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.08f;
             case "Kazzymodus":
                 laserLuminance = MathHelper.Lerp(0.6f, 0.8f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.3f;
                 return 0.33f;
             case "Khaios":
                 laserLuminance = MathHelper.Lerp(0f, 0.1f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.25f;
                 return 0.35f;
             case "Loki":
                 laserLuminance = MathHelper.Lerp(0f, 0.3f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 5.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.4f;
                 return 0f;
             case "ManaUser":
                 return 0.49f + (float)Math.Cos(timeForVisualEffects / 140.0 * 6.2831854820251465) * 0.08f;
             case "Mid":
                 laserLuminance = 0.25f;
                 laserAlphaMultiplier = 0.4f;
                 return 0.86f + (float)Math.Cos(timeForVisualEffects / 270.0 * 6.2831854820251465) * 0.13f;
             case "Nimbus":
                 laserLuminance = MathHelper.Lerp(0f, 0.3f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 20.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.2f;
                 return 0.75f;
             case "ppowersteef":
                 laserLuminance = MathHelper.Lerp(0.1f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.25f;
                 return 0.6f;
             case "RBrandon":
                 laserLuminance = MathHelper.Lerp(0f, 0.5f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 105.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.4f;
                 return 1f;
             case "Redigit":
                 return 0.7f;
             case "Serenity":
                 laserLuminance = MathHelper.Lerp(0.9f, 0.65f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.3f;
                 return 0.85f;
             case "Sigma":
                 return 0.06f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.06f;
             case "teiull":
                 return 0.5f + (float)Math.Cos(timeForVisualEffects / 45.0 * 6.2831854820251465) * 0.3f;
             case "Unit One":
                 return 0.38f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.24f;
             case "Vulpes Inculta":
                 return 0.7f + (float)Math.Cos(timeForVisualEffects / 180.0 * 6.2831854820251465) * 0.05f;
             case "Waze3174":
                 return 0.38f + (float)Math.Cos(timeForVisualEffects / 90.0 * 6.2831854820251465) * 0.24f;
             case "Xman101":
                 laserLuminance = MathHelper.Lerp(0.9f, 0.55f, Utils.GetLerpValue(-1f, 1f, (float)Math.Cos(timeForVisualEffects / 120.0 * 6.2831854820251465)));
                 laserAlphaMultiplier = 0.2f;
                 return 0.33f;
             case "Zoomo":
                 return 0.77f;
             case "Random":
                 return Main.rand.NextFloat();
             }
         }
         return (float)(int)laserIndex / 6f;
     }
References Entity.active, Color, Utils.GetLerpValue(), Player.name, owner, Utils.PingPongFrom01To010(), Main.player, Main.rand, Main.rgbToHsl(), Main.timeForVisualEffects, and Utils.Turn01ToCyclic010().
Referenced by Main.DrawProjDirect().