Terraria: Projectile.AI_137_CanHit
AI_137_CanHit()
bool Projectile.AI_137_CanHit (Vector2 targetPosition) inline
     {
         if (WorldGen.SolidTile((int)targetPosition.X / 16, (int)targetPosition.Y / 16))
         {
             return false;
         }
         Vector2 vector = base.Top + Vector2.UnitY * 20f;
         bool flag = Collision.CanHitLine(vector, 0, 0, targetPosition, 0, 0);
         if (!flag)
         {
             Vector2 v = targetPosition - vector;
             Vector2 spinningpoint = v.SafeNormalize(Vector2.UnitY);
             Vector2 vector2 = Vector2.Lerp(vector, targetPosition, 0.5f);
             Vector2 vector3 = vector2 + spinningpoint.RotatedBy(1.5707963705062866) * v.Length() * 0.2f;
             if (Collision.CanHitLine(vector, 0, 0, vector3, 0, 0) && Collision.CanHitLine(vector3, 0, 0, targetPosition, 0, 0))
             {
                 flag = true;
             }
             if (!flag)
             {
                 Vector2 vector4 = vector2 + spinningpoint.RotatedBy(-1.5707963705062866) * v.Length() * 0.2f;
                 if (Collision.CanHitLine(vector, 0, 0, vector4, 0, 0) && Collision.CanHitLine(vector4, 0, 0, targetPosition, 0, 0))
                 {
                     flag = true;
                 }
             }
         }
         return flag;
     }
References Collision.CanHitLine(), and WorldGen.SolidTile().
Referenced by Colliding().