Terraria: Projectile.UpdateEnchantmentVisuals
UpdateEnchantmentVisuals()
void Projectile.UpdateEnchantmentVisuals () inline private
     {
         if (npcProj)
         {
             return;
         }
         Vector2 boxPosition = position;
         int boxWidth = width;
         int boxHeight = height;
         if (aiStyle == 190 || aiStyle == 191)
         {
             for (float num = -(float)Math.PI / 4f; num <= (float)Math.PI / 4f; num += (float)Math.PI / 2f)
             {
                 Rectangle r = Utils.CenteredRectangle(base.Center + (rotation + num).ToRotationVector2() * 70f * scale, new Vector2(60f * scale, 60f * scale));
                 EmitEnchantmentVisualsAt(r.TopLeft(), r.Width, r.Height);
             }
         }
         else if (ProjectileID.Sets.IsAWhip[type])
         {
             WhipPointsForCollision.Clear();
             FillWhipControlPoints(this, WhipPointsForCollision);
             Vector2 vector = WhipPointsForCollision[WhipPointsForCollision.Count - 1];
             EmitEnchantmentVisualsAt(new Vector2(vector.X - (float)(width / 2), vector.Y - (float)(height / 2)), width, height);
         }
         else
         {
             EmitEnchantmentVisualsAt(boxPosition, boxWidth, boxHeight);
         }
     }
References aiStyle, Utils.CenteredRectangle(), EmitEnchantmentVisualsAt(), FillWhipControlPoints(), Entity.height, ProjectileID.Sets.IsAWhip, npcProj, Entity.position, rotation, scale, type, WhipPointsForCollision, and Entity.width.
Referenced by Update().