Terraria: Projectile.AI_061_FishingBobber_DoASplash
AI_061_FishingBobber_DoASplash()
void Projectile.AI_061_FishingBobber_DoASplash () inline private
     {
         for (int i = 0; i < 100; i++)
         {
             int num = Dust.NewDust(new Vector2(position.X - 6f, position.Y - 10f), width + 12, 24, Dust.dustWater());
             Main.dust[num].velocity.Y -= 4f;
             Main.dust[num].velocity.X *= 2.5f;
             Main.dust[num].scale = 0.8f;
             Main.dust[num].alpha = 100;
             Main.dust[num].noGravity = true;
         }
         SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 0);
     }
References Dust.alpha, Main.dust, Dust.dustWater(), Dust.NewDust(), Dust.noGravity, SoundEngine.PlaySound(), Dust.scale, and Dust.velocity.