Terraria: System.Net.Http.DiagnosticsHandler.SendAsyncCore
SendAsyncCore()
async ValueTask< HttpResponseMessage > System.Net.Http.DiagnosticsHandler.SendAsyncCore (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline private
Definition at line 188 of file DiagnosticsHandler.cs.
    {
        if (request == null)
        {
            throw new ArgumentNullException("request", System.SR.net_http_handler_norequest);
        }
        if (request.WasRedirected())
        {
            HeaderDescriptor[] propagatorFields = _propagatorFields;
            if (propagatorFields != null)
            {
                HeaderDescriptor[] array = propagatorFields;
                foreach (HeaderDescriptor descriptor in array)
                {
                    request.Headers.Remove(descriptor);
                }
            }
        }
        Activity activity2 = null;
        DiagnosticListener diagnosticListener = s_diagnosticListener;
        if (!diagnosticListener.IsEnabled())
        {
            activity2 = new Activity("System.Net.Http.HttpRequestOut");
            activity2.Start();
            InjectHeaders(activity2, request);
            try
            {
                return (!async) ? _innerHandler.Send(request, cancellationToken) : (await _innerHandler.SendAsync(request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false));
            }
            finally
            {
                activity2.Stop();
            }
        }
        Guid loggingRequestId = Guid.Empty;
        if (diagnosticListener.IsEnabled("System.Net.Http.HttpRequestOut", request))
        {
            activity2 = new Activity("System.Net.Http.HttpRequestOut");
            if (diagnosticListener.IsEnabled("System.Net.Http.HttpRequestOut.Start"))
            {
                StartActivity(diagnosticListener, activity2, new ActivityStartData(request));
            }
            else
            {
                activity2.Start();
            }
        }
        if (diagnosticListener.IsEnabled("System.Net.Http.Request"))
        {
            long timestamp = Stopwatch.GetTimestamp();
            loggingRequestId = Guid.NewGuid();
            Write(diagnosticListener, "System.Net.Http.Request", new RequestData(request, loggingRequestId, timestamp));
        }
        Activity current = Activity.Current;
        if (current != null)
        {
            InjectHeaders(current, request);
        }
        HttpResponseMessage response = null;
        TaskStatus taskStatus = TaskStatus.RanToCompletion;
        try
        {
            HttpResponseMessage httpResponseMessage = ((!async) ? _innerHandler.Send(request, cancellationToken) : (await _innerHandler.SendAsync(request, cancellationToken).ConfigureAwait(continueOnCapturedContext: false)));
            response = httpResponseMessage;
            return response;
        }
        catch (OperationCanceledException)
        {
            taskStatus = TaskStatus.Canceled;
            throw;
        }
        catch (Exception exception)
        {
            taskStatus = TaskStatus.Faulted;
            if (diagnosticListener.IsEnabled("System.Net.Http.Exception"))
            {
                Write(diagnosticListener, "System.Net.Http.Exception", new ExceptionData(exception, request));
            }
            throw;
        }
        finally
        {
            if (activity2 != null)
            {
                StopActivity(diagnosticListener, activity2, new ActivityStopData(response, request, taskStatus));
            }
            if (diagnosticListener.IsEnabled("System.Net.Http.Response"))
            {
                long timestamp2 = Stopwatch.GetTimestamp();
                Write(diagnosticListener, "System.Net.Http.Response", new ResponseData(response, loggingRequestId, timestamp2, taskStatus));
            }
        }
    }
References System.Net.Http.DiagnosticsHandler._innerHandler, System.Net.Http.DiagnosticsHandler._propagatorFields, System.array, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Diagnostics.Activity.Current, System.Guid.Empty, System.exception, System.Diagnostics.Stopwatch.GetTimestamp(), System.Net.Http.DiagnosticsHandler.InjectHeaders(), System.SR.net_http_handler_norequest, System.Guid.NewGuid(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), System.Net.Http.DiagnosticsHandler.s_diagnosticListener, System.Net.Http.HttpMessageHandler.Send(), and System.Net.Http.HttpMessageHandler.SendAsync().
Referenced by System.Net.Http.DiagnosticsHandler.SendAsync().