Terraria: Projectile.AI_194_HorsemanPumpkin
AI_194_HorsemanPumpkin()
void Projectile.AI_194_HorsemanPumpkin () inline private
     {
         int num = (int)ai[0];
         Vector2 center = base.Center;
         if (Main.player.IndexInRange(num))
         {
             Player player = Main.player[num];
             if (player.active && !player.dead)
             {
                 center = player.Center;
             }
         }
         Vector2 vector = center - base.Center;
         int num2 = 30;
         float num3 = 4f;
         float num4 = 5f;
         float num5 = 0.4f;
         float num6 = 0.4f;
         if (!(vector.Y < (float)num2) || !(vector.Y > (float)(-num2)))
         {
             float num7 = (float)Math.Sign(vector.Y) * num6;
             velocity.Y = Utils.Clamp(velocity.Y + num7, 0f - num4, num4);
         }
         velocity.X = Utils.Clamp(velocity.X + (float)Math.Sign(vector.X) * num5, 0f - num3, num3);
         rotation = velocity.ToRotation();
         spriteDirection = ((!(velocity.X < 0f)) ? 1 : (-1));
         if (timeLeft < 6)
         {
             Opacity -= 0.1f;
         }
         else
         {
             Opacity += 1f / 30f;
         }
         if (Main.rand.Next(3) != 0)
         {
             Dust dust = Dust.NewDustDirect(position, width, height, 6, velocity.X, velocity.Y);
             dust.scale = 0.6f;
             dust.fadeIn = 1.1f;
             dust.noGravity = true;
             dust.noLight = true;
         }
     }
References Entity.active, Entity.Center, Player.dead, Dust.fadeIn, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Main.player, Main.rand, Dust.scale, and Utils.ToRotation().