Terraria: Projectile.AI_178_FireExplosion
AI_178_FireExplosion()
void Projectile.AI_178_FireExplosion () inline private
     {
         if (localAI[0] == 0f)
         {
             SoundEngine.PlaySound(SoundID.Item14, position);
             for (int i = 0; i < 4; i++)
             {
                 int num = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
             }
             for (int j = 0; j < 30; j++)
             {
                 int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                 Main.dust[num2].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 Main.dust[num2].noGravity = true;
                 Main.dust[num2].velocity *= 3f;
                 num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                 Main.dust[num2].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 Main.dust[num2].velocity *= 2f;
                 Main.dust[num2].noGravity = true;
                 Main.dust[num2].fadeIn = 2.5f;
             }
             for (int k = 0; k < 10; k++)
             {
                 int num3 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                 Main.dust[num3].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                 Main.dust[num3].noGravity = true;
                 Main.dust[num3].velocity *= 3f;
             }
             for (int l = 0; l < 10; l++)
             {
                 int num4 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                 Main.dust[num4].position = base.Center + Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(velocity.ToRotation()) * width / 2f;
                 Main.dust[num4].noGravity = true;
                 Main.dust[num4].velocity *= 3f;
             }
             for (int m = 0; m < 2; m++)
             {
                 int num5 = Gore.NewGore(position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f, default(Vector2), Main.rand.Next(61, 64));
                 Main.gore[num5].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * width / 2f;
                 Main.gore[num5].velocity *= 0.3f;
                 Main.gore[num5].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                 Main.gore[num5].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
             }
         }
         localAI[0] += 1f;
         if (localAI[0] >= 10f)
         {
             Kill();
         }
     }
References Color, Main.dust, Dust.fadeIn, Main.gore, SoundID.Item14, Dust.NewDust(), Gore.NewGore(), UnifiedRandom.Next(), UnifiedRandom.NextDouble(), Dust.noGravity, SoundEngine.PlaySound(), Dust.position, Gore.position, Main.rand, Dust.velocity, and Gore.velocity.