Terraria: Projectile.GasTrapCheck
GasTrapCheck()
static bool Projectile.GasTrapCheck (int x, int y, Player user) inline static
     {
         if (Main.netMode == 1)
         {
             return false;
         }
         int num = Chest.FindChest(x, y);
         if (num < 0)
         {
             return false;
         }
         Chest chest = Main.chest[num];
         int num2 = 16;
         int num3 = 16;
         bool flag = false;
         for (int i = 0; i < 40; i++)
         {
             ushort num4 = Main.tile[chest.x, chest.y].type;
             if (TileObjectData.CustomPlace(num4, 0))
             {
                 TileObjectData tileData = TileObjectData.GetTileData(num4, 0);
                 if (tileData != null)
                 {
                     int num5 = (int)Math.Ceiling((float)tileData.Width / 2f);
                     int num6 = (int)Math.Ceiling((float)tileData.Width / 2f);
                     num2 = num5 * 16;
                     num3 = num6 * 16;
                     if (num5 % 2 != 0)
                     {
                         num2 += 8;
                     }
                     if (num6 % 2 != 0)
                     {
                         num3 += 8;
                     }
                 }
             }
             if (chest.item[i] != null && chest.item[i].type == 5346)
             {
                 UseGasTrapInChest(num, chest, i, num2, num3);
                 flag = true;
                 break;
             }
         }
         if (flag)
         {
             num3 -= 8;
             NewProjectile(position: new Vector2(x * 16 + num2, y * 16 + num3), spawnSource: user.GetProjectileSource_TileInteraction(x, y), velocity: Vector2.Zero, Type: 1007, Damage: 10, KnockBack: 0f, Owner: Main.myPlayer);
         }
         return flag;
     }
References Main.chest, TileObjectData.CustomPlace(), Damage, Chest.FindChest(), Player.GetProjectileSource_TileInteraction(), TileObjectData.GetTileData(), Chest.item, Main.myPlayer, Main.netMode, Main.tile, Item.type, Tile.type, TileObjectData.Width, Chest.x, and Chest.y.
Referenced by Player.Update().