Terraria: Terraria.GameContent.UI.Elements.GroupOptionButton.GroupOptionButton
GroupOptionButton()
Terraria.GameContent.UI.Elements.GroupOptionButton< T >.GroupOptionButton (T option, LocalizedText title, LocalizedText description, Color textColor, string iconTexturePath, float textSize = 1f, float titleAlignmentX = 0::5f, float titleWidthReduction = 10f) inline
    {
        _borderColor = Color.White;
        _currentOption = option;
        _myOption = option;
        Description = description;
        Width = StyleDimension.FromPixels(44f);
        Height = StyleDimension.FromPixels(34f);
        _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
        _selectedBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
        _hoveredBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelBorder", (AssetRequestMode)1);
        if (iconTexturePath != null)
        {
            _iconTexture = Main.Assets.Request<Texture2D>(iconTexturePath, (AssetRequestMode)1);
        }
        _color = Colors.InventoryDefaultColor;
        if (title != null)
        {
            UIText uIText = new UIText(title, textSize)
            {
                HAlign = titleAlignmentX,
                VAlign = 0.5f,
                Width = StyleDimension.FromPixelsAndPercent(0f - titleWidthReduction, 1f),
                Top = StyleDimension.FromPixels(0f)
            };
            uIText.TextColor = textColor;
            Append(uIText);
            _title = uIText;
        }
    }
References Terraria.GameContent.UI.Elements.GroupOptionButton< T >._BasePanelTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._borderColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._color, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._currentOption, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._hoveredBorderTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._iconTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._myOption, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._selectedBorderTexture, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._title, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.Description, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.ID.Colors.InventoryDefaultColor, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.