Terraria: Terraria.GameContent.UI.Elements.GroupOptionButton.SetColorsBasedOnSelectionState
SetColorsBasedOnSelectionState()
void Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColorsBasedOnSelectionState (Color pickedColor, Color unpickedColor, float opacityPicked, float opacityNotPicked) inline
Implements Terraria.GameContent.UI.Elements.IGroupOptionButton.
Definition at line 190 of file GroupOptionButton.cs.
    {
        _UseOverrideColors = true;
        _overridePickedColor = pickedColor;
        _overrideUnpickedColor = unpickedColor;
        _overrideOpacityPicked = opacityPicked;
        _overrideOpacityUnpicked = opacityNotPicked;
    }
References Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overrideOpacityPicked, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overrideOpacityUnpicked, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overridePickedColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >._overrideUnpickedColor, and Terraria.GameContent.UI.Elements.GroupOptionButton< T >._UseOverrideColors.
Referenced by Terraria.GameContent.Creative.CreativePowersHelper.CreateCategoryButton< T >(), Terraria.GameContent.Creative.CreativePowersHelper.CreateSimpleButton(), and Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton().