Terraria: Terraria.GameContent.UI.Elements.GroupOptionButton.SetText
SetText()
void Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetText (LocalizedText text, float textSize, Color color) inline
    {
        if (_title != null)
        {
            _title.Remove();
        }
        UIText uIText = new UIText(text, textSize)
        {
            HAlign = 0.5f,
            VAlign = 0.5f,
            Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
            Top = StyleDimension.FromPixels(0f)
        };
        uIText.TextColor = color;
        Append(uIText);
        _title = uIText;
    }
References Terraria.GameContent.UI.Elements.GroupOptionButton< T >._title, Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Remove(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.