Terraria: Terraria.UI.ItemSlot.AfterItemSwap
AfterItemSwap()
static void Terraria.UI.ItemSlot.AfterItemSwap (int oldType, int newType) inline static private
Definition at line 1703 of file ItemSlot.cs.
    {
        if (newType == 5324 || newType == 5329 || newType == 5330 || newType == 4346 || newType == 5391 || newType == 5358 || newType == 5361 || newType == 5360 || newType == 5359)
        {
            SoundEngine.PlaySound(22);
        }
        else
        {
            SoundEngine.PlaySound(7);
        }
        Main.stackSplit = 30;
        Main.mouseRightRelease = false;
        Recipe.FindRecipes();
    }
References Terraria.Recipe.FindRecipes(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.UI.ItemSlot.TryItemSwap().