Terraria: Terraria.UI.ItemSlot.GetItemLight
GetItemLight() [2/4]
static void Terraria.UI.ItemSlot.GetItemLight (ref Color currentColor, Item item, bool outInTheWorld = false) inline static
    {
        float scale = 1f;
        GetItemLight(ref currentColor, ref scale, item, outInTheWorld);
    }
References Terraria.UI.ItemSlot.GetItemLight().
Referenced by Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItem_GetColorAndScale(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.UI.ItemSlot.GetItemLight(), and Terraria.UI.ItemSlot.GetItemLight().