Terraria: Terraria.UI.ItemSlot.GetOverrideInstructions
GetOverrideInstructions()
static string Terraria.UI.ItemSlot.GetOverrideInstructions (Item[] inv, int context, int slot) inline static private
Definition at line 1067 of file ItemSlot.cs.
    {
        Player player = Main.player[Main.myPlayer];
        TileEntity tileEntity = player.tileEntityAnchor.GetTileEntity();
        if (tileEntity != null && tileEntity.TryGetItemGamepadOverrideInstructions(inv, context, slot, out var instruction))
        {
            return instruction;
        }
        if (inv[slot].type > 0 && inv[slot].stack > 0)
        {
            if (!inv[slot].favorited)
            {
                switch (context)
                {
                case 0:
                case 1:
                case 2:
                    if (Main.npcShop > 0 && !inv[slot].favorited)
                    {
                        return Lang.misc[75].Value;
                    }
                    if (Main.player[Main.myPlayer].chest != -1)
                    {
                        if (ChestUI.TryPlacingInChest(inv[slot], justCheck: true, context))
{
                            return Lang.misc[76].Value;
                        }
                    }
                    else if (Main.InGuideCraftMenu && inv[slot].material)
                    {
                        return Lang.misc[76].Value;
                    }
                    if (Main.mouseItem.type > 0 && (context == 0 || context == 1 || context == 2 || context == 6 || context == 15 || context == 7 || context == 4 || context == 32 || context == 3))
                    {
                        return null;
                    }
                    return Lang.misc[74].Value;
                case 3:
                case 4:
                case 32:
                    if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                    {
                        return Lang.misc[76].Value;
                    }
                    break;
                case 5:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                case 16:
                case 17:
                case 18:
                case 19:
                case 20:
                case 25:
                case 27:
                case 33:
                    if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                    {
                        return Lang.misc[68].Value;
                    }
                    break;
                }
            }
            bool flag = false;
            if ((uint)context <= 4u || context == 32)
            {
                flag = player.chest == -1;
            }
            if (flag)
            {
                if (Main.npcShop > 0 && !inv[slot].favorited)
                {
                    _ = Main.instance.shop[Main.npcShop];
                    if (inv[slot].type >= 71 && inv[slot].type <= 74)
                    {
                        return "";
                    }
                    return Lang.misc[75].Value;
                }
                if (!inv[slot].favorited)
                {
                    return Lang.misc[74].Value;
                }
            }
        }
        return "";
    }
References Terraria.Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Terraria.Player.chest, Terraria.Item.favorited, Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.Main.InGuideCraftMenu, Terraria.Main.instance, Terraria.Player.ItemSpace(), Terraria.Item.material, Terraria.Lang.misc, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.npcShop, Terraria.Main.player, Terraria.Main.shop, Terraria.Player.tileEntityAnchor, Terraria.DataStructures.TileEntity.TryGetItemGamepadOverrideInstructions(), Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.Item.type, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.UI.ItemSlot.GetGamepadInstructions().