Terraria: Terraria.UI.ItemSlot.GetGamepadPointForSlot
GetGamepadPointForSlot()
static int Terraria.UI.ItemSlot.GetGamepadPointForSlot (Item[] inv, int context, int slot) inline static private
Definition at line 2333 of file ItemSlot.cs.
    {
        Player localPlayer = Main.LocalPlayer;
        int result = -1;
        switch (context)
        {
        case 0:
        case 1:
        case 2:
            result = slot;
            break;
        case 8:
        case 9:
        case 10:
        case 11:
        {
            int num2 = slot;
            if (num2 % 10 == 9 && !localPlayer.CanDemonHeartAccessoryBeShown())
            {
                num2--;
            }
            result = 100 + num2;
            break;
        }
        case 12:
            if (inv == localPlayer.dye)
            {
                int num = slot;
                if (num % 10 == 9 && !localPlayer.CanDemonHeartAccessoryBeShown())
                {
                    num--;
                }
                result = 120 + num;
            }
            break;
        case 33:
            if (inv == localPlayer.miscDyes)
            {
                result = 185 + slot;
            }
            break;
        case 19:
            result = 180;
            break;
        case 20:
            result = 181;
            break;
        case 18:
            result = 182;
            break;
        case 17:
            result = 183;
            break;
        case 16:
            result = 184;
            break;
        case 3:
        case 4:
        case 32:
            result = 400 + slot;
            break;
        case 15:
            result = 2700 + slot;
            break;
        case 6:
            result = 300;
            break;
        case 22:
            if (UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig != -1)
            {
                result = 700 + UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig;
            }
            if (UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall != -1)
            {
                result = 1500 + UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall + 1;
            }
            break;
        case 7:
            result = 1500;
            break;
        case 5:
            result = 303;
            break;
        case 23:
            result = 5100 + slot;
            break;
        case 24:
            result = 5100 + slot;
            break;
        case 25:
            result = 5108 + slot;
            break;
        case 26:
            result = 5000 + slot;
            break;
        case 27:
            result = 5002 + slot;
            break;
        case 29:
            result = 3000 + slot;
            if (UILinkPointNavigator.Shortcuts.CREATIVE_ItemSlotShouldHighlightAsSelected)
            {
                result = UILinkPointNavigator.CurrentPoint;
            }
            break;
        case 30:
            result = 15000 + slot;
            break;
        }
        return result;
    }
References Terraria.Player.CanDemonHeartAccessoryBeShown(), Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.CREATIVE_ItemSlotShouldHighlightAsSelected, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.Player.dye, Terraria.Main.LocalPlayer, and Terraria.Player.miscDyes.
Referenced by Terraria.UI.ItemSlot.Draw(), and Terraria.UI.ItemSlot.OverrideHover().