Terraria: Terraria.UI.ItemSlot.TryOpenContainer
TryOpenContainer()
static void Terraria.UI.ItemSlot.TryOpenContainer (Item item, Player player) inline static private
Definition at line 1490 of file ItemSlot.cs.
    {
        if (ItemID.Sets.BossBag[item.type])
        {
            player.OpenBossBag(item.type);
        }
        else if (ItemID.Sets.IsFishingCrate[item.type])
        {
            player.OpenFishingCrate(item.type);
        }
        else if (item.type == 3093)
        {
            player.OpenHerbBag(3093);
        }
        else if (item.type == 4345)
        {
            player.OpenCanofWorms(item.type);
        }
        else if (item.type == 4410)
        {
            player.OpenOyster(item.type);
        }
        else if (item.type == 1774)
        {
            player.OpenGoodieBag(1774);
        }
        else if (item.type == 3085)
        {
            if (!player.ConsumeItem(327, reverseOrder: false, includeVoidBag: true))
            {
                return;
            }
            player.OpenLockBox(3085);
        }
        else if (item.type == 4879)
        {
            if (!player.HasItemInInventoryOrOpenVoidBag(329))
            {
                return;
            }
            player.OpenShadowLockbox(4879);
        }
        else if (item.type == 1869)
        {
            player.OpenPresent(1869);
        }
        else
        {
            if (item.type != 599 && item.type != 600 && item.type != 601)
            {
                return;
            }
            player.OpenLegacyPresent(item.type);
        }
        item.stack--;
        if (item.stack == 0)
        {
            item.SetDefaults();
        }
        SoundEngine.PlaySound(7);
        Main.stackSplit = 30;
        Main.mouseRightRelease = false;
        Recipe.FindRecipes();
    }
References Terraria.ID.ItemID.Sets.BossBag, Terraria.Player.ConsumeItem(), Terraria.Recipe.FindRecipes(), Terraria.Player.HasItemInInventoryOrOpenVoidBag(), Terraria.ID.ItemID.Sets.IsFishingCrate, Terraria.Player.OpenBossBag(), Terraria.Player.OpenCanofWorms(), Terraria.Player.OpenFishingCrate(), Terraria.Player.OpenGoodieBag(), Terraria.Player.OpenHerbBag(), Terraria.Player.OpenLegacyPresent(), Terraria.Player.OpenLockBox(), Terraria.Player.OpenOyster(), Terraria.Player.OpenPresent(), Terraria.Player.OpenShadowLockbox(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.RightClick().