Terraria: Terraria.UI.ItemSlot.RefreshStackSplitCooldown
RefreshStackSplitCooldown()
static void Terraria.UI.ItemSlot.RefreshStackSplitCooldown () inline static
    {
        if (Main.stackSplit == 0)
        {
            Main.stackSplit = 30;
        }
        else
        {
            Main.stackSplit = Main.stackDelay;
        }
    }
References Terraria.Main.stackDelay, and Terraria.Main.stackSplit.
Referenced by Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Main.HoverOverCraftingItemButton(), Terraria.Initializers.UILinksInitializer.Load(), and Terraria.UI.ItemSlot.RightClick().