Terraria: Terraria.UI.ItemSlot.EquipSwap
EquipSwap()
static Item Terraria.UI.ItemSlot.EquipSwap (Item item, Item[] inv, int slot, out bool success) inline static private
    {
        success = false;
        _ = Main.player[Main.myPlayer];
        item.favorited = false;
        Item result = inv[slot].Clone();
        inv[slot] = item.Clone();
        SoundEngine.PlaySound(7);
        Recipe.FindRecipes();
        success = true;
        return result;
    }
References Terraria.Item.Clone(), Terraria.Recipe.FindRecipes(), Terraria.Main.myPlayer, Terraria.Main.player, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.UI.ItemSlot.SwapEquip().