Terraria: Terraria.UI.ItemSlot.Handle
Handle() [1/2]
static void Terraria.UI.ItemSlot.Handle (Item[] inv, int context = 0, int slot = 0) inline static
Definition at line 310 of file ItemSlot.cs.
    {
        OverrideHover(inv, context, slot);
        LeftClick(inv, context, slot);
        RightClick(inv, context, slot);
        if (Main.mouseLeftRelease && Main.mouseLeft)
        {
            Recipe.FindRecipes();
        }
        MouseHover(inv, context, slot);
    }
References Terraria.Recipe.FindRecipes(), Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.UI.ItemSlot.OverrideHover(), and Terraria.UI.ItemSlot.RightClick().