Terraria: Terraria.UI.ItemSlot.TryPickupDyeToCursor
TryPickupDyeToCursor()
static void Terraria.UI.ItemSlot.TryPickupDyeToCursor (int context, Item[] inv, int slot, Player player) inline static private
    {
        bool flag = false;
        if (!flag && ((Main.mouseItem.stack < Main.mouseItem.maxStack && Main.mouseItem.type > 0) || Main.mouseItem.IsAir) && inv[slot].type > 0 && (Main.mouseItem.type == inv[slot].type || Main.mouseItem.IsAir))
        {
            flag = true;
            if (Main.mouseItem.IsAir)
            {
                Main.mouseItem = inv[slot].Clone();
            }
            else
            {
                Main.mouseItem.stack++;
            }
            inv[slot].SetDefaults();
            SoundEngine.PlaySound(7);
        }
        if (flag)
        {
            if (context == 25 && Main.netMode == 1)
            {
                NetMessage.SendData(121, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
            }
            if (context == 27 && Main.netMode == 1)
            {
                NetMessage.SendData(124, -1, -1, null, Main.myPlayer, player.tileEntityAnchor.interactEntityID, slot, 1f);
            }
        }
    }
References Terraria.Item.Clone(), Terraria.DataStructures.PlayerInteractionAnchor.interactEntityID, Terraria.Item.IsAir, Terraria.Item.maxStack, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Player.tileEntityAnchor, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.RightClick().