Terraria: Terraria.UI.ItemSlot.ArmorSwap
ArmorSwap()
static Item Terraria.UI.ItemSlot.ArmorSwap (Item item, out bool success) inline static private
Definition at line 2730 of file ItemSlot.cs.
    {
        success = false;
        if (item.stack < 1)
        {
            return item;
        }
        if (item.headSlot == -1 && item.bodySlot == -1 && item.legSlot == -1 && !item.accessory)
        {
            return item;
        }
        Player player = Main.player[Main.myPlayer];
        int num = ((item.vanity && !item.accessory) ? 10 : 0);
        item.favorited = false;
        Item result = item;
        if (item.headSlot != -1)
        {
            result = player.armor[num].Clone();
            player.armor[num] = item.Clone();
        }
        else if (item.bodySlot != -1)
        {
            result = player.armor[num + 1].Clone();
            player.armor[num + 1] = item.Clone();
        }
        else if (item.legSlot != -1)
        {
            result = player.armor[num + 2].Clone();
            player.armor[num + 2] = item.Clone();
        }
        else if (item.accessory)
        {
            int num2 = 3;
            for (int i = 3; i < 10; i++)
            {
                if (player.IsItemSlotUnlockedAndUsable(i))
                {
                    num2 = i;
                    if (player.armor[i].type == 0)
                    {
                        accSlotToSwapTo = i - 3;
                        break;
                    }
                }
            }
            for (int j = 0; j < player.armor.Length; j++)
            {
                if (item.IsTheSameAs(player.armor[j]))
                {
                    accSlotToSwapTo = j - 3;
                }
                if (j < 10 && item.wingSlot > 0 && player.armor[j].wingSlot > 0)
                {
                    accSlotToSwapTo = j - 3;
                }
            }
            if (accSlotToSwapTo > num2)
            {
                return item;
            }
            if (accSlotToSwapTo < 0)
            {
                accSlotToSwapTo = num2 - 3;
            }
            int num3 = 3 + accSlotToSwapTo;
            if (isEquipLocked(player.armor[num3].type))
            {
                return item;
            }
            for (int k = 0; k < player.armor.Length; k++)
            {
                if (item.IsTheSameAs(player.armor[k]))
                {
                    num3 = k;
                }
            }
            result = player.armor[num3].Clone();
            player.armor[num3] = item.Clone();
            accSlotToSwapTo = 0;
        }
        SoundEngine.PlaySound(7);
        Recipe.FindRecipes();
        success = true;
        return result;
    }
References Terraria.Item.accessory, Terraria.UI.ItemSlot.accSlotToSwapTo, Terraria.Player.armor, Terraria.Item.bodySlot, Terraria.Item.Clone(), Terraria.Recipe.FindRecipes(), Terraria.Item.headSlot, Terraria.UI.ItemSlot.isEquipLocked(), Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Item.IsTheSameAs(), Terraria.Item.legSlot, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.stack, Terraria.Item.type, and Terraria.Item.wingSlot.
Referenced by Terraria.UI.ItemSlot.SwapEquip().