Terraria: System.Linq.Enumerable.ConcatNIterator.LazyToArray
LazyToArray()
TSource[] System.Linq.Enumerable.ConcatNIterator< TSource >.LazyToArray () inline private
Definition at line 492 of file Enumerable.cs.
        {
            SparseArrayBuilder<TSource> sparseArrayBuilder = new SparseArrayBuilder<TSource>(initialize: true);
            System.Collections.Generic.ArrayBuilder<int> arrayBuilder = default(System.Collections.Generic.ArrayBuilder<int>);
            int num = 0;
            while (true)
            {
                IEnumerable<TSource> enumerable = GetEnumerable(num);
                if (enumerable == null)
                {
                    break;
                }
                if (sparseArrayBuilder.ReserveOrAdd(enumerable))
                {
                    arrayBuilder.Add(num);
                }
                num++;
            }
            TSource[] array = sparseArrayBuilder.ToArray();
            System.Collections.Generic.ArrayBuilder<Marker> markers = sparseArrayBuilder.Markers;
            for (int i = 0; i < markers.Count; i++)
            {
                Marker marker = markers[i];
                IEnumerable<TSource> enumerable2 = GetEnumerable(arrayBuilder[i]);
                System.Collections.Generic.EnumerableHelpers.Copy(enumerable2, array, marker.Index, marker.Count);
            }
            return array;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Linq.enumerable, and System.Linq.Enumerable.ConcatNIterator< TSource >.GetEnumerable().
Referenced by System.Linq.Enumerable.ConcatNIterator< TSource >.ToArray().