Terraria: System.Xml.Serialization.IndentedWriter.WriteLine
WriteLine() [2/2]
void System.Xml.Serialization.IndentedWriter.WriteLine (string s) inline package
Definition at line 51 of file IndentedWriter.cs.
    {
        if (_needIndent)
        {
            WriteIndent();
        }
        _writer.WriteLine(s);
        _needIndent = true;
    }
References System.Xml.Serialization.IndentedWriter._needIndent, System.Xml.Serialization.IndentedWriter._writer, System.s, System.Xml.Serialization.IndentedWriter.WriteIndent(), and System.IO.TextWriter.WriteLine().
Referenced by System.Xml.Serialization.XmlSerializationCodeGen.GenerateBaseSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationCodeGen.GeneratePublicMethods(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateSerializerContract(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializer(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateTypedSerializers(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteArrayLocalDecl(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteAssemblyInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteCreateInstance(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteDefaultIndexerInit(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteLocalDecl(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMemberInfo(), System.Xml.Serialization.ReflectionAwareCodeGen.WriteMethodInfo(), and System.Xml.Serialization.ReflectionAwareCodeGen.WriteTypeInfo().