Terraria: System.Data.SqlTypes.SqlMoney.ToDouble
ToDouble()
double System.Data.SqlTypes.SqlMoney.ToDouble () inline
Definition at line 128 of file SqlMoney.cs.
    {
        return decimal.ToDouble(ToDecimal());
    }
References System.Data.SqlTypes.SqlMoney.ToDecimal().
Referenced by System.Data.SqlTypes.SqlDouble.operator SqlDouble(), and System.Data.SqlTypes.SqlSingle.operator SqlSingle().