Terraria: System.Data.SqlTypes.SqlMoney.Null
Null
readonly SqlMoney System.Data.SqlTypes.SqlMoney.Null = new SqlMoney(fNull: true) static
Definition at line 17 of file SqlMoney.cs.
Referenced by System.Data.Common.SqlConvert.ConvertToSqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator SqlMoney(), System.Data.SqlTypes.SqlMoney.operator*(), System.Data.SqlTypes.SqlMoney.operator+(), System.Data.SqlTypes.SqlMoney.operator-(), System.Data.SqlTypes.SqlMoney.operator-(), System.Data.SqlTypes.SqlMoney.operator/(), and System.Data.SqlTypes.SqlMoney.Parse().