Terraria: MapTile.Equals
Equals()
bool MapTile.Equals (ref MapTile other) inline
     {
         if (Light == other.Light && Type == other.Type)
         {
             return Color == other.Color;
         }
         return false;
     }
References Color, Light, and Type.
Referenced by Main.DrawToMap(), MapHelper.InternalSaveMap(), WorldMap.UpdateLighting(), and WorldMap.UpdateType().