Terraria: EmojiCommand.ProcessOutgoingMessage
ProcessOutgoingMessage()
void EmojiCommand.ProcessOutgoingMessage (ChatMessage message) inline
Implements IChatCommand.
     {
         int result = -1;
         if (int.TryParse(message.Text, out result))
         {
             if (result < 0 || result >= EmoteID.Count)
             {
                 return;
             }
         }
         else
         {
             result = -1;
         }
         if (result == -1)
         {
             foreach (LocalizedText key in _byName.Keys)
             {
                 if (message.Text == key.Value)
                 {
                     result = _byName[key];
                     break;
                 }
             }
         }
         if (result != -1)
         {
             if (Main.netMode == 0)
             {
                 EmoteBubble.NewBubble(result, new WorldUIAnchor(Main.LocalPlayer), 360);
                 EmoteBubble.CheckForNPCsToReactToEmoteBubble(result, Main.LocalPlayer);
             }
             else
             {
                 NetMessage.SendData(120, -1, -1, null, Main.myPlayer, result);
             }
         }
         message.Consume();
     }
References _byName, EmoteBubble.CheckForNPCsToReactToEmoteBubble(), ChatMessage.Consume(), EmoteID.Count, Main.LocalPlayer, Main.myPlayer, Main.netMode, EmoteBubble.NewBubble(), NetMessage.SendData(), ChatMessage.Text, and LocalizedText.Value.