Terraria: System.Xml.Schema.Preprocessor.CountGroupSelfReference
CountGroupSelfReference()
int System.Xml.Schema.Preprocessor.CountGroupSelfReference (XmlSchemaObjectCollection items, XmlQualifiedName name, XmlSchemaGroup redefined) inline private
Definition at line 915 of file Preprocessor.cs.
    {
        int num = 0;
        for (int i = 0; i < items.Count; i++)
        {
            if (items[i] is XmlSchemaGroupRef xmlSchemaGroupRef)
            {
                if (xmlSchemaGroupRef.RefName == name)
                {
                    xmlSchemaGroupRef.Redefined = redefined;
                    if (xmlSchemaGroupRef.MinOccurs != 1m || xmlSchemaGroupRef.MaxOccurs != 1m)
                    {
                        SendValidationEvent(System.SR.Sch_MinMaxGroupRedefine, xmlSchemaGroupRef);
                    }
                    num++;
                }
            }
            else if (items[i] is XmlSchemaGroupBase)
            {
                num += CountGroupSelfReference(((XmlSchemaGroupBase)items[i]).Items, name, redefined);
            }
            if (num > 1)
            {
                break;
            }
        }
        return num;
    }
References System.Collections.CollectionBase.Count, System.Xml.Schema.Preprocessor.CountGroupSelfReference(), System.Xml.Dictionary, System.SR.Sch_MinMaxGroupRedefine, and System.Xml.Schema.BaseProcessor.SendValidationEvent().
Referenced by System.Xml.Schema.Preprocessor.CheckRefinedGroup(), and System.Xml.Schema.Preprocessor.CountGroupSelfReference().