Terraria: System.Xml.Schema.Preprocessor.ValidateIdAttribute
ValidateIdAttribute()
void System.Xml.Schema.Preprocessor.ValidateIdAttribute (XmlSchemaObject xso) inline private
Definition at line 1865 of file Preprocessor.cs.
    {
        if (xso.IdAttribute != null)
        {
            try
            {
                xso.IdAttribute = base.NameTable.Add(XmlConvert.VerifyNCName(xso.IdAttribute));
            }
            catch (XmlException ex)
            {
                SendValidationEvent(System.SR.Sch_InvalidIdAttribute, new string[1] { ex.Message }, ex, xso);
                return;
            }
            catch (ArgumentNullException)
            {
                SendValidationEvent(System.SR.Sch_InvalidIdAttribute, System.SR.Sch_NullValue, xso);
                return;
            }
            try
            {
                _currentSchema.Ids.Add(xso.IdAttribute, xso);
            }
            catch (ArgumentException)
            {
                SendValidationEvent(System.SR.Sch_DupIdAttribute, xso);
            }
        }
    }
References System.Xml.Schema.Preprocessor._currentSchema, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaObject.IdAttribute, System.Xml.Schema.XmlSchema.Ids, System.SR.Sch_DupIdAttribute, System.SR.Sch_InvalidIdAttribute, System.SR.Sch_NullValue, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessAttribute(), System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), System.Xml.Schema.Preprocessor.PreprocessAttributes(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElement(), System.Xml.Schema.Preprocessor.PreprocessGroup(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessNotation(), System.Xml.Schema.Preprocessor.PreprocessParticle(), and System.Xml.Schema.Preprocessor.PreprocessSimpleType().