Terraria: System.Xml.Schema.Preprocessor.ValidateNameAttribute
ValidateNameAttribute()
void System.Xml.Schema.Preprocessor.ValidateNameAttribute (XmlSchemaObject xso) inline private
Definition at line 1894 of file Preprocessor.cs.
    {
        string nameAttribute = xso.NameAttribute;
        if (nameAttribute == null || nameAttribute.Length == 0)
        {
            SendValidationEvent(System.SR.Sch_InvalidNameAttributeEx, null, System.SR.Sch_NullValue, xso);
        }
        nameAttribute = XmlComplianceUtil.NonCDataNormalize(nameAttribute ?? string.Empty);
        int num = ValidateNames.ParseNCName(nameAttribute, 0);
        if (num != nameAttribute.Length)
        {
            string[] array = XmlException.BuildCharExceptionArgs(nameAttribute, num);
            string msg = System.SR.Format(System.SR.Xml_BadNameCharWithPos, array[0], array[1], num);
            SendValidationEvent(System.SR.Sch_InvalidNameAttributeEx, nameAttribute, msg, xso);
        }
        else
        {
            xso.NameAttribute = base.NameTable.Add(nameAttribute);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.XmlSchemaObject.NameAttribute, System.Xml.XmlComplianceUtil.NonCDataNormalize(), System.Xml.ValidateNames.ParseNCName(), System.SR.Sch_InvalidNameAttributeEx, System.SR.Sch_NullValue, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.SR.Xml_BadNameCharWithPos.
Referenced by System.Xml.Schema.Preprocessor.PreprocessAttribute(), System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElement(), System.Xml.Schema.Preprocessor.PreprocessGroup(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessNotation(), and System.Xml.Schema.Preprocessor.PreprocessSimpleType().