Terraria: System.Xml.Schema.Preprocessor.PreprocessAttributes
PreprocessAttributes()
void System.Xml.Schema.Preprocessor.PreprocessAttributes (XmlSchemaObjectCollection attributes, XmlSchemaAnyAttribute anyAttribute, XmlSchemaObject parent) inline private
Definition at line 1827 of file Preprocessor.cs.
    {
        for (int i = 0; i < attributes.Count; i++)
        {
            SetParent(attributes[i], parent);
            if (attributes[i] is XmlSchemaAttribute attribute)
            {
                PreprocessLocalAttribute(attribute);
                continue;
            }
            XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef = (XmlSchemaAttributeGroupRef)attributes[i];
            if (xmlSchemaAttributeGroupRef.RefName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_MissAttribute, "ref", xmlSchemaAttributeGroupRef);
            }
            else
            {
                ValidateQNameAttribute(xmlSchemaAttributeGroupRef, "ref", xmlSchemaAttributeGroupRef.RefName);
            }
            PreprocessAnnotation(attributes[i]);
            ValidateIdAttribute(attributes[i]);
        }
        if (anyAttribute != null)
        {
            try
            {
                SetParent(anyAttribute, parent);
                PreprocessAnnotation(anyAttribute);
                anyAttribute.BuildNamespaceList(_targetNamespace);
            }
            catch (FormatException ex)
            {
                SendValidationEvent(System.SR.Sch_InvalidAnyDetailed, new string[1] { ex.Message }, ex, anyAttribute);
            }
            ValidateIdAttribute(anyAttribute);
        }
    }
References System.Xml.Schema.Preprocessor._targetNamespace, System.Collections.CollectionBase.Count, System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.SR.Sch_InvalidAnyDetailed, System.SR.Sch_MissAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.SetParent(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), and System.Xml.Schema.Preprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), and System.Xml.Schema.Preprocessor.PreprocessComplexType().