Terraria: System.Xml.Schema.Preprocessor.PreprocessAttributeContent
PreprocessAttributeContent()
void System.Xml.Schema.Preprocessor.PreprocessAttributeContent (XmlSchemaAttribute attribute) inline private
Definition at line 1062 of file Preprocessor.cs.
    {
        PreprocessAnnotation(attribute);
        if (Ref.Equal(_currentSchema.TargetNamespace, _nsXsi))
        {
            SendValidationEvent(System.SR.Sch_TargetNamespaceXsi, attribute);
        }
        if (!attribute.RefName.IsEmpty)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "ref", attribute);
        }
        if (attribute.DefaultValue != null && attribute.FixedValue != null)
        {
            SendValidationEvent(System.SR.Sch_DefaultFixedAttributes, attribute);
        }
        if (attribute.DefaultValue != null && attribute.Use != XmlSchemaUse.Optional && attribute.Use != 0)
        {
            SendValidationEvent(System.SR.Sch_OptionalDefaultAttribute, attribute);
        }
        if (attribute.Name == _xmlns)
        {
            SendValidationEvent(System.SR.Sch_XmlNsAttribute, attribute);
        }
        if (attribute.SchemaType != null)
        {
            SetParent(attribute.SchemaType, attribute);
            if (!attribute.SchemaTypeName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_TypeMutualExclusive, attribute);
            }
            PreprocessSimpleType(attribute.SchemaType, local: true);
        }
        if (!attribute.SchemaTypeName.IsEmpty)
        {
            ValidateQNameAttribute(attribute, "type", attribute.SchemaTypeName);
        }
    }
References System.Xml.Schema.Preprocessor._currentSchema, System.Xml.Schema.Preprocessor._nsXsi, System.Xml.Schema.Preprocessor._xmlns, System.Xml.Ref.Equal(), System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessSimpleType(), System.SR.Sch_DefaultFixedAttributes, System.SR.Sch_ForbiddenAttribute, System.SR.Sch_OptionalDefaultAttribute, System.SR.Sch_TargetNamespaceXsi, System.SR.Sch_TypeMutualExclusive, System.SR.Sch_XmlNsAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.SetParent(), System.Xml.Schema.XmlSchema.TargetNamespace, and System.Xml.Schema.Preprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.Preprocessor.PreprocessAttribute(), and System.Xml.Schema.Preprocessor.PreprocessLocalAttribute().