Terraria: System.Xml.Schema.Preprocessor.Execute
Execute()
bool System.Xml.Schema.Preprocessor.Execute (XmlSchema schema, string targetNamespace, bool loadExternals) inline
Definition at line 95 of file Preprocessor.cs.
    {
        _rootSchema = schema;
        _xmlns = base.NameTable.Add("xmlns");
        _nsXsi = base.NameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _rootSchema.ImportedSchemas.Clear();
        _rootSchema.ImportedNamespaces.Clear();
        if (_rootSchema.BaseUri != null && _schemaLocations[_rootSchema.BaseUri] == null)
        {
            _schemaLocations.Add(_rootSchema.BaseUri, _rootSchema);
        }
        if (_rootSchema.TargetNamespace != null)
        {
            if (targetNamespace == null)
            {
                targetNamespace = _rootSchema.TargetNamespace;
            }
            else if (targetNamespace != _rootSchema.TargetNamespace)
            {
                SendValidationEvent(System.SR.Sch_MismatchTargetNamespaceEx, targetNamespace, _rootSchema.TargetNamespace, _rootSchema);
            }
        }
        else if (targetNamespace != null && targetNamespace.Length != 0)
        {
            _rootSchema = GetChameleonSchema(targetNamespace, _rootSchema);
        }
        if (loadExternals && _xmlResolver != null)
        {
            LoadExternals(_rootSchema);
        }
        BuildSchemaList(_rootSchema);
        int i = 0;
        try
        {
            for (i = 0; i < _lockList.Count; i++)
            {
                XmlSchema xmlSchema = (XmlSchema)_lockList.GetByIndex(i);
                Monitor.Enter(xmlSchema);
                xmlSchema.IsProcessing = false;
            }
            _rootSchemaForRedefine = _rootSchema;
            Preprocess(_rootSchema, targetNamespace, _rootSchema.ImportedSchemas);
            if (_redefinedList != null)
            {
                for (int j = 0; j < _redefinedList.Count; j++)
                {
                    PreprocessRedefine((RedefineEntry)_redefinedList[j]);
                }
            }
        }
        finally
        {
            if (i == _lockList.Count)
            {
                i--;
            }
            int num = i;
            while (i >= 0)
            {
                XmlSchema xmlSchema = (XmlSchema)_lockList.GetByIndex(i);
                xmlSchema.IsProcessing = false;
                if (xmlSchema == GetBuildInSchema())
                {
                    Monitor.Exit(xmlSchema);
                }
                else
                {
                    xmlSchema.IsCompiledBySet = false;
                    xmlSchema.IsPreprocessed = !base.HasErrors;
                    Monitor.Exit(xmlSchema);
                }
                i--;
            }
        }
        _rootSchema.IsPreprocessed = !base.HasErrors;
        return !base.HasErrors;
    }
References System.Xml.Schema.Preprocessor._lockList, System.Xml.Schema.Preprocessor._nsXsi, System.Xml.Schema.Preprocessor._redefinedList, System.Xml.Schema.Preprocessor._rootSchema, System.Xml.Schema.Preprocessor._rootSchemaForRedefine, System.Xml.Schema.Preprocessor._schemaLocations, System.Xml.Schema.Preprocessor._xmlns, System.Xml.Schema.Preprocessor._xmlResolver, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchema.BaseUri, System.Xml.Schema.Preprocessor.BuildSchemaList(), System.Collections.ArrayList.Clear(), System.Collections.SortedList.Count, System.Collections.ArrayList.Count, System.Xml.Dictionary, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Collections.SortedList.GetByIndex(), System.Xml.Schema.Preprocessor.GetChameleonSchema(), System.Xml.Schema.XmlSchema.ImportedNamespaces, System.Xml.Schema.XmlSchema.ImportedSchemas, System.Xml.Schema.Preprocessor.LoadExternals(), System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessRedefine(), System.SR.Sch_MismatchTargetNamespaceEx, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.Schema.XmlSchema.TargetNamespace.