Terraria: System.Xml.Schema.Preprocessor.PreprocessParticle
PreprocessParticle()
void System.Xml.Schema.Preprocessor.PreprocessParticle (XmlSchemaParticle particle) inline private
Definition at line 1733 of file Preprocessor.cs.
    {
        if (particle is XmlSchemaAll)
        {
            if (particle.MinOccurs != 0m && particle.MinOccurs != 1m)
            {
                particle.MinOccurs = 1m;
                SendValidationEvent(System.SR.Sch_InvalidAllMin, particle);
            }
            if (particle.MaxOccurs != 1m)
            {
                particle.MaxOccurs = 1m;
                SendValidationEvent(System.SR.Sch_InvalidAllMax, particle);
            }
            XmlSchemaObjectCollection items = ((XmlSchemaAll)particle).Items;
            for (int i = 0; i < items.Count; i++)
            {
                XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)items[i];
                if (xmlSchemaElement.MaxOccurs != 0m && xmlSchemaElement.MaxOccurs != 1m)
                {
                    xmlSchemaElement.MaxOccurs = 1m;
                    SendValidationEvent(System.SR.Sch_InvalidAllElementMax, xmlSchemaElement);
                }
                SetParent(xmlSchemaElement, particle);
                PreprocessLocalElement(xmlSchemaElement);
            }
        }
        else
        {
            if (particle.MinOccurs > particle.MaxOccurs)
            {
                particle.MinOccurs = particle.MaxOccurs;
                SendValidationEvent(System.SR.Sch_MinGtMax, particle);
            }
            if (particle is XmlSchemaChoice)
            {
                XmlSchemaObjectCollection items = ((XmlSchemaChoice)particle).Items;
                for (int j = 0; j < items.Count; j++)
                {
                    SetParent(items[j], particle);
                    if (items[j] is XmlSchemaElement element)
                    {
                        PreprocessLocalElement(element);
                    }
                    else
                    {
                        PreprocessParticle((XmlSchemaParticle)items[j]);
                    }
                }
            }
            else if (particle is XmlSchemaSequence)
            {
                XmlSchemaObjectCollection items = ((XmlSchemaSequence)particle).Items;
                for (int k = 0; k < items.Count; k++)
                {
                    SetParent(items[k], particle);
                    if (items[k] is XmlSchemaElement element2)
                    {
                        PreprocessLocalElement(element2);
                    }
                    else
                    {
                        PreprocessParticle((XmlSchemaParticle)items[k]);
                    }
                }
            }
            else if (particle is XmlSchemaGroupRef)
            {
                XmlSchemaGroupRef xmlSchemaGroupRef = (XmlSchemaGroupRef)particle;
                if (xmlSchemaGroupRef.RefName.IsEmpty)
                {
                    SendValidationEvent(System.SR.Sch_MissAttribute, "ref", xmlSchemaGroupRef);
                }
                else
                {
                    ValidateQNameAttribute(xmlSchemaGroupRef, "ref", xmlSchemaGroupRef.RefName);
                }
            }
            else if (particle is XmlSchemaAny)
            {
                try
                {
                    ((XmlSchemaAny)particle).BuildNamespaceList(_targetNamespace);
                }
                catch (FormatException ex)
                {
                    SendValidationEvent(System.SR.Sch_InvalidAnyDetailed, new string[1] { ex.Message }, ex, particle);
                }
            }
        }
        PreprocessAnnotation(particle);
        ValidateIdAttribute(particle);
    }
References System.Xml.Schema.Preprocessor._targetNamespace, System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.MaxOccurs, System.Xml.Schema.XmlSchemaParticle.MinOccurs, System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessParticle(), System.SR.Sch_InvalidAllElementMax, System.SR.Sch_InvalidAllMax, System.SR.Sch_InvalidAllMin, System.SR.Sch_InvalidAnyDetailed, System.SR.Sch_MinGtMax, System.SR.Sch_MissAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.SetParent(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), and System.Xml.Schema.Preprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessGroup(), and System.Xml.Schema.Preprocessor.PreprocessParticle().