Terraria: Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList
UpdatePlayersList()
void Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList () inline private
    {
        _playerList.Clear();
        List<PlayerFileData> list = new List<PlayerFileData>(Main.PlayerList);
        list.Sort(delegate(PlayerFileData x, PlayerFileData y)
        {
            if (x.IsFavorite && !y.IsFavorite)
            {
                return -1;
            }
            if (!x.IsFavorite && y.IsFavorite)
            {
                return 1;
            }
            return (x.Name.CompareTo(y.Name) != 0) ? x.Name.CompareTo(y.Name) : x.GetFileName().CompareTo(y.GetFileName());
        });
        int num = 0;
        foreach (PlayerFileData item in list)
        {
            _playerList.Add(new UICharacterListItem(item, num++));
        }
    }
References Terraria.GameContent.UI.States.UICharacterSelect._playerList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.IO.FileData.GetFileName(), Terraria.IO.FileData.IsFavorite, Terraria.IO.FileData.Name, and Terraria.Main.PlayerList.
Referenced by Terraria.GameContent.UI.States.UICharacterSelect.OnActivate(), and Terraria.GameContent.UI.States.UICharacterSelect.UpdateFavoritesCache().