Terraria: System.Xml.Schema.Preprocessor.LoadExternals
LoadExternals()
void System.Xml.Schema.Preprocessor.LoadExternals (XmlSchema schema) inline private
Definition at line 215 of file Preprocessor.cs.
    {
        if (schema.IsProcessing)
        {
            return;
        }
        schema.IsProcessing = true;
        for (int i = 0; i < schema.Includes.Count; i++)
        {
            Uri uri = null;
            XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
            XmlSchema schema2 = xmlSchemaExternal.Schema;
            if (schema2 != null)
            {
                uri = schema2.BaseUri;
                if (uri != null && _schemaLocations[uri] == null)
                {
                    _schemaLocations.Add(uri, schema2);
                }
                LoadExternals(schema2);
                continue;
            }
            string schemaLocation = xmlSchemaExternal.SchemaLocation;
            Uri uri2 = null;
            Exception innerException = null;
            if (schemaLocation != null)
            {
                try
                {
                    uri2 = ResolveSchemaLocationUri(schema, schemaLocation);
                }
                catch (Exception ex)
                {
                    uri2 = null;
                    innerException = ex;
                }
            }
            if (xmlSchemaExternal.Compositor == Compositor.Import)
            {
                XmlSchemaImport xmlSchemaImport = xmlSchemaExternal as XmlSchemaImport;
                string text = ((xmlSchemaImport.Namespace != null) ? xmlSchemaImport.Namespace : string.Empty);
                if (!schema.ImportedNamespaces.Contains(text))
                {
                    schema.ImportedNamespaces.Add(text);
                }
                if (text == "http://www.w3.org/XML/1998/namespace" && uri2 == null)
                {
                    xmlSchemaExternal.Schema = GetBuildInSchema();
                    continue;
                }
            }
            if (uri2 == null)
            {
                if (schemaLocation != null)
                {
                    SendValidationEvent(new XmlSchemaException(System.SR.Sch_InvalidIncludeLocation, null, innerException, xmlSchemaExternal.SourceUri, xmlSchemaExternal.LineNumber, xmlSchemaExternal.LinePosition, xmlSchemaExternal), XmlSeverityType.Warning);
                }
            }
            else if (_schemaLocations[uri2] == null)
            {
                object obj = null;
                try
                {
                    obj = GetSchemaEntity(uri2);
                }
                catch (Exception ex2)
                {
                    innerException = ex2;
                    obj = null;
                }
                if (obj != null)
                {
                    xmlSchemaExternal.BaseUri = uri2;
                    Type type = obj.GetType();
                    if (typeof(XmlSchema).IsAssignableFrom(type))
                    {
                        xmlSchemaExternal.Schema = (XmlSchema)obj;
                        _schemaLocations.Add(uri2, xmlSchemaExternal.Schema);
                        LoadExternals(xmlSchemaExternal.Schema);
                        continue;
                    }
                    XmlReader xmlReader = null;
                    if (type.IsSubclassOf(typeof(Stream)))
                    {
                        _readerSettings.CloseInput = true;
                        _readerSettings.XmlResolver = _xmlResolver;
                        xmlReader = XmlReader.Create((Stream)obj, _readerSettings, uri2.ToString());
                    }
                    else if (type.IsSubclassOf(typeof(XmlReader)))
                    {
                        xmlReader = (XmlReader)obj;
                    }
                    else if (type.IsSubclassOf(typeof(TextReader)))
                    {
                        _readerSettings.CloseInput = true;
                        _readerSettings.XmlResolver = _xmlResolver;
                        xmlReader = XmlReader.Create((TextReader)obj, _readerSettings, uri2.ToString());
                    }
                    if (xmlReader == null)
                    {
                        SendValidationEvent(System.SR.Sch_InvalidIncludeLocation, xmlSchemaExternal, XmlSeverityType.Warning);
                        continue;
                    }
                    try
                    {
                        Parser parser = new Parser(SchemaType.XSD, base.NameTable, base.SchemaNames, base.EventHandler);
                        parser.Parse(xmlReader, null);
                        while (xmlReader.Read())
{
                        }
                        schema2 = (xmlSchemaExternal.Schema = parser.XmlSchema);
                        _schemaLocations.Add(uri2, schema2);
                        LoadExternals(schema2);
                    }
                    catch (XmlSchemaException ex3)
                    {
                        SendValidationEvent(System.SR.Sch_CannotLoadSchemaLocation, schemaLocation, ex3.Message, ex3.SourceUri, ex3.LineNumber, ex3.LinePosition);
                    }
                    catch (Exception innerException2)
                    {
                        SendValidationEvent(new XmlSchemaException(System.SR.Sch_InvalidIncludeLocation, null, innerException2, xmlSchemaExternal.SourceUri, xmlSchemaExternal.LineNumber, xmlSchemaExternal.LinePosition, xmlSchemaExternal), XmlSeverityType.Warning);
                    }
                    finally
                    {
                        xmlReader.Close();
                    }
                }
                else
                {
                    SendValidationEvent(new XmlSchemaException(System.SR.Sch_InvalidIncludeLocation, null, innerException, xmlSchemaExternal.SourceUri, xmlSchemaExternal.LineNumber, xmlSchemaExternal.LinePosition, xmlSchemaExternal), XmlSeverityType.Warning);
                }
            }
            else
            {
                xmlSchemaExternal.Schema = (XmlSchema)_schemaLocations[uri2];
            }
        }
    }
References System.Xml.Schema.Preprocessor._readerSettings, System.Xml.Schema.Preprocessor._schemaLocations, System.Xml.Schema.Preprocessor._xmlResolver, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlReader.Create(), System.Xml.Dictionary, System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Xml.Schema.Preprocessor.GetSchemaEntity(), System.Type.GetType(), System.Xml.Schema.Preprocessor.LoadExternals(), System.obj, System.Xml.Schema.Preprocessor.ResolveSchemaLocationUri(), System.SR.Sch_CannotLoadSchemaLocation, System.SR.Sch_InvalidIncludeLocation, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.text, and System.type.
Referenced by System.Xml.Schema.Preprocessor.Execute(), and System.Xml.Schema.Preprocessor.LoadExternals().