Terraria: System.Xml.Schema.Preprocessor.PreprocessSimpleType
PreprocessSimpleType()
void System.Xml.Schema.Preprocessor.PreprocessSimpleType (XmlSchemaSimpleType simpleType, bool local) inline private
Definition at line 1340 of file Preprocessor.cs.
    {
        if (local)
        {
            if (simpleType.Name != null)
            {
                SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "name", simpleType);
            }
        }
        else
        {
            if (simpleType.Name != null)
            {
                ValidateNameAttribute(simpleType);
                simpleType.SetQualifiedName(new XmlQualifiedName(simpleType.Name, _targetNamespace));
            }
            else
            {
                SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", simpleType);
            }
            if (simpleType.Final == XmlSchemaDerivationMethod.All)
            {
                simpleType.SetFinalResolved(XmlSchemaDerivationMethod.All);
            }
            else if (simpleType.Final == XmlSchemaDerivationMethod.None)
            {
                if (_finalDefault == XmlSchemaDerivationMethod.All)
                {
                    simpleType.SetFinalResolved(XmlSchemaDerivationMethod.All);
                }
                else
                {
                    simpleType.SetFinalResolved(_finalDefault & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction | XmlSchemaDerivationMethod.List | XmlSchemaDerivationMethod.Union));
                }
            }
            else
            {
                if (((uint)simpleType.Final & 0xFFFFFFE1u) != 0)
                {
                    SendValidationEvent(System.SR.Sch_InvalidSimpleTypeFinalValue, simpleType);
                }
                simpleType.SetFinalResolved(simpleType.Final & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction | XmlSchemaDerivationMethod.List | XmlSchemaDerivationMethod.Union));
            }
        }
        if (simpleType.Content == null)
        {
            SendValidationEvent(System.SR.Sch_NoSimpleTypeContent, simpleType);
        }
        else if (simpleType.Content is XmlSchemaSimpleTypeRestriction)
        {
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = (XmlSchemaSimpleTypeRestriction)simpleType.Content;
            SetParent(xmlSchemaSimpleTypeRestriction, simpleType);
            for (int i = 0; i < xmlSchemaSimpleTypeRestriction.Facets.Count; i++)
            {
                SetParent(xmlSchemaSimpleTypeRestriction.Facets[i], xmlSchemaSimpleTypeRestriction);
            }
            if (xmlSchemaSimpleTypeRestriction.BaseType != null)
            {
                if (!xmlSchemaSimpleTypeRestriction.BaseTypeName.IsEmpty)
                {
                    SendValidationEvent(System.SR.Sch_SimpleTypeRestRefBase, xmlSchemaSimpleTypeRestriction);
                }
                PreprocessSimpleType(xmlSchemaSimpleTypeRestriction.BaseType, local: true);
            }
            else if (xmlSchemaSimpleTypeRestriction.BaseTypeName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_SimpleTypeRestRefBaseNone, xmlSchemaSimpleTypeRestriction);
            }
            else
            {
                ValidateQNameAttribute(xmlSchemaSimpleTypeRestriction, "base", xmlSchemaSimpleTypeRestriction.BaseTypeName);
            }
            PreprocessAnnotation(xmlSchemaSimpleTypeRestriction);
            ValidateIdAttribute(xmlSchemaSimpleTypeRestriction);
        }
        else if (simpleType.Content is XmlSchemaSimpleTypeList)
        {
            XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = (XmlSchemaSimpleTypeList)simpleType.Content;
            SetParent(xmlSchemaSimpleTypeList, simpleType);
            if (xmlSchemaSimpleTypeList.ItemType != null)
            {
                if (!xmlSchemaSimpleTypeList.ItemTypeName.IsEmpty)
                {
                    SendValidationEvent(System.SR.Sch_SimpleTypeListRefBase, xmlSchemaSimpleTypeList);
                }
                SetParent(xmlSchemaSimpleTypeList.ItemType, xmlSchemaSimpleTypeList);
                PreprocessSimpleType(xmlSchemaSimpleTypeList.ItemType, local: true);
            }
            else if (xmlSchemaSimpleTypeList.ItemTypeName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_SimpleTypeListRefBaseNone, xmlSchemaSimpleTypeList);
            }
            else
            {
                ValidateQNameAttribute(xmlSchemaSimpleTypeList, "itemType", xmlSchemaSimpleTypeList.ItemTypeName);
            }
            PreprocessAnnotation(xmlSchemaSimpleTypeList);
            ValidateIdAttribute(xmlSchemaSimpleTypeList);
        }
        else
        {
            XmlSchemaSimpleTypeUnion xmlSchemaSimpleTypeUnion = (XmlSchemaSimpleTypeUnion)simpleType.Content;
            SetParent(xmlSchemaSimpleTypeUnion, simpleType);
            int num = xmlSchemaSimpleTypeUnion.BaseTypes.Count;
            if (xmlSchemaSimpleTypeUnion.MemberTypes != null)
            {
                num += xmlSchemaSimpleTypeUnion.MemberTypes.Length;
                XmlQualifiedName[] memberTypes = xmlSchemaSimpleTypeUnion.MemberTypes;
                for (int j = 0; j < memberTypes.Length; j++)
                {
                    ValidateQNameAttribute(xmlSchemaSimpleTypeUnion, "memberTypes", memberTypes[j]);
                }
            }
            if (num == 0)
            {
                SendValidationEvent(System.SR.Sch_SimpleTypeUnionNoBase, xmlSchemaSimpleTypeUnion);
            }
            for (int k = 0; k < xmlSchemaSimpleTypeUnion.BaseTypes.Count; k++)
            {
                XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)xmlSchemaSimpleTypeUnion.BaseTypes[k];
                SetParent(xmlSchemaSimpleType, xmlSchemaSimpleTypeUnion);
                PreprocessSimpleType(xmlSchemaSimpleType, local: true);
            }
            PreprocessAnnotation(xmlSchemaSimpleTypeUnion);
            ValidateIdAttribute(xmlSchemaSimpleTypeUnion);
        }
        ValidateIdAttribute(simpleType);
    }
References System.Xml.Schema.Preprocessor._finalDefault, System.Xml.Schema.Preprocessor._targetNamespace, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessSimpleType(), System.SR.Sch_ForbiddenAttribute, System.SR.Sch_InvalidSimpleTypeFinalValue, System.SR.Sch_MissRequiredAttribute, System.SR.Sch_NoSimpleTypeContent, System.SR.Sch_SimpleTypeListRefBase, System.SR.Sch_SimpleTypeListRefBaseNone, System.SR.Sch_SimpleTypeRestRefBase, System.SR.Sch_SimpleTypeRestRefBaseNone, System.SR.Sch_SimpleTypeUnionNoBase, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.SetParent(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), System.Xml.Schema.Preprocessor.ValidateNameAttribute(), and System.Xml.Schema.Preprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElementContent(), System.Xml.Schema.Preprocessor.PreprocessRedefine(), and System.Xml.Schema.Preprocessor.PreprocessSimpleType().