Terraria: System.Xml.Schema.Preprocessor.GetBuildInSchema
GetBuildInSchema()
static XmlSchema System.Xml.Schema.Preprocessor.GetBuildInSchema () inline static package
Definition at line 354 of file Preprocessor.cs.
    {
        if (s_builtInSchemaForXmlNS == null)
        {
            XmlSchema xmlSchema = new XmlSchema();
            xmlSchema.TargetNamespace = "http://www.w3.org/XML/1998/namespace";
            xmlSchema.Namespaces.Add("xml", "http://www.w3.org/XML/1998/namespace");
            XmlSchemaAttribute xmlSchemaAttribute = new XmlSchemaAttribute();
            xmlSchemaAttribute.Name = "lang";
            xmlSchemaAttribute.SchemaTypeName = new XmlQualifiedName("language", "http://www.w3.org/2001/XMLSchema");
            xmlSchema.Items.Add(xmlSchemaAttribute);
            XmlSchemaAttribute xmlSchemaAttribute2 = new XmlSchemaAttribute();
            xmlSchemaAttribute2.Name = "base";
            xmlSchemaAttribute2.SchemaTypeName = new XmlQualifiedName("anyURI", "http://www.w3.org/2001/XMLSchema");
            xmlSchema.Items.Add(xmlSchemaAttribute2);
            XmlSchemaAttribute xmlSchemaAttribute3 = new XmlSchemaAttribute();
            xmlSchemaAttribute3.Name = "space";
            XmlSchemaSimpleType xmlSchemaSimpleType = new XmlSchemaSimpleType();
            XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = new XmlSchemaSimpleTypeRestriction();
            xmlSchemaSimpleTypeRestriction.BaseTypeName = new XmlQualifiedName("NCName", "http://www.w3.org/2001/XMLSchema");
            XmlSchemaEnumerationFacet xmlSchemaEnumerationFacet = new XmlSchemaEnumerationFacet();
            xmlSchemaEnumerationFacet.Value = "default";
            xmlSchemaSimpleTypeRestriction.Facets.Add(xmlSchemaEnumerationFacet);
            XmlSchemaEnumerationFacet xmlSchemaEnumerationFacet2 = new XmlSchemaEnumerationFacet();
            xmlSchemaEnumerationFacet2.Value = "preserve";
            xmlSchemaSimpleTypeRestriction.Facets.Add(xmlSchemaEnumerationFacet2);
            xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeRestriction;
            xmlSchemaAttribute3.SchemaType = xmlSchemaSimpleType;
            xmlSchemaAttribute3.DefaultValue = "preserve";
            xmlSchema.Items.Add(xmlSchemaAttribute3);
            XmlSchemaAttributeGroup xmlSchemaAttributeGroup = new XmlSchemaAttributeGroup();
            xmlSchemaAttributeGroup.Name = "specialAttrs";
            XmlSchemaAttribute xmlSchemaAttribute4 = new XmlSchemaAttribute();
            xmlSchemaAttribute4.RefName = new XmlQualifiedName("lang", "http://www.w3.org/XML/1998/namespace");
            xmlSchemaAttributeGroup.Attributes.Add(xmlSchemaAttribute4);
            XmlSchemaAttribute xmlSchemaAttribute5 = new XmlSchemaAttribute();
            xmlSchemaAttribute5.RefName = new XmlQualifiedName("space", "http://www.w3.org/XML/1998/namespace");
            xmlSchemaAttributeGroup.Attributes.Add(xmlSchemaAttribute5);
            XmlSchemaAttribute xmlSchemaAttribute6 = new XmlSchemaAttribute();
            xmlSchemaAttribute6.RefName = new XmlQualifiedName("base", "http://www.w3.org/XML/1998/namespace");
            xmlSchemaAttributeGroup.Attributes.Add(xmlSchemaAttribute6);
            xmlSchema.Items.Add(xmlSchemaAttributeGroup);
            xmlSchema.IsPreprocessed = true;
            xmlSchema.CompileSchemaInSet(new NameTable(), null, null);
            Interlocked.CompareExchange(ref s_builtInSchemaForXmlNS, xmlSchema, null);
        }
        return s_builtInSchemaForXmlNS;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Threading.Interlocked.CompareExchange(), System.Xml.Dictionary, System.Xml.Schema.BaseProcessor.NameTable, and System.Xml.Schema.Preprocessor.s_builtInSchemaForXmlNS.
Referenced by System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchemaSet.AddToTable(), System.Xml.Schema.XmlSchemaValidator.AddXmlNamespaceSchema(), System.Xml.Schema.Preprocessor.Cleanup(), System.Xml.Schema.XmlSchemaSet.Compile(), System.Xml.Schema.Preprocessor.Execute(), System.Xml.Schema.Preprocessor.LoadExternals(), and System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals().