Terraria: System.Xml.Schema.Preprocessor.PreprocessLocalAttribute
PreprocessLocalAttribute()
void System.Xml.Schema.Preprocessor.PreprocessLocalAttribute (XmlSchemaAttribute attribute) inline private
Definition at line 1034 of file Preprocessor.cs.
    {
        if (attribute.Name != null)
        {
            ValidateNameAttribute(attribute);
            PreprocessAttributeContent(attribute);
            attribute.SetQualifiedName(new XmlQualifiedName(attribute.Name, (attribute.Form == XmlSchemaForm.Qualified || (attribute.Form == XmlSchemaForm.None && _attributeFormDefault == XmlSchemaForm.Qualified)) ? _targetNamespace : null));
        }
        else
        {
            PreprocessAnnotation(attribute);
            if (attribute.RefName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_AttributeNameRef, "???", attribute);
            }
            else
            {
                ValidateQNameAttribute(attribute, "ref", attribute.RefName);
            }
            if (!attribute.SchemaTypeName.IsEmpty || attribute.SchemaType != null || attribute.Form != 0)
            {
                SendValidationEvent(System.SR.Sch_InvalidAttributeRef, attribute);
            }
            attribute.SetQualifiedName(attribute.RefName);
        }
        ValidateIdAttribute(attribute);
    }
References System.Xml.Schema.Preprocessor._attributeFormDefault, System.Xml.Schema.Preprocessor._targetNamespace, System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.SR.Sch_AttributeNameRef, System.SR.Sch_InvalidAttributeRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), System.Xml.Schema.Preprocessor.ValidateNameAttribute(), and System.Xml.Schema.Preprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.Preprocessor.PreprocessAttributes().