Terraria: System.Xml.Schema.Preprocessor.PreprocessRedefine
PreprocessRedefine()
void System.Xml.Schema.Preprocessor.PreprocessRedefine (RedefineEntry redefineEntry) inline private
Definition at line 715 of file Preprocessor.cs.
    {
        XmlSchemaRedefine redefine = redefineEntry.redefine;
        XmlSchema schema = redefine.Schema;
        _currentSchema = GetParentSchema(redefine);
        SetSchemaDefaults(_currentSchema);
        if (schema.IsRedefined)
        {
            SendValidationEvent(System.SR.Sch_MultipleRedefine, redefine, XmlSeverityType.Warning);
            return;
        }
        schema.IsRedefined = true;
        XmlSchema schemaToUpdate = redefineEntry.schemaToUpdate;
        ArrayList arrayList = new ArrayList();
        GetIncludedSet(schema, arrayList);
        string @namespace = ((schemaToUpdate.TargetNamespace == null) ? string.Empty : schemaToUpdate.TargetNamespace);
        XmlSchemaObjectCollection items = redefine.Items;
        for (int i = 0; i < items.Count; i++)
        {
            SetParent(items[i], redefine);
            if (items[i] is XmlSchemaGroup xmlSchemaGroup)
            {
                PreprocessGroup(xmlSchemaGroup);
                xmlSchemaGroup.QualifiedName.SetNamespace(@namespace);
                if (redefine.Groups[xmlSchemaGroup.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_GroupDoubleRedefine, xmlSchemaGroup);
                    continue;
                }
                AddToTable(redefine.Groups, xmlSchemaGroup.QualifiedName, xmlSchemaGroup);
                XmlSchemaGroup xmlSchemaGroup2 = (XmlSchemaGroup)schemaToUpdate.Groups[xmlSchemaGroup.QualifiedName];
                XmlSchema parentSchema = GetParentSchema(xmlSchemaGroup2);
                if (xmlSchemaGroup2 == null || (parentSchema != schema && !arrayList.Contains(parentSchema)))
                {
                    SendValidationEvent(System.SR.Sch_ComponentRedefineNotFound, "<group>", xmlSchemaGroup.QualifiedName.ToString(), xmlSchemaGroup);
                    continue;
                }
                xmlSchemaGroup.Redefined = xmlSchemaGroup2;
                schemaToUpdate.Groups.Insert(xmlSchemaGroup.QualifiedName, xmlSchemaGroup);
                CheckRefinedGroup(xmlSchemaGroup);
            }
            else if (items[i] is XmlSchemaAttributeGroup)
            {
                XmlSchemaAttributeGroup xmlSchemaAttributeGroup = (XmlSchemaAttributeGroup)items[i];
                PreprocessAttributeGroup(xmlSchemaAttributeGroup);
                xmlSchemaAttributeGroup.QualifiedName.SetNamespace(@namespace);
                if (redefine.AttributeGroups[xmlSchemaAttributeGroup.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_AttrGroupDoubleRedefine, xmlSchemaAttributeGroup);
                    continue;
                }
                AddToTable(redefine.AttributeGroups, xmlSchemaAttributeGroup.QualifiedName, xmlSchemaAttributeGroup);
                XmlSchemaAttributeGroup xmlSchemaAttributeGroup2 = (XmlSchemaAttributeGroup)schemaToUpdate.AttributeGroups[xmlSchemaAttributeGroup.QualifiedName];
                XmlSchema parentSchema2 = GetParentSchema(xmlSchemaAttributeGroup2);
                if (xmlSchemaAttributeGroup2 == null || (parentSchema2 != schema && !arrayList.Contains(parentSchema2)))
                {
                    SendValidationEvent(System.SR.Sch_ComponentRedefineNotFound, "<attributeGroup>", xmlSchemaAttributeGroup.QualifiedName.ToString(), xmlSchemaAttributeGroup);
                    continue;
                }
                xmlSchemaAttributeGroup.Redefined = xmlSchemaAttributeGroup2;
                schemaToUpdate.AttributeGroups.Insert(xmlSchemaAttributeGroup.QualifiedName, xmlSchemaAttributeGroup);
                CheckRefinedAttributeGroup(xmlSchemaAttributeGroup);
            }
            else if (items[i] is XmlSchemaComplexType)
            {
                XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)items[i];
                PreprocessComplexType(xmlSchemaComplexType, local: false);
                xmlSchemaComplexType.QualifiedName.SetNamespace(@namespace);
                if (redefine.SchemaTypes[xmlSchemaComplexType.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_ComplexTypeDoubleRedefine, xmlSchemaComplexType);
                    continue;
                }
                AddToTable(redefine.SchemaTypes, xmlSchemaComplexType.QualifiedName, xmlSchemaComplexType);
                XmlSchemaType xmlSchemaType = (XmlSchemaType)schemaToUpdate.SchemaTypes[xmlSchemaComplexType.QualifiedName];
                XmlSchema parentSchema3 = GetParentSchema(xmlSchemaType);
                if (xmlSchemaType == null || (parentSchema3 != schema && !arrayList.Contains(parentSchema3)))
                {
                    SendValidationEvent(System.SR.Sch_ComponentRedefineNotFound, "<complexType>", xmlSchemaComplexType.QualifiedName.ToString(), xmlSchemaComplexType);
                }
                else if (xmlSchemaType is XmlSchemaComplexType)
                {
                    xmlSchemaComplexType.Redefined = xmlSchemaType;
                    schemaToUpdate.SchemaTypes.Insert(xmlSchemaComplexType.QualifiedName, xmlSchemaComplexType);
                    CheckRefinedComplexType(xmlSchemaComplexType);
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_SimpleToComplexTypeRedefine, xmlSchemaComplexType);
                }
            }
            else
            {
                if (!(items[i] is XmlSchemaSimpleType))
                {
                    continue;
                }
                XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)items[i];
                PreprocessSimpleType(xmlSchemaSimpleType, local: false);
                xmlSchemaSimpleType.QualifiedName.SetNamespace(@namespace);
                if (redefine.SchemaTypes[xmlSchemaSimpleType.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_SimpleTypeDoubleRedefine, xmlSchemaSimpleType);
                    continue;
                }
                AddToTable(redefine.SchemaTypes, xmlSchemaSimpleType.QualifiedName, xmlSchemaSimpleType);
                XmlSchemaType xmlSchemaType2 = (XmlSchemaType)schemaToUpdate.SchemaTypes[xmlSchemaSimpleType.QualifiedName];
                XmlSchema parentSchema4 = GetParentSchema(xmlSchemaType2);
                if (xmlSchemaType2 == null || (parentSchema4 != schema && !arrayList.Contains(parentSchema4)))
                {
                    SendValidationEvent(System.SR.Sch_ComponentRedefineNotFound, "<simpleType>", xmlSchemaSimpleType.QualifiedName.ToString(), xmlSchemaSimpleType);
                }
                else if (xmlSchemaType2 is XmlSchemaSimpleType)
                {
                    xmlSchemaSimpleType.Redefined = xmlSchemaType2;
                    schemaToUpdate.SchemaTypes.Insert(xmlSchemaSimpleType.QualifiedName, xmlSchemaSimpleType);
                    CheckRefinedSimpleType(xmlSchemaSimpleType);
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_ComplexToSimpleTypeRedefine, xmlSchemaSimpleType);
                }
            }
        }
    }
References System.Xml.Schema.Preprocessor._currentSchema, System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchema.AttributeGroups, System.Xml.Schema.XmlSchemaRedefine.AttributeGroups, System.Xml.Schema.Preprocessor.CheckRefinedAttributeGroup(), System.Xml.Schema.Preprocessor.CheckRefinedComplexType(), System.Xml.Schema.Preprocessor.CheckRefinedGroup(), System.Xml.Schema.Preprocessor.CheckRefinedSimpleType(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.Preprocessor.GetIncludedSet(), System.Xml.Schema.Preprocessor.GetParentSchema(), System.Xml.Schema.XmlSchema.Groups, System.Xml.Schema.XmlSchemaRedefine.Groups, System.Xml.Schema.XmlSchemaObjectTable.Insert(), System.Xml.Schema.XmlSchemaRedefine.Items, System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessGroup(), System.Xml.Schema.Preprocessor.PreprocessSimpleType(), System.SR.Sch_AttrGroupDoubleRedefine, System.SR.Sch_ComplexToSimpleTypeRedefine, System.SR.Sch_ComplexTypeDoubleRedefine, System.SR.Sch_ComponentRedefineNotFound, System.SR.Sch_GroupDoubleRedefine, System.SR.Sch_MultipleRedefine, System.SR.Sch_SimpleToComplexTypeRedefine, System.SR.Sch_SimpleTypeDoubleRedefine, System.Xml.Schema.XmlSchemaExternal.Schema, System.Xml.Schema.XmlSchema.SchemaTypes, System.Xml.Schema.XmlSchemaRedefine.SchemaTypes, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.Preprocessor.SetParent(), System.Xml.Schema.Preprocessor.SetSchemaDefaults(), and System.Xml.Schema.XmlSchema.TargetNamespace.
Referenced by System.Xml.Schema.Preprocessor.Execute().