Terraria: System.Xml.Schema.Preprocessor.ValidateQNameAttribute
ValidateQNameAttribute()
void System.Xml.Schema.Preprocessor.ValidateQNameAttribute (XmlSchemaObject xso, string attributeName, XmlQualifiedName value) inline private
Definition at line 1915 of file Preprocessor.cs.
    {
        try
        {
            value.Verify();
            value.Atomize(base.NameTable);
            if (_currentSchema.IsChameleon && value.Namespace.Length == 0)
            {
                value.SetNamespace(_currentSchema.TargetNamespace);
            }
            if (_referenceNamespaces[value.Namespace] == null)
            {
                SendValidationEvent(System.SR.Sch_UnrefNS, value.Namespace, xso, XmlSeverityType.Warning);
            }
        }
        catch (FormatException ex)
        {
            SendValidationEvent(System.SR.Sch_InvalidAttribute, new string[2] { attributeName, ex.Message }, ex, xso);
        }
        catch (XmlException ex2)
        {
            SendValidationEvent(System.SR.Sch_InvalidAttribute, new string[2] { attributeName, ex2.Message }, ex2, xso);
        }
    }
References System.Xml.Schema.Preprocessor._currentSchema, System.Xml.Schema.Preprocessor._referenceNamespaces, System.Xml.Schema.XmlSchema.IsChameleon, System.SR.Sch_InvalidAttribute, System.SR.Sch_UnrefNS, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.XmlSchema.TargetNamespace, and System.value.
Referenced by System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.Xml.Schema.Preprocessor.PreprocessAttributes(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElement(), System.Xml.Schema.Preprocessor.PreprocessElementContent(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessParticle(), and System.Xml.Schema.Preprocessor.PreprocessSimpleType().