Terraria: System.Xml.Schema.Preprocessor.PreprocessAnnotation
PreprocessAnnotation() [2/2]
void System.Xml.Schema.Preprocessor.PreprocessAnnotation (XmlSchemaObject schemaObject) inline private
Definition at line 1975 of file Preprocessor.cs.
    {
        if (schemaObject is XmlSchemaAnnotated xmlSchemaAnnotated)
        {
            XmlSchemaAnnotation annotation = xmlSchemaAnnotated.Annotation;
            if (annotation != null)
            {
                PreprocessAnnotation(annotation);
                annotation.Parent = schemaObject;
            }
        }
    }
References System.Xml.Dictionary, and System.Xml.Schema.Preprocessor.PreprocessAnnotation().
Referenced by System.Xml.Schema.Preprocessor.Preprocess(), System.Xml.Schema.Preprocessor.PreprocessAnnotation(), System.Xml.Schema.Preprocessor.PreprocessAttributeContent(), System.Xml.Schema.Preprocessor.PreprocessAttributeGroup(), System.Xml.Schema.Preprocessor.PreprocessAttributes(), System.Xml.Schema.Preprocessor.PreprocessComplexType(), System.Xml.Schema.Preprocessor.PreprocessElementContent(), System.Xml.Schema.Preprocessor.PreprocessGroup(), System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.Preprocessor.PreprocessLocalAttribute(), System.Xml.Schema.Preprocessor.PreprocessLocalElement(), System.Xml.Schema.Preprocessor.PreprocessNotation(), System.Xml.Schema.Preprocessor.PreprocessParticle(), and System.Xml.Schema.Preprocessor.PreprocessSimpleType().