Terraria: System.Xml.Schema.Preprocessor.BuildSchemaList
BuildSchemaList()
void System.Xml.Schema.Preprocessor.BuildSchemaList (XmlSchema schema) inline private
Definition at line 198 of file Preprocessor.cs.
    {
        if (_lockList.Contains(schema.SchemaId))
        {
            return;
        }
        _lockList.Add(schema.SchemaId, schema);
        for (int i = 0; i < schema.Includes.Count; i++)
        {
            XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
            if (xmlSchemaExternal.Schema != null)
            {
                BuildSchemaList(xmlSchemaExternal.Schema);
            }
        }
    }
References System.Xml.Schema.Preprocessor._lockList, System.Collections.SortedList.Add(), System.Xml.Schema.Preprocessor.BuildSchemaList(), System.Collections.SortedList.Contains(), and System.Collections.Generic.Dictionary< TKey, TValue >.Count.
Referenced by System.Xml.Schema.Preprocessor.BuildSchemaList(), and System.Xml.Schema.Preprocessor.Execute().