Terraria: System.Xml.Schema.Preprocessor.BuildRefNamespaces
BuildRefNamespaces()
void System.Xml.Schema.Preprocessor.BuildRefNamespaces (XmlSchema schema) inline private
Definition at line 403 of file Preprocessor.cs.
    {
        _referenceNamespaces.Clear();
        _referenceNamespaces.Add("http://www.w3.org/2001/XMLSchema", "http://www.w3.org/2001/XMLSchema");
        for (int i = 0; i < schema.Includes.Count; i++)
        {
            XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
            if (xmlSchemaExternal is XmlSchemaImport)
            {
                XmlSchemaImport xmlSchemaImport = xmlSchemaExternal as XmlSchemaImport;
                string text = xmlSchemaImport.Namespace;
                if (text == null)
                {
                    text = string.Empty;
                }
                if (_referenceNamespaces[text] == null)
                {
                    _referenceNamespaces.Add(text, text);
                }
            }
        }
        string text2 = schema.TargetNamespace;
        if (text2 == null)
        {
            text2 = string.Empty;
        }
        if (_referenceNamespaces[text2] == null)
        {
            _referenceNamespaces.Add(text2, text2);
        }
    }
References System.Xml.Schema.Preprocessor._referenceNamespaces, System.Collections.Hashtable.Add(), System.Collections.Hashtable.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.text.
Referenced by System.Xml.Schema.Preprocessor.Preprocess().