Terraria: ChromaInitializer.LoadSpecialRulesFor_GameSense
LoadSpecialRulesFor_GameSense()
static void ChromaInitializer.LoadSpecialRulesFor_GameSense () inline static private
     {
         //IL_0000: Unknown result type (might be due to invalid IL or missing references)
         //IL_0006: Expected O, but got Unknown
         GameSenseSpecificInfo val = new GameSenseSpecificInfo();
         List<Bind_Event> eventsToBind = (val.EventsToBind = new List<Bind_Event>());
         LoadSpecialRulesFor_GameSense_Keyboard(eventsToBind);
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE1", "zone1", new RGBZonedDevice("one"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE2", "zone2", new RGBZonedDevice("two"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE3", "zone3", new RGBZonedDevice("three"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE4", "zone4", new RGBZonedDevice("four"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE5", "zone5", new RGBZonedDevice("five"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE6", "zone6", new RGBZonedDevice("six"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE7", "zone7", new RGBZonedDevice("seven"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE8", "zone8", new RGBZonedDevice("eight"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE9", "zone9", new RGBZonedDevice("nine"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE10", "zone10", new RGBZonedDevice("ten"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE11", "zone11", new RGBZonedDevice("eleven"));
         LoadSpecialRulesFor_SecondaryDevice(eventsToBind, "ZONE12", "zone12", new RGBZonedDevice("twelve"));
         AddGameplayEvents(eventsToBind);
         val.MiscEvents = new List<ARgbGameValueTracker>
         {
             (ARgbGameValueTracker)(object)Event_LifePercent,
             (ARgbGameValueTracker)(object)Event_ManaPercent,
             (ARgbGameValueTracker)(object)Event_BreathPercent
         };
         foreach (Bind_Event item in val.EventsToBind)
         {
             if (_localizedEvents.TryGetValue(item.eventName, out var value))
             {
                 item.defaultDisplayName = value.DefaultDisplayName;
                 item.localizedDisplayNames = value.LocalizedNames;
             }
         }
         _engine.LoadSpecialRules((object)val);
     }
References _engine, _localizedEvents, AddGameplayEvents(), Event_BreathPercent, Event_LifePercent, Event_ManaPercent, GameSenseSpecificInfo.EventsToBind, ChromaEngine.LoadSpecialRules(), LoadSpecialRulesFor_GameSense_Keyboard(), LoadSpecialRulesFor_SecondaryDevice(), and GameSenseSpecificInfo.MiscEvents.
Referenced by LoadSpecialRulesForDevices().