Terraria: Terraria.Graphics.Light.ILightingEngine.GetColor
GetColor()
Vector3 Terraria.Graphics.Light.ILightingEngine.GetColor (int x, int y)
Implemented in Terraria.Graphics.Light.LegacyLighting, and Terraria.Graphics.Light.LightingEngine.
Referenced by Terraria.Lighting.Brightness(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.Lighting.GetColorClamped(), Terraria.Lighting.GetCornerColors(), and Terraria.Lighting.GetSubLight().