Terraria: WorldGen.Spread.Gem
Gem()
static void WorldGen.Spread.Gem (int x, int y) inline static
         {
             if (!InWorld(x, y))
             {
                 return;
             }
             List<Point> list = new List<Point>();
             List<Point> list2 = new List<Point>();
             HashSet<Point> hashSet = new HashSet<Point>();
             list2.Add(new Point(x, y));
             while (list2.Count > 0)
             {
                 list.Clear();
                 list.AddRange(list2);
                 list2.Clear();
                 while (list.Count > 0)
                 {
                     Point item = list[0];
                     if (!InWorld(item.X, item.Y, 1))
                     {
                         list.Remove(item);
                         continue;
                     }
                     hashSet.Add(item);
                     list.Remove(item);
                     Tile tile = Main.tile[item.X, item.Y];
                     if (SolidTile(item.X, item.Y) || tile.wall != 0)
                     {
                         if (tile.active())
{
                             if (Gemmable(tile.type))
{
                                 tile.type = randGemTile();
                             }
                             Tile tile2 = Main.tile[item.X - 1, item.Y];
                             if (Gemmable(tile2.type))
{
                                 tile2.type = randGemTile();
                             }
                             tile2 = Main.tile[item.X + 1, item.Y];
                             if (Gemmable(tile2.type))
{
                                 tile2.type = randGemTile();
                             }
                             tile2 = Main.tile[item.X, item.Y - 1];
                             if (Gemmable(tile2.type))
{
                                 tile2.type = randGemTile();
                             }
                             tile2 = Main.tile[item.X, item.Y + 1];
                             if (Gemmable(tile2.type))
{
                                 tile2.type = randGemTile();
                             }
                         }
                     }
                     else
                     {
                         tile.wall = (ushort)(48 + randGem());
                         if (!tile.active() && genRand.Next(2) == 0)
{
                             PlaceTile(item.X, item.Y, 178, mute: true, forced: false, -1, randGem());
                         }
                         Point item2 = new Point(item.X - 1, item.Y);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X + 1, item.Y);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X, item.Y - 1);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                         item2 = new Point(item.X, item.Y + 1);
                         if (!hashSet.Contains(item2))
{
                             list2.Add(item2);
                         }
                     }
                 }
             }
         }
References Tile.active(), WorldGen.Spread.Gemmable(), WorldGen.genRand, WorldGen.InWorld(), UnifiedRandom.Next(), WorldGen.PlaceTile(), WorldGen.randGem(), WorldGen.randGemTile(), WorldGen.SolidTile(), Main.tile, Tile.type, and Tile.wall.
Referenced by WorldGen.gemCave().