Terraria: WorldGen.Spread.Spider
Spider()
static void WorldGen.Spread.Spider (int x, int y) inline static
         {
             if (!InWorld(x, y))
             {
                 return;
             }
             byte wall = 62;
             List<Point> list = new List<Point>();
             List<Point> list2 = new List<Point>();
             HashSet<Point> hashSet = new HashSet<Point>();
             list2.Add(new Point(x, y));
             while (list2.Count > 0)
             {
                 list.Clear();
                 list.AddRange(list2);
                 list2.Clear();
                 while (list.Count > 0)
                 {
                     Point item = list[0];
                     if (!InWorld(item.X, item.Y, 1))
                     {
                         list.Remove(item);
                         continue;
                     }
                     hashSet.Add(item);
                     list.Remove(item);
                     Tile tile = Main.tile[item.X, item.Y];
                     if (SolidTile(item.X, item.Y) || tile.wall != 0)
                     {
                         if (tile.active() && tile.wall == 0)
{
                             tile.wall = wall;
                         }
                         continue;
                     }
                     tile.wall = wall;
                     SquareWallFrame(item.X, item.Y);
                     if (!tile.active())
                     {
                         tile.liquid = 0;
                         tile.lava(lava: false);
                         if (SolidTile(item.X, item.Y + 1) && genRand.Next(3) == 0)
{
                             if (genRand.Next(15) == 0)
{
                                 AddBuriedChest(item.X, item.Y, 939, notNearOtherChests: true, 15, trySlope: false, 0);
                             }
                             else
{
                                 PlacePot(item.X, item.Y, 28, genRand.Next(19, 21));
                             }
                         }
                         if (!tile.active())
{
                             if (SolidTile(item.X, item.Y - 1) && genRand.Next(3) == 0)
{
                                 PlaceTight(item.X, item.Y, spiders: true);
                             }
                             else if (SolidTile(item.X, item.Y + 1))
{
                                 PlaceTile(item.X, item.Y, 187, mute: true, forced: false, -1, 9 + genRand.Next(5));
                                 if (genRand.Next(3) == 0)
{
                                     if (!tile.active())
{
                                         PlaceSmallPile(item.X, item.Y, 34 + genRand.Next(4), 1, 185);
                                     }
                                     if (!tile.active())
{
                                         PlaceSmallPile(item.X, item.Y, 48 + genRand.Next(6), 0, 185);
                                     }
                                 }
                             }
                         }
                     }
                     Point item2 = new Point(item.X - 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X + 1, item.Y);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y - 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                     item2 = new Point(item.X, item.Y + 1);
                     if (!hashSet.Contains(item2))
                     {
                         list2.Add(item2);
                     }
                 }
             }
         }
References Tile.active(), WorldGen.AddBuriedChest(), WorldGen.genRand, WorldGen.InWorld(), Tile.lava(), Tile.liquid, UnifiedRandom.Next(), WorldGen.PlacePot(), WorldGen.PlaceSmallPile(), WorldGen.PlaceTight(), WorldGen.PlaceTile(), WorldGen.SolidTile(), WorldGen.SquareWallFrame(), Main.tile, and Tile.wall.