Terraria: Sandstorm.UpdateTime
UpdateTime()
static void Sandstorm.UpdateTime () inline static
     {
         if (Main.netMode != 1)
         {
             if (Happening)
             {
                 if (TimeLeft > 86400)
                 {
                     TimeLeft = 0;
                 }
                 TimeLeft -= Main.dayRate;
                 if (!HasSufficientWind())
                 {
                     TimeLeft -= 15 * Main.dayRate;
                 }
                 if (Main.windSpeedCurrent == 0f)
                 {
                     TimeLeft = 0;
                 }
                 if (TimeLeft <= 0)
                 {
                     StopSandstorm();
                 }
             }
             else
             {
                 int num = 21600;
                 num = ((!Main.hardMode) ? (num * 3) : (num * 2));
                 if (HasSufficientWind())
                 {
                     for (int i = 0; i < Main.dayRate; i++)
                     {
                         if (Main.rand.Next(num) == 0)
{
                             StartSandstorm();
                         }
                     }
                 }
             }
             if (Main.rand.Next(18000) == 0)
             {
                 ChangeSeverityIntentions();
             }
         }
         UpdateSeverity();
     }
References ChangeSeverityIntentions(), Main.dayRate, Happening, Main.hardMode, HasSufficientWind(), Main.netMode, UnifiedRandom.Next(), Main.rand, StartSandstorm(), StopSandstorm(), TimeLeft, UpdateSeverity(), and Main.windSpeedCurrent.
Referenced by Main.UpdateTime().