Terraria: Sandstorm.HandleEffectAndSky
HandleEffectAndSky()
static void Sandstorm.HandleEffectAndSky (bool toState) inline static
     {
         if (toState != _effectsUp)
         {
             _effectsUp = toState;
             Vector2 center = Main.player[Main.myPlayer].Center;
             if (_effectsUp)
             {
                 SkyManager.Instance.Activate("Sandstorm", center);
                 Filters.Scene.Activate("Sandstorm", center);
                 Overlays.Scene.Activate("Sandstorm", center);
             }
             else
             {
                 SkyManager.Instance.Deactivate("Sandstorm");
                 Filters.Scene.Deactivate("Sandstorm");
                 Overlays.Scene.Deactivate("Sandstorm");
             }
         }
     }
References _effectsUp, EffectManager< T >.Activate(), Entity.Center, EffectManager< T >.Deactivate(), SkyManager.Instance, Main.myPlayer, Main.player, Filters.Scene, and Overlays.Scene.
Referenced by EmitDust().