Terraria: Sandstorm.EmitDust
EmitDust()
static void Sandstorm.EmitDust () inline static
     {
         if (Main.gamePaused)
         {
             return;
         }
         int sandTileCount = Main.SceneMetrics.SandTileCount;
         Player player = Main.player[Main.myPlayer];
         bool flag = ShouldSandstormDustPersist();
         HandleEffectAndSky(flag && Main.UseStormEffects);
         if (sandTileCount < 100 || (double)player.position.Y > Main.worldSurface * 16.0 || player.ZoneBeach)
         {
             return;
         }
         int maxValue = 1;
         if (!flag || Main.rand.Next(maxValue) != 0)
         {
             return;
         }
         int num = Math.Sign(Main.windSpeedCurrent);
         float num2 = Math.Abs(Main.windSpeedCurrent);
         if (num2 < 0.01f)
         {
             return;
         }
         float num3 = (float)num * MathHelper.Lerp(0.9f, 1f, num2);
         float num4 = 2000f / (float)sandTileCount;
         float value = 3f / num4;
         value = MathHelper.Clamp(value, 0.77f, 1f);
         int num5 = (int)num4;
         float num6 = (float)Main.screenWidth / (float)Main.maxScreenW;
         int num7 = (int)(1000f * num6);
         float num8 = 20f * Severity;
         float num9 = (float)num7 * (Main.gfxQuality * 0.5f + 0.5f) + (float)num7 * 0.1f - (float)Dust.SandStormCount;
         if (num9 <= 0f)
         {
             return;
         }
         float num10 = (float)Main.screenWidth + 1000f;
         float num11 = Main.screenHeight;
         Vector2 vector = Main.screenPosition + player.velocity;
         WeightedRandom<Color> weightedRandom = new WeightedRandom<Color>();
         weightedRandom.Add(new Color(200, 160, 20, 180), Main.SceneMetrics.GetTileCount(53) + Main.SceneMetrics.GetTileCount(396) + Main.SceneMetrics.GetTileCount(397));
         weightedRandom.Add(new Color(103, 98, 122, 180), Main.SceneMetrics.GetTileCount(112) + Main.SceneMetrics.GetTileCount(400) + Main.SceneMetrics.GetTileCount(398));
         weightedRandom.Add(new Color(135, 43, 34, 180), Main.SceneMetrics.GetTileCount(234) + Main.SceneMetrics.GetTileCount(401) + Main.SceneMetrics.GetTileCount(399));
         weightedRandom.Add(new Color(213, 196, 197, 180), Main.SceneMetrics.GetTileCount(116) + Main.SceneMetrics.GetTileCount(403) + Main.SceneMetrics.GetTileCount(402));
         float num12 = MathHelper.Lerp(0.2f, 0.35f, Severity);
         float num13 = MathHelper.Lerp(0.5f, 0.7f, Severity);
         float amount = (value - 0.77f) / 0.23000002f;
         int maxValue2 = (int)MathHelper.Lerp(1f, 10f, amount);
         for (int i = 0; (float)i < num8; i++)
         {
             if (Main.rand.Next(num5 / 4) != 0)
             {
                 continue;
             }
             Vector2 position = new Vector2(Main.rand.NextFloat() * num10 - 500f, Main.rand.NextFloat() * -50f);
             if (Main.rand.Next(3) == 0 && num == 1)
             {
                 position.X = Main.rand.Next(500) - 500;
             }
             else if (Main.rand.Next(3) == 0 && num == -1)
             {
                 position.X = Main.rand.Next(500) + Main.screenWidth;
             }
             if (position.X < 0f || position.X > (float)Main.screenWidth)
             {
                 position.Y += Main.rand.NextFloat() * num11 * 0.9f;
             }
             position += vector;
             int num14 = (int)position.X / 16;
             int num15 = (int)position.Y / 16;
             if (!WorldGen.InWorld(num14, num15, 10) || Main.tile[num14, num15] == null || Main.tile[num14, num15].wall != 0)
             {
                 continue;
             }
             for (int j = 0; j < 1; j++)
             {
                 Dust dust = Main.dust[Dust.NewDust(position, 10, 10, 268)];
                 dust.velocity.Y = 2f + Main.rand.NextFloat() * 0.2f;
                 dust.velocity.Y *= dust.scale;
                 dust.velocity.Y *= 0.35f;
                 dust.velocity.X = num3 * 5f + Main.rand.NextFloat() * 1f;
                 dust.velocity.X += num3 * num13 * 20f;
                 dust.fadeIn += num13 * 0.2f;
                 dust.velocity *= 1f + num12 * 0.5f;
                 dust.color = weightedRandom;
                 dust.velocity *= 1f + num12;
                 dust.velocity *= value;
                 dust.scale = 0.9f;
                 num9 -= 1f;
                 if (num9 <= 0f)
                 {
                     break;
                 }
                 if (Main.rand.Next(maxValue2) != 0)
                 {
                     j--;
                     position += Utils.RandomVector2(Main.rand, -10f, 10f) + dust.velocity * -1.1f;
                     num14 = (int)position.X / 16;
                     num15 = (int)position.Y / 16;
                     if (WorldGen.InWorld(num14, num15, 10) && Main.tile[num14, num15] != null)
                     {
                         _ = Main.tile[num14, num15].wall;
                     }
                 }
             }
             if (num9 <= 0f)
             {
                 break;
             }
         }
     }
References WeightedRandom< T >.Add(), Color, Dust.color, Main.dust, Dust.fadeIn, Main.gamePaused, SceneMetrics.GetTileCount(), Main.gfxQuality, HandleEffectAndSky(), WorldGen.InWorld(), Main.maxScreenW, Main.myPlayer, Dust.NewDust(), UnifiedRandom.Next(), Main.player, Entity.position, Main.rand, Utils.RandomVector2(), Dust.SandStormCount, SceneMetrics.SandTileCount, Dust.scale, Main.SceneMetrics, Main.screenHeight, Main.screenPosition, Main.screenWidth, Severity, ShouldSandstormDustPersist(), Main.tile, Main.UseStormEffects, Dust.velocity, Entity.velocity, Tile.wall, Main.windSpeedCurrent, Main.worldSurface, and Player.ZoneBeach.
Referenced by Main.DoUpdate().