Terraria: MS.Internal.Xml.XPath.ForwardPositionQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.ForwardPositionQuery.Evaluate (XPathNodeIterator context) inline inherited
Definition at line 17 of file ForwardPositionQuery.cs.
    {
        base.Evaluate(context);
        XPathNavigator xPathNavigator;
        while ((xPathNavigator = input.Advance()) != null)
        {
            outputBuffer.Add(xPathNavigator.Clone());
        }
        return this;
    }
References System.Collections.Generic.List< T >.Add(), MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.CacheOutputQuery.input, and MS.Internal.Xml.XPath.CacheOutputQuery.outputBuffer.