Terraria: System.Xml.Linq.XElement.ReadXml
ReadXml()
void IXmlSerializable. System.Xml.Linq.XElement.ReadXml (XmlReader reader) inline private
Implements System.Xml.Serialization.IXmlSerializable.
Definition at line 961 of file XElement.cs.
    {
        if (reader == null)
        {
            throw new ArgumentNullException("reader");
        }
        if (parent != null || annotations != null || content != null || lastAttr != null)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_DeserializeInstance);
        }
        if (reader.MoveToContent() != XmlNodeType.Element)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_ExpectedNodeType, XmlNodeType.Element, reader.NodeType));
        }
        ReadElementFrom(reader, LoadOptions.None);
    }
References System.Xml.Linq.XObject.annotations, System.Xml.Linq.XContainer.content, System.SR.Format(), System.SR.InvalidOperation_DeserializeInstance, System.SR.InvalidOperation_ExpectedNodeType, System.Xml.Linq.XElement.lastAttr, System.Xml.XmlReader.MoveToContent(), System.Xml.XmlReader.NodeType, System.Xml.Linq.XObject.parent, and System.Xml.Linq.XElement.ReadElementFrom().