Terraria: System.Xml.Linq.XElement.LoadAsyncInternal
LoadAsyncInternal()
static async Task< XElement > System.Xml.Linq.XElement.LoadAsyncInternal (XmlReader reader, LoadOptions options, CancellationToken cancellationToken) inline static private
Definition at line 441 of file XElement.cs.
    {
        if (await reader.MoveToContentAsync().ConfigureAwait(continueOnCapturedContext: false) != XmlNodeType.Element)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.InvalidOperation_ExpectedNodeType, XmlNodeType.Element, reader.NodeType));
        }
        XElement e = new XElement(default(AsyncConstructionSentry));
        await e.ReadElementFromAsync(reader, options, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
        cancellationToken.ThrowIfCancellationRequested();
        await reader.MoveToContentAsync().ConfigureAwait(continueOnCapturedContext: false);
        if (!reader.EOF)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExpectedEndOfFile);
        }
        return e;
    }
References System.Xml.Linq.XElement.XElement(), System.cancellationToken, System.Xml.XmlReader.EOF, System.SR.Format(), System.SR.InvalidOperation_ExpectedEndOfFile, System.SR.InvalidOperation_ExpectedNodeType, System.Xml.XmlReader.MoveToContentAsync(), System.Xml.XmlReader.NodeType, System.options, and System.Xml.Linq.XElement.ReadElementFromAsync().
Referenced by System.Xml.Linq.XElement.LoadAsync().