Terraria: System.Xml.Linq.XElement.GetNamespaceOfPrefix
GetNamespaceOfPrefix()
XNamespace? System.Xml.Linq.XElement.GetNamespaceOfPrefix (string prefix) inline
Definition at line 279 of file XElement.cs.
    {
        if (prefix == null)
        {
            throw new ArgumentNullException("prefix");
        }
        if (prefix.Length == 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidPrefix, prefix));
        }
        if (prefix == "xmlns")
        {
            return XNamespace.Xmlns;
        }
        string namespaceOfPrefixInScope = GetNamespaceOfPrefixInScope(prefix, null);
        if (namespaceOfPrefixInScope != null)
        {
            return XNamespace.Get(namespaceOfPrefixInScope);
        }
        if (prefix == "xml")
        {
            return XNamespace.Xml;
        }
        return null;
    }
References System.SR.Argument_InvalidPrefix, System.Xml.ArgumentException, System.SR.Format(), System.Xml.Linq.XNamespace.Get(), System.Xml.Linq.XElement.GetNamespaceOfPrefixInScope(), System.prefix, System.Xml.Linq.XNamespace.Xml, and System.Xml.Linq.XNamespace.Xmlns.
Referenced by System.Xml.Linq.XNodeReader.GetNameInAttributeScope().