Terraria: System.Xml.Linq.XElement.RemoveAttribute
RemoveAttribute()
void System.Xml.Linq.XElement.RemoveAttribute (XAttribute a) inline package
Definition at line 1198 of file XElement.cs.
    {
        bool flag = NotifyChanging(a, XObjectChangeEventArgs.Remove);
        if (a.parent != this)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
        }
        XAttribute xAttribute = lastAttr;
        XAttribute xAttribute2;
        while ((xAttribute2 = xAttribute.next) != a)
        {
            xAttribute = xAttribute2;
        }
        if (xAttribute == a)
        {
            lastAttr = null;
        }
        else
        {
            if (lastAttr == a)
            {
                lastAttr = xAttribute;
            }
            xAttribute.next = a.next;
        }
        a.parent = null;
        a.next = null;
        if (flag)
        {
            NotifyChanged(a, XObjectChangeEventArgs.Remove);
        }
    }
References System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XElement.lastAttr, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), and System.Xml.Linq.XObjectChangeEventArgs.Remove.
Referenced by System.Xml.Linq.XElement.SetAttributeValue().