Terraria: System.Xml.Linq.XElement.WriteToAsync
WriteToAsync()
override Task System.Xml.Linq.XElement.WriteToAsync (XmlWriter writer, CancellationToken cancellationToken) inline
Definition at line 684 of file XElement.cs.
    {
        if (writer == null)
        {
            throw new ArgumentNullException("writer");
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        return new ElementWriter(writer).WriteElementAsync(this, cancellationToken);
    }
References System.cancellationToken, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Xml.Linq.ElementWriter.WriteElementAsync(), and System.writer.
Referenced by System.Xml.Linq.XElement.SaveAsyncInternal().