Terraria: System.Xml.Linq.XElement.ReadElementFromImpl
ReadElementFromImpl()
void System.Xml.Linq.XElement.ReadElementFromImpl (XmlReader r, LoadOptions o) inline private
Definition at line 1157 of file XElement.cs.
    {
        if (r.ReadState != ReadState.Interactive)
        {
            throw new InvalidOperationException(System.SR.InvalidOperation_ExpectedInteractive);
        }
        name = XNamespace.Get(r.NamespaceURI).GetName(r.LocalName);
        if ((o & LoadOptions.SetBaseUri) != 0)
        {
            string baseURI = r.BaseURI;
            if (!string.IsNullOrEmpty(baseURI))
            {
                SetBaseUri(baseURI);
            }
        }
        IXmlLineInfo xmlLineInfo = null;
        if ((o & LoadOptions.SetLineInfo) != 0)
        {
            xmlLineInfo = r as IXmlLineInfo;
            if (xmlLineInfo != null && xmlLineInfo.HasLineInfo())
            {
                SetLineInfo(xmlLineInfo.LineNumber, xmlLineInfo.LinePosition);
            }
        }
        if (!r.MoveToFirstAttribute())
        {
            return;
        }
        do
        {
            XAttribute xAttribute = new XAttribute(XNamespace.Get((r.Prefix.Length == 0) ? string.Empty : r.NamespaceURI).GetName(r.LocalName), r.Value);
            if (xmlLineInfo != null && xmlLineInfo.HasLineInfo())
            {
                xAttribute.SetLineInfo(xmlLineInfo.LineNumber, xmlLineInfo.LinePosition);
            }
            AppendAttributeSkipNotify(xAttribute);
        }
        while (r.MoveToNextAttribute());
        r.MoveToElement();
    }
References System.Xml.Linq.XElement.AppendAttributeSkipNotify(), System.Xml.Linq.XNamespace.Get(), System.SR.InvalidOperation_ExpectedInteractive, System.Xml.Linq.XElement.name, System.Xml.Linq.SetBaseUri, and System.Xml.Linq.SetLineInfo.
Referenced by System.Xml.Linq.XElement.ReadElementFrom(), and System.Xml.Linq.XElement.ReadElementFromAsync().