Terraria: System.Xml.Linq.XElement.RemoveAttributes
RemoveAttributes()
void System.Xml.Linq.XElement.RemoveAttributes () inline
Definition at line 477 of file XElement.cs.
    {
        if (SkipNotify())
        {
            RemoveAttributesSkipNotify();
            return;
        }
        while (lastAttr != null)
        {
            XAttribute xAttribute = lastAttr.next;
            NotifyChanging(xAttribute, XObjectChangeEventArgs.Remove);
            if (lastAttr == null || xAttribute != lastAttr.next)
            {
                throw new InvalidOperationException(System.SR.InvalidOperation_ExternalCode);
            }
            if (xAttribute != lastAttr)
            {
                lastAttr.next = xAttribute.next;
            }
            else
            {
                lastAttr = null;
            }
            xAttribute.parent = null;
            xAttribute.next = null;
            NotifyChanged(xAttribute, XObjectChangeEventArgs.Remove);
        }
    }
References System.Xml.Dictionary, System.SR.InvalidOperation_ExternalCode, System.Xml.Linq.XElement.lastAttr, System.Xml.Linq.XAttribute.next, System.Xml.Linq.XObject.NotifyChanged(), System.Xml.Linq.XObject.NotifyChanging(), System.Xml.Linq.XObjectChangeEventArgs.Remove, System.Xml.Linq.XElement.RemoveAttributesSkipNotify(), and System.Xml.Linq.XObject.SkipNotify().
Referenced by System.Xml.Linq.XElement.RemoveAll(), and System.Xml.Linq.XElement.ReplaceAttributes().