Terraria: Star.UpdateStars
UpdateStars()
static void Star.UpdateStars () inline static
     {
         if (!Main.dayTime)
         {
             dayCheck = false;
         }
         else if (!dayCheck && Main.time >= 27000.0)
         {
             for (int i = 0; i < Main.numStars; i++)
             {
                 if (Main.star[i].hidden)
                 {
                     SpawnStars(i);
                 }
             }
         }
         for (int j = 0; j < Main.numStars; j++)
         {
             Main.star[j].Update();
         }
     }
References dayCheck, Main.dayTime, hidden, Main.numStars, SpawnStars(), Main.star, Main.time, and Update().
Referenced by Main.DoUpdate(), and Main.DrawMenu().