Terraria: Star.Fall
Fall()
void Star.Fall () inline
     {
         fallTime = 0;
         falling = true;
         fallSpeed.Y = (float)Main.rand.Next(700, 1001) * 0.01f;
         fallSpeed.X = (float)Main.rand.Next(-400, 401) * 0.01f;
     }
References falling, fallSpeed, fallTime, UnifiedRandom.Next(), and Main.rand.
Referenced by Main.DoUpdate(), StarFall(), and Main.UpdateMenu().