Terraria: System.Threading.Thread.SetApartmentState
SetApartmentState() [1/2]
void System.Threading.Thread.SetApartmentState (ApartmentState state) inline
Definition at line 771 of file Thread.cs.
    {
        SetApartmentState(state, throwOnError: true);
    }
References System.Threading.Thread.SetApartmentState(), and System.state.
Referenced by ReLogic.OS.Windows.STATaskInvoker.STATaskInvoker(), ReLogic.OS.Windows.Clipboard.InvokeInStaThread(), ReLogic.OS.Windows.Clipboard.InvokeInStaThread< T >(), System.Threading.Thread.SetApartmentState(), and System.Threading.Thread.TrySetApartmentState().