Terraria: System.Threading.Thread.Yield
Yield()
static bool System.Threading.Thread.Yield () inline static
Definition at line 412 of file Thread.cs.
    {
        return YieldInternal() != Interop.BOOL.FALSE;
    }
References System.Threading.Thread.YieldInternal().
Referenced by ReLogic.Content.AssetRepository.SafelyWaitForLoad< T >(), System.Threading.SpinWait.SpinOnceCore(), and System.Threading.Tasks.Dataflow.Internal.Common.TryKeepAliveUntil< TStateIn, TStateOut >().