Terraria: System.Threading.Thread.Join
Join() [2/3]
bool System.Threading.Thread.Join (int millisecondsTimeout)
Referenced by System.Diagnostics.Metrics.AggregationManager.Dispose(), ReLogic.OS.Windows.Clipboard.InvokeInStaThread(), ReLogic.OS.Windows.Clipboard.InvokeInStaThread< T >(), and ReLogic.Threading.AsyncActionDispatcher.Stop().