Terraria: Terraria.Social.Steam.NetServerSocialModule.Initialize
Initialize()
override void Terraria.Social.Steam.NetServerSocialModule.Initialize () inline
Implements Terraria.Social.ISocialModule.
    {
        base.Initialize();
        _reader.SetReadEvent(OnPacketRead);
        _p2pSessionRequest = Callback<P2PSessionRequest_t>.Create((DispatchDelegate<P2PSessionRequest_t>)OnP2PSessionRequest);
        if (Program.LaunchParameters.ContainsKey("-lobby"))
        {
            _mode |= ServerMode.Lobby;
            string text = Program.LaunchParameters["-lobby"];
            if (!(text == "private"))
            {
                if (text == "friends")
                {
                    _mode |= ServerMode.FriendsCanJoin;
                    _lobby.Create(inviteOnly: false, OnLobbyCreated);
                }
                else
                {
                    Console.WriteLine(Language.GetTextValue("Error.InvalidLobbyFlag", "private", "friends"));
                }
            }
            else
            {
                _lobby.Create(inviteOnly: true, OnLobbyCreated);
            }
        }
        if (Program.LaunchParameters.ContainsKey("-friendsoffriends"))
        {
            _mode |= ServerMode.FriendsOfFriends;
        }
    }
References Terraria.Social.Steam.NetSocialModule._lobby, Terraria.Social.Steam.NetServerSocialModule._mode, Terraria.Social.Steam.NetServerSocialModule._p2pSessionRequest, Terraria.Social.Steam.NetSocialModule._reader, Terraria.Social.Steam.Lobby.Create(), Terraria.Localization.Language.GetTextValue(), Terraria.Program.LaunchParameters, Terraria.Social.Steam.NetServerSocialModule.OnLobbyCreated(), Terraria.Social.Steam.NetServerSocialModule.OnP2PSessionRequest(), Terraria.Social.Steam.NetServerSocialModule.OnPacketRead(), and Terraria.Social.Steam.SteamP2PReader.SetReadEvent().