Terraria: System.Threading.Thread.Sleep
Sleep() [1/2]
static void System.Threading.Thread.Sleep (int millisecondsTimeout) inline static
Definition at line 658 of file Thread.cs.
    {
        if (millisecondsTimeout < -1)
        {
            throw new ArgumentOutOfRangeException("millisecondsTimeout", millisecondsTimeout, SR.ArgumentOutOfRange_NeedNonNegOrNegative1);
        }
        SleepInternal(millisecondsTimeout);
    }
References System.SR.ArgumentOutOfRange_NeedNonNegOrNegative1, System.millisecondsTimeout, and System.Threading.Thread.SleepInternal().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._gamesenseWrk(), System.Threading.ReaderWriterLock.AcquireReaderLock(), System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Runtime.InteropServices.HandleCollector.Add(), Terraria.Netplay.BroadcastThread(), System.IO.MemoryMappedFiles.MemoryMappedFile.CreateOrOpenCore(), Terraria.Main.DedServ(), System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners(), System.Threading.ReaderWriterLock.DowngradeFromWriterLock(), System.Threading.ReaderWriterLockSlim.SpinLock.EnterSpin(), System.Transactions.CheapUnfairReaderWriterLock.EnterWriteLock(), System.Diagnostics.NtProcessManager.EnumProcessModulesUntilSuccess(), Terraria.Graphics.Capture.CaptureCamera.FinishCapture(), System.IO.MemoryMappedFiles.MemoryMappedView.Flush(), System.Diagnostics.PerformanceCounterLib.PerformanceMonitor.GetData(), System.Diagnostics.PerformanceCounterLib.GetStringTable(), Terraria.Social.Steam.AchievementsSocialModule.Initialize(), Terraria.Social.WeGame.AchievementsSocialModule.Initialize(), Terraria.Netplay.InnerClientLoop(), Terraria.WorldGen.playWorldCallBack(), Terraria.Net.Sockets.SocialSocket.ReadCallback(), System.Threading.ReaderWriterLock.ReleaseReaderLock(), System.Threading.ReaderWriterLock.ReleaseWriterLock(), System.Diagnostics.Tracing.EventSource.SendManifest(), Terraria.Netplay.ServerLoop(), System.Threading.SpinWait.SpinOnceCore(), System.Threading.ReaderWriterLockSlim.SpinWait(), Terraria.Netplay.TcpClientLoop(), System.Net.TimerThread.ThreadProc(), and Terraria.FrameSkipTest.Update().