Terraria: System.Threading.Thread.GetCurrentProcessorId
GetCurrentProcessorId()
static int System.Threading.Thread.GetCurrentProcessorId () inline static
Definition at line 501 of file Thread.cs.
    {
        if (s_isProcessorNumberReallyFast)
        {
            return GetCurrentProcessorNumber();
        }
        return ProcessorIdCache.GetCurrentProcessorId();
    }
References System.Threading.ProcessorIdCache.GetCurrentProcessorId(), System.Threading.Thread.GetCurrentProcessorNumber(), and System.Threading.Thread.s_isProcessorNumberReallyFast.
Referenced by System.Threading.TimerQueueTimer.TimerQueueTimer(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPop(), and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.TryPush().