Terraria: Terraria.Social.Steam.NetServerSocialModule.OnP2PSessionRequest
OnP2PSessionRequest()
void Terraria.Social.Steam.NetServerSocialModule.OnP2PSessionRequest (P2PSessionRequest_t result) inline private
Definition at line 232 of file NetServerSocialModule.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Invalid comparison between Unknown and I4
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        CSteamID steamIDRemote = result.m_steamIDRemote;
        if (_connectionStateMap.ContainsKey(steamIDRemote) && _connectionStateMap[steamIDRemote] != 0)
        {
            SteamNetworking.AcceptP2PSessionWithUser(steamIDRemote);
        }
        else if (_acceptingClients && (_mode.HasFlag(ServerMode.FriendsOfFriends) || (int)SteamFriends.GetFriendRelationship(steamIDRemote) == 3))
        {
            SteamNetworking.AcceptP2PSessionWithUser(steamIDRemote);
            P2PSessionState_t val = default(P2PSessionState_t);
            while (SteamNetworking.GetP2PSessionState(steamIDRemote, ref val) && val.m_bConnecting == 1)
            {
            }
            if (val.m_bConnectionActive == 0)
            {
                Close(steamIDRemote);
            }
            _connectionStateMap[steamIDRemote] = ConnectionState.Authenticating;
            _connectionAcceptedCallback(new SocialSocket(new SteamAddress(steamIDRemote)));
        }
    }
References Terraria.Social.Steam.NetServerSocialModule._acceptingClients, Terraria.Social.Steam.NetServerSocialModule._connectionAcceptedCallback, Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetServerSocialModule._mode, Terraria.Social.Steam.NetServerSocialModule.Close(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ContainsKey().
Referenced by Terraria.Social.Steam.NetServerSocialModule.Initialize(), and Terraria.Social.Steam.NetServerSocialModule.OnPacketRead().