Terraria: System.Xml.Serialization.ReflectionXmlSerializationHelper.GetMember
GetMember()
static MemberInfo System.Xml.Serialization.ReflectionXmlSerializationHelper.GetMember (Type declaringType, string memberName, bool throwOnNotFound) inline static
Definition at line 9 of file ReflectionXmlSerializationHelper.cs.
    {
        MemberInfo[] member = declaringType.GetMember(memberName);
        if (member == null || member.Length == 0)
        {
            bool flag = false;
            Type baseType = declaringType.BaseType;
            while (baseType != null)
            {
                member = baseType.GetMember(memberName);
                if (member != null && member.Length != 0)
                {
                    flag = true;
                    break;
                }
                baseType = baseType.BaseType;
            }
            if (!flag)
            {
                if (throwOnNotFound)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInternalErrorDetails, $"Could not find member named {memberName} of type {declaringType}"));
                }
                return null;
            }
            declaringType = baseType;
        }
        MemberInfo result = member[0];
        if (member.Length != 1)
        {
            MemberInfo[] array = member;
            foreach (MemberInfo memberInfo in array)
            {
                if (declaringType == memberInfo.DeclaringType)
                {
                    result = memberInfo;
                    break;
                }
            }
        }
        return result;
    }
References System.array, System.Type.BaseType, System.Xml.Dictionary, System.SR.Format(), and System.SR.XmlInternalErrorDetails.
Referenced by System.Xml.Serialization.ReflectionXmlSerializationHelper.GetEffectiveGetInfo(), and System.Xml.Serialization.ReflectionXmlSerializationHelper.GetEffectiveSetInfo().