Terraria: System.Xml.XmlBaseReader.AttributeSorter.Sort
Sort() [1/2]
bool System.Xml.XmlBaseReader.AttributeSorter.Sort () inline private
Definition at line 507 of file XmlBaseReader.cs.
        {
            if (_indeces != null && _indeces.Length == _attributeCount && IsSorted())
            {
                return true;
            }
            object[] array = new object[_attributeCount];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = i;
            }
            _indeces = array;
            Array.Sort(_indeces, 0, _attributeCount, this);
            return IsSorted();
        }
References System.Xml.XmlBaseReader.AttributeSorter._attributeCount, System.Xml.XmlBaseReader.AttributeSorter._indeces, System.array, System.Xml.XmlBaseReader.AttributeSorter.IsSorted(), and System.Array.Sort().
Referenced by System.Xml.XmlBaseReader.AttributeSorter.Sort().