Terraria: Terraria.Chat.Commands.EmojiCommand.Initialize
Initialize()
void Terraria.Chat.Commands.EmojiCommand.Initialize () inline
Definition at line 20 of file EmojiCommand.cs.
    {
        _byName.Clear();
        for (int i = 0; i < EmoteID.Count; i++)
        {
            LocalizedText emojiName = Lang.GetEmojiName(i);
            if (emojiName != LocalizedText.Empty)
            {
                _byName[emojiName] = i;
            }
        }
    }
References Terraria.Chat.Commands.EmojiCommand._byName, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.GameContent.UI.EmoteID.Count, Terraria.Localization.LocalizedText.Empty, and Terraria.Lang.GetEmojiName().
Referenced by Terraria.Chat.Commands.EmojiCommand.EmojiCommand().