Terraria: OverlayManager.Draw
Draw()
void OverlayManager.Draw (SpriteBatch spriteBatch, RenderLayers layer) inline
     {
         if (_overlayCount == 0)
         {
             return;
         }
         bool flag = false;
         for (int i = 0; i < _activeOverlays.Length; i++)
         {
             for (LinkedListNode<Overlay> linkedListNode = _activeOverlays[i].First; linkedListNode != null; linkedListNode = linkedListNode.Next)
             {
                 Overlay value = linkedListNode.Value;
                 if (value.Layer == layer && value.IsVisible())
                 {
                     if (!flag)
                     {
                         spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                         flag = true;
                     }
                     value.Draw(spriteBatch);
                 }
             }
         }
         if (flag)
         {
             spriteBatch.End();
         }
     }
References _activeOverlays, _overlayCount, Overlay.Draw(), GameEffect.IsVisible(), Overlay.Layer, and Main.Transform.
Referenced by Main.DoDraw(), and Main.DoDraw_WallsAndBlacks().