Terraria: Terraria.Graphics.TileBatch.RenderBatch
RenderBatch()
unsafe void Terraria.Graphics.TileBatch.RenderBatch (Texture2D texture, SpriteData[] sprites, int offset, int count) inline private
Definition at line 281 of file TileBatch.cs.
    {
        _graphicsDevice.Textures[0] = texture;
        float num = 1f / (float)texture.Width;
        float num2 = 1f / (float)texture.Height;
        while (count > 0)
        {
            SetDataOptions options = SetDataOptions.NoOverwrite;
            int num3 = count;
            if (num3 > 2048 - _vertexBufferPosition)
            {
                num3 = 2048 - _vertexBufferPosition;
                if (num3 < 256)
                {
                    _vertexBufferPosition = 0;
                    options = SetDataOptions.Discard;
                    num3 = count;
                    if (num3 > 2048)
                    {
                        num3 = 2048;
                    }
                }
            }
            fixed (SpriteData* ptr = &sprites[offset])
            {
                fixed (VertexPositionColorTexture* ptr3 = &_vertices[0])
                {
                    SpriteData* ptr2 = ptr;
                    VertexPositionColorTexture* ptr4 = ptr3;
                    for (int i = 0; i < num3; i++)
                    {
                        float num4;
                        float num5;
                        if (ptr2->Rotation != 0f)
{
                            num4 = (float)Math.Cos(ptr2->Rotation);
                            num5 = (float)Math.Sin(ptr2->Rotation);
                        }
                        else
{
                            num4 = 1f;
                            num5 = 0f;
                        }
                        float num6 = ptr2->Origin.X / ptr2->Source.Z;
                        float num7 = ptr2->Origin.Y / ptr2->Source.W;
                        ptr4->Color = ptr2->Colors.TopLeftColor;
                        ptr4[1].Color = ptr2->Colors.TopRightColor;
                        ptr4[2].Color = ptr2->Colors.BottomRightColor;
                        ptr4[3].Color = ptr2->Colors.BottomLeftColor;
                        for (int j = 0; j < 4; j++)
{
                            float num8 = CORNER_OFFSET_X[j];
                            float num9 = CORNER_OFFSET_Y[j];
                            float num10 = (num8 - num6) * ptr2->Destination.Z;
                            float num11 = (num9 - num7) * ptr2->Destination.W;
                            float x = ptr2->Destination.X + num10 * num4 - num11 * num5;
                            float y = ptr2->Destination.Y + num10 * num5 + num11 * num4;
                            if ((ptr2->Effects & SpriteEffects.FlipVertically) != 0)
{
                                num9 = 1f - num9;
                            }
                            if ((ptr2->Effects & SpriteEffects.FlipHorizontally) != 0)
{
                                num8 = 1f - num8;
                            }
                            ptr4->Position.X = x;
                            ptr4->Position.Y = y;
                            ptr4->Position.Z = 0f;
                            ptr4->TextureCoordinate.X = (ptr2->Source.X + num8 * ptr2->Source.Z) * num;
                            ptr4->TextureCoordinate.Y = (ptr2->Source.Y + num9 * ptr2->Source.W) * num2;
                            ptr4++;
                        }
                        ptr2++;
                    }
                }
            }
            int offsetInBytes = _vertexBufferPosition * sizeof(VertexPositionColorTexture) * 4;
            _vertexBuffer.SetData(offsetInBytes, _vertices, 0, num3 * 4, sizeof(VertexPositionColorTexture), options);
            int minVertexIndex = _vertexBufferPosition * 4;
            int numVertices = num3 * 4;
            int startIndex = _vertexBufferPosition * 6;
            int primitiveCount = num3 * 2;
            _graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, minVertexIndex, numVertices, startIndex, primitiveCount);
            _vertexBufferPosition += num3;
            offset += num3;
            count -= num3;
        }
    }
References Terraria.Graphics.TileBatch._graphicsDevice, Terraria.Graphics.TileBatch._vertexBuffer, Terraria.Graphics.TileBatch._vertexBufferPosition, Terraria.Graphics.TileBatch._vertices, Terraria.Graphics.VertexColors.BottomLeftColor, Terraria.Graphics.VertexColors.BottomRightColor, Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.Color, Terraria.Graphics.TileBatch.SpriteData.Colors, Terraria.Graphics.TileBatch.CORNER_OFFSET_X, Terraria.Graphics.TileBatch.CORNER_OFFSET_Y, System.Math.Cos(), System.count, Terraria.Graphics.TileBatch.SpriteData.Destination, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Terraria.Graphics.TileBatch.SpriteData.Effects, Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.offset, System.options, Terraria.Graphics.TileBatch.SpriteData.Origin, Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.Position, Terraria.Graphics.TileBatch.SpriteData.Rotation, System.Math.Sin(), Terraria.Graphics.TileBatch.SpriteData.Source, System.startIndex, Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.TextureCoordinate, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Terraria.Graphics.VertexColors.TopLeftColor, Terraria.Graphics.VertexColors.TopRightColor, Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, Microsoft.Xna.Framework.Vector4.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector4.Z.
Referenced by Terraria.Graphics.TileBatch.Flush().