Terraria: Terraria.Graphics.TileBatch.FlushRenderState
FlushRenderState()
void Terraria.Graphics.TileBatch.FlushRenderState () inline private
Definition at line 95 of file TileBatch.cs.
    {
        Allocate();
        _graphicsDevice.SetVertexBuffer(_vertexBuffer);
        _graphicsDevice.Indices = _indexBuffer;
        _graphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
    }
References Terraria.Graphics.TileBatch._graphicsDevice, Terraria.Graphics.TileBatch._indexBuffer, Terraria.Graphics.TileBatch._vertexBuffer, Terraria.Graphics.TileBatch.Allocate(), Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer().
Referenced by Terraria.Graphics.TileBatch.End().