Terraria: Terraria.Graphics.TileBatch.Begin
Begin() [2/2]
void Terraria.Graphics.TileBatch.Begin (RasterizerState rasterizer, Matrix transformation) inline
Definition at line 115 of file TileBatch.cs.
    {
        _spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, rasterizer, null, transformation);
        _spriteBatch.End();
    }
References Terraria.Graphics.TileBatch._spriteBatch, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.End().
Referenced by Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), and Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().