Terraria: Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget
CreateRenderTarget()
void Microsoft.Xna.Framework.Graphics.RenderTarget2D.CreateRenderTarget (GraphicsDevice graphicsDevice, int width, int height, [MarshalAs(UnmanagedType.U1)] bool mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, int preferredMultiSampleCount, RenderTargetUsage usage) inline package
Definition at line 99 of file RenderTarget2D.cs.
    {
        if (graphicsDevice == null)
        {
            throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
        }
        graphicsDevice.Adapter.QueryFormat(isBackBuffer: false, graphicsDevice._deviceType, graphicsDevice._graphicsProfile, preferredFormat, preferredDepthFormat, preferredMultiSampleCount, out var selectedFormat, out var selectedDepthFormat, out var selectedMultiSampleCount);
        Texture2D.ValidateCreationParameters(graphicsDevice._profileCapabilities, width, height, selectedFormat, mipMap);
        (helper = new RenderTargetHelper(this, width, height, selectedFormat, selectedDepthFormat, selectedMultiSampleCount, usage, graphicsDevice._profileCapabilities)).CreateSurfaces(graphicsDevice);
        CreateTexture(graphicsDevice, width, height, mipMap, 1u, (_D3DPOOL)0, selectedFormat);
        renderTargetContentsDirty = true;
    }
References Microsoft.Xna.Framework.Graphics.GraphicsDevice._deviceType, Microsoft.Xna.Framework.Graphics.GraphicsDevice._graphicsProfile, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Adapter, Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, Microsoft.Xna.Framework.Graphics.RenderTarget2D.helper, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.QueryFormat(), Microsoft.Xna.Framework.Graphics.Texture.renderTargetContentsDirty, and Microsoft.Xna.Framework.Graphics.Texture2D.ValidateCreationParameters().
Referenced by Microsoft.Xna.Framework.Graphics.RenderTarget2D.RenderTarget2D(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.RenderTarget2D(), and Microsoft.Xna.Framework.Graphics.RenderTarget2D.RenderTarget2D().