Terraria: Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject
RecreateAndPopulateObject() [1/2]
unsafe override int Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject () inline package virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.Texture2D.
Definition at line 123 of file RenderTarget2D.cs.
    {
        if (pComPtr != null)
        {
            return -2147467259;
        }
        int num = ((_levelCount > 1) ? 1 : 0);
        CreateTexture(_parent, _width, _height, (byte)num != 0, 1u, (_D3DPOOL)0, _format);
        helper.CreateSurfaces(_parent);
        renderTargetContentsDirty = true;
        return 0;
    }
References Microsoft.Xna.Framework.Graphics.Texture._format, Microsoft.Xna.Framework.Graphics.Texture2D._height, Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.Texture2D._width, Microsoft.Xna.Framework.Graphics.RenderTargetHelper.CreateSurfaces(), Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture(), Microsoft.Xna.Framework.Graphics.RenderTarget2D.helper, Microsoft.Xna.Framework.Graphics.Texture2D.pComPtr, and Microsoft.Xna.Framework.Graphics.Texture.renderTargetContentsDirty.
Referenced by Microsoft.Xna.Framework.Graphics.RenderTarget2D.RecreateAndPopulateObject().