Terraria: Interop.GetRandomBytes
GetRandomBytes()
static unsafe void Interop.GetRandomBytes (byte * buffer, int length) inline static package
Definition at line 1871 of file Interop.cs.
    {
        switch (BCrypt.BCryptGenRandom(IntPtr.Zero, buffer, length, 2))
        {
        case BCrypt.NTSTATUS.STATUS_NO_MEMORY:
            throw new OutOfMemoryException();
        default:
            throw new InvalidOperationException();
        case BCrypt.NTSTATUS.STATUS_SUCCESS:
            break;
        }
    }
References Interop.BCrypt.BCryptGenRandom(), System.buffer, System.length, and System.IntPtr.Zero.
Referenced by System.Collections.Generic.RandomizedStringEqualityComparer.RandomizedStringEqualityComparer(), System.Random.XoshiroImpl.XoshiroImpl(), System.HashCode.GenerateGlobalSeed(), System.Marvin.GenerateSeed(), and System.IO.Path.GetRandomFileName().