Terraria: System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory
ExtractRelativeToDirectory()
static void System.IO.Compression.ZipFileExtensions.ExtractRelativeToDirectory (this ZipArchiveEntry source, string destinationDirectoryName, bool overwrite) inline static package
Definition at line 98 of file ZipFileExtensions.cs.
    {
        if (source == null)
        {
            throw new ArgumentNullException("source");
        }
        if (destinationDirectoryName == null)
        {
            throw new ArgumentNullException("destinationDirectoryName");
        }
        DirectoryInfo directoryInfo = Directory.CreateDirectory(destinationDirectoryName);
        string text = directoryInfo.FullName;
        if (!text.EndsWith(Path.DirectorySeparatorChar))
        {
            text += Path.DirectorySeparatorChar;
        }
        string fullPath = Path.GetFullPath(Path.Combine(text, source.FullName));
        if (!fullPath.StartsWith(text, System.IO.PathInternal.StringComparison))
        {
            throw new IOException(System.SR.IO_ExtractingResultsInOutside);
        }
        if (Path.GetFileName(fullPath).Length == 0)
        {
            if (source.Length != 0L)
            {
                throw new IOException(System.SR.IO_DirectoryNameWithData);
            }
            Directory.CreateDirectory(fullPath);
        }
        else
        {
            Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
            source.ExtractToFile(fullPath, overwrite);
        }
    }
References System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.IO.Path.DirectorySeparatorChar, System.IO.FileSystemInfo.FullName, System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.SR.IO_DirectoryNameWithData, System.SR.IO_ExtractingResultsInOutside, System.L, System.source, System.IO.PathInternal.StringComparison, and System.text.