Terraria: System.Xml.XPath.XPathNavigator.CheckValidity
CheckValidity()
virtual bool System.Xml.XPath.XPathNavigator.CheckValidity (XmlSchemaSet schemas, ValidationEventHandler validationEventHandler) inline virtual inherited
Reimplemented in System.Xml.DocumentXPathNavigator.
Definition at line 1189 of file XPathNavigator.cs.
    {
        XmlSchemaType xmlSchemaType = null;
        XmlSchemaElement xmlSchemaElement = null;
        XmlSchemaAttribute xmlSchemaAttribute = null;
        switch (NodeType)
        {
        case XPathNodeType.Root:
            if (schemas == null)
            {
                throw new InvalidOperationException(System.SR.XPathDocument_MissingSchemas);
            }
            xmlSchemaType = null;
            break;
        case XPathNodeType.Element:
        {
            if (schemas == null)
            {
                throw new InvalidOperationException(System.SR.XPathDocument_MissingSchemas);
            }
            IXmlSchemaInfo schemaInfo = SchemaInfo;
            if (schemaInfo != null)
            {
                xmlSchemaType = schemaInfo.SchemaType;
                xmlSchemaElement = schemaInfo.SchemaElement;
            }
            if (xmlSchemaType == null && xmlSchemaElement == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XPathDocument_NotEnoughSchemaInfo, null));
            }
            break;
        }
        case XPathNodeType.Attribute:
        {
            if (schemas == null)
            {
                throw new InvalidOperationException(System.SR.XPathDocument_MissingSchemas);
            }
            IXmlSchemaInfo schemaInfo = SchemaInfo;
            if (schemaInfo != null)
            {
                xmlSchemaType = schemaInfo.SchemaType;
                xmlSchemaAttribute = schemaInfo.SchemaAttribute;
            }
            if (xmlSchemaType == null && xmlSchemaAttribute == null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XPathDocument_NotEnoughSchemaInfo, null));
            }
            break;
        }
        default:
            throw new InvalidOperationException(System.SR.Format(System.SR.XPathDocument_ValidateInvalidNodeType, null));
        }
        XPathNavigatorReader reader = (XPathNavigatorReader)CreateReader();
        CheckValidityHelper checkValidityHelper = new CheckValidityHelper(validationEventHandler, reader);
        validationEventHandler = checkValidityHelper.ValidationCallback;
        XmlReader validatingReader = GetValidatingReader(reader, schemas, validationEventHandler, xmlSchemaType, xmlSchemaElement, xmlSchemaAttribute);
        while (validatingReader.Read())
        {
        }
        return checkValidityHelper.IsValid;
    }
References System.Xml.XPath.XPathNavigator.CreateReader(), System.SR.Format(), System.Xml.XPath.XPathNavigator.GetValidatingReader(), System.Xml.XPath.XPathNavigator.NodeType, System.Xml.Schema.IXmlSchemaInfo.SchemaAttribute, System.Xml.Schema.IXmlSchemaInfo.SchemaElement, System.Xml.XPath.XPathNavigator.SchemaInfo, System.Xml.Schema.IXmlSchemaInfo.SchemaType, System.SR.XPathDocument_MissingSchemas, System.SR.XPathDocument_NotEnoughSchemaInfo, and System.SR.XPathDocument_ValidateInvalidNodeType.