Terraria: System.Xml.XPath.XPathNavigator.CreateContextReader
CreateContextReader()
XmlReader System.Xml.XPath.XPathNavigator.CreateContextReader (string xml, bool fromCurrentNode) inline private inherited
Definition at line 1873 of file XPathNavigator.cs.
    {
        if (xml == null)
        {
            throw new ArgumentNullException("xml");
        }
        XPathNavigator xPathNavigator = CreateNavigator();
        XmlNamespaceManager xmlNamespaceManager = new XmlNamespaceManager(NameTable);
        if (!fromCurrentNode)
        {
            xPathNavigator.MoveToParent();
        }
        if (xPathNavigator.MoveToFirstNamespace(XPathNamespaceScope.All))
        {
            do
            {
                xmlNamespaceManager.AddNamespace(xPathNavigator.LocalName, xPathNavigator.Value);
            }
            while (xPathNavigator.MoveToNextNamespace(XPathNamespaceScope.All));
        }
        XmlParserContext context = new XmlParserContext(NameTable, xmlNamespaceManager, null, XmlSpace.Default);
        XmlTextReader xmlTextReader = new XmlTextReader(xml, XmlNodeType.Element, context);
        xmlTextReader.WhitespaceHandling = WhitespaceHandling.Significant;
        return xmlTextReader;
    }
References System.Xml.XPath.XPathNavigator.CreateNavigator(), and System.Xml.Dictionary.
Referenced by System.Xml.XPath.XPathNavigator.AppendChild(), System.Xml.XPath.XPathNavigator.InsertAfter(), System.Xml.XPath.XPathNavigator.InsertBefore(), System.Xml.XPath.XPathNavigator.PrependChild(), and System.Xml.XPath.XPathNavigator.ReplaceSelf().