Terraria: System.Xml.XPath.XPathNavigator.IsDescendant
IsDescendant()
virtual bool System.Xml.XPath.XPathNavigator.IsDescendant ([NotNullWhen(true)] XPathNavigator? nav) inline virtual inherited
Definition at line 1116 of file XPathNavigator.cs.
    {
        if (nav != null)
        {
            nav = nav.Clone();
            while (nav.MoveToParent())
            {
                if (nav.IsSamePosition(this))
                {
                    return true;
                }
            }
        }
        return false;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.IsSamePosition(), and System.Xml.XPath.XPathNavigator.MoveToParent().
Referenced by MS.Internal.Xml.XPath.FollowingQuery.Advance(), MS.Internal.Xml.XPath.FollSiblingQuery.Advance(), System.Xml.Xsl.Runtime.DescendantMergeIterator.MoveNext(), and System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext().