Terraria: System.Xml.XPath.XPathNavigator.LookupNamespace
LookupNamespace()
virtual ? string System.Xml.XPath.XPathNavigator.LookupNamespace (string prefix) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Reimplemented in System.Xml.DocumentXPathNavigator.
Definition at line 715 of file XPathNavigator.cs.
    {
        if (prefix == null)
        {
            return null;
        }
        if (NodeType != XPathNodeType.Element)
        {
            XPathNavigator xPathNavigator = Clone();
            if (xPathNavigator.MoveToParent())
            {
                return xPathNavigator.LookupNamespace(prefix);
            }
        }
        else if (MoveToNamespace(prefix))
        {
            string value = Value;
            MoveToParent();
            return value;
        }
        if (prefix.Length == 0)
        {
            return string.Empty;
        }
        if (prefix == "xml")
        {
            return "http://www.w3.org/XML/1998/namespace";
        }
        if (prefix == "xmlns")
        {
            return "http://www.w3.org/2000/xmlns/";
        }
        return null;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.MoveToNamespace(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NodeType, System.prefix, System.value, and System.Xml.XPath.XPathItem.Value.
Referenced by System.Xml.XPath.XPathNavigatorReader.LookupNamespace(), System.Xml.XPath.XPathNavigator.LookupPrefix(), and System.Xml.Xsl.Runtime.XsltFunctions.MSNamespaceUri().