Terraria: System.Xml.XPath.XPathNavigator.GetNamespacesInScope
GetNamespacesInScope()
virtual IDictionary< string, string > System.Xml.XPath.XPathNavigator.GetNamespacesInScope (XmlNamespaceScope scope) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Definition at line 790 of file XPathNavigator.cs.
    {
        XPathNodeType nodeType = NodeType;
        if ((nodeType != XPathNodeType.Element && scope != XmlNamespaceScope.Local) || nodeType == XPathNodeType.Attribute || nodeType == XPathNodeType.Namespace)
        {
            XPathNavigator xPathNavigator = Clone();
            if (xPathNavigator.MoveToParent())
            {
                return xPathNavigator.GetNamespacesInScope(scope);
            }
        }
        Dictionary<string, string> dictionary = new Dictionary<string, string>();
        if (scope == XmlNamespaceScope.All)
        {
            dictionary["xml"] = "http://www.w3.org/XML/1998/namespace";
        }
        if (MoveToFirstNamespace((XPathNamespaceScope)scope))
        {
            do
            {
                string localName = LocalName;
                string value = Value;
                if (localName.Length != 0 || value.Length != 0 || scope == XmlNamespaceScope.Local)
                {
                    dictionary[localName] = value;
                }
            }
            while (MoveToNextNamespace((XPathNamespaceScope)scope));
            MoveToParent();
        }
        return dictionary;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.dictionary, System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NodeType, System.value, and System.Xml.XPath.XPathItem.Value.
Referenced by System.Xml.XPath.XPathNavigatorReader.GetNamespacesInScope().