Terraria: System.Xml.XPath.XPathNavigator.Evaluate
Evaluate() [4/4]
virtual object System.Xml.XPath.XPathNavigator.Evaluate (XPathExpression expr, XPathNodeIterator? context) inline virtual inherited
Definition at line 1333 of file XPathNavigator.cs.
    {
        if (!(expr is CompiledXpathExpr compiledXpathExpr))
        {
            throw XPathException.Create(System.SR.Xp_BadQueryObject);
        }
        Query query = Query.Clone(compiledXpathExpr.QueryTree);
        query.Reset();
        if (context == null)
        {
            context = new XPathSingletonIterator(Clone(), moved: true);
        }
        object obj = query.Evaluate(context);
        if (obj is XPathNodeIterator)
        {
            return new XPathSelectionIterator(context.Current, query);
        }
        return obj;
    }
References System.Xml.XPath.XPathNavigator.Clone(), MS.Internal.Xml.XPath.Query.Clone(), System.Xml.XPath.XPathException.Create(), System.Xml.XPath.XPathNodeIterator.Current, System.obj, and System.SR.Xp_BadQueryObject.