Terraria: TrackGenerator.GetHistorySegmentPlacementState
GetHistorySegmentPlacementState()
TrackPlacementState TrackGenerator.GetHistorySegmentPlacementState (int startIndex, int length) inline private
     {
         TrackPlacementState result = TrackPlacementState.Available;
         for (int i = startIndex; i < startIndex + length; i++)
         {
             TrackPlacementState trackPlacementState = CalculateStateForLocation(_history[i].X, _history[i].Y);
             switch (trackPlacementState)
             {
             case TrackPlacementState.Invalid:
                 return trackPlacementState;
             case TrackPlacementState.Obstructed:
                 if (_history[i].Mode != TrackMode.Tunnel)
                 {
                     result = trackPlacementState;
                 }
                 break;
             }
         }
         return result;
     }
References _history, CalculateStateForLocation(), X, and Y.
Referenced by FindPath(), and TryRewriteHistoryToAvoidTiles().