Terraria: TrackGenerator.FindPath
FindPath()
bool TrackGenerator.FindPath (int minLength, int maxLength) inline private
     {
         int length = _length;
         while (_length < _history.Length - 100)
         {
             TrackSlope slope = ((_history[_length - 1].Slope != TrackSlope.Up) ? TrackSlope.Down : TrackSlope.Straight);
             AppendToHistory(slope);
             TrackPlacementState trackPlacementState = TryRewriteHistoryToAvoidTiles();
             if (trackPlacementState == TrackPlacementState.Invalid)
             {
                 break;
             }
             length = _length;
             TrackPlacementState trackPlacementState2 = trackPlacementState;
             while (trackPlacementState2 != 0)
             {
                 trackPlacementState2 = CreateTunnel();
                 if (trackPlacementState2 == TrackPlacementState.Invalid)
                 {
                     break;
                 }
                 length = _length;
             }
             if (_length >= maxLength)
             {
                 break;
             }
         }
         _length = Math.Min(maxLength, length);
         if (_length < minLength)
         {
             return false;
         }
         SmoothTrack();
         return GetHistorySegmentPlacementState(0, _length) != TrackPlacementState.Invalid;
     }
References _history, _length, AppendToHistory(), CreateTunnel(), GetHistorySegmentPlacementState(), TrackGenerator.TrackHistory.Slope, SmoothTrack(), and TryRewriteHistoryToAvoidTiles().
Referenced by Place().