Terraria: System.Xml.XPath.XPathNavigator.MoveToPrevious
MoveToPrevious() [2/3]
bool System.Xml.XPath.XPathNavigator.MoveToPrevious (string localName, string namespaceURI) inline package inherited
Definition at line 1661 of file XPathNavigator.cs.
    {
        XPathNavigator other = Clone();
        string text = ((localName != null) ? NameTable.Get(localName) : null);
        while (MoveToPrevious())
        {
            if (NodeType == XPathNodeType.Element && text == LocalName && namespaceURI == NamespaceURI)
            {
                return true;
            }
        }
        MoveTo(other);
        return false;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.NameTable.Get(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigator.MoveToPrevious(), System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, System.other, and System.text.