Terraria: TrackGenerator.IsLocationInvalid
IsLocationInvalid()
static bool TrackGenerator.IsLocationInvalid (int x, int y) inline static private
     {
         if (y > Main.UnderworldLayer || x < 5 || y < (int)Main.worldSurface || x > Main.maxTilesX - 5)
         {
             return true;
         }
         if (Math.Abs((double)x - GenVars.shimmerPosition.X) < (double)(WorldGen.shimmerSafetyDistance / 2) && Math.Abs((double)y - GenVars.shimmerPosition.Y) < (double)(WorldGen.shimmerSafetyDistance / 2))
         {
             return true;
         }
         if (WorldGen.oceanDepths(x, y))
         {
             return true;
         }
         ushort wall = Main.tile[x, y].wall;
         for (int i = 0; i < InvalidWalls.Length; i++)
         {
             if (wall == InvalidWalls[i] && (!WorldGen.notTheBees || wall != 108))
             {
                 return true;
             }
         }
         ushort type = Main.tile[x, y].type;
         for (int j = 0; j < InvalidTiles.Length; j++)
         {
             if (type == InvalidTiles[j])
             {
                 return true;
             }
         }
         for (int k = -1; k <= 1; k++)
         {
             if (Main.tile[x + k, y].active() && (Main.tile[x + k, y].type == 314 || !TileID.Sets.GeneralPlacementTiles[Main.tile[x + k, y].type]) && (!WorldGen.notTheBees || Main.tile[x + k, y].type != 225))
             {
                 return true;
             }
         }
         return false;
     }
References Tile.active(), TileID.Sets.GeneralPlacementTiles, InvalidTiles, InvalidWalls, Main.maxTilesX, WorldGen.notTheBees, WorldGen.oceanDepths(), GenVars.shimmerPosition, WorldGen.shimmerSafetyDistance, Main.tile, Tile.type, Main.UnderworldLayer, Tile.wall, Main.worldSurface, Vector2D.X, and Vector2D.Y.
Referenced by CalculateStateForLocation().