Terraria: System.Xml.XPath.XPathNavigator.MoveToFirstChild
MoveToFirstChild()
bool System.Xml.XPath.XPathNavigator.MoveToFirstChild () abstract
Referenced by System.Xml.Xsl.XsltOld.NavigatorInput.NavigatorInput(), MS.Internal.Xml.XPath.CacheChildrenQuery.Advance(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode(), MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode(), System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.XPathChildIterator.MoveNext(), MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext(), System.Xml.Xsl.Runtime.ContentIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.XPath.XPathNavigator.MoveToFirst(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), System.Xml.XPath.XPathNavigatorReader.Read(), and System.Xml.Xsl.XsltOld.NavigatorInput.Recurse().