Terraria: System.Xml.XPath.XPathNavigator.Clone
Clone() [1/2]
object ICloneable. System.Xml.XPath.XPathNavigator.Clone () inline private inherited
Implements System.ICloneable.
Definition at line 705 of file XPathNavigator.cs.
    {
        return Clone();
    }
References System.Xml.XPath.XPathNavigator.Clone().
Referenced by System.Xml.DocumentXPathNodeIterator_Empty.DocumentXPathNodeIterator_Empty(), MS.Internal.Xml.XPath.XPathArrayIterator.XPathArrayIterator(), MS.Internal.Xml.XPath.XPathAxisIterator.XPathAxisIterator(), MS.Internal.Xml.XPath.XPathSelectionIterator.XPathSelectionIterator(), MS.Internal.Xml.XPath.XPathSelectionIterator.XPathSelectionIterator(), MS.Internal.Xml.XPath.XPathSingletonIterator.XPathSingletonIterator(), System.Xml.Xsl.Runtime.XmlQueryRuntime.AddNewIndex(), MS.Internal.Xml.XPath.AttributeQuery.Advance(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.Advance(), MS.Internal.Xml.XPath.FollowingQuery.Advance(), MS.Internal.Xml.XPath.FollSiblingQuery.Advance(), MS.Internal.Xml.XPath.NamespaceQuery.Advance(), MS.Internal.Xml.XPath.PrecedingQuery.Advance(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.ComparePosition(), System.Xml.Xsl.XsltOld.NewInstructionAction.Compile(), System.Xml.Xsl.Runtime.NamespaceIterator.Create(), System.Xml.Xsl.Runtime.PrecedingIterator.Create(), System.Xml.XPath.XPathNavigator.CreateNavigator(), System.Xml.Xsl.XsltOld.XsltCompileContext.Current(), System.Xml.XPath.XPathNavigator.Evaluate(), MS.Internal.Xml.XPath.AbsoluteQuery.Evaluate(), MS.Internal.Xml.XPath.ForwardPositionQuery.Evaluate(), MS.Internal.Xml.XPath.IDQuery.Evaluate(), MS.Internal.Xml.XPath.ParentQuery.Evaluate(), MS.Internal.Xml.XPath.PreSiblingQuery.Evaluate(), MS.Internal.Xml.XPath.XPathAncestorQuery.Evaluate(), System.Xml.Xsl.XsltOld.NumberAction.Execute(), System.Xml.Xsl.Runtime.XmlQueryRuntime.FindIndex(), System.Xml.Xsl.Runtime.DocumentOrderComparer.GetDocumentIndex(), System.Xml.XPath.XPathNavigatorReader.GetElemNav(), System.Xml.XPath.XPathNavigatorReader.GetElemNav(), System.Xml.XPath.XPathNavigator.GetNamespacesInScope(), MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput(), MS.Internal.Xml.XPath.Query.Insert(), System.Xml.Xsl.XsltOld.XsltCompileContext.FuncKey.Invoke(), System.Xml.XPath.XPathNavigator.IsDescendant(), System.Xml.XPath.XPathNavigator.LookupNamespace(), System.Xml.XPath.XPathNavigator.LookupPrefix(), MS.Internal.Xml.XPath.AttributeQuery.MatchNode(), MS.Internal.Xml.XPath.ChildrenQuery.MatchNode(), MS.Internal.Xml.XPath.DescendantBaseQuery.MatchNode(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.MergeFilterQuery.MatchNode(), MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), System.Xml.XPath.XPathNavigator.MoveToPrevious(), System.Xml.XPath.XPathNavigator.MoveToPrevious(), System.Xml.Xsl.XsltOld.ActionFrame.NewNextNode(), System.Xml.Xsl.XsltOld.ActionFrame.NextNode(), MS.Internal.Xml.XPath.PreSiblingQuery.NotVisited(), System.Xml.Xsl.XsltOld.NumberAction.numberCount(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.PushAncestors(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors(), System.Xml.XPath.XPathNavigator.SelectAncestors(), System.Xml.XPath.XPathNavigator.SelectAncestors(), System.Xml.XPath.XPathNavigator.SelectChildren(), System.Xml.XPath.XPathNavigator.SelectChildren(), System.Xml.XPath.XPathNavigator.SelectDescendants(), System.Xml.XPath.XPathNavigator.SelectDescendants(), System.Xml.Xsl.XsltOld.ActionFrame.SortNewNodeSet(), and MS.Internal.Xml.XPath.FollSiblingQuery.Visited().