Terraria: System.Xml.XPath.XPathNavigator.MoveToChild
MoveToChild() [1/2]
virtual bool System.Xml.XPath.XPathNavigator.MoveToChild (string localName, string namespaceURI) inline virtual inherited
Reimplemented in System.Xml.XPath.XNodeNavigator, MS.Internal.Xml.Cache.XPathDocumentNavigator, and System.Xml.DocumentXPathNavigator.
Definition at line 959 of file XPathNavigator.cs.
    {
        if (MoveToFirstChild())
        {
            do
            {
                if (NodeType == XPathNodeType.Element && localName == LocalName && namespaceURI == NamespaceURI)
                {
                    return true;
                }
            }
            while (MoveToNext());
            MoveToParent();
        }
        return false;
    }
References System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NamespaceURI, and System.Xml.XPath.XPathNavigator.NodeType.
Referenced by System.Xml.Xsl.Runtime.ElementContentIterator.MoveNext(), and System.Xml.Xsl.Runtime.NodeKindContentIterator.MoveNext().