Terraria: System.Xml.XPath.XPathNavigator.MoveToNonDescendant
MoveToNonDescendant()
bool System.Xml.XPath.XPathNavigator.MoveToNonDescendant () inline package inherited
Definition at line 1691 of file XPathNavigator.cs.
    {
        if (NodeType == XPathNodeType.Root)
        {
            return false;
        }
        if (MoveToNext())
        {
            return true;
        }
        XPathNavigator xPathNavigator = Clone();
        if (!MoveToParent())
        {
            return false;
        }
        XPathNodeType nodeType = xPathNavigator.NodeType;
        if ((uint)(nodeType - 2) <= 1u && MoveToFirstChild())
        {
            return true;
        }
        while (!MoveToNext())
        {
            if (!MoveToParent())
            {
                MoveTo(xPathNavigator);
                return false;
            }
        }
        return true;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToParent(), and System.Xml.XPath.XPathNavigator.NodeType.
Referenced by MS.Internal.Xml.Cache.XPathDocumentElementDescendantIterator.XPathDocumentElementDescendantIterator(), MS.Internal.Xml.Cache.XPathDocumentKindDescendantIterator.XPathDocumentKindDescendantIterator(), System.Xml.Xsl.Runtime.DescendantIterator.Create(), System.Xml.Xsl.Runtime.XPathFollowingIterator.MoveFirst(), System.Xml.Xsl.Runtime.DescendantMergeIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), and System.Xml.XPath.XPathNavigator.MoveToFollowing().