Terraria: System.Xml.XPath.XPathNavigator.MoveToNamespace
MoveToNamespace()
virtual bool System.Xml.XPath.XPathNavigator.MoveToNamespace (string name) inline virtual inherited
Reimplemented in System.Xml.XPath.XNodeNavigator, System.Xml.DataDocumentXPathNavigator, System.Xml.DocumentXPathNavigator, and System.Xml.XPath.XmlEmptyNavigator.
Definition at line 895 of file XPathNavigator.cs.
    {
        if (MoveToFirstNamespace(XPathNamespaceScope.All))
        {
            do
            {
                if (name == LocalName)
                {
                    return true;
                }
            }
            while (MoveToNextNamespace(XPathNamespaceScope.All));
            MoveToParent();
        }
        return false;
    }
References System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), System.Xml.XPath.XPathNavigator.MoveToNextNamespace(), and System.Xml.XPath.XPathNavigator.MoveToParent().
Referenced by System.Xml.XPath.XPathNavigator.GetNamespace(), and System.Xml.XPath.XPathNavigator.LookupNamespace().