Terraria: System.Xml.XPath.XPathNavigator.MoveToParent
MoveToParent()
bool System.Xml.XPath.XPathNavigator.MoveToParent () abstract
Referenced by MS.Internal.Xml.XPath.FollowingQuery.Advance(), MS.Internal.Xml.XPath.PrecedingQuery.Advance(), System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable(), System.Xml.Xsl.XsltOld.NumberAction.checkFrom(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode(), System.Xml.Xsl.Runtime.NamespaceIterator.Create(), System.Xml.Xsl.Runtime.ParentIterator.Create(), System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), MS.Internal.Xml.XPath.ParentQuery.Evaluate(), MS.Internal.Xml.XPath.XPathAncestorQuery.Evaluate(), System.Xml.Xsl.XsltOld.CopyAttributesAction.Execute(), System.Xml.Xsl.XsltOld.CopyNamespacesAction.Execute(), System.Xml.XPath.XPathNavigator.GetAttribute(), System.Xml.XPath.XPathNavigator.GetDepth(), System.Xml.XPath.XPathNavigator.GetNamespace(), System.Xml.XPath.XPathNavigator.GetNamespacesInScope(), System.Xml.XPath.XPathNavigator.IsDescendant(), System.Xml.XPath.XPathNavigator.LookupNamespace(), MS.Internal.Xml.XPath.AttributeQuery.MatchNode(), MS.Internal.Xml.XPath.ChildrenQuery.MatchNode(), MS.Internal.Xml.XPath.DescendantBaseQuery.MatchNode(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), System.Xml.Xsl.Runtime.XPathFollowingIterator.MoveFirst(), MS.Internal.Xml.XPath.XPathAncestorIterator.MoveNext(), MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext(), System.Xml.Xsl.Runtime.AncestorIterator.MoveNext(), System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToAttribute(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.Xsl.XsltOld.NumberAction.moveToCount(), System.Xml.XPath.XPathNavigatorReader.MoveToElement(), System.Xml.XPath.XPathNavigator.MoveToFirst(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNamespace(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), System.Xml.XPath.XPathNavigator.MoveToRoot(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.MoveUpUntilNext(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.PushAncestors(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.PushAncestors(), System.Xml.XPath.XPathNavigatorReader.Read(), and System.Xml.Xsl.XsltOld.NavigatorInput.ToParent().