Terraria: System.Xml.XPath.XPathNavigator.MoveToAttribute
MoveToAttribute()
virtual bool System.Xml.XPath.XPathNavigator.MoveToAttribute (string localName, string namespaceURI) inline virtual inherited
Reimplemented in System.Xml.XPath.XNodeNavigator, System.Xml.XPath.XmlEmptyNavigator, System.Xml.DataDocumentXPathNavigator, MS.Internal.Xml.Cache.XPathDocumentNavigator, and System.Xml.DocumentXPathNavigator.
Definition at line 855 of file XPathNavigator.cs.
    {
        if (MoveToFirstAttribute())
        {
            do
            {
                if (localName == LocalName && namespaceURI == NamespaceURI)
                {
                    return true;
                }
            }
            while (MoveToNextAttribute());
            MoveToParent();
        }
        return false;
    }
References System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveToFirstAttribute(), System.Xml.XPath.XPathNavigator.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToParent(), and System.Xml.XPath.XPathNavigator.NamespaceURI.
Referenced by System.Xml.XPath.XPathNavigator.GetAttribute().