Terraria: System.Xml.XPath.XPathNavigator.MoveToFirstAttribute
MoveToFirstAttribute()
bool System.Xml.XPath.XPathNavigator.MoveToFirstAttribute () abstract
Referenced by MS.Internal.Xml.XPath.AttributeQuery.Advance(), System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode(), System.Xml.Xsl.XsltOld.CopyAttributesAction.Execute(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), System.Xml.Xsl.Runtime.AttributeIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToAttribute(), and System.Xml.Xsl.XsltOld.NavigatorInput.MoveToFirstAttribute().