Terraria: System.Xml.XPath.XPathNavigator.MoveToNext
MoveToNext() [1/3]
bool System.Xml.XPath.XPathNavigator.MoveToNext () abstract
Referenced by MS.Internal.Xml.XPath.CacheChildrenQuery.Advance(), MS.Internal.Xml.XPath.FollowingQuery.Advance(), MS.Internal.Xml.XPath.FollSiblingQuery.Advance(), System.Xml.Xsl.XsltOld.NavigatorInput.Advance(), System.Xml.Xsl.Runtime.XmlMergeSequenceWriter.CopyNode(), System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), MS.Internal.Xml.XPath.FilterQuery.MatchNode(), MS.Internal.Xml.XPath.XPathChildIterator.MoveNext(), MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext(), System.Xml.Xsl.Runtime.ContentIterator.MoveNext(), System.Xml.Xsl.Runtime.ElementContentIterator.MoveNext(), System.Xml.Xsl.Runtime.NodeKindContentIterator.MoveNext(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), MS.Internal.Xml.XPath.DescendantOverDescendantQuery.MoveUpUntilNext(), and System.Xml.XPath.XPathNavigatorReader.Read().