Terraria: System.Xml.XPath.XPathNavigator.MoveToNext
MoveToNext() [3/3]
virtual bool System.Xml.XPath.XPathNavigator.MoveToNext (XPathNodeType type) inline virtual inherited
Reimplemented in System.Xml.XPath.XNodeNavigator, MS.Internal.Xml.Cache.XPathDocumentNavigator, and System.Xml.DocumentXPathNavigator.
Definition at line 1099 of file XPathNavigator.cs.
    {
        XPathNavigator other = Clone();
        int contentKindMask = GetContentKindMask(type);
        while (MoveToNext())
        {
            if (((1 << (int)NodeType) & contentKindMask) != 0)
            {
                return true;
            }
        }
        MoveTo(other);
        return false;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.GetContentKindMask(), System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.NodeType, System.other, and System.type.