Terraria: System.Xml.XPath.XPathNavigator.MoveToFollowing
MoveToFollowing() [2/4]
virtual bool System.Xml.XPath.XPathNavigator.MoveToFollowing (string localName, string namespaceURI, XPathNavigator? end) inline virtual inherited
Definition at line 999 of file XPathNavigator.cs.
    {
        XPathNavigator other = Clone();
        if (end != null)
        {
            XPathNodeType nodeType = end.NodeType;
            if ((uint)(nodeType - 2) <= 1u)
            {
                end = end.Clone();
                end.MoveToNonDescendant();
            }
        }
        XPathNodeType nodeType2 = NodeType;
        if ((uint)(nodeType2 - 2) <= 1u && !MoveToParent())
        {
            return false;
        }
        do
        {
            if (!MoveToFirstChild())
            {
                while (!MoveToNext())
                {
                    if (!MoveToParent())
                    {
                        MoveTo(other);
                        return false;
                    }
                }
            }
            if (end != null && IsSamePosition(end))
            {
                MoveTo(other);
                return false;
            }
        }
        while (NodeType != XPathNodeType.Element || localName != LocalName || namespaceURI != NamespaceURI);
        return true;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.IsSamePosition(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, and System.other.