Terraria: System.Xml.XPath.XPathNavigator.MoveToFirstNamespace
MoveToFirstNamespace() [1/2]
bool System.Xml.XPath.XPathNavigator.MoveToFirstNamespace () inline inherited
Definition at line 916 of file XPathNavigator.cs.
    {
        return MoveToFirstNamespace(XPathNamespaceScope.All);
    }
References System.Xml.XPath.XPathNavigator.MoveToFirstNamespace().
Referenced by System.Xml.XPath.XPathNavigator.GetNamespacesInScope(), System.Xml.XPath.XPathNavigator.MoveToFirstNamespace(), and System.Xml.XPath.XPathNavigator.MoveToNamespace().