Terraria: System.Xml.XPath.XPathNavigator.MoveToNext
MoveToNext() [2/3]
virtual bool System.Xml.XPath.XPathNavigator.MoveToNext (string localName, string namespaceURI) inline virtual inherited
Reimplemented in System.Xml.XPath.XNodeNavigator, MS.Internal.Xml.Cache.XPathDocumentNavigator, and System.Xml.DocumentXPathNavigator.
Definition at line 1085 of file XPathNavigator.cs.
    {
        XPathNavigator other = Clone();
        while (MoveToNext())
        {
            if (NodeType == XPathNodeType.Element && localName == LocalName && namespaceURI == NamespaceURI)
            {
                return true;
            }
        }
        MoveTo(other);
        return false;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.LocalName, System.Xml.XPath.XPathNavigator.MoveTo(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.NamespaceURI, System.Xml.XPath.XPathNavigator.NodeType, and System.other.