Terraria: System.Xml.XPath.XPathNavigator.LookupPrefix
LookupPrefix()
virtual ? string System.Xml.XPath.XPathNavigator.LookupPrefix (string namespaceURI) inline virtual inherited
Implements System.Xml.IXmlNamespaceResolver.
Definition at line 750 of file XPathNavigator.cs.
    {
        if (namespaceURI == null)
        {
            return null;
        }
        XPathNavigator xPathNavigator = Clone();
        if (NodeType != XPathNodeType.Element)
        {
            if (xPathNavigator.MoveToParent())
            {
                return xPathNavigator.LookupPrefix(namespaceURI);
            }
        }
        else if (xPathNavigator.MoveToFirstNamespace(XPathNamespaceScope.All))
        {
            do
            {
                if (namespaceURI == xPathNavigator.Value)
                {
                    return xPathNavigator.LocalName;
                }
            }
            while (xPathNavigator.MoveToNextNamespace(XPathNamespaceScope.All));
        }
        if (namespaceURI == LookupNamespace(string.Empty))
        {
            return string.Empty;
        }
        if (namespaceURI == "http://www.w3.org/XML/1998/namespace")
        {
            return "xml";
        }
        if (namespaceURI == "http://www.w3.org/2000/xmlns/")
        {
            return "xmlns";
        }
        return null;
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.LookupNamespace(), and System.Xml.XPath.XPathNavigator.NodeType.
Referenced by System.Xml.XPath.XPathNavigatorReader.LookupPrefix().