Terraria: System.Xml.XPath.XPathNavigator.SelectChildren
SelectChildren() [2/2]
virtual XPathNodeIterator System.Xml.XPath.XPathNavigator.SelectChildren (XPathNodeType type) inline virtual inherited
Reimplemented in MS.Internal.Xml.Cache.XPathDocumentNavigator.
Definition at line 1375 of file XPathNavigator.cs.
    {
        return new XPathChildIterator(Clone(), type);
    }
References System.Xml.XPath.XPathNavigator.Clone(), and System.type.
Referenced by MS.Internal.Xml.XPath.ChildrenQuery.Advance(), System.Xml.Xsl.XsltOld.ApplyTemplatesAction.Execute(), and System.Xml.Xsl.XsltOld.CopyNodeSetAction.Execute().