Terraria: System.Xml.XPath.XPathNavigator.ComparePosition
ComparePosition()
virtual XmlNodeOrder System.Xml.XPath.XPathNavigator.ComparePosition (XPathNavigator? nav) inline virtual inherited
Definition at line 1132 of file XPathNavigator.cs.
    {
        if (nav == null)
        {
            return XmlNodeOrder.Unknown;
        }
        if (IsSamePosition(nav))
        {
            return XmlNodeOrder.Same;
        }
        XPathNavigator xPathNavigator = Clone();
        XPathNavigator xPathNavigator2 = nav.Clone();
        int num = GetDepth(xPathNavigator.Clone());
        int num2 = GetDepth(xPathNavigator2.Clone());
        if (num > num2)
        {
            while (num > num2)
            {
                xPathNavigator.MoveToParent();
                num--;
            }
            if (xPathNavigator.IsSamePosition(xPathNavigator2))
            {
                return XmlNodeOrder.After;
            }
        }
        if (num2 > num)
        {
            while (num2 > num)
            {
                xPathNavigator2.MoveToParent();
                num2--;
            }
            if (xPathNavigator.IsSamePosition(xPathNavigator2))
            {
                return XmlNodeOrder.Before;
            }
        }
        XPathNavigator xPathNavigator3 = xPathNavigator.Clone();
        XPathNavigator xPathNavigator4 = xPathNavigator2.Clone();
        while (true)
        {
            if (!xPathNavigator3.MoveToParent() || !xPathNavigator4.MoveToParent())
            {
                return XmlNodeOrder.Unknown;
            }
            if (xPathNavigator3.IsSamePosition(xPathNavigator4))
            {
                break;
            }
            xPathNavigator.MoveToParent();
            xPathNavigator2.MoveToParent();
        }
        _ = xPathNavigator.GetType().ToString() != "Microsoft.VisualStudio.Modeling.StoreNavigator";
        return CompareSiblings(xPathNavigator, xPathNavigator2);
    }
References System.Xml.XPath.XPathNavigator.Clone(), System.Xml.XPath.XPathNavigator.CompareSiblings(), System.Xml.XPath.XPathNavigator.GetDepth(), and System.Xml.XPath.XPathNavigator.IsSamePosition().
Referenced by System.Xml.Xsl.Runtime.ContentMergeIterator.DocOrderMerge(), System.Xml.Xsl.Runtime.PrecedingSiblingDocOrderIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathFollowingMergeIterator.MoveNext(), and System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext().