Terraria: System.Xml.XPath.XPathNavigator.BuildSubtree
BuildSubtree()
void System.Xml.XPath.XPathNavigator.BuildSubtree (XmlReader reader, XmlWriter writer) inline package inherited
Definition at line 1899 of file XPathNavigator.cs.
    {
        string text = "http://www.w3.org/2000/xmlns/";
        ReadState readState = reader.ReadState;
        if (readState != 0 && readState != ReadState.Interactive)
        {
            throw new ArgumentException(System.SR.Xml_InvalidOperation, "reader");
        }
        int num = 0;
        if (readState == ReadState.Initial)
        {
            if (!reader.Read())
            {
                return;
            }
            num++;
        }
        do
        {
            switch (reader.NodeType)
            {
            case XmlNodeType.Element:
            {
                writer.WriteStartElement(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                bool isEmptyElement = reader.IsEmptyElement;
                while (reader.MoveToNextAttribute())
                {
                    if ((object)reader.NamespaceURI == text)
                    {
                        if (reader.Prefix.Length == 0)
{
                            writer.WriteAttributeString("", "xmlns", text, reader.Value);
                        }
                        else
{
                            writer.WriteAttributeString("xmlns", reader.LocalName, text, reader.Value);
                        }
                    }
                    else
                    {
                        writer.WriteStartAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                        writer.WriteString(reader.Value);
                        writer.WriteEndAttribute();
                    }
                }
                reader.MoveToElement();
                if (isEmptyElement)
                {
                    writer.WriteEndElement();
                }
                else
                {
                    num++;
                }
                break;
            }
            case XmlNodeType.EndElement:
                writer.WriteFullEndElement();
                num--;
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
                writer.WriteString(reader.Value);
                break;
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
                writer.WriteString(reader.Value);
                break;
            case XmlNodeType.Comment:
                writer.WriteComment(reader.Value);
                break;
            case XmlNodeType.ProcessingInstruction:
                writer.WriteProcessingInstruction(reader.LocalName, reader.Value);
                break;
            case XmlNodeType.EntityReference:
                reader.ResolveEntity();
                break;
            case XmlNodeType.Attribute:
                if ((object)reader.NamespaceURI == text)
                {
                    if (reader.Prefix.Length == 0)
                    {
                        writer.WriteAttributeString("", "xmlns", text, reader.Value);
                    }
                    else
                    {
                        writer.WriteAttributeString("xmlns", reader.LocalName, text, reader.Value);
                    }
                }
                else
                {
                    writer.WriteStartAttribute(reader.Prefix, reader.LocalName, reader.NamespaceURI);
                    writer.WriteString(reader.Value);
                    writer.WriteEndAttribute();
                }
                break;
            }
        }
        while (reader.Read() && num > 0);
    }
References System.Xml.ArgumentException, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.LocalName, System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.MoveToNextAttribute(), System.Xml.XmlReader.NamespaceURI, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Prefix, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadState, System.Xml.XmlReader.ResolveEntity(), System.text, System.Xml.XmlReader.Value, System.writer, and System.SR.Xml_InvalidOperation.
Referenced by System.Xml.XPath.XPathNavigator.AppendChild(), System.Xml.XPath.XPathNavigator.InsertAfter(), System.Xml.XPath.XPathNavigator.InsertBefore(), System.Xml.XPath.XPathNavigator.PrependChild(), and System.Xml.XPath.XPathNavigator.ReplaceSelf().