Terraria: System.Xml.XPath.XPathNavigator.MoveTo
MoveTo()
bool System.Xml.XPath.XPathNavigator.MoveTo (XPathNavigator other) abstract inherited
Referenced by MS.Internal.Xml.XPath.PrecedingQuery.Advance(), MS.Internal.Xml.XPath.XPathAncestorQuery.Evaluate(), MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext(), System.Xml.Xsl.Runtime.NodeRangeIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingDocOrderIterator.MoveNext(), System.Xml.Xsl.Runtime.XPathPrecedingMergeIterator.MoveNext(), System.Xml.XPath.XPathNavigatorReader.MoveToAttr(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigatorReader.MoveToNextAttribute(), System.Xml.XPath.XPathNavigator.MoveToNonDescendant(), System.Xml.XPath.XPathNavigator.MoveToPrevious(), and System.Xml.XPath.XPathNavigator.MoveToPrevious().