Terraria: System.Xml.XPath.XPathNavigator.GetContentKindMask
GetContentKindMask()
static int System.Xml.XPath.XPathNavigator.GetContentKindMask (XPathNodeType type) inline static package inherited
Definition at line 1818 of file XPathNavigator.cs.
    {
        return ContentKindMasks[(int)type];
    }
References System.Xml.XPath.XPathNavigator.ContentKindMasks, and System.type.
Referenced by System.Xml.Xsl.Runtime.XmlNavTypeFilter.XmlNavTypeFilter(), MS.Internal.Xml.Cache.XPathNodeHelper.GetContentChild(), MS.Internal.Xml.Cache.XPathNodeHelper.GetContentFollowing(), MS.Internal.Xml.Cache.XPathNodeHelper.GetContentSibling(), System.Xml.XPath.XPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToChild(), System.Xml.DocumentXPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToFollowing(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.DocumentXPathNavigator.MoveToNext(), and System.Xml.XPath.XPathNavigator.MoveToPrevious().