Terraria: System.Xml.Ucs4Decoder.Ucs4ToUTF16
Ucs4ToUTF16()
void System.Xml.Ucs4Decoder.Ucs4ToUTF16 (uint code, char[] chars, int charIndex) inline package inherited
Definition at line 112 of file Ucs4Decoder.cs.
    {
        chars[charIndex] = (char)(55296 + (ushort)((code >> 16) - 1) + (ushort)((code >> 10) & 0x3F));
        chars[charIndex + 1] = (char)(56320 + (ushort)(code & 0x3FF));
    }
References System.charIndex, System.chars, and System.Xml.Dictionary.
Referenced by System.Xml.Ucs4Decoder1234.GetFullChars(), System.Xml.Ucs4Decoder2143.GetFullChars(), System.Xml.Ucs4Decoder3412.GetFullChars(), and System.Xml.Ucs4Decoder4321.GetFullChars().