Terraria: System.Net.Security.SslStream.SslStream
SslStream() [5/5]
System.Net.Security.SslStream.SslStream (Stream innerStream, bool leaveInnerStreamOpen, RemoteCertificateValidationCallback? userCertificateValidationCallback, LocalCertificateSelectionCallback? userCertificateSelectionCallback, EncryptionPolicy encryptionPolicy) inline
Definition at line 343 of file SslStream.cs.
        : base(innerStream, leaveInnerStreamOpen)
    {
        if (encryptionPolicy != 0 && encryptionPolicy != EncryptionPolicy.AllowNoEncryption && encryptionPolicy != EncryptionPolicy.NoEncryption)
        {
            throw new ArgumentException(System.SR.Format(System.SR.net_invalid_enum, "EncryptionPolicy"), "encryptionPolicy");
        }
        _userCertificateValidationCallback = userCertificateValidationCallback;
        _userCertificateSelectionCallback = userCertificateSelectionCallback;
        _encryptionPolicy = encryptionPolicy;
        _certSelectionDelegate = ((userCertificateSelectionCallback == null) ? null : new LocalCertSelectionCallback(UserCertSelectionCallbackWrapper));
        _innerStream = innerStream;
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Log.SslStreamCtor(this, innerStream);
        }
    }
References System.Net.Security.SslStream._certSelectionDelegate, System.Net.Security.SslStream._encryptionPolicy, System.Net.Security.SslStream._innerStream, System.Net.Security.SslStream._userCertificateSelectionCallback, System.Net.Security.SslStream._userCertificateValidationCallback, System.SR.Format(), System.Net.Security.LocalCertSelectionCallback(), System.Net.NetEventSource.Log, System.SR.net_invalid_enum, and System.Net.Security.SslStream.UserCertSelectionCallbackWrapper().