Terraria: System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter >
RenegotiateAsync< TIOAdapter >()
async Task System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter > (TIOAdapter adapter) inline private
Type Constraints
TIOAdapter : IReadWriteAdapter
Definition at line 1051 of file SslStream.cs.
                                                                                         : IReadWriteAdapter
    {
        if (Interlocked.Exchange(ref _nestedAuth, 1) == 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_io_invalidnestedcall, "NegotiateClientCertificateAsync", "renegotiate"));
        }
        if (Interlocked.Exchange(ref _nestedRead, 1) == 1)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "ReadAsync", "read"));
        }
        if (Interlocked.Exchange(ref _nestedWrite, 1) == 1)
        {
            _nestedRead = 0;
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "WriteAsync", "write"));
        }
        try
        {
            if (_decryptedBytesCount != 0)
            {
                throw new InvalidOperationException(System.SR.net_ssl_renegotiate_buffer);
            }
            _sslAuthenticationOptions.RemoteCertRequired = true;
            _isRenego = true;
            byte[] output;
            SecurityStatusPal status = _context.Renegotiate(out output);
            if (output != null && output.Length != 0)
            {
                await adapter.WriteAsync(output, 0, output.Length).ConfigureAwait(continueOnCapturedContext: false);
                await adapter.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
            }
            if (status.ErrorCode != SecurityStatusPalErrorCode.OK)
            {
                if (status.ErrorCode != SecurityStatusPalErrorCode.NoRenegotiation)
                {
                    throw SslStreamPal.GetException(status);
                }
                return;
            }
            _handshakeBuffer = new ArrayBuffer(4160);
            ProtocolToken message;
            do
            {
                message = await ReceiveBlobAsync(adapter).ConfigureAwait(continueOnCapturedContext: false);
                if (message.Size > 0)
                {
                    await adapter.WriteAsync(message.Payload, 0, message.Size).ConfigureAwait(continueOnCapturedContext: false);
                    await adapter.FlushAsync().ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            while (message.Status.ErrorCode == SecurityStatusPalErrorCode.ContinueNeeded);
            if (_handshakeBuffer.ActiveLength > 0)
            {
                ResetReadBuffer();
                _handshakeBuffer.ActiveSpan.CopyTo(_internalBuffer);
                _internalBufferCount = _handshakeBuffer.ActiveLength;
            }
            CompleteHandshake(_sslAuthenticationOptions);
        }
        finally
        {
            _nestedRead = 0;
            _nestedWrite = 0;
            _isRenego = false;
        }
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._decryptedBytesCount, System.Net.Security.SslStream._handshakeBuffer, System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalBufferCount, System.Net.Security.SslStream._isRenego, System.Net.Security.SslStream._nestedAuth, System.Net.Security.SslStream._nestedRead, System.Net.Security.SslStream._nestedWrite, System.Net.Security.SslStream._sslAuthenticationOptions, System.Net.ArrayBuffer.ActiveLength, System.Net.ArrayBuffer.ActiveSpan, System.Net.Security.SslStream.CompleteHandshake(), System.Span< T >.CopyTo(), System.Net.SecurityStatusPal.ErrorCode, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.Net.Security.SslStreamPal.GetException(), System.SR.net_io_invalidnestedcall, System.SR.net_ssl_renegotiate_buffer, System.Net.Security.ProtocolToken.Payload, System.Net.Security.SecureChannel.Renegotiate(), System.Net.Security.SslStream.ResetReadBuffer(), System.Net.Security.ProtocolToken.Size, and System.Net.Security.ProtocolToken.Status.