Terraria: System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync
ProcessAuthenticationWithTelemetryAsync()
async Task System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync (bool isAsync, bool isApm, CancellationToken cancellationToken) inline private
Definition at line 1020 of file SslStream.cs.
    {
        NetSecurityTelemetry.Log.HandshakeStart(_context.IsServer, _sslAuthenticationOptions.TargetHost);
        ValueStopwatch stopwatch = ValueStopwatch.StartNew();
        try
        {
            Task task = (isAsync ? ForceAuthenticationAsync(new AsyncReadWriteAdapter(base.InnerStream, cancellationToken), _context.IsServer, null, isApm) : ForceAuthenticationAsync(new SyncReadWriteAdapter(base.InnerStream), _context.IsServer, null));
            await task.ConfigureAwait(continueOnCapturedContext: false);
            bool connectionOpen = Interlocked.CompareExchange(ref _connectionOpenedStatus, 1, 0) == 0;
            NetSecurityTelemetry.Log.HandshakeCompleted(GetSslProtocolInternal(), stopwatch, connectionOpen);
        }
        catch (Exception ex)
        {
            NetSecurityTelemetry.Log.HandshakeFailed(_context.IsServer, stopwatch, ex.Message);
            throw;
        }
    }
References System.Net.Security.SslStream._connectionOpenedStatus, System.Net.Security.SslStream._context, System.Net.Security.SslStream._sslAuthenticationOptions, System.cancellationToken, System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Net.Security.SslStream.GetSslProtocolInternal(), System.Net.Security.SecureChannel.IsServer, System.Net.Security.NetSecurityTelemetry.Log, System.Exception.Message, Microsoft.Extensions.Internal.ValueStopwatch.StartNew(), System.Net.Security.SslAuthenticationOptions.TargetHost, and System.task.
Referenced by System.Net.Security.SslStream.ProcessAuthenticationAsync().