Terraria: System.Net.Security.SslStream.CloseInternal
CloseInternal()
void System.Net.Security.SslStream.CloseInternal () inline private
Definition at line 967 of file SslStream.cs.
    {
        _exception = s_disposedSentinel;
        _context?.Close();
        if (Interlocked.CompareExchange(ref _nestedRead, 1, 0) == 0)
        {
            byte[] internalBuffer = _internalBuffer;
            if (internalBuffer != null)
            {
                _internalBuffer = null;
                _internalBufferCount = 0;
                _internalOffset = 0;
                ArrayPool<byte>.Shared.Return(internalBuffer);
            }
        }
        if (_internalBuffer == null)
        {
            GC.SuppressFinalize(this);
        }
        if (NetSecurityTelemetry.Log.IsEnabled() && Interlocked.Exchange(ref _connectionOpenedStatus, 2) == 1)
        {
            NetSecurityTelemetry.Log.ConnectionClosed(GetSslProtocolInternal());
        }
    }
References System.Net.Security.SslStream._connectionOpenedStatus, System.Net.Security.SslStream._context, System.Net.Security.SslStream._exception, System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalBufferCount, System.Net.Security.SslStream._internalOffset, System.Net.Security.SslStream._nestedRead, System.Net.Security.SecureChannel.Close(), System.Threading.Interlocked.CompareExchange(), System.Threading.Interlocked.Exchange(), System.Net.Security.SslStream.GetSslProtocolInternal(), System.Net.Security.NetSecurityTelemetry.Log, System.Net.Security.SslStream.s_disposedSentinel, System.Buffers.ArrayPool< T >.Shared, and System.GC.SuppressFinalize().
Referenced by System.Net.Security.SslStream.Dispose(), and System.Net.Security.SslStream.DisposeAsync().