Terraria: System.Net.Security.SslStream.CompleteHandshake
CompleteHandshake() [2/2]
void System.Net.Security.SslStream.CompleteHandshake (SslAuthenticationOptions sslAuthenticationOptions) inline private
Definition at line 1353 of file SslStream.cs.
    {
        ProtocolToken alertToken = null;
        if (!CompleteHandshake(ref alertToken, out var sslPolicyErrors, out var chainStatus))
        {
            if (sslAuthenticationOptions.CertValidationDelegate != null)
            {
                SendAuthResetSignal(alertToken, ExceptionDispatchInfo.Capture(new AuthenticationException(System.SR.net_ssl_io_cert_custom_validation, null)));
            }
            else if (sslPolicyErrors == SslPolicyErrors.RemoteCertificateChainErrors && chainStatus != 0)
            {
                SendAuthResetSignal(alertToken, ExceptionDispatchInfo.Capture(new AuthenticationException(System.SR.Format(System.SR.net_ssl_io_cert_chain_validation, chainStatus), null)));
            }
            else
            {
                SendAuthResetSignal(alertToken, ExceptionDispatchInfo.Capture(new AuthenticationException(System.SR.Format(System.SR.net_ssl_io_cert_validation, sslPolicyErrors), null)));
            }
        }
    }
References System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Net.Security.SslAuthenticationOptions.CertValidationDelegate, System.Net.Security.SslStream.CompleteHandshake(), System.SR.Format(), System.SR.net_ssl_io_cert_chain_validation, System.SR.net_ssl_io_cert_custom_validation, System.SR.net_ssl_io_cert_validation, and System.Net.Security.SslStream.SendAuthResetSignal().