Terraria: System.Net.Security.SslStream.CreateAuthenticationOptions
CreateAuthenticationOptions()
SslAuthenticationOptions System.Net.Security.SslStream.CreateAuthenticationOptions (SslServerAuthenticationOptions sslServerAuthenticationOptions) inline private
Definition at line 396 of file SslStream.cs.
    {
        if (sslServerAuthenticationOptions.ServerCertificate == null && sslServerAuthenticationOptions.ServerCertificateContext == null && sslServerAuthenticationOptions.ServerCertificateSelectionCallback == null && _certSelectionDelegate == null)
        {
            throw new ArgumentNullException("ServerCertificate");
        }
        if ((sslServerAuthenticationOptions.ServerCertificate != null || sslServerAuthenticationOptions.ServerCertificateContext != null || _certSelectionDelegate != null) && sslServerAuthenticationOptions.ServerCertificateSelectionCallback != null)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_conflicting_options, "ServerCertificateSelectionCallback"));
        }
        SslAuthenticationOptions sslAuthenticationOptions = new SslAuthenticationOptions(sslServerAuthenticationOptions);
        _userServerCertificateSelectionCallback = sslServerAuthenticationOptions.ServerCertificateSelectionCallback;
        sslAuthenticationOptions.ServerCertSelectionDelegate = ((_userServerCertificateSelectionCallback == null) ? null : new ServerCertSelectionCallback(ServerCertSelectionCallbackWrapper));
        sslAuthenticationOptions.CertValidationDelegate = _userCertificateValidationCallback;
        sslAuthenticationOptions.CertSelectionDelegate = _certSelectionDelegate;
        return sslAuthenticationOptions;
    }
References System.Net.Security.SslStream._certSelectionDelegate, System.Net.Security.SslStream._userCertificateValidationCallback, System.Net.Security.SslStream._userServerCertificateSelectionCallback, System.SR.Format(), System.SR.net_conflicting_options, System.Net.Security.SslServerAuthenticationOptions.ServerCertificate, System.Net.Security.SslServerAuthenticationOptions.ServerCertificateContext, System.Net.Security.SslServerAuthenticationOptions.ServerCertificateSelectionCallback, System.Net.Security.ServerCertSelectionCallback(), and System.Net.Security.SslStream.ServerCertSelectionCallbackWrapper().
Referenced by System.Net.Security.SslStream.AuthenticateAsServer(), System.Net.Security.SslStream.AuthenticateAsServerApm(), and System.Net.Security.SslStream.AuthenticateAsServerAsync().