Terraria: System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated
ThrowIfExceptionalOrNotAuthenticated()
void System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated () inline private
Definition at line 866 of file SslStream.cs.
    {
        ThrowIfExceptional();
        if (!IsAuthenticated)
        {
            ThrowNotAuthenticated();
        }
    }
References System.Net.Security.SslStream.IsAuthenticated, System.Net.Security.SslStream.ThrowIfExceptional(), and System.Net.Security.SslStream.ThrowNotAuthenticated().
Referenced by System.Net.Security.SslStream.BeginRead(), System.Net.Security.SslStream.BeginWrite(), System.Net.Security.SslStream.DecryptData(), System.Net.Security.SslStream.EncryptData(), System.Net.Security.SslStream.EndRead(), System.Net.Security.SslStream.EndWrite(), System.Net.Security.SslStream.NegotiateClientCertificateAsync(), System.Net.Security.SslStream.Read(), System.Net.Security.SslStream.ReadAsync(), System.Net.Security.SslStream.ReadAsync(), System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >(), System.Net.Security.SslStream.ReadByte(), System.Net.Security.SslStream.Write(), System.Net.Security.SslStream.WriteAsync(), and System.Net.Security.SslStream.WriteAsync().