Terraria: System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >
WriteSingleChunk< TIOAdapter >()
ValueTask System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter > (TIOAdapter writeAdapter, ReadOnlyMemory< byte > buffer) inline private
Type Constraints
TIOAdapter : struct
TIOAdapter : IReadWriteAdapter
Definition at line 1384 of file SslStream.cs.
                                                                                                                          : struct, IReadWriteAdapter
    {
        byte[] array = ArrayPool<byte>.Shared.Rent(buffer.Length + 64);
        byte[] outBuffer = array;
        SecurityStatusPal status;
        int outSize;
        while (true)
        {
            status = EncryptData(buffer, ref outBuffer, out outSize);
            if (status.ErrorCode != SecurityStatusPalErrorCode.TryAgain)
            {
                break;
            }
            TaskCompletionSource<bool> handshakeWaiter = _handshakeWaiter;
            if (handshakeWaiter != null)
            {
                Task task = writeAdapter.WaitAsync(handshakeWaiter);
                if (!task.IsCompletedSuccessfully)
                {
                    return WaitAndWriteAsync(writeAdapter, buffer, task, array);
                }
            }
        }
        if (status.ErrorCode != SecurityStatusPalErrorCode.OK)
        {
            ArrayPool<byte>.Shared.Return(array);
            return ValueTask.FromException(ExceptionDispatchInfo.SetCurrentStackTrace(new IOException(System.SR.net_io_encrypt, SslStreamPal.GetException(status))));
        }
        ValueTask valueTask = writeAdapter.WriteAsync(outBuffer, 0, outSize);
        if (valueTask.IsCompletedSuccessfully)
        {
            ArrayPool<byte>.Shared.Return(array);
            return valueTask;
        }
        return CompleteWriteAsync(valueTask, array);
        static async ValueTask CompleteWriteAsync(ValueTask writeTask, byte[] bufferToReturn)
        {
            try
            {
                await writeTask.ConfigureAwait(continueOnCapturedContext: false);
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(bufferToReturn);
            }
        }
        async ValueTask WaitAndWriteAsync(TIOAdapter writeAdapter, ReadOnlyMemory<byte> buffer, Task waitTask, byte[] rentedBuffer)
        {
            byte[] bufferToReturn2 = rentedBuffer;
            byte[] outBuffer2 = rentedBuffer;
            try
            {
                await waitTask.ConfigureAwait(continueOnCapturedContext: false);
                int outSize2;
                SecurityStatusPal status2 = EncryptData(buffer, ref outBuffer2, out outSize2);
                if (status2.ErrorCode == SecurityStatusPalErrorCode.TryAgain)
                {
                    byte[] array2 = bufferToReturn2;
                    bufferToReturn2 = null;
                    ArrayPool<byte>.Shared.Return(array2);
                    await WriteSingleChunk(writeAdapter, buffer).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    if (status2.ErrorCode != SecurityStatusPalErrorCode.OK)
                    {
                        throw new IOException(System.SR.net_io_encrypt, SslStreamPal.GetException(status2));
                    }
                    await writeAdapter.WriteAsync(outBuffer2, 0, outSize2).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            finally
            {
                if (bufferToReturn2 != null)
                {
                    ArrayPool<byte>.Shared.Return(bufferToReturn2);
                }
            }
        }
    }
References System.Net.Security.SslStream._handshakeWaiter, System.array, System.buffer, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.Security.SslStream.EncryptData(), System.Net.SecurityStatusPal.ErrorCode, System.Threading.Tasks.ValueTask< TResult >.FromException(), System.Net.Security.SslStreamPal.GetException(), System.Threading.Tasks.ValueTask< TResult >.IsCompletedSuccessfully, System.SR.net_io_encrypt, System.Runtime.ExceptionServices.ExceptionDispatchInfo.SetCurrentStackTrace(), System.Buffers.ArrayPool< T >.Shared, System.task, and System.Threading.Tasks.Task< TResult >.WaitAsync().