Terraria: System.Net.Security.SslStream.CompleteHandshake
CompleteHandshake() [1/2]
bool System.Net.Security.SslStream.CompleteHandshake (ref ProtocolToken alertToken, out SslPolicyErrors sslPolicyErrors, out X509ChainStatusFlags chainStatus) inline private
Definition at line 1331 of file SslStream.cs.
    {
        _context.ProcessHandshakeSuccess();
        if (_nestedAuth != 1)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"Ignoring unsolicited renegotiated certificate.", "CompleteHandshake");
            }
            sslPolicyErrors = SslPolicyErrors.None;
            chainStatus = X509ChainStatusFlags.NoError;
            return true;
        }
        if (!_context.VerifyRemoteCertificate(_sslAuthenticationOptions.CertValidationDelegate, _sslAuthenticationOptions.CertificateContext?.Trust, ref alertToken, out sslPolicyErrors, out chainStatus))
        {
            _handshakeCompleted = false;
            return false;
        }
        _handshakeCompleted = true;
        return true;
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._handshakeCompleted, System.Net.Security.SslStream._nestedAuth, System.Net.Security.SslStream._sslAuthenticationOptions, System.Net.Security.SslAuthenticationOptions.CertificateContext, System.Net.Security.SslAuthenticationOptions.CertValidationDelegate, System.Net.NetEventSource.Error(), System.Net.NetEventSource.Log, System.Net.Security.SecureChannel.ProcessHandshakeSuccess(), System.Net.Security.SslStreamCertificateContext.Trust, and System.Net.Security.SecureChannel.VerifyRemoteCertificate().
Referenced by System.Net.Security.SslStream.CompleteHandshake(), System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), and System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter >().