Terraria: System.Net.Security.SslStream.Read
Read() [1/2]
override int System.Net.Security.SslStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 779 of file SslStream.cs.
    {
        ThrowIfExceptionalOrNotAuthenticated();
        Stream.ValidateBufferArguments(buffer, offset, count);
        return ReadAsyncInternal(new SyncReadWriteAdapter(base.InnerStream), new Memory<byte>(buffer, offset, count)).GetAwaiter().GetResult();
    }
References System.buffer, System.count, System.offset, System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated(), and System.IO.Stream.ValidateBufferArguments().
Referenced by System.Net.TlsStream.Read().