Terraria: System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >
ReceiveBlobAsync< TIOAdapter >()
async ValueTask< ProtocolToken > System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter > (TIOAdapter adapter) inline private
Type Constraints
TIOAdapter : IReadWriteAdapter
Definition at line 1215 of file SslStream.cs.
                                                                                                             : IReadWriteAdapter
    {
        if (await FillHandshakeBufferAsync(adapter, 5).ConfigureAwait(continueOnCapturedContext: false) == 0)
        {
            throw new IOException(System.SR.net_io_eof);
        }
        if (_framing == Framing.Unified || _framing == Framing.Unknown)
        {
            _framing = DetectFraming(_handshakeBuffer.ActiveReadOnlySpan);
        }
        if (_framing != Framing.SinceSSL3)
        {
            _lastFrame.Header.Version = SslProtocols.Ssl2;
            _lastFrame.Header.Length = GetFrameSize(_handshakeBuffer.ActiveReadOnlySpan) - 5;
        }
        else
        {
            TlsFrameHelper.TryGetFrameHeader(_handshakeBuffer.ActiveReadOnlySpan, ref _lastFrame.Header);
        }
        if (_lastFrame.Header.Length < 0)
        {
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, "invalid TLS frame size", "ReceiveBlobAsync");
            }
            throw new IOException(System.SR.net_frame_read_size);
        }
        int frameSize = _lastFrame.Header.Length + 5;
        if (_handshakeBuffer.ActiveLength < frameSize)
        {
            await FillHandshakeBufferAsync(adapter, frameSize).ConfigureAwait(continueOnCapturedContext: false);
        }
        switch (_lastFrame.Header.Type)
        {
        case TlsContentType.Alert:
            if (TlsFrameHelper.TryGetFrameInfo(_handshakeBuffer.ActiveReadOnlySpan, ref _lastFrame) && System.Net.NetEventSource.Log.IsEnabled() && _lastFrame.AlertDescription != 0)
            {
                System.Net.NetEventSource.Error(this, $"Received TLS alert {_lastFrame.AlertDescription}", "ReceiveBlobAsync");
            }
            break;
        case TlsContentType.Handshake:
        {
            if (_isRenego || _handshakeBuffer.ActiveReadOnlySpan[5] != 1 || (_sslAuthenticationOptions.ServerCertSelectionDelegate == null && _sslAuthenticationOptions.ServerOptionDelegate == null))
            {
                break;
            }
            TlsFrameHelper.ProcessingOptions options = ((!System.Net.NetEventSource.Log.IsEnabled()) ? TlsFrameHelper.ProcessingOptions.ServerName : TlsFrameHelper.ProcessingOptions.All);
            if (!TlsFrameHelper.TryGetFrameInfo(_handshakeBuffer.ActiveReadOnlySpan, ref _lastFrame, options) && System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Error(this, $"Failed to parse TLS hello.", "ReceiveBlobAsync");
            }
            if (_lastFrame.HandshakeType == TlsHandshakeType.ClientHello)
            {
                if (_lastFrame.TargetName != null)
                {
                    _sslAuthenticationOptions.TargetHost = _lastFrame.TargetName;
                }
                if (_sslAuthenticationOptions.ServerOptionDelegate != null)
                {
                    SslServerAuthenticationOptions sslServerAuthenticationOptions = await _sslAuthenticationOptions.ServerOptionDelegate(this, new SslClientHelloInfo(_sslAuthenticationOptions.TargetHost, _lastFrame.SupportedVersions), _sslAuthenticationOptions.UserState, adapter.CancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                    _sslAuthenticationOptions.UpdateOptions(sslServerAuthenticationOptions);
                }
            }
            if (System.Net.NetEventSource.Log.IsEnabled())
            {
                System.Net.NetEventSource.Log.ReceivedFrame(this, _lastFrame);
            }
            break;
        }
        case TlsContentType.AppData:
            if (_isRenego && SslProtocol != SslProtocols.Tls13)
            {
                throw new InvalidOperationException(System.SR.net_ssl_renegotiate_data);
            }
            break;
        }
        return ProcessBlob(frameSize);
    }
References System.Net.Security.SslStream._framing, System.Net.Security.SslStream._handshakeBuffer, System.Net.Security.SslStream._isRenego, System.Net.Security.SslStream._lastFrame, System.Net.Security.SslStream._sslAuthenticationOptions, System.Net.ArrayBuffer.ActiveLength, System.Net.ArrayBuffer.ActiveReadOnlySpan, System.Net.Security.SslStream.DetectFraming(), System.Net.NetEventSource.Error(), System.Net.Security.SslStream.GetFrameSize(), System.Net.NetEventSource.Log, System.SR.net_frame_read_size, System.SR.net_io_eof, System.SR.net_ssl_renegotiate_data, System.options, System.Net.Security.SslStream.ProcessBlob(), System.Net.Security.SslAuthenticationOptions.ServerCertSelectionDelegate, System.Net.Security.SslAuthenticationOptions.ServerOptionDelegate, System.Net.Security.SslStream.SslProtocol, System.Net.Security.SslAuthenticationOptions.TargetHost, System.Net.Security.TlsFrameHelper.TryGetFrameHeader(), System.Net.Security.TlsFrameHelper.TryGetFrameInfo(), System.Net.Security.SslAuthenticationOptions.UpdateOptions(), and System.Net.Security.SslAuthenticationOptions.UserState.