Terraria: System.Net.Security.SslStream.HaveFullTlsFrame
HaveFullTlsFrame()
bool System.Net.Security.SslStream.HaveFullTlsFrame (out int frameSize) inline private
Definition at line 1486 of file SslStream.cs.
    {
        if (_internalBufferCount < 5)
        {
            frameSize = int.MaxValue;
            return false;
        }
        frameSize = GetFrameSize(_internalBuffer.AsSpan(_internalOffset));
        return _internalBufferCount >= frameSize;
    }
References System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalBufferCount, System.Net.Security.SslStream._internalOffset, and System.Net.Security.SslStream.GetFrameSize().
Referenced by System.Net.Security.SslStream.EnsureFullTlsFrameAsync< TIOAdapter >(), and System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >().