Terraria: System.Net.Security.SslStream.ThrowIfExceptional
ThrowIfExceptional()
void System.Net.Security.SslStream.ThrowIfExceptional () inline private
Definition at line 848 of file SslStream.cs.
    {
        ExceptionDispatchInfo exception = _exception;
        if (exception != null)
        {
            ThrowExceptional(exception);
        }
        static void ThrowExceptional(ExceptionDispatchInfo e)
        {
            if (e == s_disposedSentinel)
            {
                throw new ObjectDisposedException("SslStream");
            }
            e.Throw();
        }
    }
References System.Net.Security.SslStream._exception, System.exception, System.Net.Security.SslStream.s_disposedSentinel, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.Net.Security.SslStream.ProcessAuthenticationAsync(), System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated(), System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticatedOrShutdown(), System.Net.Security.SslStream.ThrowIfExceptionalOrNotHandshake(), System.Net.Security.SslStream.ValidateCreateContext(), and System.Net.Security.SslStream.ValidateCreateContext().