Terraria: System.Net.Security.SslStream.ProcessAuthenticationAsync
ProcessAuthenticationAsync()
Task System.Net.Security.SslStream.ProcessAuthenticationAsync (bool isAsync = false, bool isApm = false, CancellationToken cancellationToken = default(CancellationToken)) inline private
Definition at line 1006 of file SslStream.cs.
    {
        ThrowIfExceptional();
        if (NetSecurityTelemetry.Log.IsEnabled())
        {
            return ProcessAuthenticationWithTelemetryAsync(isAsync, isApm, cancellationToken);
        }
        if (!isAsync)
        {
            return ForceAuthenticationAsync(new SyncReadWriteAdapter(base.InnerStream), _context.IsServer, null);
        }
        return ForceAuthenticationAsync(new AsyncReadWriteAdapter(base.InnerStream, cancellationToken), _context.IsServer, null, isApm);
    }
References System.Net.Security.SslStream._context, System.cancellationToken, System.Net.Security.SecureChannel.IsServer, System.Net.Security.NetSecurityTelemetry.Log, System.Net.Security.SslStream.ProcessAuthenticationWithTelemetryAsync(), and System.Net.Security.SslStream.ThrowIfExceptional().
Referenced by System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsClientApm(), System.Net.Security.SslStream.AuthenticateAsClientAsync(), System.Net.Security.SslStream.AuthenticateAsServer(), System.Net.Security.SslStream.AuthenticateAsServerApm(), System.Net.Security.SslStream.AuthenticateAsServerAsync(), and System.Net.Security.SslStream.AuthenticateAsServerAsync().