Terraria: System.Net.Security.SslStream.DecryptData
DecryptData()
SecurityStatusPal System.Net.Security.SslStream.DecryptData (int frameSize) inline private
Definition at line 1524 of file SslStream.cs.
    {
        _decryptedBytesOffset = _internalOffset;
        _decryptedBytesCount = frameSize;
        SecurityStatusPal result;
        lock (_handshakeLock)
        {
            ThrowIfExceptionalOrNotAuthenticated();
            result = _context.Decrypt(new Span<byte>(_internalBuffer, _internalOffset, frameSize), out var outputOffset, out var outputCount);
            _decryptedBytesCount = outputCount;
            if (outputCount > 0)
            {
                _decryptedBytesOffset = _internalOffset + outputOffset;
            }
            if (result.ErrorCode == SecurityStatusPalErrorCode.Renegotiate && (_sslAuthenticationOptions.AllowRenegotiation || SslProtocol == SslProtocols.Tls13 || _nestedAuth != 0))
            {
                _handshakeWaiter = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);
            }
        }
        ConsumeBufferedBytes(frameSize);
        return result;
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._decryptedBytesCount, System.Net.Security.SslStream._decryptedBytesOffset, System.Net.Security.SslStream._handshakeLock, System.Net.Security.SslStream._handshakeWaiter, System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalOffset, System.Net.Security.SslStream._nestedAuth, System.Net.Security.SslStream._sslAuthenticationOptions, System.Net.Security.SslAuthenticationOptions.AllowRenegotiation, System.Net.Security.SslStream.ConsumeBufferedBytes(), System.Net.Security.SecureChannel.Decrypt(), System.Net.SecurityStatusPal.ErrorCode, System.Net.Security.SslStream.SslProtocol, and System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated().
Referenced by System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >().