Terraria: System.Net.Security.SslStream.EnsureFullTlsFrameAsync< TIOAdapter >
EnsureFullTlsFrameAsync< TIOAdapter >()
async ValueTask< int > System.Net.Security.SslStream.EnsureFullTlsFrameAsync< TIOAdapter > (TIOAdapter adapter) inline private
Type Constraints
TIOAdapter : IReadWriteAdapter
Definition at line 1497 of file SslStream.cs.
                                                                                                          : IReadWriteAdapter
    {
        if (HaveFullTlsFrame(out var frameSize))
        {
            return frameSize;
        }
        ResetReadBuffer();
        while (_internalBufferCount < frameSize)
        {
            int num = await adapter.ReadAsync(_internalBuffer.AsMemory(_internalBufferCount)).ConfigureAwait(continueOnCapturedContext: false);
            if (num == 0)
            {
                if (_internalBufferCount != 0)
                {
                    throw new IOException(System.SR.net_io_eof);
                }
                return 0;
            }
            _internalBufferCount += num;
            if (frameSize == int.MaxValue && _internalBufferCount > 5)
            {
                frameSize = GetFrameSize(_internalBuffer.AsSpan(_internalOffset));
            }
        }
        return frameSize;
    }
References System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalBufferCount, System.Net.Security.SslStream._internalOffset, System.Net.Security.SslStream.GetFrameSize(), System.Net.Security.SslStream.HaveFullTlsFrame(), System.SR.net_io_eof, and System.Net.Security.SslStream.ResetReadBuffer().