Terraria: System.Net.Security.SslStream.ProcessBlob
ProcessBlob()
ProtocolToken System.Net.Security.SslStream.ProcessBlob (int frameSize) inline private
Definition at line 1294 of file SslStream.cs.
    {
        int num = frameSize;
        ReadOnlySpan<byte> activeReadOnlySpan = _handshakeBuffer.ActiveReadOnlySpan;
        _handshakeBuffer.Discard(frameSize);
        if (_framing == Framing.SinceSSL3)
        {
            while (_handshakeBuffer.ActiveLength > 5)
            {
                TlsFrameHeader header = default(TlsFrameHeader);
                if (!TlsFrameHelper.TryGetFrameHeader(_handshakeBuffer.ActiveReadOnlySpan, ref header))
                {
                    break;
                }
                frameSize = header.Length + 5;
                if ((header.Type != TlsContentType.Handshake && header.Type != TlsContentType.ChangeCipherSpec) || frameSize > _handshakeBuffer.ActiveLength)
                {
                    break;
                }
                num += frameSize;
                _handshakeBuffer.Discard(frameSize);
            }
        }
        return _context.NextMessage(activeReadOnlySpan.Slice(0, num));
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._framing, System.Net.Security.SslStream._handshakeBuffer, System.Net.ArrayBuffer.ActiveLength, System.Net.ArrayBuffer.ActiveReadOnlySpan, System.Net.ArrayBuffer.Discard(), System.Net.Security.SecureChannel.NextMessage(), System.ReadOnlySpan< T >.Slice(), System.Net.Security.TlsFrameHelper.TryGetFrameHeader(), and System.Net.Security.TlsFrameHeader.Type.
Referenced by System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >().