Terraria: System.Net.Security.SslStream.GetFrameSize
GetFrameSize()
int System.Net.Security.SslStream.GetFrameSize (ReadOnlySpan< byte > buffer) inline private
Definition at line 1817 of file SslStream.cs.
    {
        int num = -1;
        switch (_framing)
        {
        case Framing.BeforeSSL3:
        case Framing.Unified:
            if (buffer.Length < 2)
            {
                throw new IOException(System.SR.net_ssl_io_frame);
            }
            if ((buffer[0] & 0x80u) != 0)
            {
                return (((buffer[0] & 0x7F) << 8) | buffer[1]) + 2;
            }
            return (((buffer[0] & 0x3F) << 8) | buffer[1]) + 3;
        case Framing.SinceSSL3:
            if (buffer.Length < 5)
            {
                throw new IOException(System.SR.net_ssl_io_frame);
            }
            return ((buffer[3] << 8) | buffer[4]) + 5;
        default:
            throw new IOException(System.SR.net_frame_read_size);
        }
    }
References System.Net.Security.SslStream._framing, System.buffer, System.SR.net_frame_read_size, and System.SR.net_ssl_io_frame.
Referenced by System.Net.Security.SslStream.EnsureFullTlsFrameAsync< TIOAdapter >(), System.Net.Security.SslStream.HaveFullTlsFrame(), and System.Net.Security.SslStream.ReceiveBlobAsync< TIOAdapter >().