Terraria: System.Net.Security.SslStream.EncryptData
EncryptData()
SecurityStatusPal System.Net.Security.SslStream.EncryptData (ReadOnlyMemory< byte > buffer, ref byte[] outBuffer, out int outSize) inline private
Definition at line 992 of file SslStream.cs.
    {
        ThrowIfExceptionalOrNotAuthenticated();
        lock (_handshakeLock)
        {
            if (_handshakeWaiter != null)
            {
                outSize = 0;
                return new SecurityStatusPal(SecurityStatusPalErrorCode.TryAgain);
            }
            return _context.Encrypt(buffer, ref outBuffer, out outSize);
        }
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._handshakeLock, System.Net.Security.SslStream._handshakeWaiter, System.buffer, System.Net.Security.SecureChannel.Encrypt(), and System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated().
Referenced by System.Net.Security.SslStream.WriteSingleChunk< TIOAdapter >().