Terraria: System.Net.Security.SslStream.SetAndVerifySelectionCallback
SetAndVerifySelectionCallback()
void System.Net.Security.SslStream.SetAndVerifySelectionCallback (LocalCertificateSelectionCallback callback) inline private
Definition at line 373 of file SslStream.cs.
    {
        if (_userCertificateSelectionCallback == null)
        {
            _userCertificateSelectionCallback = callback;
            _certSelectionDelegate = ((_userCertificateSelectionCallback == null) ? null : new LocalCertSelectionCallback(UserCertSelectionCallbackWrapper));
        }
        else if (callback != null && _userCertificateSelectionCallback != callback)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_conflicting_options, "LocalCertificateSelectionCallback"));
        }
    }
References System.Net.Security.SslStream._certSelectionDelegate, System.Net.Security.SslStream._userCertificateSelectionCallback, System.SR.Format(), System.Net.Security.LocalCertSelectionCallback(), System.SR.net_conflicting_options, and System.Net.Security.SslStream.UserCertSelectionCallbackWrapper().
Referenced by System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsClientApm(), and System.Net.Security.SslStream.AuthenticateAsClientAsync().