Terraria: System.Net.Security.SslStream.AuthenticateAsClientApm
AuthenticateAsClientApm()
Task System.Net.Security.SslStream.AuthenticateAsClientApm (SslClientAuthenticationOptions sslClientAuthenticationOptions, CancellationToken cancellationToken = default(CancellationToken)) inline private
Definition at line 589 of file SslStream.cs.
    {
        SetAndVerifyValidationCallback(sslClientAuthenticationOptions.RemoteCertificateValidationCallback);
        SetAndVerifySelectionCallback(sslClientAuthenticationOptions.LocalCertificateSelectionCallback);
        ValidateCreateContext(sslClientAuthenticationOptions, _userCertificateValidationCallback, _certSelectionDelegate);
        return ProcessAuthenticationAsync(isAsync: true, isApm: true, cancellationToken);
    }
References System.Net.Security.SslStream._certSelectionDelegate, System.Net.Security.SslStream._userCertificateValidationCallback, System.cancellationToken, System.Net.Security.SslClientAuthenticationOptions.LocalCertificateSelectionCallback, System.Net.Security.SslStream.ProcessAuthenticationAsync(), System.Net.Security.SslClientAuthenticationOptions.RemoteCertificateValidationCallback, System.Net.Security.SslStream.SetAndVerifySelectionCallback(), System.Net.Security.SslStream.SetAndVerifyValidationCallback(), and System.Net.Security.SslStream.ValidateCreateContext().
Referenced by System.Net.Security.SslStream.BeginAuthenticateAsClient().