Terraria: System.Net.Security.SslStream.WriteAsyncInternal< TIOAdapter >
WriteAsyncInternal< TIOAdapter >()
async ValueTask System.Net.Security.SslStream.WriteAsyncInternal< TIOAdapter > (TIOAdapter writeAdapter, ReadOnlyMemory< byte > buffer) inline private
Type Constraints
TIOAdapter : struct
TIOAdapter : IReadWriteAdapter
Definition at line 1696 of file SslStream.cs.
                                                                                                                                  : struct, IReadWriteAdapter
    {
        ThrowIfExceptionalOrNotAuthenticatedOrShutdown();
        _ = buffer.Length;
        if (Interlocked.Exchange(ref _nestedWrite, 1) == 1)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "WriteAsync", "write"));
        }
        try
        {
            await ((buffer.Length < MaxDataSize) ? WriteSingleChunk(writeAdapter, buffer) : WriteAsyncChunked(writeAdapter, buffer)).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception ex)
        {
            if (ex is IOException || (ex is OperationCanceledException && writeAdapter.CancellationToken.IsCancellationRequested))
            {
                throw;
            }
            throw new IOException(System.SR.net_io_write, ex);
        }
        finally
        {
            _nestedWrite = 0;
        }
    }
References System.Net.Security.SslStream._nestedWrite, System.buffer, System.OperationCanceledException.CancellationToken, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.Threading.CancellationToken.IsCancellationRequested, System.Net.Security.SslStream.MaxDataSize, System.SR.net_io_invalidnestedcall, System.SR.net_io_write, and System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticatedOrShutdown().