Terraria: System.Net.Security.SslStream.CopyDecryptedData
CopyDecryptedData()
int System.Net.Security.SslStream.CopyDecryptedData (Memory< byte > buffer) inline private
Definition at line 1732 of file SslStream.cs.
    {
        int num = Math.Min(_decryptedBytesCount, buffer.Length);
        if (num != 0)
        {
            new ReadOnlySpan<byte>(_internalBuffer, _decryptedBytesOffset, num).CopyTo(buffer.Span);
            _decryptedBytesOffset += num;
            _decryptedBytesCount -= num;
        }
        if (_decryptedBytesCount == 0)
        {
            _decryptedBytesOffset = 0;
        }
        return num;
    }
References System.Net.Security.SslStream._decryptedBytesCount, System.Net.Security.SslStream._decryptedBytesOffset, System.Net.Security.SslStream._internalBuffer, System.buffer, System.ReadOnlySpan< T >.CopyTo(), and System.Math.Min().
Referenced by System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >().