Terraria: System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticatedOrShutdown
ThrowIfExceptionalOrNotAuthenticatedOrShutdown()
void System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticatedOrShutdown () inline private
Definition at line 886 of file SslStream.cs.
    {
        ThrowIfExceptional();
        if (!IsAuthenticated)
        {
            ThrowNotAuthenticated();
        }
        if (_shutdown)
        {
            ThrowAlreadyShutdown();
        }
        static void ThrowAlreadyShutdown()
        {
            throw new InvalidOperationException(System.SR.net_ssl_io_already_shutdown);
        }
    }
References System.Net.Security.SslStream._shutdown, System.Net.Security.SslStream.IsAuthenticated, System.SR.net_ssl_io_already_shutdown, System.Net.Security.SslStream.ThrowIfExceptional(), and System.Net.Security.SslStream.ThrowNotAuthenticated().
Referenced by System.Net.Security.SslStream.ShutdownAsync(), and System.Net.Security.SslStream.WriteAsyncInternal< TIOAdapter >().