Terraria: System.Linq.Expressions.LambdaExpression.GetCompileMethod
GetCompileMethod()
static MethodInfo System.Linq.Expressions.LambdaExpression.GetCompileMethod (Type lambdaExpressionType) inline static package inherited
Definition at line 76 of file LambdaExpression.cs.
    {
        if (lambdaExpressionType == typeof(LambdaExpression))
        {
            return typeof(LambdaExpression).GetMethod("Compile", System.Type.EmptyTypes);
        }
        return (MethodInfo)lambdaExpressionType.GetMemberWithSameMetadataDefinitionAs(s_expressionCompileMethodInfo);
    }
References System.Type.EmptyTypes, System.Type.GetMemberWithSameMetadataDefinitionAs(), and System.Linq.Expressions.LambdaExpression.s_expressionCompileMethodInfo.
Referenced by System.Linq.Expressions.Interpreter.LightCompiler.CompileInvocationExpression(), and System.Linq.Expressions.Compiler.LambdaCompiler.EmitInvocationExpression().