Terraria: System.Net.Security.SslStream.ResetReadBuffer
ResetReadBuffer()
void System.Net.Security.SslStream.ResetReadBuffer () inline private
Definition at line 1748 of file SslStream.cs.
    {
        if (_internalBuffer == null)
        {
            _internalBuffer = ArrayPool<byte>.Shared.Rent(16448);
        }
        else if (_internalOffset > 0)
        {
            Buffer.BlockCopy(_internalBuffer, _internalOffset, _internalBuffer, 0, _internalBufferCount);
            _internalOffset = 0;
        }
    }
References System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalBufferCount, System.Net.Security.SslStream._internalOffset, System.Buffer.BlockCopy(), and System.Buffers.ArrayPool< T >.Shared.
Referenced by System.Net.Security.SslStream.EnsureFullTlsFrameAsync< TIOAdapter >(), System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), and System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter >().