Terraria: System.Net.Security.SslStream.ReadByte
ReadByte()
override int System.Net.Security.SslStream.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 749 of file SslStream.cs.
    {
        ThrowIfExceptionalOrNotAuthenticated();
        if (Interlocked.Exchange(ref _nestedRead, 1) == 1)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "ReadByte", "read"));
        }
        try
        {
            if (_decryptedBytesCount > 0)
            {
                int result = _internalBuffer[_decryptedBytesOffset++];
                _decryptedBytesCount--;
                ReturnReadBufferIfEmpty();
                return result;
            }
        }
        finally
        {
            _nestedRead = 0;
        }
        byte[] array = new byte[1];
        int num = Read(array, 0, 1);
        if (num != 1)
        {
            return -1;
        }
        return array[0];
    }
References System.Net.Security.SslStream._decryptedBytesCount, System.Net.Security.SslStream._decryptedBytesOffset, System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._nestedRead, System.array, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.SR.net_io_invalidnestedcall, System.IO.Read, System.Net.Security.SslStream.ReturnReadBufferIfEmpty(), and System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated().