Terraria: System.Net.Security.SslStream.ValidateCreateContext
ValidateCreateContext() [2/2]
void System.Net.Security.SslStream.ValidateCreateContext (SslClientAuthenticationOptions sslClientAuthenticationOptions, RemoteCertificateValidationCallback remoteCallback, LocalCertSelectionCallback localCallback) inline private
Definition at line 908 of file SslStream.cs.
    {
        ThrowIfExceptional();
        if (_context != null && _context.IsValidContext)
        {
            throw new InvalidOperationException(System.SR.net_auth_reauth);
        }
        if (_context != null && IsServer)
        {
            throw new InvalidOperationException(System.SR.net_auth_client_server);
        }
        if (sslClientAuthenticationOptions.TargetHost == null)
        {
            throw new ArgumentNullException("TargetHost");
        }
        _exception = null;
        try
        {
            _sslAuthenticationOptions = new SslAuthenticationOptions(sslClientAuthenticationOptions, remoteCallback, localCallback);
            _context = new SecureChannel(_sslAuthenticationOptions, this);
        }
        catch (Win32Exception innerException)
        {
            throw new AuthenticationException(System.SR.net_auth_SSPI, innerException);
        }
    }
References System.Net.Security.SslStream._context, System.Net.Security.SslStream._exception, System.Net.Security.SslStream._sslAuthenticationOptions, System.Net.Security.SslStream.IsServer, System.Net.Security.SecureChannel.IsValidContext, System.SR.net_auth_client_server, System.SR.net_auth_reauth, System.SR.net_auth_SSPI, System.Net.Security.SslClientAuthenticationOptions.TargetHost, and System.Net.Security.SslStream.ThrowIfExceptional().
Referenced by System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsClientApm(), System.Net.Security.SslStream.AuthenticateAsClientAsync(), System.Net.Security.SslStream.AuthenticateAsServer(), System.Net.Security.SslStream.AuthenticateAsServerApm(), System.Net.Security.SslStream.AuthenticateAsServerAsync(), and System.Net.Security.SslStream.AuthenticateAsServerAsync().