Terraria: System.Net.Security.SslStream.SetAndVerifyValidationCallback
SetAndVerifyValidationCallback()
void System.Net.Security.SslStream.SetAndVerifyValidationCallback (RemoteCertificateValidationCallback callback) inline private
Definition at line 361 of file SslStream.cs.
    {
        if (_userCertificateValidationCallback == null)
        {
            _userCertificateValidationCallback = callback;
        }
        else if (callback != null && _userCertificateValidationCallback != callback)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_conflicting_options, "RemoteCertificateValidationCallback"));
        }
    }
References System.Net.Security.SslStream._userCertificateValidationCallback, System.SR.Format(), and System.SR.net_conflicting_options.
Referenced by System.Net.Security.SslStream.AuthenticateAsClient(), System.Net.Security.SslStream.AuthenticateAsClientApm(), System.Net.Security.SslStream.AuthenticateAsClientAsync(), System.Net.Security.SslStream.AuthenticateAsServer(), System.Net.Security.SslStream.AuthenticateAsServerApm(), and System.Net.Security.SslStream.AuthenticateAsServerAsync().