Terraria: System.Net.Security.SslStream.FillHandshakeBufferAsync< TIOAdapter >
FillHandshakeBufferAsync< TIOAdapter >()
ValueTask< int > System.Net.Security.SslStream.FillHandshakeBufferAsync< TIOAdapter > (TIOAdapter adapter, int minSize) inline private
Type Constraints
TIOAdapter : IReadWriteAdapter
Definition at line 1653 of file SslStream.cs.
                                                                                                                  : IReadWriteAdapter
    {
        if (_handshakeBuffer.ActiveLength >= minSize)
        {
            return new ValueTask<int>(minSize);
        }
        int byteCount = minSize - _handshakeBuffer.ActiveLength;
        _handshakeBuffer.EnsureAvailableSpace(byteCount);
        while (_handshakeBuffer.ActiveLength < minSize)
        {
            ValueTask<int> task2 = adapter.ReadAsync(_handshakeBuffer.AvailableMemory);
            if (!task2.IsCompletedSuccessfully)
            {
                return InternalFillHandshakeBufferAsync(adapter, task2, minSize);
            }
            int result = task2.Result;
            if (result == 0)
            {
                return new ValueTask<int>(0);
            }
            _handshakeBuffer.Commit(result);
        }
        return new ValueTask<int>(minSize);
        async ValueTask<int> InternalFillHandshakeBufferAsync(TIOAdapter adap, ValueTask<int> task, int minSize)
        {
            while (true)
            {
                int num = await task.ConfigureAwait(continueOnCapturedContext: false);
                if (num == 0)
                {
                    throw new IOException(System.SR.net_io_eof);
                }
                _handshakeBuffer.Commit(num);
                if (_handshakeBuffer.ActiveLength >= minSize)
                {
                    break;
                }
                task = adap.ReadAsync(_handshakeBuffer.AvailableMemory);
            }
            return minSize;
        }
    }
References System.Net.Security.SslStream._handshakeBuffer, System.Net.ArrayBuffer.ActiveLength, System.Net.ArrayBuffer.AvailableMemory, System.byteCount, System.Net.ArrayBuffer.Commit(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.Net.ArrayBuffer.EnsureAvailableSpace(), System.Threading.Tasks.ValueTask< TResult >.IsCompletedSuccessfully, System.SR.net_io_eof, System.Threading.Tasks.ValueTask< TResult >.Result, and System.task.