Terraria: System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter >
ReadAsyncInternal< TIOAdapter >()
async ValueTask< int > System.Net.Security.SslStream.ReadAsyncInternal< TIOAdapter > (TIOAdapter adapter, Memory< byte > buffer) inline private
Type Constraints
TIOAdapter : IReadWriteAdapter
Definition at line 1547 of file SslStream.cs.
                                                                                                                         : IReadWriteAdapter
    {
        if (Interlocked.Exchange(ref _nestedRead, 1) == 1)
        {
            throw new NotSupportedException(System.SR.Format(System.SR.net_io_invalidnestedcall, "ReadAsync", "read"));
        }
        ThrowIfExceptionalOrNotAuthenticated();
        int processedLength = 0;
        int frameSize = 0;
        try
        {
            if (_decryptedBytesCount != 0)
            {
                processedLength = CopyDecryptedData(buffer);
                if (processedLength == buffer.Length || !HaveFullTlsFrame(out frameSize))
                {
                    return processedLength;
                }
                buffer = buffer.Slice(processedLength);
            }
            if (_receivedEOF)
            {
                return 0;
            }
            if (buffer.Length == 0 && _internalBuffer == null)
            {
                await adapter.ReadAsync(Memory<byte>.Empty).ConfigureAwait(continueOnCapturedContext: false);
            }
            while (true)
            {
                frameSize = await EnsureFullTlsFrameAsync(adapter).ConfigureAwait(continueOnCapturedContext: false);
                if (frameSize == 0)
                {
                    _receivedEOF = true;
                    break;
                }
                SecurityStatusPal securityStatusPal = DecryptData(frameSize);
                if (securityStatusPal.ErrorCode != SecurityStatusPalErrorCode.OK)
                {
                    byte[] array = null;
                    if (_decryptedBytesCount != 0)
                    {
                        array = new byte[_decryptedBytesCount];
                        Buffer.BlockCopy(_internalBuffer, _decryptedBytesOffset, array, 0, _decryptedBytesCount);
                        _decryptedBytesCount = 0;
                    }
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(null, $"***Processing an error Status = {securityStatusPal}", "ReadAsyncInternal");
                    }
                    if (securityStatusPal.ErrorCode == SecurityStatusPalErrorCode.Renegotiate)
                    {
                        if (_handshakeWaiter == null)
{
                            throw new IOException(System.SR.net_ssl_io_renego);
                        }
                        await ReplyOnReAuthenticationAsync(adapter, array).ConfigureAwait(continueOnCapturedContext: false);
                        continue;
                    }
                    if (securityStatusPal.ErrorCode == SecurityStatusPalErrorCode.ContextExpired)
                    {
                        _receivedEOF = true;
                        break;
                    }
                    throw new IOException(System.SR.net_io_decrypt, SslStreamPal.GetException(securityStatusPal));
                }
                if (_decryptedBytesCount > 0)
                {
                    int num = CopyDecryptedData(buffer);
                    processedLength += num;
                    if (num == buffer.Length)
                    {
                        break;
                    }
                    buffer = buffer.Slice(num);
                }
                if (processedLength != 0)
                {
                    if (!HaveFullTlsFrame(out frameSize))
                    {
                        break;
                    }
                    TlsFrameHelper.TryGetFrameHeader(_internalBuffer.AsSpan(_internalOffset), ref _lastFrame.Header);
                    if (_lastFrame.Header.Type != TlsContentType.AppData)
                    {
                        break;
                    }
                }
            }
            return processedLength;
        }
        catch (Exception ex)
        {
            if (ex is IOException || (ex is OperationCanceledException && adapter.CancellationToken.IsCancellationRequested))
            {
                throw;
            }
            throw new IOException(System.SR.net_io_read, ex);
        }
        finally
        {
            ReturnReadBufferIfEmpty();
            _nestedRead = 0;
        }
    }
References System.Net.Security.SslStream._decryptedBytesCount, System.Net.Security.SslStream._decryptedBytesOffset, System.Net.Security.SslStream._handshakeWaiter, System.Net.Security.SslStream._internalBuffer, System.Net.Security.SslStream._internalOffset, System.Net.Security.SslStream._lastFrame, System.Net.Security.SslStream._nestedRead, System.Net.Security.SslStream._receivedEOF, System.array, System.Buffer.BlockCopy(), System.buffer, System.OperationCanceledException.CancellationToken, System.Net.Security.SslStream.CopyDecryptedData(), System.Net.Security.SslStream.DecryptData(), System.Net.SecurityStatusPal.ErrorCode, System.Threading.Interlocked.Exchange(), System.SR.Format(), System.Net.Security.SslStreamPal.GetException(), System.Net.Security.SslStream.HaveFullTlsFrame(), System.Net.NetEventSource.Info(), System.Threading.CancellationToken.IsCancellationRequested, System.Net.NetEventSource.Log, System.SR.net_io_decrypt, System.SR.net_io_invalidnestedcall, System.SR.net_io_read, System.SR.net_ssl_io_renego, System.Net.Security.SslStream.ReturnReadBufferIfEmpty(), System.Net.Security.SslStream.ThrowIfExceptionalOrNotAuthenticated(), and System.Net.Security.TlsFrameHelper.TryGetFrameHeader().