Terraria: Terraria.Graphics.Capture.CaptureCamera.SaveImage
SaveImage() [1/2]
bool Terraria.Graphics.Capture.CaptureCamera.SaveImage (int width, int height, ImageFormat imageFormat, string filename) inline private
Definition at line 250 of file CaptureCamera.cs.
    {
        if (!Utils.TryCreatingDirectory(Main.SavePath + Path.DirectorySeparatorChar + "Captures" + Path.DirectorySeparatorChar))
        {
            return false;
        }
        try
        {
            if (!Platform.IsWindows)
            {
                using FileStream stream = File.Create(filename);
                PlatformUtilities.SavePng(stream, width, height, width, height, _outputData);
            }
            else
            {
                using Bitmap bitmap = new Bitmap(width, height);
                System.Drawing.Rectangle rect = new System.Drawing.Rectangle(0, 0, width, height);
                BitmapData bitmapData = bitmap.LockBits(rect, ImageLockMode.WriteOnly, PixelFormat.Format32bppPArgb);
                IntPtr scan = bitmapData.Scan0;
                Marshal.Copy(_outputData, 0, scan, width * height * 4);
                bitmap.UnlockBits(bitmapData);
                bitmap.Save(filename, imageFormat);
                bitmap.Dispose();
            }
            return true;
        }
        catch (Exception value)
        {
            Console.WriteLine(value);
            return false;
        }
    }
References Terraria.Graphics.Capture.CaptureCamera._outputData, System.Runtime.InteropServices.Marshal.Copy(), System.IO.File.Create(), System.IO.Path.DirectorySeparatorChar, ReLogic.OS.Platform.IsWindows, Terraria.Main.SavePath, Terraria.Utilities.PlatformUtilities.SavePng(), System.stream, Terraria.Utils.TryCreatingDirectory(), System.value, and System.Console.WriteLine().
Referenced by Terraria.Graphics.Capture.CaptureCamera.DrawTick(), and Terraria.Graphics.Capture.CaptureCamera.FinishCapture().