Terraria: Terraria.Graphics.Capture.CaptureCamera.FinishCapture
FinishCapture()
void Terraria.Graphics.Capture.CaptureCamera.FinishCapture () inline private
Definition at line 341 of file CaptureCamera.cs.
    {
        if (_activeSettings.UseScaling)
        {
            int num = 0;
            while (!SaveImage(_outputImageSize.Width, _outputImageSize.Height, ImageFormat.Png, Main.SavePath + Path.DirectorySeparatorChar + "Captures" + Path.DirectorySeparatorChar + _activeSettings.OutputName + ".png"))
            {
                GC.Collect();
                Thread.Sleep(5);
                num++;
                Console.WriteLine(Language.GetTextValue("Error.CaptureError"));
                if (num > 5)
                {
                    Console.WriteLine(Language.GetTextValue("Error.UnableToCapture"));
                    break;
                }
            }
        }
        _outputData = null;
        _scaledFrameData = null;
        Main.GlobalTimerPaused = false;
        CaptureInterface.EndCamera();
        if (_scaledFrameBuffer != null)
        {
            _scaledFrameBuffer.Dispose();
            _scaledFrameBuffer = null;
        }
        _activeSettings = null;
    }
References Terraria.Graphics.Capture.CaptureCamera._activeSettings, Terraria.Graphics.Capture.CaptureCamera._outputData, Terraria.Graphics.Capture.CaptureCamera._outputImageSize, Terraria.Graphics.Capture.CaptureCamera._scaledFrameBuffer, Terraria.Graphics.Capture.CaptureCamera._scaledFrameData, System.GC.Collect(), System.IO.Path.DirectorySeparatorChar, Microsoft.Xna.Framework.Graphics.RenderTarget2D.Dispose(), Terraria.Graphics.Capture.CaptureInterface.EndCamera(), Terraria.Localization.Language.GetTextValue(), System.Drawing.Size.Height, Terraria.Graphics.Capture.CaptureSettings.OutputName, Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Main.SavePath, System.Threading.Thread.Sleep(), Terraria.Graphics.Capture.CaptureSettings.UseScaling, System.Drawing.Size.Width, and System.Console.WriteLine().
Referenced by Terraria.Graphics.Capture.CaptureCamera.DrawTick().