Terraria: Terraria.Graphics.Capture.CaptureCamera.Capture
Capture()
void Terraria.Graphics.Capture.CaptureCamera.Capture (CaptureSettings settings) inline
Definition at line 106 of file CaptureCamera.cs.
    {
        Main.GlobalTimerPaused = true;
        Monitor.Enter(_captureLock);
        if (_activeSettings != null)
        {
            throw new InvalidOperationException("Capture called while another capture was already active.");
        }
        _activeSettings = settings;
        Microsoft.Xna.Framework.Rectangle area = settings.Area;
        float num = 1f;
        if (settings.UseScaling)
        {
            if (area.Width * 16 > 4096)
            {
                num = 4096f / (float)(area.Width * 16);
            }
            if (area.Height * 16 > 4096)
            {
                num = Math.Min(num, 4096f / (float)(area.Height * 16));
            }
            num = Math.Min(1f, num);
            _outputImageSize = new Size((int)MathHelper.Clamp((int)(num * (float)(area.Width * 16)), 1f, 4096f), (int)MathHelper.Clamp((int)(num * (float)(area.Height * 16)), 1f, 4096f));
            _outputData = new byte[4 * _outputImageSize.Width * _outputImageSize.Height];
            int num2 = (int)Math.Floor(num * 2048f);
            _scaledFrameData = new byte[4 * num2 * num2];
            _scaledFrameBuffer = new RenderTarget2D(_graphics, num2, num2, mipMap: false, _graphics.PresentationParameters.BackBufferFormat, DepthFormat.None);
        }
        else
        {
            _outputData = new byte[16777216];
        }
        _tilesProcessed = 0f;
        _totalTiles = area.Width * area.Height;
        for (int i = area.X; i < area.X + area.Width; i += 126)
        {
            for (int j = area.Y; j < area.Y + area.Height; j += 126)
            {
                int num3 = Math.Min(128, area.X + area.Width - i);
                int num4 = Math.Min(128, area.Y + area.Height - j);
                int width = (int)Math.Floor(num * (float)(num3 * 16));
                int height = (int)Math.Floor(num * (float)(num4 * 16));
                int x = (int)Math.Floor(num * (float)((i - area.X) * 16));
                int y = (int)Math.Floor(num * (float)((j - area.Y) * 16));
                _renderQueue.Enqueue(new CaptureChunk(new Microsoft.Xna.Framework.Rectangle(i, j, num3, num4), new Microsoft.Xna.Framework.Rectangle(x, y, width, height)));
            }
        }
        Monitor.Exit(_captureLock);
    }
References Terraria.Graphics.Capture.CaptureCamera._activeSettings, Terraria.Graphics.Capture.CaptureCamera._captureLock, Terraria.Graphics.Capture.CaptureCamera._graphics, Terraria.Graphics.Capture.CaptureCamera._outputData, Terraria.Graphics.Capture.CaptureCamera._outputImageSize, Terraria.Graphics.Capture.CaptureCamera._renderQueue, Terraria.Graphics.Capture.CaptureCamera._scaledFrameBuffer, Terraria.Graphics.Capture.CaptureCamera._scaledFrameData, Terraria.Graphics.Capture.CaptureCamera._tilesProcessed, Terraria.Graphics.Capture.CaptureCamera._totalTiles, Terraria.Graphics.Capture.CaptureSettings.Area, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.MathHelper.Clamp(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Math.Floor(), System.Drawing.Size.Height, System.Math.Min(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, System.IO.Size, and Terraria.Graphics.Capture.CaptureSettings.UseScaling.
Referenced by Terraria.Graphics.Capture.CaptureManager.Capture().