Terraria: System.Net.Mail.SendMailAsyncResult.SendMailFrom
SendMailFrom()
void System.Net.Mail.SendMailAsyncResult.SendMailFrom () inline private
Definition at line 58 of file SendMailAsyncResult.cs.
    {
        IAsyncResult asyncResult = MailCommand.BeginSend(_connection, SmtpCommands.Mail, _from, _allowUnicode, s_sendMailFromCompleted, this);
        if (asyncResult.CompletedSynchronously)
        {
            MailCommand.EndSend(asyncResult);
            SendToCollection();
        }
    }
References System.Net.Mail.SendMailAsyncResult._allowUnicode, System.Net.Mail.SendMailAsyncResult._connection, System.Net.Mail.SendMailAsyncResult._from, System.asyncResult, System.Net.Mail.MailCommand.BeginSend(), System.Net.Mail.MailCommand.EndSend(), System.Net.Mail.SmtpCommands.Mail, System.Net.Mail.SendMailAsyncResult.s_sendMailFromCompleted, and System.Net.Mail.SendMailAsyncResult.SendToCollection().
Referenced by System.Net.Mail.SendMailAsyncResult.Send().