Terraria: System.Xml.Schema.XsdBuilder.ProcessAttribute
ProcessAttribute()
override void System.Xml.Schema.XsdBuilder.ProcessAttribute (string prefix, string name, string ns, string value) inline package
Definition at line 766 of file XsdBuilder.cs.
    {
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(name, ns);
        if (_currentEntry.Attributes != null)
        {
            for (int i = 0; i < _currentEntry.Attributes.Length; i++)
            {
                XsdAttributeEntry xsdAttributeEntry = _currentEntry.Attributes[i];
                if (_schemaNames.TokenToQName[(int)xsdAttributeEntry.Attribute].Equals(xmlQualifiedName))
                {
                    try
                    {
                        xsdAttributeEntry.BuildFunc(this, value);
                        return;
                    }
                    catch (XmlSchemaException ex)
                    {
                        ex.SetSource(_reader.BaseURI, _positionInfo.LineNumber, _positionInfo.LinePosition);
                        SendValidationEvent(System.SR.Sch_InvalidXsdAttributeDatatypeValue, new string[2] { name, ex.Message }, XmlSeverityType.Error);
                        return;
                    }
                }
            }
        }
        if (ns != _schemaNames.NsXs && ns.Length != 0)
        {
            if (ns == _schemaNames.NsXmlNs)
            {
                if (_namespaces == null)
                {
                    _namespaces = new List<XmlQualifiedName>();
                }
                _namespaces.Add(new XmlQualifiedName((name == _schemaNames.QnXmlNs.Name) ? string.Empty : name, value));
            }
            else
            {
                XmlAttribute xmlAttribute = new XmlAttribute(prefix, name, ns, _schema.Document);
                xmlAttribute.Value = value;
                _unhandledAttributes.Add(xmlAttribute);
            }
        }
        else
        {
            SendValidationEvent(System.SR.Sch_UnsupportedAttribute, xmlQualifiedName.ToString());
        }
    }
References System.Xml.Schema.XsdBuilder._currentEntry, System.Xml.Schema.XsdBuilder._namespaces, System.Xml.Schema.XsdBuilder._positionInfo, System.Xml.Schema.XsdBuilder._reader, System.Xml.Schema.XsdBuilder._schema, System.Xml.Schema.XsdBuilder._schemaNames, System.Xml.Schema.XsdBuilder._unhandledAttributes, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XsdBuilder.XsdEntry.Attributes, System.Xml.XmlReader.BaseURI, System.Xml.Dictionary, System.Xml.Schema.XmlSchema.Document, System.Xml.XmlQualifiedName.Equals(), System.Xml.PositionInfo.LineNumber, System.Xml.PositionInfo.LinePosition, System.Xml.XmlQualifiedName.Name, System.Xml.Schema.SchemaNames.NsXmlNs, System.Xml.Schema.SchemaNames.NsXs, System.prefix, System.Xml.Schema.SchemaNames.QnXmlNs, System.SR.Sch_InvalidXsdAttributeDatatypeValue, System.SR.Sch_UnsupportedAttribute, System.Xml.Schema.XsdBuilder.SendValidationEvent(), System.Xml.Schema.SchemaNames.TokenToQName, and System.value.