Terraria: System.Xml.Schema.XsdBuilder.ParseQName
ParseQName()
XmlQualifiedName System.Xml.Schema.XsdBuilder.ParseQName (string value, string attributeName) inline private
Definition at line 2156 of file XsdBuilder.cs.
    {
        try
        {
            value = XmlComplianceUtil.NonCDataNormalize(value);
            string prefix;
            return XmlQualifiedName.Parse(value, _namespaceManager, out prefix);
        }
        catch (Exception)
        {
            SendValidationEvent(System.SR.Sch_InvalidXsdAttributeValue, attributeName, value, null);
            return XmlQualifiedName.Empty;
        }
    }
References System.Xml.Schema.XsdBuilder._namespaceManager, System.Xml.XmlQualifiedName.Empty, System.Xml.XmlComplianceUtil.NonCDataNormalize(), System.Xml.XmlQualifiedName.Parse(), System.prefix, System.SR.Sch_InvalidXsdAttributeValue, System.Xml.Schema.XsdBuilder.SendValidationEvent(), and System.value.