Terraria: System.Net.Http.Http3Connection.SendSettingsAsync
SendSettingsAsync()
async Task System.Net.Http.Http3Connection.SendSettingsAsync () inline private
Definition at line 272 of file Http3Connection.cs.
    {
        try
        {
            _clientControl = _connection.OpenUnidirectionalStream();
            await _clientControl.WriteAsync(_pool.Settings.Http3SettingsFrame, CancellationToken.None).ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (Exception abortException)
        {
            Abort(abortException);
        }
    }
References System.Net.Http.Http3Connection._clientControl, System.Net.Http.Http3Connection._connection, System.Net.Http.Http3Connection._pool, System.Net.Abort, System.Net.Http.HttpConnectionSettings.Http3SettingsFrame, System.Threading.CancellationToken.None, System.Net.Quic.QuicConnection.OpenUnidirectionalStream(), System.Net.Http.HttpConnectionPool.Settings, and System.Net.Quic.QuicStream.WriteAsync().
Referenced by System.Net.Http.Http3Connection.Http3Connection().