Terraria: System.Net.Http.Http3Connection.Http3Connection
Http3Connection()
System.Net.Http.Http3Connection.Http3Connection (HttpConnectionPool pool, HttpAuthority origin, HttpAuthority authority, QuicConnection connection) inline
Definition at line 59 of file Http3Connection.cs.
    {
        _pool = pool;
        _origin = origin;
        _authority = authority;
        _connection = connection;
        string text;
        if ((pool.Kind != 0 || authority.Port != 80) && (pool.Kind != HttpConnectionKind.Https || authority.Port != 443))
        {
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(1, 2, invariantCulture);
            handler.AppendFormatted(authority.IdnHost);
            handler.AppendLiteral(":");
            handler.AppendFormatted(authority.Port);
            text = string.Create(invariantCulture, ref handler);
        }
        else
        {
            text = authority.IdnHost;
        }
        string value = text;
        _altUsedEncodedHeader = QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray(KnownHeaders.AltUsed.Name, value);
        SendSettingsAsync();
        AcceptStreamsAsync();
    }
References System.Net.Http.Http3Connection._altUsedEncodedHeader, System.Net.Http.Http3Connection._authority, System.Net.Http.Http3Connection._connection, System.Net.Http.Http3Connection._origin, System.Net.Http.Http3Connection._pool, System.Net.Http.Http3Connection.AcceptStreamsAsync(), System.Net.Http.Headers.KnownHeaders.AltUsed, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Net.Http.QPack.QPackEncoder.EncodeLiteralHeaderFieldWithoutNameReferenceToArray(), System.Globalization.CultureInfo.InvariantCulture, System.Net.Http.Http3Connection.SendSettingsAsync(), System.text, and System.value.