Terraria: System.Net.Http.Http3Connection.SendAsync
SendAsync()
async Task< HttpResponseMessage > System.Net.Http.Http3Connection.SendAsync (HttpRequestMessage request, bool async, CancellationToken cancellationToken) inline
Definition at line 131 of file Http3Connection.cs.
    {
        QuicStream quicStream = null;
        Http3RequestStream requestStream = null;
        ValueTask valueTask = default(ValueTask);
        try
        {
            while (true)
            {
                lock (SyncObj)
                {
                    if (_connection != null)
                    {
                        if (_connection.GetRemoteAvailableBidirectionalStreamCount() <= 0)
{
                            valueTask = _connection.WaitForAvailableBidirectionalStreamsAsync(cancellationToken);
                            goto IL_00ce;
                        }
                        quicStream = _connection.OpenBidirectionalStream();
                        requestStream = new Http3RequestStream(request, this, quicStream);
                        _activeRequests.Add(quicStream, requestStream);
                    }
                }
                break;
                IL_00ce:
                await valueTask.ConfigureAwait(continueOnCapturedContext: false);
            }
            if (quicStream == null)
            {
                throw new HttpRequestException(System.SR.net_http_request_aborted, null, RequestRetryType.RetryOnConnectionFailure);
            }
            requestStream.StreamId = quicStream.StreamId;
            bool flag;
            lock (SyncObj)
            {
                flag = _lastProcessedStreamId != -1 && requestStream.StreamId > _lastProcessedStreamId;
            }
            if (flag)
            {
                throw new HttpRequestException(System.SR.net_http_request_aborted, null, RequestRetryType.RetryOnConnectionFailure);
            }
            Task<HttpResponseMessage> task = requestStream.SendAsync(cancellationToken);
            requestStream = null;
            return await task.ConfigureAwait(continueOnCapturedContext: false);
        }
        catch (QuicConnectionAbortedException ex)
        {
            Abort(ex);
            throw new HttpRequestException(System.SR.Format(System.SR.net_http_http3_connection_error, ex.ErrorCode), ex, RequestRetryType.RetryOnConnectionFailure);
        }
        finally
        {
            requestStream?.Dispose();
        }
    }
References System.Net.Http.Http3Connection._activeRequests, System.Net.Http.Http3Connection._connection, System.Net.Http.Http3Connection._lastProcessedStreamId, System.Net.Abort, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.cancellationToken, System.SR.Format(), System.Net.Quic.QuicConnection.GetRemoteAvailableBidirectionalStreamCount(), System.SR.net_http_http3_connection_error, System.SR.net_http_request_aborted, System.Net.Quic.QuicConnection.OpenBidirectionalStream(), System.Net.Http.Http3Connection.SyncObj, System.task, and System.Net.Quic.QuicConnection.WaitForAvailableBidirectionalStreamsAsync().
Referenced by System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async().