Terraria: System.Net.Http.Http3Connection.Trace
Trace() [2/2]
override void System.Net.Http.Http3Connection.Trace (string message, [CallerMemberName] string memberName = null) inline
Implements System.Net.Http.IHttpTrace.
Definition at line 262 of file Http3Connection.cs.
    {
        Trace(0L, message, memberName);
    }
References System.L, and System.Net.Http.Http3Connection.Trace().
Referenced by System.Net.Http.Http3Connection.Abort(), System.Net.Http.Http3Connection.CheckForShutdown(), System.Net.Http.Http3Connection.OnServerGoAway(), System.Net.Http.Http3Connection.Trace(), and System.Net.Http.Http3RequestStream.Trace().