Terraria: System.Net.Http.Http3Connection.OnServerGoAway
OnServerGoAway()
void System.Net.Http.Http3Connection.OnServerGoAway (long lastProcessedStreamId) inline private
Definition at line 215 of file Http3Connection.cs.
    {
        _pool.InvalidateHttp3Connection(this);
        List<Http3RequestStream> list = new List<Http3RequestStream>();
        lock (SyncObj)
        {
            if (_lastProcessedStreamId != -1 && lastProcessedStreamId > _lastProcessedStreamId)
            {
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    Trace("HTTP/3 server sent GOAWAY with increasing stream ID. Retried requests may have been double-processed by server.", "OnServerGoAway");
                }
                return;
            }
            _lastProcessedStreamId = lastProcessedStreamId;
            foreach (KeyValuePair<QuicStream, Http3RequestStream> activeRequest in _activeRequests)
            {
                if (activeRequest.Value.StreamId > lastProcessedStreamId)
                {
                    list.Add(activeRequest.Value);
                }
            }
            CheckForShutdown();
        }
        foreach (Http3RequestStream item in list)
        {
            item.GoAway();
        }
    }
References System.Net.Http.Http3Connection._activeRequests, System.Net.Http.Http3Connection._lastProcessedStreamId, System.Net.Http.Http3Connection._pool, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Http.Http3Connection.CheckForShutdown(), System.Net.Http.HttpConnectionPool.InvalidateHttp3Connection(), System.item, System.list, System.Net.NetEventSource.Log, System.Net.Http.Http3Connection.SyncObj, and System.Net.Http.Http3Connection.Trace().
Referenced by System.Net.Http.Http3Connection.ProcessServerControlStreamAsync().