Terraria: System.Net.Http.Http3Connection.ProcessServerStreamAsync
ProcessServerStreamAsync()
async Task System.Net.Http.Http3Connection.ProcessServerStreamAsync (QuicStream stream) inline private
Definition at line 324 of file Http3Connection.cs.
    {
        System.Net.ArrayBuffer buffer = default(System.Net.ArrayBuffer);
        try
        {
            ConfiguredAsyncDisposable configuredAsyncDisposable = stream.ConfigureAwait(continueOnCapturedContext: false);
            try
            {
                if (stream.CanWrite)
                {
                    throw new Http3ConnectionException(Http3ErrorCode.StreamCreationError);
                }
                buffer = new System.Net.ArrayBuffer(32, usePool: true);
                int num;
                try
                {
                    num = await stream.ReadAsync(buffer.AvailableMemory, CancellationToken.None).ConfigureAwait(continueOnCapturedContext: false);
                }
                catch (QuicStreamAbortedException)
                {
                    num = 0;
                }
                if (num == 0)
                {
                    return;
                }
                buffer.Commit(num);
                switch (buffer.ActiveSpan[0])
                {
                case 0:
                {
                    if (Interlocked.Exchange(ref _haveServerControlStream, 1) != 0)
                    {
                        throw new Http3ConnectionException(Http3ErrorCode.StreamCreationError);
                    }
                    buffer.Discard(1);
                    System.Net.ArrayBuffer buffer2 = buffer;
                    buffer = default(System.Net.ArrayBuffer);
                    await ProcessServerControlStreamAsync(stream, buffer2).ConfigureAwait(continueOnCapturedContext: false);
                    return;
                }
                case 3:
                    if (Interlocked.Exchange(ref _haveServerQpackDecodeStream, 1) != 0)
                    {
                        throw new Http3ConnectionException(Http3ErrorCode.StreamCreationError);
                    }
                    buffer.Dispose();
                    await stream.CopyToAsync(Stream.Null).ConfigureAwait(continueOnCapturedContext: false);
                    return;
                case 2:
                    if (Interlocked.Exchange(ref _haveServerQpackEncodeStream, 1) != 0)
                    {
                        throw new Http3ConnectionException(Http3ErrorCode.StreamCreationError);
                    }
                    buffer.Dispose();
                    await stream.CopyToAsync(Stream.Null).ConfigureAwait(continueOnCapturedContext: false);
                    return;
                case 1:
                    throw new Http3ConnectionException(Http3ErrorCode.IdError);
                }
                if (System.Net.NetEventSource.Log.IsEnabled())
                {
                    long value;
                    int bytesRead;
                    while (!VariableLengthIntegerHelper.TryRead(buffer.ActiveSpan, out value, out bytesRead))
                    {
                        buffer.EnsureAvailableSpace(8);
                        num = await stream.ReadAsync(buffer.AvailableMemory, CancellationToken.None).ConfigureAwait(continueOnCapturedContext: false);
                        if (num == 0)
{
                            value = -1L;
                            break;
                        }
                        buffer.Commit(num);
                    }
                    System.Net.NetEventSource.Info(this, $"Ignoring server-initiated stream of unknown type {value}.", "ProcessServerStreamAsync");
                }
                stream.AbortWrite(259L);
            }
            finally
            {
                IAsyncDisposable asyncDisposable = configuredAsyncDisposable as IAsyncDisposable;
                if (asyncDisposable != null)
                {
                    await asyncDisposable.DisposeAsync();
                }
            }
        }
        catch (Exception abortException)
        {
            Abort(abortException);
        }
        finally
        {
            buffer.Dispose();
        }
    }
References System.Net.Http.Http3Connection._haveServerControlStream, System.Net.Http.Http3Connection._haveServerQpackDecodeStream, System.Net.Http.Http3Connection._haveServerQpackEncodeStream, System.Net.Abort, System.buffer, System.Threading.Interlocked.Exchange(), System.Net.NetEventSource.Info(), System.L, System.Net.NetEventSource.Log, System.Threading.CancellationToken.None, System.IO.Stream.Null, System.Net.Http.Http3Connection.ProcessServerControlStreamAsync(), System.stream, System.Net.Http.VariableLengthIntegerHelper.TryRead(), and System.value.
Referenced by System.Net.Http.Http3Connection.AcceptStreamsAsync().