Terraria: System.Globalization.Calendar.GetWeekOfYearFullDays
GetWeekOfYearFullDays()
int System.Globalization.Calendar.GetWeekOfYearFullDays (DateTime time, int firstDayOfWeek, int fullDays) inline private inherited
Definition at line 203 of file Calendar.cs.
    {
        int num = GetDayOfYear(time) - 1;
        int num2 = (int)(GetDayOfWeek(time) - num % 7);
        int num3 = (firstDayOfWeek - num2 + 14) % 7;
        if (num3 != 0 && num3 >= fullDays)
        {
            num3 -= 7;
        }
        int num4 = num - num3;
        if (num4 >= 0)
        {
            return num4 / 7 + 1;
        }
        if (time <= MinSupportedDateTime.AddDays(num))
        {
            return GetWeekOfYearOfMinSupportedDateTime(firstDayOfWeek, fullDays);
        }
        return GetWeekOfYearFullDays(time.AddDays(-(num + 1)), firstDayOfWeek, fullDays);
    }
References System.DateTime.AddDays(), System.Globalization.Calendar.GetDayOfWeek(), System.Globalization.Calendar.GetDayOfYear(), System.Globalization.Calendar.GetWeekOfYearFullDays(), System.Globalization.Calendar.GetWeekOfYearOfMinSupportedDateTime(), and System.Globalization.Calendar.MinSupportedDateTime.
Referenced by System.Globalization.Calendar.GetWeekOfYear(), and System.Globalization.Calendar.GetWeekOfYearFullDays().