Terraria: System.Net.Http.Http3Connection.Abort
Abort()
Exception System.Net.Http.Http3Connection.Abort (Exception abortException) inline package
Definition at line 187 of file Http3Connection.cs.
    {
        Exception ex = Interlocked.CompareExchange(ref _abortException, abortException, null);
        if (ex != null)
        {
            if (System.Net.NetEventSource.Log.IsEnabled() && ex != abortException)
            {
                Trace($"{"abortException"}=={abortException}", "Abort");
            }
            return ex;
        }
        _pool.InvalidateHttp3Connection(this);
        Http3ErrorCode errorCode = (abortException as Http3ProtocolException)?.ErrorCode ?? Http3ErrorCode.InternalError;
        lock (SyncObj)
        {
            if (_lastProcessedStreamId == -1)
            {
                _lastProcessedStreamId = long.MaxValue;
            }
            if (_connection != null && _connectionClosedTask == null)
            {
                _connectionClosedTask = _connection.CloseAsync((long)errorCode).AsTask();
            }
            CheckForShutdown();
            return abortException;
        }
    }
References System.Net.Http.Http3Connection._abortException, System.Net.Http.Http3Connection._connection, System.Net.Http.Http3Connection._connectionClosedTask, System.Net.Http.Http3Connection._lastProcessedStreamId, System.Net.Http.Http3Connection._pool, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.Net.Http.Http3Connection.CheckForShutdown(), System.Net.Quic.QuicConnection.CloseAsync(), System.Threading.Interlocked.CompareExchange(), System.Net.Http.HttpConnectionPool.InvalidateHttp3Connection(), System.Net.NetEventSource.Log, System.Net.Http.Http3Connection.SyncObj, and System.Net.Http.Http3Connection.Trace().
Referenced by System.Net.Http.Http3RequestStream.HandleReadResponseContentException(), and System.Net.Http.Http3RequestStream.SendAsync().