Terraria: System.Net.Http.Http3Connection.CheckForShutdown
CheckForShutdown()
void System.Net.Http.Http3Connection.CheckForShutdown () inline private
Definition at line 97 of file Http3Connection.cs.
    {
        if (_activeRequests.Count != 0 || _connection == null)
        {
            return;
        }
        if (_connectionClosedTask == null)
        {
            _connectionClosedTask = _connection.CloseAsync(256L).AsTask();
        }
        QuicConnection connection = _connection;
        _connection = null;
        _connectionClosedTask.ContinueWith(delegate(Task closeTask)
        {
            if (closeTask.IsFaulted && System.Net.NetEventSource.Log.IsEnabled())
            {
                Trace($"{"QuicConnection"} failed to close: {closeTask.Exception.InnerException}", "CheckForShutdown");
            }
            try
            {
                connection.Dispose();
            }
            catch (Exception value)
            {
                Trace($"{"QuicConnection"} failed to dispose: {value}", "CheckForShutdown");
            }
            if (_clientControl != null)
            {
                _clientControl.Dispose();
                _clientControl = null;
            }
        }, CancellationToken.None, TaskContinuationOptions.ExecuteSynchronously, TaskScheduler.Default);
    }
References System.Net.Http.Http3Connection._activeRequests, System.Net.Http.Http3Connection._clientControl, System.Net.Http.Http3Connection._connection, System.Net.Http.Http3Connection._connectionClosedTask, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.Net.Quic.QuicConnection.CloseAsync(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Net.Quic.QuicStream.Dispose(), System.L, System.Net.NetEventSource.Log, System.Threading.CancellationToken.None, System.Net.Http.Http3Connection.Trace(), and System.value.
Referenced by System.Net.Http.Http3Connection.Abort(), System.Net.Http.Http3Connection.Dispose(), System.Net.Http.Http3Connection.OnServerGoAway(), and System.Net.Http.Http3Connection.RemoveStream().