Terraria: System.Net.Mail.SendMailAsyncResult.SendMailAsyncResult
SendMailAsyncResult()
System.Net.Mail.SendMailAsyncResult.SendMailAsyncResult (SmtpConnection connection, MailAddress from, MailAddressCollection toCollection, bool allowUnicode, string deliveryNotify, AsyncCallback callback, object state) inline package
Definition at line 32 of file SendMailAsyncResult.cs.
        : base(null, state, callback)
    {
        _toCollection = toCollection;
        _connection = connection;
        _from = from;
        _deliveryNotify = deliveryNotify;
        _allowUnicode = allowUnicode;
    }
References System.Net.Mail.SendMailAsyncResult._allowUnicode, System.Net.Mail.SendMailAsyncResult._connection, System.Net.Mail.SendMailAsyncResult._deliveryNotify, System.Net.Mail.SendMailAsyncResult._from, and System.Net.Mail.SendMailAsyncResult._toCollection.
Referenced by System.Net.Mail.SendMailAsyncResult.End(), System.Net.Mail.SendMailAsyncResult.SendDataCompleted(), System.Net.Mail.SendMailAsyncResult.SendMailFromCompleted(), and System.Net.Mail.SendMailAsyncResult.SendToCollectionCompleted().