Terraria: System.Net.Http.Http3Connection.AcceptStreamsAsync
AcceptStreamsAsync()
async Task System.Net.Http.Http3Connection.AcceptStreamsAsync () inline private
Definition at line 297 of file Http3Connection.cs.
    {
        try
        {
            while (true)
            {
                ValueTask<QuicStream> valueTask;
                lock (SyncObj)
                {
                    if (ShuttingDown)
                    {
                        break;
                    }
                    valueTask = _connection.AcceptStreamAsync(CancellationToken.None);
                }
                ProcessServerStreamAsync(await valueTask.ConfigureAwait(continueOnCapturedContext: false));
            }
        }
        catch (QuicOperationAbortedException)
        {
        }
        catch (Exception abortException)
        {
            Abort(abortException);
        }
    }
References System.Net.Http.Http3Connection._connection, System.Net.Abort, System.Net.Quic.QuicConnection.AcceptStreamAsync(), System.Threading.CancellationToken.None, System.Net.Http.Http3Connection.ProcessServerStreamAsync(), System.Net.Http.Http3Connection.ShuttingDown, and System.Net.Http.Http3Connection.SyncObj.
Referenced by System.Net.Http.Http3Connection.Http3Connection().