Terraria: System.Globalization.Calendar.CheckAddResult
CheckAddResult()
static void System.Globalization.Calendar.CheckAddResult (long ticks, DateTime minValue, DateTime maxValue) inline static package inherited
Definition at line 89 of file Calendar.cs.
    {
        if (ticks < minValue.Ticks || ticks > maxValue.Ticks)
        {
            throw new ArgumentException(SR.Format(SR.Argument_ResultCalendarRange, minValue, maxValue));
        }
    }
References System.SR.Argument_ResultCalendarRange, System.SR.Format(), and System.DateTime.Ticks.
Referenced by System.Globalization.Calendar.Add(), System.Globalization.EastAsianLunisolarCalendar.AddMonths(), System.Globalization.GregorianCalendar.AddMonths(), System.Globalization.GregorianCalendarHelper.AddMonths(), System.Globalization.HijriCalendar.AddMonths(), System.Globalization.JulianCalendar.AddMonths(), System.Globalization.PersianCalendar.AddMonths(), System.Globalization.UmAlQuraCalendar.AddMonths(), System.Globalization.EastAsianLunisolarCalendar.AddYears(), and System.Globalization.HebrewCalendar.AddYears().