Terraria: System.Xml.Schema.XsdBuilder.Push
Push()
void System.Xml.Schema.XsdBuilder.Push () inline private
Definition at line 854 of file XsdBuilder.cs.
    {
        _stateHistory.Push();
        _stateHistory[_stateHistory.Length - 1] = _currentEntry;
        _containerStack.Push(GetContainer(_currentEntry.CurrentState));
        _currentEntry = _nextEntry;
        if (_currentEntry.Name != SchemaNames.Token.XsdAnnotation)
        {
            _hasChild = false;
        }
    }
References System.Xml.Schema.XsdBuilder._containerStack, System.Xml.Schema.XsdBuilder._currentEntry, System.Xml.Schema.XsdBuilder._hasChild, System.Xml.Schema.XsdBuilder._nextEntry, System.Xml.Schema.XsdBuilder._stateHistory, System.Xml.Schema.XsdBuilder.XsdEntry.CurrentState, System.Xml.Dictionary, System.Xml.Schema.XsdBuilder.GetContainer(), System.Xml.Schema.XsdBuilder.XsdEntry.Name, and System.Xml.HWStack.Push().
Referenced by System.Xml.Schema.XsdBuilder.ProcessElement().