Terraria: System.Net.Mail.SendMailAsyncResult.SendToCollection
SendToCollection()
void System.Net.Mail.SendMailAsyncResult.SendToCollection () inline private
Definition at line 85 of file SendMailAsyncResult.cs.
    {
        while (_toIndex < _toCollection.Count)
        {
            MultiAsyncResult multiAsyncResult = (MultiAsyncResult)RecipientCommand.BeginSend(_connection, _toCollection[_toIndex++].GetSmtpAddress(_allowUnicode) + _deliveryNotify, s_sendToCollectionCompleted, this);
            if (!multiAsyncResult.CompletedSynchronously)
            {
                return;
            }
            if (!RecipientCommand.EndSend(multiAsyncResult, out var response))
            {
                _failedRecipientExceptions.Add(new SmtpFailedRecipientException(_connection.Reader.StatusCode, _toCollection[_toIndex - 1].GetSmtpAddress(_allowUnicode), response));
            }
        }
        SendData();
    }
References System.Net.Mail.SendMailAsyncResult._allowUnicode, System.Net.Mail.SendMailAsyncResult._connection, System.Net.Mail.SendMailAsyncResult._deliveryNotify, System.Net.Mail.SendMailAsyncResult._failedRecipientExceptions, System.Net.Mail.SendMailAsyncResult._toCollection, System.Net.Mail.SendMailAsyncResult._toIndex, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Net.Mail.RecipientCommand.BeginSend(), System.Collections.ObjectModel.Collection< T >.Count, System.Net.Mail.RecipientCommand.EndSend(), System.Net.Mail.SmtpConnection.Reader, System.Net.Mail.SendMailAsyncResult.s_sendToCollectionCompleted, System.Net.Mail.SendMailAsyncResult.SendData(), and System.Net.Mail.SmtpReplyReaderFactory.StatusCode.
Referenced by System.Net.Mail.SendMailAsyncResult.SendMailFrom().