Terraria: System.Xml.Schema.XsdBuilder.SendValidationEvent
SendValidationEvent() [1/5]
void System.Xml.Schema.XsdBuilder.SendValidationEvent (string code, string arg0, string arg1, string arg2) inline private
Definition at line 2211 of file XsdBuilder.cs.
    {
        SendValidationEvent(new XmlSchemaException(code, new string[3] { arg0, arg1, arg2 }, _reader.BaseURI, _positionInfo.LineNumber, _positionInfo.LinePosition));
    }
References System.Xml.Schema.XsdBuilder._positionInfo, System.Xml.Schema.XsdBuilder._reader, System.Xml.XmlReader.BaseURI, System.Xml.Dictionary, System.Xml.PositionInfo.LineNumber, System.Xml.PositionInfo.LinePosition, and System.Xml.Schema.XsdBuilder.SendValidationEvent().
Referenced by System.Xml.Schema.XsdBuilder.AddAttribute(), System.Xml.Schema.XsdBuilder.AddParticle(), System.Xml.Schema.XsdBuilder.ParseBlockFinalEnum(), System.Xml.Schema.XsdBuilder.ParseBoolean(), System.Xml.Schema.XsdBuilder.ParseEnum(), System.Xml.Schema.XsdBuilder.ParseQName(), System.Xml.Schema.XsdBuilder.ProcessAttribute(), System.Xml.Schema.XsdBuilder.ProcessCData(), System.Xml.Schema.XsdBuilder.ProcessElement(), System.Xml.Schema.XsdBuilder.SendValidationEvent(), System.Xml.Schema.XsdBuilder.SendValidationEvent(), System.Xml.Schema.XsdBuilder.SendValidationEvent(), System.Xml.Schema.XsdBuilder.SendValidationEvent(), System.Xml.Schema.XsdBuilder.SetMaxOccurs(), and System.Xml.Schema.XsdBuilder.SetMinOccurs().