Terraria: System.Globalization.Calendar.IsValidYear
IsValidYear()
virtual bool System.Globalization.Calendar.IsValidYear (int year, int era) inline package virtual inherited
Reimplemented in System.Globalization.GregorianCalendar, and System.Globalization.JapaneseCalendar.
Definition at line 325 of file Calendar.cs.
    {
        if (year >= GetYear(MinSupportedDateTime))
        {
            return year <= GetYear(MaxSupportedDateTime);
        }
        return false;
    }
References System.Globalization.Calendar.GetYear(), System.Globalization.Calendar.MaxSupportedDateTime, System.Globalization.Calendar.MinSupportedDateTime, and System.year.
Referenced by System.Globalization.Calendar.IsValidMonth(), and Internal.Cryptography.Helpers.IsValidMonth().