Terraria: System.Net.Mail.SendMailAsyncResult.SendData
SendData()
void System.Net.Mail.SendMailAsyncResult.SendData () inline private
Definition at line 130 of file SendMailAsyncResult.cs.
    {
        IAsyncResult asyncResult = DataCommand.BeginSend(_connection, s_sendDataCompleted, this);
        if (asyncResult.CompletedSynchronously)
        {
            DataCommand.EndSend(asyncResult);
            _stream = _connection.GetClosableStream();
            if (_failedRecipientExceptions.Count > 1)
            {
                InvokeCallback(new SmtpFailedRecipientsException(_failedRecipientExceptions, _failedRecipientExceptions.Count == _toCollection.Count));
            }
            else if (_failedRecipientExceptions.Count == 1)
            {
                InvokeCallback(_failedRecipientExceptions[0]);
            }
            else
            {
                InvokeCallback();
            }
        }
    }
References System.Net.Mail.SendMailAsyncResult._connection, System.Net.Mail.SendMailAsyncResult._failedRecipientExceptions, System.Net.Mail.SendMailAsyncResult._stream, System.Net.Mail.SendMailAsyncResult._toCollection, System.asyncResult, System.Net.Mail.DataCommand.BeginSend(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.ObjectModel.Collection< T >.Count, System.Net.Mail.DataCommand.EndSend(), System.Net.Mail.SmtpConnection.GetClosableStream(), System.Net.LazyAsyncResult.InvokeCallback(), and System.Net.Mail.SendMailAsyncResult.s_sendDataCompleted.
Referenced by System.Net.Mail.SendMailAsyncResult.SendToCollection().