Terraria: System.Buffers.ReadOnlySequence.GetFirstSpan
GetFirstSpan() [1/2]
ReadOnlySpan< T > System.Buffers.ReadOnlySequence< T >.GetFirstSpan () inline private
Definition at line 592 of file ReadOnlySequence.cs.
    {
        object startObject = _startObject;
        if (startObject == null)
        {
            return default(ReadOnlySpan<T>);
        }
        int startInteger = _startInteger;
        int endInteger = _endInteger;
        bool flag = startObject != _endObject;
        if ((startInteger | endInteger) >= 0)
        {
            ReadOnlySpan<T> span = ((ReadOnlySequenceSegment<T>)startObject).Memory.Span;
            if (flag)
            {
                return span.Slice(startInteger);
            }
            return span.Slice(startInteger, endInteger - startInteger);
        }
        return GetFirstSpanSlow(startObject, flag);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetFirstSpanSlow(), and System.ReadOnlySpan< T >.Slice().
Referenced by System.Buffers.SequenceReader< T >.SequenceReader().