Terraria: System.Buffers.ReadOnlySequence.Slice
Slice() [5/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (long start, SequencePosition end) inline
Definition at line 241 of file ReadOnlySequence.cs.
    {
        if (start < 0)
        {
            System.ThrowHelper.ThrowStartOrEndArgumentValidationException(start);
        }
        uint index = (uint)GetIndex(_startInteger);
        object startObject = _startObject;
        uint index2 = (uint)GetIndex(_endInteger);
        object endObject = _endObject;
        uint num = (uint)end.GetInteger();
        object obj = end.GetObject();
        if (obj == null)
        {
            obj = _startObject;
            num = index;
        }
        if (startObject == endObject)
        {
            if (!InRange(num, index, index2))
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
            }
            if (num - index < start)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(-1L);
            }
        }
        else
        {
            ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)startObject;
            ulong num2 = (ulong)(readOnlySequenceSegment.RunningIndex + index);
            ulong num3 = (ulong)(((ReadOnlySequenceSegment<T>)obj).RunningIndex + num);
            if (!InRange(num3, num2, (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + index2)))
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
            }
            if ((ulong)((long)num2 + start) > num3)
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument.start);
            }
            int num4 = readOnlySequenceSegment.Memory.Length - (int)index;
            if (num4 <= start)
            {
                if (num4 < 0)
                {
                    System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                SequencePosition start2 = SeekMultiSegment(readOnlySequenceSegment.Next, obj, (int)num, start - num4, System.ExceptionArgument.start);
                return SliceImpl(in start2, in end);
            }
        }
        SequencePosition start3 = new SequencePosition(startObject, (int)index + (int)start);
        SequencePosition end2 = new SequencePosition(obj, (int)num);
        return SliceImpl(in start3, in end2);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.SequencePosition.GetInteger(), System.SequencePosition.GetObject(), System.index, System.index2, System.Buffers.ReadOnlySequence< T >.InRange(), System.L, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.obj, System.Buffers.ReadOnlySequenceSegment< T >.RunningIndex, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().