Terraria: System.Buffers.ReadOnlySequence.GetFirstBufferSlow
GetFirstBufferSlow()
ReadOnlyMemory< T > System.Buffers.ReadOnlySequence< T >.GetFirstBufferSlow (object startObject, bool isMultiSegment) inline private
Definition at line 571 of file ReadOnlySequence.cs.
    {
        if (isMultiSegment)
        {
            System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached();
        }
        int startInteger = _startInteger;
        int endInteger = _endInteger;
        if (startInteger >= 0)
        {
            return new ReadOnlyMemory<T>((T[])startObject, startInteger, (endInteger & 0x7FFFFFFF) - startInteger);
        }
        if (typeof(T) == typeof(char) && endInteger < 0)
        {
            return (ReadOnlyMemory<T>)(object)((string)startObject).AsMemory(startInteger & 0x7FFFFFFF, endInteger - startInteger);
        }
        startInteger &= 0x7FFFFFFF;
        return ((MemoryManager<T>)startObject).Memory.Slice(startInteger, endInteger - startInteger);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._startInteger, System.Memory< T >.Slice(), and System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached().
Referenced by System.Buffers.ReadOnlySequence< T >.GetFirstBuffer().