Terraria: System.Buffers.ReadOnlySequence.Slice
Slice() [3/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (long start) inline
Definition at line 391 of file ReadOnlySequence.cs.
    {
        if (start < 0)
        {
            System.ThrowHelper.ThrowStartOrEndArgumentValidationException(start);
        }
        if (start == 0L)
        {
            return this;
        }
        SequencePosition start2 = Seek(start, System.ExceptionArgument.start);
        return SliceImpl(in start2);
    }
References System.L, System.Buffers.ReadOnlySequence< T >.Seek(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().