Terraria: System.Buffers.ReadOnlySequence.Slice
Slice() [4/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (long start, long length) inline
Definition at line 179 of file ReadOnlySequence.cs.
    {
        if (start < 0 || length < 0)
        {
            System.ThrowHelper.ThrowStartOrEndArgumentValidationException(start);
        }
        int index = GetIndex(_startInteger);
        int index2 = GetIndex(_endInteger);
        object startObject = _startObject;
        object endObject = _endObject;
        SequencePosition start2;
        SequencePosition end;
        if (startObject != endObject)
        {
            ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)startObject;
            int num = readOnlySequenceSegment.Memory.Length - index;
            if (num > start)
            {
                index += (int)start;
                start2 = new SequencePosition(startObject, index);
                end = GetEndPosition(readOnlySequenceSegment, startObject, index, endObject, index2, length);
            }
            else
            {
                if (num < 0)
                {
                    System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                start2 = SeekMultiSegment(readOnlySequenceSegment.Next, endObject, index2, start - num, System.ExceptionArgument.start);
                int integer = start2.GetInteger();
                object @object = start2.GetObject();
                if (@object != endObject)
                {
                    end = GetEndPosition((ReadOnlySequenceSegment<T>)@object, @object, integer, endObject, index2, length);
                }
                else
                {
                    if (index2 - integer < length)
                    {
                        System.ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
                    }
                    end = new SequencePosition(@object, integer + (int)length);
                }
            }
        }
        else
        {
            if (index2 - index < start)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(-1L);
            }
            index += (int)start;
            start2 = new SequencePosition(startObject, index);
            if (index2 - index < length)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
            }
            end = new SequencePosition(startObject, index + (int)length);
        }
        return SliceImpl(in start2, in end);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetEndPosition(), System.Buffers.ReadOnlySequence< T >.GetIndex(), System.SequencePosition.GetInteger(), System.SequencePosition.GetObject(), System.index, System.index2, System.L, System.length, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().
Referenced by System.Text.Json.Utf8JsonReader.CheckLiteralMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringAndValidateMultiSegment(), System.Text.Json.Utf8JsonReader.ConsumeStringNextSegment(), System.Text.Json.Utf8JsonReader.SkipOrConsumeCommentMultiSegmentWithRollback(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Buffers.ReadOnlySequence< T >.Slice(), System.Text.Json.Utf8JsonReader.TryGetDateTimeCore(), System.Text.Json.Utf8JsonReader.TryGetDateTimeOffsetCore(), System.Text.Json.Utf8JsonReader.TryGetGuidCore(), System.Text.Json.Utf8JsonReader.TryGetNumberMultiSegment(), and System.Text.Json.JsonDocument.TryParseValue().