Terraria: System.Buffers.ReadOnlySequence.GetOffset
GetOffset()
long System.Buffers.ReadOnlySequence< T >.GetOffset (SequencePosition position) inline
Definition at line 440 of file ReadOnlySequence.cs.
    {
        object obj = position.GetObject();
        bool flag = obj == null;
        BoundsCheck(in position, !flag);
        object startObject = _startObject;
        object endObject = _endObject;
        uint num = (uint)position.GetInteger();
        if (flag)
        {
            obj = _startObject;
            num = (uint)GetIndex(_startInteger);
        }
        if (startObject == endObject)
        {
            return num;
        }
        if (((ReadOnlySequenceSegment<T>)obj).Memory.Length - num < 0)
        {
            System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
        }
        ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)startObject;
        while (readOnlySequenceSegment != null && readOnlySequenceSegment != obj)
        {
            readOnlySequenceSegment = readOnlySequenceSegment.Next;
        }
        if (readOnlySequenceSegment == null)
        {
            System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
        }
        return readOnlySequenceSegment.RunningIndex + num;
    }
References System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.BoundsCheck(), System.Buffers.ReadOnlySequence< T >.GetIndex(), System.SequencePosition.GetInteger(), System.SequencePosition.GetObject(), System.Memory< T >.Length, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.obj, and System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange().