Terraria: System.Buffers.ReadOnlySequence.GetFirstSpanSlow
GetFirstSpanSlow() [1/2]
ReadOnlySpan< T > System.Buffers.ReadOnlySequence< T >.GetFirstSpanSlow (object startObject, bool isMultiSegment) inline private
Definition at line 615 of file ReadOnlySequence.cs.
    {
        if (isMultiSegment)
        {
            System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached();
        }
        int startInteger = _startInteger;
        int endInteger = _endInteger;
        if (startInteger >= 0)
        {
            return ((ReadOnlySpan<T>)(T[])startObject).Slice(startInteger, (endInteger & 0x7FFFFFFF) - startInteger);
        }
        if (typeof(T) == typeof(char) && endInteger < 0)
        {
            return ((ReadOnlyMemory<T>)(object)((string)startObject).AsMemory()).Span.Slice(startInteger & 0x7FFFFFFF, endInteger - startInteger);
        }
        startInteger &= 0x7FFFFFFF;
        return ((MemoryManager<T>)startObject).Memory.Span.Slice(startInteger, endInteger - startInteger);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._startInteger, and System.ThrowHelper.ThrowInvalidOperationException_EndPositionNotReached().
Referenced by System.Buffers.ReadOnlySequence< T >.GetFirstSpan(), and System.Buffers.ReadOnlySequence< T >.GetFirstSpan().