Terraria: System.Buffers.ReadOnlySequence.BoundsCheck
BoundsCheck() [1/2]
void System.Buffers.ReadOnlySequence< T >.BoundsCheck (in SequencePosition position, bool positionIsNotNull) inline private
Definition at line 714 of file ReadOnlySequence.cs.
    {
        uint integer = (uint)position.GetInteger();
        object startObject = _startObject;
        object endObject = _endObject;
        uint index = (uint)GetIndex(_startInteger);
        uint index2 = (uint)GetIndex(_endInteger);
        if (startObject == endObject)
        {
            if (!InRange(integer, index, index2))
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
            }
            return;
        }
        ulong start = (ulong)(((ReadOnlySequenceSegment<T>)startObject).RunningIndex + index);
        long num = 0L;
        if (positionIsNotNull)
        {
            num = ((ReadOnlySequenceSegment<T>)position.GetObject()).RunningIndex;
        }
        if (!InRange((ulong)(num + integer), start, (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + index2)))
        {
            System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
        }
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.index, System.index2, System.Buffers.ReadOnlySequence< T >.InRange(), System.L, System.start, and System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange().
Referenced by System.Buffers.ReadOnlySequence< T >.GetOffset(), System.Buffers.ReadOnlySequence< T >.Slice(), and System.Buffers.ReadOnlySequence< T >.Slice().