Terraria: System.Buffers.ReadOnlySequence.ReadOnlySequence
ReadOnlySequence() [5/5]
System.Buffers.ReadOnlySequence< T >.ReadOnlySequence (ReadOnlyMemory< T > memory) inline
Definition at line 139 of file ReadOnlySequence.cs.
    {
        ArraySegment<T> segment;
        if (MemoryMarshal.TryGetMemoryManager<T, MemoryManager<T>>(memory, out MemoryManager<T> manager, out int start, out int length))
        {
            _startObject = manager;
            _endObject = manager;
            _startInteger = ReadOnlySequence.MemoryManagerToSequenceStart(start);
            _endInteger = start + length;
        }
        else if (MemoryMarshal.TryGetArray(memory, out segment))
        {
            T[] array = segment.Array;
            int offset = segment.Offset;
            _startObject = array;
            _endObject = array;
            _startInteger = offset;
            _endInteger = ReadOnlySequence.ArrayToSequenceEnd(offset + segment.Count);
        }
        else if (typeof(T) == typeof(char))
        {
            if (!MemoryMarshal.TryGetString((ReadOnlyMemory<char>)(object)memory, out string text, out int start2, out length))
            {
                System.ThrowHelper.ThrowInvalidOperationException();
            }
            _startObject = text;
            _endObject = text;
            _startInteger = ReadOnlySequence.StringToSequenceStart(start2);
            _endInteger = ReadOnlySequence.StringToSequenceEnd(start2 + length);
        }
        else
        {
            System.ThrowHelper.ThrowInvalidOperationException();
            _startObject = null;
            _endObject = null;
            _startInteger = 0;
            _endInteger = 0;
        }
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.array, System.ArraySegment< T >.Array, System.Buffers.ReadOnlySequence< T >.ArrayToSequenceEnd(), System.ArraySegment< T >.Count, System.length, System.manager, System.Buffers.ReadOnlySequence< T >.MemoryManagerToSequenceStart(), System.offset, System.ArraySegment< T >.Offset, System.start, System.Buffers.ReadOnlySequence< T >.StringToSequenceEnd(), System.Buffers.ReadOnlySequence< T >.StringToSequenceStart(), System.text, System.ThrowHelper.ThrowInvalidOperationException(), and System.Runtime.InteropServices.MemoryMarshal.TryGetString().