Terraria: System.Buffers.ReadOnlySequence.Slice
Slice() [8/9]
ReadOnlySequence< T > System.Buffers.ReadOnlySequence< T >.Slice (SequencePosition start, long length) inline
Definition at line 298 of file ReadOnlySequence.cs.
    {
        uint index = (uint)GetIndex(_startInteger);
        object startObject = _startObject;
        uint index2 = (uint)GetIndex(_endInteger);
        object endObject = _endObject;
        uint num = (uint)start.GetInteger();
        object obj = start.GetObject();
        if (obj == null)
        {
            num = index;
            obj = _startObject;
        }
        if (startObject == endObject)
        {
            if (!InRange(num, index, index2))
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
            }
            if (length < 0)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
            }
            if (index2 - num < length)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
            }
        }
        else
        {
            ReadOnlySequenceSegment<T> readOnlySequenceSegment = (ReadOnlySequenceSegment<T>)obj;
            ulong num2 = (ulong)(readOnlySequenceSegment.RunningIndex + num);
            ulong start2 = (ulong)(((ReadOnlySequenceSegment<T>)startObject).RunningIndex + index);
            ulong num3 = (ulong)(((ReadOnlySequenceSegment<T>)endObject).RunningIndex + index2);
            if (!InRange(num2, start2, num3))
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
            }
            if (length < 0)
            {
                System.ThrowHelper.ThrowStartOrEndArgumentValidationException(0L);
            }
            if ((ulong)((long)num2 + length) > num3)
            {
                System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument.length);
            }
            int num4 = readOnlySequenceSegment.Memory.Length - (int)num;
            if (num4 < length)
            {
                if (num4 < 0)
                {
                    System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange();
                }
                SequencePosition end = SeekMultiSegment(readOnlySequenceSegment.Next, endObject, (int)index2, length - num4, System.ExceptionArgument.length);
                return SliceImpl(in start, in end);
            }
        }
        SequencePosition start3 = new SequencePosition(obj, (int)num);
        SequencePosition end2 = new SequencePosition(obj, (int)num + (int)length);
        return SliceImpl(in start3, in end2);
    }
References System.Buffers.ReadOnlySequence< T >._endInteger, System.Buffers.ReadOnlySequence< T >._endObject, System.Buffers.ReadOnlySequence< T >._startInteger, System.Buffers.ReadOnlySequence< T >._startObject, System.Buffers.ReadOnlySequence< T >.GetIndex(), System.index, System.index2, System.Buffers.ReadOnlySequence< T >.InRange(), System.L, System.length, System.Buffers.ReadOnlySequenceSegment< T >.Next, System.obj, System.Buffers.ReadOnlySequenceSegment< T >.RunningIndex, System.Buffers.ReadOnlySequence< T >.SeekMultiSegment(), System.Buffers.ReadOnlySequence< T >.SliceImpl(), System.start, System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange(), and System.ThrowHelper.ThrowStartOrEndArgumentValidationException().