Terraria: Terraria.WorldBuilding.Actions.Chain
Chain()
static GenAction Terraria.WorldBuilding.Actions.Chain (params GenAction[] actions) inline static
Definition at line 470 of file Actions.cs.
    {
        for (int i = 0; i < actions.Length - 1; i++)
        {
            actions[i].NextAction = actions[i + 1];
        }
        return actions[0];
    }
Referenced by Terraria.GameContent.Biomes.CaveHouse.DesertHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.GraniteHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.IceHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.JungleHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.MarbleHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.MushroomHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.WoodHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetRoomSolidPrecentage(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.CorruptionPitBiome.Place(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.Biomes.ThinIceBiome.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.AnthillEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.LarvaHoleEntrance.PlaceAt(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceEmptyRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlacePlatforms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceStairs(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams(), and Terraria.WorldGen.smCallBack().