Terraria: System.Reflection.Emit.SymbolType.SymbolType
SymbolType()
System.Reflection.Emit.SymbolType.SymbolType (TypeKind typeKind) inline package
Definition at line 228 of file SymbolType.cs.
    {
        m_typeKind = typeKind;
        m_iaLowerBound = new int[4];
        m_iaUpperBound = new int[4];
    }
References System.Reflection.Emit.SymbolType.m_iaLowerBound, System.Reflection.Emit.SymbolType.m_iaUpperBound, and System.Reflection.Emit.SymbolType.m_typeKind.
Referenced by System.Reflection.Emit.SymbolType.FormCompoundType(), System.Reflection.Emit.SymbolType.GetAttributeFlagsImpl(), and System.Reflection.Emit.SymbolType.MakeArrayType().