Terraria: System.Reflection.Emit.SymbolType.FormCompoundType
FormCompoundType()
static Type System.Reflection.Emit.SymbolType.FormCompoundType (string format, Type baseType, int curIndex) inline static package
Definition at line 114 of file SymbolType.cs.
    {
        if (format == null || curIndex == format.Length)
        {
            return baseType;
        }
        if (format[curIndex] == '&')
        {
            SymbolType symbolType = new SymbolType(TypeKind.IsByRef);
            symbolType.SetFormat(format, curIndex, 1);
            curIndex++;
            if (curIndex != format.Length)
            {
                throw new ArgumentException(SR.Argument_BadSigFormat);
            }
            symbolType.SetElementType(baseType);
            return symbolType;
        }
        if (format[curIndex] == '[')
        {
            SymbolType symbolType = new SymbolType(TypeKind.IsArray);
            int num = curIndex;
            curIndex++;
            int num2 = 0;
            int num3 = -1;
            while (format[curIndex] != ']')
            {
                if (format[curIndex] == '*')
                {
                    symbolType.m_isSzArray = false;
                    curIndex++;
                }
                if ((format[curIndex] >= '0' && format[curIndex] <= '9') || format[curIndex] == '-')
                {
                    bool flag = false;
                    if (format[curIndex] == '-')
                    {
                        flag = true;
                        curIndex++;
                    }
                    while (format[curIndex] >= '0' && format[curIndex] <= '9')
                    {
                        num2 *= 10;
                        num2 += format[curIndex] - 48;
                        curIndex++;
                    }
                    if (flag)
                    {
                        num2 = -num2;
                    }
                    num3 = num2 - 1;
                }
                if (format[curIndex] == '.')
                {
                    curIndex++;
                    if (format[curIndex] != '.')
                    {
                        throw new ArgumentException(SR.Argument_BadSigFormat);
                    }
                    curIndex++;
                    if ((format[curIndex] >= '0' && format[curIndex] <= '9') || format[curIndex] == '-')
                    {
                        bool flag2 = false;
                        num3 = 0;
                        if (format[curIndex] == '-')
{
                            flag2 = true;
                            curIndex++;
                        }
                        while (format[curIndex] >= '0' && format[curIndex] <= '9')
{
                            num3 *= 10;
                            num3 += format[curIndex] - 48;
                            curIndex++;
                        }
                        if (flag2)
{
                            num3 = -num3;
                        }
                        if (num3 < num2)
{
                            throw new ArgumentException(SR.Argument_BadSigFormat);
                        }
                    }
                }
                if (format[curIndex] == ',')
                {
                    curIndex++;
                    symbolType.SetBounds(num2, num3);
                    num2 = 0;
                    num3 = -1;
                }
                else if (format[curIndex] != ']')
                {
                    throw new ArgumentException(SR.Argument_BadSigFormat);
                }
            }
            symbolType.SetBounds(num2, num3);
            curIndex++;
            symbolType.SetFormat(format, num, curIndex - num);
            symbolType.SetElementType(baseType);
            return FormCompoundType(format, symbolType, curIndex);
        }
        if (format[curIndex] == '*')
        {
            SymbolType symbolType = new SymbolType(TypeKind.IsPointer);
            symbolType.SetFormat(format, curIndex, 1);
            curIndex++;
            symbolType.SetElementType(baseType);
            return FormCompoundType(format, symbolType, curIndex);
        }
        return null;
    }
References System.Reflection.Emit.SymbolType.SymbolType(), System.SR.Argument_BadSigFormat, System.format, System.Reflection.Emit.SymbolType.FormCompoundType(), System.Reflection.Emit.SymbolType.SetBounds(), System.Reflection.Emit.SymbolType.SetElementType(), and System.Reflection.Emit.SymbolType.SetFormat().
Referenced by System.Reflection.Emit.SymbolType.FormCompoundType(), System.Reflection.Emit.ModuleBuilder.GetType(), System.Reflection.Emit.EnumBuilder.MakeArrayType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakeArrayType(), System.Reflection.Emit.SymbolType.MakeArrayType(), System.Reflection.Emit.TypeBuilder.MakeArrayType(), System.Reflection.Emit.TypeBuilderInstantiation.MakeArrayType(), System.Reflection.Emit.EnumBuilder.MakeArrayType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakeArrayType(), System.Reflection.Emit.SymbolType.MakeArrayType(), System.Reflection.Emit.TypeBuilder.MakeArrayType(), System.Reflection.Emit.TypeBuilderInstantiation.MakeArrayType(), System.Reflection.Emit.EnumBuilder.MakeByRefType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakeByRefType(), System.Reflection.Emit.SymbolType.MakeByRefType(), System.Reflection.Emit.TypeBuilder.MakeByRefType(), System.Reflection.Emit.TypeBuilderInstantiation.MakeByRefType(), System.Reflection.Emit.EnumBuilder.MakePointerType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakePointerType(), System.Reflection.Emit.SymbolType.MakePointerType(), System.Reflection.Emit.TypeBuilder.MakePointerType(), and System.Reflection.Emit.TypeBuilderInstantiation.MakePointerType().