Terraria: Terraria.IO.WorldFile.DoRollingBackups
DoRollingBackups()
static void Terraria.IO.WorldFile.DoRollingBackups (string backupWorldWritePath) inline static private
Definition at line 890 of file WorldFile.cs.
    {
        if (Main.WorldRollingBackupsCountToKeep <= 1)
        {
            return;
        }
        int num = Main.WorldRollingBackupsCountToKeep;
        if (num > 9)
        {
            num = 9;
        }
        int num2 = 1;
        for (int i = 1; i < num; i++)
        {
            string path = backupWorldWritePath + i;
            if (i == 1)
            {
                path = backupWorldWritePath;
            }
            if (!FileUtilities.Exists(path, cloud: false))
            {
                break;
            }
            num2 = i + 1;
        }
        for (int num3 = num2 - 1; num3 > 0; num3--)
        {
            string text = backupWorldWritePath + num3;
            if (num3 == 1)
            {
                text = backupWorldWritePath;
            }
            string destination = backupWorldWritePath + (num3 + 1);
            if (FileUtilities.Exists(text, cloud: false))
            {
                FileUtilities.Move(text, destination, cloud: false, overwrite: true, forceDeleteSourceFile: true);
            }
        }
    }
References System.destination, Terraria.Utilities.FileUtilities.Exists(), Terraria.Utilities.FileUtilities.Move(), System.text, and Terraria.Main.WorldRollingBackupsCountToKeep.
Referenced by Terraria.IO.WorldFile.InternalSaveWorld().