Terraria: Terraria.IO.WorldFile.SaveWorld
SaveWorld() [2/2]
static void Terraria.IO.WorldFile.SaveWorld (bool useCloudSaving, bool resetTime = false) inline static
Definition at line 793 of file WorldFile.cs.
    {
        if (useCloudSaving && SocialAPI.Cloud == null)
        {
            return;
        }
        if (Main.worldName == "")
        {
            Main.worldName = "World";
        }
        while (WorldGen.IsGeneratingHardMode)
        {
            Main.statusText = Lang.gen[48].Value;
        }
        if (!Monitor.TryEnter(IOLock))
        {
            return;
        }
        try
        {
            FileUtilities.ProtectedInvoke(delegate
            {
                InternalSaveWorld(useCloudSaving, resetTime);
            });
        }
        finally
        {
            Monitor.Exit(IOLock);
        }
    }
References Terraria.Social.SocialAPI.Cloud, System.Threading.Monitor.Exit(), Terraria.Lang.gen, Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.IO.WorldFile.IOLock, Terraria.WorldGen.IsGeneratingHardMode, Terraria.Utilities.FileUtilities.ProtectedInvoke(), System.Threading.Monitor.TryEnter(), and Terraria.Main.worldName.