Terraria: System.Security.Cryptography.X509Certificates.CertificateRequest.Create
Create() [2/4]
X509Certificate2 System.Security.Cryptography.X509Certificates.CertificateRequest.Create (X500DistinguishedName issuerName, X509SignatureGenerator generator, DateTimeOffset notBefore, DateTimeOffset notAfter, ReadOnlySpan< byte > serialNumber) inline
Definition at line 286 of file CertificateRequest.cs.
    {
        if (issuerName == null)
        {
            throw new ArgumentNullException("issuerName");
        }
        if (generator == null)
        {
            throw new ArgumentNullException("generator");
        }
        if (notAfter < notBefore)
        {
            throw new ArgumentException(System.SR.Cryptography_CertReq_DatesReversed);
        }
        if (serialNumber == null || serialNumber.Length < 1)
        {
            throw new ArgumentException(System.SR.Arg_EmptyOrNullArray, "serialNumber");
        }
        byte[] signatureAlgorithmIdentifier = generator.GetSignatureAlgorithmIdentifier(HashAlgorithm);
        System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn signatureAlgorithm = System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(signatureAlgorithmIdentifier, AsnEncodingRules.DER);
        if (signatureAlgorithm.Parameters.HasValue)
        {
            Internal.Cryptography.Helpers.ValidateDer(signatureAlgorithm.Parameters.Value);
        }
        ArraySegment<byte> arraySegment = NormalizeSerialNumber(serialNumber);
        TbsCertificateAsn tbsCertificateAsn = default(TbsCertificateAsn);
        tbsCertificateAsn.Version = 2;
        tbsCertificateAsn.SerialNumber = arraySegment;
        tbsCertificateAsn.SignatureAlgorithm = signatureAlgorithm;
        tbsCertificateAsn.Issuer = issuerName.RawData;
        tbsCertificateAsn.SubjectPublicKeyInfo = new System.Security.Cryptography.Asn1.SubjectPublicKeyInfoAsn
        {
            Algorithm = new System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn
            {
                Algorithm = PublicKey.Oid.Value,
                Parameters = PublicKey.EncodedParameters.RawData
            },
            SubjectPublicKey = PublicKey.EncodedKeyValue.RawData
        };
        tbsCertificateAsn.Validity = new ValidityAsn(notBefore, notAfter);
        tbsCertificateAsn.Subject = SubjectName.RawData;
        TbsCertificateAsn tbsCertificate = tbsCertificateAsn;
        if (CertificateExtensions.Count > 0)
        {
            HashSet<string> hashSet = new HashSet<string>(CertificateExtensions.Count);
            List<X509ExtensionAsn> list = new List<X509ExtensionAsn>(CertificateExtensions.Count);
            foreach (X509Extension certificateExtension in CertificateExtensions)
            {
                if (certificateExtension != null)
                {
                    if (!hashSet.Add(certificateExtension.Oid.Value))
                    {
                        throw new InvalidOperationException(System.SR.Format(System.SR.Cryptography_CertReq_DuplicateExtension, certificateExtension.Oid.Value));
                    }
                    list.Add(new X509ExtensionAsn(certificateExtension));
                }
            }
            if (list.Count > 0)
            {
                tbsCertificate.Extensions = list.ToArray();
            }
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        tbsCertificate.Encode(asnWriter);
        byte[] data = asnWriter.Encode();
        asnWriter.Reset();
        CertificateAsn certificateAsn = default(CertificateAsn);
        certificateAsn.TbsCertificate = tbsCertificate;
        certificateAsn.SignatureAlgorithm = signatureAlgorithm;
        certificateAsn.SignatureValue = generator.SignData(data, HashAlgorithm);
        CertificateAsn certificateAsn2 = certificateAsn;
        certificateAsn2.Encode(asnWriter);
        X509Certificate2 result = new X509Certificate2(asnWriter.Encode());
        System.Security.Cryptography.CryptoPool.Return(arraySegment);
        return result;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.SR.Arg_EmptyOrNullArray, System.Security.Cryptography.X509Certificates.CertificateRequest.CertificateExtensions, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Cryptography_CertReq_DatesReversed, System.SR.Cryptography_CertReq_DuplicateExtension, System.Security.Cryptography.Asn1.AlgorithmIdentifierAsn.Decode(), System.SR.Format(), System.list, System.Security.Cryptography.X509Certificates.CertificateRequest.NormalizeSerialNumber(), System.Security.Cryptography.X509Certificates.PublicKey.Oid, System.Security.Cryptography.AsnEncodedData.RawData, System.Security.Cryptography.CryptoPool.Return(), System.Security.Cryptography.X509Certificates.CertificateRequest.SubjectName, Internal.Cryptography.Helpers.ValidateDer(), and System.Security.Cryptography.Oid.Value.