Terraria: System.Security.Cryptography.X509Certificates.CertificateRequest.Create
Create() [3/4]
X509Certificate2 System.Security.Cryptography.X509Certificates.CertificateRequest.Create (X509Certificate2 issuerCertificate, DateTimeOffset notBefore, DateTimeOffset notAfter, byte[] serialNumber) inline
Definition at line 193 of file CertificateRequest.cs.
    {
        return Create(issuerCertificate, notBefore, notAfter, new ReadOnlySpan<byte>(serialNumber));
    }
References System.Security.Cryptography.X509Certificates.CertificateRequest.Create().
Referenced by System.Security.Cryptography.X509Certificates.CertificateRequest.Create(), System.Security.Cryptography.X509Certificates.CertificateRequest.Create(), System.Security.Cryptography.X509Certificates.CertificateRequest.Create(), and System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned().