Terraria: System.Security.Cryptography.X509Certificates.CertificateRequest.NormalizeSerialNumber
NormalizeSerialNumber()
ArraySegment< byte > System.Security.Cryptography.X509Certificates.CertificateRequest.NormalizeSerialNumber (ReadOnlySpan< byte > serialNumber) inline private
Definition at line 363 of file CertificateRequest.cs.
    {
        byte[] array;
        if (serialNumber[0] >= 128)
        {
            array = System.Security.Cryptography.CryptoPool.Rent(serialNumber.Length + 1);
            array[0] = 0;
            serialNumber.CopyTo(array.AsSpan(1));
            return new ArraySegment<byte>(array, 0, serialNumber.Length + 1);
        }
        int i;
        for (i = 0; i < serialNumber.Length - 1 && serialNumber[i] == 0 && serialNumber[i + 1] < 128; i++)
        {
        }
        int num = serialNumber.Length - i;
        array = System.Security.Cryptography.CryptoPool.Rent(num);
        serialNumber.Slice(i).CopyTo(array);
        return new ArraySegment<byte>(array, 0, num);
    }
References System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), and System.Security.Cryptography.CryptoPool.Rent().
Referenced by System.Security.Cryptography.X509Certificates.CertificateRequest.Create().