Terraria: StringReaderWrapExtension.ReadUntilBreakable
ReadUntilBreakable()
static string StringReaderWrapExtension.ReadUntilBreakable (this StringReader reader, CultureInfo culture) inline static package
     {
         StringBuilder stringBuilder = new StringBuilder();
         char c = (char)reader.Peek();
         WrapScanMode wrapScanMode = WrapScanMode.None;
         while (reader.Peek() > 0)
         {
             if (IsIgnoredCharacter((char)reader.Peek()))
             {
                 reader.Read();
                 continue;
             }
             char previousChar = c;
             c = (char)reader.Peek();
             WrapScanMode wrapScanMode2 = wrapScanMode;
             wrapScanMode = GetModeForCharacter(c);
             if (!stringBuilder.IsEmpty() && wrapScanMode2 != wrapScanMode)
             {
                 return stringBuilder.ToString();
             }
             if (stringBuilder.IsEmpty())
             {
                 stringBuilder.Append((char)reader.Read());
                 continue;
             }
             if (CanBreakBetween(previousChar, c, culture))
             {
                 return stringBuilder.ToString();
             }
             stringBuilder.Append((char)reader.Read());
         }
         return stringBuilder.ToString();
     }
References CanBreakBetween(), GetModeForCharacter(), and IsIgnoredCharacter().