Terraria: System.Reflection.Metadata.Ecma335.PermissionSetEncoder.AddPermission
AddPermission() [2/2]
PermissionSetEncoder System.Reflection.Metadata.Ecma335.PermissionSetEncoder.AddPermission (string typeName, ImmutableArray< byte > encodedArguments) inline
Definition at line 14 of file PermissionSetEncoder.cs.
    {
        if (typeName == null)
        {
            Throw.ArgumentNull("typeName");
        }
        if (encodedArguments.IsDefault)
        {
            Throw.ArgumentNull("encodedArguments");
        }
        if (encodedArguments.Length > 536870911)
        {
            Throw.BlobTooLarge("encodedArguments");
        }
        Builder.WriteSerializedString(typeName);
        Builder.WriteCompressedInteger(encodedArguments.Length);
        Builder.WriteBytes(encodedArguments);
        return this;
    }
References System.Reflection.Throw.ArgumentNull(), System.Reflection.Throw.BlobTooLarge(), System.Reflection.Metadata.Ecma335.PermissionSetEncoder.Builder, System.Collections.Immutable.ImmutableArray< T >.IsDefault, System.Collections.Immutable.ImmutableArray< T >.Length, System.Reflection.Metadata.BlobBuilder.WriteBytes(), System.Reflection.Metadata.BlobBuilder.WriteCompressedInteger(), and System.Reflection.Metadata.BlobBuilder.WriteSerializedString().