Terraria: System.Transactions.TransactionsEtwProvider.ExceptionConsumed
ExceptionConsumed() [2/2]
void System.Transactions.TransactionsEtwProvider.ExceptionConsumed (TraceSourceType traceSource, Exception exception) inline package
Definition at line 577 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Verbose, EventKeywords.All))
        {
            if (traceSource == TraceSourceType.TraceSourceBase)
            {
                ExceptionConsumedBase(exception.ToString());
            }
            else
            {
                ExceptionConsumedLtm(exception.ToString());
            }
        }
    }
References System.exception, System.Transactions.TransactionsEtwProvider.ExceptionConsumedBase(), System.Transactions.TransactionsEtwProvider.ExceptionConsumedLtm(), and System.Diagnostics.Tracing.EventSource.IsEnabled().
Referenced by System.Transactions.TransactionStateDelegatedBase.EnterState(), System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(), System.Transactions.TransactionStatePromoted.EnterState(), System.Transactions.TransactionStatePromotedP0Wave.Phase0VolatilePrepareDone(), System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome(), System.Transactions.TransactionScope.Timeout(), and System.Transactions.TransactionStatePromotedBase.Timeout().