Terraria: System.Transactions.TransactionsEtwProvider.MethodEnter
MethodEnter() [2/2]
void System.Transactions.TransactionsEtwProvider.MethodEnter (TraceSourceType traceSource, object thisOrContextObject, [CallerMemberName] string methodname = null) inline package
Definition at line 455 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Verbose, EventKeywords.All))
        {
            switch (traceSource)
            {
            case TraceSourceType.TraceSourceLtm:
                MethodEnterTraceLtm(IdOf(thisOrContextObject), methodname);
                break;
            case TraceSourceType.TraceSourceBase:
                MethodEnterTraceBase(IdOf(thisOrContextObject), methodname);
                break;
            case TraceSourceType.TraceSourceDistributed:
                MethodEnterTraceDistributed(IdOf(thisOrContextObject), methodname);
                break;
            }
        }
    }
References System.Transactions.TransactionsEtwProvider.IdOf(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceBase(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceDistributed(), and System.Transactions.TransactionsEtwProvider.MethodEnterTraceLtm().
Referenced by System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Transactions.CommittableTransaction.BeginCommit(), System.Transactions.CommittableTransaction.Commit(), System.Transactions.SinglePhaseEnlistment.Committed(), System.Transactions.DependentTransaction.Complete(), System.Transactions.TransactionScope.Complete(), System.Transactions.TransactionScope.Dispose(), System.Transactions.Enlistment.Done(), System.Transactions.CommittableTransaction.EndCommit(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Transactions.TransactionInterop.GetDtcTransaction(), System.Transactions.TransactionInterop.GetExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromDtcTransaction(), System.Transactions.TransactionInterop.GetTransactionFromExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetWhereabouts(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.CommittableTransaction.InternalDispose(), System.Transactions.PreparingEnlistment.Prepared(), System.Transactions.TransactionManager.RecoveryComplete(), System.Transactions.PreparingEnlistment.RecoveryInformation(), and System.Transactions.TransactionManager.Reenlist().