Terraria: System.Transactions.TransactionsEtwProvider.EnlistmentStatus
EnlistmentStatus() [2/2]
void System.Transactions.TransactionsEtwProvider.EnlistmentStatus (InternalEnlistment enlistment, NotificationCall notificationCall) inline package
Definition at line 294 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Verbose, EventKeywords.All))
        {
            if (enlistment != null && enlistment.EnlistmentTraceId.EnlistmentIdentifier != 0)
            {
                EnlistmentStatus(enlistment.EnlistmentTraceId.EnlistmentIdentifier, notificationCall.ToString());
            }
            else
            {
                EnlistmentStatus(0, notificationCall.ToString());
            }
        }
    }
References System.Transactions.EnlistmentTraceIdentifier.EnlistmentIdentifier, System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Transactions.InternalEnlistment.EnlistmentTraceId, and System.Diagnostics.Tracing.EventSource.IsEnabled().
Referenced by System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Transactions.DurableEnlistmentAborting.EnterState(), System.Transactions.DurableEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentAborting.EnterState(), System.Transactions.VolatileEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentInDoubt.EnterState(), System.Transactions.VolatileEnlistmentPreparing.EnterState(), System.Transactions.VolatileEnlistmentSPC.EnterState(), System.Transactions.TransactionStateDelegatedAborting.EnterState(), System.Transactions.TransactionStateDelegatedBase.EnterState(), System.Transactions.TransactionStateDelegatedCommitting.EnterState(), System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(), and System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnterState().