Terraria: System.Transactions.TransactionsEtwProvider.MethodExit
MethodExit() [1/2]
void System.Transactions.TransactionsEtwProvider.MethodExit (TraceSourceType traceSource, [CallerMemberName] string methodname = null) inline package
Definition at line 536 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Verbose, EventKeywords.All))
        {
            switch (traceSource)
            {
            case TraceSourceType.TraceSourceLtm:
                MethodExitTraceLtm(string.Empty, methodname);
                break;
            case TraceSourceType.TraceSourceBase:
                MethodExitTraceBase(string.Empty, methodname);
                break;
            case TraceSourceType.TraceSourceDistributed:
                MethodExitTraceDistributed(string.Empty, methodname);
                break;
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.MethodExitTraceBase(), System.Transactions.TransactionsEtwProvider.MethodExitTraceDistributed(), and System.Transactions.TransactionsEtwProvider.MethodExitTraceLtm().