Terraria: Terraria.Initializers.LaunchInitializer.TryParameter
TryParameter()
static string Terraria.Initializers.LaunchInitializer.TryParameter (params string[] keys) inline static private
Definition at line 198 of file LaunchInitializer.cs.
    {
        for (int i = 0; i < keys.Length; i++)
        {
            if (Program.LaunchParameters.TryGetValue(keys[i], out var value))
            {
                if (value == null)
                {
                    return "";
                }
                return value;
            }
        }
        return null;
    }
References System.keys, Terraria.Program.LaunchParameters, and System.value.
Referenced by Terraria.Initializers.LaunchInitializer.LoadClientParameters(), Terraria.Initializers.LaunchInitializer.LoadServerParameters(), and Terraria.Initializers.LaunchInitializer.LoadSharedParameters().