Terraria: System.Transactions.TransactionsEtwProvider.SetActivityId
SetActivityId()
void System.Transactions.TransactionsEtwProvider.SetActivityId (string str) inline private
Definition at line 889 of file TransactionsEtwProvider.cs.
    {
        Guid result = Guid.Empty;
        if (str.Contains('-'))
        {
            if (str.Length >= 36)
            {
                Guid.TryParse(str.AsSpan(0, 36), out result);
            }
        }
        else if (str.Length >= 32)
        {
            Guid.TryParse(str.AsSpan(0, 32), out result);
        }
        EventSource.SetCurrentThreadActivityId(result);
    }
References System.Guid.Empty, System.Diagnostics.Tracing.EventSource.SetCurrentThreadActivityId(), System.str, and System.Guid.TryParse().
Referenced by System.Transactions.TransactionsEtwProvider.ConfiguredDefaultTimeoutAdjustedTrace(), System.Transactions.TransactionsEtwProvider.EnlistmentAborted(), System.Transactions.TransactionsEtwProvider.EnlistmentCommitted(), System.Transactions.TransactionsEtwProvider.EnlistmentDone(), System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback(), System.Transactions.TransactionsEtwProvider.EnlistmentInDoubt(), System.Transactions.TransactionsEtwProvider.EnlistmentPrepared(), System.Transactions.TransactionsEtwProvider.EnlistmentStatus(), System.Transactions.TransactionsEtwProvider.ExceptionConsumedBase(), System.Transactions.TransactionsEtwProvider.ExceptionConsumedLtm(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceBase(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceDistributed(), System.Transactions.TransactionsEtwProvider.MethodEnterTraceLtm(), System.Transactions.TransactionsEtwProvider.MethodExitTraceBase(), System.Transactions.TransactionsEtwProvider.MethodExitTraceDistributed(), System.Transactions.TransactionsEtwProvider.MethodExitTraceLtm(), System.Transactions.TransactionsEtwProvider.TransactionAborted(), System.Transactions.TransactionsEtwProvider.TransactionCloneCreate(), System.Transactions.TransactionsEtwProvider.TransactionCommit(), System.Transactions.TransactionsEtwProvider.TransactionCommitted(), System.Transactions.TransactionsEtwProvider.TransactionCreated(), System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete(), System.Transactions.TransactionsEtwProvider.TransactionExceptionBase(), System.Transactions.TransactionsEtwProvider.TransactionExceptionLtm(), System.Transactions.TransactionsEtwProvider.TransactionInDoubt(), System.Transactions.TransactionsEtwProvider.TransactionInvalidOperation(), System.Transactions.TransactionsEtwProvider.TransactionManagerRecoveryComplete(), System.Transactions.TransactionsEtwProvider.TransactionManagerReenlistTrace(), System.Transactions.TransactionsEtwProvider.TransactionPromoted(), System.Transactions.TransactionsEtwProvider.TransactionRollback(), System.Transactions.TransactionsEtwProvider.TransactionScopeCreated(), System.Transactions.TransactionsEtwProvider.TransactionScopeCurrentChanged(), System.Transactions.TransactionsEtwProvider.TransactionScopeDisposed(), System.Transactions.TransactionsEtwProvider.TransactionScopeIncomplete(), System.Transactions.TransactionsEtwProvider.TransactionScopeInternalErrorTrace(), System.Transactions.TransactionsEtwProvider.TransactionScopeNestedIncorrectly(), System.Transactions.TransactionsEtwProvider.TransactionScopeTimeout(), System.Transactions.TransactionsEtwProvider.TransactionstateEnlist(), and System.Transactions.TransactionsEtwProvider.TransactionTimeout().