Terraria: System.Transactions.TransactionsEtwProvider.Log
Log
readonly TransactionsEtwProvider System.Transactions.TransactionsEtwProvider.Log = new TransactionsEtwProvider() static package
Definition at line 101 of file TransactionsEtwProvider.cs.
Referenced by System.Transactions.CommittableTransaction.CommittableTransaction(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.TransactionScope.TransactionScope(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Transactions.SinglePhaseEnlistment.Aborted(), System.Transactions.CommittableTransaction.BeginCommit(), System.Transactions.TransactionState.ChangeStateAbortedDuringPromotion(), System.Transactions.TransactionState.ChangeStatePromotedAborted(), System.Transactions.TransactionState.ChangeStatePromotedCommitted(), System.Transactions.TransactionState.ChangeStateTransactionAborted(), System.Transactions.TransactionState.ChangeStateTransactionCommitted(), System.Transactions.Transaction.Clone(), System.Transactions.CommittableTransaction.Commit(), System.Transactions.SinglePhaseEnlistment.Committed(), System.Transactions.DependentTransaction.Complete(), System.Transactions.TransactionScope.Complete(), System.Transactions.TransactionAbortedException.Create(), System.Transactions.TransactionException.Create(), System.Transactions.TransactionException.Create(), System.Transactions.TransactionInDoubtException.Create(), System.Transactions.TransactionException.CreateEnlistmentStateException(), System.Transactions.TransactionException.CreateInvalidOperationException(), System.Transactions.TransactionException.CreateTransactionCompletedException(), System.Transactions.Transaction.DependentClone(), System.Transactions.TransactionScope.Dispose(), System.Transactions.Enlistment.Done(), System.Transactions.CommittableTransaction.EndCommit(), System.Transactions.Transaction.EnlistDurable(), System.Transactions.Transaction.EnlistDurable(), System.Transactions.EnlistableStates.EnlistDurable(), System.Transactions.TransactionStateActive.EnlistPromotableSinglePhase(), System.Transactions.TransactionStatePhase0.EnlistPromotableSinglePhase(), System.Transactions.Transaction.EnlistPromotableSinglePhase(), System.Transactions.Transaction.EnlistVolatile(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), System.Transactions.Transaction.EnlistVolatile(), System.Transactions.DurableEnlistmentAborting.EnterState(), System.Transactions.DurableEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentAborting.EnterState(), System.Transactions.VolatileEnlistmentCommitting.EnterState(), System.Transactions.VolatileEnlistmentInDoubt.EnterState(), System.Transactions.VolatileEnlistmentPreparing.EnterState(), System.Transactions.VolatileEnlistmentSPC.EnterState(), System.Transactions.TransactionStateAborted.EnterState(), System.Transactions.TransactionStateCommitted.EnterState(), System.Transactions.TransactionStateDelegatedAborting.EnterState(), System.Transactions.TransactionStateDelegatedBase.EnterState(), System.Transactions.TransactionStateDelegatedCommitting.EnterState(), System.Transactions.TransactionStateDelegatedNonMSDTC.EnterState(), System.Transactions.TransactionStateInDoubt.EnterState(), System.Transactions.TransactionStatePromoted.EnterState(), System.Transactions.TransactionStatePromotedAborted.EnterState(), System.Transactions.TransactionStatePromotedCommitted.EnterState(), System.Transactions.TransactionStatePromotedIndoubt.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCAborted.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCCommitted.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCIndoubt.EnterState(), System.Transactions.TransactionStatePromotedNonMSDTCSinglePhaseCommit.EnterState(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Transactions.PreparingEnlistment.ForceRollback(), System.Transactions.TransactionInterop.GetDtcTransaction(), System.Transactions.TransactionInterop.GetExportCookie(), System.Transactions.Transaction.GetPromotedToken(), System.Transactions.TransactionInterop.GetTransactionFromDtcTransaction(), System.Transactions.TransactionInterop.GetTransactionFromExportCookie(), System.Transactions.TransactionInterop.GetTransactionFromTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetTransmitterPropagationToken(), System.Transactions.TransactionInterop.GetWhereabouts(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.SinglePhaseEnlistment.InDoubt(), System.Transactions.TransactionState.InDoubtFromEnlistment(), System.Transactions.TransactionScope.Initialize(), System.Transactions.Transaction.InternalClone(), System.Transactions.CommittableTransaction.InternalDispose(), System.Transactions.Transaction.InternalDispose(), System.Transactions.TransactionScope.InternalDispose(), System.Transactions.TransactionStatePromotedP0Wave.Phase0VolatilePrepareDone(), System.Transactions.PreparingEnlistment.Prepared(), System.Transactions.Transaction.PromoteAndEnlistDurable(), System.Transactions.TransactionStatePromoted.PromoteEnlistmentsAndOutcome(), System.Transactions.TransactionManager.RecoveryComplete(), System.Transactions.PreparingEnlistment.RecoveryInformation(), System.Transactions.TransactionManager.Reenlist(), System.Transactions.TransactionState.RestartCommitIfNeeded(), System.Transactions.Transaction.Rollback(), System.Transactions.Transaction.Rollback(), System.Transactions.Transaction.SetDistributedTransactionIdentifier(), System.Transactions.TransactionScope.Timeout(), System.Transactions.EnlistableStates.Timeout(), System.Transactions.TransactionStatePromotedBase.Timeout(), System.Transactions.TransactionStatePromotedNonMSDTCBase.Timeout(), System.Transactions.TransactionStateVolatilePhase1.Timeout(), and System.Transactions.TransactionScope.TimerCallback().