Terraria: System.Transactions.TransactionsEtwProvider.TransactionstateEnlist
TransactionstateEnlist() [1/2]
void System.Transactions.TransactionsEtwProvider.TransactionstateEnlist (EnlistmentTraceIdentifier enlistmentID, EnlistmentType enlistmentType, EnlistmentOptions enlistmentOption) inline package
Definition at line 803 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Informational, EventKeywords.All))
        {
            if (enlistmentID.EnlistmentIdentifier != 0)
            {
                TransactionstateEnlist(enlistmentID.EnlistmentIdentifier.ToString(), enlistmentType.ToString(), enlistmentOption.ToString());
            }
            else
            {
                TransactionstateEnlist(string.Empty, enlistmentType.ToString(), enlistmentOption.ToString());
            }
        }
    }
References System.Transactions.EnlistmentTraceIdentifier.EnlistmentIdentifier, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Empty.ToString(), and System.Transactions.TransactionsEtwProvider.TransactionstateEnlist().
Referenced by System.Transactions.EnlistableStates.EnlistDurable(), System.Transactions.TransactionStateActive.EnlistPromotableSinglePhase(), System.Transactions.TransactionStatePhase0.EnlistPromotableSinglePhase(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), System.Transactions.TransactionStateActive.EnlistVolatile(), System.Transactions.TransactionStatePhase0.EnlistVolatile(), System.Transactions.TransactionStatePromotedNonMSDTCBase.EnlistVolatile(), and System.Transactions.TransactionsEtwProvider.TransactionstateEnlist().