Terraria: System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete
TransactionDependentCloneComplete() [2/2]
void System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete (Transaction transaction, string type) inline package
Definition at line 248 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Informational, EventKeywords.All))
        {
            if (transaction != null && transaction.TransactionTraceId.TransactionIdentifier != null)
            {
                TransactionDependentCloneComplete(transaction.TransactionTraceId.TransactionIdentifier, type);
            }
            else
            {
                TransactionDependentCloneComplete(string.Empty, type);
            }
        }
    }
References System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete(), System.Transactions.TransactionTraceIdentifier.TransactionIdentifier, System.Transactions.Transaction.TransactionTraceId, and System.type.
Referenced by System.Transactions.DependentTransaction.Complete(), and System.Transactions.TransactionsEtwProvider.TransactionDependentCloneComplete().