Terraria: System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback
EnlistmentForceRollback() [2/2]
void System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback (InternalEnlistment enlistment) inline package
Definition at line 363 of file TransactionsEtwProvider.cs.
    {
        if (IsEnabled(EventLevel.Warning, EventKeywords.All))
        {
            if (enlistment != null && enlistment.EnlistmentTraceId.EnlistmentIdentifier != 0)
            {
                EnlistmentForceRollback(enlistment.EnlistmentTraceId.EnlistmentIdentifier);
            }
            else
            {
                EnlistmentForceRollback(0);
            }
        }
    }
References System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback(), System.Transactions.EnlistmentTraceIdentifier.EnlistmentIdentifier, System.Transactions.InternalEnlistment.EnlistmentTraceId, and System.Diagnostics.Tracing.EventSource.IsEnabled().
Referenced by System.Transactions.TransactionsEtwProvider.EnlistmentForceRollback(), System.Transactions.PreparingEnlistment.ForceRollback(), and System.Transactions.PreparingEnlistment.ForceRollback().