Terraria: UIBestiaryTest.MakeExitButton
MakeExitButton()
void UIBestiaryTest.MakeExitButton (UIElement outerContainer) inline private
     {
         UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
         {
             Width = StyleDimension.FromPixelsAndPercent(-10f, 0.5f),
             Height = StyleDimension.FromPixels(50f),
             VAlign = 1f,
             HAlign = 0.5f,
             Top = StyleDimension.FromPixels(-25f)
         };
         uITextPanel.OnMouseOver += FadedMouseOver;
         uITextPanel.OnMouseOut += FadedMouseOut;
         uITextPanel.OnLeftMouseDown += Click_GoBack;
         uITextPanel.SetSnapPoint("ExitButton", 0);
         outerContainer.Append(uITextPanel);
     }
References UIElement.Append(), Click_GoBack(), FadedMouseOut(), FadedMouseOver(), StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), Language.GetText(), UIElement.HAlign, UIElement.Height, UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().