Terraria: UIBestiaryTest.SetupGamepadPoints
SetupGamepadPoints()
void UIBestiaryTest.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num = 3000;
         int currentID = num;
         List<SnapPoint> snapPoints = GetSnapPoints();
         SnapPoint snap = null;
         SnapPoint snap2 = null;
         SnapPoint snap3 = null;
         SnapPoint snap4 = null;
         SnapPoint snap5 = null;
         SnapPoint snap6 = null;
         for (int i = 0; i < snapPoints.Count; i++)
         {
             SnapPoint snapPoint = snapPoints[i];
             switch (snapPoint.Name)
             {
             case "BackPage":
                 snap = snapPoint;
                 break;
             case "NextPage":
                 snap2 = snapPoint;
                 break;
             case "ExitButton":
                 snap6 = snapPoint;
                 break;
             case "FilterButton":
                 snap4 = snapPoint;
                 break;
             case "SortButton":
                 snap3 = snapPoint;
                 break;
             case "SearchButton":
                 snap5 = snapPoint;
                 break;
             }
         }
         UILinkPoint uILinkPoint = MakeLinkPointFromSnapPoint(currentID++, snap);
         UILinkPoint uILinkPoint2 = MakeLinkPointFromSnapPoint(currentID++, snap2);
         UILinkPoint uILinkPoint3 = MakeLinkPointFromSnapPoint(currentID++, snap6);
         UILinkPoint uILinkPoint4 = MakeLinkPointFromSnapPoint(currentID++, snap4);
         UILinkPoint uILinkPoint5 = MakeLinkPointFromSnapPoint(currentID++, snap3);
         UILinkPoint rightSide = MakeLinkPointFromSnapPoint(currentID++, snap5);
         PairLeftRight(uILinkPoint, uILinkPoint2);
         PairLeftRight(uILinkPoint2, uILinkPoint5);
         PairLeftRight(uILinkPoint5, uILinkPoint4);
         PairLeftRight(uILinkPoint4, rightSide);
         uILinkPoint3.Up = uILinkPoint2.ID;
         UILinkPoint[,] gridPoints = new UILinkPoint[1, 1];
         int gridWidth;
         int gridHeight;
         if (_filteringGrid.Parent != null)
         {
             SetupPointsForFilterGrid(ref currentID, snapPoints, out gridWidth, out gridHeight, out gridPoints);
             PairUpDown(uILinkPoint2, uILinkPoint3);
             PairUpDown(uILinkPoint, uILinkPoint3);
             for (int num2 = gridWidth - 1; num2 >= 0; num2--)
             {
                 UILinkPoint uILinkPoint6 = gridPoints[num2, gridHeight - 1];
                 if (uILinkPoint6 != null)
                 {
                     PairUpDown(uILinkPoint6, uILinkPoint3);
                 }
                 UILinkPoint uILinkPoint7 = gridPoints[num2, gridHeight - 2];
                 if (uILinkPoint7 != null && uILinkPoint6 == null)
                 {
                     PairUpDown(uILinkPoint7, uILinkPoint3);
                 }
                 UILinkPoint uILinkPoint8 = gridPoints[num2, 0];
                 if (uILinkPoint8 != null)
                 {
                     if (num2 < gridWidth - 3)
                     {
                         PairUpDown(uILinkPoint5, uILinkPoint8);
                     }
                     else
                     {
                         PairUpDown(uILinkPoint4, uILinkPoint8);
                     }
                 }
             }
         }
         else if (_sortingGrid.Parent != null)
         {
             SetupPointsForSortingGrid(ref currentID, snapPoints, out gridWidth, out gridHeight, out gridPoints);
             PairUpDown(uILinkPoint2, uILinkPoint3);
             PairUpDown(uILinkPoint, uILinkPoint3);
             for (int num3 = gridWidth - 1; num3 >= 0; num3--)
             {
                 UILinkPoint uILinkPoint9 = gridPoints[num3, gridHeight - 1];
                 if (uILinkPoint9 != null)
                 {
                     PairUpDown(uILinkPoint9, uILinkPoint3);
                 }
                 UILinkPoint uILinkPoint10 = gridPoints[num3, 0];
                 if (uILinkPoint10 != null)
                 {
                     PairUpDown(uILinkPoint4, uILinkPoint10);
                     PairUpDown(uILinkPoint5, uILinkPoint10);
                 }
             }
         }
         else if (_entryGrid.Parent != null)
         {
             SetupPointsForEntryGrid(ref currentID, snapPoints, out gridWidth, out gridHeight, out gridPoints);
             for (int j = 0; j < gridWidth; j++)
             {
                 if (gridHeight - 1 >= 0)
                 {
                     UILinkPoint uILinkPoint11 = gridPoints[j, gridHeight - 1];
                     if (uILinkPoint11 != null)
                     {
                         PairUpDown(uILinkPoint11, uILinkPoint3);
                     }
                     if (gridHeight - 2 >= 0)
                     {
                         UILinkPoint uILinkPoint12 = gridPoints[j, gridHeight - 2];
                         if (uILinkPoint12 != null && uILinkPoint11 == null)
{
                             PairUpDown(uILinkPoint12, uILinkPoint3);
                         }
                     }
                 }
                 UILinkPoint uILinkPoint13 = gridPoints[j, 0];
                 if (uILinkPoint13 != null)
                 {
                     if (j < gridWidth / 2)
                     {
                         PairUpDown(uILinkPoint2, uILinkPoint13);
                     }
                     else if (j == gridWidth - 1)
                     {
                         PairUpDown(uILinkPoint4, uILinkPoint13);
                     }
                     else
                     {
                         PairUpDown(uILinkPoint5, uILinkPoint13);
                     }
                 }
             }
             UILinkPoint uILinkPoint14 = gridPoints[0, 0];
             if (uILinkPoint14 != null)
             {
                 PairUpDown(uILinkPoint2, uILinkPoint14);
                 PairUpDown(uILinkPoint, uILinkPoint14);
             }
             else
             {
                 PairUpDown(uILinkPoint2, uILinkPoint3);
                 PairUpDown(uILinkPoint, uILinkPoint3);
                 PairUpDown(uILinkPoint4, uILinkPoint3);
                 PairUpDown(uILinkPoint5, uILinkPoint3);
             }
         }
         List<UILinkPoint> list = new List<UILinkPoint>();
         for (int k = num; k < currentID; k++)
         {
             list.Add(UILinkPointNavigator.Points[k]);
         }
         if (PlayerInput.UsingGamepadUI && UILinkPointNavigator.CurrentPoint >= currentID)
         {
             MoveToVisuallyClosestPoint(list);
         }
     }
References _entryGrid, _filteringGrid, _sortingGrid, UILinkPointNavigator.Shortcuts.BackButtonCommand, UILinkPointNavigator.CurrentPoint, UIElement.GetSnapPoints(), UILinkPoint.ID, MakeLinkPointFromSnapPoint(), MoveToVisuallyClosestPoint(), SnapPoint.Name, PairLeftRight(), PairUpDown(), UIElement.Parent, UILinkPointNavigator.Points, SetupPointsForEntryGrid(), SetupPointsForFilterGrid(), SetupPointsForSortingGrid(), UILinkPoint.Up, and PlayerInput.UsingGamepadUI.
Referenced by Draw().