Terraria: UIBestiaryTest.FillProgressBottomBar
FillProgressBottomBar()
void UIBestiaryTest.FillProgressBottomBar (UIElement container) inline private
     {
         UIText progressPercentText = new UIText("", 0.8f)
         {
             HAlign = 0f,
             VAlign = 1f,
             TextOriginX = 0f,
             TextOriginY = 0f
         };
         _progressPercentText = progressPercentText;
         UIColoredSliderSimple uIColoredSliderSimple = new UIColoredSliderSimple
         {
             Width = new StyleDimension(0f, 1f),
             Height = new StyleDimension(15f, 0f),
             VAlign = 1f,
             FilledColor = new Color(51, 137, 255),
             EmptyColor = new Color(35, 43, 81),
             FillPercent = 0f
         };
         uIColoredSliderSimple.OnUpdate += ShowStats_Completion;
         _unlocksProgressBar = uIColoredSliderSimple;
         container.Append(uIColoredSliderSimple);
     }
References _progressPercentText, _unlocksProgressBar, UIElement.Append(), Color, UIElement.HAlign, UIElement.Height, UIElement.OnUpdate, ShowStats_Completion(), UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().