Terraria: UIBestiaryTest.GetProgressPercent
GetProgressPercent()
float UIBestiaryTest.GetProgressPercent () inline private
     {
         return _progressReport.CompletionPercent;
     }
References _progressReport, and BestiaryUnlockProgressReport.CompletionPercent.
Referenced by GetColorAtBlip(), GetCompletionPercentText(), and UpdateBestiaryContents().