Terraria: UIBestiaryTest.UpdateBestiaryContents
UpdateBestiaryContents()
void UIBestiaryTest.UpdateBestiaryContents () inline private
     {
         _filteringGrid.UpdateAvailability();
         _sortingText.SetText(_sorter.GetDisplayName());
         _filteringText.SetText(_filterer.GetDisplayName());
         FilterEntries();
         SortEntries();
         FillBestiarySpaceWithEntries();
         _progressReport = GetUnlockProgress();
         string completionPercentText = GetCompletionPercentText();
         _progressPercentText.SetText(completionPercentText);
         _unlocksProgressBar.FillPercent = GetProgressPercent();
     }
References _filterer, _filteringGrid, _filteringText, _progressPercentText, _progressReport, _sorter, _sortingText, _unlocksProgressBar, FillBestiarySpaceWithEntries(), UIColoredSliderSimple.FillPercent, FilterEntries(), GetCompletionPercentText(), EntryFilterer< T, U >.GetDisplayName(), EntrySorter< TEntryType, TStepType >.GetDisplayName(), GetProgressPercent(), GetUnlockProgress(), UIText.SetText(), SortEntries(), and UIBestiaryFilteringOptionsGrid.UpdateAvailability().
Referenced by BuildPage(), CloseFilteringGrid(), CloseSortingGrid(), OnOpenPage(), and OnSearchContentsChanged().