Terraria: UIBestiaryTest.UIBestiaryTest
UIBestiaryTest()
UIBestiaryTest.UIBestiaryTest (BestiaryDatabase database) inline
     {
         _filterer.SetSearchFilterObject(new Filters.BySearch());
         _originalEntriesList = new List<BestiaryEntry>(database.Entries);
         _workingSetEntries = new List<BestiaryEntry>(_originalEntriesList);
         _filterer.AddFilters(database.Filters);
         _sorter.AddSortSteps(database.SortSteps);
         BuildPage();
     }
References _filterer, _originalEntriesList, _sorter, _workingSetEntries, EntryFilterer< T, U >.AddFilters(), EntrySorter< TEntryType, TStepType >.AddSortSteps(), BuildPage(), BestiaryDatabase.Entries, BestiaryDatabase.Filters, and BestiaryDatabase.SortSteps.