Terraria: UIBestiaryTest.AddSortAndFilterButtons
AddSortAndFilterButtons()
void UIBestiaryTest.AddSortAndFilterButtons (UIElement innerTopContainer, UIBestiaryEntryInfoPage infoSpace) inline private
     {
         int num = 17;
         UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Filtering", (AssetRequestMode)1))
         {
             Left = new StyleDimension(0f - infoSpace.Width.Pixels - (float)num, 0f),
             HAlign = 1f
         };
         uIImageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Wide_Border", (AssetRequestMode)1));
         uIImageButton.SetVisibility(1f, 1f);
         uIImageButton.SetSnapPoint("FilterButton", 0);
         uIImageButton.OnLeftClick += OpenOrCloseFilteringGrid;
         innerTopContainer.Append(uIImageButton);
         UIText uIText = new UIText("", 0.8f)
         {
             Left = new StyleDimension(34f, 0f),
             Top = new StyleDimension(2f, 0f),
             VAlign = 0.5f,
             TextOriginX = 0f,
             TextOriginY = 0f
         };
         uIImageButton.Append(uIText);
         _filteringText = uIText;
         UIImageButton uIImageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Sorting", (AssetRequestMode)1))
         {
             Left = new StyleDimension(0f - infoSpace.Width.Pixels - uIImageButton.Width.Pixels - 3f - (float)num, 0f),
             HAlign = 1f
         };
         uIImageButton2.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Wide_Border", (AssetRequestMode)1));
         uIImageButton2.SetVisibility(1f, 1f);
         uIImageButton2.SetSnapPoint("SortButton", 0);
         uIImageButton2.OnLeftClick += OpenOrCloseSortingOptions;
         innerTopContainer.Append(uIImageButton2);
         UIText uIText2 = new UIText("", 0.8f)
         {
             Left = new StyleDimension(34f, 0f),
             Top = new StyleDimension(2f, 0f),
             VAlign = 0.5f,
             TextOriginX = 0f,
             TextOriginY = 0f
         };
         uIImageButton2.Append(uIText2);
         _sortingText = uIText2;
     }
References _filteringText, _sortingText, UIElement.Append(), Main.Assets, UIElement.HAlign, UIElement.Left, UIElement.OnLeftClick, OpenOrCloseFilteringGrid(), OpenOrCloseSortingOptions(), StyleDimension.Pixels, UIImageButton.SetHoverImage(), UIElement.SetSnapPoint(), UIImageButton.SetVisibility(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().