Terraria: UIDynamicItemCollection.UpdateSize
UpdateSize()
void UIDynamicItemCollection.UpdateSize () inline
     {
         int num = (_itemsPerLine = GetDimensions().ToRectangle().Width / 44);
         int num2 = (int)Math.Ceiling((float)_itemIdsAvailableToShow.Count / (float)num);
         MinHeight.Set(44 * num2, 0f);
     }
References _itemIdsAvailableToShow, _itemsPerLine, UIElement.GetDimensions(), UIElement.MinHeight, StyleDimension.Set(), and CalculatedStyle.ToRectangle().
Referenced by UIDynamicItemCollection(), Recalculate(), and SetContentsToShow().