Terraria: UIDynamicItemCollection.GetSnapPoints
GetSnapPoints()
override List<SnapPoint> UIDynamicItemCollection.GetSnapPoints () inline virtual
Reimplemented from UIElement.
     {
         List<SnapPoint> list = new List<SnapPoint>();
         GetGridParameters(out var startX, out var startY, out var startItemIndex, out var endItemIndex);
         _ = _itemsPerLine;
         Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
         int num = endItemIndex - startItemIndex;
         while (_dummySnapPoints.Count < num)
         {
             _dummySnapPoints.Add(new SnapPoint("CreativeInfinitesSlot", 0, Vector2.Zero, Vector2.Zero));
         }
         int num2 = 0;
         Vector2 vector = GetDimensions().Position();
         for (int i = startItemIndex; i < endItemIndex; i++)
         {
             Point center = GetItemSlotHitbox(startX, startY, startItemIndex, i).Center;
             if (viewCullingArea.Contains(center))
             {
                 SnapPoint snapPoint = _dummySnapPoints[num2];
                 snapPoint.ThisIsAHackThatChangesTheSnapPointsInfo(Vector2.Zero, center.ToVector2() - vector, num2);
                 snapPoint.Calculate(this);
                 num2++;
                 list.Add(snapPoint);
             }
         }
         foreach (UIElement element in Elements)
         {
             list.AddRange(element.GetSnapPoints());
         }
         return list;
     }
References _dummySnapPoints, _itemsPerLine, SnapPoint.Calculate(), UIElement.Elements, UIElement.GetDimensions(), GetGridParameters(), GetItemSlotHitbox(), UIElement.GetSnapPoints(), CalculatedStyle.Position(), and SnapPoint.ThisIsAHackThatChangesTheSnapPointsInfo().