Terraria: System.Threading.LowLevelLifoSemaphore.Create
Create()
void System.Threading.LowLevelLifoSemaphore.Create (int maximumSignalCount) inline private
Definition at line 315 of file LowLevelLifoSemaphore.cs.
    {
        _completionPort = Interop.Kernel32.CreateIoCompletionPort(new IntPtr(-1), IntPtr.Zero, UIntPtr.Zero, maximumSignalCount);
        if (_completionPort == IntPtr.Zero)
        {
            int lastPInvokeError = Marshal.GetLastPInvokeError();
            OutOfMemoryException ex = new OutOfMemoryException();
            ex.HResult = lastPInvokeError;
            throw ex;
        }
    }
References System.Threading.LowLevelLifoSemaphore._completionPort, Interop.Kernel32.CreateIoCompletionPort(), System.Runtime.InteropServices.Marshal.GetLastPInvokeError(), System.IntPtr.Zero, and System.UIntPtr.Zero.
Referenced by System.Threading.LowLevelLifoSemaphore.LowLevelLifoSemaphore().