Terraria: System.Xml.XmlNamedNodeMap.SetNamedItem
SetNamedItem()
virtual ? XmlNode System.Xml.XmlNamedNodeMap.SetNamedItem (XmlNode? node) inline virtual
Reimplemented in System.Xml.XmlAttributeCollection.
Definition at line 208 of file XmlNamedNodeMap.cs.
    {
        if (node == null)
        {
            return null;
        }
        int num = FindNodeOffset(node.LocalName, node.NamespaceURI);
        if (num == -1)
        {
            AddNode(node);
            return null;
        }
        return ReplaceNodeAt(num, node);
    }
References System.Xml.XmlNamedNodeMap.AddNode(), System.Xml.XmlNamedNodeMap.FindNodeOffset(), and System.Xml.XmlNamedNodeMap.ReplaceNodeAt().