Terraria: System.Xml.XmlNamedNodeMap.AddNode
AddNode()
virtual XmlNode System.Xml.XmlNamedNodeMap.AddNode (XmlNode node) inline package virtual
Reimplemented in System.Xml.XmlAttributeCollection.
Definition at line 302 of file XmlNamedNodeMap.cs.
    {
        XmlNode oldParent = ((node.NodeType != XmlNodeType.Attribute) ? node.ParentNode : ((XmlAttribute)node).OwnerElement);
        string value = node.Value;
        XmlNodeChangedEventArgs eventArgs = parent.GetEventArgs(node, oldParent, parent, value, value, XmlNodeChangedAction.Insert);
        if (eventArgs != null)
        {
            parent.BeforeEvent(eventArgs);
        }
        nodes.Add(node);
        node.SetParent(parent);
        if (eventArgs != null)
        {
            parent.AfterEvent(eventArgs);
        }
        return node;
    }
References System.Xml.XmlNamedNodeMap.SmallXmlNodeList.Add(), System.Xml.XmlNode.AfterEvent(), System.Xml.XmlNode.BeforeEvent(), System.Xml.Dictionary, System.Xml.XmlNode.GetEventArgs(), System.Xml.XmlNamedNodeMap.nodes, System.Xml.XmlNamedNodeMap.parent, and System.value.
Referenced by System.Xml.XmlNamedNodeMap.SetNamedItem().