Terraria: System.Threading.LowLevelLifoSemaphore.Release
Release()
void System.Threading.LowLevelLifoSemaphore.Release (int releaseCount) inline
Definition at line 249 of file LowLevelLifoSemaphore.cs.
    {
        Counts counts = _separated._counts;
        int num;
        while (true)
        {
            Counts newCounts = counts;
            newCounts.AddSignalCount((uint)releaseCount);
            num = (int)(Math.Min(newCounts.SignalCount, (uint)(counts.WaiterCount + counts.SpinnerCount)) - counts.SpinnerCount - counts.CountOfWaitersSignaledToWake);
            if (num > 0)
            {
                if (num > releaseCount)
                {
                    num = releaseCount;
                }
                newCounts.AddUpToMaxCountOfWaitersSignaledToWake((uint)num);
            }
            Counts counts2 = _separated._counts.InterlockedCompareExchange(newCounts, counts);
            if (counts2 == counts)
            {
                break;
            }
            counts = counts2;
        }
        if (num > 0)
        {
            ReleaseCore(num);
        }
    }
References System.Threading.LowLevelLifoSemaphore.CacheLineSeparatedCounts._counts, System.Threading.LowLevelLifoSemaphore._separated, System.Threading.LowLevelLifoSemaphore.Counts.AddSignalCount(), System.Threading.LowLevelLifoSemaphore.Counts.AddUpToMaxCountOfWaitersSignaledToWake(), System.Threading.LowLevelLifoSemaphore.Counts.CountOfWaitersSignaledToWake, System.Threading.LowLevelLifoSemaphore.Counts.InterlockedCompareExchange(), System.Math.Min(), System.Threading.LowLevelLifoSemaphore.ReleaseCore(), System.Threading.LowLevelLifoSemaphore.Counts.SignalCount, System.Threading.LowLevelLifoSemaphore.Counts.SpinnerCount, and System.Threading.LowLevelLifoSemaphore.Counts.WaiterCount.