Terraria: System.Threading.LowLevelLifoSemaphore.Wait
Wait()
bool System.Threading.LowLevelLifoSemaphore.Wait (int timeoutMs, bool spinWait) inline
Definition at line 160 of file LowLevelLifoSemaphore.cs.
    {
        int num = (spinWait ? _spinCount : 0);
        Counts counts = _separated._counts;
        Counts newCounts;
        while (true)
        {
            newCounts = counts;
            if (counts.SignalCount != 0)
            {
                newCounts.DecrementSignalCount();
            }
            else if (timeoutMs != 0)
            {
                if (num > 0 && newCounts.SpinnerCount < byte.MaxValue)
                {
                    newCounts.IncrementSpinnerCount();
                }
                else
                {
                    newCounts.IncrementWaiterCount();
                }
            }
            Counts counts2 = _separated._counts.InterlockedCompareExchange(newCounts, counts);
            if (counts2 == counts)
            {
                break;
            }
            counts = counts2;
        }
        if (counts.SignalCount != 0)
        {
            return true;
        }
        if (newCounts.WaiterCount != counts.WaiterCount)
        {
            return WaitForSignal(timeoutMs);
        }
        if (timeoutMs == 0)
        {
            return false;
        }
        int processorCount = Environment.ProcessorCount;
        int num2 = ((processorCount <= 1) ? 10 : 0);
        while (num2 < num)
        {
            LowLevelSpinWaiter.Wait(num2, 10, processorCount);
            num2++;
            counts = _separated._counts;
            while (counts.SignalCount != 0)
            {
                Counts newCounts2 = counts;
                newCounts2.DecrementSignalCount();
                newCounts2.DecrementSpinnerCount();
                Counts counts3 = _separated._counts.InterlockedCompareExchange(newCounts2, counts);
                if (counts3 == counts)
                {
                    return true;
                }
                counts = counts3;
            }
        }
        counts = _separated._counts;
        while (true)
        {
            Counts newCounts3 = counts;
            newCounts3.DecrementSpinnerCount();
            if (counts.SignalCount != 0)
            {
                newCounts3.DecrementSignalCount();
            }
            else
            {
                newCounts3.IncrementWaiterCount();
            }
            Counts counts4 = _separated._counts.InterlockedCompareExchange(newCounts3, counts);
            if (counts4 == counts)
            {
                break;
            }
            counts = counts4;
        }
        if (counts.SignalCount == 0)
        {
            return WaitForSignal(timeoutMs);
        }
        return true;
    }
References System.Threading.LowLevelLifoSemaphore.CacheLineSeparatedCounts._counts, System.Threading.LowLevelLifoSemaphore._separated, System.Threading.LowLevelLifoSemaphore._spinCount, System.Threading.LowLevelLifoSemaphore.Counts.DecrementSignalCount(), System.Threading.LowLevelLifoSemaphore.Counts.DecrementSpinnerCount(), System.Threading.LowLevelLifoSemaphore.Counts.IncrementSpinnerCount(), System.Threading.LowLevelLifoSemaphore.Counts.IncrementWaiterCount(), System.Threading.LowLevelLifoSemaphore.Counts.InterlockedCompareExchange(), System.Environment.ProcessorCount, System.Threading.LowLevelLifoSemaphore.Counts.SignalCount, System.Threading.LowLevelLifoSemaphore.Counts.SpinnerCount, System.Threading.LowLevelSpinWaiter.Wait(), System.Threading.LowLevelLifoSemaphore.Counts.WaiterCount, and System.Threading.LowLevelLifoSemaphore.WaitForSignal().
Referenced by System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart().