Terraria: System.Threading.LowLevelLifoSemaphore.WaitForSignal
WaitForSignal()
bool System.Threading.LowLevelLifoSemaphore.WaitForSignal (int timeoutMs) inline private
Definition at line 279 of file LowLevelLifoSemaphore.cs.
    {
        _onWait();
        Counts counts;
        do
        {
            if (!WaitCore(timeoutMs))
            {
                _separated._counts.InterlockedDecrementWaiterCount();
                return false;
            }
            counts = _separated._counts;
            while (true)
            {
                Counts newCounts = counts;
                if (counts.SignalCount != 0)
                {
                    newCounts.DecrementSignalCount();
                    newCounts.DecrementWaiterCount();
                }
                if (counts.CountOfWaitersSignaledToWake != 0)
                {
                    newCounts.DecrementCountOfWaitersSignaledToWake();
                }
                Counts counts2 = _separated._counts.InterlockedCompareExchange(newCounts, counts);
                if (counts2 == counts)
                {
                    break;
                }
                counts = counts2;
            }
        }
        while (counts.SignalCount == 0);
        return true;
    }
References System.Threading.LowLevelLifoSemaphore.CacheLineSeparatedCounts._counts, System.Threading.LowLevelLifoSemaphore._onWait, System.Threading.LowLevelLifoSemaphore._separated, System.Threading.LowLevelLifoSemaphore.Counts.CountOfWaitersSignaledToWake, System.Threading.LowLevelLifoSemaphore.Counts.DecrementCountOfWaitersSignaledToWake(), System.Threading.LowLevelLifoSemaphore.Counts.DecrementSignalCount(), System.Threading.LowLevelLifoSemaphore.Counts.DecrementWaiterCount(), System.Threading.LowLevelLifoSemaphore.Counts.InterlockedCompareExchange(), System.Threading.LowLevelLifoSemaphore.Counts.InterlockedDecrementWaiterCount(), System.Threading.LowLevelLifoSemaphore.Counts.SignalCount, and System.Threading.LowLevelLifoSemaphore.WaitCore().
Referenced by System.Threading.LowLevelLifoSemaphore.Wait().