Terraria: Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise
GetDynamicNoise() [1/3]
static float Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise (int index, float currentTime) inline static
Definition at line 30 of file NoiseHelper.cs.
    {
        float num = StaticNoise[index & 0x3FF];
        float num2 = currentTime % 1f;
        return Math.Abs(Math.Abs(num - num2) - 0.5f) * 2f;
    }
References System.Math.Abs(), System.index, and Terraria.GameContent.RGB.NoiseHelper.StaticNoise.
Referenced by Terraria.GameContent.RGB.SkyShader.ProcessAnyDetail(), Terraria.GameContent.RGB.BrainShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.IceShader.ProcessHighDetail(), Terraria.GameContent.RGB.JungleShader.ProcessHighDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessHighDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessHighDetail(), Terraria.GameContent.RGB.UnderworldShader.ProcessHighDetail(), Terraria.GameContent.RGB.WallOfFleshShader.ProcessHighDetail(), Terraria.GameContent.RGB.JungleShader.ProcessLowDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessLowDetail(), Terraria.GameContent.RGB.MoonShader.ProcessLowDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessLowDetail(), and Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail().