Terraria: Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise
GetStaticNoise() [1/3]
static float Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise (int index) inline static
Definition at line 37 of file NoiseHelper.cs.
    {
        return StaticNoise[index & 0x3FF];
    }
References System.index, and Terraria.GameContent.RGB.NoiseHelper.StaticNoise.
Referenced by Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Terraria.GameContent.RGB.BlizzardShader.ProcessHighDetail(), Terraria.GameContent.RGB.CavernShader.ProcessHighDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DesertShader.ProcessHighDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessHighDetail(), Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.FrostLegionShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessHighDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.RainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SandstormShader.ProcessHighDetail(), Terraria.GameContent.RGB.SkullShader.ProcessHighDetail(), Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail(), Terraria.GameContent.RGB.TempleShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessHighDetail(), Terraria.GameContent.RGB.VineShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessLowDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessLowDetail(), and Terraria.GameContent.RGB.EmpressShader.RedsVersion().