Terraria: System.Net.Http.Headers.AltSvcHeaderValue.ToString
ToString()
override string System.Net.Http.Headers.AltSvcHeaderValue.ToString () inline
Definition at line 30 of file AltSvcHeaderValue.cs.
    {
        StringBuilder stringBuilder = System.Text.StringBuilderCache.Acquire(AlpnProtocolName.Length + (Host?.Length ?? 0) + 64);
        stringBuilder.Append(AlpnProtocolName);
        stringBuilder.Append("=\"");
        if (Host != null)
        {
            stringBuilder.Append(Host);
        }
        stringBuilder.Append(':');
        stringBuilder.Append((uint)Port);
        stringBuilder.Append('"');
        if (MaxAge != TimeSpan.FromTicks(864000000000L))
        {
            StringBuilder stringBuilder2 = stringBuilder;
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(5, 1, stringBuilder2, invariantCulture);
            handler.AppendLiteral("; ma=");
            handler.AppendFormatted(MaxAge.Ticks / 10000000);
            stringBuilder2.Append(invariantCulture, ref handler);
        }
        if (Persist)
        {
            stringBuilder.Append("; persist=1");
        }
        return System.Text.StringBuilderCache.GetStringAndRelease(stringBuilder);
    }
References System.Text.StringBuilderCache.Acquire(), System.Net.Http.Headers.AltSvcHeaderValue.AlpnProtocolName, System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendLiteral(), System.TimeSpan.FromTicks(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Net.Http.Headers.AltSvcHeaderValue.Host, System.Globalization.CultureInfo.InvariantCulture, System.L, System.Net.Http.Headers.AltSvcHeaderValue.MaxAge, System.Net.Http.Headers.AltSvcHeaderValue.Persist, System.Net.Http.Headers.AltSvcHeaderValue.Port, and System.TimeSpan.Ticks.