Terraria: Terraria.GameContent.PlayerSittingHelper.SitUp
SitUp()
void Terraria.GameContent.PlayerSittingHelper.SitUp (Player player, bool multiplayerBroadcast = true) inline
Definition at line 78 of file PlayerSittingHelper.cs.
    {
        if (isSitting)
        {
            isSitting = false;
            offsetForSeat = Vector2.Zero;
            sittingIndex = -1;
            details = default(ExtraSeatInfo);
            if (multiplayerBroadcast && Main.myPlayer == player.whoAmI)
            {
                NetMessage.SendData(13, -1, -1, null, player.whoAmI);
            }
        }
    }
References Terraria.GameContent.PlayerSittingHelper.details, Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.Main.myPlayer, Terraria.GameContent.PlayerSittingHelper.offsetForSeat, Terraria.NetMessage.SendData(), Terraria.GameContent.PlayerSittingHelper.sittingIndex, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.PlayerSittingHelper.SitDown(), and Terraria.GameContent.PlayerSittingHelper.UpdateSitting().