Terraria: Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPowerInternal
UpdateUnlockStateByPowerInternal()
static void Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPowerInternal (ICreativePower power, Color colorWhenSelected, IGroupOptionButton asButton) inline static private
Definition at line 199 of file CreativePowersHelper.cs.
    {
        bool isUnlocked = power.GetIsUnlocked();
        bool flag = !IsAvailableForPlayer(power, Main.myPlayer);
        asButton.SetBorderColor(flag ? Color.DimGray : Color.White);
        if (flag)
        {
            asButton.SetColorsBasedOnSelectionState(new Color(60, 60, 60), new Color(60, 60, 60), 0.7f, 0.7f);
        }
        else if (isUnlocked)
        {
            asButton.SetColorsBasedOnSelectionState(colorWhenSelected, Colors.InventoryDefaultColor, 1f, 0.7f);
        }
        else
        {
            asButton.SetColorsBasedOnSelectionState(Color.Crimson, Color.Red, 0.7f, 0.7f);
        }
    }
References Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Color.Crimson, Microsoft.Xna.Framework.Color.DimGray, Terraria.GameContent.Creative.ICreativePower.GetIsUnlocked(), Terraria.ID.Colors.InventoryDefaultColor, Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), Terraria.Main.myPlayer, Microsoft.Xna.Framework.Color.Red, Terraria.GameContent.UI.Elements.IGroupOptionButton.SetBorderColor(), Terraria.GameContent.UI.Elements.IGroupOptionButton.SetColorsBasedOnSelectionState(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPower().