Terraria: Terraria.GameContent.Creative.CreativePowersHelper.CreateSimpleButton
CreateSimpleButton()
static GroupOptionButton< bool > Terraria.GameContent.Creative.CreativePowersHelper.CreateSimpleButton (CreativePowerUIElementRequestInfo info) inline static
Definition at line 99 of file CreativePowersHelper.cs.
    {
        GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(option: true, null, null, Color.White, null, 0.8f);
        groupOptionButton.Width = new StyleDimension(info.PreferredButtonWidth, 0f);
        groupOptionButton.Height = new StyleDimension(info.PreferredButtonHeight, 0f);
        groupOptionButton.ShowHighlightWhenSelected = false;
        groupOptionButton.SetCurrentOption(option: false);
        groupOptionButton.SetColorsBasedOnSelectionState(new Color(152, 175, 235), Colors.InventoryDefaultColor, 1f, 0.7f);
        return groupOptionButton;
    }
References Microsoft.Xna.Framework.Graphics.Color, System.info, Terraria.ID.Colors.InventoryDefaultColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColorsBasedOnSelectionState(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.ProvidePowerButtons().