Terraria: Terraria.GameContent.Creative.CreativePowersHelper.AddDescriptionIfNeeded
AddDescriptionIfNeeded()
static void Terraria.GameContent.Creative.CreativePowersHelper.AddDescriptionIfNeeded (ref string originalText, string descriptionKey) inline static
    {
        if (CreativePowerSettings.ShouldPowersBeElaborated)
        {
            string textValue = Language.GetTextValue(descriptionKey);
            originalText = originalText + "\n" + textValue;
        }
    }
References Terraria.Localization.Language.GetTextValue(), and Terraria.GameContent.Creative.CreativePowerSettings.ShouldPowersBeElaborated.
Referenced by Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.categoryButton_OnUpdate(), and Terraria.GameContent.UI.States.UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips().