Terraria: Terraria.GameContent.ObjectInteractions.PotionOfReturnSmartInteractCandidateProvider.ProvideCandidate
ProvideCandidate()
bool Terraria.GameContent.ObjectInteractions.PotionOfReturnSmartInteractCandidateProvider.ProvideCandidate (SmartInteractScanSettings settings, out ISmartInteractCandidate candidate) inline
Implements Terraria.GameContent.ObjectInteractions.ISmartInteractCandidateProvider.
Definition at line 30 of file PotionOfReturnSmartInteractCandidateProvider.cs.
    {
        candidate = null;
        if (!PotionOfReturnHelper.TryGetGateHitbox(settings.player, out var homeHitbox))
        {
            return false;
        }
        Vector2 vector = homeHitbox.ClosestPointInRect(settings.mousevec);
        float distanceFromCursor = vector.Distance(settings.mousevec);
        Point point = vector.ToTileCoordinates();
        if (point.X < settings.LX || point.X > settings.HX || point.Y < settings.LY || point.Y > settings.HY)
        {
            return false;
        }
        _candidate.Reuse(distanceFromCursor);
        candidate = _candidate;
        return true;
    }
References Terraria.GameContent.ObjectInteractions.PotionOfReturnSmartInteractCandidateProvider._candidate, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.HX, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.HY, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.LX, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.LY, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.mousevec, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.player, Terraria.GameContent.ObjectInteractions.PotionOfReturnSmartInteractCandidateProvider.ReusableCandidate.Reuse(), Terraria.GameContent.ObjectInteractions.PotionOfReturnHelper.TryGetGateHitbox(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.