Terraria: Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack
AlreadyLeadsIntoWantedTrack()
bool Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack (Point tileCoordsOfFrontWheel, Point tileCoordsWeWantToReach) inline private
Definition at line 100 of file MinecartDiggerHelper.cs.
    {
        Tile tileSafely = Framing.GetTileSafely(tileCoordsOfFrontWheel);
        Tile tileSafely2 = Framing.GetTileSafely(tileCoordsWeWantToReach);
        if (!tileSafely.active() || tileSafely.type != 314)
        {
            return false;
        }
        if (!tileSafely2.active() || tileSafely2.type != 314)
        {
            return false;
        }
        GetExpectedDirections(tileCoordsOfFrontWheel, tileCoordsWeWantToReach, out var expectedStartLeft, out var expectedStartRight, out var expectedEndLeft, out var expectedEndRight);
        if (!Minecart.GetAreExpectationsForSidesMet(tileCoordsOfFrontWheel, expectedStartLeft, expectedStartRight))
        {
            return false;
        }
        if (!Minecart.GetAreExpectationsForSidesMet(tileCoordsWeWantToReach, expectedEndLeft, expectedEndRight))
        {
            return false;
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.Minecart.GetAreExpectationsForSidesMet(), Terraria.GameContent.MinecartDiggerHelper.GetExpectedDirections(), Terraria.Framing.GetTileSafely(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.DoTheTracksConnectProperly(), and Terraria.GameContent.MinecartDiggerHelper.TryDigging().