Terraria: Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections
CorrectTrackConnections()
void Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections (Point startCoords, Point endCoords) inline private
    {
        GetExpectedDirections(startCoords, endCoords, out var expectedStartLeft, out var expectedStartRight, out var expectedEndLeft, out var expectedEndRight);
        Tile tileSafely = Framing.GetTileSafely(startCoords);
        Tile tileSafely2 = Framing.GetTileSafely(endCoords);
        if (tileSafely.active() && tileSafely.type == 314)
        {
            Minecart.TryFittingTileOrientation(startCoords, expectedStartLeft, expectedStartRight);
        }
        if (tileSafely2.active() && tileSafely2.type == 314)
        {
            Minecart.TryFittingTileOrientation(endCoords, expectedEndLeft, expectedEndRight);
        }
    }
References Terraria.Tile.active(), Terraria.GameContent.MinecartDiggerHelper.GetExpectedDirections(), Terraria.Framing.GetTileSafely(), Terraria.Minecart.TryFittingTileOrientation(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.TryDigging().