Terraria: Terraria.GameContent.MinecartDiggerHelper.TryDigging
TryDigging()
void Terraria.GameContent.MinecartDiggerHelper.TryDigging (Player player, Vector2 trackWorldPosition, int digDirectionX, int digDirectionY) inline
Definition at line 11 of file MinecartDiggerHelper.cs.
    {
        digDirectionY = 0;
        Point point = trackWorldPosition.ToTileCoordinates();
        if (Framing.GetTileSafely(point).type != 314 || (double)point.Y < Main.worldSurface)
        {
            return;
        }
        Point point2 = point;
        point2.X += digDirectionX;
        point2.Y += digDirectionY;
        if (AlreadyLeadsIntoWantedTrack(point, point2) || (digDirectionY == 0 && (AlreadyLeadsIntoWantedTrack(point, new Point(point2.X, point2.Y - 1)) || AlreadyLeadsIntoWantedTrack(point, new Point(point2.X, point2.Y + 1)))))
        {
            return;
        }
        int num = 5;
        if (digDirectionY != 0)
        {
            num = 5;
        }
        Point point3 = point2;
        Point point4 = point3;
        point4.Y -= num - 1;
        int x = point4.X;
        for (int i = point4.Y; i <= point3.Y; i++)
        {
            if (!CanGetPastTile(x, i) || !HasPickPower(player, x, i))
            {
                return;
            }
        }
        if (CanConsumeATrackItem(player))
        {
            int x2 = point4.X;
            for (int j = point4.Y; j <= point3.Y; j++)
            {
                MineTheTileIfNecessary(x2, j);
            }
            ConsumeATrackItem(player);
            PlaceATrack(point2.X, point2.Y);
            player.velocity.X = MathHelper.Clamp(player.velocity.X, -1f, 1f);
            if (!DoTheTracksConnectProperly(point, point2))
            {
                CorrectTrackConnections(point, point2);
            }
        }
    }
References Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), Terraria.GameContent.MinecartDiggerHelper.CanConsumeATrackItem(), Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.GameContent.MinecartDiggerHelper.ConsumeATrackItem(), Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections(), Terraria.GameContent.MinecartDiggerHelper.DoTheTracksConnectProperly(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.MinecartDiggerHelper.HasPickPower(), Terraria.GameContent.MinecartDiggerHelper.MineTheTileIfNecessary(), Terraria.GameContent.MinecartDiggerHelper.PlaceATrack(), Terraria.Entity.velocity, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Point.Y.