Terraria: System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction
InvokeXsltLateBoundFunction()
IList< XPathItem > System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction (string name, string namespaceUri, IList< XPathItem >[] args) inline
Definition at line 186 of file XmlQueryContext.cs.
    {
        object obj = ((_argList != null) ? _argList.GetExtensionObject(namespaceUri) : null);
        if (obj == null)
        {
            throw new XslTransformException(System.SR.XmlIl_UnknownExtObj, namespaceUri);
        }
        if (_extFuncsLate == null)
        {
            _extFuncsLate = new XmlExtensionFunctionTable();
        }
        XmlExtensionFunction xmlExtensionFunction = _extFuncsLate.Bind(name, namespaceUri, args.Length, obj.GetType(), BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public);
        object[] array = new object[args.Length];
        for (int i = 0; i < args.Length; i++)
        {
            XmlQueryType xmlArgumentType = xmlExtensionFunction.GetXmlArgumentType(i);
            switch (xmlArgumentType.TypeCode)
            {
            case XmlTypeCode.Boolean:
                array[i] = XsltConvert.ToBoolean(args[i]);
                break;
            case XmlTypeCode.Double:
                array[i] = XsltConvert.ToDouble(args[i]);
                break;
            case XmlTypeCode.String:
                array[i] = XsltConvert.ToString(args[i]);
                break;
            case XmlTypeCode.Node:
                if (xmlArgumentType.IsSingleton)
                {
                    array[i] = XsltConvert.ToNode(args[i]);
                }
                else
                {
                    array[i] = XsltConvert.ToNodeSet(args[i]);
                }
                break;
            case XmlTypeCode.Item:
                array[i] = args[i];
                break;
            }
            Type clrArgumentType = xmlExtensionFunction.GetClrArgumentType(i);
            if (xmlArgumentType.TypeCode == XmlTypeCode.Item || !clrArgumentType.IsAssignableFrom(array[i].GetType()))
            {
                array[i] = _runtime.ChangeTypeXsltArgument(xmlArgumentType, array[i], clrArgumentType);
            }
        }
        object obj2 = xmlExtensionFunction.Invoke(obj, array);
        if (obj2 == null && xmlExtensionFunction.ClrReturnType == XsltConvert.VoidType)
        {
            return XmlQueryNodeSequence.Empty;
        }
        return (IList<XPathItem>)_runtime.ChangeTypeXsltResult(XmlQueryTypeFactory.ItemS, obj2);
    }
References System.Xml.Xsl.Runtime.XmlQueryContext._argList, System.Xml.Xsl.Runtime.XmlQueryContext._extFuncsLate, System.Xml.Xsl.Runtime.XmlQueryContext._runtime, System.array, System.Xml.Xsl.Runtime.XmlExtensionFunctionTable.Bind(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltArgument(), System.Xml.Xsl.Runtime.XmlQueryRuntime.ChangeTypeXsltResult(), System.Xml.Xsl.Runtime.XmlQueryNodeSequence.Empty, System.Xml.Xsl.XsltArgumentList.GetExtensionObject(), System.Xml.Xsl.XmlQueryTypeFactory.ItemS, System.obj, System.Xml.Xsl.Runtime.XsltConvert.ToBoolean(), System.Xml.Xsl.Runtime.XsltConvert.ToDouble(), System.Xml.Xsl.Runtime.XsltConvert.ToNode(), System.Xml.Xsl.Runtime.XsltConvert.ToNodeSet(), System.Xml.Xsl.Runtime.XsltConvert.ToString(), System.Xml.Xsl.Runtime.XsltConvert.VoidType, and System.SR.XmlIl_UnknownExtObj.