Terraria: System.Xml.Xsl.Runtime.XmlQueryContext.LateBoundFunctionExists
LateBoundFunctionExists()
bool System.Xml.Xsl.Runtime.XmlQueryContext.LateBoundFunctionExists (string name, string namespaceUri) inline
Definition at line 171 of file XmlQueryContext.cs.
    {
        if (_argList == null)
        {
            return false;
        }
        object extensionObject = _argList.GetExtensionObject(namespaceUri);
        if (extensionObject == null)
        {
            return false;
        }
        return new XmlExtensionFunction(name, namespaceUri, -1, extensionObject.GetType(), BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public).CanBind();
    }
References System.Xml.Xsl.Runtime.XmlQueryContext._argList, System.Xml.Xsl.Runtime.XmlExtensionFunction.CanBind(), and System.Xml.Xsl.XsltArgumentList.GetExtensionObject().
Referenced by System.Xml.Xsl.Runtime.XsltLibrary.FunctionAvailableHelper().