Terraria: System.ComponentModel.DataAnnotations.ValidationContext.GetDisplayName
GetDisplayName()
string System.ComponentModel.DataAnnotations.ValidationContext.GetDisplayName () inline private
Definition at line 75 of file ValidationContext.cs.
    {
        string text = null;
        ValidationAttributeStore instance = ValidationAttributeStore.Instance;
        DisplayAttribute displayAttribute = null;
        if (string.IsNullOrEmpty(MemberName))
        {
            displayAttribute = instance.GetTypeDisplayAttribute(this);
        }
        else if (instance.IsPropertyContext(this))
        {
            displayAttribute = instance.GetPropertyDisplayAttribute(this);
        }
        if (displayAttribute != null)
        {
            text = displayAttribute.GetName();
        }
        return text ?? MemberName;
    }
References System.ComponentModel.DataAnnotations.ValidationAttributeStore.GetPropertyDisplayAttribute(), System.ComponentModel.DataAnnotations.ValidationAttributeStore.GetTypeDisplayAttribute(), System.ComponentModel.DataAnnotations.ValidationAttributeStore.Instance, System.ComponentModel.DataAnnotations.ValidationAttributeStore.IsPropertyContext(), System.ComponentModel.DataAnnotations.ValidationContext.MemberName, and System.text.