Terraria: UIDifficultyButton.UIDifficultyButton
UIDifficultyButton()
UIDifficultyButton.UIDifficultyButton (Player player, LocalizedText title, LocalizedText description, byte difficulty, Color color) inline
     {
         _player = player;
         _difficulty = difficulty;
         Width = StyleDimension.FromPixels(44f);
         Height = StyleDimension.FromPixels(110f);
         _BasePanelTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/PanelGrayscale", (AssetRequestMode)1);
         _selectedBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", (AssetRequestMode)1);
         _hoveredBorderTexture = Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelBorder", (AssetRequestMode)1);
         _color = color;
         UIText element = new UIText(title, 0.9f)
         {
             HAlign = 0.5f,
             VAlign = 0f,
             Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
             Top = StyleDimension.FromPixels(5f)
         };
         Append(element);
     }
References _BasePanelTexture, _color, _difficulty, _hoveredBorderTexture, _player, _selectedBorderTexture, UIElement.Append(), Main.Assets, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.HAlign, UIElement.Height, UIElement.Top, UIElement.VAlign, and UIElement.Width.