Terraria: UIDifficultyButton.DrawSelf
DrawSelf()
override void UIDifficultyButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         if (_hovered)
         {
             if (!_soundedHover)
             {
                 SoundEngine.PlaySound(12);
             }
             _soundedHover = true;
         }
         else
         {
             _soundedHover = false;
         }
         CalculatedStyle dimensions = GetDimensions();
         int num = 7;
         if (dimensions.Height < 30f)
         {
             num = 5;
         }
         int num2 = 10;
         int num3 = 10;
         bool num4 = _difficulty == _player.difficulty;
         Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.Lerp(Color.Black, _color, 0.8f) * 0.5f);
         if (num4)
         {
             Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X + num, (int)dimensions.Y + num - 2, (int)dimensions.Width - num * 2, (int)dimensions.Height - num * 2, num2, num2, num3, num3, Color.Lerp(_color, Color.White, 0.7f) * 0.5f);
         }
         if (_hovered)
         {
             Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.White);
         }
     }
References _BasePanelTexture, _color, _difficulty, _hovered, _hoveredBorderTexture, _player, _soundedHover, Color, Player.difficulty, Utils.DrawSplicedPanel(), UIElement.GetDimensions(), CalculatedStyle.Height, SoundEngine.PlaySound(), Asset< T >.Value, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.