Terraria: Modifiers.SkipTiles.Apply
Apply()
override bool Modifiers.SkipTiles.Apply (Point origin, int x, int y, params object[] args) inline virtual
Implements GenAction.
         {
             if (!GenBase._tiles[x, y].active())
             {
                 return UnitApply(origin, x, y, args);
             }
             for (int i = 0; i < _types.Length; i++)
             {
                 if (GenBase._tiles[x, y].type == _types[i])
                 {
                     return Fail();
                 }
             }
             return UnitApply(origin, x, y, args);
         }
References GenBase._tiles, Modifiers.SkipTiles._types, Tile.active(), GenAction.Fail(), Tile.type, and GenAction.UnitApply().