Terraria: DesertShader.ProcessHighDetail
ProcessHighDetail()
void DesertShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
References _baseColor, _sandColor, Fragment.Count, Fragment.GetCanvasPositionOfIndex(), Fragment.GetGridPositionOfIndex(), NoiseHelper.GetStaticNoise(), and Fragment.SetColor().