Terraria: WaterfallManager.FindWaterfalls
FindWaterfalls()
void WaterfallManager.FindWaterfalls (bool forced = false) inline
     {
         findWaterfallCount++;
         if (findWaterfallCount < 30 && !forced)
         {
             return;
         }
         findWaterfallCount = 0;
         waterfallDist = (int)(75f * Main.gfxQuality) + 25;
         qualityMax = (int)((float)maxWaterfallCount * Main.gfxQuality);
         currentMax = 0;
         int num = (int)(Main.screenPosition.X / 16f - 1f);
         int num2 = (int)((Main.screenPosition.X + (float)Main.screenWidth) / 16f) + 2;
         int num3 = (int)(Main.screenPosition.Y / 16f - 1f);
         int num4 = (int)((Main.screenPosition.Y + (float)Main.screenHeight) / 16f) + 2;
         num -= waterfallDist;
         num2 += waterfallDist;
         num3 -= waterfallDist;
         num4 += 20;
         if (num < 0)
         {
             num = 0;
         }
         if (num2 > Main.maxTilesX)
         {
             num2 = Main.maxTilesX;
         }
         if (num3 < 0)
         {
             num3 = 0;
         }
         if (num4 > Main.maxTilesY)
         {
             num4 = Main.maxTilesY;
         }
         for (int i = num; i < num2; i++)
         {
             for (int j = num3; j < num4; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (tile == null)
                 {
                     tile = new Tile();
                     Main.tile[i, j] = tile;
                 }
                 if (!tile.active())
                 {
                     continue;
                 }
                 if (tile.halfBrick())
                 {
                     Tile tile2 = Main.tile[i, j - 1];
                     if (tile2 == null)
                     {
                         tile2 = new Tile();
                         Main.tile[i, j - 1] = tile2;
                     }
                     if (tile2.liquid < 16 || WorldGen.SolidTile(tile2))
                     {
                         Tile tile3 = Main.tile[i - 1, j];
                         if (tile3 == null)
{
                             tile3 = new Tile();
                             Main.tile[i - 1, j] = tile3;
                         }
                         Tile tile4 = Main.tile[i + 1, j];
                         if (tile4 == null)
{
                             tile4 = new Tile();
                             Main.tile[i + 1, j] = tile4;
                         }
                         if ((tile3.liquid > 160 || tile4.liquid > 160) && ((tile3.liquid == 0 && !WorldGen.SolidTile(tile3) && tile3.slope() == 0) || (tile4.liquid == 0 && !WorldGen.SolidTile(tile4) && tile4.slope() == 0)) && currentMax < qualityMax)
{
                             waterfalls[currentMax].type = 0;
                             if (tile2.lava() || tile4.lava() || tile3.lava())
{
                                 waterfalls[currentMax].type = 1;
                             }
                             else if (tile2.honey() || tile4.honey() || tile3.honey())
{
                                 waterfalls[currentMax].type = 14;
                             }
                             else if (tile2.shimmer() || tile4.shimmer() || tile3.shimmer())
{
                                 waterfalls[currentMax].type = 25;
                             }
                             else
{
                                 waterfalls[currentMax].type = 0;
                             }
                             waterfalls[currentMax].x = i;
                             waterfalls[currentMax].y = j;
                             currentMax++;
                         }
                     }
                 }
                 if (tile.type == 196)
                 {
                     Tile tile5 = Main.tile[i, j + 1];
                     if (tile5 == null)
                     {
                         tile5 = new Tile();
                         Main.tile[i, j + 1] = tile5;
                     }
                     if (!WorldGen.SolidTile(tile5) && tile5.slope() == 0 && currentMax < qualityMax)
                     {
                         waterfalls[currentMax].type = 11;
                         waterfalls[currentMax].x = i;
                         waterfalls[currentMax].y = j + 1;
                         currentMax++;
                     }
                 }
                 if (tile.type == 460)
                 {
                     Tile tile6 = Main.tile[i, j + 1];
                     if (tile6 == null)
                     {
                         tile6 = new Tile();
                         Main.tile[i, j + 1] = tile6;
                     }
                     if (!WorldGen.SolidTile(tile6) && tile6.slope() == 0 && currentMax < qualityMax)
                     {
                         waterfalls[currentMax].type = 22;
                         waterfalls[currentMax].x = i;
                         waterfalls[currentMax].y = j + 1;
                         currentMax++;
                     }
                 }
             }
         }
     }
References Tile.active(), currentMax, findWaterfallCount, Main.gfxQuality, Tile.halfBrick(), Tile.honey(), Tile.lava(), Tile.liquid, Main.maxTilesX, Main.maxTilesY, maxWaterfallCount, qualityMax, Main.screenHeight, Main.screenPosition, Main.screenWidth, Tile.shimmer(), Tile.slope(), WorldGen.SolidTile(), Tile, Main.tile, Tile.type, WaterfallManager.WaterfallData.type, waterfallDist, waterfalls, WaterfallManager.WaterfallData.x, and WaterfallManager.WaterfallData.y.
Referenced by Main.DoDraw(), and Main.DrawCapture().