Terraria: MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput
GetNextInput()
XPathNavigator MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput () inline private
Definition at line 102 of file CacheChildrenQuery.cs.
    {
        XPathNavigator xPathNavigator;
        if (_nextInput != null)
        {
            xPathNavigator = _nextInput;
            _nextInput = null;
        }
        else
        {
            xPathNavigator = qyInput.Advance();
            if (xPathNavigator != null)
            {
                xPathNavigator = xPathNavigator.Clone();
            }
        }
        return xPathNavigator;
    }
References MS.Internal.Xml.XPath.CacheChildrenQuery._nextInput, MS.Internal.Xml.XPath.Query.Advance(), System.Xml.XPath.XPathNavigator.Clone(), System.Xml.Dictionary, and MS.Internal.Xml.XPath.BaseAxisQuery.qyInput.
Referenced by MS.Internal.Xml.XPath.CacheChildrenQuery.Advance(), and MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode().