Terraria: MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode
DecideNextNode()
bool MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode () inline private
Definition at line 84 of file CacheChildrenQuery.cs.
    {
        _nextInput = GetNextInput();
        if (_nextInput != null && Query.CompareNodes(currentNode, _nextInput) == XmlNodeOrder.After)
        {
            _elementStk.Push(currentNode);
            _positionStk.Push(position);
            currentNode = _nextInput;
            _nextInput = null;
            if (!currentNode.MoveToFirstChild())
            {
                return false;
            }
            position = 0;
        }
        return true;
    }
References MS.Internal.Xml.XPath.CacheChildrenQuery._elementStk, MS.Internal.Xml.XPath.CacheChildrenQuery._nextInput, MS.Internal.Xml.XPath.CacheChildrenQuery._positionStk, MS.Internal.Xml.XPath.Query.CompareNodes(), MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), MS.Internal.Xml.XPath.BaseAxisQuery.position, and MS.Internal.Xml.XPath.ClonableStack< T >.Push().
Referenced by MS.Internal.Xml.XPath.CacheChildrenQuery.Advance().