Terraria: MS.Internal.Xml.XPath.CacheChildrenQuery.Advance
Advance()
override XPathNavigator MS.Internal.Xml.XPath.CacheChildrenQuery.Advance () inline
Definition at line 42 of file CacheChildrenQuery.cs.
    {
        do
        {
            IL_0000:
            if (_needInput)
            {
                if (_elementStk.Count == 0)
                {
                    currentNode = GetNextInput();
                    if (currentNode == null)
                    {
                        return null;
                    }
                    if (!currentNode.MoveToFirstChild())
                    {
                        goto IL_0000;
                    }
                    position = 0;
                }
                else
                {
                    currentNode = _elementStk.Pop();
                    position = _positionStk.Pop();
                    if (!DecideNextNode())
                    {
                        goto IL_0000;
                    }
                }
                _needInput = false;
            }
            else if (!currentNode.MoveToNext() || !DecideNextNode())
            {
                _needInput = true;
                goto IL_0000;
            }
        }
        while (!matches(currentNode));
        position++;
        return currentNode;
    }
References MS.Internal.Xml.XPath.CacheChildrenQuery._elementStk, MS.Internal.Xml.XPath.CacheChildrenQuery._needInput, MS.Internal.Xml.XPath.CacheChildrenQuery._positionStk, MS.Internal.Xml.XPath.BaseAxisQuery.currentNode, MS.Internal.Xml.XPath.CacheChildrenQuery.DecideNextNode(), System.Xml.Dictionary, MS.Internal.Xml.XPath.CacheChildrenQuery.GetNextInput(), MS.Internal.Xml.XPath.BaseAxisQuery.matches(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), MS.Internal.Xml.XPath.ClonableStack< T >.Pop(), and MS.Internal.Xml.XPath.BaseAxisQuery.position.