Terraria: System.Globalization.CultureInfo.GetCultureInfo
GetCultureInfo() [3/4]
static CultureInfo System.Globalization.CultureInfo.GetCultureInfo (string name, bool predefinedOnly) inline static
Definition at line 875 of file CultureInfo.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (predefinedOnly && !GlobalizationMode.Invariant && (GlobalizationMode.UseNls ? (!CultureData.NlsIsEnsurePredefinedLocaleName(name)) : (!CultureData.IcuIsEnsurePredefinedLocaleName(name))))
        {
            throw new CultureNotFoundException("name", name, SR.Format(SR.Argument_InvalidPredefinedCultureName, name));
        }
        return GetCultureInfo(name);
    }
References System.SR.Argument_InvalidPredefinedCultureName, System.SR.Format(), System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.CultureData.IcuIsEnsurePredefinedLocaleName(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureData.NlsIsEnsurePredefinedLocaleName(), and System.Globalization.GlobalizationMode.UseNls.