Terraria: System.Globalization.CultureInfo.GetCultureInfo
GetCultureInfo() [2/4]
static CultureInfo System.Globalization.CultureInfo.GetCultureInfo (string name) inline static
Definition at line 808 of file CultureInfo.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        name = CultureData.AnsiToLower(name);
        Dictionary<string, CultureInfo> cachedCulturesByName = CachedCulturesByName;
        CultureInfo value;
        lock (cachedCulturesByName)
        {
            if (cachedCulturesByName.TryGetValue(name, out value))
            {
                return value;
            }
        }
        value = CreateCultureInfoNoThrow(name, useUserOverride: false) ?? throw new CultureNotFoundException("name", name, GetCultureNotSupportedExceptionMessage());
        value._isReadOnly = true;
        name = CultureData.AnsiToLower(value._name);
        lock (cachedCulturesByName)
        {
            cachedCulturesByName[name] = value;
            return value;
        }
    }
References System.Globalization.CultureData.AnsiToLower(), System.Globalization.CultureInfo.CachedCulturesByName, System.Globalization.CultureInfo.CreateCultureInfoNoThrow(), System.Globalization.CultureInfo.GetCultureNotSupportedExceptionMessage(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.