Terraria: System.Globalization.CultureInfo.ClearCachedData
ClearCachedData()
void System.Globalization.CultureInfo.ClearCachedData () inline
Definition at line 625 of file CultureInfo.cs.
    {
        UserDefaultLocaleName = GetUserDefaultLocaleName();
        s_userDefaultCulture = GetUserDefaultCulture();
        s_userDefaultUICulture = GetUserDefaultUICulture();
        RegionInfo.s_currentRegionInfo = null;
        TimeZone.ResetTimeZone();
        TimeZoneInfo.ClearCachedData();
        s_cachedCulturesByLcid = null;
        s_cachedCulturesByName = null;
        CultureData.ClearCachedData();
    }
References System.Globalization.CultureData.ClearCachedData(), System.TimeZoneInfo.ClearCachedData(), System.Globalization.CultureInfo.GetUserDefaultCulture(), System.Globalization.CultureInfo.GetUserDefaultLocaleName(), System.Globalization.CultureInfo.GetUserDefaultUICulture(), System.TimeZone.ResetTimeZone(), System.Globalization.CultureInfo.s_cachedCulturesByLcid, System.Globalization.CultureInfo.s_cachedCulturesByName, System.Globalization.CultureInfo.s_userDefaultCulture, System.Globalization.CultureInfo.s_userDefaultUICulture, and System.Globalization.CultureInfo.UserDefaultLocaleName.