Terraria: System.Globalization.CultureInfo.Clone
Clone()
virtual object System.Globalization.CultureInfo.Clone () inline virtual
Implements System.ICloneable.
Definition at line 690 of file CultureInfo.cs.
    {
        CultureInfo cultureInfo = (CultureInfo)MemberwiseClone();
        cultureInfo._isReadOnly = false;
        if (!_isInherited)
        {
            if (_dateTimeInfo != null)
            {
                cultureInfo._dateTimeInfo = (DateTimeFormatInfo)_dateTimeInfo.Clone();
            }
            if (_numInfo != null)
            {
                cultureInfo._numInfo = (NumberFormatInfo)_numInfo.Clone();
            }
        }
        else
        {
            cultureInfo.DateTimeFormat = (DateTimeFormatInfo)DateTimeFormat.Clone();
            cultureInfo.NumberFormat = (NumberFormatInfo)NumberFormat.Clone();
        }
        if (_textInfo != null)
        {
            cultureInfo._textInfo = (TextInfo)_textInfo.Clone();
        }
        if (_dateTimeInfo != null && _dateTimeInfo.Calendar == _calendar)
        {
            cultureInfo._calendar = cultureInfo.DateTimeFormat.Calendar;
        }
        else if (_calendar != null)
        {
            cultureInfo._calendar = (Calendar)_calendar.Clone();
        }
        return cultureInfo;
    }
References System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo._calendar, System.Globalization.CultureInfo._dateTimeInfo, System.Globalization.CultureInfo._isInherited, System.Globalization.CultureInfo._numInfo, System.Globalization.CultureInfo._textInfo, System.Globalization.CultureInfo.Calendar, System.Globalization.DateTimeFormatInfo.Calendar, System.Globalization.Calendar.Clone(), System.Globalization.NumberFormatInfo.Clone(), System.Globalization.TextInfo.Clone(), System.ICloneable.Clone(), System.Globalization.CultureInfo.NumberFormat, and System.Globalization.CultureInfo.TextInfo.