Terraria: System.Xml.Schema.XmlMiscConverter.ChangeType
ChangeType() [8/9]
override object System.Xml.Schema.XmlMiscConverter.ChangeType (object value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 128 of file XmlMiscConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        Type type = value.GetType();
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.ByteArrayType)
        {
            if (type == XmlBaseConverter.ByteArrayType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Base64Binary:
                    return (byte[])value;
                case XmlTypeCode.HexBinary:
                    return (byte[])value;
                }
            }
            if (type == XmlBaseConverter.StringType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Base64Binary:
                    return XmlBaseConverter.StringToBase64Binary((string)value);
                case XmlTypeCode.HexBinary:
                    return XmlBaseConverter.StringToHexBinary((string)value);
                }
            }
        }
        if (destinationType == XmlBaseConverter.XmlQualifiedNameType)
        {
            if (type == XmlBaseConverter.StringType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Notation:
                    return XmlBaseConverter.StringToQName((string)value, nsResolver);
                case XmlTypeCode.QName:
                    return XmlBaseConverter.StringToQName((string)value, nsResolver);
                }
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XmlQualifiedNameType))
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Notation:
                    return (XmlQualifiedName)value;
                case XmlTypeCode.QName:
                    return (XmlQualifiedName)value;
                }
            }
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return ToString(value, nsResolver);
        }
        if (destinationType == XmlBaseConverter.TimeSpanType)
        {
            if (type == XmlBaseConverter.StringType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.DayTimeDuration:
                    return XmlBaseConverter.StringToDayTimeDuration((string)value);
                case XmlTypeCode.Duration:
                    return XmlBaseConverter.StringToDuration((string)value);
                case XmlTypeCode.YearMonthDuration:
                    return XmlBaseConverter.StringToYearMonthDuration((string)value);
                }
            }
            if (type == XmlBaseConverter.TimeSpanType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.DayTimeDuration:
                    return (TimeSpan)value;
                case XmlTypeCode.Duration:
                    return (TimeSpan)value;
                case XmlTypeCode.YearMonthDuration:
                    return (TimeSpan)value;
                }
            }
        }
        if (destinationType == XmlBaseConverter.UriType)
        {
            if (type == XmlBaseConverter.StringType && base.TypeCode == XmlTypeCode.AnyUri)
            {
                return XmlConvert.ToUri((string)value);
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.UriType) && base.TypeCode == XmlTypeCode.AnyUri)
            {
                return (Uri)value;
            }
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            if (type == XmlBaseConverter.ByteArrayType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Base64Binary:
                    return new XmlAtomicValue(base.SchemaType, value);
                case XmlTypeCode.HexBinary:
                    return new XmlAtomicValue(base.SchemaType, value);
                }
            }
            if (type == XmlBaseConverter.StringType)
            {
                return new XmlAtomicValue(base.SchemaType, (string)value, nsResolver);
            }
            if (type == XmlBaseConverter.TimeSpanType)
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.DayTimeDuration:
                    return new XmlAtomicValue(base.SchemaType, value);
                case XmlTypeCode.Duration:
                    return new XmlAtomicValue(base.SchemaType, value);
                case XmlTypeCode.YearMonthDuration:
                    return new XmlAtomicValue(base.SchemaType, value);
                }
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.UriType) && base.TypeCode == XmlTypeCode.AnyUri)
            {
                return new XmlAtomicValue(base.SchemaType, value);
            }
            if (type == XmlBaseConverter.XmlAtomicValueType)
            {
                return (XmlAtomicValue)value;
            }
            if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XmlQualifiedNameType))
            {
                switch (base.TypeCode)
                {
                case XmlTypeCode.Notation:
                    return new XmlAtomicValue(base.SchemaType, value, nsResolver);
                case XmlTypeCode.QName:
                    return new XmlAtomicValue(base.SchemaType, value, nsResolver);
                }
            }
        }
        if (destinationType == XmlBaseConverter.XPathItemType && type == XmlBaseConverter.XmlAtomicValueType)
        {
            return (XmlAtomicValue)value;
        }
        if (destinationType == XmlBaseConverter.XPathItemType)
        {
            return (XPathItem)ChangeType(value, XmlBaseConverter.XmlAtomicValueType, nsResolver);
        }
        if (type == XmlBaseConverter.XmlAtomicValueType)
        {
            return ((XmlAtomicValue)value).ValueAs(destinationType, nsResolver);
        }
        return ChangeListType(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlBaseConverter.ChangeListType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Dictionary, System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.IsDerivedFrom(), System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringToBase64Binary(), System.Xml.Schema.XmlBaseConverter.StringToDayTimeDuration(), System.Xml.Schema.XmlBaseConverter.StringToDuration(), System.Xml.Schema.XmlBaseConverter.StringToHexBinary(), System.Xml.Schema.XmlBaseConverter.StringToQName(), System.Xml.Schema.XmlBaseConverter.StringToYearMonthDuration(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.ToString, System.Xml.XmlConvert.ToUri(), System.type, System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType, and System.Xml.Schema.XmlBaseConverter.XPathItemType.