Terraria: System.Xml.Schema.XmlMiscConverter.ChangeType
ChangeType() [9/9]
override object System.Xml.Schema.XmlMiscConverter.ChangeType (string value, Type destinationType, IXmlNamespaceResolver nsResolver) inline
Definition at line 67 of file XmlMiscConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        if (destinationType == null)
        {
            throw new ArgumentNullException("destinationType");
        }
        if (destinationType == XmlBaseConverter.ObjectType)
        {
            destinationType = base.DefaultClrType;
        }
        if (destinationType == XmlBaseConverter.ByteArrayType)
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.Base64Binary:
                return XmlBaseConverter.StringToBase64Binary(value);
            case XmlTypeCode.HexBinary:
                return XmlBaseConverter.StringToHexBinary(value);
            }
        }
        if (destinationType == XmlBaseConverter.XmlQualifiedNameType)
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.Notation:
                return XmlBaseConverter.StringToQName(value, nsResolver);
            case XmlTypeCode.QName:
                return XmlBaseConverter.StringToQName(value, nsResolver);
            }
        }
        if (destinationType == XmlBaseConverter.StringType)
        {
            return value;
        }
        if (destinationType == XmlBaseConverter.TimeSpanType)
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.DayTimeDuration:
                return XmlBaseConverter.StringToDayTimeDuration(value);
            case XmlTypeCode.Duration:
                return XmlBaseConverter.StringToDuration(value);
            case XmlTypeCode.YearMonthDuration:
                return XmlBaseConverter.StringToYearMonthDuration(value);
            }
        }
        if (destinationType == XmlBaseConverter.UriType && base.TypeCode == XmlTypeCode.AnyUri)
        {
            return XmlConvert.ToUri(value);
        }
        if (destinationType == XmlBaseConverter.XmlAtomicValueType)
        {
            return new XmlAtomicValue(base.SchemaType, value, nsResolver);
        }
        return ChangeTypeWildcardSource(value, destinationType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardSource(), System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.ObjectType, System.Xml.Schema.XmlBaseConverter.StringToBase64Binary(), System.Xml.Schema.XmlBaseConverter.StringToDayTimeDuration(), System.Xml.Schema.XmlBaseConverter.StringToDuration(), System.Xml.Schema.XmlBaseConverter.StringToHexBinary(), System.Xml.Schema.XmlBaseConverter.StringToQName(), System.Xml.Schema.XmlBaseConverter.StringToYearMonthDuration(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.XmlConvert.ToUri(), System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlAtomicValueType, and System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType.
Referenced by System.Xml.Schema.XmlMiscConverter.ChangeType(), and System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardSource().