Terraria: System.Globalization.CultureInfo.GetCultureInfo
GetCultureInfo() [4/4]
static CultureInfo System.Globalization.CultureInfo.GetCultureInfo (string name, string altName) inline static
Definition at line 834 of file CultureInfo.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (altName == null)
        {
            throw new ArgumentNullException("altName");
        }
        name = CultureData.AnsiToLower(name);
        altName = CultureData.AnsiToLower(altName);
        string key = name + "\ufffd" + altName;
        Dictionary<string, CultureInfo> cachedCulturesByName = CachedCulturesByName;
        CultureInfo value;
        lock (cachedCulturesByName)
        {
            if (cachedCulturesByName.TryGetValue(key, out value))
            {
                return value;
            }
        }
        try
        {
            value = new CultureInfo(name, altName)
            {
                _isReadOnly = true
            };
            value.TextInfo.SetReadOnlyState(readOnly: true);
        }
        catch (ArgumentException)
        {
            throw new CultureNotFoundException("name/altName", SR.Format(SR.Argument_OneOfCulturesNotSupported, name, altName));
        }
        lock (cachedCulturesByName)
        {
            cachedCulturesByName[key] = value;
            return value;
        }
    }
References System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo._isReadOnly, System.Globalization.CultureData.AnsiToLower(), System.SR.Argument_OneOfCulturesNotSupported, System.Globalization.CultureInfo.CachedCulturesByName, System.SR.Format(), System.key, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.