Terraria: System.Globalization.CultureInfo.CultureInfo
CultureInfo() [6/6]
System.Globalization.CultureInfo.CultureInfo (string cultureName, string textAndCompareCultureName) inline package
Definition at line 485 of file CultureInfo.cs.
    {
        if (cultureName == null)
        {
            throw new ArgumentNullException("cultureName", SR.ArgumentNull_String);
        }
        CultureData cultureData = CultureData.GetCultureData(cultureName, useUserOverride: false) ?? throw new CultureNotFoundException("cultureName", cultureName, GetCultureNotSupportedExceptionMessage());
        _cultureData = cultureData;
        _name = _cultureData.CultureName;
        CultureInfo cultureInfo = GetCultureInfo(textAndCompareCultureName);
        _compareInfo = cultureInfo.CompareInfo;
        _textInfo = cultureInfo.TextInfo;
    }
References System.Globalization.CultureInfo._compareInfo, System.Globalization.CultureInfo._cultureData, System.Globalization.CultureInfo._name, System.Globalization.CultureInfo._textInfo, System.SR.ArgumentNull_String, System.Globalization.CultureData.CultureName, System.Globalization.CultureData.GetCultureData(), System.Globalization.CultureInfo.GetCultureInfo(), and System.Globalization.CultureInfo.GetCultureNotSupportedExceptionMessage().