Terraria: System.Xml.Schema.XmlMiscConverter.ToString
ToString() [10/10]
override string System.Xml.Schema.XmlMiscConverter.ToString (object value, IXmlNamespaceResolver nsResolver) inline
Definition at line 17 of file XmlMiscConverter.cs.
    {
        if (value == null)
        {
            throw new ArgumentNullException("value");
        }
        Type type = value.GetType();
        if (type == XmlBaseConverter.ByteArrayType)
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.Base64Binary:
                return XmlBaseConverter.Base64BinaryToString((byte[])value);
            case XmlTypeCode.HexBinary:
                return XmlConvert.ToBinHexString((byte[])value);
            }
        }
        if (type == XmlBaseConverter.StringType)
        {
            return (string)value;
        }
        if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.UriType) && base.TypeCode == XmlTypeCode.AnyUri)
        {
            return XmlBaseConverter.AnyUriToString((Uri)value);
        }
        if (type == XmlBaseConverter.TimeSpanType)
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.DayTimeDuration:
                return XmlBaseConverter.DayTimeDurationToString((TimeSpan)value);
            case XmlTypeCode.Duration:
                return XmlBaseConverter.DurationToString((TimeSpan)value);
            case XmlTypeCode.YearMonthDuration:
                return XmlBaseConverter.YearMonthDurationToString((TimeSpan)value);
            }
        }
        if (XmlBaseConverter.IsDerivedFrom(type, XmlBaseConverter.XmlQualifiedNameType))
        {
            switch (base.TypeCode)
            {
            case XmlTypeCode.Notation:
                return XmlBaseConverter.QNameToString((XmlQualifiedName)value, nsResolver);
            case XmlTypeCode.QName:
                return XmlBaseConverter.QNameToString((XmlQualifiedName)value, nsResolver);
            }
        }
        return (string)ChangeTypeWildcardDestination(value, XmlBaseConverter.StringType, nsResolver);
    }
References System.Xml.Schema.XmlBaseConverter.AnyUriToString(), System.Xml.Schema.XmlBaseConverter.Base64BinaryToString(), System.Xml.Schema.XmlBaseConverter.ByteArrayType, System.Xml.Schema.XmlMiscConverter.ChangeTypeWildcardDestination(), System.Xml.Schema.XmlBaseConverter.DayTimeDurationToString(), System.Xml.Dictionary, System.Xml.Schema.XmlBaseConverter.DurationToString(), System.Type.GetType(), System.Xml.Schema.XmlBaseConverter.IsDerivedFrom(), System.Xml.Schema.XmlBaseConverter.QNameToString(), System.Xml.Schema.XmlBaseConverter.StringType, System.Xml.Schema.XmlBaseConverter.TimeSpanType, System.Xml.XmlConvert.ToBinHexString(), System.type, System.Xml.Schema.XmlBaseConverter.UriType, System.value, System.Xml.Schema.XmlBaseConverter.XmlQualifiedNameType, and System.Xml.Schema.XmlBaseConverter.YearMonthDurationToString().