Terraria: System.Globalization.CultureInfo.GetCultureInfo
GetCultureInfo() [1/4]
static CultureInfo System.Globalization.CultureInfo.GetCultureInfo (int culture) inline static
Definition at line 775 of file CultureInfo.cs.
    {
        if (culture <= 0)
        {
            throw new ArgumentOutOfRangeException("culture", SR.ArgumentOutOfRange_NeedPosNum);
        }
        Dictionary<int, CultureInfo> cachedCulturesByLcid = CachedCulturesByLcid;
        CultureInfo value;
        lock (cachedCulturesByLcid)
        {
            if (cachedCulturesByLcid.TryGetValue(culture, out value))
            {
                return value;
            }
        }
        try
        {
            value = new CultureInfo(culture, useUserOverride: false)
            {
                _isReadOnly = true
            };
        }
        catch (ArgumentException)
        {
            throw new CultureNotFoundException("culture", culture, GetCultureNotSupportedExceptionMessage());
        }
        lock (cachedCulturesByLcid)
        {
            cachedCulturesByLcid[culture] = value;
            return value;
        }
    }
References System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CultureInfo._isReadOnly, System.SR.ArgumentOutOfRange_NeedPosNum, System.Globalization.CultureInfo.CachedCulturesByLcid, System.culture, System.Globalization.CultureInfo.GetCultureNotSupportedExceptionMessage(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Globalization.CultureInfo.CultureInfo(), System.Globalization.CalendarData.GetCalendarCurrentEra(), System.Globalization.CompareInfo.GetCompareInfo(), System.Globalization.CompareInfo.GetCompareInfo(), System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.CultureInfo.GetCultureInfoByIetfLanguageTag(), System.Reflection.RuntimeAssembly.GetLocale(), System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(), System.Globalization.CultureData.IcuEnumCultures(), System.Globalization.TextInfo.NeedsTurkishCasing(), System.Globalization.CompareInfo.OnDeserialized(), System.Globalization.CompareInfo.OnSerializing(), System.Globalization.TextInfo.PopulateIsAsciiCasingSameAsInvariant(), and System.Data.SqlTypes.SqlString.SetCompareInfo().