Terraria: System.Globalization.CultureInfo.ReadOnly
ReadOnly()
static CultureInfo System.Globalization.CultureInfo.ReadOnly (CultureInfo ci) inline static
Definition at line 725 of file CultureInfo.cs.
    {
        if (ci == null)
        {
            throw new ArgumentNullException("ci");
        }
        if (ci.IsReadOnly)
        {
            return ci;
        }
        CultureInfo cultureInfo = (CultureInfo)ci.MemberwiseClone();
        if (!ci.IsNeutralCulture)
        {
            if (!ci._isInherited)
            {
                if (ci._dateTimeInfo != null)
                {
                    cultureInfo._dateTimeInfo = DateTimeFormatInfo.ReadOnly(ci._dateTimeInfo);
                }
                if (ci._numInfo != null)
                {
                    cultureInfo._numInfo = NumberFormatInfo.ReadOnly(ci._numInfo);
                }
            }
            else
            {
                cultureInfo.DateTimeFormat = DateTimeFormatInfo.ReadOnly(ci.DateTimeFormat);
                cultureInfo.NumberFormat = NumberFormatInfo.ReadOnly(ci.NumberFormat);
            }
        }
        if (ci._textInfo != null)
        {
            cultureInfo._textInfo = System.Globalization.TextInfo.ReadOnly(ci._textInfo);
        }
        if (ci._calendar != null)
        {
            cultureInfo._calendar = System.Globalization.Calendar.ReadOnly(ci._calendar);
        }
        cultureInfo._isReadOnly = true;
        return cultureInfo;
    }
References System.Globalization.CultureInfo.CultureInfo(), System.Collections.Generic.Dictionary< TKey, TValue >.IsReadOnly, System.Globalization.Calendar.ReadOnly(), System.Globalization.NumberFormatInfo.ReadOnly(), and System.Globalization.TextInfo.ReadOnly().
Referenced by System.ComponentModel.MaskedTextProvider.MaskedTextProvider().