Terraria: System.Text.EncodingNLS.GetChars
GetChars() [2/6]
unsafe int System.Text.EncodingNLS.GetChars (byte * bytes, int byteCount, char * chars, int charCount, System.Text.DecoderNLS decoder) abstract virtual
Reimplemented from System.Text.Encoding.
Reimplemented in System.Text.GB18030Encoding, System.Text.ISCIIEncoding, System.Text.ISO2022Encoding, and System.Text.SBCSCodePageEncoding.
Referenced by System.Text.DecoderNLS.Convert(), System.Text.EncodingNLS.GetChars(), System.Text.DecoderNLS.GetChars(), and System.Text.EncodingNLS.GetChars().