Terraria: System.Text.EncodingNLS.GetByteCount
GetByteCount() [2/7]
unsafe int System.Text.EncodingNLS.GetByteCount (char * chars, int count, System.Text.EncoderNLS encoder) abstract virtual
Reimplemented from System.Text.Encoding.
Reimplemented in System.Text.ISCIIEncoding, System.Text.ISO2022Encoding, System.Text.GB18030Encoding, and System.Text.SBCSCodePageEncoding.
Referenced by System.Text.EncodingNLS.GetByteCount(), System.Text.EncoderNLS.GetByteCount(), System.Text.EncodingNLS.GetByteCount(), and System.Text.EncodingNLS.GetByteCount().