Terraria: System.Text.EncodingNLS.ThrowCharsOverflow
ThrowCharsOverflow() [2/2]
void System.Text.EncodingNLS.ThrowCharsOverflow (System::Text::DecoderNLS decoder, bool nothingDecoded) inline package inherited
Definition at line 353 of file EncodingNLS.cs.
    {
        if ((decoder?.m_throwOnOverflow ?? true) || nothingDecoded)
        {
            if (decoder != null && decoder.InternalHasFallbackBuffer)
            {
                decoder.FallbackBuffer.Reset();
            }
            ThrowCharsOverflow();
        }
        decoder.ClearMustFlush();
    }
References System.Text.EncodingNLS.ThrowCharsOverflow().
Referenced by System.Text.EncodingCharBuffer.AddChar(), System.Text.EncodingCharBuffer.AddChar(), and System.Text.EncodingCharBuffer.Fallback().