Terraria: UIColoredSlider.DrawSelf
DrawSelf()
override void UIColoredSlider.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         UISliderBase.CurrentAimedSlider = null;
         if (!Main.mouseLeft)
         {
             UISliderBase.CurrentLockedSlider = null;
         }
         int usageLevel = GetUsageLevel();
         float num = 8f;
         base.DrawSelf(spriteBatch);
         CalculatedStyle dimensions = GetDimensions();
         float num2 = dimensions.Width + 1f;
         Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
         bool flag = false;
         bool flag2 = base.IsMouseHovering;
         if (usageLevel == 2)
         {
             flag2 = false;
         }
         if (usageLevel == 1)
         {
             flag2 = true;
         }
         Vector2 vector2 = vector + new Vector2(0f, 2f);
         Color value = (flag ? Color.Gold : (flag2 ? Color.White : Color.Silver));
         value = Color.Lerp(value, Color.White, flag2 ? 0.5f : 0f);
         Vector2 vector3 = new Vector2(0.8f);
         vector2.X += 8f;
         vector2.Y += num;
         vector2.X -= 17f;
         TextureAssets.ColorBar.Frame();
         vector2 = new Vector2(dimensions.X + dimensions.Width - 10f, dimensions.Y + 10f + num);
         bool wasInBar;
         float obj = DrawValueBar(spriteBatch, vector2, 1f, _getStatusTextAct(), usageLevel, out wasInBar, _blipFunc);
         if (UISliderBase.CurrentLockedSlider == this || wasInBar)
         {
             UISliderBase.CurrentAimedSlider = this;
             if (PlayerInput.Triggers.Current.MouseLeft && !PlayerInput.UsingGamepad && UISliderBase.CurrentLockedSlider == this)
             {
                 _slideKeyboardAction(obj);
                 if (!_soundedUsage)
                 {
                     SoundEngine.PlaySound(12);
                 }
                 _soundedUsage = true;
             }
             else
             {
                 _soundedUsage = false;
             }
         }
         if (UISliderBase.CurrentAimedSlider != null && UISliderBase.CurrentLockedSlider == null)
         {
             UISliderBase.CurrentLockedSlider = UISliderBase.CurrentAimedSlider;
         }
         if (_isReallyMouseOvered)
         {
             _slideGamepadAction();
         }
     }
References _blipFunc, _getStatusTextAct, _isReallyMouseOvered, _slideGamepadAction, _slideKeyboardAction, _soundedUsage, Color, TextureAssets.ColorBar, TriggersPack.Current, UISliderBase.CurrentAimedSlider, UISliderBase.CurrentLockedSlider, DrawValueBar(), UIElement.GetDimensions(), UISliderBase.GetUsageLevel(), TriggersSet.MouseLeft, Main.mouseLeft, SoundEngine.PlaySound(), PlayerInput.Triggers, PlayerInput.UsingGamepad, CalculatedStyle.Width, CalculatedStyle.X, and CalculatedStyle.Y.