Terraria: System.Xml.Xsl.XsltOld.ElementAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.ElementAction.Compile (Compiler compiler) inline package
Definition at line 44 of file ElementAction.cs.
    {
        CompileAttributes(compiler);
        CheckRequiredAttribute(compiler, _nameAvt, "name");
        _name = CompiledAction.PrecalculateAvt(ref _nameAvt);
        _nsUri = CompiledAction.PrecalculateAvt(ref _nsAvt);
        if (_nameAvt == null && _nsAvt == null)
        {
            if (_name != "xmlns")
            {
                _qname = CreateElementQName(_name, _nsUri, compiler.CloneScopeManager());
            }
        }
        else
        {
            _manager = compiler.CloneScopeManager();
        }
        if (compiler.Recurse())
        {
            CompileTemplate(compiler);
            compiler.ToParent();
        }
        _empty = containedActions == null;
    }
References System.Xml.Xsl.XsltOld.ElementAction._empty, System.Xml.Xsl.XsltOld.ElementAction._manager, System.Xml.Xsl.XsltOld.ElementAction._name, System.Xml.Xsl.XsltOld.ElementAction._nameAvt, System.Xml.Xsl.XsltOld.ElementAction._nsAvt, System.Xml.Xsl.XsltOld.ElementAction._nsUri, System.Xml.Xsl.XsltOld.ElementAction._qname, System.Xml.Xsl.XsltOld.CompiledAction.CheckRequiredAttribute(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Xsl.XsltOld.ContainerAction.containedActions, System.Xml.Xsl.XsltOld.ElementAction.CreateElementQName(), System.Xml.Dictionary, and System.Xml.Xsl.XsltOld.CompiledAction.PrecalculateAvt().