Terraria: System.Xml.Xsl.XsltOld.ElementAction.Execute
Execute()
override void System.Xml.Xsl.XsltOld.ElementAction.Execute (Processor processor, ActionFrame frame) inline package
Definition at line 92 of file ElementAction.cs.
    {
        switch (frame.State)
        {
        default:
            return;
        case 0:
            if (_qname != null)
            {
                frame.CalulatedName = _qname;
            }
            else
            {
                frame.CalulatedName = CreateElementQName((_nameAvt == null) ? _name : _nameAvt.Evaluate(processor, frame), (_nsAvt == null) ? _nsUri : _nsAvt.Evaluate(processor, frame), _manager);
            }
            goto case 2;
        case 2:
        {
            PrefixQName calulatedName = frame.CalulatedName;
            if (!processor.BeginEvent(XPathNodeType.Element, calulatedName.Prefix, calulatedName.Name, calulatedName.Namespace, _empty))
            {
                frame.State = 2;
                return;
            }
            if (!_empty)
            {
                processor.PushActionFrame(frame);
                frame.State = 1;
                return;
            }
            break;
        }
        case 1:
            break;
        }
        if (!processor.EndEvent(XPathNodeType.Element))
        {
            frame.State = 1;
        }
        else
        {
            frame.Finished();
        }
    }
References System.Xml.Xsl.XsltOld.ElementAction._empty, System.Xml.Xsl.XsltOld.ElementAction._manager, System.Xml.Xsl.XsltOld.ElementAction._name, System.Xml.Xsl.XsltOld.ElementAction._nameAvt, System.Xml.Xsl.XsltOld.ElementAction._nsAvt, System.Xml.Xsl.XsltOld.ElementAction._nsUri, System.Xml.Xsl.XsltOld.ElementAction._qname, System.Xml.Xsl.XsltOld.ActionFrame.CalulatedName, System.Xml.Xsl.XsltOld.ElementAction.CreateElementQName(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.Avt.Evaluate(), System.Xml.Xsl.XsltOld.ActionFrame.Finished(), and System.Xml.Xsl.XsltOld.ActionFrame.State.