Terraria: System.Reflection.Metadata.Ecma335.ConstantTableReader.ConstantTableReader
ConstantTableReader()
System.Reflection.Metadata.Ecma335.ConstantTableReader.ConstantTableReader (int numberOfRows, bool declaredSorted, int hasConstantRefSize, int blobHeapRefSize, MemoryBlock containingBlock, int containingBlockOffset) inline package
Definition at line 23 of file ConstantTableReader.cs.
    {
        NumberOfRows = numberOfRows;
        _IsHasConstantRefSizeSmall = hasConstantRefSize == 2;
        _IsBlobHeapRefSizeSmall = blobHeapRefSize == 2;
        _TypeOffset = 0;
        _ParentOffset = _TypeOffset + 1 + 1;
        _ValueOffset = _ParentOffset + hasConstantRefSize;
        RowSize = _ValueOffset + blobHeapRefSize;
        Block = containingBlock.GetMemoryBlockAt(containingBlockOffset, RowSize * numberOfRows);
        if (!declaredSorted && !CheckSorted())
        {
            Throw.TableNotSorted(TableIndex.Constant);
        }
    }
References System.Reflection.Metadata.Ecma335.ConstantTableReader._IsBlobHeapRefSizeSmall, System.Reflection.Metadata.Ecma335.ConstantTableReader._IsHasConstantRefSizeSmall, System.Reflection.Metadata.Ecma335.ConstantTableReader._ParentOffset, System.Reflection.Metadata.Ecma335.ConstantTableReader._TypeOffset, System.Reflection.Metadata.Ecma335.ConstantTableReader._ValueOffset, System.Reflection.Metadata.Ecma335.ConstantTableReader.Block, System.Reflection.Metadata.Ecma335.ConstantTableReader.CheckSorted(), System.Reflection.Internal.MemoryBlock.GetMemoryBlockAt(), System.Reflection.Metadata.Ecma335.ConstantTableReader.NumberOfRows, System.Reflection.Metadata.Ecma335.ConstantTableReader.RowSize, and System.Reflection.Throw.TableNotSorted().