Terraria: System.Reflection.Metadata.Ecma335.ConstantTableReader.FindConstant
FindConstant()
ConstantHandle System.Reflection.Metadata.Ecma335.ConstantTableReader.FindConstant (EntityHandle parentHandle) inline package
Definition at line 57 of file ConstantTableReader.cs.
    {
        int num = Block.BinarySearchReference(NumberOfRows, RowSize, _ParentOffset, HasConstantTag.ConvertToTag(parentHandle), _IsHasConstantRefSizeSmall);
        return ConstantHandle.FromRowId(num + 1);
    }
References System.Reflection.Metadata.Ecma335.ConstantTableReader._IsHasConstantRefSizeSmall, System.Reflection.Metadata.Ecma335.ConstantTableReader._ParentOffset, System.Reflection.Internal.MemoryBlock.BinarySearchReference(), System.Reflection.Metadata.Ecma335.ConstantTableReader.Block, System.Reflection.Metadata.Ecma335.HasConstantTag.ConvertToTag(), System.Reflection.Metadata.ConstantHandle.FromRowId(), System.Reflection.Metadata.Ecma335.ConstantTableReader.NumberOfRows, and System.Reflection.Metadata.Ecma335.ConstantTableReader.RowSize.
Referenced by System.Reflection.Metadata.FieldDefinition.GetDefaultValue(), and System.Reflection.Metadata.PropertyDefinition.GetDefaultValue().