Terraria: UserInterface.ResetState
ResetState()
void UserInterface.ResetState () inline private
     {
         if (!Main.dedServ)
         {
             GetMousePosition();
             ImmediatelyUpdateInputPointers();
             if (_lastElementHover != null)
             {
                 _lastElementHover.MouseOut(new UIMouseEvent(_lastElementHover, MousePosition));
             }
         }
         ClearPointers();
         _lastElementHover = null;
         _clickDisabledTimeRemaining = Math.Max(_clickDisabledTimeRemaining, 200.0);
     }
References _clickDisabledTimeRemaining, _lastElementHover, ClearPointers(), Main.dedServ, GetMousePosition(), ImmediatelyUpdateInputPointers(), UIElement.MouseOut(), and MousePosition.
Referenced by RefreshState(), and SetState().