Terraria: UserInterface.SetState
SetState()
void UserInterface.SetState (UIState state) inline
     {
         if (state == _currentState)
         {
             return;
         }
         if (state != null)
         {
             AddToHistory(state);
         }
         if (_currentState != null)
         {
             if (_lastElementHover != null)
             {
                 _lastElementHover.MouseOut(new UIMouseEvent(_lastElementHover, MousePosition));
             }
             _currentState.Deactivate();
         }
         _currentState = state;
         ResetState();
         if (state != null)
         {
             _isStateDirty = true;
             state.Activate();
             state.Recalculate();
         }
     }
References _currentState, _isStateDirty, _lastElementHover, UIElement.Activate(), AddToHistory(), UIElement.Deactivate(), UIElement.MouseOut(), MousePosition, UIElement.Recalculate(), and ResetState().
Referenced by UIResourcePackSelectionMenu.Click_Info(), UICharacterCreation.Click_Naming(), UICharacterCreation.Click_NamingAndCreating(), UIWorldCreation.Click_NamingAndCreating(), UIWorkshopHub.Click_OpenResourcePackPublishMenu(), UIWorkshopHub.Click_OpenWorldImportMenu(), UIWorkshopHub.Click_OpenWorldPublishMenu(), UIWorldCreation.Click_SetName(), UIWorldCreation.Click_SetSeed(), IngameFancyUI.Close(), WorldGen.CreateNewWorld(), Main.DoUpdate(), IngameFancyUI.Draw(), Main.DrawMenu(), GoBack(), UIReportsPage.GoBackClick(), UIResourcePackInfoMenu.GoBackClick(), UIBestiaryTest.GoBackHere(), UIWorldCreation.GoBackHere(), WorkshopPublishInfoStateForResourcePack.GoToPublishConfirmation(), WorkshopPublishInfoStateForWorld.GoToPublishConfirmation(), Main.GoToWorldSelect(), AWorkshopPublishInfoState< TPublishedObjectType >.HandleBackButtonUsage(), UIResourcePackSelectionMenu.HandleBackButtonUsage(), UIWorkshopHub.HandleBackButtonUsage(), UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), UIWorkshopWorldImport.HandleBackButtonUsage(), UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), CreativeUI.Initialize(), UICharacterSelect.NewCharacterClick(), UIWorldSelect.NewWorldClick(), UICharacterCreation.OnCanceledNaming(), UICharacterCreation.OnFinishedNaming(), UICharacterCreation.OnFinishedNamingAndCreating(), IngameFancyUI.OpenAchievements(), Main.OpenCharacterSelectUI(), Main.OpenPlayerSelect(), Main.OpenReportsMenu(), Main.OpenResourcePacksMenu(), IngameFancyUI.OpenUIState(), IngameFancyUI.OpenVirtualKeyboard(), UIBestiaryTest.OpenVirtualKeyboardWhenNeeded(), Main.OpenWorldSelectUI(), UIWorkshopPublishResourcePackListItem.PublishButtonClick_ImportResourcePackToLocalFiles(), UIWorkshopPublishWorldListItem.PublishButtonClick_ImportWorldToLocalFiles(), UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), UICharacterListItem.RenameButtonClick(), and UIWorldListItem.RenameButtonClick().