Terraria: UserInterface.Update
Update()
void UserInterface.Update (GameTime time) inline
     {
         if (_currentState == null)
         {
             return;
         }
         GetMousePosition();
         UIElement uIElement = (Main.hasFocus ? _currentState.GetElementAt(MousePosition) : null);
         _clickDisabledTimeRemaining = Math.Max(0.0, _clickDisabledTimeRemaining - time.ElapsedGameTime.TotalMilliseconds);
         bool num = _clickDisabledTimeRemaining > 0.0;
         if (uIElement != _lastElementHover)
         {
             if (_lastElementHover != null)
             {
                 _lastElementHover.MouseOut(new UIMouseEvent(_lastElementHover, MousePosition));
             }
             uIElement?.MouseOver(new UIMouseEvent(uIElement, MousePosition));
             _lastElementHover = uIElement;
         }
         if (!num)
         {
             HandleClick(LeftMouse, time, Main.mouseLeft && Main.hasFocus, uIElement);
             HandleClick(RightMouse, time, Main.mouseRight && Main.hasFocus, uIElement);
         }
         if (PlayerInput.ScrollWheelDeltaForUI != 0)
         {
             uIElement?.ScrollWheel(new UIScrollWheelEvent(uIElement, MousePosition, PlayerInput.ScrollWheelDeltaForUI));
             PlayerInput.ScrollWheelDeltaForUI = 0;
         }
         if (_currentState != null)
         {
             _currentState.Update(time);
         }
     }
References _clickDisabledTimeRemaining, _currentState, _lastElementHover, UIElement.GetElementAt(), GetMousePosition(), HandleClick(), Main.hasFocus, LeftMouse, Main.mouseLeft, UIElement.MouseOut(), UIElement.MouseOver(), MousePosition, Main.mouseRight, RightMouse, UIElement.ScrollWheel(), PlayerInput.ScrollWheelDeltaForUI, and UIElement.Update().
Referenced by CreativeUI.Update(), and Main.UpdateUIStates().