Terraria: System.Text.Json.Serialization.Converters.IDictionaryConverter.OnWriteResume
OnWriteResume()
override bool System.Text.Json.Serialization.Converters.IDictionaryConverter< TDictionary >.OnWriteResume (Utf8JsonWriter writer, TDictionary value, JsonSerializerOptions options, ref WriteStack state) inline package
Definition at line 55 of file IDictionaryConverter.cs.
    {
        IDictionaryEnumerator dictionaryEnumerator;
        if (state.Current.CollectionEnumerator == null)
        {
            dictionaryEnumerator = value.GetEnumerator();
            if (!dictionaryEnumerator.MoveNext())
            {
                return true;
            }
        }
        else
        {
            dictionaryEnumerator = (IDictionaryEnumerator)state.Current.CollectionEnumerator;
        }
        JsonTypeInfo jsonTypeInfo = state.Current.JsonTypeInfo;
        if (_valueConverter == null)
        {
            _valueConverter = JsonDictionaryConverter<TDictionary, string, object>.GetConverter<object>(jsonTypeInfo.ElementTypeInfo);
        }
        do
        {
            if (ShouldFlush(writer, ref state))
            {
                state.Current.CollectionEnumerator = dictionaryEnumerator;
                return false;
            }
            if ((int)state.Current.PropertyState < 2)
            {
                state.Current.PropertyState = StackFramePropertyState.Name;
                object key = dictionaryEnumerator.Key;
                if (key is string value2)
                {
                    if (_keyConverter == null)
                    {
                        _keyConverter = JsonDictionaryConverter<TDictionary, string, object>.GetConverter<string>(jsonTypeInfo.KeyTypeInfo);
                    }
                    _keyConverter.WriteAsPropertyNameCore(writer, value2, options, state.Current.IsWritingExtensionDataProperty);
                }
                else
                {
                    _valueConverter.WriteAsPropertyNameCore(writer, key, options, state.Current.IsWritingExtensionDataProperty);
                }
            }
            object value3 = dictionaryEnumerator.Value;
            if (!_valueConverter.TryWrite(writer, in value3, options, ref state))
            {
                state.Current.CollectionEnumerator = dictionaryEnumerator;
                return false;
            }
            state.Current.EndDictionaryElement();
        }
        while (dictionaryEnumerator.MoveNext());
        return true;
    }
References System.Text.Json.Serialization.JsonDictionaryConverter< TDictionary, string, object >._keyConverter, System.Text.Json.Serialization.JsonDictionaryConverter< TDictionary, string, object >._valueConverter, System.Text.Json.Dictionary, System.Collections.Generic.Dictionary< TKey, TValue >.GetEnumerator(), System.key, System.options, System.state, System.Text.Json.Serialization.JsonConverter< T >.TryWrite(), System.value, System.Text.Json.Serialization.JsonConverter< T >.WriteAsPropertyNameCore(), and System.writer.