Terraria: System.ComponentModel.MaskedTextProvider.SetString
SetString()
void System.ComponentModel.MaskedTextProvider.SetString (string input, int testPosition) inline private
Definition at line 1377 of file MaskedTextProvider.cs.
    {
        foreach (char input2 in input)
        {
            if (!TestEscapeChar(input2, testPosition))
            {
                testPosition = FindEditPositionFrom(testPosition, direction: true);
            }
            SetChar(input2, testPosition);
            testPosition++;
        }
    }
References System.ComponentModel.MaskedTextProvider.FindEditPositionFrom(), System.input, System.ComponentModel.MaskedTextProvider.SetChar(), and System.ComponentModel.MaskedTextProvider.TestEscapeChar().
Referenced by System.ComponentModel.MaskedTextProvider.InsertAtInt(), System.ComponentModel.MaskedTextProvider.Replace(), and System.ComponentModel.MaskedTextProvider.TestSetString().