Terraria: System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionFrom
FindAssignedEditPositionFrom()
int System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionFrom (int position, bool direction) inline
Definition at line 558 of file MaskedTextProvider.cs.
    {
        if (AssignedEditPositionCount == 0)
        {
            return -1;
        }
        int startPosition;
        int endPosition;
        if (direction)
        {
            startPosition = position;
            endPosition = _testString.Length - 1;
        }
        else
        {
            startPosition = 0;
            endPosition = position;
        }
        return FindAssignedEditPositionInRange(startPosition, endPosition, direction);
    }
References System.ComponentModel.MaskedTextProvider.AssignedEditPositionCount, and System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionInRange().
Referenced by System.ComponentModel.MaskedTextProvider.ResetString(), and System.ComponentModel.MaskedTextProvider.Set().