Terraria: System.ComponentModel.MaskedTextProvider.RemoveAtInt
RemoveAtInt()
bool System.ComponentModel.MaskedTextProvider.RemoveAtInt (int startPosition, int endPosition, out int testPosition, out MaskedTextResultHint resultHint, bool testOnly) inline private
Definition at line 1027 of file MaskedTextProvider.cs.
    {
        int lastAssignedPosition = LastAssignedPosition;
        int num = FindEditPositionInRange(startPosition, endPosition, direction: true);
        resultHint = MaskedTextResultHint.NoEffect;
        if (num == -1 || num > lastAssignedPosition)
        {
            testPosition = startPosition;
            return true;
        }
        testPosition = startPosition;
        bool flag = endPosition < lastAssignedPosition;
        if (FindAssignedEditPositionInRange(startPosition, endPosition, direction: true) != -1)
        {
            resultHint = MaskedTextResultHint.Success;
        }
        if (flag)
        {
            int num2 = FindEditPositionFrom(endPosition + 1, direction: true);
            int num3 = num2;
            startPosition = num;
            while (true)
            {
                char c = _testString[num2];
                CharDescriptor charDescriptor = _stringDescriptor[num2];
                if ((c != PromptChar || charDescriptor.IsAssigned) && !TestChar(c, num, out var resultHint2))
                {
                    resultHint = resultHint2;
                    testPosition = num;
                    return false;
                }
                if (num2 == lastAssignedPosition)
                {
                    break;
                }
                num2 = FindEditPositionFrom(num2 + 1, direction: true);
                num = FindEditPositionFrom(num + 1, direction: true);
            }
            if (MaskedTextResultHint.SideEffect > resultHint)
            {
                resultHint = MaskedTextResultHint.SideEffect;
            }
            if (testOnly)
            {
                return true;
            }
            num2 = num3;
            num = startPosition;
            while (true)
            {
                char c2 = _testString[num2];
                CharDescriptor charDescriptor2 = _stringDescriptor[num2];
                if (c2 == PromptChar && !charDescriptor2.IsAssigned)
                {
                    ResetChar(num);
                }
                else
                {
                    SetChar(c2, num);
                    ResetChar(num2);
                }
                if (num2 == lastAssignedPosition)
                {
                    break;
                }
                num2 = FindEditPositionFrom(num2 + 1, direction: true);
                num = FindEditPositionFrom(num + 1, direction: true);
            }
            startPosition = num + 1;
        }
        if (startPosition <= endPosition)
        {
            ResetString(startPosition, endPosition);
        }
        return true;
    }
References System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionInRange(), System.ComponentModel.MaskedTextProvider.FindEditPositionFrom(), System.ComponentModel.MaskedTextProvider.FindEditPositionInRange(), System.ComponentModel.MaskedTextProvider.LastAssignedPosition, System.ComponentModel.MaskedTextProvider.PromptChar, System.ComponentModel.MaskedTextProvider.ResetChar(), System.ComponentModel.MaskedTextProvider.ResetString(), System.ComponentModel.MaskedTextProvider.SetChar(), and System.ComponentModel.MaskedTextProvider.TestChar().
Referenced by System.ComponentModel.MaskedTextProvider.RemoveAt(), and System.ComponentModel.MaskedTextProvider.Replace().