Terraria: System.ComponentModel.MaskedTextProvider.ToString
ToString() [3/7]
string System.ComponentModel.MaskedTextProvider.ToString (bool ignorePasswordChar, bool includePrompt, bool includeLiterals, int startPosition, int length) inline
Definition at line 1669 of file MaskedTextProvider.cs.
    {
        if (length <= 0)
        {
            return string.Empty;
        }
        if (startPosition < 0)
        {
            startPosition = 0;
        }
        if (startPosition >= _testString.Length)
        {
            return string.Empty;
        }
        int num = _testString.Length - startPosition;
        if (length > num)
        {
            length = num;
        }
        if ((!IsPassword || ignorePasswordChar) && includePrompt && includeLiterals)
        {
            return _testString.ToString(startPosition, length);
        }
        StringBuilder stringBuilder = new StringBuilder();
        int num2 = startPosition + length - 1;
        if (!includePrompt)
        {
            int num3 = (includeLiterals ? FindNonEditPositionInRange(startPosition, num2, direction: false) : InvalidIndex);
            int num4 = FindAssignedEditPositionInRange((num3 == InvalidIndex) ? startPosition : num3, num2, direction: false);
            num2 = ((num4 != InvalidIndex) ? num4 : num3);
            if (num2 == InvalidIndex)
            {
                return string.Empty;
            }
        }
        for (int i = startPosition; i <= num2; i++)
        {
            char value = _testString[i];
            CharDescriptor charDescriptor = _stringDescriptor[i];
            switch (charDescriptor.CharType)
            {
            case CharType.EditOptional:
            case CharType.EditRequired:
                if (charDescriptor.IsAssigned)
                {
                    if (IsPassword && !ignorePasswordChar)
                    {
                        stringBuilder.Append(_passwordChar);
                        continue;
                    }
                }
                else if (!includePrompt)
                {
                    stringBuilder.Append(' ');
                    continue;
                }
                break;
            case CharType.Separator:
            case CharType.Literal:
                if (!includeLiterals)
                {
                    continue;
                }
                break;
            }
            stringBuilder.Append(value);
        }
        return stringBuilder.ToString();
    }
References System.ComponentModel.MaskedTextProvider._passwordChar, System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionInRange(), System.ComponentModel.MaskedTextProvider.FindNonEditPositionInRange(), System.ComponentModel.MaskedTextProvider.InvalidIndex, System.ComponentModel.MaskedTextProvider.IsPassword, System.length, System.Text.StringBuilder.Length, System.Text.StringBuilder.ToString(), and System.value.