Terraria: System.ComponentModel.MaskedTextProvider.Clone
Clone()
object System.ComponentModel.MaskedTextProvider.Clone () inline
Implements System.ICloneable.
Definition at line 454 of file MaskedTextProvider.cs.
    {
        Type type = GetType();
        MaskedTextProvider maskedTextProvider;
        if (type == s_maskTextProviderType)
        {
            maskedTextProvider = new MaskedTextProvider(Mask, Culture, AllowPromptAsInput, PromptChar, PasswordChar, AsciiOnly);
        }
        else
        {
            object[] args = new object[6] { Mask, Culture, AllowPromptAsInput, PromptChar, PasswordChar, AsciiOnly };
            maskedTextProvider = Activator.CreateInstance(type, args) as MaskedTextProvider;
        }
        maskedTextProvider.ResetOnPrompt = false;
        maskedTextProvider.ResetOnSpace = false;
        maskedTextProvider.SkipLiterals = false;
        for (int i = 0; i < _testString.Length; i++)
        {
            CharDescriptor charDescriptor = _stringDescriptor[i];
            if (IsEditPosition(charDescriptor) && charDescriptor.IsAssigned)
            {
                maskedTextProvider.Replace(_testString[i], i);
            }
        }
        maskedTextProvider.ResetOnPrompt = ResetOnPrompt;
        maskedTextProvider.ResetOnSpace = ResetOnSpace;
        maskedTextProvider.SkipLiterals = SkipLiterals;
        maskedTextProvider.IncludeLiterals = IncludeLiterals;
        maskedTextProvider.IncludePrompt = IncludePrompt;
        return maskedTextProvider;
    }
References System.ComponentModel.MaskedTextProvider.MaskedTextProvider(), System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.AllowPromptAsInput, System.ComponentModel.MaskedTextProvider.AsciiOnly, System.Activator.CreateInstance(), System.ComponentModel.MaskedTextProvider.Culture, System.ComponentModel.MaskedTextProvider.IncludeLiterals, System.ComponentModel.MaskedTextProvider.IncludePrompt, System.ComponentModel.MaskedTextProvider.IsEditPosition(), System.Text.StringBuilder.Length, System.ComponentModel.MaskedTextProvider.Mask, System.ComponentModel.MaskedTextProvider.PasswordChar, System.ComponentModel.MaskedTextProvider.PromptChar, System.ComponentModel.MaskedTextProvider.ResetOnPrompt, System.ComponentModel.MaskedTextProvider.ResetOnSpace, System.ComponentModel.MaskedTextProvider.s_maskTextProviderType, System.ComponentModel.MaskedTextProvider.SkipLiterals, and System.type.