Terraria: System.ComponentModel.MaskedTextProvider.Replace
Replace() [6/6]
bool System.ComponentModel.MaskedTextProvider.Replace (string input, int startPosition, int endPosition, out int testPosition, out MaskedTextResultHint resultHint) inline
Definition at line 1189 of file MaskedTextProvider.cs.
    {
        if (input == null)
        {
            throw new ArgumentNullException("input");
        }
        if (endPosition >= _testString.Length)
        {
            testPosition = endPosition;
            resultHint = MaskedTextResultHint.PositionOutOfRange;
            return false;
        }
        if (startPosition < 0 || startPosition > endPosition)
        {
            testPosition = startPosition;
            resultHint = MaskedTextResultHint.PositionOutOfRange;
            return false;
        }
        if (input.Length == 0)
        {
            return RemoveAt(startPosition, endPosition, out testPosition, out resultHint);
        }
        if (!TestString(input, startPosition, out testPosition, out resultHint))
        {
            return false;
        }
        if (AssignedEditPositionCount > 0)
        {
            MaskedTextResultHint resultHint2;
            if (testPosition < endPosition)
            {
                if (!RemoveAtInt(testPosition + 1, endPosition, out var testPosition2, out resultHint2, testOnly: false))
                {
                    testPosition = testPosition2;
                    resultHint = resultHint2;
                    return false;
                }
                if (resultHint2 == MaskedTextResultHint.Success && resultHint != resultHint2)
                {
                    resultHint = MaskedTextResultHint.SideEffect;
                }
            }
            else if (testPosition > endPosition)
            {
                int lastAssignedPosition = LastAssignedPosition;
                int position = testPosition + 1;
                int position2 = endPosition + 1;
                while (true)
                {
                    position2 = FindEditPositionFrom(position2, direction: true);
                    position = FindEditPositionFrom(position, direction: true);
                    if (position == -1)
                    {
                        testPosition = _testString.Length;
                        resultHint = MaskedTextResultHint.UnavailableEditPosition;
                        return false;
                    }
                    if (!TestChar(_testString[position2], position, out resultHint2))
                    {
                        testPosition = position;
                        resultHint = resultHint2;
                        return false;
                    }
                    if (resultHint2 == MaskedTextResultHint.Success && resultHint != resultHint2)
                    {
                        resultHint = MaskedTextResultHint.Success;
                    }
                    if (position2 == lastAssignedPosition)
                    {
                        break;
                    }
                    position2++;
                    position++;
                }
                while (position > testPosition)
                {
                    SetChar(_testString[position2], position);
                    position2 = FindEditPositionFrom(position2 - 1, direction: false);
                    position = FindEditPositionFrom(position - 1, direction: false);
                }
            }
        }
        SetString(input, startPosition);
        return true;
    }
References System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.AssignedEditPositionCount, System.ComponentModel.MaskedTextProvider.FindEditPositionFrom(), System.input, System.ComponentModel.MaskedTextProvider.LastAssignedPosition, System.Text.StringBuilder.Length, System.ComponentModel.MaskedTextProvider.RemoveAt(), System.ComponentModel.MaskedTextProvider.RemoveAtInt(), System.ComponentModel.MaskedTextProvider.SetChar(), System.ComponentModel.MaskedTextProvider.SetString(), System.ComponentModel.MaskedTextProvider.TestChar(), and System.ComponentModel.MaskedTextProvider.TestString().