Terraria: System.ComponentModel.MaskedTextProvider.Initialize
Initialize()
void System.ComponentModel.MaskedTextProvider.Initialize () inline private
Definition at line 358 of file MaskedTextProvider.cs.
    {
        _testString = new StringBuilder();
        _stringDescriptor = new List<CharDescriptor>();
        CaseConversion caseConversion = CaseConversion.None;
        bool flag = false;
        int num = 0;
        CharType charType = CharType.Literal;
        string text = string.Empty;
        for (int i = 0; i < Mask.Length; i++)
        {
            char c = Mask[i];
            if (!flag)
            {
                switch (c)
                {
                case '.':
                    text = Culture.NumberFormat.NumberDecimalSeparator;
                    charType = CharType.Separator;
                    break;
                case ',':
                    text = Culture.NumberFormat.NumberGroupSeparator;
                    charType = CharType.Separator;
                    break;
                case ':':
                    text = Culture.DateTimeFormat.TimeSeparator;
                    charType = CharType.Separator;
                    break;
                case '/':
                    text = Culture.DateTimeFormat.DateSeparator;
                    charType = CharType.Separator;
                    break;
                case '$':
                    text = Culture.NumberFormat.CurrencySymbol;
                    charType = CharType.Separator;
                    break;
                case '<':
                    caseConversion = CaseConversion.ToLower;
                    continue;
                case '>':
                    caseConversion = CaseConversion.ToUpper;
                    continue;
                case '|':
                    caseConversion = CaseConversion.None;
                    continue;
                case '\\':
                    flag = true;
                    charType = CharType.Literal;
                    continue;
                case '&':
                case '0':
                case 'A':
                case 'L':
                    _requiredEditChars++;
                    c = _promptChar;
                    charType = CharType.EditRequired;
                    break;
                case '#':
                case '9':
                case '?':
                case 'C':
                case 'a':
                    _optionalEditChars++;
                    c = _promptChar;
                    charType = CharType.EditOptional;
                    break;
                default:
                    charType = CharType.Literal;
                    break;
                }
            }
            else
            {
                flag = false;
            }
            CharDescriptor charDescriptor = new CharDescriptor(i, charType);
            if (IsEditPosition(charDescriptor))
            {
                charDescriptor.CaseConversion = caseConversion;
            }
            if (charType != CharType.Separator)
            {
                text = c.ToString();
            }
            string text2 = text;
            foreach (char value in text2)
            {
                _testString.Append(value);
                _stringDescriptor.Add(charDescriptor);
                num++;
            }
        }
        _testString.Capacity = _testString.Length;
    }
References System.ComponentModel.MaskedTextProvider._optionalEditChars, System.ComponentModel.MaskedTextProvider._promptChar, System.ComponentModel.MaskedTextProvider._requiredEditChars, System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Text.StringBuilder.Append(), System.ComponentModel.MaskedTextProvider.Culture, System.Globalization.CultureInfo.DateTimeFormat, System.ComponentModel.MaskedTextProvider.IsEditPosition(), System.Text.StringBuilder.Length, System.ComponentModel.MaskedTextProvider.Mask, System.Globalization.CultureInfo.NumberFormat, System.text, and System.value.
Referenced by System.ComponentModel.MaskedTextProvider.MaskedTextProvider().