Terraria: System.ComponentModel.MaskedTextProvider.TestSetString
TestSetString()
bool System.ComponentModel.MaskedTextProvider.TestSetString (string input, int position, out int testPosition, out MaskedTextResultHint resultHint) inline private
Definition at line 1573 of file MaskedTextProvider.cs.
    {
        if (TestString(input, position, out testPosition, out resultHint))
        {
            SetString(input, position);
            return true;
        }
        return false;
    }
References System.input, System.ComponentModel.MaskedTextProvider.SetString(), and System.ComponentModel.MaskedTextProvider.TestString().
Referenced by System.ComponentModel.MaskedTextProvider.Add(), System.ComponentModel.MaskedTextProvider.Replace(), and System.ComponentModel.MaskedTextProvider.Set().