Terraria: System.ComponentModel.MaskedTextProvider.Set
Set() [2/2]
bool System.ComponentModel.MaskedTextProvider.Set (string input, out int testPosition, out MaskedTextResultHint resultHint) inline
Definition at line 1312 of file MaskedTextProvider.cs.
    {
        if (input == null)
        {
            throw new ArgumentNullException("input");
        }
        resultHint = MaskedTextResultHint.Unknown;
        testPosition = 0;
        if (input.Length == 0)
        {
            Clear(out resultHint);
            return true;
        }
        if (!TestSetString(input, testPosition, out testPosition, out resultHint))
        {
            return false;
        }
        int num = FindAssignedEditPositionFrom(testPosition + 1, direction: true);
        if (num != -1)
        {
            ResetString(num, _testString.Length - 1);
        }
        return true;
    }
References System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.Clear(), System.ComponentModel.MaskedTextProvider.FindAssignedEditPositionFrom(), System.input, System.Text.StringBuilder.Length, System.ComponentModel.MaskedTextProvider.ResetString(), and System.ComponentModel.MaskedTextProvider.TestSetString().