Terraria: System.ComponentModel.MaskedTextProvider.SetChar
SetChar() [1/2]
void System.ComponentModel.MaskedTextProvider.SetChar (char input, int position) inline private
Definition at line 1337 of file MaskedTextProvider.cs.
    {
        CharDescriptor charDescriptor = _stringDescriptor[position];
        SetChar(input, position, charDescriptor);
    }
References System.ComponentModel.MaskedTextProvider._stringDescriptor, System.input, and System.ComponentModel.MaskedTextProvider.SetChar().
Referenced by System.ComponentModel.MaskedTextProvider.InsertAtInt(), System.ComponentModel.MaskedTextProvider.RemoveAtInt(), System.ComponentModel.MaskedTextProvider.Replace(), System.ComponentModel.MaskedTextProvider.SetChar(), System.ComponentModel.MaskedTextProvider.SetString(), and System.ComponentModel.MaskedTextProvider.TestSetChar().