Terraria: System.ComponentModel.MaskedTextProvider.TestChar
TestChar()
bool System.ComponentModel.MaskedTextProvider.TestChar (char input, int position, out MaskedTextResultHint resultHint) inline private
Definition at line 1390 of file MaskedTextProvider.cs.
    {
        if (!IsPrintableChar(input))
        {
            resultHint = MaskedTextResultHint.InvalidInput;
            return false;
        }
        CharDescriptor charDescriptor = _stringDescriptor[position];
        if (IsLiteralPosition(charDescriptor))
        {
            if (SkipLiterals && input == _testString[position])
            {
                resultHint = MaskedTextResultHint.CharacterEscaped;
                return true;
            }
            resultHint = MaskedTextResultHint.NonEditPosition;
            return false;
        }
        if (input == _promptChar)
        {
            if (ResetOnPrompt)
            {
                if (IsEditPosition(charDescriptor) && charDescriptor.IsAssigned)
                {
                    resultHint = MaskedTextResultHint.SideEffect;
                }
                else
                {
                    resultHint = MaskedTextResultHint.CharacterEscaped;
                }
                return true;
            }
            if (!AllowPromptAsInput)
            {
                resultHint = MaskedTextResultHint.PromptCharNotAllowed;
                return false;
            }
        }
        if (input == ' ' && ResetOnSpace)
        {
            if (IsEditPosition(charDescriptor) && charDescriptor.IsAssigned)
            {
                resultHint = MaskedTextResultHint.SideEffect;
            }
            else
            {
                resultHint = MaskedTextResultHint.CharacterEscaped;
            }
            return true;
        }
        switch (Mask[charDescriptor.MaskPosition])
        {
        case '#':
            if (!char.IsDigit(input) && input != '-' && input != '+' && input != ' ')
            {
                resultHint = MaskedTextResultHint.DigitExpected;
                return false;
            }
            break;
        case '0':
            if (!char.IsDigit(input))
            {
                resultHint = MaskedTextResultHint.DigitExpected;
                return false;
            }
            break;
        case '9':
            if (!char.IsDigit(input) && input != ' ')
            {
                resultHint = MaskedTextResultHint.DigitExpected;
                return false;
            }
            break;
        case 'L':
            if (!char.IsLetter(input))
            {
                resultHint = MaskedTextResultHint.LetterExpected;
                return false;
            }
            if (!IsAsciiLetter(input) && AsciiOnly)
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        case '?':
            if (!char.IsLetter(input) && input != ' ')
            {
                resultHint = MaskedTextResultHint.LetterExpected;
                return false;
            }
            if (!IsAsciiLetter(input) && AsciiOnly)
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        case '&':
            if (!IsAscii(input) && AsciiOnly)
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        case 'C':
            if (!IsAscii(input) && AsciiOnly && input != ' ')
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        case 'A':
            if (!IsAlphanumeric(input))
            {
                resultHint = MaskedTextResultHint.AlphanumericCharacterExpected;
                return false;
            }
            if (!IsAciiAlphanumeric(input) && AsciiOnly)
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        case 'a':
            if (!IsAlphanumeric(input) && input != ' ')
            {
                resultHint = MaskedTextResultHint.AlphanumericCharacterExpected;
                return false;
            }
            if (!IsAciiAlphanumeric(input) && AsciiOnly)
            {
                resultHint = MaskedTextResultHint.AsciiCharacterExpected;
                return false;
            }
            break;
        }
        if (input == _testString[position] && charDescriptor.IsAssigned)
        {
            resultHint = MaskedTextResultHint.NoEffect;
        }
        else
        {
            resultHint = MaskedTextResultHint.Success;
        }
        return true;
    }
References System.ComponentModel.MaskedTextProvider._promptChar, System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.AllowPromptAsInput, System.ComponentModel.MaskedTextProvider.AsciiOnly, System.input, System.ComponentModel.MaskedTextProvider.IsAciiAlphanumeric(), System.ComponentModel.MaskedTextProvider.IsAlphanumeric(), System.ComponentModel.MaskedTextProvider.IsAscii(), System.ComponentModel.MaskedTextProvider.IsAsciiLetter(), System.ComponentModel.MaskedTextProvider.IsEditPosition(), System.ComponentModel.MaskedTextProvider.IsLiteralPosition(), System.ComponentModel.MaskedTextProvider.IsPrintableChar(), System.ComponentModel.MaskedTextProvider.Mask, System.ComponentModel.MaskedTextProvider.ResetOnPrompt, System.ComponentModel.MaskedTextProvider.ResetOnSpace, and System.ComponentModel.MaskedTextProvider.SkipLiterals.
Referenced by System.ComponentModel.MaskedTextProvider.InsertAtInt(), System.ComponentModel.MaskedTextProvider.RemoveAtInt(), System.ComponentModel.MaskedTextProvider.Replace(), System.ComponentModel.MaskedTextProvider.TestSetChar(), System.ComponentModel.MaskedTextProvider.TestString(), and System.ComponentModel.MaskedTextProvider.VerifyChar().