Terraria: System.ComponentModel.MaskedTextProvider.MaskedTextProvider
MaskedTextProvider() [7/7]
System.ComponentModel.MaskedTextProvider.MaskedTextProvider (string mask, CultureInfo? culture, bool allowPromptAsInput, char promptChar, char passwordChar, bool restrictToAscii) inline
Definition at line 301 of file MaskedTextProvider.cs.
    {
        if (string.IsNullOrEmpty(mask))
        {
            throw new ArgumentException(System.SR.MaskedTextProviderMaskNullOrEmpty, "mask");
        }
        foreach (char c in mask)
        {
            if (!IsPrintableChar(c))
            {
                throw new ArgumentException(System.SR.MaskedTextProviderMaskInvalidChar);
            }
        }
        if (culture == null)
        {
            culture = CultureInfo.CurrentCulture;
        }
        _flagState = default(BitVector32);
        Mask = mask;
        _promptChar = promptChar;
        _passwordChar = passwordChar;
        if (culture.IsNeutralCulture)
        {
            CultureInfo[] cultures = CultureInfo.GetCultures(CultureTypes.SpecificCultures);
            foreach (CultureInfo cultureInfo in cultures)
            {
                if (culture.Equals(cultureInfo.Parent))
                {
                    Culture = cultureInfo;
                    break;
                }
            }
            if (Culture == null)
            {
                Culture = CultureInfo.InvariantCulture;
            }
        }
        else
        {
            Culture = culture;
        }
        if (!Culture.IsReadOnly)
        {
            Culture = CultureInfo.ReadOnly(Culture);
        }
        _flagState[s_ALLOW_PROMPT_AS_INPUT] = allowPromptAsInput;
        _flagState[s_ASCII_ONLY] = restrictToAscii;
        _flagState[s_INCLUDE_PROMPT] = false;
        _flagState[s_INCLUDE_LITERALS] = true;
        _flagState[s_RESET_ON_PROMPT] = true;
        _flagState[s_SKIP_SPACE] = true;
        _flagState[s_RESET_ON_LITERALS] = true;
        Initialize();
    }
References System.ComponentModel.MaskedTextProvider._flagState, System.ComponentModel.MaskedTextProvider._passwordChar, System.ComponentModel.MaskedTextProvider._promptChar, System.ComponentModel.MaskedTextProvider.Culture, System.culture, System.Globalization.CultureInfo.CurrentCulture, System.Globalization.CultureInfo.GetCultures(), System.ComponentModel.MaskedTextProvider.Initialize(), System.Globalization.CultureInfo.InvariantCulture, System.ComponentModel.MaskedTextProvider.IsPrintableChar(), System.Globalization.CultureInfo.IsReadOnly, System.ComponentModel.MaskedTextProvider.Mask, System.SR.MaskedTextProviderMaskInvalidChar, System.SR.MaskedTextProviderMaskNullOrEmpty, System.Globalization.CultureInfo.ReadOnly(), System.ComponentModel.MaskedTextProvider.s_ALLOW_PROMPT_AS_INPUT, System.ComponentModel.MaskedTextProvider.s_ASCII_ONLY, System.ComponentModel.MaskedTextProvider.s_INCLUDE_LITERALS, System.ComponentModel.MaskedTextProvider.s_INCLUDE_PROMPT, System.ComponentModel.MaskedTextProvider.s_RESET_ON_LITERALS, System.ComponentModel.MaskedTextProvider.s_RESET_ON_PROMPT, and System.ComponentModel.MaskedTextProvider.s_SKIP_SPACE.