Terraria: System.ComponentModel.MaskedTextProvider.ResetChar
ResetChar()
void System.ComponentModel.MaskedTextProvider.ResetChar (int testPosition) inline private
Definition at line 1275 of file MaskedTextProvider.cs.
    {
        CharDescriptor charDescriptor = _stringDescriptor[testPosition];
        if (IsEditPosition(testPosition) && charDescriptor.IsAssigned)
        {
            charDescriptor.IsAssigned = false;
            _testString[testPosition] = _promptChar;
            AssignedEditPositionCount--;
            if (charDescriptor.CharType == CharType.EditRequired)
            {
                _requiredCharCount--;
            }
        }
    }
References System.ComponentModel.MaskedTextProvider._promptChar, System.ComponentModel.MaskedTextProvider._requiredCharCount, System.ComponentModel.MaskedTextProvider._stringDescriptor, System.ComponentModel.MaskedTextProvider._testString, System.ComponentModel.MaskedTextProvider.AssignedEditPositionCount, and System.ComponentModel.MaskedTextProvider.IsEditPosition().
Referenced by System.ComponentModel.MaskedTextProvider.Clear(), System.ComponentModel.MaskedTextProvider.InsertAtInt(), System.ComponentModel.MaskedTextProvider.Remove(), System.ComponentModel.MaskedTextProvider.RemoveAtInt(), System.ComponentModel.MaskedTextProvider.ResetString(), and System.ComponentModel.MaskedTextProvider.SetChar().