Terraria: Terraria.GameContent.Events.Sandstorm.UpdateTime
UpdateTime()
static void Terraria.GameContent.Events.Sandstorm.UpdateTime () inline static
Definition at line 34 of file Sandstorm.cs.
    {
        if (Main.netMode != 1)
        {
            if (Happening)
            {
                if (TimeLeft > 86400)
                {
                    TimeLeft = 0;
                }
                TimeLeft -= Main.dayRate;
                if (!HasSufficientWind())
                {
                    TimeLeft -= 15 * Main.dayRate;
                }
                if (Main.windSpeedCurrent == 0f)
                {
                    TimeLeft = 0;
                }
                if (TimeLeft <= 0)
                {
                    StopSandstorm();
                }
            }
            else
            {
                int num = 21600;
                num = ((!Main.hardMode) ? (num * 3) : (num * 2));
                if (HasSufficientWind())
                {
                    for (int i = 0; i < Main.dayRate; i++)
                    {
                        if (Main.rand.Next(num) == 0)
{
                            StartSandstorm();
                        }
                    }
                }
            }
            if (Main.rand.Next(18000) == 0)
            {
                ChangeSeverityIntentions();
            }
        }
        UpdateSeverity();
    }
References Terraria.GameContent.Events.Sandstorm.ChangeSeverityIntentions(), Terraria.Main.dayRate, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.Main.hardMode, Terraria.GameContent.Events.Sandstorm.HasSufficientWind(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.GameContent.Events.Sandstorm.StartSandstorm(), Terraria.GameContent.Events.Sandstorm.StopSandstorm(), Terraria.GameContent.Events.Sandstorm.TimeLeft, Terraria.GameContent.Events.Sandstorm.UpdateSeverity(), and Terraria.Main.windSpeedCurrent.
Referenced by Terraria.Main.UpdateTime().