Terraria: Terraria.GameContent.Events.Sandstorm.HandleEffectAndSky
HandleEffectAndSky()
static void Terraria.GameContent.Events.Sandstorm.HandleEffectAndSky (bool toState) inline static
    {
        if (toState != _effectsUp)
        {
            _effectsUp = toState;
            Vector2 center = Main.player[Main.myPlayer].Center;
            if (_effectsUp)
            {
                SkyManager.Instance.Activate("Sandstorm", center);
                Filters.Scene.Activate("Sandstorm", center);
                Overlays.Scene.Activate("Sandstorm", center);
            }
            else
            {
                SkyManager.Instance.Deactivate("Sandstorm");
                Filters.Scene.Deactivate("Sandstorm");
                Overlays.Scene.Deactivate("Sandstorm");
            }
        }
    }
References Terraria.GameContent.Events.Sandstorm._effectsUp, Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Entity.Center, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Graphics.Effects.Filters.Scene, and Terraria.Graphics.Effects.Overlays.Scene.
Referenced by Terraria.GameContent.Events.Sandstorm.EmitDust().