Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer
GenerateGetSerializer()
void System.Xml.Serialization.XmlSerializationILGen.GenerateGetSerializer (Dictionary< string, string > serializers, XmlMapping[] xmlMappings, TypeBuilder serializerContractTypeBuilder) inline private inherited
Definition at line 374 of file XmlSerializationILGen.cs.
    {
        ilg = new CodeGenerator(serializerContractTypeBuilder);
        ilg.BeginMethod(typeof(XmlSerializer), "GetSerializer", new Type[1] { typeof(Type) }, new string[1] { "type" }, MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        for (int i = 0; i < xmlMappings.Length; i++)
        {
            if (xmlMappings[i] is XmlTypeMapping)
            {
                Type type = xmlMappings[i].Accessor.Mapping.TypeDesc.Type;
                if (!(type == null) && (type.IsPublic || type.IsNestedPublic) && !type.IsGenericType && !type.ContainsGenericParameters)
                {
                    ilg.Ldarg("type");
                    ilg.Ldc(type);
                    ilg.If(Cmp.EqualTo);
                    ConstructorInfo constructor = CreatedTypes[serializers[xmlMappings[i].Key]].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
                    ilg.New(constructor);
                    ilg.Stloc(ilg.ReturnLocal);
                    ilg.Br(ilg.ReturnLabel);
                    ilg.EndIf();
                }
            }
        }
        ilg.Load(null);
        ilg.Stloc(ilg.ReturnLocal);
        ilg.Br(ilg.ReturnLabel);
        ilg.MarkLabel(ilg.ReturnLabel);
        ilg.Ldloc(ilg.ReturnLocal);
        ilg.EndMethod();
    }
References System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Text.RegularExpressions.i, System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), and System.type.