Terraria: System.Xml.Serialization.XmlSerializationILGen.NewRegex
NewRegex()
static Regex System.Xml.Serialization.XmlSerializationILGen.NewRegex (string pattern) inline static package inherited
Definition at line 102 of file XmlSerializationILGen.cs.
    {
        Regex value;
        lock (s_regexs)
        {
            if (!s_regexs.TryGetValue(pattern, out value))
            {
                value = new Regex(pattern);
                s_regexs.Add(pattern, value);
            }
        }
        return value;
    }
References System.Xml.Dictionary, System.Text.RegularExpressions.pattern, System.Xml.Serialization.XmlSerializationILGen.s_regexs, and System.value.
Referenced by System.Xml.Serialization.XmlSerializationReaderILGen.ILGenElseString(), System.Xml.Serialization.XmlSerializationReaderILGen.ILGenParamsReadSource(), System.Xml.Serialization.XmlSerializationReaderILGen.ILGenParamsReadSource(), System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceBegin(), and System.Xml.Serialization.XmlSerializationReaderILGen.WriteSourceEnd().