Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers
GenerateTypedSerializers()
FieldBuilder System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializers (Dictionary< string, string > serializers, TypeBuilder serializerContractTypeBuilder) inline private inherited
Definition at line 352 of file XmlSerializationILGen.cs.
    {
        string privateName = "typedSerializers";
        FieldBuilder fieldBuilder = GenerateHashtableGetBegin(privateName, "TypedSerializers", serializerContractTypeBuilder);
        MethodInfo method = typeof(Hashtable).GetMethod("Add", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
        {
            typeof(object),
            typeof(object)
        });
        foreach (string key in serializers.Keys)
        {
            ConstructorInfo constructor = CreatedTypes[serializers[key]].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldloc(typeof(Hashtable), "_tmp");
            ilg.Ldstr(GetCSharpString(key));
            ilg.New(constructor);
            ilg.Call(method);
        }
        GenerateHashtableGetEnd(fieldBuilder);
        return fieldBuilder;
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Type.EmptyTypes, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), and System.Xml.Serialization.CodeGenerator.New().