Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer
GenerateTypedSerializer()
string System.Xml.Serialization.XmlSerializationILGen.GenerateTypedSerializer (string readMethod, string writeMethod, XmlMapping mapping, CodeIdentifiers classes, string baseSerializer, string readerClass, string writerClass) inline package inherited
Definition at line 286 of file XmlSerializationILGen.cs.
    {
        string text = CodeIdentifier.MakeValid(Accessor.UnescapeName(mapping.Accessor.Mapping.TypeDesc.Name));
        text = classes.AddUnique(text + "Serializer", mapping);
        TypeBuilder typeBuilder = CodeGenerator.CreateTypeBuilder(_moduleBuilder, CodeIdentifier.GetCSharpName(text), TypeAttributes.Public | TypeAttributes.Sealed | TypeAttributes.BeforeFieldInit, CreatedTypes[baseSerializer], Type.EmptyTypes);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(bool), "CanDeserialize", new Type[1] { typeof(XmlReader) }, new string[1] { "xmlReader" }, MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        if (mapping.Accessor.Any)
        {
            ilg.Ldc(boolVar: true);
            ilg.Stloc(ilg.ReturnLocal);
            ilg.Br(ilg.ReturnLabel);
        }
        else
        {
            MethodInfo method = typeof(XmlReader).GetMethod("IsStartElement", BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[2]
            {
                typeof(string),
                typeof(string)
            });
            ilg.Ldarg(ilg.GetArg("xmlReader"));
            ilg.Ldstr(GetCSharpString(mapping.Accessor.Name));
            ilg.Ldstr(GetCSharpString(mapping.Accessor.Namespace));
            ilg.Call(method);
            ilg.Stloc(ilg.ReturnLocal);
            ilg.Br(ilg.ReturnLabel);
        }
        ilg.MarkLabel(ilg.ReturnLabel);
        ilg.Ldloc(ilg.ReturnLocal);
        ilg.EndMethod();
        if (writeMethod != null)
        {
            ilg = new CodeGenerator(typeBuilder);
            ilg.BeginMethod(typeof(void), "Serialize", new Type[2]
            {
                typeof(object),
                typeof(XmlSerializationWriter)
            }, new string[2] { "objectToSerialize", "writer" }, MethodAttributes.Family | MethodAttributes.Virtual | MethodAttributes.HideBySig);
            MethodInfo method2 = CreatedTypes[writerClass].GetMethod(writeMethod, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { (mapping is XmlMembersMapping) ? typeof(object[]) : typeof(object) });
            ilg.Ldarg("writer");
            ilg.Castclass(CreatedTypes[writerClass]);
            ilg.Ldarg("objectToSerialize");
            if (mapping is XmlMembersMapping)
            {
                ilg.ConvertValue(typeof(object), typeof(object[]));
            }
            ilg.Call(method2);
            ilg.EndMethod();
        }
        if (readMethod != null)
        {
            ilg = new CodeGenerator(typeBuilder);
            ilg.BeginMethod(typeof(object), "Deserialize", new Type[1] { typeof(XmlSerializationReader) }, new string[1] { "reader" }, MethodAttributes.Family | MethodAttributes.Virtual | MethodAttributes.HideBySig);
            MethodInfo method3 = CreatedTypes[readerClass].GetMethod(readMethod, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
            ilg.Ldarg("reader");
            ilg.Castclass(CreatedTypes[readerClass]);
            ilg.Call(method3);
            ilg.EndMethod();
        }
        typeBuilder.DefineDefaultConstructor(MethodAttributes.Public | MethodAttributes.HideBySig);
        Type type = typeBuilder.CreateTypeInfo().AsType();
        CreatedTypes.Add(type.Name, type);
        return type.Name;
    }
References System.Xml.Serialization.XmlSerializationILGen._moduleBuilder, System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Br(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.Castclass(), System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Serialization.XmlSerializationILGen.CreatedTypes, System.Xml.Serialization.CodeGenerator.CreateTypeBuilder(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeGenerator.GetArg(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Ldstr(), System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Serialization.CodeGenerator.MarkLabel(), System.Xml.Serialization.CodeGenerator.ReturnLabel, System.Xml.Serialization.CodeGenerator.ReturnLocal, System.Xml.Serialization.CodeGenerator.Stloc(), System.text, System.Xml.Serialization.XmlSerializationILGen.typeBuilder, and System.Xml.Serialization.Accessor.UnescapeName().