Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract
GenerateSerializerContract()
void System.Xml.Serialization.XmlSerializationILGen.GenerateSerializerContract (string className, XmlMapping[] xmlMappings, Type[] types, string readerType, string[] readMethods, string writerType, string[] writerMethods, Dictionary< string, string > serializers) inline package inherited
Definition at line 405 of file XmlSerializationILGen.cs.
    {
        TypeBuilder typeBuilder = CodeGenerator.CreateTypeBuilder(_moduleBuilder, "XmlSerializerContract", TypeAttributes.Public | TypeAttributes.BeforeFieldInit, typeof(XmlSerializerImplementation), Type.EmptyTypes);
        ilg = new CodeGenerator(typeBuilder);
        PropertyBuilder propertyBuilder = typeBuilder.DefineProperty("Reader", PropertyAttributes.None, typeof(XmlSerializationReader), null, null, null, null, null);
        ilg.BeginMethod(typeof(XmlSerializationReader), "get_Reader", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig | MethodAttributes.SpecialName);
        propertyBuilder.SetGetMethod(ilg.MethodBuilder);
        ConstructorInfo constructor = CreatedTypes[readerType].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.New(constructor);
        ilg.EndMethod();
        ilg = new CodeGenerator(typeBuilder);
        propertyBuilder = typeBuilder.DefineProperty("Writer", PropertyAttributes.None, typeof(XmlSerializationWriter), null, null, null, null, null);
        ilg.BeginMethod(typeof(XmlSerializationWriter), "get_Writer", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig | MethodAttributes.SpecialName);
        propertyBuilder.SetGetMethod(ilg.MethodBuilder);
        constructor = CreatedTypes[writerType].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.New(constructor);
        ilg.EndMethod();
        FieldBuilder memberInfo = GeneratePublicMethods("readMethods", "ReadMethods", readMethods, xmlMappings, typeBuilder);
        FieldBuilder memberInfo2 = GeneratePublicMethods("writeMethods", "WriteMethods", writerMethods, xmlMappings, typeBuilder);
        FieldBuilder memberInfo3 = GenerateTypedSerializers(serializers, typeBuilder);
        GenerateSupportedTypes(types, typeBuilder);
        GenerateGetSerializer(serializers, xmlMappings, typeBuilder);
        ConstructorInfo constructor2 = typeof(XmlSerializerImplementation).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(void), ".ctor", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Public | MethodAttributes.HideBySig | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);
        ilg.Ldarg(0);
        ilg.Load(null);
        ilg.StoreMember(memberInfo);
        ilg.Ldarg(0);
        ilg.Load(null);
        ilg.StoreMember(memberInfo2);
        ilg.Ldarg(0);
        ilg.Load(null);
        ilg.StoreMember(memberInfo3);
        ilg.Ldarg(0);
        ilg.Call(constructor2);
        ilg.EndMethod();
        Type type = typeBuilder.CreateTypeInfo().AsType();
        CreatedTypes.Add(type.Name, type);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.TypeInfo.AsType(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Serialization.CodeGenerator.CreateTypeBuilder(), System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.TypeBuilder.DefineProperty(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.MethodBuilder, System.Xml.Serialization.CodeGenerator.New(), System.Xml.Serialization.CodeGenerator.StoreMember(), and System.type.