Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin
GenerateHashtableGetBegin()
FieldBuilder System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin (string privateName, string publicName, TypeBuilder serializerContractTypeBuilder) inline package inherited
Definition at line 180 of file XmlSerializationILGen.cs.
    {
        FieldBuilder fieldBuilder = serializerContractTypeBuilder.DefineField(privateName, typeof(Hashtable), FieldAttributes.Private);
        ilg = new CodeGenerator(serializerContractTypeBuilder);
        PropertyBuilder propertyBuilder = serializerContractTypeBuilder.DefineProperty(publicName, PropertyAttributes.None, CallingConventions.HasThis, typeof(Hashtable), null, null, null, null, null);
        ilg.BeginMethod(typeof(Hashtable), "get_" + publicName, Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig | MethodAttributes.SpecialName);
        propertyBuilder.SetGetMethod(ilg.MethodBuilder);
        ilg.Ldarg(0);
        ilg.LoadMember(fieldBuilder);
        ilg.Load(null);
        ilg.If(Cmp.EqualTo);
        ConstructorInfo constructor = typeof(Hashtable).GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        LocalBuilder local = ilg.DeclareLocal(typeof(Hashtable), "_tmp");
        ilg.New(constructor);
        ilg.Stloc(local);
        return fieldBuilder;
    }
References System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.CodeGenerator.DeclareLocal(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.Xml.Serialization.CodeGenerator.MethodBuilder, System.Xml.Serialization.CodeGenerator.New(), and System.Xml.Serialization.CodeGenerator.Stloc().
Referenced by System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods().