Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd
GenerateHashtableGetEnd()
void System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd (FieldBuilder fieldBuilder) inline package inherited
Definition at line 199 of file XmlSerializationILGen.cs.
    {
        ilg.Ldarg(0);
        ilg.LoadMember(fieldBuilder);
        ilg.Load(null);
        ilg.If(Cmp.EqualTo);
        ilg.Ldarg(0);
        ilg.Ldloc(typeof(Hashtable), "_tmp");
        ilg.StoreMember(fieldBuilder);
        ilg.EndIf();
        ilg.EndIf();
        ilg.Ldarg(0);
        ilg.LoadMember(fieldBuilder);
        ilg.GotoMethodEnd();
        ilg.EndMethod();
    }
References System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldloc(), System.Xml.Serialization.CodeGenerator.Load(), System.Xml.Serialization.CodeGenerator.LoadMember(), and System.Xml.Serialization.CodeGenerator.StoreMember().
Referenced by System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods().