Terraria: System.Xml.Serialization.XmlSerializationILGen.ILGenLoad
ILGenLoad() [2/2]
void System.Xml.Serialization.XmlSerializationILGen.ILGenLoad (string source, Type type) inline package inherited
Definition at line 462 of file XmlSerializationILGen.cs.
    {
        if (source.StartsWith("o.@", StringComparison.Ordinal))
        {
            MemberInfo memberInfo = memberInfos[source.Substring(3)];
            ilg.LoadMember(ilg.GetVariable("o"), memberInfo);
            if (type != null)
            {
                Type source2 = ((memberInfo is FieldInfo) ? ((FieldInfo)memberInfo).FieldType : ((PropertyInfo)memberInfo).PropertyType);
                ilg.ConvertValue(source2, type);
            }
        }
        else
        {
            SourceInfo sourceInfo = new SourceInfo(source, null, null, null, ilg);
            sourceInfo.Load(type);
        }
    }
References System.Xml.Serialization.CodeGenerator.ConvertValue(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.GetVariable(), System.Xml.Serialization.CodeGenerator.LoadMember(), System.source, and System.type.