Terraria: System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods
GeneratePublicMethods()
FieldBuilder System.Xml.Serialization.XmlSerializationILGen.GeneratePublicMethods (string privateName, string publicName, string[] methods, XmlMapping[] xmlMappings, TypeBuilder serializerContractTypeBuilder) inline package inherited
Definition at line 217 of file XmlSerializationILGen.cs.
    {
        FieldBuilder fieldBuilder = GenerateHashtableGetBegin(privateName, publicName, serializerContractTypeBuilder);
        if (methods != null && methods.Length != 0 && xmlMappings != null && xmlMappings.Length == methods.Length)
        {
            MethodInfo method = typeof(Hashtable).GetMethod("set_Item", new Type[2]
            {
                typeof(object),
                typeof(object)
            });
            for (int i = 0; i < methods.Length; i++)
            {
                if (methods[i] != null)
                {
                    ilg.Ldloc(typeof(Hashtable), "_tmp");
                    ilg.Ldstr(GetCSharpString(xmlMappings[i].Key));
                    ilg.Ldstr(GetCSharpString(methods[i]));
                    ilg.Call(method);
                }
            }
        }
        GenerateHashtableGetEnd(fieldBuilder);
        return fieldBuilder;
    }
References System.Xml.Serialization.CodeGenerator.Call(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetBegin(), System.Xml.Serialization.XmlSerializationILGen.GenerateHashtableGetEnd(), System.Xml.Serialization.XmlSerializationILGen.GetCSharpString(), System.Text.RegularExpressions.i, System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldloc(), and System.Xml.Serialization.CodeGenerator.Ldstr().