Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes
GenerateSupportedTypes()
void System.Xml.Serialization.XmlSerializationILGen.GenerateSupportedTypes (Type[] types, TypeBuilder serializerContractTypeBuilder) inline package inherited
Definition at line 242 of file XmlSerializationILGen.cs.
    {
        ilg = new CodeGenerator(serializerContractTypeBuilder);
        ilg.BeginMethod(typeof(bool), "CanSerialize", new Type[1] { typeof(Type) }, new string[1] { "type" }, MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        HashSet<Type> hashSet = new HashSet<Type>();
        foreach (Type type in types)
        {
            if (!(type == null) && (type.IsPublic || type.IsNestedPublic) && hashSet.Add(type) && !type.IsGenericType && !type.ContainsGenericParameters)
            {
                ilg.Ldarg("type");
                ilg.Ldc(type);
                ilg.If(Cmp.EqualTo);
                ilg.Ldc(boolVar: true);
                ilg.GotoMethodEnd();
                ilg.EndIf();
            }
        }
        ilg.Ldc(boolVar: false);
        ilg.GotoMethodEnd();
        ilg.EndMethod();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Dictionary, System.Xml.Serialization.CodeGenerator.EndIf(), System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeGenerator.GotoMethodEnd(), System.Xml.Serialization.CodeGenerator.If(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeGenerator.Ldarg(), System.Xml.Serialization.CodeGenerator.Ldc(), and System.type.