Terraria: System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer
GenerateBaseSerializer()
string System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer (string baseSerializer, string readerClass, string writerClass, CodeIdentifiers classes) inline package inherited
Definition at line 265 of file XmlSerializationILGen.cs.
    {
        baseSerializer = CodeIdentifier.MakeValid(baseSerializer);
        baseSerializer = classes.AddUnique(baseSerializer, baseSerializer);
        TypeBuilder typeBuilder = CodeGenerator.CreateTypeBuilder(_moduleBuilder, CodeIdentifier.GetCSharpName(baseSerializer), TypeAttributes.Public | TypeAttributes.Abstract | TypeAttributes.BeforeFieldInit, typeof(XmlSerializer), Type.EmptyTypes);
        ConstructorInfo constructor = CreatedTypes[readerClass].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg = new CodeGenerator(typeBuilder);
        ilg.BeginMethod(typeof(XmlSerializationReader), "CreateReader", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Family | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        ilg.New(constructor);
        ilg.EndMethod();
        ConstructorInfo constructor2 = CreatedTypes[writerClass].GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes);
        ilg.BeginMethod(typeof(XmlSerializationWriter), "CreateWriter", Type.EmptyTypes, Array.Empty<string>(), MethodAttributes.Family | MethodAttributes.Virtual | MethodAttributes.HideBySig);
        ilg.New(constructor2);
        ilg.EndMethod();
        typeBuilder.DefineDefaultConstructor(MethodAttributes.Family | MethodAttributes.HideBySig | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName);
        Type type = typeBuilder.CreateTypeInfo().AsType();
        CreatedTypes.Add(type.Name, type);
        return baseSerializer;
    }
References System.Xml.Serialization.XmlSerializationILGen._moduleBuilder, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.TypeInfo.AsType(), System.Xml.Serialization.CodeGenerator.BeginMethod(), System.Xml.Serialization.XmlSerializationILGen.CreatedTypes, System.Xml.Serialization.CodeGenerator.CreateTypeBuilder(), System.Reflection.Emit.TypeBuilder.CreateTypeInfo(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), System.Xml.Dictionary, System.Type.EmptyTypes, System.Xml.Serialization.CodeGenerator.EndMethod(), System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Xml.Serialization.XmlSerializationILGen.ilg, System.Xml.Serialization.CodeIdentifier.MakeValid(), System.Xml.Serialization.CodeGenerator.New(), System.type, and System.Xml.Serialization.XmlSerializationILGen.typeBuilder.