Terraria: System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter
CreateConverter()
override JsonConverter System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter (Type typeToConvert, JsonSerializerOptions options) inline
Definition at line 25 of file ObjectConverterFactory.cs.
    {
        if (typeToConvert.IsKeyValuePair())
        {
            return CreateKeyValuePairConverter(typeToConvert, options);
        }
        if (!typeToConvert.TryGetDeserializationConstructor(_useDefaultConstructorInUnannotatedStructs, out var deserializationCtor))
        {
            ThrowHelper.ThrowInvalidOperationException_SerializationDuplicateTypeAttribute<JsonConstructorAttribute>(typeToConvert);
        }
        ParameterInfo[] array = deserializationCtor?.GetParameters();
        Type type;
        if (deserializationCtor == null || typeToConvert.IsAbstract || array.Length == 0)
        {
            type = typeof(ObjectDefaultConverter<>).MakeGenericType(typeToConvert);
        }
        else
        {
            int num = array.Length;
            if (num <= 4)
            {
                Type objectType = JsonTypeInfo.ObjectType;
                Type[] array2 = new Type[5] { typeToConvert, null, null, null, null };
                for (int i = 0; i < 4; i++)
                {
                    if (i < num)
                    {
                        array2[i + 1] = array[i].ParameterType;
                    }
                    else
                    {
                        array2[i + 1] = objectType;
                    }
                }
                type = typeof(SmallObjectWithParameterizedConstructorConverter<, , , , >).MakeGenericType(array2);
            }
            else
            {
                type = typeof(LargeObjectWithParameterizedConstructorConverterWithReflection<>).MakeGenericType(typeToConvert);
            }
        }
        JsonConverter jsonConverter = (JsonConverter)Activator.CreateInstance(type, BindingFlags.Instance | BindingFlags.Public, null, null, null);
        jsonConverter.ConstructorInfo = deserializationCtor;
        return jsonConverter;
    }
References System.Text.Json.Serialization.JsonConverter< T >.JsonConverter(), System.Text.Json.Serialization.Converters.ObjectConverterFactory._useDefaultConstructorInUnannotatedStructs, System.array, System.Activator.CreateInstance(), System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateKeyValuePairConverter(), System.Text.Json.Dictionary, System.Type.MakeGenericType(), System.Text.Json.Serialization.Metadata.JsonTypeInfo< T >.ObjectType, System.options, System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationDuplicateTypeAttribute(), and System.type.