Terraria: System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateKeyValuePairConverter
CreateKeyValuePairConverter()
JsonConverter System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateKeyValuePairConverter (Type type, JsonSerializerOptions options) inline private
Definition at line 71 of file ObjectConverterFactory.cs.
    {
        Type type2 = type.GetGenericArguments()[0];
        Type type3 = type.GetGenericArguments()[1];
        JsonConverter jsonConverter = (JsonConverter)Activator.CreateInstance(typeof(KeyValuePairConverter<, >).MakeGenericType(type2, type3), BindingFlags.Instance | BindingFlags.Public, null, null, null);
        jsonConverter.Initialize(options);
        return jsonConverter;
    }
References System.Text.Json.Serialization.JsonConverter< T >.JsonConverter(), System.Activator.CreateInstance(), System.Text.Json.Dictionary, System.Type.GetGenericArguments(), System.options, and System.type.
Referenced by System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter().