Terraria: System.Xml.HtmlEncodedRawTextWriter.WriteChars
WriteChars()
unsafe override void System.Xml.HtmlEncodedRawTextWriter.WriteChars (char[] buffer, int index, int count) inline inherited
Definition at line 280 of file HtmlEncodedRawTextWriter.cs.
    {
        if (_trackTextContent && !_inTextContent)
        {
            ChangeTextContentMark(value: true);
        }
        fixed (char* ptr = &buffer[index])
        {
            if (_inAttributeValue)
            {
                WriteAttributeTextBlock(ptr, ptr + count);
            }
            else
            {
                WriteElementTextBlock(ptr, ptr + count);
            }
        }
    }
References System.Xml.XmlEncodedRawTextWriter._inAttributeValue, System.Xml.XmlEncodedRawTextWriter._inTextContent, System.Xml.XmlEncodedRawTextWriter._trackTextContent, System.buffer, System.Xml.XmlEncodedRawTextWriter.ChangeTextContentMark(), System.count, System.Xml.Dictionary, System.index, System.value, System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(), and System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock().