Terraria: System.Xml.HtmlEncodedRawTextWriter.WriteMetaElement
WriteMetaElement()
void System.Xml.HtmlEncodedRawTextWriter.WriteMetaElement () inline protected inherited
Definition at line 313 of file HtmlEncodedRawTextWriter.cs.
    {
        RawText("<META http-equiv=\"Content-Type\"");
        if (_mediaType == null)
        {
            _mediaType = "text/html";
        }
        RawText(" content=\"");
        RawText(_mediaType);
        RawText("; charset=");
        RawText(_encoding.WebName);
        RawText("\">");
    }
References System.Xml.XmlEncodedRawTextWriter._encoding, System.Xml.HtmlEncodedRawTextWriter._mediaType, and System.Xml.XmlEncodedRawTextWriter.RawText().
Referenced by System.Xml.HtmlEncodedRawTextWriter.StartElementContent(), and System.Xml.HtmlEncodedRawTextWriterIndent.StartElementContent().