Terraria: System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeText
WriteHtmlAttributeText()
unsafe void System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeText (char * pSrc, char * pSrcEnd) inline private inherited
Definition at line 365 of file HtmlEncodedRawTextWriter.cs.
    {
        if (_endsWithAmpersand)
        {
            if (pSrcEnd - pSrc > 0 && *pSrc != '{')
            {
                OutputRestAmps();
            }
            _endsWithAmpersand = false;
        }
        fixed (char* ptr = _bufChars)
        {
            char* pDst = ptr + _bufPos;
            char c = '\0';
            while (true)
            {
                char* ptr2 = pDst + (pSrcEnd - pSrc);
                if (ptr2 > ptr + _bufLen)
                {
                    ptr2 = ptr + _bufLen;
                }
                while (pDst < ptr2 && XmlCharType.IsAttributeValueChar(c = *pSrc))
                {
                    *(pDst++) = c;
                    pSrc++;
                }
                if (pSrc >= pSrcEnd)
                {
                    break;
                }
                if (pDst >= ptr2)
                {
                    _bufPos = (int)(pDst - ptr);
                    FlushBuffer();
                    pDst = ptr + 1;
                    continue;
                }
                switch (c)
                {
                case '&':
                    if (pSrc + 1 == pSrcEnd)
                    {
                        _endsWithAmpersand = true;
                    }
                    else if (pSrc[1] != '{')
                    {
                        pDst = XmlEncodedRawTextWriter.AmpEntity(pDst);
                        break;
                    }
                    *(pDst++) = c;
                    break;
                case '"':
                    pDst = XmlEncodedRawTextWriter.QuoteEntity(pDst);
                    break;
                case '\t':
                case '\'':
                case '<':
                case '>':
                    *(pDst++) = c;
                    break;
                case '\r':
                    pDst = XmlEncodedRawTextWriter.CarriageReturnEntity(pDst);
                    break;
                case '\n':
                    pDst = XmlEncodedRawTextWriter.LineFeedEntity(pDst);
                    break;
                default:
                    EncodeChar(ref pSrc, pSrcEnd, ref pDst);
                    continue;
                }
                pSrc++;
            }
            _bufPos = (int)(pDst - ptr);
        }
    }
References System.Xml.XmlEncodedRawTextWriter._bufChars, System.Xml.XmlEncodedRawTextWriter._bufLen, System.Xml.XmlEncodedRawTextWriter._bufPos, System.Xml.HtmlEncodedRawTextWriter._endsWithAmpersand, System.Xml.XmlEncodedRawTextWriter.AmpEntity(), System.Xml.XmlEncodedRawTextWriter.CarriageReturnEntity(), System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.EncodeChar(), System.Xml.XmlEncodedRawTextWriter.FlushBuffer(), System.Xml.XmlCharType.IsAttributeValueChar(), System.Xml.XmlEncodedRawTextWriter.LineFeedEntity(), System.Xml.HtmlEncodedRawTextWriter.OutputRestAmps(), and System.Xml.XmlEncodedRawTextWriter.QuoteEntity().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteHtmlAttributeTextBlock().