Terraria: System.Xml.HtmlEncodedRawTextWriter.WriteHtmlElementTextBlock
WriteHtmlElementTextBlock()
unsafe void System.Xml.HtmlEncodedRawTextWriter.WriteHtmlElementTextBlock (char * pSrc, char * pSrcEnd) inline protected inherited
Definition at line 327 of file HtmlEncodedRawTextWriter.cs.
    {
        if ((_currentElementProperties & ElementProperties.NO_ENTITIES) != 0)
        {
            RawText(pSrc, pSrcEnd);
        }
        else
        {
            WriteElementTextBlock(pSrc, pSrcEnd);
        }
    }
References System.Xml.HtmlEncodedRawTextWriter._currentElementProperties, System.Xml.Dictionary, System.Xml.XmlEncodedRawTextWriter.RawText(), and System.Xml.XmlEncodedRawTextWriter.WriteElementTextBlock().
Referenced by System.Xml.HtmlEncodedRawTextWriter.WriteString().