Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement
WriteElement()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement (string source, string arrayName, string choiceSource, ElementAccessor element, ChoiceIdentifierAccessor choice, string checkSpecified, bool checkForNull, bool readOnly, int fixupIndex, int elementIndex) inline private
Definition at line 2613 of file XmlSerializationReaderCodeGen.cs.
    {
        if (checkSpecified != null && checkSpecified.Length > 0)
        {
            base.Writer.Write(checkSpecified);
            base.Writer.WriteLine(" = true;");
        }
        if (element.Mapping is ArrayMapping)
        {
            WriteArray(source, arrayName, (ArrayMapping)element.Mapping, readOnly, element.IsNullable, fixupIndex);
        }
        else if (element.Mapping is NullableMapping)
        {
            string s = ReferenceMapping(element.Mapping);
            WriteSourceBegin(source);
            base.Writer.Write(s);
            base.Writer.Write("(true)");
            WriteSourceEnd(source);
            base.Writer.WriteLine(";");
        }
        else if (!element.Mapping.IsSoap && element.Mapping is PrimitiveMapping)
        {
            if (element.IsNullable)
            {
                base.Writer.WriteLine("if (ReadNull()) {");
                base.Writer.Indent++;
                WriteSourceBegin(source);
                if (element.Mapping.TypeDesc.IsValueType)
                {
                    base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(element.Mapping.TypeDesc.CSharpName, element.Mapping.TypeDesc.UseReflection, ctorInaccessible: false, cast: false));
                }
                else
                {
                    base.Writer.Write("null");
                }
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                base.Writer.Write("else ");
            }
            if (element.Default != null && element.Default != DBNull.Value && element.Mapping.TypeDesc.IsValueType)
            {
                base.Writer.WriteLine("if (Reader.IsEmptyElement) {");
                base.Writer.Indent++;
                base.Writer.WriteLine("Reader.Skip();");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                base.Writer.WriteLine("else {");
            }
            else
            {
                base.Writer.WriteLine("{");
            }
            base.Writer.Indent++;
            if (element.Mapping.TypeDesc.Type == typeof(TimeSpan) || element.Mapping.TypeDesc.Type == typeof(DateTimeOffset))
            {
                base.Writer.WriteLine("if (Reader.IsEmptyElement) {");
                base.Writer.Indent++;
                base.Writer.WriteLine("Reader.Skip();");
                WriteSourceBegin(source);
                if (element.Mapping.TypeDesc.Type == typeof(TimeSpan))
                {
                    base.Writer.Write("default(System.TimeSpan)");
                }
                else if (element.Mapping.TypeDesc.Type == typeof(DateTimeOffset))
                {
                    base.Writer.Write("default(System.DateTimeOffset)");
                }
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
                base.Writer.WriteLine("else {");
                base.Writer.Indent++;
                WriteSourceBegin(source);
                WritePrimitive(element.Mapping, "Reader.ReadElementString()");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            else
            {
                WriteSourceBegin(source);
                if (element.Mapping.TypeDesc == base.QnameTypeDesc)
                {
                    base.Writer.Write("ReadElementQualifiedName()");
                }
                else
                {
                    string formatterName = element.Mapping.TypeDesc.FormatterName;
                    WritePrimitive(source: (!(formatterName == "ByteArrayBase64") && !(formatterName == "ByteArrayHex")) ? "Reader.ReadElementString()" : "false", mapping: element.Mapping);
                }
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        else if (element.Mapping is StructMapping || (element.Mapping.IsSoap && element.Mapping is PrimitiveMapping))
        {
            TypeMapping mapping = element.Mapping;
            if (mapping.IsSoap)
            {
                base.Writer.Write("object rre = ");
                base.Writer.Write((fixupIndex >= 0) ? "ReadReferencingElement" : "ReadReferencedElement");
                base.Writer.Write("(");
                WriteID(mapping.TypeName);
                base.Writer.Write(", ");
                WriteID(mapping.Namespace);
                if (fixupIndex >= 0)
                {
                    base.Writer.Write(", out fixup.Ids[");
                    base.Writer.Write(fixupIndex.ToString(CultureInfo.InvariantCulture));
                    base.Writer.Write("]");
                }
                base.Writer.Write(")");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                if (mapping.TypeDesc.IsValueType)
                {
                    base.Writer.WriteLine("if (rre != null) {");
                    base.Writer.Indent++;
                }
                base.Writer.WriteLine("try {");
                base.Writer.Indent++;
                WriteSourceBeginTyped(source, mapping.TypeDesc);
                base.Writer.Write("rre");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                WriteCatchCastException(mapping.TypeDesc, "rre", null);
                base.Writer.Write("Referenced(");
                base.Writer.Write(source);
                base.Writer.WriteLine(");");
                if (mapping.TypeDesc.IsValueType)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
            else
            {
                string s2 = ReferenceMapping(mapping);
                if (checkForNull)
                {
                    base.Writer.Write("if ((object)(");
                    base.Writer.Write(arrayName);
                    base.Writer.Write(") == null) Reader.Skip(); else ");
                }
                WriteSourceBegin(source);
                base.Writer.Write(s2);
                base.Writer.Write("(");
                if (mapping.TypeDesc.IsNullable)
                {
                    WriteBooleanValue(element.IsNullable);
                    base.Writer.Write(", ");
                }
                base.Writer.Write("true");
                base.Writer.Write(")");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
            }
        }
        else
        {
            if (!(element.Mapping is SpecialMapping))
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            SpecialMapping specialMapping = (SpecialMapping)element.Mapping;
            switch (specialMapping.TypeDesc.Kind)
            {
            case TypeKind.Node:
            {
                bool flag2 = specialMapping.TypeDesc.FullName == typeof(XmlDocument).FullName;
                WriteSourceBeginTyped(source, specialMapping.TypeDesc);
                base.Writer.Write(flag2 ? "ReadXmlDocument(" : "ReadXmlNode(");
                base.Writer.Write(element.Any ? "false" : "true");
                base.Writer.Write(")");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                break;
            }
            case TypeKind.Serializable:
            {
                SerializableMapping serializableMapping = (SerializableMapping)element.Mapping;
                if (serializableMapping.DerivedMappings != null)
                {
                    base.Writer.Write(typeof(XmlQualifiedName).FullName);
                    base.Writer.WriteLine(" tser = GetXsiType();");
                    base.Writer.Write("if (tser == null");
                    base.Writer.Write(" || ");
                    WriteQNameEqual("tser", serializableMapping.XsiType.Name, serializableMapping.XsiType.Namespace);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                }
                WriteSourceBeginTyped(source, serializableMapping.TypeDesc);
                base.Writer.Write("ReadSerializable(( ");
                base.Writer.Write(typeof(IXmlSerializable).FullName);
                base.Writer.Write(")");
                base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(serializableMapping.TypeDesc.CSharpName, serializableMapping.TypeDesc.UseReflection, serializableMapping.TypeDesc.CannotNew, cast: false));
                bool flag = !element.Any && XmlSerializationCodeGen.IsWildcard(serializableMapping);
                if (flag)
                {
                    base.Writer.WriteLine(", true");
                }
                base.Writer.Write(")");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                if (serializableMapping.DerivedMappings != null)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                    WriteDerivedSerializable(serializableMapping, serializableMapping, source, flag);
                    WriteUnknownNode("UnknownNode", "null", null, anyIfs: true);
                }
                break;
            }
            default:
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
        }
        if (choice != null)
        {
            string cSharpName = choice.Mapping.TypeDesc.CSharpName;
            base.Writer.Write(choiceSource);
            base.Writer.Write(" = ");
            CodeIdentifier.CheckValidIdentifier(choice.MemberIds[elementIndex]);
            base.Writer.Write(base.RaCodeGen.GetStringForEnumMember(cSharpName, choice.MemberIds[elementIndex], choice.Mapping.TypeDesc.UseReflection));
            base.Writer.WriteLine(";");
        }
    }
References System.Xml.Serialization.Accessor.Any, System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Serialization.Accessor.Default, System.Xml.Dictionary, System.elementIndex, System.Xml.Serialization.TypeDesc.FormatterName, System.FullName, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.ElementAccessor.IsNullable, System.Xml.Serialization.Mapping.IsSoap, System.Xml.Serialization.TypeDesc.IsValueType, System.Xml.Serialization.XmlSerializationCodeGen.IsWildcard(), System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.source, System.Xml.Serialization.TypeDesc.Type, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.TypeDesc.UseReflection, System.DBNull.Value, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteBooleanValue(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCatchCastException(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteUnknownNode(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsElse(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsIf(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteNullableMethod().