Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement
GenerateLiteralMembersElement()
string System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 493 of file XmlSerializationReaderCodeGen.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MemberMapping[] members = ((MembersMapping)accessor.Mapping).Members;
        bool hasWrapperElement = ((MembersMapping)accessor.Mapping).HasWrapperElement;
        string text = NextMethodName(accessor.Name);
        base.Writer.WriteLine();
        base.Writer.Write("public object[] ");
        base.Writer.Write(text);
        base.Writer.WriteLine("() {");
        base.Writer.Indent++;
        base.Writer.WriteLine("Reader.MoveToContent();");
        base.Writer.Write("object[] p = new object[");
        base.Writer.Write(members.Length.ToString(CultureInfo.InvariantCulture));
        base.Writer.WriteLine("];");
        InitializeValueTypes("p", members);
        if (hasWrapperElement)
        {
            WriteWhileNotLoopStart();
            base.Writer.Indent++;
            WriteIsStartTag(accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
        }
        Member anyText = null;
        Member anyElement = null;
        Member anyAttribute = null;
        List<Member> list = new List<Member>();
        List<Member> list2 = new List<Member>();
        List<Member> list3 = new List<Member>();
        for (int i = 0; i < members.Length; i++)
        {
            MemberMapping memberMapping = members[i];
            string text2 = $"p[{i}]";
            string arraySource = text2;
            if (memberMapping.Xmlns != null)
            {
                arraySource = $"(({memberMapping.TypeDesc.CSharpName}){text2})";
            }
            string choiceIdentifierSource = GetChoiceIdentifierSource(members, memberMapping);
            Member member = new Member(this, text2, arraySource, "a", i, memberMapping, choiceIdentifierSource);
            Member member2 = new Member(this, text2, null, "a", i, memberMapping, choiceIdentifierSource);
            if (!memberMapping.IsSequence)
            {
                member.ParamsReadSource = $"paramsRead[{i}]";
            }
            if (memberMapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
            {
                string text3 = memberMapping.Name + "Specified";
                for (int j = 0; j < members.Length; j++)
                {
                    if (members[j].Name == text3)
                    {
                        member.CheckSpecifiedSource = $"p[{j}]";
                        break;
                    }
                }
            }
            bool flag = false;
            if (memberMapping.Text != null)
            {
                anyText = member2;
            }
            if (memberMapping.Attribute != null && memberMapping.Attribute.Any)
            {
                anyAttribute = member2;
            }
            if (memberMapping.Attribute != null || memberMapping.Xmlns != null)
            {
                list3.Add(member);
            }
            else if (memberMapping.Text != null)
            {
                list2.Add(member);
            }
            if (!memberMapping.IsSequence)
            {
                for (int k = 0; k < memberMapping.Elements.Length; k++)
                {
                    if (memberMapping.Elements[k].Any && memberMapping.Elements[k].Name.Length == 0)
                    {
                        anyElement = member2;
                        if (memberMapping.Attribute == null && memberMapping.Text == null)
{
                            list2.Add(member2);
                        }
                        flag = true;
                        break;
                    }
                }
            }
            if (memberMapping.Attribute != null || memberMapping.Text != null || flag)
            {
                list.Add(member2);
                continue;
            }
            if (memberMapping.TypeDesc.IsArrayLike && (memberMapping.Elements.Length != 1 || !(memberMapping.Elements[0].Mapping is ArrayMapping)))
            {
                list.Add(member2);
                list2.Add(member2);
                continue;
            }
            if (memberMapping.TypeDesc.IsArrayLike && !memberMapping.TypeDesc.IsArray)
            {
                member.ParamsReadSource = null;
            }
            list.Add(member);
        }
        Member[] array = list.ToArray();
        Member[] members2 = list2.ToArray();
        if (array.Length != 0 && array[0].Mapping.IsReturnValue)
        {
            base.Writer.WriteLine("IsReturnValue = true;");
        }
        WriteParamsRead(members.Length);
        if (list3.Count > 0)
        {
            Member[] members3 = list3.ToArray();
            WriteMemberBegin(members3);
            WriteAttributes(members3, anyAttribute, "UnknownNode", "(object)p");
            WriteMemberEnd(members3);
            base.Writer.WriteLine("Reader.MoveToElement();");
        }
        WriteMemberBegin(members2);
        if (hasWrapperElement)
        {
            base.Writer.WriteLine("if (Reader.IsEmptyElement) { Reader.Skip(); Reader.MoveToContent(); continue; }");
            base.Writer.WriteLine("Reader.ReadStartElement();");
        }
        if (IsSequence(array))
        {
            base.Writer.WriteLine("int state = 0;");
        }
        WriteWhileNotLoopStart();
        base.Writer.Indent++;
        string text4 = "UnknownNode((object)p, " + ExpectedElements(array) + ");";
        WriteMemberElements(array, text4, text4, anyElement, anyText, null);
        base.Writer.WriteLine("Reader.MoveToContent();");
        WriteWhileLoopEnd();
        WriteMemberEnd(members2);
        if (hasWrapperElement)
        {
            base.Writer.WriteLine("ReadEndElement();");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            WriteUnknownNode("UnknownNode", "null", accessor, anyIfs: true);
            base.Writer.WriteLine("Reader.MoveToContent();");
            WriteWhileLoopEnd();
        }
        base.Writer.WriteLine("return p;");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        return text;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource(), System.Xml.Serialization.XmlSerializationReaderCodeGen.InitializeValueTypes(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationReaderCodeGen.IsSequence(), System.list, System.Xml.Name, System.Xml.Serialization.XmlSerializationReaderCodeGen.NextMethodName(), System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteParamsRead(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteUnknownNode(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileNotLoopStart().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMembersElement().