Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEncodedMembersElement
GenerateEncodedMembersElement()
string System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEncodedMembersElement (XmlMembersMapping xmlMembersMapping) inline private
Definition at line 669 of file XmlSerializationReaderCodeGen.cs.
    {
        ElementAccessor accessor = xmlMembersMapping.Accessor;
        MembersMapping membersMapping = (MembersMapping)accessor.Mapping;
        MemberMapping[] members = membersMapping.Members;
        bool hasWrapperElement = membersMapping.HasWrapperElement;
        bool writeAccessors = membersMapping.WriteAccessors;
        string text = NextMethodName(accessor.Name);
        base.Writer.WriteLine();
        base.Writer.Write("public object[] ");
        base.Writer.Write(text);
        base.Writer.WriteLine("() {");
        base.Writer.Indent++;
        base.Writer.WriteLine("Reader.MoveToContent();");
        base.Writer.Write("object[] p = new object[");
        base.Writer.Write(members.Length.ToString(CultureInfo.InvariantCulture));
        base.Writer.WriteLine("];");
        InitializeValueTypes("p", members);
        if (hasWrapperElement)
        {
            WriteReadNonRoots();
            if (membersMapping.ValidateRpcWrapperElement)
            {
                base.Writer.Write("if (!");
                WriteXmlNodeEqual("Reader", accessor.Name, (accessor.Form == XmlSchemaForm.Qualified) ? accessor.Namespace : "");
                base.Writer.WriteLine(") throw CreateUnknownNodeException();");
            }
            base.Writer.WriteLine("bool isEmptyWrapper = Reader.IsEmptyElement;");
            base.Writer.WriteLine("Reader.ReadStartElement();");
        }
        Member[] array = new Member[members.Length];
        for (int i = 0; i < members.Length; i++)
        {
            MemberMapping memberMapping = members[i];
            string text2 = $"p[{i}]";
            string arraySource = text2;
            if (memberMapping.Xmlns != null)
            {
                arraySource = $"(({memberMapping.TypeDesc.CSharpName}){text2})";
            }
            Member member = new Member(this, text2, arraySource, "a", i, memberMapping);
            if (!memberMapping.IsSequence)
            {
                member.ParamsReadSource = $"paramsRead[{i}]";
            }
            array[i] = member;
            if (memberMapping.CheckSpecified != SpecifiedAccessor.ReadWrite)
            {
                continue;
            }
            string text3 = memberMapping.Name + "Specified";
            for (int j = 0; j < members.Length; j++)
            {
                if (members[j].Name == text3)
                {
                    member.CheckSpecifiedSource = $"p[{j}]";
                    break;
                }
            }
        }
        string fixupMethodName = "fixup_" + text;
        bool flag = WriteMemberFixupBegin(array, fixupMethodName, "p");
        if (array.Length != 0 && array[0].Mapping.IsReturnValue)
        {
            base.Writer.WriteLine("IsReturnValue = true;");
        }
        string text4 = ((!hasWrapperElement && !writeAccessors) ? "hrefList" : null);
        if (text4 != null)
        {
            WriteInitCheckTypeHrefList(text4);
        }
        WriteParamsRead(members.Length);
        WriteWhileNotLoopStart();
        base.Writer.Indent++;
        string elementElseString = ((text4 == null) ? "UnknownNode((object)p);" : "if (Reader.GetAttribute(\"id\", null) != null) { ReadReferencedElement(); } else { UnknownNode((object)p); }");
        WriteMemberElements(array, elementElseString, "UnknownNode((object)p);", null, null, text4);
        base.Writer.WriteLine("Reader.MoveToContent();");
        WriteWhileLoopEnd();
        if (hasWrapperElement)
        {
            base.Writer.WriteLine("if (!isEmptyWrapper) ReadEndElement();");
        }
        if (text4 != null)
        {
            WriteHandleHrefList(array, text4);
        }
        base.Writer.WriteLine("ReadReferencedElements();");
        base.Writer.WriteLine("return p;");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (flag)
        {
            WriteFixupMethod(fixupMethodName, array, "object[]", useReflection: false, typed: false, "p");
        }
        return text;
    }
References System.array, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.InitializeValueTypes(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Name, System.Xml.Serialization.XmlSerializationReaderCodeGen.NextMethodName(), System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteFixupMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHandleHrefList(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteInitCheckTypeHrefList(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberFixupBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteParamsRead(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteReadNonRoots(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileNotLoopStart(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteXmlNodeEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMembersElement().