Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttribute
WriteAttribute()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttribute (Member member) inline private
Definition at line 1826 of file XmlSerializationReaderCodeGen.cs.
    {
        AttributeAccessor attribute = member.Mapping.Attribute;
        if (attribute.Mapping is SpecialMapping)
        {
            SpecialMapping specialMapping = (SpecialMapping)attribute.Mapping;
            if (specialMapping.TypeDesc.Kind == TypeKind.Attribute)
            {
                WriteSourceBegin(member.ArraySource);
                base.Writer.Write("attr");
                WriteSourceEnd(member.ArraySource);
                base.Writer.WriteLine(";");
            }
            else
            {
                if (!specialMapping.TypeDesc.CanBeAttributeValue)
                {
                    throw new InvalidOperationException(System.SR.XmlInternalError);
                }
                base.Writer.Write("if (attr is ");
                base.Writer.Write(typeof(XmlAttribute).FullName);
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                WriteSourceBegin(member.ArraySource);
                base.Writer.Write("(");
                base.Writer.Write(typeof(XmlAttribute).FullName);
                base.Writer.Write(")attr");
                WriteSourceEnd(member.ArraySource);
                base.Writer.WriteLine(";");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
        }
        else if (attribute.IsList)
        {
            base.Writer.WriteLine("string listValues = Reader.Value;");
            base.Writer.WriteLine("string[] vals = listValues.Split(null);");
            base.Writer.WriteLine("for (int i = 0; i < vals.Length; i++) {");
            base.Writer.Indent++;
            string arraySource = GetArraySource(member.Mapping.TypeDesc, member.ArrayName);
            WriteSourceBegin(arraySource);
            WritePrimitive(attribute.Mapping, "vals[i]");
            WriteSourceEnd(arraySource);
            base.Writer.WriteLine(";");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        else
        {
            WriteSourceBegin(member.ArraySource);
            WritePrimitive(attribute.Mapping, attribute.IsList ? "vals[i]" : "Reader.Value");
            WriteSourceEnd(member.ArraySource);
            base.Writer.WriteLine(";");
        }
        if (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite && member.CheckSpecifiedSource != null && member.CheckSpecifiedSource.Length > 0)
        {
            base.Writer.Write(member.CheckSpecifiedSource);
            base.Writer.WriteLine(" = true;");
        }
        if (member.ParamsReadSource != null)
        {
            base.Writer.Write(member.ParamsReadSource);
            base.Writer.WriteLine(" = true;");
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArraySource, System.Xml.Serialization.AccessorMapping.Attribute, System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.CheckSpecifiedSource, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.GetArraySource(), System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ParamsReadSource, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes().