Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID
WriteID()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID (string name) inline private
Definition at line 1696 of file XmlSerializationReaderCodeGen.cs.
    {
        if (name == null)
        {
            name = "";
        }
        string text = (string)_idNames[name];
        if (text == null)
        {
            text = NextIdName(name);
            _idNames.Add(name, text);
        }
        base.Writer.Write(text);
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen._idNames, System.Collections.Hashtable.Add(), System.Xml.Serialization.XmlSerializationReaderCodeGen.NextIdName(), and System.text.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteIsStartTag(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteXmlNodeEqual().