Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteFixupMethod
WriteFixupMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteFixupMethod (string fixupMethodName, Member[] members, string typeName, bool useReflection, bool typed, string source) inline private
Definition at line 1536 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.WriteLine();
        base.Writer.Write("void ");
        base.Writer.Write(fixupMethodName);
        base.Writer.WriteLine("(object objFixup) {");
        base.Writer.Indent++;
        base.Writer.WriteLine("Fixup fixup = (Fixup)objFixup;");
        WriteLocalDecl(typeName, source, "fixup.Source", useReflection);
        base.Writer.WriteLine("string[] ids = fixup.Ids;");
        foreach (Member member in members)
        {
            if (!member.MultiRef)
            {
                continue;
            }
            string text = member.FixupIndex.ToString(CultureInfo.InvariantCulture);
            base.Writer.Write("if (ids[");
            base.Writer.Write(text);
            base.Writer.WriteLine("] != null) {");
            base.Writer.Indent++;
            string arraySource = member.ArraySource;
            string text2 = "GetTarget(ids[" + text + "])";
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            if (typeDesc.IsCollection || typeDesc.IsEnumerable)
            {
                WriteAddCollectionFixup(typeDesc, member.Mapping.ReadOnly, arraySource, text2);
            }
            else
            {
                if (typed)
                {
                    base.Writer.WriteLine("try {");
                    base.Writer.Indent++;
                    WriteSourceBeginTyped(arraySource, member.Mapping.TypeDesc);
                }
                else
                {
                    WriteSourceBegin(arraySource);
                }
                base.Writer.Write(text2);
                WriteSourceEnd(arraySource);
                base.Writer.WriteLine(";");
                if (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite && member.CheckSpecifiedSource != null && member.CheckSpecifiedSource.Length > 0)
                {
                    base.Writer.Write(member.CheckSpecifiedSource);
                    base.Writer.WriteLine(" = true;");
                }
                if (typed)
                {
                    WriteCatchCastException(member.Mapping.TypeDesc, text2, "ids[" + text + "]");
                }
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArraySource, System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.CheckSpecifiedSource, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.FixupIndex, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.MultiRef, System.Xml.Serialization.MemberMapping.ReadOnly, System.source, System.text, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCatchCastException(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLocalDecl(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEncodedMembersElement(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod().