Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd
WriteWhileLoopEnd()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd () inline private
Definition at line 2921 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEncodedMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteReadNonRoots().