Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin
WriteMemberBegin()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin (Member[] members) inline private
Definition at line 1925 of file XmlSerializationReaderCodeGen.cs.
    {
        foreach (Member member in members)
        {
            if (!member.IsArrayLike)
            {
                continue;
            }
            string arrayName = member.ArrayName;
            string s = "c" + arrayName;
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            string cSharpName = typeDesc.CSharpName;
            if (member.Mapping.TypeDesc.IsArray)
            {
                WriteArrayLocalDecl(typeDesc.CSharpName, arrayName, "null", typeDesc);
                base.Writer.Write("int ");
                base.Writer.Write(s);
                base.Writer.WriteLine(" = 0;");
                if (member.Mapping.ChoiceIdentifier != null)
                {
                    WriteArrayLocalDecl(member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.CSharpName + "[]", member.ChoiceArrayName, "null", member.Mapping.ChoiceIdentifier.Mapping.TypeDesc);
                    base.Writer.Write("int c");
                    base.Writer.Write(member.ChoiceArrayName);
                    base.Writer.WriteLine(" = 0;");
                }
                continue;
            }
            bool useReflection = typeDesc.UseReflection;
            if (member.Source[member.Source.Length - 1] == '(' || member.Source[member.Source.Length - 1] == '{')
            {
                WriteCreateInstance(cSharpName, arrayName, useReflection, typeDesc.CannotNew);
                base.Writer.Write(member.Source);
                base.Writer.Write(arrayName);
                if (member.Source[member.Source.Length - 1] == '{')
                {
                    base.Writer.WriteLine("});");
                }
                else
                {
                    base.Writer.WriteLine(");");
                }
                continue;
            }
            if (member.IsList && !member.Mapping.ReadOnly && member.Mapping.TypeDesc.IsNullable)
            {
                base.Writer.Write("if ((object)(");
                base.Writer.Write(member.Source);
                base.Writer.Write(") == null) ");
                if (!member.Mapping.TypeDesc.HasDefaultConstructor)
                {
                    base.Writer.Write("throw CreateReadOnlyCollectionException(");
                    WriteQuotedCSharpString(member.Mapping.TypeDesc.CSharpName);
                    base.Writer.WriteLine(");");
                }
                else
                {
                    base.Writer.Write(member.Source);
                    base.Writer.Write(" = ");
                    base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(cSharpName, useReflection, typeDesc.CannotNew, cast: true));
                    base.Writer.WriteLine(";");
                }
            }
            WriteLocalDecl(cSharpName, arrayName, member.Source, useReflection);
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ChoiceArrayName, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.Xml.Serialization.TypeDesc.HasDefaultConstructor, System.Xml.Serialization.TypeDesc.IsArray, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsArrayLike, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsList, System.Xml.Serialization.TypeDesc.IsNullable, System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.Xml.Serialization.MemberMapping.ReadOnly, System.s, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Source, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArrayLocalDecl(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateInstance(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLocalDecl(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().