Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMethod
GenerateMethod()
override void System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMethod (TypeMapping mapping) inline package virtual
Reimplemented from System.Xml.Serialization.XmlSerializationCodeGen.
Definition at line 292 of file XmlSerializationReaderCodeGen.cs.
    {
        if (!base.GeneratedMethods.Contains(mapping))
        {
            base.GeneratedMethods[mapping] = mapping;
            if (mapping is StructMapping)
            {
                WriteStructMethod((StructMapping)mapping);
            }
            else if (mapping is EnumMapping)
            {
                WriteEnumMethod((EnumMapping)mapping);
            }
            else if (mapping is NullableMapping)
            {
                WriteNullableMethod((NullableMapping)mapping);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteStructMethod().