Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes
WriteDerivedTypes()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes (StructMapping mapping, bool isTypedReturn, string returnTypeName) inline private
Definition at line 1085 of file XmlSerializationReaderCodeGen.cs.
    {
        for (StructMapping structMapping = mapping.DerivedMappings; structMapping != null; structMapping = structMapping.NextDerivedMapping)
        {
            base.Writer.Write("if (");
            WriteQNameEqual("xsiType", structMapping.TypeName, structMapping.Namespace);
            base.Writer.WriteLine(")");
            base.Writer.Indent++;
            string s = ReferenceMapping(structMapping);
            base.Writer.Write("return ");
            if (structMapping.TypeDesc.UseReflection && isTypedReturn)
            {
                base.Writer.Write("(" + returnTypeName + ")");
            }
            base.Writer.Write(s);
            base.Writer.Write("(");
            if (structMapping.TypeDesc.IsNullable)
            {
                base.Writer.Write("isNullable, ");
            }
            base.Writer.WriteLine("false);");
            base.Writer.Indent--;
            WriteDerivedTypes(structMapping, isTypedReturn, returnTypeName);
        }
    }
References System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().