Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateInitCallbacksMethod
GenerateInitCallbacksMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateInitCallbacksMethod () inline private
Definition at line 402 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.WriteLine();
        base.Writer.WriteLine("protected override void InitCallbacks() {");
        base.Writer.Indent++;
        string text = NextMethodName("Array");
        bool flag = false;
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (TypeMapping typeMapping in typeScope.TypeMappings)
            {
                if (typeMapping.IsSoap && (typeMapping is StructMapping || typeMapping is EnumMapping || typeMapping is ArrayMapping || typeMapping is NullableMapping) && !typeMapping.TypeDesc.IsRoot)
                {
                    string s;
                    if (typeMapping is ArrayMapping)
                    {
                        s = text;
                        flag = true;
                    }
                    else
                    {
                        s = (string)base.MethodNames[typeMapping];
                    }
                    base.Writer.Write("AddReadCallback(");
                    WriteID(typeMapping.TypeName);
                    base.Writer.Write(", ");
                    WriteID(typeMapping.Namespace);
                    base.Writer.Write(", ");
                    base.Writer.Write(base.RaCodeGen.GetStringForTypeof(typeMapping.TypeDesc.CSharpName, typeMapping.TypeDesc.UseReflection));
                    base.Writer.Write(", new ");
                    base.Writer.Write(typeof(XmlSerializationReadCallback).FullName);
                    base.Writer.Write("(this.");
                    base.Writer.Write(s);
                    base.Writer.WriteLine("));");
                }
            }
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (flag)
        {
            base.Writer.WriteLine();
            base.Writer.Write("object ");
            base.Writer.Write(text);
            base.Writer.WriteLine("() {");
            base.Writer.Indent++;
            base.Writer.WriteLine("// dummy array method");
            base.Writer.WriteLine("UnknownNode(null);");
            base.Writer.WriteLine("return null;");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.NextMethodName(), System.s, System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID(), and System.Xml.Serialization.XmlSerializationReadCallback().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEnd().