Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup
WriteAddCollectionFixup()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup (TypeDesc typeDesc, bool readOnly, string memberSource, string targetSource) inline private
Definition at line 1596 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.WriteLine("// get array of the collection items");
        CreateCollectionInfo createCollectionInfo = (CreateCollectionInfo)_createMethods[typeDesc];
        if (createCollectionInfo == null)
        {
            IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
            DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(7, 2, invariantCulture);
            handler.AppendLiteral("create");
            handler.AppendFormatted(++_nextCreateMethodNumber);
            handler.AppendLiteral("_");
            handler.AppendFormatted(typeDesc.Name);
            string name = string.Create(invariantCulture, ref handler);
            createCollectionInfo = new CreateCollectionInfo(name, typeDesc);
            _createMethods.Add(typeDesc, createCollectionInfo);
        }
        base.Writer.Write("if ((object)(");
        base.Writer.Write(memberSource);
        base.Writer.WriteLine(") == null) {");
        base.Writer.Indent++;
        if (readOnly)
        {
            base.Writer.Write("throw CreateReadOnlyCollectionException(");
            WriteQuotedCSharpString(typeDesc.CSharpName);
            base.Writer.WriteLine(");");
        }
        else
        {
            base.Writer.Write(memberSource);
            base.Writer.Write(" = ");
            base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(typeDesc.CSharpName, typeDesc.UseReflection, typeDesc.CannotNew, cast: true));
            base.Writer.WriteLine(";");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.Write("CollectionFixup collectionFixup = new CollectionFixup(");
        base.Writer.Write(memberSource);
        base.Writer.Write(", ");
        base.Writer.Write("new ");
        base.Writer.Write(typeof(XmlSerializationCollectionFixupCallback).FullName);
        base.Writer.Write("(this.");
        base.Writer.Write(createCollectionInfo.Name);
        base.Writer.Write("), ");
        base.Writer.Write(targetSource);
        base.Writer.WriteLine(");");
        base.Writer.WriteLine("AddFixup(collectionFixup);");
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen._createMethods, System.Xml.Serialization.XmlSerializationReaderCodeGen._nextCreateMethodNumber, System.Collections.Hashtable.Add(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationCollectionFixupCallback().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteFixupMethod().