Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteText
WriteText()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteText (Member member) inline private
Definition at line 2086 of file XmlSerializationReaderCodeGen.cs.
    {
        TextAccessor text = member.Mapping.Text;
        if (text.Mapping is SpecialMapping)
        {
            SpecialMapping specialMapping = (SpecialMapping)text.Mapping;
            WriteSourceBeginTyped(member.ArraySource, specialMapping.TypeDesc);
            TypeKind kind = specialMapping.TypeDesc.Kind;
            if (kind != TypeKind.Node)
            {
                throw new InvalidOperationException(System.SR.XmlInternalError);
            }
            base.Writer.Write("Document.CreateTextNode(Reader.ReadString())");
            WriteSourceEnd(member.ArraySource);
        }
        else
        {
            if (member.IsArrayLike)
            {
                WriteSourceBegin(member.ArraySource);
                if (text.Mapping.TypeDesc.CollapseWhitespace)
                {
                    base.Writer.Write("CollapseWhitespace(Reader.ReadString())");
                }
                else
                {
                    base.Writer.Write("Reader.ReadString()");
                }
            }
            else if (text.Mapping.TypeDesc == base.StringTypeDesc || text.Mapping.TypeDesc.FormatterName == "String")
            {
                base.Writer.Write("tmp = ReadString(tmp, ");
                if (text.Mapping.TypeDesc.CollapseWhitespace)
                {
                    base.Writer.WriteLine("true);");
                }
                else
                {
                    base.Writer.WriteLine("false);");
                }
                WriteSourceBegin(member.ArraySource);
                base.Writer.Write("tmp");
            }
            else
            {
                WriteSourceBegin(member.ArraySource);
                WritePrimitive(text.Mapping, "Reader.ReadString()");
            }
            WriteSourceEnd(member.ArraySource);
        }
        base.Writer.WriteLine(";");
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArraySource, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsArrayLike, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.text, System.Xml.Serialization.AccessorMapping.Text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WritePrimitive(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), and System.SR.XmlInternalError.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberText().