Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod
WriteEnumMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod (EnumMapping mapping) inline private
Definition at line 1003 of file XmlSerializationReaderCodeGen.cs.
    {
        string s = null;
        if (mapping.IsFlags)
        {
            s = WriteHashtable(mapping, mapping.TypeDesc.Name);
        }
        string s2 = (string)base.MethodNames[mapping];
        base.Writer.WriteLine();
        bool useReflection = mapping.TypeDesc.UseReflection;
        string cSharpName = mapping.TypeDesc.CSharpName;
        if (mapping.IsSoap)
        {
            base.Writer.Write("object");
            base.Writer.Write(" ");
            base.Writer.Write(s2);
            base.Writer.WriteLine("() {");
            base.Writer.Indent++;
            base.Writer.WriteLine("string s = Reader.ReadElementString();");
        }
        else
        {
            base.Writer.Write(useReflection ? "object" : cSharpName);
            base.Writer.Write(" ");
            base.Writer.Write(s2);
            base.Writer.WriteLine("(string s) {");
            base.Writer.Indent++;
        }
        ConstantMapping[] constants = mapping.Constants;
        if (mapping.IsFlags)
        {
            if (useReflection)
            {
                base.Writer.Write("return ");
                base.Writer.Write(typeof(Enum).FullName);
                base.Writer.Write(".ToObject(");
                base.Writer.Write(base.RaCodeGen.GetStringForTypeof(cSharpName, useReflection));
                base.Writer.Write(", ToEnum(s, ");
                base.Writer.Write(s);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(cSharpName);
                base.Writer.WriteLine("));");
            }
            else
            {
                base.Writer.Write("return (");
                base.Writer.Write(cSharpName);
                base.Writer.Write(")ToEnum(s, ");
                base.Writer.Write(s);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(cSharpName);
                base.Writer.WriteLine(");");
            }
        }
        else
        {
            base.Writer.WriteLine("switch (s) {");
            base.Writer.Indent++;
            Hashtable hashtable = new Hashtable();
            foreach (ConstantMapping constantMapping in constants)
            {
                CodeIdentifier.CheckValidIdentifier(constantMapping.Name);
                if (hashtable[constantMapping.XmlName] == null)
                {
                    base.Writer.Write("case ");
                    WriteQuotedCSharpString(constantMapping.XmlName);
                    base.Writer.Write(": return ");
                    base.Writer.Write(base.RaCodeGen.GetStringForEnumMember(cSharpName, constantMapping.Name, useReflection));
                    base.Writer.WriteLine(";");
                    hashtable[constantMapping.XmlName] = constantMapping.XmlName;
                }
            }
            base.Writer.Write("default: throw CreateUnknownConstantException(s, ");
            base.Writer.Write(base.RaCodeGen.GetStringForTypeof(cSharpName, useReflection));
            base.Writer.WriteLine(");");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.s, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateBegin(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMethod().