Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteNullableMethod
WriteNullableMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteNullableMethod (NullableMapping nullableMapping) inline private
Definition at line 1194 of file XmlSerializationReaderCodeGen.cs.
    {
        string s = (string)base.MethodNames[nullableMapping];
        bool useReflection = nullableMapping.BaseMapping.TypeDesc.UseReflection;
        string s2 = (useReflection ? "object" : nullableMapping.TypeDesc.CSharpName);
        base.Writer.WriteLine();
        base.Writer.Write(s2);
        base.Writer.Write(" ");
        base.Writer.Write(s);
        base.Writer.WriteLine("(bool checkType) {");
        base.Writer.Indent++;
        base.Writer.Write(s2);
        base.Writer.Write(" o = ");
        if (useReflection)
        {
            base.Writer.Write("null");
        }
        else
        {
            base.Writer.Write("default(");
            base.Writer.Write(s2);
            base.Writer.Write(")");
        }
        base.Writer.WriteLine(";");
        base.Writer.WriteLine("if (ReadNull())");
        base.Writer.Indent++;
        base.Writer.WriteLine("return o;");
        base.Writer.Indent--;
        ElementAccessor elementAccessor = new ElementAccessor();
        elementAccessor.Mapping = nullableMapping.BaseMapping;
        elementAccessor.Any = false;
        elementAccessor.IsNullable = nullableMapping.BaseMapping.TypeDesc.IsNullable;
        WriteElement("o", null, null, elementAccessor, null, null, checkForNull: false, readOnly: false, -1, -1);
        base.Writer.WriteLine("return o;");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Dictionary, System.s, and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateBegin(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateMethod().