Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements
WriteMemberElements()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements (Member[] members, string elementElseString, string elseString, Member anyElement, Member anyText, string checkTypeHrefsSource) inline private
Definition at line 2025 of file XmlSerializationReaderCodeGen.cs.
    {
        bool flag = checkTypeHrefsSource != null && checkTypeHrefsSource.Length > 0;
        if (anyText != null)
        {
            base.Writer.WriteLine("string tmp = null;");
        }
        base.Writer.Write("if (Reader.NodeType == ");
        base.Writer.Write(typeof(XmlNodeType).FullName);
        base.Writer.WriteLine(".Element) {");
        base.Writer.Indent++;
        if (flag)
        {
            WriteIfNotSoapRoot(elementElseString + " continue;");
            WriteMemberElementsCheckType(checkTypeHrefsSource);
        }
        else
        {
            WriteMemberElementsIf(members, anyElement, elementElseString, null);
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (anyText != null)
        {
            WriteMemberText(anyText, elseString);
        }
        base.Writer.WriteLine("else {");
        base.Writer.Indent++;
        base.Writer.WriteLine(elseString);
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteIfNotSoapRoot(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsCheckType(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsIf(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberText().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEncodedMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().