Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements
ExpectedElements()
string System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements (Member[] members) inline private
Definition at line 1991 of file XmlSerializationReaderCodeGen.cs.
    {
        if (IsSequence(members))
        {
            return "null";
        }
        string text = string.Empty;
        bool flag = true;
        foreach (Member member in members)
        {
            if (member.Mapping.Xmlns != null || member.Mapping.Ignore || member.Mapping.IsText || member.Mapping.IsAttribute)
            {
                continue;
            }
            ElementAccessor[] elements = member.Mapping.Elements;
            foreach (ElementAccessor elementAccessor in elements)
            {
                string text2 = ((elementAccessor.Form == XmlSchemaForm.Qualified) ? elementAccessor.Namespace : "");
                if (!elementAccessor.Any || (elementAccessor.Name != null && elementAccessor.Name.Length != 0))
                {
                    if (!flag)
                    {
                        text += ", ";
                    }
                    text = text + text2 + ":" + elementAccessor.Name;
                    flag = false;
                }
            }
        }
        StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
        ReflectionAwareCodeGen.WriteQuotedCSharpString(new IndentedWriter(stringWriter, compact: true), text);
        return stringWriter.ToString();
    }
References System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.Elements, System.Xml.Serialization.AccessorMapping.Ignore, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.AccessorMapping.IsAttribute, System.Xml.Serialization.XmlSerializationReaderCodeGen.IsSequence(), System.Xml.Serialization.AccessorMapping.IsText, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.text, System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.AccessorMapping.Xmlns.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateTypeElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().