Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes
WriteAttributes()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes (Member[] members, Member anyAttribute, string elseCall, string firstParam) inline private
Definition at line 1711 of file XmlSerializationReaderCodeGen.cs.
    {
        int num = 0;
        Member member = null;
        ArrayList arrayList = new ArrayList();
        base.Writer.WriteLine("while (Reader.MoveToNextAttribute()) {");
        base.Writer.Indent++;
        foreach (Member member2 in members)
        {
            if (member2.Mapping.Xmlns != null)
            {
                member = member2;
            }
            else
            {
                if (member2.Mapping.Ignore)
                {
                    continue;
                }
                AttributeAccessor attribute = member2.Mapping.Attribute;
                if (attribute != null && !attribute.Any)
                {
                    arrayList.Add(attribute);
                    if (num++ > 0)
                    {
                        base.Writer.Write("else ");
                    }
                    base.Writer.Write("if (");
                    if (member2.ParamsReadSource != null)
                    {
                        base.Writer.Write("!");
                        base.Writer.Write(member2.ParamsReadSource);
                        base.Writer.Write(" && ");
                    }
                    if (attribute.IsSpecialXmlNamespace)
                    {
                        WriteXmlNodeEqual("Reader", attribute.Name, "http://www.w3.org/XML/1998/namespace");
                    }
                    else
                    {
                        WriteXmlNodeEqual("Reader", attribute.Name, (attribute.Form == XmlSchemaForm.Qualified) ? attribute.Namespace : "");
                    }
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                    WriteAttribute(member2);
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
        }
        if (num > 0)
        {
            base.Writer.Write("else ");
        }
        if (member != null)
        {
            base.Writer.WriteLine("if (IsXmlnsAttribute(Reader.Name)) {");
            base.Writer.Indent++;
            base.Writer.Write("if (");
            base.Writer.Write(member.Source);
            base.Writer.Write(" == null) ");
            base.Writer.Write(member.Source);
            base.Writer.Write(" = new ");
            base.Writer.Write(member.Mapping.TypeDesc.CSharpName);
            base.Writer.WriteLine("();");
            base.Writer.Write("((" + member.Mapping.TypeDesc.CSharpName + ")" + member.ArraySource + ")");
            base.Writer.WriteLine(".Add(Reader.Name.Length == 5 ? \"\" : Reader.LocalName, Reader.Value);");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            base.Writer.WriteLine("else {");
            base.Writer.Indent++;
        }
        else
        {
            base.Writer.WriteLine("if (!IsXmlnsAttribute(Reader.Name)) {");
            base.Writer.Indent++;
        }
        if (anyAttribute != null)
        {
            base.Writer.Write(typeof(XmlAttribute).FullName);
            base.Writer.Write(" attr = ");
            base.Writer.Write("(");
            base.Writer.Write(typeof(XmlAttribute).FullName);
            base.Writer.WriteLine(") Document.ReadNode(Reader);");
            base.Writer.WriteLine("ParseWsdlArrayType(attr);");
            WriteAttribute(anyAttribute);
        }
        else
        {
            base.Writer.Write(elseCall);
            base.Writer.Write("(");
            base.Writer.Write(firstParam);
            if (arrayList.Count > 0)
            {
                base.Writer.Write(", ");
                string text = "";
                for (int j = 0; j < arrayList.Count; j++)
                {
                    AttributeAccessor attributeAccessor = (AttributeAccessor)arrayList[j];
                    if (j > 0)
                    {
                        text += ", ";
                    }
                    text += (attributeAccessor.IsSpecialXmlNamespace ? "http://www.w3.org/XML/1998/namespace" : (((attributeAccessor.Form == XmlSchemaForm.Qualified) ? attributeAccessor.Namespace : "") + ":" + attributeAccessor.Name));
                }
                WriteQuotedCSharpString(text);
            }
            base.Writer.WriteLine(");");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArraySource, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Source, System.text, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttribute(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteXmlNodeEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().