Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod
WriteLiteralStructMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod (StructMapping structMapping) inline private
Definition at line 1244 of file XmlSerializationReaderCodeGen.cs.
    {
        string s = (string)base.MethodNames[structMapping];
        bool useReflection = structMapping.TypeDesc.UseReflection;
        string text = (useReflection ? "object" : structMapping.TypeDesc.CSharpName);
        base.Writer.WriteLine();
        base.Writer.Write(text);
        base.Writer.Write(" ");
        base.Writer.Write(s);
        base.Writer.Write("(");
        if (structMapping.TypeDesc.IsNullable)
        {
            base.Writer.Write("bool isNullable, ");
        }
        base.Writer.WriteLine("bool checkType) {");
        base.Writer.Indent++;
        base.Writer.Write(typeof(XmlQualifiedName).FullName);
        base.Writer.WriteLine(" xsiType = checkType ? GetXsiType() : null;");
        base.Writer.WriteLine("bool isNull = false;");
        if (structMapping.TypeDesc.IsNullable)
        {
            base.Writer.WriteLine("if (isNullable) isNull = ReadNull();");
        }
        base.Writer.WriteLine("if (checkType) {");
        if (structMapping.TypeDesc.IsRoot)
        {
            base.Writer.Indent++;
            base.Writer.WriteLine("if (isNull) {");
            base.Writer.Indent++;
            base.Writer.WriteLine("if (xsiType != null) return (" + text + ")ReadTypedNull(xsiType);");
            base.Writer.Write("else return ");
            if (structMapping.TypeDesc.IsValueType)
            {
                base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(structMapping.TypeDesc.CSharpName, useReflection, ctorInaccessible: false, cast: false));
                base.Writer.WriteLine(";");
            }
            else
            {
                base.Writer.WriteLine("null;");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
        base.Writer.Write("if (xsiType == null");
        if (!structMapping.TypeDesc.IsRoot)
        {
            base.Writer.Write(" || ");
            WriteQNameEqual("xsiType", structMapping.TypeName, structMapping.Namespace);
        }
        base.Writer.WriteLine(") {");
        if (structMapping.TypeDesc.IsRoot)
        {
            base.Writer.Indent++;
            base.Writer.WriteLine("return ReadTypedPrimitive(new System.Xml.XmlQualifiedName(\"anyType\", \"http://www.w3.org/2001/XMLSchema\"));");
            base.Writer.Indent--;
        }
        base.Writer.WriteLine("}");
        base.Writer.WriteLine("else {");
        base.Writer.Indent++;
        WriteDerivedTypes(structMapping, !useReflection && !structMapping.TypeDesc.IsRoot, text);
        if (structMapping.TypeDesc.IsRoot)
        {
            WriteEnumAndArrayTypes();
        }
        if (structMapping.TypeDesc.IsRoot)
        {
            base.Writer.Write("return ReadTypedPrimitive((");
        }
        else
        {
            base.Writer.Write("throw CreateUnknownTypeException((");
        }
        base.Writer.Write(typeof(XmlQualifiedName).FullName);
        base.Writer.WriteLine(")xsiType);");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (structMapping.TypeDesc.IsRoot)
        {
            base.Writer.Indent--;
        }
        base.Writer.WriteLine("}");
        if (structMapping.TypeDesc.IsNullable)
        {
            base.Writer.WriteLine("if (isNull) return null;");
        }
        if (structMapping.TypeDesc.IsAbstract)
        {
            base.Writer.Write("throw CreateAbstractTypeException(");
            WriteQuotedCSharpString(structMapping.TypeName);
            base.Writer.Write(", ");
            WriteQuotedCSharpString(structMapping.Namespace);
            base.Writer.WriteLine(");");
        }
        else
        {
            if (structMapping.TypeDesc.Type != null && typeof(XmlSchemaObject).IsAssignableFrom(structMapping.TypeDesc.Type))
            {
                base.Writer.WriteLine("DecodeName = false;");
            }
            WriteCreateMapping(structMapping, "o");
            MemberMapping[] settableMembers = TypeScope.GetSettableMembers(structMapping);
            Member member = null;
            Member member2 = null;
            Member member3 = null;
            bool flag = structMapping.HasExplicitSequence();
            List<Member> list = new List<Member>(settableMembers.Length);
            List<Member> list2 = new List<Member>(settableMembers.Length);
            List<Member> list3 = new List<Member>(settableMembers.Length);
            for (int i = 0; i < settableMembers.Length; i++)
            {
                MemberMapping memberMapping = settableMembers[i];
                CodeIdentifier.CheckValidIdentifier(memberMapping.Name);
                string stringForMember = base.RaCodeGen.GetStringForMember("o", memberMapping.Name, structMapping.TypeDesc);
                Member member4 = new Member(this, stringForMember, "a", i, memberMapping, GetChoiceIdentifierSource(memberMapping, "o", structMapping.TypeDesc));
                if (!memberMapping.IsSequence)
                {
                    member4.ParamsReadSource = $"paramsRead[{i}]";
                }
                member4.IsNullable = memberMapping.TypeDesc.IsNullable;
                if (memberMapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
                {
                    member4.CheckSpecifiedSource = base.RaCodeGen.GetStringForMember("o", memberMapping.Name + "Specified", structMapping.TypeDesc);
                }
                if (memberMapping.Text != null)
                {
                    member = member4;
                }
                if (memberMapping.Attribute != null && memberMapping.Attribute.Any)
                {
                    member3 = member4;
                }
                if (!flag)
                {
                    for (int j = 0; j < memberMapping.Elements.Length; j++)
                    {
                        if (memberMapping.Elements[j].Any && (memberMapping.Elements[j].Name == null || memberMapping.Elements[j].Name.Length == 0))
{
                            member2 = member4;
                            break;
                        }
                    }
                }
                else if (memberMapping.IsParticle && !memberMapping.IsSequence)
                {
                    structMapping.FindDeclaringMapping(memberMapping, out var declaringMapping, structMapping.TypeName);
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlSequenceHierarchy, structMapping.TypeDesc.FullName, memberMapping.Name, declaringMapping.TypeDesc.FullName, "Order"));
                }
                if (memberMapping.Attribute == null && memberMapping.Elements.Length == 1 && memberMapping.Elements[0].Mapping is ArrayMapping)
                {
                    Member member5 = new Member(this, stringForMember, stringForMember, "a", i, memberMapping, GetChoiceIdentifierSource(memberMapping, "o", structMapping.TypeDesc));
                    member5.CheckSpecifiedSource = member4.CheckSpecifiedSource;
                    list3.Add(member5);
                }
                else
                {
                    list3.Add(member4);
                }
                if (!memberMapping.TypeDesc.IsArrayLike)
                {
                    continue;
                }
                list.Add(member4);
                if (memberMapping.TypeDesc.IsArrayLike && (memberMapping.Elements.Length != 1 || !(memberMapping.Elements[0].Mapping is ArrayMapping)))
                {
                    member4.ParamsReadSource = null;
                    if (member4 != member && member4 != member2)
                    {
                        list2.Add(member4);
                    }
                }
                else if (!memberMapping.TypeDesc.IsArray)
                {
                    member4.ParamsReadSource = null;
                }
            }
            if (member2 != null)
            {
                list2.Add(member2);
            }
            if (member != null && member != member2)
            {
                list2.Add(member);
            }
            Member[] members = list.ToArray();
            Member[] members2 = list2.ToArray();
            Member[] members3 = list3.ToArray();
            WriteMemberBegin(members);
            WriteParamsRead(settableMembers.Length);
            WriteAttributes(members3, member3, "UnknownNode", "(object)o");
            if (member3 != null)
            {
                WriteMemberEnd(members);
            }
            base.Writer.WriteLine("Reader.MoveToElement();");
            base.Writer.WriteLine("if (Reader.IsEmptyElement) {");
            base.Writer.Indent++;
            base.Writer.WriteLine("Reader.Skip();");
            WriteMemberEnd(members2);
            base.Writer.WriteLine("return o;");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            base.Writer.WriteLine("Reader.ReadStartElement();");
            if (IsSequence(members3))
            {
                base.Writer.WriteLine("int state = 0;");
            }
            WriteWhileNotLoopStart();
            base.Writer.Indent++;
            string text2 = "UnknownNode((object)o, " + ExpectedElements(members3) + ");";
            WriteMemberElements(members3, text2, text2, member2, member, null);
            base.Writer.WriteLine("Reader.MoveToContent();");
            WriteWhileLoopEnd();
            WriteMemberEnd(members2);
            base.Writer.WriteLine("ReadEndElement();");
            base.Writer.WriteLine("return o;");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements(), System.SR.Format(), System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.Xml.Serialization.XmlSerializationReaderCodeGen.IsSequence(), System.list, System.s, System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateMapping(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedTypes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumAndArrayTypes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteParamsRead(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileNotLoopStart(), and System.SR.XmlSequenceHierarchy.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteStructMethod().