Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource
GetChoiceIdentifierSource() [2/2]
string System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource (MemberMapping[] mappings, MemberMapping member) inline private
Definition at line 466 of file XmlSerializationReaderCodeGen.cs.
    {
        string result = null;
        if (member.ChoiceIdentifier != null)
        {
            for (int i = 0; i < mappings.Length; i++)
            {
                if (mappings[i].Name == member.ChoiceIdentifier.MemberName)
                {
                    result = $"p[{i}]";
                    break;
                }
            }
        }
        return result;
    }
References System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.ChoiceIdentifierAccessor.MemberName, and System.Xml.Name.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().