Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsIf
WriteMemberElementsIf()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsIf (Member[] members, Member anyElement, string elementElseString, string checkTypeSource) inline private
Definition at line 2194 of file XmlSerializationReaderCodeGen.cs.
    {
        bool flag = checkTypeSource != null && checkTypeSource.Length > 0;
        int num = 0;
        bool flag2 = IsSequence(members);
        if (flag2)
        {
            base.Writer.WriteLine("switch (state) {");
        }
        int num2 = 0;
        foreach (Member member in members)
        {
            if (member.Mapping.Xmlns != null || member.Mapping.Ignore || (flag2 && (member.Mapping.IsText || member.Mapping.IsAttribute)))
            {
                continue;
            }
            bool flag3 = true;
            ChoiceIdentifierAccessor choiceIdentifier = member.Mapping.ChoiceIdentifier;
            ElementAccessor[] elements = member.Mapping.Elements;
            for (int j = 0; j < elements.Length; j++)
            {
                ElementAccessor elementAccessor = elements[j];
                string ns = ((elementAccessor.Form == XmlSchemaForm.Qualified) ? elementAccessor.Namespace : "");
                if (!flag2 && elementAccessor.Any && (elementAccessor.Name == null || elementAccessor.Name.Length == 0))
                {
                    continue;
                }
                if (!flag2)
                {
                    if (flag3 && num == 0)
                    {
                        base.Writer.WriteLine("do {");
                        base.Writer.Indent++;
                    }
                }
                else if (!flag3 || (!flag2 && num > 0))
                {
                    base.Writer.Write("else ");
                }
                else if (flag2)
                {
                    base.Writer.Write("case ");
                    base.Writer.Write(num2.ToString(CultureInfo.InvariantCulture));
                    base.Writer.WriteLine(":");
                    base.Writer.Indent++;
                }
                num++;
                flag3 = false;
                base.Writer.Write("if (");
                if (member.ParamsReadSource != null)
                {
                    base.Writer.Write("!");
                    base.Writer.Write(member.ParamsReadSource);
                    base.Writer.Write(" && ");
                }
                if (flag)
                {
                    if (elementAccessor.Mapping is NullableMapping)
                    {
                        TypeDesc typeDesc = ((NullableMapping)elementAccessor.Mapping).BaseMapping.TypeDesc;
                        base.Writer.Write(base.RaCodeGen.GetStringForTypeof(typeDesc.CSharpName, typeDesc.UseReflection));
                    }
                    else
                    {
                        base.Writer.Write(base.RaCodeGen.GetStringForTypeof(elementAccessor.Mapping.TypeDesc.CSharpName, elementAccessor.Mapping.TypeDesc.UseReflection));
                    }
                    base.Writer.Write(".IsAssignableFrom(");
                    base.Writer.Write(checkTypeSource);
                    base.Writer.Write("Type)");
                }
                else
                {
                    if (member.Mapping.IsReturnValue)
                    {
                        base.Writer.Write("(IsReturnValue || ");
                    }
                    if (flag2 && elementAccessor.Any && elementAccessor.AnyNamespaces == null)
                    {
                        base.Writer.Write("true");
                    }
                    else
                    {
                        WriteXmlNodeEqual("Reader", elementAccessor.Name, ns);
                    }
                    if (member.Mapping.IsReturnValue)
                    {
                        base.Writer.Write(")");
                    }
                }
                base.Writer.WriteLine(") {");
                base.Writer.Indent++;
                if (flag)
                {
                    if (elementAccessor.Mapping.TypeDesc.IsValueType || elementAccessor.Mapping is NullableMapping)
                    {
                        base.Writer.Write("if (");
                        base.Writer.Write(checkTypeSource);
                        base.Writer.WriteLine(" != null) {");
                        base.Writer.Indent++;
                    }
                    if (elementAccessor.Mapping is NullableMapping)
                    {
                        WriteSourceBegin(member.ArraySource);
                        TypeDesc typeDesc2 = ((NullableMapping)elementAccessor.Mapping).BaseMapping.TypeDesc;
                        base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(elementAccessor.Mapping.TypeDesc.CSharpName, elementAccessor.Mapping.TypeDesc.UseReflection, ctorInaccessible: false, cast: true, "(" + typeDesc2.CSharpName + ")" + checkTypeSource));
                    }
                    else
                    {
                        WriteSourceBeginTyped(member.ArraySource, elementAccessor.Mapping.TypeDesc);
                        base.Writer.Write(checkTypeSource);
                    }
                    WriteSourceEnd(member.ArraySource);
                    base.Writer.WriteLine(";");
                    if (elementAccessor.Mapping.TypeDesc.IsValueType)
                    {
                        base.Writer.Indent--;
                        base.Writer.WriteLine("}");
                    }
                    if (member.FixupIndex >= 0)
                    {
                        base.Writer.Write("fixup.Ids[");
                        base.Writer.Write(member.FixupIndex.ToString(CultureInfo.InvariantCulture));
                        base.Writer.Write("] = ");
                        base.Writer.Write(checkTypeSource);
                        base.Writer.WriteLine("Id;");
                    }
                }
                else
                {
                    WriteElement(member.ArraySource, member.ArrayName, member.ChoiceArraySource, elementAccessor, choiceIdentifier, (member.Mapping.CheckSpecified == SpecifiedAccessor.ReadWrite) ? member.CheckSpecifiedSource : null, member.IsList && member.Mapping.TypeDesc.IsNullable, member.Mapping.ReadOnly, member.FixupIndex, j);
                }
                if (member.Mapping.IsReturnValue)
                {
                    base.Writer.WriteLine("IsReturnValue = false;");
                }
                if (member.ParamsReadSource != null)
                {
                    base.Writer.Write(member.ParamsReadSource);
                    base.Writer.WriteLine(" = true;");
                }
                if (!flag2)
                {
                    base.Writer.WriteLine("break;");
                }
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            if (flag2)
            {
                if (member.IsArrayLike)
                {
                    base.Writer.WriteLine("else {");
                    base.Writer.Indent++;
                }
                num2++;
                base.Writer.Write("state = ");
                base.Writer.Write(num2.ToString(CultureInfo.InvariantCulture));
                base.Writer.WriteLine(";");
                if (member.IsArrayLike)
                {
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                base.Writer.WriteLine("break;");
                base.Writer.Indent--;
            }
        }
        if (num > 0 && flag2)
        {
            base.Writer.WriteLine("default:");
            base.Writer.Indent++;
        }
        WriteMemberElementsElse(anyElement, elementElseString);
        if (num > 0)
        {
            if (flag2)
            {
                base.Writer.WriteLine("break;");
            }
            base.Writer.Indent--;
            if (!flag2)
            {
                base.Writer.WriteLine("} while (false);");
            }
            else
            {
                base.Writer.WriteLine("}");
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArraySource, System.Xml.Serialization.MemberMapping.CheckSpecified, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.CheckSpecifiedSource, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ChoiceArraySource, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Dictionary, System.Xml.Serialization.AccessorMapping.Elements, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.FixupIndex, System.Xml.Serialization.AccessorMapping.Ignore, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsArrayLike, System.Xml.Serialization.AccessorMapping.IsAttribute, System.Xml.Serialization.TypeDesc.IsNullable, System.Xml.Serialization.MemberMapping.IsReturnValue, System.Xml.Serialization.XmlSerializationReaderCodeGen.IsSequence(), System.Xml.Serialization.AccessorMapping.IsText, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ParamsReadSource, System.Xml.Serialization.MemberMapping.ReadOnly, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElementsElse(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteXmlNodeEqual(), and System.Xml.Serialization.AccessorMapping.Xmlns.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHandleHrefList(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements().