Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteUnknownNode
WriteUnknownNode()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteUnknownNode (string func, string node, ElementAccessor e, bool anyIfs) inline private
Definition at line 376 of file XmlSerializationReaderCodeGen.cs.
    {
        if (anyIfs)
        {
            base.Writer.WriteLine("else {");
            base.Writer.Indent++;
        }
        base.Writer.Write(func);
        base.Writer.Write("(");
        base.Writer.Write(node);
        if (e != null)
        {
            base.Writer.Write(", ");
            string text = ((e.Form == XmlSchemaForm.Qualified) ? e.Namespace : "");
            text += ":";
            text += e.Name;
            ReflectionAwareCodeGen.WriteQuotedCSharpString(base.Writer, text);
        }
        base.Writer.WriteLine(");");
        if (anyIfs)
        {
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.Accessor.Name, System.Xml.Serialization.Accessor.Namespace, System.text, and System.Xml.Serialization.ReflectionAwareCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateLiteralMembersElement(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement().