Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateBegin
GenerateBegin()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateBegin () inline package
Definition at line 246 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.Write(base.Access);
        base.Writer.Write(" class ");
        base.Writer.Write(base.ClassName);
        base.Writer.Write(" : ");
        base.Writer.Write(typeof(XmlSerializationReader).FullName);
        base.Writer.WriteLine(" {");
        base.Writer.Indent++;
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (TypeMapping typeMapping3 in typeScope.TypeMappings)
            {
                if (typeMapping3 is StructMapping || typeMapping3 is EnumMapping || typeMapping3 is NullableMapping)
                {
                    base.MethodNames.Add(typeMapping3, NextMethodName(typeMapping3.TypeDesc.Name));
                }
            }
            base.RaCodeGen.WriteReflectionInit(typeScope);
        }
        TypeScope[] scopes2 = base.Scopes;
        foreach (TypeScope typeScope2 in scopes2)
        {
            foreach (TypeMapping typeMapping4 in typeScope2.TypeMappings)
            {
                if (typeMapping4.IsSoap)
                {
                    if (typeMapping4 is StructMapping)
                    {
                        WriteStructMethod((StructMapping)typeMapping4);
                    }
                    else if (typeMapping4 is EnumMapping)
                    {
                        WriteEnumMethod((EnumMapping)typeMapping4);
                    }
                    else if (typeMapping4 is NullableMapping)
                    {
                        WriteNullableMethod((NullableMapping)typeMapping4);
                    }
                }
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationReaderCodeGen.NextMethodName(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteNullableMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteStructMethod().