Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateMapping
WriteCreateMapping()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateMapping (TypeMapping mapping, string local) inline private
Definition at line 3006 of file XmlSerializationReaderCodeGen.cs.
    {
        string cSharpName = mapping.TypeDesc.CSharpName;
        bool useReflection = mapping.TypeDesc.UseReflection;
        bool cannotNew = mapping.TypeDesc.CannotNew;
        base.Writer.Write(useReflection ? "object" : cSharpName);
        base.Writer.Write(" ");
        base.Writer.Write(local);
        base.Writer.WriteLine(";");
        if (cannotNew)
        {
            base.Writer.WriteLine("try {");
            base.Writer.Indent++;
        }
        base.Writer.Write(local);
        base.Writer.Write(" = ");
        base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(cSharpName, useReflection, mapping.TypeDesc.CannotNew, cast: true));
        base.Writer.WriteLine(";");
        if (cannotNew)
        {
            WriteCatchException(typeof(MissingMethodException));
            base.Writer.Indent++;
            base.Writer.Write("throw CreateInaccessibleConstructorException(");
            WriteQuotedCSharpString(cSharpName);
            base.Writer.WriteLine(");");
            WriteCatchException(typeof(SecurityException));
            base.Writer.Indent++;
            base.Writer.Write("throw CreateCtorHasSecurityException(");
            WriteQuotedCSharpString(cSharpName);
            base.Writer.WriteLine(");");
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCatchException(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().