Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable
WriteDerivedSerializable()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable (SerializableMapping head, SerializableMapping mapping, string source, bool isWrappedAny) inline private
Definition at line 2847 of file XmlSerializationReaderCodeGen.cs.
    {
        if (mapping == null)
        {
            return;
        }
        for (SerializableMapping serializableMapping = mapping.DerivedMappings; serializableMapping != null; serializableMapping = serializableMapping.NextDerivedMapping)
        {
            base.Writer.Write("else if (tser == null");
            base.Writer.Write(" || ");
            WriteQNameEqual("tser", serializableMapping.XsiType.Name, serializableMapping.XsiType.Namespace);
            base.Writer.WriteLine(") {");
            base.Writer.Indent++;
            if (serializableMapping.Type != null)
            {
                if (head.Type.IsAssignableFrom(serializableMapping.Type))
                {
                    WriteSourceBeginTyped(source, head.TypeDesc);
                    base.Writer.Write("ReadSerializable(( ");
                    base.Writer.Write(typeof(IXmlSerializable).FullName);
                    base.Writer.Write(")");
                    base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(serializableMapping.TypeDesc.CSharpName, serializableMapping.TypeDesc.UseReflection, serializableMapping.TypeDesc.CannotNew, cast: false));
                    if (isWrappedAny)
                    {
                        base.Writer.WriteLine(", true");
                    }
                    base.Writer.Write(")");
                    WriteSourceEnd(source);
                    base.Writer.WriteLine(";");
                }
                else
                {
                    base.Writer.Write("throw CreateBadDerivationException(");
                    WriteQuotedCSharpString(serializableMapping.XsiType.Name);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(serializableMapping.XsiType.Namespace);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(head.XsiType.Name);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(head.XsiType.Namespace);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(serializableMapping.Type.FullName);
                    base.Writer.Write(", ");
                    WriteQuotedCSharpString(head.Type.FullName);
                    base.Writer.WriteLine(");");
                }
            }
            else
            {
                base.Writer.WriteLine("// missing real mapping for " + serializableMapping.XsiType);
                base.Writer.Write("throw CreateMissingIXmlSerializableType(");
                WriteQuotedCSharpString(serializableMapping.XsiType.Name);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(serializableMapping.XsiType.Namespace);
                base.Writer.Write(", ");
                WriteQuotedCSharpString(head.Type.FullName);
                base.Writer.WriteLine(");");
            }
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
            WriteDerivedSerializable(head, serializableMapping, source, isWrappedAny);
        }
    }
References System.Xml.Dictionary, System.Type.FullName, System.FullName, System.Type.IsAssignableFrom(), System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, System.source, System.Xml.Serialization.SerializableMapping.Type, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), and System.Xml.Serialization.SerializableMapping.XsiType.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteDerivedSerializable(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement().