Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray
WriteArray()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray (string source, string arrayName, ArrayMapping arrayMapping, bool readOnly, bool isNullable, int fixupIndex) inline private
Definition at line 2522 of file XmlSerializationReaderCodeGen.cs.
    {
        if (arrayMapping.IsSoap)
        {
            base.Writer.Write("object rre = ");
            base.Writer.Write((fixupIndex >= 0) ? "ReadReferencingElement" : "ReadReferencedElement");
            base.Writer.Write("(");
            WriteID(arrayMapping.TypeName);
            base.Writer.Write(", ");
            WriteID(arrayMapping.Namespace);
            if (fixupIndex >= 0)
            {
                base.Writer.Write(", ");
                base.Writer.Write("out fixup.Ids[");
                base.Writer.Write(fixupIndex.ToString(CultureInfo.InvariantCulture));
                base.Writer.Write("]");
            }
            base.Writer.WriteLine(");");
            TypeDesc typeDesc = arrayMapping.TypeDesc;
            if (typeDesc.IsEnumerable || typeDesc.IsCollection)
            {
                base.Writer.WriteLine("if (rre != null) {");
                base.Writer.Indent++;
                WriteAddCollectionFixup(typeDesc, readOnly, source, "rre");
                base.Writer.Indent--;
                base.Writer.WriteLine("}");
            }
            else
            {
                base.Writer.WriteLine("try {");
                base.Writer.Indent++;
                WriteSourceBeginTyped(source, arrayMapping.TypeDesc);
                base.Writer.Write("rre");
                WriteSourceEnd(source);
                base.Writer.WriteLine(";");
                WriteCatchCastException(arrayMapping.TypeDesc, "rre", null);
            }
            return;
        }
        base.Writer.WriteLine("if (!ReadNull()) {");
        base.Writer.Indent++;
        MemberMapping memberMapping = new MemberMapping();
        memberMapping.Elements = arrayMapping.Elements;
        memberMapping.TypeDesc = arrayMapping.TypeDesc;
        memberMapping.ReadOnly = readOnly;
        Member member = new Member(this, source, arrayName, 0, memberMapping, multiRef: false);
        member.IsNullable = false;
        Member[] members = new Member[1] { member };
        WriteMemberBegin(members);
        if (readOnly)
        {
            base.Writer.Write("if (((object)(");
            base.Writer.Write(member.ArrayName);
            base.Writer.Write(") == null) || ");
        }
        else
        {
            base.Writer.Write("if (");
        }
        base.Writer.WriteLine("(Reader.IsEmptyElement)) {");
        base.Writer.Indent++;
        base.Writer.WriteLine("Reader.Skip();");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.WriteLine("else {");
        base.Writer.Indent++;
        base.Writer.WriteLine("Reader.ReadStartElement();");
        WriteWhileNotLoopStart();
        base.Writer.Indent++;
        string text = "UnknownNode(null, " + ExpectedElements(members) + ");";
        WriteMemberElements(members, text, text, null, null, null);
        base.Writer.WriteLine("Reader.MoveToContent();");
        WriteWhileLoopEnd();
        base.Writer.Indent--;
        base.Writer.WriteLine("ReadEndElement();");
        base.Writer.WriteLine("}");
        WriteMemberEnd(members, soapRefs: false);
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (isNullable)
        {
            base.Writer.WriteLine("else {");
            base.Writer.Indent++;
            member.IsNullable = true;
            WriteMemberBegin(members);
            WriteMemberEnd(members);
            base.Writer.Indent--;
            base.Writer.WriteLine("}");
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.ExpectedElements(), System.Globalization.CultureInfo.InvariantCulture, System.source, System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAddCollectionFixup(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCatchCastException(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteID(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBeginTyped(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileNotLoopStart().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteElement(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumAndArrayTypes().