Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumAndArrayTypes
WriteEnumAndArrayTypes()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumAndArrayTypes () inline private
Definition at line 1111 of file XmlSerializationReaderCodeGen.cs.
    {
        TypeScope[] scopes = base.Scopes;
        foreach (TypeScope typeScope in scopes)
        {
            foreach (Mapping typeMapping in typeScope.TypeMappings)
            {
                if (typeMapping.IsSoap)
                {
                    continue;
                }
                if (typeMapping is EnumMapping)
                {
                    EnumMapping enumMapping = (EnumMapping)typeMapping;
                    base.Writer.Write("if (");
                    WriteQNameEqual("xsiType", enumMapping.TypeName, enumMapping.Namespace);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                    base.Writer.WriteLine("Reader.ReadStartElement();");
                    string s = ReferenceMapping(enumMapping);
                    base.Writer.Write("object e = ");
                    base.Writer.Write(s);
                    base.Writer.WriteLine("(CollapseWhitespace(Reader.ReadString()));");
                    base.Writer.WriteLine("ReadEndElement();");
                    base.Writer.WriteLine("return e;");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
                else
                {
                    if (!(typeMapping is ArrayMapping))
                    {
                        continue;
                    }
                    ArrayMapping arrayMapping = (ArrayMapping)typeMapping;
                    if (!arrayMapping.TypeDesc.HasDefaultConstructor)
                    {
                        continue;
                    }
                    base.Writer.Write("if (");
                    WriteQNameEqual("xsiType", arrayMapping.TypeName, arrayMapping.Namespace);
                    base.Writer.WriteLine(") {");
                    base.Writer.Indent++;
                    MemberMapping memberMapping = new MemberMapping();
                    memberMapping.TypeDesc = arrayMapping.TypeDesc;
                    memberMapping.Elements = arrayMapping.Elements;
                    Member member = new Member(this, "a", "z", 0, memberMapping);
                    TypeDesc typeDesc = arrayMapping.TypeDesc;
                    string cSharpName = arrayMapping.TypeDesc.CSharpName;
                    if (typeDesc.UseReflection)
                    {
                        if (typeDesc.IsArray)
{
                            base.Writer.Write(typeof(Array).FullName);
                        }
                        else
{
                            base.Writer.Write("object");
                        }
                    }
                    else
                    {
                        base.Writer.Write(cSharpName);
                    }
                    base.Writer.Write(" a = ");
                    if (arrayMapping.TypeDesc.IsValueType)
                    {
                        base.Writer.Write(base.RaCodeGen.GetStringForCreateInstance(cSharpName, typeDesc.UseReflection, ctorInaccessible: false, cast: false));
                        base.Writer.WriteLine(";");
                    }
                    else
                    {
                        base.Writer.WriteLine("null;");
                    }
                    WriteArray(member.Source, member.ArrayName, arrayMapping, readOnly: false, isNullable: false, -1);
                    base.Writer.WriteLine("return a;");
                    base.Writer.Indent--;
                    base.Writer.WriteLine("}");
                }
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.XmlSerializationCodeGen.ReferenceMapping(), System.s, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Source, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteArray(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteQNameEqual().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLiteralStructMethod().