Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateCollectionMethod
WriteCreateCollectionMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateCollectionMethod (CreateCollectionInfo c) inline private
Definition at line 1644 of file XmlSerializationReaderCodeGen.cs.
    {
        base.Writer.Write("void ");
        base.Writer.Write(c.Name);
        base.Writer.WriteLine("(object collection, object collectionItems) {");
        base.Writer.Indent++;
        base.Writer.WriteLine("if (collectionItems == null) return;");
        base.Writer.WriteLine("if (collection == null) return;");
        TypeDesc typeDesc = c.TypeDesc;
        bool useReflection = typeDesc.UseReflection;
        string cSharpName = typeDesc.CSharpName;
        WriteLocalDecl(cSharpName, "c", "collection", useReflection);
        WriteCreateCollection(typeDesc, "collectionItems");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.CreateCollectionInfo.Name, System.Xml.Serialization.XmlSerializationReaderCodeGen.CreateCollectionInfo.TypeDesc, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateCollection(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteLocalDecl().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEnd().