Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod
WriteEncodedStructMethod()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEncodedStructMethod (StructMapping structMapping) inline private
Definition at line 1464 of file XmlSerializationReaderCodeGen.cs.
    {
        if (structMapping.TypeDesc.IsRoot)
        {
            return;
        }
        string text = (string)base.MethodNames[structMapping];
        base.Writer.WriteLine();
        base.Writer.Write("object");
        base.Writer.Write(" ");
        base.Writer.Write(text);
        base.Writer.Write("(");
        base.Writer.WriteLine(") {");
        base.Writer.Indent++;
        Member[] array;
        bool flag;
        string fixupMethodName;
        if (structMapping.TypeDesc.IsAbstract)
        {
            base.Writer.Write("throw CreateAbstractTypeException(");
            WriteQuotedCSharpString(structMapping.TypeName);
            base.Writer.Write(", ");
            WriteQuotedCSharpString(structMapping.Namespace);
            base.Writer.WriteLine(");");
            array = Array.Empty<Member>();
            flag = false;
            fixupMethodName = null;
        }
        else
        {
            WriteCreateMapping(structMapping, "o");
            MemberMapping[] settableMembers = TypeScope.GetSettableMembers(structMapping);
            array = new Member[settableMembers.Length];
            for (int i = 0; i < settableMembers.Length; i++)
            {
                MemberMapping memberMapping = settableMembers[i];
                CodeIdentifier.CheckValidIdentifier(memberMapping.Name);
                string stringForMember = base.RaCodeGen.GetStringForMember("o", memberMapping.Name, structMapping.TypeDesc);
                Member member = new Member(this, stringForMember, stringForMember, "a", i, memberMapping, GetChoiceIdentifierSource(memberMapping, "o", structMapping.TypeDesc));
                if (memberMapping.CheckSpecified == SpecifiedAccessor.ReadWrite)
                {
                    member.CheckSpecifiedSource = base.RaCodeGen.GetStringForMember("o", memberMapping.Name + "Specified", structMapping.TypeDesc);
                }
                if (!memberMapping.IsSequence)
                {
                    member.ParamsReadSource = $"paramsRead[{i}]";
                }
                array[i] = member;
            }
            fixupMethodName = "fixup_" + text;
            flag = WriteMemberFixupBegin(array, fixupMethodName, "o");
            WriteParamsRead(settableMembers.Length);
            WriteAttributes(array, null, "UnknownNode", "(object)o");
            base.Writer.WriteLine("Reader.MoveToElement();");
            base.Writer.WriteLine("if (Reader.IsEmptyElement) { Reader.Skip(); return o; }");
            base.Writer.WriteLine("Reader.ReadStartElement();");
            WriteWhileNotLoopStart();
            base.Writer.Indent++;
            WriteMemberElements(array, "UnknownNode((object)o);", "UnknownNode((object)o);", null, null, null);
            base.Writer.WriteLine("Reader.MoveToContent();");
            WriteWhileLoopEnd();
            base.Writer.WriteLine("ReadEndElement();");
            base.Writer.WriteLine("return o;");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        if (flag)
        {
            WriteFixupMethod(fixupMethodName, array, structMapping.TypeDesc.CSharpName, structMapping.TypeDesc.UseReflection, typed: true, "o");
        }
    }
References System.array, System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.GetChoiceIdentifierSource(), System.Xml.Serialization.TypeScope.GetSettableMembers(), System.text, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteAttributes(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateMapping(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteFixupMethod(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberElements(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberFixupBegin(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteParamsRead(), System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileLoopEnd(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteWhileNotLoopStart().
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteStructMethod().