Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEnd
GenerateEnd()
void System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateEnd (string[] methods, XmlMapping[] xmlMappings, Type[] types) inline package
Definition at line 313 of file XmlSerializationReaderCodeGen.cs.
    {
        GenerateReferencedMethods();
        GenerateInitCallbacksMethod();
        foreach (CreateCollectionInfo value in _createMethods.Values)
        {
            WriteCreateCollectionMethod(value);
        }
        base.Writer.WriteLine();
        foreach (string value2 in _idNames.Values)
        {
            base.Writer.Write("string ");
            base.Writer.Write(value2);
            base.Writer.WriteLine(";");
        }
        base.Writer.WriteLine();
        base.Writer.WriteLine("protected override void InitIDs() {");
        base.Writer.Indent++;
        foreach (string key in _idNames.Keys)
        {
            string s2 = (string)_idNames[key];
            base.Writer.Write(s2);
            base.Writer.Write(" = Reader.NameTable.Add(");
            WriteQuotedCSharpString(key);
            base.Writer.WriteLine(");");
        }
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen._createMethods, System.Xml.Serialization.XmlSerializationReaderCodeGen._idNames, System.Xml.Serialization.XmlSerializationReaderCodeGen.GenerateInitCallbacksMethod(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateReferencedMethods(), System.key, System.Collections.Hashtable.Keys, System.value, System.Collections.Hashtable.Values, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteCreateCollectionMethod(), and System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString().