Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable
WriteHashtable()
string System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteHashtable (EnumMapping mapping, string typeName) inline private
Definition at line 932 of file XmlSerializationReaderCodeGen.cs.
    {
        CodeIdentifier.CheckValidIdentifier(typeName);
        string text = MakeUnique(mapping, typeName + "Values");
        if (text == null)
        {
            return CodeIdentifier.GetCSharpName(typeName);
        }
        string s = MakeUnique(mapping, "_" + text);
        text = CodeIdentifier.GetCSharpName(text);
        base.Writer.WriteLine();
        base.Writer.Write(typeof(Hashtable).FullName);
        base.Writer.Write(" ");
        base.Writer.Write(s);
        base.Writer.WriteLine(";");
        base.Writer.WriteLine();
        base.Writer.Write("internal ");
        base.Writer.Write(typeof(Hashtable).FullName);
        base.Writer.Write(" ");
        base.Writer.Write(text);
        base.Writer.WriteLine(" {");
        base.Writer.Indent++;
        base.Writer.WriteLine("get {");
        base.Writer.Indent++;
        base.Writer.Write("if ((object)");
        base.Writer.Write(s);
        base.Writer.WriteLine(" == null) {");
        base.Writer.Indent++;
        base.Writer.Write(typeof(Hashtable).FullName);
        base.Writer.Write(" h = new ");
        base.Writer.Write(typeof(Hashtable).FullName);
        base.Writer.WriteLine("();");
        ConstantMapping[] constants = mapping.Constants;
        for (int i = 0; i < constants.Length; i++)
        {
            base.Writer.Write("h.Add(");
            WriteQuotedCSharpString(constants[i].XmlName);
            if (!mapping.TypeDesc.UseReflection)
            {
                base.Writer.Write(", (long)");
                base.Writer.Write(mapping.TypeDesc.CSharpName);
                base.Writer.Write(".@");
                CodeIdentifier.CheckValidIdentifier(constants[i].Name);
                base.Writer.Write(constants[i].Name);
            }
            else
            {
                base.Writer.Write(", ");
                IndentedWriter writer = base.Writer;
                IFormatProvider invariantCulture = CultureInfo.InvariantCulture;
                DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(1, 1, invariantCulture);
                handler.AppendFormatted(constants[i].Value);
                handler.AppendLiteral("L");
                writer.Write(string.Create(invariantCulture, ref handler));
            }
            base.Writer.WriteLine(");");
        }
        base.Writer.Write(s);
        base.Writer.WriteLine(" = h;");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.Write("return ");
        base.Writer.Write(s);
        base.Writer.WriteLine(";");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        base.Writer.Indent--;
        base.Writer.WriteLine("}");
        return text;
    }
References System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.Xml.Serialization.CodeIdentifier.CheckValidIdentifier(), System.IO.Create, System.Xml.Dictionary, System.FullName, System.Xml.Serialization.CodeIdentifier.GetCSharpName(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.XmlSerializationReaderCodeGen.MakeUnique(), System.Xml.Name, System.s, System.text, System.Xml.Serialization.XmlSerializationCodeGen.WriteQuotedCSharpString(), and System.writer.
Referenced by System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteEnumMethod().