Terraria: System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberEnd
WriteMemberEnd() [2/2]
void System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteMemberEnd (Member[] members, bool soapRefs) inline private
Definition at line 2421 of file XmlSerializationReaderCodeGen.cs.
    {
        foreach (Member member in members)
        {
            if (!member.IsArrayLike)
            {
                continue;
            }
            TypeDesc typeDesc = member.Mapping.TypeDesc;
            if (typeDesc.IsArray)
            {
                WriteSourceBegin(member.Source);
                if (soapRefs)
                {
                    base.Writer.Write(" soap[1] = ");
                }
                string arrayName = member.ArrayName;
                string s = "c" + arrayName;
                bool useReflection = typeDesc.ArrayElementTypeDesc.UseReflection;
                string cSharpName = typeDesc.ArrayElementTypeDesc.CSharpName;
                if (!useReflection)
                {
                    base.Writer.Write("(" + cSharpName + "[])");
                }
                base.Writer.Write("ShrinkArray(");
                base.Writer.Write(arrayName);
                base.Writer.Write(", ");
                base.Writer.Write(s);
                base.Writer.Write(", ");
                base.Writer.Write(base.RaCodeGen.GetStringForTypeof(cSharpName, useReflection));
                base.Writer.Write(", ");
                WriteBooleanValue(member.IsNullable);
                base.Writer.Write(")");
                WriteSourceEnd(member.Source);
                base.Writer.WriteLine(";");
                if (member.Mapping.ChoiceIdentifier != null)
                {
                    WriteSourceBegin(member.ChoiceSource);
                    arrayName = member.ChoiceArrayName;
                    s = "c" + arrayName;
                    bool useReflection2 = member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.UseReflection;
                    string cSharpName2 = member.Mapping.ChoiceIdentifier.Mapping.TypeDesc.CSharpName;
                    if (!useReflection2)
                    {
                        base.Writer.Write("(" + cSharpName2 + "[])");
                    }
                    base.Writer.Write("ShrinkArray(");
                    base.Writer.Write(arrayName);
                    base.Writer.Write(", ");
                    base.Writer.Write(s);
                    base.Writer.Write(", ");
                    base.Writer.Write(base.RaCodeGen.GetStringForTypeof(cSharpName2, useReflection2));
                    base.Writer.Write(", ");
                    WriteBooleanValue(member.IsNullable);
                    base.Writer.Write(")");
                    WriteSourceEnd(member.ChoiceSource);
                    base.Writer.WriteLine(";");
                }
            }
            else if (typeDesc.IsValueType)
            {
                base.Writer.Write(member.Source);
                base.Writer.Write(" = ");
                base.Writer.Write(member.ArrayName);
                base.Writer.WriteLine(";");
            }
        }
    }
References System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ArrayName, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ChoiceArrayName, System.Xml.Serialization.AccessorMapping.ChoiceIdentifier, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.ChoiceSource, System.Xml.Serialization.TypeDesc.CSharpName, System.Xml.Dictionary, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsArrayLike, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.IsNullable, System.Xml.Serialization.Accessor.Mapping, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Mapping, System.s, System.Xml.Serialization.XmlSerializationReaderCodeGen.Member.Source, System.Xml.Serialization.AccessorMapping.TypeDesc, System.Xml.Serialization.TypeMapping.TypeDesc, System.Xml.Serialization.TypeDesc.UseReflection, System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteBooleanValue(), System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceBegin(), and System.Xml.Serialization.XmlSerializationReaderCodeGen.WriteSourceEnd().