Terraria: STATaskInvoker.STATaskInvoker
STATaskInvoker()
STATaskInvoker.STATaskInvoker () inline private
     {
         _shouldThreadContinue = true;
         _staThread = new Thread(TaskThreadStart);
         _staThread.Name = "STA Invoker Thread";
         _staThread.SetApartmentState(ApartmentState.STA);
         _staThread.Start();
     }
References _shouldThreadContinue, _staThread, and TaskThreadStart().
Referenced by Invoke(), and Invoke< T >().