Terraria: System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing
HandleResourceStreamMissing()
void System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing (string fileName) inline private
Definition at line 289 of file ManifestBasedResourceGroveler.cs.
    {
        if (_mediator.MainAssembly == typeof(object).Assembly && _mediator.BaseName.Equals("System.Private.CoreLib"))
        {
            Environment.FailFast("System.Private.CoreLib.resources couldn't be found!  Large parts of the BCL won't work!");
        }
        string text = string.Empty;
        if (_mediator.LocationInfo != null && _mediator.LocationInfo.Namespace != null)
        {
            text = _mediator.LocationInfo.Namespace + Type.Delimiter;
        }
        text += fileName;
        throw new MissingManifestResourceException(SR.Format(SR.MissingManifestResource_NoNeutralAsm, text, _mediator.MainAssembly.GetName().Name, GetManifestResourceNamesList(_mediator.MainAssembly)));
    }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Resources.ResourceManager.BaseName, System.Type.Delimiter, System.Environment.FailFast(), System.SR.Format(), System.Resources.ManifestBasedResourceGroveler.GetManifestResourceNamesList(), System.Reflection.Assembly.GetName(), System.Resources.ResourceManager.MainAssembly, System.SR.MissingManifestResource_NoNeutralAsm, and System.text.
Referenced by System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet().