Terraria: System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet
GrovelForResourceSet()
ResourceSet System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (CultureInfo culture, Dictionary< string, ResourceSet > localResourceSets, bool tryParents, bool createIfNotExists) inline
Implements System.Resources.IResourceGroveler.
Definition at line 23 of file ManifestBasedResourceGroveler.cs.
    {
        ResourceSet value = null;
        Stream stream = null;
        CultureInfo cultureInfo = UltimateFallbackFixup(culture);
        Assembly assembly;
        if (cultureInfo.HasInvariantCultureName && _mediator.FallbackLoc == UltimateResourceFallbackLocation.MainAssembly)
        {
            assembly = _mediator.MainAssembly;
        }
        else
        {
            assembly = GetSatelliteAssembly(cultureInfo);
            if (assembly == null && culture.HasInvariantCultureName && _mediator.FallbackLoc == UltimateResourceFallbackLocation.Satellite)
            {
                HandleSatelliteMissing();
            }
        }
        string resourceFileName = _mediator.GetResourceFileName(cultureInfo);
        if (assembly != null)
        {
            lock (localResourceSets)
            {
                localResourceSets.TryGetValue(culture.Name, out value);
            }
            stream = GetManifestResourceStream(assembly, resourceFileName);
        }
        if (createIfNotExists && stream != null && value == null)
        {
            value = CreateResourceSet(stream, assembly);
        }
        else if (stream == null && tryParents && culture.HasInvariantCultureName)
        {
            HandleResourceStreamMissing(resourceFileName);
        }
        return value;
    }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.culture, System.Resources.ManifestBasedResourceGroveler.GetManifestResourceStream(), System.Resources.ResourceManager.GetResourceFileName(), System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(), System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(), System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing(), System.Resources.ResourceManager.MainAssembly, System.stream, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.Resources.ManifestBasedResourceGroveler.UltimateFallbackFixup(), and System.value.