Terraria: System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData
InternalGetResourceSetFromSerializedData()
static ResourceSet System.Resources.ManifestBasedResourceGroveler.InternalGetResourceSetFromSerializedData (Stream store, string readerTypeName, string resSetTypeName, ResourceManager::ResourceManagerMediator mediator) inline static private
Definition at line 168 of file ManifestBasedResourceGroveler.cs.
    {
        IResourceReader resourceReader;
        if (ResourceManager.IsDefaultType(readerTypeName, "System.Resources.ResourceReader"))
        {
            resourceReader = new ResourceReader(store, new Dictionary<string, ResourceLocator>(FastResourceComparer.Default), permitDeserialization: true);
        }
        else
        {
            Type type = Type.GetType(readerTypeName, throwOnError: true);
            resourceReader = (IResourceReader)Activator.CreateInstance(type, store);
        }
        object[] args = new object[1] { resourceReader };
        Type type2 = mediator.UserResourceSet;
        if (type2 == null)
        {
            type2 = Type.GetType(resSetTypeName, throwOnError: true, ignoreCase: false);
        }
        return (ResourceSet)Activator.CreateInstance(type2, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.CreateInstance, null, args, null, null);
    }
References System.Activator.CreateInstance(), System.Resources.FastResourceComparer.Default, System.Type.GetType(), System.Resources.ResourceManager.IsDefaultType(), and System.type.
Referenced by System.Resources.ManifestBasedResourceGroveler.CreateResourceSet().