Terraria: System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
GetNeutralResourcesLanguage()
static CultureInfo System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage (Assembly a, out UltimateResourceFallbackLocation fallbackLocation) inline static package
Definition at line 75 of file ManifestBasedResourceGroveler.cs.
    {
        NeutralResourcesLanguageAttribute customAttribute = a.GetCustomAttribute<NeutralResourcesLanguageAttribute>();
        if (customAttribute == null || (GlobalizationMode.Invariant && GlobalizationMode.PredefinedCulturesOnly))
        {
            fallbackLocation = UltimateResourceFallbackLocation.MainAssembly;
            return CultureInfo.InvariantCulture;
        }
        fallbackLocation = customAttribute.Location;
        if (fallbackLocation < UltimateResourceFallbackLocation.MainAssembly || fallbackLocation > UltimateResourceFallbackLocation.Satellite)
        {
            throw new ArgumentException(SR.Format(SR.Arg_InvalidNeutralResourcesLanguage_FallbackLoc, fallbackLocation));
        }
        try
        {
            return CultureInfo.GetCultureInfo(customAttribute.CultureName);
        }
        catch (ArgumentException innerException)
        {
            if (a == typeof(object).Assembly)
            {
                return CultureInfo.InvariantCulture;
            }
            throw new ArgumentException(SR.Format(SR.Arg_InvalidNeutralResourcesLanguage_Asm_Culture, a, customAttribute.CultureName), innerException);
        }
    }
References System.SR.Arg_InvalidNeutralResourcesLanguage_Asm_Culture, System.SR.Arg_InvalidNeutralResourcesLanguage_FallbackLoc, System.SR.Format(), System.Globalization.CultureInfo.GetCultureInfo(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureInfo.InvariantCulture, and System.Globalization.GlobalizationMode.PredefinedCulturesOnly.
Referenced by System.Resources.ResourceManager.CommonAssemblyInit(), and System.Resources.ResourceManager.GetNeutralResourcesLanguage().