Terraria: System.Xml.Serialization.XmlSerializer.Deserialize
Deserialize() [5/7]
object? System.Xml.Serialization.XmlSerializer.Deserialize (XmlReader xmlReader, string? encodingStyle, XmlDeserializationEvents events) inline
Definition at line 506 of file XmlSerializer.cs.
    {
        events.sender = this;
        try
        {
            if (_primitiveType != null)
            {
                if (encodingStyle != null && encodingStyle.Length > 0)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidEncodingNotEncoded1, encodingStyle));
                }
                return DeserializePrimitive(xmlReader, events);
            }
            if (ShouldUseReflectionBasedSerialization(_mapping) || _isReflectionBasedSerializer)
            {
                return DeserializeUsingReflection(xmlReader, encodingStyle, events);
            }
            if (_tempAssembly == null || _typedSerializer)
            {
                XmlSerializationReader xmlSerializationReader = CreateReader();
                xmlSerializationReader.Init(xmlReader, events, encodingStyle, _tempAssembly);
                try
                {
                    return Deserialize(xmlSerializationReader);
                }
                finally
                {
                    xmlSerializationReader.Dispose();
                }
            }
            return _tempAssembly.InvokeReader(_mapping, xmlReader, events, encodingStyle);
        }
        catch (Exception innerException)
        {
            if (innerException is TargetInvocationException)
            {
                innerException = innerException.InnerException;
            }
            if (xmlReader is IXmlLineInfo)
            {
                IXmlLineInfo xmlLineInfo = (IXmlLineInfo)xmlReader;
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlSerializeErrorDetails, xmlLineInfo.LineNumber.ToString(CultureInfo.InvariantCulture), xmlLineInfo.LinePosition.ToString(CultureInfo.InvariantCulture)), innerException);
            }
            throw new InvalidOperationException(System.SR.XmlSerializeError, innerException);
        }
    }
References System.Xml.Serialization.XmlSerializer._isReflectionBasedSerializer, System.Xml.Serialization.XmlSerializer._mapping, System.Xml.Serialization.XmlSerializer._primitiveType, System.Xml.Serialization.XmlSerializer._tempAssembly, System.Xml.Serialization.XmlSerializer._typedSerializer, System.Xml.Serialization.XmlSerializer.CreateReader(), System.Xml.Serialization.XmlSerializer.Deserialize(), System.Xml.Serialization.XmlSerializer.DeserializePrimitive(), System.Xml.Serialization.XmlSerializer.DeserializeUsingReflection(), System.Xml.Dictionary, System.SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.Serialization.TempAssembly.InvokeReader(), System.Xml.Serialization.XmlSerializer.ShouldUseReflectionBasedSerialization(), System.SR.XmlInvalidEncodingNotEncoded1, System.SR.XmlSerializeError, and System.SR.XmlSerializeErrorDetails.