Terraria: System.Diagnostics.FileVersionInfo.ToString
ToString()
override string System.Diagnostics.FileVersionInfo.ToString () inline
Definition at line 133 of file FileVersionInfo.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(512);
        stringBuilder.Append("File:             ").AppendLine(FileName);
        stringBuilder.Append("InternalName:     ").AppendLine(InternalName);
        stringBuilder.Append("OriginalFilename: ").AppendLine(OriginalFilename);
        stringBuilder.Append("FileVersion:      ").AppendLine(FileVersion);
        stringBuilder.Append("FileDescription:  ").AppendLine(FileDescription);
        stringBuilder.Append("Product:          ").AppendLine(ProductName);
        stringBuilder.Append("ProductVersion:   ").AppendLine(ProductVersion);
        stringBuilder.Append("Debug:            ").AppendLine(IsDebug.ToString());
        stringBuilder.Append("Patched:          ").AppendLine(IsPatched.ToString());
        stringBuilder.Append("PreRelease:       ").AppendLine(IsPreRelease.ToString());
        stringBuilder.Append("PrivateBuild:     ").AppendLine(IsPrivateBuild.ToString());
        stringBuilder.Append("SpecialBuild:     ").AppendLine(IsSpecialBuild.ToString());
        stringBuilder.Append("Language:         ").AppendLine(Language);
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendLine(), System.Diagnostics.FileVersionInfo.FileDescription, System.Diagnostics.FileVersionInfo.FileName, System.Diagnostics.FileVersionInfo.FileVersion, System.Diagnostics.FileVersionInfo.InternalName, System.Diagnostics.FileVersionInfo.IsDebug, System.Diagnostics.FileVersionInfo.IsPatched, System.Diagnostics.FileVersionInfo.IsPreRelease, System.Diagnostics.FileVersionInfo.IsPrivateBuild, System.Diagnostics.FileVersionInfo.IsSpecialBuild, System.Diagnostics.FileVersionInfo.Language, System.Diagnostics.FileVersionInfo.OriginalFilename, System.Diagnostics.FileVersionInfo.ProductName, System.Diagnostics.FileVersionInfo.ProductVersion, and System.Text.StringBuilder.ToString().