Terraria: System.Xml.Serialization.XmlSerializer.DeserializePrimitive
DeserializePrimitive()
object System.Xml.Serialization.XmlSerializer.DeserializePrimitive (XmlReader xmlReader, XmlDeserializationEvents events) inline private
Definition at line 909 of file XmlSerializer.cs.
    {
        XmlSerializationPrimitiveReader xmlSerializationPrimitiveReader = new XmlSerializationPrimitiveReader();
        xmlSerializationPrimitiveReader.Init(xmlReader, events, null, null);
        switch (Type.GetTypeCode(_primitiveType))
        {
        case TypeCode.String:
            return xmlSerializationPrimitiveReader.Read_string();
        case TypeCode.Int32:
            return xmlSerializationPrimitiveReader.Read_int();
        case TypeCode.Boolean:
            return xmlSerializationPrimitiveReader.Read_boolean();
        case TypeCode.Int16:
            return xmlSerializationPrimitiveReader.Read_short();
        case TypeCode.Int64:
            return xmlSerializationPrimitiveReader.Read_long();
        case TypeCode.Single:
            return xmlSerializationPrimitiveReader.Read_float();
        case TypeCode.Double:
            return xmlSerializationPrimitiveReader.Read_double();
        case TypeCode.Decimal:
            return xmlSerializationPrimitiveReader.Read_decimal();
        case TypeCode.DateTime:
            return xmlSerializationPrimitiveReader.Read_dateTime();
        case TypeCode.Char:
            return xmlSerializationPrimitiveReader.Read_char();
        case TypeCode.Byte:
            return xmlSerializationPrimitiveReader.Read_unsignedByte();
        case TypeCode.SByte:
            return xmlSerializationPrimitiveReader.Read_byte();
        case TypeCode.UInt16:
            return xmlSerializationPrimitiveReader.Read_unsignedShort();
        case TypeCode.UInt32:
            return xmlSerializationPrimitiveReader.Read_unsignedInt();
        case TypeCode.UInt64:
            return xmlSerializationPrimitiveReader.Read_unsignedLong();
        default:
            if (_primitiveType == typeof(XmlQualifiedName))
            {
                return xmlSerializationPrimitiveReader.Read_QName();
            }
            if (_primitiveType == typeof(byte[]))
            {
                return xmlSerializationPrimitiveReader.Read_base64Binary();
            }
            if (_primitiveType == typeof(Guid))
            {
                return xmlSerializationPrimitiveReader.Read_guid();
            }
            if (_primitiveType == typeof(TimeSpan))
            {
                return xmlSerializationPrimitiveReader.Read_TimeSpan();
            }
            if (_primitiveType == typeof(DateTimeOffset))
            {
                return xmlSerializationPrimitiveReader.Read_dateTimeOffset();
            }
            throw new InvalidOperationException(System.SR.Format(System.SR.XmlUnxpectedType, _primitiveType.FullName));
        }
    }
References System.Xml.Serialization.XmlSerializer._primitiveType, System.Xml.Dictionary, System.SR.Format(), System.Type.FullName, System.Type.GetTypeCode(), and System.SR.XmlUnxpectedType.
Referenced by System.Xml.Serialization.XmlSerializer.Deserialize().