Terraria: System.Xml.Serialization.XmlSerializer.Deserialize
Deserialize() [1/7]
object? System.Xml.Serialization.XmlSerializer.Deserialize (Stream stream) inline
Definition at line 468 of file XmlSerializer.cs.
    {
        XmlReader xmlReader = XmlReader.Create(stream, new XmlReaderSettings
        {
            IgnoreWhitespace = true
        });
        return Deserialize(xmlReader, null);
    }
References System.Xml.XmlReader.Create(), System.Xml.Serialization.XmlSerializer.Deserialize(), and System.stream.
Referenced by System.Xml.Serialization.XmlSerializer.Deserialize(), System.Xml.Serialization.XmlSerializer.Deserialize(), System.Xml.Serialization.XmlSerializer.Deserialize(), System.Xml.Serialization.XmlSerializer.Deserialize(), System.Xml.Serialization.XmlSerializer.Deserialize(), and System.Xml.Serialization.XmlSerializer.Deserialize().