Terraria: System.Xml.Serialization.XmlSerializer.GetMapping
GetMapping()
XmlMapping System.Xml.Serialization.XmlSerializer.GetMapping () inline private
Definition at line 458 of file XmlSerializer.cs.
    {
        if (_mapping == null || !_mapping.GenerateSerializer)
        {
            _mapping = GenerateXmlTypeMapping(_rootType, null, null, null, DefaultNamespace);
        }
        return _mapping;
    }
References System.Xml.Serialization.XmlSerializer._mapping, System.Xml.Serialization.XmlSerializer._rootType, System.Xml.Serialization.XmlSerializer.DefaultNamespace, System.Xml.Serialization.XmlMapping.GenerateSerializer, and System.Xml.Serialization.XmlSerializer.GenerateXmlTypeMapping().
Referenced by System.Xml.Serialization.XmlSerializer.DeserializeUsingReflection(), and System.Xml.Serialization.XmlSerializer.SerializeUsingReflection().