Terraria: System.Xml.Base64Encoder.Encode
Encode()
void System.Xml.Base64Encoder.Encode (byte[] buffer, int index, int count) inline package inherited
Definition at line 20 of file Base64Encoder.cs.
    {
        if (buffer == null)
        {
            throw new ArgumentNullException("buffer");
        }
        if (index < 0)
        {
            throw new ArgumentOutOfRangeException("index");
        }
        if (count < 0)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (count > buffer.Length - index)
        {
            throw new ArgumentOutOfRangeException("count");
        }
        if (_leftOverBytesCount > 0)
        {
            int leftOverBytesCount = _leftOverBytesCount;
            while (leftOverBytesCount < 3 && count > 0)
            {
                _leftOverBytes[leftOverBytesCount++] = buffer[index++];
                count--;
            }
            if (count == 0 && leftOverBytesCount < 3)
            {
                _leftOverBytesCount = leftOverBytesCount;
                return;
            }
            int count2 = Convert.ToBase64CharArray(_leftOverBytes, 0, 3, _charsLine, 0);
            WriteChars(_charsLine, 0, count2);
        }
        _leftOverBytesCount = count % 3;
        if (_leftOverBytesCount > 0)
        {
            count -= _leftOverBytesCount;
            if (_leftOverBytes == null)
            {
                _leftOverBytes = new byte[3];
            }
            for (int i = 0; i < _leftOverBytesCount; i++)
            {
                _leftOverBytes[i] = buffer[index + count + i];
            }
        }
        int num = index + count;
        int num2 = 768;
        while (index < num)
        {
            if (index + num2 > num)
            {
                num2 = num - index;
            }
            int count3 = Convert.ToBase64CharArray(buffer, index, num2, _charsLine, 0);
            WriteChars(_charsLine, 0, count3);
            index += num2;
        }
    }
References System.Xml.Base64Encoder._charsLine, System.Xml.Base64Encoder._leftOverBytes, System.Xml.Base64Encoder._leftOverBytesCount, System.buffer, System.count, System.Xml.Dictionary, System.index, System.Convert.ToBase64CharArray(), and System.Xml.Base64Encoder.WriteChars().
Referenced by System.Xml.XmlRawWriter.WriteBase64().