Terraria: System.Xml.Serialization.XmlSerializer.FromMappings
FromMappings() [1/2]
static XmlSerializer[] System.Xml.Serialization.XmlSerializer.FromMappings (XmlMapping?[] mappings) inline static
Definition at line 589 of file XmlSerializer.cs.
    {
        return FromMappings(mappings, null);
    }
References System.Xml.Serialization.XmlSerializer.FromMappings().
Referenced by System.Xml.Serialization.XmlSerializer.FromMappings(), and System.Xml.Serialization.XmlSerializer.FromTypes().