Terraria: System.Xml.Base64Encoder.FlushAsync
FlushAsync()
async Task System.Xml.Base64Encoder.FlushAsync () inline package inherited
Definition at line 154 of file Base64Encoder.cs.
    {
        if (_leftOverBytesCount > 0)
        {
            int count = Convert.ToBase64CharArray(_leftOverBytes, 0, _leftOverBytesCount, _charsLine, 0);
            await WriteCharsAsync(_charsLine, 0, count).ConfigureAwait(continueOnCapturedContext: false);
            _leftOverBytesCount = 0;
        }
    }
References System.Xml.Base64Encoder._charsLine, System.Xml.Base64Encoder._leftOverBytes, System.Xml.Base64Encoder._leftOverBytesCount, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.Xml.Dictionary, System.Convert.ToBase64CharArray(), and System.Xml.Base64Encoder.WriteCharsAsync().
Referenced by System.Xml.XmlRawWriter.WriteEndBase64Async().