Terraria: System.Diagnostics.FileVersionInfo.FileVersionInfo
FileVersionInfo()
unsafe System.Diagnostics.FileVersionInfo.FileVersionInfo (string fileName) inline private
Definition at line 152 of file FileVersionInfo.cs.
    {
        _fileName = fileName;
        uint lpdwHandle;
        uint fileVersionInfoSizeEx = global::Interop.Version.GetFileVersionInfoSizeEx(1u, _fileName, out lpdwHandle);
        if (fileVersionInfoSizeEx == 0)
        {
            return;
        }
        byte[] array = new byte[fileVersionInfoSizeEx];
        fixed (byte* value = &array[0])
        {
            IntPtr intPtr = new IntPtr(value);
            if (!global::Interop.Version.GetFileVersionInfoEx(3u, _fileName, 0u, fileVersionInfoSizeEx, intPtr))
            {
                return;
            }
            uint varEntry = GetVarEntry(intPtr);
            if (GetVersionInfoForCodePage(intPtr, ConvertTo8DigitHex(varEntry)))
            {
                return;
            }
            uint[] array2 = s_fallbackLanguageCodePages;
            foreach (uint num in array2)
            {
                if (num != varEntry && GetVersionInfoForCodePage(intPtr, ConvertTo8DigitHex(num)))
                {
                    break;
                }
            }
        }
    }
References System.Diagnostics.FileVersionInfo._fileName, System.array, System.Diagnostics.FileVersionInfo.ConvertTo8DigitHex(), System.Diagnostics.FileVersionInfo.GetVarEntry(), System.Diagnostics.FileVersionInfo.GetVersionInfoForCodePage(), System.Diagnostics.FileVersionInfo.s_fallbackLanguageCodePages, and System.value.
Referenced by System.Diagnostics.FileVersionInfo.GetVersionInfo().