Terraria: System.Diagnostics.FileVersionInfo.GetVersionInfo
GetVersionInfo()
static FileVersionInfo System.Diagnostics.FileVersionInfo.GetVersionInfo (string fileName) inline static
Definition at line 120 of file FileVersionInfo.cs.
    {
        if (!Path.IsPathFullyQualified(fileName))
        {
            fileName = Path.GetFullPath(fileName);
        }
        if (!File.Exists(fileName))
        {
            throw new FileNotFoundException(fileName);
        }
        return new FileVersionInfo(fileName);
    }
References System.Diagnostics.FileVersionInfo.FileVersionInfo(), System.IO.File.Exists(), System.IO.Path.GetFullPath(), and System.IO.Path.IsPathFullyQualified().