Terraria: System.Xml.Serialization.XmlSerializer.SerializePrimitive
SerializePrimitive()
void System.Xml.Serialization.XmlSerializer.SerializePrimitive (XmlWriter xmlWriter, object o, XmlSerializerNamespaces namespaces) inline private
Definition at line 829 of file XmlSerializer.cs.
    {
        XmlSerializationPrimitiveWriter xmlSerializationPrimitiveWriter = new XmlSerializationPrimitiveWriter();
        xmlSerializationPrimitiveWriter.Init(xmlWriter, namespaces, null, null, null);
        switch (Type.GetTypeCode(_primitiveType))
        {
        case TypeCode.String:
            xmlSerializationPrimitiveWriter.Write_string(o);
            return;
        case TypeCode.Int32:
            xmlSerializationPrimitiveWriter.Write_int(o);
            return;
        case TypeCode.Boolean:
            xmlSerializationPrimitiveWriter.Write_boolean(o);
            return;
        case TypeCode.Int16:
            xmlSerializationPrimitiveWriter.Write_short(o);
            return;
        case TypeCode.Int64:
            xmlSerializationPrimitiveWriter.Write_long(o);
            return;
        case TypeCode.Single:
            xmlSerializationPrimitiveWriter.Write_float(o);
            return;
        case TypeCode.Double:
            xmlSerializationPrimitiveWriter.Write_double(o);
            return;
        case TypeCode.Decimal:
            xmlSerializationPrimitiveWriter.Write_decimal(o);
            return;
        case TypeCode.DateTime:
            xmlSerializationPrimitiveWriter.Write_dateTime(o);
            return;
        case TypeCode.Char:
            xmlSerializationPrimitiveWriter.Write_char(o);
            return;
        case TypeCode.Byte:
            xmlSerializationPrimitiveWriter.Write_unsignedByte(o);
            return;
        case TypeCode.SByte:
            xmlSerializationPrimitiveWriter.Write_byte(o);
            return;
        case TypeCode.UInt16:
            xmlSerializationPrimitiveWriter.Write_unsignedShort(o);
            return;
        case TypeCode.UInt32:
            xmlSerializationPrimitiveWriter.Write_unsignedInt(o);
            return;
        case TypeCode.UInt64:
            xmlSerializationPrimitiveWriter.Write_unsignedLong(o);
            return;
        }
        if (_primitiveType == typeof(XmlQualifiedName))
        {
            xmlSerializationPrimitiveWriter.Write_QName(o);
            return;
        }
        if (_primitiveType == typeof(byte[]))
        {
            xmlSerializationPrimitiveWriter.Write_base64Binary(o);
            return;
        }
        if (_primitiveType == typeof(Guid))
        {
            xmlSerializationPrimitiveWriter.Write_guid(o);
            return;
        }
        if (_primitiveType == typeof(TimeSpan))
        {
            xmlSerializationPrimitiveWriter.Write_TimeSpan(o);
            return;
        }
        if (_primitiveType == typeof(DateTimeOffset))
        {
            xmlSerializationPrimitiveWriter.Write_dateTimeOffset(o);
            return;
        }
        throw new InvalidOperationException(System.SR.Format(System.SR.XmlUnxpectedType, _primitiveType.FullName));
    }
References System.Xml.Serialization.XmlSerializer._primitiveType, System.Xml.Dictionary, System.SR.Format(), System.Type.FullName, System.Type.GetTypeCode(), and System.SR.XmlUnxpectedType.
Referenced by System.Xml.Serialization.XmlSerializer.Serialize().