Terraria: System.Xml.Serialization.XmlSerializer.GenerateSerializer
GenerateSerializer()
static bool System.Xml.Serialization.XmlSerializer.GenerateSerializer (Type[] types, XmlMapping[] mappings, Stream stream) inline static package
Definition at line 665 of file XmlSerializer.cs.
    {
        if (types == null || types.Length == 0)
        {
            return false;
        }
        if (mappings == null)
        {
            throw new ArgumentNullException("mappings");
        }
        if (stream == null)
        {
            throw new ArgumentNullException("stream");
        }
        if (XmlMapping.IsShallow(mappings))
        {
            throw new InvalidOperationException(System.SR.XmlMelformMapping);
        }
        Assembly assembly = null;
        foreach (Type type in types)
        {
            if (DynamicAssemblies.IsTypeDynamic(type))
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.XmlPregenTypeDynamic, type.FullName));
            }
            if (assembly == null)
            {
                assembly = type.Assembly;
            }
            else if (type.Assembly != assembly)
            {
                string text = assembly.Location;
                if (text == string.Empty)
                {
                    text = assembly.FullName;
                }
                throw new ArgumentException(System.SR.Format(System.SR.XmlPregenOrphanType, type.FullName, text), "types");
            }
        }
        return TempAssembly.GenerateSerializerToStream(mappings, types, null, assembly, new Hashtable(), stream);
    }
References System.Xml.ArgumentException, System.SR.Format(), System.Xml.Serialization.TempAssembly.GenerateSerializerToStream(), System.Xml.Serialization.XmlMapping.IsShallow(), System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), System.stream, System.text, System.type, System.SR.XmlMelformMapping, System.SR.XmlPregenOrphanType, and System.SR.XmlPregenTypeDynamic.