Terraria: System.Diagnostics.FileVersionInfo.GetVersionInfoForCodePage
GetVersionInfoForCodePage()
bool System.Diagnostics.FileVersionInfo.GetVersionInfoForCodePage (IntPtr memIntPtr, string codepage) inline private
Definition at line 228 of file FileVersionInfo.cs.
    {
        Span<char> span = stackalloc char[256];
        IFormatProvider formatProvider = null;
        IFormatProvider provider = formatProvider;
        Span<char> span2 = span;
        Span<char> initialBuffer = span2;
        DefaultInterpolatedStringHandler handler = new DefaultInterpolatedStringHandler(31, 1, formatProvider, span2);
        handler.AppendLiteral("\\\\StringFileInfo\\\\");
        handler.AppendFormatted(codepage);
        handler.AppendLiteral("\\\\CompanyName");
        _companyName = GetFileVersionString(memIntPtr, string.Create(provider, initialBuffer, ref handler));
        formatProvider = null;
        IFormatProvider provider2 = formatProvider;
        span2 = span;
        Span<char> initialBuffer2 = span2;
        DefaultInterpolatedStringHandler handler2 = new DefaultInterpolatedStringHandler(35, 1, formatProvider, span2);
        handler2.AppendLiteral("\\\\StringFileInfo\\\\");
        handler2.AppendFormatted(codepage);
        handler2.AppendLiteral("\\\\FileDescription");
        _fileDescription = GetFileVersionString(memIntPtr, string.Create(provider2, initialBuffer2, ref handler2));
        formatProvider = null;
        IFormatProvider provider3 = formatProvider;
        span2 = span;
        Span<char> initialBuffer3 = span2;
        DefaultInterpolatedStringHandler handler3 = new DefaultInterpolatedStringHandler(31, 1, formatProvider, span2);
        handler3.AppendLiteral("\\\\StringFileInfo\\\\");
        handler3.AppendFormatted(codepage);
        handler3.AppendLiteral("\\\\FileVersion");
        _fileVersion = GetFileVersionString(memIntPtr, string.Create(provider3, initialBuffer3, ref handler3));
        formatProvider = null;
        IFormatProvider provider4 = formatProvider;
        span2 = span;
        Span<char> initialBuffer4 = span2;
        DefaultInterpolatedStringHandler handler4 = new DefaultInterpolatedStringHandler(32, 1, formatProvider, span2);
        handler4.AppendLiteral("\\\\StringFileInfo\\\\");
        handler4.AppendFormatted(codepage);
        handler4.AppendLiteral("\\\\InternalName");
        _internalName = GetFileVersionString(memIntPtr, string.Create(provider4, initialBuffer4, ref handler4));
        formatProvider = null;
        IFormatProvider provider5 = formatProvider;
        span2 = span;
        Span<char> initialBuffer5 = span2;
        DefaultInterpolatedStringHandler handler5 = new DefaultInterpolatedStringHandler(34, 1, formatProvider, span2);
        handler5.AppendLiteral("\\\\StringFileInfo\\\\");
        handler5.AppendFormatted(codepage);
        handler5.AppendLiteral("\\\\LegalCopyright");
        _legalCopyright = GetFileVersionString(memIntPtr, string.Create(provider5, initialBuffer5, ref handler5));
        formatProvider = null;
        IFormatProvider provider6 = formatProvider;
        span2 = span;
        Span<char> initialBuffer6 = span2;
        DefaultInterpolatedStringHandler handler6 = new DefaultInterpolatedStringHandler(36, 1, formatProvider, span2);
        handler6.AppendLiteral("\\\\StringFileInfo\\\\");
        handler6.AppendFormatted(codepage);
        handler6.AppendLiteral("\\\\OriginalFilename");
        _originalFilename = GetFileVersionString(memIntPtr, string.Create(provider6, initialBuffer6, ref handler6));
        formatProvider = null;
        IFormatProvider provider7 = formatProvider;
        span2 = span;
        Span<char> initialBuffer7 = span2;
        DefaultInterpolatedStringHandler handler7 = new DefaultInterpolatedStringHandler(31, 1, formatProvider, span2);
        handler7.AppendLiteral("\\\\StringFileInfo\\\\");
        handler7.AppendFormatted(codepage);
        handler7.AppendLiteral("\\\\ProductName");
        _productName = GetFileVersionString(memIntPtr, string.Create(provider7, initialBuffer7, ref handler7));
        formatProvider = null;
        IFormatProvider provider8 = formatProvider;
        span2 = span;
        Span<char> initialBuffer8 = span2;
        DefaultInterpolatedStringHandler handler8 = new DefaultInterpolatedStringHandler(34, 1, formatProvider, span2);
        handler8.AppendLiteral("\\\\StringFileInfo\\\\");
        handler8.AppendFormatted(codepage);
        handler8.AppendLiteral("\\\\ProductVersion");
        _productVersion = GetFileVersionString(memIntPtr, string.Create(provider8, initialBuffer8, ref handler8));
        formatProvider = null;
        IFormatProvider provider9 = formatProvider;
        span2 = span;
        Span<char> initialBuffer9 = span2;
        DefaultInterpolatedStringHandler handler9 = new DefaultInterpolatedStringHandler(28, 1, formatProvider, span2);
        handler9.AppendLiteral("\\\\StringFileInfo\\\\");
        handler9.AppendFormatted(codepage);
        handler9.AppendLiteral("\\\\Comments");
        _comments = GetFileVersionString(memIntPtr, string.Create(provider9, initialBuffer9, ref handler9));
        formatProvider = null;
        IFormatProvider provider10 = formatProvider;
        span2 = span;
        Span<char> initialBuffer10 = span2;
        DefaultInterpolatedStringHandler handler10 = new DefaultInterpolatedStringHandler(35, 1, formatProvider, span2);
        handler10.AppendLiteral("\\\\StringFileInfo\\\\");
        handler10.AppendFormatted(codepage);
        handler10.AppendLiteral("\\\\LegalTrademarks");
        _legalTrademarks = GetFileVersionString(memIntPtr, string.Create(provider10, initialBuffer10, ref handler10));
        formatProvider = null;
        IFormatProvider provider11 = formatProvider;
        span2 = span;
        Span<char> initialBuffer11 = span2;
        DefaultInterpolatedStringHandler handler11 = new DefaultInterpolatedStringHandler(32, 1, formatProvider, span2);
        handler11.AppendLiteral("\\\\StringFileInfo\\\\");
        handler11.AppendFormatted(codepage);
        handler11.AppendLiteral("\\\\PrivateBuild");
        _privateBuild = GetFileVersionString(memIntPtr, string.Create(provider11, initialBuffer11, ref handler11));
        formatProvider = null;
        IFormatProvider provider12 = formatProvider;
        span2 = span;
        Span<char> initialBuffer12 = span2;
        DefaultInterpolatedStringHandler handler12 = new DefaultInterpolatedStringHandler(32, 1, formatProvider, span2);
        handler12.AppendLiteral("\\\\StringFileInfo\\\\");
        handler12.AppendFormatted(codepage);
        handler12.AppendLiteral("\\\\SpecialBuild");
        _specialBuild = GetFileVersionString(memIntPtr, string.Create(provider12, initialBuffer12, ref handler12));
        _language = GetFileVersionLanguage(memIntPtr);
        global::Interop.Version.VS_FIXEDFILEINFO fixedFileInfo = GetFixedFileInfo(memIntPtr);
        _fileMajor = (int)HIWORD(fixedFileInfo.dwFileVersionMS);
        _fileMinor = (int)LOWORD(fixedFileInfo.dwFileVersionMS);
        _fileBuild = (int)HIWORD(fixedFileInfo.dwFileVersionLS);
        _filePrivate = (int)LOWORD(fixedFileInfo.dwFileVersionLS);
        _productMajor = (int)HIWORD(fixedFileInfo.dwProductVersionMS);
        _productMinor = (int)LOWORD(fixedFileInfo.dwProductVersionMS);
        _productBuild = (int)HIWORD(fixedFileInfo.dwProductVersionLS);
        _productPrivate = (int)LOWORD(fixedFileInfo.dwProductVersionLS);
        _isDebug = (fixedFileInfo.dwFileFlags & 1) != 0;
        _isPatched = (fixedFileInfo.dwFileFlags & 4) != 0;
        _isPrivateBuild = (fixedFileInfo.dwFileFlags & 8) != 0;
        _isPreRelease = (fixedFileInfo.dwFileFlags & 2) != 0;
        _isSpecialBuild = (fixedFileInfo.dwFileFlags & 0x20) != 0;
        return _fileVersion != string.Empty;
    }
References System.Diagnostics.FileVersionInfo._comments, System.Diagnostics.FileVersionInfo._companyName, System.Diagnostics.FileVersionInfo._fileBuild, System.Diagnostics.FileVersionInfo._fileDescription, System.Diagnostics.FileVersionInfo._fileMajor, System.Diagnostics.FileVersionInfo._fileMinor, System.Diagnostics.FileVersionInfo._filePrivate, System.Diagnostics.FileVersionInfo._fileVersion, System.Diagnostics.FileVersionInfo._internalName, System.Diagnostics.FileVersionInfo._isDebug, System.Diagnostics.FileVersionInfo._isPatched, System.Diagnostics.FileVersionInfo._isPreRelease, System.Diagnostics.FileVersionInfo._isPrivateBuild, System.Diagnostics.FileVersionInfo._isSpecialBuild, System.Diagnostics.FileVersionInfo._language, System.Diagnostics.FileVersionInfo._legalCopyright, System.Diagnostics.FileVersionInfo._legalTrademarks, System.Diagnostics.FileVersionInfo._originalFilename, System.Diagnostics.FileVersionInfo._privateBuild, System.Diagnostics.FileVersionInfo._productBuild, System.Diagnostics.FileVersionInfo._productMajor, System.Diagnostics.FileVersionInfo._productMinor, System.Diagnostics.FileVersionInfo._productName, System.Diagnostics.FileVersionInfo._productPrivate, System.Diagnostics.FileVersionInfo._productVersion, System.Diagnostics.FileVersionInfo._specialBuild, System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(), System.IO.Create, System.Diagnostics.FileVersionInfo.GetFileVersionLanguage(), System.Diagnostics.FileVersionInfo.GetFileVersionString(), System.Diagnostics.FileVersionInfo.GetFixedFileInfo(), System.Diagnostics.FileVersionInfo.HIWORD(), and System.Diagnostics.FileVersionInfo.LOWORD().
Referenced by System.Diagnostics.FileVersionInfo.FileVersionInfo().