Terraria: System.Xml.Serialization.XmlSerializer.FromMappings
FromMappings() [2/2]
static XmlSerializer[] System.Xml.Serialization.XmlSerializer.FromMappings (XmlMapping?[] mappings, Type? type) inline static
Definition at line 595 of file XmlSerializer.cs.
    {
        if (mappings == null || mappings.Length == 0)
        {
            return Array.Empty<XmlSerializer>();
        }
        bool flag = false;
        foreach (XmlMapping xmlMapping in mappings)
        {
            if (xmlMapping.IsSoap)
            {
                flag = true;
            }
        }
        if ((flag && ReflectionMethodEnabled) || Mode == SerializationMode.ReflectionOnly)
        {
            return GetReflectionBasedSerializers(mappings, type);
        }
        XmlSerializerImplementation contract = null;
        Assembly assembly = ((type == null) ? null : TempAssembly.LoadGeneratedAssembly(type, null, out contract));
        TempAssembly tempAssembly = null;
        if (assembly == null)
        {
            if (Mode == SerializationMode.PreGenOnly)
            {
                AssemblyName name = type.Assembly.GetName();
                string tempAssemblyName = Compiler.GetTempAssemblyName(name, null);
                throw new FileLoadException(System.SR.Format(System.SR.FailLoadAssemblyUnderPregenMode, tempAssemblyName));
            }
            if (XmlMapping.IsShallow(mappings))
            {
                return Array.Empty<XmlSerializer>();
            }
            if (type == null)
            {
                tempAssembly = new TempAssembly(mappings, new Type[1] { type }, null, null);
                XmlSerializer[] array = new XmlSerializer[mappings.Length];
                contract = tempAssembly.Contract;
                for (int j = 0; j < array.Length; j++)
                {
                    array[j] = (XmlSerializer)contract.TypedSerializers[mappings[j].Key];
                    array[j].SetTempAssembly(tempAssembly, mappings[j]);
                }
                return array;
            }
            return GetSerializersFromCache(mappings, type);
        }
        XmlSerializer[] array2 = new XmlSerializer[mappings.Length];
        for (int k = 0; k < array2.Length; k++)
        {
            array2[k] = (XmlSerializer)contract.TypedSerializers[mappings[k].Key];
        }
        return array2;
    }
References System.Xml.Serialization.XmlSerializer.XmlSerializer(), System.array, System.Xml.Dictionary, System.SR.FailLoadAssemblyUnderPregenMode, System.SR.Format(), System.Xml.Serialization.XmlSerializer.GetReflectionBasedSerializers(), System.Xml.Serialization.XmlSerializer.GetSerializersFromCache(), System.Xml.Serialization.Compiler.GetTempAssemblyName(), System.Xml.Serialization.XmlMapping.IsShallow(), System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(), System.Xml.Serialization.XmlSerializer.ReflectionMethodEnabled, and System.type.