Terraria: System.Xml.Serialization.XmlSerializer.XmlSerializer
XmlSerializer() [8/9]
System.Xml.Serialization.XmlSerializer.XmlSerializer (Type type, string? defaultNamespace) inline
Definition at line 245 of file XmlSerializer.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        DefaultNamespace = defaultNamespace;
        _rootType = type;
        _mapping = GetKnownMapping(type, defaultNamespace);
        if (_mapping != null)
        {
            _primitiveType = type;
        }
        else
        {
            if (Mode == SerializationMode.ReflectionOnly)
            {
                return;
            }
            _tempAssembly = s_cache[defaultNamespace, type];
            if (_tempAssembly == null)
            {
                lock (s_cache)
                {
                    _tempAssembly = s_cache[defaultNamespace, type];
                    if (_tempAssembly == null)
                    {
                        XmlSerializerImplementation contract = null;
                        Assembly assembly = TempAssembly.LoadGeneratedAssembly(type, defaultNamespace, out contract);
                        if (assembly == null)
{
                            if (Mode == SerializationMode.PreGenOnly)
{
                                AssemblyName name = type.Assembly.GetName();
                                string tempAssemblyName = Compiler.GetTempAssemblyName(name, defaultNamespace);
                                throw new FileLoadException(System.SR.Format(System.SR.FailLoadAssemblyUnderPregenMode, tempAssemblyName));
                            }
                            XmlReflectionImporter xmlReflectionImporter = new XmlReflectionImporter(defaultNamespace);
                            _mapping = xmlReflectionImporter.ImportTypeMapping(type, null, defaultNamespace);
                            _tempAssembly = GenerateTempAssembly(_mapping, type, defaultNamespace);
                        }
                        else
{
                            _mapping = XmlReflectionImporter.GetTopLevelMapping(type, defaultNamespace);
                            _tempAssembly = new TempAssembly(new XmlMapping[1] { _mapping }, assembly, contract);
                        }
                    }
                    s_cache.Add(defaultNamespace, type, _tempAssembly);
                }
            }
            if (_mapping == null)
            {
                _mapping = XmlReflectionImporter.GetTopLevelMapping(type, defaultNamespace);
            }
        }
    }
References System.Xml.Serialization.XmlSerializer._mapping, System.Xml.Serialization.XmlSerializer._primitiveType, System.Xml.Serialization.XmlSerializer._rootType, System.Xml.Serialization.XmlSerializer._tempAssembly, System.Xml.Serialization.XmlSerializer.DefaultNamespace, System.Xml.Dictionary, System.SR.FailLoadAssemblyUnderPregenMode, System.SR.Format(), System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(), System.Xml.Serialization.XmlSerializer.GetKnownMapping(), System.Xml.Serialization.Compiler.GetTempAssemblyName(), System.Xml.Serialization.XmlReflectionImporter.GetTopLevelMapping(), System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(), System.Xml.Serialization.XmlSerializer.s_cache, and System.type.