Terraria: System.Xml.Serialization.XmlSerializer.Serialize
Serialize() [9/9]
void System.Xml.Serialization.XmlSerializer.Serialize (XmlWriter xmlWriter, object? o, XmlSerializerNamespaces? namespaces, string? encodingStyle, string? id) inline
Definition at line 404 of file XmlSerializer.cs.
    {
        try
        {
            if (_primitiveType != null)
            {
                if (encodingStyle != null && encodingStyle.Length > 0)
                {
                    throw new InvalidOperationException(System.SR.Format(System.SR.XmlInvalidEncodingNotEncoded1, encodingStyle));
                }
                SerializePrimitive(xmlWriter, o, namespaces);
            }
            else if (ShouldUseReflectionBasedSerialization(_mapping) || _isReflectionBasedSerializer)
            {
                SerializeUsingReflection(xmlWriter, o, namespaces, encodingStyle, id);
            }
            else if (_tempAssembly == null || _typedSerializer)
            {
                XmlSerializationWriter xmlSerializationWriter = CreateWriter();
                xmlSerializationWriter.Init(xmlWriter, (namespaces == null || namespaces.Count == 0) ? DefaultNamespaces : namespaces, encodingStyle, id, _tempAssembly);
                try
                {
                    Serialize(o, xmlSerializationWriter);
                }
                finally
                {
                    xmlSerializationWriter.Dispose();
                }
            }
            else
            {
                _tempAssembly.InvokeWriter(_mapping, xmlWriter, o, (namespaces == null || namespaces.Count == 0) ? DefaultNamespaces : namespaces, encodingStyle, id);
            }
        }
        catch (Exception innerException)
        {
            if (innerException is TargetInvocationException)
            {
                innerException = innerException.InnerException;
            }
            throw new InvalidOperationException(System.SR.XmlGenError, innerException);
        }
        xmlWriter.Flush();
    }
References System.Xml.Serialization.XmlSerializer._isReflectionBasedSerializer, System.Xml.Serialization.XmlSerializer._mapping, System.Xml.Serialization.XmlSerializer._primitiveType, System.Xml.Serialization.XmlSerializer._tempAssembly, System.Xml.Serialization.XmlSerializer._typedSerializer, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Serialization.XmlSerializer.CreateWriter(), System.Xml.Serialization.XmlSerializer.DefaultNamespaces, System.Xml.Dictionary, System.SR.Format(), System.Xml.Serialization.TempAssembly.InvokeWriter(), System.Xml.Serialization.XmlSerializer.Serialize(), System.Xml.Serialization.XmlSerializer.SerializePrimitive(), System.Xml.Serialization.XmlSerializer.SerializeUsingReflection(), System.Xml.Serialization.XmlSerializer.ShouldUseReflectionBasedSerialization(), System.SR.XmlGenError, and System.SR.XmlInvalidEncodingNotEncoded1.