Terraria: Terraria.Program.DisplayException
DisplayException()
static void Terraria.Program.DisplayException (Exception e) inline static private
Definition at line 247 of file Program.cs.
    {
        try
        {
            string text = e.ToString();
            if (WorldGen.gen)
            {
                try
                {
                    text = $"Creating world - Seed: {Main.ActiveWorldFileData.Seed} Width: {Main.maxTilesX}, Height: {Main.maxTilesY}, Evil: {WorldGen.WorldGenParam_Evil}, IsExpert: {Main.expertMode}\n{text}";
                }
                catch
                {
                }
            }
            using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", append: true))
            {
                streamWriter.WriteLine(DateTime.Now);
                streamWriter.WriteLine(text);
                streamWriter.WriteLine("");
            }
            if (Main.dedServ)
            {
                Console.WriteLine(Language.GetTextValue("Error.ServerCrash"), DateTime.Now, text);
            }
            MessageBox.Show(text, "Terraria: Error");
        }
        catch
        {
        }
    }
References Terraria.Main.dedServ, Terraria.WorldGen.gen, Terraria.Localization.Language.GetTextValue(), System.DateTime.Now, System.text, System.Exception.ToString(), and System.Console.WriteLine().
Referenced by Terraria.Program.RunGame().