Terraria: Terraria.Program.SetupLogging
SetupLogging()
static void Terraria.Program.SetupLogging () inline static private
Definition at line 140 of file Program.cs.
    {
        if (LaunchParameters.ContainsKey("-logfile"))
        {
            string text = LaunchParameters["-logfile"];
            text = ((text != null && !(text.Trim() == "")) ? Path.Combine(text, $"Log_{DateTime.Now:yyyyMMddHHmmssfff}.log") : Path.Combine(SavePath, "Logs", $"Log_{DateTime.Now:yyyyMMddHHmmssfff}.log"));
            ConsoleOutputMirror.ToFile(text);
        }
        CrashWatcher.Inititialize();
        CrashWatcher.DumpOnException = LaunchParameters.ContainsKey("-minidump");
        CrashWatcher.LogAllExceptions = LaunchParameters.ContainsKey("-logerrors");
        if (LaunchParameters.ContainsKey("-fulldump"))
        {
            Console.WriteLine("Full Dump logs enabled.");
            CrashWatcher.EnableCrashDumps(CrashDump.Options.WithFullMemory);
        }
    }
References Terraria.Utilities.CrashWatcher.EnableCrashDumps(), Terraria.Utilities.CrashWatcher.Inititialize(), Terraria.Program.LaunchParameters, Terraria.Program.SavePath, and ReLogic.IO.ConsoleOutputMirror.ToFile().
Referenced by Terraria.Program.LaunchGame().