Terraria: System.Collections.DictionaryBase.Remove
Remove()
void IDictionary. System.Collections.DictionaryBase.Remove (object key) inline private
Implements System.Collections.IDictionary.
Definition at line 116 of file DictionaryBase.cs.
    {
        if (InnerHashtable.Contains(key))
        {
            object value = InnerHashtable[key];
            OnValidate(key, value);
            OnRemove(key, value);
            InnerHashtable.Remove(key);
            try
            {
                OnRemoveComplete(key, value);
            }
            catch
            {
                InnerHashtable.Add(key, value);
                throw;
            }
        }
    }
References System.Collections.Hashtable.Add(), System.Collections.Hashtable.Contains(), System.Collections.DictionaryBase.InnerHashtable, System.key, System.Collections.DictionaryBase.OnRemove(), System.Collections.DictionaryBase.OnRemoveComplete(), System.Collections.DictionaryBase.OnValidate(), System.Collections.Hashtable.Remove(), and System.value.