Terraria: Terraria.GameContent.NetModules.NetLiquidModule.Serialize
Serialize()
static NetPacket Terraria.GameContent.NetModules.NetLiquidModule.Serialize (HashSet< int > changes) inline static
Definition at line 35 of file NetLiquidModule.cs.
    {
        NetPacket result = NetModule.CreatePacket<NetLiquidModule>(changes.Count * 6 + 2);
        result.Writer.Write((ushort)changes.Count);
        foreach (int change in changes)
        {
            int num = (change >> 16) & 0xFFFF;
            int num2 = change & 0xFFFF;
            result.Writer.Write(change);
            result.Writer.Write(Main.tile[num, num2].liquid);
            result.Writer.Write(Main.tile[num, num2].liquidType());
        }
        return result;
    }
References Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.tile, and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.NetModules.NetLiquidModule.BroadcastAllChanges(), and Terraria.GameContent.NetModules.NetLiquidModule.BroadcastEachChunkSeparately().