Terraria: System.Globalization.UmAlQuraCalendar.ConvertGregorianToHijri
ConvertGregorianToHijri()
static void System.Globalization.UmAlQuraCalendar.ConvertGregorianToHijri (DateTime time, out int HijriYear, out int HijriMonth, out int HijriDay) inline static private
Definition at line 202 of file UmAlQuraCalendar.cs.
    {
        int num = (int)((time.Ticks - s_minDate.Ticks) / 864000000000L) / 355;
        while (time.CompareTo(s_hijriYearInfo[++num].GregorianDate) > 0)
        {
        }
        if (time.CompareTo(s_hijriYearInfo[num].GregorianDate) != 0)
        {
            num--;
        }
        TimeSpan timeSpan = time.Subtract(s_hijriYearInfo[num].GregorianDate);
        int num2 = num + 1318;
        int num3 = 1;
        int num4 = 1;
        double num5 = timeSpan.TotalDays;
        int num6 = s_hijriYearInfo[num].HijriMonthsLengthFlags;
        int num7 = 29 + (num6 & 1);
        while (num5 >= (double)num7)
        {
            num5 -= (double)num7;
            num6 >>= 1;
            num7 = 29 + (num6 & 1);
            num3++;
        }
        num4 += (int)num5;
        HijriDay = num4;
        HijriMonth = num3;
        HijriYear = num2;
    }
References System.DateTime.CompareTo(), System.L, System.Globalization.UmAlQuraCalendar.s_hijriYearInfo, System.Globalization.UmAlQuraCalendar.s_minDate, System.DateTime.Subtract(), System.DateTime.Ticks, and System.TimeSpan.TotalDays.
Referenced by System.Globalization.UmAlQuraCalendar.GetDatePart().