Terraria: System.Globalization.UmAlQuraCalendar.ConvertHijriToGregorian
ConvertHijriToGregorian()
static void System.Globalization.UmAlQuraCalendar.ConvertHijriToGregorian (int HijriYear, int HijriMonth, int HijriDay, out int yg, out int mg, out int dg) inline static private
Definition at line 148 of file UmAlQuraCalendar.cs.
    {
        int num = HijriDay - 1;
        int num2 = HijriYear - 1318;
        DateTime gregorianDate = s_hijriYearInfo[num2].GregorianDate;
        int num3 = s_hijriYearInfo[num2].HijriMonthsLengthFlags;
        for (int i = 1; i < HijriMonth; i++)
        {
            num = num + 29 + (num3 & 1);
            num3 >>= 1;
        }
        gregorianDate.AddDays(num).GetDate(out yg, out mg, out dg);
    }
References System.DateTime.AddDays(), System.DateTime.GetDate(), and System.Globalization.UmAlQuraCalendar.s_hijriYearInfo.
Referenced by System.Globalization.UmAlQuraCalendar.GetAbsoluteDateUmAlQura().