Terraria: System.Globalization.UmAlQuraCalendar.CheckYearMonthRange
CheckYearMonthRange()
static void System.Globalization.UmAlQuraCalendar.CheckYearMonthRange (int year, int month, int era) inline static package
Definition at line 193 of file UmAlQuraCalendar.cs.
    {
        CheckYearRange(year, era);
        if (month < 1 || month > 12)
        {
            ThrowHelper.ThrowArgumentOutOfRange_Month(month);
        }
    }
References System.Globalization.UmAlQuraCalendar.CheckYearRange(), System.ThrowHelper.ThrowArgumentOutOfRange_Month(), and System.year.
Referenced by System.Globalization.UmAlQuraCalendar.GetDaysInMonth(), System.Globalization.UmAlQuraCalendar.IsLeapDay(), System.Globalization.UmAlQuraCalendar.IsLeapMonth(), and System.Globalization.UmAlQuraCalendar.ToDateTime().