Terraria: System.__DTString.MatchSpecifiedWords
MatchSpecifiedWords()
bool System.__DTString.MatchSpecifiedWords (string target, bool checkWordBoundary, ref int matchLength) inline package
Definition at line 178 of file __DTString.cs.
    {
        int num = Value.Length - Index;
        matchLength = target.Length;
        if (matchLength > num || m_info.Compare(Value.Slice(Index, matchLength), target, CompareOptions.IgnoreCase) != 0)
        {
            int num2 = 0;
            int num3 = Index;
            int num4 = target.IndexOfAny(WhiteSpaceChecks, num2);
            if (num4 == -1)
            {
                return false;
            }
            do
            {
                int num5 = num4 - num2;
                if (num3 >= Value.Length - num5)
                {
                    return false;
                }
                if (num5 == 0)
                {
                    matchLength--;
                }
                else
                {
                    if (!char.IsWhiteSpace(Value[num3 + num5]))
                    {
                        return false;
                    }
                    if (m_info.CompareOptionIgnoreCase(Value.Slice(num3, num5), target.AsSpan(num2, num5)) != 0)
                    {
                        return false;
                    }
                    num3 = num3 + num5 + 1;
                }
                num2 = num4 + 1;
                while (num3 < Value.Length && char.IsWhiteSpace(Value[num3]))
                {
                    num3++;
                    matchLength++;
                }
            }
            while ((num4 = target.IndexOfAny(WhiteSpaceChecks, num2)) >= 0);
            if (num2 < target.Length)
            {
                int num6 = target.Length - num2;
                if (num3 > Value.Length - num6)
                {
                    return false;
                }
                if (m_info.CompareOptionIgnoreCase(Value.Slice(num3, num6), target.AsSpan(num2, num6)) != 0)
                {
                    return false;
                }
            }
        }
        if (checkWordBoundary)
        {
            int num7 = Index + matchLength;
            if (num7 < Value.Length && char.IsLetter(Value[num7]))
            {
                return false;
            }
        }
        return true;
    }
References System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.CompareOptionIgnoreCase(), System.__DTString.Index, System.ReadOnlySpan< T >.Length, System.__DTString.m_info, System.ReadOnlySpan< T >.Slice(), System.__DTString.Value, and System.__DTString.WhiteSpaceChecks.
Referenced by System.__DTString.MatchLongestWords().