Terraria: NoiseHelper.GetDynamicNoise
GetDynamicNoise() [1/3]
static float NoiseHelper.GetDynamicNoise (int index, float currentTime) inline static
     {
         float num = StaticNoise[index & 0x3FF];
         float num2 = currentTime % 1f;
         return Math.Abs(Math.Abs(num - num2) - 0.5f) * 2f;
     }
References StaticNoise.
Referenced by SkyShader.ProcessAnyDetail(), BrainShader.ProcessHighDetail(), CultistShader.ProcessHighDetail(), DukeFishronShader.ProcessHighDetail(), GemCaveShader.ProcessHighDetail(), HallowSurfaceShader.ProcessHighDetail(), IceShader.ProcessHighDetail(), JungleShader.ProcessHighDetail(), LavaIndicatorShader.ProcessHighDetail(), MeteoriteShader.ProcessHighDetail(), MoonShader.ProcessHighDetail(), SurfaceBiomeShader.ProcessHighDetail(), TwinsShader.ProcessHighDetail(), UndergroundCorruptionShader.ProcessHighDetail(), UndergroundHallowShader.ProcessHighDetail(), UnderworldShader.ProcessHighDetail(), WallOfFleshShader.ProcessHighDetail(), JungleShader.ProcessLowDetail(), KingSlimeShader.ProcessLowDetail(), MoonShader.ProcessLowDetail(), QueenSlimeShader.ProcessLowDetail(), and TwinsShader.ProcessLowDetail().