Terraria: System.Linq.ThrowHelper.ThrowNoElementsException
ThrowNoElementsException()
static void System.Linq.ThrowHelper.ThrowNoElementsException () inline static package
Definition at line 32 of file ThrowHelper.cs.
    {
        throw new InvalidOperationException(System.SR.NoElements);
    }
References System.SR.NoElements.
Referenced by System.Linq.Enumerable.Aggregate< TSource >(), System.Linq.Enumerable.Average(), System.Linq.Enumerable.Average(), System.Linq.Enumerable.Average(), System.Linq.Enumerable.Average(), System.Linq.Enumerable.Average(), System.Linq.Enumerable.Average< TSource >(), System.Linq.Enumerable.Average< TSource >(), System.Linq.Enumerable.Average< TSource >(), System.Linq.Enumerable.Average< TSource >(), System.Linq.Enumerable.Average< TSource >(), System.Linq.Enumerable.First< TSource >(), System.Linq.Enumerable.Last< TSource >(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Max(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource >(), System.Linq.Enumerable.Max< TSource, TResult >(), System.Linq.Enumerable.MaxBy< TSource, TKey >(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Min(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource >(), System.Linq.Enumerable.Min< TSource, TResult >(), System.Linq.Enumerable.MinBy< TSource, TKey >(), and System.Linq.Enumerable.Single< TSource >().