Terraria: System.Text.UTF32Encoding.GetByteCount
GetByteCount() [4/7]
unsafe override int System.Text.UTF32Encoding.GetByteCount (char[] chars, int index, int count) inline
Definition at line 98 of file UTF32Encoding.cs.
    {
        if (chars == null)
        {
            throw new ArgumentNullException("chars", SR.ArgumentNull_Array);
        }
        if (index < 0 || count < 0)
        {
            throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", SR.ArgumentOutOfRange_NeedNonNegNum);
        }
        if (chars.Length - index < count)
        {
            throw new ArgumentOutOfRangeException("chars", SR.ArgumentOutOfRange_IndexCountBuffer);
        }
        if (count == 0)
        {
            return 0;
        }
        fixed (char* ptr = chars)
        {
            return GetByteCount(ptr + index, count, null);
        }
    }
References System.SR.ArgumentNull_Array, System.SR.ArgumentOutOfRange_IndexCountBuffer, System.SR.ArgumentOutOfRange_NeedNonNegNum, System.chars, System.count, System.Text.UTF32Encoding.GetByteCount(), and System.index.
Referenced by System.Text.UTF32Encoding.GetByteCount(), System.Text.UTF32Encoding.GetByteCount(), and System.Text.UTF32Encoding.GetByteCount().