Terraria: TileEntity.Read
Read()
static TileEntity TileEntity.Read (BinaryReader reader, bool networkSend = false) inline static
     {
         byte id = reader.ReadByte();
         TileEntity tileEntity = manager.GenerateInstance(id);
         tileEntity.type = id;
         tileEntity.ReadInner(reader, networkSend);
         return tileEntity;
     }
References TileEntitiesManager.GenerateInstance(), manager, ReadInner(), and type.
Referenced by NetMessage.DecompressTileBlock_Inner(), MessageBuffer.GetData(), WorldFile.LoadTileEntities(), and WorldFile.ValidateWorld().