Terraria: TileEntity.SetInteractionAnchor
SetInteractionAnchor()
static void TileEntity.SetInteractionAnchor (Player player, int x, int y, int id) inline static
     {
         player.chest = -1;
         player.SetTalkNPC(-1);
         if (player.whoAmI == Main.myPlayer)
         {
             Main.playerInventory = true;
             Main.recBigList = false;
             Main.CreativeMenu.CloseMenu();
             if (PlayerInput.GrappleAndInteractAreShared)
             {
                 PlayerInput.Triggers.JustPressed.Grapple = false;
             }
             if (player.tileEntityAnchor.interactEntityID != -1)
             {
                 SoundEngine.PlaySound(12);
             }
             else
             {
                 SoundEngine.PlaySound(10);
             }
         }
         player.tileEntityAnchor.Set(id, x, y);
     }
References Player.chest, CreativeUI.CloseMenu(), Main.CreativeMenu, TriggersSet.Grapple, PlayerInput.GrappleAndInteractAreShared, PlayerInteractionAnchor.interactEntityID, TriggersPack.JustPressed, Main.myPlayer, Main.playerInventory, SoundEngine.PlaySound(), Main.recBigList, PlayerInteractionAnchor.Set(), Player.SetTalkNPC(), Player.tileEntityAnchor, PlayerInput.Triggers, and Entity.whoAmI.
Referenced by BasicOpenCloseInteraction(), and MessageBuffer.GetData().