Terraria: System.Reflection.PortableExecutable.PEHeaderBuilder.PEHeaderBuilder
PEHeaderBuilder()
System.Reflection.PortableExecutable.PEHeaderBuilder.PEHeaderBuilder (Machine machine = Machine::Unknown, int sectionAlignment = 8192, int fileAlignment = 512, ulong imageBase = 4194304uL, byte majorLinkerVersion = 48, byte minorLinkerVersion = 0, ushort majorOperatingSystemVersion = 4, ushort minorOperatingSystemVersion = 0, ushort majorImageVersion = 0, ushort minorImageVersion = 0, ushort majorSubsystemVersion = 4, ushort minorSubsystemVersion = 0, Subsystem subsystem = Subsystem::WindowsCui, DllCharacteristics dllCharacteristics = DllCharacteristics::DynamicBase | DllCharacteristics::NxCompatible | DllCharacteristics::NoSeh | DllCharacteristics::TerminalServerAware, Characteristics imageCharacteristics = Characteristics::Dll, ulong sizeOfStackReserve = 1048576uL, ulong sizeOfStackCommit = 4096uL, ulong sizeOfHeapReserve = 1048576uL, ulong sizeOfHeapCommit = 4096uL) inline
Definition at line 57 of file PEHeaderBuilder.cs.
    {
        if (fileAlignment < 512 || fileAlignment > 65536 || BitArithmetic.CountBits(fileAlignment) != 1)
        {
            Throw.ArgumentOutOfRange("fileAlignment");
        }
        if (sectionAlignment < fileAlignment || BitArithmetic.CountBits(sectionAlignment) != 1)
        {
            Throw.ArgumentOutOfRange("sectionAlignment");
        }
        Machine = machine;
        SectionAlignment = sectionAlignment;
        FileAlignment = fileAlignment;
        ImageBase = imageBase;
        MajorLinkerVersion = majorLinkerVersion;
        MinorLinkerVersion = minorLinkerVersion;
        MajorOperatingSystemVersion = majorOperatingSystemVersion;
        MinorOperatingSystemVersion = minorOperatingSystemVersion;
        MajorImageVersion = majorImageVersion;
        MinorImageVersion = minorImageVersion;
        MajorSubsystemVersion = majorSubsystemVersion;
        MinorSubsystemVersion = minorSubsystemVersion;
        Subsystem = subsystem;
        DllCharacteristics = dllCharacteristics;
        ImageCharacteristics = imageCharacteristics;
        SizeOfStackReserve = sizeOfStackReserve;
        SizeOfStackCommit = sizeOfStackCommit;
        SizeOfHeapReserve = sizeOfHeapReserve;
        SizeOfHeapCommit = sizeOfHeapCommit;
    }
References System.Reflection.Throw.ArgumentOutOfRange(), System.Reflection.Internal.BitArithmetic.CountBits(), System.Reflection.PortableExecutable.PEHeaderBuilder.FileAlignment, System.Reflection.PortableExecutable.PEHeaderBuilder.ImageBase, System.Reflection.PortableExecutable.PEHeaderBuilder.ImageCharacteristics, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorImageVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorLinkerVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorOperatingSystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MajorSubsystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorImageVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorLinkerVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorOperatingSystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.MinorSubsystemVersion, System.Reflection.PortableExecutable.PEHeaderBuilder.SectionAlignment, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfHeapCommit, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfHeapReserve, System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfStackCommit, and System.Reflection.PortableExecutable.PEHeaderBuilder.SizeOfStackReserve.
Referenced by System.Reflection.PortableExecutable.PEHeaderBuilder.CreateExecutableHeader(), and System.Reflection.PortableExecutable.PEHeaderBuilder.CreateLibraryHeader().