Terraria: System.Xml.Linq.ElementWriter.PushAncestors
PushAncestors()
void System.Xml.Linq.ElementWriter.PushAncestors (XElement e) inline private
Definition at line 126 of file ElementWriter.cs.
    {
        while (true)
        {
            e = e.parent as XElement;
            if (e == null)
            {
                break;
            }
            XAttribute xAttribute = e.lastAttr;
            if (xAttribute == null)
            {
                continue;
            }
            do
            {
                xAttribute = xAttribute.next;
                if (xAttribute.IsNamespaceDeclaration)
                {
                    _resolver.AddFirst((xAttribute.Name.NamespaceName.Length == 0) ? string.Empty : xAttribute.Name.LocalName, XNamespace.Get(xAttribute.Value));
                }
            }
            while (xAttribute != e.lastAttr);
        }
    }
References System.Xml.Linq.ElementWriter._resolver, System.Xml.Linq.NamespaceResolver.AddFirst(), System.Xml.Dictionary, System.Xml.Linq.XNamespace.Get(), System.Xml.Linq.XElement.lastAttr, and System.Xml.Linq.XAttribute.next.
Referenced by System.Xml.Linq.ElementWriter.WriteElement(), and System.Xml.Linq.ElementWriter.WriteElementAsync().