Terraria: System.Xml.Linq.ElementWriter.WriteElement
WriteElement()
void System.Xml.Linq.ElementWriter.WriteElement (XElement e) inline
Definition at line 18 of file ElementWriter.cs.
    {
        PushAncestors(e);
        XNode xNode = e;
        while (true)
        {
            if (xNode is XElement xElement)
            {
                WriteStartElement(xElement);
                if (xElement.content == null)
                {
                    WriteEndElement();
                }
                else
                {
                    if (!(xElement.content is string text))
                    {
                        xNode = ((XNode)xElement.content).next;
                        continue;
                    }
                    _writer.WriteString(text);
                    WriteFullEndElement();
                }
            }
            else
            {
                xNode.WriteTo(_writer);
            }
            while (xNode != e && xNode == xNode.parent.content)
            {
                xNode = xNode.parent;
                WriteFullEndElement();
            }
            if (xNode != e)
            {
                xNode = xNode.next;
                continue;
            }
            break;
        }
    }
References System.Xml.Linq.ElementWriter._writer, System.Xml.Linq.XContainer.content, System.Xml.Dictionary, System.Xml.Linq.XObject.parent, System.Xml.Linq.ElementWriter.PushAncestors(), System.text, System.Xml.Linq.ElementWriter.WriteEndElement(), System.Xml.Linq.ElementWriter.WriteFullEndElement(), System.Xml.Linq.ElementWriter.WriteStartElement(), and System.Xml.XmlWriter.WriteString().
Referenced by System.Xml.Linq.XElement.WriteTo().