Terraria: System.Xml.Linq.ElementWriter.PushElement
PushElement()
void System.Xml.Linq.ElementWriter.PushElement (XElement e) inline private
Definition at line 152 of file ElementWriter.cs.
    {
        _resolver.PushScope();
        XAttribute xAttribute = e.lastAttr;
        if (xAttribute == null)
        {
            return;
        }
        do
        {
            xAttribute = xAttribute.next;
            if (xAttribute.IsNamespaceDeclaration)
            {
                _resolver.Add((xAttribute.Name.NamespaceName.Length == 0) ? string.Empty : xAttribute.Name.LocalName, XNamespace.Get(xAttribute.Value));
            }
        }
        while (xAttribute != e.lastAttr);
    }
References System.Xml.Linq.ElementWriter._resolver, System.Xml.Linq.NamespaceResolver.Add(), System.Xml.Dictionary, System.Xml.Linq.XNamespace.Get(), System.Xml.Linq.XElement.lastAttr, System.Xml.Linq.XAttribute.next, and System.Xml.Linq.NamespaceResolver.PushScope().
Referenced by System.Xml.Linq.ElementWriter.WriteStartElement().