Terraria: System.Xml.Linq.ElementWriter.WriteElementAsync
WriteElementAsync()
async Task System.Xml.Linq.ElementWriter.WriteElementAsync (XElement e, CancellationToken cancellationToken) inline
Definition at line 60 of file ElementWriter.cs.
    {
        PushAncestors(e);
        XNode i = e;
        while (true)
        {
            if (i is XElement current)
            {
                await WriteStartElementAsync(current, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                if (current.content == null)
                {
                    await WriteEndElementAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
                else
                {
                    if (!(current.content is string text))
                    {
                        i = ((XNode)current.content).next;
                        continue;
                    }
                    cancellationToken.ThrowIfCancellationRequested();
                    await _writer.WriteStringAsync(text).ConfigureAwait(continueOnCapturedContext: false);
                    await WriteFullEndElementAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
                }
            }
            else
            {
                await i.WriteToAsync(_writer, cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            while (i != e && i == i.parent.content)
            {
                i = i.parent;
                await WriteFullEndElementAsync(cancellationToken).ConfigureAwait(continueOnCapturedContext: false);
            }
            if (i != e)
            {
                i = i.next;
                continue;
            }
            break;
        }
    }
References System.Xml.Linq.ElementWriter._writer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.Linq.ElementWriter.PushAncestors(), System.text, System.Xml.Linq.ElementWriter.WriteEndElementAsync(), System.Xml.Linq.ElementWriter.WriteFullEndElementAsync(), System.Xml.Linq.ElementWriter.WriteStartElementAsync(), and System.Xml.XmlWriter.WriteStringAsync().
Referenced by System.Xml.Linq.XElement.WriteToAsync().