Terraria: System.Xml.Linq.ElementWriter.WriteEndElementAsync
WriteEndElementAsync()
async Task System.Xml.Linq.ElementWriter.WriteEndElementAsync (CancellationToken cancellationToken) inline private
Definition at line 177 of file ElementWriter.cs.
    {
        cancellationToken.ThrowIfCancellationRequested();
        await _writer.WriteEndElementAsync().ConfigureAwait(continueOnCapturedContext: false);
        _resolver.PopScope();
    }
References System.Xml.Linq.ElementWriter._resolver, System.Xml.Linq.ElementWriter._writer, System.cancellationToken, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Xml.Dictionary, System.Xml.Linq.NamespaceResolver.PopScope(), and System.Xml.XmlWriter.WriteEndElementAsync().
Referenced by System.Xml.Linq.ElementWriter.WriteElementAsync().