Terraria: System.Xml.Xsl.XsltOld.TemplateAction.CompileAttribute
CompileAttribute()
override bool System.Xml.Xsl.XsltOld.TemplateAction.CompileAttribute (Compiler compiler) inline package virtual
Reimplemented from System.Xml.Xsl.XsltOld.CompiledAction.
Definition at line 72 of file TemplateAction.cs.
    {
        string localName = compiler.Input.LocalName;
        string value = compiler.Input.Value;
        if (Ref.Equal(localName, compiler.Atoms.Match))
        {
            _matchKey = compiler.AddQuery(value, allowVar: false, allowKey: true, isPattern: true);
        }
        else if (Ref.Equal(localName, compiler.Atoms.Name))
        {
            _name = compiler.CreateXPathQName(value);
        }
        else if (Ref.Equal(localName, compiler.Atoms.Priority))
        {
            _priority = XmlConvert.ToXPathDouble(value);
            if (double.IsNaN(_priority) && !compiler.ForwardCompatibility)
            {
                throw XsltException.Create(System.SR.Xslt_InvalidAttrValue, "priority", value);
            }
        }
        else
        {
            if (!Ref.Equal(localName, compiler.Atoms.Mode))
            {
                return false;
            }
            if (compiler.AllowBuiltInMode && value == "*")
            {
                _mode = Compiler.BuiltInMode;
            }
            else
            {
                _mode = compiler.CreateXPathQName(value);
            }
        }
        return true;
    }
References System.Xml.Xsl.XsltOld.TemplateAction._matchKey, System.Xml.Xsl.XsltOld.TemplateAction._mode, System.Xml.Xsl.XsltOld.TemplateAction._name, System.Xml.Xsl.XsltOld.TemplateAction._priority, System.Xml.Xsl.XsltOld.Compiler.BuiltInMode, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Xml.XmlConvert.ToXPathDouble(), System.value, and System.SR.Xslt_InvalidAttrValue.