Terraria: System.Xml.Xsl.XsltOld.TemplateAction.Compile
Compile()
override void System.Xml.Xsl.XsltOld.TemplateAction.Compile (Compiler compiler) inline package
Definition at line 40 of file TemplateAction.cs.
    {
        CompileAttributes(compiler);
        if (_matchKey == -1)
        {
            if (_name == null)
            {
                throw XsltException.Create(System.SR.Xslt_TemplateNoAttrib);
            }
            if (_mode != null)
            {
                throw XsltException.Create(System.SR.Xslt_InvalidModeAttribute);
            }
        }
        compiler.BeginTemplate(this);
        if (compiler.Recurse())
        {
            CompileParameters(compiler);
            CompileTemplate(compiler);
            compiler.ToParent();
        }
        compiler.EndTemplate();
        AnalyzePriority(compiler);
    }
References System.Xml.Xsl.XsltOld.TemplateAction._matchKey, System.Xml.Xsl.XsltOld.TemplateAction._mode, System.Xml.Xsl.XsltOld.TemplateAction._name, System.Xml.Xsl.XsltOld.TemplateAction.AnalyzePriority(), System.Xml.Xsl.XsltOld.CompiledAction.CompileAttributes(), System.Xml.Xsl.XsltOld.TemplateAction.CompileParameters(), System.Xml.Xsl.XsltOld.ContainerAction.CompileTemplate(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.SR.Xslt_InvalidModeAttribute, and System.SR.Xslt_TemplateNoAttrib.