Terraria: LogitechDeviceGroup.Initialize
Initialize()
override void LogitechDeviceGroup.Initialize () inline protected virtual
Implements RgbDeviceGroup.
     {
         if (_isInitialized || _initializationFailed)
         {
             return;
         }
         if (!NativeLibrary.TryLoad("LogitechLedEnginesWrapper ", out var _))
         {
             _initializationFailed = true;
             return;
         }
         try
         {
             if (!NativeMethods.LogiLedInit())
             {
                 throw new DeviceInitializationException("LogitechGSDK failed to initialize.");
             }
             _isInitialized = true;
             if (!NativeMethods.LogiLedSetTargetDevice(6))
             {
                 throw new DeviceInitializationException("LogitechGSDK failed to target RGB devices.");
             }
             _devices.Add(new LogitechKeyboard(_colorProfiles.Keyboard));
             _devices.Add(new LogitechSingleLightDevice(_colorProfiles.Generic));
             Console.WriteLine("Logitech RGB initialized.");
         }
         catch (DeviceInitializationException)
         {
             Console.WriteLine("Logitech RGB not supported. (Can be disabled via Config.json)");
             Uninitialize();
         }
         catch (Exception ex2)
         {
             Console.WriteLine("Logitech RGB not supported: " + ex2);
         }
     }
References _colorProfiles, _devices, _initializationFailed, _isInitialized, VendorColorProfile.Generic, VendorColorProfile.Keyboard, NativeMethods.LogiLedInit(), NativeMethods.LogiLedSetTargetDevice(), and Uninitialize().