Terraria: System.Xml.Schema.ParticleContentValidator.CheckUniqueParticleAttribution
CheckUniqueParticleAttribution() [2/2]
void System.Xml.Schema.ParticleContentValidator.CheckUniqueParticleAttribution (BitSet firstpos, BitSet[] followpos) inline private
Definition at line 323 of file ParticleContentValidator.cs.
    {
        CheckUniqueParticleAttribution(firstpos);
        for (int i = 0; i < _positions.Count; i++)
        {
            CheckUniqueParticleAttribution(followpos[i]);
        }
    }
References System.Xml.Schema.ParticleContentValidator._positions, System.Xml.Schema.ParticleContentValidator.CheckUniqueParticleAttribution(), and System.Xml.Schema.Positions.Count.
Referenced by System.Xml.Schema.ParticleContentValidator.CheckUniqueParticleAttribution(), and System.Xml.Schema.ParticleContentValidator.Finish().