Terraria: System.Collections.Immutable.Requires.Range
Range()
static void System.Collections.Immutable.Requires.Range (bool condition, string? parameterName, string? message = null) inline static
Definition at line 40 of file Requires.cs.
    {
        if (!condition)
        {
            FailRange(parameterName, message);
        }
    }
References System.Collections.Immutable.Requires.FailRange().
Referenced by System.Collections.Immutable.ImmutableArray< T >.Builder.Builder(), System.Collections.Immutable.ImmutableList< T >.Enumerator.Enumerator(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.ImmutableSortedDictionary(), System.Collections.Immutable.ImmutableHashSet< T >.MutationInput.MutationInput(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableArray< T >.Builder.AddRange(), System.Collections.Immutable.ImmutableList< T >.Node.BinarySearch(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Builder.CopyTo(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.CopyTo(), System.Collections.Immutable.ImmutableHashSet< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.CopyTo(), System.Collections.Immutable.KeysOrValuesCollectionAccessor< TKey, TValue, T >.CopyTo(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.CopyTo(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.CopyTo(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableHashSet< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableHashSet< T >.CopyTo(), System.Collections.Immutable.ImmutableList< T >.Node.CopyTo(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.CopyTo(), System.Collections.Immutable.KeysOrValuesCollectionAccessor< TKey, TValue, T >.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.Builder.CopyTo(), System.Collections.Immutable.ImmutableArray< T >.Create< T >(), System.Collections.Immutable.ImmutableArray< T >.Create< T >(), System.Collections.Immutable.ImmutableArray< T >.CreateRange< TSource, TArg, TResult >(), System.Collections.Immutable.ImmutableArray< T >.CreateRange< TSource, TResult >(), System.Collections.Immutable.ImmutableList< T >.Node.FindIndex(), System.Collections.Immutable.ImmutableList< T >.Node.FindIndex(), System.Collections.Immutable.ImmutableList< T >.Node.FindLastIndex(), System.Collections.Immutable.ImmutableList< T >.Node.FindLastIndex(), System.Collections.Immutable.ImmutableList< T >.Builder.GetRange(), System.Collections.Immutable.ImmutableList< T >.GetRange(), System.Collections.Immutable.ImmutableList< T >.Node.IndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.IndexOf(), System.Collections.Immutable.ImmutableArray< T >.IndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.Insert(), System.Collections.Immutable.ImmutableArray< T >.Insert(), System.Collections.Immutable.ImmutableList< T >.Insert(), System.Collections.Immutable.ImmutableList< T >.Node.Insert(), System.Collections.Immutable.ImmutableArray< T >.InsertRange(), System.Collections.Immutable.ImmutableList< T >.Builder.InsertRange(), System.Collections.Immutable.ImmutableList< T >.InsertRange(), System.Collections.Immutable.ImmutableList< T >.Node.InsertRange(), System.Collections.Immutable.ImmutableArray< T >.InsertRange(), System.Collections.Immutable.ImmutableList< T >.Node.ItemRef(), System.Collections.Immutable.ImmutableSortedSet< T >.Node.ItemRef(), System.Collections.Immutable.ImmutableList< T >.Node.LastIndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.LastIndexOf(), System.Collections.Immutable.ImmutableArray< T >.Builder.LastIndexOf(), System.Collections.Immutable.ImmutableArray< T >.LastIndexOf(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.NodeTreeFromList(), System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), System.Collections.Immutable.ImmutableArray< T >.Builder.RemoveAt(), System.Collections.Immutable.ImmutableList< T >.Node.RemoveAt(), System.Collections.Immutable.ImmutableList< T >.RemoveAt(), System.Collections.Immutable.ImmutableList< T >.RemoveRange(), System.Collections.Immutable.ImmutableArray< T >.RemoveRange(), System.Collections.Immutable.ImmutableList< T >.Node.ReplaceAt(), System.Collections.Immutable.ImmutableList< T >.Builder.Reverse(), System.Collections.Immutable.ImmutableList< T >.Node.Reverse(), System.Collections.Immutable.ImmutableArray< T >.SetItem(), System.Collections.Immutable.ImmutableArray< T >.Builder.Sort(), System.Collections.Immutable.ImmutableArray< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Builder.Sort(), System.Collections.Immutable.ImmutableList< T >.Node.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableExtensions.ToArray< T >(), System.Collections.Immutable.ImmutableDictionary< TKey, TValue >.Wrap(), and System.Collections.Immutable.ImmutableHashSet< T >.Wrap().