Terraria: System.Xml.Schema.ParticleContentValidator.Finish
Finish()
ContentValidator System.Xml.Schema.ParticleContentValidator.Finish (bool useDFA) inline
Definition at line 189 of file ParticleContentValidator.cs.
    {
        if (_contentNode == null)
        {
            if (base.ContentType == XmlSchemaContentType.Mixed)
            {
                if (!base.IsOpen)
                {
                    return ContentValidator.TextOnly;
                }
                return ContentValidator.Any;
            }
            return ContentValidator.Empty;
        }
        InteriorNode interiorNode = new SequenceNode();
        interiorNode.LeftChild = _contentNode;
        LeafNode leafNode = (LeafNode)(interiorNode.RightChild = new LeafNode(_positions.Add(_symbols.AddName(XmlQualifiedName.Empty, null), null)));
        _contentNode.ExpandTree(interiorNode, _symbols, _positions);
        int count = _positions.Count;
        BitSet bitSet = new BitSet(count);
        BitSet lastpos = new BitSet(count);
        BitSet[] array = new BitSet[count];
        for (int i = 0; i < count; i++)
        {
            array[i] = new BitSet(count);
        }
        interiorNode.ConstructPos(bitSet, lastpos, array);
        if (_minMaxNodesCount > 0)
        {
            BitSet posWithRangeTerminals;
            BitSet[] minmaxFollowPos = CalculateTotalFollowposForRangeNodes(bitSet, array, out posWithRangeTerminals);
            if (_enableUpaCheck)
            {
                CheckCMUPAWithLeafRangeNodes(GetApplicableMinMaxFollowPos(bitSet, posWithRangeTerminals, minmaxFollowPos));
                for (int j = 0; j < count; j++)
                {
                    CheckCMUPAWithLeafRangeNodes(GetApplicableMinMaxFollowPos(array[j], posWithRangeTerminals, minmaxFollowPos));
                }
            }
            return new RangeContentValidator(bitSet, array, _symbols, _positions, leafNode.Pos, base.ContentType, interiorNode.LeftChild.IsNullable, posWithRangeTerminals, _minMaxNodesCount);
        }
        int[][] array2 = null;
        if (!_symbols.IsUpaEnforced)
        {
            if (_enableUpaCheck)
            {
                CheckUniqueParticleAttribution(bitSet, array);
            }
        }
        else if (useDFA)
        {
            array2 = BuildTransitionTable(bitSet, array, leafNode.Pos);
        }
        if (array2 != null)
        {
            return new DfaContentValidator(array2, _symbols, base.ContentType, base.IsOpen, interiorNode.LeftChild.IsNullable);
        }
        return new NfaContentValidator(bitSet, array, _symbols, _positions, leafNode.Pos, base.ContentType, base.IsOpen, interiorNode.LeftChild.IsNullable);
    }
References System.Xml.Schema.ParticleContentValidator._contentNode, System.Xml.Schema.ParticleContentValidator._enableUpaCheck, System.Xml.Schema.ParticleContentValidator._minMaxNodesCount, System.Xml.Schema.ParticleContentValidator._positions, System.Xml.Schema.ParticleContentValidator._symbols, System.Xml.Schema.Positions.Add(), System.Xml.Schema.SymbolsDictionary.AddName(), System.Xml.Schema.ContentValidator.Any, System.array, System.Xml.Schema.ParticleContentValidator.BuildTransitionTable(), System.Xml.Schema.ParticleContentValidator.CalculateTotalFollowposForRangeNodes(), System.Xml.Schema.ParticleContentValidator.CheckCMUPAWithLeafRangeNodes(), System.Xml.Schema.ParticleContentValidator.CheckUniqueParticleAttribution(), System.count, System.Xml.Schema.Positions.Count, System.Xml.Dictionary, System.Xml.Schema.ContentValidator.Empty, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.SyntaxTreeNode.ExpandTree(), System.Xml.Schema.ParticleContentValidator.GetApplicableMinMaxFollowPos(), System.Xml.Schema.SymbolsDictionary.IsUpaEnforced, and System.Xml.Schema.ContentValidator.TextOnly.