Terraria: System.Reflection.Emit.EventBuilder.SetCustomAttribute
SetCustomAttribute() [1/2]
void System.Reflection.Emit.EventBuilder.SetCustomAttribute (ConstructorInfo con, byte[] binaryAttribute) inline
Definition at line 57 of file EventBuilder.cs.
    {
        if (con == null)
        {
            throw new ArgumentNullException("con");
        }
        if (binaryAttribute == null)
        {
            throw new ArgumentNullException("binaryAttribute");
        }
        m_type.ThrowIfCreated();
        TypeBuilder.DefineCustomAttribute(m_module, m_evToken, m_module.GetConstructorToken(con), binaryAttribute);
    }
References System.Reflection.Emit.TypeBuilder.DefineCustomAttribute(), System.Reflection.Emit.ModuleBuilder.GetConstructorToken(), System.Reflection.Emit.EventBuilder.m_evToken, System.Reflection.Emit.EventBuilder.m_module, System.Reflection.Emit.EventBuilder.m_type, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().