Terraria: System.Reflection.Emit.EventBuilder.SetMethodSemantics
SetMethodSemantics()
void System.Reflection.Emit.EventBuilder.SetMethodSemantics (MethodBuilder mdBuilder, MethodSemanticsAttributes semantics) inline private
Definition at line 26 of file EventBuilder.cs.
    {
        if (mdBuilder == null)
        {
            throw new ArgumentNullException("mdBuilder");
        }
        m_type.ThrowIfCreated();
        ModuleBuilder module = m_module;
        TypeBuilder.DefineMethodSemantics(new QCallModule(ref module), m_evToken, semantics, mdBuilder.MetadataToken);
    }
References System.Reflection.Emit.TypeBuilder.DefineMethodSemantics(), System.Reflection.Emit.EventBuilder.m_evToken, System.Reflection.Emit.EventBuilder.m_module, System.Reflection.Emit.EventBuilder.m_type, System.Reflection.Emit.MethodBuilder.MetadataToken, and System.Reflection.Emit.TypeBuilder.ThrowIfCreated().
Referenced by System.Reflection.Emit.EventBuilder.AddOtherMethod(), System.Reflection.Emit.EventBuilder.SetAddOnMethod(), System.Reflection.Emit.EventBuilder.SetRaiseMethod(), and System.Reflection.Emit.EventBuilder.SetRemoveOnMethod().