Terraria: ReLogic.Peripherals.RGB.Corsair.CorsairMousepad.Create
Create()
static CorsairMousepad ReLogic.Peripherals.RGB.Corsair.CorsairMousepad.Create (int deviceIndex, DeviceColorProfile colorProfile) inline static
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        CorsairLedPosition[] ledPositionsForMouseMatOrKeyboard = CorsairHelper.GetLedPositionsForMouseMatOrKeyboard(deviceIndex);
        return new CorsairMousepad(CorsairHelper.CreateFragment(ledPositionsForMouseMatOrKeyboard, new Vector2(1040f, 0f)), ledPositionsForMouseMatOrKeyboard, colorProfile);
    }
References ReLogic.Peripherals.RGB.Corsair.CorsairMousepad.CorsairMousepad(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.CreateFragment(), and ReLogic.Peripherals.RGB.Corsair.CorsairHelper.GetLedPositionsForMouseMatOrKeyboard().
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.AddDeviceIfSupported().