Terraria: System.Runtime.Serialization.CodeGenerator.Store
Store()
void System.Runtime.Serialization.CodeGenerator.Store (object var) inline package
Definition at line 800 of file CodeGenerator.cs.
    {
        if (var is ArgBuilder)
        {
            Starg((ArgBuilder)var);
            return;
        }
        if (var is LocalBuilder)
        {
            Stloc((LocalBuilder)var);
            return;
        }
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CanOnlyStoreIntoArgOrLocGot0, DataContract.GetClrTypeFullName(var.GetType()))));
    }
References System.SR.CanOnlyStoreIntoArgOrLocGot0, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Reflection.Emit.Starg, System.Reflection.Emit.Stloc, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.CodeGenerator.Dec(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.BitFlagsGenerator.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.CodeGenerator.Set(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue().