Terraria: System.Runtime.Serialization.CodeGenerator.GetBranchCode
GetBranchCode()
OpCode System.Runtime.Serialization.CodeGenerator.GetBranchCode (Cmp cmp) inline private
Definition at line 385 of file CodeGenerator.cs.
    {
        return cmp switch
        {
            Cmp.LessThan => OpCodes.Bge,
            Cmp.EqualTo => OpCodes.Bne_Un,
            Cmp.LessThanOrEqualTo => OpCodes.Bgt,
            Cmp.GreaterThan => OpCodes.Ble,
            Cmp.NotEqualTo => OpCodes.Beq,
            _ => OpCodes.Blt,
        };
    }
References System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Bge, System.Reflection.Emit.OpCodes.Bgt, System.Reflection.Emit.OpCodes.Ble, System.Reflection.Emit.OpCodes.Blt, System.Reflection.Emit.OpCodes.Bne_Un, and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), and System.Runtime.Serialization.CodeGenerator.If().