Terraria: System.Runtime.Serialization.CodeGenerator.NewArray
NewArray()
void System.Runtime.Serialization.CodeGenerator.NewArray (Type elementType, object len) inline package
Definition at line 578 of file CodeGenerator.cs.
    {
        Load(len);
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction("Newarr " + elementType);
        }
        _ilGen.Emit(OpCodes.Newarr, elementType);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.elementType, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.len, System.Runtime.Serialization.CodeGenerator.Load(), and System.Reflection.Emit.OpCodes.Newarr.
Referenced by System.Runtime.Serialization.CodeGenerator.CallStringFormat(), System.Runtime.Serialization.BitFlagsGenerator.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection().