Terraria: System.Runtime.Serialization.CodeGenerator.CallStringFormat
CallStringFormat()
void System.Runtime.Serialization.CodeGenerator.CallStringFormat (string msg, params object[] values) inline package
Definition at line 1650 of file CodeGenerator.cs.
    {
        NewArray(typeof(object), values.Length);
        if (_stringFormatArray == null)
        {
            _stringFormatArray = DeclareLocal(typeof(object[]), "stringFormatArray");
        }
        Stloc(_stringFormatArray);
        for (int i = 0; i < values.Length; i++)
        {
            StoreArrayElement(_stringFormatArray, i, values[i]);
        }
        Load(msg);
        Load(_stringFormatArray);
        Call(StringFormat);
    }
References System.Runtime.Serialization.CodeGenerator._stringFormatArray, System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Reflection.Emit.Stloc, System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.CodeGenerator.StringFormat, and System.values.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException().