Terraria: System.Runtime.Serialization.CodeGenerator.Ldelem
Ldelem()
void System.Runtime.Serialization.CodeGenerator.Ldelem (Type arrayElementType) inline package
Definition at line 1208 of file CodeGenerator.cs.
    {
        if (arrayElementType.IsEnum)
        {
            Ldelem(Enum.GetUnderlyingType(arrayElementType));
            return;
        }
        OpCode ldelemOpCode = GetLdelemOpCode(arrayElementType.GetTypeCode());
        if (ldelemOpCode.Equals(OpCodes.Nop))
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ArrayTypeIsNotSupported_GeneratingCode, DataContract.GetClrTypeFullName(arrayElementType))));
        }
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction(ldelemOpCode.ToString());
        }
        _ilGen.Emit(ldelemOpCode);
        EmitStackTop(arrayElementType);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.SR.ArrayTypeIsNotSupported_GeneratingCode, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.Runtime.Serialization.CodeGenerator.EmitStackTop(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.CodeGenerator.GetLdelemOpCode(), System.Enum.GetUnderlyingType(), System.Reflection.Emit.Ldelem, System.Reflection.Emit.OpCodes.Nop, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().