Terraria: System.Runtime.Serialization.CodeGenerator.For
For()
object System.Runtime.Serialization.CodeGenerator.For (LocalBuilder local, object start, object end) inline package
Definition at line 247 of file CodeGenerator.cs.
    {
        ForState forState = new ForState(local, DefineLabel(), DefineLabel(), end);
        if (forState.Index != null)
        {
            Load(start);
            Stloc(forState.Index);
            Br(forState.TestLabel);
        }
        MarkLabel(forState.BeginLabel);
        _blockStack.Push(forState);
        return forState;
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Br, System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Collections.Generic.Stack< T >.Push(), System.start, and System.Reflection.Emit.Stloc.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().