Terraria: System.Runtime.Serialization.CodeGenerator.GetArg
GetArg()
ArgBuilder System.Runtime.Serialization.CodeGenerator.GetArg (int index) inline package
Definition at line 199 of file CodeGenerator.cs.
    {
        return _argList[index];
    }
References System.Runtime.Serialization.CodeGenerator._argList, and System.index.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs().