Terraria: System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue
IfNotDefaultValue()
void System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue (object value) inline package
Definition at line 354 of file CodeGenerator.cs.
    {
        Type variableType = GetVariableType(value);
        TypeCode typeCode = variableType.GetTypeCode();
        if ((typeCode == TypeCode.Object && variableType.IsValueType) || typeCode == TypeCode.DateTime || typeCode == TypeCode.Decimal)
        {
            LoadDefaultValue(variableType);
            ConvertValue(variableType, Globals.TypeOfObject);
            Load(value);
            ConvertValue(variableType, Globals.TypeOfObject);
            Call(ObjectEquals);
            IfNot();
        }
        else
        {
            LoadDefaultValue(variableType);
            Load(value);
            If(Cmp.NotEqualTo);
        }
    }
References System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.GetVariableType(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNot(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadDefaultValue(), System.Runtime.Serialization.CodeGenerator.ObjectEquals, System.Runtime.Serialization.Globals.TypeOfObject, and System.value.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().