Terraria: System.Runtime.Serialization.CodeGenerator.StoreMember
StoreMember()
void System.Runtime.Serialization.CodeGenerator.StoreMember (MemberInfo memberInfo) inline package
Definition at line 691 of file CodeGenerator.cs.
    {
        if (memberInfo is FieldInfo)
        {
            FieldInfo fieldInfo = (FieldInfo)memberInfo;
            if (fieldInfo.IsStatic)
            {
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction("Stsfld " + fieldInfo?.ToString() + " on type " + fieldInfo.DeclaringType);
                }
                _ilGen.Emit(OpCodes.Stsfld, fieldInfo);
            }
            else
            {
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction("Stfld " + fieldInfo?.ToString() + " on type " + fieldInfo.DeclaringType);
                }
                _ilGen.Emit(OpCodes.Stfld, fieldInfo);
            }
        }
        else if (memberInfo is PropertyInfo)
        {
            PropertyInfo propertyInfo = memberInfo as PropertyInfo;
            if (propertyInfo != null)
            {
                MethodInfo setMethod = propertyInfo.SetMethod;
                if (setMethod == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.NoSetMethodForProperty, propertyInfo.DeclaringType, propertyInfo)));
                }
                Call(setMethod);
            }
        }
        else
        {
            if (!(memberInfo is MethodInfo))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CannotLoadMemberType, "Unknown")));
            }
            Call((MethodInfo)memberInfo);
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.Call, System.SR.CannotLoadMemberType, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.SR.Format(), System.SR.NoSetMethodForProperty, System.Reflection.PropertyInfo.SetMethod, System.Reflection.Emit.OpCodes.Stfld, System.Reflection.Emit.OpCodes.Stsfld, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.ToString.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers().