Terraria: System.Runtime.Serialization.CodeGenerator.LoadDefaultValue
LoadDefaultValue()
void System.Runtime.Serialization.CodeGenerator.LoadDefaultValue (Type type) inline package
Definition at line 736 of file CodeGenerator.cs.
    {
        if (type.IsValueType)
        {
            switch (type.GetTypeCode())
            {
            case TypeCode.Boolean:
                Ldc(boolVar: false);
                return;
            case TypeCode.Char:
            case TypeCode.SByte:
            case TypeCode.Byte:
            case TypeCode.Int16:
            case TypeCode.UInt16:
            case TypeCode.Int32:
            case TypeCode.UInt32:
                Ldc(0);
                return;
            case TypeCode.Int64:
            case TypeCode.UInt64:
                Ldc(0L);
                return;
            case TypeCode.Single:
                Ldc(0f);
                return;
            case TypeCode.Double:
                Ldc(0.0);
                return;
            }
            LocalBuilder obj = DeclareLocal(type, "zero");
            LoadAddress(obj);
            InitObj(type);
            Load(obj);
        }
        else
        {
            Load(null);
        }
    }
References System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.InitObj(), System.L, System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.obj, and System.type.
Referenced by System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue().