Terraria: System.Runtime.Serialization.CodeGenerator.Throw
Throw()
void System.Runtime.Serialization.CodeGenerator.Throw () inline package
Definition at line 936 of file CodeGenerator.cs.
    {
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction("Throw");
        }
        _ilGen.Emit(OpCodes.Throw);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), and System.Reflection.Emit.OpCodes.Throw.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException().