Terraria: System.Runtime.Serialization.CodeGenerator.Else
Else()
void System.Runtime.Serialization.CodeGenerator.Else () inline package
Definition at line 414 of file CodeGenerator.cs.
    {
        IfState ifState = PopIfState();
        Br(ifState.EndIf);
        MarkLabel(ifState.ElseBegin);
        ifState.ElseBegin = ifState.EndIf;
        _blockStack.Push(ifState);
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Br, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Runtime.Serialization.CodeGenerator.PopIfState(), and System.Collections.Generic.Stack< T >.Push().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().