Terraria: System.Runtime.Serialization.CodeGenerator.EndMethod
EndMethod()
Delegate System.Runtime.Serialization.CodeGenerator.EndMethod () inline package
Definition at line 181 of file CodeGenerator.cs.
    {
        MarkLabel(_methodEndLabel);
        if (_codeGenTrace != 0)
        {
            EmitSourceLabel("} End method");
        }
        Ret();
        Delegate @delegate = null;
        @delegate = _dynamicMethod.CreateDelegate(_delegateType);
        _dynamicMethod = null;
        _delegateType = null;
        _ilGen = null;
        _blockStack = null;
        _argList = null;
        return @delegate;
    }
References System.Runtime.Serialization.CodeGenerator._argList, System.Runtime.Serialization.CodeGenerator._blockStack, System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._delegateType, System.Runtime.Serialization.CodeGenerator._dynamicMethod, System.Runtime.Serialization.CodeGenerator._ilGen, System.Runtime.Serialization.CodeGenerator._methodEndLabel, System.Reflection.Emit.DynamicMethod.CreateDelegate(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.EmitSourceLabel(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), and System.Runtime.Serialization.CodeGenerator.Ret().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateGetOnlyCollectionReader().