Terraria: System.Runtime.Serialization.CodeGenerator.Ldc
Ldc() [6/6]
void System.Runtime.Serialization.CodeGenerator.Ldc (object o) inline package
Definition at line 954 of file CodeGenerator.cs.
    {
        Type type = o.GetType();
        if (o is Type)
        {
            Ldtoken((Type)o);
            Call(GetTypeFromHandle);
            return;
        }
        if (type.IsEnum)
        {
            if (_codeGenTrace != 0)
            {
                EmitSourceComment("Ldc " + o.GetType()?.ToString() + "." + o);
            }
            Ldc(Convert.ChangeType(o, Enum.GetUnderlyingType(type), null));
            return;
        }
        switch (type.GetTypeCode())
        {
        case TypeCode.Boolean:
            Ldc((bool)o);
            break;
        case TypeCode.Char:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new NotSupportedException(System.SR.CharIsInvalidPrimitive));
        case TypeCode.SByte:
        case TypeCode.Byte:
        case TypeCode.Int16:
        case TypeCode.UInt16:
            Ldc(Convert.ToInt32(o, CultureInfo.InvariantCulture));
            break;
        case TypeCode.Int32:
            Ldc((int)o);
            break;
        case TypeCode.UInt32:
            Ldc((int)(uint)o);
            break;
        case TypeCode.UInt64:
            Ldc((long)(ulong)o);
            break;
        case TypeCode.Int64:
            Ldc((long)o);
            break;
        case TypeCode.Single:
            Ldc((float)o);
            break;
        case TypeCode.Double:
            Ldc((double)o);
            break;
        case TypeCode.String:
            Ldstr((string)o);
            break;
        default:
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.UnknownConstantType, DataContract.GetClrTypeFullName(type))));
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Reflection.Emit.Call, System.Convert.ChangeType(), System.SR.CharIsInvalidPrimitive, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Runtime.Serialization.CodeGenerator.EmitSourceComment(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.CodeGenerator.GetTypeFromHandle, System.Enum.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.CodeGenerator.Ldc(), System.Reflection.Emit.Ldstr, System.Reflection.Emit.Ldtoken, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Convert.ToInt32(), System.type, and System.SR.UnknownConstantType.
Referenced by System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Load(), and System.Runtime.Serialization.CodeGenerator.LoadDefaultValue().