Terraria: System.Runtime.Serialization.CodeGenerator.Call
Call() [3/9]
void System.Runtime.Serialization.CodeGenerator.Call (object thisObj, MethodInfo methodInfo) inline package
Definition at line 453 of file CodeGenerator.cs.
    {
        VerifyParameterCount(methodInfo, 0);
        LoadThis(thisObj, methodInfo);
        Call(methodInfo);
    }
References System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.LoadThis(), and System.Runtime.Serialization.CodeGenerator.VerifyParameterCount().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsStartElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreKeyValuePair(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.ThrowIfCannotSerializeReadOnlyTypes(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowUnexpectedStateException(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteArrayAttribute(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteEndElement(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteEndElement(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteObjectAttribute(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().