Terraria: System.Runtime.Serialization.CodeGenerator.IfNotIsEmptyString
IfNotIsEmptyString()
void System.Runtime.Serialization.CodeGenerator.IfNotIsEmptyString (LocalBuilder strLocal) inline package
Definition at line 1621 of file CodeGenerator.cs.
    {
        Load(strLocal);
        Call(s_stringLength);
        Load(0);
        If(Cmp.NotEqualTo);
    }
References System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.Load(), and System.Runtime.Serialization.CodeGenerator.s_stringLength.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue().