Terraria: System.Runtime.Serialization.CodeGenerator.ConvertValue
ConvertValue()
void System.Runtime.Serialization.CodeGenerator.ConvertValue (Type source, Type target) inline package
Definition at line 844 of file CodeGenerator.cs.
    {
        InternalConvert(source, target, isAddress: false);
    }
References System.Runtime.Serialization.CodeGenerator.InternalConvert(), and System.source.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.CodeGenerator.ForEach(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.CodeGenerator.LoadParam(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().