Terraria: System.Runtime.Serialization.CodeGenerator.LoadArrayElement
LoadArrayElement()
void System.Runtime.Serialization.CodeGenerator.LoadArrayElement (object obj, object arrayIndex) inline package
Definition at line 588 of file CodeGenerator.cs.
    {
        Type elementType = GetVariableType(obj).GetElementType();
        Load(obj);
        Load(arrayIndex);
        if (IsStruct(elementType))
        {
            Ldelema(elementType);
            Ldobj(elementType);
        }
        else
        {
            Ldelem(elementType);
        }
    }
References System.arrayIndex, System.elementType, System.Type.GetElementType(), System.Runtime.Serialization.CodeGenerator.GetVariableType(), System.Runtime.Serialization.CodeGenerator.IsStruct(), System.Reflection.Emit.Ldelem, System.Reflection.Emit.Ldelema, System.Reflection.Emit.Ldobj, System.Runtime.Serialization.CodeGenerator.Load(), and System.obj.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement().