Terraria: System.Runtime.Serialization.CodeGenerator.InitILGeneration
InitILGeneration()
void System.Runtime.Serialization.CodeGenerator.InitILGeneration (string methodName, Type[] argTypes) inline private
Definition at line 166 of file CodeGenerator.cs.
    {
        _methodEndLabel = _ilGen.DefineLabel();
        _blockStack = new Stack<object>();
        _argList = new List<ArgBuilder>();
        for (int i = 0; i < argTypes.Length; i++)
        {
            _argList.Add(new ArgBuilder(i, argTypes[i]));
        }
        if (_codeGenTrace != 0)
        {
            EmitSourceLabel("Begin method " + methodName + " {");
        }
    }
References System.Runtime.Serialization.CodeGenerator._argList, System.Runtime.Serialization.CodeGenerator._blockStack, System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Runtime.Serialization.CodeGenerator._methodEndLabel, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Emit.ILGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.CodeGenerator.EmitSourceLabel().
Referenced by System.Runtime.Serialization.CodeGenerator.BeginMethod(), and System.Runtime.Serialization.CodeGenerator.BeginMethod().