Terraria: System.Runtime.Serialization.CodeGenerator.Call
Call() [9/9]
void System.Runtime.Serialization.CodeGenerator.Call (object thisObj, MethodInfo methodInfo, object param1, object param2, object param3, object param4, object param5, object param6) inline package
Definition at line 510 of file CodeGenerator.cs.
    {
        VerifyParameterCount(methodInfo, 6);
        LoadThis(thisObj, methodInfo);
        LoadParam(param1, 1, methodInfo);
        LoadParam(param2, 2, methodInfo);
        LoadParam(param3, 3, methodInfo);
        LoadParam(param4, 4, methodInfo);
        LoadParam(param5, 5, methodInfo);
        LoadParam(param6, 6, methodInfo);
        Call(methodInfo);
    }
References System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.LoadParam(), System.Runtime.Serialization.CodeGenerator.LoadThis(), and System.Runtime.Serialization.CodeGenerator.VerifyParameterCount().