Terraria: System.Runtime.Serialization.CodeGenerator.EndFor
EndFor()
void System.Runtime.Serialization.CodeGenerator.EndFor () inline package
Definition at line 261 of file CodeGenerator.cs.
    {
        object obj = _blockStack.Pop();
        ForState forState = obj as ForState;
        if (forState == null)
        {
            ThrowMismatchException(obj);
        }
        if (forState.Index != null)
        {
            Ldloc(forState.Index);
            Ldc(1);
            Add();
            Stloc(forState.Index);
            MarkLabel(forState.TestLabel);
            Ldloc(forState.Index);
            Load(forState.End);
            if (GetVariableType(forState.End).IsArray)
            {
                Ldlen();
            }
            Blt(forState.BeginLabel);
        }
        else
        {
            Br(forState.BeginLabel);
        }
        if (forState.RequiresEndLabel)
        {
            MarkLabel(forState.EndLabel);
        }
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Runtime.Serialization.CodeGenerator.Add(), System.Reflection.Emit.Blt, System.Reflection.Emit.Br, System.Runtime.Serialization.CodeGenerator.GetVariableType(), System.Type.IsArray, System.Runtime.Serialization.CodeGenerator.Ldc(), System.Runtime.Serialization.CodeGenerator.Ldlen(), System.Reflection.Emit.Ldloc, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.obj, System.Collections.Generic.Stack< T >.Pop(), System.Reflection.Emit.Stloc, and System.Runtime.Serialization.CodeGenerator.ThrowMismatchException().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().