Terraria: System.Runtime.Serialization.CodeGenerator.ElseIf
ElseIf()
void System.Runtime.Serialization.CodeGenerator.ElseIf (object value1, Cmp cmpOp, object value2) inline package
Definition at line 423 of file CodeGenerator.cs.
    {
        IfState ifState = (IfState)_blockStack.Pop();
        Br(ifState.EndIf);
        MarkLabel(ifState.ElseBegin);
        Load(value1);
        Load(value2);
        ifState.ElseBegin = DefineLabel();
        _ilGen.Emit(GetBranchCode(cmpOp), ifState.ElseBegin);
        _blockStack.Push(ifState);
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.Br, System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.GetBranchCode(), System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Collections.Generic.Stack< T >.Pop(), and System.Collections.Generic.Stack< T >.Push().