Terraria: System.Runtime.Serialization.CodeGenerator.Dec
Dec()
void System.Runtime.Serialization.CodeGenerator.Dec (object var) inline package
Definition at line 815 of file CodeGenerator.cs.
    {
        Load(var);
        Load(1);
        Subtract();
        Store(var);
    }
References System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.Store(), and System.Runtime.Serialization.CodeGenerator.Subtract().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection().