Terraria: System.Runtime.Serialization.CodeGenerator.GetVariableType
GetVariableType()
Type System.Runtime.Serialization.CodeGenerator.GetVariableType (object var) inline package
Definition at line 204 of file CodeGenerator.cs.
    {
        if (var is ArgBuilder)
        {
            return ((ArgBuilder)var).ArgType;
        }
        if (var is LocalBuilder)
        {
            return ((LocalBuilder)var).LocalType;
        }
        return var.GetType();
    }
Referenced by System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.ForEach(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.CodeGenerator.LoadParam(), System.Runtime.Serialization.CodeGenerator.LoadThis(), and System.Runtime.Serialization.CodeGenerator.StoreArrayElement().