Terraria: System.Runtime.Serialization.CodeGenerator.Ceq
Ceq()
void System.Runtime.Serialization.CodeGenerator.Ceq () inline package
Definition at line 927 of file CodeGenerator.cs.
    {
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction("Ceq");
        }
        _ilGen.Emit(OpCodes.Ceq);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.OpCodes.Ceq, System.Reflection.Emit.ILGenerator.Emit(), and System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CheckRequiredElements(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.BitFlagsGenerator.Load(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().