Terraria: System.Runtime.Serialization.CodeGenerator.If
If() [1/3]
void System.Runtime.Serialization.CodeGenerator.If () inline package
Definition at line 375 of file CodeGenerator.cs.
    {
        InternalIf(negate: false);
    }
References System.Runtime.Serialization.CodeGenerator.InternalIf().
Referenced by System.Runtime.Serialization.CodeGenerator.BeginWhileBody(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.HandleUnexpectedItemInCollection(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.CodeGenerator.IfNotIsEmptyString(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().