Terraria: System.Runtime.Serialization.CodeGenerator.VerifyParameterCount
VerifyParameterCount()
void System.Runtime.Serialization.CodeGenerator.VerifyParameterCount (MethodInfo methodInfo, int expectedCount) inline package
Definition at line 445 of file CodeGenerator.cs.
    {
        if (methodInfo.GetParameters().Length != expectedCount)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ParameterCountMismatch, methodInfo.Name, methodInfo.GetParameters().Length, expectedCount)));
        }
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.Format(), System.SR.ParameterCountMismatch, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), and System.Runtime.Serialization.CodeGenerator.Call().