Terraria: System.Reflection.RuntimeConstructorInfo.Invoke
Invoke() [1/6]
override object System.Reflection.RuntimeConstructorInfo.Invoke (BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture) inline
Definition at line 386 of file RuntimeConstructorInfo.cs.
    {
        INVOCATION_FLAGS invocationFlags = InvocationFlags;
        if ((invocationFlags & (INVOCATION_FLAGS.INVOCATION_FLAGS_NO_INVOKE | INVOCATION_FLAGS.INVOCATION_FLAGS_NO_CTOR_INVOKE | INVOCATION_FLAGS.INVOCATION_FLAGS_CONTAINS_STACK_POINTERS)) != 0)
        {
            ThrowNoInvokeException();
        }
        Signature signature = Signature;
        int num = signature.Arguments.Length;
        int num2 = ((parameters != null) ? parameters.Length : 0);
        if (num != num2)
        {
            throw new TargetParameterCountException(SR.Arg_ParmCnt);
        }
        bool wrapExceptions = (invokeAttr & BindingFlags.DoNotWrapExceptions) == 0;
        StackAllocedArguments stackArgs = default(StackAllocedArguments);
        Span<object> arguments = default(Span<object>);
        if (num2 != 0)
        {
            arguments = CheckArguments(ref stackArgs, parameters, binder, invokeAttr, culture, signature);
        }
        object result = RuntimeMethodHandle.InvokeMethod(null, in arguments, signature, constructor: true, wrapExceptions);
        for (int i = 0; i < arguments.Length; i++)
        {
            parameters[i] = arguments[i];
        }
        return result;
    }
References System.SR.Arg_ParmCnt, System.Reflection.MethodBase.CheckArguments(), System.culture, System.Reflection.RuntimeConstructorInfo.InvocationFlags, System.RuntimeMethodHandle.InvokeMethod(), System.Reflection.RuntimeConstructorInfo.Signature, and System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException().