Terraria: System.Runtime.Serialization.CodeGenerator.New
New()
void System.Runtime.Serialization.CodeGenerator.New (ConstructorInfo constructorInfo) inline package
Definition at line 560 of file CodeGenerator.cs.
    {
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction("Newobj " + constructorInfo.ToString() + " on type " + constructorInfo.DeclaringType.ToString());
        }
        _ilGen.Emit(OpCodes.Newobj, constructorInfo);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), and System.Reflection.Emit.OpCodes.Newobj.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().