Terraria: System.Runtime.Serialization.CodeGenerator.LoadAddress
LoadAddress()
void System.Runtime.Serialization.CodeGenerator.LoadAddress (object obj) inline package
Definition at line 823 of file CodeGenerator.cs.
    {
        if (obj is ArgBuilder)
        {
            LdargAddress((ArgBuilder)obj);
        }
        else if (obj is LocalBuilder)
        {
            LdlocAddress((LocalBuilder)obj);
        }
        else
        {
            Load(obj);
        }
    }
References System.Runtime.Serialization.CodeGenerator.LdargAddress(), System.Runtime.Serialization.CodeGenerator.LdlocAddress(), System.Runtime.Serialization.CodeGenerator.Load(), and System.obj.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.CodeGenerator.LoadDefaultValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.CodeGenerator.LoadThis(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.WrapNullableObject(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection().