Terraria: System.Runtime.Serialization.CodeGenerator.BeginMethod
BeginMethod() [1/3]
void System.Runtime.Serialization.CodeGenerator.BeginMethod (DynamicMethod dynamicMethod, Type delegateType, string methodName, Type[] argTypes, bool allowPrivateMemberAccess) inline package
Definition at line 138 of file CodeGenerator.cs.
    {
        _dynamicMethod = dynamicMethod;
        _ilGen = _dynamicMethod.GetILGenerator();
        _delegateType = delegateType;
        InitILGeneration(methodName, argTypes);
    }
References System.Runtime.Serialization.CodeGenerator._delegateType, System.Runtime.Serialization.CodeGenerator._dynamicMethod, System.Runtime.Serialization.CodeGenerator._ilGen, System.Runtime.Serialization.Dictionary, System.Reflection.Emit.DynamicMethod.GetILGenerator(), and System.Runtime.Serialization.CodeGenerator.InitILGeneration().
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.BeginMethod(), System.Runtime.Serialization.CodeGenerator.BeginMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateClassWriter(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReaderHelper(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter().