Terraria: System.Runtime.Serialization.CodeGenerator.DeclareLocal
DeclareLocal() [3/3]
LocalBuilder System.Runtime.Serialization.CodeGenerator.DeclareLocal (Type type, string name, object initialValue) inline package
Definition at line 217 of file CodeGenerator.cs.
    {
        LocalBuilder localBuilder = DeclareLocal(type, name);
        Load(initialValue);
        Store(localBuilder);
        return localBuilder;
    }
References System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.CodeGenerator.Load(), System.Runtime.Serialization.CodeGenerator.Store(), and System.type.
Referenced by System.Runtime.Serialization.BitFlagsGenerator.BitFlagsGenerator(), System.Runtime.Serialization.CodeGenerator.CallStringFormat(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.BitFlagsGenerator.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Runtime.Serialization.CodeGenerator.LoadDefaultValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadClass(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().