Terraria: System.Runtime.Serialization.CodeGenerator.MarkLabel
MarkLabel()
void System.Runtime.Serialization.CodeGenerator.MarkLabel (Label label) inline package
Definition at line 1286 of file CodeGenerator.cs.
    {
        _ilGen.MarkLabel(label);
        if (_codeGenTrace != 0)
        {
            EmitSourceLabel(label.GetHashCode() + ":");
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Runtime.Serialization.CodeGenerator.EmitSourceLabel(), and System.Reflection.Emit.ILGenerator.MarkLabel().
Referenced by System.Runtime.Serialization.CodeGenerator.BeginWhileCondition(), System.Runtime.Serialization.CodeGenerator.Case(), System.Runtime.Serialization.CodeGenerator.Else(), System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndForEach(), System.Runtime.Serialization.CodeGenerator.EndIf(), System.Runtime.Serialization.CodeGenerator.EndMethod(), System.Runtime.Serialization.CodeGenerator.EndSwitch(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.CodeGenerator.ForEach(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject().