Terraria: System.Runtime.Serialization.CodeGenerator.StoreArrayElement
StoreArrayElement()
void System.Runtime.Serialization.CodeGenerator.StoreArrayElement (object obj, object arrayIndex, object value) inline package
Definition at line 604 of file CodeGenerator.cs.
    {
        Type variableType = GetVariableType(obj);
        if (variableType == Globals.TypeOfArray)
        {
            Call(obj, ArraySetValue, value, arrayIndex);
            return;
        }
        Type elementType = variableType.GetElementType();
        Load(obj);
        Load(arrayIndex);
        if (IsStruct(elementType))
        {
            Ldelema(elementType);
        }
        Load(value);
        ConvertValue(GetVariableType(value), elementType);
        if (IsStruct(elementType))
        {
            Stobj(elementType);
        }
        else
        {
            Stelem(elementType);
        }
    }
References System.arrayIndex, System.Runtime.Serialization.CodeGenerator.ArraySetValue, System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.elementType, System.Runtime.Serialization.CodeGenerator.GetVariableType(), System.Runtime.Serialization.CodeGenerator.IsStruct(), System.Reflection.Emit.Ldelema, System.Runtime.Serialization.CodeGenerator.Load(), System.obj, System.Reflection.Emit.Stelem, System.Reflection.Emit.Stobj, System.Runtime.Serialization.Globals.TypeOfArray, and System.value.
Referenced by System.Runtime.Serialization.CodeGenerator.CallStringFormat(), System.Runtime.Serialization.BitFlagsGenerator.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), and System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection().