Terraria: System.Runtime.Serialization.CodeGenerator.LoadParam
LoadParam()
void System.Runtime.Serialization.CodeGenerator.LoadParam (object arg, int oneBasedArgIndex, MethodBase methodInfo) inline private
Definition at line 1412 of file CodeGenerator.cs.
    {
        Load(arg);
        if (arg != null)
        {
            ConvertValue(GetVariableType(arg), methodInfo.GetParameters()[oneBasedArgIndex - 1].ParameterType);
        }
    }
References System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.GetVariableType(), and System.Runtime.Serialization.CodeGenerator.Load().
Referenced by System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), System.Runtime.Serialization.CodeGenerator.Call(), and System.Runtime.Serialization.CodeGenerator.Call().