Terraria: System.Runtime.Serialization.CodeGenerator.LoadMember
LoadMember()
Type System.Runtime.Serialization.CodeGenerator.LoadMember (MemberInfo memberInfo) inline package
Definition at line 640 of file CodeGenerator.cs.
    {
        Type type = null;
        if (memberInfo is FieldInfo)
        {
            FieldInfo fieldInfo = (FieldInfo)memberInfo;
            type = fieldInfo.FieldType;
            if (fieldInfo.IsStatic)
            {
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction("Ldsfld " + fieldInfo?.ToString() + " on type " + fieldInfo.DeclaringType);
                }
                _ilGen.Emit(OpCodes.Ldsfld, fieldInfo);
            }
            else
            {
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction("Ldfld " + fieldInfo?.ToString() + " on type " + fieldInfo.DeclaringType);
                }
                _ilGen.Emit(OpCodes.Ldfld, fieldInfo);
            }
        }
        else if (memberInfo is PropertyInfo propertyInfo)
        {
            type = propertyInfo.PropertyType;
            if (propertyInfo != null)
            {
                MethodInfo getMethod = propertyInfo.GetMethod;
                if (getMethod == null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.NoGetMethodForProperty, propertyInfo.DeclaringType, propertyInfo)));
                }
                Call(getMethod);
            }
        }
        else
        {
            if (!(memberInfo is MethodInfo))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.CannotLoadMemberType, "Unknown", memberInfo.DeclaringType, memberInfo.Name)));
            }
            MethodInfo methodInfo = (MethodInfo)memberInfo;
            type = methodInfo.ReturnType;
            Call(methodInfo);
        }
        EmitStackTop(type);
        return type;
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.Call, System.SR.CannotLoadMemberType, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.Runtime.Serialization.CodeGenerator.EmitStackTop(), System.SR.Format(), System.Reflection.Emit.OpCodes.Ldfld, System.Reflection.Emit.OpCodes.Ldsfld, System.SR.NoGetMethodForProperty, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.ToString, and System.type.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.LoadMemberValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.StoreCollectionValue(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.ThrowIfCannotSerializeReadOnlyTypes(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers().