Terraria: System.Runtime.Serialization.CodeGenerator.InternalConvert
InternalConvert()
void System.Runtime.Serialization.CodeGenerator.InternalConvert (Type source, Type target, bool isAddress) inline private
Definition at line 1457 of file CodeGenerator.cs.
    {
        if (target == source)
        {
            return;
        }
        if (target.IsValueType)
        {
            if (source.IsValueType)
            {
                OpCode convOpCode = GetConvOpCode(target.GetTypeCode());
                if (convOpCode.Equals(OpCodes.Nop))
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.NoConversionPossibleTo, DataContract.GetClrTypeFullName(target))));
                }
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction(convOpCode.ToString());
                }
                _ilGen.Emit(convOpCode);
            }
            else
            {
                if (!source.IsAssignableFrom(target))
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.IsNotAssignableFrom, DataContract.GetClrTypeFullName(target), DataContract.GetClrTypeFullName(source))));
                }
                Unbox(target);
                if (!isAddress)
                {
                    Ldobj(target);
                }
            }
        }
        else if (target.IsAssignableFrom(source))
        {
            if (source.IsValueType)
            {
                if (isAddress)
                {
                    Ldobj(source);
                }
                Box(source);
            }
        }
        else if (source.IsAssignableFrom(target))
        {
            Castclass(target);
        }
        else
        {
            if (!target.IsInterface && !source.IsInterface)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.IsNotAssignableFrom, DataContract.GetClrTypeFullName(target), DataContract.GetClrTypeFullName(source))));
            }
            Castclass(target);
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.Box, System.Reflection.Emit.Castclass, System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.CodeGenerator.GetConvOpCode(), System.Type.GetTypeCode(), System.Type.IsAssignableFrom(), System.Type.IsInterface, System.SR.IsNotAssignableFrom, System.Type.IsValueType, System.Reflection.Emit.Ldobj, System.SR.NoConversionPossibleTo, System.Reflection.Emit.OpCodes.Nop, System.source, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Reflection.Emit.Unbox.
Referenced by System.Runtime.Serialization.CodeGenerator.ConvertAddress(), and System.Runtime.Serialization.CodeGenerator.ConvertValue().