Terraria: System.Runtime.Serialization.CodeGenerator.InitObj
InitObj()
void System.Runtime.Serialization.CodeGenerator.InitObj (Type valueType) inline package
Definition at line 569 of file CodeGenerator.cs.
    {
        if (_codeGenTrace != 0)
        {
            EmitSourceInstruction("Initobj " + valueType);
        }
        _ilGen.Emit(OpCodes.Initobj, valueType);
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), and System.Reflection.Emit.OpCodes.Initobj.
Referenced by System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.CreateObject(), System.Runtime.Serialization.CodeGenerator.LoadDefaultValue(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), and System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject().