Terraria: System.Runtime.Serialization.CodeGenerator.Ldobj
Ldobj()
void System.Runtime.Serialization.CodeGenerator.Ldobj (Type type) inline package
Definition at line 897 of file CodeGenerator.cs.
    {
        OpCode ldindOpCode = GetLdindOpCode(type.GetTypeCode());
        if (!ldindOpCode.Equals(OpCodes.Nop))
        {
            if (_codeGenTrace != 0)
            {
                EmitSourceInstruction(ldindOpCode.ToString());
            }
            _ilGen.Emit(ldindOpCode);
        }
        else
        {
            if (_codeGenTrace != 0)
            {
                EmitSourceInstruction("Ldobj " + type);
            }
            _ilGen.Emit(OpCodes.Ldobj, type);
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.Runtime.Serialization.CodeGenerator.GetLdindOpCode(), System.Reflection.Emit.OpCodes.Ldobj, System.Reflection.Emit.OpCodes.Nop, and System.type.