Terraria: System.Reflection.RuntimeConstructorInfo.Invoke
Invoke() [3/6]
override object System.Reflection.RuntimeConstructorInfo.Invoke (object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture) inline
Definition at line 330 of file RuntimeConstructorInfo.cs.
    {
        INVOCATION_FLAGS invocationFlags = InvocationFlags;
        if ((invocationFlags & INVOCATION_FLAGS.INVOCATION_FLAGS_NO_INVOKE) != 0)
        {
            ThrowNoInvokeException();
        }
        CheckConsistency(obj);
        if ((invocationFlags & INVOCATION_FLAGS.INVOCATION_FLAGS_RUN_CLASS_CONSTRUCTOR) != 0)
        {
            Type declaringType = DeclaringType;
            if (declaringType != null)
            {
                RuntimeHelpers.RunClassConstructor(declaringType.TypeHandle);
            }
            else
            {
                RuntimeHelpers.RunModuleConstructor(Module.ModuleHandle);
            }
            return null;
        }
        Signature signature = Signature;
        int num = signature.Arguments.Length;
        int num2 = ((parameters != null) ? parameters.Length : 0);
        if (num != num2)
        {
            throw new TargetParameterCountException(SR.Arg_ParmCnt);
        }
        bool wrapExceptions = (invokeAttr & BindingFlags.DoNotWrapExceptions) == 0;
        StackAllocedArguments stackArgs = default(StackAllocedArguments);
        Span<object> arguments = default(Span<object>);
        if (num2 != 0)
        {
            arguments = CheckArguments(ref stackArgs, parameters, binder, invokeAttr, culture, signature);
        }
        object result = RuntimeMethodHandle.InvokeMethod(obj, in arguments, signature, constructor: false, wrapExceptions);
        for (int i = 0; i < arguments.Length; i++)
        {
            parameters[i] = arguments[i];
        }
        return result;
    }
References System.SR.Arg_ParmCnt, System.Reflection.MethodBase.CheckArguments(), System.Reflection.RuntimeConstructorInfo.CheckConsistency(), System.culture, System.Reflection.RuntimeConstructorInfo.DeclaringType, System.Reflection.RuntimeConstructorInfo.InvocationFlags, System.RuntimeMethodHandle.InvokeMethod(), System.Reflection.Module.ModuleHandle, System.obj, System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(), System.Runtime.CompilerServices.RuntimeHelpers.RunModuleConstructor(), System.Reflection.RuntimeConstructorInfo.Signature, and System.Reflection.RuntimeConstructorInfo.ThrowNoInvokeException().