Terraria: System.Runtime.Serialization.CodeGenerator.ForEach
ForEach()
void System.Runtime.Serialization.CodeGenerator.ForEach (LocalBuilder local, Type elementType, Type enumeratorType, LocalBuilder enumerator, MethodInfo getCurrentMethod) inline package
Definition at line 325 of file CodeGenerator.cs.
    {
        ForState forState = new ForState(local, DefineLabel(), DefineLabel(), enumerator);
        Br(forState.TestLabel);
        MarkLabel(forState.BeginLabel);
        Call(enumerator, getCurrentMethod);
        ConvertValue(elementType, GetVariableType(local));
        Stloc(local);
        _blockStack.Push(forState);
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Br, System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.ConvertValue(), System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.elementType, System.Runtime.Serialization.CodeGenerator.GetVariableType(), System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.Collections.Generic.Stack< T >.Push(), and System.Reflection.Emit.Stloc.
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().