Terraria: System.Runtime.Serialization.CodeGenerator.ThrowMismatchException
ThrowMismatchException()
void System.Runtime.Serialization.CodeGenerator.ThrowMismatchException (object expected) inline private
Definition at line 1528 of file CodeGenerator.cs.
    {
        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlObjectSerializer.CreateSerializationException(System.SR.Format(System.SR.ExpectingEnd, expected.ToString())));
    }
References System.Runtime.Serialization.XmlObjectSerializer.CreateSerializationException(), System.SR.ExpectingEnd, System.SR.Format(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.CodeGenerator.EndCase(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.EndForEach(), System.Runtime.Serialization.CodeGenerator.EndSwitch(), and System.Runtime.Serialization.CodeGenerator.PopIfState().