Terraria: System.Runtime.Serialization.CodeGenerator.Load
Load()
void System.Runtime.Serialization.CodeGenerator.Load (object obj) inline package
Definition at line 776 of file CodeGenerator.cs.
    {
        if (obj == null)
        {
            if (_codeGenTrace != 0)
            {
                EmitSourceInstruction("Ldnull");
            }
            _ilGen.Emit(OpCodes.Ldnull);
        }
        else if (obj is ArgBuilder)
        {
            Ldarg((ArgBuilder)obj);
        }
        else if (obj is LocalBuilder)
        {
            Ldloc((LocalBuilder)obj);
        }
        else
        {
            Ldc(obj);
        }
    }
References System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), System.Reflection.Emit.Ldarg, System.Runtime.Serialization.CodeGenerator.Ldc(), System.Reflection.Emit.Ldloc, System.Reflection.Emit.OpCodes.Ldnull, and System.obj.
Referenced by System.Runtime.Serialization.CodeGenerator.CallStringFormat(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.CheckRequiredElements(), System.Runtime.Serialization.CodeGenerator.Dec(), System.Runtime.Serialization.CodeGenerator.DeclareLocal(), System.Runtime.Serialization.CodeGenerator.ElseIf(), System.Runtime.Serialization.CodeGenerator.ElseIfIsEmptyString(), System.Runtime.Serialization.CodeGenerator.EndFor(), System.Runtime.Serialization.CodeGenerator.For(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateCollectionReader(), System.Runtime.Serialization.CodeGenerator.If(), System.Runtime.Serialization.CodeGenerator.IfNotDefaultValue(), System.Runtime.Serialization.CodeGenerator.IfNotIsEmptyString(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InitArgs(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InternalDeserialize(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InternalSerialize(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeFactoryMethod(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserialized(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.InvokeOnDeserializing(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerialized(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.InvokeOnSerializing(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.IsEndElement(), System.Runtime.Serialization.BitFlagsGenerator.Load(), System.Runtime.Serialization.CodeGenerator.LoadAddress(), System.Runtime.Serialization.BitFlagsGenerator.LoadArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.LoadArray(), System.Runtime.Serialization.CodeGenerator.LoadArrayElement(), System.Runtime.Serialization.CodeGenerator.LoadDefaultValue(), System.Runtime.Serialization.CodeGenerator.LoadParam(), System.Runtime.Serialization.CodeGenerator.NewArray(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadCollectionItem(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadGetOnlyCollection(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadMembers(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadSimpleDictionary(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadValue(), System.Runtime.Serialization.CodeGenerator.Set(), System.Runtime.Serialization.BitFlagsGenerator.Store(), System.Runtime.Serialization.CodeGenerator.StoreArrayElement(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.ThrowIfCannotSerializeReadOnlyTypes(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.ThrowSerializationException(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ThrowValidationException(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.TryReadPrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitive(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.TryWritePrimitiveArray(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.UnwrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.WrapNullableObject(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteClass(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteMembers(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteStartElement(), System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteStartElement(), System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteValue(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteValue().