Terraria: System.Runtime.Serialization.CodeGenerator.InternalBreakFor
InternalBreakFor()
void System.Runtime.Serialization.CodeGenerator.InternalBreakFor (object userForState, OpCode branchInstruction) inline package
Definition at line 304 of file CodeGenerator.cs.
    {
        foreach (object item in _blockStack)
        {
            if (item is ForState forState && forState == userForState)
            {
                if (!forState.RequiresEndLabel)
                {
                    forState.EndLabel = DefineLabel();
                    forState.RequiresEndLabel = true;
                }
                if (_codeGenTrace != 0)
                {
                    EmitSourceInstruction(branchInstruction.ToString() + " " + forState.EndLabel.GetHashCode());
                }
                _ilGen.Emit(branchInstruction, forState.EndLabel);
                break;
            }
        }
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Runtime.Serialization.CodeGenerator._codeGenTrace, System.Runtime.Serialization.CodeGenerator._ilGen, System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, System.Reflection.Emit.ILGenerator.Emit(), System.Runtime.Serialization.CodeGenerator.EmitSourceInstruction(), and System.item.
Referenced by System.Runtime.Serialization.CodeGenerator.Break(), and System.Runtime.Serialization.CodeGenerator.IfFalseBreak().