Terraria: System.Runtime.Serialization.CodeGenerator.EndForEach
EndForEach()
void System.Runtime.Serialization.CodeGenerator.EndForEach (MethodInfo moveNextMethod) inline package
Definition at line 336 of file CodeGenerator.cs.
    {
        object obj = _blockStack.Pop();
        ForState forState = obj as ForState;
        if (forState == null)
        {
            ThrowMismatchException(obj);
        }
        MarkLabel(forState.TestLabel);
        object end = forState.End;
        Call(end, moveNextMethod);
        Brtrue(forState.BeginLabel);
        if (forState.RequiresEndLabel)
        {
            MarkLabel(forState.EndLabel);
        }
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Brtrue, System.Reflection.Emit.Call, System.Runtime.Serialization.CodeGenerator.MarkLabel(), System.obj, System.Collections.Generic.Stack< T >.Pop(), and System.Runtime.Serialization.CodeGenerator.ThrowMismatchException().
Referenced by System.Runtime.Serialization.Json.JsonFormatWriterGenerator.CriticalHelper.WriteCollection(), and System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.WriteCollection().