Terraria: System.Runtime.Serialization.CodeGenerator.InternalIf
InternalIf()
void System.Runtime.Serialization.CodeGenerator.InternalIf (bool negate) inline private
Definition at line 1421 of file CodeGenerator.cs.
    {
        IfState ifState = new IfState();
        ifState.EndIf = DefineLabel();
        ifState.ElseBegin = DefineLabel();
        if (negate)
        {
            Brtrue(ifState.ElseBegin);
        }
        else
        {
            Brfalse(ifState.ElseBegin);
        }
        _blockStack.Push(ifState);
    }
References System.Runtime.Serialization.CodeGenerator._blockStack, System.Reflection.Emit.Brfalse, System.Reflection.Emit.Brtrue, System.Runtime.Serialization.CodeGenerator.DefineLabel(), System.Runtime.Serialization.Dictionary, and System.Collections.Generic.Stack< T >.Push().
Referenced by System.Runtime.Serialization.CodeGenerator.If(), and System.Runtime.Serialization.CodeGenerator.IfNot().