Terraria: System.Xml.Xsl.Qil.QilPatternVisitor.NoReplace
NoReplace()
virtual QilNode System.Xml.Xsl.Qil.QilPatternVisitor.NoReplace (QilNode node) inline protected virtual
Reimplemented in System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.
Definition at line 74 of file QilPatternVisitor.cs.
    {
        return node;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilPatternVisitor.VisitActualParameterList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAdd(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAfter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAncestor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAncestorOrSelf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAnd(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAttribute(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAttributeCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitAverage(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitBefore(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitBranchList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitChoice(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitCommentCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitConditional(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitContent(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDataSource(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDeref(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDescendant(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDescendantOrSelf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDifference(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDivide(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitDocumentCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitElementCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitEq(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitError(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFalse(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFilter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFollowingSibling(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFormalParameterList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitForReference(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFunction(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFunctionList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitFunctionReference(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitGe(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitGlobalParameterList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitGlobalVariableList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitGt(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitIntersection(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitInvoke(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitIs(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitIsEmpty(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitIsType(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLe(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLength(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLet(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLetReference(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralDecimal(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralDouble(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralInt32(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralInt64(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralObject(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralQName(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralString(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLiteralType(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLocalNameOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLoop(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitLt(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitMaximum(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitMinimum(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitModulo(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitMultiply(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNameOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNamespaceDecl(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNamespaceUriOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNe(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNegate(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNodeRange(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNop(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitNot(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitOptimizeBarrier(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitOr(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitParameter(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitParameterReference(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitParent(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitPICtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitPositionOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitPreceding(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitPrecedingSibling(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitPrefixOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitQilExpression(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitRawTextCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitRoot(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitRtfCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSequence(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSort(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSortKey(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSortKeyList(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitStrConcat(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitStrLength(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitStrParseQName(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSubtract(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitSum(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitTextCtor(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitTrue(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitTypeAssert(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitUnion(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitUnknown(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitWarning(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXmlContext(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXPathFollowing(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXPathNamespace(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXPathNodeValue(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXPathPreceding(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltConvert(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltCopy(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltCopyOf(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltGenerateId(), System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltInvokeEarlyBound(), and System.Xml.Xsl.Qil.QilPatternVisitor.VisitXsltInvokeLateBound().