Terraria: System.Memory.Slice
Slice() [1/2]
Memory< T > System.Memory< T >.Slice (int start) inline
Definition at line 194 of file Memory.cs.
    {
        if ((uint)start > (uint)_length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.start);
        }
        return new Memory<T>(_object, _index + start, _length - start);
    }
References System.Memory< T >._index, System.Memory< T >._length, System.Memory< T >._object, System.start, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.IO.Compression.InputBuffer.CopyTo(), System.IO.Compression.InputBuffer.EnsureBitsAvailable(), System.Buffers.ReadOnlySequence< T >.GetFirstBufferSlow(), System.Net.WebSockets.ManagedWebSocket.HandleReceivedPingPongAsync(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext(), System.IO.Strategies.BufferedFileStreamStrategy._003CReadAsyncSlowPath_003Ed__39.MoveNext(), and System.IO.Compression.InputBuffer.TryLoad16Bits().