Terraria: CreativeUI.GetSacrificeNumbers
GetSacrificeNumbers()
bool CreativeUI.GetSacrificeNumbers (out int itemIdChecked, out int amountWeHave, out int amountNeededTotal) inline
     {
         amountWeHave = 0;
         amountNeededTotal = 0;
         itemIdChecked = 0;
         Item item = _itemSlotsForUI[0];
         if (!item.IsAir)
         {
             itemIdChecked = item.type;
         }
         if (!Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out amountWeHave, out amountNeededTotal))
         {
             return false;
         }
         return true;
     }
References _itemSlotsForUI, Item.IsAir, CreativeUnlocksTracker.ItemSacrifices, Main.LocalPlayerCreativeTracker, ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers(), and Item.type.
Referenced by UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate(), and UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan().