Terraria: CreativeUI.Draw
Draw()
void CreativeUI.Draw (SpriteBatch spriteBatch) inline
     {
         if (!_initialized)
         {
             Initialize();
         }
         if (Main.LocalPlayer.difficulty != 3)
         {
             Enabled = false;
         }
         else if (!Blocked)
         {
             Vector2 location = new Vector2(28f, 267f);
             Vector2 vector = new Vector2(353f, 258f);
             new Vector2(40f, 267f);
             _ = vector + new Vector2(50f, 50f);
             if (Main.screenHeight < 650 && Enabled)
             {
                 location.X += 52f * Main.inventoryScale;
             }
             DrawToggleButton(spriteBatch, location);
             if (Enabled)
             {
                 _powersUI.Draw(spriteBatch, Main.gameTimeCache);
             }
         }
     }
References _initialized, _powersUI, Blocked, Player.difficulty, UserInterface.Draw(), DrawToggleButton(), Enabled, Main.gameTimeCache, Initialize(), Main.inventoryScale, Main.LocalPlayer, and Main.screenHeight.
Referenced by Main.DrawInventory().