Terraria: CreativeUI.ShouldDrawSacrificeArea
ShouldDrawSacrificeArea()
bool CreativeUI.ShouldDrawSacrificeArea () inline
     {
         if (!_itemSlotsForUI[0].IsAir)
         {
             return true;
         }
         Item mouseItem = Main.mouseItem;
         if (mouseItem.IsAir)
         {
             return false;
         }
         if (!CreativeItemSacrificesCatalog.Instance.TryGetSacrificeCountCapToUnlockInfiniteItems(mouseItem.type, out var amountNeeded))
         {
             return false;
         }
         if (Main.LocalPlayerCreativeTracker.ItemSacrifices.GetSacrificeCount(mouseItem.type) < amountNeeded)
         {
             return true;
         }
         return false;
     }
References _itemSlotsForUI, ItemsSacrificedUnlocksTracker.GetSacrificeCount(), CreativeItemSacrificesCatalog.Instance, Item.IsAir, CreativeUnlocksTracker.ItemSacrifices, Main.LocalPlayerCreativeTracker, Main.mouseItem, CreativeItemSacrificesCatalog.TryGetSacrificeCountCapToUnlockInfiniteItems(), and Item.type.
Referenced by UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate().