Terraria: CreativeUI.ToggleMenu
ToggleMenu()
void CreativeUI.ToggleMenu () inline
     {
         Enabled = !Enabled;
         _powersUI.EscapeElements();
         UISliderBase.EscapeElements();
         SoundEngine.PlaySound(12);
         if (Enabled)
         {
             Recipe.FindRecipes();
             Main.LocalPlayer.tileEntityAnchor.Clear();
             RefreshAvailableInfiniteItemsList();
         }
         else if (_itemSlotsForUI[0].stack > 0)
         {
             _itemSlotsForUI[0] = Main.LocalPlayer.GetItem(Main.myPlayer, _itemSlotsForUI[0], GetItemSettings.InventoryUIToInventorySettings);
             StopPlayingSacrificeAnimations();
         }
     }
References _itemSlotsForUI, _powersUI, PlayerInteractionAnchor.Clear(), Enabled, UISliderBase.EscapeElements(), UserInterface.EscapeElements(), Recipe.FindRecipes(), Player.GetItem(), GetItemSettings.InventoryUIToInventorySettings, Main.LocalPlayer, Main.myPlayer, SoundEngine.PlaySound(), RefreshAvailableInfiniteItemsList(), StopPlayingSacrificeAnimations(), and Player.tileEntityAnchor.
Referenced by DrawToggleButton(), UICreativeInfiniteItemsDisplay.EscapeVirtualKeyboard(), UICreativeInfiniteItemsDisplay.GoBackHere(), and Player.ToggleCreativeMenu().