Terraria: CreativeUI.SacrificeItem
SacrificeItem()
ItemSacrificeResult CreativeUI.SacrificeItem (out int amountWeSacrificed) inline
     {
         int amountNeededTotal = 0;
         int amountWeHave = 0;
         amountWeSacrificed = 0;
         Item item = _itemSlotsForUI[0];
         if (!Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out amountWeHave, out amountNeededTotal))
         {
             return ItemSacrificeResult.CannotSacrifice;
         }
         int num = Utils.Clamp(amountNeededTotal - amountWeHave, 0, amountNeededTotal);
         if (num == 0)
         {
             return ItemSacrificeResult.CannotSacrifice;
         }
         int num2 = Math.Min(num, item.stack);
         if (!Main.ServerSideCharacter)
         {
             Main.LocalPlayerCreativeTracker.ItemSacrifices.RegisterItemSacrifice(item.type, num2);
         }
         else
         {
             NetPacket packet = NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(item.type, num2);
             NetManager.Instance.SendToServerOrLoopback(packet);
         }
         bool num3 = num2 == num;
         item.stack -= num2;
         if (item.stack <= 0)
         {
             item.TurnToAir();
         }
         amountWeSacrificed = num2;
         RefreshAvailableInfiniteItemsList();
         if (item.stack > 0)
         {
             item.position.X = Main.player[Main.myPlayer].Center.X - (float)(item.width / 2);
             item.position.Y = Main.player[Main.myPlayer].Center.Y - (float)(item.height / 2);
             _itemSlotsForUI[0] = Main.LocalPlayer.GetItem(Main.myPlayer, item, GetItemSettings.InventoryUIToInventorySettings);
         }
         if (!num3)
         {
             return ItemSacrificeResult.SacrificedButNotDone;
         }
         return ItemSacrificeResult.SacrificedAndDone;
     }
References _itemSlotsForUI, Entity.Center, Player.GetItem(), Entity.height, NetManager.Instance, GetItemSettings.InventoryUIToInventorySettings, CreativeUnlocksTracker.ItemSacrifices, Main.LocalPlayer, Main.LocalPlayerCreativeTracker, Main.myPlayer, Main.player, Entity.position, RefreshAvailableInfiniteItemsList(), ItemsSacrificedUnlocksTracker.RegisterItemSacrifice(), NetManager.SendToServerOrLoopback(), NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), Main.ServerSideCharacter, Item.stack, ItemsSacrificedUnlocksTracker.TryGetSacrificeNumbers(), Item.TurnToAir(), Item.type, and Entity.width.
Referenced by UICreativeInfiniteItemsDisplay.SacrificeWhatYouCan().