Terraria: CreativeUI.CloseMenu
CloseMenu()
void CreativeUI.CloseMenu () inline
     {
         Enabled = false;
         if (_itemSlotsForUI[0].stack > 0)
         {
             _itemSlotsForUI[0] = Main.LocalPlayer.GetItem(Main.myPlayer, _itemSlotsForUI[0], GetItemSettings.InventoryUIToInventorySettings);
         }
         StopPlayingSacrificeAnimations();
     }
References _itemSlotsForUI, Enabled, Player.GetItem(), GetItemSettings.InventoryUIToInventorySettings, Main.LocalPlayer, Main.myPlayer, and StopPlayingSacrificeAnimations().
Referenced by Main.DrawInterface_27_Inventory(), and TileEntity.SetInteractionAnchor().