Terraria: System.Reflection.Metadata.BlobHandle.FromOffset
FromOffset()
static BlobHandle System.Reflection.Metadata.BlobHandle.FromOffset (int heapOffset) inline static package
Definition at line 34 of file BlobHandle.cs.
    {
        return new BlobHandle((uint)heapOffset);
    }
References System.Reflection.Metadata.BlobHandle.BlobHandle().
Referenced by System.Reflection.Metadata.Ecma335.MetadataTokens.BlobHandle(), System.Reflection.Metadata.Ecma335.DocumentTableReader.GetHash(), System.Reflection.Metadata.Ecma335.FileTableReader.GetHashValue(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetHashValue(), System.Reflection.Metadata.Ecma335.ImportScopeTableReader.GetImports(), System.Reflection.Metadata.Ecma335.MethodSpecTableReader.GetInstantiation(), System.Reflection.Metadata.Ecma335.FieldMarshalTableReader.GetNativeType(), System.Reflection.Metadata.Ecma335.BlobHeap.GetNextHandle(), System.Reflection.Metadata.Ecma335.MetadataBuilder.GetOrAddBlob(), System.Reflection.Metadata.Ecma335.DeclSecurityTableReader.GetPermissionSet(), System.Reflection.Metadata.Ecma335.AssemblyTableReader.GetPublicKey(), System.Reflection.Metadata.Ecma335.AssemblyRefTableReader.GetPublicKeyOrToken(), System.Reflection.Metadata.Ecma335.MethodDebugInformationTableReader.GetSequencePoints(), System.Reflection.Metadata.Ecma335.FieldTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.StandAloneSigTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.LocalConstantTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.MemberRefTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.MethodTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.PropertyTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.TypeSpecTableReader.GetSignature(), System.Reflection.Metadata.Ecma335.ConstantTableReader.GetValue(), System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetValue(), System.Reflection.Metadata.Ecma335.CustomDebugInformationTableReader.GetValue(), System.Reflection.Metadata.DocumentNameBlobHandle.operator BlobHandle(), and System.Reflection.Metadata.BlobReader.ReadBlobHandle().