Terraria: System.IFormatProvider.GetFormat
GetFormat()
object? System.IFormatProvider.GetFormat (Type? formatType) inherited
Implemented in System.Globalization.CultureInfo, and System.Globalization.NumberFormatInfo.
Referenced by System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendCustomFormatter< T >(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendCustomFormatter< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendCustomFormatter< T >(), System.ComponentModel.DateTimeConverter.ConvertFrom(), System.ComponentModel.DateTimeOffsetConverter.ConvertFrom(), System.ComponentModel.DateTimeConverter.ConvertTo(), System.ComponentModel.DateTimeOffsetConverter.ConvertTo(), System.Globalization.NumberFormatInfo.GetInstance(), and System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.HasCustomFormatter().