Terraria: Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1
EmitGolfballExplosion_v1()
static void Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1 (Vector2 Center) inline static
Definition at line 245 of file GolfHelper.cs.
        {
            for (float num = 0f; num < 1f; num += 0.085f)
            {
                Dust dust = Dust.NewDustPerfect(Center, 278, (num * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(2f, 0.5f));
                dust.fadeIn = 1.2f;
                dust.noGravity = true;
                dust.velocity.X *= 0.7f;
                dust.velocity.Y -= 1.5f;
                dust.position.Y += 8f;
                dust.color = Color.Lerp(Color.Silver, Color.White, 0.5f);
            }
            for (float num2 = 0f; num2 < 1f; num2 += 0.2f)
            {
                Dust dust2 = Dust.NewDustPerfect(Center, 278, (num2 * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(1f, 0.5f));
                dust2.fadeIn = 1.2f;
                dust2.noGravity = true;
                dust2.velocity.X *= 0.7f;
                dust2.velocity.Y -= 0.5f;
                dust2.position.Y += 8f;
                dust2.color = Color.Lerp(Color.Silver, Color.White, 0.5f);
            }
            float num3 = Main.rand.NextFloatDirection();
            for (float num4 = 0f; num4 < 1f; num4 += 0.15f)
            {
                Dust dust3 = Dust.NewDustPerfect(Center, 278, (num3 + num4 * ((float)Math.PI * 2f)).ToRotationVector2() * 4f);
                dust3.fadeIn = 1.5f;
                dust3.velocity *= 0.5f + num4 * 0.8f;
                dust3.noGravity = true;
                dust3.velocity.X *= 0.35f;
                dust3.velocity.Y *= 2f;
                dust3.velocity.Y -= 1f;
                dust3.velocity.Y = 0f - Math.Abs(dust3.velocity.Y);
                dust3.position += dust3.velocity * 3f;
                dust3.color = Color.Lerp(Color.Silver, Color.White, 0.5f);
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Dust.NewDustPerfect(), System.Math.PI, Terraria.Main.rand, Microsoft.Xna.Framework.Color.Silver, Terraria.Dust.velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Y.