Terraria: System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessMessagesLoopCore
ProcessMessagesLoopCore()
void System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessMessagesLoopCore () inline private
Definition at line 263 of file JoinBlockTargetSharedResources.cs.
    {
        try
        {
            int num = 0;
            int actualMaxMessagesPerTask = _dataflowBlockOptions.ActualMaxMessagesPerTask;
            bool flag;
            do
            {
                flag = ((!_dataflowBlockOptions.Greedy) ? RetrievePostponedItemsNonGreedy() : RetrievePostponedItemsGreedyBounded());
                if (flag)
                {
                    lock (IncomingLock)
                    {
                        if (AllTargetsHaveAtLeastOneMessage)
{
                            _joinFilledAction();
                            _joinsCreated++;
                            if (!_dataflowBlockOptions.Greedy && _boundingState != null)
{
                                _boundingState.CurrentCount++;
                            }
                        }
                    }
                }
                num++;
            }
            while (flag && num < actualMaxMessagesPerTask);
        }
        catch (Exception exception)
        {
            _targets[0].CompleteCore(exception, dropPendingMessages: true, releaseReservedMessages: true);
        }
        finally
        {
            lock (IncomingLock)
            {
                _taskForInputProcessing = null;
                ProcessAsyncIfNecessary(isReplacementReplica: true);
                CompleteBlockIfPossible();
            }
        }
    }
References System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._boundingState, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._joinFilledAction, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._joinsCreated, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._targets, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._taskForInputProcessing, System.Threading.Tasks.Dataflow.DataflowBlockOptions.ActualMaxMessagesPerTask, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.AllTargetsHaveAtLeastOneMessage, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetBase.CompleteCore(), System.Threading.Tasks.Dataflow.Internal.BoundingState.CurrentCount, System.exception, System.Threading.Tasks.Dataflow.GroupingDataflowBlockOptions.Greedy, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.IncomingLock, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.RetrievePostponedItemsGreedyBounded(), and System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.RetrievePostponedItemsNonGreedy().