Terraria: Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer
DynamicIndexBuffer() [1/2]
unsafe Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.DynamicIndexBuffer (GraphicsDevice graphicsDevice, Type indexType, int indexCount, BufferUsage usage) inline
Definition at line 41 of file DynamicIndexBuffer.cs.
    {
        try
        {
            if (indexCount <= 0)
            {
                throw new ArgumentOutOfRangeException("indexCount", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
            }
            _parent = graphicsDevice;
            uint indexSize = (uint)Marshal.SizeOf(indexType);
            CreateBuffer((uint)indexCount, indexSize, _003CModule_003E.ConvertXnaBufferUsageToDx(usage) | 0x200u, (_D3DPOOL)0);
            graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 0u, _internalHandle, ref _internalHandle);
            return;
        }
        catch
        {
            //try-fault
            Dispose(true);
            throw;
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CreateBuffer(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose(), Microsoft.Xna.Framework.Graphics.IndexBuffer.pComPtr, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, Microsoft.Xna.Framework.FrameworkResources.ResourcesMustBeGreaterThanZeroSize, and System.Runtime.InteropServices.Marshal.SizeOf().