Terraria: System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary_Slow
ProcessAsyncIfNecessary_Slow()
void System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary_Slow (bool isReplacementReplica) inline private
Definition at line 207 of file JoinBlockTargetSharedResources.cs.
    {
        _taskForInputProcessing = new Task(delegate(object thisSharedResources)
        {
            ((JoinBlockTargetSharedResources)thisSharedResources).ProcessMessagesLoopCore();
        }, this, Common.GetCreationOptionsForTask(isReplacementReplica));
        DataflowEtwProvider log = DataflowEtwProvider.Log;
        if (log.IsEnabled())
        {
            log.TaskLaunchedForMessageHandling(_ownerJoin, _taskForInputProcessing, DataflowEtwProvider.TaskLaunchedReason.ProcessingInputMessages, _targets.Max((JoinBlockTargetBase t) => t.NumberOfMessagesAvailableOrPostponed));
        }
        Exception ex = Common.StartTaskSafe(_taskForInputProcessing, _dataflowBlockOptions.TaskScheduler);
        if (ex != null)
        {
            _exceptionAction(ex);
            _taskForInputProcessing = null;
            CompleteBlockIfPossible();
        }
    }
References System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.JoinBlockTargetSharedResources(), System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._dataflowBlockOptions, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._exceptionAction, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._ownerJoin, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._targets, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources._taskForInputProcessing, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.CompleteBlockIfPossible(), System.Threading.Tasks.Dataflow.Internal.Common.GetCreationOptionsForTask(), System.Threading.Tasks.Dataflow.Internal.DataflowEtwProvider.Log, System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetBase.NumberOfMessagesAvailableOrPostponed, System.Threading.Tasks.Dataflow.Internal.Common.StartTaskSafe(), and System.Threading.Tasks.Dataflow.DataflowBlockOptions.TaskScheduler.
Referenced by System.Threading.Tasks.Dataflow.Internal.JoinBlockTargetSharedResources.ProcessAsyncIfNecessary().