Terraria: EmoteBubble.NewBubble
NewBubble()
static int EmoteBubble.NewBubble (int emoticon, WorldUIAnchor bubbleAnchor, int time) inline static
     {
         if (Main.netMode == 1)
         {
             return -1;
         }
         EmoteBubble emoteBubble = new EmoteBubble(emoticon, bubbleAnchor, time);
         emoteBubble.ID = AssignNewID();
         byID[emoteBubble.ID] = emoteBubble;
         if (Main.netMode == 2)
         {
             Tuple<int, int> tuple = SerializeNetAnchor(bubbleAnchor);
             NetMessage.SendData(91, -1, -1, null, emoteBubble.ID, tuple.Item1, tuple.Item2, time, emoticon);
         }
         OnBubbleChange(emoteBubble.ID);
         return emoteBubble.ID;
     }
References EmoteBubble(), AssignNewID(), byID, ID, Main.netMode, OnBubbleChange(), NetMessage.SendData(), and SerializeNetAnchor().
Referenced by DD2Film.DryadAlertEmote(), DD2Film.DryadConfusedEmote(), NPC.FindFrame(), MessageBuffer.GetData(), MakeLocalPlayerEmote(), EmojiCommand.ProcessOutgoingMessage(), and RockPaperScissorsCommand.ProcessOutgoingMessage().