Terraria: System.Xml.XmlBufferReader.ReadGuid
ReadGuid()
Guid System.Xml.XmlBufferReader.ReadGuid () inline
Definition at line 504 of file XmlBufferReader.cs.
    {
        GetBuffer(16, out var offset);
        Guid guid = GetGuid(offset);
        Advance(16);
        return guid;
    }
References System.Xml.XmlBufferReader.Advance(), System.Xml.XmlBufferReader.GetBuffer(), System.Xml.XmlBufferReader.GetGuid(), and System.offset.