Terraria: System.Xml.XmlBufferReader.ReadList
ReadList()
void System.Xml.XmlBufferReader.ReadList (ValueHandle value) inline private
Definition at line 1310 of file XmlBufferReader.cs.
    {
        if (_listValue == null)
        {
            _listValue = new ValueHandle(this);
        }
        int num = 0;
        int offset = Offset;
        while (true)
        {
            XmlBinaryNodeType nodeType = GetNodeType();
            SkipNodeType();
            if (nodeType == XmlBinaryNodeType.StartListText)
            {
                XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
            }
            if (nodeType == XmlBinaryNodeType.EndListText)
            {
                break;
            }
            ReadValue(nodeType, _listValue);
            num++;
        }
        value.SetValue(ValueHandleType.List, offset, num);
    }
References System.Xml.XmlBufferReader._listValue, System.Xml.XmlBufferReader._reader, System.Xml.XmlBufferReader.GetNodeType(), System.offset, System.Xml.XmlBufferReader.Offset, System.Xml.XmlBufferReader.ReadValue(), System.Xml.XmlBufferReader.SkipNodeType(), System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat(), and System.value.
Referenced by System.Xml.XmlBufferReader.ReadValue().