Terraria: System.Xml.XmlBufferReader.GetBuffer
GetBuffer() [1/3]
byte[] System.Xml.XmlBufferReader.GetBuffer (int count, out int offset) inline
Definition at line 153 of file XmlBufferReader.cs.
    {
        offset = _offset;
        if (offset <= _offsetMax - count)
        {
            return _buffer;
        }
        return GetBufferHard(count, out offset);
    }
References System.Xml.XmlBufferReader._buffer, System.Xml.XmlBufferReader._offset, System.Xml.XmlBufferReader._offsetMax, System.count, System.Xml.XmlBufferReader.GetBufferHard(), and System.offset.
Referenced by System.Xml.XmlBufferReader.ReadDecimal(), System.Xml.XmlBufferReader.ReadDouble(), System.Xml.XmlBufferReader.ReadGuid(), System.Xml.XmlBufferReader.ReadInt32(), System.Xml.XmlBufferReader.ReadSingle(), System.Xml.XmlBufferReader.ReadUInt16(), System.Xml.XmlBufferReader.ReadUniqueId(), System.Xml.XmlBufferReader.ReadUTF8String(), and System.Xml.XmlBufferReader.UnsafeReadArray().