Terraria: System.Xml.XmlBufferReader.ReadValue
ReadValue() [2/2]
void System.Xml.XmlBufferReader.ReadValue (XmlBinaryNodeType nodeType, ValueHandle value) inline
Definition at line 1195 of file XmlBufferReader.cs.
    {
        switch (nodeType)
        {
        case XmlBinaryNodeType.EmptyText:
            value.SetValue(ValueHandleType.Empty);
            break;
        case XmlBinaryNodeType.MinText:
            value.SetValue(ValueHandleType.Zero);
            break;
        case XmlBinaryNodeType.OneText:
            value.SetValue(ValueHandleType.One);
            break;
        case XmlBinaryNodeType.TrueText:
            value.SetValue(ValueHandleType.True);
            break;
        case XmlBinaryNodeType.FalseText:
            value.SetValue(ValueHandleType.False);
            break;
        case XmlBinaryNodeType.BoolText:
            value.SetValue((ReadUInt8() != 0) ? ValueHandleType.True : ValueHandleType.False);
            break;
        case XmlBinaryNodeType.Chars8Text:
            ReadValue(value, ValueHandleType.UTF8, ReadUInt8());
            break;
        case XmlBinaryNodeType.Chars16Text:
            ReadValue(value, ValueHandleType.UTF8, ReadUInt16());
            break;
        case XmlBinaryNodeType.Chars32Text:
            ReadValue(value, ValueHandleType.UTF8, ReadUInt31());
            break;
        case XmlBinaryNodeType.UnicodeChars8Text:
            ReadUnicodeValue(value, ReadUInt8());
            break;
        case XmlBinaryNodeType.UnicodeChars16Text:
            ReadUnicodeValue(value, ReadUInt16());
            break;
        case XmlBinaryNodeType.UnicodeChars32Text:
            ReadUnicodeValue(value, ReadUInt31());
            break;
        case XmlBinaryNodeType.Bytes8Text:
            ReadValue(value, ValueHandleType.Base64, ReadUInt8());
            break;
        case XmlBinaryNodeType.Bytes16Text:
            ReadValue(value, ValueHandleType.Base64, ReadUInt16());
            break;
        case XmlBinaryNodeType.Bytes32Text:
            ReadValue(value, ValueHandleType.Base64, ReadUInt31());
            break;
        case XmlBinaryNodeType.DictionaryText:
            value.SetDictionaryValue(ReadDictionaryKey());
            break;
        case XmlBinaryNodeType.UniqueIdText:
            ReadValue(value, ValueHandleType.UniqueId, 16);
            break;
        case XmlBinaryNodeType.GuidText:
            ReadValue(value, ValueHandleType.Guid, 16);
            break;
        case XmlBinaryNodeType.DecimalText:
            ReadValue(value, ValueHandleType.Decimal, 16);
            break;
        case XmlBinaryNodeType.Int8Text:
            ReadValue(value, ValueHandleType.Int8, 1);
            break;
        case XmlBinaryNodeType.Int16Text:
            ReadValue(value, ValueHandleType.Int16, 2);
            break;
        case XmlBinaryNodeType.Int32Text:
            ReadValue(value, ValueHandleType.Int32, 4);
            break;
        case XmlBinaryNodeType.Int64Text:
            ReadValue(value, ValueHandleType.Int64, 8);
            break;
        case XmlBinaryNodeType.UInt64Text:
            ReadValue(value, ValueHandleType.UInt64, 8);
            break;
        case XmlBinaryNodeType.FloatText:
            ReadValue(value, ValueHandleType.Single, 4);
            break;
        case XmlBinaryNodeType.DoubleText:
            ReadValue(value, ValueHandleType.Double, 8);
            break;
        case XmlBinaryNodeType.TimeSpanText:
            ReadValue(value, ValueHandleType.TimeSpan, 8);
            break;
        case XmlBinaryNodeType.DateTimeText:
            ReadValue(value, ValueHandleType.DateTime, 8);
            break;
        case XmlBinaryNodeType.StartListText:
            ReadList(value);
            break;
        case XmlBinaryNodeType.QNameDictionaryText:
            ReadQName(value);
            break;
        default:
            XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
            break;
        }
    }
References System.Xml.XmlBufferReader._reader, System.Xml.XmlBufferReader.ReadDictionaryKey(), System.Xml.XmlBufferReader.ReadList(), System.Xml.XmlBufferReader.ReadQName(), System.Xml.XmlBufferReader.ReadUInt16(), System.Xml.XmlBufferReader.ReadUInt31(), System.Xml.XmlBufferReader.ReadUInt8(), System.Xml.XmlBufferReader.ReadUnicodeValue(), System.Xml.XmlBufferReader.ReadValue(), System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat(), and System.value.
Referenced by System.Xml.XmlBufferReader.GetList(), System.Xml.XmlBufferReader.ReadList(), System.Xml.XmlBufferReader.ReadUnicodeValue(), and System.Xml.XmlBufferReader.ReadValue().