Terraria: System.Xml.XmlBufferReader.GetEscapedChars
GetEscapedChars()
int System.Xml.XmlBufferReader.GetEscapedChars (int offset, int length, char[] chars) inline
Definition at line 623 of file XmlBufferReader.cs.
    {
        byte[] buffer = _buffer;
        int num = 0;
        int num2 = offset;
        int num3 = offset + length;
        while (true)
        {
            if (offset < num3 && IsAttrChar(buffer[offset]))
            {
                offset++;
                continue;
            }
            num += GetChars(num2, offset - num2, chars, num);
            if (offset == num3)
            {
                break;
            }
            num2 = offset;
            if (buffer[offset] == 38)
            {
                while (offset < num3 && buffer[offset] != 59)
                {
                    offset++;
                }
                offset++;
                int charEntity = GetCharEntity(num2, offset - num2);
                num2 = offset;
                if (charEntity > 65535)
                {
                    SurrogateChar surrogateChar = new SurrogateChar(charEntity);
                    chars[num++] = surrogateChar.HighChar;
                    chars[num++] = surrogateChar.LowChar;
                }
                else
                {
                    chars[num++] = (char)charEntity;
                }
            }
            else if (buffer[offset] == 10 || buffer[offset] == 9)
            {
                chars[num++] = ' ';
                offset++;
                num2 = offset;
            }
            else
            {
                chars[num++] = ' ';
                offset++;
                if (offset < num3 && buffer[offset] == 10)
                {
                    offset++;
                }
                num2 = offset;
            }
        }
        return num;
    }
References System.Xml.XmlBufferReader._buffer, System.buffer, System.chars, System.Xml.XmlBufferReader.GetCharEntity(), System.Xml.XmlBufferReader.GetChars(), System.Xml.XmlBufferReader.IsAttrChar(), System.length, and System.offset.
Referenced by System.Xml.XmlBufferReader.GetEscapedString().