Terraria: System.Xml.XmlBufferReader.GetCharEntity
GetCharEntity()
int System.Xml.XmlBufferReader.GetCharEntity (int offset, int length) inline
Definition at line 789 of file XmlBufferReader.cs.
    {
        if (length < 3)
        {
            XmlExceptionHelper.ThrowInvalidCharRef(_reader);
        }
        byte[] buffer = _buffer;
        switch (buffer[offset + 1])
        {
        case 108:
            return GetLessThanCharEntity(offset, length);
        case 103:
            return GetGreaterThanCharEntity(offset, length);
        case 97:
            if (buffer[offset + 2] == 109)
            {
                return GetAmpersandCharEntity(offset, length);
            }
            return GetApostropheCharEntity(offset, length);
        case 113:
            return GetQuoteCharEntity(offset, length);
        case 35:
            if (buffer[offset + 2] == 120)
            {
                return GetHexCharEntity(offset, length);
            }
            return GetDecimalCharEntity(offset, length);
        default:
            XmlExceptionHelper.ThrowInvalidCharRef(_reader);
            return 0;
        }
    }
References System.Xml.XmlBufferReader._buffer, System.Xml.XmlBufferReader._reader, System.buffer, System.Xml.XmlBufferReader.GetAmpersandCharEntity(), System.Xml.XmlBufferReader.GetApostropheCharEntity(), System.Xml.XmlBufferReader.GetDecimalCharEntity(), System.Xml.XmlBufferReader.GetGreaterThanCharEntity(), System.Xml.XmlBufferReader.GetHexCharEntity(), System.Xml.XmlBufferReader.GetLessThanCharEntity(), System.Xml.XmlBufferReader.GetQuoteCharEntity(), System.length, System.offset, and System.Xml.XmlExceptionHelper.ThrowInvalidCharRef().
Referenced by System.Xml.XmlBufferReader.GetEscapedChars().