Terraria: System.Xml.XmlBufferReader.ReadQName
ReadQName()
void System.Xml.XmlBufferReader.ReadQName (ValueHandle value) inline
Definition at line 1336 of file XmlBufferReader.cs.
    {
        int num = ReadUInt8();
        if (num >= 26)
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
        }
        int key = ReadDictionaryKey();
        value.SetQNameValue(num, key);
    }
References System.Xml.XmlBufferReader._reader, System.key, System.Xml.XmlBufferReader.ReadDictionaryKey(), System.Xml.XmlBufferReader.ReadUInt8(), System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat(), and System.value.
Referenced by System.Xml.XmlBufferReader.ReadValue().