Terraria: System.Xml.XmlBufferReader.TryEnsureBytes
TryEnsureBytes()
bool System.Xml.XmlBufferReader.TryEnsureBytes (int count) inline private
Definition at line 227 of file XmlBufferReader.cs.
    {
        if (_stream == null)
        {
            return false;
        }
        while (true)
        {
            int num = _offset + count;
            if (num <= _offsetMax)
            {
                break;
            }
            if (num > _buffer.Length)
            {
                byte[] array = new byte[Math.Max(256, _buffer.Length * 2)];
                System.Buffer.BlockCopy(_buffer, 0, array, 0, _offsetMax);
                num = Math.Min(num, array.Length);
                _buffer = array;
                _streamBuffer = array;
            }
            int num2 = num - _offsetMax;
            do
            {
                int num3 = _stream.Read(_buffer, _offsetMax, num2);
                if (num3 == 0)
                {
                    return false;
                }
                _offsetMax += num3;
                num2 -= num3;
            }
            while (num2 > 0);
        }
        return true;
    }
References System.Xml.XmlBufferReader._buffer, System.Xml.XmlBufferReader._offset, System.Xml.XmlBufferReader._offsetMax, System.Xml.XmlBufferReader._stream, System.Xml.XmlBufferReader._streamBuffer, System.array, System.Buffer.BlockCopy(), System.count, System.Xml.Dictionary, System.Math.Max(), System.Math.Min(), and System.IO.Stream.Read().
Referenced by System.Xml.XmlBufferReader.EnsureBytes(), System.Xml.XmlBufferReader.GetBuffer(), and System.Xml.XmlBufferReader.TryEnsureByte().