Terraria: System.Xml.XmlBufferReader.TryEnsureByte
TryEnsureByte()
bool System.Xml.XmlBufferReader.TryEnsureByte () inline private
Definition at line 200 of file XmlBufferReader.cs.
    {
        if (_stream == null)
        {
            return false;
        }
        if (_offsetMax >= _buffer.Length)
        {
            return TryEnsureBytes(1);
        }
        int num = _stream.ReadByte();
        if (num == -1)
        {
            return false;
        }
        _buffer[_offsetMax++] = (byte)num;
        return true;
    }
References System.Xml.XmlBufferReader._buffer, System.Xml.XmlBufferReader._offsetMax, System.Xml.XmlBufferReader._stream, System.IO.Stream.ReadByte(), and System.Xml.XmlBufferReader.TryEnsureBytes().
Referenced by System.Xml.XmlBufferReader.EnsureByte().