Terraria: System.Xml.XmlBufferReader.EnsureByte
EnsureByte()
void System.Xml.XmlBufferReader.EnsureByte () inline private
Definition at line 192 of file XmlBufferReader.cs.
    {
        if (!TryEnsureByte())
        {
            XmlExceptionHelper.ThrowUnexpectedEndOfFile(_reader);
        }
    }
References System.Xml.XmlBufferReader._reader, System.Xml.XmlExceptionHelper.ThrowUnexpectedEndOfFile(), and System.Xml.XmlBufferReader.TryEnsureByte().
Referenced by System.Xml.XmlBufferReader.GetByteHard().