Terraria: System.Xml.XmlBufferReader.ReadDictionaryKey
ReadDictionaryKey()
int System.Xml.XmlBufferReader.ReadDictionaryKey () inline
Definition at line 1157 of file XmlBufferReader.cs.
    {
        int num = ReadMultiByteUInt31();
        if (((uint)num & (true ? 1u : 0u)) != 0)
        {
            if (_session == null)
            {
                XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
            }
            int num2 = num >> 1;
            if (!_session.TryLookup(num2, out XmlDictionaryString _))
            {
                if (num2 < 0 || num2 > 536870911)
                {
                    XmlExceptionHelper.ThrowXmlDictionaryStringIDOutOfRange(_reader);
                }
                XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedSession(_reader, num2);
            }
        }
        else
        {
            if (_dictionary == null)
            {
                XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
            }
            int num3 = num >> 1;
            if (!_dictionary.TryLookup(num3, out XmlDictionaryString _))
            {
                if (num3 < 0 || num3 > 536870911)
                {
                    XmlExceptionHelper.ThrowXmlDictionaryStringIDOutOfRange(_reader);
                }
                XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedStatic(_reader, num3);
            }
        }
        return num;
    }
References System.Xml.XmlBufferReader._dictionary, System.Xml.XmlBufferReader._reader, System.Xml.XmlBufferReader._session, System.Xml.Dictionary, System.Xml.XmlBufferReader.ReadMultiByteUInt31(), System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDOutOfRange(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedSession(), System.Xml.XmlExceptionHelper.ThrowXmlDictionaryStringIDUndefinedStatic(), System.Xml.XmlBinaryReaderSession.TryLookup(), and System.Xml.IXmlDictionary.TryLookup().
Referenced by System.Xml.XmlBufferReader.ReadQName(), and System.Xml.XmlBufferReader.ReadValue().