Terraria: System.Xml.XmlBufferReader.ReadDateTime
ReadDateTime()
DateTime System.Xml.XmlBufferReader.ReadDateTime () inline
Definition at line 460 of file XmlBufferReader.cs.
    {
        long dateData = 0L;
        try
        {
            dateData = ReadInt64();
            return DateTime.FromBinary(dateData);
        }
        catch (ArgumentException exception)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(dateData.ToString(CultureInfo.InvariantCulture), "DateTime", exception));
        }
        catch (FormatException exception2)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(dateData.ToString(CultureInfo.InvariantCulture), "DateTime", exception2));
        }
        catch (OverflowException exception3)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(dateData.ToString(CultureInfo.InvariantCulture), "DateTime", exception3));
        }
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.exception, System.DateTime.FromBinary(), System.Globalization.CultureInfo.InvariantCulture, System.Xml.L, System.Xml.XmlBufferReader.ReadInt64(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().