Terraria: System.Xml.XmlBufferReader.Advance
Advance()
void System.Xml.XmlBufferReader.Advance (int count) inline
Definition at line 264 of file XmlBufferReader.cs.
    {
        _offset += count;
    }
References System.Xml.XmlBufferReader._offset, and System.count.
Referenced by System.Xml.XmlBufferReader.ReadDecimal(), System.Xml.XmlBufferReader.ReadDouble(), System.Xml.XmlBufferReader.ReadGuid(), System.Xml.XmlBufferReader.ReadInt32(), System.Xml.XmlBufferReader.ReadMultiByteUInt31(), System.Xml.XmlBufferReader.ReadSingle(), System.Xml.XmlBufferReader.ReadUInt16(), System.Xml.XmlBufferReader.ReadUInt8(), System.Xml.XmlBufferReader.ReadUniqueId(), System.Xml.XmlBufferReader.ReadUTF8String(), System.Xml.XmlBufferReader.SkipByte(), and System.Xml.XmlBufferReader.UnsafeReadArray().