Terraria: System.Xml.XmlBufferReader.GetHexCharEntity
GetHexCharEntity()
int System.Xml.XmlBufferReader.GetHexCharEntity (int offset, int length) inline private
Definition at line 768 of file XmlBufferReader.cs.
    {
        byte[] buffer = _buffer;
        int num = 0;
        for (int i = 3; i < length - 1; i++)
        {
            byte c = buffer[offset + i];
            int num2 = System.HexConverter.FromChar(c);
            if (num2 == 255)
            {
                XmlExceptionHelper.ThrowInvalidCharRef(_reader);
            }
            num = num * 16 + num2;
            if (num > 1114111)
            {
                XmlExceptionHelper.ThrowInvalidCharRef(_reader);
            }
        }
        return num;
    }
References System.Xml.XmlBufferReader._buffer, System.Xml.XmlBufferReader._reader, System.buffer, System.Xml.Dictionary, System.HexConverter.FromChar(), System.length, System.offset, and System.Xml.XmlExceptionHelper.ThrowInvalidCharRef().
Referenced by System.Xml.XmlBufferReader.GetCharEntity().