Terraria: System.Xml.XmlBufferReader.IsWhitespaceKey
IsWhitespaceKey()
bool System.Xml.XmlBufferReader.IsWhitespaceKey (int key) inline
Definition at line 822 of file XmlBufferReader.cs.
    {
        string value = GetDictionaryString(key).Value;
        for (int i = 0; i < value.Length; i++)
        {
            if (!XmlConverter.IsWhitespace(value[i]))
            {
                return false;
            }
        }
        return true;
    }
References System.Xml.XmlBufferReader.GetDictionaryString(), System.Xml.XmlConverter.IsWhitespace(), System.key, System.value, and System.Xml.XmlDictionaryString.Value.
Referenced by System.Xml.ValueHandle.IsWhitespace().