Terraria: System.Xml.XmlBufferReader.GetDictionaryString
GetDictionaryString()
XmlDictionaryString System.Xml.XmlBufferReader.GetDictionaryString (int key) inline
Definition at line 1147 of file XmlBufferReader.cs.
    {
        IXmlDictionary xmlDictionary = (((key & 1) == 0) ? _dictionary : _session);
        if (!xmlDictionary.TryLookup(key >> 1, out XmlDictionaryString result))
        {
            XmlExceptionHelper.ThrowInvalidBinaryFormat(_reader);
        }
        return result;
    }
References System.Xml.XmlBufferReader._dictionary, System.Xml.XmlBufferReader._reader, System.Xml.XmlBufferReader._session, System.key, and System.Xml.XmlExceptionHelper.ThrowInvalidBinaryFormat().
Referenced by System.Xml.XmlBufferReader.Equals2(), System.Xml.XmlBufferReader.Equals2(), System.Xml.StringHandle.Equals2(), System.Xml.StringHandle.Equals2(), System.Xml.StringHandle.Equals2(), System.Xml.ValueHandle.GetDictionaryString(), System.Xml.ValueHandle.GetQNameDictionaryText(), System.Xml.StringHandle.GetString(), System.Xml.StringHandle.GetString(), System.Xml.StringHandle.GetString(), System.Xml.XmlBufferReader.IsWhitespaceKey(), and System.Xml.StringHandle.TryGetDictionaryString().