Terraria: System.Xml.XmlBufferReader.ReadUInt8
ReadUInt8()
int System.Xml.XmlBufferReader.ReadUInt8 () inline
Definition at line 350 of file XmlBufferReader.cs.
    {
        byte @byte = GetByte();
        Advance(1);
        return @byte;
    }
References System.Xml.XmlBufferReader.Advance(), and System.Xml.XmlBufferReader.GetByte().
Referenced by System.Xml.XmlBufferReader.ReadInt8(), System.Xml.XmlBufferReader.ReadQName(), and System.Xml.XmlBufferReader.ReadValue().