Terraria: UIDynamicItemCollection.GetGridParameters
GetGridParameters()
void UIDynamicItemCollection.GetGridParameters (out int startX, out int startY, out int startItemIndex, out int endItemIndex) inline private
     {
         Rectangle rectangle = GetDimensions().ToRectangle();
         Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
         int x = rectangle.Center.X;
         startX = x - (int)((float)(44 * _itemsPerLine) * 0.5f);
         startY = rectangle.Top;
         startItemIndex = 0;
         endItemIndex = _itemIdsAvailableToShow.Count;
         int num = (Math.Min(viewCullingArea.Top, rectangle.Top) - viewCullingArea.Top) / 44;
         startY += -num * 44;
         startItemIndex += -num * _itemsPerLine;
         int num2 = (int)Math.Ceiling((float)viewCullingArea.Height / 44f) * _itemsPerLine;
         if (endItemIndex > num2 + startItemIndex + _itemsPerLine)
         {
             endItemIndex = num2 + startItemIndex + _itemsPerLine;
         }
     }
References _itemIdsAvailableToShow, _itemsPerLine, UIElement.GetDimensions(), and CalculatedStyle.ToRectangle().
Referenced by DrawSelf(), and GetSnapPoints().