Terraria: System.Marvin.DefaultSeed
DefaultSeed
ulong System.Marvin.DefaultSeed = GenerateSeed() static get
Definition at line 13 of file Marvin.cs.
{ get; } = GenerateSeed();
Referenced by System.String.GetHashCode(), System.String.GetHashCode(), System.String.GetHashCodeOrdinalIgnoreCase(), System.String.GetHashCodeOrdinalIgnoreCase(), System.Globalization.CompareInfo.IcuGetHashCodeOfString(), and System.Globalization.CompareInfo.NlsGetHashCodeOfString().