Terraria: System.Marvin.ComputeHash32OrdinalIgnoreCaseSlow
ComputeHash32OrdinalIgnoreCaseSlow()
static int System.Marvin.ComputeHash32OrdinalIgnoreCaseSlow (ref char data, int count, uint p0, uint p1) inline static private
Definition at line 144 of file Marvin.cs.
    {
        char[] array = null;
        Span<char> span = (((uint)count > 64u) ? ((Span<char>)(array = ArrayPool<char>.Shared.Rent(count))) : stackalloc char[64]);
        Span<char> span2 = span;
        int num = Ordinal.ToUpperOrdinal(new ReadOnlySpan<char>(ref data, count), span2);
        int result = ComputeHash32(ref Unsafe.As<char, byte>(ref MemoryMarshal.GetReference(span2)), (uint)(num * 2), p0, p1);
        if (array != null)
        {
            ArrayPool<char>.Shared.Return(array);
        }
        return result;
    }
References System.array, System.Marvin.ComputeHash32(), System.count, System.Buffers.ArrayPool< T >.Rent(), System.Buffers.ArrayPool< T >.Shared, and System.Globalization.Ordinal.ToUpperOrdinal().
Referenced by System.Marvin.ComputeHash32OrdinalIgnoreCase().