Terraria: System.Marvin.Block
Block()
static void System.Marvin.Block (ref uint rp0, ref uint rp1) inline static private
Definition at line 83 of file Marvin.cs.
    {
        uint num = rp0;
        uint num2 = rp1;
        num2 ^= num;
        num = BitOperations.RotateLeft(num, 20);
        num += num2;
        num2 = BitOperations.RotateLeft(num2, 9);
        num2 ^= num;
        num = BitOperations.RotateLeft(num, 27);
        num += num2;
        num2 = BitOperations.RotateLeft(num2, 19);
        rp0 = num;
        rp1 = num2;
    }
References System.Numerics.BitOperations.RotateLeft().
Referenced by System.Marvin.ComputeHash32(), and System.Marvin.ComputeHash32OrdinalIgnoreCase().