Terraria: System.Marvin.ComputeHash32
ComputeHash32() [1/2]
static int System.Marvin.ComputeHash32 (ReadOnlySpan< byte > data, ulong seed) inline static
Definition at line 17 of file Marvin.cs.
    {
        return ComputeHash32(ref MemoryMarshal.GetReference(data), (uint)data.Length, (uint)seed, (uint)(seed >> 32));
    }
References System.Marvin.ComputeHash32(), and System.ReadOnlySpan< T >.Length.
Referenced by System.Marvin.ComputeHash32(), System.Marvin.ComputeHash32OrdinalIgnoreCaseSlow(), System.String.GetHashCode(), System.String.GetHashCode(), System.Collections.Generic.RandomizedStringEqualityComparer.OrdinalComparer.GetHashCode(), System.Globalization.CompareInfo.IcuGetHashCodeOfString(), and System.Globalization.CompareInfo.NlsGetHashCodeOfString().