Terraria: System.Marvin.ComputeHash32OrdinalIgnoreCase
ComputeHash32OrdinalIgnoreCase()
static int System.Marvin.ComputeHash32OrdinalIgnoreCase (ref char data, int count, uint p0, uint p1) inline static
Definition at line 106 of file Marvin.cs.
    {
        uint num = (uint)count;
        nuint num2 = 0u;
        while (true)
        {
            if (num >= 2)
            {
                uint value = Unsafe.ReadUnaligned<uint>(ref Unsafe.As<char, byte>(ref Unsafe.AddByteOffset(ref data, num2)));
                if (!Utf16Utility.AllCharsInUInt32AreAscii(value))
                {
                    break;
                }
                p0 += Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value);
                Block(ref p0, ref p1);
                num2 += 4;
                num -= 2;
                continue;
            }
            if (num != 0)
            {
                uint value = Unsafe.AddByteOffset(ref data, num2);
                if (value > 127)
                {
                    break;
                }
                _ = BitConverter.IsLittleEndian;
                p0 += Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(value) + 8388480;
            }
            _ = BitConverter.IsLittleEndian;
            p0 += 128;
            Block(ref p0, ref p1);
            Block(ref p0, ref p1);
            return (int)(p1 ^ p0);
        }
        return ComputeHash32OrdinalIgnoreCaseSlow(ref Unsafe.AddByteOffset(ref data, num2), (int)num, p0, p1);
    }
References System.Text.Unicode.Utf16Utility.AllCharsInUInt32AreAscii(), System.Marvin.Block(), System.Marvin.ComputeHash32OrdinalIgnoreCaseSlow(), System.Text.Unicode.Utf16Utility.ConvertAllAsciiCharsInUInt32ToUppercase(), System.count, System.BitConverter.IsLittleEndian, and System.value.
Referenced by System.Collections.Generic.RandomizedStringEqualityComparer.OrdinalIgnoreCaseComparer.GetHashCode(), System.String.GetHashCodeOrdinalIgnoreCase(), and System.String.GetHashCodeOrdinalIgnoreCase().