Terraria: HouseUtils.AreRoomsValid
AreRoomsValid()
static bool HouseUtils.AreRoomsValid (IEnumerable< Rectangle > rooms, StructureMap structures, HouseType style) inline static private
     {
         foreach (Rectangle room in rooms)
         {
             if (style != HouseType.Granite && WorldUtils.Find(new Point(room.X - 2, room.Y - 2), Searches.Chain(new Searches.Rectangle(room.Width + 4, room.Height + 4).RequireAll(mode: false), new Conditions.HasLava()), out var _))
             {
                 return false;
             }
             if (WorldGen.notTheBees)
             {
                 if (!structures.CanPlace(room, BeelistedTiles, 5))
                 {
                     return false;
                 }
             }
             else if (!structures.CanPlace(room, BlacklistedTiles, 5))
             {
                 return false;
             }
         }
         return true;
     }
References BeelistedTiles, BlacklistedTiles, Searches.Chain(), WorldUtils.Find(), WorldGen.notTheBees, and GenSearch.RequireAll().
Referenced by CreateBuilder().