Terraria: HouseUtils.CreateRooms
CreateRooms()
static List<Rectangle> HouseUtils.CreateRooms (Point origin) inline static private
     {
         if (!WorldUtils.Find(origin, Searches.Chain(new Searches.Down(200), new Conditions.IsSolid()), out var result) || result == origin)
         {
             return new List<Rectangle>();
         }
         Rectangle item = FindRoom(result);
         Rectangle rectangle = FindRoom(new Point(item.Center.X, item.Y + 1));
         Rectangle rectangle2 = FindRoom(new Point(item.Center.X, item.Y + item.Height + 10));
         rectangle2.Y = item.Y + item.Height - 1;
         double roomSolidPrecentage = GetRoomSolidPrecentage(rectangle);
         double roomSolidPrecentage2 = GetRoomSolidPrecentage(rectangle2);
         item.Y += 3;
         rectangle.Y += 3;
         rectangle2.Y += 3;
         List<Rectangle> list = new List<Rectangle>();
         if (WorldGen.genRand.NextDouble() > roomSolidPrecentage + 0.2)
         {
             list.Add(rectangle);
         }
         list.Add(item);
         if (WorldGen.genRand.NextDouble() > roomSolidPrecentage2 + 0.2)
         {
             list.Add(rectangle2);
         }
         return list;
     }
References Searches.Chain(), WorldUtils.Find(), FindRoom(), WorldGen.genRand, GetRoomSolidPrecentage(), and UnifiedRandom.NextDouble().
Referenced by CreateBuilder().