Terraria: HouseUtils.CreateBuilder
CreateBuilder()
static HouseBuilder HouseUtils.CreateBuilder (Point origin, StructureMap structures) inline static
     {
         List<Rectangle> list = CreateRooms(origin);
         if (list.Count == 0 || !AreRoomLocationsValid(list))
         {
             return HouseBuilder.Invalid;
         }
         HouseType houseType = GetHouseType(list);
         if (!AreRoomsValid(list, structures, houseType))
         {
             return HouseBuilder.Invalid;
         }
         return houseType switch
         {
             HouseType.Wood => new WoodHouseBuilder(list),
             HouseType.Desert => new DesertHouseBuilder(list),
             HouseType.Granite => new GraniteHouseBuilder(list),
             HouseType.Ice => new IceHouseBuilder(list),
             HouseType.Jungle => new JungleHouseBuilder(list),
             HouseType.Marble => new MarbleHouseBuilder(list),
             HouseType.Mushroom => new MushroomHouseBuilder(list),
             _ => new WoodHouseBuilder(list),
         };
     }
References AreRoomLocationsValid(), AreRoomsValid(), CreateRooms(), GetHouseType(), and HouseBuilder.Invalid.
Referenced by CaveHouseBiome.Place().