Terraria: HouseUtils.GetRoomSolidPrecentage
GetRoomSolidPrecentage()
static double HouseUtils.GetRoomSolidPrecentage (Rectangle room) inline static private
     {
         double num = room.Width * room.Height;
         Ref<int> @ref = new Ref<int>(0);
         WorldUtils.Gen(new Point(room.X, room.Y), new Shapes.Rectangle(room.Width, room.Height), Actions.Chain(new Modifiers.IsSolid(), new Actions.Count(@ref)));
         return (double)@ref.Value / num;
     }
References Actions.Chain(), WorldUtils.Gen(), and Ref< T >.Value.
Referenced by CreateRooms().