Terraria: System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes
GetUnspecifiedDefaultAttributes() [2/2]
void System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes (ArrayList defaultAttributes, bool createNodeData) inline package
Definition at line 1036 of file XmlSchemaValidator.cs.
    {
        _currentState = ValidatorState.Attribute;
        SchemaElementDecl elementDecl = _context.ElementDecl;
        if (elementDecl == null || !elementDecl.HasDefaultAttribute)
        {
            return;
        }
        for (int i = 0; i < elementDecl.DefaultAttDefs.Count; i++)
        {
            SchemaAttDef schemaAttDef = (SchemaAttDef)elementDecl.DefaultAttDefs[i];
            if (_attPresence.Contains(schemaAttDef.Name) || schemaAttDef.DefaultValueTyped == null)
            {
                continue;
            }
            string text = _nameTable.Add(schemaAttDef.Name.Namespace);
            string text2 = string.Empty;
            if (text.Length > 0)
            {
                text2 = GetDefaultAttributePrefix(text);
                if (text2 == null || text2.Length == 0)
                {
                    SendValidationEvent(System.SR.Sch_DefaultAttributeNotApplied, new string[2]
                    {
                        schemaAttDef.Name.ToString(),
                        QNameString(_context.LocalName, _context.Namespace)
                    });
                    continue;
                }
            }
            XmlSchemaDatatype datatype = schemaAttDef.Datatype;
            if (createNodeData)
            {
                ValidatingReaderNodeData validatingReaderNodeData = new ValidatingReaderNodeData();
                validatingReaderNodeData.LocalName = _nameTable.Add(schemaAttDef.Name.Name);
                validatingReaderNodeData.Namespace = text;
                validatingReaderNodeData.Prefix = _nameTable.Add(text2);
                validatingReaderNodeData.NodeType = XmlNodeType.Attribute;
                AttributePSVIInfo attributePSVIInfo = new AttributePSVIInfo();
                XmlSchemaInfo attributeSchemaInfo = attributePSVIInfo.attributeSchemaInfo;
                if (schemaAttDef.Datatype.Variety == XmlSchemaDatatypeVariety.Union)
                {
                    XsdSimpleValue xsdSimpleValue = schemaAttDef.DefaultValueTyped as XsdSimpleValue;
                    attributeSchemaInfo.MemberType = xsdSimpleValue.XmlType;
                    datatype = xsdSimpleValue.XmlType.Datatype;
                    attributePSVIInfo.typedAttributeValue = xsdSimpleValue.TypedValue;
                }
                else
                {
                    attributePSVIInfo.typedAttributeValue = schemaAttDef.DefaultValueTyped;
                }
                attributeSchemaInfo.IsDefault = true;
                attributeSchemaInfo.Validity = XmlSchemaValidity.Valid;
                attributeSchemaInfo.SchemaType = schemaAttDef.SchemaType;
                attributeSchemaInfo.SchemaAttribute = schemaAttDef.SchemaAttribute;
                validatingReaderNodeData.RawValue = attributeSchemaInfo.XmlType.ValueConverter.ToString(attributePSVIInfo.typedAttributeValue);
                validatingReaderNodeData.AttInfo = attributePSVIInfo;
                defaultAttributes.Add(validatingReaderNodeData);
            }
            else
            {
                defaultAttributes.Add(schemaAttDef.SchemaAttribute);
            }
            CheckTokenizedTypes(datatype, schemaAttDef.DefaultValueTyped, attrValue: true);
            if (HasIdentityConstraints)
            {
                AttributeIdentityConstraints(schemaAttDef.Name.Name, schemaAttDef.Name.Namespace, schemaAttDef.DefaultValueTyped, schemaAttDef.DefaultValueRaw, datatype);
            }
        }
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.XmlNameTable.Add(), System.Collections.ArrayList.Add(), System.Xml.Schema.XmlSchemaValidator.AttributeIdentityConstraints(), System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes(), System.Collections.Hashtable.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix(), System.Xml.Schema.XmlSchemaValidator.HasIdentityConstraints, System.SR.Sch_DefaultAttributeNotApplied, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.text, System.Xml.Schema.XmlValueConverter.ToString(), System.Xml.Schema.XmlSchemaType.ValueConverter, and System.Xml.Schema.XmlSchemaInfo.XmlType.