Terraria: System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet
RecompileSchemaSet()
void System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet () inline package
Definition at line 1774 of file XmlSchemaValidator.cs.
    {
        if (!_schemaSet.IsCompiled)
        {
            try
            {
                _schemaSet.Compile();
            }
            catch (XmlSchemaException e)
            {
                SendValidationEvent(e);
            }
        }
        _compiledSchemaInfo = _schemaSet.CompiledInfo;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaSet.Compile(), System.Xml.Schema.XmlSchemaSet.CompiledInfo, System.Xml.Schema.XmlSchemaSet.IsCompiled, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.AddSchema(), System.Xml.Schema.XmlSchemaValidator.AddXmlNamespaceSchema(), System.Xml.Schema.XmlSchemaValidator.Init(), and System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations().