Terraria: System.Xml.Schema.XmlSchemaValidator.CompleteValidationError
CompleteValidationError()
static void System.Xml.Schema.XmlSchemaValidator.CompleteValidationError (ValidationState context, ValidationEventHandler eventHandler, object sender, string sourceUri, int lineNo, int linePos, XmlSchemaSet schemaSet) inline static package
Definition at line 2374 of file XmlSchemaValidator.cs.
    {
        ArrayList arrayList = null;
        bool flag = schemaSet != null;
        if (context.ElementDecl != null)
        {
            arrayList = ((!flag) ? context.ElementDecl.ContentValidator.ExpectedElements(context, isRequiredOnly: true) : context.ElementDecl.ContentValidator.ExpectedParticles(context, isRequiredOnly: true, schemaSet));
        }
        if (arrayList == null || arrayList.Count == 0)
        {
            if (context.TooComplex)
            {
                SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_IncompleteContentComplex, new string[2]
                {
                    BuildElementName(context.LocalName, context.Namespace),
                    System.SR.Sch_ComplexContentModel
                }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
            }
            SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_IncompleteContent, BuildElementName(context.LocalName, context.Namespace), sourceUri, lineNo, linePos), XmlSeverityType.Error);
        }
        else if (context.TooComplex)
        {
            SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_IncompleteContentExpectingComplex, new string[3]
            {
                BuildElementName(context.LocalName, context.Namespace),
                PrintExpectedElements(arrayList, flag),
                System.SR.Sch_ComplexContentModel
            }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
        }
        else
        {
            SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_IncompleteContentExpecting, new string[2]
            {
                BuildElementName(context.LocalName, context.Namespace),
                PrintExpectedElements(arrayList, flag)
            }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
        }
    }
References System.Xml.Schema.XmlSchemaValidator.BuildElementName(), System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ContentValidator.ExpectedElements(), System.Xml.Schema.ContentValidator.ExpectedParticles(), System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.SR.Sch_IncompleteContent, System.SR.Sch_IncompleteContentComplex, System.SR.Sch_IncompleteContentExpecting, System.SR.Sch_IncompleteContentExpectingComplex, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.Schema.ValidationState.TooComplex.
Referenced by System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(), System.Xml.Schema.DtdValidator.ValidateEndElement(), System.Xml.Schema.XdrValidator.ValidateEndElement(), and System.Xml.Schema.XsdValidator.ValidateEndElement().