Terraria: System.Xml.Schema.XmlSchemaValidator.BuildXsiAttributes
BuildXsiAttributes()
static void System.Xml.Schema.XmlSchemaValidator.BuildXsiAttributes () inline static private
Definition at line 2265 of file XmlSchemaValidator.cs.
    {
        if (s_xsiTypeSO == null)
        {
            XmlSchemaAttribute xmlSchemaAttribute = new XmlSchemaAttribute();
            xmlSchemaAttribute.Name = "type";
            xmlSchemaAttribute.SetQualifiedName(new XmlQualifiedName("type", "http://www.w3.org/2001/XMLSchema-instance"));
            xmlSchemaAttribute.SetAttributeType(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.QName));
            Interlocked.CompareExchange(ref s_xsiTypeSO, xmlSchemaAttribute, null);
        }
        if (s_xsiNilSO == null)
        {
            XmlSchemaAttribute xmlSchemaAttribute2 = new XmlSchemaAttribute();
            xmlSchemaAttribute2.Name = "nil";
            xmlSchemaAttribute2.SetQualifiedName(new XmlQualifiedName("nil", "http://www.w3.org/2001/XMLSchema-instance"));
            xmlSchemaAttribute2.SetAttributeType(XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.Boolean));
            Interlocked.CompareExchange(ref s_xsiNilSO, xmlSchemaAttribute2, null);
        }
        if (s_xsiSLSO == null)
        {
            XmlSchemaSimpleType builtInSimpleType = XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String);
            XmlSchemaAttribute xmlSchemaAttribute3 = new XmlSchemaAttribute();
            xmlSchemaAttribute3.Name = "schemaLocation";
            xmlSchemaAttribute3.SetQualifiedName(new XmlQualifiedName("schemaLocation", "http://www.w3.org/2001/XMLSchema-instance"));
            xmlSchemaAttribute3.SetAttributeType(builtInSimpleType);
            Interlocked.CompareExchange(ref s_xsiSLSO, xmlSchemaAttribute3, null);
        }
        if (s_xsiNoNsSLSO == null)
        {
            XmlSchemaSimpleType builtInSimpleType2 = XmlSchemaType.GetBuiltInSimpleType(XmlTypeCode.String);
            XmlSchemaAttribute xmlSchemaAttribute4 = new XmlSchemaAttribute();
            xmlSchemaAttribute4.Name = "noNamespaceSchemaLocation";
            xmlSchemaAttribute4.SetQualifiedName(new XmlQualifiedName("noNamespaceSchemaLocation", "http://www.w3.org/2001/XMLSchema-instance"));
            xmlSchemaAttribute4.SetAttributeType(builtInSimpleType2);
            Interlocked.CompareExchange(ref s_xsiNoNsSLSO, xmlSchemaAttribute4, null);
        }
    }
References System.Threading.Interlocked.CompareExchange(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaType.GetBuiltInSimpleType(), System.Xml.Schema.XmlSchemaValidator.s_xsiNilSO, System.Xml.Schema.XmlSchemaValidator.s_xsiNoNsSLSO, System.Xml.Schema.XmlSchemaValidator.s_xsiSLSO, and System.Xml.Schema.XmlSchemaValidator.s_xsiTypeSO.
Referenced by System.Xml.Schema.XmlSchemaValidator.AddXsiAttributes().