Terraria: System.Xml.Schema.XmlSchemaValidator.EnumerateAny
EnumerateAny()
static void System.Xml.Schema.XmlSchemaValidator.EnumerateAny (StringBuilder builder, string namespaces) inline static private
Definition at line 2524 of file XmlSchemaValidator.cs.
    {
        StringBuilder stringBuilder = new StringBuilder();
        if (namespaces == "##any" || namespaces == "##other")
        {
            stringBuilder.Append(namespaces);
        }
        else
        {
            string[] array = XmlConvert.SplitString(namespaces);
            stringBuilder.Append(array[0]);
            for (int i = 1; i < array.Length; i++)
            {
                stringBuilder.Append(", ");
                stringBuilder.Append(array[i]);
            }
        }
        builder.Append(System.SR.Format(System.SR.Sch_AnyElementNS, stringBuilder));
    }
References System.array, System.SR.Format(), System.SR.Sch_AnyElementNS, and System.Xml.XmlConvert.SplitString().
Referenced by System.Xml.Schema.XmlSchemaValidator.PrintNamesWithNS().