Terraria: System.Xml.Schema.XmlSchemaValidator.AddIdentityConstraints
AddIdentityConstraints()
void System.Xml.Schema.XmlSchemaValidator.AddIdentityConstraints () inline private
Definition at line 2035 of file XmlSchemaValidator.cs.
    {
        SchemaElementDecl elementDecl = _context.ElementDecl;
        _context.Constr = new ConstraintStruct[elementDecl.Constraints.Length];
        int num = 0;
        for (int i = 0; i < elementDecl.Constraints.Length; i++)
        {
            _context.Constr[num++] = new ConstraintStruct(elementDecl.Constraints[i]);
        }
        for (int j = 0; j < _context.Constr.Length; j++)
        {
            if (_context.Constr[j].constraint.Role != CompiledIdentityConstraint.ConstraintRole.Keyref)
            {
                continue;
            }
            bool flag = false;
            for (int num2 = _validationStack.Length - 1; num2 >= ((_startIDConstraint >= 0) ? _startIDConstraint : (_validationStack.Length - 1)); num2--)
            {
                if (((ValidationState)_validationStack[num2]).Constr != null)
                {
                    ConstraintStruct[] constr = ((ValidationState)_validationStack[num2]).Constr;
                    for (int k = 0; k < constr.Length; k++)
                    {
                        if (constr[k].constraint.name == _context.Constr[j].constraint.refer)
{
                            flag = true;
                            if (constr[k].keyrefTable == null)
{
                                constr[k].keyrefTable = new Hashtable();
                            }
                            _context.Constr[j].qualifiedTable = constr[k].keyrefTable;
                            break;
                        }
                    }
                    if (flag)
                    {
                        break;
                    }
                }
            }
            if (!flag)
            {
                SendValidationEvent(System.SR.Sch_RefNotInScope, QNameString(_context.LocalName, _context.Namespace));
            }
        }
        if (_startIDConstraint == -1)
        {
            _startIDConstraint = _validationStack.Length - 1;
        }
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._startIDConstraint, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Schema.ValidationState.Constr, System.Xml.Schema.ConstraintStruct.constraint, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.HWStack.Length, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.ConstraintStruct.qualifiedTable, System.Xml.Schema.CompiledIdentityConstraint.refer, System.Xml.Schema.CompiledIdentityConstraint.Role, System.SR.Sch_RefNotInScope, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateStartElementIdentityConstraints().