Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateAttribute
ValidateAttribute() [1/3]
object? System.Xml.Schema.XmlSchemaValidator.ValidateAttribute (string localName, string namespaceUri, string attributeValue, XmlSchemaInfo? schemaInfo) inline
Definition at line 567 of file XmlSchemaValidator.cs.
    {
        if (attributeValue == null)
        {
            throw new ArgumentNullException("attributeValue");
        }
        return ValidateAttribute(localName, namespaceUri, null, attributeValue, schemaInfo);
    }
References System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.Schema.XNodeValidator.ValidateAttribute(), System.Xml.XsdValidatingReader.ValidateAttributes(), System.Xml.DocumentSchemaValidator.ValidateAttributes(), and System.Xml.DocumentSchemaValidator.ValidateNode().