Terraria: System.Xml.Schema.XmlSchemaValidator.Reset
Reset()
void System.Xml.Schema.XmlSchemaValidator.Reset () inline private
Definition at line 373 of file XmlSchemaValidator.cs.
    {
        _isRoot = true;
        _rootHasSchema = true;
        while (_validationStack.Length > 1)
        {
            _validationStack.Pop();
        }
        _startIDConstraint = -1;
        _partialValidationType = null;
        if (_IDs != null)
        {
            _IDs.Clear();
        }
        if (ProcessSchemaHints)
        {
            _validatedNamespaces.Clear();
        }
    }
References System.Xml.Schema.XmlSchemaValidator._IDs, System.Xml.Schema.XmlSchemaValidator._isRoot, System.Xml.Schema.XmlSchemaValidator._partialValidationType, System.Xml.Schema.XmlSchemaValidator._rootHasSchema, System.Xml.Schema.XmlSchemaValidator._startIDConstraint, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Collections.Hashtable.Clear(), System.Xml.HWStack.Length, System.Xml.HWStack.Pop(), and System.Xml.Schema.XmlSchemaValidator.ProcessSchemaHints.
Referenced by System.Xml.Schema.XmlSchemaValidator.Init(), System.Xml.Schema.XmlSchemaValidator.Initialize(), and System.Xml.Schema.XmlSchemaValidator.Initialize().