Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateAttribute
ValidateAttribute() [3/3]
object System.Xml.Schema.XmlSchemaValidator.ValidateAttribute (string localName, string namespaceUri, XmlValueGetter attributeValueGetter, string attributeStringValue, XmlSchemaInfo schemaInfo) inline private
Definition at line 585 of file XmlSchemaValidator.cs.
    {
        if (localName == null)
        {
            throw new ArgumentNullException("localName");
        }
        if (namespaceUri == null)
        {
            throw new ArgumentNullException("namespaceUri");
        }
        ValidatorState validatorState = ((_validationStack.Length > 1) ? ValidatorState.Attribute : ValidatorState.TopLevelAttribute);
        CheckStateTransition(validatorState, s_methodNames[(int)validatorState]);
        object obj = null;
        _attrValid = true;
        XmlSchemaValidity validity = XmlSchemaValidity.NotKnown;
        XmlSchemaAttribute xmlSchemaAttribute = null;
        XmlSchemaSimpleType memberType = null;
        namespaceUri = _nameTable.Add(namespaceUri);
        if (Ref.Equal(namespaceUri, _nsXmlNs))
        {
            return null;
        }
        SchemaAttDef schemaAttDef = null;
        SchemaElementDecl elementDecl = _context.ElementDecl;
        XmlQualifiedName xmlQualifiedName = new XmlQualifiedName(localName, namespaceUri);
        if (_attPresence[xmlQualifiedName] != null)
        {
            SendValidationEvent(System.SR.Sch_DuplicateAttribute, xmlQualifiedName.ToString());
            schemaInfo?.Clear();
            return null;
        }
        if (!Ref.Equal(namespaceUri, _nsXsi))
        {
            XmlSchemaObject xmlSchemaObject = ((_currentState == ValidatorState.TopLevelAttribute) ? _partialValidationType : null);
            schemaAttDef = _compiledSchemaInfo.GetAttributeXsd(elementDecl, xmlQualifiedName, xmlSchemaObject, out var attributeMatchState);
            switch (attributeMatchState)
            {
            case AttributeMatchState.UndeclaredElementAndAttribute:
                if ((schemaAttDef = CheckIsXmlAttribute(xmlQualifiedName)) == null)
                {
                    if (elementDecl == null && _processContents == XmlSchemaContentProcessing.Strict && xmlQualifiedName.Namespace.Length != 0 && _compiledSchemaInfo.Contains(xmlQualifiedName.Namespace))
                    {
                        _attrValid = false;
                        SendValidationEvent(System.SR.Sch_UndeclaredAttribute, xmlQualifiedName.ToString());
                    }
                    else if (_processContents != XmlSchemaContentProcessing.Skip)
                    {
                        SendValidationEvent(System.SR.Sch_NoAttributeSchemaFound, xmlQualifiedName.ToString(), XmlSeverityType.Warning);
                    }
                    break;
                }
                goto case AttributeMatchState.AttributeFound;
            case AttributeMatchState.UndeclaredAttribute:
                if ((schemaAttDef = CheckIsXmlAttribute(xmlQualifiedName)) == null)
                {
                    _attrValid = false;
                    SendValidationEvent(System.SR.Sch_UndeclaredAttribute, xmlQualifiedName.ToString());
                    break;
                }
                goto case AttributeMatchState.AttributeFound;
            case AttributeMatchState.ProhibitedAnyAttribute:
                if ((schemaAttDef = CheckIsXmlAttribute(xmlQualifiedName)) == null)
                {
                    _attrValid = false;
                    SendValidationEvent(System.SR.Sch_ProhibitedAttribute, xmlQualifiedName.ToString());
                    break;
                }
                goto case AttributeMatchState.AttributeFound;
            case AttributeMatchState.ProhibitedAttribute:
                _attrValid = false;
                SendValidationEvent(System.SR.Sch_ProhibitedAttribute, xmlQualifiedName.ToString());
                break;
            case AttributeMatchState.AttributeNameMismatch:
                _attrValid = false;
                SendValidationEvent(System.SR.Sch_SchemaAttributeNameMismatch, new string[2]
                {
                    xmlQualifiedName.ToString(),
                    ((XmlSchemaAttribute)xmlSchemaObject).QualifiedName.ToString()
                });
                break;
            case AttributeMatchState.ValidateAttributeInvalidCall:
                _currentState = ValidatorState.Start;
                _attrValid = false;
                SendValidationEvent(System.SR.Sch_ValidateAttributeInvalidCall, string.Empty);
                break;
            case AttributeMatchState.AnyIdAttributeFound:
                if (_wildID == null)
                {
                    _wildID = schemaAttDef;
                    XmlSchemaComplexType xmlSchemaComplexType = elementDecl.SchemaType as XmlSchemaComplexType;
                    if (xmlSchemaComplexType.ContainsIdAttribute(findAll: false))
                    {
                        SendValidationEvent(System.SR.Sch_AttrUseAndWildId, string.Empty);
                        break;
                    }
                    goto case AttributeMatchState.AttributeFound;
                }
                SendValidationEvent(System.SR.Sch_MoreThanOneWildId, string.Empty);
                break;
            case AttributeMatchState.AttributeFound:
            {
                xmlSchemaAttribute = schemaAttDef.SchemaAttribute;
                if (elementDecl != null)
                {
                    _attPresence.Add(xmlQualifiedName, schemaAttDef);
                }
                object obj2 = ((attributeValueGetter == null) ? attributeStringValue : attributeValueGetter());
                obj = CheckAttributeValue(obj2, schemaAttDef);
                XmlSchemaDatatype datatype = schemaAttDef.Datatype;
                if (datatype.Variety == XmlSchemaDatatypeVariety.Union && obj != null)
                {
                    XsdSimpleValue xsdSimpleValue = obj as XsdSimpleValue;
                    memberType = xsdSimpleValue.XmlType;
                    datatype = xsdSimpleValue.XmlType.Datatype;
                    obj = xsdSimpleValue.TypedValue;
                }
                CheckTokenizedTypes(datatype, obj, attrValue: true);
                if (HasIdentityConstraints)
                {
                    AttributeIdentityConstraints(xmlQualifiedName.Name, xmlQualifiedName.Namespace, obj, obj2.ToString(), datatype);
                }
                break;
            }
            case AttributeMatchState.AnyAttributeLax:
                SendValidationEvent(System.SR.Sch_NoAttributeSchemaFound, xmlQualifiedName.ToString(), XmlSeverityType.Warning);
                break;
            }
        }
        else
        {
            localName = _nameTable.Add(localName);
            if (Ref.Equal(localName, _xsiTypeString) || Ref.Equal(localName, _xsiNilString) || Ref.Equal(localName, _xsiSchemaLocationString) || Ref.Equal(localName, _xsiNoNamespaceSchemaLocationString))
            {
                _attPresence.Add(xmlQualifiedName, SchemaAttDef.Empty);
            }
            else
            {
                _attrValid = false;
                SendValidationEvent(System.SR.Sch_NotXsiAttribute, xmlQualifiedName.ToString());
            }
        }
        if (!_attrValid)
        {
            validity = XmlSchemaValidity.Invalid;
        }
        else if (schemaAttDef != null)
        {
            validity = XmlSchemaValidity.Valid;
        }
        if (schemaInfo != null)
        {
            schemaInfo.SchemaAttribute = xmlSchemaAttribute;
            schemaInfo.SchemaType = xmlSchemaAttribute?.AttributeSchemaType;
            schemaInfo.MemberType = memberType;
            schemaInfo.IsDefault = false;
            schemaInfo.Validity = validity;
        }
        if (ProcessSchemaHints && _validatedNamespaces[namespaceUri] == null)
        {
            _validatedNamespaces.Add(namespaceUri, namespaceUri);
        }
        return obj;
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Xml.Schema.XmlSchemaValidator._attrValid, System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsXmlNs, System.Xml.Schema.XmlSchemaValidator._nsXsi, System.Xml.Schema.XmlSchemaValidator._partialValidationType, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._wildID, System.Xml.Schema.XmlSchemaValidator._xsiNilString, System.Xml.Schema.XmlSchemaValidator._xsiNoNamespaceSchemaLocationString, System.Xml.Schema.XmlSchemaValidator._xsiSchemaLocationString, System.Xml.Schema.XmlSchemaValidator._xsiTypeString, System.Xml.XmlNameTable.Add(), System.Collections.Hashtable.Add(), System.Xml.Schema.XmlSchemaValidator.AttributeIdentityConstraints(), System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(), System.Xml.Schema.XmlSchemaValidator.CheckIsXmlAttribute(), System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes(), System.Xml.Schema.XmlSchemaInfo.Clear(), System.Xml.Schema.SchemaInfo.Contains(), System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.SchemaAttDef.Empty, System.Xml.Ref.Equal(), System.Xml.Schema.SchemaInfo.GetAttributeXsd(), System.Xml.Schema.XmlSchemaValidator.HasIdentityConstraints, System.obj, System.Xml.Schema.XmlSchemaValidator.ProcessSchemaHints, System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.SR.Sch_AttrUseAndWildId, System.SR.Sch_DuplicateAttribute, System.SR.Sch_MoreThanOneWildId, System.SR.Sch_NoAttributeSchemaFound, System.SR.Sch_NotXsiAttribute, System.SR.Sch_ProhibitedAttribute, System.SR.Sch_SchemaAttributeNameMismatch, System.SR.Sch_UndeclaredAttribute, System.SR.Sch_ValidateAttributeInvalidCall, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.Schema.XmlSchemaDatatype.Variety.