Terraria: System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue
CheckAttributeValue()
object System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue (object value, SchemaAttDef attdef) inline private
Definition at line 1834 of file XmlSchemaValidator.cs.
    {
        object typedValue = null;
        XmlSchemaDatatype datatype = attdef.Datatype;
        string text = value as string;
        Exception ex = null;
        if (text != null)
        {
            ex = datatype.TryParseValue(text, _nameTable, _nsResolver, out typedValue);
            if (ex == null)
            {
                goto IL_0050;
            }
        }
        else
        {
            ex = datatype.TryParseValue(value, _nameTable, _nsResolver, out typedValue);
            if (ex == null)
            {
                goto IL_0050;
            }
        }
        _attrValid = false;
        if (text == null)
        {
            text = XmlSchemaDatatype.ConcatenatedToString(value);
        }
        SendValidationEvent(System.SR.Sch_AttributeValueDataTypeDetailed, new string[4]
        {
            attdef.Name.ToString(),
            text,
            GetTypeName(attdef),
            ex.Message
        }, ex);
        return null;
        IL_0050:
        if (!attdef.CheckValue(typedValue))
        {
            _attrValid = false;
            SendValidationEvent(System.SR.Sch_FixedAttributeValue, attdef.Name.ToString());
        }
        return typedValue;
    }
References System.Xml.Schema.XmlSchemaValidator._attrValid, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaDatatype.ConcatenatedToString(), System.Xml.Dictionary, System.SR.Sch_AttributeValueDataTypeDetailed, System.SR.Sch_FixedAttributeValue, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.text, System.Xml.Schema.XmlSchemaDatatype.TryParseValue(), and System.value.
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().