Terraria: System.Xml.Schema.XmlSchemaValidator.XmlSchemaValidator
XmlSchemaValidator()
System.Xml.Schema.XmlSchemaValidator.XmlSchemaValidator (XmlNameTable nameTable, XmlSchemaSet schemas, IXmlNamespaceResolver namespaceResolver, XmlSchemaValidationFlags validationFlags) inline
Definition at line 300 of file XmlSchemaValidator.cs.
    {
        if (nameTable == null)
        {
            throw new ArgumentNullException("nameTable");
        }
        if (schemas == null)
        {
            throw new ArgumentNullException("schemas");
        }
        if (namespaceResolver == null)
        {
            throw new ArgumentNullException("namespaceResolver");
        }
        _nameTable = nameTable;
        _nsResolver = namespaceResolver;
        _validationFlags = validationFlags;
        if ((validationFlags & XmlSchemaValidationFlags.ProcessInlineSchema) != 0 || (validationFlags & XmlSchemaValidationFlags.ProcessSchemaLocation) != 0)
        {
            _schemaSet = new XmlSchemaSet(nameTable);
            _schemaSet.ValidationEventHandler += schemas.GetEventHandler();
            _schemaSet.CompilationSettings = schemas.CompilationSettings;
            _schemaSet.XmlResolver = schemas.GetResolver();
            _schemaSet.Add(schemas);
            _validatedNamespaces = new Hashtable();
        }
        else
        {
            _schemaSet = schemas;
        }
        Init();
    }
References System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._validationFlags, System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.Schema.XmlSchemaSet.CompilationSettings, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaSet.GetEventHandler(), System.Xml.Schema.XmlSchemaSet.GetResolver(), and System.Xml.Schema.XmlSchemaValidator.Init().