Terraria: System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl
FastGetElementDecl()
SchemaElementDecl System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl (XmlQualifiedName elementName, object particle) inline private
Definition at line 1510 of file XmlSchemaValidator.cs.
    {
        SchemaElementDecl schemaElementDecl = null;
        if (particle != null)
        {
            if (particle is XmlSchemaElement xmlSchemaElement)
            {
                schemaElementDecl = xmlSchemaElement.ElementDecl;
            }
            else
            {
                XmlSchemaAny xmlSchemaAny = (XmlSchemaAny)particle;
                _processContents = xmlSchemaAny.ProcessContentsCorrect;
            }
        }
        if (schemaElementDecl == null && _processContents != XmlSchemaContentProcessing.Skip)
        {
            if (_isRoot && _partialValidationType != null)
            {
                if (_partialValidationType is XmlSchemaElement)
                {
                    XmlSchemaElement xmlSchemaElement2 = (XmlSchemaElement)_partialValidationType;
                    if (elementName.Equals(xmlSchemaElement2.QualifiedName))
                    {
                        schemaElementDecl = xmlSchemaElement2.ElementDecl;
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_SchemaElementNameMismatch, elementName.ToString(), xmlSchemaElement2.QualifiedName.ToString());
                    }
                }
                else if (_partialValidationType is XmlSchemaType)
                {
                    XmlSchemaType xmlSchemaType = (XmlSchemaType)_partialValidationType;
                    schemaElementDecl = xmlSchemaType.ElementDecl;
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_ValidateElementInvalidCall, string.Empty);
                }
            }
            else
            {
                schemaElementDecl = _compiledSchemaInfo.GetElementDecl(elementName);
            }
        }
        return schemaElementDecl;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._isRoot, System.Xml.Schema.XmlSchemaValidator._partialValidationType, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Equals(), System.Xml.Schema.SchemaInfo.GetElementDecl(), System.SR.Sch_SchemaElementNameMismatch, System.SR.Sch_ValidateElementInvalidCall, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.XmlQualifiedName.ToString().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElement().