Terraria: System.Xml.Schema.XmlSchemaValidator.Init
Init()
void System.Xml.Schema.XmlSchemaValidator.Init () inline private
Definition at line 350 of file XmlSchemaValidator.cs.
    {
        _validationStack = new HWStack(10);
        _attPresence = new Hashtable();
        Push(XmlQualifiedName.Empty);
        _positionInfo = s_dummyPositionInfo;
        _validationEventSender = this;
        _currentState = ValidatorState.None;
        _textValue = new StringBuilder(100);
        _xmlResolver = null;
        _contextQName = new XmlQualifiedName();
        Reset();
        RecompileSchemaSet();
        _nsXs = _nameTable.Add("http://www.w3.org/2001/XMLSchema");
        _nsXsi = _nameTable.Add("http://www.w3.org/2001/XMLSchema-instance");
        _nsXmlNs = _nameTable.Add("http://www.w3.org/2000/xmlns/");
        _nsXml = _nameTable.Add("http://www.w3.org/XML/1998/namespace");
        _xsiTypeString = _nameTable.Add("type");
        _xsiNilString = _nameTable.Add("nil");
        _xsiSchemaLocationString = _nameTable.Add("schemaLocation");
        _xsiNoNamespaceSchemaLocationString = _nameTable.Add("noNamespaceSchemaLocation");
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Xml.Schema.XmlSchemaValidator._contextQName, System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsXml, System.Xml.Schema.XmlSchemaValidator._nsXmlNs, System.Xml.Schema.XmlSchemaValidator._nsXs, System.Xml.Schema.XmlSchemaValidator._nsXsi, System.Xml.Schema.XmlSchemaValidator._positionInfo, System.Xml.Schema.XmlSchemaValidator._textValue, System.Xml.Schema.XmlSchemaValidator._validationEventSender, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Schema.XmlSchemaValidator._xmlResolver, System.Xml.Schema.XmlSchemaValidator._xsiNilString, System.Xml.Schema.XmlSchemaValidator._xsiNoNamespaceSchemaLocationString, System.Xml.Schema.XmlSchemaValidator._xsiSchemaLocationString, System.Xml.Schema.XmlSchemaValidator._xsiTypeString, System.Xml.XmlNameTable.Add(), System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.XmlSchemaValidator.Push(), System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet(), System.Xml.Schema.XmlSchemaValidator.Reset(), and System.Xml.Schema.XmlSchemaValidator.s_dummyPositionInfo.
Referenced by System.Xml.Schema.XmlSchemaValidator.XmlSchemaValidator().