Terraria: System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes
CheckTokenizedTypes()
void System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes (XmlSchemaDatatype dtype, object typedValue, bool attrValue) inline private
Definition at line 1902 of file XmlSchemaValidator.cs.
    {
        if (typedValue == null)
        {
            return;
        }
        XmlTokenizedType tokenizedType = dtype.TokenizedType;
        if (tokenizedType != XmlTokenizedType.ENTITY && tokenizedType != XmlTokenizedType.ID && tokenizedType != XmlTokenizedType.IDREF)
        {
            return;
        }
        if (dtype.Variety == XmlSchemaDatatypeVariety.List)
        {
            string[] array = (string[])typedValue;
            for (int i = 0; i < array.Length; i++)
            {
                ProcessTokenizedType(dtype.TokenizedType, array[i], attrValue);
            }
        }
        else
        {
            ProcessTokenizedType(dtype.TokenizedType, (string)typedValue, attrValue);
        }
    }
References System.array, and System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType().
Referenced by System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), and System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().