Terraria: System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement
InternalValidateEndElement()
object System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement (XmlSchemaInfo schemaInfo, object typedValue) inline private
Definition at line 1118 of file XmlSchemaValidator.cs.
    {
        if (_validationStack.Length <= 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.Sch_InvalidEndElementMultiple, s_methodNames[9]));
        }
        CheckStateTransition(ValidatorState.EndElement, s_methodNames[9]);
        SchemaElementDecl elementDecl = _context.ElementDecl;
        XmlSchemaSimpleType memberType = null;
        XmlSchemaType schemaType = null;
        XmlSchemaElement schemaElement = null;
        string text = string.Empty;
        if (elementDecl != null)
        {
            if (_context.CheckRequiredAttribute && elementDecl.HasRequiredAttribute)
            {
                CheckRequiredAttributes(elementDecl);
            }
            if (!_context.IsNill && _context.NeedValidateChildren)
            {
                switch (elementDecl.ContentValidator.ContentType)
                {
                case XmlSchemaContentType.TextOnly:
                    if (typedValue == null)
                    {
                        text = _textValue.ToString();
                        typedValue = ValidateAtomicValue(text, out memberType);
                    }
                    else
                    {
                        typedValue = ValidateAtomicValue(typedValue, out memberType);
                    }
                    break;
                case XmlSchemaContentType.Mixed:
                    if (elementDecl.DefaultValueTyped != null && typedValue == null)
                    {
                        text = _textValue.ToString();
                        typedValue = CheckMixedValueConstraint(text);
                    }
                    break;
                case XmlSchemaContentType.ElementOnly:
                    if (typedValue != null)
                    {
                        throw new InvalidOperationException(System.SR.Sch_InvalidEndElementCallTyped);
                    }
                    break;
                }
                if (!elementDecl.ContentValidator.CompleteValidation(_context))
                {
                    CompleteValidationError(_context, _eventHandler, _nsResolver, _sourceUriString, _positionInfo.LineNumber, _positionInfo.LinePosition, _schemaSet);
                    _context.Validity = XmlSchemaValidity.Invalid;
                }
            }
            if (HasIdentityConstraints)
            {
                XmlSchemaType xmlSchemaType = ((memberType == null) ? elementDecl.SchemaType : memberType);
                EndElementIdentityConstraints(typedValue, text, xmlSchemaType.Datatype);
            }
            schemaType = elementDecl.SchemaType;
            schemaElement = GetSchemaElement();
        }
        if (schemaInfo != null)
        {
            schemaInfo.SchemaType = schemaType;
            schemaInfo.SchemaElement = schemaElement;
            schemaInfo.MemberType = memberType;
            schemaInfo.IsNil = _context.IsNill;
            schemaInfo.IsDefault = _context.IsDefault;
            if (_context.Validity == XmlSchemaValidity.NotKnown && StrictlyAssessed)
            {
                _context.Validity = XmlSchemaValidity.Valid;
            }
            schemaInfo.Validity = _context.Validity;
        }
        Pop();
        return typedValue;
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._eventHandler, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator._positionInfo, System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator._sourceUriString, System.Xml.Schema.XmlSchemaValidator._textValue, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Schema.XmlSchemaValidator.CheckMixedValueConstraint(), System.Xml.Schema.ValidationState.CheckRequiredAttribute, System.Xml.Schema.XmlSchemaValidator.CheckRequiredAttributes(), System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Schema.XmlSchemaValidator.CompleteValidationError(), System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.XmlSchemaValidator.EndElementIdentityConstraints(), System.SR.Format(), System.Xml.Schema.XmlSchemaValidator.GetSchemaElement(), System.Xml.Schema.XmlSchemaValidator.HasIdentityConstraints, System.Xml.Schema.ValidationState.IsDefault, System.Xml.Schema.ValidationState.IsNill, System.Xml.HWStack.Length, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XmlSchemaValidator.Pop(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.SR.Sch_InvalidEndElementCallTyped, System.SR.Sch_InvalidEndElementMultiple, System.Xml.Schema.XmlSchemaValidator.StrictlyAssessed, System.text, System.Text.StringBuilder.ToString(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), and System.Xml.Schema.ValidationState.Validity.
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateEndElement(), and System.Xml.Schema.XmlSchemaValidator.ValidateEndElement().