Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue
ValidateAtomicValue() [2/2]
object System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue (string stringValue, out XmlSchemaSimpleType memberType) inline private
Definition at line 1340 of file XmlSchemaValidator.cs.
    {
        object typedValue = null;
        memberType = null;
        if (!_context.IsNill)
        {
            SchemaElementDecl elementDecl = _context.ElementDecl;
            if (stringValue.Length == 0 && elementDecl.DefaultValueTyped != null)
            {
                SchemaElementDecl elementDeclBeforeXsi = _context.ElementDeclBeforeXsi;
                if (elementDeclBeforeXsi != null && elementDeclBeforeXsi != elementDecl)
                {
                    Exception ex = elementDecl.Datatype.TryParseValue(elementDecl.DefaultValueRaw, _nameTable, _nsResolver, out typedValue);
                    if (ex != null)
                    {
                        SendValidationEvent(System.SR.Sch_InvalidElementDefaultValue, new string[2]
{
                            elementDecl.DefaultValueRaw,
                            QNameString(_context.LocalName, _context.Namespace)
                        });
                    }
                    else
                    {
                        _context.IsDefault = true;
                    }
                }
                else
                {
                    _context.IsDefault = true;
                    typedValue = elementDecl.DefaultValueTyped;
                }
            }
            else
            {
                typedValue = CheckElementValue(stringValue);
            }
            XsdSimpleValue xsdSimpleValue = typedValue as XsdSimpleValue;
            XmlSchemaDatatype datatype = elementDecl.Datatype;
            if (xsdSimpleValue != null)
            {
                memberType = xsdSimpleValue.XmlType;
                typedValue = xsdSimpleValue.TypedValue;
                datatype = memberType.Datatype;
            }
            CheckTokenizedTypes(datatype, typedValue, attrValue: false);
        }
        return typedValue;
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator.CheckElementValue(), System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes(), System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.ElementDeclBeforeXsi, System.Xml.Schema.ValidationState.IsNill, System.SR.Sch_InvalidElementDefaultValue, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement().