Terraria: System.Xml.Schema.XmlSchemaValidator.ProcessEntity
ProcessEntity()
void System.Xml.Schema.XmlSchemaValidator.ProcessEntity (string name) inline private
Definition at line 2567 of file XmlSchemaValidator.cs.
    {
        if (_checkEntity)
        {
            IDtdEntityInfo dtdEntityInfo = null;
            if (_dtdSchemaInfo != null)
            {
                dtdEntityInfo = _dtdSchemaInfo.LookupEntity(name);
            }
            if (dtdEntityInfo == null)
            {
                SendValidationEvent(System.SR.Sch_UndeclaredEntity, name);
            }
            else if (dtdEntityInfo.IsUnparsedEntity)
            {
                SendValidationEvent(System.SR.Sch_UnparsedEntityRef, name);
            }
        }
    }
References System.Xml.Schema.XmlSchemaValidator._checkEntity, System.Xml.Schema.XmlSchemaValidator._dtdSchemaInfo, System.Xml.IDtdInfo.LookupEntity(), System.SR.Sch_UndeclaredEntity, System.SR.Sch_UnparsedEntityRef, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType().