Terraria: System.Xml.Schema.XmlSchemaValidator.LoadSchema
LoadSchema()
void System.Xml.Schema.XmlSchemaValidator.LoadSchema (string uri, string url) inline private
Definition at line 1743 of file XmlSchemaValidator.cs.
    {
        XmlReader xmlReader = null;
        try
        {
            Uri uri2 = _xmlResolver.ResolveUri(_sourceUri, url);
            Stream input = (Stream)_xmlResolver.GetEntity(uri2, null, null);
            XmlReaderSettings readerSettings = _schemaSet.ReaderSettings;
            readerSettings.CloseInput = true;
            readerSettings.XmlResolver = _xmlResolver;
            xmlReader = XmlReader.Create(input, readerSettings, uri2.ToString());
            _schemaSet.Add(uri, xmlReader, _validatedNamespaces);
            while (xmlReader.Read())
            {
            }
        }
        catch (XmlSchemaException ex)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2] { uri, ex.Message }, ex);
        }
        catch (Exception ex2)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2] { uri, ex2.Message }, ex2, XmlSeverityType.Warning);
        }
        finally
        {
            xmlReader?.Close();
        }
    }
References System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator._sourceUri, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._xmlResolver, System.Xml.Schema.XmlSchemaSet.Add(), System.Xml.XmlReader.Create(), System.Xml.Dictionary, System.Xml.XmlResolver.GetEntity(), System.input, System.Xml.Schema.XmlSchemaSet.ReaderSettings, System.Xml.XmlResolver.ResolveUri(), System.SR.Sch_CannotLoadSchema, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations().