Terraria: System.Xml.Schema.XmlSchemaValidator.ThrowDeclNotFoundWarningOrError
ThrowDeclNotFoundWarningOrError()
void System.Xml.Schema.XmlSchemaValidator.ThrowDeclNotFoundWarningOrError (bool declFound) inline private
Definition at line 1661 of file XmlSchemaValidator.cs.
    {
        if (declFound)
        {
            _processContents = (_context.ProcessContents = XmlSchemaContentProcessing.Skip);
            _context.NeedValidateChildren = false;
        }
        else if (HasSchema && _processContents == XmlSchemaContentProcessing.Strict)
        {
            _processContents = (_context.ProcessContents = XmlSchemaContentProcessing.Skip);
            _context.NeedValidateChildren = false;
            SendValidationEvent(System.SR.Sch_UndeclaredElement, QNameString(_context.LocalName, _context.Namespace));
        }
        else
        {
            SendValidationEvent(System.SR.Sch_NoElementSchemaFound, QNameString(_context.LocalName, _context.Namespace), XmlSeverityType.Warning);
        }
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.HasSchema, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_NoElementSchemaFound, System.SR.Sch_UndeclaredElement, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElement().