Terraria: System.Xml.Schema.XmlSchemaValidator.CheckForwardRefs
CheckForwardRefs()
void System.Xml.Schema.XmlSchemaValidator.CheckForwardRefs () inline private
Definition at line 1936 of file XmlSchemaValidator.cs.
    {
        IdRefNode idRefNode = _idRefListHead;
        while (idRefNode != null)
        {
            if (FindId(idRefNode.Id) == null)
            {
                SendValidationEvent(new XmlSchemaValidationException(System.SR.Sch_UndeclaredId, idRefNode.Id, _sourceUriString, idRefNode.LineNo, idRefNode.LinePos), XmlSeverityType.Error);
            }
            IdRefNode next = idRefNode.Next;
            idRefNode.Next = null;
            idRefNode = next;
        }
        _idRefListHead = null;
    }
References System.Xml.Schema.XmlSchemaValidator._idRefListHead, System.Xml.Schema.XmlSchemaValidator._sourceUriString, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.FindId(), System.SR.Sch_UndeclaredId, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.EndValidation().