Terraria: System.Xml.Schema.XmlSchemaValidator.Pop
Pop()
void System.Xml.Schema.XmlSchemaValidator.Pop () inline private
Definition at line 1470 of file XmlSchemaValidator.cs.
    {
        ValidationState validationState = (ValidationState)_validationStack.Pop();
        if (_startIDConstraint == _validationStack.Length)
        {
            _startIDConstraint = -1;
        }
        _context = (ValidationState)_validationStack.Peek();
        if (validationState.Validity == XmlSchemaValidity.Invalid)
        {
            _context.Validity = XmlSchemaValidity.Invalid;
        }
        if (validationState.ValidationSkipped)
        {
            _context.ValidationSkipped = true;
        }
        _processContents = _context.ProcessContents;
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Schema.XmlSchemaValidator._startIDConstraint, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Dictionary, System.Xml.HWStack.Length, System.Xml.HWStack.Peek(), System.Xml.HWStack.Pop(), and System.Xml.Schema.ValidationState.ProcessContents.
Referenced by System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(), and System.Xml.Schema.XmlSchemaValidator.SkipToEndElement().