Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateElementContext
ValidateElementContext()
object System.Xml.Schema.XmlSchemaValidator.ValidateElementContext (XmlQualifiedName elementName, out bool invalidElementInContext) inline private
Definition at line 1233 of file XmlSchemaValidator.cs.
    {
        object obj = null;
        int errorCode = 0;
        XmlSchemaElement xmlSchemaElement = null;
        invalidElementInContext = false;
        if (_context.NeedValidateChildren)
        {
            if (_context.IsNill)
            {
                SendValidationEvent(System.SR.Sch_ContentInNill, QNameString(_context.LocalName, _context.Namespace));
                return null;
            }
            ContentValidator contentValidator = _context.ElementDecl.ContentValidator;
            if (contentValidator.ContentType == XmlSchemaContentType.Mixed && _context.ElementDecl.Presence == SchemaDeclBase.Use.Fixed)
            {
                SendValidationEvent(System.SR.Sch_ElementInMixedWithFixed, QNameString(_context.LocalName, _context.Namespace));
                return null;
            }
            XmlQualifiedName xmlQualifiedName = elementName;
            bool flag = false;
            while (true)
            {
                obj = _context.ElementDecl.ContentValidator.ValidateElement(xmlQualifiedName, _context, out errorCode);
                if (obj != null)
                {
                    break;
                }
                if (errorCode == -2)
                {
                    SendValidationEvent(System.SR.Sch_AllElement, elementName.ToString());
                    invalidElementInContext = true;
                    _processContents = (_context.ProcessContents = XmlSchemaContentProcessing.Skip);
                    return null;
                }
                flag = true;
                xmlSchemaElement = GetSubstitutionGroupHead(xmlQualifiedName);
                if (xmlSchemaElement == null)
                {
                    break;
                }
                xmlQualifiedName = xmlSchemaElement.QualifiedName;
            }
            if (flag)
            {
                if (!(obj is XmlSchemaElement xmlSchemaElement2))
                {
                    obj = null;
                }
                else if (xmlSchemaElement2.RefName.IsEmpty)
                {
                    SendValidationEvent(System.SR.Sch_InvalidElementSubstitution, BuildElementName(elementName), BuildElementName(xmlSchemaElement2.QualifiedName));
                    invalidElementInContext = true;
                    _processContents = (_context.ProcessContents = XmlSchemaContentProcessing.Skip);
                }
                else
                {
                    obj = _compiledSchemaInfo.GetElement(elementName);
                    _context.NeedValidateChildren = true;
                }
            }
            if (obj == null)
            {
                ElementValidationError(elementName, _context, _eventHandler, _nsResolver, _sourceUriString, _positionInfo.LineNumber, _positionInfo.LinePosition, _schemaSet);
                invalidElementInContext = true;
                _processContents = (_context.ProcessContents = XmlSchemaContentProcessing.Skip);
            }
        }
        return obj;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._eventHandler, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator._positionInfo, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator._sourceUriString, System.Xml.Schema.XmlSchemaValidator.BuildElementName(), System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.XmlSchemaValidator.ElementValidationError(), System.Xml.Schema.SchemaInfo.GetElement(), System.Xml.Schema.XmlSchemaValidator.GetSubstitutionGroupHead(), System.Xml.Schema.ValidationState.IsNill, System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.ValidationState.NeedValidateChildren, System.obj, System.Xml.Schema.SchemaDeclBase.Presence, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_AllElement, System.SR.Sch_ContentInNill, System.SR.Sch_ElementInMixedWithFixed, System.SR.Sch_InvalidElementSubstitution, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.XmlQualifiedName.ToString(), and System.Xml.Schema.ContentValidator.ValidateElement().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElement().