Terraria: System.Xml.Schema.XmlSchemaValidator.GetSubstitutionGroupHead
GetSubstitutionGroupHead()
XmlSchemaElement System.Xml.Schema.XmlSchemaValidator.GetSubstitutionGroupHead (XmlQualifiedName member) inline private
Definition at line 1304 of file XmlSchemaValidator.cs.
    {
        XmlSchemaElement element = _compiledSchemaInfo.GetElement(member);
        if (element != null)
        {
            XmlQualifiedName substitutionGroup = element.SubstitutionGroup;
            if (!substitutionGroup.IsEmpty)
            {
                XmlSchemaElement element2 = _compiledSchemaInfo.GetElement(substitutionGroup);
                if (element2 != null)
                {
                    if ((element2.BlockResolved & XmlSchemaDerivationMethod.Substitution) != 0)
                    {
                        SendValidationEvent(System.SR.Sch_SubstitutionNotAllowed, new string[2]
{
                            member.ToString(),
                            substitutionGroup.ToString()
                        });
                        return null;
                    }
                    if (!XmlSchemaType.IsDerivedFrom(element.ElementSchemaType, element2.ElementSchemaType, element2.BlockResolved))
                    {
                        SendValidationEvent(System.SR.Sch_SubstitutionBlocked, new string[2]
{
                            member.ToString(),
                            substitutionGroup.ToString()
                        });
                        return null;
                    }
                    return element2;
                }
            }
        }
        return null;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaElement.ElementSchemaType, System.Xml.Schema.SchemaInfo.GetElement(), System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.SR.Sch_SubstitutionBlocked, System.SR.Sch_SubstitutionNotAllowed, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.Schema.XmlSchemaElement.SubstitutionGroup.
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElementContext().