Terraria: System.Xml.Schema.XmlSchemaValidator.AddSchema
AddSchema()
void System.Xml.Schema.XmlSchemaValidator.AddSchema (XmlSchema schema) inline
Definition at line 393 of file XmlSchemaValidator.cs.
    {
        if (schema == null)
        {
            throw new ArgumentNullException("schema");
        }
        if ((_validationFlags & XmlSchemaValidationFlags.ProcessInlineSchema) == 0)
        {
            return;
        }
        string text = schema.TargetNamespace;
        if (text == null)
        {
            text = string.Empty;
        }
        Hashtable schemaLocations = _schemaSet.SchemaLocations;
        DictionaryEntry[] array = new DictionaryEntry[schemaLocations.Count];
        schemaLocations.CopyTo(array, 0);
        if (_validatedNamespaces[text] != null && _schemaSet.FindSchemaByNSAndUrl(schema.BaseUri, text, array) == null)
        {
            SendValidationEvent(System.SR.Sch_ComponentAlreadySeenForNS, text, XmlSeverityType.Error);
        }
        if (schema.ErrorCount != 0)
        {
            return;
        }
        try
        {
            _schemaSet.Add(schema);
            RecompileSchemaSet();
        }
        catch (XmlSchemaException ex)
        {
            SendValidationEvent(System.SR.Sch_CannotLoadSchema, new string[2]
            {
                schema.BaseUri.ToString(),
                ex.Message
            }, ex);
        }
        for (int i = 0; i < schema.ImportedSchemas.Count; i++)
        {
            XmlSchema xmlSchema = (XmlSchema)schema.ImportedSchemas[i];
            text = xmlSchema.TargetNamespace;
            if (text == null)
            {
                text = string.Empty;
            }
            if (_validatedNamespaces[text] != null && _schemaSet.FindSchemaByNSAndUrl(xmlSchema.BaseUri, text, array) == null)
            {
                SendValidationEvent(System.SR.Sch_ComponentAlreadySeenForNS, text, XmlSeverityType.Error);
                _schemaSet.RemoveRecursive(schema);
                break;
            }
        }
    }
References System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._validationFlags, System.Xml.Schema.XmlSchemaSet.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchemaSet.FindSchemaByNSAndUrl(), System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet(), System.Xml.Schema.XmlSchemaSet.RemoveRecursive(), System.SR.Sch_CannotLoadSchema, System.SR.Sch_ComponentAlreadySeenForNS, System.Xml.Schema.XmlSchemaSet.SchemaLocations, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.text.
Referenced by System.Xml.XsdValidatingReader.ProcessInlineSchema(), and System.Xml.XsdValidatingReader.ProcessInlineSchemaAsync().