Terraria: System.Xml.Schema.XmlSchemaValidator.CheckStateTransition
CheckStateTransition()
void System.Xml.Schema.XmlSchemaValidator.CheckStateTransition (ValidatorState toState, string methodName) inline private
Definition at line 1952 of file XmlSchemaValidator.cs.
    {
        if (!ValidStates[(int)_currentState, (int)toState])
        {
            object[] args;
            if (_currentState == ValidatorState.None)
            {
                string sch_InvalidStartTransition = System.SR.Sch_InvalidStartTransition;
                args = new string[2]
                {
                    methodName,
                    s_methodNames[1]
                };
                throw new InvalidOperationException(System.SR.Format(sch_InvalidStartTransition, args));
            }
            string sch_InvalidStateTransition = System.SR.Sch_InvalidStateTransition;
            args = new string[2]
            {
                s_methodNames[(int)_currentState],
                methodName
            };
            throw new InvalidOperationException(System.SR.Format(sch_InvalidStateTransition, args));
        }
        _currentState = toState;
    }
References System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Dictionary, System.SR.Format(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.SR.Sch_InvalidStartTransition, System.SR.Sch_InvalidStateTransition, and System.Xml.Schema.XmlSchemaValidator.ValidStates.
Referenced by System.Xml.Schema.XmlSchemaValidator.EndValidation(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement(), System.Xml.Schema.XmlSchemaValidator.SkipToEndElement(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.Schema.XmlSchemaValidator.ValidateElement(), System.Xml.Schema.XmlSchemaValidator.ValidateEndOfAttributes(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().