Terraria: System.Xml.Schema.XmlSchemaValidator.EndValidation
EndValidation()
void System.Xml.Schema.XmlSchemaValidator.EndValidation () inline
Definition at line 966 of file XmlSchemaValidator.cs.
    {
        if (_validationStack.Length > 1)
        {
            throw new InvalidOperationException(System.SR.Sch_InvalidEndValidation);
        }
        CheckStateTransition(ValidatorState.Finish, s_methodNames[11]);
        CheckForwardRefs();
    }
References System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Schema.XmlSchemaValidator.CheckForwardRefs(), System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.HWStack.Length, System.Xml.Schema.XmlSchemaValidator.s_methodNames, and System.SR.Sch_InvalidEndValidation.
Referenced by System.Xml.XsdValidatingReader._ReadAsync_Read(), System.Xml.XsdValidatingReader.Read(), System.Xml.XsdValidatingReader.ReadAsync_Read(), System.Xml.DocumentSchemaValidator.Validate(), and System.Xml.Schema.XNodeValidator.Validate().