Terraria: System.Xml.Schema.XmlSchemaValidator.PrintExpectedElements
PrintExpectedElements()
static string System.Xml.Schema.XmlSchemaValidator.PrintExpectedElements (ArrayList expected, bool getParticles) inline static package
Definition at line 2413 of file XmlSchemaValidator.cs.
    {
        if (getParticles)
        {
            string sch_ContinuationString = System.SR.Sch_ContinuationString;
            object[] args = new string[1] { " " };
            string value = System.SR.Format(sch_ContinuationString, args);
            XmlSchemaParticle xmlSchemaParticle = null;
            XmlSchemaParticle xmlSchemaParticle2 = null;
            ArrayList arrayList = new ArrayList();
            StringBuilder stringBuilder = new StringBuilder();
            if (expected.Count == 1)
            {
                xmlSchemaParticle2 = expected[0] as XmlSchemaParticle;
            }
            else
            {
                for (int i = 1; i < expected.Count; i++)
                {
                    xmlSchemaParticle = expected[i - 1] as XmlSchemaParticle;
                    xmlSchemaParticle2 = expected[i] as XmlSchemaParticle;
                    XmlQualifiedName qualifiedName = xmlSchemaParticle.GetQualifiedName();
                    if (qualifiedName.Namespace != xmlSchemaParticle2.GetQualifiedName().Namespace)
                    {
                        arrayList.Add(qualifiedName);
                        PrintNamesWithNS(arrayList, stringBuilder);
                        arrayList.Clear();
                        stringBuilder.Append(value);
                    }
                    else
                    {
                        arrayList.Add(qualifiedName);
                    }
                }
            }
            arrayList.Add(xmlSchemaParticle2.GetQualifiedName());
            PrintNamesWithNS(arrayList, stringBuilder);
            return stringBuilder.ToString();
        }
        return PrintNames(expected);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.SR.Format(), System.Xml.Schema.XmlSchemaValidator.PrintNames(), System.Xml.Schema.XmlSchemaValidator.PrintNamesWithNS(), System.SR.Sch_ContinuationString, and System.value.