Terraria: System.Xml.Schema.XmlSchemaValidator.ElementValidationError
ElementValidationError()
static void System.Xml.Schema.XmlSchemaValidator.ElementValidationError (XmlQualifiedName name, ValidationState context, ValidationEventHandler eventHandler, object sender, string sourceUri, int lineNo, int linePos, XmlSchemaSet schemaSet) inline static package
Definition at line 2303 of file XmlSchemaValidator.cs.
    {
        ArrayList arrayList = null;
        if (context.ElementDecl == null)
        {
            return;
        }
        ContentValidator contentValidator = context.ElementDecl.ContentValidator;
        XmlSchemaContentType contentType = contentValidator.ContentType;
        if (contentType == XmlSchemaContentType.ElementOnly || (contentType == XmlSchemaContentType.Mixed && contentValidator != ContentValidator.Mixed && contentValidator != ContentValidator.Any))
        {
            bool flag = schemaSet != null;
            arrayList = ((!flag) ? contentValidator.ExpectedElements(context, isRequiredOnly: false) : contentValidator.ExpectedParticles(context, isRequiredOnly: false, schemaSet));
            if (arrayList == null || arrayList.Count == 0)
            {
                if (context.TooComplex)
                {
                    SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementContentComplex, new string[3]
                    {
                        BuildElementName(context.LocalName, context.Namespace),
                        BuildElementName(name),
                        System.SR.Sch_ComplexContentModel
                    }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
                }
                else
                {
                    SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementContent, new string[2]
                    {
                        BuildElementName(context.LocalName, context.Namespace),
                        BuildElementName(name)
                    }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
                }
            }
            else if (context.TooComplex)
            {
                SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementContentExpectingComplex, new string[4]
                {
                    BuildElementName(context.LocalName, context.Namespace),
                    BuildElementName(name),
                    PrintExpectedElements(arrayList, flag),
                    System.SR.Sch_ComplexContentModel
                }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
            }
            else
            {
                SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementContentExpecting, new string[3]
                {
                    BuildElementName(context.LocalName, context.Namespace),
                    BuildElementName(name),
                    PrintExpectedElements(arrayList, flag)
                }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
            }
        }
        else if (contentType == XmlSchemaContentType.Empty)
        {
            SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementInEmptyEx, new string[2]
            {
                QNameString(context.LocalName, context.Namespace),
                name.ToString()
            }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
        }
        else if (!contentValidator.IsOpen)
        {
            SendValidationEvent(eventHandler, sender, new XmlSchemaValidationException(System.SR.Sch_InvalidElementInTextOnlyEx, new string[2]
            {
                QNameString(context.LocalName, context.Namespace),
                name.ToString()
            }, sourceUri, lineNo, linePos), XmlSeverityType.Error);
        }
    }
References System.Xml.Schema.ContentValidator.Any, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ContentValidator.Mixed, System.SR.Sch_InvalidElementContent, System.SR.Sch_InvalidElementContentComplex, System.SR.Sch_InvalidElementContentExpecting, System.SR.Sch_InvalidElementContentExpectingComplex, System.SR.Sch_InvalidElementInEmptyEx, System.SR.Sch_InvalidElementInTextOnlyEx, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.Schema.ValidationState.TooComplex.
Referenced by System.Xml.Schema.DtdValidator.ValidateChildElement(), System.Xml.Schema.XdrValidator.ValidateChildElement(), System.Xml.Schema.XsdValidator.ValidateChildElement(), and System.Xml.Schema.XmlSchemaValidator.ValidateElementContext().