Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace
ValidateWhitespace() [1/3]
void System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace (string elementStringValue, XmlValueGetter elementValueGetter) inline private
Definition at line 873 of file XmlSchemaValidator.cs.
    {
        ValidatorState validatorState = ((_validationStack.Length > 1) ? ValidatorState.Whitespace : ValidatorState.TopLevelTextOrWS);
        CheckStateTransition(validatorState, s_methodNames[(int)validatorState]);
        if (!_context.NeedValidateChildren)
        {
            return;
        }
        if (_context.IsNill)
        {
            SendValidationEvent(System.SR.Sch_ContentInNill, QNameString(_context.LocalName, _context.Namespace));
        }
        switch (_context.ElementDecl.ContentValidator.ContentType)
        {
        case XmlSchemaContentType.Empty:
            SendValidationEvent(System.SR.Sch_InvalidWhitespaceInEmpty, string.Empty);
            break;
        case XmlSchemaContentType.TextOnly:
            if (elementValueGetter != null)
            {
                SaveTextValue(elementValueGetter());
            }
            else
            {
                SaveTextValue(elementStringValue);
            }
            break;
        case XmlSchemaContentType.Mixed:
            if (_context.ElementDecl.DefaultValueTyped != null)
            {
                if (elementValueGetter != null)
                {
                    SaveTextValue(elementValueGetter());
                }
                else
                {
                    SaveTextValue(elementStringValue);
                }
            }
            break;
        case XmlSchemaContentType.ElementOnly:
            break;
        }
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Schema.ContentValidator.ContentType, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.Xml.Schema.XmlSchemaValidator.SaveTextValue(), System.SR.Sch_ContentInNill, System.SR.Sch_InvalidWhitespaceInEmpty, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().