Terraria: System.Xml.Schema.XmlSchemaValidator.EndElementIdentityConstraints
EndElementIdentityConstraints()
void System.Xml.Schema.XmlSchemaValidator.EndElementIdentityConstraints (object typedValue, string stringValue, XmlSchemaDatatype datatype) inline private
Definition at line 2153 of file XmlSchemaValidator.cs.
    {
        string localName = _context.LocalName;
        string @namespace = _context.Namespace;
        for (int num = _validationStack.Length - 1; num >= _startIDConstraint; num--)
        {
            if (((ValidationState)_validationStack[num]).Constr != null)
            {
                ConstraintStruct[] constr = ((ValidationState)_validationStack[num]).Constr;
                for (int i = 0; i < constr.Length; i++)
                {
                    for (int j = 0; j < constr[i].axisFields.Count; j++)
                    {
                        LocatedActiveAxis locatedActiveAxis = (LocatedActiveAxis)constr[i].axisFields[j];
                        if (locatedActiveAxis.isMatched)
{
                            locatedActiveAxis.isMatched = false;
                            if (locatedActiveAxis.Ks[locatedActiveAxis.Column] != null)
{
                                SendValidationEvent(System.SR.Sch_FieldSingleValueExpected, localName);
                            }
                            else if (System.LocalAppContextSwitches.IgnoreEmptyKeySequences)
{
                                if (typedValue != null && stringValue.Length != 0)
{
                                    locatedActiveAxis.Ks[locatedActiveAxis.Column] = new TypedObject(typedValue, stringValue, datatype);
                                }
                            }
                            else if (typedValue != null)
{
                                locatedActiveAxis.Ks[locatedActiveAxis.Column] = new TypedObject(typedValue, stringValue, datatype);
                            }
                        }
                        locatedActiveAxis.EndElement(localName, @namespace);
                    }
                    if (!constr[i].axisSelector.EndElement(localName, @namespace))
                    {
                        continue;
                    }
                    KeySequence keySequence = constr[i].axisSelector.PopKS();
                    switch (constr[i].constraint.Role)
                    {
                    case CompiledIdentityConstraint.ConstraintRole.Key:
                        if (!keySequence.IsQualified())
{
                            SendValidationEvent(new XmlSchemaValidationException(System.SR.Sch_MissingKey, constr[i].constraint.name.ToString(), _sourceUriString, keySequence.PosLine, keySequence.PosCol));
                        }
                        else if (constr[i].qualifiedTable.Contains(keySequence))
{
                            SendValidationEvent(new XmlSchemaValidationException(System.SR.Sch_DuplicateKey, new string[2]
{
                                keySequence.ToString(),
                                constr[i].constraint.name.ToString()
                            }, _sourceUriString, keySequence.PosLine, keySequence.PosCol));
                        }
                        else
{
                            constr[i].qualifiedTable.Add(keySequence, keySequence);
                        }
                        break;
                    case CompiledIdentityConstraint.ConstraintRole.Unique:
                        if (keySequence.IsQualified())
{
                            if (constr[i].qualifiedTable.Contains(keySequence))
{
                                SendValidationEvent(new XmlSchemaValidationException(System.SR.Sch_DuplicateKey, new string[2]
{
                                    keySequence.ToString(),
                                    constr[i].constraint.name.ToString()
                                }, _sourceUriString, keySequence.PosLine, keySequence.PosCol));
                            }
                            else
{
                                constr[i].qualifiedTable.Add(keySequence, keySequence);
                            }
                        }
                        break;
                    case CompiledIdentityConstraint.ConstraintRole.Keyref:
                        if (constr[i].qualifiedTable != null && keySequence.IsQualified() && !constr[i].qualifiedTable.Contains(keySequence))
{
                            constr[i].qualifiedTable.Add(keySequence, keySequence);
                        }
                        break;
                    }
                }
            }
        }
        ConstraintStruct[] constr2 = ((ValidationState)_validationStack[_validationStack.Length - 1]).Constr;
        if (constr2 == null)
        {
            return;
        }
        for (int k = 0; k < constr2.Length; k++)
        {
            if (constr2[k].constraint.Role == CompiledIdentityConstraint.ConstraintRole.Keyref || constr2[k].keyrefTable == null)
            {
                continue;
            }
            foreach (KeySequence key in constr2[k].keyrefTable.Keys)
            {
                if (!constr2[k].qualifiedTable.Contains(key))
                {
                    SendValidationEvent(new XmlSchemaValidationException(System.SR.Sch_UnresolvedKeyref, new string[2]
                    {
                        key.ToString(),
                        constr2[k].constraint.name.ToString()
                    }, _sourceUriString, key.PosLine, key.PosCol));
                }
            }
        }
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.LocalAppContextSwitches.IgnoreEmptyKeySequences, System.key, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, System.Xml.HWStack.Length, System.Xml.Schema.ValidationState.LocalName, System.SR.Sch_DuplicateKey, System.SR.Sch_FieldSingleValueExpected, System.SR.Sch_MissingKey, and System.SR.Sch_UnresolvedKeyref.
Referenced by System.Xml.Schema.XmlSchemaValidator.InternalValidateEndElement().