Terraria: System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix
GetDefaultAttributePrefix()
string System.Xml.Schema.XmlSchemaValidator.GetDefaultAttributePrefix (string attributeNS) inline package
Definition at line 2016 of file XmlSchemaValidator.cs.
    {
        IDictionary<string, string> namespacesInScope = _nsResolver.GetNamespacesInScope(XmlNamespaceScope.All);
        string text = null;
        foreach (KeyValuePair<string, string> item in namespacesInScope)
        {
            string strA = _nameTable.Add(item.Value);
            if (Ref.Equal(strA, attributeNS))
            {
                text = item.Key;
                if (text.Length != 0)
                {
                    return text;
                }
            }
        }
        return text;
    }
References System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.XmlNameTable.Add(), System.Xml.Ref.Equal(), System.Xml.IXmlNamespaceResolver.GetNamespacesInScope(), System.item, and System.text.
Referenced by System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes().