Terraria: System.Xml.Schema.XmlSchemaValidator.SendValidationEvent
SendValidationEvent() [1/11]
void System.Xml.Schema.XmlSchemaValidator.SendValidationEvent (string code) inline private
Definition at line 2587 of file XmlSchemaValidator.cs.
    {
        SendValidationEvent(code, string.Empty);
    }
References System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.AddIdentityConstraints(), System.Xml.Schema.XmlSchemaValidator.AddSchema(), System.Xml.Schema.XmlSchemaValidator.AttributeIdentityConstraints(), System.Xml.Schema.XmlSchemaValidator.CheckAttributeValue(), System.Xml.Schema.XmlSchemaValidator.CheckElementProperties(), System.Xml.Schema.XmlSchemaValidator.CheckElementValue(), System.Xml.Schema.XmlSchemaValidator.CheckForwardRefs(), System.Xml.Schema.XmlSchemaValidator.CheckMixedValueConstraint(), System.Xml.Schema.XmlSchemaValidator.CheckRequiredAttributes(), System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil(), System.Xml.Schema.XmlSchemaValidator.CompleteValidationError(), System.Xml.Schema.XmlSchemaValidator.ElementValidationError(), System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl(), System.Xml.Schema.XmlSchemaValidator.GetSubstitutionGroupHead(), System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), System.Xml.Schema.XmlSchemaValidator.LoadSchema(), System.Xml.Schema.XmlSchemaValidator.ProcessEntity(), System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations(), System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType(), System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), System.Xml.Schema.XmlSchemaValidator.ThrowDeclNotFoundWarningOrError(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), System.Xml.Schema.XmlSchemaValidator.ValidateAttribute(), System.Xml.Schema.XmlSchemaValidator.ValidateElementContext(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().