Terraria: System.Xml.Schema.XmlSchemaValidator.AddXsiAttributes
AddXsiAttributes()
void System.Xml.Schema.XmlSchemaValidator.AddXsiAttributes (ArrayList attList) inline private
Definition at line 1489 of file XmlSchemaValidator.cs.
    {
        BuildXsiAttributes();
        if (_attPresence[s_xsiTypeSO.QualifiedName] == null)
        {
            attList.Add(s_xsiTypeSO);
        }
        if (_attPresence[s_xsiNilSO.QualifiedName] == null)
        {
            attList.Add(s_xsiNilSO);
        }
        if (_attPresence[s_xsiSLSO.QualifiedName] == null)
        {
            attList.Add(s_xsiSLSO);
        }
        if (_attPresence[s_xsiNoNsSLSO.QualifiedName] == null)
        {
            attList.Add(s_xsiNoNsSLSO);
        }
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaValidator.BuildXsiAttributes(), System.Xml.Schema.XmlSchemaValidator.s_xsiNilSO, System.Xml.Schema.XmlSchemaValidator.s_xsiNoNsSLSO, System.Xml.Schema.XmlSchemaValidator.s_xsiSLSO, and System.Xml.Schema.XmlSchemaValidator.s_xsiTypeSO.
Referenced by System.Xml.Schema.XmlSchemaValidator.GetExpectedAttributes().