Terraria: System.Xml.Schema.XmlSchemaValidator.CheckIsXmlAttribute
CheckIsXmlAttribute()
SchemaAttDef System.Xml.Schema.XmlSchemaValidator.CheckIsXmlAttribute (XmlQualifiedName attQName) inline private
Definition at line 1700 of file XmlSchemaValidator.cs.
    {
        SchemaAttDef value = null;
        if (Ref.Equal(attQName.Namespace, _nsXml) && (_validationFlags & XmlSchemaValidationFlags.AllowXmlAttributes) != 0)
        {
            if (!_compiledSchemaInfo.Contains(_nsXml))
            {
                AddXmlNamespaceSchema();
            }
            _compiledSchemaInfo.AttributeDecls.TryGetValue(attQName, out value);
        }
        return value;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._nsXml, System.Xml.Schema.XmlSchemaValidator._validationFlags, System.Xml.Schema.XmlSchemaValidator.AddXmlNamespaceSchema(), System.Xml.Schema.SchemaInfo.AttributeDecls, System.Xml.Schema.SchemaInfo.Contains(), System.Xml.Ref.Equal(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().