Terraria: System.Xml.Schema.XmlSchemaValidator.CheckElementValue
CheckElementValue()
object System.Xml.Schema.XmlSchemaValidator.CheckElementValue (string stringValue) inline private
Definition at line 1878 of file XmlSchemaValidator.cs.
    {
        object typedValue = null;
        SchemaDeclBase elementDecl = _context.ElementDecl;
        XmlSchemaDatatype datatype = elementDecl.Datatype;
        Exception ex = datatype.TryParseValue(stringValue, _nameTable, _nsResolver, out typedValue);
        if (ex != null)
        {
            SendValidationEvent(System.SR.Sch_ElementValueDataTypeDetailed, new string[4]
            {
                QNameString(_context.LocalName, _context.Namespace),
                stringValue,
                GetTypeName(elementDecl),
                ex.Message
            }, ex);
            return null;
        }
        if (!elementDecl.CheckValue(typedValue))
        {
            SendValidationEvent(System.SR.Sch_FixedElementValue, QNameString(_context.LocalName, _context.Namespace));
        }
        return typedValue;
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.SR.Sch_ElementValueDataTypeDetailed, System.SR.Sch_FixedElementValue, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.Schema.XmlSchemaDatatype.TryParseValue().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue().