Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateText
ValidateText() [1/3]
void System.Xml.Schema.XmlSchemaValidator.ValidateText (string elementStringValue, XmlValueGetter elementValueGetter) inline private
Definition at line 792 of file XmlSchemaValidator.cs.
    {
        ValidatorState validatorState = ((_validationStack.Length > 1) ? ValidatorState.Text : ValidatorState.TopLevelTextOrWS);
        CheckStateTransition(validatorState, s_methodNames[(int)validatorState]);
        if (!_context.NeedValidateChildren)
        {
            return;
        }
        if (_context.IsNill)
        {
            SendValidationEvent(System.SR.Sch_ContentInNill, QNameString(_context.LocalName, _context.Namespace));
            return;
        }
        switch (_context.ElementDecl.ContentValidator.ContentType)
        {
        case XmlSchemaContentType.Empty:
            SendValidationEvent(System.SR.Sch_InvalidTextInEmpty, string.Empty);
            break;
        case XmlSchemaContentType.TextOnly:
            if (elementValueGetter != null)
            {
                SaveTextValue(elementValueGetter());
            }
            else
            {
                SaveTextValue(elementStringValue);
            }
            break;
        case XmlSchemaContentType.ElementOnly:
        {
            string str = ((elementValueGetter != null) ? elementValueGetter().ToString() : elementStringValue);
            if (!XmlCharType.IsOnlyWhitespace(str))
            {
                ArrayList arrayList = _context.ElementDecl.ContentValidator.ExpectedParticles(_context, isRequiredOnly: false, _schemaSet);
                if (arrayList == null || arrayList.Count == 0)
                {
                    SendValidationEvent(System.SR.Sch_InvalidTextInElement, BuildElementName(_context.LocalName, _context.Namespace));
                    break;
                }
                SendValidationEvent(System.SR.Sch_InvalidTextInElementExpecting, new string[2]
                {
                    BuildElementName(_context.LocalName, _context.Namespace),
                    PrintExpectedElements(arrayList, getParticles: true)
                });
            }
            break;
        }
        case XmlSchemaContentType.Mixed:
            if (_context.ElementDecl.DefaultValueTyped != null)
            {
                if (elementValueGetter != null)
                {
                    SaveTextValue(elementValueGetter());
                }
                else
                {
                    SaveTextValue(elementStringValue);
                }
            }
            break;
        }
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._schemaSet, System.Xml.Schema.XmlSchemaValidator.BuildElementName(), System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Schema.ContentValidator.ContentType, System.Xml.Schema.SchemaElementDecl.ContentValidator, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.SchemaDeclBase.DefaultValueTyped, System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.Schema.ContentValidator.ExpectedParticles(), System.Xml.Schema.ValidationState.IsNill, System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.ValidationState.NeedValidateChildren, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.Xml.Schema.XmlSchemaValidator.SaveTextValue(), System.SR.Sch_ContentInNill, System.SR.Sch_InvalidTextInElement, System.SR.Sch_InvalidTextInElementExpecting, System.SR.Sch_InvalidTextInEmpty, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.str.