Terraria: System.Xml.Schema.XmlSchemaValidator.ValidateElement
ValidateElement() [2/2]
void System.Xml.Schema.XmlSchemaValidator.ValidateElement (string localName, string namespaceUri, XmlSchemaInfo? schemaInfo, string? xsiType, string? xsiNil, string? xsiSchemaLocation, string? xsiNoNamespaceSchemaLocation) inline
Definition at line 495 of file XmlSchemaValidator.cs.
    {
        if (localName == null)
        {
            throw new ArgumentNullException("localName");
        }
        if (namespaceUri == null)
        {
            throw new ArgumentNullException("namespaceUri");
        }
        CheckStateTransition(ValidatorState.Element, s_methodNames[4]);
        ClearPSVI();
        _contextQName.Init(localName, namespaceUri);
        XmlQualifiedName contextQName = _contextQName;
        bool invalidElementInContext;
        object particle = ValidateElementContext(contextQName, out invalidElementInContext);
        SchemaElementDecl schemaElementDecl = FastGetElementDecl(contextQName, particle);
        Push(contextQName);
        if (invalidElementInContext)
        {
            _context.Validity = XmlSchemaValidity.Invalid;
        }
        if ((_validationFlags & XmlSchemaValidationFlags.ProcessSchemaLocation) != 0 && _xmlResolver != null)
        {
            ProcessSchemaLocations(xsiSchemaLocation, xsiNoNamespaceSchemaLocation);
        }
        if (_processContents != XmlSchemaContentProcessing.Skip)
        {
            if (schemaElementDecl == null && _partialValidationType == null)
            {
                schemaElementDecl = _compiledSchemaInfo.GetElementDecl(contextQName);
            }
            bool declFound = schemaElementDecl != null;
            if (xsiType != null || xsiNil != null)
            {
                schemaElementDecl = CheckXsiTypeAndNil(schemaElementDecl, xsiType, xsiNil, ref declFound);
            }
            if (schemaElementDecl == null)
            {
                ThrowDeclNotFoundWarningOrError(declFound);
            }
        }
        _context.ElementDecl = schemaElementDecl;
        XmlSchemaElement schemaElement = null;
        XmlSchemaType schemaType = null;
        if (schemaElementDecl != null)
        {
            CheckElementProperties();
            _attPresence.Clear();
            _context.NeedValidateChildren = _processContents != XmlSchemaContentProcessing.Skip;
            ValidateStartElementIdentityConstraints();
            schemaElementDecl.ContentValidator.InitValidation(_context);
            schemaType = schemaElementDecl.SchemaType;
            schemaElement = GetSchemaElement();
        }
        if (schemaInfo != null)
        {
            schemaInfo.SchemaType = schemaType;
            schemaInfo.SchemaElement = schemaElement;
            schemaInfo.IsNil = _context.IsNill;
            schemaInfo.Validity = _context.Validity;
        }
        if (ProcessSchemaHints && _validatedNamespaces[namespaceUri] == null)
        {
            _validatedNamespaces.Add(namespaceUri, namespaceUri);
        }
        if (_isRoot)
        {
            _isRoot = false;
        }
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._contextQName, System.Xml.Schema.XmlSchemaValidator._isRoot, System.Xml.Schema.XmlSchemaValidator._partialValidationType, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Schema.XmlSchemaValidator._validatedNamespaces, System.Xml.Schema.XmlSchemaValidator._validationFlags, System.Xml.Schema.XmlSchemaValidator._xmlResolver, System.Collections.Hashtable.Add(), System.Xml.Schema.XmlSchemaValidator.CheckElementProperties(), System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil(), System.Collections.Hashtable.Clear(), System.Xml.Schema.XmlSchemaValidator.ClearPSVI(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.FastGetElementDecl(), System.Xml.Schema.SchemaInfo.GetElementDecl(), System.Xml.Schema.XmlSchemaValidator.GetSchemaElement(), System.Xml.XmlQualifiedName.Init(), System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.XmlSchemaValidator.ProcessSchemaHints, System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations(), System.Xml.Schema.XmlSchemaValidator.Push(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.Xml.Schema.XmlSchemaValidator.ThrowDeclNotFoundWarningOrError(), System.Xml.Schema.XmlSchemaValidator.ValidateElementContext(), System.Xml.Schema.XmlSchemaValidator.ValidateStartElementIdentityConstraints(), and System.Xml.Schema.ValidationState.Validity.