Terraria: System.Xml.Schema.XmlSchemaValidator.QNameString
QNameString()
static string System.Xml.Schema.XmlSchemaValidator.QNameString (string localName, string ns) inline static package
Definition at line 2544 of file XmlSchemaValidator.cs.
    {
        if (ns.Length == 0)
        {
            return localName;
        }
        return ns + ":" + localName;
    }
Referenced by System.Xml.Schema.XmlSchemaValidator.AddIdentityConstraints(), System.Xml.Schema.XsdValidator.AddIdentityConstraints(), System.Xml.Schema.XmlSchemaValidator.CheckElementProperties(), System.Xml.Schema.XmlSchemaValidator.CheckElementValue(), System.Xml.Schema.DtdValidator.CheckValue(), System.Xml.Schema.XdrValidator.CheckValue(), System.Xml.Schema.XsdValidator.CheckValue(), System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil(), System.Xml.Schema.DtdValidator.ProcessElement(), System.Xml.Schema.XsdValidator.ProcessElement(), System.Xml.Schema.XdrValidator.ThoroughGetElementDecl(), System.Xml.Schema.XsdValidator.ThoroughGetElementDecl(), System.Xml.Schema.XmlSchemaValidator.ThrowDeclNotFoundWarningOrError(), System.Xml.Schema.XmlSchemaValidator.ValidateAtomicValue(), System.Xml.Schema.XmlSchemaValidator.ValidateElementContext(), System.Xml.Schema.XsdValidator.ValidateStartElement(), System.Xml.Schema.BaseValidator.ValidateText(), System.Xml.Schema.XmlSchemaValidator.ValidateText(), System.Xml.Schema.BaseValidator.ValidateWhitespace(), and System.Xml.Schema.XmlSchemaValidator.ValidateWhitespace().