Terraria: System.Xml.Schema.XmlSchemaValidator.Push
Push()
void System.Xml.Schema.XmlSchemaValidator.Push (XmlQualifiedName elementName) inline private
Definition at line 1448 of file XmlSchemaValidator.cs.
    {
        _context = (ValidationState)_validationStack.Push();
        if (_context == null)
        {
            _context = new ValidationState();
            _validationStack.AddToTop(_context);
        }
        _context.LocalName = elementName.Name;
        _context.Namespace = elementName.Namespace;
        _context.HasMatched = false;
        _context.IsNill = false;
        _context.IsDefault = false;
        _context.CheckRequiredAttribute = true;
        _context.ValidationSkipped = false;
        _context.Validity = XmlSchemaValidity.NotKnown;
        _context.NeedValidateChildren = false;
        _context.ProcessContents = _processContents;
        _context.ElementDeclBeforeXsi = null;
        _context.Constr = null;
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.HWStack.AddToTop(), System.Xml.Dictionary, System.Xml.XmlQualifiedName.Name, System.Xml.XmlQualifiedName.Namespace, and System.Xml.HWStack.Push().
Referenced by System.Xml.Schema.XmlSchemaValidator.Init(), and System.Xml.Schema.XmlSchemaValidator.ValidateElement().