Terraria: System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations
ProcessSchemaLocations()
void System.Xml.Schema.XmlSchemaValidator.ProcessSchemaLocations (string xsiSchemaLocation, string xsiNoNamespaceSchemaLocation) inline private
Definition at line 1196 of file XmlSchemaValidator.cs.
    {
        bool flag = false;
        if (xsiNoNamespaceSchemaLocation != null)
        {
            flag = true;
            LoadSchema(string.Empty, xsiNoNamespaceSchemaLocation);
        }
        if (xsiSchemaLocation != null)
        {
            object typedValue;
            Exception ex = s_dtStringArray.TryParseValue(xsiSchemaLocation, _nameTable, _nsResolver, out typedValue);
            if (ex != null)
            {
                SendValidationEvent(System.SR.Sch_InvalidValueDetailedAttribute, new string[4] { "schemaLocation", xsiSchemaLocation, s_dtStringArray.TypeCodeString, ex.Message }, ex);
                return;
            }
            string[] array = (string[])typedValue;
            flag = true;
            try
            {
                for (int i = 0; i < array.Length - 1; i += 2)
                {
                    LoadSchema(array[i], array[i + 1]);
                }
            }
            catch (XmlSchemaException e)
            {
                SendValidationEvent(e);
            }
        }
        if (flag)
        {
            RecompileSchemaSet();
        }
    }
References System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.array, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaValidator.LoadSchema(), System.Xml.Schema.XmlSchemaValidator.RecompileSchemaSet(), System.Xml.Schema.XmlSchemaValidator.s_dtStringArray, System.SR.Sch_InvalidValueDetailedAttribute, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElement().