Terraria: System.Xml.Schema.XmlSchemaValidator.GetExpectedAttributes
GetExpectedAttributes()
XmlSchemaAttribute[] System.Xml.Schema.XmlSchemaValidator.GetExpectedAttributes () inline
Definition at line 1007 of file XmlSchemaValidator.cs.
    {
        if (_currentState == ValidatorState.Element || _currentState == ValidatorState.Attribute)
        {
            SchemaElementDecl elementDecl = _context.ElementDecl;
            ArrayList arrayList = new ArrayList();
            if (elementDecl != null)
            {
                foreach (SchemaAttDef value in elementDecl.AttDefs.Values)
                {
                    if (_attPresence[value.Name] == null)
                    {
                        arrayList.Add(value.SchemaAttribute);
                    }
                }
            }
            if (_nsResolver.LookupPrefix(_nsXsi) != null)
            {
                AddXsiAttributes(arrayList);
            }
            return arrayList.ToArray(typeof(XmlSchemaAttribute)) as XmlSchemaAttribute[];
        }
        if (_currentState == ValidatorState.Start && _partialValidationType != null && _partialValidationType is XmlSchemaAttribute xmlSchemaAttribute)
        {
            return new XmlSchemaAttribute[1] { xmlSchemaAttribute };
        }
        return Array.Empty<XmlSchemaAttribute>();
    }
References System.Xml.Schema.XmlSchemaValidator._attPresence, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator._nsXsi, System.Xml.Schema.XmlSchemaValidator._partialValidationType, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaValidator.AddXsiAttributes(), System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.Xml.IXmlNamespaceResolver.LookupPrefix(), System.value, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.