Terraria: System.Xml.Schema.XmlSchemaValidator.AttributeIdentityConstraints
AttributeIdentityConstraints()
void System.Xml.Schema.XmlSchemaValidator.AttributeIdentityConstraints (string name, string ns, object obj, string sobj, XmlSchemaDatatype datatype) inline private
Definition at line 2123 of file XmlSchemaValidator.cs.
    {
        for (int i = _startIDConstraint; i < _validationStack.Length; i++)
        {
            if (((ValidationState)_validationStack[i]).Constr == null)
            {
                continue;
            }
            ConstraintStruct[] constr = ((ValidationState)_validationStack[i]).Constr;
            for (int j = 0; j < constr.Length; j++)
            {
                for (int k = 0; k < constr[j].axisFields.Count; k++)
                {
                    LocatedActiveAxis locatedActiveAxis = (LocatedActiveAxis)constr[j].axisFields[k];
                    if (locatedActiveAxis.MoveToAttribute(name, ns))
                    {
                        if (locatedActiveAxis.Ks[locatedActiveAxis.Column] != null)
{
                            SendValidationEvent(System.SR.Sch_FieldSingleValueExpected, name);
                        }
                        else
{
                            locatedActiveAxis.Ks[locatedActiveAxis.Column] = new TypedObject(obj, sobj, datatype);
                        }
                    }
                }
            }
        }
    }
References System.Xml.Schema.XmlSchemaValidator._startIDConstraint, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.HWStack.Length, System.obj, System.SR.Sch_FieldSingleValueExpected, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.GetUnspecifiedDefaultAttributes(), and System.Xml.Schema.XmlSchemaValidator.ValidateAttribute().