Terraria: System.Xml.Schema.XmlSchemaValidator.PrintNamesWithNS
PrintNamesWithNS()
static void System.Xml.Schema.XmlSchemaValidator.PrintNamesWithNS (ArrayList expected, StringBuilder builder) inline static private
Definition at line 2469 of file XmlSchemaValidator.cs.
    {
        XmlQualifiedName xmlQualifiedName = expected[0] as XmlQualifiedName;
        if (expected.Count == 1)
        {
            if (xmlQualifiedName.Name == "*")
            {
                EnumerateAny(builder, xmlQualifiedName.Namespace);
            }
            else if (xmlQualifiedName.Namespace.Length != 0)
            {
                builder.Append(System.SR.Format(System.SR.Sch_ElementNameAndNamespace, xmlQualifiedName.Name, xmlQualifiedName.Namespace));
            }
            else
            {
                builder.Append(System.SR.Format(System.SR.Sch_ElementName, xmlQualifiedName.Name));
            }
            return;
        }
        bool flag = false;
        bool flag2 = true;
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i < expected.Count; i++)
        {
            xmlQualifiedName = expected[i] as XmlQualifiedName;
            if (xmlQualifiedName.Name == "*")
            {
                flag = true;
                continue;
            }
            if (flag2)
            {
                flag2 = false;
            }
            else
            {
                stringBuilder.Append(", ");
            }
            stringBuilder.Append(xmlQualifiedName.Name);
        }
        if (flag)
        {
            stringBuilder.Append(", ");
            stringBuilder.Append(System.SR.Sch_AnyElement);
        }
        else if (xmlQualifiedName.Namespace.Length != 0)
        {
            builder.Append(System.SR.Format(System.SR.Sch_ElementNameAndNamespace, stringBuilder, xmlQualifiedName.Namespace));
        }
        else
        {
            builder.Append(System.SR.Format(System.SR.Sch_ElementName, stringBuilder));
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchemaValidator.EnumerateAny(), System.SR.Format(), System.SR.Sch_AnyElement, System.SR.Sch_ElementName, and System.SR.Sch_ElementNameAndNamespace.
Referenced by System.Xml.Schema.XmlSchemaValidator.PrintExpectedElements().