Terraria: System.Xml.Schema.XmlSchemaValidator.SkipToEndElement
SkipToEndElement()
void System.Xml.Schema.XmlSchemaValidator.SkipToEndElement (XmlSchemaInfo? schemaInfo) inline
Definition at line 936 of file XmlSchemaValidator.cs.
    {
        if (_validationStack.Length <= 1)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.Sch_InvalidEndElementMultiple, s_methodNames[10]));
        }
        CheckStateTransition(ValidatorState.SkipToEndElement, s_methodNames[10]);
        if (schemaInfo != null)
        {
            SchemaElementDecl elementDecl = _context.ElementDecl;
            if (elementDecl != null)
            {
                schemaInfo.SchemaType = elementDecl.SchemaType;
                schemaInfo.SchemaElement = GetSchemaElement();
            }
            else
            {
                schemaInfo.SchemaType = null;
                schemaInfo.SchemaElement = null;
            }
            schemaInfo.MemberType = null;
            schemaInfo.IsNil = _context.IsNill;
            schemaInfo.IsDefault = _context.IsDefault;
            schemaInfo.Validity = _context.Validity;
        }
        _context.ValidationSkipped = true;
        _currentState = ValidatorState.SkipToEndElement;
        Pop();
    }
References System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._currentState, System.Xml.Schema.XmlSchemaValidator._validationStack, System.Xml.Schema.XmlSchemaValidator.CheckStateTransition(), System.Xml.Dictionary, System.Xml.Schema.ValidationState.ElementDecl, System.SR.Format(), System.Xml.Schema.XmlSchemaValidator.GetSchemaElement(), System.Xml.Schema.ValidationState.IsDefault, System.Xml.Schema.ValidationState.IsNill, System.Xml.HWStack.Length, System.Xml.Schema.XmlSchemaValidator.Pop(), System.Xml.Schema.XmlSchemaValidator.s_methodNames, System.SR.Sch_InvalidEndElementMultiple, and System.Xml.Schema.ValidationState.Validity.
Referenced by System.Xml.XsdValidatingReader.Skip(), System.Xml.XsdValidatingReader.SkipAsync(), and System.Xml.DocumentSchemaValidator.ValidateSingleElement().