Terraria: System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil
CheckXsiTypeAndNil()
SchemaElementDecl System.Xml.Schema.XmlSchemaValidator.CheckXsiTypeAndNil (SchemaElementDecl elementDecl, string xsiType, string xsiNil, ref bool declFound) inline private
Definition at line 1559 of file XmlSchemaValidator.cs.
    {
        XmlQualifiedName xmlQualifiedName = XmlQualifiedName.Empty;
        if (xsiType != null)
        {
            object typedValue = null;
            Exception ex = s_dtQName.TryParseValue(xsiType, _nameTable, _nsResolver, out typedValue);
            if (ex != null)
            {
                SendValidationEvent(System.SR.Sch_InvalidValueDetailedAttribute, new string[4] { "type", xsiType, s_dtQName.TypeCodeString, ex.Message }, ex);
            }
            else
            {
                xmlQualifiedName = typedValue as XmlQualifiedName;
            }
        }
        if (elementDecl != null)
        {
            if (elementDecl.IsNillable)
            {
                if (xsiNil != null)
                {
                    _context.IsNill = XmlConvert.ToBoolean(xsiNil);
                    if (_context.IsNill && elementDecl.Presence == SchemaDeclBase.Use.Fixed)
                    {
                        SendValidationEvent(System.SR.Sch_XsiNilAndFixed);
                    }
                }
            }
            else if (xsiNil != null)
            {
                SendValidationEvent(System.SR.Sch_InvalidXsiNill);
            }
        }
        if (xmlQualifiedName.IsEmpty)
        {
            if (elementDecl != null && elementDecl.IsAbstract)
            {
                SendValidationEvent(System.SR.Sch_AbstractElement, QNameString(_context.LocalName, _context.Namespace));
                elementDecl = null;
            }
        }
        else
        {
            SchemaElementDecl schemaElementDecl = _compiledSchemaInfo.GetTypeDecl(xmlQualifiedName);
            XmlSeverityType severity = XmlSeverityType.Warning;
            if (HasSchema && _processContents == XmlSchemaContentProcessing.Strict)
            {
                severity = XmlSeverityType.Error;
            }
            if (schemaElementDecl == null && xmlQualifiedName.Namespace == _nsXs)
            {
                XmlSchemaType xmlSchemaType = DatatypeImplementation.GetSimpleTypeFromXsdType(xmlQualifiedName);
                if (xmlSchemaType == null)
                {
                    xmlSchemaType = XmlSchemaType.GetBuiltInComplexType(xmlQualifiedName);
                }
                if (xmlSchemaType != null)
                {
                    schemaElementDecl = xmlSchemaType.ElementDecl;
                }
            }
            if (schemaElementDecl == null)
            {
                SendValidationEvent(System.SR.Sch_XsiTypeNotFound, xmlQualifiedName.ToString(), severity);
                elementDecl = null;
            }
            else
            {
                declFound = true;
                if (schemaElementDecl.IsAbstract)
                {
                    SendValidationEvent(System.SR.Sch_XsiTypeAbstract, xmlQualifiedName.ToString(), severity);
                    elementDecl = null;
                }
                else if (elementDecl != null && !XmlSchemaType.IsDerivedFrom(schemaElementDecl.SchemaType, elementDecl.SchemaType, elementDecl.Block))
                {
                    SendValidationEvent(System.SR.Sch_XsiTypeBlockedEx, new string[2]
                    {
                        xmlQualifiedName.ToString(),
                        QNameString(_context.LocalName, _context.Namespace)
                    });
                    elementDecl = null;
                }
                else
                {
                    if (elementDecl != null)
                    {
                        schemaElementDecl = schemaElementDecl.Clone();
                        schemaElementDecl.Constraints = elementDecl.Constraints;
                        schemaElementDecl.DefaultValueRaw = elementDecl.DefaultValueRaw;
                        schemaElementDecl.DefaultValueTyped = elementDecl.DefaultValueTyped;
                        schemaElementDecl.Block = elementDecl.Block;
                    }
                    _context.ElementDeclBeforeXsi = elementDecl;
                    elementDecl = schemaElementDecl;
                }
            }
        }
        return elementDecl;
    }
References System.Xml.Schema.XmlSchemaValidator._compiledSchemaInfo, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._nameTable, System.Xml.Schema.XmlSchemaValidator._nsResolver, System.Xml.Schema.XmlSchemaValidator._nsXs, System.Xml.Schema.XmlSchemaValidator._processContents, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.XmlSchemaType.GetBuiltInComplexType(), System.Xml.Schema.DatatypeImplementation.GetSimpleTypeFromXsdType(), System.Xml.Schema.SchemaInfo.GetTypeDecl(), System.Xml.Schema.XmlSchemaValidator.HasSchema, System.Xml.Schema.XmlSchemaType.IsDerivedFrom(), System.Xml.Schema.ValidationState.IsNill, System.Xml.Schema.ValidationState.LocalName, System.Xml.Schema.ValidationState.Namespace, System.Xml.Schema.XmlSchemaValidator.QNameString(), System.Xml.Schema.XmlSchemaValidator.s_dtQName, System.SR.Sch_AbstractElement, System.SR.Sch_InvalidValueDetailedAttribute, System.SR.Sch_InvalidXsiNill, System.SR.Sch_XsiNilAndFixed, System.SR.Sch_XsiTypeAbstract, System.SR.Sch_XsiTypeBlockedEx, System.SR.Sch_XsiTypeNotFound, System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(), and System.Xml.XmlConvert.ToBoolean().
Referenced by System.Xml.Schema.XmlSchemaValidator.ValidateElement().