Terraria: System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType
ProcessTokenizedType()
void System.Xml.Schema.XmlSchemaValidator.ProcessTokenizedType (XmlTokenizedType ttype, string name, bool attrValue) inline private
Definition at line 1790 of file XmlSchemaValidator.cs.
    {
        switch (ttype)
        {
        case XmlTokenizedType.ID:
            if (!ProcessIdentityConstraints)
            {
                break;
            }
            if (FindId(name) != null)
            {
                if (attrValue)
                {
                    _attrValid = false;
                }
                SendValidationEvent(System.SR.Sch_DupId, name);
            }
            else
            {
                if (_IDs == null)
                {
                    _IDs = new Hashtable();
                }
                _IDs.Add(name, _context.LocalName);
            }
            break;
        case XmlTokenizedType.IDREF:
            if (ProcessIdentityConstraints)
            {
                object obj = FindId(name);
                if (obj == null)
                {
                    _idRefListHead = new IdRefNode(_idRefListHead, name, _positionInfo.LineNumber, _positionInfo.LinePosition);
                }
            }
            break;
        case XmlTokenizedType.ENTITY:
            ProcessEntity(name);
            break;
        case XmlTokenizedType.IDREFS:
            break;
        }
    }
References System.Xml.Schema.XmlSchemaValidator._attrValid, System.Xml.Schema.XmlSchemaValidator._context, System.Xml.Schema.XmlSchemaValidator._idRefListHead, System.Xml.Schema.XmlSchemaValidator._IDs, System.Xml.Schema.XmlSchemaValidator._positionInfo, System.Collections.Hashtable.Add(), System.Xml.Schema.XmlSchemaValidator.FindId(), System.Xml.IXmlLineInfo.LineNumber, System.Xml.IXmlLineInfo.LinePosition, System.Xml.Schema.ValidationState.LocalName, System.obj, System.Xml.Schema.XmlSchemaValidator.ProcessEntity(), System.Xml.Schema.XmlSchemaValidator.ProcessIdentityConstraints, System.SR.Sch_DupId, and System.Xml.Schema.XmlSchemaValidator.SendValidationEvent().
Referenced by System.Xml.Schema.XmlSchemaValidator.CheckTokenizedTypes().