Terraria: Terraria.DataStructures.PlayerDeathReason.FromReader
FromReader()
static PlayerDeathReason Terraria.DataStructures.PlayerDeathReason.FromReader (BinaryReader reader) inline static
Definition at line 178 of file PlayerDeathReason.cs.
    {
        PlayerDeathReason playerDeathReason = new PlayerDeathReason();
        BitsByte bitsByte = reader.ReadByte();
        if (bitsByte[0])
        {
            playerDeathReason._sourcePlayerIndex = reader.ReadInt16();
        }
        if (bitsByte[1])
        {
            playerDeathReason._sourceNPCIndex = reader.ReadInt16();
        }
        if (bitsByte[2])
        {
            playerDeathReason._sourceProjectileLocalIndex = reader.ReadInt16();
        }
        if (bitsByte[3])
        {
            playerDeathReason._sourceOtherIndex = reader.ReadByte();
        }
        if (bitsByte[4])
        {
            playerDeathReason._sourceProjectileType = reader.ReadInt16();
        }
        if (bitsByte[5])
        {
            playerDeathReason._sourceItemType = reader.ReadInt16();
        }
        if (bitsByte[6])
        {
            playerDeathReason._sourceItemPrefix = reader.ReadByte();
        }
        if (bitsByte[7])
        {
            playerDeathReason._sourceCustomReason = reader.ReadString();
        }
        return playerDeathReason;
    }
References System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), and System.IO.BinaryReader.ReadString().
Referenced by Terraria.MessageBuffer.GetData().