Terraria: Terraria.DataStructures.PlayerDeathReason.ByOther
ByOther()
static PlayerDeathReason Terraria.DataStructures.PlayerDeathReason.ByOther (int type) inline static
Definition at line 99 of file PlayerDeathReason.cs.
    {
        return new PlayerDeathReason
        {
            _sourceOtherIndex = type
        };
    }
References Terraria.DataStructures.PlayerDeathReason._sourceOtherIndex.
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Player.ApplyTouchDamage(), Terraria.Player.BordersMovement(), Terraria.Player.CheckDrowning(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.Update(), Terraria.GameContent.DontStarveDarknessDamageDealer.Update(), Terraria.Player.UpdateBuffs(), Terraria.Player.UpdateLifeRegen(), Terraria.Mount.UseDrill(), and Terraria.Player.WOFTongue().