Terraria: Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode
SetCursorMode()
static void Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode (CursorMode cursorMode) inline static
Definition at line 92 of file PlayerInput.cs.
        {
            CurrentCursorMode = cursorMode;
            if (CurrentCursorMode == CursorMode.Mouse)
            {
                FramesSinceLastTimeInMouseMode = 0;
            }
        }
References Terraria.GameInput.PlayerInput.SettingsForUI.CurrentCursorMode, and Terraria.GameInput.PlayerInput.SettingsForUI.FramesSinceLastTimeInMouseMode.
Referenced by Terraria.GameInput.TriggersSet.CopyInto(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameInput.PlayerInput.HandleDpadSnap(), Terraria.Social.Steam.PlatformSocialModule.Initialize(), Terraria.GameInput.PlayerInput.MouseInput(), and Terraria.GameInput.PlayerInput.SettingsForUI.TryRevertingToMouseMode().