Terraria: System.Net.Security.SafeDeleteContext.InitializeSecurityContext
InitializeSecurityContext() [4/4]
static unsafe int System.Net.Security.SafeDeleteContext.InitializeSecurityContext (ref System::Net::Security::SafeFreeCredentials inCredentials, ref System::Net::Security::SafeDeleteSslContext refContext, string targetName, global::Interop::SspiCli::ContextFlags inFlags, global::Interop::SspiCli::Endianness endianness, System::Net::Security::InputSecurityBuffers inSecBuffers, ref System::Net::Security::SecurityBuffer outSecBuffer, ref global::Interop::SspiCli::ContextFlags outFlags) inline static package inherited
Definition at line 40 of file SafeDeleteContext.cs.
    {
        if (inCredentials == null)
        {
            throw new ArgumentNullException("inCredentials");
        }
        global::Interop.SspiCli.SecBufferDesc secBufferDesc = new global::Interop.SspiCli.SecBufferDesc(inSecBuffers.Count);
        global::Interop.SspiCli.SecBufferDesc outputBuffer = new global::Interop.SspiCli.SecBufferDesc(1);
        bool flag = (((inFlags & global::Interop.SspiCli.ContextFlags.AllocateMemory) != 0) ? true : false);
        int result = -1;
        bool flag2 = true;
        if (refContext != null)
        {
            flag2 = refContext._handle.IsZero;
        }
        IntPtr intPtr = IntPtr.Zero;
        try
        {
            Span<global::Interop.SspiCli.SecBuffer> span = stackalloc global::Interop.SspiCli.SecBuffer[3];
            fixed (global::Interop.SspiCli.SecBuffer* ptr = span)
            {
                void* pBuffers = ptr;
                fixed (byte* ptr2 = inSecBuffers._item0.Token)
                {
                    void* ptr3 = ptr2;
                    fixed (byte* ptr4 = inSecBuffers._item1.Token)
                    {
                        void* ptr5 = ptr4;
                        fixed (byte* ptr6 = inSecBuffers._item2.Token)
{
                            void* ptr7 = ptr6;
                            secBufferDesc.pBuffers = pBuffers;
                            if (inSecBuffers.Count > 2)
{
                                span[2].BufferType = inSecBuffers._item2.Type;
                                if (inSecBuffers._item2.UnmanagedToken != null)
{
                                    span[2].pvBuffer = inSecBuffers._item2.UnmanagedToken.DangerousGetHandle();
                                    span[2].cbBuffer = ((ChannelBinding)inSecBuffers._item2.UnmanagedToken).Size;
                                }
                                else
{
                                    span[2].cbBuffer = inSecBuffers._item2.Token.Length;
                                    span[2].pvBuffer = (IntPtr)ptr7;
                                }
                            }
                            if (inSecBuffers.Count > 1)
{
                                span[1].BufferType = inSecBuffers._item1.Type;
                                if (inSecBuffers._item1.UnmanagedToken != null)
{
                                    span[1].pvBuffer = inSecBuffers._item1.UnmanagedToken.DangerousGetHandle();
                                    span[1].cbBuffer = ((ChannelBinding)inSecBuffers._item1.UnmanagedToken).Size;
                                }
                                else
{
                                    span[1].cbBuffer = inSecBuffers._item1.Token.Length;
                                    span[1].pvBuffer = (IntPtr)ptr5;
                                }
                            }
                            if (inSecBuffers.Count > 0)
{
                                span[0].BufferType = inSecBuffers._item0.Type;
                                if (inSecBuffers._item0.UnmanagedToken != null)
{
                                    span[0].pvBuffer = inSecBuffers._item0.UnmanagedToken.DangerousGetHandle();
                                    span[0].cbBuffer = ((ChannelBinding)inSecBuffers._item0.UnmanagedToken).Size;
                                }
                                else
{
                                    span[0].cbBuffer = inSecBuffers._item0.Token.Length;
                                    span[0].pvBuffer = (IntPtr)ptr3;
                                }
                            }
                            fixed (byte* ptr8 = outSecBuffer.token)
{
                                global::Interop.SspiCli.SecBuffer secBuffer = default(global::Interop.SspiCli.SecBuffer);
                                outputBuffer.pBuffers = &secBuffer;
                                secBuffer.cbBuffer = outSecBuffer.size;
                                secBuffer.BufferType = outSecBuffer.type;
                                secBuffer.pvBuffer = ((outSecBuffer.token == null || outSecBuffer.token.Length == 0) ? IntPtr.Zero : ((IntPtr)(ptr8 + outSecBuffer.offset)));
                                if ((refContext == null || refContext.IsInvalid) && flag2)
{
                                    refContext = new System.Net.Security.SafeDeleteSslContext();
                                }
                                if (targetName == null || targetName.Length == 0)
{
                                    targetName = " ";
                                }
                                string ascii = s_idnMapping.GetAscii(targetName);
                                fixed (char* ptr9 = ascii)
{
                                    result = MustRunInitializeSecurityContext(ref inCredentials, flag2, (byte*)(((object)targetName == " ") ? null : ptr9), inFlags, endianness, &secBufferDesc, refContext, ref outputBuffer, ref outFlags, null);
                                    if (flag)
{
                                        intPtr = secBuffer.pvBuffer;
                                    }
                                    outSecBuffer.size = secBuffer.cbBuffer;
                                    outSecBuffer.type = secBuffer.BufferType;
                                    outSecBuffer.token = ((outSecBuffer.size > 0) ? new Span<byte>((void*)secBuffer.pvBuffer, secBuffer.cbBuffer).ToArray() : null);
                                    if (inSecBuffers.Count > 1 && span[1].BufferType == System.Net.Security.SecurityBufferType.SECBUFFER_EXTRA && inSecBuffers._item1.Type == System.Net.Security.SecurityBufferType.SECBUFFER_EMPTY)
{
                                        int cbBuffer = span[1].cbBuffer;
                                        int num = inSecBuffers._item0.Token.Length - span[1].cbBuffer;
                                        span[0].cbBuffer = cbBuffer;
                                        span[0].pvBuffer = span[0].pvBuffer + num;
                                        span[1].BufferType = System.Net.Security.SecurityBufferType.SECBUFFER_EMPTY;
                                        span[1].cbBuffer = 0;
                                        secBuffer.cbBuffer = 0;
                                        if (intPtr != IntPtr.Zero)
{
                                            global::Interop.SspiCli.FreeContextBuffer(intPtr);
                                            intPtr = IntPtr.Zero;
                                        }
                                        result = MustRunInitializeSecurityContext(ref inCredentials, flag2, (byte*)(((object)targetName == " ") ? null : ptr9), inFlags, endianness, &secBufferDesc, refContext, ref outputBuffer, ref outFlags, null);
                                        if (flag)
{
                                            intPtr = secBuffer.pvBuffer;
                                        }
                                        if (secBuffer.cbBuffer > 0)
{
                                            if (outSecBuffer.size == 0)
{
                                                outSecBuffer.size = secBuffer.cbBuffer;
                                                outSecBuffer.type = secBuffer.BufferType;
                                                outSecBuffer.token = new Span<byte>((void*)secBuffer.pvBuffer, secBuffer.cbBuffer).ToArray();
                                            }
                                            else
{
                                                byte[] array = new byte[outSecBuffer.size + secBuffer.cbBuffer];
                                                Buffer.BlockCopy(outSecBuffer.token, 0, array, 0, outSecBuffer.size);
                                                new Span<byte>((void*)secBuffer.pvBuffer, secBuffer.cbBuffer).CopyTo(new Span<byte>(array, outSecBuffer.size, secBuffer.cbBuffer));
                                                outSecBuffer.size = array.Length;
                                                outSecBuffer.token = array;
                                            }
                                        }
                                        if (span[1].BufferType == System.Net.Security.SecurityBufferType.SECBUFFER_EXTRA)
{
                                            result = -2146893032;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        finally
        {
            if (intPtr != IntPtr.Zero)
            {
                global::Interop.SspiCli.FreeContextBuffer(intPtr);
            }
        }
        return result;
    }
References System.array, System.Buffer.BlockCopy(), System.Span< T >.CopyTo(), System.Span< T >.Length, System.Net.Security.SafeDeleteContext.MustRunInitializeSecurityContext(), System.Net.Security.SafeDeleteContext.s_idnMapping, System.Span< T >.ToArray(), and System.IntPtr.Zero.