Terraria: Terraria.GameInput.PlayerInput.SettingsForUI.TryRevertingToMouseMode
TryRevertingToMouseMode()
static void Terraria.GameInput.PlayerInput.SettingsForUI.TryRevertingToMouseMode () inline static
Definition at line 109 of file PlayerInput.cs.
        {
            if (FramesSinceLastTimeInMouseMode <= 0)
            {
                SetCursorMode(CursorMode.Mouse);
                CurrentInputMode = InputMode.Mouse;
                Triggers.Current.UsedMovementKey = false;
                NavigatorUnCachePosition();
            }
        }
References Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.SettingsForUI.FramesSinceLastTimeInMouseMode, Terraria.GameInput.PlayerInput.NavigatorUnCachePosition(), and Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode().
Referenced by Terraria.Initializers.UILinksInitializer.FancyUISpecialInstructions(), Terraria.UI.ItemSlot.GetGamepadInstructions(), and Terraria.Initializers.UILinksInitializer.Load().