Terraria: System.Net.Security.SafeDeleteContext.AcceptSecurityContext
AcceptSecurityContext() [1/4]
static unsafe int System.Net.Security.SafeDeleteContext.AcceptSecurityContext (ref SafeFreeCredentials inCredentials, ref SafeDeleteSslContext refContext, global::Interop::SspiCli::ContextFlags inFlags, global::Interop::SspiCli::Endianness endianness, InputSecurityBuffers inSecBuffers, ref SecurityBuffer outSecBuffer, ref global::Interop::SspiCli::ContextFlags outFlags) inline static package inherited
Definition at line 240 of file SafeDeleteContext.cs.
    {
        if (inCredentials == null)
        {
            throw new ArgumentNullException("inCredentials");
        }
        global::Interop.SspiCli.SecBufferDesc secBufferDesc = new global::Interop.SspiCli.SecBufferDesc(inSecBuffers.Count);
        global::Interop.SspiCli.SecBufferDesc outputBuffer = new global::Interop.SspiCli.SecBufferDesc(2);
        bool flag = (((inFlags & global::Interop.SspiCli.ContextFlags.AllocateMemory) != 0) ? true : false);
        int result = -1;
        bool flag2 = true;
        if (refContext != null)
        {
            flag2 = refContext._handle.IsZero;
        }
        Span<global::Interop.SspiCli.SecBuffer> span = stackalloc global::Interop.SspiCli.SecBuffer[2];
        span[1].pvBuffer = IntPtr.Zero;
        try
        {
            Span<global::Interop.SspiCli.SecBuffer> span2 = stackalloc global::Interop.SspiCli.SecBuffer[3];
            fixed (global::Interop.SspiCli.SecBuffer* ptr = span2)
            {
                void* pBuffers = ptr;
                fixed (global::Interop.SspiCli.SecBuffer* ptr2 = span)
                {
                    void* pBuffers2 = ptr2;
                    fixed (byte* ptr3 = inSecBuffers._item0.Token)
                    {
                        void* ptr4 = ptr3;
                        fixed (byte* ptr5 = inSecBuffers._item1.Token)
{
                            void* ptr6 = ptr5;
                            fixed (byte* ptr7 = inSecBuffers._item2.Token)
{
                                void* ptr8 = ptr7;
                                secBufferDesc.pBuffers = pBuffers;
                                if (inSecBuffers.Count > 2)
{
                                    span2[2].BufferType = inSecBuffers._item2.Type;
                                    if (inSecBuffers._item2.UnmanagedToken != null)
{
                                        span2[2].pvBuffer = inSecBuffers._item2.UnmanagedToken.DangerousGetHandle();
                                        span2[2].cbBuffer = ((ChannelBinding)inSecBuffers._item2.UnmanagedToken).Size;
                                    }
                                    else
{
                                        span2[2].cbBuffer = inSecBuffers._item2.Token.Length;
                                        span2[2].pvBuffer = (IntPtr)ptr8;
                                    }
                                }
                                if (inSecBuffers.Count > 1)
{
                                    span2[1].BufferType = inSecBuffers._item1.Type;
                                    if (inSecBuffers._item1.UnmanagedToken != null)
{
                                        span2[1].pvBuffer = inSecBuffers._item1.UnmanagedToken.DangerousGetHandle();
                                        span2[1].cbBuffer = ((ChannelBinding)inSecBuffers._item1.UnmanagedToken).Size;
                                    }
                                    else
{
                                        span2[1].cbBuffer = inSecBuffers._item1.Token.Length;
                                        span2[1].pvBuffer = (IntPtr)ptr6;
                                    }
                                }
                                if (inSecBuffers.Count > 0)
{
                                    span2[0].BufferType = inSecBuffers._item0.Type;
                                    if (inSecBuffers._item0.UnmanagedToken != null)
{
                                        span2[0].pvBuffer = inSecBuffers._item0.UnmanagedToken.DangerousGetHandle();
                                        span2[0].cbBuffer = ((ChannelBinding)inSecBuffers._item0.UnmanagedToken).Size;
                                    }
                                    else
{
                                        span2[0].cbBuffer = inSecBuffers._item0.Token.Length;
                                        span2[0].pvBuffer = (IntPtr)ptr4;
                                    }
                                }
                                fixed (byte* ptr9 = outSecBuffer.token)
{
                                    outputBuffer.pBuffers = pBuffers2;
                                    span[0].cbBuffer = outSecBuffer.size;
                                    span[0].BufferType = outSecBuffer.type;
                                    span[0].pvBuffer = ((outSecBuffer.token == null || outSecBuffer.token.Length == 0) ? IntPtr.Zero : ((IntPtr)(ptr9 + outSecBuffer.offset)));
                                    span[1].cbBuffer = 0;
                                    span[1].BufferType = SecurityBufferType.SECBUFFER_ALERT;
                                    if ((refContext == null || refContext.IsInvalid) && flag2)
{
                                        refContext = new SafeDeleteSslContext();
                                    }
                                    result = MustRunAcceptSecurityContext_SECURITY(ref inCredentials, flag2, &secBufferDesc, inFlags, endianness, refContext, ref outputBuffer, ref outFlags, null);
                                    int index = ((span[0].cbBuffer == 0 && span[1].cbBuffer > 0) ? 1 : 0);
                                    outSecBuffer.size = span[index].cbBuffer;
                                    outSecBuffer.type = span[index].BufferType;
                                    outSecBuffer.token = ((outSecBuffer.size > 0) ? new Span<byte>((void*)span[index].pvBuffer, span[0].cbBuffer).ToArray() : null);
                                    if (inSecBuffers.Count > 1 && span2[1].BufferType == SecurityBufferType.SECBUFFER_EXTRA && inSecBuffers._item1.Type == SecurityBufferType.SECBUFFER_EMPTY)
{
                                        int cbBuffer = span2[1].cbBuffer;
                                        int num = inSecBuffers._item0.Token.Length - span2[1].cbBuffer;
                                        span2[0].cbBuffer = cbBuffer;
                                        span2[0].pvBuffer = span2[0].pvBuffer + num;
                                        span2[1].BufferType = SecurityBufferType.SECBUFFER_EMPTY;
                                        span2[1].cbBuffer = 0;
                                        span[0].cbBuffer = 0;
                                        if (flag && span[0].pvBuffer != IntPtr.Zero)
{
                                            global::Interop.SspiCli.FreeContextBuffer(span[0].pvBuffer);
                                            span[0].pvBuffer = IntPtr.Zero;
                                        }
                                        result = MustRunAcceptSecurityContext_SECURITY(ref inCredentials, flag2, &secBufferDesc, inFlags, endianness, refContext, ref outputBuffer, ref outFlags, null);
                                        index = ((span[0].cbBuffer == 0 && span[1].cbBuffer > 0) ? 1 : 0);
                                        if (span[index].cbBuffer > 0)
{
                                            if (outSecBuffer.size == 0)
{
                                                outSecBuffer.size = span[index].cbBuffer;
                                                outSecBuffer.type = span[index].BufferType;
                                                outSecBuffer.token = new Span<byte>((void*)span[index].pvBuffer, span[index].cbBuffer).ToArray();
                                            }
                                            else
{
                                                byte[] array = new byte[outSecBuffer.size + span[index].cbBuffer];
                                                Buffer.BlockCopy(outSecBuffer.token, 0, array, 0, outSecBuffer.size);
                                                new Span<byte>((void*)span[index].pvBuffer, span[index].cbBuffer).CopyTo(new Span<byte>(array, outSecBuffer.size, span[index].cbBuffer));
                                                outSecBuffer.size = array.Length;
                                                outSecBuffer.token = array;
                                            }
                                        }
                                        if (span2[1].BufferType == SecurityBufferType.SECBUFFER_EXTRA)
{
                                            result = -2146893032;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        finally
        {
            if (flag && span[0].pvBuffer != IntPtr.Zero)
            {
                global::Interop.SspiCli.FreeContextBuffer(span[0].pvBuffer);
            }
            if (span[1].pvBuffer != IntPtr.Zero)
            {
                global::Interop.SspiCli.FreeContextBuffer(span[1].pvBuffer);
            }
        }
        return result;
    }
References System.Net.Security.InputSecurityBuffers._item0, System.Net.Security.InputSecurityBuffers._item1, System.Net.Security.InputSecurityBuffers._item2, System.array, System.Buffer.BlockCopy(), System.Span< T >.CopyTo(), System.Net.Security.InputSecurityBuffers.Count, System.index, System.Net.Security.SafeDeleteContext.MustRunAcceptSecurityContext_SECURITY(), System.Span< T >.ToArray(), and System.IntPtr.Zero.