Terraria: System.Xml.Schema.XsdDateTime.PrintDate
PrintDate()
void System.Xml.Schema.XsdDateTime.PrintDate (StringBuilder sb) inline private
Definition at line 688 of file XsdDateTime.cs.
    {
        char[] array = new char[s_lzyyyy_MM_dd];
        GetYearMonthDay(out var year, out var month, out var day);
        IntToCharArray(array, 0, year, 4);
        array[s_lzyyyy] = '-';
        ShortToCharArray(array, s_lzyyyy_, month);
        array[s_lzyyyy_MM] = '-';
        ShortToCharArray(array, s_lzyyyy_MM_, day);
        sb.Append(array);
    }
References System.Text.StringBuilder.Append(), System.array, System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.GetYearMonthDay(), System.Xml.Schema.XsdDateTime.IntToCharArray(), System.Xml.Schema.XsdDateTime.s_lzyyyy, System.Xml.Schema.XsdDateTime.s_lzyyyy_, System.Xml.Schema.XsdDateTime.s_lzyyyy_MM, System.Xml.Schema.XsdDateTime.s_lzyyyy_MM_, System.Xml.Schema.XsdDateTime.s_lzyyyy_MM_dd, System.Xml.Schema.XsdDateTime.ShortToCharArray(), and System.year.
Referenced by System.Xml.Schema.XsdDateTime.ToString().