Terraria: System.Xml.Schema.XsdDateTime.InitiateXsdDateTime
InitiateXsdDateTime()
void System.Xml.Schema.XsdDateTime.InitiateXsdDateTime (Parser parser) inline private
Definition at line 439 of file XsdDateTime.cs.
    {
        _dt = new DateTime(parser.year, parser.month, parser.day, parser.hour, parser.minute, parser.second);
        if (parser.fraction != 0)
        {
            _dt = _dt.AddTicks(parser.fraction);
        }
        _extra = (uint)(((int)parser.typeCode << 24) | ((int)parser.kind << 16) | (parser.zoneHour << 8) | parser.zoneMinute);
    }
References System.Xml.Schema.XsdDateTime._dt, System.Xml.Schema.XsdDateTime._extra, System.DateTime.AddTicks(), System.Xml.Schema.XsdDateTime.DateTime, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.XsdDateTime.XsdDateTime(), and System.Xml.Schema.XsdDateTime.XsdDateTime().