Terraria: System.Xml.Schema.XsdDateTime.PrintTime
PrintTime()
void System.Xml.Schema.XsdDateTime.PrintTime (StringBuilder sb) inline private
Definition at line 730 of file XsdDateTime.cs.
    {
        char[] array = new char[s_lzHH_mm_ss];
        ShortToCharArray(array, 0, Hour);
        array[s_lzHH] = ':';
        ShortToCharArray(array, s_lzHH_, Minute);
        array[s_lzHH_mm] = ':';
        ShortToCharArray(array, s_lzHH_mm_, Second);
        sb.Append(array);
        int num = Fraction;
        if (num != 0)
        {
            int num2 = 7;
            while (num % 10 == 0)
            {
                num2--;
                num /= 10;
            }
            array = new char[num2 + 1];
            array[0] = '.';
            IntToCharArray(array, 1, num, num2);
            sb.Append(array);
        }
    }
References System.Text.StringBuilder.Append(), System.array, System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.Fraction, System.Xml.Schema.XsdDateTime.Hour, System.Xml.Schema.XsdDateTime.IntToCharArray(), System.Xml.Schema.XsdDateTime.Minute, System.Xml.Schema.XsdDateTime.s_lzHH, System.Xml.Schema.XsdDateTime.s_lzHH_, System.Xml.Schema.XsdDateTime.s_lzHH_mm, System.Xml.Schema.XsdDateTime.s_lzHH_mm_, System.Xml.Schema.XsdDateTime.s_lzHH_mm_ss, System.Xml.Schema.XsdDateTime.Second, and System.Xml.Schema.XsdDateTime.ShortToCharArray().
Referenced by System.Xml.Schema.XsdDateTime.ToString().