Terraria: System.Xml.Schema.XsdDateTime.ToString
ToString()
override string System.Xml.Schema.XsdDateTime.ToString () inline
Definition at line 619 of file XsdDateTime.cs.
    {
        StringBuilder stringBuilder = new StringBuilder(64);
        switch (InternalTypeCode)
        {
        case DateTimeTypeCode.DateTime:
            PrintDate(stringBuilder);
            stringBuilder.Append('T');
            PrintTime(stringBuilder);
            break;
        case DateTimeTypeCode.Time:
            PrintTime(stringBuilder);
            break;
        case DateTimeTypeCode.Date:
            PrintDate(stringBuilder);
            break;
        case DateTimeTypeCode.GYearMonth:
        {
            char[] array = new char[s_lzyyyy_MM];
            IntToCharArray(array, 0, Year, 4);
            array[s_lzyyyy] = '-';
            ShortToCharArray(array, s_lzyyyy_, Month);
            stringBuilder.Append(array);
            break;
        }
        case DateTimeTypeCode.GYear:
        {
            char[] array = new char[s_lzyyyy];
            IntToCharArray(array, 0, Year, 4);
            stringBuilder.Append(array);
            break;
        }
        case DateTimeTypeCode.GMonthDay:
        {
            char[] array = new char[s_lz__mm_dd];
            array[0] = '-';
            array[s_Lz_] = '-';
            ShortToCharArray(array, s_Lz__, Month);
            array[s_lz__mm] = '-';
            ShortToCharArray(array, s_lz__mm_, Day);
            stringBuilder.Append(array);
            break;
        }
        case DateTimeTypeCode.GDay:
        {
            char[] array = new char[s_lz___dd];
            array[0] = '-';
            array[s_Lz_] = '-';
            array[s_Lz__] = '-';
            ShortToCharArray(array, s_Lz___, Day);
            stringBuilder.Append(array);
            break;
        }
        case DateTimeTypeCode.GMonth:
        {
            char[] array = new char[s_lz__mm__];
            array[0] = '-';
            array[s_Lz_] = '-';
            ShortToCharArray(array, s_Lz__, Month);
            array[s_lz__mm] = '-';
            array[s_lz__mm_] = '-';
            stringBuilder.Append(array);
            break;
        }
        }
        PrintZone(stringBuilder);
        return stringBuilder.ToString();
    }
References System.array, System.Xml.Schema.XsdDateTime.Day, System.Xml.Dictionary, System.Xml.Schema.XsdDateTime.InternalTypeCode, System.Xml.Schema.XsdDateTime.IntToCharArray(), System.Xml.Schema.XsdDateTime.Month, System.Xml.Schema.XsdDateTime.PrintDate(), System.Xml.Schema.XsdDateTime.PrintTime(), System.Xml.Schema.XsdDateTime.PrintZone(), System.Xml.Schema.XsdDateTime.s_Lz_, System.Xml.Schema.XsdDateTime.s_Lz__, System.Xml.Schema.XsdDateTime.s_Lz___, System.Xml.Schema.XsdDateTime.s_lz___dd, System.Xml.Schema.XsdDateTime.s_lz__mm, System.Xml.Schema.XsdDateTime.s_lz__mm_, System.Xml.Schema.XsdDateTime.s_lz__mm__, System.Xml.Schema.XsdDateTime.s_lz__mm_dd, System.Xml.Schema.XsdDateTime.s_lzyyyy, System.Xml.Schema.XsdDateTime.s_lzyyyy_, System.Xml.Schema.XsdDateTime.s_lzyyyy_MM, System.Xml.Schema.XsdDateTime.ShortToCharArray(), and System.Xml.Schema.XsdDateTime.Year.
Referenced by System.Xml.Schema.XmlBaseConverter.DateOffsetToString(), System.Xml.Schema.XmlBaseConverter.DateTimeOffsetToString(), System.Xml.Schema.XmlBaseConverter.DateTimeToString(), System.Xml.Schema.XmlBaseConverter.DateToString(), System.Xml.Schema.XmlBaseConverter.GDayOffsetToString(), System.Xml.Schema.XmlBaseConverter.GDayToString(), System.Xml.Schema.XmlBaseConverter.GMonthDayOffsetToString(), System.Xml.Schema.XmlBaseConverter.GMonthDayToString(), System.Xml.Schema.XmlBaseConverter.GMonthOffsetToString(), System.Xml.Schema.XmlBaseConverter.GMonthToString(), System.Xml.Schema.XmlBaseConverter.GYearMonthOffsetToString(), System.Xml.Schema.XmlBaseConverter.GYearMonthToString(), System.Xml.Schema.XmlBaseConverter.GYearOffsetToString(), System.Xml.Schema.XmlBaseConverter.GYearToString(), System.Xml.Schema.XmlBaseConverter.TimeOffsetToString(), System.Xml.Schema.XmlBaseConverter.TimeToString(), System.Xml.Xsl.Runtime.XsltConvert.ToString(), System.Xml.XmlConvert.ToString(), and System.Xml.XmlConvert.ToString().