Terraria: System.Xml.Schema.XsdDateTime.PrintZone
PrintZone()
void System.Xml.Schema.XsdDateTime.PrintZone (StringBuilder sb) inline private
Definition at line 755 of file XsdDateTime.cs.
    {
        switch (InternalKind)
        {
        case XsdDateTimeKind.Zulu:
            sb.Append('Z');
            break;
        case XsdDateTimeKind.LocalWestOfZulu:
        {
            char[] array = new char[s_lz_zz_zz];
            array[0] = '-';
            ShortToCharArray(array, s_Lz_, ZoneHour);
            array[s_lz_zz] = ':';
            ShortToCharArray(array, s_lz_zz_, ZoneMinute);
            sb.Append(array);
            break;
        }
        case XsdDateTimeKind.LocalEastOfZulu:
        {
            char[] array = new char[s_lz_zz_zz];
            array[0] = '+';
            ShortToCharArray(array, s_Lz_, ZoneHour);
            array[s_lz_zz] = ':';
            ShortToCharArray(array, s_lz_zz_, ZoneMinute);
            sb.Append(array);
            break;
        }
        }
    }
References System.Text.StringBuilder.Append(), System.array, System.Xml.Schema.XsdDateTime.InternalKind, System.Xml.Schema.XsdDateTime.s_Lz_, System.Xml.Schema.XsdDateTime.s_lz_zz, System.Xml.Schema.XsdDateTime.s_lz_zz_, System.Xml.Schema.XsdDateTime.s_lz_zz_zz, System.Xml.Schema.XsdDateTime.ShortToCharArray(), System.Xml.Schema.XsdDateTime.ZoneHour, and System.Xml.Schema.XsdDateTime.ZoneMinute.
Referenced by System.Xml.Schema.XsdDateTime.ToString().