Terraria: System.Reflection.Metadata.MethodBodyBlock.Create
Create()
static MethodBodyBlock System.Reflection.Metadata.MethodBodyBlock.Create (BlobReader reader) inline static
Definition at line 56 of file MethodBodyBlock.cs.
    {
        int offset = reader.Offset;
        byte b = reader.ReadByte();
        int num;
        if ((b & 3) == 2)
        {
            num = b >> 2;
            return new MethodBodyBlock(localVariablesInitialized: false, 8, default(StandaloneSignatureHandle), reader.GetMemoryBlockAt(0, num), ImmutableArray<ExceptionRegion>.Empty, 1 + num);
        }
        if ((b & 3) != 3)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.InvalidMethodHeader1, b));
        }
        byte b2 = reader.ReadByte();
        if (b2 >> 4 != 3)
        {
            throw new BadImageFormatException(System.SR.Format(System.SR.InvalidMethodHeader2, b, b2));
        }
        bool localVariablesInitialized = (b & 0x10) == 16;
        bool flag = (b & 8) == 8;
        ushort maxStack = reader.ReadUInt16();
        num = reader.ReadInt32();
        int num2 = reader.ReadInt32();
        StandaloneSignatureHandle localSignatureHandle;
        if (num2 == 0)
        {
            localSignatureHandle = default(StandaloneSignatureHandle);
        }
        else
        {
            if (((ulong)num2 & 0x7F000000uL) != 285212672)
            {
                throw new BadImageFormatException(System.SR.Format(System.SR.InvalidLocalSignatureToken, (uint)num2));
            }
            localSignatureHandle = StandaloneSignatureHandle.FromRowId(num2 & 0xFFFFFF);
        }
        MemoryBlock memoryBlockAt = reader.GetMemoryBlockAt(0, num);
        reader.Offset += num;
        ImmutableArray<ExceptionRegion> exceptionRegions;
        if (flag)
        {
            reader.Align(4);
            byte b3 = reader.ReadByte();
            if ((b3 & 1) != 1)
            {
                throw new BadImageFormatException(System.SR.Format(System.SR.InvalidSehHeader, b3));
            }
            bool flag2 = (b3 & 0x40) == 64;
            int num3 = reader.ReadByte();
            if (flag2)
            {
                num3 += reader.ReadUInt16() << 8;
                exceptionRegions = ReadFatExceptionHandlers(ref reader, num3 / 24);
            }
            else
            {
                reader.Offset += 2;
                exceptionRegions = ReadSmallExceptionHandlers(ref reader, num3 / 12);
            }
        }
        else
        {
            exceptionRegions = ImmutableArray<ExceptionRegion>.Empty;
        }
        return new MethodBodyBlock(localVariablesInitialized, maxStack, localSignatureHandle, memoryBlockAt, exceptionRegions, reader.Offset - offset);
    }
References System.Reflection.Metadata.MethodBodyBlock.MethodBodyBlock(), System.Reflection.Metadata.BlobReader.Align(), System.Collections.Immutable.ImmutableArray< T >.Empty, System.SR.Format(), System.Reflection.Metadata.StandaloneSignatureHandle.FromRowId(), System.Reflection.Metadata.BlobReader.GetMemoryBlockAt(), System.SR.InvalidLocalSignatureToken, System.SR.InvalidMethodHeader1, System.SR.InvalidMethodHeader2, System.SR.InvalidSehHeader, System.offset, System.Reflection.Metadata.BlobReader.Offset, System.Reflection.Metadata.BlobReader.ReadByte(), System.Reflection.Metadata.MethodBodyBlock.ReadFatExceptionHandlers(), System.Reflection.Metadata.BlobReader.ReadInt32(), System.Reflection.Metadata.MethodBodyBlock.ReadSmallExceptionHandlers(), and System.Reflection.Metadata.BlobReader.ReadUInt16().
Referenced by System.Reflection.Metadata.PEReaderExtensions.GetMethodBody().