Terraria: UILinksInitializer.FancyUISpecialInstructions
FancyUISpecialInstructions()
static string UILinksInitializer.FancyUISpecialInstructions () inline static
     {
         string text = "";
         int fANCYUI_SPECIAL_INSTRUCTIONS = UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS;
         if (fANCYUI_SPECIAL_INSTRUCTIONS == 1)
         {
             if (CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.HotbarMinus)
             {
                 UIVirtualKeyboard.CycleSymbols();
                 PlayerInput.LockGamepadButtons("HotbarMinus");
                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
             }
             text += PlayerInput.BuildCommand(Lang.menu[235].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["HotbarMinus"]);
             if (CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.MouseRight)
             {
                 UIVirtualKeyboard.BackSpace();
                 PlayerInput.LockGamepadButtons("MouseRight");
                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
             }
             text += PlayerInput.BuildCommand(Lang.menu[236].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]);
             if (CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
             {
                 UIVirtualKeyboard.Write(" ");
                 PlayerInput.LockGamepadButtons("SmartCursor");
                 PlayerInput.SettingsForUI.TryRevertingToMouseMode();
             }
             text += PlayerInput.BuildCommand(Lang.menu[238].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"]);
             if (UIVirtualKeyboard.CanSubmit)
             {
                 if (CanExecuteInputCommand() && PlayerInput.Triggers.JustPressed.HotbarPlus)
                 {
                     UIVirtualKeyboard.Submit();
                     PlayerInput.LockGamepadButtons("HotbarPlus");
                     PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                 }
                 text += PlayerInput.BuildCommand(Lang.menu[237].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["HotbarPlus"]);
             }
         }
         return text;
     }
References UIVirtualKeyboard.BackSpace(), PlayerInput.BuildCommand(), UIVirtualKeyboard.CanSubmit, UIVirtualKeyboard.CycleSymbols(), UILinkPointNavigator.Shortcuts.FANCYUI_SPECIAL_INSTRUCTIONS, TriggersSet.HotbarMinus, TriggersSet.HotbarPlus, TriggersPack.JustPressed, KeyConfiguration.KeyStatus, PlayerInput.LockGamepadButtons(), Lang.menu, TriggersSet.MouseRight, PlayerInput.ProfileGamepadUI, TriggersSet.SmartCursor, UIVirtualKeyboard.Submit(), PlayerInput.Triggers, PlayerInput.SettingsForUI.TryRevertingToMouseMode(), LocalizedText.Value, and UIVirtualKeyboard.Write().