Terraria: GameInterfaceLayer.Draw
Draw()
bool GameInterfaceLayer.Draw () inline inherited
     {
         Matrix transformMatrix;
         if (ScaleType == InterfaceScaleType.Game)
         {
             PlayerInput.SetZoom_World();
             transformMatrix = Main.GameViewMatrix.ZoomMatrix;
         }
         else if (ScaleType == InterfaceScaleType.UI)
         {
             PlayerInput.SetZoom_UI();
             transformMatrix = Main.UIScaleMatrix;
         }
         else
         {
             PlayerInput.SetZoom_Unscaled();
             transformMatrix = Matrix.Identity;
         }
         bool result = false;
         Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, transformMatrix);
         try
         {
             result = DrawSelf();
         }
         catch (Exception e)
         {
             TimeLogger.DrawException(e);
         }
         Main.spriteBatch.End();
         return result;
     }
References TimeLogger.DrawException(), GameInterfaceLayer.DrawSelf(), Main.GameViewMatrix, GameInterfaceLayer.ScaleType, PlayerInput.SetZoom_UI(), PlayerInput.SetZoom_Unscaled(), PlayerInput.SetZoom_World(), Main.spriteBatch, Main.UIScaleMatrix, and SpriteViewMatrix.ZoomMatrix.