Terraria: PlayerInput.SettingsForUI.TryRevertingToMouseMode
TryRevertingToMouseMode()
static void PlayerInput.SettingsForUI.TryRevertingToMouseMode () inline static
         {
             if (FramesSinceLastTimeInMouseMode <= 0)
             {
                 SetCursorMode(CursorMode.Mouse);
                 CurrentInputMode = InputMode.Mouse;
                 Triggers.Current.UsedMovementKey = false;
                 NavigatorUnCachePosition();
             }
         }
References TriggersPack.Current, PlayerInput.CurrentInputMode, PlayerInput.SettingsForUI.FramesSinceLastTimeInMouseMode, PlayerInput.NavigatorUnCachePosition(), PlayerInput.SettingsForUI.SetCursorMode(), PlayerInput.Triggers, and TriggersSet.UsedMovementKey.
Referenced by UILinksInitializer.FancyUISpecialInstructions(), and ItemSlot.GetGamepadInstructions().