Terraria: System.UriParser.InternalValidate
InternalValidate()
void System.UriParser.InternalValidate (Uri thisUri, out UriFormatException parsingError) inline package inherited
Definition at line 320 of file UriParser.cs.
    {
        InitializeAndValidate(thisUri, out parsingError);
        Interlocked.Or(ref Unsafe.As<Uri.Flags, ulong>(ref thisUri._flags), 4611686018427387904uL);
    }
References System.Uri._flags, System.UriParser.InitializeAndValidate(), and System.Threading.Interlocked.Or().
Referenced by System.Uri.InitializeUri().