Terraria: System.Text.Base64Encoding.IsValidTailBytes
IsValidTailBytes()
bool System.Text.Base64Encoding.IsValidTailBytes (int v3, int v4) inline private
Definition at line 50 of file Base64Encoding.cs.
    {
        if (v3 == 64)
        {
            return v4 == 64;
        }
        return true;
    }
References System.Runtime.Serialization.Dictionary.
Referenced by System.Text.Base64Encoding.GetByteCount(), System.Text.Base64Encoding.GetBytes(), and System.Text.Base64Encoding.GetBytes().