Terraria: System.Text.Base64Encoding.GetBytes
GetBytes() [5/10]
unsafe override int System.Text.Base64Encoding.GetBytes (char[] chars, int charIndex, int charCount, byte[] bytes, int byteIndex) inline
Definition at line 121 of file Base64Encoding.cs.
    {
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (charIndex < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charIndex", System.SR.ValueMustBeNonNegative));
        }
        if (charIndex > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (charCount < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charCount", System.SR.ValueMustBeNonNegative));
        }
        if (charCount > chars.Length - charIndex)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charCount", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - charIndex)));
        }
        if (bytes == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("bytes"));
        }
        if (byteIndex < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteIndex", System.SR.ValueMustBeNonNegative));
        }
        if (byteIndex > bytes.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, bytes.Length)));
        }
        if (charCount == 0)
        {
            return 0;
        }
        if (charCount % 4 != 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Length, charCount.ToString())));
        }
        fixed (byte* ptr7 = &Char2val[0])
        {
            fixed (char* ptr = &chars[charIndex])
            {
                fixed (byte* ptr4 = &bytes[byteIndex])
                {
                    char* ptr2 = ptr;
                    char* ptr3 = ptr + charCount;
                    byte* ptr5 = ptr4;
                    byte* ptr6 = ptr4 + bytes.Length - byteIndex;
                    for (; ptr2 < ptr3; ptr2 += 4)
                    {
                        char c = *ptr2;
                        char c2 = ptr2[1];
                        char c3 = ptr2[2];
                        char c4 = ptr2[3];
                        if ((c | c2 | c3 | c4) >= 128)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Sequence, new string(ptr2, 0, 4), charIndex + (int)(ptr2 - ptr))));
                        }
                        int num = ptr7[(int)c];
                        int num2 = ptr7[(int)c2];
                        int num3 = ptr7[(int)c3];
                        int num4 = ptr7[(int)c4];
                        if (!IsValidLeadBytes(num, num2, num3, num4) || !IsValidTailBytes(num3, num4))
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Sequence, new string(ptr2, 0, 4), charIndex + (int)(ptr2 - ptr))));
                        }
                        int num5 = ((num4 != 64) ? 3 : ((num3 == 64) ? 1 : 2));
                        if (ptr5 + num5 > ptr6)
{
                            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlArrayTooSmall, "bytes"));
                        }
                        *ptr5 = (byte)((uint)(num << 2) | ((uint)(num2 >> 4) & 3u));
                        if (num5 > 1)
{
                            ptr5[1] = (byte)((uint)(num2 << 4) | ((uint)(num3 >> 2) & 0xFu));
                            if (num5 > 2)
{
                                ptr5[2] = (byte)((uint)(num3 << 6) | ((uint)num4 & 0x3Fu));
                            }
                        }
                        ptr5 += num5;
                    }
                    return (int)(ptr5 - ptr4);
                }
            }
        }
    }
References System.byteIndex, System.bytes, System.Text.Base64Encoding.Char2val, System.charCount, System.charIndex, System.chars, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Text.Base64Encoding.IsValidLeadBytes(), System.Text.Base64Encoding.IsValidTailBytes(), System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, System.SR.XmlArrayTooSmall, System.SR.XmlInvalidBase64Length, and System.SR.XmlInvalidBase64Sequence.
Referenced by System.Xml.ValueHandle.ToByteArray(), and System.Xml.ValueHandle.TryReadBase64().