Terraria: System.Text.Base64Encoding.GetChars
GetChars() [5/7]
unsafe override int System.Text.Base64Encoding.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) inline
Definition at line 319 of file Base64Encoding.cs.
    {
        if (bytes == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("bytes"));
        }
        if (byteIndex < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteIndex", System.SR.ValueMustBeNonNegative));
        }
        if (byteIndex > bytes.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, bytes.Length)));
        }
        if (byteCount < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteCount", System.SR.ValueMustBeNonNegative));
        }
        if (byteCount > bytes.Length - byteIndex)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteCount", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, bytes.Length - byteIndex)));
        }
        int charCount = GetCharCount(bytes, byteIndex, byteCount);
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (charIndex < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charIndex", System.SR.ValueMustBeNonNegative));
        }
        if (charIndex > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("charIndex", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (charCount < 0 || charCount > chars.Length - charIndex)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentException(System.SR.XmlArrayTooSmall, "chars"));
        }
        if (byteCount > 0)
        {
            fixed (char* ptr6 = &"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".GetPinnableReference())
            {
                fixed (byte* ptr = &bytes[byteIndex])
                {
                    fixed (char* ptr4 = &chars[charIndex])
                    {
                        byte* ptr2 = ptr;
                        byte* ptr3 = ptr2 + byteCount - 3;
                        char* ptr5 = ptr4;
                        while (ptr2 <= ptr3)
{
                            *ptr5 = ptr6[*ptr2 >> 2];
                            ptr5[1] = ptr6[((*ptr2 & 3) << 4) | (ptr2[1] >> 4)];
                            ptr5[2] = ptr6[((ptr2[1] & 0xF) << 2) | (ptr2[2] >> 6)];
                            ptr5[3] = ptr6[ptr2[2] & 0x3F];
                            ptr2 += 3;
                            ptr5 += 4;
                        }
                        if (ptr2 - ptr3 == 2)
{
                            *ptr5 = ptr6[*ptr2 >> 2];
                            ptr5[1] = ptr6[(*ptr2 & 3) << 4];
                            ptr5[2] = '=';
                            ptr5[3] = '=';
                        }
                        else if (ptr2 - ptr3 == 1)
{
                            *ptr5 = ptr6[*ptr2 >> 2];
                            ptr5[1] = ptr6[((*ptr2 & 3) << 4) | (ptr2[1] >> 4)];
                            ptr5[2] = ptr6[(ptr2[1] & 0xF) << 2];
                            ptr5[3] = '=';
                        }
                    }
                }
            }
        }
        return charCount;
    }
References System.byteCount, System.byteIndex, System.bytes, System.charCount, System.charIndex, System.chars, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Text.Base64Encoding.GetCharCount(), System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, and System.SR.XmlArrayTooSmall.
Referenced by System.Xml.XmlUTF8NodeWriter.InternalWriteBase64TextAsync().