Terraria: System.UriParser.FetchSyntax
FetchSyntax()
static void System.UriParser.FetchSyntax (UriParser syntax, string lwrCaseSchemeName, int defaultPort) inline static private inherited
Definition at line 242 of file UriParser.cs.
    {
        if (syntax.SchemeName.Length != 0)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_NeedFreshParser, syntax.SchemeName));
        }
        lock (s_table)
        {
            syntax._flags &= ~UriSyntaxFlags.V1_UnknownUri;
            UriParser uriParser = (UriParser)s_table[lwrCaseSchemeName];
            if (uriParser != null)
            {
                throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_AlreadyRegistered, uriParser.SchemeName));
            }
            uriParser = (UriParser)s_tempTable[syntax.SchemeName];
            if (uriParser != null)
            {
                lwrCaseSchemeName = uriParser._scheme;
                s_tempTable.Remove(lwrCaseSchemeName);
            }
            syntax.OnRegister(lwrCaseSchemeName, defaultPort);
            syntax._scheme = lwrCaseSchemeName;
            syntax.CheckSetIsSimpleFlag();
            syntax._port = defaultPort;
            s_table[syntax.SchemeName] = syntax;
        }
    }
References System.UriParser.UriParser(), System.UriParser._scheme, System.UriParser.CheckSetIsSimpleFlag(), System.SR.Format(), System.SR.net_uri_AlreadyRegistered, System.SR.net_uri_NeedFreshParser, System.UriParser.OnRegister(), System.UriParser.s_table, System.UriParser.s_tempTable, and System.UriParser.SchemeName.
Referenced by System.UriParser.Register().