Terraria: System.UriParser.GetComponents
GetComponents()
virtual string System.UriParser.GetComponents (Uri uri, UriComponents components, UriFormat format) inline protected virtual inherited
Definition at line 147 of file UriParser.cs.
    {
        if (((uint)components & 0x80000000u) != 0 && components != UriComponents.SerializationInfoString)
        {
            throw new ArgumentOutOfRangeException("components", components, System.SR.net_uri_NotJustSerialization);
        }
        if (((uint)format & 0xFFFFFFFCu) != 0)
        {
            throw new ArgumentOutOfRangeException("format");
        }
        if (uri.UserDrivenParsing)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_UserDrivenParsing, GetType()));
        }
        if (!uri.IsAbsoluteUri)
        {
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        if (uri.DisablePathAndQueryCanonicalization && (components & UriComponents.PathAndQuery) != 0)
        {
            throw new InvalidOperationException(System.SR.net_uri_GetComponentsCalledWhenCanonicalizationDisabled);
        }
        return uri.GetComponentsHelper(components, format);
    }
References System.Uri.DisablePathAndQueryCanonicalization, System.SR.Format(), System.format, System.Uri.GetComponentsHelper(), System.Uri.IsAbsoluteUri, System.SR.net_uri_GetComponentsCalledWhenCanonicalizationDisabled, System.SR.net_uri_NotAbsolute, System.SR.net_uri_NotJustSerialization, System.SR.net_uri_UserDrivenParsing, and System.Uri.UserDrivenParsing.
Referenced by System.UriParser.InternalGetComponents().