Terraria: System.UriParser.InitializeAndValidate
InitializeAndValidate()
virtual void System.UriParser.InitializeAndValidate (Uri uri, out UriFormatException? parsingError) inline protected virtual inherited
Definition at line 103 of file UriParser.cs.
    {
        if (uri._syntax == null)
        {
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        if (uri._syntax != this)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_UserDrivenParsing, uri._syntax.GetType()));
        }
        ulong num = Interlocked.Or(ref Unsafe.As<Uri.Flags, ulong>(ref uri._flags), 4611686018427387904uL);
        if ((num & 0x4000000000000000L) != 0L)
        {
            throw new InvalidOperationException(System.SR.net_uri_InitializeCalledAlreadyOrTooLate);
        }
        parsingError = uri.ParseMinimal();
    }
References System.Uri._flags, System.Uri._syntax, System.SR.Format(), System.L, System.SR.net_uri_InitializeCalledAlreadyOrTooLate, System.SR.net_uri_NotAbsolute, System.SR.net_uri_UserDrivenParsing, System.Threading.Interlocked.Or(), and System.Uri.ParseMinimal().
Referenced by System.UriParser.InternalValidate().