Terraria: System.Text.Base64Encoding.GetByteCount
GetByteCount() [4/7]
unsafe override int System.Text.Base64Encoding.GetByteCount (char[] chars, int index, int count) inline
Definition at line 59 of file Base64Encoding.cs.
    {
        if (chars == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentNullException("chars"));
        }
        if (index < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("index", System.SR.ValueMustBeNonNegative));
        }
        if (index > chars.Length)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("index", System.SR.Format(System.SR.OffsetExceedsBufferSize, chars.Length)));
        }
        if (count < 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.ValueMustBeNonNegative));
        }
        if (count > chars.Length - index)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("count", System.SR.Format(System.SR.SizeExceedsRemainingBufferSpace, chars.Length - index)));
        }
        if (count == 0)
        {
            return 0;
        }
        if (count % 4 != 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Length, count.ToString())));
        }
        fixed (byte* ptr4 = &Char2val[0])
        {
            fixed (char* ptr = &chars[index])
            {
                int num = 0;
                char* ptr2 = ptr;
                for (char* ptr3 = ptr + count; ptr2 < ptr3; ptr2 += 4)
                {
                    char c = *ptr2;
                    char c2 = ptr2[1];
                    char c3 = ptr2[2];
                    char c4 = ptr2[3];
                    if ((c | c2 | c3 | c4) >= 128)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Sequence, new string(ptr2, 0, 4), index + (int)(ptr2 - ptr))));
                    }
                    int v = ptr4[(int)c];
                    int v2 = ptr4[(int)c2];
                    int num2 = ptr4[(int)c3];
                    int num3 = ptr4[(int)c4];
                    if (!IsValidLeadBytes(v, v2, num2, num3) || !IsValidTailBytes(num2, num3))
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new FormatException(System.SR.Format(System.SR.XmlInvalidBase64Sequence, new string(ptr2, 0, 4), index + (int)(ptr2 - ptr))));
                    }
                    int num4 = ((num3 != 64) ? 3 : ((num2 == 64) ? 1 : 2));
                    num += num4;
                }
                return num;
            }
        }
    }
References System.Text.Base64Encoding.Char2val, System.chars, System.count, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.index, System.Text.Base64Encoding.IsValidLeadBytes(), System.Text.Base64Encoding.IsValidTailBytes(), System.SR.OffsetExceedsBufferSize, System.SR.SizeExceedsRemainingBufferSpace, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.SR.ValueMustBeNonNegative, System.SR.XmlInvalidBase64Length, and System.SR.XmlInvalidBase64Sequence.