Terraria: System.UriParser.Resolve
Resolve()
virtual ? string System.UriParser.Resolve (Uri baseUri, Uri? relativeUri, out UriFormatException? parsingError) inline protected virtual inherited
Definition at line 121 of file UriParser.cs.
    {
        if (baseUri.UserDrivenParsing)
        {
            throw new InvalidOperationException(System.SR.Format(System.SR.net_uri_UserDrivenParsing, GetType()));
        }
        if (!baseUri.IsAbsoluteUri)
        {
            throw new InvalidOperationException(System.SR.net_uri_NotAbsolute);
        }
        string newUriString = null;
        bool userEscaped = false;
        parsingError = null;
        Uri uri = Uri.ResolveHelper(baseUri, relativeUri, ref newUriString, ref userEscaped);
        if (uri != null)
        {
            return uri.OriginalString;
        }
        return newUriString;
    }
References System.SR.Format(), System.Uri.IsAbsoluteUri, System.SR.net_uri_NotAbsolute, System.SR.net_uri_UserDrivenParsing, System.Uri.OriginalString, System.Uri.ResolveHelper(), and System.Uri.UserDrivenParsing.
Referenced by System.UriParser.InternalResolve().