Terraria: System.Text.Base64Encoding.GetMaxCharCount
GetMaxCharCount()
override int System.Text.Base64Encoding.GetMaxCharCount (int byteCount) inline
Definition at line 305 of file Base64Encoding.cs.
    {
        if (byteCount < 0 || byteCount > 1610612731)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new ArgumentOutOfRangeException("byteCount", System.SR.Format(System.SR.ValueMustBeInRange, 0, 1610612731)));
        }
        return (byteCount + 2) / 3 * 4;
    }
References System.byteCount, System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.SR.ValueMustBeInRange.
Referenced by System.Text.Base64Encoding.GetCharCount().