Terraria: NetworkText.ConvertSubstitutionsToNetworkText
ConvertSubstitutionsToNetworkText()
static NetworkText [] NetworkText.ConvertSubstitutionsToNetworkText (object[] substitutions) inline static private
     {
         NetworkText[] array = new NetworkText[substitutions.Length];
         for (int i = 0; i < substitutions.Length; i++)
         {
             NetworkText networkText = substitutions[i] as NetworkText;
             if (networkText == null)
             {
                 networkText = FromLiteral(substitutions[i].ToString());
             }
             array[i] = networkText;
         }
         return array;
     }
References NetworkText(), FromLiteral(), and ToString().
Referenced by FromFormattable(), and FromKey().