Terraria: UIWorldCreation.MakeInfoMenu
MakeInfoMenu()
void UIWorldCreation.MakeInfoMenu (UIElement parentContainer) inline private
     {
         UIElement uIElement = new UIElement
         {
             Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
             Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
             HAlign = 0.5f,
             VAlign = 0f
         };
         uIElement.SetPadding(10f);
         uIElement.PaddingBottom = 0f;
         uIElement.PaddingTop = 0f;
         parentContainer.Append(uIElement);
         float num = 0f;
         float num2 = 44f;
         float num3 = 88f + num2;
         float pixels = num2;
         GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(option: true, null, Language.GetText("UI.WorldCreationRandomizeNameDescription"), Color.White, "Images/UI/WorldCreation/IconRandomName")
         {
             Width = StyleDimension.FromPixelsAndPercent(40f, 0f),
             Height = new StyleDimension(40f, 0f),
             HAlign = 0f,
             Top = StyleDimension.FromPixelsAndPercent(num, 0f),
             ShowHighlightWhenSelected = false
         };
         groupOptionButton.OnLeftMouseDown += ClickRandomizeName;
         groupOptionButton.OnMouseOver += ShowOptionDescription;
         groupOptionButton.OnMouseOut += ClearOptionDescription;
         groupOptionButton.SetSnapPoint("RandomizeName", 0);
         uIElement.Append(groupOptionButton);
         UICharacterNameButton uICharacterNameButton = new UICharacterNameButton(Language.GetText("UI.WorldCreationName"), Language.GetText("UI.WorldCreationNameEmpty"), Language.GetText("UI.WorldDescriptionName"))
         {
             Width = StyleDimension.FromPixelsAndPercent(0f - num3, 1f),
             HAlign = 0f,
             Left = new StyleDimension(pixels, 0f),
             Top = StyleDimension.FromPixelsAndPercent(num, 0f)
         };
         uICharacterNameButton.OnLeftMouseDown += Click_SetName;
         uICharacterNameButton.OnMouseOver += ShowOptionDescription;
         uICharacterNameButton.OnMouseOut += ClearOptionDescription;
         uICharacterNameButton.SetSnapPoint("Name", 0);
         uIElement.Append(uICharacterNameButton);
         _namePlate = uICharacterNameButton;
         num += uICharacterNameButton.GetDimensions().Height + 4f;
         GroupOptionButton<bool> groupOptionButton2 = new GroupOptionButton<bool>(option: true, null, Language.GetText("UI.WorldCreationRandomizeSeedDescription"), Color.White, "Images/UI/WorldCreation/IconRandomSeed")
         {
             Width = StyleDimension.FromPixelsAndPercent(40f, 0f),
             Height = new StyleDimension(40f, 0f),
             HAlign = 0f,
             Top = StyleDimension.FromPixelsAndPercent(num, 0f),
             ShowHighlightWhenSelected = false
         };
         groupOptionButton2.OnLeftMouseDown += ClickRandomizeSeed;
         groupOptionButton2.OnMouseOver += ShowOptionDescription;
         groupOptionButton2.OnMouseOut += ClearOptionDescription;
         groupOptionButton2.SetSnapPoint("RandomizeSeed", 0);
         uIElement.Append(groupOptionButton2);
         UICharacterNameButton uICharacterNameButton2 = new UICharacterNameButton(Language.GetText("UI.WorldCreationSeed"), Language.GetText("UI.WorldCreationSeedEmpty"), Language.GetText("UI.WorldDescriptionSeed"))
         {
             Width = StyleDimension.FromPixelsAndPercent(0f - num3, 1f),
             HAlign = 0f,
             Left = new StyleDimension(pixels, 0f),
             Top = StyleDimension.FromPixelsAndPercent(num, 0f),
             DistanceFromTitleToOption = 29f
         };
         uICharacterNameButton2.OnLeftMouseDown += Click_SetSeed;
         uICharacterNameButton2.OnMouseOver += ShowOptionDescription;
         uICharacterNameButton2.OnMouseOut += ClearOptionDescription;
         uICharacterNameButton2.SetSnapPoint("Seed", 0);
         uIElement.Append(uICharacterNameButton2);
         _seedPlate = uICharacterNameButton2;
         UIWorldCreationPreview uIWorldCreationPreview = new UIWorldCreationPreview
         {
             Width = StyleDimension.FromPixels(84f),
             Height = StyleDimension.FromPixels(84f),
             HAlign = 1f,
             VAlign = 0f
         };
         uIElement.Append(uIWorldCreationPreview);
         _previewPlate = uIWorldCreationPreview;
         num += uICharacterNameButton2.GetDimensions().Height + 10f;
         AddHorizontalSeparator(uIElement, num + 2f);
         float usableWidthPercent = 1f;
         AddWorldSizeOptions(uIElement, num, ClickSizeOption, "size", usableWidthPercent);
         num += 48f;
         AddHorizontalSeparator(uIElement, num);
         AddWorldDifficultyOptions(uIElement, num, ClickDifficultyOption, "difficulty", usableWidthPercent);
         num += 48f;
         AddHorizontalSeparator(uIElement, num);
         AddWorldEvilOptions(uIElement, num, ClickEvilOption, "evil", usableWidthPercent);
         num += 48f;
         AddHorizontalSeparator(uIElement, num);
         AddDescriptionPanel(uIElement, num, "desc");
         SetDefaultOptions();
     }
References _namePlate, _previewPlate, _seedPlate, AddDescriptionPanel(), AddHorizontalSeparator(), AddWorldDifficultyOptions(), AddWorldEvilOptions(), AddWorldSizeOptions(), UIElement.Append(), ClearOptionDescription(), Click_SetName(), Click_SetSeed(), ClickDifficultyOption(), ClickEvilOption(), ClickRandomizeName(), ClickRandomizeSeed(), ClickSizeOption(), Color, StyleDimension.FromPixels(), StyleDimension.FromPixelsAndPercent(), UIElement.GetDimensions(), Language.GetText(), UIElement.HAlign, CalculatedStyle.Height, UIElement.Height, UIElement.Left, UIElement.OnLeftMouseDown, UIElement.OnMouseOut, UIElement.OnMouseOver, UIElement.PaddingBottom, UIElement.PaddingTop, SetDefaultOptions(), UIElement.SetPadding(), UIElement.SetSnapPoint(), ShowOptionDescription(), UIElement.Top, UIElement.VAlign, and UIElement.Width.
Referenced by BuildPage().