Terraria: UIWorldCreation.ClickSizeOption
ClickSizeOption()
void UIWorldCreation.ClickSizeOption (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         GroupOptionButton<WorldSizeId> groupOptionButton = (GroupOptionButton<WorldSizeId>)listeningElement;
         _optionSize = groupOptionButton.OptionValue;
         GroupOptionButton<WorldSizeId>[] sizeButtons = _sizeButtons;
         for (int i = 0; i < sizeButtons.Length; i++)
         {
             sizeButtons[i].SetCurrentOption(groupOptionButton.OptionValue);
         }
         UpdatePreviewPlate();
     }
References _optionSize, _sizeButtons, GroupOptionButton< T >.OptionValue, GroupOptionButton< T >.SetCurrentOption(), and UpdatePreviewPlate().
Referenced by MakeInfoMenu().