Terraria: UIWorldCreation.UpdateSliders
UpdateSliders()
void UIWorldCreation.UpdateSliders () inline private
     {
         GroupOptionButton<WorldSizeId>[] sizeButtons = _sizeButtons;
         for (int i = 0; i < sizeButtons.Length; i++)
         {
             sizeButtons[i].SetCurrentOption(_optionSize);
         }
         GroupOptionButton<WorldDifficultyId>[] difficultyButtons = _difficultyButtons;
         for (int i = 0; i < difficultyButtons.Length; i++)
         {
             difficultyButtons[i].SetCurrentOption(_optionDifficulty);
         }
         GroupOptionButton<WorldEvilId>[] evilButtons = _evilButtons;
         for (int i = 0; i < evilButtons.Length; i++)
         {
             evilButtons[i].SetCurrentOption(_optionEvil);
         }
     }
References _difficultyButtons, _evilButtons, _optionDifficulty, _optionEvil, _optionSize, _sizeButtons, and GroupOptionButton< T >.SetCurrentOption().
Referenced by ClickRandomizeName(), ClickRandomizeSeed(), and OnFinishedSettingSeed().