Terraria: UIWorldCreation.SetDefaultOptions
SetDefaultOptions()
void UIWorldCreation.SetDefaultOptions () inline private
     {
         AssignRandomWorldName();
         AssignRandomWorldSeed();
         UpdateInputFields();
         GroupOptionButton<WorldSizeId>[] sizeButtons = _sizeButtons;
         for (int i = 0; i < sizeButtons.Length; i++)
         {
             sizeButtons[i].SetCurrentOption(WorldSizeId.Medium);
         }
         _optionSize = WorldSizeId.Medium;
         if (Main.ActivePlayerFileData.Player.difficulty == 3)
         {
             GroupOptionButton<WorldDifficultyId>[] difficultyButtons = _difficultyButtons;
             for (int i = 0; i < difficultyButtons.Length; i++)
             {
                 difficultyButtons[i].SetCurrentOption(WorldDifficultyId.Creative);
             }
             _optionDifficulty = WorldDifficultyId.Creative;
             UpdatePreviewPlate();
         }
         else
         {
             GroupOptionButton<WorldDifficultyId>[] difficultyButtons = _difficultyButtons;
             for (int i = 0; i < difficultyButtons.Length; i++)
             {
                 difficultyButtons[i].SetCurrentOption(WorldDifficultyId.Normal);
             }
         }
         GroupOptionButton<WorldEvilId>[] evilButtons = _evilButtons;
         for (int i = 0; i < evilButtons.Length; i++)
         {
             evilButtons[i].SetCurrentOption(WorldEvilId.Random);
         }
     }
References _difficultyButtons, _evilButtons, _optionDifficulty, _optionSize, _sizeButtons, Main.ActivePlayerFileData, AssignRandomWorldName(), AssignRandomWorldSeed(), Player.difficulty, PlayerFileData.Player, GroupOptionButton< T >.SetCurrentOption(), UpdateInputFields(), and UpdatePreviewPlate().
Referenced by MakeInfoMenu().