Terraria: UIWorldCreation.OnFinishedSettingSeed
OnFinishedSettingSeed()
void UIWorldCreation.OnFinishedSettingSeed (string seed) inline private
     {
         _optionSeed = seed.Trim();
         ProcessSeed(out var processedSeed);
         _optionSeed = processedSeed;
         UpdateInputFields();
         UpdateSliders();
         UpdatePreviewPlate();
         GoBackHere();
     }
References _optionSeed, GoBackHere(), ProcessSeed(), UpdateInputFields(), UpdatePreviewPlate(), and UpdateSliders().
Referenced by Click_SetSeed().