Terraria: UIWorldCreation.Click_NamingAndCreating
Click_NamingAndCreating()
void UIWorldCreation.Click_NamingAndCreating (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         SoundEngine.PlaySound(10);
         if (string.IsNullOrEmpty(_optionwWorldName))
         {
             _optionwWorldName = "";
             Main.clrInput();
             UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[48].Value, "", OnFinishedNamingAndCreating, GoBackHere);
             uIVirtualKeyboard.SetMaxInputLength(27);
             Main.MenuUI.SetState(uIVirtualKeyboard);
         }
         else
         {
             FinishCreatingWorld();
         }
     }
References _optionwWorldName, Main.clrInput(), FinishCreatingWorld(), GoBackHere(), Lang.menu, Main.MenuUI, OnFinishedNamingAndCreating(), SoundEngine.PlaySound(), UIVirtualKeyboard.SetMaxInputLength(), UserInterface.SetState(), and LocalizedText.Value.
Referenced by MakeBackAndCreatebuttons().