Terraria: UIWorldCreation.SetupGamepadPoints
SetupGamepadPoints()
void UIWorldCreation.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
     {
         UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
         int num = 3000;
         List<SnapPoint> snapPoints = GetSnapPoints();
         SnapPoint snapPoint = null;
         SnapPoint snapPoint2 = null;
         SnapPoint snapPoint3 = null;
         SnapPoint snapPoint4 = null;
         SnapPoint snapPoint5 = null;
         SnapPoint snapPoint6 = null;
         for (int i = 0; i < snapPoints.Count; i++)
         {
             SnapPoint snapPoint7 = snapPoints[i];
             switch (snapPoint7.Name)
             {
             case "Back":
                 snapPoint = snapPoint7;
                 break;
             case "Create":
                 snapPoint2 = snapPoint7;
                 break;
             case "Name":
                 snapPoint3 = snapPoint7;
                 break;
             case "Seed":
                 snapPoint4 = snapPoint7;
                 break;
             case "RandomizeName":
                 snapPoint5 = snapPoint7;
                 break;
             case "RandomizeSeed":
                 snapPoint6 = snapPoint7;
                 break;
             }
         }
         List<SnapPoint> snapGroup = GetSnapGroup(snapPoints, "size");
         List<SnapPoint> snapGroup2 = GetSnapGroup(snapPoints, "difficulty");
         List<SnapPoint> snapGroup3 = GetSnapGroup(snapPoints, "evil");
         UILinkPointNavigator.SetPosition(num, snapPoint.Position);
         UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint2 = uILinkPoint;
         num++;
         UILinkPointNavigator.SetPosition(num, snapPoint2.Position);
         uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint3 = uILinkPoint;
         num++;
         UILinkPointNavigator.SetPosition(num, snapPoint5.Position);
         uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint4 = uILinkPoint;
         num++;
         UILinkPointNavigator.SetPosition(num, snapPoint3.Position);
         uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint5 = uILinkPoint;
         num++;
         UILinkPointNavigator.SetPosition(num, snapPoint6.Position);
         uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint6 = uILinkPoint;
         num++;
         UILinkPointNavigator.SetPosition(num, snapPoint4.Position);
         uILinkPoint = UILinkPointNavigator.Points[num];
         uILinkPoint.Unlink();
         UILinkPoint uILinkPoint7 = uILinkPoint;
         num++;
         UILinkPoint[] array = new UILinkPoint[snapGroup.Count];
         for (int j = 0; j < snapGroup.Count; j++)
         {
             UILinkPointNavigator.SetPosition(num, snapGroup[j].Position);
             uILinkPoint = UILinkPointNavigator.Points[num];
             uILinkPoint.Unlink();
             array[j] = uILinkPoint;
             num++;
         }
         UILinkPoint[] array2 = new UILinkPoint[snapGroup2.Count];
         for (int k = 0; k < snapGroup2.Count; k++)
         {
             UILinkPointNavigator.SetPosition(num, snapGroup2[k].Position);
             uILinkPoint = UILinkPointNavigator.Points[num];
             uILinkPoint.Unlink();
             array2[k] = uILinkPoint;
             num++;
         }
         UILinkPoint[] array3 = new UILinkPoint[snapGroup3.Count];
         for (int l = 0; l < snapGroup3.Count; l++)
         {
             UILinkPointNavigator.SetPosition(num, snapGroup3[l].Position);
             uILinkPoint = UILinkPointNavigator.Points[num];
             uILinkPoint.Unlink();
             array3[l] = uILinkPoint;
             num++;
         }
         LoopHorizontalLineLinks(array);
         LoopHorizontalLineLinks(array2);
         EstablishUpDownRelationship(array, array2);
         for (int m = 0; m < array.Length; m++)
         {
             array[m].Up = uILinkPoint7.ID;
         }
         if (true)
         {
             LoopHorizontalLineLinks(array3);
             EstablishUpDownRelationship(array2, array3);
             for (int n = 0; n < array3.Length; n++)
             {
                 array3[n].Down = uILinkPoint2.ID;
             }
             array3[array3.Length - 1].Down = uILinkPoint3.ID;
             uILinkPoint3.Up = array3[array3.Length - 1].ID;
             uILinkPoint2.Up = array3[0].ID;
         }
         else
         {
             for (int num2 = 0; num2 < array2.Length; num2++)
             {
                 array2[num2].Down = uILinkPoint2.ID;
             }
             array2[array2.Length - 1].Down = uILinkPoint3.ID;
             uILinkPoint3.Up = array2[array2.Length - 1].ID;
             uILinkPoint2.Up = array2[0].ID;
         }
         uILinkPoint3.Left = uILinkPoint2.ID;
         uILinkPoint2.Right = uILinkPoint3.ID;
         uILinkPoint5.Down = uILinkPoint7.ID;
         uILinkPoint5.Left = uILinkPoint4.ID;
         uILinkPoint4.Right = uILinkPoint5.ID;
         uILinkPoint7.Up = uILinkPoint5.ID;
         uILinkPoint7.Down = array[0].ID;
         uILinkPoint7.Left = uILinkPoint6.ID;
         uILinkPoint6.Right = uILinkPoint7.ID;
         uILinkPoint6.Up = uILinkPoint4.ID;
         uILinkPoint6.Down = array[0].ID;
         uILinkPoint4.Down = uILinkPoint6.ID;
     }
References UILinkPointNavigator.Shortcuts.BackButtonCommand, UILinkPoint.Down, EstablishUpDownRelationship(), GetSnapGroup(), UIElement.GetSnapPoints(), UILinkPoint.ID, UILinkPoint.Left, LoopHorizontalLineLinks(), SnapPoint.Name, UILinkPointNavigator.Points, SnapPoint.Position, UILinkPoint.Right, UILinkPointNavigator.SetPosition(), UILinkPoint.Unlink(), and UILinkPoint.Up.
Referenced by Draw().