Terraria: System.Net.Mime.QuotedPrintableStream.EncodeBytes
EncodeBytes()
int System.Net.Mime.QuotedPrintableStream.EncodeBytes (byte[] buffer, int offset, int count) inline
Definition at line 255 of file QuotedPrintableStream.cs.
    {
        int i;
        for (i = offset; i < count + offset; i++)
        {
            if ((_lineLength != -1 && WriteState.CurrentLineLength + 3 + 2 >= _lineLength && (buffer[i] == 32 || buffer[i] == 9 || buffer[i] == 13 || buffer[i] == 10)) || _writeState.CurrentLineLength + 3 + 2 >= 70)
            {
                if (WriteState.Buffer.Length - WriteState.Length < 3)
                {
                    return i - offset;
                }
                WriteState.Append(61);
                WriteState.AppendCRLF(includeSpace: false);
            }
            if (buffer[i] == 13 && i + 1 < count + offset && buffer[i + 1] == 10)
            {
                if (WriteState.Buffer.Length - WriteState.Length < (_encodeCRLF ? 6 : 2))
                {
                    return i - offset;
                }
                i++;
                if (_encodeCRLF)
                {
                    WriteState.Append(61, 48, 68, 61, 48, 65);
                }
                else
                {
                    WriteState.AppendCRLF(includeSpace: false);
                }
                continue;
            }
            if ((buffer[i] < 32 && buffer[i] != 9) || buffer[i] == 61 || buffer[i] > 126)
            {
                if (WriteState.Buffer.Length - WriteState.Length < 3)
                {
                    return i - offset;
                }
                WriteState.Append(61);
                WriteState.Append(HexEncodeMap[buffer[i] >> 4]);
                WriteState.Append(HexEncodeMap[buffer[i] & 0xF]);
                continue;
            }
            if (WriteState.Buffer.Length - WriteState.Length < 1)
            {
                return i - offset;
            }
            if ((buffer[i] == 9 || buffer[i] == 32) && i + 1 >= count + offset)
            {
                if (WriteState.Buffer.Length - WriteState.Length < 3)
                {
                    return i - offset;
                }
                WriteState.Append(61);
                WriteState.Append(HexEncodeMap[buffer[i] >> 4]);
                WriteState.Append(HexEncodeMap[buffer[i] & 0xF]);
            }
            else
            {
                WriteState.Append(buffer[i]);
            }
        }
        return i - offset;
    }
References System.Net.Mime.QuotedPrintableStream._encodeCRLF, System.Net.Mime.QuotedPrintableStream._lineLength, System.Net.Mime.QuotedPrintableStream._writeState, System.buffer, System.count, System.Net.Mime.WriteStateInfoBase.CurrentLineLength, System.Net.Mime.QuotedPrintableStream.HexEncodeMap, and System.offset.
Referenced by System.Net.Mime.QuotedPrintableStream.EncodeString(), System.Net.Mime.QuotedPrintableStream.WriteAsyncResult.Write(), and System.Net.Mime.QuotedPrintableStream.Write().