Terraria: System.Runtime.Serialization.Formatters.Binary.SerStack.Pop
Pop()
object System.Runtime.Serialization.Formatters.Binary.SerStack.Pop () inline package
Definition at line 25 of file SerStack.cs.
    {
        if (_top < 0)
        {
            return null;
        }
        object result = _objects[_top];
        _objects[_top--] = null;
        return result;
    }
References System.Runtime.Serialization.Formatters.Binary.SerStack._objects, and System.Runtime.Serialization.Formatters.Binary.SerStack._top.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNameInfo(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.GetOp(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseSerializedStreamHeaderEnd(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().