Terraria: System.Runtime.Serialization.Formatters.Binary.SerStack.Peek
Peek()
object System.Runtime.Serialization.Formatters.Binary.SerStack.Peek () inline package
Definition at line 44 of file SerStack.cs.
    {
        if (_top >= 0)
        {
            return _objects[_top];
        }
        return null;
    }
References System.Runtime.Serialization.Formatters.Binary.SerStack._objects, and System.Runtime.Serialization.Formatters.Binary.SerStack._top.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectString(), and System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run().