Terraria: System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic
IsTypeDynamic() [1/2]
static bool System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic (Type type) inline static package
Definition at line 14 of file DynamicAssemblies.cs.
    {
        object obj = s_tableIsTypeDynamic[type];
        if (obj == null)
        {
            Assembly assembly = type.Assembly;
            bool flag = assembly.IsDynamic;
            if (!flag)
            {
                if (type.IsArray)
                {
                    flag = IsTypeDynamic(type.GetElementType());
                }
                else if (type.IsGenericType)
                {
                    Type[] genericArguments = type.GetGenericArguments();
                    if (genericArguments != null)
                    {
                        foreach (Type type2 in genericArguments)
{
                            if (!(type2 == null) && !type2.IsGenericParameter)
{
                                flag = IsTypeDynamic(type2);
                                if (flag)
{
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            obj = (s_tableIsTypeDynamic[type] = flag);
        }
        return (bool)obj;
    }
References System.Xml.Dictionary, System.Type.GetGenericArguments(), System.Reflection.Assembly.IsDynamic, System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), System.obj, System.Xml.Serialization.DynamicAssemblies.s_tableIsTypeDynamic, and System.type.
Referenced by System.Xml.Serialization.Compiler.AddImport(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateGetSerializer(), System.Xml.Serialization.XmlSerializer.GenerateSerializer(), System.Xml.Serialization.TempAssembly.GenerateSerializerToStream(), System.Xml.Serialization.XmlSerializationCodeGen.GenerateSupportedTypes(), System.Xml.Serialization.TypeScope.ImportTypeDesc(), System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic(), and System.Xml.Serialization.DynamicAssemblies.IsTypeDynamic().