Terraria: System.Net.Mail.StartTlsCommand.Send
Send()
static void System.Net.Mail.StartTlsCommand.Send (SmtpConnection conn) inline static package
Definition at line 43 of file StartTlsCommand.cs.
    {
        PrepareCommand(conn);
        string response;
        SmtpStatusCode statusCode = CheckCommand.Send(conn, out response);
        CheckResponse(statusCode, response);
    }
References System.Net.Mail.StartTlsCommand.CheckResponse(), System.Net.Mail.StartTlsCommand.PrepareCommand(), and System.Net.Mail.CheckCommand.Send().
Referenced by System.Net.Mail.SmtpConnection.GetConnection().