Terraria: System.Diagnostics.Tracing.Statics.FormatScalar
FormatScalar()
static TraceLoggingDataType System.Diagnostics.Tracing.Statics.FormatScalar (EventFieldFormat format, TraceLoggingDataType nativeFormat) inline static
Definition at line 133 of file Statics.cs.
    {
        switch (nativeFormat)
        {
        case TraceLoggingDataType.Int8:
        case TraceLoggingDataType.UInt8:
        case TraceLoggingDataType.Boolean8:
            return Format8(format, nativeFormat);
        case TraceLoggingDataType.Int16:
        case TraceLoggingDataType.UInt16:
        case TraceLoggingDataType.Char16:
            return Format16(format, nativeFormat);
        case TraceLoggingDataType.Int32:
        case TraceLoggingDataType.UInt32:
        case TraceLoggingDataType.Float:
            return Format32(format, nativeFormat);
        case TraceLoggingDataType.Int64:
        case TraceLoggingDataType.UInt64:
        case TraceLoggingDataType.Double:
            return Format64(format, nativeFormat);
        default:
            return MakeDataType(nativeFormat, format);
        }
    }
References System.format, System.Diagnostics.Tracing.Statics.Format16(), System.Diagnostics.Tracing.Statics.Format32(), System.Diagnostics.Tracing.Statics.Format64(), System.Diagnostics.Tracing.Statics.Format8(), and System.Diagnostics.Tracing.Statics.MakeDataType().
Referenced by System.Diagnostics.Tracing.ScalarArrayTypeInfo.WriteMetadata(), and System.Diagnostics.Tracing.ScalarTypeInfo.WriteMetadata().