Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteName
WriteName()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteName (string prefix, string name) inline private inherited
Definition at line 432 of file SequentialOutput.cs.
    {
        if (prefix != null && prefix.Length > 0)
        {
            Write(prefix);
            if (name == null || name.Length <= 0)
            {
                return;
            }
            Write(':');
        }
        Write(name);
    }
References System.prefix, and System.Xml.Xsl.XsltOld.SequentialOutput.Write().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord(), System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteAttributes(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteDoctype(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteEndElement(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteProcessingInstruction(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlDeclaration().