Terraria: System.Diagnostics.Tracing.Statics.CreateDefaultTypeInfo
CreateDefaultTypeInfo()
static TraceLoggingTypeInfo System.Diagnostics.Tracing.Statics.CreateDefaultTypeInfo (Type dataType, List< Type > recursionCheck) inline static
Definition at line 219 of file Statics.cs.
    {
        if (recursionCheck.Contains(dataType))
        {
            throw new NotSupportedException(SR.EventSource_RecursiveTypeDefinition);
        }
        recursionCheck.Add(dataType);
        EventDataAttribute customAttribute = GetCustomAttribute<EventDataAttribute>(dataType);
        if (customAttribute != null || GetCustomAttribute<CompilerGeneratedAttribute>(dataType) != null || IsGenericMatch(dataType, typeof(KeyValuePair<, >)))
        {
            TypeAnalysis typeAnalysis = new TypeAnalysis(dataType, customAttribute, recursionCheck);
            return new InvokeTypeInfo(dataType, typeAnalysis);
        }
        if (dataType.IsArray)
        {
            Type elementType = dataType.GetElementType();
            if (elementType == typeof(bool))
            {
                return ScalarArrayTypeInfo.Boolean();
            }
            if (elementType == typeof(byte))
            {
                return ScalarArrayTypeInfo.Byte();
            }
            if (elementType == typeof(sbyte))
            {
                return ScalarArrayTypeInfo.SByte();
            }
            if (elementType == typeof(short))
            {
                return ScalarArrayTypeInfo.Int16();
            }
            if (elementType == typeof(ushort))
            {
                return ScalarArrayTypeInfo.UInt16();
            }
            if (elementType == typeof(int))
            {
                return ScalarArrayTypeInfo.Int32();
            }
            if (elementType == typeof(uint))
            {
                return ScalarArrayTypeInfo.UInt32();
            }
            if (elementType == typeof(long))
            {
                return ScalarArrayTypeInfo.Int64();
            }
            if (elementType == typeof(ulong))
            {
                return ScalarArrayTypeInfo.UInt64();
            }
            if (elementType == typeof(char))
            {
                return ScalarArrayTypeInfo.Char();
            }
            if (elementType == typeof(double))
            {
                return ScalarArrayTypeInfo.Double();
            }
            if (elementType == typeof(float))
            {
                return ScalarArrayTypeInfo.Single();
            }
            if (elementType == typeof(IntPtr))
            {
                return ScalarArrayTypeInfo.IntPtr();
            }
            if (elementType == typeof(UIntPtr))
            {
                return ScalarArrayTypeInfo.UIntPtr();
            }
            if (elementType == typeof(Guid))
            {
                return ScalarArrayTypeInfo.Guid();
            }
            return new ArrayTypeInfo(dataType, TraceLoggingTypeInfo.GetInstance(elementType, recursionCheck));
        }
        if (dataType.IsEnum)
        {
            dataType = Enum.GetUnderlyingType(dataType);
        }
        if (dataType == typeof(string))
        {
            return StringTypeInfo.Instance();
        }
        if (dataType == typeof(bool))
        {
            return ScalarTypeInfo.Boolean();
        }
        if (dataType == typeof(byte))
        {
            return ScalarTypeInfo.Byte();
        }
        if (dataType == typeof(sbyte))
        {
            return ScalarTypeInfo.SByte();
        }
        if (dataType == typeof(short))
        {
            return ScalarTypeInfo.Int16();
        }
        if (dataType == typeof(ushort))
        {
            return ScalarTypeInfo.UInt16();
        }
        if (dataType == typeof(int))
        {
            return ScalarTypeInfo.Int32();
        }
        if (dataType == typeof(uint))
        {
            return ScalarTypeInfo.UInt32();
        }
        if (dataType == typeof(long))
        {
            return ScalarTypeInfo.Int64();
        }
        if (dataType == typeof(ulong))
        {
            return ScalarTypeInfo.UInt64();
        }
        if (dataType == typeof(char))
        {
            return ScalarTypeInfo.Char();
        }
        if (dataType == typeof(double))
        {
            return ScalarTypeInfo.Double();
        }
        if (dataType == typeof(float))
        {
            return ScalarTypeInfo.Single();
        }
        if (dataType == typeof(DateTime))
        {
            return DateTimeTypeInfo.Instance();
        }
        if (dataType == typeof(decimal))
        {
            return DecimalTypeInfo.Instance();
        }
        if (dataType == typeof(IntPtr))
        {
            return ScalarTypeInfo.IntPtr();
        }
        if (dataType == typeof(UIntPtr))
        {
            return ScalarTypeInfo.UIntPtr();
        }
        if (dataType == typeof(Guid))
        {
            return ScalarTypeInfo.Guid();
        }
        if (dataType == typeof(TimeSpan))
        {
            return TimeSpanTypeInfo.Instance();
        }
        if (dataType == typeof(DateTimeOffset))
        {
            return DateTimeOffsetTypeInfo.Instance();
        }
        if (dataType == typeof(EmptyStruct))
        {
            return NullTypeInfo.Instance();
        }
        if (IsGenericMatch(dataType, typeof(Nullable<>)))
        {
            return new NullableTypeInfo(dataType, recursionCheck);
        }
        Type type = FindEnumerableElementType(dataType);
        if (type != null)
        {
            return new EnumerableTypeInfo(dataType, TraceLoggingTypeInfo.GetInstance(type, recursionCheck));
        }
        throw new ArgumentException(SR.Format(SR.EventSource_NonCompliantTypeError, dataType.Name));
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Boolean(), System.Diagnostics.Tracing.ScalarTypeInfo.Boolean(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Byte(), System.Diagnostics.Tracing.ScalarTypeInfo.Byte(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Char(), System.Diagnostics.Tracing.ScalarTypeInfo.Char(), System.Collections.Generic.Dictionary< TKey, TValue >.Contains(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Double(), System.Diagnostics.Tracing.ScalarTypeInfo.Double(), System.elementType, System.SR.EventSource_NonCompliantTypeError, System.SR.EventSource_RecursiveTypeDefinition, System.Diagnostics.Tracing.Statics.FindEnumerableElementType(), System.SR.Format(), System.Type.GetElementType(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.GetInstance(), System.Enum.GetUnderlyingType(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Guid(), System.Diagnostics.Tracing.ScalarTypeInfo.Guid(), System.Diagnostics.Tracing.DateTimeOffsetTypeInfo.Instance(), System.Diagnostics.Tracing.DateTimeTypeInfo.Instance(), System.Diagnostics.Tracing.DecimalTypeInfo.Instance(), System.Diagnostics.Tracing.NullTypeInfo.Instance(), System.Diagnostics.Tracing.StringTypeInfo.Instance(), System.Diagnostics.Tracing.TimeSpanTypeInfo.Instance(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int16(), System.Diagnostics.Tracing.ScalarTypeInfo.Int16(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int32(), System.Diagnostics.Tracing.ScalarTypeInfo.Int32(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Int64(), System.Diagnostics.Tracing.ScalarTypeInfo.Int64(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.IntPtr(), System.Diagnostics.Tracing.ScalarTypeInfo.IntPtr(), System.Type.IsArray, System.Type.IsEnum, System.Diagnostics.Tracing.Statics.IsGenericMatch(), System.Reflection.MemberInfo.Name, System.Diagnostics.Tracing.ScalarArrayTypeInfo.SByte(), System.Diagnostics.Tracing.ScalarTypeInfo.SByte(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.Single(), System.Diagnostics.Tracing.ScalarTypeInfo.Single(), System.type, System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt16(), System.Diagnostics.Tracing.ScalarTypeInfo.UInt16(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt32(), System.Diagnostics.Tracing.ScalarTypeInfo.UInt32(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UInt64(), System.Diagnostics.Tracing.ScalarTypeInfo.UInt64(), System.Diagnostics.Tracing.ScalarArrayTypeInfo.UIntPtr(), and System.Diagnostics.Tracing.ScalarTypeInfo.UIntPtr().
Referenced by System.Diagnostics.Tracing.TraceLoggingTypeInfo.GetInstance().