Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord
OutputRecord() [2/2]
void System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord (RecordBuilder record) inline private inherited
Definition at line 343 of file SequentialOutput.cs.
    {
        BuilderInfo mainNode = record.MainNode;
        if (_outputXmlDecl)
        {
            WriteXmlDeclaration();
        }
        switch (mainNode.NodeType)
        {
        case XmlNodeType.Element:
            WriteStartElement(record);
            break;
        case XmlNodeType.Text:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            WriteTextNode(record);
            break;
        case XmlNodeType.EntityReference:
            Write('&');
            WriteName(mainNode.Prefix, mainNode.LocalName);
            Write(';');
            break;
        case XmlNodeType.ProcessingInstruction:
            WriteProcessingInstruction(record);
            break;
        case XmlNodeType.Comment:
            Indent(record);
            Write("<!--");
            Write(mainNode.Value);
            Write("-->");
            break;
        case XmlNodeType.DocumentType:
            Write(mainNode.Value);
            break;
        case XmlNodeType.EndElement:
            WriteEndElement(record);
            break;
        case XmlNodeType.Attribute:
        case XmlNodeType.CDATA:
        case XmlNodeType.Entity:
        case XmlNodeType.Document:
        case XmlNodeType.DocumentFragment:
        case XmlNodeType.Notation:
            break;
        }
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._outputXmlDecl, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.SequentialOutput.Indent(), System.Xml.Xsl.XsltOld.SequentialOutput.Write(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteEndElement(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteName(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteProcessingInstruction(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteTextNode(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlDeclaration().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.OutputCachedRecords(), and System.Xml.Xsl.XsltOld.SequentialOutput.RecordDone().