Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteWithReplace
WriteWithReplace()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteWithReplace (string value, char[] find, string[] replace) inline private inherited
Definition at line 533 of file SequentialOutput.cs.
    {
        int length = value.Length;
        int i;
        for (i = 0; i < length; i++)
        {
            int num = value.IndexOfAny(find, i);
            if (num == -1)
            {
                break;
            }
            for (; i < num; i++)
            {
                Write(value[i]);
            }
            char c = value[i];
            int num2 = find.Length - 1;
            while (0 <= num2)
            {
                if (find[num2] == c)
                {
                    Write(replace[num2]);
                    break;
                }
                num2--;
            }
        }
        if (i == 0)
        {
            Write(value);
            return;
        }
        for (; i < length; i++)
        {
            Write(value[i]);
        }
    }
References System.Xml.Dictionary, System.length, System.value, and System.Xml.Xsl.XsltOld.SequentialOutput.Write().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.WriteTextNode(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlAttributeValue().