Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlDeclaration
WriteXmlDeclaration()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlDeclaration () inline private inherited
Definition at line 207 of file SequentialOutput.cs.
    {
        _outputXmlDecl = false;
        Indent(0);
        Write("<?");
        WriteName(string.Empty, "xml");
        Write(" version=\"1.0\"");
        if (encoding != null)
        {
            Write(" encoding=\"");
            Write(encoding.WebName);
            Write('"');
        }
        if (_output.HasStandalone)
        {
            Write(" standalone=\"");
            Write(_output.Standalone ? "yes" : "no");
            Write('"');
        }
        Write("?>");
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._output, System.Xml.Xsl.XsltOld.SequentialOutput._outputXmlDecl, System.Xml.Xsl.XsltOld.SequentialOutput.encoding, System.Xml.Xsl.XsltOld.XsltOutput.HasStandalone, System.Xml.Xsl.XsltOld.SequentialOutput.Indent(), System.Xml.Xsl.XsltOld.XsltOutput.Standalone, System.Text.Encoding.WebName, System.Xml.Xsl.XsltOld.SequentialOutput.Write(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteName().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord(), and System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord().