Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteHtmlUri
WriteHtmlUri()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteHtmlUri (string value) inline private inherited
Definition at line 481 of file SequentialOutput.cs.
    {
        int length = value.Length;
        int num = 0;
        while (num < length)
        {
            char c = value[num];
            num++;
            switch (c)
            {
            case '&':
                if (num != length && value[num] == '{')
                {
                    Write(c);
                }
                else
                {
                    Write("&amp;");
                }
                continue;
            case '"':
                Write("&quot;");
                continue;
            case '\n':
                Write("&#xA;");
                continue;
            case '\r':
                Write("&#xD;");
                continue;
            }
            if ('\u007f' < c)
            {
                if (_utf8Encoding == null)
                {
                    _utf8Encoding = Encoding.UTF8;
                    _byteBuffer = new byte[_utf8Encoding.GetMaxByteCount(1)];
                }
                int bytes = _utf8Encoding.GetBytes(value, num - 1, 1, _byteBuffer, 0);
                for (int i = 0; i < bytes; i++)
                {
                    Write("%");
                    uint num2 = _byteBuffer[i];
                    Write(num2.ToString("X2", CultureInfo.InvariantCulture));
                }
            }
            else
            {
                Write(c);
            }
        }
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._byteBuffer, System.Xml.Xsl.XsltOld.SequentialOutput._utf8Encoding, System.bytes, System.Xml.Dictionary, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetMaxByteCount(), System.Globalization.CultureInfo.InvariantCulture, System.length, System.Text.Encoding.UTF8, System.value, and System.Xml.Xsl.XsltOld.SequentialOutput.Write().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.WriteAttributes().