Terraria: System.Diagnostics.Tracing.Statics.MetadataForString
MetadataForString()
static byte[] System.Diagnostics.Tracing.Statics.MetadataForString (string name, int prefixSize, int suffixSize, int additionalSize) inline static
Definition at line 17 of file Statics.cs.
    {
        CheckName(name);
        int num = Encoding.UTF8.GetByteCount(name) + 3 + prefixSize + suffixSize;
        byte[] array = new byte[num];
        ushort num2 = checked((ushort)(num + additionalSize));
        array[0] = (byte)num2;
        array[1] = (byte)(num2 >> 8);
        Encoding.UTF8.GetBytes(name, 0, name.Length, array, 2 + prefixSize);
        return array;
    }
References System.array, System.Diagnostics.Tracing.Statics.CheckName(), and System.Text.Encoding.UTF8.
Referenced by System.Diagnostics.Tracing.NameInfo.NameInfo(), and System.Diagnostics.Tracing.EventSource.InitializeProviderMetadata().