Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.Write
Write() [1/2]
void System.Xml.Xsl.XsltOld.SequentialOutput.Write (char outputChar) abstract package
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.Indent(), System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord(), System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteAttributes(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteCData(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteCDataSection(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteDoctype(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteEndElement(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteHtmlAttributeValue(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteHtmlUri(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteName(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteProcessingInstruction(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteTextNode(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteTextNode(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteWithReplace(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteXmlDeclaration().