Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.DecideDefaultOutput
DecideDefaultOutput()
bool System.Xml.Xsl.XsltOld.SequentialOutput.DecideDefaultOutput (BuilderInfo node) inline private inherited
Definition at line 291 of file SequentialOutput.cs.
    {
        XsltOutput.OutputMethod defaultOutput = XsltOutput.OutputMethod.Xml;
        switch (node.NodeType)
        {
        case XmlNodeType.Element:
            if (node.NamespaceURI.Length == 0 && string.Equals("html", node.LocalName, StringComparison.OrdinalIgnoreCase))
            {
                defaultOutput = XsltOutput.OutputMethod.Html;
            }
            break;
        case XmlNodeType.Text:
        case XmlNodeType.Whitespace:
        case XmlNodeType.SignificantWhitespace:
            if (XmlCharType.IsOnlyWhitespace(node.Value))
            {
                return false;
            }
            defaultOutput = XsltOutput.OutputMethod.Xml;
            break;
        default:
            return false;
        }
        if (_processor.SetDefaultOutput(defaultOutput))
        {
            CacheOuptutProps(_processor.Output);
        }
        return true;
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._processor, System.Xml.Xsl.XsltOld.SequentialOutput.CacheOuptutProps(), System.Xml.Dictionary, System.Xml.XmlCharType.IsOnlyWhitespace(), System.Xml.Xsl.XsltOld.Processor.Output, and System.Xml.Xsl.XsltOld.Processor.SetDefaultOutput().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.RecordDone().