Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteDoctype
WriteDoctype()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteDoctype (BuilderInfo mainNode) inline private inherited
Definition at line 174 of file SequentialOutput.cs.
    {
        Indent(0);
        Write("<!DOCTYPE ");
        if (_isXmlOutput)
        {
            WriteName(mainNode.Prefix, mainNode.LocalName);
        }
        else
        {
            WriteName(string.Empty, "html");
        }
        Write(' ');
        if (_output.DoctypePublic != null)
        {
            Write("PUBLIC ");
            Write('"');
            Write(_output.DoctypePublic);
            Write("\" ");
        }
        else
        {
            Write("SYSTEM ");
        }
        if (_output.DoctypeSystem != null)
        {
            Write('"');
            Write(_output.DoctypeSystem);
            Write('"');
        }
        Write('>');
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._isXmlOutput, System.Xml.Xsl.XsltOld.SequentialOutput._output, System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltOutput.DoctypePublic, System.Xml.Xsl.XsltOld.XsltOutput.DoctypeSystem, System.Xml.Xsl.XsltOld.SequentialOutput.Indent(), System.Xml.Xsl.XsltOld.SequentialOutput.Write(), and System.Xml.Xsl.XsltOld.SequentialOutput.WriteName().
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement().