Terraria: System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement
WriteStartElement()
void System.Xml.Xsl.XsltOld.SequentialOutput.WriteStartElement (RecordBuilder record) inline private inherited
Definition at line 72 of file SequentialOutput.cs.
    {
        BuilderInfo mainNode = record.MainNode;
        HtmlElementProps htmlElementProps = null;
        if (_isHtmlOutput)
        {
            if (mainNode.Prefix.Length == 0)
            {
                htmlElementProps = mainNode.htmlProps;
                if (htmlElementProps == null && mainNode.search)
                {
                    htmlElementProps = HtmlElementProps.GetProps(mainNode.LocalName);
                }
                record.Manager.CurrentElementScope.HtmlElementProps = htmlElementProps;
                mainNode.IsEmptyTag = false;
            }
        }
        else if (_isXmlOutput && mainNode.Depth == 0)
        {
            if (_secondRoot && (_output.DoctypeSystem != null || _output.Standalone))
            {
                throw XsltException.Create(System.SR.Xslt_MultipleRoots);
            }
            _secondRoot = true;
        }
        if (_outputDoctype)
        {
            WriteDoctype(mainNode);
            _outputDoctype = false;
        }
        if (_cdataElements != null && _cdataElements.Contains(new XmlQualifiedName(mainNode.LocalName, mainNode.NamespaceURI)) && _isXmlOutput)
        {
            record.Manager.CurrentElementScope.ToCData = true;
        }
        Indent(record);
        Write('<');
        WriteName(mainNode.Prefix, mainNode.LocalName);
        WriteAttributes(record.AttributeList, record.AttributeCount, htmlElementProps);
        if (mainNode.IsEmptyTag)
        {
            Write(" />");
        }
        else
        {
            Write('>');
        }
        if (htmlElementProps != null && htmlElementProps.Head)
        {
            mainNode.Depth++;
            Indent(record);
            mainNode.Depth--;
            Write("<META http-equiv=\"Content-Type\" content=\"");
            Write(_output.MediaType);
            Write("; charset=");
            Write(encoding.WebName);
            Write("\">");
        }
    }
References System.Xml.Xsl.XsltOld.SequentialOutput._cdataElements, System.Xml.Xsl.XsltOld.SequentialOutput._isHtmlOutput, System.Xml.Xsl.XsltOld.SequentialOutput._isXmlOutput, System.Xml.Xsl.XsltOld.SequentialOutput._output, System.Xml.Xsl.XsltOld.SequentialOutput._outputDoctype, System.Xml.Xsl.XsltOld.SequentialOutput._secondRoot, System.Collections.Hashtable.Contains(), System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.Xsl.XsltOld.XsltOutput.DoctypeSystem, System.Xml.Xsl.XsltOld.SequentialOutput.encoding, System.Xml.Xsl.XsltOld.HtmlElementProps.GetProps(), System.Xml.Xsl.XsltOld.SequentialOutput.Indent(), System.Xml.Xsl.XsltOld.XsltOutput.MediaType, System.Xml.Xsl.XsltOld.XsltOutput.Standalone, System.Text.Encoding.WebName, System.Xml.Xsl.XsltOld.SequentialOutput.Write(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteAttributes(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteDoctype(), System.Xml.Xsl.XsltOld.SequentialOutput.WriteName(), and System.SR.Xslt_MultipleRoots.
Referenced by System.Xml.Xsl.XsltOld.SequentialOutput.OutputRecord().