Terraria: System.TimeZoneInfo.CachedData.GetCurrentOneYearLocal
GetCurrentOneYearLocal()
static TimeZoneInfo System.TimeZoneInfo.CachedData.GetCurrentOneYearLocal () inline static private
Definition at line 279 of file TimeZoneInfo.cs.
        {
            Interop.Kernel32.TIME_ZONE_INFORMATION lpTimeZoneInformation;
            uint timeZoneInformation = Interop.Kernel32.GetTimeZoneInformation(out lpTimeZoneInformation);
            if (timeZoneInformation != uint.MaxValue)
            {
                return GetLocalTimeZoneFromWin32Data(in lpTimeZoneInformation, dstDisabled: false);
            }
            return CreateCustomTimeZone("Local", TimeSpan.Zero, "Local", "Local");
        }
References System.TimeZoneInfo.CreateCustomTimeZone(), System.Runtime.Serialization.Dictionary, System.TimeZoneInfo.GetLocalTimeZoneFromWin32Data(), Interop.Kernel32.GetTimeZoneInformation(), and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.CachedData.GetOneYearLocalFromUtc().