Terraria: PlayerFileData.MoveToCloud
MoveToCloud()
override void PlayerFileData.MoveToCloud () inline virtual
Implements FileData.
     {
         if (base.IsCloudSave || SocialAPI.Cloud == null)
         {
             return;
         }
         string playerPathFromName = Main.GetPlayerPathFromName(Name, cloudSave: true);
         if (!FileUtilities.MoveToCloud(base.Path, playerPathFromName))
         {
             return;
         }
         string fileName = GetFileName(includeExtension: false);
         string path = Main.PlayerPath + System.IO.Path.DirectorySeparatorChar + fileName + System.IO.Path.DirectorySeparatorChar;
         if (Directory.Exists(path))
         {
             string[] files = Directory.GetFiles(path);
             for (int i = 0; i < files.Length; i++)
             {
                 string cloudPath = Main.CloudPlayerPath + "/" + fileName + "/" + FileUtilities.GetFileName(files[i]);
                 FileUtilities.MoveToCloud(files[i], cloudPath);
             }
         }
         Main.LocalFavoriteData.ClearEntry(this);
         _isCloudSave = true;
         _path = playerPathFromName;
         Main.CloudFavoritesData.SaveFavorite(this);
     }
References FileData._isCloudSave, FileData._path, FavoritesFile.ClearEntry(), SocialAPI.Cloud, Main.CloudFavoritesData, Main.CloudPlayerPath, FileData.GetFileName(), FileUtilities.GetFileName(), Main.GetPlayerPathFromName(), Main.LocalFavoriteData, FileUtilities.MoveToCloud(), FileData.Name, Main.PlayerPath, and FavoritesFile.SaveFavorite().
Referenced by UICharacterListItem.CloudButtonClick().