Terraria: PlayerFileData.CreateAndSave
CreateAndSave()
static PlayerFileData PlayerFileData.CreateAndSave (Player player) inline static
     {
         PlayerFileData playerFileData = new PlayerFileData();
         playerFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.Player);
         playerFileData.Player = player;
         playerFileData._isCloudSave = SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault;
         playerFileData._path = Main.GetPlayerPathFromName(player.name, playerFileData.IsCloudSave);
         (playerFileData.IsCloudSave ? Main.CloudFavoritesData : Main.LocalFavoriteData).ClearEntry(playerFileData);
         Player.SavePlayer(playerFileData, skipMapSave: true);
         return playerFileData;
     }
References PlayerFileData(), FileData._isCloudSave, FileData._path, SocialAPI.Cloud, Main.CloudFavoritesData, CloudSocialModule.EnabledByDefault, FileMetadata.FromCurrentSettings(), Main.GetPlayerPathFromName(), FileData.IsCloudSave, Main.LocalFavoriteData, FileData.Metadata, Player.name, Player, and Player.SavePlayer().
Referenced by UICharacterCreation.FinishCreatingCharacter(), and Main.OnCharacterNamed().