Terraria: PlayerFileData.MoveToLocal
MoveToLocal()
override void PlayerFileData.MoveToLocal () inline virtual
Implements FileData.
     {
         if (!base.IsCloudSave || SocialAPI.Cloud == null)
         {
             return;
         }
         string playerPathFromName = Main.GetPlayerPathFromName(Name, cloudSave: false);
         if (!FileUtilities.MoveToLocal(base.Path, playerPathFromName))
         {
             return;
         }
         string fileName = GetFileName(includeExtension: false);
         string mapPath = System.IO.Path.Combine(Main.CloudPlayerPath, fileName);
         foreach (string item in (from path in SocialAPI.Cloud.GetFiles().ToList()
             where MapBelongsToPath(mapPath, path)
             select path).ToList())
         {
             string localPath = System.IO.Path.Combine(Main.PlayerPath, fileName, FileUtilities.GetFileName(item));
             FileUtilities.MoveToLocal(item, localPath);
         }
         Main.CloudFavoritesData.ClearEntry(this);
         _isCloudSave = false;
         _path = playerPathFromName;
         Main.LocalFavoriteData.SaveFavorite(this);
     }
References FileData._isCloudSave, FileData._path, FavoritesFile.ClearEntry(), SocialAPI.Cloud, Main.CloudFavoritesData, Main.CloudPlayerPath, FileData.GetFileName(), FileUtilities.GetFileName(), CloudSocialModule.GetFiles(), Main.GetPlayerPathFromName(), Main.LocalFavoriteData, MapBelongsToPath(), FileUtilities.MoveToLocal(), FileData.Name, Main.PlayerPath, and FavoritesFile.SaveFavorite().
Referenced by UICharacterListItem.CloudButtonClick().