Terraria: Microsoft.Xna.Framework.Helpers.CheckDisposed
CheckDisposed()
static void Microsoft.Xna.Framework.Helpers.CheckDisposed (object obj, IntPtr pComPtr) inline static
Definition at line 188 of file Helpers.cs.
    {
        if (pComPtr == IntPtr.Zero)
        {
            throw new ObjectDisposedException(obj.GetType().Name);
        }
    }
References System.obj, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.Effect.Effect(), Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.BlendState.Apply(), Microsoft.Xna.Framework.Graphics.DepthStencilState.Apply(), Microsoft.Xna.Framework.Graphics.RasterizerState.Apply(), Microsoft.Xna.Framework.Graphics.SamplerState.Apply(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawInstancedPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers(), Microsoft.Xna.Framework.Graphics.Effect.OnLostDevice(), Microsoft.Xna.Framework.Graphics.Effect.OnResetDevice(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Present(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), Microsoft.Xna.Framework.Graphics.TextureCollection.ResetState(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTargets(), Microsoft.Xna.Framework.Graphics.EffectParameter.SetValue(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers().