Terraria: Microsoft.Xna.Framework.Helpers.GetExceptionFromResult
GetExceptionFromResult()
static Exception Microsoft.Xna.Framework.Helpers.GetExceptionFromResult (uint result) inline static
Definition at line 115 of file Helpers.cs.
    {
        if (result == 0)
        {
            return null;
        }
        switch (result)
        {
        case 2289436696u:
            return new ArgumentException(FrameworkResources.WrongTextureFormat);
        case 2289436774u:
            return new ArgumentException(FrameworkResources.NotFound);
        case 2289436775u:
            return new ArgumentException(FrameworkResources.MoreData);
        case 2289436701u:
            return new InvalidOperationException(FrameworkResources.TooManyOperations);
        case 2289436786u:
            return new InvalidOperationException(FrameworkResources.InvalidCall);
        case 2328297475u:
            return new InvalidOperationException(FrameworkResources.Expired);
        case 2328297478u:
            return new InvalidOperationException(FrameworkResources.InvalidUsage);
        case 2328297494u:
            return new InvalidOperationException(FrameworkResources.WaveBankNotPrepared);
        case 2328297482u:
            return new IndexOutOfRangeException(FrameworkResources.InvalidVariableIndex);
        case 2328297485u:
            return new IndexOutOfRangeException(FrameworkResources.InvalidWaveIndex);
        case 2328297486u:
            return new IndexOutOfRangeException(FrameworkResources.InvalidTrackIndex);
        case 2328297487u:
            return new IndexOutOfRangeException(FrameworkResources.InvalidSoundOffsetOrIndex);
        case 2328297488u:
            return new IOException(FrameworkResources.XactReadFile);
        case 2328297479u:
            return new ArgumentException(FrameworkResources.InvalidContentVersion);
        case 2328297483u:
            return new ArgumentException(FrameworkResources.InvalidCategory);
        case 2328297484u:
            return new IndexOutOfRangeException(FrameworkResources.InvalidCue);
        case 2328297490u:
            return new InvalidOperationException(FrameworkResources.InCallback);
        case 2328297491u:
            return new InvalidOperationException(FrameworkResources.NoWaveBank);
        case 2328297492u:
            return new InvalidOperationException(FrameworkResources.SelectVariation);
        case 2328297495u:
            return new NoAudioHardwareException();
        case 2328297496u:
            return new ArgumentException(FrameworkResources.InvalidEntryCount);
        case 2328297480u:
        case 2343370753u:
            return new InstancePlayLimitException(FrameworkResources.InstancePlayFailedDueToLimit);
        case 2147746390u:
            return new InvalidOperationException(FrameworkResources.NoAudioPlaybackDevicesFound);
        case 2364407809u:
            return new NoMicrophoneConnectedException();
        case 2147500033u:
            return new NotImplementedException();
        case 2147942487u:
            return new ArgumentException();
        case 2147942405u:
            return new UnauthorizedAccessException();
        case 2147942414u:
            throw new OutOfMemoryException();
        case 2147500036u:
            throw new InvalidOperationException(FrameworkResources.ResourceInUse);
        default:
            return new InvalidOperationException(FrameworkResources.UnexpectedError);
        }
    }
References Microsoft.Xna.Framework.FrameworkResources.Expired, Microsoft.Xna.Framework.FrameworkResources.InCallback, Microsoft.Xna.Framework.FrameworkResources.InstancePlayFailedDueToLimit, Microsoft.Xna.Framework.FrameworkResources.InvalidCall, Microsoft.Xna.Framework.FrameworkResources.InvalidCategory, Microsoft.Xna.Framework.FrameworkResources.InvalidContentVersion, Microsoft.Xna.Framework.FrameworkResources.InvalidCue, Microsoft.Xna.Framework.FrameworkResources.InvalidEntryCount, Microsoft.Xna.Framework.FrameworkResources.InvalidSoundOffsetOrIndex, Microsoft.Xna.Framework.FrameworkResources.InvalidTrackIndex, Microsoft.Xna.Framework.FrameworkResources.InvalidUsage, Microsoft.Xna.Framework.FrameworkResources.InvalidVariableIndex, Microsoft.Xna.Framework.FrameworkResources.InvalidWaveIndex, Microsoft.Xna.Framework.FrameworkResources.MoreData, Microsoft.Xna.Framework.FrameworkResources.NoAudioPlaybackDevicesFound, Microsoft.Xna.Framework.FrameworkResources.NotFound, Microsoft.Xna.Framework.FrameworkResources.NoWaveBank, Microsoft.Xna.Framework.FrameworkResources.ResourceInUse, Microsoft.Xna.Framework.FrameworkResources.SelectVariation, Microsoft.Xna.Framework.FrameworkResources.TooManyOperations, Microsoft.Xna.Framework.FrameworkResources.UnexpectedError, Microsoft.Xna.Framework.FrameworkResources.WaveBankNotPrepared, Microsoft.Xna.Framework.FrameworkResources.WrongTextureFormat, and Microsoft.Xna.Framework.FrameworkResources.XactReadFile.
Referenced by Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Helpers.ThrowExceptionFromErrorCode(), Microsoft.Xna.Framework.Helpers.ThrowExceptionFromErrorCode(), and Microsoft.Xna.Framework.Helpers.ThrowExceptionFromResult().