Terraria: Microsoft.Xna.Framework.Helpers.ValidateCopyParameters
ValidateCopyParameters()
static void Microsoft.Xna.Framework.Helpers.ValidateCopyParameters (int dataLength, int dataIndex, int elementCount) inline static
Definition at line 66 of file Helpers.cs.
    {
        if (dataIndex < 0 || dataIndex > dataLength)
        {
            throw new ArgumentOutOfRangeException("dataIndex", FrameworkResources.MustBeValidIndex);
        }
        if (elementCount + dataIndex > dataLength)
        {
            throw new ArgumentOutOfRangeException("elementCount", FrameworkResources.MustBeValidIndex);
        }
        if (elementCount <= 0)
        {
            throw new ArgumentOutOfRangeException("elementCount", FrameworkResources.MustBeValidIndex);
        }
    }
References Microsoft.Xna.Framework.FrameworkResources.MustBeValidIndex.
Referenced by Microsoft.Xna.Framework.Graphics.TextureCube.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.CopyData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.CopyData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.CopyData< T >(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >().