Terraria: Microsoft.Xna.Framework.Helpers.SmartGetHashCode
SmartGetHashCode()
static unsafe int Microsoft.Xna.Framework.Helpers.SmartGetHashCode (object obj) inline static
Definition at line 43 of file Helpers.cs.
    {
        GCHandle gCHandle = GCHandle.Alloc(obj, GCHandleType.Pinned);
        try
        {
            int num = Marshal.SizeOf(obj);
            int num2 = 0;
            int num3 = 0;
            int* ptr = (int*)gCHandle.AddrOfPinnedObject().ToPointer();
            while (num2 + 4 <= num)
            {
                num3 ^= *ptr;
                num2 += 4;
                ptr++;
            }
            return (num3 == 0) ? int.MaxValue : num3;
        }
        finally
        {
            gCHandle.Free();
        }
    }
References System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.GCHandle.Free(), System.obj, System.Runtime.InteropServices.Marshal.SizeOf(), and System.IntPtr.ToPointer().
Referenced by Microsoft.Xna.Framework.Graphics.VertexElement.GetHashCode(), Microsoft.Xna.Framework.Graphics.VertexPositionColor.GetHashCode(), Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.GetHashCode(), Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture.GetHashCode(), and Microsoft.Xna.Framework.Graphics.VertexPositionTexture.GetHashCode().