Terraria: Microsoft.Xna.Framework.Helpers.ThrowExceptionFromResult
ThrowExceptionFromResult()
static void Microsoft.Xna.Framework.Helpers.ThrowExceptionFromResult (uint result) inline static
Definition at line 103 of file Helpers.cs.
    {
        if (result == 0)
        {
            return;
        }
        throw GetExceptionFromResult(result);
    }
References Microsoft.Xna.Framework.Helpers.GetExceptionFromResult().
Referenced by Microsoft.Xna.Framework.UserAsyncDispatcher.AsyncDispatcherThreadFunction(), and Microsoft.Xna.Framework.UserAsyncDispatcher.PlatformSpecificInitialize().