Terraria: Terraria.GameContent.Shaders.WaterShaderData.Apply
Apply()
override void Terraria.GameContent.Shaders.WaterShaderData.Apply () inline virtual
Reimplemented from Terraria.Graphics.Shaders.ShaderData.
Definition at line 358 of file WaterShaderData.cs.
    {
        if (_usingRenderTargets && Main.IsGraphicsDeviceAvailable)
        {
            UseProgress(_progress);
            Main.graphics.GraphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
            Vector2 vector = new Vector2(Main.screenWidth, Main.screenHeight) * 0.5f * (Vector2.One - Vector2.One / Main.GameViewMatrix.Zoom);
            Vector2 vector2 = (Main.drawToScreen ? Vector2.Zero : new Vector2(Main.offScreenRange, Main.offScreenRange)) - Main.screenPosition - vector;
            UseImage(_distortionTarget, 1);
            UseImage(Main.waterTarget, 2, SamplerState.PointClamp);
            UseTargetPosition(Main.screenPosition - Main.sceneWaterPos + new Vector2(Main.offScreenRange, Main.offScreenRange) + vector);
            UseImageOffset(-(vector2 * 0.25f - _lastDistortionDrawOffset) / new Vector2(_distortionTarget.Width, _distortionTarget.Height));
            base.Apply();
        }
    }
References Terraria.GameContent.Shaders.WaterShaderData._distortionTarget, Terraria.GameContent.Shaders.WaterShaderData._lastDistortionDrawOffset, Terraria.GameContent.Shaders.WaterShaderData._progress, Terraria.GameContent.Shaders.WaterShaderData._usingRenderTargets, Terraria.Main.GameViewMatrix, Terraria.Main.graphics, Microsoft.Xna.Framework.Graphics.Texture2D.Height, Terraria.Main.IsGraphicsDeviceAvailable, Terraria.Main.offScreenRange, Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp, Terraria.Main.sceneWaterPos, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Graphics.Shaders.ScreenShaderData.UseImage(), Terraria.Graphics.Shaders.ScreenShaderData.UseImageOffset(), Terraria.Graphics.Shaders.ScreenShaderData.UseProgress(), Terraria.Graphics.Shaders.ScreenShaderData.UseTargetPosition(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Main.waterTarget, and Microsoft.Xna.Framework.Graphics.Texture2D.Width.