Terraria: Terraria.GameContent.Shaders.WaterShaderData.QueueRipple
QueueRipple() [3/3]
void Terraria.GameContent.Shaders.WaterShaderData.QueueRipple (Vector2 position, float strength = 1f, RippleShape shape = RippleShape::Square, float rotation = 0f) inline
Definition at line 436 of file WaterShaderData.cs.
    {
        float g = strength * 0.5f + 0.5f;
        float num = Math.Min(Math.Abs(strength), 1f);
        QueueRipple(position, new Color(0.5f, g, 0f, 1f) * num, new Vector2(4f * Math.Max(Math.Abs(strength), 1f)), shape, rotation);
    }
References System.Math.Abs(), Microsoft.Xna.Framework.Graphics.Color, System.Math.Max(), System.Math.Min(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), and Terraria.GameContent.Shaders.WaterShaderData.QueueRipple().