Terraria: FileUtilities.Copy
Copy()
static void FileUtilities.Copy (string source, string destination, bool cloud, bool overwrite = true) inline static
     {
         if (!cloud)
         {
             try
             {
                 File.Copy(source, destination, overwrite);
                 return;
             }
             catch (IOException ex)
             {
                 if (ex.GetType() != typeof(IOException))
                 {
                     throw;
                 }
                 using FileStream fileStream = File.OpenRead(source);
                 using FileStream destination2 = File.Create(destination);
                 fileStream.CopyTo(destination2);
                 return;
             }
         }
         if (SocialAPI.Cloud != null && (overwrite || !SocialAPI.Cloud.HasFile(destination)))
         {
             SocialAPI.Cloud.Write(destination, SocialAPI.Cloud.Read(source));
         }
     }
References SocialAPI.Cloud, CloudSocialModule.HasFile(), CloudSocialModule.Read(), and CloudSocialModule.Write().
Referenced by WorldFileData.CopyToLocal(), Player.InternalSavePlayerFile(), Move(), WorldGen.playWorldCallBack(), WorkshopHelper.UGCBased.WorldPublisherInstance.PrepareContentForUpdate(), and WorldGen.serverLoadWorldCallBack().