Terraria: FileUtilities.MoveToCloud
MoveToCloud()
static bool FileUtilities.MoveToCloud (string localPath, string cloudPath) inline static
     {
         if (SocialAPI.Cloud == null)
         {
             return false;
         }
         WriteAllBytes(cloudPath, ReadAllBytes(localPath, cloud: false), cloud: true);
         Delete(localPath, cloud: false);
         return true;
     }
References SocialAPI.Cloud, Delete(), ReadAllBytes(), and WriteAllBytes().
Referenced by PlayerFileData.MoveToCloud(), and WorldFileData.MoveToCloud().