Terraria: System.Diagnostics.Tracing.ActivityTracker.OnStart
OnStart()
void System.Diagnostics.Tracing.ActivityTracker.OnStart (string providerName, string activityName, int task, ref Guid activityId, ref Guid relatedActivityId, EventActivityOptions options, bool useTplSource = true) inline
Definition at line 202 of file ActivityTracker.cs.
    {
        if (m_current == null)
        {
            if (m_checkedForEnable)
            {
                return;
            }
            m_checkedForEnable = true;
            if (useTplSource && TplEventSource.Log.IsEnabled(EventLevel.Informational, (EventKeywords)128L))
            {
                Enable();
            }
            if (m_current == null)
            {
                return;
            }
        }
        ActivityInfo value = m_current.Value;
        string text = NormalizeActivityName(providerName, activityName, task);
        TplEventSource tplEventSource = (useTplSource ? TplEventSource.Log : null);
        bool flag = tplEventSource?.Debug ?? false;
        if (flag)
        {
            tplEventSource.DebugFacilityMessage("OnStartEnter", text);
            tplEventSource.DebugFacilityMessage("OnStartEnterActivityState", ActivityInfo.LiveActivities(value));
        }
        if (value != null)
        {
            if (value.m_level >= 100)
            {
                activityId = Guid.Empty;
                relatedActivityId = Guid.Empty;
                if (flag)
                {
                    tplEventSource.DebugFacilityMessage("OnStartRET", "Fail");
                }
                return;
            }
            if ((options & EventActivityOptions.Recursive) == 0)
            {
                ActivityInfo activityInfo = FindActiveActivity(text, value);
                if (activityInfo != null)
                {
                    OnStop(providerName, activityName, task, ref activityId);
                    value = m_current.Value;
                }
            }
        }
        long uniqueId = ((value != null) ? Interlocked.Increment(ref value.m_lastChildID) : Interlocked.Increment(ref m_nextId));
        relatedActivityId = EventSource.CurrentThreadActivityId;
        ActivityInfo activityInfo2 = new ActivityInfo(text, uniqueId, value, relatedActivityId, options);
        m_current.Value = activityInfo2;
        activityId = activityInfo2.ActivityId;
        if (flag)
        {
            tplEventSource.DebugFacilityMessage("OnStartRetActivityState", ActivityInfo.LiveActivities(activityInfo2));
            tplEventSource.DebugFacilityMessage1("OnStartRet", activityId.ToString(), relatedActivityId.ToString());
        }
    }
References System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.ActivityId, System.Diagnostics.Tracing.EventSource.CurrentThreadActivityId, System.Threading.Tasks.TplEventSource.Debug, System.Threading.Tasks.TplEventSource.DebugFacilityMessage(), System.Threading.Tasks.TplEventSource.DebugFacilityMessage1(), System.Guid.Empty, System.Diagnostics.Tracing.ActivityTracker.Enable(), System.Diagnostics.Tracing.ActivityTracker.FindActiveActivity(), System.Threading.Interlocked.Increment(), System.L, System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.LiveActivities(), System.Threading.Tasks.TplEventSource.Log, System.Diagnostics.Tracing.ActivityTracker.m_checkedForEnable, System.Diagnostics.Tracing.ActivityTracker.m_current, System.Diagnostics.Tracing.ActivityTracker.m_nextId, System.Diagnostics.Tracing.ActivityTracker.NormalizeActivityName(), System.Diagnostics.Tracing.ActivityTracker.OnStop(), System.options, System.task, System.text, and System.value.
Referenced by System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(), and System.Diagnostics.Tracing.EventSource.WriteImpl().