Terraria: System.Diagnostics.Tracing.ActivityTracker.OnStop
OnStop()
void System.Diagnostics.Tracing.ActivityTracker.OnStop (string providerName, string activityName, int task, ref Guid activityId, bool useTplSource = true) inline
Definition at line 263 of file ActivityTracker.cs.
    {
        if (m_current == null)
        {
            return;
        }
        string text = NormalizeActivityName(providerName, activityName, task);
        TplEventSource tplEventSource = (useTplSource ? TplEventSource.Log : null);
        bool flag = tplEventSource?.Debug ?? false;
        if (flag)
        {
            tplEventSource.DebugFacilityMessage("OnStopEnter", text);
            tplEventSource.DebugFacilityMessage("OnStopEnterActivityState", ActivityInfo.LiveActivities(m_current.Value));
        }
        ActivityInfo activityInfo;
        ActivityInfo activityInfo2;
        do
        {
            ActivityInfo value = m_current.Value;
            activityInfo = null;
            activityInfo2 = FindActiveActivity(text, value);
            if (activityInfo2 == null)
            {
                activityId = Guid.Empty;
                if (flag)
                {
                    tplEventSource.DebugFacilityMessage("OnStopRET", "Fail");
                }
                return;
            }
            activityId = activityInfo2.ActivityId;
            ActivityInfo activityInfo3 = value;
            while (activityInfo3 != activityInfo2 && activityInfo3 != null)
            {
                if (activityInfo3.m_stopped != 0)
                {
                    activityInfo3 = activityInfo3.m_creator;
                    continue;
                }
                if (activityInfo3.CanBeOrphan())
                {
                    if (activityInfo == null)
                    {
                        activityInfo = activityInfo3;
                    }
                }
                else
                {
                    activityInfo3.m_stopped = 1;
                }
                activityInfo3 = activityInfo3.m_creator;
            }
        }
        while (Interlocked.CompareExchange(ref activityInfo2.m_stopped, 1, 0) != 0);
        if (activityInfo == null)
        {
            activityInfo = activityInfo2.m_creator;
        }
        m_current.Value = activityInfo;
        if (flag)
        {
            tplEventSource.DebugFacilityMessage("OnStopRetActivityState", ActivityInfo.LiveActivities(activityInfo));
            tplEventSource.DebugFacilityMessage("OnStopRet", activityId.ToString());
        }
    }
References System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.ActivityId, System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.CanBeOrphan(), System.Threading.Interlocked.CompareExchange(), System.Threading.Tasks.TplEventSource.Debug, System.Threading.Tasks.TplEventSource.DebugFacilityMessage(), System.Guid.Empty, System.Diagnostics.Tracing.ActivityTracker.FindActiveActivity(), System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.LiveActivities(), System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.m_creator, System.Diagnostics.Tracing.ActivityTracker.m_current, System.Diagnostics.Tracing.ActivityTracker.ActivityInfo.m_stopped, System.Diagnostics.Tracing.ActivityTracker.NormalizeActivityName(), System.task, System.text, and System.value.
Referenced by System.Diagnostics.Tracing.ActivityTracker.OnStart(), System.Diagnostics.Tracing.EventSource.WriteEventVarargs(), System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(), and System.Diagnostics.Tracing.EventSource.WriteImpl().