Terraria: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks
ProcessExclusiveTasks()
void System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks () inline private
Definition at line 478 of file ConcurrentExclusiveSchedulerPair.cs.
    {
        try
        {
            m_threadProcessingMode.Value = ProcessingMode.ProcessingExclusiveTask;
            for (int i = 0; i < m_maxItemsPerTask; i++)
            {
                if (!m_exclusiveTaskScheduler.m_tasks.TryDequeue(out var result))
                {
                    break;
                }
                if (!result.IsFaulted)
                {
                    m_exclusiveTaskScheduler.ExecuteTask(result);
                }
            }
        }
        finally
        {
            m_threadProcessingMode.Value = ProcessingMode.NotCurrentlyProcessing;
            lock (ValueLock)
            {
                m_processingCount = 0;
                ProcessAsyncIfNecessary(fairly: true);
            }
        }
    }
References System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.ExecuteTask(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_exclusiveTaskScheduler, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_maxItemsPerTask, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_processingCount, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.m_tasks, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary(), and System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ValueLock.
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.SchedulerWorkItem.Execute().