Terraria: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary
ProcessAsyncIfNecessary()
void System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary (bool fairly = false) inline private
Definition at line 404 of file ConcurrentExclusiveSchedulerPair.cs.
    {
        if (m_processingCount < 0)
        {
            return;
        }
        bool flag = !m_exclusiveTaskScheduler.m_tasks.IsEmpty;
        Task task = null;
        if (m_processingCount == 0 && flag)
        {
            m_processingCount = -1;
            if (!TryQueueThreadPoolWorkItem(fairly))
            {
                try
                {
                    task = new Task(delegate(object thisPair)
                    {
                        ((ConcurrentExclusiveSchedulerPair)thisPair).ProcessExclusiveTasks();
                    }, this, default(CancellationToken), GetCreationOptionsForTask(fairly));
                    task.Start(m_underlyingTaskScheduler);
                }
                catch (Exception exception)
                {
                    m_processingCount = 0;
                    FaultWithTask(task ?? Task.FromException(exception));
                }
            }
        }
        else
        {
            int count = m_concurrentTaskScheduler.m_tasks.Count;
            if (count > 0 && !flag && m_processingCount < m_maxConcurrencyLevel)
            {
                for (int i = 0; i < count; i++)
                {
                    if (m_processingCount >= m_maxConcurrencyLevel)
                    {
                        break;
                    }
                    m_processingCount++;
                    if (TryQueueThreadPoolWorkItem(fairly))
                    {
                        continue;
                    }
                    try
                    {
                        task = new Task(delegate(object thisPair)
{
                            ((ConcurrentExclusiveSchedulerPair)thisPair).ProcessConcurrentTasks();
                        }, this, default(CancellationToken), GetCreationOptionsForTask(fairly));
                        task.Start(m_underlyingTaskScheduler);
                    }
                    catch (Exception exception2)
                    {
                        m_processingCount--;
                        FaultWithTask(task ?? Task.FromException(exception2));
                    }
                }
            }
        }
        CleanupStateIfCompletingAndQuiesced();
    }
References System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveSchedulerPair(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CleanupStateIfCompletingAndQuiesced(), System.count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.exception, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.FaultWithTask(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.GetCreationOptionsForTask(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_concurrentTaskScheduler, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_exclusiveTaskScheduler, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_maxConcurrencyLevel, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_processingCount, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.m_tasks, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_underlyingTaskScheduler, System.Threading.Tasks.Task< TResult >.Start(), System.task, and System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.TryQueueThreadPoolWorkItem().
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessConcurrentTasks(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessExclusiveTasks(), and System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.QueueTask().