Terraria: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessConcurrentTasks
ProcessConcurrentTasks()
void System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessConcurrentTasks () inline private
Definition at line 506 of file ConcurrentExclusiveSchedulerPair.cs.
    {
        try
        {
            m_threadProcessingMode.Value = ProcessingMode.ProcessingConcurrentTasks;
            for (int i = 0; i < m_maxItemsPerTask; i++)
            {
                if (!m_concurrentTaskScheduler.m_tasks.TryDequeue(out var result))
                {
                    break;
                }
                if (!result.IsFaulted)
                {
                    m_concurrentTaskScheduler.ExecuteTask(result);
                }
                if (!m_exclusiveTaskScheduler.m_tasks.IsEmpty)
                {
                    break;
                }
            }
        }
        finally
        {
            m_threadProcessingMode.Value = ProcessingMode.NotCurrentlyProcessing;
            lock (ValueLock)
            {
                if (m_processingCount > 0)
                {
                    m_processingCount--;
                }
                ProcessAsyncIfNecessary(fairly: true);
            }
        }
    }
References System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.ExecuteTask(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_concurrentTaskScheduler, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_exclusiveTaskScheduler, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_maxItemsPerTask, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_processingCount, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveTaskScheduler.m_tasks, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary(), and System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ValueLock.
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.SchedulerWorkItem.Execute().