Terraria: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.FaultWithTask
FaultWithTask()
void System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.FaultWithTask (Task faultedTask) inline private
Definition at line 391 of file ConcurrentExclusiveSchedulerPair.cs.
    {
        AggregateException exception = faultedTask.Exception;
        CompletionState completionState = EnsureCompletionStateInitialized();
        CompletionState completionState2 = completionState;
        if (completionState2.m_exceptions == null)
        {
            completionState2.m_exceptions = new List<Exception>(exception.InnerExceptionCount);
        }
        completionState.m_exceptions.AddRange(exception.InternalInnerExceptions);
        RequestCompletion();
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.AddRange(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.EnsureCompletionStateInitialized(), System.exception, and System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.RequestCompletion().
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ProcessAsyncIfNecessary().