Terraria: PotionOfReturnGateHelper.SpawnReturnPortalDust
SpawnReturnPortalDust()
void PotionOfReturnGateHelper.SpawnReturnPortalDust () inline
     {
         if (_gateType == GateType.EntryPoint)
         {
             if (Main.rand.Next(3) == 0)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     Vector2 vector = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                     vector *= new Vector2(0.5f, 1f);
                     Dust dust = Dust.NewDustDirect(_position - vector * 30f, 0, 0, Utils.SelectRandom<int>(Main.rand, 86, 88));
                     dust.noGravity = true;
                     dust.noLightEmittence = true;
                     dust.position = _position - vector.SafeNormalize(Vector2.Zero) * Main.rand.Next(10, 21);
                     dust.velocity = vector.RotatedBy(1.5707963705062866) * 2f;
                     dust.scale = 0.5f + Main.rand.NextFloat();
                     dust.fadeIn = 0.5f;
                     dust.customData = this;
                     dust.position += dust.velocity * 10f;
                     dust.velocity *= -1f;
                 }
                 else
                 {
                     Vector2 vector2 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                     vector2 *= new Vector2(0.5f, 1f);
                     Dust dust2 = Dust.NewDustDirect(_position - vector2 * 30f, 0, 0, 240);
                     dust2.noGravity = true;
                     dust2.noLight = true;
                     dust2.position = _position - vector2.SafeNormalize(Vector2.Zero) * Main.rand.Next(5, 10);
                     dust2.velocity = vector2.RotatedBy(-1.5707963705062866) * 3f;
                     dust2.scale = 0.5f + Main.rand.NextFloat();
                     dust2.fadeIn = 0.5f;
                     dust2.customData = this;
                     dust2.position += dust2.velocity * 10f;
                     dust2.velocity *= -1f;
                 }
             }
         }
         else if (Main.rand.Next(3) == 0)
         {
             if (Main.rand.Next(2) == 0)
             {
                 Vector2 vector3 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                 vector3 *= new Vector2(0.5f, 1f);
                 Dust dust3 = Dust.NewDustDirect(_position - vector3 * 30f, 0, 0, Utils.SelectRandom<int>(Main.rand, 86, 88));
                 dust3.noGravity = true;
                 dust3.noLightEmittence = true;
                 dust3.position = _position;
                 dust3.velocity = vector3.RotatedBy(-0.7853981852531433) * 2f;
                 dust3.scale = 0.5f + Main.rand.NextFloat();
                 dust3.fadeIn = 0.5f;
                 dust3.customData = this;
                 dust3.position += vector3 * new Vector2(20f);
             }
             else
             {
                 Vector2 vector4 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                 vector4 *= new Vector2(0.5f, 1f);
                 Dust dust4 = Dust.NewDustDirect(_position - vector4 * 30f, 0, 0, Utils.SelectRandom<int>(Main.rand, 86, 88));
                 dust4.noGravity = true;
                 dust4.noLightEmittence = true;
                 dust4.position = _position;
                 dust4.velocity = vector4.RotatedBy(-0.7853981852531433) * 2f;
                 dust4.scale = 0.5f + Main.rand.NextFloat();
                 dust4.fadeIn = 0.5f;
                 dust4.customData = this;
                 dust4.position += vector4 * new Vector2(20f);
             }
         }
     }
References _gateType, _position, Dust.customData, Dust.fadeIn, Dust.NewDustDirect(), UnifiedRandom.Next(), Dust.noGravity, Dust.noLight, Dust.noLightEmittence, Dust.position, Main.rand, Dust.scale, and Dust.velocity.
Referenced by Update().