Terraria: System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString
BuildDeliveryStatusNotificationString()
string System.Net.Mail.MailMessage.BuildDeliveryStatusNotificationString () inline package
Definition at line 436 of file MailMessage.cs.
    {
        if (_deliveryStatusNotification != 0)
        {
            StringBuilder stringBuilder = new StringBuilder(" NOTIFY=");
            bool flag = false;
            if (_deliveryStatusNotification == DeliveryNotificationOptions.Never)
            {
                stringBuilder.Append("NEVER");
                return stringBuilder.ToString();
            }
            if ((_deliveryStatusNotification & DeliveryNotificationOptions.OnSuccess) > DeliveryNotificationOptions.None)
            {
                stringBuilder.Append("SUCCESS");
                flag = true;
            }
            if ((_deliveryStatusNotification & DeliveryNotificationOptions.OnFailure) > DeliveryNotificationOptions.None)
            {
                if (flag)
                {
                    stringBuilder.Append(',');
                }
                stringBuilder.Append("FAILURE");
                flag = true;
            }
            if ((_deliveryStatusNotification & DeliveryNotificationOptions.Delay) > DeliveryNotificationOptions.None)
            {
                if (flag)
                {
                    stringBuilder.Append(',');
                }
                stringBuilder.Append("DELAY");
            }
            return stringBuilder.ToString();
        }
        return string.Empty;
    }
References System.Net.Mail.MailMessage._deliveryStatusNotification, System.Text.StringBuilder.Append(), and System.Text.StringBuilder.ToString().
Referenced by System.Net.Mail.SmtpClient.ConnectCallback(), and System.Net.Mail.SmtpClient.Send().