Terraria: System.Net.Mail.MailMessage.Send
Send()
void System.Net.Mail.MailMessage.Send (BaseWriter writer, bool sendEnvelope, bool allowUnicode) inline package
Definition at line 419 of file MailMessage.cs.
    {
        SetContent(allowUnicode);
        _message.Send(writer, sendEnvelope, allowUnicode);
    }
References System.Net.Mail.MailMessage._message, System.Net.Mail.Message.Send(), System.Net.Mail.MailMessage.SetContent(), and System.writer.
Referenced by System.Net.Mail.SmtpClient.Send(), and System.Net.Mail.SmtpClient.SendAsync().