Terraria: System.Net.Mail.MailMessage.SetContent
SetContent()
void System.Net.Mail.MailMessage.SetContent (bool allowUnicode) inline private
Definition at line 319 of file MailMessage.cs.
    {
        if (_bodyView != null)
        {
            _bodyView.Dispose();
            _bodyView = null;
        }
        if (AlternateViews.Count == 0 && Attachments.Count == 0)
        {
            if (!string.IsNullOrEmpty(_body))
            {
                _bodyView = AlternateView.CreateAlternateViewFromString(_body, _bodyEncoding, _isBodyHtml ? "text/html" : null);
                _message.Content = _bodyView.MimePart;
            }
        }
        else if (AlternateViews.Count == 0 && Attachments.Count > 0)
        {
            MimeMultiPart mimeMultiPart = new MimeMultiPart(MimeMultiPartType.Mixed);
            if (!string.IsNullOrEmpty(_body))
            {
                _bodyView = AlternateView.CreateAlternateViewFromString(_body, _bodyEncoding, _isBodyHtml ? "text/html" : null);
            }
            else
            {
                _bodyView = AlternateView.CreateAlternateViewFromString(string.Empty);
            }
            mimeMultiPart.Parts.Add(_bodyView.MimePart);
            foreach (Attachment attachment in Attachments)
            {
                if (attachment != null)
                {
                    attachment.PrepareForSending(allowUnicode);
                    mimeMultiPart.Parts.Add(attachment.MimePart);
                }
            }
            _message.Content = mimeMultiPart;
        }
        else
        {
            MimeMultiPart mimeMultiPart2 = null;
            MimeMultiPart mimeMultiPart3 = new MimeMultiPart(MimeMultiPartType.Alternative);
            if (!string.IsNullOrEmpty(_body))
            {
                _bodyView = AlternateView.CreateAlternateViewFromString(_body, _bodyEncoding, null);
                mimeMultiPart3.Parts.Add(_bodyView.MimePart);
            }
            foreach (AlternateView alternateView in AlternateViews)
            {
                if (alternateView == null)
                {
                    continue;
                }
                alternateView.PrepareForSending(allowUnicode);
                if (alternateView.LinkedResources.Count > 0)
                {
                    MimeMultiPart mimeMultiPart4 = new MimeMultiPart(MimeMultiPartType.Related);
                    mimeMultiPart4.ContentType.Parameters["type"] = alternateView.ContentType.MediaType;
                    mimeMultiPart4.ContentLocation = alternateView.MimePart.ContentLocation;
                    mimeMultiPart4.Parts.Add(alternateView.MimePart);
                    foreach (LinkedResource linkedResource in alternateView.LinkedResources)
                    {
                        linkedResource.PrepareForSending(allowUnicode);
                        mimeMultiPart4.Parts.Add(linkedResource.MimePart);
                    }
                    mimeMultiPart3.Parts.Add(mimeMultiPart4);
                }
                else
                {
                    mimeMultiPart3.Parts.Add(alternateView.MimePart);
                }
            }
            if (Attachments.Count > 0)
            {
                mimeMultiPart2 = new MimeMultiPart(MimeMultiPartType.Mixed);
                mimeMultiPart2.Parts.Add(mimeMultiPart3);
                foreach (Attachment attachment2 in Attachments)
                {
                    if (attachment2 != null)
                    {
                        attachment2.PrepareForSending(allowUnicode);
                        mimeMultiPart2.Parts.Add(attachment2.MimePart);
                    }
                }
                _message.Content = mimeMultiPart2;
            }
            else if (mimeMultiPart3.Parts.Count == 1 && string.IsNullOrEmpty(_body))
            {
                _message.Content = mimeMultiPart3.Parts[0];
            }
            else
            {
                _message.Content = mimeMultiPart3;
            }
        }
        if (_bodyView != null && _bodyTransferEncoding != TransferEncoding.Unknown)
        {
            _bodyView.TransferEncoding = _bodyTransferEncoding;
        }
    }
References System.Net.Mail.MailMessage._body, System.Net.Mail.MailMessage._bodyEncoding, System.Net.Mail.MailMessage._bodyTransferEncoding, System.Net.Mail.MailMessage._bodyView, System.Net.Mail.MailMessage._isBodyHtml, System.Net.Mail.MailMessage.AlternateViews, System.Net.Mail.MailMessage.Attachments, System.Net.Mime.MimeBasePart.ContentLocation, System.Net.Mail.AttachmentBase.ContentType, System.Net.Mime.MimeBasePart.ContentType, System.Collections.ObjectModel.Collection< T >.Count, System.Net.Mail.AlternateView.CreateAlternateViewFromString(), System.Net.Mail.AlternateView.Dispose(), System.Net.Mail.AlternateView.LinkedResources, System.Net.Mime.ContentType.MediaType, System.Net.Mail.AttachmentBase.MimePart, System.Net.Mime.ContentType.Parameters, System.Net.Mime.MimeMultiPart.Parts, System.Net.Mail.Attachment.PrepareForSending(), and System.Net.Mail.AttachmentBase.PrepareForSending().
Referenced by System.Net.Mail.MailMessage.BeginSend(), and System.Net.Mail.MailMessage.Send().