Terraria: System.Net.Mail.MailMessage.Dispose
Dispose() [2/2]
virtual void System.Net.Mail.MailMessage.Dispose (bool disposing) inline protected virtual
Definition at line 299 of file MailMessage.cs.
    {
        if (disposing && !_disposed)
        {
            _disposed = true;
            if (_views != null)
            {
                _views.Dispose();
            }
            if (_attachments != null)
            {
                _attachments.Dispose();
            }
            if (_bodyView != null)
            {
                _bodyView.Dispose();
            }
        }
    }
References System.Net.Mail.MailMessage._attachments, System.Net.Mail.MailMessage._bodyView, System.Net.Mail.MailMessage._disposed, System.Net.Mail.MailMessage._views, System.Net.Mail.AlternateViewCollection.Dispose(), System.Net.Mail.AttachmentCollection.Dispose(), and System.Net.Mail.AlternateView.Dispose().