Terraria: Wiring.MassWireOperationInner
MassWireOperationInner()
static void Wiring.MassWireOperationInner (Player user, Point ps, Point pe, Vector2 dropPoint, bool dir, ref int wireCount, ref int actuatorCount) inline static private
     {
         Math.Abs(ps.X - pe.X);
         Math.Abs(ps.Y - pe.Y);
         int num = Math.Sign(pe.X - ps.X);
         int num2 = Math.Sign(pe.Y - ps.Y);
         WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
         Point pt = default(Point);
         bool flag = false;
         Item.StartCachingType(530);
         Item.StartCachingType(849);
         bool flag2 = dir;
         int num3;
         int num4;
         int num5;
         if (flag2)
         {
             pt.X = ps.X;
             num3 = ps.Y;
             num4 = pe.Y;
             num5 = num2;
         }
         else
         {
             pt.Y = ps.Y;
             num3 = ps.X;
             num4 = pe.X;
             num5 = num;
         }
         for (int i = num3; i != num4; i += num5)
         {
             if (flag)
             {
                 break;
             }
             if (flag2)
             {
                 pt.Y = i;
             }
             else
             {
                 pt.X = i;
             }
             bool? flag3 = MassWireOperationStep(user, pt, toolMode, ref wireCount, ref actuatorCount);
             if (flag3.HasValue && !flag3.Value)
             {
                 flag = true;
                 break;
             }
         }
         if (flag2)
         {
             pt.Y = pe.Y;
             num3 = ps.X;
             num4 = pe.X;
             num5 = num;
         }
         else
         {
             pt.X = pe.X;
             num3 = ps.Y;
             num4 = pe.Y;
             num5 = num2;
         }
         for (int j = num3; j != num4; j += num5)
         {
             if (flag)
             {
                 break;
             }
             if (!flag2)
             {
                 pt.Y = j;
             }
             else
             {
                 pt.X = j;
             }
             bool? flag4 = MassWireOperationStep(user, pt, toolMode, ref wireCount, ref actuatorCount);
             if (flag4.HasValue && !flag4.Value)
             {
                 flag = true;
                 break;
             }
         }
         if (!flag)
         {
             MassWireOperationStep(user, pe, toolMode, ref wireCount, ref actuatorCount);
         }
         EntitySource_ByItemSourceId reason = new EntitySource_ByItemSourceId(user, 5);
         Item.DropCache(reason, dropPoint, Vector2.Zero, 530);
         Item.DropCache(reason, dropPoint, Vector2.Zero, 849);
     }
References Item.DropCache(), Item.StartCachingType(), and WiresUI.Settings.ToolMode.
Referenced by MassWireOperation().