Terraria: Wiring.GeyserTrap
GeyserTrap()
static void Wiring.GeyserTrap (int i, int j) inline static private
     {
         Tile tile = Main.tile[i, j];
         if (tile.type != 443)
         {
             return;
         }
         int num = tile.frameX / 36;
         int num2 = i - (tile.frameX - num * 36) / 18;
         if (CheckMech(num2, j, 200))
         {
             Vector2 zero = Vector2.Zero;
             Vector2 zero2 = Vector2.Zero;
             int num3 = 654;
             int damage = 20;
             if (num < 2)
             {
                 zero = new Vector2(num2 + 1, j) * 16f;
                 zero2 = new Vector2(0f, -8f);
             }
             else
             {
                 zero = new Vector2(num2 + 1, j + 1) * 16f;
                 zero2 = new Vector2(0f, 8f);
             }
             if (num3 != 0)
             {
                 Projectile.NewProjectile(GetProjectileSource(num2, j), (int)zero.X, (int)zero.Y, zero2.X, zero2.Y, num3, damage, 2f, Main.myPlayer);
             }
         }
     }
References Tile.frameX, Main.myPlayer, Projectile.NewProjectile(), Main.tile, and Tile.type.
Referenced by HitSwitch(), and HitWireSingle().