Terraria: Wiring.Teleport
Teleport()
static void Wiring.Teleport () inline static private
     {
         if (_teleport[0].X < _teleport[1].X + 3f && _teleport[0].X > _teleport[1].X - 3f && _teleport[0].Y > _teleport[1].Y - 3f && _teleport[0].Y < _teleport[1].Y)
         {
             return;
         }
         Rectangle[] array = new Rectangle[2];
         array[0].X = (int)(_teleport[0].X * 16f);
         array[0].Width = 48;
         array[0].Height = 48;
         array[0].Y = (int)(_teleport[0].Y * 16f - (float)array[0].Height);
         array[1].X = (int)(_teleport[1].X * 16f);
         array[1].Width = 48;
         array[1].Height = 48;
         array[1].Y = (int)(_teleport[1].Y * 16f - (float)array[1].Height);
         for (int i = 0; i < 2; i++)
         {
             Vector2 vector = new Vector2(array[1].X - array[0].X, array[1].Y - array[0].Y);
             if (i == 1)
             {
                 vector = new Vector2(array[0].X - array[1].X, array[0].Y - array[1].Y);
             }
             if (!blockPlayerTeleportationForOneIteration)
             {
                 for (int j = 0; j < 255; j++)
                 {
                     if (Main.player[j].active && !Main.player[j].dead && !Main.player[j].teleporting && TeleporterHitboxIntersects(array[i], Main.player[j].Hitbox))
                     {
                         Vector2 vector2 = Main.player[j].position + vector;
                         Main.player[j].teleporting = true;
                         if (Main.netMode == 2)
{
                             RemoteClient.CheckSection(j, vector2);
                         }
                         Main.player[j].Teleport(vector2);
                         if (Main.netMode == 2)
{
                             NetMessage.SendData(65, -1, -1, null, 0, j, vector2.X, vector2.Y);
                         }
                     }
                 }
             }
             for (int k = 0; k < 200; k++)
             {
                 if (Main.npc[k].active && !Main.npc[k].teleporting && Main.npc[k].lifeMax > 5 && !Main.npc[k].boss && !Main.npc[k].noTileCollide)
                 {
                     int type = Main.npc[k].type;
                     if (!NPCID.Sets.TeleportationImmune[type] && TeleporterHitboxIntersects(array[i], Main.npc[k].Hitbox))
                     {
                         Main.npc[k].teleporting = true;
                         Main.npc[k].Teleport(Main.npc[k].position + vector);
                     }
                 }
             }
         }
         for (int l = 0; l < 255; l++)
         {
             Main.player[l].teleporting = false;
         }
         for (int m = 0; m < 200; m++)
         {
             Main.npc[m].teleporting = false;
         }
     }
References Entity.active, NPC.boss, RemoteClient.CheckSection(), Player.dead, Entity.Hitbox, NPC.lifeMax, Main.netMode, NPC.noTileCollide, Main.npc, Main.player, Entity.position, NetMessage.SendData(), NPC.Teleport(), Player.Teleport(), NPCID.Sets.TeleportationImmune, NPC.teleporting, Player.teleporting, NPC.type, X, and Y.
Referenced by TripWire().