Terraria: Wiring.Toggle2x2Light
Toggle2x2Light()
static void Wiring.Toggle2x2Light (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
     {
         int num;
         for (num = tileCache.frameY / 18; num >= 2; num -= 2)
         {
         }
         num = j - num;
         int num2 = tileCache.frameX / 18;
         if (num2 > 1)
         {
             num2 -= 2;
         }
         num2 = i - num2;
         short num3 = 36;
         if (Main.tile[num2, num].frameX > 0)
         {
             num3 = -36;
         }
         bool flag = Main.tile[num2, num].frameX > 0;
         if (!forcedStateWhereTrueIsOn.HasValue || !forcedStateWhereTrueIsOn.Value != flag)
         {
             Main.tile[num2, num].frameX += num3;
             Main.tile[num2, num + 1].frameX += num3;
             Main.tile[num2 + 1, num].frameX += num3;
             Main.tile[num2 + 1, num + 1].frameX += num3;
             if (doSkipWires)
             {
                 SkipWire(num2, num);
                 SkipWire(num2 + 1, num);
                 SkipWire(num2, num + 1);
                 SkipWire(num2 + 1, num + 1);
             }
             NetMessage.SendTileSquare(-1, num2, num, 2, 2);
         }
     }
References Tile.frameX, Tile.frameY, NetMessage.SendTileSquare(), and Main.tile.
Referenced by HitWireSingle(), and WorldGen.TryToggleLight().