Terraria: Wiring.ToggleChandelier
ToggleChandelier()
static void Wiring.ToggleChandelier (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn, bool doSkipWires) inline static
     {
         int num;
         for (num = tileCache.frameY / 18; num >= 3; num -= 3)
         {
         }
         int num2 = j - num;
         int num3 = tileCache.frameX % 108 / 18;
         if (num3 > 2)
         {
             num3 -= 3;
         }
         num3 = i - num3;
         short num4 = 54;
         if (Main.tile[num3, num2].frameX % 108 > 0)
         {
             num4 = -54;
         }
         bool flag = Main.tile[num3, num2].frameX % 108 > 0;
         if (forcedStateWhereTrueIsOn.HasValue && !forcedStateWhereTrueIsOn.Value == flag)
         {
             return;
         }
         for (int k = num3; k < num3 + 3; k++)
         {
             for (int l = num2; l < num2 + 3; l++)
             {
                 Main.tile[k, l].frameX += num4;
                 if (doSkipWires)
                 {
                     SkipWire(k, l);
                 }
             }
         }
         NetMessage.SendTileSquare(-1, num3 + 1, num2 + 1, 3);
     }
References Tile.frameX, Tile.frameY, NetMessage.SendTileSquare(), and Main.tile.
Referenced by HitWireSingle(), and WorldGen.TryToggleLight().