Terraria: Wiring.PokeLogicGate
PokeLogicGate()
static void Wiring.PokeLogicGate (int lampX, int lampY) inline static
     {
         if (Main.netMode != 1)
         {
             _LampsToCheck.Enqueue(new Point16(lampX, lampY));
             LogicGatePass();
         }
     }
References _LampsToCheck, LogicGatePass(), and Main.netMode.
Referenced by MessageBuffer.GetData(), WorldGen.KillTile(), and Player.PlaceThing_Tiles_PlaceIt_TriggerLogicLamp().