Terraria: Wiring.ReActive
ReActive()
static void Wiring.ReActive (int i, int j) inline static private
     {
         Main.tile[i, j].inActive(inActive: false);
         WorldGen.SquareTileFrame(i, j, resetFrame: false);
         if (Main.netMode != 1)
         {
             NetMessage.SendTileSquare(-1, i, j);
         }
     }
References Tile.inActive(), Main.netMode, NetMessage.SendTileSquare(), WorldGen.SquareTileFrame(), and Main.tile.
Referenced by Actuate(), and ActuateForced().