Terraria: Wiring.LogicGatePass
LogicGatePass()
static void Wiring.LogicGatePass () inline static private
     {
         if (_GatesCurrent.Count != 0)
         {
             return;
         }
         _GatesDone.Clear();
         while (_LampsToCheck.Count > 0)
         {
             while (_LampsToCheck.Count > 0)
             {
                 Point16 point = _LampsToCheck.Dequeue();
                 CheckLogicGate(point.X, point.Y);
             }
             while (_GatesNext.Count > 0)
             {
                 Utils.Swap(ref _GatesCurrent, ref _GatesNext);
                 while (_GatesCurrent.Count > 0)
                 {
                     Point16 key = _GatesCurrent.Peek();
                     if (_GatesDone.TryGetValue(key, out var value) && value)
                     {
                         _GatesCurrent.Dequeue();
                         continue;
                     }
                     _GatesDone.Add(key, value: true);
                     TripWire(key.X, key.Y, 1, 1);
                     _GatesCurrent.Dequeue();
                 }
             }
         }
         _GatesDone.Clear();
         if (blockPlayerTeleportationForOneIteration)
         {
             blockPlayerTeleportationForOneIteration = false;
         }
     }
References _GatesCurrent, _GatesDone, _GatesNext, _LampsToCheck, blockPlayerTeleportationForOneIteration, CheckLogicGate(), TripWire(), Point16.X, and Point16.Y.
Referenced by PokeLogicGate(), and TripWire().