Terraria: Wiring.DeActive
DeActive()
static void Wiring.DeActive (int i, int j) inline static private
     {
         if (!Main.tile[i, j].active() || (Main.tile[i, j].type == 226 && (double)j > Main.worldSurface && !NPC.downedPlantBoss))
         {
             return;
         }
         bool flag = Main.tileSolid[Main.tile[i, j].type] && !TileID.Sets.NotReallySolid[Main.tile[i, j].type];
         ushort type = Main.tile[i, j].type;
         if (type == 314 || (uint)(type - 386) <= 3u || type == 476)
         {
             flag = false;
         }
         if (flag && (!Main.tile[i, j - 1].active() || (!TileID.Sets.BasicChest[Main.tile[i, j - 1].type] && Main.tile[i, j - 1].type != 26 && Main.tile[i, j - 1].type != 77 && Main.tile[i, j - 1].type != 88 && Main.tile[i, j - 1].type != 470 && Main.tile[i, j - 1].type != 475 && Main.tile[i, j - 1].type != 237 && Main.tile[i, j - 1].type != 597 && WorldGen.CanKillTile(i, j))))
         {
             Main.tile[i, j].inActive(inActive: true);
             WorldGen.SquareTileFrame(i, j, resetFrame: false);
             if (Main.netMode != 1)
             {
                 NetMessage.SendTileSquare(-1, i, j);
             }
         }
     }
References Tile.active(), TileID.Sets.BasicChest, WorldGen.CanKillTile(), NPC.downedPlantBoss, Tile.inActive(), Main.netMode, TileID.Sets.NotReallySolid, NetMessage.SendTileSquare(), WorldGen.SquareTileFrame(), Main.tile, Main.tileSolid, Tile.type, and Main.worldSurface.
Referenced by Actuate(), and ActuateForced().