Terraria: BallCollision.Step
Step()
static BallStepResult BallCollision.Step (PhysicsProperties physicsProperties, Entity entity, ref float entityAngularVelocity, IBallContactListener listener) inline static
     {
         Vector2 position = entity.position;
         Vector2 velocity = entity.velocity;
         Vector2 size = entity.Size;
         float num = entityAngularVelocity;
         float num2 = size.X * 0.5f;
         num *= physicsProperties.Drag;
         velocity *= physicsProperties.Drag;
         float num3 = velocity.Length();
         if (num3 > 1000f)
         {
             velocity = 1000f * Vector2.Normalize(velocity);
             num3 = 1000f;
         }
         int num4 = Math.Max(1, (int)Math.Ceiling(num3 / 2f));
         float num5 = 1f / (float)num4;
         velocity *= num5;
         num *= num5;
         float num6 = physicsProperties.Gravity / (float)(num4 * num4);
         bool flag = false;
         for (int i = 0; i < num4; i++)
         {
             velocity.Y += num6;
             if (CheckForPassThrough(position + size * 0.5f, out var type, out var contactTile))
             {
                 if (type == BallPassThroughType.Tile && Main.tileSolid[contactTile.type] && !Main.tileSolidTop[contactTile.type])
                 {
                     velocity *= 0f;
                     num *= 0f;
                     flag = true;
                 }
                 else
                 {
                     BallPassThroughEvent passThrough = new BallPassThroughEvent(num5, contactTile, entity, type);
                     listener.OnPassThrough(physicsProperties, ref position, ref velocity, ref num, ref passThrough);
                 }
             }
             position += velocity;
             if (!IsBallInWorld(position, size))
             {
                 return BallStepResult.OutOfBounds();
             }
             if (GetClosestEdgeToCircle(position, size, velocity, out var collisionPoint, out contactTile))
             {
                 Vector2 vector = Vector2.Normalize(position + size * 0.5f - collisionPoint);
                 position = collisionPoint + vector * (num2 + 0.0001f) - size * 0.5f;
                 BallCollisionEvent collision = new BallCollisionEvent(num5, vector, collisionPoint, contactTile, entity);
                 flag = true;
                 velocity = Vector2.Reflect(velocity, collision.Normal);
                 listener.OnCollision(physicsProperties, ref position, ref velocity, ref collision);
                 num = (collision.Normal.X * velocity.Y - collision.Normal.Y * velocity.X) / num2;
             }
         }
         velocity /= num5;
         num /= num5;
         BallStepResult result = BallStepResult.Moving();
         if (flag && velocity.X > -0.01f && velocity.X < 0.01f && velocity.Y <= 0f && velocity.Y > 0f - physicsProperties.Gravity)
         {
             result = BallStepResult.Resting();
         }
         entity.position = position;
         entity.velocity = velocity;
         entityAngularVelocity = num;
         return result;
     }
References CheckForPassThrough(), PhysicsProperties.Drag, GetClosestEdgeToCircle(), PhysicsProperties.Gravity, IsBallInWorld(), BallStepResult.Moving(), IBallContactListener.OnCollision(), IBallContactListener.OnPassThrough(), BallStepResult.OutOfBounds(), Entity.position, BallStepResult.Resting(), Entity.Size, Main.tileSolid, Main.tileSolidTop, and Entity.velocity.
Referenced by GolfHelper.StepGolfBall().