Terraria: BallCollision.GetClosestEdgeToCircle
GetClosestEdgeToCircle()
static bool BallCollision.GetClosestEdgeToCircle (Vector2 position, Vector2 size, Vector2 velocity, out Vector2 collisionPoint, out Tile collisionTile) inline static private
     {
         Rectangle tileBounds = GetTileBounds(position, size);
         Vector2 vector = position + size * 0.5f;
         TileEdges tileEdges = TileEdges.None;
         tileEdges = ((!(velocity.Y < 0f)) ? (tileEdges | TileEdges.Top) : (tileEdges | TileEdges.Bottom));
         tileEdges = ((!(velocity.X < 0f)) ? (tileEdges | TileEdges.Left) : (tileEdges | TileEdges.Right));
         tileEdges = ((!(velocity.Y > velocity.X)) ? (tileEdges | TileEdges.TopRightSlope) : (tileEdges | TileEdges.BottomLeftSlope));
         tileEdges = ((!(velocity.Y > 0f - velocity.X)) ? (tileEdges | TileEdges.TopLeftSlope) : (tileEdges | TileEdges.BottomRightSlope));
         collisionPoint = Vector2.Zero;
         collisionTile = null;
         float num = float.MaxValue;
         Vector2 closestPointOut = default(Vector2);
         float distanceSquaredOut = 0f;
         for (int i = tileBounds.Left; i < tileBounds.Right; i++)
         {
             for (int j = tileBounds.Top; j < tileBounds.Bottom; j++)
             {
                 if (GetCollisionPointForTile(tileEdges, i, j, vector, ref closestPointOut, ref distanceSquaredOut) && !(distanceSquaredOut >= num) && !(Vector2.Dot(velocity, vector - closestPointOut) > 0f))
                 {
                     num = distanceSquaredOut;
                     collisionPoint = closestPointOut;
                     collisionTile = Main.tile[i, j];
                 }
             }
         }
         float num2 = size.X / 2f;
         return num < num2 * num2;
     }
References GetCollisionPointForTile(), GetTileBounds(), and Main.tile.
Referenced by Step().