Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.GetNamespaceData
GetNamespaceData()
NamespaceData System.Reflection.Metadata.Ecma335.NamespaceCache.GetNamespaceData (NamespaceDefinitionHandle handle) inline package
Definition at line 89 of file NamespaceCache.cs.
    {
        EnsureNamespaceTableIsPopulated();
        if (!_namespaceTable.TryGetValue(handle, out var value))
        {
            Throw.InvalidHandle();
        }
        return value;
    }
References System.Reflection.Metadata.Ecma335.NamespaceCache._namespaceTable, System.Reflection.Metadata.Ecma335.NamespaceCache.EnsureNamespaceTableIsPopulated(), System.handle, System.Reflection.Throw.InvalidHandle(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.GetFullName(), and System.Reflection.Metadata.MetadataReader.GetNamespaceDefinition().