Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateNamespaceTable
PopulateNamespaceTable()
void System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateNamespaceTable () inline private
Definition at line 116 of file NamespaceCache.cs.
    {
        lock (_namespaceTableAndListLock)
        {
            if (_namespaceTable != null)
            {
                return;
            }
            Dictionary<NamespaceDefinitionHandle, NamespaceDataBuilder> dictionary = new Dictionary<NamespaceDefinitionHandle, NamespaceDataBuilder>();
            NamespaceDefinitionHandle namespaceDefinitionHandle = NamespaceDefinitionHandle.FromFullNameOffset(0);
            dictionary.Add(namespaceDefinitionHandle, new NamespaceDataBuilder(namespaceDefinitionHandle, namespaceDefinitionHandle.GetFullName(), string.Empty));
            PopulateTableWithTypeDefinitions(dictionary);
            PopulateTableWithExportedTypes(dictionary);
            MergeDuplicateNamespaces(dictionary, out var stringTable);
            ResolveParentChildRelationships(stringTable, out var virtualNamespaces);
            Dictionary<NamespaceDefinitionHandle, NamespaceData> dictionary2 = new Dictionary<NamespaceDefinitionHandle, NamespaceData>();
            foreach (KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder> item in dictionary)
            {
                dictionary2.Add(item.Key, item.Value.Freeze());
            }
            if (virtualNamespaces != null)
            {
                foreach (NamespaceDataBuilder item2 in virtualNamespaces)
                {
                    dictionary2.Add(item2.Handle, item2.Freeze());
                }
            }
            _rootNamespace = dictionary2[namespaceDefinitionHandle];
            _namespaceTable = dictionary2;
        }
    }
References System.Reflection.Metadata.Ecma335.NamespaceCache._namespaceTable, System.Reflection.Metadata.Ecma335.NamespaceCache._namespaceTableAndListLock, System.Reflection.Metadata.Ecma335.NamespaceCache._rootNamespace, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, System.Reflection.Metadata.NamespaceDefinitionHandle.FromFullNameOffset(), System.item, System.Reflection.Metadata.Ecma335.NamespaceCache.MergeDuplicateNamespaces(), System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithExportedTypes(), System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithTypeDefinitions(), and System.Reflection.Metadata.Ecma335.NamespaceCache.ResolveParentChildRelationships().
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.EnsureNamespaceTableIsPopulated().