Terraria: Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles
TryRewriteHistoryToAvoidTiles()
TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles () inline private
    {
        int num = _length - 1;
        int num2 = Math.Min(_length, _rewriteHistory.Length);
        for (int i = 0; i < num2; i++)
        {
            _rewriteHistory[i] = _history[num - i];
        }
        while (num >= _length - num2)
        {
            if (_history[num].Slope == TrackSlope.Down)
            {
                TrackPlacementState historySegmentPlacementState = GetHistorySegmentPlacementState(num, _length - num);
                if (historySegmentPlacementState == TrackPlacementState.Available)
                {
                    return historySegmentPlacementState;
                }
                RewriteSlopeDirection(num, TrackSlope.Straight);
            }
            num--;
        }
        if (GetHistorySegmentPlacementState(num + 1, _length - (num + 1)) == TrackPlacementState.Available)
        {
            return TrackPlacementState.Available;
        }
        for (num = _length - 1; num >= _length - num2 + 1; num--)
        {
            if (_history[num].Slope == TrackSlope.Straight)
            {
                TrackPlacementState historySegmentPlacementState2 = GetHistorySegmentPlacementState(_length - num2, num2);
                if (historySegmentPlacementState2 == TrackPlacementState.Available)
                {
                    return historySegmentPlacementState2;
                }
                RewriteSlopeDirection(num, TrackSlope.Up);
            }
        }
        for (int j = 0; j < num2; j++)
        {
            _history[_length - 1 - j] = _rewriteHistory[j];
        }
        RewriteSlopeDirection(_length - 1, TrackSlope.Straight);
        return GetHistorySegmentPlacementState(num + 1, _length - (num + 1));
    }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.GameContent.Generation.TrackGenerator._rewriteHistory, Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState(), and Terraria.GameContent.Generation.TrackGenerator.RewriteSlopeDirection().
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath().