Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.MergeDuplicateNamespaces
MergeDuplicateNamespaces()
void System.Reflection.Metadata.Ecma335.NamespaceCache.MergeDuplicateNamespaces (Dictionary< NamespaceDefinitionHandle, NamespaceDataBuilder > table, out Dictionary< string, NamespaceDataBuilder > stringTable) inline private
Definition at line 148 of file NamespaceCache.cs.
    {
        Dictionary<string, NamespaceDataBuilder> dictionary = new Dictionary<string, NamespaceDataBuilder>();
        List<KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder>> list = null;
        foreach (KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder> item in table)
        {
            NamespaceDataBuilder value = item.Value;
            if (dictionary.TryGetValue(value.FullName, out var value2))
            {
                value.MergeInto(value2);
                if (list == null)
                {
                    list = new List<KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder>>();
                }
                list.Add(new KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder>(item.Key, value2));
            }
            else
            {
                dictionary.Add(value.FullName, value);
            }
        }
        if (list != null)
        {
            foreach (KeyValuePair<NamespaceDefinitionHandle, NamespaceDataBuilder> item2 in list)
            {
                table[item2.Key] = item2.Value;
            }
        }
        stringTable = dictionary;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, System.item, System.list, System.Reflection.Metadata.Ecma335.NamespaceCache.NamespaceDataBuilder.MergeInto(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateNamespaceTable().