Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.GetSimpleName
GetSimpleName()
StringHandle System.Reflection.Metadata.Ecma335.NamespaceCache.GetSimpleName (NamespaceDefinitionHandle fullNamespaceHandle, int segmentIndex = int::MaxValue) inline private
Definition at line 99 of file NamespaceCache.cs.
    {
        StringHandle fullName = fullNamespaceHandle.GetFullName();
        int num = fullNamespaceHandle.GetHeapOffset() - 1;
        for (int i = 0; i < segmentIndex; i++)
        {
            int num2 = _metadataReader.StringHeap.IndexOfRaw(num + 1, '.');
            if (num2 == -1)
            {
                break;
            }
            num = num2;
        }
        int heapOffset = num + 1;
        return StringHandle.FromOffset(heapOffset).WithDotTermination();
    }
References System.Reflection.Metadata.Ecma335.NamespaceCache._metadataReader, System.Reflection.Metadata.StringHandle.FromOffset(), and System.Reflection.Metadata.MetadataReader.StringHeap.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithExportedTypes(), System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithTypeDefinitions(), and System.Reflection.Metadata.Ecma335.NamespaceCache.SynthesizeNamespaceData().