Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithExportedTypes
PopulateTableWithExportedTypes()
void System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithExportedTypes (Dictionary< NamespaceDefinitionHandle, NamespaceDataBuilder > table) inline private
Definition at line 279 of file NamespaceCache.cs.
    {
        foreach (ExportedTypeHandle exportedType2 in _metadataReader.ExportedTypes)
        {
            ExportedType exportedType = _metadataReader.GetExportedType(exportedType2);
            if (exportedType.Implementation.Kind != HandleKind.ExportedType)
            {
                NamespaceDefinitionHandle namespaceDefinition = exportedType.NamespaceDefinition;
                if (table.TryGetValue(namespaceDefinition, out var value))
                {
                    value.ExportedTypes.Add(exportedType2);
                    continue;
                }
                StringHandle simpleName = GetSimpleName(namespaceDefinition);
                string @string = _metadataReader.GetString(namespaceDefinition);
                NamespaceDataBuilder namespaceDataBuilder = new NamespaceDataBuilder(namespaceDefinition, simpleName, @string);
                namespaceDataBuilder.ExportedTypes.Add(exportedType2);
                table.Add(namespaceDefinition, namespaceDataBuilder);
            }
        }
    }
References System.Reflection.Metadata.Ecma335.NamespaceCache._metadataReader, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Metadata.MetadataReader.ExportedTypes, System.Reflection.Metadata.MetadataReader.GetExportedType(), System.Reflection.Metadata.Ecma335.NamespaceCache.GetSimpleName(), System.Reflection.Metadata.MetadataReader.GetString(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateNamespaceTable().