Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.LinkChildToParentNamespace
LinkChildToParentNamespace()
void System.Reflection.Metadata.Ecma335.NamespaceCache.LinkChildToParentNamespace (Dictionary< string, NamespaceDataBuilder > existingNamespaces, NamespaceDataBuilder realChild, ref List< NamespaceDataBuilder > virtualNamespaces) inline private
Definition at line 200 of file NamespaceCache.cs.
    {
        string fullName = realChild.FullName;
        NamespaceDataBuilder child = realChild;
        NamespaceDataBuilder value;
        while (true)
        {
            int num = fullName.LastIndexOf('.');
            string text;
            if (num == -1)
            {
                if (fullName.Length == 0)
                {
                    return;
                }
                text = string.Empty;
            }
            else
            {
                text = fullName.Substring(0, num);
            }
            if (existingNamespaces.TryGetValue(text, out value))
            {
                break;
            }
            if (virtualNamespaces != null)
            {
                foreach (NamespaceDataBuilder virtualNamespace in virtualNamespaces)
                {
                    if (virtualNamespace.FullName == text)
                    {
                        LinkChildDataToParentData(child, virtualNamespace);
                        return;
                    }
                }
            }
            else
            {
                virtualNamespaces = new List<NamespaceDataBuilder>();
            }
            NamespaceDataBuilder namespaceDataBuilder = SynthesizeNamespaceData(text, realChild.Handle);
            LinkChildDataToParentData(child, namespaceDataBuilder);
            virtualNamespaces.Add(namespaceDataBuilder);
            fullName = namespaceDataBuilder.FullName;
            child = namespaceDataBuilder;
        }
        LinkChildDataToParentData(child, value);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Metadata.Ecma335.NamespaceCache.LinkChildDataToParentData(), System.Reflection.Metadata.Ecma335.NamespaceCache.SynthesizeNamespaceData(), System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.ResolveParentChildRelationships().