Terraria: Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState
GetHistorySegmentPlacementState()
TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState (int startIndex, int length) inline private
Definition at line 312 of file TrackGenerator.cs.
    {
        TrackPlacementState result = TrackPlacementState.Available;
        for (int i = startIndex; i < startIndex + length; i++)
        {
            TrackPlacementState trackPlacementState = CalculateStateForLocation(_history[i].X, _history[i].Y);
            switch (trackPlacementState)
            {
            case TrackPlacementState.Invalid:
                return trackPlacementState;
            case TrackPlacementState.Obstructed:
                if (_history[i].Mode != TrackMode.Tunnel)
                {
                    result = trackPlacementState;
                }
                break;
            }
        }
        return result;
    }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation(), System.length, System.startIndex, System.X, and System.Y.
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath(), and Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles().