Terraria: System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithTypeDefinitions
PopulateTableWithTypeDefinitions()
void System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateTableWithTypeDefinitions (Dictionary< NamespaceDefinitionHandle, NamespaceDataBuilder > table) inline private
Definition at line 258 of file NamespaceCache.cs.
    {
        foreach (TypeDefinitionHandle typeDefinition in _metadataReader.TypeDefinitions)
        {
            if (!_metadataReader.GetTypeDefinition(typeDefinition).Attributes.IsNested())
            {
                NamespaceDefinitionHandle namespaceDefinition = _metadataReader.TypeDefTable.GetNamespaceDefinition(typeDefinition);
                if (table.TryGetValue(namespaceDefinition, out var value))
                {
                    value.TypeDefinitions.Add(typeDefinition);
                    continue;
                }
                StringHandle simpleName = GetSimpleName(namespaceDefinition);
                string @string = _metadataReader.GetString(namespaceDefinition);
                NamespaceDataBuilder namespaceDataBuilder = new NamespaceDataBuilder(namespaceDefinition, simpleName, @string);
                namespaceDataBuilder.TypeDefinitions.Add(typeDefinition);
                table.Add(namespaceDefinition, namespaceDataBuilder);
            }
        }
    }
References System.Reflection.Metadata.Ecma335.NamespaceCache._metadataReader, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Reflection.Metadata.TypeDefinition.Attributes, System.Reflection.Metadata.Ecma335.NamespaceCache.GetSimpleName(), System.Reflection.Metadata.MetadataReader.GetString(), System.Reflection.Metadata.MetadataReader.GetTypeDefinition(), System.Reflection.Metadata.MetadataReader.TypeDefinitions, System.Reflection.Metadata.MetadataReader.TypeDefTable, and System.value.
Referenced by System.Reflection.Metadata.Ecma335.NamespaceCache.PopulateNamespaceTable().