Terraria: System.Transactions.EnlistmentState.InternalAborted
InternalAborted()
virtual void System.Transactions.EnlistmentState.InternalAborted (InternalEnlistment enlistment) inline package virtual inherited
Reimplemented in System.Transactions.DurableEnlistmentActive, System.Transactions.DurableEnlistmentEnded, System.Transactions.VolatileEnlistmentAborting, System.Transactions.VolatileEnlistmentActive, System.Transactions.VolatileEnlistmentEnded, System.Transactions.VolatileEnlistmentPrepared, System.Transactions.VolatileEnlistmentPreparing, and System.Transactions.VolatileEnlistmentPreparingAborting.
Definition at line 50 of file EnlistmentState.cs.
    {
        throw TransactionException.CreateEnlistmentStateException(null, enlistment?.DistributedTxId ?? Guid.Empty);
    }
References System.Transactions.TransactionException.CreateEnlistmentStateException(), and System.Guid.Empty.
Referenced by System.Transactions.TransactionStateAborted.EnterState(), and System.Transactions.TransactionStatePromotedNonMSDTCAborted.EnterState().