Terraria: System.Transactions.EnlistmentState.Aborted
Aborted()
virtual void System.Transactions.EnlistmentState.Aborted (InternalEnlistment enlistment, Exception e) inline package virtual inherited
Reimplemented in System.Transactions.DurableEnlistmentAborting, System.Transactions.DurableEnlistmentCommitting, System.Transactions.DurableEnlistmentDelegated, System.Transactions.EnlistmentStatePromoted, and System.Transactions.VolatileEnlistmentSPC.
Definition at line 35 of file EnlistmentState.cs.
    {
        throw TransactionException.CreateEnlistmentStateException(null, enlistment?.DistributedTxId ?? Guid.Empty);
    }
References System.Transactions.TransactionException.CreateEnlistmentStateException(), and System.Guid.Empty.
Referenced by System.Transactions.SinglePhaseEnlistment.Aborted(), and System.Transactions.SinglePhaseEnlistment.Aborted().