Terraria: System.Transactions.EnlistmentState.ForceRollback
ForceRollback()
virtual void System.Transactions.EnlistmentState.ForceRollback (InternalEnlistment enlistment, Exception e) inline package virtual inherited
Reimplemented in System.Transactions.EnlistmentStatePromoted, System.Transactions.VolatileEnlistmentPreparing, and System.Transactions.VolatileEnlistmentPreparingAborting.
Definition at line 25 of file EnlistmentState.cs.
    {
        throw TransactionException.CreateEnlistmentStateException(null, enlistment?.DistributedTxId ?? Guid.Empty);
    }
References System.Transactions.TransactionException.CreateEnlistmentStateException(), and System.Guid.Empty.
Referenced by System.Transactions.PreparingEnlistment.ForceRollback(), and System.Transactions.PreparingEnlistment.ForceRollback().