Terraria: System.Net.Security.SslStreamPal.AcquireCredentialsHandle
AcquireCredentialsHandle() [3/3]
static SafeFreeCredentials System.Net.Security.SslStreamPal.AcquireCredentialsHandle (SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, bool isServer) inline static
Definition at line 76 of file SslStreamPal.cs.
    {
        SafeFreeCredentials safeFreeCredentials = ((!UseNewCryptoApi || policy == EncryptionPolicy.NoEncryption) ? AcquireCredentialsHandleSchannelCred(certificateContext?.Certificate, protocols, policy, isServer) : AcquireCredentialsHandleSchCredentials(certificateContext?.Certificate, protocols, policy, isServer));
        if (certificateContext != null && certificateContext.Trust != null && certificateContext.Trust._sendTrustInHandshake)
        {
            AttachCertificateStore(safeFreeCredentials, certificateContext.Trust._store);
        }
        return safeFreeCredentials;
    }
References System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(), System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(), System.Net.Security.SslStreamPal.AttachCertificateStore(), System.Net.Security.Certificate, and System.Net.Security.SslStreamPal.UseNewCryptoApi.
Referenced by System.Net.Security.SecureChannel.AcquireClientCredentials(), System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred(), System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(), and System.Net.Security.SecureChannel.AcquireServerCredentials().