Terraria: System.Net.Security.SslStreamPal.InitializeSecurityContext
InitializeSecurityContext()
static SecurityStatusPal System.Net.Security.SslStreamPal.InitializeSecurityContext (ref SafeFreeCredentials credentialsHandle, ref SafeDeleteSslContext context, string targetName, ReadOnlySpan< byte > inputBuffer, ref byte[] outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) inline static
Definition at line 51 of file SslStreamPal.cs.
    {
        global::Interop.SspiCli.ContextFlags outFlags = global::Interop.SspiCli.ContextFlags.Zero;
        InputSecurityBuffers inputBuffers = default(InputSecurityBuffers);
        inputBuffers.SetNextBuffer(new InputSecurityBuffer(inputBuffer, SecurityBufferType.SECBUFFER_TOKEN));
        inputBuffers.SetNextBuffer(new InputSecurityBuffer(default(ReadOnlySpan<byte>), SecurityBufferType.SECBUFFER_EMPTY));
        if (sslAuthenticationOptions.ApplicationProtocols != null && sslAuthenticationOptions.ApplicationProtocols.Count != 0)
        {
            byte[] array = ConvertAlpnProtocolListToByteArray(sslAuthenticationOptions.ApplicationProtocols);
            inputBuffers.SetNextBuffer(new InputSecurityBuffer(new ReadOnlySpan<byte>(array), SecurityBufferType.SECBUFFER_APPLICATION_PROTOCOLS));
        }
        SecurityBuffer outputBuffer2 = new SecurityBuffer(outputBuffer, SecurityBufferType.SECBUFFER_TOKEN);
        int win32SecurityStatus = SSPIWrapper.InitializeSecurityContext(GlobalSSPI.SSPISecureChannel, ref credentialsHandle, ref context, targetName, global::Interop.SspiCli.ContextFlags.ReplayDetect | global::Interop.SspiCli.ContextFlags.SequenceDetect | global::Interop.SspiCli.ContextFlags.Confidentiality | global::Interop.SspiCli.ContextFlags.AllocateMemory | global::Interop.SspiCli.ContextFlags.InitManualCredValidation, global::Interop.SspiCli.Endianness.SECURITY_NATIVE_DREP, inputBuffers, ref outputBuffer2, ref outFlags);
        outputBuffer = outputBuffer2.token;
        return SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt(win32SecurityStatus);
    }
References System.array, System.Net.Security.SslStreamPal.ConvertAlpnProtocolListToByteArray(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt(), System.Net.SSPIWrapper.InitializeSecurityContext(), and System.Net.GlobalSSPI.SSPISecureChannel.
Referenced by System.Net.Security.SecureChannel.GenerateToken().