Terraria: System.Net.Security.SslStreamPal.ApplyShutdownToken
ApplyShutdownToken()
static SecurityStatusPal System.Net.Security.SslStreamPal.ApplyShutdownToken (ref SafeFreeCredentials credentialsHandle, SafeDeleteContext securityContext) inline static
Definition at line 293 of file SslStreamPal.cs.
    {
        SecurityBuffer inputBuffer = new SecurityBuffer(s_schannelShutdownBytes, SecurityBufferType.SECBUFFER_TOKEN);
        global::Interop.SECURITY_STATUS win32SecurityStatus = (global::Interop.SECURITY_STATUS)SSPIWrapper.ApplyControlToken(GlobalSSPI.SSPISecureChannel, ref securityContext, in inputBuffer);
        return SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(win32SecurityStatus, attachException: true);
    }
References System.Net.SSPIWrapper.ApplyControlToken(), System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(), System.Net.Security.SslStreamPal.s_schannelShutdownBytes, and System.Net.GlobalSSPI.SSPISecureChannel.
Referenced by System.Net.Security.SecureChannel.CreateShutdownToken().