Terraria: System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred
AcquireCredentialsHandleSchannelCred()
static unsafe SafeFreeCredentials System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchannelCred (X509Certificate2 certificate, SslProtocols protocols, EncryptionPolicy policy, bool isServer) inline static
Definition at line 100 of file SslStreamPal.cs.
    {
        int protocolFlagsFromSslProtocols = GetProtocolFlagsFromSslProtocols(protocols, isServer);
        global::Interop.SspiCli.CredentialUse credUsage;
        global::Interop.SspiCli.SCHANNEL_CRED.Flags flags;
        if (!isServer)
        {
            credUsage = global::Interop.SspiCli.CredentialUse.SECPKG_CRED_OUTBOUND;
            flags = global::Interop.SspiCli.SCHANNEL_CRED.Flags.SCH_CRED_MANUAL_CRED_VALIDATION | global::Interop.SspiCli.SCHANNEL_CRED.Flags.SCH_CRED_NO_DEFAULT_CREDS | global::Interop.SspiCli.SCHANNEL_CRED.Flags.SCH_SEND_AUX_RECORD;
            if ((protocolFlagsFromSslProtocols == 0 || ((uint)protocolFlagsFromSslProtocols & 0xFFFFFFC3u) != 0) && policy != EncryptionPolicy.AllowNoEncryption && policy != EncryptionPolicy.NoEncryption)
            {
                flags |= global::Interop.SspiCli.SCHANNEL_CRED.Flags.SCH_USE_STRONG_CRYPTO;
            }
        }
        else
        {
            credUsage = global::Interop.SspiCli.CredentialUse.SECPKG_CRED_INBOUND;
            flags = global::Interop.SspiCli.SCHANNEL_CRED.Flags.SCH_SEND_AUX_RECORD;
        }
        if (System.Net.NetEventSource.Log.IsEnabled())
        {
            System.Net.NetEventSource.Info($"flags=({flags}), ProtocolFlags=({protocolFlagsFromSslProtocols}), EncryptionPolicy={policy}", null, "AcquireCredentialsHandleSchannelCred");
        }
        global::Interop.SspiCli.SCHANNEL_CRED sCHANNEL_CRED = CreateSecureCredential(flags, protocolFlagsFromSslProtocols, policy);
        global::Interop.Crypt32.CERT_CONTEXT* ptr = null;
        if (certificate != null)
        {
            sCHANNEL_CRED.cCreds = 1;
            ptr = (global::Interop.Crypt32.CERT_CONTEXT*)(void*)certificate.Handle;
            sCHANNEL_CRED.paCred = &ptr;
        }
        return AcquireCredentialsHandle(credUsage, &sCHANNEL_CRED);
    }
References System.Net.Security.SslStreamPal.AcquireCredentialsHandle(), System.Net.Security.SslStreamPal.CreateSecureCredential(), System.Net.Security.SslStreamPal.GetProtocolFlagsFromSslProtocols(), System.Net.NetEventSource.Info(), and System.Net.NetEventSource.Log.
Referenced by System.Net.Security.SslStreamPal.AcquireCredentialsHandle().