Terraria: System.Net.Security.SslStreamPal.EncryptMessage
EncryptMessage()
static unsafe SecurityStatusPal System.Net.Security.SslStreamPal.EncryptMessage (SafeDeleteSslContext securityContext, ReadOnlyMemory< byte > input, int headerSize, int trailerSize, ref byte[] output, out int resultSize) inline static
Definition at line 197 of file SslStreamPal.cs.
    {
        checked
        {
            int num = input.Length + headerSize + trailerSize;
            if (output == null || output.Length < num)
            {
                output = new byte[num];
            }
            input.Span.CopyTo(new Span<byte>(output, headerSize, input.Length));
            global::Interop.SspiCli.SecBuffer* ptr = stackalloc global::Interop.SspiCli.SecBuffer[4];
            global::Interop.SspiCli.SecBufferDesc secBufferDesc = new global::Interop.SspiCli.SecBufferDesc(4);
            secBufferDesc.pBuffers = ptr;
            global::Interop.SspiCli.SecBufferDesc inputOutput = secBufferDesc;
            fixed (byte* ptr3 = output)
            {
                global::Interop.SspiCli.SecBuffer* ptr2 = ptr;
                ptr2->BufferType = SecurityBufferType.SECBUFFER_STREAM_HEADER;
                ptr2->pvBuffer = (IntPtr)ptr3;
                ptr2->cbBuffer = headerSize;
                global::Interop.SspiCli.SecBuffer* ptr4 = ptr + 1;
                ptr4->BufferType = SecurityBufferType.SECBUFFER_DATA;
                ptr4->pvBuffer = (IntPtr)(ptr3 + headerSize);
                ptr4->cbBuffer = input.Length;
                global::Interop.SspiCli.SecBuffer* ptr5 = ptr + 2;
                ptr5->BufferType = SecurityBufferType.SECBUFFER_STREAM_TRAILER;
                ptr5->pvBuffer = (IntPtr)(ptr3 + headerSize + input.Length);
                ptr5->cbBuffer = trailerSize;
                global::Interop.SspiCli.SecBuffer* ptr6 = ptr + 3;
                ptr6->BufferType = SecurityBufferType.SECBUFFER_EMPTY;
                ptr6->cbBuffer = 0;
                ptr6->pvBuffer = IntPtr.Zero;
                int num2 = GlobalSSPI.SSPISecureChannel.EncryptMessage(securityContext, ref inputOutput, 0u);
                if (num2 != 0)
                {
                    if (System.Net.NetEventSource.Log.IsEnabled())
                    {
                        System.Net.NetEventSource.Info(securityContext, $"Encrypt ERROR {num2:X}", "EncryptMessage");
                    }
                    resultSize = 0;
                    return SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt(num2);
                }
                resultSize = ptr2->cbBuffer + ptr4->cbBuffer + ptr5->cbBuffer;
                return new SecurityStatusPal(SecurityStatusPalErrorCode.OK);
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromNativeInt(), System.Net.NetEventSource.Info(), System.input, System.Net.NetEventSource.Log, System.Net.GlobalSSPI.SSPISecureChannel, and System.IntPtr.Zero.
Referenced by System.Net.Security.SecureChannel.Encrypt().