Terraria: PlayerSleepingHelper.StopSleeping
StopSleeping()
void PlayerSleepingHelper.StopSleeping (Player player, bool multiplayerBroadcast = true) inline
     {
         if (isSleeping)
         {
             SetIsSleepingAndAdjustPlayerRotation(player, state: false);
             timeSleeping = 0;
             sleepingIndex = -1;
             visualOffsetOfBedBase = default(Vector2);
             if (multiplayerBroadcast && Main.myPlayer == player.whoAmI)
             {
                 NetMessage.SendData(13, -1, -1, null, player.whoAmI);
             }
         }
     }
References isSleeping, Main.myPlayer, NetMessage.SendData(), SetIsSleepingAndAdjustPlayerRotation(), sleepingIndex, timeSleeping, visualOffsetOfBedBase, and Entity.whoAmI.
Referenced by StartSleeping(), and UpdateState().