Terraria: PlayerSleepingHelper.UpdateState
UpdateState()
void PlayerSleepingHelper.UpdateState (Player player) inline
     {
         if (!isSleeping)
         {
             timeSleeping = 0;
             return;
         }
         timeSleeping++;
         if (DoesPlayerHaveReasonToActUpInBed(player))
         {
             timeSleeping = 0;
         }
         Point coords = (player.Bottom + new Vector2(0f, -2f)).ToTileCoordinates();
         if (!GetSleepingTargetInfo(coords.X, coords.Y, out var targetDirection, out var _, out var visualoffset))
         {
             StopSleeping(player);
             return;
         }
         if (player.controlLeft || player.controlRight || player.controlUp || player.controlDown || player.controlJump || player.pulley || player.mount.Active || targetDirection != player.direction)
         {
             StopSleeping(player);
         }
         bool flag = false;
         if (player.itemAnimation > 0)
         {
             Item heldItem = player.HeldItem;
             if (heldItem.damage > 0 && !heldItem.noMelee)
             {
                 flag = true;
             }
             if (heldItem.fishingPole > 0)
             {
                 flag = true;
             }
             bool? flag2 = ItemID.Sets.ForcesBreaksSleeping[heldItem.type];
             if (flag2.HasValue)
             {
                 flag = flag2.Value;
             }
         }
         if (flag)
         {
             StopSleeping(player);
         }
         if (Main.sleepingManager.GetNextPlayerStackIndexInCoords(coords) >= 2)
         {
             StopSleeping(player);
         }
         if (isSleeping)
         {
             visualOffsetOfBedBase = visualoffset;
             Main.sleepingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, coords, out sleepingIndex);
         }
     }
References Mount.Active, AnchoredEntitiesCollection.AddPlayerAndGetItsStackedIndexInCoords(), Entity.Bottom, Player.controlDown, Player.controlJump, Player.controlLeft, Player.controlRight, Player.controlUp, Item.damage, Entity.direction, DoesPlayerHaveReasonToActUpInBed(), Item.fishingPole, ItemID.Sets.ForcesBreaksSleeping, AnchoredEntitiesCollection.GetNextPlayerStackIndexInCoords(), GetSleepingTargetInfo(), Player.HeldItem, isSleeping, Player.itemAnimation, Player.mount, Item.noMelee, Player.pulley, sleepingIndex, Main.sleepingManager, StopSleeping(), timeSleeping, Item.type, visualOffsetOfBedBase, and Entity.whoAmI.