Terraria: System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken
GetMemberRefToken()
int System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken (MethodBase methodInfo, Type[] optionalParameterTypes) inline private
Definition at line 333 of file DynamicILGenerator.cs.
    {
        if (optionalParameterTypes != null && (methodInfo.CallingConvention & CallingConventions.VarArgs) == 0)
        {
            throw new InvalidOperationException(SR.InvalidOperation_NotAVarArgCallingConvention);
        }
        RuntimeMethodInfo runtimeMethodInfo = methodInfo as RuntimeMethodInfo;
        DynamicMethod dynamicMethod = methodInfo as DynamicMethod;
        if (runtimeMethodInfo == null && dynamicMethod == null)
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeMethodInfo, "methodInfo");
        }
        ParameterInfo[] parametersNoCopy = methodInfo.GetParametersNoCopy();
        Type[] array;
        Type[][] array2;
        Type[][] array3;
        if (parametersNoCopy != null && parametersNoCopy.Length != 0)
        {
            array = new Type[parametersNoCopy.Length];
            array2 = new Type[array.Length][];
            array3 = new Type[array.Length][];
            for (int i = 0; i < parametersNoCopy.Length; i++)
            {
                array[i] = parametersNoCopy[i].ParameterType;
                array2[i] = parametersNoCopy[i].GetRequiredCustomModifiers();
                array3[i] = parametersNoCopy[i].GetOptionalCustomModifiers();
            }
        }
        else
        {
            array = null;
            array2 = null;
            array3 = null;
        }
        SignatureHelper memberRefSignature = GetMemberRefSignature(methodInfo.CallingConvention, MethodBuilder.GetMethodBaseReturnType(methodInfo), array, array2, array3, optionalParameterTypes);
        if (runtimeMethodInfo != null)
        {
            return GetTokenForVarArgMethod(runtimeMethodInfo, memberRefSignature);
        }
        return GetTokenForVarArgMethod(dynamicMethod, memberRefSignature);
    }
References System.SR.Argument_MustBeRuntimeMethodInfo, System.array, System.Reflection.MethodBase.CallingConvention, System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature(), System.Reflection.Emit.MethodBuilder.GetMethodBaseReturnType(), System.Reflection.ParameterInfo.GetOptionalCustomModifiers(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Reflection.ParameterInfo.GetRequiredCustomModifiers(), System.Reflection.Emit.DynamicILGenerator.GetTokenForVarArgMethod(), System.SR.InvalidOperation_NotAVarArgCallingConvention, and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.Reflection.Emit.DynamicILGenerator.EmitCall().