Terraria: System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature
GetMemberRefSignature() [2/2]
override SignatureHelper System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature (CallingConventions call, Type returnType, Type[] parameterTypes, Type requiredCustomModifiers[][], Type optionalCustomModifiers[][], Type[] optionalParameterTypes) inline package virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 375 of file DynamicILGenerator.cs.
    {
        SignatureHelper methodSigHelper = SignatureHelper.GetMethodSigHelper(null, call, returnType, null, null, parameterTypes, requiredCustomModifiers, optionalCustomModifiers);
        if (optionalParameterTypes != null && optionalParameterTypes.Length != 0)
        {
            methodSigHelper.AddSentinel();
            methodSigHelper.AddArguments(optionalParameterTypes, null, null);
        }
        return methodSigHelper;
    }
References System.Reflection.Emit.SignatureHelper.AddArguments(), System.Reflection.Emit.SignatureHelper.AddSentinel(), and System.Reflection.Emit.SignatureHelper.GetMethodSigHelper().
Referenced by System.Reflection.Emit.DynamicILGenerator.EmitCalli(), and System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken().