Terraria: System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey
FromPkcs1PrivateKey()
static void System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey (ReadOnlyMemory< byte > keyData, in AlgorithmIdentifierAsn algId, out RSAParameters ret) inline static package
Definition at line 10 of file RSAKeyFormatHelper.cs.
    {
        RSAPrivateKeyAsn rSAPrivateKeyAsn = RSAPrivateKeyAsn.Decode(keyData, AsnEncodingRules.BER);
        if (!algId.HasNullEquivalentParameters())
        {
            throw new CryptographicException(System.SR.Cryptography_Der_Invalid_Encoding);
        }
        if (rSAPrivateKeyAsn.Version > 0)
        {
            throw new CryptographicException(System.SR.Format(System.SR.Cryptography_RSAPrivateKey_VersionTooNew, rSAPrivateKeyAsn.Version, 0));
        }
        byte[] array = rSAPrivateKeyAsn.Modulus.ToByteArray(isUnsigned: true, isBigEndian: true);
        int length = (array.Length + 1) / 2;
        ret = new RSAParameters
        {
            Modulus = array,
            Exponent = rSAPrivateKeyAsn.PublicExponent.ToByteArray(isUnsigned: true, isBigEndian: true),
            D = rSAPrivateKeyAsn.PrivateExponent.ExportKeyParameter(array.Length),
            P = rSAPrivateKeyAsn.Prime1.ExportKeyParameter(length),
            Q = rSAPrivateKeyAsn.Prime2.ExportKeyParameter(length),
            DP = rSAPrivateKeyAsn.Exponent1.ExportKeyParameter(length),
            DQ = rSAPrivateKeyAsn.Exponent2.ExportKeyParameter(length),
            InverseQ = rSAPrivateKeyAsn.Coefficient.ExportKeyParameter(length)
        };
    }
References System.array, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Coefficient, System.SR.Cryptography_Der_Invalid_Encoding, System.SR.Cryptography_RSAPrivateKey_VersionTooNew, System.D, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(), System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Exponent1, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Exponent2, System.SR.Format(), System.length, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Modulus, System.P, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Prime1, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Prime2, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.PrivateExponent, System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.PublicExponent, System.Q, and System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Version.
Referenced by System.Security.Cryptography.RSA.ImportRSAPrivateKey(), System.Security.Cryptography.RSAKeyFormatHelper.ReadEncryptedPkcs8(), and System.Security.Cryptography.RSAKeyFormatHelper.ReadEncryptedPkcs8().