Terraria: ReLogic.Peripherals.RGB.Razer.RazerMousepad.Present
Present()
override void ReLogic.Peripherals.RGB.Razer.RazerMousepad.Present () inline
Definition at line 45 of file RazerMousepad.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < base.LedCount; i++)
        {
            _effect.Color[i] = RazerHelper.Vector4ToDeviceColor(GetProcessedLedColor(i));
        }
        _handle.SetAsMousepadEffect(ref _effect);
        _handle.Apply();
    }
References ReLogic.Peripherals.RGB.Razer.RazerMousepad._effect, ReLogic.Peripherals.RGB.Razer.RazerMousepad._handle, ReLogic.Peripherals.RGB.Razer.EffectHandle.Apply(), ReLogic.Peripherals.RGB.RgbDevice.GetProcessedLedColor(), ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsMousepadEffect(), and ReLogic.Peripherals.RGB.Razer.RazerHelper.Vector4ToDeviceColor().