Terraria: System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PrivateKey
WritePkcs1PrivateKey()
static AsnWriter System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs1PrivateKey (in RSAParameters rsaParameters) inline static package
Definition at line 110 of file RSAKeyFormatHelper.cs.
    {
        if (rsaParameters.Modulus == null || rsaParameters.Exponent == null)
        {
            throw new CryptographicException(System.SR.Cryptography_InvalidRsaParameters);
        }
        if (rsaParameters.D == null || rsaParameters.P == null || rsaParameters.Q == null || rsaParameters.DP == null || rsaParameters.DQ == null || rsaParameters.InverseQ == null)
        {
            throw new CryptographicException(System.SR.Cryptography_NotValidPrivateKey);
        }
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        asnWriter.WriteInteger(0L);
        asnWriter.WriteKeyParameterInteger(rsaParameters.Modulus);
        asnWriter.WriteKeyParameterInteger(rsaParameters.Exponent);
        asnWriter.WriteKeyParameterInteger(rsaParameters.D);
        asnWriter.WriteKeyParameterInteger(rsaParameters.P);
        asnWriter.WriteKeyParameterInteger(rsaParameters.Q);
        asnWriter.WriteKeyParameterInteger(rsaParameters.DP);
        asnWriter.WriteKeyParameterInteger(rsaParameters.DQ);
        asnWriter.WriteKeyParameterInteger(rsaParameters.InverseQ);
        asnWriter.PopSequence();
        return asnWriter;
    }
References System.SR.Cryptography_InvalidRsaParameters, System.SR.Cryptography_NotValidPrivateKey, System.L, System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), and System.Formats.Asn1.AsnWriter.WriteInteger().
Referenced by System.Security.Cryptography.RSA.WritePkcs1PrivateKey().