Terraria: System.Reflection.Emit.DynamicILGenerator.EmitCalli
EmitCalli() [3/4]
override void System.Reflection.Emit.DynamicILGenerator.EmitCalli (OpCode opcode, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type[] optionalParameterTypes) inline
Definition at line 150 of file DynamicILGenerator.cs.
    {
        int num = 0;
        if (optionalParameterTypes != null && (callingConvention & CallingConventions.VarArgs) == 0)
        {
            throw new InvalidOperationException(SR.InvalidOperation_NotAVarArgCallingConvention);
        }
        SignatureHelper memberRefSignature = GetMemberRefSignature(callingConvention, returnType, parameterTypes, optionalParameterTypes);
        EnsureCapacity(7);
        Emit(OpCodes.Calli);
        if (returnType != typeof(void))
        {
            num++;
        }
        if (parameterTypes != null)
        {
            num -= parameterTypes.Length;
        }
        if (optionalParameterTypes != null)
        {
            num -= optionalParameterTypes.Length;
        }
        if ((callingConvention & CallingConventions.HasThis) == CallingConventions.HasThis)
        {
            num--;
        }
        num--;
        UpdateStackSize(OpCodes.Calli, num);
        int tokenForSig = GetTokenForSig(memberRefSignature.GetSignature(appendEndOfSig: true));
        PutInteger4(tokenForSig);
    }
References System.Reflection.Emit.OpCodes.Calli, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.DynamicILGenerator.GetMemberRefSignature(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.DynamicILGenerator.GetTokenForSig(), System.SR.InvalidOperation_NotAVarArgCallingConvention, System.Reflection.Emit.ILGenerator.PutInteger4(), and System.Reflection.Emit.ILGenerator.UpdateStackSize().