Terraria: System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs8PrivateKey
WritePkcs8PrivateKey()
static AsnWriter System.Security.Cryptography.RSAKeyFormatHelper.WritePkcs8PrivateKey (ReadOnlySpan< byte > pkcs1PrivateKey, AsnWriter copyFrom = null) inline static package
Definition at line 66 of file RSAKeyFormatHelper.cs.
    {
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.BER);
        using (asnWriter.PushSequence())
        {
            asnWriter.WriteInteger(0L);
            WriteAlgorithmIdentifier(asnWriter);
            if (copyFrom != null)
            {
                using (asnWriter.PushOctetString())
                {
                    copyFrom.CopyTo(asnWriter);
                }
            }
            else
            {
                asnWriter.WriteOctetString(pkcs1PrivateKey);
            }
        }
        return asnWriter;
    }
References System.L, System.Formats.Asn1.AsnWriter.PushOctetString(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.RSAKeyFormatHelper.WriteAlgorithmIdentifier(), System.Formats.Asn1.AsnWriter.WriteInteger(), and System.Formats.Asn1.AsnWriter.WriteOctetString().
Referenced by System.Security.Cryptography.RSA.WritePkcs8PrivateKey().