Terraria: System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock
BeginExceptFilterBlock()
override void System.Reflection.Emit.DynamicILGenerator.BeginExceptFilterBlock () inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 272 of file DynamicILGenerator.cs.
    {
        if (base.CurrExcStackCount == 0)
        {
            throw new NotSupportedException(SR.Argument_NotInExceptionBlock);
        }
        __ExceptionInfo _ExceptionInfo = base.CurrExcStack[base.CurrExcStackCount - 1];
        Label endLabel = _ExceptionInfo.GetEndLabel();
        Emit(OpCodes.Leave, endLabel);
        UpdateStackSize(OpCodes.Nop, 1);
        _ExceptionInfo.MarkFilterAddr(ILOffset);
    }
References System.SR.Argument_NotInExceptionBlock, System.Reflection.Emit.__ExceptionInfo.GetEndLabel(), System.Reflection.Emit.ILGenerator.ILOffset, System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.__ExceptionInfo.MarkFilterAddr(), System.Reflection.Emit.OpCodes.Nop, and System.Reflection.Emit.ILGenerator.UpdateStackSize().