Terraria: System.Reflection.Emit.DynamicILGenerator.Emit
Emit() [12/17]
override void System.Reflection.Emit.DynamicILGenerator.Emit (OpCode opcode, MethodInfo meth) inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 40 of file DynamicILGenerator.cs.
    {
        if (meth == null)
        {
            throw new ArgumentNullException("meth");
        }
        int num = 0;
        int num2 = 0;
        DynamicMethod dynamicMethod = meth as DynamicMethod;
        if (dynamicMethod == null)
        {
            RuntimeMethodInfo runtimeMethodInfo = meth as RuntimeMethodInfo;
            if (runtimeMethodInfo == null)
            {
                throw new ArgumentException(SR.Argument_MustBeRuntimeMethodInfo, "meth");
            }
            RuntimeType runtimeType = runtimeMethodInfo.GetRuntimeType();
            num2 = ((!(runtimeType != null) || (!runtimeType.IsGenericType && !runtimeType.IsArray)) ? GetTokenFor(runtimeMethodInfo) : GetTokenFor(runtimeMethodInfo, runtimeType));
        }
        else
        {
            if (opcode.Equals(OpCodes.Ldtoken) || opcode.Equals(OpCodes.Ldftn) || opcode.Equals(OpCodes.Ldvirtftn))
            {
                throw new ArgumentException(SR.Argument_InvalidOpCodeOnDynamicMethod);
            }
            num2 = GetTokenFor(dynamicMethod);
        }
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (opcode.StackBehaviourPush == StackBehaviour.Varpush && meth.ReturnType != typeof(void))
        {
            num++;
        }
        if (opcode.StackBehaviourPop == StackBehaviour.Varpop)
        {
            num -= meth.GetParametersNoCopy().Length;
        }
        if (!meth.IsStatic && !opcode.Equals(OpCodes.Newobj) && !opcode.Equals(OpCodes.Ldtoken) && !opcode.Equals(OpCodes.Ldftn))
        {
            num--;
        }
        UpdateStackSize(opcode, num);
        PutInteger4(num2);
    }
References System.SR.Argument_InvalidOpCodeOnDynamicMethod, System.SR.Argument_MustBeRuntimeMethodInfo, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Reflection.RuntimeMethodInfo.GetRuntimeType(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Type.IsArray, System.RuntimeType.IsGenericType, System.Reflection.MethodBase.IsStatic, System.Reflection.Emit.OpCodes.Ldftn, System.Reflection.Emit.OpCodes.Ldtoken, System.Reflection.Emit.OpCodes.Ldvirtftn, System.Reflection.Emit.OpCodes.Newobj, System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.MethodInfo.ReturnType, System.Reflection.Emit.OpCode.StackBehaviourPop, System.Reflection.Emit.OpCode.StackBehaviourPush, and System.Reflection.Emit.ILGenerator.UpdateStackSize().