Terraria: System.Security.Cryptography.RSAKeyFormatHelper.WriteSubjectPublicKeyInfo
WriteSubjectPublicKeyInfo()
static AsnWriter System.Security.Cryptography.RSAKeyFormatHelper.WriteSubjectPublicKeyInfo (ReadOnlySpan< byte > pkcs1PublicKey) inline static package
Definition at line 56 of file RSAKeyFormatHelper.cs.
    {
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        asnWriter.PushSequence();
        WriteAlgorithmIdentifier(asnWriter);
        asnWriter.WriteBitString(pkcs1PublicKey);
        asnWriter.PopSequence();
        return asnWriter;
    }
References System.Formats.Asn1.AsnWriter.PopSequence(), System.Formats.Asn1.AsnWriter.PushSequence(), System.Security.Cryptography.RSAKeyFormatHelper.WriteAlgorithmIdentifier(), and System.Formats.Asn1.AsnWriter.WriteBitString().
Referenced by System.Security.Cryptography.RSA.TryExportSubjectPublicKeyInfo().