Terraria: System.Reflection.Emit.DynamicILGenerator.EmitCalli
EmitCalli() [1/4]
override void System.Reflection.Emit.DynamicILGenerator.EmitCalli (OpCode opcode, CallingConvention unmanagedCallConv, Type returnType, Type[] parameterTypes) inline
Definition at line 182 of file DynamicILGenerator.cs.
    {
        int num = 0;
        int num2 = 0;
        if (parameterTypes != null)
        {
            num2 = parameterTypes.Length;
        }
        SignatureHelper methodSigHelper = SignatureHelper.GetMethodSigHelper(unmanagedCallConv, returnType);
        if (parameterTypes != null)
        {
            for (int i = 0; i < num2; i++)
            {
                methodSigHelper.AddArgument(parameterTypes[i]);
            }
        }
        if (returnType != typeof(void))
        {
            num++;
        }
        if (parameterTypes != null)
        {
            num -= num2;
        }
        num--;
        UpdateStackSize(OpCodes.Calli, num);
        EnsureCapacity(7);
        Emit(OpCodes.Calli);
        int tokenForSig = GetTokenForSig(methodSigHelper.GetSignature(appendEndOfSig: true));
        PutInteger4(tokenForSig);
    }
References System.Reflection.Emit.SignatureHelper.AddArgument(), System.Reflection.Emit.OpCodes.Calli, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.DynamicILGenerator.GetTokenForSig(), System.Reflection.Emit.ILGenerator.PutInteger4(), and System.Reflection.Emit.ILGenerator.UpdateStackSize().