Terraria: System.Reflection.Emit.DynamicILGenerator.Emit
Emit() [15/17]
override void System.Reflection.Emit.DynamicILGenerator.Emit (OpCode opcode, SignatureHelper signature) inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 253 of file DynamicILGenerator.cs.
    {
        if (signature == null)
        {
            throw new ArgumentNullException("signature");
        }
        int num = 0;
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (opcode.StackBehaviourPop == StackBehaviour.Varpop)
        {
            num -= signature.ArgumentCount;
            num--;
            UpdateStackSize(opcode, num);
        }
        int tokenForSig = GetTokenForSig(signature.GetSignature(appendEndOfSig: true));
        PutInteger4(tokenForSig);
    }
References System.Reflection.Emit.SignatureHelper.ArgumentCount, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.SignatureHelper.GetSignature(), System.Reflection.Emit.DynamicILGenerator.GetTokenForSig(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.Emit.OpCode.StackBehaviourPop, and System.Reflection.Emit.ILGenerator.UpdateStackSize().