Terraria: System.Reflection.Emit.DynamicILGenerator.BeginCatchBlock
BeginCatchBlock()
override void System.Reflection.Emit.DynamicILGenerator.BeginCatchBlock (Type exceptionType) inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 285 of file DynamicILGenerator.cs.
    {
        if (base.CurrExcStackCount == 0)
        {
            throw new NotSupportedException(SR.Argument_NotInExceptionBlock);
        }
        __ExceptionInfo _ExceptionInfo = base.CurrExcStack[base.CurrExcStackCount - 1];
        RuntimeType runtimeType = exceptionType as RuntimeType;
        if (_ExceptionInfo.GetCurrentState() == 1)
        {
            if (exceptionType != null)
            {
                throw new ArgumentException(SR.Argument_ShouldNotSpecifyExceptionType);
            }
            Emit(OpCodes.Endfilter);
            _ExceptionInfo.MarkCatchAddr(ILOffset, null);
            return;
        }
        if (exceptionType == null)
        {
            throw new ArgumentNullException("exceptionType");
        }
        if (runtimeType == null)
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType);
        }
        Label endLabel = _ExceptionInfo.GetEndLabel();
        Emit(OpCodes.Leave, endLabel);
        UpdateStackSize(OpCodes.Nop, 1);
        _ExceptionInfo.MarkCatchAddr(ILOffset, exceptionType);
        _ExceptionInfo.m_filterAddr[_ExceptionInfo.m_currentCatch - 1] = GetTokenFor(runtimeType);
    }
References System.SR.Argument_MustBeRuntimeType, System.SR.Argument_NotInExceptionBlock, System.SR.Argument_ShouldNotSpecifyExceptionType, System.Reflection.Emit.OpCodes.Endfilter, System.Reflection.Emit.__ExceptionInfo.GetCurrentState(), System.Reflection.Emit.__ExceptionInfo.GetEndLabel(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.ILGenerator.ILOffset, System.Reflection.Emit.OpCodes.Leave, System.Reflection.Emit.__ExceptionInfo.m_filterAddr, System.Reflection.Emit.__ExceptionInfo.MarkCatchAddr(), System.Reflection.Emit.OpCodes.Nop, and System.Reflection.Emit.ILGenerator.UpdateStackSize().