Terraria: System.Security.Cryptography.RSAKeyFormatHelper.ReadEncryptedPkcs8
ReadEncryptedPkcs8() [2/2]
static void System.Security.Cryptography.RSAKeyFormatHelper.ReadEncryptedPkcs8 (ReadOnlySpan< byte > source, ReadOnlySpan< char > password, out int bytesRead, out RSAParameters key) inline static package
Definition at line 135 of file RSAKeyFormatHelper.cs.
    {
        KeyFormatHelper.ReadEncryptedPkcs8(s_validOids, source, password, (KeyFormatHelper.KeyReader<RSAParameters>)FromPkcs1PrivateKey, out bytesRead, out key);
    }
References System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey(), System.key, System.Security.Cryptography.RSAKeyFormatHelper.s_validOids, and System.source.
Referenced by System.Security.Cryptography.RSA.ImportEncryptedPkcs8PrivateKey(), and System.Security.Cryptography.RSA.ImportEncryptedPkcs8PrivateKey().