Terraria: System.Reflection.Emit.DynamicILGenerator.GetTokenForSig
GetTokenForSig()
int System.Reflection.Emit.DynamicILGenerator.GetTokenForSig (byte[] sig) inline private
Definition at line 447 of file DynamicILGenerator.cs.
    {
        return m_scope.GetTokenFor(sig);
    }
References System.Reflection.Emit.DynamicScope.GetTokenFor(), and System.Reflection.Emit.DynamicILGenerator.m_scope.
Referenced by System.Reflection.Emit.DynamicILGenerator.Emit(), System.Reflection.Emit.DynamicILGenerator.EmitCalli(), and System.Reflection.Emit.DynamicILGenerator.EmitCalli().