Terraria: System.Reflection.Emit.DynamicILGenerator.EmitCall
EmitCall() [1/2]
override void System.Reflection.Emit.DynamicILGenerator.EmitCall (OpCode opcode, MethodInfo methodInfo, Type[] optionalParameterTypes) inline
Definition at line 214 of file DynamicILGenerator.cs.
    {
        if (methodInfo == null)
        {
            throw new ArgumentNullException("methodInfo");
        }
        if (!opcode.Equals(OpCodes.Call) && !opcode.Equals(OpCodes.Callvirt) && !opcode.Equals(OpCodes.Newobj))
        {
            throw new ArgumentException(SR.Argument_NotMethodCallOpcode, "opcode");
        }
        if (methodInfo.ContainsGenericParameters)
        {
            throw new ArgumentException(SR.Argument_GenericsInvalid, "methodInfo");
        }
        if (methodInfo.DeclaringType != null && methodInfo.DeclaringType.ContainsGenericParameters)
        {
            throw new ArgumentException(SR.Argument_GenericsInvalid, "methodInfo");
        }
        int num = 0;
        int memberRefToken = GetMemberRefToken(methodInfo, optionalParameterTypes);
        EnsureCapacity(7);
        InternalEmit(opcode);
        if (methodInfo.ReturnType != typeof(void))
        {
            num++;
        }
        num -= methodInfo.GetParameterTypes().Length;
        if (!(methodInfo is SymbolMethod) && !methodInfo.IsStatic && !opcode.Equals(OpCodes.Newobj))
        {
            num--;
        }
        if (optionalParameterTypes != null)
        {
            num -= optionalParameterTypes.Length;
        }
        UpdateStackSize(opcode, num);
        PutInteger4(memberRefToken);
    }
References System.SR.Argument_GenericsInvalid, System.SR.Argument_NotMethodCallOpcode, System.Reflection.Emit.OpCodes.Call, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.MethodBase.ContainsGenericParameters, System.Type.ContainsGenericParameters, System.Reflection.MemberInfo.DeclaringType, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.OpCode.Equals(), System.Reflection.Emit.DynamicILGenerator.GetMemberRefToken(), System.Reflection.MethodBase.GetParameterTypes(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.MethodBase.IsStatic, System.Reflection.Emit.OpCodes.Newobj, System.Reflection.Emit.ILGenerator.PutInteger4(), System.Reflection.MethodInfo.ReturnType, and System.Reflection.Emit.ILGenerator.UpdateStackSize().