Terraria: System.Reflection.Emit.DynamicILGenerator.Emit
Emit() [16/17]
override void System.Reflection.Emit.DynamicILGenerator.Emit (OpCode opcode, string str) inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 138 of file DynamicILGenerator.cs.
    {
        if (str == null)
        {
            throw new ArgumentNullException("str");
        }
        int tokenForString = GetTokenForString(str);
        EnsureCapacity(7);
        InternalEmit(opcode);
        PutInteger4(tokenForString);
    }
References System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.DynamicILGenerator.GetTokenForString(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.Emit.ILGenerator.PutInteger4(), and System.str.