Terraria: System.Reflection.Emit.DynamicILGenerator.Emit
Emit() [17/17]
override void System.Reflection.Emit.DynamicILGenerator.Emit (OpCode opcode, Type type) inline virtual
Reimplemented from System.Reflection.Emit.ILGenerator.
Definition at line 104 of file DynamicILGenerator.cs.
    {
        if (type == null)
        {
            throw new ArgumentNullException("type");
        }
        RuntimeType runtimeType = type as RuntimeType;
        if (runtimeType == null)
        {
            throw new ArgumentException(SR.Argument_MustBeRuntimeType);
        }
        int tokenFor = GetTokenFor(runtimeType);
        EnsureCapacity(7);
        InternalEmit(opcode);
        PutInteger4(tokenFor);
    }
References System.SR.Argument_MustBeRuntimeType, System.Reflection.Emit.ILGenerator.EnsureCapacity(), System.Reflection.Emit.DynamicILGenerator.GetTokenFor(), System.Reflection.Emit.ILGenerator.InternalEmit(), System.Reflection.Emit.ILGenerator.PutInteger4(), and System.type.