Terraria: System.Reflection.Metadata.BlobWriterImpl.WriteCompressedSignedInteger
WriteCompressedSignedInteger() [2/2]
static void System.Reflection.Metadata.BlobWriterImpl.WriteCompressedSignedInteger (ref BlobWriter writer, int value) inline static package
Definition at line 68 of file BlobWriterImpl.cs.
    {
        int num = value >> 31;
        if ((value & -64) == (num & -64))
        {
            int num2 = ((value & 0x3F) << 1) | (num & 1);
            writer.WriteByte((byte)num2);
        }
        else if ((value & -8192) == (num & -8192))
        {
            int num3 = ((value & 0x1FFF) << 1) | (num & 1);
            writer.WriteUInt16BE((ushort)(0x8000u | (uint)num3));
        }
        else if ((value & -268435456) == (num & -268435456))
        {
            int num4 = ((value & 0xFFFFFFF) << 1) | (num & 1);
            writer.WriteUInt32BE(0xC0000000u | (uint)num4);
        }
        else
        {
            Throw.ValueArgumentOutOfRange();
        }
    }
References System.value, System.Reflection.Throw.ValueArgumentOutOfRange(), and System.writer.
Referenced by System.Reflection.Metadata.BlobBuilder.WriteCompressedSignedInteger(), and System.Reflection.Metadata.BlobWriter.WriteCompressedSignedInteger().