Terraria: System.Reflection.Metadata.BlobWriterImpl.WriteConstant
WriteConstant() [2/2]
static void System.Reflection.Metadata.BlobWriterImpl.WriteConstant (ref BlobWriter writer, object? value) inline static package
Definition at line 116 of file BlobWriterImpl.cs.
    {
        if (value == null)
        {
            writer.WriteUInt32(0u);
            return;
        }
        Type type = value.GetType();
        if (type.GetTypeInfo().IsEnum)
        {
            type = Enum.GetUnderlyingType(type);
        }
        if (type == typeof(bool))
        {
            writer.WriteBoolean((bool)value);
            return;
        }
        if (type == typeof(int))
        {
            writer.WriteInt32((int)value);
            return;
        }
        if (type == typeof(string))
        {
            writer.WriteUTF16((string)value);
            return;
        }
        if (type == typeof(byte))
        {
            writer.WriteByte((byte)value);
            return;
        }
        if (type == typeof(char))
        {
            writer.WriteUInt16((char)value);
            return;
        }
        if (type == typeof(double))
        {
            writer.WriteDouble((double)value);
            return;
        }
        if (type == typeof(short))
        {
            writer.WriteInt16((short)value);
            return;
        }
        if (type == typeof(long))
        {
            writer.WriteInt64((long)value);
            return;
        }
        if (type == typeof(sbyte))
        {
            writer.WriteSByte((sbyte)value);
            return;
        }
        if (type == typeof(float))
        {
            writer.WriteSingle((float)value);
            return;
        }
        if (type == typeof(ushort))
        {
            writer.WriteUInt16((ushort)value);
            return;
        }
        if (type == typeof(uint))
        {
            writer.WriteUInt32((uint)value);
            return;
        }
        if (type == typeof(ulong))
        {
            writer.WriteUInt64((ulong)value);
            return;
        }
        throw new ArgumentException(System.SR.Format(System.SR.InvalidConstantValueOfType, type));
    }
References System.SR.Format(), System.Type.GetType(), System.Enum.GetUnderlyingType(), System.SR.InvalidConstantValueOfType, System.type, System.value, and System.writer.
Referenced by System.Reflection.Metadata.BlobBuilder.WriteConstant(), and System.Reflection.Metadata.BlobWriter.WriteConstant().