Terraria: Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Save
Save()
void Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Save (BinaryWriter writer) inline
Implements Terraria.GameContent.IPersistentPerWorldContent.
Definition at line 13 of file BestiaryUnlocksTracker.cs.
    {
        Kills.Save(writer);
        Sights.Save(writer);
        Chats.Save(writer);
    }
References Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Chats, Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Kills, Terraria.GameContent.Bestiary.NPCKillsTracker.Save(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Save(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Save(), and Terraria.GameContent.Bestiary.BestiaryUnlocksTracker.Sights.