Terraria: System.Diagnostics.Activity.TagsLinkedList.ToString
ToString()
override string System.Diagnostics.Activity.TagsLinkedList.ToString () inline
Definition at line 261 of file Activity.cs.
        {
            lock (this)
            {
                if (_first == null)
                {
                    return string.Empty;
                }
                if (_stringBuilder == null)
                {
                    _stringBuilder = new StringBuilder();
                }
                _stringBuilder.Append(_first.Value.Key);
                _stringBuilder.Append(':');
                _stringBuilder.Append(_first.Value.Value);
                for (DiagNode<KeyValuePair<string, object>> next = _first.Next; next != null; next = next.Next)
                {
                    _stringBuilder.Append(", ");
                    _stringBuilder.Append(next.Value.Key);
                    _stringBuilder.Append(':');
                    _stringBuilder.Append(next.Value.Value);
                }
                string result = _stringBuilder.ToString();
                _stringBuilder.Clear();
                return result;
            }
        }
References System.Diagnostics.Activity.TagsLinkedList._first, System.Diagnostics.Activity.TagsLinkedList._stringBuilder, System.Text.StringBuilder.Append(), System.Text.StringBuilder.Clear(), System.Diagnostics.DiagNode< T >.Next, System.Text.StringBuilder.ToString(), and System.Diagnostics.DiagNode< T >.Value.