Terraria: Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage
UIBestiaryEntryInfoPage()
Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage () inline
Definition at line 28 of file UIBestiaryEntryInfoPage.cs.
    {
        Width.Set(230f, 0f);
        Height.Set(0f, 1f);
        SetPadding(0f);
        BorderColor = new Color(89, 116, 213, 255);
        BackgroundColor = new Color(73, 94, 171);
        UIList uIList = new UIList
        {
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f)
        };
        uIList.SetPadding(2f);
        uIList.PaddingBottom = 4f;
        uIList.PaddingTop = 4f;
        Append(uIList);
        _list = uIList;
        uIList.ListPadding = 4f;
        uIList.ManualSortMethod = ManualIfnoSortingMethod;
        UIScrollbar uIScrollbar = new UIScrollbar();
        uIScrollbar.SetView(100f, 1000f);
        uIScrollbar.Height.Set(-20f, 1f);
        uIScrollbar.HAlign = 1f;
        uIScrollbar.VAlign = 0.5f;
        uIScrollbar.Left.Set(-6f, 0f);
        _scrollbar = uIScrollbar;
        _list.SetScrollbar(_scrollbar);
        CheckScrollBar();
        AppendBorderOverEverything();
    }
References Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._list, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage._scrollbar, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AppendBorderOverEverything(), Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.Height, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.ManualIfnoSortingMethod(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), and Terraria.UI.UIElement.Width.