Terraria: System.Text.RegularExpressions.RegexWriter.StringCode
StringCode()
int System.Text.RegularExpressions.RegexWriter.StringCode (string str) inline private
Definition at line 157 of file RegexWriter.cs.
    {
        if (!_stringTable.TryGetValue(str, out var value))
        {
            value = _stringTable.Count;
            _stringTable.Add(str, value);
        }
        return value;
    }
References System.Text.RegularExpressions.RegexWriter._stringTable, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Text.RegularExpressions.str, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.Text.RegularExpressions.value.
Referenced by System.Text.RegularExpressions.RegexWriter.EmitFragment().