Terraria: System.Text.RegularExpressions.RegexWriter.RegexCodeFromRegexTree
RegexCodeFromRegexTree()
RegexCode System.Text.RegularExpressions.RegexWriter.RegexCodeFromRegexTree (RegexTree tree) inline
Definition at line 44 of file RegexWriter.cs.
    {
        int capsize;
        if (tree.CapNumList == null || tree.CapTop == tree.CapNumList.Length)
        {
            capsize = tree.CapTop;
            _caps = null;
        }
        else
        {
            capsize = tree.CapNumList.Length;
            _caps = tree.Caps;
            for (int i = 0; i < tree.CapNumList.Length; i++)
            {
                _caps[tree.CapNumList[i]] = i;
            }
        }
        Emit(23, 0);
        RegexNode regexNode = tree.Root;
        int num = 0;
        while (true)
        {
            int num2 = regexNode.ChildCount();
            if (num2 == 0)
            {
                EmitFragment(regexNode.Type, regexNode, 0);
            }
            else if (num < num2)
            {
                EmitFragment(regexNode.Type | 0x40, regexNode, num);
                regexNode = regexNode.Child(num);
                _intStack.Append(num);
                num = 0;
                continue;
            }
            if (_intStack.Length == 0)
            {
                break;
            }
            num = _intStack.Pop();
            regexNode = regexNode.Next;
            EmitFragment(regexNode.Type | 0x80, regexNode, num);
            num++;
        }
        PatchJump(0, _emitted.Length);
        Emit(40);
        int[] codes = _emitted.AsSpan().ToArray();
        bool rightToLeft = (tree.Options & RegexOptions.RightToLeft) != 0;
        bool flag = (tree.Options & RegexOptions.Compiled) != 0;
        RegexBoyerMoore regexBoyerMoore = null;
        (string, bool)[] array = null;
        var (text, caseInsensitive) = RegexPrefixAnalyzer.ComputeLeadingSubstring(tree);
        if (text.Length > 1 && text.Length <= 50000)
        {
            CultureInfo culture = (((tree.Options & RegexOptions.CultureInvariant) != 0) ? CultureInfo.InvariantCulture : CultureInfo.CurrentCulture);
            regexBoyerMoore = new RegexBoyerMoore(text, caseInsensitive, rightToLeft, culture);
        }
        if (regexBoyerMoore == null || (regexBoyerMoore.NegativeUnicode != null && flag))
        {
            regexBoyerMoore = null;
            if ((tree.Options & RegexOptions.Compiled) != 0)
            {
                array = RegexPrefixAnalyzer.ComputeMultipleCharClasses(tree, 5);
            }
            if (array == null)
            {
                array = RegexPrefixAnalyzer.ComputeFirstCharClass(tree);
            }
        }
        int leadingAnchor = RegexPrefixAnalyzer.FindLeadingAnchor(tree);
        string[] array2 = new string[_stringTable.Count];
        foreach (KeyValuePair<string, int> item in _stringTable)
        {
            array2[item.Value] = item.Key;
        }
        return new RegexCode(tree, codes, array2, _trackCount, _caps, capsize, regexBoyerMoore, array, leadingAnchor, rightToLeft);
    }
References System.Text.RegularExpressions.RegexWriter._caps, System.Text.RegularExpressions.RegexWriter._emitted, System.Text.RegularExpressions.RegexWriter._intStack, System.Text.RegularExpressions.RegexWriter._stringTable, System.Text.RegularExpressions.RegexWriter._trackCount, System.Text.RegularExpressions.array, System.Text.RegularExpressions.RegexPrefixAnalyzer.ComputeFirstCharClass(), System.Text.RegularExpressions.RegexPrefixAnalyzer.ComputeLeadingSubstring(), System.Text.RegularExpressions.RegexPrefixAnalyzer.ComputeMultipleCharClasses(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.culture, System.Globalization.CultureInfo.CurrentCulture, System.Text.RegularExpressions.RegexWriter.Emit(), System.Text.RegularExpressions.RegexWriter.EmitFragment(), System.Text.RegularExpressions.RegexPrefixAnalyzer.FindLeadingAnchor(), System.Text.RegularExpressions.i, System.item, System.Text.RegularExpressions.RegexWriter.PatchJump(), and System.text.