Terraria: System.DomainNameHelper.IsValid
IsValid()
static unsafe bool System.DomainNameHelper.IsValid (char * name, int pos, ref int returnedEnd, ref bool notCanonical, bool notImplicitFile) inline static package
Definition at line 40 of file DomainNameHelper.cs.
    {
        char* ptr = name + pos;
        char* ptr2 = ptr;
        char* ptr3;
        for (ptr3 = name + returnedEnd; ptr2 < ptr3; ptr2++)
        {
            char c = *ptr2;
            if (c > '\u007f')
            {
                return false;
            }
            if (c < 'a' && (c == '/' || c == '\\' || (notImplicitFile && (c == ':' || c == '?' || c == '#'))))
            {
                ptr3 = ptr2;
                break;
            }
        }
        if (ptr3 == ptr)
        {
            return false;
        }
        do
        {
            for (ptr2 = ptr; ptr2 < ptr3 && *ptr2 != '.'; ptr2++)
            {
            }
            if (ptr == ptr2 || ptr2 - ptr > 63 || !IsASCIILetterOrDigit(*(ptr++), ref notCanonical))
            {
                return false;
            }
            while (ptr < ptr2)
            {
                if (!IsValidDomainLabelCharacter(*(ptr++), ref notCanonical))
                {
                    return false;
                }
            }
            ptr++;
        }
        while (ptr < ptr3);
        returnedEnd = (int)(ptr3 - name);
        return true;
    }
References System.DomainNameHelper.IsASCIILetterOrDigit(), and System.DomainNameHelper.IsValidDomainLabelCharacter().
Referenced by System.Uri.CheckAuthorityHelper(), and System.Uri.CheckHostName().