Terraria: System.DomainNameHelper.IsValidByIri
IsValidByIri()
static unsafe bool System.DomainNameHelper.IsValidByIri (char * name, int pos, ref int returnedEnd, ref bool notCanonical, bool notImplicitFile) inline static package
Definition at line 85 of file DomainNameHelper.cs.
    {
        char* ptr = name + pos;
        char* ptr2 = ptr;
        char* ptr3 = name + returnedEnd;
        int num = 0;
        for (; ptr2 < ptr3; ptr2++)
        {
            char c = *ptr2;
            if (c == '/' || c == '\\' || (notImplicitFile && (c == ':' || c == '?' || c == '#')))
            {
                ptr3 = ptr2;
                break;
            }
        }
        if (ptr3 == ptr)
        {
            return false;
        }
        do
        {
            ptr2 = ptr;
            num = 0;
            bool flag = false;
            for (; ptr2 < ptr3 && *ptr2 != '.' && *ptr2 != '。' && *ptr2 != '．' && *ptr2 != '｡'; ptr2++)
            {
                num++;
                if (*ptr2 > 'ÿ')
                {
                    num++;
                }
                if (*ptr2 >= '\u00a0')
                {
                    flag = true;
                }
            }
            if (ptr == ptr2 || (flag ? (num + 4) : num) > 63 || (*(ptr++) < '\u00a0' && !IsASCIILetterOrDigit(*(ptr - 1), ref notCanonical)))
            {
                return false;
            }
            while (ptr < ptr2)
            {
                if (*(ptr++) < '\u00a0' && !IsValidDomainLabelCharacter(*(ptr - 1), ref notCanonical))
                {
                    return false;
                }
            }
            ptr++;
        }
        while (ptr < ptr3);
        returnedEnd = (int)(ptr3 - name);
        return true;
    }
References System.DomainNameHelper.IsASCIILetterOrDigit(), and System.DomainNameHelper.IsValidDomainLabelCharacter().
Referenced by System.Uri.CheckAuthorityHelper(), and System.Uri.CheckHostName().