Terraria: System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract
ExportXmlDataContract()
void System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract (XmlDataContract dataContract) inline private
Definition at line 693 of file SchemaExporter.cs.
    {
        Type underlyingType = dataContract.UnderlyingType;
        if (!IsSpecialXmlType(underlyingType, out var typeName, out var xsdType, out var hasRoot) && !InvokeSchemaProviderMethod(underlyingType, _schemas, out typeName, out xsdType, out hasRoot))
        {
            InvokeGetSchemaMethod(underlyingType, _schemas, typeName);
        }
        if (hasRoot)
        {
            typeName.Equals(dataContract.StableName);
            if (SchemaHelper.GetSchemaElement(Schemas, new XmlQualifiedName(dataContract.TopLevelElementName.Value, dataContract.TopLevelElementNamespace.Value), out var outSchema) == null)
            {
                XmlSchemaElement xmlSchemaElement = ExportTopLevelElement(dataContract, outSchema);
                xmlSchemaElement.IsNillable = dataContract.IsTopLevelElementNullable;
                ReprocessAll(_schemas);
            }
            XmlSchemaType xmlSchemaType = xsdType;
            xsdType = SchemaHelper.GetSchemaType(_schemas, typeName, out outSchema);
            if (xmlSchemaType == null && xsdType == null && typeName.Namespace != "http://www.w3.org/2001/XMLSchema")
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.MissingSchemaType, typeName, DataContract.GetClrTypeFullName(underlyingType))));
            }
            if (xsdType != null)
            {
                xsdType.Annotation = GetSchemaAnnotation(ExportSurrogateData(dataContract), dataContract.IsValueType ? GetAnnotationMarkup(IsValueTypeName, XmlConvert.ToString(dataContract.IsValueType), outSchema) : null);
            }
        }
    }
References System.Runtime.Serialization.SchemaExporter._schemas, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.ExportSurrogateData(), System.Runtime.Serialization.SchemaExporter.ExportTopLevelElement(), System.SR.Format(), System.Runtime.Serialization.SchemaExporter.GetAnnotationMarkup(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation(), System.Runtime.Serialization.SchemaHelper.GetSchemaElement(), System.Runtime.Serialization.SchemaHelper.GetSchemaType(), System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod(), System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(), System.Runtime.Serialization.SchemaExporter.IsSpecialXmlType(), System.Runtime.Serialization.SchemaExporter.IsValueTypeName, System.SR.MissingSchemaType, System.Runtime.Serialization.SchemaExporter.ReprocessAll(), System.Runtime.Serialization.SchemaExporter.Schemas, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.XmlConvert.ToString().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportDataContract().