Terraria: System.Runtime.Serialization.SchemaExporter.ReprocessAll
ReprocessAll()
static void System.Runtime.Serialization.SchemaExporter.ReprocessAll (XmlSchemaSet schemas) inline static private
Definition at line 722 of file SchemaExporter.cs.
    {
        Hashtable hashtable = new Hashtable();
        Hashtable hashtable2 = new Hashtable();
        XmlSchema[] array = new XmlSchema[schemas.Count];
        schemas.CopyTo(array, 0);
        foreach (XmlSchema xmlSchema in array)
        {
            XmlSchemaObject[] array2 = new XmlSchemaObject[xmlSchema.Items.Count];
            xmlSchema.Items.CopyTo(array2, 0);
            foreach (XmlSchemaObject xmlSchemaObject in array2)
            {
                Hashtable hashtable3;
                XmlQualifiedName key;
                if (xmlSchemaObject is XmlSchemaElement)
                {
                    hashtable3 = hashtable;
                    key = new XmlQualifiedName(((XmlSchemaElement)xmlSchemaObject).Name, xmlSchema.TargetNamespace);
                }
                else
                {
                    if (!(xmlSchemaObject is XmlSchemaType))
                    {
                        continue;
                    }
                    hashtable3 = hashtable2;
                    key = new XmlQualifiedName(((XmlSchemaType)xmlSchemaObject).Name, xmlSchema.TargetNamespace);
                }
                object obj = hashtable3[key];
                if (obj != null)
                {
                    xmlSchema.Items.Remove(xmlSchemaObject);
                }
                else
                {
                    hashtable3.Add(key, xmlSchemaObject);
                }
            }
            schemas.Reprocess(xmlSchema);
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.Xml.Schema.XmlSchemaSet.CopyTo(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Schema.XmlSchemaSet.Count, System.Runtime.Serialization.Dictionary, System.key, System.Name, System.obj, and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract().