Terraria: System.Runtime.Serialization.SchemaExporter.ExportEnumDataContract
ExportEnumDataContract()
void System.Runtime.Serialization.SchemaExporter.ExportEnumDataContract (EnumDataContract enumDataContract, XmlSchema schema) inline private
Definition at line 605 of file SchemaExporter.cs.
    {
        XmlSchemaSimpleType xmlSchemaSimpleType = new XmlSchemaSimpleType();
        xmlSchemaSimpleType.Name = enumDataContract.StableName.Name;
        XmlElement xmlElement = ((enumDataContract.BaseContractName == DefaultEnumBaseTypeName) ? null : ExportActualType(enumDataContract.BaseContractName));
        xmlSchemaSimpleType.Annotation = GetSchemaAnnotation(xmlElement, ExportSurrogateData(enumDataContract));
        schema.Items.Add(xmlSchemaSimpleType);
        XmlSchemaSimpleTypeRestriction xmlSchemaSimpleTypeRestriction = new XmlSchemaSimpleTypeRestriction();
        xmlSchemaSimpleTypeRestriction.BaseTypeName = StringQualifiedName;
        SchemaHelper.AddSchemaImport(enumDataContract.BaseContractName.Namespace, schema);
        if (enumDataContract.Values != null)
        {
            for (int i = 0; i < enumDataContract.Values.Count; i++)
            {
                XmlSchemaEnumerationFacet xmlSchemaEnumerationFacet = new XmlSchemaEnumerationFacet();
                xmlSchemaEnumerationFacet.Value = enumDataContract.Members[i].Name;
                if (enumDataContract.Values[i] != GetDefaultEnumValue(enumDataContract.IsFlags, i))
                {
                    xmlSchemaEnumerationFacet.Annotation = GetSchemaAnnotation(EnumerationValueAnnotationName, enumDataContract.GetStringFromEnumValue(enumDataContract.Values[i]), schema);
                }
                xmlSchemaSimpleTypeRestriction.Facets.Add(xmlSchemaEnumerationFacet);
            }
        }
        if (enumDataContract.IsFlags)
        {
            XmlSchemaSimpleTypeList xmlSchemaSimpleTypeList = new XmlSchemaSimpleTypeList();
            XmlSchemaSimpleType xmlSchemaSimpleType2 = new XmlSchemaSimpleType();
            xmlSchemaSimpleType2.Content = xmlSchemaSimpleTypeRestriction;
            xmlSchemaSimpleTypeList.ItemType = xmlSchemaSimpleType2;
            xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeList;
        }
        else
        {
            xmlSchemaSimpleType.Content = xmlSchemaSimpleTypeRestriction;
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.SchemaHelper.AddSchemaImport(), System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection.Count, System.Runtime.Serialization.SchemaExporter.DefaultEnumBaseTypeName, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.EnumerationValueAnnotationName, System.Runtime.Serialization.SchemaExporter.ExportActualType(), System.Runtime.Serialization.SchemaExporter.ExportSurrogateData(), System.Runtime.Serialization.SchemaExporter.GetDefaultEnumValue(), System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation(), System.Runtime.Serialization.SchemaExporter.StringQualifiedName, and System.Collections.Generic.Dictionary< TKey, TValue >.Values.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportDataContract().