Terraria: System.Runtime.Serialization.SchemaExporter.ExportTopLevelElement
ExportTopLevelElement()
XmlSchemaElement System.Runtime.Serialization.SchemaExporter.ExportTopLevelElement (DataContract dataContract, XmlSchema schema) inline private
Definition at line 297 of file SchemaExporter.cs.
    {
        if (schema == null || dataContract.StableName.Namespace != dataContract.TopLevelElementNamespace.Value)
        {
            schema = GetSchema(dataContract.TopLevelElementNamespace.Value);
        }
        XmlSchemaElement xmlSchemaElement = new XmlSchemaElement();
        xmlSchemaElement.Name = dataContract.TopLevelElementName.Value;
        SetElementType(xmlSchemaElement, dataContract, schema);
        xmlSchemaElement.IsNillable = true;
        schema.Items.Add(xmlSchemaElement);
        return xmlSchemaElement;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.GetSchema(), and System.Runtime.Serialization.SchemaExporter.SetElementType().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportDataContract(), and System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract().