Terraria: System.Threading.SynchronizationContext.Post
Post()
virtual void System.Threading.SynchronizationContext.Post (SendOrPostCallback d, object? state) inline virtual
Definition at line 29 of file SynchronizationContext.cs.
    {
        ThreadPool.QueueUserWorkItem(delegate((SendOrPostCallback d, object state) s)
        {
            s.d(s.state);
        }, (d, state), preferLocal: false);
    }
References System.Threading.ThreadPool.QueueUserWorkItem(), System.s, and System.state.
Referenced by System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.AwaitUnsafeOnCompleted(), System.Progress< T >.OnReport(), System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.PostAction(), System.ComponentModel.AsyncOperation.PostCore(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), and System.Threading.Tasks.SynchronizationContextTaskScheduler.QueueTask().