Terraria: System.Runtime.Serialization.SchemaExporter.CreateTypeContent
CreateTypeContent()
XmlSchemaComplexContentExtension System.Runtime.Serialization.SchemaExporter.CreateTypeContent (XmlSchemaComplexType type, XmlQualifiedName baseTypeName, XmlSchema schema) inline private
Definition at line 682 of file SchemaExporter.cs.
    {
        SchemaHelper.AddSchemaImport(baseTypeName.Namespace, schema);
        XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = new XmlSchemaComplexContentExtension();
        xmlSchemaComplexContentExtension.BaseTypeName = baseTypeName;
        type.ContentModel = new XmlSchemaComplexContent();
        type.ContentModel.Content = xmlSchemaComplexContentExtension;
        return xmlSchemaComplexContentExtension;
    }
References System.Runtime.Serialization.SchemaHelper.AddSchemaImport(), and System.Runtime.Serialization.Dictionary.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), and System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract().