Terraria: System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract
ExportCollectionDataContract()
void System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract (CollectionDataContract collectionDataContract, XmlSchema schema) inline private
Definition at line 538 of file SchemaExporter.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = new XmlSchemaComplexType();
        xmlSchemaComplexType.Name = collectionDataContract.StableName.Name;
        schema.Items.Add(xmlSchemaComplexType);
        XmlElement xmlElement = null;
        XmlElement xmlElement2 = null;
        if (collectionDataContract.UnderlyingType.IsGenericType && CollectionDataContract.IsCollectionDataContract(collectionDataContract.UnderlyingType))
        {
            xmlElement = ExportGenericInfo(collectionDataContract.UnderlyingType, "GenericType", "http://schemas.microsoft.com/2003/10/Serialization/");
        }
        if (collectionDataContract.IsDictionary)
        {
            xmlElement2 = ExportIsDictionary();
        }
        xmlSchemaComplexType.Annotation = GetSchemaAnnotation(xmlElement2, xmlElement, ExportSurrogateData(collectionDataContract));
        XmlSchemaSequence xmlSchemaSequence = new XmlSchemaSequence();
        XmlSchemaElement xmlSchemaElement = new XmlSchemaElement();
        xmlSchemaElement.Name = collectionDataContract.ItemName;
        xmlSchemaElement.MinOccurs = 0m;
        xmlSchemaElement.MaxOccursString = "unbounded";
        if (collectionDataContract.IsDictionary)
        {
            ClassDataContract classDataContract = collectionDataContract.ItemContract as ClassDataContract;
            XmlSchemaComplexType xmlSchemaComplexType2 = new XmlSchemaComplexType();
            XmlSchemaSequence xmlSchemaSequence2 = new XmlSchemaSequence();
            foreach (DataMember member in classDataContract.Members)
            {
                XmlSchemaElement xmlSchemaElement2 = new XmlSchemaElement();
                xmlSchemaElement2.Name = member.Name;
                SetElementType(xmlSchemaElement2, _dataContractSet.GetMemberTypeDataContract(member), schema);
                SchemaHelper.AddElementForm(xmlSchemaElement2, schema);
                if (member.IsNullable)
                {
                    xmlSchemaElement2.IsNillable = true;
                }
                xmlSchemaElement2.Annotation = GetSchemaAnnotation(ExportSurrogateData(member));
                xmlSchemaSequence2.Items.Add(xmlSchemaElement2);
            }
            xmlSchemaComplexType2.Particle = xmlSchemaSequence2;
            xmlSchemaElement.SchemaType = xmlSchemaComplexType2;
        }
        else
        {
            if (collectionDataContract.IsItemTypeNullable)
            {
                xmlSchemaElement.IsNillable = true;
            }
            DataContract itemTypeDataContract = _dataContractSet.GetItemTypeDataContract(collectionDataContract);
            SetElementType(xmlSchemaElement, itemTypeDataContract, schema);
        }
        SchemaHelper.AddElementForm(xmlSchemaElement, schema);
        xmlSchemaSequence.Items.Add(xmlSchemaElement);
        xmlSchemaComplexType.Particle = xmlSchemaSequence;
        if (collectionDataContract.IsReference)
        {
            AddReferenceAttributes(xmlSchemaComplexType.Attributes, schema);
        }
    }
References System.Runtime.Serialization.SchemaExporter._dataContractSet, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.SchemaHelper.AddElementForm(), System.Runtime.Serialization.SchemaExporter.AddReferenceAttributes(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.SchemaExporter.ExportIsDictionary(), System.Runtime.Serialization.SchemaExporter.ExportSurrogateData(), System.Runtime.Serialization.DataContractSet.GetItemTypeDataContract(), System.Runtime.Serialization.DataContractSet.GetMemberTypeDataContract(), System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation(), System.Runtime.Serialization.CollectionDataContract.IsCollectionDataContract(), System.Runtime.Serialization.DataMember.IsNullable, System.Runtime.Serialization.DataMember.Name, and System.Runtime.Serialization.SchemaExporter.SetElementType().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportDataContract().