Terraria: System.Runtime.Serialization.SchemaExporter.ExportGenericInfo
ExportGenericInfo()
XmlElement System.Runtime.Serialization.SchemaExporter.ExportGenericInfo (Type clrType, string elementName, string elementNs) inline private
Definition at line 447 of file SchemaExporter.cs.
    {
        int num = 0;
        Type itemType;
        while (CollectionDataContract.IsCollection(clrType, out itemType) && DataContract.GetBuiltInDataContract(clrType) == null && !CollectionDataContract.IsCollectionDataContract(clrType))
        {
            clrType = itemType;
            num++;
        }
        Type[] array = null;
        IList<int> list = null;
        if (clrType.IsGenericType)
        {
            array = clrType.GetGenericArguments();
            string text;
            if (clrType.DeclaringType == null)
            {
                text = clrType.Name;
            }
            else
            {
                int num2 = ((clrType.Namespace != null) ? clrType.Namespace.Length : 0);
                if (num2 > 0)
                {
                    num2++;
                }
                text = DataContract.GetClrTypeFullName(clrType).Substring(num2).Replace('+', '.');
            }
            int num3 = text.IndexOf('[');
            if (num3 >= 0)
            {
                text = text.Substring(0, num3);
            }
            list = DataContract.GetDataContractNameForGenericName(text, null);
            clrType = clrType.GetGenericTypeDefinition();
        }
        XmlQualifiedName xmlQualifiedName = DataContract.GetStableName(clrType);
        if (num > 0)
        {
            string text2 = xmlQualifiedName.Name;
            for (int i = 0; i < num; i++)
            {
                text2 = "ArrayOf" + text2;
            }
            xmlQualifiedName = new XmlQualifiedName(text2, DataContract.GetCollectionNamespace(xmlQualifiedName.Namespace));
        }
        XmlElement xmlElement = XmlDoc.CreateElement(elementName, elementNs);
        XmlAttribute xmlAttribute = XmlDoc.CreateAttribute("Name");
        xmlAttribute.Value = ((array != null) ? XmlConvert.DecodeName(xmlQualifiedName.Name) : xmlQualifiedName.Name);
        xmlElement.Attributes.Append(xmlAttribute);
        XmlAttribute xmlAttribute2 = XmlDoc.CreateAttribute("Namespace");
        xmlAttribute2.Value = xmlQualifiedName.Namespace;
        xmlElement.Attributes.Append(xmlAttribute2);
        if (array != null)
        {
            int num4 = 0;
            int num5 = 0;
            foreach (int item in list)
            {
                int num6 = 0;
                while (num6 < item)
                {
                    XmlElement xmlElement2 = ExportGenericInfo(array[num4], "GenericParameter", "http://schemas.microsoft.com/2003/10/Serialization/");
                    if (num5 > 0)
                    {
                        XmlAttribute xmlAttribute3 = XmlDoc.CreateAttribute("NestedLevel");
                        xmlAttribute3.Value = num5.ToString(CultureInfo.InvariantCulture);
                        xmlElement2.Attributes.Append(xmlAttribute3);
                    }
                    xmlElement.AppendChild(xmlElement2);
                    num6++;
                    num4++;
                }
                num5++;
            }
            if (list[num5 - 1] == 0)
            {
                XmlAttribute xmlAttribute4 = XmlDoc.CreateAttribute("NestedLevel");
                xmlAttribute4.Value = list.Count.ToString(CultureInfo.InvariantCulture);
                xmlElement.Attributes.Append(xmlAttribute4);
            }
        }
        return xmlElement;
    }
References System.array, System.Xml.XmlDocument.CreateAttribute(), System.Xml.XmlDocument.CreateElement(), System.Xml.XmlConvert.DecodeName(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.DataContract.GetBuiltInDataContract(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetCollectionNamespace(), System.Runtime.Serialization.DataContract.GetDataContractNameForGenericName(), System.Runtime.Serialization.DataContract.GetStableName(), System.Globalization.CultureInfo.InvariantCulture, System.Runtime.Serialization.CollectionDataContract.IsCollection(), System.Runtime.Serialization.CollectionDataContract.IsCollectionDataContract(), System.item, System.list, System.text, and System.Runtime.Serialization.SchemaExporter.XmlDoc.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), and System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract().