Terraria: System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract
ExportISerializableDataContract()
void System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract (ClassDataContract dataContract, XmlSchema schema) inline private
Definition at line 652 of file SchemaExporter.cs.
    {
        XmlSchemaComplexType xmlSchemaComplexType = new XmlSchemaComplexType();
        xmlSchemaComplexType.Name = dataContract.StableName.Name;
        schema.Items.Add(xmlSchemaComplexType);
        XmlElement xmlElement = null;
        if (dataContract.UnderlyingType.IsGenericType)
        {
            xmlElement = ExportGenericInfo(dataContract.UnderlyingType, "GenericType", "http://schemas.microsoft.com/2003/10/Serialization/");
        }
        XmlElement xmlElement2 = null;
        if (dataContract.BaseContract != null)
        {
            CreateTypeContent(xmlSchemaComplexType, dataContract.BaseContract.StableName, schema);
        }
        else
        {
            schema.Namespaces.Add("ser", "http://schemas.microsoft.com/2003/10/Serialization/");
            xmlSchemaComplexType.Particle = ISerializableSequence;
            XmlSchemaAttribute iSerializableFactoryTypeAttribute = ISerializableFactoryTypeAttribute;
            xmlSchemaComplexType.Attributes.Add(iSerializableFactoryTypeAttribute);
            SchemaHelper.AddSchemaImport(ISerializableFactoryTypeAttribute.RefName.Namespace, schema);
            if (dataContract.IsValueType)
            {
                xmlElement2 = GetAnnotationMarkup(IsValueTypeName, XmlConvert.ToString(dataContract.IsValueType), schema);
            }
        }
        xmlSchemaComplexType.Annotation = GetSchemaAnnotation(xmlElement, ExportSurrogateData(dataContract), xmlElement2);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.SchemaHelper.AddSchemaImport(), System.Runtime.Serialization.SchemaExporter.CreateTypeContent(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Runtime.Serialization.SchemaExporter.ExportSurrogateData(), System.Runtime.Serialization.SchemaExporter.GetAnnotationMarkup(), System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation(), System.Runtime.Serialization.SchemaExporter.ISerializableFactoryTypeAttribute, System.Runtime.Serialization.SchemaExporter.ISerializableSequence, System.Runtime.Serialization.SchemaExporter.IsValueTypeName, and System.Xml.XmlConvert.ToString().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportDataContract().