Terraria: System.Runtime.Serialization.SchemaExporter.AddReferenceAttributes
AddReferenceAttributes()
void System.Runtime.Serialization.SchemaExporter.AddReferenceAttributes (XmlSchemaObjectCollection attributes, XmlSchema schema) inline private
Definition at line 377 of file SchemaExporter.cs.
    {
        SchemaHelper.AddSchemaImport("http://schemas.microsoft.com/2003/10/Serialization/", schema);
        schema.Namespaces.Add("ser", "http://schemas.microsoft.com/2003/10/Serialization/");
        attributes.Add(IdAttribute);
        attributes.Add(RefAttribute);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.XmlSchemaObjectCollection.Add(), System.Runtime.Serialization.SchemaHelper.AddSchemaImport(), System.Runtime.Serialization.SchemaExporter.IdAttribute, and System.Runtime.Serialization.SchemaExporter.RefAttribute.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), and System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract().