Terraria: System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation
GetSchemaAnnotation() [2/2]
XmlSchemaAnnotation System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation (XmlQualifiedName annotationQualifiedName, string innerText, XmlSchema schema) inline private
Definition at line 985 of file SchemaExporter.cs.
    {
        XmlSchemaAnnotation xmlSchemaAnnotation = new XmlSchemaAnnotation();
        XmlSchemaAppInfo xmlSchemaAppInfo = new XmlSchemaAppInfo();
        XmlElement annotationMarkup = GetAnnotationMarkup(annotationQualifiedName, innerText, schema);
        xmlSchemaAppInfo.Markup = new XmlNode[1] { annotationMarkup };
        xmlSchemaAnnotation.Items.Add(xmlSchemaAppInfo);
        return xmlSchemaAnnotation;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.SchemaExporter.GetAnnotationMarkup().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract(), System.Runtime.Serialization.SchemaExporter.ExportEnumDataContract(), System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract(), System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), and System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod().