Terraria: System.Runtime.Serialization.SchemaExporter.ExportDataContract
ExportDataContract()
void System.Runtime.Serialization.SchemaExporter.ExportDataContract (DataContract dataContract) inline private
Definition at line 261 of file SchemaExporter.cs.
    {
        if (dataContract.IsBuiltInDataContract)
        {
            return;
        }
        if (dataContract is XmlDataContract)
        {
            ExportXmlDataContract((XmlDataContract)dataContract);
            return;
        }
        XmlSchema schema = GetSchema(dataContract.StableName.Namespace);
        if (dataContract is ClassDataContract)
        {
            ClassDataContract classDataContract = (ClassDataContract)dataContract;
            if (classDataContract.IsISerializable)
            {
                ExportISerializableDataContract(classDataContract, schema);
            }
            else
            {
                ExportClassDataContract(classDataContract, schema);
            }
        }
        else if (dataContract is CollectionDataContract)
        {
            ExportCollectionDataContract((CollectionDataContract)dataContract, schema);
        }
        else if (dataContract is EnumDataContract)
        {
            ExportEnumDataContract((EnumDataContract)dataContract, schema);
        }
        ExportTopLevelElement(dataContract, schema);
        Schemas.Reprocess(schema);
    }
References System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract(), System.Runtime.Serialization.SchemaExporter.ExportEnumDataContract(), System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract(), System.Runtime.Serialization.SchemaExporter.ExportTopLevelElement(), System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), System.Runtime.Serialization.SchemaExporter.GetSchema(), System.Xml.Schema.XmlSchemaSet.Reprocess(), and System.Runtime.Serialization.SchemaExporter.Schemas.
Referenced by System.Runtime.Serialization.SchemaExporter.Export().