Terraria: System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod
InvokeGetSchemaMethod()
static void System.Runtime.Serialization.SchemaExporter.InvokeGetSchemaMethod ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type clrType, XmlSchemaSet schemas, XmlQualifiedName stableName) inline static private
Definition at line 878 of file SchemaExporter.cs.
    {
        IXmlSerializable xmlSerializable = (IXmlSerializable)Activator.CreateInstance(clrType);
        XmlSchema schema = xmlSerializable.GetSchema();
        if (schema == null)
        {
            AddDefaultDatasetType(schemas, stableName.Name, stableName.Namespace);
            return;
        }
        if (schema.Id == null || schema.Id.Length == 0)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidReturnSchemaOnGetSchemaMethod, DataContract.GetClrTypeFullName(clrType))));
        }
        AddDefaultTypedDatasetType(schemas, schema, stableName.Name, stableName.Namespace);
    }
References System.Runtime.Serialization.SchemaExporter.AddDefaultDatasetType(), System.Runtime.Serialization.SchemaExporter.AddDefaultTypedDatasetType(), System.Activator.CreateInstance(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidReturnSchemaOnGetSchemaMethod, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract().