Terraria: System.Threading.SynchronizationContext.Wait
Wait()
virtual int System.Threading.SynchronizationContext.Wait (IntPtr[] waitHandles, bool waitAll, int millisecondsTimeout) inline virtual
Definition at line 46 of file SynchronizationContext.cs.
    {
        return WaitHelper(waitHandles, waitAll, millisecondsTimeout);
    }
References System.millisecondsTimeout, and System.Threading.SynchronizationContext.WaitHelper().
Referenced by System.Threading.SynchronizationContext.InvokeWaitMethodHelper(), System.Threading.WaitHandle.WaitAnyMultiple(), System.Threading.WaitHandle.WaitMultiple(), and System.Threading.WaitHandle.WaitOneNoCheck().