Terraria: System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo
GetXmlTypeInfo()
static void System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo (Type type, out XmlQualifiedName stableName, out XmlSchemaType xsdType, out bool hasRoot) inline static package
Definition at line 765 of file SchemaExporter.cs.
    {
        if (!IsSpecialXmlType(type, out stableName, out xsdType, out hasRoot))
        {
            XmlSchemaSet xmlSchemaSet = new XmlSchemaSet();
            xmlSchemaSet.XmlResolver = null;
            InvokeSchemaProviderMethod(type, xmlSchemaSet, out stableName, out xsdType, out hasRoot);
            if (stableName.Name == null || stableName.Name.Length == 0)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidXmlDataContractName, DataContract.GetClrTypeFullName(type))));
            }
        }
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.SR.InvalidXmlDataContractName, System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod(), System.Runtime.Serialization.SchemaExporter.IsSpecialXmlType(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.type.
Referenced by System.Runtime.Serialization.XmlDataContract.XmlDataContractCriticalHelper.XmlDataContractCriticalHelper(), and System.Runtime.Serialization.DataContract.TryGetBuiltInXmlAndArrayTypeStableName().