Terraria: System.Runtime.Serialization.SchemaExporter.IsSpecialXmlType
IsSpecialXmlType()
static bool System.Runtime.Serialization.SchemaExporter.IsSpecialXmlType (Type type, [NotNullWhen(true)] out XmlQualifiedName typeName, [NotNullWhen(true)] out XmlSchemaType xsdType, out bool hasRoot) inline static package
Definition at line 929 of file SchemaExporter.cs.
    {
        xsdType = null;
        hasRoot = true;
        if (type == Globals.TypeOfXmlElement || type == Globals.TypeOfXmlNodeArray)
        {
            string text = null;
            if (type == Globals.TypeOfXmlElement)
            {
                xsdType = CreateAnyElementType();
                text = "XmlElement";
                hasRoot = false;
            }
            else
            {
                xsdType = CreateAnyType();
                text = "ArrayOfXmlNode";
                hasRoot = true;
            }
            typeName = new XmlQualifiedName(text, DataContract.GetDefaultStableNamespace(type));
            return true;
        }
        typeName = null;
        return false;
    }
References System.Runtime.Serialization.SchemaExporter.CreateAnyElementType(), System.Runtime.Serialization.SchemaExporter.CreateAnyType(), System.Runtime.Serialization.DataContract.GetDefaultStableNamespace(), System.text, System.type, System.Runtime.Serialization.Globals.TypeOfXmlElement, and System.Runtime.Serialization.Globals.TypeOfXmlNodeArray.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), and System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo().