Terraria: System.Runtime.Serialization.SchemaExporter.Export
Export()
void System.Runtime.Serialization.SchemaExporter.Export () inline package
Definition at line 221 of file SchemaExporter.cs.
    {
        try
        {
            ExportSerializationSchema();
            foreach (KeyValuePair<XmlQualifiedName, DataContract> item in _dataContractSet)
            {
                DataContract value = item.Value;
                if (!_dataContractSet.IsContractProcessed(value))
                {
                    ExportDataContract(value);
                    _dataContractSet.SetContractProcessed(value);
                }
            }
        }
        finally
        {
            _xmlDoc = null;
            _dataContractSet = null;
        }
    }
References System.Runtime.Serialization.SchemaExporter._dataContractSet, System.Runtime.Serialization.SchemaExporter._xmlDoc, System.Runtime.Serialization.SchemaExporter.ExportDataContract(), System.Runtime.Serialization.SchemaExporter.ExportSerializationSchema(), System.Runtime.Serialization.DataContractSet.IsContractProcessed(), System.item, System.Runtime.Serialization.DataContractSet.SetContractProcessed(), and System.value.