Terraria: System.Runtime.Serialization.SchemaExporter.SetElementType
SetElementType()
void System.Runtime.Serialization.SchemaExporter.SetElementType (XmlSchemaElement element, DataContract dataContract, XmlSchema schema) inline private
Definition at line 385 of file SchemaExporter.cs.
    {
        if (dataContract is XmlDataContract { IsAnonymous: not false } xmlDataContract)
        {
            element.SchemaType = xmlDataContract.XsdType;
            return;
        }
        element.SchemaTypeName = dataContract.StableName;
        if (element.SchemaTypeName.Namespace.Equals("http://schemas.microsoft.com/2003/10/Serialization/"))
        {
            schema.Namespaces.Add("ser", "http://schemas.microsoft.com/2003/10/Serialization/");
        }
        SchemaHelper.AddSchemaImport(dataContract.StableName.Namespace, schema);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Runtime.Serialization.SchemaHelper.AddSchemaImport(), System.Runtime.Serialization.Dictionary, System.Xml.XmlQualifiedName.Namespace, and System.Xml.Schema.XmlSchemaElement.SchemaTypeName.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportCollectionDataContract(), and System.Runtime.Serialization.SchemaExporter.ExportTopLevelElement().