Terraria: System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod
InvokeSchemaProviderMethod()
static bool System.Runtime.Serialization.SchemaExporter.InvokeSchemaProviderMethod (Type clrType, XmlSchemaSet schemas, out XmlQualifiedName stableName, out XmlSchemaType xsdType, out bool hasRoot) inline static private
Definition at line 780 of file SchemaExporter.cs.
    {
        xsdType = null;
        hasRoot = true;
        object[] customAttributes = clrType.GetCustomAttributes(Globals.TypeOfXmlSchemaProviderAttribute, inherit: false);
        if (customAttributes == null || customAttributes.Length == 0)
        {
            stableName = DataContract.GetDefaultStableName(clrType);
            return false;
        }
        XmlSchemaProviderAttribute xmlSchemaProviderAttribute = (XmlSchemaProviderAttribute)customAttributes[0];
        if (xmlSchemaProviderAttribute.IsAny)
        {
            xsdType = CreateAnyElementType();
            hasRoot = false;
        }
        string methodName = xmlSchemaProviderAttribute.MethodName;
        if (methodName == null || methodName.Length == 0)
        {
            if (!xmlSchemaProviderAttribute.IsAny)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidGetSchemaMethod, DataContract.GetClrTypeFullName(clrType))));
            }
            stableName = DataContract.GetDefaultStableName(clrType);
        }
        else
        {
            MethodInfo method = clrType.GetMethod(methodName, BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic, new Type[1] { typeof(XmlSchemaSet) });
            if (method == null)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.MissingGetSchemaMethod, DataContract.GetClrTypeFullName(clrType), methodName)));
            }
            if (!Globals.TypeOfXmlQualifiedName.IsAssignableFrom(method.ReturnType) && !Globals.TypeOfXmlSchemaType.IsAssignableFrom(method.ReturnType))
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidReturnTypeOnGetSchemaMethod, DataContract.GetClrTypeFullName(clrType), methodName, DataContract.GetClrTypeFullName(method.ReturnType), DataContract.GetClrTypeFullName(Globals.TypeOfXmlQualifiedName), typeof(XmlSchemaType))));
            }
            object obj = method.Invoke(null, new object[1] { schemas });
            if (xmlSchemaProviderAttribute.IsAny)
            {
                if (obj != null)
                {
                    throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.InvalidNonNullReturnValueByIsAny, DataContract.GetClrTypeFullName(clrType), methodName)));
                }
                stableName = DataContract.GetDefaultStableName(clrType);
            }
            else if (obj == null)
            {
                xsdType = CreateAnyElementType();
                hasRoot = false;
                stableName = DataContract.GetDefaultStableName(clrType);
            }
            else if (obj is XmlSchemaType xmlSchemaType)
            {
                string localName = xmlSchemaType.Name;
                string ns = null;
                if (localName == null || localName.Length == 0)
                {
                    DataContract.GetDefaultStableName(DataContract.GetClrTypeFullName(clrType), out localName, out ns);
                    stableName = new XmlQualifiedName(localName, ns);
                    xmlSchemaType.Annotation = GetSchemaAnnotation(ExportActualType(stableName, new XmlDocument()));
                    xsdType = xmlSchemaType;
                }
                else
                {
                    foreach (XmlSchema item in schemas.Schemas())
                    {
                        foreach (XmlSchemaObject item2 in item.Items)
{
                            if (item2 == xmlSchemaType)
{
                                ns = item.TargetNamespace;
                                if (ns == null)
{
                                    ns = string.Empty;
                                }
                                break;
                            }
                        }
                        if (ns != null)
{
                            break;
                        }
                    }
                    if (ns == null)
                    {
                        throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidDataContractException(System.SR.Format(System.SR.MissingSchemaType, localName, DataContract.GetClrTypeFullName(clrType))));
                    }
                    stableName = new XmlQualifiedName(localName, ns);
                }
            }
            else
            {
                stableName = (XmlQualifiedName)obj;
            }
        }
        return true;
    }
References System.Runtime.Serialization.SchemaExporter.CreateAnyElementType(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.SchemaExporter.ExportActualType(), System.SR.Format(), System.Runtime.Serialization.DataContract.GetClrTypeFullName(), System.Runtime.Serialization.DataContract.GetDefaultStableName(), System.Runtime.Serialization.SchemaExporter.GetSchemaAnnotation(), System.SR.InvalidGetSchemaMethod, System.SR.InvalidNonNullReturnValueByIsAny, System.SR.InvalidReturnTypeOnGetSchemaMethod, System.item, System.SR.MissingGetSchemaMethod, System.SR.MissingSchemaType, System.obj, System.Xml.Schema.XmlSchemaSet.Schemas(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Runtime.Serialization.Globals.TypeOfXmlQualifiedName, System.Runtime.Serialization.Globals.TypeOfXmlSchemaProviderAttribute, and System.Runtime.Serialization.Globals.TypeOfXmlSchemaType.
Referenced by System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), and System.Runtime.Serialization.SchemaExporter.GetXmlTypeInfo().