Terraria: System.Numerics.Matrix4x4.CreateConstrainedBillboard
CreateConstrainedBillboard()
static Matrix4x4 System.Numerics.Matrix4x4.CreateConstrainedBillboard (Vector3 objectPosition, Vector3 cameraPosition, Vector3 rotateAxis, Vector3 cameraForwardVector, Vector3 objectForwardVector) inline static
Definition at line 377 of file Matrix4x4.cs.
    {
        Vector3 left = objectPosition - cameraPosition;
        float num = left.LengthSquared();
        left = ((!(num < 0.0001f)) ? Vector3.Multiply(left, 1f / MathF.Sqrt(num)) : (-cameraForwardVector));
        Vector3 vector = rotateAxis;
        float x = Vector3.Dot(rotateAxis, left);
        Vector3 vector3;
        Vector3 vector2;
        if (MathF.Abs(x) > 0.99825466f)
        {
            vector2 = objectForwardVector;
            x = Vector3.Dot(rotateAxis, vector2);
            if (MathF.Abs(x) > 0.99825466f)
            {
                vector2 = ((MathF.Abs(rotateAxis.Z) > 0.99825466f) ? new Vector3(1f, 0f, 0f) : new Vector3(0f, 0f, -1f));
            }
            vector3 = Vector3.Normalize(Vector3.Cross(rotateAxis, vector2));
            vector2 = Vector3.Normalize(Vector3.Cross(vector3, rotateAxis));
        }
        else
        {
            vector3 = Vector3.Normalize(Vector3.Cross(rotateAxis, left));
            vector2 = Vector3.Normalize(Vector3.Cross(vector3, vector));
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = vector3.X;
        result.M12 = vector3.Y;
        result.M13 = vector3.Z;
        result.M14 = 0f;
        result.M21 = vector.X;
        result.M22 = vector.Y;
        result.M23 = vector.Z;
        result.M24 = 0f;
        result.M31 = vector2.X;
        result.M32 = vector2.Y;
        result.M33 = vector2.Z;
        result.M34 = 0f;
        result.M41 = objectPosition.X;
        result.M42 = objectPosition.Y;
        result.M43 = objectPosition.Z;
        result.M44 = 1f;
        return result;
    }
References System.MathF.Abs(), System.Numerics.Vector3.Cross(), System.Numerics.Vector3.Dot(), System.Numerics.Vector3.LengthSquared(), System.Numerics.Vector3.Multiply(), System.Numerics.Vector3.Normalize(), System.MathF.Sqrt(), System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.