Terraria: System.Numerics.Matrix4x4.Decompose
Decompose()
static unsafe bool System.Numerics.Matrix4x4.Decompose (Matrix4x4 matrix, out Vector3 scale, out Quaternion rotation, out Vector3 translation) inline static
Definition at line 1085 of file Matrix4x4.cs.
    {
        bool result = true;
        fixed (Vector3* ptr = &scale)
        {
            float* ptr2 = (float*)ptr;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out VectorBasis vectorBasis);
            Vector3** ptr3 = (Vector3**)(&vectorBasis);
            Matrix4x4 identity = Identity;
            CanonicalBasis canonicalBasis = default(CanonicalBasis);
            Vector3* ptr4 = &canonicalBasis.Row0;
            canonicalBasis.Row0 = new Vector3(1f, 0f, 0f);
            canonicalBasis.Row1 = new Vector3(0f, 1f, 0f);
            canonicalBasis.Row2 = new Vector3(0f, 0f, 1f);
            translation = new Vector3(matrix.M41, matrix.M42, matrix.M43);
            *ptr3 = (Vector3*)(&identity.M11);
            ptr3[1] = (Vector3*)(&identity.M21);
            ptr3[2] = (Vector3*)(&identity.M31);
            *(*ptr3) = new Vector3(matrix.M11, matrix.M12, matrix.M13);
            *ptr3[1] = new Vector3(matrix.M21, matrix.M22, matrix.M23);
            *ptr3[2] = new Vector3(matrix.M31, matrix.M32, matrix.M33);
            scale.X = (*ptr3)->Length();
            scale.Y = ptr3[1]->Length();
            scale.Z = ptr3[2]->Length();
            float num = *ptr2;
            float num2 = ptr2[1];
            float num3 = ptr2[2];
            uint num4;
            uint num5;
            uint num6;
            if (num < num2)
            {
                if (num2 < num3)
                {
                    num4 = 2u;
                    num5 = 1u;
                    num6 = 0u;
                }
                else
                {
                    num4 = 1u;
                    if (num < num3)
                    {
                        num5 = 2u;
                        num6 = 0u;
                    }
                    else
                    {
                        num5 = 0u;
                        num6 = 2u;
                    }
                }
            }
            else if (num < num3)
            {
                num4 = 2u;
                num5 = 0u;
                num6 = 1u;
            }
            else
            {
                num4 = 0u;
                if (num2 < num3)
                {
                    num5 = 2u;
                    num6 = 1u;
                }
                else
                {
                    num5 = 1u;
                    num6 = 2u;
                }
            }
            if (ptr2[num4] < 0.0001f)
            {
                *ptr3[num4] = ptr4[num4];
            }
            *ptr3[num4] = Vector3.Normalize(*ptr3[num4]);
            if (ptr2[num5] < 0.0001f)
            {
                float num7 = MathF.Abs(ptr3[num4]->X);
                float num8 = MathF.Abs(ptr3[num4]->Y);
                float num9 = MathF.Abs(ptr3[num4]->Z);
                uint num10 = ((num7 < num8) ? ((!(num8 < num9)) ? ((!(num7 < num9)) ? 2u : 0u) : 0u) : ((num7 < num9) ? 1u : ((num8 < num9) ? 1u : 2u)));
                *ptr3[num5] = Vector3.Cross(*ptr3[num4], ptr4[num10]);
            }
            *ptr3[num5] = Vector3.Normalize(*ptr3[num5]);
            if (ptr2[num6] < 0.0001f)
            {
                *ptr3[num6] = Vector3.Cross(*ptr3[num4], *ptr3[num5]);
            }
            *ptr3[num6] = Vector3.Normalize(*ptr3[num6]);
            float num11 = identity.GetDeterminant();
            if (num11 < 0f)
            {
                ptr2[num4] = 0f - ptr2[num4];
                *ptr3[num4] = -(*ptr3[num4]);
                num11 = 0f - num11;
            }
            num11 -= 1f;
            num11 *= num11;
            if (0.0001f < num11)
            {
                rotation = Quaternion.Identity;
                result = false;
            }
            else
            {
                rotation = Quaternion.CreateFromRotationMatrix(identity);
            }
        }
        return result;
    }
References System.MathF.Abs(), System.Numerics.Quaternion.CreateFromRotationMatrix(), System.Numerics.Vector3.Cross(), System.Numerics.Matrix4x4.GetDeterminant(), System.Numerics.Matrix4x4.Identity, System.Numerics.Quaternion.Identity, System.Numerics.Vector3.Length(), System.Numerics.Matrix4x4.M11, System.Numerics.Matrix4x4.M12, System.Numerics.Matrix4x4.M13, System.Numerics.Matrix4x4.M21, System.Numerics.Matrix4x4.M22, System.Numerics.Matrix4x4.M23, System.Numerics.Matrix4x4.M31, System.Numerics.Matrix4x4.M32, System.Numerics.Matrix4x4.M33, System.Numerics.Matrix4x4.M41, System.Numerics.Matrix4x4.M42, System.Numerics.Matrix4x4.M43, System.Numerics.Vector3.Normalize(), System.Numerics.Matrix4x4.CanonicalBasis.Row0, System.X, System.Y, and System.Z.