Terraria: System.Numerics.Matrix4x4.operator-
operator-() [1/2]
static unsafe Matrix4x4 System.Numerics.Matrix4x4.operator- (Matrix4x4 value) inline static
Definition at line 310 of file Matrix4x4.cs.
    {
        if (AdvSimd.IsSupported)
        {
        }
        if (Sse.IsSupported)
        {
            Vector128<float> zero = Vector128<float>.Zero;
            Sse.Store(&value.M11, Sse.Subtract(zero, Sse.LoadVector128(&value.M11)));
            Sse.Store(&value.M21, Sse.Subtract(zero, Sse.LoadVector128(&value.M21)));
            Sse.Store(&value.M31, Sse.Subtract(zero, Sse.LoadVector128(&value.M31)));
            Sse.Store(&value.M41, Sse.Subtract(zero, Sse.LoadVector128(&value.M41)));
            return value;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = 0f - value.M11;
        result.M12 = 0f - value.M12;
        result.M13 = 0f - value.M13;
        result.M14 = 0f - value.M14;
        result.M21 = 0f - value.M21;
        result.M22 = 0f - value.M22;
        result.M23 = 0f - value.M23;
        result.M24 = 0f - value.M24;
        result.M31 = 0f - value.M31;
        result.M32 = 0f - value.M32;
        result.M33 = 0f - value.M33;
        result.M34 = 0f - value.M34;
        result.M41 = 0f - value.M41;
        result.M42 = 0f - value.M42;
        result.M43 = 0f - value.M43;
        result.M44 = 0f - value.M44;
        return result;
    }
References System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse.LoadVector128(), System.Runtime.Intrinsics.X86.Sse.Store(), System.Runtime.Intrinsics.X86.Sse.Subtract(), System.value, and System.Runtime.Intrinsics.Vector128< T >.Zero.