Terraria: System.Numerics.Matrix4x4.operator*
operator*() [1/2]
static unsafe Matrix4x4 System.Numerics.Matrix4x4.operator* (Matrix4x4 value1, float value2) inline static
Definition at line 243 of file Matrix4x4.cs.
    {
        if (AdvSimd.IsSupported)
        {
        }
        if (Sse.IsSupported)
        {
            Vector128<float> right = Vector128.Create(value2);
            Sse.Store(&value1.M11, Sse.Multiply(Sse.LoadVector128(&value1.M11), right));
            Sse.Store(&value1.M21, Sse.Multiply(Sse.LoadVector128(&value1.M21), right));
            Sse.Store(&value1.M31, Sse.Multiply(Sse.LoadVector128(&value1.M31), right));
            Sse.Store(&value1.M41, Sse.Multiply(Sse.LoadVector128(&value1.M41), right));
            return value1;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = value1.M11 * value2;
        result.M12 = value1.M12 * value2;
        result.M13 = value1.M13 * value2;
        result.M14 = value1.M14 * value2;
        result.M21 = value1.M21 * value2;
        result.M22 = value1.M22 * value2;
        result.M23 = value1.M23 * value2;
        result.M24 = value1.M24 * value2;
        result.M31 = value1.M31 * value2;
        result.M32 = value1.M32 * value2;
        result.M33 = value1.M33 * value2;
        result.M34 = value1.M34 * value2;
        result.M41 = value1.M41 * value2;
        result.M42 = value1.M42 * value2;
        result.M43 = value1.M43 * value2;
        result.M44 = value1.M44 * value2;
        return result;
    }
References System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse.LoadVector128(), System.Numerics.Matrix4x4.M11, System.Numerics.Matrix4x4.M21, System.Numerics.Matrix4x4.M31, System.Numerics.Matrix4x4.M41, System.Runtime.Intrinsics.X86.Sse.Multiply(), and System.Runtime.Intrinsics.X86.Sse.Store().