Terraria: System.Numerics.Matrix4x4.CreateBillboard
CreateBillboard()
static Matrix4x4 System.Numerics.Matrix4x4.CreateBillboard (Vector3 objectPosition, Vector3 cameraPosition, Vector3 cameraUpVector, Vector3 cameraForwardVector) inline static
Definition at line 350 of file Matrix4x4.cs.
    {
        Vector3 left = objectPosition - cameraPosition;
        float num = left.LengthSquared();
        left = ((!(num < 0.0001f)) ? Vector3.Multiply(left, 1f / MathF.Sqrt(num)) : (-cameraForwardVector));
        Vector3 vector = Vector3.Normalize(Vector3.Cross(cameraUpVector, left));
        Vector3 vector2 = Vector3.Cross(left, vector);
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = vector.X;
        result.M12 = vector.Y;
        result.M13 = vector.Z;
        result.M14 = 0f;
        result.M21 = vector2.X;
        result.M22 = vector2.Y;
        result.M23 = vector2.Z;
        result.M24 = 0f;
        result.M31 = left.X;
        result.M32 = left.Y;
        result.M33 = left.Z;
        result.M34 = 0f;
        result.M41 = objectPosition.X;
        result.M42 = objectPosition.Y;
        result.M43 = objectPosition.Z;
        result.M44 = 1f;
        return result;
    }
References System.Numerics.Vector3.Cross(), System.Numerics.Vector3.LengthSquared(), System.Numerics.Vector3.Multiply(), System.Numerics.Vector3.Normalize(), System.MathF.Sqrt(), System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.