Terraria: System.Numerics.Matrix4x4.operator+
operator+()
static unsafe Matrix4x4 System.Numerics.Matrix4x4.operator+ (Matrix4x4 value1, Matrix4x4 value2) inline static
Definition at line 133 of file Matrix4x4.cs.
    {
        if (AdvSimd.IsSupported)
        {
        }
        if (Sse.IsSupported)
        {
            Sse.Store(&value1.M11, Sse.Add(Sse.LoadVector128(&value1.M11), Sse.LoadVector128(&value2.M11)));
            Sse.Store(&value1.M21, Sse.Add(Sse.LoadVector128(&value1.M21), Sse.LoadVector128(&value2.M21)));
            Sse.Store(&value1.M31, Sse.Add(Sse.LoadVector128(&value1.M31), Sse.LoadVector128(&value2.M31)));
            Sse.Store(&value1.M41, Sse.Add(Sse.LoadVector128(&value1.M41), Sse.LoadVector128(&value2.M41)));
            return value1;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = value1.M11 + value2.M11;
        result.M12 = value1.M12 + value2.M12;
        result.M13 = value1.M13 + value2.M13;
        result.M14 = value1.M14 + value2.M14;
        result.M21 = value1.M21 + value2.M21;
        result.M22 = value1.M22 + value2.M22;
        result.M23 = value1.M23 + value2.M23;
        result.M24 = value1.M24 + value2.M24;
        result.M31 = value1.M31 + value2.M31;
        result.M32 = value1.M32 + value2.M32;
        result.M33 = value1.M33 + value2.M33;
        result.M34 = value1.M34 + value2.M34;
        result.M41 = value1.M41 + value2.M41;
        result.M42 = value1.M42 + value2.M42;
        result.M43 = value1.M43 + value2.M43;
        result.M44 = value1.M44 + value2.M44;
        return result;
    }
References System.Runtime.Intrinsics.X86.Sse.Add(), System.Runtime.Intrinsics.Arm.AdvSimd.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse.LoadVector128(), System.Numerics.Matrix4x4.M11, System.Numerics.Matrix4x4.M12, System.Numerics.Matrix4x4.M13, System.Numerics.Matrix4x4.M14, System.Numerics.Matrix4x4.M21, System.Numerics.Matrix4x4.M22, System.Numerics.Matrix4x4.M23, System.Numerics.Matrix4x4.M24, System.Numerics.Matrix4x4.M31, System.Numerics.Matrix4x4.M32, System.Numerics.Matrix4x4.M33, System.Numerics.Matrix4x4.M34, System.Numerics.Matrix4x4.M41, System.Numerics.Matrix4x4.M42, System.Numerics.Matrix4x4.M43, System.Numerics.Matrix4x4.M44, and System.Runtime.Intrinsics.X86.Sse.Store().