Terraria: System.Numerics.Matrix4x4.Invert
Invert()
static bool System.Numerics.Matrix4x4.Invert (Matrix4x4 matrix, out Matrix4x4 result) inline static
Definition at line 855 of file Matrix4x4.cs.
    {
        if (Sse.IsSupported)
        {
            return SseImpl(matrix, out result);
        }
        return SoftwareFallback(matrix, out result);
        static bool SoftwareFallback(Matrix4x4 matrix, out Matrix4x4 result)
        {
            float m = matrix.M11;
            float m2 = matrix.M12;
            float m3 = matrix.M13;
            float m4 = matrix.M14;
            float m5 = matrix.M21;
            float m6 = matrix.M22;
            float m7 = matrix.M23;
            float m8 = matrix.M24;
            float m9 = matrix.M31;
            float m10 = matrix.M32;
            float m11 = matrix.M33;
            float m12 = matrix.M34;
            float m13 = matrix.M41;
            float m14 = matrix.M42;
            float m15 = matrix.M43;
            float m16 = matrix.M44;
            float num = m11 * m16 - m12 * m15;
            float num2 = m10 * m16 - m12 * m14;
            float num3 = m10 * m15 - m11 * m14;
            float num4 = m9 * m16 - m12 * m13;
            float num5 = m9 * m15 - m11 * m13;
            float num6 = m9 * m14 - m10 * m13;
            float num7 = m6 * num - m7 * num2 + m8 * num3;
            float num8 = 0f - (m5 * num - m7 * num4 + m8 * num5);
            float num9 = m5 * num2 - m6 * num4 + m8 * num6;
            float num10 = 0f - (m5 * num3 - m6 * num5 + m7 * num6);
            float num11 = m * num7 + m2 * num8 + m3 * num9 + m4 * num10;
            if (MathF.Abs(num11) < float.Epsilon)
            {
                result = new Matrix4x4(float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN);
                return false;
            }
            float num12 = 1f / num11;
            result.M11 = num7 * num12;
            result.M21 = num8 * num12;
            result.M31 = num9 * num12;
            result.M41 = num10 * num12;
            result.M12 = (0f - (m2 * num - m3 * num2 + m4 * num3)) * num12;
            result.M22 = (m * num - m3 * num4 + m4 * num5) * num12;
            result.M32 = (0f - (m * num2 - m2 * num4 + m4 * num6)) * num12;
            result.M42 = (m * num3 - m2 * num5 + m3 * num6) * num12;
            float num13 = m7 * m16 - m8 * m15;
            float num14 = m6 * m16 - m8 * m14;
            float num15 = m6 * m15 - m7 * m14;
            float num16 = m5 * m16 - m8 * m13;
            float num17 = m5 * m15 - m7 * m13;
            float num18 = m5 * m14 - m6 * m13;
            result.M13 = (m2 * num13 - m3 * num14 + m4 * num15) * num12;
            result.M23 = (0f - (m * num13 - m3 * num16 + m4 * num17)) * num12;
            result.M33 = (m * num14 - m2 * num16 + m4 * num18) * num12;
            result.M43 = (0f - (m * num15 - m2 * num17 + m3 * num18)) * num12;
            float num19 = m7 * m12 - m8 * m11;
            float num20 = m6 * m12 - m8 * m10;
            float num21 = m6 * m11 - m7 * m10;
            float num22 = m5 * m12 - m8 * m9;
            float num23 = m5 * m11 - m7 * m9;
            float num24 = m5 * m10 - m6 * m9;
            result.M14 = (0f - (m2 * num19 - m3 * num20 + m4 * num21)) * num12;
            result.M24 = (m * num19 - m3 * num22 + m4 * num23) * num12;
            result.M34 = (0f - (m * num20 - m2 * num22 + m4 * num24)) * num12;
            result.M44 = (m * num21 - m2 * num23 + m3 * num24) * num12;
            return true;
        }
        unsafe static bool SseImpl(Matrix4x4 matrix, out Matrix4x4 result)
        {
            if (!Sse.IsSupported)
            {
                throw new PlatformNotSupportedException();
            }
            Vector128<float> left = Sse.LoadVector128(&matrix.M11);
            Vector128<float> right = Sse.LoadVector128(&matrix.M21);
            Vector128<float> left2 = Sse.LoadVector128(&matrix.M31);
            Vector128<float> right2 = Sse.LoadVector128(&matrix.M41);
            Vector128<float> left3 = Sse.Shuffle(left, right, 68);
            Vector128<float> left4 = Sse.Shuffle(left, right, 238);
            Vector128<float> right3 = Sse.Shuffle(left2, right2, 68);
            Vector128<float> right4 = Sse.Shuffle(left2, right2, 238);
            left = Sse.Shuffle(left3, right3, 136);
            right = Sse.Shuffle(left3, right3, 221);
            left2 = Sse.Shuffle(left4, right4, 136);
            right2 = Sse.Shuffle(left4, right4, 221);
            Vector128<float> left5 = Permute(left2, 80);
            Vector128<float> right5 = Permute(right2, 238);
            Vector128<float> left6 = Permute(left, 80);
            Vector128<float> right6 = Permute(right, 238);
            Vector128<float> left7 = Sse.Shuffle(left2, left, 136);
            Vector128<float> right7 = Sse.Shuffle(right2, right, 221);
            Vector128<float> left8 = Sse.Multiply(left5, right5);
            Vector128<float> left9 = Sse.Multiply(left6, right6);
            Vector128<float> left10 = Sse.Multiply(left7, right7);
            left5 = Permute(left2, 238);
            right5 = Permute(right2, 80);
            left6 = Permute(left, 238);
            right6 = Permute(right, 80);
            left7 = Sse.Shuffle(left2, left, 221);
            right7 = Sse.Shuffle(right2, right, 136);
            left8 = Sse.Subtract(left8, Sse.Multiply(left5, right5));
            left9 = Sse.Subtract(left9, Sse.Multiply(left6, right6));
            left10 = Sse.Subtract(left10, Sse.Multiply(left7, right7));
            right6 = Sse.Shuffle(left8, left10, 93);
            left5 = Permute(right, 73);
            right5 = Sse.Shuffle(right6, left8, 50);
            left6 = Permute(left, 18);
            right6 = Sse.Shuffle(right6, left8, 153);
            Vector128<float> left11 = Sse.Shuffle(left9, left10, 253);
            left7 = Permute(right2, 73);
            right7 = Sse.Shuffle(left11, left9, 50);
            Vector128<float> left12 = Permute(left2, 18);
            left11 = Sse.Shuffle(left11, left9, 153);
            Vector128<float> left13 = Sse.Multiply(left5, right5);
            Vector128<float> left14 = Sse.Multiply(left6, right6);
            Vector128<float> left15 = Sse.Multiply(left7, right7);
            Vector128<float> left16 = Sse.Multiply(left12, left11);
            right6 = Sse.Shuffle(left8, left10, 4);
            left5 = Permute(right, 158);
            right5 = Sse.Shuffle(left8, right6, 147);
            left6 = Permute(left, 123);
            right6 = Sse.Shuffle(left8, right6, 38);
            left11 = Sse.Shuffle(left9, left10, 164);
            left7 = Permute(right2, 158);
            right7 = Sse.Shuffle(left9, left11, 147);
            left12 = Permute(left2, 123);
            left11 = Sse.Shuffle(left9, left11, 38);
            left13 = Sse.Subtract(left13, Sse.Multiply(left5, right5));
            left14 = Sse.Subtract(left14, Sse.Multiply(left6, right6));
            left15 = Sse.Subtract(left15, Sse.Multiply(left7, right7));
            left16 = Sse.Subtract(left16, Sse.Multiply(left12, left11));
            left5 = Permute(right, 51);
            right5 = Sse.Shuffle(left8, left10, 74);
            right5 = Permute(right5, 44);
            left6 = Permute(left, 141);
            right6 = Sse.Shuffle(left8, left10, 76);
            right6 = Permute(right6, 147);
            left7 = Permute(right2, 51);
            right7 = Sse.Shuffle(left9, left10, 234);
            right7 = Permute(right7, 44);
            left12 = Permute(left2, 141);
            left11 = Sse.Shuffle(left9, left10, 236);
            left11 = Permute(left11, 147);
            left5 = Sse.Multiply(left5, right5);
            left6 = Sse.Multiply(left6, right6);
            left7 = Sse.Multiply(left7, right7);
            left12 = Sse.Multiply(left12, left11);
            Vector128<float> right8 = Sse.Subtract(left13, left5);
            left13 = Sse.Add(left13, left5);
            Vector128<float> right9 = Sse.Add(left14, left6);
            left14 = Sse.Subtract(left14, left6);
            Vector128<float> right10 = Sse.Subtract(left15, left7);
            left15 = Sse.Add(left15, left7);
            Vector128<float> right11 = Sse.Add(left16, left12);
            left16 = Sse.Subtract(left16, left12);
            left13 = Sse.Shuffle(left13, right8, 216);
            left14 = Sse.Shuffle(left14, right9, 216);
            left15 = Sse.Shuffle(left15, right10, 216);
            left16 = Sse.Shuffle(left16, right11, 216);
            left13 = Permute(left13, 216);
            left14 = Permute(left14, 216);
            left15 = Permute(left15, 216);
            left16 = Permute(left16, 216);
            right3 = left;
            float num25 = Vector4.Dot(left13.AsVector4(), right3.AsVector4());
            if (MathF.Abs(num25) < float.Epsilon)
            {
                result = new Matrix4x4(float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN, float.NaN);
                return false;
            }
            Vector128<float> left17 = Vector128.Create(1f);
            Vector128<float> right12 = Vector128.Create(num25);
            right12 = Sse.Divide(left17, right12);
            left = Sse.Multiply(left13, right12);
            right = Sse.Multiply(left14, right12);
            left2 = Sse.Multiply(left15, right12);
            right2 = Sse.Multiply(left16, right12);
            Unsafe.SkipInit<Matrix4x4>(out result);
            ref Vector128<float> reference = ref Unsafe.As<Matrix4x4, Vector128<float>>(ref result);
            reference = left;
            Unsafe.Add(ref reference, 1) = right;
            Unsafe.Add(ref reference, 2) = left2;
            Unsafe.Add(ref reference, 3) = right2;
            return true;
        }
    }
References System.Numerics.Matrix4x4.Matrix4x4(), System.MathF.Abs(), System.Runtime.Intrinsics.X86.Sse.Add(), System.Runtime.Intrinsics.Vector128< T >.AsVector4(), System.Runtime.Intrinsics.Vector128< T >.Create(), System.Runtime.Intrinsics.X86.Sse.Divide(), System.Numerics.Vector4.Dot(), System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse.LoadVector128(), System.Numerics.Matrix4x4.M11, System.Numerics.Matrix4x4.M12, System.Numerics.Matrix4x4.M13, System.Numerics.Matrix4x4.M14, System.Numerics.Matrix4x4.M21, System.Numerics.Matrix4x4.M22, System.Numerics.Matrix4x4.M23, System.Numerics.Matrix4x4.M24, System.Numerics.Matrix4x4.M31, System.Numerics.Matrix4x4.M32, System.Numerics.Matrix4x4.M33, System.Numerics.Matrix4x4.M34, System.Numerics.Matrix4x4.M41, System.Numerics.Matrix4x4.M42, System.Numerics.Matrix4x4.M43, System.Numerics.Matrix4x4.M44, System.Runtime.Intrinsics.X86.Sse.Multiply(), System.Numerics.Matrix4x4.Permute(), System.Runtime.Intrinsics.X86.Sse.Shuffle(), and System.Runtime.Intrinsics.X86.Sse.Subtract().
Referenced by System.Numerics.Plane.Transform().