Terraria: System.Numerics.Matrix4x4.CreateLookAt
CreateLookAt()
static Matrix4x4 System.Numerics.Matrix4x4.CreateLookAt (Vector3 cameraPosition, Vector3 cameraTarget, Vector3 cameraUpVector) inline static
Definition at line 478 of file Matrix4x4.cs.
    {
        Vector3 vector = Vector3.Normalize(cameraPosition - cameraTarget);
        Vector3 vector2 = Vector3.Normalize(Vector3.Cross(cameraUpVector, vector));
        Vector3 vector3 = Vector3.Cross(vector, vector2);
        Matrix4x4 identity = Identity;
        identity.M11 = vector2.X;
        identity.M12 = vector3.X;
        identity.M13 = vector.X;
        identity.M21 = vector2.Y;
        identity.M22 = vector3.Y;
        identity.M23 = vector.Y;
        identity.M31 = vector2.Z;
        identity.M32 = vector3.Z;
        identity.M33 = vector.Z;
        identity.M41 = 0f - Vector3.Dot(vector2, cameraPosition);
        identity.M42 = 0f - Vector3.Dot(vector3, cameraPosition);
        identity.M43 = 0f - Vector3.Dot(vector, cameraPosition);
        return identity;
    }
References System.Numerics.Vector3.Cross(), System.Numerics.Vector3.Dot(), System.Numerics.Matrix4x4.Identity, System.Numerics.Vector3.Normalize(), System.Numerics.Vector3.X, System.Numerics.Vector3.Y, and System.Numerics.Vector3.Z.