Terraria: System.Numerics.Matrix4x4.Transpose
Transpose()
static unsafe Matrix4x4 System.Numerics.Matrix4x4.Transpose (Matrix4x4 matrix) inline static
Definition at line 1276 of file Matrix4x4.cs.
    {
        if (AdvSimd.Arm64.IsSupported)
        {
        }
        if (Sse.IsSupported)
        {
            Vector128<float> left = Sse.LoadVector128(&matrix.M11);
            Vector128<float> right = Sse.LoadVector128(&matrix.M21);
            Vector128<float> left2 = Sse.LoadVector128(&matrix.M31);
            Vector128<float> right2 = Sse.LoadVector128(&matrix.M41);
            Vector128<float> vector = Sse.UnpackLow(left, right);
            Vector128<float> vector2 = Sse.UnpackLow(left2, right2);
            Vector128<float> vector3 = Sse.UnpackHigh(left, right);
            Vector128<float> vector4 = Sse.UnpackHigh(left2, right2);
            Sse.Store(&matrix.M11, Sse.MoveLowToHigh(vector, vector2));
            Sse.Store(&matrix.M21, Sse.MoveHighToLow(vector2, vector));
            Sse.Store(&matrix.M31, Sse.MoveLowToHigh(vector3, vector4));
            Sse.Store(&matrix.M41, Sse.MoveHighToLow(vector4, vector3));
            return matrix;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out Matrix4x4 result);
        result.M11 = matrix.M11;
        result.M12 = matrix.M21;
        result.M13 = matrix.M31;
        result.M14 = matrix.M41;
        result.M21 = matrix.M12;
        result.M22 = matrix.M22;
        result.M23 = matrix.M32;
        result.M24 = matrix.M42;
        result.M31 = matrix.M13;
        result.M32 = matrix.M23;
        result.M33 = matrix.M33;
        result.M34 = matrix.M43;
        result.M41 = matrix.M14;
        result.M42 = matrix.M24;
        result.M43 = matrix.M34;
        result.M44 = matrix.M44;
        return result;
    }
References System.Runtime.Intrinsics.Arm.AdvSimd.Arm64.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Sse.LoadVector128(), System.Numerics.Matrix4x4.M11, System.Numerics.Matrix4x4.M12, System.Numerics.Matrix4x4.M13, System.Numerics.Matrix4x4.M14, System.Numerics.Matrix4x4.M21, System.Numerics.Matrix4x4.M22, System.Numerics.Matrix4x4.M23, System.Numerics.Matrix4x4.M24, System.Numerics.Matrix4x4.M31, System.Numerics.Matrix4x4.M32, System.Numerics.Matrix4x4.M33, System.Numerics.Matrix4x4.M34, System.Numerics.Matrix4x4.M41, System.Numerics.Matrix4x4.M42, System.Numerics.Matrix4x4.M43, System.Numerics.Matrix4x4.M44, System.Runtime.Intrinsics.X86.Sse.MoveHighToLow(), System.Runtime.Intrinsics.X86.Sse.MoveLowToHigh(), System.Runtime.Intrinsics.X86.Sse.Store(), System.Runtime.Intrinsics.X86.Sse.UnpackHigh(), and System.Runtime.Intrinsics.X86.Sse.UnpackLow().