Terraria: System.Numerics.Matrix4x4.Permute
Permute()
static Vector128< float > System.Numerics.Matrix4x4.Permute (Vector128< float > value, byte control) inline static private
Definition at line 1072 of file Matrix4x4.cs.
    {
        if (Avx.IsSupported)
        {
            return Avx.Permute(value, control);
        }
        if (Sse.IsSupported)
        {
            return Sse.Shuffle(value, value, control);
        }
        throw new PlatformNotSupportedException();
    }
References System.Runtime.Intrinsics.X86.Avx.IsSupported, System.Runtime.Intrinsics.X86.Sse.IsSupported, System.Runtime.Intrinsics.X86.Avx.Permute(), System.Runtime.Intrinsics.X86.Sse.Shuffle(), and System.value.
Referenced by System.Numerics.Matrix4x4.Invert().