Terraria: System.Xml.StringHandle.GetString
GetString() [3/3]
string System.Xml.StringHandle.GetString (XmlNameTable nameTable) inline
Definition at line 106 of file StringHandle.cs.
    {
        return _type switch
        {
            StringHandleType.UTF8 => _bufferReader.GetString(_offset, _length, nameTable),
            StringHandleType.Dictionary => nameTable.Add(_bufferReader.GetDictionaryString(_key).Value),
            _ => nameTable.Add(s_constStrings[_key]),
        };
    }
References System.Xml.StringHandle._bufferReader, System.Xml.StringHandle._key, System.Xml.StringHandle._length, System.Xml.StringHandle._offset, System.Xml.StringHandle._type, System.Xml.StringHandle.Dictionary, System.Xml.XmlBufferReader.GetDictionaryString(), System.Xml.XmlBufferReader.GetString(), System.Xml.StringHandle.s_constStrings, and System.Xml.XmlDictionaryString.Value.
Referenced by System.Xml.XmlBaseReader.GetOpenElements(), System.Xml.XmlBaseReader.LookupNamespace(), System.Xml.XmlUTF8TextReader.ReadEndElement(), System.Xml.XmlUTF8TextReader.ReadQualifiedName(), System.Xml.XmlBaseReader.NamespaceManager.Sign(), System.Xml.XmlBaseReader.SignEndElement(), and System.Xml.XmlBaseReader.SignStartElement().