Terraria: System.Xml.StringHandle.TryGetDictionaryString
TryGetDictionaryString()
bool System.Xml.StringHandle.TryGetDictionaryString ([NotNullWhen(true)] out XmlDictionaryString value) inline
Definition at line 158 of file StringHandle.cs.
    {
        if (_type == StringHandleType.Dictionary)
        {
            value = _bufferReader.GetDictionaryString(_key);
            return true;
        }
        if (IsEmpty)
        {
            value = XmlDictionaryString.Empty;
            return true;
        }
        value = null;
        return false;
    }
References System.Xml.StringHandle._bufferReader, System.Xml.StringHandle._key, System.Xml.StringHandle._type, System.Xml.XmlDictionaryString.Empty, System.Xml.XmlBufferReader.GetDictionaryString(), System.Xml.StringHandle.IsEmpty, and System.value.
Referenced by System.Xml.XmlBaseReader.XmlNode.TryGetLocalNameAsDictionaryString(), and System.Xml.XmlBaseReader.XmlNode.TryGetNamespaceUriAsDictionaryString().