Terraria: System.Xml.StringHandle.GetString
GetString() [2/3]
byte[] System.Xml.StringHandle.GetString (out int offset, out int length) inline
Definition at line 126 of file StringHandle.cs.
    {
        switch (_type)
        {
        case StringHandleType.UTF8:
            offset = _offset;
            length = _length;
            return _bufferReader.Buffer;
        case StringHandleType.Dictionary:
        {
            byte[] array3 = _bufferReader.GetDictionaryString(_key).ToUTF8();
            offset = 0;
            length = array3.Length;
            return array3;
        }
        case StringHandleType.ConstString:
        {
            byte[] array2 = XmlConverter.ToBytes(s_constStrings[_key]);
            offset = 0;
            length = array2.Length;
            return array2;
        }
        default:
        {
            byte[] array = XmlConverter.ToBytes(_bufferReader.GetEscapedString(_offset, _length));
            offset = 0;
            length = array.Length;
            return array;
        }
        }
    }
References System.Xml.StringHandle._bufferReader, System.Xml.StringHandle._key, System.Xml.StringHandle._length, System.Xml.StringHandle._offset, System.Xml.StringHandle._type, System.array, System.Xml.XmlBufferReader.Buffer, System.Xml.StringHandle.Dictionary, System.Xml.XmlBufferReader.GetDictionaryString(), System.Xml.XmlBufferReader.GetEscapedString(), System.length, System.offset, System.Xml.StringHandle.s_constStrings, System.Xml.XmlConverter.ToBytes(), and System.Xml.XmlDictionaryString.ToUTF8().