Terraria: PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder
DrawPlayer_04_RabbitOrder()
static void PlayerDrawHeadLayers.DrawPlayer_04_RabbitOrder (ref PlayerDrawHeadSet drawinfo) inline static
     {
         int verticalFrames = 27;
         Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
         Rectangle rectangle = value.Frame(1, verticalFrames, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
         Vector2 origin = rectangle.Size() / 2f;
         int usedGravDir = 1;
         Vector2 vector = DrawPlayer_04_GetHatDrawPosition(ref drawinfo, new Vector2(1f, -26f), usedGravDir);
         int hatStacks = GetHatStacks(ref drawinfo, 4955);
         float num = (float)Math.PI / 60f;
         float num2 = num * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
         for (int num3 = hatStacks - 1; num3 >= 0; num3--)
         {
             float x = Vector2.UnitY.RotatedBy(num2 + num * (float)num3).X * ((float)num3 / 30f) * 2f - (float)(num3 * 2 * drawinfo.drawPlayer.direction);
             QuickCDD(drawinfo.DrawData, drawinfo.cHead, value, vector + new Vector2(x, (float)(num3 * -14) * drawinfo.scale), rectangle, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin, drawinfo.scale, drawinfo.playerEffect, 0f);
         }
         if (!drawinfo.hideHair)
         {
             Rectangle hairFrame = drawinfo.HairFrame;
             hairFrame.Y -= 336;
             if (hairFrame.Y < 0)
             {
                 hairFrame.Y = 0;
             }
             QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, hairFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
         }
     }
References TextureAssets.ArmorHead, DrawPlayer_04_GetHatDrawPosition(), GetHatStacks(), TextureAssets.PlayerHair, QuickCDD(), Main.screenPosition, Asset< T >.Value, and X.
Referenced by DrawPlayer_04_HatsWithFullHair().