Terraria: PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair
DrawPlayer_04_HatsWithFullHair()
static void PlayerDrawHeadLayers.DrawPlayer_04_HatsWithFullHair (ref PlayerDrawHeadSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.head == 259)
         {
             DrawPlayer_04_RabbitOrder(ref drawinfo);
         }
         else
         {
             if (!drawinfo.helmetIsOverFullHair)
             {
                 return;
             }
             if (!drawinfo.hideHair)
             {
                 Rectangle hairFrame = drawinfo.HairFrame;
                 hairFrame.Y -= 336;
                 if (hairFrame.Y < 0)
                 {
                     hairFrame.Y = 0;
                 }
                 QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, hairFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
             }
             if (drawinfo.drawPlayer.head != 0)
             {
                 Color color = drawinfo.colorArmorHead;
                 int shaderTechnique = drawinfo.cHead;
                 if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                 {
                     color = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                     shaderTechnique = drawinfo.skinDyePacked;
                 }
                 QuickCDD(drawinfo.DrawData, shaderTechnique, TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.bodyFrameMemory, color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
             }
         }
     }
References TextureAssets.ArmorHead, Color, DrawPlayer_04_RabbitOrder(), TextureAssets.PlayerHair, QuickCDD(), Main.screenPosition, ArmorIDs.Head.Sets.UseSkinColor, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().