Terraria: PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet
DrawPlayer_00_BackHelmet()
static void PlayerDrawHeadLayers.DrawPlayer_00_BackHelmet (ref PlayerDrawHeadSet drawinfo) inline static
     {
         if (drawinfo.drawPlayer.head >= 0 && drawinfo.drawPlayer.head < ArmorIDs.Head.Count)
         {
             int num = ArmorIDs.Head.Sets.FrontToBackID[drawinfo.drawPlayer.head];
             if (num >= 0)
             {
                 Rectangle hairFrame = drawinfo.HairFrame;
                 QuickCDD(drawinfo.DrawData, drawinfo.cHead, TextureAssets.ArmorHead[num].Value, drawinfo.helmetOffset + new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, hairFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
             }
         }
     }
References TextureAssets.ArmorHead, ArmorIDs.Head.Count, ArmorIDs.Head.Sets.FrontToBackID, QuickCDD(), Main.screenPosition, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().