Terraria: PlayerDrawHeadLayers.DrawPlayer_07_JustHair
DrawPlayer_07_JustHair()
static void PlayerDrawHeadLayers.DrawPlayer_07_JustHair (ref PlayerDrawHeadSet drawinfo) inline static
     {
         if (!drawinfo.helmetIsNormal && !drawinfo.helmetIsOverFullHair && !drawinfo.helmetIsTall && !drawinfo.hideHair)
         {
             Rectangle hairFrame = drawinfo.HairFrame;
             hairFrame.Y -= 336;
             if (hairFrame.Y < 0)
             {
                 hairFrame.Y = 0;
             }
             QuickCDD(drawinfo.DrawData, drawinfo.hairShaderPacked, TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, new Vector2(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.bodyFrameMemory.Width / 2) + (float)(drawinfo.drawPlayer.width / 2), drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.bodyFrameMemory.Height + 4f) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + drawinfo.hairOffset, hairFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, drawinfo.scale, drawinfo.playerEffect, 0f);
         }
     }
References TextureAssets.PlayerHair, QuickCDD(), Main.screenPosition, and Asset< T >.Value.
Referenced by LegacyPlayerRenderer.DrawPlayerHead(), and PlayerHeadDrawRenderTargetContent.DrawTheContent().