Terraria: System.Diagnostics.Tracing.PropertyValue.GetBoxedValueTypePropertyGetter
GetBoxedValueTypePropertyGetter()
static Func< PropertyValue, PropertyValue > System.Diagnostics.Tracing.PropertyValue.GetBoxedValueTypePropertyGetter (PropertyInfo property) inline static private
Definition at line 460 of file PropertyValue.cs.
    {
        Type type = property.PropertyType;
        if (type.IsEnum)
        {
            type = Enum.GetUnderlyingType(type);
        }
        Func<object, PropertyValue> factory = GetFactory(type);
        return (PropertyValue container) => factory(property.GetValue(container.ReferenceValue));
    }
References System.Diagnostics.Tracing.PropertyValue.GetFactory(), System.Enum.GetUnderlyingType(), System.Reflection.PropertyInfo.GetValue(), System.Diagnostics.Tracing.PropertyValue.ReferenceValue, and System.type.
Referenced by System.Diagnostics.Tracing.PropertyValue.GetPropertyGetter().