Terraria: System.Security.Cryptography.Asn1.PssParamsAsn.Encode
Encode() [2/2]
void System.Security.Cryptography.Asn1.PssParamsAsn.Encode (AsnWriter writer, Asn1Tag tag) inline package
Definition at line 37 of file PssParamsAsn.cs.
    {
        writer.PushSequence(tag);
        AsnWriter asnWriter = new AsnWriter(AsnEncodingRules.DER);
        HashAlgorithm.Encode(asnWriter);
        if (!asnWriter.EncodedValueEquals(DefaultHashAlgorithm))
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            asnWriter.CopyTo(writer);
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
        }
        AsnWriter asnWriter2 = new AsnWriter(AsnEncodingRules.DER);
        MaskGenAlgorithm.Encode(asnWriter2);
        if (!asnWriter2.EncodedValueEquals(DefaultMaskGenAlgorithm))
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 1));
            asnWriter2.CopyTo(writer);
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 1));
        }
        AsnWriter asnWriter3 = new AsnWriter(AsnEncodingRules.DER);
        asnWriter3.WriteInteger(SaltLength);
        if (!asnWriter3.EncodedValueEquals(DefaultSaltLength))
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 2));
            asnWriter3.CopyTo(writer);
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 2));
        }
        AsnWriter asnWriter4 = new AsnWriter(AsnEncodingRules.DER);
        asnWriter4.WriteInteger(TrailerField);
        if (!asnWriter4.EncodedValueEquals(DefaultTrailerField))
        {
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 3));
            asnWriter4.CopyTo(writer);
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 3));
        }
        writer.PopSequence(tag);
    }
References System.Formats.Asn1.AsnWriter.CopyTo(), System.Security.Cryptography.Asn1.PssParamsAsn.DefaultHashAlgorithm, System.Security.Cryptography.Asn1.PssParamsAsn.DefaultMaskGenAlgorithm, System.Security.Cryptography.Asn1.PssParamsAsn.DefaultSaltLength, System.Security.Cryptography.Asn1.PssParamsAsn.DefaultTrailerField, System.Formats.Asn1.AsnWriter.EncodedValueEquals(), System.Security.Cryptography.Asn1.PssParamsAsn.MaskGenAlgorithm, System.Security.Cryptography.Asn1.PssParamsAsn.SaltLength, System.Security.Cryptography.Asn1.PssParamsAsn.TrailerField, System.Formats.Asn1.AsnWriter.WriteInteger(), and System.writer.