Terraria: System.Diagnostics.Tracing.PropertyValue.GetFactory
GetFactory()
static Func< object, PropertyValue > System.Diagnostics.Tracing.PropertyValue.GetFactory (Type type) inline static
Definition at line 370 of file PropertyValue.cs.
    {
        if (type == typeof(bool))
        {
            return (object value) => new PropertyValue((bool)value);
        }
        if (type == typeof(byte))
        {
            return (object value) => new PropertyValue((byte)value);
        }
        if (type == typeof(sbyte))
        {
            return (object value) => new PropertyValue((sbyte)value);
        }
        if (type == typeof(char))
        {
            return (object value) => new PropertyValue((char)value);
        }
        if (type == typeof(short))
        {
            return (object value) => new PropertyValue((short)value);
        }
        if (type == typeof(ushort))
        {
            return (object value) => new PropertyValue((ushort)value);
        }
        if (type == typeof(int))
        {
            return (object value) => new PropertyValue((int)value);
        }
        if (type == typeof(uint))
        {
            return (object value) => new PropertyValue((uint)value);
        }
        if (type == typeof(long))
        {
            return (object value) => new PropertyValue((long)value);
        }
        if (type == typeof(ulong))
        {
            return (object value) => new PropertyValue((ulong)value);
        }
        if (type == typeof(IntPtr))
        {
            return (object value) => new PropertyValue((IntPtr)value);
        }
        if (type == typeof(UIntPtr))
        {
            return (object value) => new PropertyValue((UIntPtr)value);
        }
        if (type == typeof(float))
        {
            return (object value) => new PropertyValue((float)value);
        }
        if (type == typeof(double))
        {
            return (object value) => new PropertyValue((double)value);
        }
        if (type == typeof(Guid))
        {
            return (object value) => new PropertyValue((Guid)value);
        }
        if (type == typeof(DateTime))
        {
            return (object value) => new PropertyValue((DateTime)value);
        }
        if (type == typeof(DateTimeOffset))
        {
            return (object value) => new PropertyValue((DateTimeOffset)value);
        }
        if (type == typeof(TimeSpan))
        {
            return (object value) => new PropertyValue((TimeSpan)value);
        }
        if (type == typeof(decimal))
        {
            return (object value) => new PropertyValue((decimal)value);
        }
        return (object value) => new PropertyValue(value);
    }
References System.Diagnostics.Tracing.PropertyValue.PropertyValue(), System.type, and System.value.
Referenced by System.Diagnostics.Tracing.TraceLoggingTypeInfo.TraceLoggingTypeInfo(), System.Diagnostics.Tracing.TraceLoggingTypeInfo.TraceLoggingTypeInfo(), and System.Diagnostics.Tracing.PropertyValue.GetBoxedValueTypePropertyGetter().