Terraria: Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.ReportDroprates
ReportDroprates()
override void Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.ReportDroprates (List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline virtual
Reimplemented from Terraria.GameContent.ItemDropRules.CommonDrop.
Definition at line 20 of file ItemDropWithConditionRule.cs.
    {
        DropRateInfoChainFeed ratesInfo2 = ratesInfo.With(1f);
        ratesInfo2.AddCondition(condition);
        float num = (float)chanceNumerator / (float)chanceDenominator;
        float dropRate = num * ratesInfo2.parentDroprateChance;
        drops.Add(new DropRateInfo(itemId, amountDroppedMinimum, amountDroppedMaximum, dropRate, ratesInfo2.conditions));
        Chains.ReportDroprates(base.ChainedRules, num, drops, ratesInfo2);
    }
References Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.AddCondition(), Terraria.GameContent.ItemDropRules.CommonDrop.amountDroppedMaximum, Terraria.GameContent.ItemDropRules.CommonDrop.amountDroppedMinimum, Terraria.GameContent.ItemDropRules.CommonDrop.chanceDenominator, Terraria.GameContent.ItemDropRules.CommonDrop.chanceNumerator, Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.condition, Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.conditions, Terraria.GameContent.ItemDropRules.CommonDrop.itemId, Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.parentDroprateChance, Terraria.GameContent.ItemDropRules.Chains.ReportDroprates(), and Terraria.GameContent.ItemDropRules.DropRateInfoChainFeed.With().