Terraria: System.Decimal.DecCalc.UInt64x64To128
UInt64x64To128()
static void System.Decimal.DecCalc.UInt64x64To128 (ulong a, ulong b, ref DecCalc result) inline static private
Definition at line 305 of file Decimal.cs.
        {
            ulong num = UInt32x32To64((uint)a, (uint)b);
            ulong num2 = UInt32x32To64((uint)a, (uint)(b >> 32));
            ulong num3 = UInt32x32To64((uint)(a >> 32), (uint)(b >> 32));
            num3 += num2 >> 32;
            num += (num2 <<= 32);
            if (num < num2)
            {
                num3++;
            }
            num2 = UInt32x32To64((uint)(a >> 32), (uint)b);
            num3 += num2 >> 32;
            num += (num2 <<= 32);
            if (num < num2)
            {
                num3++;
            }
            if (num3 > uint.MaxValue)
            {
                Number.ThrowOverflowException(TypeCode.Decimal);
            }
            result.Low64 = num;
            result.High = (uint)num3;
        }
References System.Runtime.Serialization.Dictionary, System.Number.ThrowOverflowException(), and System.Decimal.DecCalc.UInt32x32To64().
Referenced by System.Decimal.DecCalc.VarDecFromR4(), and System.Decimal.DecCalc.VarDecFromR8().