Terraria: System.Decimal.DecCalc.VarDecCmp
VarDecCmp()
static int System.Decimal.DecCalc.VarDecCmp (in decimal d1, in decimal d2) inline static package
Definition at line 1045 of file Decimal.cs.
        {
            if ((d2.Low64 | d2.High) == 0L)
            {
                if ((d1.Low64 | d1.High) == 0L)
                {
                    return 0;
                }
                return (d1._flags >> 31) | 1;
            }
            if ((d1.Low64 | d1.High) == 0L)
            {
                return -((d2._flags >> 31) | 1);
            }
            int num = (d1._flags >> 31) - (d2._flags >> 31);
            if (num != 0)
            {
                return num;
            }
            return VarDecCmpSub(in d1, in d2);
        }
References System.Runtime.Serialization.Dictionary, System.L, and System.Decimal.DecCalc.VarDecCmpSub().
Referenced by System.Decimal.Compare(), System.Decimal.CompareTo(), System.Decimal.CompareTo(), System.Decimal.Equals(), System.Decimal.Equals(), System.Decimal.Equals(), System.Decimal.Max(), System.Decimal.Min(), System.Decimal.operator!=(), System.Decimal.operator<(), System.Decimal.operator<=(), System.Decimal.operator==(), System.Decimal.operator>(), and System.Decimal.operator>=().