Terraria: System.Decimal.DecCalc.Div128By96
Div128By96()
static uint System.Decimal.DecCalc.Div128By96 (ref Buf16 bufNum, ref Buf12 bufDen) inline static private
Definition at line 444 of file Decimal.cs.
        {
            ulong high = bufNum.High64;
            uint u = bufDen.U2;
            if (high < u)
            {
                return 0u;
            }
            uint num = (uint)(high / u);
            uint num2 = (uint)(int)high - num * u;
            ulong num3 = UInt32x32To64(num, bufDen.U0);
            ulong num4 = UInt32x32To64(num, bufDen.U1);
            num4 += num3 >> 32;
            num3 = (uint)num3 | (num4 << 32);
            num4 >>= 32;
            ulong low = bufNum.Low64;
            low -= num3;
            num2 -= (uint)(int)num4;
            if (low > ~num3)
            {
                num2--;
                if (num2 >= (uint)(~num4))
                {
                    goto IL_008b;
                }
            }
            else if (num2 > (uint)(~num4))
            {
                goto IL_008b;
            }
            goto IL_00b4;
            IL_008b:
            num3 = bufDen.Low64;
            do
            {
                num--;
                low += num3;
                num2 += u;
            }
            while ((low >= num3 || num2++ >= u) && num2 >= u);
            goto IL_00b4;
            IL_00b4:
            bufNum.Low64 = low;
            bufNum.U2 = num2;
            return num;
        }
References System.Runtime.Serialization.Dictionary, and System.Decimal.DecCalc.UInt32x32To64().
Referenced by System.Decimal.DecCalc.VarDecDiv(), and System.Decimal.DecCalc.VarDecModFull().