Terraria: System.Decimal.DecCalc.VarR8FromDec
VarR8FromDec()
static double System.Decimal.DecCalc.VarR8FromDec (in decimal value) inline static package
Definition at line 1533 of file Decimal.cs.
        {
            double num = ((double)value.Low64 + (double)value.High * 1.8446744073709552E+19) / s_doublePowers10[value.Scale];
            if (value.IsNegative)
            {
                num = 0.0 - num;
            }
            return num;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.s_doublePowers10, and System.value.
Referenced by System.Decimal.operator double(), System.Decimal.ToDouble(), System.Decimal.ToDouble(), and System.Decimal.DecCalc.VarR4FromDec().