Terraria: System.Decimal.DecCalc.VarDecCmpSub
VarDecCmpSub()
static int System.Decimal.DecCalc.VarDecCmpSub (in decimal d1, in decimal d2) inline static private
Definition at line 1067 of file Decimal.cs.
        {
            int flags = d2._flags;
            int num = (flags >> 31) | 1;
            int num2 = flags - d1._flags;
            ulong num3 = d1.Low64;
            uint num4 = d1.High;
            ulong num5 = d2.Low64;
            uint num6 = d2.High;
            if (num2 != 0)
            {
                num2 >>= 16;
                if (num2 < 0)
                {
                    num2 = -num2;
                    num = -num;
                    ulong num7 = num3;
                    num3 = num5;
                    num5 = num7;
                    uint num8 = num4;
                    num4 = num6;
                    num6 = num8;
                }
                do
                {
                    uint b = ((num2 >= 9) ? 1000000000u : s_powers10[num2]);
                    ulong num9 = UInt32x32To64((uint)num3, b);
                    ulong num10 = UInt32x32To64((uint)(num3 >> 32), b) + (num9 >> 32);
                    num3 = (uint)num9 + (num10 << 32);
                    num10 >>= 32;
                    num10 += UInt32x32To64(num4, b);
                    if (num10 > uint.MaxValue)
                    {
                        return num;
                    }
                    num4 = (uint)num10;
                }
                while ((num2 -= 9) > 0);
            }
            uint num11 = num4 - num6;
            if (num11 != 0)
            {
                if (num11 > num4)
                {
                    num = -num;
                }
                return num;
            }
            ulong num12 = num3 - num5;
            if (num12 == 0L)
            {
                num = 0;
            }
            else if (num12 > num3)
            {
                num = -num;
            }
            return num;
        }
References System.Runtime.Serialization.Dictionary, System.L, System.Decimal.DecCalc.s_powers10, and System.Decimal.DecCalc.UInt32x32To64().
Referenced by System.Decimal.DecCalc.VarDecCmp(), and System.Decimal.DecCalc.VarDecMod().