Terraria: System.Decimal.DecCalc.VarDecMul
VarDecMul()
static unsafe void System.Decimal.DecCalc.VarDecMul (ref DecCalc d1, ref DecCalc d2) inline static package
Definition at line 1127 of file Decimal.cs.
        {
            int num = (byte)(d1.uflags + d2.uflags >> 16);
            Unsafe.SkipInit<Buf24>(out var value);
            uint num6;
            if ((d1.High | d1.Mid) == 0)
            {
                ulong num4;
                if ((d2.High | d2.Mid) == 0)
                {
                    ulong num2 = UInt32x32To64(d1.Low, d2.Low);
                    if (num > 28)
                    {
                        if (num > 47)
{
                            goto IL_03b4;
                        }
                        num -= 29;
                        ulong num3 = s_ulongPowers10[num];
                        num4 = num2 / num3;
                        ulong num5 = num2 - num4 * num3;
                        num2 = num4;
                        num3 >>= 1;
                        if (num5 >= num3 && (num5 > num3 || ((uint)(int)num2 & (true ? 1u : 0u)) != 0))
{
                            num2++;
                        }
                        num = 28;
                    }
                    d1.Low64 = num2;
                    d1.uflags = ((d2.uflags ^ d1.uflags) & 0x80000000u) | (uint)(num << 16);
                    return;
                }
                num4 = UInt32x32To64(d1.Low, d2.Low);
                value.U0 = (uint)num4;
                num4 = UInt32x32To64(d1.Low, d2.Mid) + (num4 >> 32);
                value.U1 = (uint)num4;
                num4 >>= 32;
                if (d2.High != 0)
                {
                    num4 += UInt32x32To64(d1.Low, d2.High);
                    if (num4 > uint.MaxValue)
                    {
                        value.Mid64 = num4;
                        num6 = 3u;
                        goto IL_0368;
                    }
                }
                value.U2 = (uint)num4;
                num6 = 2u;
            }
            else if ((d2.High | d2.Mid) == 0)
            {
                ulong num4 = UInt32x32To64(d2.Low, d1.Low);
                value.U0 = (uint)num4;
                num4 = UInt32x32To64(d2.Low, d1.Mid) + (num4 >> 32);
                value.U1 = (uint)num4;
                num4 >>= 32;
                if (d1.High != 0)
                {
                    num4 += UInt32x32To64(d2.Low, d1.High);
                    if (num4 > uint.MaxValue)
                    {
                        value.Mid64 = num4;
                        num6 = 3u;
                        goto IL_0368;
                    }
                }
                value.U2 = (uint)num4;
                num6 = 2u;
            }
            else
            {
                ulong num4 = UInt32x32To64(d1.Low, d2.Low);
                value.U0 = (uint)num4;
                ulong num7 = UInt32x32To64(d1.Low, d2.Mid) + (num4 >> 32);
                num4 = UInt32x32To64(d1.Mid, d2.Low);
                num4 += num7;
                value.U1 = (uint)num4;
                num7 = ((num4 >= num7) ? (num4 >> 32) : ((num4 >> 32) | 0x100000000uL));
                num4 = UInt32x32To64(d1.Mid, d2.Mid) + num7;
                if ((d1.High | d2.High) != 0)
                {
                    num7 = UInt32x32To64(d1.Low, d2.High);
                    num4 += num7;
                    uint num8 = 0u;
                    if (num4 < num7)
                    {
                        num8 = 1u;
                    }
                    num7 = UInt32x32To64(d1.High, d2.Low);
                    num4 += num7;
                    value.U2 = (uint)num4;
                    if (num4 < num7)
                    {
                        num8++;
                    }
                    num7 = ((ulong)num8 << 32) | (num4 >> 32);
                    num4 = UInt32x32To64(d1.Mid, d2.High);
                    num4 += num7;
                    num8 = 0u;
                    if (num4 < num7)
                    {
                        num8 = 1u;
                    }
                    num7 = UInt32x32To64(d1.High, d2.Mid);
                    num4 += num7;
                    value.U3 = (uint)num4;
                    if (num4 < num7)
                    {
                        num8++;
                    }
                    num4 = ((ulong)num8 << 32) | (num4 >> 32);
                    value.High64 = UInt32x32To64(d1.High, d2.High) + num4;
                    num6 = 5u;
                }
                else
                {
                    value.Mid64 = num4;
                    num6 = 3u;
                }
            }
            uint* ptr = (uint*)(&value);
            while (ptr[(int)num6] == 0)
            {
                if (num6 != 0)
                {
                    num6--;
                    continue;
                }
                goto IL_03b4;
            }
            goto IL_0368;
            IL_0368:
            if (num6 > 2 || num > 28)
            {
                num = ScaleResult(&value, num6, num);
            }
            d1.Low64 = value.Low64;
            d1.High = value.U2;
            d1.uflags = ((d2.uflags ^ d1.uflags) & 0x80000000u) | (uint)(num << 16);
            return;
            IL_03b4:
            d1 = default(DecCalc);
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.s_ulongPowers10, System.Decimal.DecCalc.ScaleResult(), System.Decimal.DecCalc.UInt32x32To64(), and System.value.
Referenced by System.Decimal.Multiply(), and System.Decimal.operator*().