Terraria: System.Decimal.DecCalc.VarDecFromR4
VarDecFromR4()
static void System.Decimal.DecCalc.VarDecFromR4 (float input, out DecCalc result) inline static package
Definition at line 1273 of file Decimal.cs.
        {
            result = default(DecCalc);
            int num = (int)(GetExponent(input) - 126);
            if (num < -94)
            {
                return;
            }
            if (num > 96)
            {
                Number.ThrowOverflowException(TypeCode.Decimal);
            }
            uint num2 = 0u;
            if (input < 0f)
            {
                input = 0f - input;
                num2 = 2147483648u;
            }
            double num3 = input;
            int num4 = 6 - (num * 19728 >> 16);
            if (num4 >= 0)
            {
                if (num4 > 28)
                {
                    num4 = 28;
                }
                num3 *= s_doublePowers10[num4];
            }
            else if (num4 != -1 || num3 >= 10000000.0)
            {
                num3 /= s_doublePowers10[-num4];
            }
            else
            {
                num4 = 0;
            }
            if (num3 < 1000000.0 && num4 < 28)
            {
                num3 *= 10.0;
                num4++;
            }
            uint num5;
            if (Sse41.IsSupported)
            {
                num5 = (uint)(int)Math.Round(num3);
            }
            else
            {
                num5 = (uint)(int)num3;
                num3 -= (double)(int)num5;
                if (num3 > 0.5 || (num3 == 0.5 && (num5 & (true ? 1u : 0u)) != 0))
                {
                    num5++;
                }
            }
            if (num5 == 0)
            {
                return;
            }
            if (num4 < 0)
            {
                num4 = -num4;
                if (num4 < 10)
                {
                    result.Low64 = UInt32x32To64(num5, s_powers10[num4]);
                }
                else if (num4 > 18)
                {
                    ulong a = UInt32x32To64(num5, s_powers10[num4 - 18]);
                    UInt64x64To128(a, 1000000000000000000uL, ref result);
                }
                else
                {
                    ulong num6 = UInt32x32To64(num5, s_powers10[num4 - 9]);
                    ulong num7 = UInt32x32To64(1000000000u, (uint)(num6 >> 32));
                    num6 = UInt32x32To64(1000000000u, (uint)num6);
                    result.Low = (uint)num6;
                    num7 += num6 >> 32;
                    result.Mid = (uint)num7;
                    num7 >>= 32;
                    result.High = (uint)num7;
                }
            }
            else
            {
                int num8 = num4;
                if (num8 > 6)
                {
                    num8 = 6;
                }
                if ((num5 & 0xF) == 0 && num8 >= 4)
                {
                    uint num9 = num5 / 10000;
                    if (num5 == num9 * 10000)
                    {
                        num5 = num9;
                        num4 -= 4;
                        num8 -= 4;
                    }
                }
                if ((num5 & 3) == 0 && num8 >= 2)
                {
                    uint num10 = num5 / 100;
                    if (num5 == num10 * 100)
                    {
                        num5 = num10;
                        num4 -= 2;
                        num8 -= 2;
                    }
                }
                if ((num5 & 1) == 0 && num8 >= 1)
                {
                    uint num11 = num5 / 10;
                    if (num5 == num11 * 10)
                    {
                        num5 = num11;
                        num4--;
                    }
                }
                num2 |= (uint)(num4 << 16);
                result.Low = num5;
            }
            result.uflags = num2;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.GetExponent(), System.input, System.Runtime.Intrinsics.X86.Sse41.IsSupported, System.Math.Round(), System.Decimal.DecCalc.s_doublePowers10, System.Decimal.DecCalc.s_powers10, System.Number.ThrowOverflowException(), System.Decimal.DecCalc.UInt32x32To64(), and System.Decimal.DecCalc.UInt64x64To128().
Referenced by System.Decimal.Decimal().