Terraria: System.Decimal.DecCalc.ScaleResult
ScaleResult()
static unsafe int System.Decimal.DecCalc.ScaleResult (Buf24 * bufRes, uint hiRes, int scale) inline static private
Definition at line 513 of file Decimal.cs.
        {
            int num = 0;
            if (hiRes > 2)
            {
                num = (int)(hiRes * 32 - 64 - 1);
                num -= BitOperations.LeadingZeroCount(*(uint*)((byte*)bufRes + (long)hiRes * 4L));
                num = (num * 77 >> 8) + 1;
                if (num > scale)
                {
                    goto IL_01cc;
                }
            }
            if (num < scale - 28)
            {
                num = scale - 28;
            }
            if (num == 0)
            {
                goto IL_01ca;
            }
            scale -= num;
            uint num2 = 0u;
            uint remainder = 0u;
            while (true)
            {
                num2 |= remainder;
                uint num3 = num switch
                {
                    1 => DivByConst((uint*)bufRes, hiRes, out var quotient, out remainder, 10u),
                    2 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 100u),
                    3 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 1000u),
                    4 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 10000u),
                    5 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 100000u),
                    6 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 1000000u),
                    7 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 10000000u),
                    8 => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 100000000u),
                    _ => DivByConst((uint*)bufRes, hiRes, out quotient, out remainder, 1000000000u),
                };
                *(uint*)((byte*)bufRes + (long)hiRes * 4L) = quotient;
                if (quotient == 0 && hiRes != 0)
                {
                    hiRes--;
                }
                num -= 9;
                if (num > 0)
                {
                    continue;
                }
                if (hiRes > 2)
                {
                    if (scale == 0)
                    {
                        break;
                    }
                    num = 1;
                    scale--;
                    continue;
                }
                num3 >>= 1;
                if (num3 <= remainder && (num3 < remainder || ((*(uint*)bufRes & (true ? 1u : 0u)) | num2) != 0) && ++(*(int*)bufRes) == 0)
                {
                    uint num4 = 0u;
                    while (++(*(int*)((byte*)bufRes + (long)(++num4) * 4L)) == 0)
                    {
                    }
                    if (num4 > 2)
                    {
                        if (scale == 0)
{
                            break;
                        }
                        hiRes = num4;
                        num2 = 0u;
                        remainder = 0u;
                        num = 1;
                        scale--;
                        continue;
                    }
                }
                goto IL_01ca;
            }
            goto IL_01cc;
            IL_01cc:
            Number.ThrowOverflowException(TypeCode.Decimal);
            return 0;
            IL_01ca:
            return scale;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.DivByConst(), System.L, System.Numerics.BitOperations.LeadingZeroCount(), and System.Number.ThrowOverflowException().
Referenced by System.Decimal.DecCalc.DecAddSub(), and System.Decimal.DecCalc.VarDecMul().