Terraria: System.Decimal.DecCalc.VarDecFromR8
VarDecFromR8()
static void System.Decimal.DecCalc.VarDecFromR8 (double input, out DecCalc result) inline static package
Definition at line 1398 of file Decimal.cs.
        {
            result = default(DecCalc);
            int num = (int)(GetExponent(input) - 1022);
            if (num < -94)
            {
                return;
            }
            if (num > 96)
            {
                Number.ThrowOverflowException(TypeCode.Decimal);
            }
            uint num2 = 0u;
            if (input < 0.0)
            {
                input = 0.0 - input;
                num2 = 2147483648u;
            }
            double num3 = input;
            int num4 = 14 - (num * 19728 >> 16);
            if (num4 >= 0)
            {
                if (num4 > 28)
                {
                    num4 = 28;
                }
                num3 *= s_doublePowers10[num4];
            }
            else if (num4 != -1 || num3 >= 1000000000000000.0)
            {
                num3 /= s_doublePowers10[-num4];
            }
            else
            {
                num4 = 0;
            }
            if (num3 < 100000000000000.0 && num4 < 28)
            {
                num3 *= 10.0;
                num4++;
            }
            ulong num5;
            if (Sse41.IsSupported)
            {
                num5 = (ulong)(long)Math.Round(num3);
            }
            else
            {
                num5 = (ulong)(long)num3;
                num3 -= (double)(long)num5;
                if (num3 > 0.5 || (num3 == 0.5 && (num5 & 1) != 0L))
                {
                    num5++;
                }
            }
            if (num5 == 0L)
            {
                return;
            }
            if (num4 < 0)
            {
                num4 = -num4;
                if (num4 < 10)
                {
                    uint b = s_powers10[num4];
                    ulong num6 = UInt32x32To64((uint)num5, b);
                    ulong num7 = UInt32x32To64((uint)(num5 >> 32), b);
                    result.Low = (uint)num6;
                    num7 += num6 >> 32;
                    result.Mid = (uint)num7;
                    num7 >>= 32;
                    result.High = (uint)num7;
                }
                else
                {
                    UInt64x64To128(num5, s_ulongPowers10[num4 - 1], ref result);
                }
            }
            else
            {
                int num8 = num4;
                if (num8 > 14)
                {
                    num8 = 14;
                }
                if ((byte)num5 == 0 && num8 >= 8)
                {
                    ulong num9 = num5 / 100000000;
                    if ((uint)num5 == (uint)(num9 * 100000000))
                    {
                        num5 = num9;
                        num4 -= 8;
                        num8 -= 8;
                    }
                }
                if (((int)num5 & 0xF) == 0 && num8 >= 4)
                {
                    ulong num10 = num5 / 10000;
                    if ((uint)num5 == (uint)(num10 * 10000))
                    {
                        num5 = num10;
                        num4 -= 4;
                        num8 -= 4;
                    }
                }
                if (((int)num5 & 3) == 0 && num8 >= 2)
                {
                    ulong num11 = num5 / 100;
                    if ((uint)num5 == (uint)(num11 * 100))
                    {
                        num5 = num11;
                        num4 -= 2;
                        num8 -= 2;
                    }
                }
                if (((int)num5 & 1) == 0 && num8 >= 1)
                {
                    ulong num12 = num5 / 10;
                    if ((uint)num5 == (uint)(num12 * 10))
                    {
                        num5 = num12;
                        num4--;
                    }
                }
                num2 |= (uint)(num4 << 16);
                result.Low64 = num5;
            }
            result.uflags = num2;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.GetExponent(), System.input, System.Runtime.Intrinsics.X86.Sse41.IsSupported, System.L, System.Math.Round(), System.Decimal.DecCalc.s_doublePowers10, System.Decimal.DecCalc.s_powers10, System.Decimal.DecCalc.s_ulongPowers10, System.Number.ThrowOverflowException(), System.Decimal.DecCalc.UInt32x32To64(), and System.Decimal.DecCalc.UInt64x64To128().
Referenced by System.Decimal.Decimal().