Terraria: System.Decimal.DecCalc.InternalRound
InternalRound()
static void System.Decimal.DecCalc.InternalRound (ref DecCalc d, uint scale, MidpointRounding mode) inline static package
Definition at line 1930 of file Decimal.cs.
        {
            d.uflags -= scale << 16;
            uint num = 0u;
            while (true)
            {
                uint num6;
                uint num5;
                if (scale >= 9)
                {
                    scale -= 9;
                    uint num2 = d.uhi;
                    if (num2 == 0)
                    {
                        ulong low = d.Low64;
                        ulong num4 = (d.Low64 = low / 1000000000);
                        num5 = (uint)(low - num4 * 1000000000);
                    }
                    else
                    {
                        num5 = num2 - (d.uhi = num2 / 1000000000) * 1000000000;
                        num2 = d.umid;
                        if ((num2 | num5) != 0)
{
                            num5 = num2 - (d.umid = (uint)((((ulong)num5 << 32) | num2) / 1000000000)) * 1000000000;
                        }
                        num2 = d.ulo;
                        if ((num2 | num5) != 0)
{
                            num5 = num2 - (d.ulo = (uint)((((ulong)num5 << 32) | num2) / 1000000000)) * 1000000000;
                        }
                    }
                    num6 = 1000000000u;
                    if (scale != 0)
                    {
                        num |= num5;
                        continue;
                    }
                }
                else
                {
                    num6 = s_powers10[scale];
                    uint num7 = d.uhi;
                    if (num7 == 0)
                    {
                        ulong low2 = d.Low64;
                        if (low2 == 0L)
{
                            if (mode <= MidpointRounding.ToZero)
{
                                break;
                            }
                            num5 = 0u;
                        }
                        else
{
                            ulong num9 = (d.Low64 = low2 / num6);
                            num5 = (uint)(low2 - num9 * num6);
                        }
                    }
                    else
                    {
                        num5 = num7 - (d.uhi = num7 / num6) * num6;
                        num7 = d.umid;
                        if ((num7 | num5) != 0)
{
                            num5 = num7 - (d.umid = (uint)((((ulong)num5 << 32) | num7) / num6)) * num6;
                        }
                        num7 = d.ulo;
                        if ((num7 | num5) != 0)
{
                            num5 = num7 - (d.ulo = (uint)((((ulong)num5 << 32) | num7) / num6)) * num6;
                        }
                    }
                }
                switch (mode)
                {
                case MidpointRounding.ToEven:
                    num5 <<= 1;
                    if ((num | (d.ulo & (true ? 1u : 0u))) != 0)
                    {
                        num5++;
                    }
                    if (num6 >= num5)
                    {
                        break;
                    }
                    goto IL_01e5;
                case MidpointRounding.AwayFromZero:
                    num5 <<= 1;
                    if (num6 > num5)
                    {
                        break;
                    }
                    goto IL_01e5;
                case MidpointRounding.ToNegativeInfinity:
                    if ((num5 | num) == 0 || !d.IsNegative)
                    {
                        break;
                    }
                    goto IL_01e5;
                default:
                    if ((num5 | num) == 0 || d.IsNegative)
                    {
                        break;
                    }
                    goto IL_01e5;
                case MidpointRounding.ToZero:
                    break;
                    IL_01e5:
                    if (++d.Low64 == 0L)
                    {
                        d.uhi++;
                    }
                    break;
                }
                break;
            }
        }
References System.Runtime.Serialization.Dictionary, System.L, and System.Decimal.DecCalc.s_powers10.
Referenced by System.Decimal.Ceiling(), System.Decimal.Floor(), System.Decimal.Round(), System.Decimal.Truncate(), and System.Decimal.DecCalc.VarCyFromDec().