Terraria: System.Decimal.DecCalc.Div96By64
Div96By64()
static uint System.Decimal.DecCalc.Div96By64 (ref Buf12 bufNum, ulong den) inline static private
Definition at line 390 of file Decimal.cs.
        {
            uint u = bufNum.U2;
            uint num;
            ulong low;
            if (u == 0)
            {
                low = bufNum.Low64;
                if (low < den)
                {
                    return 0u;
                }
                num = (uint)(low / den);
                low -= num * den;
                bufNum.Low64 = low;
                return num;
            }
            uint num2 = (uint)(den >> 32);
            if (u >= num2)
            {
                low = bufNum.Low64;
                low -= den << 32;
                num = 0u;
                do
                {
                    num--;
                    low += den;
                }
                while (low >= den);
                bufNum.Low64 = low;
                return num;
            }
            ulong high = bufNum.High64;
            if (high < num2)
            {
                return 0u;
            }
            num = (uint)(high / num2);
            low = bufNum.U0 | (high - num * num2 << 32);
            ulong num3 = UInt32x32To64(num, (uint)den);
            low -= num3;
            if (low > ~num3)
            {
                do
                {
                    num--;
                    low += den;
                }
                while (low >= den);
            }
            bufNum.Low64 = low;
            return num;
        }
References System.Runtime.Serialization.Dictionary, and System.Decimal.DecCalc.UInt32x32To64().
Referenced by System.Decimal.DecCalc.VarDecDiv(), and System.Decimal.DecCalc.VarDecModFull().