Terraria: System.Decimal.DecCalc.SearchScale
SearchScale()
static int System.Decimal.DecCalc.SearchScale (ref Buf12 bufQuo, int scale) inline static private
Definition at line 635 of file Decimal.cs.
        {
            uint u = bufQuo.U2;
            ulong low = bufQuo.Low64;
            int num = 0;
            if (u <= 429496729)
            {
                PowerOvfl[] powerOvflValues = PowerOvflValues;
                if (scale > 19)
                {
                    num = 28 - scale;
                    if (u < powerOvflValues[num - 1].Hi)
                    {
                        goto IL_00d1;
                    }
                }
                else if (u < 4 || (u == 4 && low <= 5441186219426131129L))
                {
                    return 9;
                }
                if (u > 42949)
                {
                    if (u > 4294967)
                    {
                        num = 2;
                        if (u > 42949672)
{
                            num--;
                        }
                    }
                    else
                    {
                        num = 4;
                        if (u > 429496)
{
                            num--;
                        }
                    }
                }
                else if (u > 429)
                {
                    num = 6;
                    if (u > 4294)
                    {
                        num--;
                    }
                }
                else
                {
                    num = 8;
                    if (u > 42)
                    {
                        num--;
                    }
                }
                if (u == powerOvflValues[num - 1].Hi && low > powerOvflValues[num - 1].MidLo)
                {
                    num--;
                }
            }
            goto IL_00d1;
            IL_00d1:
            if (num + scale < 0)
            {
                Number.ThrowOverflowException(TypeCode.Decimal);
            }
            return num;
        }
References System.Runtime.Serialization.Dictionary, System.L, System.Decimal.DecCalc.PowerOvflValues, and System.Number.ThrowOverflowException().
Referenced by System.Decimal.DecCalc.VarDecDiv(), and System.Decimal.DecCalc.VarDecMod().