Terraria: System.Decimal.DecCalc.VarCyFromDec
VarCyFromDec()
static long System.Decimal.DecCalc.VarCyFromDec (ref DecCalc pdecIn) inline static package
Definition at line 996 of file Decimal.cs.
        {
            int num = pdecIn.Scale - 4;
            long num4;
            if (num < 0)
            {
                if (pdecIn.High == 0)
                {
                    uint a = s_powers10[-num];
                    ulong num2 = UInt32x32To64(a, pdecIn.Mid);
                    if (num2 <= uint.MaxValue)
                    {
                        ulong num3 = UInt32x32To64(a, pdecIn.Low);
                        num3 += (num2 <<= 32);
                        if (num3 >= num2)
{
                            num4 = (long)num3;
                            goto IL_006d;
                        }
                    }
                }
            }
            else
            {
                if (num != 0)
                {
                    InternalRound(ref pdecIn, (uint)num, MidpointRounding.ToEven);
                }
                if (pdecIn.High == 0)
                {
                    num4 = (long)pdecIn.Low64;
                    goto IL_006d;
                }
            }
            goto IL_0093;
            IL_0093:
            throw new OverflowException(SR.Overflow_Currency);
            IL_006d:
            if (num4 >= 0 || (num4 == long.MinValue && pdecIn.IsNegative))
            {
                if (pdecIn.IsNegative)
                {
                    num4 = -num4;
                }
                return num4;
            }
            goto IL_0093;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.InternalRound(), System.Decimal.MinValue, System.SR.Overflow_Currency, System.Decimal.DecCalc.s_powers10, and System.Decimal.DecCalc.UInt32x32To64().
Referenced by System.Decimal.ToOACurrency().