Terraria: System.Decimal.DecCalc.VarDecModFull
VarDecModFull()
static unsafe void System.Decimal.DecCalc.VarDecModFull (ref DecCalc d1, ref DecCalc d2, int scale) inline static private
Definition at line 1859 of file Decimal.cs.
        {
            uint num = d2.High;
            if (num == 0)
            {
                num = d2.Mid;
            }
            int num2 = BitOperations.LeadingZeroCount(num);
            Unsafe.SkipInit<Buf28>(out var value);
            value.Buf24.Low64 = d1.Low64 << num2;
            value.Buf24.Mid64 = d1.Mid + ((ulong)d1.High << 32) >> 32 - num2;
            uint num3 = 3u;
            while (scale < 0)
            {
                uint b = ((scale <= -9) ? 1000000000u : s_powers10[-scale]);
                uint* ptr = (uint*)(&value);
                ulong num4 = UInt32x32To64(value.Buf24.U0, b);
                value.Buf24.U0 = (uint)num4;
                for (int i = 1; i <= num3; i++)
                {
                    num4 >>= 32;
                    num4 += UInt32x32To64(ptr[i], b);
                    ptr[i] = (uint)num4;
                }
                if (num4 > int.MaxValue)
                {
                    ptr[++num3] = (uint)(num4 >> 32);
                }
                scale += 9;
            }
            if (d2.High == 0)
            {
                ulong den = d2.Low64 << num2;
                switch (num3)
                {
                case 6u:
                    Div96By64(ref *(Buf12*)(&value.Buf24.U4), den);
                    goto case 5u;
                case 5u:
                    Div96By64(ref *(Buf12*)(&value.Buf24.U3), den);
                    goto case 4u;
                case 4u:
                    Div96By64(ref *(Buf12*)(&value.Buf24.U2), den);
                    break;
                }
                Div96By64(ref *(Buf12*)(&value.Buf24.U1), den);
                Div96By64(ref *(Buf12*)(&value), den);
                d1.Low64 = value.Buf24.Low64 >> num2;
                d1.High = 0u;
                return;
            }
            Unsafe.SkipInit<Buf12>(out var value2);
            value2.Low64 = d2.Low64 << num2;
            value2.U2 = (uint)(d2.Mid + ((ulong)d2.High << 32) >> 32 - num2);
            switch (num3)
            {
            case 6u:
                Div128By96(ref *(Buf16*)(&value.Buf24.U3), ref value2);
                goto case 5u;
            case 5u:
                Div128By96(ref *(Buf16*)(&value.Buf24.U2), ref value2);
                goto case 4u;
            case 4u:
                Div128By96(ref *(Buf16*)(&value.Buf24.U1), ref value2);
                break;
            }
            Div128By96(ref *(Buf16*)(&value), ref value2);
            d1.Low64 = (value.Buf24.Low64 >> num2) + ((ulong)value.Buf24.U2 << 32 - num2 << 32);
            d1.High = value.Buf24.U2 >> num2;
        }
References System.Runtime.Serialization.Dictionary, System.Decimal.DecCalc.Div128By96(), System.Decimal.DecCalc.Div96By64(), System.Numerics.BitOperations.LeadingZeroCount(), System.Decimal.MaxValue, System.Decimal.DecCalc.s_powers10, System.Decimal.DecCalc.UInt32x32To64(), and System.value.
Referenced by System.Decimal.DecCalc.VarDecMod().