Terraria: DeadMansChestBiome.FindDartTrapSpots
FindDartTrapSpots()
void DeadMansChestBiome.FindDartTrapSpots (Point position) inline private
     {
         int num = GenBase._random.Next(_numberOfDartTraps);
         int num2 = ((GenBase._random.Next(2) != 0) ? 1 : (-1));
         int steps = -1;
         for (int i = 0; i < num; i++)
         {
             bool num3 = FindDartTrapSpotSingle(position, num2);
             num2 *= -1;
             position.Y--;
             if (num3)
             {
                 steps = i;
             }
         }
         _wirePlacementSpots.Add(new WirePlacementAttempt(new Point(position.X, position.Y + num), 0, -1, steps));
     }
References _numberOfDartTraps, GenBase._random, _wirePlacementSpots, FindDartTrapSpotSingle(), and UnifiedRandom.Next().
Referenced by GetPossibleChestsToTrapify(), and Place().