Terraria: DeadMansChestBiome.ActuallyPlaceBoulderTrap
ActuallyPlaceBoulderTrap()
void DeadMansChestBiome.ActuallyPlaceBoulderTrap (Point position, int yPush, int requiredHeight, int bestType) inline private
     {
         for (int i = position.X; i < position.X + 2; i++)
         {
             for (int j = position.Y - requiredHeight; j <= position.Y + 2; j++)
             {
                 Tile tile = Main.tile[i, j];
                 if (j < position.Y - requiredHeight + 2)
                 {
                     tile.ClearTile();
                 }
                 else if (j <= position.Y)
                 {
                     if (!tile.active())
                     {
                         tile.active(active: true);
                         tile.type = (ushort)bestType;
                     }
                     tile.slope(0);
                     tile.halfBrick(halfBrick: false);
                     tile.actuator(actuator: true);
                     tile.wire(wire: true);
                     WorldGen.TileFrame(i, j, resetFrame: true);
                 }
                 else
                 {
                     tile.ClearTile();
                 }
             }
         }
         int num = position.X + 1;
         int num2 = position.Y - requiredHeight + 1;
         int num3 = 3;
         int num4 = num - num3;
         int num5 = num2 - num3;
         int num6 = num + num3 - 1;
         int num7 = num2 + num3 - 1;
         for (int k = num4; k <= num6; k++)
         {
             for (int l = num5; l <= num7; l++)
             {
                 if (Main.tile[k, l].type != 138)
                 {
                     Main.tile[k, l].type = 1;
                 }
             }
         }
         WorldGen.PlaceTile(num, num2, 138);
         PlaceWireLine(position, 0, 1, yPush);
     }
References Tile.active(), Tile.actuator(), Tile.ClearTile(), Tile.halfBrick(), WorldGen.PlaceTile(), PlaceWireLine(), Tile.slope(), Main.tile, WorldGen.TileFrame(), Tile.type, and Tile.wire().
Referenced by Place().