Terraria: DeadMansChestBiome.FindBoulderTrapSpots
FindBoulderTrapSpots()
void DeadMansChestBiome.FindBoulderTrapSpots (Point position) inline private
     {
         int x = position.X;
         int num = GenBase._random.Next(_numberOfBoulderTraps);
         int num2 = GenBase._random.Next(_numberOfStepsBetweenBoulderTraps);
         x -= num / 2 * num2;
         int num3 = position.Y - 6;
         for (int i = 0; i <= num; i++)
         {
             FindBoulderTrapSpot(new Point(x, num3));
             x += num2;
         }
         if (_boulderPlacementSpots.Count <= 0)
         {
             return;
         }
         int num4 = _boulderPlacementSpots[0].position.X;
         int num5 = _boulderPlacementSpots[0].position.X;
         for (int j = 1; j < _boulderPlacementSpots.Count; j++)
         {
             int x2 = _boulderPlacementSpots[j].position.X;
             if (num4 > x2)
             {
                 num4 = x2;
             }
             if (num5 < x2)
             {
                 num5 = x2;
             }
         }
         if (num4 > position.X)
         {
             num4 = position.X;
         }
         if (num5 < position.X)
         {
             num5 = position.X;
         }
         _wirePlacementSpots.Add(new WirePlacementAttempt(new Point(num4, num3 - 1), 1, 0, num5 - num4));
         _wirePlacementSpots.Add(new WirePlacementAttempt(position, 0, -1, 7));
     }
References _boulderPlacementSpots, _numberOfBoulderTraps, _numberOfStepsBetweenBoulderTraps, GenBase._random, _wirePlacementSpots, FindBoulderTrapSpot(), and UnifiedRandom.Next().
Referenced by GetPossibleChestsToTrapify(), and Place().