Terraria: System.Net.Http.HttpEnvironmentProxy.GetUriFromString
GetUriFromString()
static Uri System.Net.Http.HttpEnvironmentProxy.GetUriFromString (string value) inline static private
Definition at line 35 of file HttpEnvironmentProxy.cs.
    {
        if (string.IsNullOrEmpty(value))
        {
            return null;
        }
        if (value.StartsWith("http://", StringComparison.OrdinalIgnoreCase))
        {
            value = value.Substring(7);
        }
        string text = null;
        string text2 = null;
        ushort result = 80;
        int num = value.LastIndexOf('@');
        if (num != -1)
        {
            string text3 = value.Substring(0, num);
            try
            {
                text3 = Uri.UnescapeDataString(text3);
            }
            catch
            {
            }
            value = value.Substring(num + 1);
            num = text3.IndexOf(':');
            if (num == -1)
            {
                text = text3;
            }
            else
            {
                text = text3.Substring(0, num);
                text2 = text3.Substring(num + 1);
            }
        }
        int num2 = value.IndexOf(']');
        num = value.LastIndexOf(':');
        string host;
        if (num == -1 || (num2 != -1 && num < num2))
        {
            host = value;
        }
        else
        {
            host = value.Substring(0, num);
            int i;
            for (i = num + 1; i < value.Length && char.IsDigit(value[i]); i++)
            {
            }
            if (!ushort.TryParse(value.AsSpan(num + 1, i - num - 1), out result))
            {
                return null;
            }
        }
        try
        {
            UriBuilder uriBuilder = new UriBuilder("http", host, result);
            if (text != null)
            {
                uriBuilder.UserName = Uri.EscapeDataString(text);
            }
            if (text2 != null)
            {
                uriBuilder.Password = Uri.EscapeDataString(text2);
            }
            return uriBuilder.Uri;
        }
        catch
        {
        }
        return null;
    }
References System.Uri.EscapeDataString(), System.text, System.Uri.UnescapeDataString(), System.UriBuilder.Uri, and System.value.
Referenced by System.Net.Http.HttpEnvironmentProxy.TryCreate().