Terraria: System.DateTimeFormat.Format
Format() [1/2]
static string System.DateTimeFormat.Format (DateTime dateTime, string format, IFormatProvider provider) inline static package
Definition at line 591 of file DateTimeFormat.cs.
    {
        return Format(dateTime, format, provider, new TimeSpan(long.MinValue));
    }
References System.format, and System.Format.
Referenced by System.DateTime.ToLongDateString(), System.DateTime.ToLongTimeString(), System.DateTime.ToShortDateString(), System.DateTime.ToShortTimeString(), System.DateTime.ToString(), System.DateTimeOffset.ToString(), System.DateTimeOffset.ToString(), System.DateTime.ToString(), System.DateTime.ToString(), System.DateTimeOffset.ToString(), System.DateTimeOffset.ToString(), System.DateOnly.ToString(), System.DateTime.ToString(), and System.TimeOnly.ToString().