Terraria: System.DateTimeFormat.ParseQuoteString
ParseQuoteString()
static int System.DateTimeFormat.ParseQuoteString (ReadOnlySpan< char > format, int pos, StringBuilder result) inline static package
Definition at line 107 of file DateTimeFormat.cs.
    {
        int length = format.Length;
        int num = pos;
        char c = format[pos++];
        bool flag = false;
        while (pos < length)
        {
            char c2 = format[pos++];
            if (c2 == c)
            {
                flag = true;
                break;
            }
            if (c2 == '\\')
            {
                if (pos >= length)
                {
                    throw new FormatException(SR.Format_InvalidString);
                }
                result.Append(format[pos++]);
            }
            else
            {
                result.Append(c2);
            }
        }
        if (!flag)
        {
            throw new FormatException(SR.Format(SR.Format_BadQuote, c));
        }
        return pos - num;
    }
References System.Text.StringBuilder.Append(), System.SR.Format(), System.format, System.SR.Format_BadQuote, System.SR.Format_InvalidString, and System.length.
Referenced by System.DateTimeFormat.FormatCustomized(), and System.Globalization.TimeSpanFormat.FormatCustomized().