Terraria: System.DateTimeFormat.IsValidCustomDateFormat
IsValidCustomDateFormat()
static bool System.DateTimeFormat.IsValidCustomDateFormat (ReadOnlySpan< char > format, bool throwOnError) inline static package
Definition at line 687 of file DateTimeFormat.cs.
    {
        int i = 0;
        while (i < format.Length)
        {
            switch (format[i])
            {
            case '\\':
                if (i == format.Length - 1)
                {
                    if (throwOnError)
                    {
                        throw new FormatException(SR.Format_InvalidString);
                    }
                    return false;
                }
                i += 2;
                break;
            case '"':
            case '\'':
            {
                char c;
                for (c = format[i++]; i < format.Length && format[i] != c; i++)
                {
                }
                if (i >= format.Length)
                {
                    if (throwOnError)
                    {
                        throw new FormatException(SR.Format(SR.Format_BadQuote, c));
                    }
                    return false;
                }
                i++;
                break;
            }
            case ':':
            case 'F':
            case 'H':
            case 'K':
            case 'f':
            case 'h':
            case 'm':
            case 's':
            case 't':
            case 'z':
                if (throwOnError)
                {
                    throw new FormatException(SR.Format_InvalidString);
                }
                return false;
            default:
                i++;
                break;
            }
        }
        return true;
    }
References System.SR.Format(), System.format, System.SR.Format_BadQuote, and System.SR.Format_InvalidString.
Referenced by System.DateOnly.ToString(), and System.DateOnly.TryFormat().