Terraria: System.DateTimeFormat.ExpandPredefinedFormat
ExpandPredefinedFormat()
static string System.DateTimeFormat.ExpandPredefinedFormat (ReadOnlySpan< char > format, ref DateTime dateTime, ref DateTimeFormatInfo dtfi, TimeSpan offset) inline static private
Definition at line 555 of file DateTimeFormat.cs.
    {
        switch (format[0])
        {
        case 'O':
        case 'o':
            dtfi = DateTimeFormatInfo.InvariantInfo;
            break;
        case 'R':
        case 'r':
        case 'u':
            if (offset.Ticks != long.MinValue)
            {
                dateTime -= offset;
            }
            dtfi = DateTimeFormatInfo.InvariantInfo;
            break;
        case 's':
            dtfi = DateTimeFormatInfo.InvariantInfo;
            break;
        case 'U':
            if (offset.Ticks != long.MinValue)
            {
                throw new FormatException(SR.Format_InvalidString);
            }
            dtfi = (DateTimeFormatInfo)dtfi.Clone();
            if (dtfi.Calendar.GetType() != typeof(GregorianCalendar))
            {
                dtfi.Calendar = GregorianCalendar.GetDefaultInstance();
            }
            dateTime = dateTime.ToUniversalTime();
            break;
        }
        return GetRealFormat(format, dtfi);
    }
References System.format, System.SR.Format_InvalidString, System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTimeFormat.GetRealFormat(), System.Globalization.DateTimeFormatInfo.InvariantInfo, and System.offset.
Referenced by System.DateTimeFormat.FormatStringBuilder().