Terraria: System.DateTimeFormat.IsValidCustomTimeFormat
IsValidCustomTimeFormat()
static bool System.DateTimeFormat.IsValidCustomTimeFormat (ReadOnlySpan< char > format, bool throwOnError) inline static package
Definition at line 746 of file DateTimeFormat.cs.
    {
        int length = format.Length;
        int i = 0;
        while (i < length)
        {
            switch (format[i])
            {
            case '\\':
                if (i == length - 1)
                {
                    if (throwOnError)
                    {
                        throw new FormatException(SR.Format_InvalidString);
                    }
                    return false;
                }
                i += 2;
                break;
            case '"':
            case '\'':
            {
                char c;
                for (c = format[i++]; i < length && format[i] != c; i++)
                {
                }
                if (i >= length)
                {
                    if (throwOnError)
                    {
                        throw new FormatException(SR.Format(SR.Format_BadQuote, c));
                    }
                    return false;
                }
                i++;
                break;
            }
            case '/':
            case 'M':
            case 'd':
            case 'k':
            case 'y':
            case 'z':
                if (throwOnError)
                {
                    throw new FormatException(SR.Format_InvalidString);
                }
                return false;
            default:
                i++;
                break;
            }
        }
        return true;
    }
References System.SR.Format(), System.format, System.SR.Format_BadQuote, System.SR.Format_InvalidString, and System.length.
Referenced by System.TimeOnly.ToString(), and System.TimeOnly.TryFormat().