Terraria: System.DateTimeFormat.TryFormat
TryFormat() [2/2]
static bool System.DateTimeFormat.TryFormat (DateTime dateTime, Span< char > destination, out int charsWritten, ReadOnlySpan< char > format, IFormatProvider provider, TimeSpan offset) inline static package
Definition at line 627 of file DateTimeFormat.cs.
    {
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                return TryFormatO(dateTime, offset, destination, out charsWritten);
            case 'R':
            case 'r':
                return TryFormatR(dateTime, offset, destination, out charsWritten);
            }
        }
        DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(provider);
        StringBuilder stringBuilder = FormatStringBuilder(dateTime, format, instance, offset);
        bool flag = stringBuilder.Length <= destination.Length;
        if (flag)
        {
            stringBuilder.CopyTo(0, destination, stringBuilder.Length);
            charsWritten = stringBuilder.Length;
        }
        else
        {
            charsWritten = 0;
        }
        StringBuilderCache.Release(stringBuilder);
        return flag;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.CopyTo(), System.destination, System.format, System.DateTimeFormat.FormatStringBuilder(), System.offset, System.Text.StringBuilderCache.Release(), System.DateTimeFormat.TryFormatO(), and System.DateTimeFormat.TryFormatR().