Terraria: System.DateTimeFormat.FormatCustomizedTimeZone
FormatCustomizedTimeZone()
static void System.DateTimeFormat.FormatCustomizedTimeZone (DateTime dateTime, TimeSpan offset, int tokenLen, bool timeOnly, StringBuilder result) inline static private
Definition at line 428 of file DateTimeFormat.cs.
    {
        if (offset.Ticks == long.MinValue)
        {
            offset = ((timeOnly && dateTime.Ticks < 864000000000L) ? TimeZoneInfo.GetLocalUtcOffset(DateTime.Now, TimeZoneInfoOptions.NoThrowOnInvalidTime) : ((dateTime.Kind != DateTimeKind.Utc) ? TimeZoneInfo.GetLocalUtcOffset(dateTime, TimeZoneInfoOptions.NoThrowOnInvalidTime) : default(TimeSpan)));
        }
        if (offset.Ticks >= 0)
        {
            result.Append('+');
        }
        else
        {
            result.Append('-');
            offset = offset.Negate();
        }
        StringBuilder stringBuilder;
        IFormatProvider invariantCulture;
        if (tokenLen <= 1)
        {
            stringBuilder = result;
            StringBuilder stringBuilder2 = stringBuilder;
            invariantCulture = CultureInfo.InvariantCulture;
            IFormatProvider provider = invariantCulture;
            StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder, invariantCulture);
            handler.AppendFormatted(offset.Hours, "0");
            stringBuilder2.Append(provider, ref handler);
            return;
        }
        stringBuilder = result;
        StringBuilder stringBuilder3 = stringBuilder;
        invariantCulture = CultureInfo.InvariantCulture;
        IFormatProvider provider2 = invariantCulture;
        StringBuilder.AppendInterpolatedStringHandler handler2 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder, invariantCulture);
        handler2.AppendFormatted(offset.Hours, "00");
        stringBuilder3.Append(provider2, ref handler2);
        if (tokenLen >= 3)
        {
            stringBuilder = result;
            StringBuilder stringBuilder4 = stringBuilder;
            invariantCulture = CultureInfo.InvariantCulture;
            IFormatProvider provider3 = invariantCulture;
            StringBuilder.AppendInterpolatedStringHandler handler3 = new StringBuilder.AppendInterpolatedStringHandler(1, 1, stringBuilder, invariantCulture);
            handler3.AppendLiteral(":");
            handler3.AppendFormatted(offset.Minutes, "00");
            stringBuilder4.Append(provider3, ref handler3);
        }
    }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.TimeZoneInfo.GetLocalUtcOffset(), System.Globalization.CultureInfo.InvariantCulture, System.L, System.DateTime.Now, and System.offset.
Referenced by System.DateTimeFormat.FormatCustomized().