Terraria: System.DateTimeFormat.TryFormatR
TryFormatR()
static bool System.DateTimeFormat.TryFormatR (DateTime dateTime, TimeSpan offset, Span< char > destination, out int charsWritten) inline static private
Definition at line 943 of file DateTimeFormat.cs.
    {
        if (destination.Length <= 28)
        {
            charsWritten = 0;
            return false;
        }
        if (offset.Ticks != long.MinValue)
        {
            dateTime -= offset;
        }
        dateTime.GetDate(out var year, out var month, out var day);
        dateTime.GetTime(out var hour, out var minute, out var second);
        string text = InvariantAbbreviatedDayNames[(int)dateTime.DayOfWeek];
        string text2 = InvariantAbbreviatedMonthNames[month - 1];
        destination[0] = text[0];
        destination[1] = text[1];
        destination[2] = text[2];
        destination[3] = ',';
        destination[4] = ' ';
        WriteTwoDecimalDigits((uint)day, destination, 5);
        destination[7] = ' ';
        destination[8] = text2[0];
        destination[9] = text2[1];
        destination[10] = text2[2];
        destination[11] = ' ';
        WriteFourDecimalDigits((uint)year, destination, 12);
        destination[16] = ' ';
        WriteTwoDecimalDigits((uint)hour, destination, 17);
        destination[19] = ':';
        WriteTwoDecimalDigits((uint)minute, destination, 20);
        destination[22] = ':';
        WriteTwoDecimalDigits((uint)second, destination, 23);
        destination[25] = ' ';
        destination[26] = 'G';
        destination[27] = 'M';
        destination[28] = 'T';
        charsWritten = 29;
        return true;
    }
References System.destination, System.DateTimeFormat.InvariantAbbreviatedDayNames, System.DateTimeFormat.InvariantAbbreviatedMonthNames, System.offset, System.text, System.DateTimeFormat.WriteFourDecimalDigits(), System.DateTimeFormat.WriteTwoDecimalDigits(), and System.year.
Referenced by System.DateTimeFormat.Format(), and System.DateTimeFormat.TryFormat().