Terraria: System.DateTimeFormat.TryFormatDateOnlyR
TryFormatDateOnlyR()
static bool System.DateTimeFormat.TryFormatDateOnlyR (DayOfWeek dayOfWeek, int year, int month, int day, Span< char > destination) inline static package
Definition at line 846 of file DateTimeFormat.cs.
    {
        if (destination.Length < 16)
        {
            return false;
        }
        string text = InvariantAbbreviatedDayNames[(int)dayOfWeek];
        string text2 = InvariantAbbreviatedMonthNames[month - 1];
        destination[0] = text[0];
        destination[1] = text[1];
        destination[2] = text[2];
        destination[3] = ',';
        destination[4] = ' ';
        WriteTwoDecimalDigits((uint)day, destination, 5);
        destination[7] = ' ';
        destination[8] = text2[0];
        destination[9] = text2[1];
        destination[10] = text2[2];
        destination[11] = ' ';
        WriteFourDecimalDigits((uint)year, destination, 12);
        return true;
    }
References System.destination, System.DateTimeFormat.InvariantAbbreviatedDayNames, System.DateTimeFormat.InvariantAbbreviatedMonthNames, System.text, System.DateTimeFormat.WriteFourDecimalDigits(), System.DateTimeFormat.WriteTwoDecimalDigits(), and System.year.
Referenced by System.DateOnly.ToString(), and System.DateOnly.TryFormat().