Terraria: System.DateTimeFormat.TryFormat
TryFormat() [1/2]
static bool System.DateTimeFormat.TryFormat (DateTime dateTime, Span< char > destination, out int charsWritten, ReadOnlySpan< char > format, IFormatProvider provider) inline static package
Definition at line 622 of file DateTimeFormat.cs.
    {
        return TryFormat(dateTime, destination, out charsWritten, format, provider, new TimeSpan(long.MinValue));
    }
References System.destination, System.format, and System.DateTimeFormat.TryFormat().
Referenced by System.DateTimeFormat.TryFormat(), System.DateTimeOffset.TryFormat(), System.DateOnly.TryFormat(), System.DateTime.TryFormat(), and System.TimeOnly.TryFormat().