Terraria: System.DateTimeFormat.FormatCustomized
FormatCustomized()
static StringBuilder System.DateTimeFormat.FormatCustomized (DateTime dateTime, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, TimeSpan offset, StringBuilder result) inline static private
Definition at line 187 of file DateTimeFormat.cs.
    {
        Calendar calendar = dtfi.Calendar;
        bool flag = false;
        if (result == null)
        {
            flag = true;
            result = StringBuilderCache.Acquire();
        }
        bool flag2 = calendar.ID == CalendarId.HEBREW;
        bool flag3 = calendar.ID == CalendarId.JAPAN;
        bool timeOnly = true;
        int num;
        for (int i = 0; i < format.Length; i += num)
        {
            char c = format[i];
            switch (c)
            {
            case 'g':
                num = ParseRepeatPattern(format, i, c);
                result.Append(dtfi.GetEraName(calendar.GetEra(dateTime)));
                break;
            case 'h':
            {
                num = ParseRepeatPattern(format, i, c);
                int num3 = dateTime.Hour % 12;
                if (num3 == 0)
                {
                    num3 = 12;
                }
                FormatDigits(result, num3, num);
                break;
            }
            case 'H':
                num = ParseRepeatPattern(format, i, c);
                FormatDigits(result, dateTime.Hour, num);
                break;
            case 'm':
                num = ParseRepeatPattern(format, i, c);
                FormatDigits(result, dateTime.Minute, num);
                break;
            case 's':
                num = ParseRepeatPattern(format, i, c);
                FormatDigits(result, dateTime.Second, num);
                break;
            case 'F':
            case 'f':
                num = ParseRepeatPattern(format, i, c);
                if (num <= 7)
                {
                    long num4 = dateTime.Ticks % 10000000;
                    num4 /= (long)Math.Pow(10.0, 7 - num);
                    if (c == 'f')
                    {
                        result.AppendSpanFormattable((int)num4, fixedNumberFormats[num - 1], CultureInfo.InvariantCulture);
                        break;
                    }
                    int num5 = num;
                    while (num5 > 0 && num4 % 10 == 0L)
                    {
                        num4 /= 10;
                        num5--;
                    }
                    if (num5 > 0)
                    {
                        result.AppendSpanFormattable((int)num4, fixedNumberFormats[num5 - 1], CultureInfo.InvariantCulture);
                    }
                    else if (result.Length > 0 && result[result.Length - 1] == '.')
                    {
                        result.Remove(result.Length - 1, 1);
                    }
                    break;
                }
                if (flag)
                {
                    StringBuilderCache.Release(result);
                }
                throw new FormatException(SR.Format_InvalidString);
            case 't':
                num = ParseRepeatPattern(format, i, c);
                if (num == 1)
                {
                    if (dateTime.Hour < 12)
                    {
                        if (dtfi.AMDesignator.Length >= 1)
{
                            result.Append(dtfi.AMDesignator[0]);
                        }
                    }
                    else if (dtfi.PMDesignator.Length >= 1)
                    {
                        result.Append(dtfi.PMDesignator[0]);
                    }
                }
                else
                {
                    result.Append((dateTime.Hour < 12) ? dtfi.AMDesignator : dtfi.PMDesignator);
                }
                break;
            case 'd':
                num = ParseRepeatPattern(format, i, c);
                if (num <= 2)
                {
                    int dayOfMonth = calendar.GetDayOfMonth(dateTime);
                    if (flag2)
                    {
                        HebrewFormatDigits(result, dayOfMonth);
                    }
                    else
                    {
                        FormatDigits(result, dayOfMonth, num);
                    }
                }
                else
                {
                    int dayOfWeek = (int)calendar.GetDayOfWeek(dateTime);
                    result.Append(FormatDayOfWeek(dayOfWeek, num, dtfi));
                }
                timeOnly = false;
                break;
            case 'M':
            {
                num = ParseRepeatPattern(format, i, c);
                int month = calendar.GetMonth(dateTime);
                if (num <= 2)
                {
                    if (flag2)
                    {
                        HebrewFormatDigits(result, month);
                    }
                    else
                    {
                        FormatDigits(result, month, num);
                    }
                }
                else if (flag2)
                {
                    result.Append(FormatHebrewMonthName(dateTime, month, num, dtfi));
                }
                else if ((dtfi.FormatFlags & DateTimeFormatFlags.UseGenitiveMonth) != 0)
                {
                    result.Append(dtfi.InternalGetMonthName(month, IsUseGenitiveForm(format, i, num, 'd') ? MonthNameStyles.Genitive : MonthNameStyles.Regular, num == 3));
                }
                else
                {
                    result.Append(FormatMonth(month, num, dtfi));
                }
                timeOnly = false;
                break;
            }
            case 'y':
            {
                int year = calendar.GetYear(dateTime);
                num = ParseRepeatPattern(format, i, c);
                if (flag3 && !LocalAppContextSwitches.FormatJapaneseFirstYearAsANumber && year == 1 && ((i + num < format.Length && format[i + num] == '年') || (i + num < format.Length - 1 && format[i + num] == '\'' && format[i + num + 1] == '年')))
                {
                    result.Append("元"[0]);
                }
                else if (dtfi.HasForceTwoDigitYears)
                {
                    FormatDigits(result, year, (num <= 2) ? num : 2);
                }
                else if (calendar.ID == CalendarId.HEBREW)
                {
                    HebrewFormatDigits(result, year);
                }
                else if (num <= 2)
                {
                    FormatDigits(result, year % 100, num);
                }
                else if (num <= 16)
                {
                    FormatDigits(result, year, num, overrideLengthLimit: true);
                }
                else
                {
                    result.Append(year.ToString("D" + num.ToString(CultureInfo.InvariantCulture), CultureInfo.InvariantCulture));
                }
                timeOnly = false;
                break;
            }
            case 'z':
                num = ParseRepeatPattern(format, i, c);
                FormatCustomizedTimeZone(dateTime, offset, num, timeOnly, result);
                break;
            case 'K':
                num = 1;
                FormatCustomizedRoundripTimeZone(dateTime, offset, result);
                break;
            case ':':
                result.Append(dtfi.TimeSeparator);
                num = 1;
                break;
            case '/':
                result.Append(dtfi.DateSeparator);
                num = 1;
                break;
            case '"':
            case '\'':
                num = ParseQuoteString(format, i, result);
                break;
            case '%':
            {
                int num2 = ParseNextChar(format, i);
                if (num2 >= 0 && num2 != 37)
                {
                    char reference = (char)num2;
                    StringBuilder stringBuilder = FormatCustomized(dateTime, MemoryMarshal.CreateReadOnlySpan(ref reference, 1), dtfi, offset, result);
                    num = 2;
                    break;
                }
                if (flag)
                {
                    StringBuilderCache.Release(result);
                }
                throw new FormatException(SR.Format_InvalidString);
            }
            case '\\':
            {
                int num2 = ParseNextChar(format, i);
                if (num2 >= 0)
                {
                    result.Append((char)num2);
                    num = 2;
                    break;
                }
                if (flag)
                {
                    StringBuilderCache.Release(result);
                }
                throw new FormatException(SR.Format_InvalidString);
            }
            default:
                result.Append(c);
                num = 1;
                break;
            }
        }
        return result;
    }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.DateTimeFormat.fixedNumberFormats, System.format, System.SR.Format_InvalidString, System.DateTimeFormat.FormatCustomized(), System.DateTimeFormat.FormatCustomizedRoundripTimeZone(), System.DateTimeFormat.FormatCustomizedTimeZone(), System.DateTimeFormat.FormatDayOfWeek(), System.DateTimeFormat.FormatDigits(), System.DateTimeFormat.FormatHebrewMonthName(), System.LocalAppContextSwitches.FormatJapaneseFirstYearAsANumber, System.DateTimeFormat.FormatMonth(), System.Globalization.Calendar.GetDayOfMonth(), System.Globalization.Calendar.GetDayOfWeek(), System.Globalization.Calendar.GetEra(), System.Globalization.Calendar.GetMonth(), System.Globalization.Calendar.GetYear(), System.DateTimeFormat.HebrewFormatDigits(), System.Globalization.Calendar.ID, System.Globalization.CultureInfo.InvariantCulture, System.DateTimeFormat.IsUseGenitiveForm(), System.L, System.Text.StringBuilder.Length, System.offset, System.DateTimeFormat.ParseNextChar(), System.DateTimeFormat.ParseQuoteString(), System.DateTimeFormat.ParseRepeatPattern(), System.Math.Pow(), System.Text.StringBuilderCache.Release(), System.Text.StringBuilder.Remove(), and System.year.
Referenced by System.DateTimeFormat.FormatCustomized(), and System.DateTimeFormat.FormatStringBuilder().