Terraria: System.DateTimeFormat.TryFormatO
TryFormatO()
static bool System.DateTimeFormat.TryFormatO (DateTime dateTime, TimeSpan offset, Span< char > destination, out int charsWritten) inline static private
Definition at line 869 of file DateTimeFormat.cs.
    {
        int num = 27;
        DateTimeKind dateTimeKind = DateTimeKind.Local;
        if (offset.Ticks == long.MinValue)
        {
            dateTimeKind = dateTime.Kind;
            switch (dateTimeKind)
            {
            case DateTimeKind.Local:
                offset = TimeZoneInfo.Local.GetUtcOffset(dateTime);
                num += 6;
                break;
            case DateTimeKind.Utc:
                num++;
                break;
            }
        }
        else
        {
            num += 6;
        }
        if (destination.Length < num)
        {
            charsWritten = 0;
            return false;
        }
        charsWritten = num;
        _ = ref destination[26];
        dateTime.GetDate(out var year, out var month, out var day);
        dateTime.GetTimePrecise(out var hour, out var minute, out var second, out var tick);
        WriteFourDecimalDigits((uint)year, destination);
        destination[4] = '-';
        WriteTwoDecimalDigits((uint)month, destination, 5);
        destination[7] = '-';
        WriteTwoDecimalDigits((uint)day, destination, 8);
        destination[10] = 'T';
        WriteTwoDecimalDigits((uint)hour, destination, 11);
        destination[13] = ':';
        WriteTwoDecimalDigits((uint)minute, destination, 14);
        destination[16] = ':';
        WriteTwoDecimalDigits((uint)second, destination, 17);
        destination[19] = '.';
        WriteDigits((uint)tick, destination.Slice(20, 7));
        switch (dateTimeKind)
        {
        case DateTimeKind.Local:
        {
            int num2 = (int)(offset.Ticks / 600000000);
            char c;
            if (num2 < 0)
            {
                c = '-';
                num2 = -num2;
            }
            else
            {
                c = '+';
            }
            int result;
            int value = Math.DivRem(num2, 60, out result);
            WriteTwoDecimalDigits((uint)result, destination, 31);
            destination[30] = ':';
            WriteTwoDecimalDigits((uint)value, destination, 28);
            destination[27] = c;
            break;
        }
        case DateTimeKind.Utc:
            destination[27] = 'Z';
            break;
        }
        return true;
    }
References System.destination, System.Math.DivRem(), System.TimeZoneInfo.Local, System.offset, System.value, System.DateTimeFormat.WriteDigits(), System.DateTimeFormat.WriteFourDecimalDigits(), System.DateTimeFormat.WriteTwoDecimalDigits(), and System.year.
Referenced by System.DateTimeFormat.Format(), and System.DateTimeFormat.TryFormat().