Terraria: System.Linq.Parallel.SingleQueryOperator.SingleQueryOperatorEnumerator.MoveNext
MoveNext() [1/2]
override bool System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >.MoveNext ([AllowNull] ref TSource currentElement, ref int currentKey) inline package
Definition at line 28 of file SingleQueryOperator.cs.
        {
            if (_alreadySearched)
            {
                if (_yieldExtra)
                {
                    _yieldExtra = false;
                    currentElement = default(TSource);
                    currentKey = 0;
                    return true;
                }
                return false;
            }
            bool flag = false;
            TSource currentElement2 = default(TSource);
            TKey currentKey2 = default(TKey);
            while (_source.MoveNext(ref currentElement2, ref currentKey2))
            {
                if (_predicate == null || _predicate(currentElement2))
                {
                    Interlocked.Increment(ref _totalElementCount.Value);
                    currentElement = currentElement2;
                    currentKey = 0;
                    if (flag)
                    {
                        _yieldExtra = true;
                        break;
                    }
                    flag = true;
                }
                if (Volatile.Read(ref _totalElementCount.Value) > 1)
                {
                    break;
                }
            }
            _alreadySearched = true;
            return flag;
        }
References System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >._alreadySearched, System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >._predicate, System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >._source, System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >._totalElementCount, System.Linq.Parallel.SingleQueryOperator< TSource >.SingleQueryOperatorEnumerator< TKey >._yieldExtra, System.Threading.Interlocked.Increment(), System.Linq.Parallel.QueryOperatorEnumerator< TElement, TKey >.MoveNext(), System.Threading.Volatile.Read(), and System.Linq.Parallel.Shared< T >.Value.