Terraria: System.Threading.CancellationTokenSource.Registrations.EnterLock
EnterLock()
void System.Threading.CancellationTokenSource.Registrations.EnterLock () inline
Definition at line 204 of file CancellationTokenSource.cs.
        {
            ref int @lock = ref _lock;
            if (Interlocked.Exchange(ref @lock, 1) != 0)
            {
                Contention(ref @lock);
            }
            [MethodImpl(MethodImplOptions.NoInlining)]
            static void Contention(ref int value)
            {
                SpinWait spinWait = default(SpinWait);
                do
                {
                    spinWait.SpinOnce();
                }
                while (Interlocked.Exchange(ref value, 1) == 1);
            }
        }
References System.Threading.CancellationTokenSource.Registrations._lock, System.Threading.Interlocked.Exchange(), and System.value.
Referenced by System.Threading.CancellationTokenSource.Registrations.Unregister(), and System.Threading.CancellationTokenSource.Registrations.UnregisterAll().