Terraria: System.Threading.CancellationTokenSource.Registrations.UnregisterAll
UnregisterAll()
void System.Threading.CancellationTokenSource.Registrations.UnregisterAll () inline
Definition at line 159 of file CancellationTokenSource.cs.
        {
            EnterLock();
            try
            {
                CallbackNode callbackNode = Callbacks;
                Callbacks = null;
                while (callbackNode != null)
                {
                    CallbackNode next = callbackNode.Next;
                    Recycle(callbackNode);
                    callbackNode = next;
                }
            }
            finally
            {
                ExitLock();
            }
        }
References System.Threading.CancellationTokenSource.Registrations.Callbacks, System.Threading.CancellationTokenSource.Registrations.EnterLock(), System.Threading.CancellationTokenSource.Registrations.ExitLock(), and System.Threading.CancellationTokenSource.Registrations.Recycle().