Terraria: Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList
FilterList()
void Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(12);
        _achievementsList.Clear();
        foreach (UIAchievementListItem achievementElement in _achievementElements)
        {
            if (_categoryButtons[(int)achievementElement.GetAchievement().Category].IsOn)
            {
                _achievementsList.Add(achievementElement);
            }
        }
        Recalculate();
    }
References Terraria.GameContent.UI.States.UIAchievementsMenu._achievementElements, Terraria.GameContent.UI.States.UIAchievementsMenu._achievementsList, Terraria.GameContent.UI.States.UIAchievementsMenu._categoryButtons, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.UI.UIElement.Recalculate().
Referenced by Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage().