Terraria: System.IO.Compression.ZipHelper.SeekBackwardsToSignature
SeekBackwardsToSignature()
static bool System.IO.Compression.ZipHelper.SeekBackwardsToSignature (Stream stream, uint signatureToFind, int maxBytesToRead) inline static package
Definition at line 71 of file ZipHelper.cs.
    {
        int bufferPointer = 0;
        uint num = 0u;
        byte[] array = new byte[32];
        bool flag = false;
        bool flag2 = false;
        int num2 = 0;
        while (!flag2 && !flag && num2 <= maxBytesToRead)
        {
            flag = SeekBackwardsAndRead(stream, array, out bufferPointer);
            while (bufferPointer >= 0 && !flag2)
            {
                num = (num << 8) | array[bufferPointer];
                if (num == signatureToFind)
                {
                    flag2 = true;
                }
                else
                {
                    bufferPointer--;
                }
            }
            num2 += array.Length;
        }
        if (!flag2)
        {
            return false;
        }
        stream.Seek(bufferPointer, SeekOrigin.Current);
        return true;
    }
References System.array, System.IO.Compression.ZipHelper.SeekBackwardsAndRead(), and System.stream.
Referenced by System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory(), and System.IO.Compression.ZipArchive.TryReadZip64EndOfCentralDirectory().