Terraria: Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture
CreateTexture()
unsafe void Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture (GraphicsDevice graphicsDevice, int width, int height, int depth, [MarshalAs(UnmanagedType.U1)] bool mipMap, SurfaceFormat format) inline private
Definition at line 262 of file Texture3D.cs.
    {
        if (graphicsDevice == null)
        {
            throw new ArgumentNullException("graphicsDevice", FrameworkResources.DeviceCannotBeNullOnResourceCreate);
        }
        if (width <= 0)
        {
            throw new ArgumentOutOfRangeException("width", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        if (height <= 0)
        {
            throw new ArgumentOutOfRangeException("height", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        if (depth <= 0)
        {
            throw new ArgumentOutOfRangeException("depth", FrameworkResources.ResourcesMustBeGreaterThanZeroSize);
        }
        ProfileCapabilities profileCapabilities = graphicsDevice._profileCapabilities;
        if (profileCapabilities.MaxVolumeExtent == 0)
        {
            profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFeatureNotSupported, typeof(Texture3D).Name);
        }
        if (!profileCapabilities.ValidVolumeFormats.Contains(format))
        {
            profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileFormatNotSupported, typeof(Texture3D).Name, format);
        }
        int maxVolumeExtent = profileCapabilities.MaxVolumeExtent;
        if (width > maxVolumeExtent || height > maxVolumeExtent || depth > maxVolumeExtent)
        {
            profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileTooBig, typeof(Texture3D).Name, maxVolumeExtent);
        }
        int num = Math.Max(Math.Max(width, height), depth);
        int num2 = Math.Min(Math.Min(width, height), depth);
        int num3 = (num + num2 - 1) / num2;
        int maxTextureAspectRatio = profileCapabilities.MaxTextureAspectRatio;
        if (num3 > maxTextureAspectRatio)
        {
            profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileAspectRatio, typeof(Texture3D).Name, maxTextureAspectRatio);
        }
        if (!profileCapabilities.NonPow2Volume && (!Texture.IsPowerOfTwo((uint)width) || !Texture.IsPowerOfTwo((uint)height) || !Texture.IsPowerOfTwo((uint)depth)))
        {
            profileCapabilities.ThrowNotSupportedException(FrameworkResources.ProfileNotPowerOfTwo, typeof(Texture3D).Name);
        }
        int num4 = ((!mipMap) ? 1 : 0);
        fixed (IDirect3DVolumeTexture9** ptr = &pComPtr)
        {
            int num5 = *(int*)graphicsDevice.pComPtr + 96;
            int num6 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, uint, uint, uint, uint, _D3DFORMAT, _D3DPOOL, IDirect3DVolumeTexture9**, void**, int>)(int)(*(uint*)num5))((nint)graphicsDevice.pComPtr, (uint)width, (uint)height, (uint)depth, (uint)num4, 0u, _003CModule_003E.ConvertXnaFormatToWindows(format), (_D3DPOOL)1, ptr, null);
            if (num6 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num6);
            }
            isDisposed = false;
            _parent = graphicsDevice;
            SurfaceFormat? format2 = format;
            InitializeDescription(format2);
            graphicsDevice.Resources.AddTrackedObject(this, pComPtr, 1u, _internalHandle, ref _internalHandle);
        }
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._internalHandle, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice._profileCapabilities, Microsoft.Xna.Framework.Graphics.DeviceResourceManager.AddTrackedObject(), System.Collections.Generic.List< T >.Contains(), Microsoft.Xna.Framework.FrameworkResources.DeviceCannotBeNullOnResourceCreate, System.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.Graphics.Texture3D.InitializeDescription(), Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.Texture.IsPowerOfTwo(), System.Math.Max(), Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxTextureAspectRatio, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.MaxVolumeExtent, System.Math.Min(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.NonPow2Volume, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, Microsoft.Xna.Framework.Graphics.Texture3D.pComPtr, Microsoft.Xna.Framework.FrameworkResources.ProfileAspectRatio, Microsoft.Xna.Framework.FrameworkResources.ProfileFeatureNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileFormatNotSupported, Microsoft.Xna.Framework.FrameworkResources.ProfileNotPowerOfTwo, Microsoft.Xna.Framework.FrameworkResources.ProfileTooBig, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Resources, Microsoft.Xna.Framework.FrameworkResources.ResourcesMustBeGreaterThanZeroSize, Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ThrowNotSupportedException(), and Microsoft.Xna.Framework.Graphics.ProfileCapabilities.ValidVolumeFormats.
Referenced by Microsoft.Xna.Framework.Graphics.Texture3D.Texture3D().