Terraria: Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T >
CopyData< T >() [1/3]
unsafe void Microsoft.Xna.Framework.Graphics.Texture3D.CopyData< T > (int level, int left, int top, int right, int bottom, int front, int back, T[] data, int startIndex, int elementCount, uint options, [MarshalAs(UnmanagedType.U1)] bool isSetting) inline private
Type Constraints
T : struct
Definition at line 167 of file Texture3D.cs.
                                                                                                                                                                                                                              : struct
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        if (data != null && data.Length != 0)
        {
            if (isSetting)
            {
                int num = 0;
                GraphicsDevice parent = _parent;
                if (0 < parent.Textures._maxTextures)
                {
                    do
                    {
                        if (parent.Textures[num] != this)
{
                            num++;
                            parent = _parent;
                            continue;
                        }
                        throw GraphicsHelpers.GetExceptionFromResult(2147500036u);
                    }
                    while (num < parent.Textures._maxTextures);
                }
                int num2 = 0;
                GraphicsDevice parent2 = _parent;
                if (0 < parent2.VertexTextures._maxTextures)
                {
                    do
                    {
                        if (parent2.VertexTextures[num2] != this)
{
                            num2++;
                            parent2 = _parent;
                            continue;
                        }
                        throw GraphicsHelpers.GetExceptionFromResult(2147500036u);
                    }
                    while (num2 < parent2.VertexTextures._maxTextures);
                }
            }
            IDirect3DVolumeTexture9* ptr = pComPtr;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DVOLUME_DESC d3DVOLUME_DESC);
            int num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DVOLUME_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, (uint)level, &d3DVOLUME_DESC);
            if (num3 < 0)
            {
                throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
            }
            Helpers.ValidateCopyParameters(data.Length, startIndex, elementCount);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DBOX d3DBOX);
            *(int*)(&d3DBOX) = left;
            System.Runtime.CompilerServices.Unsafe.As<_D3DBOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DBOX, 8)) = right;
            System.Runtime.CompilerServices.Unsafe.As<_D3DBOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DBOX, 4)) = top;
            System.Runtime.CompilerServices.Unsafe.As<_D3DBOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DBOX, 12)) = bottom;
            System.Runtime.CompilerServices.Unsafe.As<_D3DBOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DBOX, 16)) = front;
            System.Runtime.CompilerServices.Unsafe.As<_D3DBOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DBOX, 20)) = back;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint num4);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint num5);
            GetAndValidateSizes<T>(&d3DVOLUME_DESC, &num4, &num5);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint num6);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint num7);
            System.Runtime.CompilerServices.Unsafe.SkipInit(out uint num8);
            GetAndValidateBox(&d3DVOLUME_DESC, &num6, &num7, &num8, &d3DBOX);
            uint num9 = num6 * num7 * num8 * num4;
            if ((int)num5 * elementCount != (int)num9)
            {
                throw new ArgumentException(FrameworkResources.InvalidTotalSize);
            }
            IDirect3DVolumeTexture9* ptr2 = pComPtr;
            System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DLOCKED_BOX d3DLOCKED_BOX);
            num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DLOCKED_BOX*, _D3DBOX*, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 76)))((nint)ptr2, (uint)level, &d3DLOCKED_BOX, &d3DBOX, options);
            if (num3 >= 0)
            {
                try
                {
                    CopyData((void*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_BOX, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_BOX, 8)), *(int*)(&d3DLOCKED_BOX), System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_BOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_BOX, 4)), data, startIndex, elementCount, &d3DVOLUME_DESC, num6, num7, num8, isSetting);
                }
                finally
                {
                    if (num3 >= 0)
                    {
                        ptr2 = pComPtr;
                        num3 = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, int>)(int)(*(uint*)(*(int*)ptr2 + 80)))((nint)ptr2, (uint)level);
                    }
                }
                if (num3 >= 0)
                {
                    return;
                }
            }
            throw GraphicsHelpers.GetExceptionFromResult((uint)num3);
        }
        throw new ArgumentNullException("data", FrameworkResources.NullNotAllowed);
    }
References Microsoft.Xna.Framework.Graphics.TextureCollection._maxTextures, Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.Texture3D.GetAndValidateBox(), Microsoft.Xna.Framework.Graphics.Texture3D.GetAndValidateSizes< T >(), Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), Microsoft.Xna.Framework.FrameworkResources.InvalidTotalSize, Microsoft.Xna.Framework.FrameworkResources.NullNotAllowed, System.options, Microsoft.Xna.Framework.Graphics.Texture3D.pComPtr, System.startIndex, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Microsoft.Xna.Framework.Helpers.ValidateCopyParameters(), and Microsoft.Xna.Framework.Graphics.GraphicsDevice.VertexTextures.