Terraria: Microsoft.Xna.Framework.Graphics.Texture3D.InitializeDescription
InitializeDescription() [2/2]
unsafe void Microsoft.Xna.Framework.Graphics.Texture3D.InitializeDescription (SurfaceFormat? format) inline private
Definition at line 26 of file Texture3D.cs.
    {
        IntPtr intPtr = (IntPtr)pComPtr;
        Helpers.CheckDisposed(this, intPtr);
        IDirect3DVolumeTexture9* ptr = pComPtr;
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DVOLUME_DESC d3DVOLUME_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DVOLUME_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, 0u, &d3DVOLUME_DESC);
        if (num < 0)
        {
            throw GraphicsHelpers.GetExceptionFromResult((uint)num);
        }
        if (!format.HasValue)
        {
            format = _003CModule_003E.ConvertWindowsFormatToXna(*(_D3DFORMAT*)(&d3DVOLUME_DESC));
        }
        _width = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 16));
        _height = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 20));
        _depth = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 24));
        base.InitializeDescription(format.Value);
    }
References Microsoft.Xna.Framework.Graphics.Texture3D._depth, Microsoft.Xna.Framework.Graphics.Texture3D._height, Microsoft.Xna.Framework.Graphics.Texture3D._width, Microsoft.Xna.Framework.Helpers.CheckDisposed(), System.format, Microsoft.Xna.Framework.Graphics.GraphicsHelpers.GetExceptionFromResult(), and Microsoft.Xna.Framework.Graphics.Texture3D.pComPtr.
Referenced by Microsoft.Xna.Framework.Graphics.Texture3D.Texture3D(), Microsoft.Xna.Framework.Graphics.Texture3D.CreateTexture(), and Microsoft.Xna.Framework.Graphics.Texture3D.OnObjectCreation().