Terraria: Microsoft.Xna.Framework.Graphics.Texture3D.CopyOrRestoreData
CopyOrRestoreData()
unsafe int Microsoft.Xna.Framework.Graphics.Texture3D.CopyOrRestoreData ([MarshalAs(UnmanagedType.U1)] bool isStoring) inline package
Definition at line 480 of file Texture3D.cs.
    {
        IDirect3DVolumeTexture9* ptr = pComPtr;
        if (ptr == null)
        {
            return 0;
        }
        System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DVOLUME_DESC d3DVOLUME_DESC);
        int num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DVOLUME_DESC*, int>)(int)(*(uint*)(*(int*)ptr + 68)))((nint)ptr, 0u, &d3DVOLUME_DESC);
        if (num >= 0)
        {
            if (isStoring)
            {
                pFaceData = new IntPtr[_levelCount];
            }
            uint num2 = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 16));
            uint num3 = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 20));
            uint num4 = System.Runtime.CompilerServices.Unsafe.As<_D3DVOLUME_DESC, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DVOLUME_DESC, 24));
            byte expectedByteSizeFromFormat = Texture.GetExpectedByteSizeFromFormat(*(_D3DFORMAT*)(&d3DVOLUME_DESC));
            int num5 = 0;
            int num6 = 0;
            if (0 < _levelCount)
            {
                System.Runtime.CompilerServices.Unsafe.SkipInit(out _D3DLOCKED_BOX d3DLOCKED_BOX);
                do
                {
                    byte* ptr2 = null;
                    int num7;
                    if (!isStoring)
                    {
                        ref IntPtr reference = ref pFaceData[num5];
                        num5++;
                        ptr2 = (byte*)reference.ToPointer();
                        num7 = 0;
                    }
                    else
                    {
                        num7 = 16;
                    }
                    ptr = pComPtr;
                    num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DLOCKED_BOX*, _D3DBOX*, uint, int>)(int)(*(uint*)(*(int*)ptr + 76)))((nint)ptr, (uint)num6, &d3DLOCKED_BOX, null, (uint)num7);
                    if (num < 0)
                    {
                        break;
                    }
                    uint num8 = expectedByteSizeFromFormat * num2;
                    if (isStoring)
                    {
                        ptr2 = (byte*)_003CModule_003E.new_005B_005D(num8 * num4 * num3);
                    }
                    byte* ptr3 = ptr2;
                    byte* ptr4 = (byte*)(int)System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_BOX, uint>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_BOX, 8));
                    if (0 < num4)
                    {
                        uint num9 = num4;
                        do
{
                            byte* ptr5 = ptr4;
                            if (0 < num3)
{
                                uint num10 = num3;
                                do
{
                                    if (isStoring)
{
                                        _003CModule_003E.memcpy_s(ptr3, num8 * num3, ptr5, num8);
                                    }
                                    else
{
                                        _003CModule_003E.memcpy_s(ptr5, *(uint*)(&d3DLOCKED_BOX), ptr3, num8);
                                    }
                                    ptr5 = *(int*)(&d3DLOCKED_BOX) + ptr5;
                                    ptr3 = (int)num8 + ptr3;
                                    num10--;
                                }
                                while (num10 != 0);
                            }
                            ptr4 = System.Runtime.CompilerServices.Unsafe.As<_D3DLOCKED_BOX, int>(ref System.Runtime.CompilerServices.Unsafe.AddByteOffset(ref d3DLOCKED_BOX, 4)) + ptr4;
                            num9--;
                        }
                        while (num9 != 0);
                    }
                    ptr = pComPtr;
                    num = ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, int>)(int)(*(uint*)(*(int*)ptr + 80)))((nint)ptr, (uint)num6);
                    if (num < 0)
                    {
                        break;
                    }
                    if (isStoring)
                    {
                        IntPtr intPtr = (IntPtr)ptr2;
                        ref IntPtr reference2 = ref pFaceData[num5];
                        num5++;
                        reference2 = intPtr;
                    }
                    num2 = ((num2 <= 1) ? 1u : (num2 >> 1));
                    num3 = ((num3 <= 1) ? 1u : (num3 >> 1));
                    num4 = ((num4 <= 1) ? 1u : (num4 >> 1));
                    num6++;
                }
                while (num6 < _levelCount);
            }
        }
        return num;
    }
References Microsoft.Xna.Framework.Graphics.Texture._levelCount, Microsoft.Xna.Framework.Graphics.Texture.GetExpectedByteSizeFromFormat(), Microsoft.Xna.Framework.Graphics.Texture3D.pComPtr, and Microsoft.Xna.Framework.Graphics.Texture3D.pFaceData.
Referenced by Microsoft.Xna.Framework.Graphics.Texture3D.RecreateAndPopulateObject(), and Microsoft.Xna.Framework.Graphics.Texture3D.SaveDataForRecreation().