Terraria: Terraria.GameContent.RGB.SkullShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.SkullShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 36 of file SkullShader.cs.
    {
        for (int i = 0; i < fragment.Count; i++)
        {
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            Vector4 value = _backgroundColor;
            float num = (NoiseHelper.GetStaticNoise(gridPositionOfIndex.X) * 10f + time * 0.75f) % 10f + canvasPositionOfIndex.Y - 1f;
            if (num > 0f)
            {
                float amount = Math.Max(0f, 1.2f - num);
                if (num < 0.2f)
                {
                    amount = num * 5f;
                }
                value = Vector4.Lerp(value, _skullColor, amount);
            }
            float staticNoise = NoiseHelper.GetStaticNoise(canvasPositionOfIndex * 0.5f + new Vector2(12.5f, time * 0.2f));
            staticNoise = Math.Max(0f, 1f - staticNoise * staticNoise * 4f * staticNoise * (1f - canvasPositionOfIndex.Y * canvasPositionOfIndex.Y)) * canvasPositionOfIndex.Y * canvasPositionOfIndex.Y;
            staticNoise = MathHelper.Clamp(staticNoise, 0f, 1f);
            Vector4 value2 = Vector4.Lerp(_bloodDark, _bloodLight, staticNoise);
            value = Vector4.Lerp(value, value2, staticNoise);
            fragment.SetColor(i, value);
        }
    }
References Terraria.GameContent.RGB.SkullShader._backgroundColor, Terraria.GameContent.RGB.SkullShader._bloodDark, Terraria.GameContent.RGB.SkullShader._bloodLight, Terraria.GameContent.RGB.SkullShader._skullColor, Microsoft.Xna.Framework.MathHelper.Clamp(), ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), ReLogic.Peripherals.RGB.Fragment.SetColor(), System.value, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Vector2.Y.