Terraria: MS.Internal.Xml.XPath.FunctionQuery.MatchNode
MatchNode()
override XPathNavigator MS.Internal.Xml.XPath.FunctionQuery.MatchNode (XPathNavigator navigator) inline virtual
Reimplemented from MS.Internal.Xml.XPath.Query.
Definition at line 98 of file FunctionQuery.cs.
    {
        if (name != "key" && prefix.Length != 0)
        {
            throw XPathException.Create(System.SR.Xp_InvalidPattern);
        }
        Evaluate(new XPathSingletonIterator(navigator, moved: true));
        XPathNavigator xPathNavigator = null;
        while ((xPathNavigator = Advance()) != null)
        {
            if (xPathNavigator.IsSamePosition(navigator))
            {
                return xPathNavigator;
            }
        }
        return xPathNavigator;
    }
References MS.Internal.Xml.XPath.ExtensionQuery.Advance(), System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.FunctionQuery.Evaluate(), MS.Internal.Xml.XPath.ExtensionQuery.name, MS.Internal.Xml.XPath.ExtensionQuery.prefix, and System.SR.Xp_InvalidPattern.