Terraria: System.StubHelpers.StubHelpers.AddToCleanupList
AddToCleanupList()
static IntPtr System.StubHelpers.StubHelpers.AddToCleanupList (ref CleanupWorkListElement pCleanupWorkList, SafeHandle handle) inline static package
Definition at line 29 of file StubHelpers.cs.
    {
        SafeHandleCleanupWorkListElement safeHandleCleanupWorkListElement = new SafeHandleCleanupWorkListElement(handle);
        CleanupWorkListElement.AddToCleanupList(ref pCleanupWorkList, safeHandleCleanupWorkListElement);
        return safeHandleCleanupWorkListElement.AddRef();
    }
References System.StubHelpers.SafeHandleCleanupWorkListElement.AddRef(), System.StubHelpers.CleanupWorkListElement.AddToCleanupList(), and System.handle.
Referenced by System.StubHelpers.HandleMarshaler.ConvertSafeHandleToNative().