Terraria: MS.Internal.Xml.XPath.FunctionQuery.Evaluate
Evaluate()
override object MS.Internal.Xml.XPath.FunctionQuery.Evaluate (XPathNodeIterator nodeIterator) inline
Definition at line 73 of file FunctionQuery.cs.
    {
        if (xsltContext == null)
        {
            throw XPathException.Create(System.SR.Xp_NoContext);
        }
        object[] array = new object[_args.Count];
        for (int i = 0; i < _args.Count; i++)
        {
            array[i] = _args[i].Evaluate(nodeIterator);
            if (array[i] is XPathNodeIterator)
            {
                array[i] = new XPathSelectionIterator(nodeIterator.Current, _args[i]);
            }
        }
        try
        {
            return ProcessResult(_function.Invoke(xsltContext, array, nodeIterator.Current));
        }
        catch (Exception innerException)
        {
            throw XPathException.Create(System.SR.Xp_FunctionFailed, base.QName, innerException);
        }
    }
References MS.Internal.Xml.XPath.FunctionQuery._args, MS.Internal.Xml.XPath.FunctionQuery._function, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XPath.XPathException.Create(), System.Xml.Xsl.IXsltContextFunction.Invoke(), MS.Internal.Xml.XPath.ExtensionQuery.ProcessResult(), System.SR.Xp_FunctionFailed, System.SR.Xp_NoContext, and MS.Internal.Xml.XPath.ExtensionQuery.xsltContext.
Referenced by MS.Internal.Xml.XPath.FunctionQuery.MatchNode().