Terraria: System.Xml.Xsl.XPathConvert.AddU
AddU()
static uint System.Xml.Xsl.XPathConvert.AddU (ref uint u1, uint u2) inline static
Definition at line 1665 of file XPathConvert.cs.
    {
        u1 += u2;
        if (u1 >= u2)
        {
            return 0u;
        }
        return 1u;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XPathConvert.BigInteger.Add(), System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbFast(), System.Xml.Xsl.XPathConvert.BigInteger.DivRem(), System.Xml.Xsl.XPathConvert.BigNumber.MakeLowerBound(), System.Xml.Xsl.XPathConvert.BigNumber.MakeUpperBound(), System.Xml.Xsl.XPathConvert.BigNumber.Mul(), System.Xml.Xsl.XPathConvert.BigInteger.MulAdd(), System.Xml.Xsl.XPathConvert.BigNumber.MulTenAdd(), System.Xml.Xsl.XPathConvert.BigNumber.operator double(), System.Xml.Xsl.XPathConvert.BigNumber.Round(), and System.Xml.Xsl.XPathConvert.BigInteger.Subtract().