Terraria: System.Collections.Immutable.ImmutableList.AddRange
AddRange() [1/2]
ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.AddRange (IEnumerable< T > items) inline
Implements System.Collections.Immutable.IImmutableList< T >.
Definition at line 1706 of file ImmutableList.cs.
    {
        Requires.NotNull(items, "items");
        if (IsEmpty)
        {
            return CreateRange(items);
        }
        Node root = _root.AddRange(items);
        return Wrap(root);
    }
References System.Collections.Immutable.ImmutableList< T >._root, System.Collections.Immutable.ImmutableList< T >.Node.AddRange(), System.Collections.Immutable.ImmutableList< T >.CreateRange(), System.Collections.Immutable.ImmutableList< T >.IsEmpty, and System.Collections.Immutable.ImmutableList< T >.Wrap().
Referenced by System.Collections.Immutable.ImmutableList< T >.AddRange().