Terraria: System.Xml.Xsl.XPathConvert.IsSpecial
IsSpecial()
static bool System.Xml.Xsl.XPathConvert.IsSpecial (double dbl) inline static
Definition at line 1651 of file XPathConvert.cs.
    {
        return (~DblHi(dbl) & 0x7FF00000) == 0;
    }
References System.Xml.Xsl.XPathConvert.DblHi(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.XPathConvert.DoubleToString(), System.Xml.Xsl.XPathConvert.FloatingDecimal.InitFromDouble(), and System.Xml.Xsl.XPathConvert.IsInteger().