Terraria: System.Xml.Xsl.XPathConvert.DoubleToString
DoubleToString()
static unsafe string System.Xml.Xsl.XPathConvert.DoubleToString (double dbl) inline static
Definition at line 1729 of file XPathConvert.cs.
    {
        if (IsInteger(dbl, out var value))
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }
        if (IsSpecial(dbl))
        {
            if (double.IsNaN(dbl))
            {
                return "NaN";
            }
            if (!(dbl < 0.0))
            {
                return "Infinity";
            }
            return "-Infinity";
        }
        FloatingDecimal floatingDecimal = new FloatingDecimal(dbl);
        int num = floatingDecimal.MantissaSize - floatingDecimal.Exponent;
        int num2;
        if (num > 0)
        {
            num2 = ((floatingDecimal.Exponent > 0) ? floatingDecimal.Exponent : 0);
        }
        else
        {
            num2 = floatingDecimal.Exponent;
            num = 0;
        }
        int num3 = num2 + num + 4;
        char* ptr = stackalloc char[num3];
        char* ptr2 = ptr;
        if (floatingDecimal.Sign < 0)
        {
            *(ptr2++) = '-';
        }
        int num4 = floatingDecimal.MantissaSize;
        int num5 = 0;
        if (num2 != 0)
        {
            do
            {
                if (num4 != 0)
                {
                    *(ptr2++) = (char)(floatingDecimal[num5++] | 0x30u);
                    num4--;
                }
                else
                {
                    *(ptr2++) = '0';
                }
            }
            while (--num2 != 0);
        }
        else
        {
            *(ptr2++) = '0';
        }
        if (num != 0)
        {
            *(ptr2++) = '.';
            while (num > num4)
            {
                *(ptr2++) = '0';
                num--;
            }
            while (num4 != 0)
            {
                *(ptr2++) = (char)(floatingDecimal[num5++] | 0x30u);
                num4--;
            }
        }
        return new string(ptr, 0, (int)(ptr2 - ptr));
    }
References System.Xml.Dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Xml.Xsl.XPathConvert.IsInteger(), System.Xml.Xsl.XPathConvert.IsSpecial(), and System.value.
Referenced by System.Xml.Xsl.Runtime.NumberFormatter.ConvertToDecimal(), System.Xml.Xsl.XPath.XPathQilFactory.ConvertToString(), System.Xml.Xsl.Runtime.NumberFormatter.FormatSequence(), System.Xml.Xsl.Runtime.XsltConvert.ToString(), and System.Xml.Xsl.Runtime.XsltConvert.ToString().