Terraria: System.Collections.Immutable.ImmutableList.RemoveRange
RemoveRange() [4/5]
ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.RemoveRange (int index, int count) inline
Implements System.Collections.Immutable.IImmutableList< T >.
Definition at line 1746 of file ImmutableList.cs.
    {
        Requires.Range(index >= 0 && index <= Count, "index");
        Requires.Range(count >= 0 && index + count <= Count, "count");
        Node node = _root;
        int num = count;
        while (num-- > 0)
        {
            node = node.RemoveAt(index);
        }
        return Wrap(node);
    }
References System.Collections.Immutable.ImmutableList< T >._root, System.Collections.Immutable.ImmutableList< T >.Count, System.count, System.index, System.Collections.Immutable.Requires.Range(), and System.Collections.Immutable.ImmutableList< T >.Wrap().
Referenced by System.Collections.Immutable.ImmutableList< T >.RemoveRange(), System.Collections.Immutable.ImmutableList< T >.RemoveRange(), and System.Collections.Immutable.ImmutableList< T >.RemoveRange().