Terraria: System.Collections.Immutable.ImmutableList.CreateRange
CreateRange()
static ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.CreateRange (IEnumerable< T > items) inline static private
Definition at line 2162 of file ImmutableList.cs.
    {
        if (TryCastToImmutableList(items, out var other))
        {
            return other;
        }
        IOrderedCollection<T> orderedCollection = items.AsOrderedCollection();
        if (orderedCollection.Count == 0)
        {
            return Empty;
        }
        Node root = Node.NodeTreeFromList(orderedCollection, 0, orderedCollection.Count);
        return new ImmutableList<T>(root);
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Collections.Immutable.ImmutableList< T >.Empty, System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), System.other, and System.Collections.Immutable.ImmutableList< T >.TryCastToImmutableList().
Referenced by System.Collections.Immutable.ImmutableList< T >.AddRange(), and System.Collections.Immutable.ImmutableList< T >.Node.FindAll().