Terraria: System.Collections.Immutable.ImmutableList.Wrap
Wrap()
ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.Wrap (Node root) inline private
Definition at line 2149 of file ImmutableList.cs.
    {
        if (root != _root)
        {
            if (!root.IsEmpty)
            {
                return new ImmutableList<T>(root);
            }
            return Clear();
        }
        return this;
    }
References System.Collections.Immutable.ImmutableList< T >._root, System.Collections.Immutable.ImmutableList< T >.Clear(), and System.Collections.Immutable.ImmutableList< T >.Node.IsEmpty.
Referenced by System.Collections.Immutable.ImmutableList< T >.Add(), System.Collections.Immutable.ImmutableList< T >.AddRange(), System.Collections.Immutable.ImmutableList< T >.GetRange(), System.Collections.Immutable.ImmutableList< T >.Insert(), System.Collections.Immutable.ImmutableList< T >.InsertRange(), System.Collections.Immutable.ImmutableList< T >.RemoveAll(), System.Collections.Immutable.ImmutableList< T >.RemoveAt(), System.Collections.Immutable.ImmutableList< T >.RemoveRange(), System.Collections.Immutable.ImmutableList< T >.RemoveRange(), System.Collections.Immutable.ImmutableList< T >.Reverse(), System.Collections.Immutable.ImmutableList< T >.Reverse(), System.Collections.Immutable.ImmutableList< T >.SetItem(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), System.Collections.Immutable.ImmutableList< T >.Sort(), and System.Collections.Immutable.ImmutableList< T >.Sort().