Terraria: System.Collections.Immutable.ImmutableList.GetRange
GetRange()
ImmutableList< T > System.Collections.Immutable.ImmutableList< T >.GetRange (int index, int count) inline
Implements System.Collections.Immutable.IImmutableListQueries< T >.
Definition at line 1876 of file ImmutableList.cs.
    {
        Requires.Range(index >= 0, "index");
        Requires.Range(count >= 0, "count");
        Requires.Range(index + count <= Count, "count");
        return Wrap(Node.NodeTreeFromList(this, index, count));
    }
References System.Collections.Immutable.ImmutableList< T >.Count, System.count, System.index, System.Collections.Immutable.ImmutableList< T >.Node.NodeTreeFromList(), System.Collections.Immutable.Requires.Range(), and System.Collections.Immutable.ImmutableList< T >.Wrap().