Terraria: System.Xml.Xsl.XPathConvert.DblLo
DblLo()
static uint System.Xml.Xsl.XPathConvert.DblLo (double dbl) inline static
Definition at line 1646 of file XPathConvert.cs.
    {
        return (uint)BitConverter.DoubleToUInt64Bits(dbl);
    }
References System.BitConverter.DoubleToUInt64Bits().
Referenced by System.Xml.Xsl.XPathConvert.FloatingDecimal.AdjustDbl(), System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbFast(), and System.Xml.Xsl.XPathConvert.BigNumber.DblToRgbPrecise().