Terraria: System.Text.SegmentStringBuilder.Create
Create()
static SegmentStringBuilder System.Text.SegmentStringBuilder.Create () inline static
Definition at line 16 of file SegmentStringBuilder.cs.
    {
        SegmentStringBuilder result = default(SegmentStringBuilder);
        result._array = Array.Empty<ReadOnlyMemory<char>>();
        return result;
    }
Referenced by System.Text.RegularExpressions.Regex.Replace(), System.Text.RegularExpressions.RegexReplacement.Replace(), and System.Text.RegularExpressions.Match.Result().