Terraria: System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.AddUnchecked
AddUnchecked()
void System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.AddUnchecked (ExceptionRegionKind kind, int tryOffset, int tryLength, int handlerOffset, int handlerLength, int catchTokenOrOffset) inline package
Definition at line 173 of file ExceptionRegionEncoder.cs.
    {
        if (HasSmallFormat)
        {
            Builder.WriteUInt16((ushort)kind);
            Builder.WriteUInt16((ushort)tryOffset);
            Builder.WriteByte((byte)tryLength);
            Builder.WriteUInt16((ushort)handlerOffset);
            Builder.WriteByte((byte)handlerLength);
        }
        else
        {
            Builder.WriteInt32((int)kind);
            Builder.WriteInt32(tryOffset);
            Builder.WriteInt32(tryLength);
            Builder.WriteInt32(handlerOffset);
            Builder.WriteInt32(handlerLength);
        }
        Builder.WriteInt32(catchTokenOrOffset);
    }
References System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.Builder, System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.HasSmallFormat, System.Reflection.Metadata.BlobBuilder.WriteByte(), System.Reflection.Metadata.BlobBuilder.WriteInt32(), and System.Reflection.Metadata.BlobBuilder.WriteUInt16().
Referenced by System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.Add().