Terraria: System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.SerializeTableHeader
SerializeTableHeader()
static ExceptionRegionEncoder System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.SerializeTableHeader (BlobBuilder builder, int exceptionRegionCount, bool hasSmallRegions) inline static package
Definition at line 61 of file ExceptionRegionEncoder.cs.
    {
        bool flag = hasSmallRegions && IsSmallRegionCount(exceptionRegionCount);
        int exceptionTableSize = GetExceptionTableSize(exceptionRegionCount, flag);
        builder.Align(4);
        if (flag)
        {
            builder.WriteByte(1);
            builder.WriteByte((byte)exceptionTableSize);
            builder.WriteInt16(0);
        }
        else
        {
            builder.WriteByte(65);
            builder.WriteByte((byte)exceptionTableSize);
            builder.WriteUInt16((ushort)(exceptionTableSize >> 8));
        }
        return new ExceptionRegionEncoder(builder, flag);
    }
References System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.ExceptionRegionEncoder(), System.Reflection.Metadata.BlobBuilder.Align(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.GetExceptionTableSize(), System.Reflection.Metadata.Ecma335.ExceptionRegionEncoder.IsSmallRegionCount(), System.Reflection.Metadata.BlobBuilder.WriteByte(), System.Reflection.Metadata.BlobBuilder.WriteInt16(), and System.Reflection.Metadata.BlobBuilder.WriteUInt16().
Referenced by System.Reflection.Metadata.Ecma335.MethodBodyStreamEncoder.AddMethodBody(), and System.Reflection.Metadata.Ecma335.ControlFlowBuilder.SerializeExceptionTable().