Terraria: System.ComponentModel.EventDescriptorCollection.RemoveAt
RemoveAt() [1/2]
void System.ComponentModel.EventDescriptorCollection.RemoveAt (int index) inline
Implements System.Collections.Generic.IList< T >.
Definition at line 275 of file EventDescriptorCollection.cs.
    {
        if (_readOnly)
        {
            throw new NotSupportedException();
        }
        if (index < Count - 1)
        {
            Array.Copy(_events, index + 1, _events, index, Count - index - 1);
        }
        _events[Count - 1] = null;
        Count--;
    }
References System.ComponentModel.EventDescriptorCollection._events, System.ComponentModel.EventDescriptorCollection._readOnly, System.Array.Copy(), System.ComponentModel.EventDescriptorCollection.Count, and System.index.
Referenced by System.ComponentModel.EventDescriptorCollection.Remove(), and System.ComponentModel.EventDescriptorCollection.RemoveAt().