Terraria: System.ComponentModel.EventDescriptorCollection.EventDescriptorCollection
EventDescriptorCollection() [1/3]
System.ComponentModel.EventDescriptorCollection.EventDescriptorCollection (EventDescriptor?[] events) inline
Definition at line 113 of file EventDescriptorCollection.cs.
    {
        if (events == null)
        {
            _events = Array.Empty<EventDescriptor>();
        }
        else
        {
            _events = events;
            Count = events.Length;
        }
        _eventsOwned = true;
    }
References System.ComponentModel.EventDescriptorCollection._events, System.ComponentModel.EventDescriptorCollection._eventsOwned, and System.ComponentModel.EventDescriptorCollection.Count.
Referenced by System.ComponentModel.EventDescriptorCollection.Sort(), System.ComponentModel.EventDescriptorCollection.Sort(), System.ComponentModel.EventDescriptorCollection.Sort(), and System.ComponentModel.EventDescriptorCollection.Sort().