Terraria: System.ComponentModel.EventDescriptorCollection.EnsureSize
EnsureSize()
void System.ComponentModel.EventDescriptorCollection.EnsureSize (int sizeNeeded) inline private
Definition at line 196 of file EventDescriptorCollection.cs.
    {
        if (sizeNeeded > _events.Length)
        {
            if (_events.Length == 0)
            {
                Count = 0;
                _events = new EventDescriptor[sizeNeeded];
                return;
            }
            EnsureEventsOwned();
            int num = Math.Max(sizeNeeded, _events.Length * 2);
            EventDescriptor[] array = new EventDescriptor[num];
            Array.Copy(_events, array, Count);
            _events = array;
        }
    }
References System.ComponentModel.EventDescriptorCollection._events, System.array, System.Array.Copy(), System.ComponentModel.EventDescriptorCollection.Count, System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned(), and System.Math.Max().
Referenced by System.ComponentModel.EventDescriptorCollection.Add(), and System.ComponentModel.EventDescriptorCollection.Insert().