Terraria: System.ComponentModel.EventDescriptorCollection.InternalSort
InternalSort() [2/2]
void System.ComponentModel.EventDescriptorCollection.InternalSort (string?[] names) inline protected
Definition at line 318 of file EventDescriptorCollection.cs.
    {
        if (_events.Length == 0)
        {
            return;
        }
        InternalSort(_comparer);
        if (names == null || names.Length == 0)
        {
            return;
        }
        List<EventDescriptor> list = new List<EventDescriptor>(_events);
        int num = 0;
        int num2 = _events.Length;
        for (int i = 0; i < names.Length; i++)
        {
            for (int j = 0; j < num2; j++)
            {
                EventDescriptor eventDescriptor = list[j];
                if (eventDescriptor != null && eventDescriptor.Name.Equals(names[i]))
                {
                    _events[num++] = eventDescriptor;
                    list[j] = null;
                    break;
                }
            }
        }
        for (int k = 0; k < num2; k++)
        {
            if (list[k] != null)
            {
                _events[num++] = list[k];
            }
        }
    }
References System.ComponentModel.EventDescriptorCollection._comparer, System.ComponentModel.EventDescriptorCollection._events, System.ComponentModel.EventDescriptorCollection.InternalSort(), and System.list.
Referenced by System.ComponentModel.EventDescriptorCollection.EnsureEventsOwned(), and System.ComponentModel.EventDescriptorCollection.InternalSort().