Terraria: UILinkPointNavigator.GetInstructions
GetInstructions()
static string UILinkPointNavigator.GetInstructions () inline static
     {
         UILinkPage uILinkPage = Pages[CurrentPage];
         UILinkPoint uILinkPoint = Points[CurrentPoint];
         if (_suggestedPointID.HasValue)
         {
             SwapToSuggestion();
             uILinkPoint = Points[_suggestedPointID.Value];
             uILinkPage = Pages[uILinkPoint.Page];
             CurrentPage = uILinkPage.ID;
             uILinkPage.CurrentPoint = _suggestedPointID.Value;
         }
         string text = uILinkPage.SpecialInteractions();
         if ((PlayerInput.SettingsForUI.CurrentCursorMode == CursorMode.Gamepad && PlayerInput.Triggers.Current.UsedMovementKey && InUse) || _suggestedPointID.HasValue)
         {
             string text2 = uILinkPoint.SpecialInteractions();
             if (!string.IsNullOrEmpty(text2))
             {
                 if (string.IsNullOrEmpty(text))
                 {
                     return text2;
                 }
                 text = text + "   " + text2;
             }
         }
         ConsumeSuggestionSwap();
         return text;
     }
References _suggestedPointID, ConsumeSuggestionSwap(), TriggersPack.Current, PlayerInput.SettingsForUI.CurrentCursorMode, CurrentPage, UILinkPage.CurrentPoint, CurrentPoint, UILinkPage.ID, InUse, UILinkPoint.Page, Pages, Points, UILinkPage.SpecialInteractions(), UILinkPoint.SpecialInteractions(), SwapToSuggestion(), PlayerInput.Triggers, and TriggersSet.UsedMovementKey.
Referenced by PlayerInput.ComposeInstructionsForGamepad().