Terraria: UILinkPointNavigator.ChangePoint
ChangePoint()
static void UILinkPointNavigator.ChangePoint (int PointID) inline static
     {
         if (Points.ContainsKey(PointID))
         {
             CurrentPage = Points[PointID].Page;
             OverridePoint = PointID;
             ProcessChanges();
         }
     }
References CurrentPage, OverridePoint, Points, and ProcessChanges().
Referenced by PlayerInput.ExitBuildingMode(), UICharacterCreation.MoveToVisuallyClosestPoint(), UIBestiaryTest.MoveToVisuallyClosestPoint(), UIGamepadHelper.MoveToVisuallyClosestPoint(), UIAchievementsMenu.OnActivate(), UICharacterSelect.OnActivate(), UIManageControls.OnActivate(), UIVirtualKeyboard.OnActivate(), UIWorkshopSelectResourcePackToPublish.OnActivate(), UIWorkshopSelectWorldToPublish.OnActivate(), UIWorkshopWorldImport.OnActivate(), UIWorldLoad.OnActivate(), UIWorldSelect.OnActivate(), UICharacterSelect.SetupGamepadPoints(), UICreativePowersMenu.SetupGamepadPoints(), UIManageControls.SetupGamepadPoints(), UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), UIWorkshopWorldImport.SetupGamepadPoints(), UIWorldSelect.SetupGamepadPoints(), UILinkPage.Travel(), and GamepadMainMenuHandler.Update().