Terraria: UILinkPointNavigator.ConsumeSuggestion
ConsumeSuggestion()
static void UILinkPointNavigator.ConsumeSuggestion () inline static
     {
         if (_suggestedPointID.HasValue)
         {
             int value = _suggestedPointID.Value;
             ClearSuggestion();
             CurrentPage = Points[value].Page;
             OverridePoint = value;
             ProcessChanges();
             PlayerInput.Triggers.Current.UsedMovementKey = true;
         }
     }
References _suggestedPointID, ClearSuggestion(), TriggersPack.Current, CurrentPage, OverridePoint, Points, ProcessChanges(), PlayerInput.Triggers, and TriggersSet.UsedMovementKey.
Referenced by Update().