Terraria: UILinkPointNavigator.GoToDefaultPage
GoToDefaultPage()
static void UILinkPointNavigator.GoToDefaultPage (int specialFlag = 0) inline static
     {
         TileEntity tileEntity = Main.LocalPlayer.tileEntityAnchor.GetTileEntity();
         if (Main.MenuUI.IsVisible)
         {
             CurrentPage = 1004;
         }
         else if (Main.InGameUI.IsVisible || specialFlag == 1)
         {
             CurrentPage = 1004;
         }
         else if (Main.gameMenu)
         {
             CurrentPage = 1000;
         }
         else if (Main.ingameOptionsWindow)
         {
             CurrentPage = 1001;
         }
         else if (Main.CreativeMenu.Enabled)
         {
             CurrentPage = 1005;
         }
         else if (Main.hairWindow)
         {
             CurrentPage = 12;
         }
         else if (Main.clothesWindow)
         {
             CurrentPage = 15;
         }
         else if (Main.npcShop != 0)
         {
             CurrentPage = 13;
         }
         else if (Main.InGuideCraftMenu)
         {
             CurrentPage = 0;
         }
         else if (Main.InReforgeMenu)
         {
             CurrentPage = 0;
         }
         else if (Main.player[Main.myPlayer].chest != -1)
         {
             CurrentPage = 4;
         }
         else if (tileEntity is TEDisplayDoll)
         {
             CurrentPage = 20;
         }
         else if (tileEntity is TEHatRack)
         {
             CurrentPage = 21;
         }
         else if (Main.player[Main.myPlayer].talkNPC != -1 || Main.player[Main.myPlayer].sign != -1)
         {
             CurrentPage = 1003;
         }
         else
         {
             CurrentPage = 0;
         }
     }
References Player.chest, Main.clothesWindow, Main.CreativeMenu, CurrentPage, CreativeUI.Enabled, Main.gameMenu, PlayerInteractionAnchor.GetTileEntity(), Main.hairWindow, Main.ingameOptionsWindow, Main.InGameUI, Main.InGuideCraftMenu, Main.InReforgeMenu, UserInterface.IsVisible, Main.LocalPlayer, Main.MenuUI, Main.myPlayer, Main.npcShop, Main.player, Player.sign, Player.talkNPC, and Player.tileEntityAnchor.
Referenced by Main.GUIChatDrawInner(), IngameFancyUI.OpenVirtualKeyboard(), ProcessChanges(), and Update().