Terraria: Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 17 of file SlimeRainShader.cs.
    {
        Vector4 vector = new Vector4(0f, 0f, 0f, 0.75f);
        for (int i = 0; i < fragment.Count; i++)
        {
            Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
            Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
            float num = (NoiseHelper.GetStaticNoise(gridPositionOfIndex.X) * 7f + time * 0.4f) % 7f - canvasPositionOfIndex.Y;
            Vector4 vector2 = vector;
            if (num > 0f)
            {
                float amount = Math.Max(0f, 1.2f - num);
                if (num < 0.4f)
                {
                    amount = num / 0.4f;
                }
                int num2 = (gridPositionOfIndex.X % _colors.Length + _colors.Length) % _colors.Length;
                vector2 = Vector4.Lerp(vector2, _colors[num2], amount);
            }
            fragment.SetColor(i, vector2);
        }
    }
References Terraria.GameContent.RGB.SlimeRainShader._colors, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), ReLogic.Peripherals.RGB.Fragment.SetColor(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Vector2.Y.