Terraria: System.IO.MemoryStream.CopyToAsync
CopyToAsync() [4/4]
override Task System.IO.MemoryStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual inherited
Reimplemented from System.IO.Stream.
Reimplemented in System.Net.Http.HttpContent.LimitMemoryStream, and System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 435 of file MemoryStream.cs.
    {
        Stream.ValidateCopyToArguments(destination, bufferSize);
        EnsureNotClosed();
        if (GetType() != typeof(MemoryStream))
        {
            return base.CopyToAsync(destination, bufferSize, cancellationToken);
        }
        if (cancellationToken.IsCancellationRequested)
        {
            return Task.FromCanceled(cancellationToken);
        }
        int position = _position;
        int num = InternalEmulateRead(_length - _position);
        if (num == 0)
        {
            return Task.CompletedTask;
        }
        if (!(destination is MemoryStream memoryStream))
        {
            return destination.WriteAsync(_buffer, position, num, cancellationToken);
        }
        try
        {
            memoryStream.Write(_buffer, position, num);
            return Task.CompletedTask;
        }
        catch (Exception exception)
        {
            return Task.FromException(exception);
        }
    }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._length, System.IO.MemoryStream._position, System.cancellationToken, System.Threading.Tasks.Task< TResult >.CompletedTask, System.destination, System.IO.MemoryStream.EnsureNotClosed(), System.exception, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.IO.MemoryStream.InternalEmulateRead(), and System.IO.Stream.ValidateCopyToArguments().