Terraria: System.IO.MemoryStream.ReadAsync
ReadAsync() [3/3]
override ValueTask< int > System.IO.MemoryStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual inherited
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 387 of file MemoryStream.cs.
    {
        if (cancellationToken.IsCancellationRequested)
        {
            return ValueTask.FromCanceled<int>(cancellationToken);
        }
        try
        {
            ArraySegment<byte> segment;
            return new ValueTask<int>(MemoryMarshal.TryGetArray((ReadOnlyMemory<byte>)buffer, out segment) ? Read(segment.Array, segment.Offset, segment.Count) : Read(buffer.Span));
        }
        catch (OperationCanceledException exception)
        {
            return new ValueTask<int>(Task.FromCanceled<int>(exception));
        }
        catch (Exception exception2)
        {
            return ValueTask.FromException<int>(exception2);
        }
    }
References System.ArraySegment< T >.Array, System.buffer, System.cancellationToken, System.ArraySegment< T >.Count, System.exception, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.ValueTask< TResult >.FromCanceled(), System.Threading.Tasks.ValueTask< TResult >.FromException(), System.ArraySegment< T >.Offset, and System.IO.Read.