Terraria: System.IO.MemoryStream.Dispose
Dispose() [2/2]
override void System.IO.MemoryStream.Dispose (bool disposing) inline protected virtual inherited
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 194 of file MemoryStream.cs.
    {
        try
        {
            if (disposing)
            {
                _isOpen = false;
                _writable = false;
                _expandable = false;
                _lastReadTask = null;
            }
        }
        finally
        {
            base.Dispose(disposing);
        }
    }
References System.IO.MemoryStream._expandable, System.IO.MemoryStream._isOpen, System.IO.MemoryStream._lastReadTask, System.IO.MemoryStream._writable, and System.Threading.Tasks.Task< TResult >.Dispose().
Referenced by System.Net.Http.HttpContent.Dispose(), System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(), System.Transactions.TransactionManager.Reenlist(), System.IO.Compression.ZipArchiveEntry.UnloadStreams(), and System.IO.Compression.ZipArchiveEntry.WriteLocalFileHeaderAndDataIfNeeded().