Terraria: System.IO.MemoryStream.EnsureCapacity
EnsureCapacity()
bool System.IO.MemoryStream.EnsureCapacity (int value) inline private inherited
Definition at line 212 of file MemoryStream.cs.
    {
        if (value < 0)
        {
            throw new IOException(SR.IO_StreamTooLong);
        }
        if (value > _capacity)
        {
            int num = Math.Max(value, 256);
            if (num < _capacity * 2)
            {
                num = _capacity * 2;
            }
            if ((uint)(_capacity * 2) > Array.MaxLength)
            {
                num = Math.Max(value, Array.MaxLength);
            }
            Capacity = num;
            return true;
        }
        return false;
    }
References System.IO.MemoryStream._capacity, System.IO.MemoryStream.Capacity, System.SR.IO_StreamTooLong, System.Math.Max(), System.Array.MaxLength, and System.value.
Referenced by System.IO.MemoryStream.SetLength(), System.IO.MemoryStream.Write(), System.IO.MemoryStream.Write(), and System.IO.MemoryStream.WriteByte().