Terraria: System.IO.MemoryStream.TryGetBuffer
TryGetBuffer()
virtual bool System.IO.MemoryStream.TryGetBuffer (out ArraySegment< byte > buffer) inline virtual inherited
Reimplemented in System.IO.UnmanagedMemoryStreamWrapper.
Definition at line 265 of file MemoryStream.cs.
    {
        if (!_exposable)
        {
            buffer = default(ArraySegment<byte>);
            return false;
        }
        buffer = new ArraySegment<byte>(_buffer, _origin, _length - _origin);
        return true;
    }
References System.IO.MemoryStream._buffer, System.IO.MemoryStream._exposable, System.IO.MemoryStream._length, System.IO.MemoryStream._origin, and System.buffer.
Referenced by System.Net.Http.HttpContent.LimitMemoryStream.CopyToAsync(), System.Net.RequestStream.GetBuffer(), System.Net.Http.HttpContent.LimitMemoryStream.GetSizedBuffer(), System.Net.Http.HttpContent.TryGetBuffer(), System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteText(), and System.Xml.XmlBinaryNodeWriter.AttributeValue.WriteTo().