Terraria: NetDiagnosticsUI.DrawCounter
DrawCounter()
void NetDiagnosticsUI.DrawCounter (SpriteBatch spriteBatch, ref CounterForMessage counter, string title, Vector2 position) inline private
     {
         if (!counter.exemptFromBadScoreTest)
         {
             if (_highestFoundReadCount < counter.timesReceived)
             {
                 _highestFoundReadCount = counter.timesReceived;
             }
             if (_highestFoundReadBytes < counter.bytesReceived)
             {
                 _highestFoundReadBytes = counter.bytesReceived;
             }
         }
         Vector2 pos = position;
         string text = title + ": ";
         float num = Utils.Remap(counter.bytesReceived, 0f, _highestFoundReadBytes, 0f, 1f);
         Color color = Main.hslToRgb(0.3f * (1f - num), 1f, 0.5f);
         if (counter.exemptFromBadScoreTest)
         {
             color = Color.White;
         }
         string text2 = "";
         text2 = text;
         DrawText(spriteBatch, text2, pos, color);
         pos.X += 30f;
         text2 = "rx:" + $"{counter.timesReceived}";
         DrawText(spriteBatch, text2, pos, color);
         pos.X += 70f;
         text2 = $"{counter.bytesReceived}";
         DrawText(spriteBatch, text2, pos, color);
         pos.X += 70f;
         text2 = text;
         DrawText(spriteBatch, text2, pos, color);
         pos.X += 30f;
         text2 = "tx:" + $"{counter.timesSent}";
         DrawText(spriteBatch, text2, pos, color);
         pos.X += 70f;
         text2 = $"{counter.bytesSent}";
         DrawText(spriteBatch, text2, pos, color);
     }
References _highestFoundReadBytes, _highestFoundReadCount, Color, DrawText(), Main.hslToRgb(), and Utils.Remap().
Referenced by Draw().