Terraria: System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack
EtwEnableCallBack()
unsafe void System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack (in Guid sourceId, int controlCode, byte setLevel, long anyKeyword, long allKeyword, Interop::Advapi32::EVENT_FILTER_DESCRIPTOR * filterData, void * callbackContext) inline private inherited
Definition at line 196 of file EventProvider.cs.
    {
        try
        {
            ControllerCommand command = ControllerCommand.Update;
            IDictionary<string, string> dictionary = null;
            bool flag = false;
            switch (controlCode)
            {
            case 1:
            {
                m_enabled = true;
                m_level = setLevel;
                m_anyKeywordMask = anyKeyword;
                m_allKeywordMask = allKeyword;
                List<KeyValuePair<SessionInfo, bool>> sessions = GetSessions();
                if (sessions.Count == 0)
                {
                    sessions.Add(new KeyValuePair<SessionInfo, bool>(new SessionInfo(0, 0), value: true));
                }
                foreach (KeyValuePair<SessionInfo, bool> item in sessions)
                {
                    int sessionIdBit = item.Key.sessionIdBit;
                    int etwSessionId = item.Key.etwSessionId;
                    bool value = item.Value;
                    flag = true;
                    dictionary = null;
                    if (sessions.Count > 1)
                    {
                        filterData = null;
                    }
                    if (value && GetDataFromController(etwSessionId, filterData, out command, out var data, out var dataStart))
                    {
                        dictionary = new Dictionary<string, string>(4);
                        if (data != null)
{
                            while (dataStart < data.Length)
{
                                int num = FindNull(data, dataStart);
                                int num2 = num + 1;
                                int num3 = FindNull(data, num2);
                                if (num3 < data.Length)
{
                                    string @string = Encoding.UTF8.GetString(data, dataStart, num - dataStart);
                                    string string2 = Encoding.UTF8.GetString(data, num2, num3 - num2);
                                    dictionary[@string] = string2;
                                }
                                dataStart = num3 + 1;
                            }
                        }
                    }
                    OnControllerCommand(command, dictionary, value ? sessionIdBit : (-sessionIdBit), etwSessionId);
                }
                break;
            }
            case 0:
                m_enabled = false;
                m_level = 0;
                m_anyKeywordMask = 0L;
                m_allKeywordMask = 0L;
                m_liveSessions = null;
                break;
            case 2:
                command = ControllerCommand.SendManifest;
                break;
            default:
                return;
            }
            if (!flag)
            {
                OnControllerCommand(command, dictionary, 0, 0);
            }
        }
        catch
        {
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.dictionary, System.Diagnostics.Tracing.EventProvider.FindNull(), System.Diagnostics.Tracing.EventProvider.GetDataFromController(), System.Diagnostics.Tracing.EventProvider.GetSessions(), System.item, System.L, System.Diagnostics.Tracing.EventProvider.m_allKeywordMask, System.Diagnostics.Tracing.EventProvider.m_anyKeywordMask, System.Diagnostics.Tracing.EventProvider.m_enabled, System.Diagnostics.Tracing.EventProvider.m_level, System.Diagnostics.Tracing.EventProvider.m_liveSessions, System.Diagnostics.Tracing.EventProvider.OnControllerCommand(), System.Text.Encoding.UTF8, and System.value.
Referenced by System.Diagnostics.Tracing.EventProvider.Register().