Terraria: System.Diagnostics.Tracing.EventProvider.EncodeObject
EncodeObject()
static unsafe object System.Diagnostics.Tracing.EventProvider.EncodeObject (ref object data, ref EventData * dataDescriptor, ref byte * dataBuffer, ref uint totalEventSize) inline static private inherited
Definition at line 474 of file EventProvider.cs.
    {
        string text;
        byte[] array;
        while (true)
        {
            dataDescriptor->Reserved = 0u;
            text = data as string;
            array = null;
            if (text != null)
            {
                dataDescriptor->Size = (uint)((text.Length + 1) * 2);
                break;
            }
            if ((array = data as byte[]) != null)
            {
                *(int*)dataBuffer = array.Length;
                dataDescriptor->Ptr = (ulong)dataBuffer;
                dataDescriptor->Size = 4u;
                totalEventSize += dataDescriptor->Size;
                dataDescriptor++;
                dataBuffer += 16;
                dataDescriptor->Size = (uint)array.Length;
                break;
            }
            if (data is IntPtr)
            {
                dataDescriptor->Size = (uint)sizeof(IntPtr);
                IntPtr* ptr = (IntPtr*)dataBuffer;
                *ptr = (IntPtr)data;
                dataDescriptor->Ptr = (ulong)ptr;
                break;
            }
            if (data is int)
            {
                dataDescriptor->Size = 4u;
                int* ptr2 = (int*)dataBuffer;
                *ptr2 = (int)data;
                dataDescriptor->Ptr = (ulong)ptr2;
                break;
            }
            if (data is long)
            {
                dataDescriptor->Size = 8u;
                long* ptr3 = (long*)dataBuffer;
                *ptr3 = (long)data;
                dataDescriptor->Ptr = (ulong)ptr3;
                break;
            }
            if (data is uint)
            {
                dataDescriptor->Size = 4u;
                uint* ptr4 = (uint*)dataBuffer;
                *ptr4 = (uint)data;
                dataDescriptor->Ptr = (ulong)ptr4;
                break;
            }
            if (data is ulong)
            {
                dataDescriptor->Size = 8u;
                ulong* ptr5 = (ulong*)dataBuffer;
                *ptr5 = (ulong)data;
                dataDescriptor->Ptr = (ulong)ptr5;
                break;
            }
            if (data is char)
            {
                dataDescriptor->Size = 2u;
                char* ptr6 = (char*)dataBuffer;
                *ptr6 = (char)data;
                dataDescriptor->Ptr = (ulong)ptr6;
                break;
            }
            if (data is byte)
            {
                dataDescriptor->Size = 1u;
                byte* ptr7 = dataBuffer;
                *ptr7 = (byte)data;
                dataDescriptor->Ptr = (ulong)ptr7;
                break;
            }
            if (data is short)
            {
                dataDescriptor->Size = 2u;
                short* ptr8 = (short*)dataBuffer;
                *ptr8 = (short)data;
                dataDescriptor->Ptr = (ulong)ptr8;
                break;
            }
            if (data is sbyte)
            {
                dataDescriptor->Size = 1u;
                sbyte* ptr9 = (sbyte*)dataBuffer;
                *ptr9 = (sbyte)data;
                dataDescriptor->Ptr = (ulong)ptr9;
                break;
            }
            if (data is ushort)
            {
                dataDescriptor->Size = 2u;
                ushort* ptr10 = (ushort*)dataBuffer;
                *ptr10 = (ushort)data;
                dataDescriptor->Ptr = (ulong)ptr10;
                break;
            }
            if (data is float)
            {
                dataDescriptor->Size = 4u;
                float* ptr11 = (float*)dataBuffer;
                *ptr11 = (float)data;
                dataDescriptor->Ptr = (ulong)ptr11;
                break;
            }
            if (data is double)
            {
                dataDescriptor->Size = 8u;
                double* ptr12 = (double*)dataBuffer;
                *ptr12 = (double)data;
                dataDescriptor->Ptr = (ulong)ptr12;
                break;
            }
            if (data is bool)
            {
                dataDescriptor->Size = 4u;
                int* ptr13 = (int*)dataBuffer;
                if ((bool)data)
                {
                    *ptr13 = 1;
                }
                else
                {
                    *ptr13 = 0;
                }
                dataDescriptor->Ptr = (ulong)ptr13;
                break;
            }
            if (data is Guid)
            {
                dataDescriptor->Size = (uint)sizeof(Guid);
                Guid* ptr14 = (Guid*)dataBuffer;
                *ptr14 = (Guid)data;
                dataDescriptor->Ptr = (ulong)ptr14;
                break;
            }
            if (data is decimal)
            {
                dataDescriptor->Size = 16u;
                decimal* ptr15 = (decimal*)dataBuffer;
                *ptr15 = (decimal)data;
                dataDescriptor->Ptr = (ulong)ptr15;
                break;
            }
            if (data is DateTime)
            {
                long num = 0L;
                if (((DateTime)data).Ticks > 504911232000000000L)
                {
                    num = ((DateTime)data).ToFileTimeUtc();
                }
                dataDescriptor->Size = 8u;
                long* ptr16 = (long*)dataBuffer;
                *ptr16 = num;
                dataDescriptor->Ptr = (ulong)ptr16;
                break;
            }
            if (data is Enum)
            {
                try
                {
                    Type underlyingType = Enum.GetUnderlyingType(data.GetType());
                    if (underlyingType == typeof(ulong))
                    {
                        data = (ulong)data;
                    }
                    else if (underlyingType == typeof(long))
                    {
                        data = (long)data;
                    }
                    else
                    {
                        data = (int)Convert.ToInt64(data);
                    }
                }
                catch
                {
                    goto IL_0411;
                }
                continue;
            }
            goto IL_0411;
            IL_0411:
            text = ((data != null) ? data.ToString() : "");
            dataDescriptor->Size = (uint)((text.Length + 1) * 2);
            break;
        }
        totalEventSize += dataDescriptor->Size;
        dataDescriptor++;
        dataBuffer += 16;
        return ((object)text) ?? ((object)array);
    }
References System.array, System.Diagnostics.DateTime, System.Enum.GetUnderlyingType(), System.Diagnostics.Tracing.Guid, System.L, System.text, and System.Convert.ToInt64().
Referenced by System.Diagnostics.Tracing.EventProvider.WriteEvent().