Terraria: System.Diagnostics.Tracing.EventProvider.GetSessions
GetSessions()
List< KeyValuePair< SessionInfo, bool > > System.Diagnostics.Tracing.EventProvider.GetSessions () inline private inherited
Definition at line 287 of file EventProvider.cs.
    {
        List<SessionInfo> sessionList2 = null;
        GetSessionInfo(delegate(int etwSessionId, long matchAllKeywords, ref List<SessionInfo> sessionList)
        {
            GetSessionInfoCallback(etwSessionId, matchAllKeywords, ref sessionList);
        }, ref sessionList2);
        List<KeyValuePair<SessionInfo, bool>> list = new List<KeyValuePair<SessionInfo, bool>>();
        if (m_liveSessions != null)
        {
            foreach (SessionInfo liveSession in m_liveSessions)
            {
                int index;
                if ((index = IndexOfSessionInList(sessionList2, liveSession.etwSessionId)) < 0 || sessionList2[index].sessionIdBit != liveSession.sessionIdBit)
                {
                    list.Add(new KeyValuePair<SessionInfo, bool>(liveSession, value: false));
                }
            }
        }
        if (sessionList2 != null)
        {
            foreach (SessionInfo item in sessionList2)
            {
                int index2;
                if ((index2 = IndexOfSessionInList(m_liveSessions, item.etwSessionId)) < 0 || m_liveSessions[index2].sessionIdBit != item.sessionIdBit)
                {
                    list.Add(new KeyValuePair<SessionInfo, bool>(item, value: true));
                }
            }
        }
        m_liveSessions = sessionList2;
        return list;
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Diagnostics.Tracing.EventProvider.GetSessionInfo(), System.Diagnostics.Tracing.EventProvider.GetSessionInfoCallback(), System.index, System.index2, System.Diagnostics.Tracing.EventProvider.IndexOfSessionInList(), System.item, System.list, System.Diagnostics.Tracing.EventProvider.m_liveSessions, and System.value.
Referenced by System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack().