Terraria: System.Diagnostics.Tracing.EventProvider.Register
Register()
unsafe void System.Diagnostics.Tracing.EventProvider.Register (EventSource eventSource) inline package inherited
Definition at line 146 of file EventProvider.cs.
    {
        m_etwCallback = EtwEnableCallBack;
        uint num = EventRegister(eventSource, m_etwCallback);
        if (num != 0)
        {
            throw new ArgumentException(Interop.Kernel32.GetMessage((int)num));
        }
    }
References System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack(), System.Diagnostics.Tracing.EventProvider.EventRegister(), Interop.Kernel32.GetMessage(), and System.Diagnostics.Tracing.EventProvider.m_etwCallback.