Terraria: System.Diagnostics.Tracing.EventProvider.GetSessionInfo
GetSessionInfo()
unsafe void System.Diagnostics.Tracing.EventProvider.GetSessionInfo (SessionInfoCallback action, ref List< SessionInfo > sessionList) inline private inherited
Definition at line 336 of file EventProvider.cs.
    {
        int ReturnLength = 256;
        byte* ptr = stackalloc byte[(int)(uint)ReturnLength];
        byte* ptr2 = ptr;
        try
        {
            while (true)
            {
                int num = 0;
                fixed (Guid* inBuffer = &m_providerId)
                {
                    num = Interop.Advapi32.EnumerateTraceGuidsEx(Interop.Advapi32.TRACE_QUERY_INFO_CLASS.TraceGuidQueryInfo, inBuffer, sizeof(Guid), ptr2, ReturnLength, out ReturnLength);
                }
                switch (num)
                {
                default:
                    return;
                case 122:
                    if (ptr2 != ptr)
                    {
                        byte* ptr7 = ptr2;
                        ptr2 = null;
                        Marshal.FreeHGlobal((IntPtr)ptr7);
                    }
                    break;
                case 0:
                {
                    Interop.Advapi32.TRACE_GUID_INFO* ptr3 = (Interop.Advapi32.TRACE_GUID_INFO*)ptr2;
                    Interop.Advapi32.TRACE_PROVIDER_INSTANCE_INFO* ptr4 = (Interop.Advapi32.TRACE_PROVIDER_INSTANCE_INFO*)(ptr3 + 1);
                    int currentProcessId = (int)Interop.Kernel32.GetCurrentProcessId();
                    for (int i = 0; i < ptr3->InstanceCount; i++)
                    {
                        if (ptr4->Pid == currentProcessId)
{
                            Interop.Advapi32.TRACE_ENABLE_INFO* ptr5 = (Interop.Advapi32.TRACE_ENABLE_INFO*)(ptr4 + 1);
                            for (int j = 0; j < ptr4->EnableCount; j++)
{
                                action(ptr5[j].LoggerId, ptr5[j].MatchAllKeyword, ref sessionList);
                            }
                        }
                        if (ptr4->NextOffset == 0)
{
                            break;
                        }
                        byte* ptr6 = (byte*)ptr4;
                        ptr4 = (Interop.Advapi32.TRACE_PROVIDER_INSTANCE_INFO*)(ptr6 + ptr4->NextOffset);
                    }
                    return;
                }
                }
                ptr2 = (byte*)(void*)Marshal.AllocHGlobal(ReturnLength);
            }
        }
        finally
        {
            if (ptr2 != null && ptr2 != ptr)
            {
                Marshal.FreeHGlobal((IntPtr)ptr2);
            }
        }
    }
References System.action, System.Runtime.InteropServices.Marshal.AllocHGlobal(), Interop.Advapi32.EnumerateTraceGuidsEx(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Interop.Kernel32.GetCurrentProcessId(), System.Diagnostics.Tracing.EventProvider.m_providerId, and System.Diagnostics.Tracing.EventProvider.MatchAllKeyword.
Referenced by System.Diagnostics.Tracing.EventProvider.GetSessions().