Terraria: System.Xml.DocumentXmlWriter.WriteDocType
WriteDocType() [1/2]
override void System.Xml.DocumentXmlWriter.WriteDocType (string name, string pubid, string sysid, string subset) inline
Definition at line 223 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteDocType);
        XmlNode node = _document.CreateDocumentType(name, pubid, sysid, subset);
        AddChild(node, _write);
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlDocument.CreateDocumentType(), and System.Xml.DocumentXmlWriter.VerifyState().