Terraria: System.Xml.DocumentXmlWriter.Close
Close() [2/2]
override void System.Xml.DocumentXmlWriter.Close (WriteState currentState) inline package virtual
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 407 of file DocumentXmlWriter.cs.
    {
        if (currentState == WriteState.Error)
        {
            return;
        }
        try
        {
            switch (_type)
            {
            case DocumentXmlWriterType.InsertSiblingAfter:
            {
                XmlNode parentNode = _start.ParentNode;
                if (parentNode == null)
                {
                    throw new InvalidOperationException(System.SR.Xpn_MissingParent);
                }
                for (int num2 = _fragment.Count - 1; num2 >= 0; num2--)
                {
                    parentNode.InsertAfter(_fragment[num2], _start);
                }
                break;
            }
            case DocumentXmlWriterType.InsertSiblingBefore:
            {
                XmlNode parentNode = _start.ParentNode;
                if (parentNode == null)
                {
                    throw new InvalidOperationException(System.SR.Xpn_MissingParent);
                }
                for (int j = 0; j < _fragment.Count; j++)
                {
                    parentNode.InsertBefore(_fragment[j], _start);
                }
                break;
            }
            case DocumentXmlWriterType.PrependChild:
            {
                for (int num = _fragment.Count - 1; num >= 0; num--)
                {
                    _start.PrependChild(_fragment[num]);
                }
                break;
            }
            case DocumentXmlWriterType.AppendChild:
            {
                for (int i = 0; i < _fragment.Count; i++)
                {
                    _start.AppendChild(_fragment[i]);
                }
                break;
            }
            case DocumentXmlWriterType.AppendAttribute:
                CloseWithAppendAttribute();
                break;
            case DocumentXmlWriterType.ReplaceToFollowingSibling:
                if (_fragment.Count == 0)
                {
                    throw new InvalidOperationException(System.SR.Xpn_NoContent);
                }
                CloseWithReplaceToFollowingSibling();
                break;
            }
        }
        finally
        {
            _fragment.Clear();
        }
    }
References System.Xml.DocumentXmlWriter._fragment, System.Xml.DocumentXmlWriter._start, System.Xml.DocumentXmlWriter._type, System.Xml.XmlNode.AppendChild(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Xml.DocumentXmlWriter.CloseWithAppendAttribute(), System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XmlNode.InsertAfter(), System.Xml.XmlNode.InsertBefore(), System.Xml.XmlNode.ParentNode, System.Xml.XmlNode.PrependChild(), System.SR.Xpn_MissingParent, and System.SR.Xpn_NoContent.