Terraria: System.Xml.DocumentXmlWriter.WriteXmlDeclaration
WriteXmlDeclaration() [1/2]
override void System.Xml.DocumentXmlWriter.WriteXmlDeclaration (string xmldecl) inline package virtual
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 200 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteXmlDeclaration);
        XmlLoader.ParseXmlDeclarationValue(xmldecl, out var version, out var encoding, out var standalone);
        XmlNode node = _document.CreateXmlDeclaration(version, encoding, standalone);
        AddChild(node, _write);
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlDocument.CreateXmlDeclaration(), System.Xml.XmlLoader.ParseXmlDeclarationValue(), and System.Xml.DocumentXmlWriter.VerifyState().