Terraria: System.Xml.DocumentXmlWriter.WriteEndNamespaceDeclaration
WriteEndNamespaceDeclaration()
override void System.Xml.DocumentXmlWriter.WriteEndNamespaceDeclaration () inline package virtual
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 311 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteEndNamespaceDeclaration);
        if (!(_write is XmlAttribute xmlAttribute))
        {
            throw new InvalidOperationException();
        }
        if (!xmlAttribute.HasChildNodes)
        {
            XmlNode node = _document.CreateTextNode(string.Empty);
            AddChild(node, xmlAttribute);
        }
        _write = xmlAttribute.OwnerElement;
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlDocument.CreateTextNode(), and System.Xml.DocumentXmlWriter.VerifyState().
Referenced by System.Xml.DocumentXmlWriter.WriteNamespaceDeclaration().