Terraria: System.Xml.DocumentXmlWriter.CloseWithAppendAttribute
CloseWithAppendAttribute()
void System.Xml.DocumentXmlWriter.CloseWithAppendAttribute () inline private
Definition at line 477 of file DocumentXmlWriter.cs.
    {
        XmlElement xmlElement = _start as XmlElement;
        XmlAttributeCollection attributes = xmlElement.Attributes;
        for (int i = 0; i < _fragment.Count; i++)
        {
            XmlAttribute xmlAttribute = _fragment[i] as XmlAttribute;
            int num = attributes.FindNodeOffsetNS(xmlAttribute);
            if (num != -1 && ((XmlAttribute)attributes.nodes[num]).Specified)
            {
                throw new XmlException(System.SR.Xml_DupAttributeName, (xmlAttribute.Prefix.Length == 0) ? xmlAttribute.LocalName : (xmlAttribute.Prefix + ":" + xmlAttribute.LocalName));
            }
        }
        for (int j = 0; j < _fragment.Count; j++)
        {
            XmlAttribute node = _fragment[j] as XmlAttribute;
            attributes.Append(node);
        }
    }
References System.Xml.DocumentXmlWriter._fragment, System.Xml.DocumentXmlWriter._start, System.Xml.XmlAttributeCollection.Append(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.XmlAttributeCollection.FindNodeOffsetNS(), System.Xml.XmlNamedNodeMap.nodes, System.SR.Xml_DupAttributeName, and System.Xml.XmlException.
Referenced by System.Xml.DocumentXmlWriter.Close().