Terraria: System.Xml.DocumentXmlWriter.VerifyState
VerifyState()
void System.Xml.DocumentXmlWriter.VerifyState (Method method) inline private
Definition at line 608 of file DocumentXmlWriter.cs.
    {
        _state = s_changeState[(int)((int)method * 5 + _state)];
        if (_state == State.Error)
        {
            throw new InvalidOperationException(System.SR.Xml_ClosedOrError);
        }
    }
References System.Xml.DocumentXmlWriter._state, System.Xml.DocumentXmlWriter.s_changeState, and System.SR.Xml_ClosedOrError.
Referenced by System.Xml.DocumentXmlWriter.WriteCData(), System.Xml.DocumentXmlWriter.WriteComment(), System.Xml.DocumentXmlWriter.WriteDocType(), System.Xml.DocumentXmlWriter.WriteEndAttribute(), System.Xml.DocumentXmlWriter.WriteEndDocument(), System.Xml.DocumentXmlWriter.WriteEndElement(), System.Xml.DocumentXmlWriter.WriteEndNamespaceDeclaration(), System.Xml.DocumentXmlWriter.WriteEntityRef(), System.Xml.DocumentXmlWriter.WriteFullEndElement(), System.Xml.DocumentXmlWriter.WriteProcessingInstruction(), System.Xml.DocumentXmlWriter.WriteStartAttribute(), System.Xml.DocumentXmlWriter.WriteStartDocument(), System.Xml.DocumentXmlWriter.WriteStartDocument(), System.Xml.DocumentXmlWriter.WriteStartElement(), System.Xml.DocumentXmlWriter.WriteStartNamespaceDeclaration(), System.Xml.DocumentXmlWriter.WriteString(), System.Xml.DocumentXmlWriter.WriteWhitespace(), System.Xml.DocumentXmlWriter.WriteXmlDeclaration(), and System.Xml.DocumentXmlWriter.WriteXmlDeclaration().