Terraria: System.Xml.DocumentXmlWriter.WriteEntityRef
WriteEntityRef()
override void System.Xml.DocumentXmlWriter.WriteEntityRef (string name) inline
Definition at line 350 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteEntityRef);
        XmlNode node = _document.CreateEntityReference(name);
        AddChild(node, _write);
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlDocument.CreateEntityReference(), and System.Xml.DocumentXmlWriter.VerifyState().