Terraria: System.Xml.DocumentXmlWriter.WriteString
WriteString() [1/2]
override void System.Xml.DocumentXmlWriter.WriteString (string text) inline
Definition at line 373 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteString);
        XmlConvert.VerifyCharData(text, ExceptionType.ArgumentException);
        XmlNode node = _document.CreateTextNode(text);
        AddChild(node, _write);
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddChild(), System.Xml.XmlDocument.CreateTextNode(), System.text, System.Xml.XmlConvert.VerifyCharData(), and System.Xml.DocumentXmlWriter.VerifyState().