Terraria: System.Xml.DocumentXmlWriter.WriteStartNamespaceDeclaration
WriteStartNamespaceDeclaration()
override void System.Xml.DocumentXmlWriter.WriteStartNamespaceDeclaration (string prefix) inline package virtual
Reimplemented from System.Xml.XmlRawWriter.
Definition at line 303 of file DocumentXmlWriter.cs.
    {
        VerifyState(Method.WriteStartNamespaceDeclaration);
        XmlAttribute xmlAttribute = ((prefix.Length != 0) ? _document.CreateAttribute(_document.strXmlns, prefix, _document.strReservedXmlns) : _document.CreateAttribute(prefix, _document.strXmlns, _document.strReservedXmlns));
        AddAttribute(xmlAttribute, _write);
        _write = xmlAttribute;
    }
References System.Xml.DocumentXmlWriter._document, System.Xml.DocumentXmlWriter._write, System.Xml.DocumentXmlWriter.AddAttribute(), System.Xml.XmlDocument.CreateAttribute(), System.Xml.Dictionary, System.prefix, System.Xml.XmlDocument.strReservedXmlns, System.Xml.XmlDocument.strXmlns, and System.Xml.DocumentXmlWriter.VerifyState().