Terraria: System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling
CloseWithReplaceToFollowingSibling()
void System.Xml.DocumentXmlWriter.CloseWithReplaceToFollowingSibling () inline private
Definition at line 497 of file DocumentXmlWriter.cs.
    {
        XmlNode parentNode = _start.ParentNode;
        if (parentNode == null)
        {
            throw new InvalidOperationException(System.SR.Xpn_MissingParent);
        }
        if (_start != _end)
        {
            if (!DocumentXPathNavigator.IsFollowingSibling(_start, _end))
            {
                throw new InvalidOperationException(System.SR.Xpn_BadPosition);
            }
            if (_start.IsReadOnly)
            {
                throw new InvalidOperationException(System.SR.Xdom_Node_Modify_ReadOnly);
            }
            DocumentXPathNavigator.DeleteToFollowingSibling(_start.NextSibling, _end);
        }
        XmlNode xmlNode = _fragment[0];
        parentNode.ReplaceChild(xmlNode, _start);
        for (int num = _fragment.Count - 1; num >= 1; num--)
        {
            parentNode.InsertAfter(_fragment[num], xmlNode);
        }
        _navigator.ResetPosition(xmlNode);
    }
References System.Xml.DocumentXmlWriter._end, System.Xml.DocumentXmlWriter._fragment, System.Xml.DocumentXmlWriter._navigator, System.Xml.DocumentXmlWriter._start, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.DocumentXPathNavigator.DeleteToFollowingSibling(), System.Xml.XmlNode.InsertAfter(), System.Xml.DocumentXPathNavigator.IsFollowingSibling(), System.Xml.XmlNode.IsReadOnly, System.Xml.XmlNode.NextSibling, System.Xml.XmlNode.ParentNode, System.Xml.XmlNode.ReplaceChild(), System.Xml.DocumentXPathNavigator.ResetPosition(), System.SR.Xdom_Node_Modify_ReadOnly, System.SR.Xpn_BadPosition, and System.SR.Xpn_MissingParent.
Referenced by System.Xml.DocumentXmlWriter.Close().