Terraria: System.Data.Common.DbEnumerator.MoveNext
MoveNext()
bool System.Data.Common.DbEnumerator.MoveNext () inline
Implements System.Collections.IEnumerator.
Definition at line 97 of file DbEnumerator.cs.
    {
        if (_schemaInfo == null)
        {
            BuildSchemaInfo();
        }
        _current = null;
        if (_reader.Read())
        {
            object[] values = new object[_schemaInfo.Length];
            _reader.GetValues(values);
            _current = new DataRecordInternal(_schemaInfo, values, _descriptors, _fieldNameLookup);
            return true;
        }
        if (_closeReader)
        {
            _reader.Close();
        }
        return false;
    }
References System.Data.Common.DbEnumerator._closeReader, System.Data.Common.DbEnumerator._current, System.Data.Common.DbEnumerator._descriptors, System.Data.Common.DbEnumerator._fieldNameLookup, System.Data.Common.DbEnumerator._reader, System.Data.Common.DbEnumerator._schemaInfo, System.Data.Common.DbEnumerator.BuildSchemaInfo(), System.Data.IDataReader.Close(), System.Data.IDataRecord.GetValues(), System.Data.IDataReader.Read(), and System.values.