Terraria: System.Data.Common.DbEnumerator.BuildSchemaInfo
BuildSchemaInfo()
void System.Data.Common.DbEnumerator.BuildSchemaInfo () inline private
Definition at line 124 of file DbEnumerator.cs.
    {
        int fieldCount = _reader.FieldCount;
        string[] array = new string[fieldCount];
        for (int i = 0; i < fieldCount; i++)
        {
            array[i] = _reader.GetName(i);
        }
        ADP.BuildSchemaTableInfoTableNames(array);
        SchemaInfo[] array2 = new SchemaInfo[fieldCount];
        PropertyDescriptor[] array3 = new PropertyDescriptor[_reader.FieldCount];
        for (int j = 0; j < array2.Length; j++)
        {
            SchemaInfo schemaInfo = default(SchemaInfo);
            schemaInfo.name = _reader.GetName(j);
            schemaInfo.type = _reader.GetFieldType(j);
            schemaInfo.typeName = _reader.GetDataTypeName(j);
            array3[j] = new DbColumnDescriptor(j, array[j], schemaInfo.type);
            array2[j] = schemaInfo;
        }
        _schemaInfo = array2;
        _fieldNameLookup = new FieldNameLookup(_reader, -1);
        _descriptors = new PropertyDescriptorCollection(array3);
    }
References System.Data.Common.DbEnumerator._descriptors, System.Data.Common.DbEnumerator._fieldNameLookup, System.Data.Common.DbEnumerator._reader, System.Data.Common.DbEnumerator._schemaInfo, System.array, System.Data.Common.ADP.BuildSchemaTableInfoTableNames(), System.Data.IDataRecord.FieldCount, System.Data.IDataRecord.GetDataTypeName(), System.Data.IDataRecord.GetFieldType(), System.Data.IDataRecord.GetName(), and System.Data.Common.SchemaInfo.type.
Referenced by System.Data.Common.DbEnumerator.MoveNext().