Terraria: Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp
PointClamp
readonly SamplerState Microsoft.Xna.Framework.Graphics.SamplerState.PointClamp = new SamplerState(TextureFilter.Point, TextureAddressMode.Clamp, "SamplerState.PointClamp") static
Definition at line 26 of file SamplerState.cs.
Referenced by Terraria.GameContent.UI.Elements.UICharacter.UICharacter(), Terraria.GameContent.Shaders.WaterShaderData.Apply(), Terraria.Main.DrawDust(), Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCChatBubble(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Graphics.TileBatch.FlushRenderState(), Terraria.Main.GUIBarsDrawInner(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseReqest(), and Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().