Terraria: Microsoft.Xna.Framework.Graphics.SamplerState.SetDefaults
SetDefaults()
void Microsoft.Xna.Framework.Graphics.SamplerState.SetDefaults () inline private
Definition at line 151 of file SamplerState.cs.
    {
        ThrowIfBound();
        cachedFilter = TextureFilter.Linear;
        ThrowIfBound();
        cachedAddressU = TextureAddressMode.Wrap;
        ThrowIfBound();
        cachedAddressV = TextureAddressMode.Wrap;
        ThrowIfBound();
        cachedAddressW = TextureAddressMode.Wrap;
        ThrowIfBound();
        cachedMaxAnisotropy = 4;
        ThrowIfBound();
        cachedMaxMipLevel = 0;
        ThrowIfBound();
        cachedMipMapLevelOfDetailBias = 0f;
    }
References Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressU, Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressV, Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressW, Microsoft.Xna.Framework.Graphics.SamplerState.cachedFilter, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMaxAnisotropy, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMaxMipLevel, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMipMapLevelOfDetailBias, and Microsoft.Xna.Framework.Graphics.SamplerState.ThrowIfBound().
Referenced by Microsoft.Xna.Framework.Graphics.SamplerState.SamplerState(), and Microsoft.Xna.Framework.Graphics.SamplerState.SamplerState().