Terraria: Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp
LinearClamp
readonly SamplerState Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp = new SamplerState(TextureFilter.Linear, TextureAddressMode.Clamp, "SamplerState.LinearClamp") static
Definition at line 30 of file SamplerState.cs.
Referenced by Terraria.GameContent.Animations.Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect.AfterDrawing(), Terraria.GameContent.Animations.Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect.BeforeDrawing(), Terraria.GameContent.Animations.Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing(), Terraria.Main.DoDraw(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.Graphics.Effects.OverlayManager.Draw(), Terraria.Main.DrawMap(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Initializers.DyeInitializer.LoadMisc(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.SetRenderState().