Terraria: Microsoft.Xna.Framework.Graphics.SamplerState.Apply
Apply()
unsafe void Microsoft.Xna.Framework.Graphics.SamplerState.Apply (GraphicsDevice device, int samplerIndex) inline package
Definition at line 214 of file SamplerState.cs.
    {
        if (isDisposed)
        {
            throw new ObjectDisposedException(typeof(SamplerState).Name);
        }
        if (_parent != device)
        {
            _parent = device;
            isBound = true;
            uint num = *(uint*)((byte*)device.d3dCaps.t + 64);
            switch (cachedFilter)
            {
            default:
                minFilter = (_D3DTEXTUREFILTERTYPE)2;
                magFilter = (_D3DTEXTUREFILTERTYPE)2;
                mipFilter = (_D3DTEXTUREFILTERTYPE)2;
                break;
            case TextureFilter.Point:
                minFilter = (_D3DTEXTUREFILTERTYPE)1;
                magFilter = (_D3DTEXTUREFILTERTYPE)1;
                mipFilter = (_D3DTEXTUREFILTERTYPE)1;
                break;
            case TextureFilter.Anisotropic:
            {
                _D3DTEXTUREFILTERTYPE d3DTEXTUREFILTERTYPE = (_D3DTEXTUREFILTERTYPE)(((num & 0x400) | 0x800) >> 10);
                minFilter = d3DTEXTUREFILTERTYPE;
                _D3DTEXTUREFILTERTYPE d3DTEXTUREFILTERTYPE2 = (_D3DTEXTUREFILTERTYPE)(((num & 0x4000000) | 0x8000000) >> 26);
                magFilter = d3DTEXTUREFILTERTYPE2;
                mipFilter = (_D3DTEXTUREFILTERTYPE)2;
                break;
            }
            case TextureFilter.LinearMipPoint:
                minFilter = (_D3DTEXTUREFILTERTYPE)2;
                magFilter = (_D3DTEXTUREFILTERTYPE)2;
                mipFilter = (_D3DTEXTUREFILTERTYPE)1;
                break;
            case TextureFilter.PointMipLinear:
                minFilter = (_D3DTEXTUREFILTERTYPE)1;
                magFilter = (_D3DTEXTUREFILTERTYPE)1;
                mipFilter = (_D3DTEXTUREFILTERTYPE)2;
                break;
            case TextureFilter.MinLinearMagPointMipLinear:
                minFilter = (_D3DTEXTUREFILTERTYPE)2;
                magFilter = (_D3DTEXTUREFILTERTYPE)1;
                mipFilter = (_D3DTEXTUREFILTERTYPE)2;
                break;
            case TextureFilter.MinLinearMagPointMipPoint:
                minFilter = (_D3DTEXTUREFILTERTYPE)2;
                magFilter = (_D3DTEXTUREFILTERTYPE)1;
                mipFilter = (_D3DTEXTUREFILTERTYPE)1;
                break;
            case TextureFilter.MinPointMagLinearMipLinear:
                minFilter = (_D3DTEXTUREFILTERTYPE)1;
                magFilter = (_D3DTEXTUREFILTERTYPE)2;
                mipFilter = (_D3DTEXTUREFILTERTYPE)2;
                break;
            case TextureFilter.MinPointMagLinearMipPoint:
                minFilter = (_D3DTEXTUREFILTERTYPE)1;
                magFilter = (_D3DTEXTUREFILTERTYPE)2;
                mipFilter = (_D3DTEXTUREFILTERTYPE)1;
                break;
            }
            d3dAddressU = _003CModule_003E.ConvertXnaAddressModeToDx(cachedAddressU);
            d3dAddressV = _003CModule_003E.ConvertXnaAddressModeToDx(cachedAddressV);
            d3dAddressW = _003CModule_003E.ConvertXnaAddressModeToDx(cachedAddressW);
            int num2 = ((minFilter != (_D3DTEXTUREFILTERTYPE)1) ? 1 : 0);
            filterMinFlag = (uint)num2;
            int num3 = ((magFilter != (_D3DTEXTUREFILTERTYPE)1) ? 1 : 0);
            filterMagFlag = (uint)num3;
            int num4 = ((mipFilter != (_D3DTEXTUREFILTERTYPE)1) ? 1 : 0);
            filterMipFlag = (uint)num4;
            int num5 = ((d3dAddressU != (_D3DTEXTUREADDRESS)3) ? 1 : 0);
            nonClampAddressUFlag = (uint)num5;
            int num6 = ((d3dAddressV != (_D3DTEXTUREADDRESS)3) ? 1 : 0);
            nonClampAddressVFlag = (uint)num6;
        }
        IntPtr pComPtr = (IntPtr)device.pComPtr;
        Helpers.CheckDisposed(device, pComPtr);
        int num7 = ((samplerIndex < 257) ? samplerIndex : (samplerIndex - 241));
        EffectPass activePass = device.activePass;
        if (activePass != null && ((uint)activePass._stateFlags & (uint)(8 << num7)) != 0)
        {
            activePass.EndPass();
            device.activePass = null;
        }
        IDirect3DDevice9* pComPtr2 = device.pComPtr;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)6, (uint)minFilter);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)5, (uint)magFilter);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)7, (uint)mipFilter);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)1, (uint)d3dAddressU);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)2, (uint)d3dAddressV);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)3, (uint)d3dAddressW);
        uint num8 = *(uint*)((byte*)device.d3dCaps.t + 108);
        int num9 = cachedMaxAnisotropy;
        uint num10 = (((uint)num9 >= num8) ? num8 : ((uint)num9));
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)10, num10);
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)9, (uint)cachedMaxMipLevel);
        float num11 = cachedMipMapLevelOfDetailBias;
        ((delegate* unmanaged[Stdcall, Stdcall]<IntPtr, uint, _D3DSAMPLERSTATETYPE, uint, int>)(int)(*(uint*)(*(int*)pComPtr2 + 276)))((nint)pComPtr2, (uint)samplerIndex, (_D3DSAMPLERSTATETYPE)8, *(uint*)(&num11));
        StateTrackerDevice* pStateTracker = device.pStateTracker;
        uint num12 = (uint)(~(1 << num7));
        *(int*)((byte*)pStateTracker + 116) = (int)(filterMinFlag << num7) | (*(int*)((byte*)pStateTracker + 116) & (int)num12);
        *(int*)((byte*)pStateTracker + 120) = (int)(filterMagFlag << num7) | ((int)num12 & *(int*)((byte*)pStateTracker + 120));
        *(int*)((byte*)pStateTracker + 124) = (int)(filterMipFlag << num7) | (*(int*)((byte*)pStateTracker + 124) & (int)num12);
        *(int*)((byte*)pStateTracker + 128) = (int)(nonClampAddressUFlag << num7) | (*(int*)((byte*)pStateTracker + 128) & (int)num12);
        *(int*)((byte*)pStateTracker + 132) = (int)(nonClampAddressVFlag << num7) | (*(int*)((byte*)pStateTracker + 132) & (int)num12);
    }
References Microsoft.Xna.Framework.Graphics.GraphicsResource._parent, Microsoft.Xna.Framework.Graphics.GraphicsDevice.activePass, Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressU, Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressV, Microsoft.Xna.Framework.Graphics.SamplerState.cachedAddressW, Microsoft.Xna.Framework.Graphics.SamplerState.cachedFilter, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMaxAnisotropy, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMaxMipLevel, Microsoft.Xna.Framework.Graphics.SamplerState.cachedMipMapLevelOfDetailBias, Microsoft.Xna.Framework.Helpers.CheckDisposed(), Microsoft.Xna.Framework.Graphics.SamplerState.d3dAddressU, Microsoft.Xna.Framework.Graphics.SamplerState.d3dAddressV, Microsoft.Xna.Framework.Graphics.SamplerState.d3dAddressW, Microsoft.Xna.Framework.Graphics.EffectPass.EndPass(), Microsoft.Xna.Framework.Graphics.SamplerState.filterMagFlag, Microsoft.Xna.Framework.Graphics.SamplerState.filterMinFlag, Microsoft.Xna.Framework.Graphics.SamplerState.filterMipFlag, Microsoft.Xna.Framework.Graphics.SamplerState.isBound, Microsoft.Xna.Framework.Graphics.GraphicsResource.isDisposed, Microsoft.Xna.Framework.Graphics.SamplerState.magFilter, Microsoft.Xna.Framework.Graphics.SamplerState.minFilter, Microsoft.Xna.Framework.Graphics.SamplerState.mipFilter, Microsoft.Xna.Framework.Graphics.GraphicsResource.Name, Microsoft.Xna.Framework.Graphics.SamplerState.nonClampAddressUFlag, Microsoft.Xna.Framework.Graphics.SamplerState.nonClampAddressVFlag, Microsoft.Xna.Framework.Graphics.GraphicsDevice.pComPtr, and Microsoft.Xna.Framework.Graphics.GraphicsDevice.pStateTracker.
Referenced by Microsoft.Xna.Framework.Graphics.SamplerStateCollection.InitializeDeviceState().