Terraria: System.Xml.Xsl.XsltOld.Processor.TextEvent
TextEvent() [2/2]
bool System.Xml.Xsl.XsltOld.Processor.TextEvent (string text, bool disableOutputEscaping) inline package
Definition at line 593 of file Processor.cs.
    {
        if (_ignoreLevel > 0)
        {
            return true;
        }
        int state = _xsm.BeginOutlook(XPathNodeType.Text);
        switch (_builder.TextEvent(state, text, disableOutputEscaping))
        {
        case OutputResult.Continue:
            _xsm.Begin(XPathNodeType.Text);
            return true;
        case OutputResult.Interrupt:
            _xsm.Begin(XPathNodeType.Text);
            ExecutionResult = ExecResult.Interrupt;
            return true;
        case OutputResult.Overflow:
            ExecutionResult = ExecResult.Interrupt;
            return false;
        case OutputResult.Error:
        case OutputResult.Ignore:
            return true;
        default:
            return true;
        }
    }
References System.Xml.Xsl.XsltOld.Processor._builder, System.Xml.Xsl.XsltOld.Processor._ignoreLevel, System.Xml.Xsl.XsltOld.Processor._xsm, System.Xml.Xsl.XsltOld.StateMachine.Begin(), System.Xml.Xsl.XsltOld.StateMachine.BeginOutlook(), System.Xml.Xsl.XsltOld.Processor.ExecutionResult, System.state, System.text, and System.Xml.Xsl.XsltOld.RecordBuilder.TextEvent().