Terraria: System.Xml.Xsl.XsltOld.Processor.GetNavigator
GetNavigator()
XPathNavigator System.Xml.Xsl.XsltOld.Processor.GetNavigator (Uri ruri) inline package
Definition at line 128 of file Processor.cs.
    {
        XPathNavigator xPathNavigator = null;
        if (_documentCache != null)
        {
            if (_documentCache[ruri] is XPathNavigator xPathNavigator2)
            {
                return xPathNavigator2.Clone();
            }
        }
        else
        {
            _documentCache = new Hashtable();
        }
        object entity = _resolver.GetEntity(ruri, null, null);
        if (entity is Stream)
        {
            XmlTextReaderImpl xmlTextReaderImpl = new XmlTextReaderImpl(ruri.ToString(), (Stream)entity);
            xmlTextReaderImpl.XmlResolver = _resolver;
            xPathNavigator = ((IXPathNavigable)Compiler.LoadDocument(xmlTextReaderImpl)).CreateNavigator();
        }
        else
        {
            if (!(entity is XPathNavigator))
            {
                throw XsltException.Create(System.SR.Xslt_CantResolve, ruri.ToString());
            }
            xPathNavigator = (XPathNavigator)entity;
        }
        _documentCache[ruri] = xPathNavigator.Clone();
        return xPathNavigator;
    }
References System.Xml.Xsl.XsltOld.Processor._documentCache, System.Xml.Xsl.XsltOld.Processor._resolver, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.Xml.XmlResolver.GetEntity(), System.Xml.Xsl.XsltOld.Compiler.LoadDocument(), and System.SR.Xslt_CantResolve.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.Document().