Terraria: System.Xml.Xsl.XsltOld.Processor.GetVariableValue
GetVariableValue()
object System.Xml.Xsl.XsltOld.Processor.GetVariableValue (VariableAction variable) inline package
Definition at line 738 of file Processor.cs.
    {
        int varKey = variable.VarKey;
        if (variable.IsGlobal)
        {
            ActionFrame actionFrame = (ActionFrame)_actionStack[0];
            object variable2 = actionFrame.GetVariable(varKey);
            if (variable2 == VariableAction.BeingComputedMark)
            {
                throw XsltException.Create(System.SR.Xslt_CircularReference, variable.NameStr);
            }
            if (variable2 != null)
            {
                return variable2;
            }
            int length = _actionStack.Length;
            ActionFrame actionFrame2 = PushNewFrame();
            actionFrame2.Inherit(actionFrame);
            actionFrame2.Init(variable, actionFrame.NodeSet);
            do
            {
                if (((ActionFrame)_actionStack.Peek()).Execute(this))
                {
                    _actionStack.Pop();
                }
            }
            while (length < _actionStack.Length);
            return actionFrame.GetVariable(varKey);
        }
        return ((ActionFrame)_actionStack.Peek()).GetVariable(varKey);
    }
References System.Xml.Xsl.XsltOld.Processor._actionStack, System.Xml.Xsl.XsltOld.VariableAction.BeingComputedMark, System.Xml.Xsl.XsltException.Create(), System.Xml.Dictionary, System.length, System.Xml.HWStack.Length, System.Xml.HWStack.Peek(), System.Xml.HWStack.Pop(), System.Xml.Xsl.XsltOld.Processor.PushNewFrame(), and System.SR.Xslt_CircularReference.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateVariable().