Terraria: System.Runtime.Serialization.ObjectManager.RegisterObject
RegisterObject() [4/4]
void System.Runtime.Serialization.ObjectManager.RegisterObject (object obj, long objectID, SerializationInfo? info, long idOfContainingObj, MemberInfo? member, int?[] arrayIndex) inline
Definition at line 470 of file ObjectManager.cs.
    {
        if (obj == null)
        {
            throw new ArgumentNullException("obj");
        }
        if (objectID <= 0)
        {
            throw new ArgumentOutOfRangeException("objectID", System.SR.ArgumentOutOfRange_ObjectID);
        }
        if (member != null && !(member is FieldInfo))
        {
            throw new SerializationException(System.SR.Serialization_UnknownMemberInfo);
        }
        ISerializationSurrogate surrogate = null;
        if (_selector != null)
        {
            Type type = (CanCallGetType(obj) ? obj.GetType() : typeof(MarshalByRefObject));
            surrogate = _selector.GetSurrogate(type, _context, out ISurrogateSelector _);
        }
        if (obj is IDeserializationCallback)
        {
            DeserializationEventHandler handler = ((IDeserializationCallback)obj).OnDeserialization;
            AddOnDeserialization(handler);
        }
        if (arrayIndex != null)
        {
            arrayIndex = (int[])arrayIndex.Clone();
        }
        ObjectHolder objectHolder = FindObjectHolder(objectID);
        if (objectHolder == null)
        {
            objectHolder = new ObjectHolder(obj, objectID, info, surrogate, idOfContainingObj, (FieldInfo)member, arrayIndex);
            AddObjectHolder(objectHolder);
            if (objectHolder.RequiresDelayedFixup)
            {
                SpecialFixupObjects.Add(objectHolder);
            }
            AddOnDeserialized(obj);
            return;
        }
        if (objectHolder.ObjectValue != null)
        {
            throw new SerializationException(System.SR.Serialization_RegisterTwice);
        }
        objectHolder.UpdateData(obj, info, surrogate, idOfContainingObj, (FieldInfo)member, arrayIndex, this);
        if (objectHolder.DirectlyDependentObjects > 0)
        {
            CompleteObject(objectHolder, bObjectFullyComplete: false);
        }
        if (objectHolder.RequiresDelayedFixup)
        {
            SpecialFixupObjects.Add(objectHolder);
        }
        if (objectHolder.CompletelyFixed)
        {
            DoNewlyRegisteredObjectFixups(objectHolder);
            objectHolder.DependentObjects = null;
        }
        if (objectHolder.TotalDependentObjects > 0)
        {
            AddOnDeserialized(obj);
        }
        else
        {
            RaiseOnDeserializedEvent(obj);
        }
    }
References System.Runtime.Serialization.ObjectManager._context, System.Runtime.Serialization.ObjectManager._selector, System.Runtime.Serialization.ObjectHolderList.Add(), System.Runtime.Serialization.ObjectManager.AddObjectHolder(), System.Runtime.Serialization.ObjectManager.AddOnDeserialization(), System.Runtime.Serialization.ObjectManager.AddOnDeserialized(), System.SR.ArgumentOutOfRange_ObjectID, System.arrayIndex, System.Runtime.Serialization.ObjectManager.CanCallGetType(), System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(), System.Runtime.Serialization.ObjectManager.FindObjectHolder(), System.Runtime.Serialization.ISurrogateSelector.GetSurrogate(), System.info, System.obj, System.Runtime.Serialization.ObjectManager.RaiseOnDeserializedEvent(), System.SR.Serialization_RegisterTwice, System.SR.Serialization_UnknownMemberInfo, System.Runtime.Serialization.ObjectManager.SpecialFixupObjects, and System.type.