Terraria: System.Xml.Xsl.XsltOld.Processor.PushActionFrame
PushActionFrame() [1/3]
void System.Xml.Xsl.XsltOld.Processor.PushActionFrame (Action action, XPathNodeIterator nodeSet) inline package
Definition at line 348 of file Processor.cs.
    {
        ActionFrame actionFrame = PushNewFrame();
        actionFrame.Init(action, nodeSet);
    }
References System.action, and System.Xml.Xsl.XsltOld.Processor.PushNewFrame().
Referenced by System.Xml.Xsl.XsltOld.Processor.Processor(), System.Xml.Xsl.XsltOld.Processor.PushActionFrame(), and System.Xml.Xsl.XsltOld.Processor.PushTemplateLookup().