Terraria: System.Runtime.Serialization.ObjectManager.RegisterFixup
RegisterFixup()
void System.Runtime.Serialization.ObjectManager.RegisterFixup (FixupHolder fixup, long objectToBeFixed, long objectRequired) inline private
Definition at line 635 of file ObjectManager.cs.
    {
        ObjectHolder objectHolder = FindOrCreateObjectHolder(objectToBeFixed);
        if (objectHolder.RequiresSerInfoFixup && fixup._fixupType == 2)
        {
            throw new SerializationException(System.SR.Serialization_InvalidFixupType);
        }
        objectHolder.AddFixup(fixup, this);
        ObjectHolder objectHolder2 = FindOrCreateObjectHolder(objectRequired);
        objectHolder2.AddDependency(objectToBeFixed);
        _fixupCount++;
    }
References System.Runtime.Serialization.ObjectManager._fixupCount, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectManager.FindOrCreateObjectHolder(), and System.SR.Serialization_InvalidFixupType.
Referenced by System.Runtime.Serialization.ObjectManager.RecordArrayElementFixup(), System.Runtime.Serialization.ObjectManager.RecordDelayedFixup(), and System.Runtime.Serialization.ObjectManager.RecordFixup().