Terraria: System.Xml.Xsl.XsltOld.Processor.BeginEvent
BeginEvent() [2/2]
bool System.Xml.Xsl.XsltOld.Processor.BeginEvent (XPathNodeType nodeType, string prefix, string name, string nspace, bool empty, object htmlProps, bool search) inline package
Definition at line 558 of file Processor.cs.
    {
        int num = _xsm.BeginOutlook(nodeType);
        if (_ignoreLevel > 0 || num == 16)
        {
            _ignoreLevel++;
            return true;
        }
        switch (_builder.BeginEvent(num, nodeType, prefix, name, nspace, empty, htmlProps, search))
        {
        case OutputResult.Continue:
            _xsm.Begin(nodeType);
            return true;
        case OutputResult.Interrupt:
            _xsm.Begin(nodeType);
            ExecutionResult = ExecResult.Interrupt;
            return true;
        case OutputResult.Overflow:
            ExecutionResult = ExecResult.Interrupt;
            return false;
        case OutputResult.Error:
            _ignoreLevel++;
            return true;
        case OutputResult.Ignore:
            return true;
        default:
            return true;
        }
    }
References System.Xml.Xsl.XsltOld.Processor._builder, System.Xml.Xsl.XsltOld.Processor._ignoreLevel, System.Xml.Xsl.XsltOld.Processor._xsm, System.Xml.Xsl.XsltOld.StateMachine.Begin(), System.Xml.Xsl.XsltOld.RecordBuilder.BeginEvent(), System.Xml.Xsl.XsltOld.StateMachine.BeginOutlook(), System.Xml.Xsl.XsltOld.Processor.ExecutionResult, and System.prefix.