Terraria: System.Runtime.Serialization.ObjectManager.GetObject
GetObject()
virtual ? object System.Runtime.Serialization.ObjectManager.GetObject (long objectID) inline virtual
Definition at line 431 of file ObjectManager.cs.
    {
        if (objectID <= 0)
        {
            throw new ArgumentOutOfRangeException("objectID", System.SR.ArgumentOutOfRange_ObjectID);
        }
        ObjectHolder objectHolder = FindObjectHolder(objectID);
        if (objectHolder == null || objectHolder.CanObjectValueChange)
        {
            return null;
        }
        return objectHolder.ObjectValue;
    }
References System.SR.ArgumentOutOfRange_ObjectID, System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.ObjectManager.FindObjectHolder().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().