Terraria: System.Runtime.Serialization.ObjectManager.CompleteISerializableObject
CompleteISerializableObject()
void System.Runtime.Serialization.ObjectManager.CompleteISerializableObject (object obj, SerializationInfo info, StreamingContext context) inline package
Definition at line 540 of file ObjectManager.cs.
    {
        if (obj == null)
        {
            throw new ArgumentNullException("obj");
        }
        if (!(obj is ISerializable))
        {
            throw new ArgumentException(System.SR.Serialization_NotISer);
        }
        Type type = obj.GetType();
        ConstructorInfo deserializationConstructor;
        try
        {
            deserializationConstructor = GetDeserializationConstructor(type);
        }
        catch (Exception innerException)
        {
            throw new SerializationException(System.SR.Format(System.SR.Serialization_ConstructorNotFound, type), innerException);
        }
        deserializationConstructor.Invoke(obj, new object[2] { info, context });
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor(), System.Type.GetType(), System.info, System.obj, System.SR.Serialization_ConstructorNotFound, System.SR.Serialization_NotISer, and System.type.
Referenced by System.Runtime.Serialization.ObjectManager.FixupSpecialObject().