Terraria: System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS
ElementValueWithoutWS()
void System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS (XPathNavigator nav, StringBuilder builder) inline private
Definition at line 449 of file Processor.cs.
    {
        bool flag = Stylesheet.PreserveWhiteSpace(this, nav);
        if (!nav.MoveToFirstChild())
        {
            return;
        }
        do
        {
            switch (nav.NodeType)
            {
            case XPathNodeType.Text:
            case XPathNodeType.SignificantWhitespace:
                builder.Append(nav.Value);
                break;
            case XPathNodeType.Whitespace:
                if (flag)
                {
                    builder.Append(nav.Value);
                }
                break;
            case XPathNodeType.Element:
                ElementValueWithoutWS(nav, builder);
                break;
            }
        }
        while (nav.MoveToNext());
        nav.MoveToParent();
    }
References System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), System.Xml.XPath.XPathNavigator.MoveToFirstChild(), System.Xml.XPath.XPathNavigator.MoveToNext(), System.Xml.XPath.XPathNavigator.MoveToParent(), System.Xml.XPath.XPathNavigator.NodeType, System.Xml.Xsl.XsltOld.Stylesheet.PreserveWhiteSpace(), and System.Xml.XPath.XPathItem.Value.
Referenced by System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), and System.Xml.Xsl.XsltOld.Processor.ValueOf().