Terraria: System.Xml.Xsl.XsltOld.Processor.Evaluate
Evaluate()
object System.Xml.Xsl.XsltOld.Processor.Evaluate (ActionFrame context, int key) inline package
Definition at line 490 of file Processor.cs.
    {
        return GetValueQuery(key).Evaluate(context.NodeSet);
    }
References MS.Internal.Xml.XPath.Query.Evaluate(), System.Xml.Xsl.XsltOld.Processor.GetValueQuery(), System.key, and System.Xml.Xsl.XsltOld.ActionFrame.NodeSet.
Referenced by System.Xml.Xsl.XsltOld.Processor.EvaluateBoolean(), and System.Xml.Xsl.XsltOld.Processor.EvaluateString().