Terraria: System.Xml.Xsl.XsltOld.Processor.ValueOf
ValueOf() [2/2]
string System.Xml.Xsl.XsltOld.Processor.ValueOf (XPathNavigator n) inline package
Definition at line 437 of file Processor.cs.
    {
        if (_stylesheet.Whitespace && n.NodeType == XPathNodeType.Element)
        {
            StringBuilder sharedStringBuilder = GetSharedStringBuilder();
            ElementValueWithoutWS(n, sharedStringBuilder);
            ReleaseSharedStringBuilder();
            return sharedStringBuilder.ToString();
        }
        return n.Value;
    }
References System.Xml.Xsl.XsltOld.Processor._stylesheet, System.Xml.Xsl.XsltOld.Processor.ElementValueWithoutWS(), System.Xml.Xsl.XsltOld.Processor.GetSharedStringBuilder(), System.Xml.Xsl.XsltOld.Processor.ReleaseSharedStringBuilder(), and System.Xml.Xsl.XsltOld.Stylesheet.Whitespace.