Terraria: System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor
GetDeserializationConstructor()
static ConstructorInfo System.Runtime.Serialization.ObjectManager.GetDeserializationConstructor ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] Type t) inline static package
Definition at line 563 of file ObjectManager.cs.
    {
        ConstructorInfo[] constructors = t.GetConstructors(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
        foreach (ConstructorInfo constructorInfo in constructors)
        {
            ParameterInfo[] parameters = constructorInfo.GetParameters();
            if (parameters.Length == 2 && parameters[0].ParameterType == typeof(SerializationInfo) && parameters[1].ParameterType == typeof(StreamingContext))
            {
                return constructorInfo;
            }
        }
        throw new SerializationException(System.SR.Format(System.SR.Serialization_ConstructorNotFound, t.FullName));
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), System.Type.GetConstructors(), System.Reflection.ParameterInfo.ParameterType, and System.SR.Serialization_ConstructorNotFound.
Referenced by System.Runtime.Serialization.ObjectManager.CompleteISerializableObject().