Terraria: System.Xml.Xsl.XsltOld.Processor.EndEvent
EndEvent()
bool System.Xml.Xsl.XsltOld.Processor.EndEvent (XPathNodeType nodeType) inline package
Definition at line 620 of file Processor.cs.
    {
        if (_ignoreLevel > 0)
        {
            _ignoreLevel--;
            return true;
        }
        int state = _xsm.EndOutlook(nodeType);
        switch (_builder.EndEvent(state, nodeType))
        {
        case OutputResult.Continue:
            _xsm.End(nodeType);
            return true;
        case OutputResult.Interrupt:
            _xsm.End(nodeType);
            ExecutionResult = ExecResult.Interrupt;
            return true;
        case OutputResult.Overflow:
            ExecutionResult = ExecResult.Interrupt;
            return false;
        default:
            return true;
        }
    }
References System.Xml.Xsl.XsltOld.Processor._builder, System.Xml.Xsl.XsltOld.Processor._ignoreLevel, System.Xml.Xsl.XsltOld.Processor._xsm, System.Xml.Xsl.XsltOld.StateMachine.End(), System.Xml.Xsl.XsltOld.RecordBuilder.EndEvent(), System.Xml.Xsl.XsltOld.StateMachine.EndOutlook(), System.Xml.Xsl.XsltOld.Processor.ExecutionResult, and System.state.
Referenced by System.Xml.Xsl.XsltOld.Processor.CopyEndEvent().