Terraria: System.Runtime.Serialization.ObjectManager.GetCompletionInfo
GetCompletionInfo()
bool System.Runtime.Serialization.ObjectManager.GetCompletionInfo (FixupHolder fixup, [NotNullWhen(true)] out ObjectHolder holder, out object member, bool bThrowIfMissing) inline private
Definition at line 108 of file ObjectManager.cs.
    {
        member = fixup._fixupInfo;
        holder = FindObjectHolder(fixup._id);
        if (holder == null || holder.CanObjectValueChange || holder.ObjectValue == null)
        {
            if (bThrowIfMissing)
            {
                if (holder == null)
                {
                    throw new SerializationException(System.SR.Format(System.SR.Serialization_NeverSeen, fixup._id));
                }
                if (holder.IsIncompleteObjectReference)
                {
                    throw new SerializationException(System.SR.Format(System.SR.Serialization_IORIncomplete, fixup._id));
                }
                throw new SerializationException(System.SR.Format(System.SR.Serialization_ObjectNotSupplied, fixup._id));
            }
            return false;
        }
        if (!holder.CompletelyFixed && holder.ObjectValue != null && holder.ObjectValue is ValueType)
        {
            SpecialFixupObjects.Add(holder);
            return false;
        }
        return true;
    }
References System.Runtime.Serialization.ObjectHolderList.Add(), System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectManager.FindObjectHolder(), System.SR.Format(), System.SR.Serialization_IORIncomplete, System.SR.Serialization_NeverSeen, System.SR.Serialization_ObjectNotSupplied, and System.Runtime.Serialization.ObjectManager.SpecialFixupObjects.
Referenced by System.Runtime.Serialization.ObjectManager.CompleteObject().