Terraria: System.Xml.Xsl.XsltOld.Processor.GetCompiledQuery
GetCompiledQuery()
Query System.Xml.Xsl.XsltOld.Processor.GetCompiledQuery (int key) inline package
Definition at line 376 of file Processor.cs.
    {
        TheQuery theQuery = _queryStore[key];
        theQuery.CompiledQuery.CheckErrors();
        Query query = Query.Clone(_queryList[key]);
        query.SetXsltContext(new XsltCompileContext(theQuery._ScopeManager, this));
        return query;
    }
References System.Xml.Xsl.XsltOld.Processor._queryList, System.Xml.Xsl.XsltOld.Processor._queryStore, MS.Internal.Xml.XPath.Query.Clone(), System.Xml.Dictionary, and System.key.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.BuildKeyTable(), System.Xml.Xsl.XsltOld.Processor.RunQuery(), and System.Xml.Xsl.XsltOld.Processor.StartQuery().