Terraria: System.Xml.Xsl.Runtime.XmlExtensionFunctionTable.Bind
Bind()
XmlExtensionFunction System.Xml.Xsl.Runtime.XmlExtensionFunctionTable.Bind (string name, string namespaceUri, int numArgs, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicMethods | DynamicallyAccessedMemberTypes.NonPublicMethods)] Type objectType, BindingFlags flags) inline
Definition at line 18 of file XmlExtensionFunctionTable.cs.
    {
        if (_funcCached == null)
        {
            _funcCached = new XmlExtensionFunction();
        }
        _funcCached.Init(name, namespaceUri, numArgs, objectType, flags);
        if (!_table.TryGetValue(_funcCached, out var value))
        {
            value = _funcCached;
            _funcCached = null;
            value.Bind();
            _table.Add(value, value);
        }
        return value;
    }
References System.Xml.Xsl.Runtime.XmlExtensionFunctionTable._funcCached, System.Xml.Xsl.Runtime.XmlExtensionFunctionTable._table, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Xsl.Runtime.XmlExtensionFunction.Bind(), System.Xml.Xsl.Runtime.XmlExtensionFunction.Init(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.
Referenced by System.Xml.Xsl.Runtime.XmlQueryContext.InvokeXsltLateBoundFunction(), and System.Xml.Xsl.Xslt.Scripts.ResolveFunction().