Terraria: System.ComponentModel.DataAnnotations.CompareAttribute.IsValid
IsValid() [2/2]
override? ValidationResult System.ComponentModel.DataAnnotations.CompareAttribute.IsValid (object? value, ValidationContext validationContext) inline protected virtual
Reimplemented from System.ComponentModel.DataAnnotations.ValidationAttribute.
Definition at line 30 of file CompareAttribute.cs.
    {
        PropertyInfo runtimeProperty = validationContext.ObjectType.GetRuntimeProperty(OtherProperty);
        if (runtimeProperty == null)
        {
            return new ValidationResult(System.SR.Format(System.SR.CompareAttribute_UnknownProperty, OtherProperty));
        }
        if (runtimeProperty.GetIndexParameters().Length != 0)
        {
            throw new ArgumentException(System.SR.Format(System.SR.Common_PropertyNotFound, validationContext.ObjectType.FullName, OtherProperty));
        }
        object value2 = runtimeProperty.GetValue(validationContext.ObjectInstance, null);
        if (!object.Equals(value, value2))
        {
            if (OtherPropertyDisplayName == null)
            {
                OtherPropertyDisplayName = GetDisplayNameForProperty(runtimeProperty);
            }
            string[] memberNames = ((validationContext.MemberName == null) ? null : new string[1] { validationContext.MemberName });
            return new ValidationResult(FormatErrorMessage(validationContext.DisplayName), memberNames);
        }
        return null;
    }
References System.SR.Common_PropertyNotFound, System.SR.CompareAttribute_UnknownProperty, System.Attribute.Equals(), System.SR.Format(), System.ComponentModel.DataAnnotations.CompareAttribute.FormatErrorMessage(), System.ComponentModel.DataAnnotations.CompareAttribute.GetDisplayNameForProperty(), System.ComponentModel.DataAnnotations.CompareAttribute.OtherProperty, System.ComponentModel.DataAnnotations.CompareAttribute.OtherPropertyDisplayName, and System.value.