Terraria: AmbientSky.SeagullsGroupSkyEntity.CreateGroup
CreateGroup()
static List<SeagullsGroupSkyEntity> AmbientSky.SeagullsGroupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
         {
             List<SeagullsGroupSkyEntity> list = new List<SeagullsGroupSkyEntity>();
             int num = 100;
             int num2 = random.Next(5, 9);
             float num3 = 100f;
             VirtualCamera virtualCamera = new VirtualCamera(player);
             SpriteEffects spriteEffects = ((!(Main.WindForVisuals > 0f)) ? SpriteEffects.FlipHorizontally : SpriteEffects.None);
             Vector2 vector = default(Vector2);
             if (spriteEffects == SpriteEffects.FlipHorizontally)
             {
                 vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
             }
             else
             {
                 vector.X = virtualCamera.Position.X - (float)num;
             }
             vector.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
             float num4 = random.NextFloat() * 2f + 1f;
             int num5 = random.Next(30, 61) * 60;
             Vector2 vector2 = new Vector2(random.NextFloat() * 0.5f + 0.5f, random.NextFloat() * 0.5f + 0.5f);
             Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * num3;
             for (int i = 0; i < num2; i++)
             {
                 SeagullsGroupSkyEntity seagullsGroupSkyEntity = new SeagullsGroupSkyEntity(player, random);
                 seagullsGroupSkyEntity.Depth = num4 + random.NextFloat() * 0.5f;
                 seagullsGroupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 50f;
                 seagullsGroupSkyEntity.Effects = spriteEffects;
                 seagullsGroupSkyEntity.SetPositionInWorldBasedOnScreenSpace(seagullsGroupSkyEntity.Position);
                 seagullsGroupSkyEntity.LifeTime = num5 + random.Next(301);
                 seagullsGroupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.3f + 0.85f) * 0.05f, targetOffset);
                 list.Add(seagullsGroupSkyEntity);
             }
             return list;
         }
References AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), AmbientSky.SkyEntity.Depth, AmbientSky.SkyEntity.Effects, AmbientSky.FadingSkyEntity.LifeTime, FastRandom.Next(), FastRandom.NextFloat(), AmbientSky.SkyEntity.Position, VirtualCamera.Position, AmbientSky.SeagullsGroupSkyEntity.SetMagnetization(), AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), VirtualCamera.Size, Main.WindForVisuals, and Main.worldSurface.
Referenced by AmbientSky.Spawn().