Terraria: UIBestiaryInfoItemLine.UIBestiaryInfoItemLine
UIBestiaryInfoItemLine()
UIBestiaryInfoItemLine.UIBestiaryInfoItemLine (DropRateInfo info, BestiaryUICollectionInfo uiinfo, float textScale = 1f) inline
     {
         _infoDisplayItem = new Item();
         _infoDisplayItem.SetDefaults(info.itemId);
         SetBestiaryNotesOnItemCache(info);
         SetPadding(0f);
         PaddingLeft = 10f;
         PaddingRight = 10f;
         Width.Set(-14f, 1f);
         Height.Set(32f, 0f);
         Left.Set(5f, 0f);
         base.OnMouseOver += MouseOver;
         base.OnMouseOut += MouseOut;
         BorderColor = new Color(89, 116, 213, 255);
         GetDropInfo(info, uiinfo, out var stackRange, out var droprate);
         if (uiinfo.UnlockState < BestiaryEntryUnlockState.CanShowDropsWithoutDropRates_3)
         {
             _hideMouseOver = true;
             Asset<Texture2D> texture = Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Icon_Locked", (AssetRequestMode)1);
             UIElement uIElement = new UIElement
             {
                 Height = new StyleDimension(0f, 1f),
                 Width = new StyleDimension(0f, 1f),
                 HAlign = 0.5f,
                 VAlign = 0.5f
             };
             uIElement.SetPadding(0f);
             UIImage element = new UIImage(texture)
             {
                 ImageScale = 0.55f,
                 HAlign = 0.5f,
                 VAlign = 0.5f
             };
             uIElement.Append(element);
             Append(uIElement);
         }
         else
         {
             UIItemIcon element2 = new UIItemIcon(_infoDisplayItem, uiinfo.UnlockState < BestiaryEntryUnlockState.CanShowDropsWithoutDropRates_3)
             {
                 IgnoresMouseInteraction = true,
                 HAlign = 0f,
                 Left = new StyleDimension(4f, 0f)
             };
             Append(element2);
             if (!string.IsNullOrEmpty(stackRange))
             {
                 droprate = stackRange + " " + droprate;
             }
             UITextPanel<string> element3 = new UITextPanel<string>(droprate, textScale)
             {
                 IgnoresMouseInteraction = true,
                 DrawPanel = false,
                 HAlign = 1f,
                 Top = new StyleDimension(-4f, 0f)
             };
             Append(element3);
         }
     }
References _hideMouseOver, _infoDisplayItem, UIElement.Append(), Main.Assets, UIPanel.BorderColor, Color, UIPanel.DrawPanel(), GetDropInfo(), UIElement.HAlign, UIElement.Height, UIElement.IgnoresMouseInteraction, DropRateInfo.itemId, UIElement.Left, MouseOut(), MouseOver(), UIElement.PaddingLeft, UIElement.PaddingRight, StyleDimension.Set(), SetBestiaryNotesOnItemCache(), Item.SetDefaults(), UIElement.SetPadding(), UIElement.Top, BestiaryUICollectionInfo.UnlockState, UIElement.VAlign, and UIElement.Width.