Terraria: System.Security.Cryptography.DSAImplementation.DSACng.ImportParameters
ImportParameters()
override void System.Security.Cryptography.DSAImplementation.DSACng.ImportParameters (DSAParameters parameters) inline
Definition at line 138 of file DSAImplementation.cs.
        {
            if (parameters.P == null || parameters.Q == null || parameters.G == null || parameters.Y == null)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidDsaParameters_MissingFields);
            }
            if (parameters.J != null && parameters.J.Length >= parameters.P.Length)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidDsaParameters_MismatchedPJ);
            }
            bool flag = parameters.X != null;
            int num = parameters.P.Length;
            int num2 = num * 8;
            if (parameters.G.Length != num || parameters.Y.Length != num)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidDsaParameters_MismatchedPGY);
            }
            if (flag && parameters.X.Length != parameters.Q.Length)
            {
                throw new ArgumentException(System.SR.Cryptography_InvalidDsaParameters_MismatchedQX);
            }
            byte[] blob;
            if (num2 <= 1024)
            {
                GenerateV1DsaBlob(out blob, parameters, num, flag);
            }
            else
            {
                GenerateV2DsaBlob(out blob, parameters, num, flag);
            }
            ImportKeyBlob(blob, flag);
        }
References System.SR.Cryptography_InvalidDsaParameters_MismatchedPGY, System.SR.Cryptography_InvalidDsaParameters_MismatchedPJ, System.SR.Cryptography_InvalidDsaParameters_MismatchedQX, System.SR.Cryptography_InvalidDsaParameters_MissingFields, System.Security.Cryptography.DSAParameters.G, System.Security.Cryptography.DSAImplementation.DSACng.GenerateV1DsaBlob(), System.Security.Cryptography.DSAImplementation.DSACng.GenerateV2DsaBlob(), System.Security.Cryptography.DSAImplementation.DSACng.ImportKeyBlob(), System.Security.Cryptography.DSAParameters.J, System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Security.Cryptography.DSAParameters.X, and System.Security.Cryptography.DSAParameters.Y.