Terraria: System.Security.Cryptography.DSAImplementation.DSACng.VerifySignatureCore
VerifySignatureCore()
unsafe override bool System.Security.Cryptography.DSAImplementation.DSACng.VerifySignatureCore (ReadOnlySpan< byte > hash, ReadOnlySpan< byte > signature, DSASignatureFormat signatureFormat) inline protected virtual
Reimplemented from System.Security.Cryptography.DSA.
Definition at line 430 of file DSAImplementation.cs.
        {
            Span<byte> stackBuf = stackalloc byte[32];
            ReadOnlySpan<byte> hash2 = AdjustHashSizeIfNecessary(hash, stackBuf);
            switch (signatureFormat)
            {
            case DSASignatureFormat.Rfc3279DerSequence:
            {
                int fieldSizeBits = hash2.Length * 8;
                signature = this.ConvertSignatureToIeeeP1363(signatureFormat, signature, fieldSizeBits);
                break;
            }
            default:
                throw new CryptographicException(System.SR.Cryptography_UnknownSignatureFormat, signatureFormat.ToString());
            case DSASignatureFormat.IeeeP1363FixedFieldConcatenation:
                break;
            }
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            return keyHandle.VerifyHash(hash2, signature, global::Interop.NCrypt.AsymmetricPaddingMode.None, null);
        }
References System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(), System.SR.Cryptography_UnknownSignatureFormat, and System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.VerifySignature().