Terraria: System.Security.Cryptography.DSAImplementation.DSACng.ExportParameters
ExportParameters()
unsafe override DSAParameters System.Security.Cryptography.DSAImplementation.DSACng.ExportParameters (bool includePrivateParameters) inline
Definition at line 315 of file DSAImplementation.cs.
        {
            byte[] array = ExportKeyBlob(includePrivateParameters);
            global::Interop.BCrypt.KeyBlobMagicNumber keyBlobMagicNumber = (global::Interop.BCrypt.KeyBlobMagicNumber)BitConverter.ToInt32(array, 0);
            CheckMagicValueOfKey(keyBlobMagicNumber, includePrivateParameters);
            DSAParameters result = default(DSAParameters);
            fixed (byte* ptr = array)
            {
                if (keyBlobMagicNumber == global::Interop.BCrypt.KeyBlobMagicNumber.BCRYPT_DSA_PUBLIC_MAGIC || keyBlobMagicNumber == global::Interop.BCrypt.KeyBlobMagicNumber.BCRYPT_DSA_PRIVATE_MAGIC)
                {
                    if (array.Length < sizeof(global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB))
                    {
                        throw global::Interop.NCrypt.ErrorCode.E_FAIL.ToCryptographicException();
                    }
                    global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB* ptr2 = (global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB*)ptr;
                    int offset = 8;
                    result.Counter = BinaryPrimitives.ReadInt32BigEndian(global::Interop.BCrypt.Consume(array, ref offset, 4));
                    result.Seed = global::Interop.BCrypt.Consume(array, ref offset, 20);
                    result.Q = global::Interop.BCrypt.Consume(array, ref offset, 20);
                    result.P = global::Interop.BCrypt.Consume(array, ref offset, ptr2->cbKey);
                    result.G = global::Interop.BCrypt.Consume(array, ref offset, ptr2->cbKey);
                    result.Y = global::Interop.BCrypt.Consume(array, ref offset, ptr2->cbKey);
                    if (includePrivateParameters)
                    {
                        result.X = global::Interop.BCrypt.Consume(array, ref offset, 20);
                    }
                }
                else
                {
                    if (array.Length < sizeof(global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB_V2))
                    {
                        throw global::Interop.NCrypt.ErrorCode.E_FAIL.ToCryptographicException();
                    }
                    global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB_V2* ptr3 = (global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB_V2*)ptr;
                    int offset = sizeof(global::Interop.BCrypt.BCRYPT_DSA_KEY_BLOB_V2) - 4;
                    result.Counter = BinaryPrimitives.ReadInt32BigEndian(global::Interop.BCrypt.Consume(array, ref offset, 4));
                    result.Seed = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbSeedLength);
                    result.Q = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbGroupSize);
                    result.P = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbKey);
                    result.G = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbKey);
                    result.Y = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbKey);
                    if (includePrivateParameters)
                    {
                        result.X = global::Interop.BCrypt.Consume(array, ref offset, ptr3->cbGroupSize);
                    }
                }
                if (result.Counter == -1)
                {
                    result.Counter = 0;
                    result.Seed = null;
                }
                return result;
            }
        }
References System.array, System.Security.Cryptography.DSAImplementation.DSACng.CheckMagicValueOfKey(), System.Security.Cryptography.DSAParameters.Counter, System.Security.Cryptography.DSAImplementation.DSACng.ExportKeyBlob(), System.offset, System.Buffers.Binary.BinaryPrimitives.ReadInt32BigEndian(), and System.BitConverter.ToInt32().