Terraria: System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary
AdjustHashSizeIfNecessary()
ReadOnlySpan< byte > System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary (ReadOnlySpan< byte > hash, Span< byte > stackBuf) inline private
Definition at line 451 of file DSAImplementation.cs.
        {
            int num = ComputeQLength();
            if (num == hash.Length)
            {
                return hash;
            }
            if (num < hash.Length)
            {
                return hash.Slice(0, num);
            }
            int num2 = num - hash.Length;
            stackBuf.Slice(0, num2).Clear();
            hash.CopyTo(stackBuf.Slice(num2));
            return stackBuf.Slice(0, num);
        }
References System.Security.Cryptography.DSAImplementation.DSACng.ComputeQLength(), System.ReadOnlySpan< T >.CopyTo(), System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), and System.Span< T >.Slice().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.CreateSignature(), System.Security.Cryptography.DSAImplementation.DSACng.TryCreateSignatureCore(), and System.Security.Cryptography.DSAImplementation.DSACng.VerifySignatureCore().