Terraria: System.Security.Cryptography.DSAImplementation.DSACng.ExportEncryptedPkcs8
ExportEncryptedPkcs8()
byte[] System.Security.Cryptography.DSAImplementation.DSACng.ExportEncryptedPkcs8 (ReadOnlySpan< char > pkcs8Password, int kdfCount) inline private
Definition at line 62 of file DSAImplementation.cs.
        {
            using SafeNCryptKeyHandle keyHandle = GetDuplicatedKeyHandle();
            return CngKeyLite.ExportPkcs8KeyBlob(keyHandle, pkcs8Password, kdfCount);
        }
References System.Security.Cryptography.CngKeyLite.ExportPkcs8KeyBlob(), and System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.ExportEncryptedPkcs8PrivateKey().