Terraria: System.Security.Cryptography.DSAImplementation.DSACng.SetKeyHandle
SetKeyHandle()
void System.Security.Cryptography.DSAImplementation.DSACng.SetKeyHandle (SafeNCryptKeyHandle keyHandle) inline private
Definition at line 82 of file DSAImplementation.cs.
        {
            _keyHandle = keyHandle;
            int keyLength = CngKeyLite.GetKeyLength(keyHandle);
            ForceSetKeySize(keyLength);
            _lastKeySize = keyLength;
        }
References System.Security.Cryptography.DSAImplementation.DSACng._keyHandle, System.Security.Cryptography.DSAImplementation.DSACng._lastKeySize, System.Security.Cryptography.DSAImplementation.DSACng.ForceSetKeySize(), and System.Security.Cryptography.CngKeyLite.GetKeyLength().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.ImportKeyBlob().