Terraria: System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle
GetDuplicatedKeyHandle()
SafeNCryptKeyHandle System.Security.Cryptography.DSAImplementation.DSACng.GetDuplicatedKeyHandle () inline private
Definition at line 39 of file DSAImplementation.cs.
        {
            ThrowIfDisposed();
            int keySize = KeySize;
            if (_lastKeySize != keySize)
            {
                if (_keyHandle != null)
                {
                    _keyHandle.Dispose();
                }
                _keyHandle = CngKeyLite.GenerateNewExportableKey("DSA", keySize);
                _lastKeySize = keySize;
            }
            return new DuplicateSafeNCryptKeyHandle(_keyHandle);
        }
References System.Security.Cryptography.DSAImplementation.DSACng._keyHandle, System.Security.Cryptography.DSAImplementation.DSACng._lastKeySize, System.Runtime.InteropServices.SafeHandle.Dispose(), System.Security.Cryptography.CngKeyLite.GenerateNewExportableKey(), System.Security.Cryptography.AsymmetricAlgorithm.KeySize, and System.Security.Cryptography.DSAImplementation.DSACng.ThrowIfDisposed().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.ComputeQLength(), System.Security.Cryptography.DSAImplementation.DSACng.CreateSignature(), System.Security.Cryptography.DSAImplementation.DSACng.ExportEncryptedPkcs8(), System.Security.Cryptography.DSAImplementation.DSACng.ExportKeyBlob(), System.Security.Cryptography.DSAImplementation.DSACng.TryCreateSignatureCore(), System.Security.Cryptography.DSAImplementation.DSACng.TryExportEncryptedPkcs8(), and System.Security.Cryptography.DSAImplementation.DSACng.VerifySignatureCore().