using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization.Json;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using System.ServiceModel.Syndication;

[assembly: CLSCompliant(true)]
[assembly: AssemblyDefaultAlias("System.ServiceModel.Web")]
[assembly: AssemblyMetadata(".NETFrameworkAssembly", "")]
[assembly: AssemblyMetadata("Serviceable", "True")]
[assembly: AssemblyMetadata("PreferInbox", "True")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft Corporation")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription("System.ServiceModel.Web")]
[assembly: AssemblyFileVersion("6.0.21.52210")]
[assembly: AssemblyInformationalVersion("6.0.0+4822e3c3aa77eb82b2fb33c9321f923cf11ddde6")]
[assembly: AssemblyProduct("Microsoft® .NET")]
[assembly: AssemblyTitle("System.ServiceModel.Web")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/dotnet/runtime")]
[assembly: AssemblyVersion("4.0.0.0")]
[assembly: TypeForwardedTo(typeof(DataContractJsonSerializer))]
[assembly: TypeForwardedTo(typeof(IXmlJsonReaderInitializer))]
[assembly: TypeForwardedTo(typeof(IXmlJsonWriterInitializer))]
[assembly: TypeForwardedTo(typeof(JsonReaderWriterFactory))]
[assembly: TypeForwardedTo(typeof(Atom10FeedFormatter))]
[assembly: TypeForwardedTo(typeof(Atom10FeedFormatter<>))]
[assembly: TypeForwardedTo(typeof(Atom10ItemFormatter))]
[assembly: TypeForwardedTo(typeof(Atom10ItemFormatter<>))]
[assembly: TypeForwardedTo(typeof(AtomPub10CategoriesDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(AtomPub10ServiceDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(AtomPub10ServiceDocumentFormatter<>))]
[assembly: TypeForwardedTo(typeof(CategoriesDocument))]
[assembly: TypeForwardedTo(typeof(CategoriesDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(InlineCategoriesDocument))]
[assembly: TypeForwardedTo(typeof(ReferencedCategoriesDocument))]
[assembly: TypeForwardedTo(typeof(ResourceCollectionInfo))]
[assembly: TypeForwardedTo(typeof(Rss20FeedFormatter))]
[assembly: TypeForwardedTo(typeof(Rss20FeedFormatter<>))]
[assembly: TypeForwardedTo(typeof(Rss20ItemFormatter))]
[assembly: TypeForwardedTo(typeof(Rss20ItemFormatter<>))]
[assembly: TypeForwardedTo(typeof(ServiceDocument))]
[assembly: TypeForwardedTo(typeof(ServiceDocumentFormatter))]
[assembly: TypeForwardedTo(typeof(SyndicationCategory))]
[assembly: TypeForwardedTo(typeof(SyndicationContent))]
[assembly: TypeForwardedTo(typeof(SyndicationElementExtension))]
[assembly: TypeForwardedTo(typeof(SyndicationElementExtensionCollection))]
[assembly: TypeForwardedTo(typeof(SyndicationFeed))]
[assembly: TypeForwardedTo(typeof(SyndicationFeedFormatter))]
[assembly: TypeForwardedTo(typeof(SyndicationItem))]
[assembly: TypeForwardedTo(typeof(SyndicationItemFormatter))]
[assembly: TypeForwardedTo(typeof(SyndicationLink))]
[assembly: TypeForwardedTo(typeof(SyndicationPerson))]
[assembly: TypeForwardedTo(typeof(SyndicationVersions))]
[assembly: TypeForwardedTo(typeof(TextSyndicationContent))]
[assembly: TypeForwardedTo(typeof(TextSyndicationContentKind))]
[assembly: TypeForwardedTo(typeof(UrlSyndicationContent))]
[assembly: TypeForwardedTo(typeof(Workspace))]
[assembly: TypeForwardedTo(typeof(XmlSyndicationContent))]
[module: SkipLocalsInit]
