Terraria: System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.VisitUnknown
VisitUnknown()
override QilNode System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.VisitUnknown (QilNode unknown) inline protected virtual
Reimplemented from System.Xml.Xsl.Qil.QilVisitor.
Definition at line 118 of file XPathBuilder.cs.
        {
            if (unknown == _fixupCurrent)
            {
                numCurrent++;
                if (!_justCount)
                {
                    if (_environment != null)
                    {
                        unknown = _environment.GetCurrent();
                    }
                    else if (_current != null)
                    {
                        unknown = _current;
                    }
                }
            }
            else if (unknown == _fixupPosition)
            {
                numPosition++;
                if (!_justCount)
                {
                    if (_environment != null)
                    {
                        unknown = _environment.GetPosition();
                    }
                    else if (_current != null)
                    {
                        unknown = f.XsltConvert(f.PositionOf(_current), XmlQueryTypeFactory.DoubleX);
                    }
                }
            }
            else if (unknown == _fixupLast)
            {
                numLast++;
                if (!_justCount)
                {
                    if (_environment != null)
                    {
                        unknown = _environment.GetLast();
                    }
                    else if (_current != null)
                    {
                        unknown = _last;
                    }
                }
            }
            return unknown;
        }
References System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._current, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._environment, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._fixupCurrent, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._fixupLast, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._fixupPosition, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._justCount, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor._last, System.Xml.Dictionary, System.Xml.Xsl.XmlQueryTypeFactory.DoubleX, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.f, System.Xml.Xsl.XPath.IFocus.GetCurrent(), System.Xml.Xsl.XPath.IFocus.GetLast(), System.Xml.Xsl.XPath.IFocus.GetPosition(), System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numCurrent, System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numLast, and System.Xml.Xsl.XPath.XPathBuilder.FixupVisitor.numPosition.