name: generate-site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz global

    - name: Generate Documentation
      run: |
        cd doxygen
        doxygen Doxyfile
        rm -r ../docs
        mv html ../docs
        cd ..

    - name: Commit and push
      run: |
        git config user.name "InfinityNichto"
        git config user.email "u5170201@gmail.com"
        git add .
        git commit -m "Commit docs"
        git pull origin master
        git push
