Terraria: System.Net.Http.HPack.DynamicTable.Insert
Insert()
void System.Net.Http.HPack.DynamicTable.Insert (ReadOnlySpan< byte > name, ReadOnlySpan< byte > value) inline
Definition at line 40 of file DynamicTable.cs.
    {
        int length = HeaderField.GetLength(name.Length, value.Length);
        EnsureAvailable(length);
        if (length <= _maxSize)
        {
            HeaderField headerField = new HeaderField(name, value);
            _buffer[_insertIndex] = headerField;
            _insertIndex = (_insertIndex + 1) % _buffer.Length;
            _size += headerField.Length;
            _count++;
        }
    }
References System.Net.Http.HPack.DynamicTable._buffer, System.Net.Http.HPack.DynamicTable._count, System.Net.Http.HPack.DynamicTable._insertIndex, System.Net.Http.HPack.DynamicTable._maxSize, System.Net.Http.HPack.DynamicTable._size, System.Net.Http.HPack.DynamicTable.EnsureAvailable(), System.Net.Http.HPack.HeaderField.GetLength(), System.length, System.Net.Http.HPack.HeaderField.Length, and System.value.
Referenced by System.Net.Http.HPack.HPackDecoder.ProcessHeaderValue().