Terraria: System.Linq.Enumerable.SelectEnumerableIterator.MoveNext
MoveNext()
override bool System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >.MoveNext () inline
Definition at line 1626 of file Enumerable.cs.
        {
            int state = _state;
            if (state != 1)
            {
                if (state != 2)
                {
                    goto IL_005a;
                }
            }
            else
            {
                _enumerator = _source.GetEnumerator();
                _state = 2;
            }
            if (_enumerator.MoveNext())
            {
                _current = _selector(_enumerator.Current);
                return true;
            }
            Dispose();
            goto IL_005a;
            IL_005a:
            return false;
        }
References System.Linq.Enumerable.Iterator< TResult >._current, System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >._enumerator, System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >._selector, System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >._source, System.Linq.Enumerable.Iterator< TResult >._state, System.Collections.IEnumerator.Current, System.Linq.Enumerable.SelectEnumerableIterator< TSource, TResult >.Dispose(), System.Collections.IEnumerable.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), and System.state.