Terraria: System.Net.Http.HPack.DynamicTable.Resize
Resize()
void System.Net.Http.HPack.DynamicTable.Resize (int maxSize) inline
Definition at line 54 of file DynamicTable.cs.
    {
        if (maxSize > _maxSize)
        {
            HeaderField[] array = new HeaderField[maxSize / 32];
            int num = Math.Min(_buffer.Length - _removeIndex, _count);
            int length = _count - num;
            Array.Copy(_buffer, _removeIndex, array, 0, num);
            Array.Copy(_buffer, 0, array, num, length);
            _buffer = array;
            _removeIndex = 0;
            _insertIndex = _count;
            _maxSize = maxSize;
        }
        else
        {
            _maxSize = maxSize;
            EnsureAvailable(0);
        }
    }
References System.Net.Http.HPack.DynamicTable._buffer, System.Net.Http.HPack.DynamicTable._count, System.Net.Http.HPack.DynamicTable._insertIndex, System.Net.Http.HPack.DynamicTable._maxSize, System.Net.Http.HPack.DynamicTable._removeIndex, System.array, System.Array.Copy(), System.Net.Http.HPack.DynamicTable.EnsureAvailable(), System.length, System.Net.Http.HPack.HeaderField.Length, and System.Math.Min().
Referenced by System.Net.Http.HPack.HPackDecoder.SetDynamicHeaderTableSize().