Terraria: Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersectionLine
ComputeIntersectionLine()
static Ray Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersectionLine (ref Plane p1, ref Plane p2) inline static private
Definition at line 172 of file BoundingFrustum.cs.
    {
        Ray result = default(Ray);
        result.Direction = Vector3.Cross(p1.Normal, p2.Normal);
        float num = result.Direction.LengthSquared();
        result.Position = Vector3.Cross((0f - p1.D) * p2.Normal + p2.D * p1.Normal, result.Direction) / num;
        return result;
    }
References Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Ray.Direction, and Microsoft.Xna.Framework.Vector3.LengthSquared().
Referenced by Microsoft.Xna.Framework.BoundingFrustum.SetMatrix().