Terraria: Microsoft.Xna.Framework.BoundingFrustum.SupportMapping
SupportMapping()
void Microsoft.Xna.Framework.BoundingFrustum.SupportMapping (ref Vector3 v, out Vector3 result) inline package
Definition at line 575 of file BoundingFrustum.cs.
    {
        int num = 0;
        Vector3.Dot(ref cornerArray[0], ref v, out var result2);
        for (int i = 1; i < cornerArray.Length; i++)
        {
            Vector3.Dot(ref cornerArray[i], ref v, out var result3);
            if (result3 > result2)
            {
                num = i;
                result2 = result3;
            }
        }
        result = cornerArray[num];
    }
References Microsoft.Xna.Framework.BoundingFrustum.cornerArray, Microsoft.Xna.Framework.Vector3.Dot(), and Microsoft.Xna.Framework.Vector3.Length().
Referenced by Microsoft.Xna.Framework.BoundingFrustum.Intersects(), Microsoft.Xna.Framework.BoundingFrustum.Intersects(), and Microsoft.Xna.Framework.BoundingFrustum.Intersects().