Terraria: Microsoft.Xna.Framework.BoundingFrustum.SetMatrix
SetMatrix()
void Microsoft.Xna.Framework.BoundingFrustum.SetMatrix (ref Matrix value) inline private
Definition at line 117 of file BoundingFrustum.cs.
    {
        matrix = value;
        planes[2].Normal.X = 0f - value.M14 - value.M11;
        planes[2].Normal.Y = 0f - value.M24 - value.M21;
        planes[2].Normal.Z = 0f - value.M34 - value.M31;
        planes[2].D = 0f - value.M44 - value.M41;
        planes[3].Normal.X = 0f - value.M14 + value.M11;
        planes[3].Normal.Y = 0f - value.M24 + value.M21;
        planes[3].Normal.Z = 0f - value.M34 + value.M31;
        planes[3].D = 0f - value.M44 + value.M41;
        planes[4].Normal.X = 0f - value.M14 + value.M12;
        planes[4].Normal.Y = 0f - value.M24 + value.M22;
        planes[4].Normal.Z = 0f - value.M34 + value.M32;
        planes[4].D = 0f - value.M44 + value.M42;
        planes[5].Normal.X = 0f - value.M14 - value.M12;
        planes[5].Normal.Y = 0f - value.M24 - value.M22;
        planes[5].Normal.Z = 0f - value.M34 - value.M32;
        planes[5].D = 0f - value.M44 - value.M42;
        planes[0].Normal.X = 0f - value.M13;
        planes[0].Normal.Y = 0f - value.M23;
        planes[0].Normal.Z = 0f - value.M33;
        planes[0].D = 0f - value.M43;
        planes[1].Normal.X = 0f - value.M14 + value.M13;
        planes[1].Normal.Y = 0f - value.M24 + value.M23;
        planes[1].Normal.Z = 0f - value.M34 + value.M33;
        planes[1].D = 0f - value.M44 + value.M43;
        for (int i = 0; i < 6; i++)
        {
            float num = planes[i].Normal.Length();
            planes[i].Normal /= num;
            planes[i].D /= num;
        }
        Ray ray = ComputeIntersectionLine(ref planes[0], ref planes[2]);
        ref Vector3 reference = ref cornerArray[0];
        reference = ComputeIntersection(ref planes[4], ref ray);
        ref Vector3 reference2 = ref cornerArray[3];
        reference2 = ComputeIntersection(ref planes[5], ref ray);
        ray = ComputeIntersectionLine(ref planes[3], ref planes[0]);
        ref Vector3 reference3 = ref cornerArray[1];
        reference3 = ComputeIntersection(ref planes[4], ref ray);
        ref Vector3 reference4 = ref cornerArray[2];
        reference4 = ComputeIntersection(ref planes[5], ref ray);
        ray = ComputeIntersectionLine(ref planes[2], ref planes[1]);
        ref Vector3 reference5 = ref cornerArray[4];
        reference5 = ComputeIntersection(ref planes[4], ref ray);
        ref Vector3 reference6 = ref cornerArray[7];
        reference6 = ComputeIntersection(ref planes[5], ref ray);
        ray = ComputeIntersectionLine(ref planes[1], ref planes[3]);
        ref Vector3 reference7 = ref cornerArray[5];
        reference7 = ComputeIntersection(ref planes[4], ref ray);
        ref Vector3 reference8 = ref cornerArray[6];
        reference8 = ComputeIntersection(ref planes[5], ref ray);
    }
References Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersection(), Microsoft.Xna.Framework.BoundingFrustum.ComputeIntersectionLine(), Microsoft.Xna.Framework.BoundingFrustum.cornerArray, Microsoft.Xna.Framework.Plane.D, Microsoft.Xna.Framework.Vector3.Length(), Microsoft.Xna.Framework.BoundingFrustum.matrix, Microsoft.Xna.Framework.Plane.Normal, Microsoft.Xna.Framework.BoundingFrustum.planes, System.value, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingFrustum.BoundingFrustum().