Terraria: FancyErrorPrinter.ShowFailedToLoadAssetError
ShowFailedToLoadAssetError()
static void FancyErrorPrinter.ShowFailedToLoadAssetError (Exception exception, string filePath) inline static
     {
         bool flag = false;
         if (exception is UnauthorizedAccessException)
         {
             flag = true;
         }
         if (exception is FileNotFoundException)
         {
             flag = true;
         }
         if (exception is DirectoryNotFoundException)
         {
             flag = true;
         }
         if (exception is AssetLoadException)
         {
             flag = true;
         }
         if (flag)
         {
             StringBuilder stringBuilder = new StringBuilder();
             stringBuilder.AppendLine("Failed to load asset: \"" + filePath.Replace("/", "\\") + "\"!");
             List<string> suggestions = new List<string> { "Try to verify/repair the game installation, the asset may be missing.", "If you are using an Anti-virus, please make sure it does not block Terraria in any way." };
             stringBuilder.AppendLine();
             stringBuilder.AppendLine("Suggestions:");
             AppendSuggestions(stringBuilder, suggestions);
             stringBuilder.AppendLine();
             IncludeOriginalMessage(stringBuilder, exception);
             ShowTheBox(stringBuilder.ToString());
             Console.WriteLine(stringBuilder.ToString());
         }
     }
References AppendSuggestions(), IncludeOriginalMessage(), and ShowTheBox().
Referenced by Main.OnceFailedLoadingAnAsset(), and AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview().