Terraria: Microsoft.Xna.Framework.BoundingFrustum.Intersects
Intersects() [7/9]
void Microsoft.Xna.Framework.BoundingFrustum.Intersects (ref BoundingSphere sphere, out bool result) inline
Definition at line 387 of file BoundingFrustum.cs.
    {
        if (gjk == null)
        {
            gjk = new Gjk();
        }
        gjk.Reset();
        Vector3.Subtract(ref cornerArray[0], ref sphere.Center, out var result2);
        if (result2.LengthSquared() < 1E-05f)
        {
            result2 = Vector3.UnitX;
        }
        float num = float.MaxValue;
        float num2 = 0f;
        result = false;
        Vector3 v = default(Vector3);
        do
        {
            v.X = 0f - result2.X;
            v.Y = 0f - result2.Y;
            v.Z = 0f - result2.Z;
            SupportMapping(ref v, out var result3);
            sphere.SupportMapping(ref result2, out var result4);
            Vector3.Subtract(ref result3, ref result4, out var result5);
            float num3 = result2.X * result5.X + result2.Y * result5.Y + result2.Z * result5.Z;
            if (num3 > 0f)
            {
                return;
            }
            gjk.AddSupportPoint(ref result5);
            result2 = gjk.ClosestPoint;
            float num4 = num;
            num = result2.LengthSquared();
            if (num4 - num <= 1E-05f * num4)
            {
                return;
            }
            num2 = 4E-05f * gjk.MaxLengthSquared;
        }
        while (!gjk.FullSimplex && num >= num2);
        result = true;
    }
References Microsoft.Xna.Framework.Gjk.AddSupportPoint(), Microsoft.Xna.Framework.Gjk.ClosestPoint, Microsoft.Xna.Framework.BoundingFrustum.cornerArray, System.E, Microsoft.Xna.Framework.Gjk.FullSimplex, Microsoft.Xna.Framework.BoundingFrustum.gjk, Microsoft.Xna.Framework.Gjk.MaxLengthSquared, Microsoft.Xna.Framework.Gjk.Reset(), Microsoft.Xna.Framework.Vector3.Subtract(), Microsoft.Xna.Framework.BoundingFrustum.SupportMapping(), Microsoft.Xna.Framework.Vector3.UnitX, and Microsoft.Xna.Framework.Vector3.X.