Terraria: System.IO.FileSystemAclExtensions.Create
Create() [2/2]
static FileStream System.IO.FileSystemAclExtensions.Create (this FileInfo fileInfo, FileMode mode, FileSystemRights rights, FileShare share, int bufferSize, FileOptions options, FileSecurity fileSecurity) inline static
Definition at line 114 of file FileSystemAclExtensions.cs.
    {
        if (fileInfo == null)
        {
            throw new ArgumentNullException("fileInfo");
        }
        if (fileSecurity == null)
        {
            throw new ArgumentNullException("fileSecurity");
        }
        FileShare fileShare = share & ~FileShare.Inheritable;
        if (mode < FileMode.CreateNew || mode > FileMode.Append)
        {
            throw new ArgumentOutOfRangeException("mode", System.SR.ArgumentOutOfRange_Enum);
        }
        if ((fileShare < FileShare.None) || fileShare > (FileShare.ReadWrite | FileShare.Delete))
        {
            throw new ArgumentOutOfRangeException("share", System.SR.ArgumentOutOfRange_Enum);
        }
        if (bufferSize <= 0)
        {
            throw new ArgumentOutOfRangeException("bufferSize", System.SR.ArgumentOutOfRange_NeedPosNum);
        }
        if ((rights & FileSystemRights.Write) == 0 && (mode == FileMode.Truncate || mode == FileMode.CreateNew || mode == FileMode.Create || mode == FileMode.Append))
        {
            throw new ArgumentException(System.SR.Format(System.SR.Argument_InvalidFileModeAndFileSystemRightsCombo, mode, rights));
        }
        SafeFileHandle safeFileHandle = CreateFileHandle(fileInfo.FullName, mode, rights, share, options, fileSecurity);
        try
        {
            return new FileStream(safeFileHandle, GetFileStreamFileAccess(rights), bufferSize, (options & FileOptions.Asynchronous) != 0);
        }
        catch
        {
            safeFileHandle.Dispose();
            throw;
        }
    }
References System.SR.Argument_InvalidFileModeAndFileSystemRightsCombo, System.SR.ArgumentOutOfRange_Enum, System.SR.ArgumentOutOfRange_NeedPosNum, System.IO.FileSystemAclExtensions.CreateFileHandle(), System.Runtime.InteropServices.SafeHandle.Dispose(), System.SR.Format(), System.IO.FileSystemInfo.FullName, System.IO.FileSystemAclExtensions.GetFileStreamFileAccess(), and System.options.