Terraria: System.IO.FileSystemAclExtensions.CreateFileHandle
CreateFileHandle()
static unsafe SafeFileHandle System.IO.FileSystemAclExtensions.CreateFileHandle (string fullPath, FileMode mode, FileSystemRights rights, FileShare share, FileOptions options, FileSecurity security) inline static private
Definition at line 186 of file FileSystemAclExtensions.cs.
    {
        if (mode == FileMode.Append)
        {
            mode = FileMode.OpenOrCreate;
        }
        int dwFlagsAndAttributes = (int)(options | (FileOptions)1048576 | FileOptions.None);
        SafeFileHandle safeFileHandle;
        fixed (byte* ptr = security.GetSecurityDescriptorBinaryForm())
        {
            global::Interop.Kernel32.SECURITY_ATTRIBUTES sECURITY_ATTRIBUTES = default(global::Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES.nLength = (uint)sizeof(global::Interop.Kernel32.SECURITY_ATTRIBUTES);
            sECURITY_ATTRIBUTES.bInheritHandle = (((share & FileShare.Inheritable) != 0) ? global::Interop.BOOL.TRUE : global::Interop.BOOL.FALSE);
            sECURITY_ATTRIBUTES.lpSecurityDescriptor = (IntPtr)ptr;
            global::Interop.Kernel32.SECURITY_ATTRIBUTES sECURITY_ATTRIBUTES2 = sECURITY_ATTRIBUTES;
            using (System.IO.DisableMediaInsertionPrompt.Create())
            {
                safeFileHandle = global::Interop.Kernel32.CreateFile(fullPath, (int)rights, share, &sECURITY_ATTRIBUTES2, mode, dwFlagsAndAttributes, IntPtr.Zero);
                ValidateFileHandle(safeFileHandle, fullPath);
            }
        }
        return safeFileHandle;
    }
References System.IO.DisableMediaInsertionPrompt.Create(), Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(), System.Security.AccessControl.ObjectSecurity< T >.GetSecurityDescriptorBinaryForm(), System.options, System.IO.FileSystemAclExtensions.ValidateFileHandle(), and System.IntPtr.Zero.
Referenced by System.IO.FileSystemAclExtensions.Create().