Terraria: System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw
EqualsRaw()
bool System.Reflection.Metadata.Ecma335.StringHeap.EqualsRaw (StringHandle rawHandle, string asciiString) inline package
Definition at line 177 of file StringHeap.cs.
    {
        return Block.CompareUtf8NullTerminatedStringWithAsciiString(rawHandle.GetHeapOffset(), asciiString) == 0;
    }
References System.Reflection.Metadata.Ecma335.StringHeap.Block, System.Reflection.Internal.MemoryBlock.CompareUtf8NullTerminatedStringWithAsciiString(), and System.Reflection.Metadata.StringHandle.GetHeapOffset().
Referenced by System.Reflection.Metadata.MetadataReader.CalculateCustomAttributeValueTreatment(), System.Reflection.Metadata.MetadataReader.CalculateFieldDefTreatmentAndRowId(), System.Reflection.Metadata.MetadataReader.FindMscorlibAssemblyRefNoProjection(), System.Reflection.Metadata.MetadataReader.GetMethodTreatmentFromCustomAttributes(), System.Reflection.Metadata.MetadataReader.GetProjectionIndexForTypeReference(), System.Reflection.Metadata.MetadataReader.GetSpecialTypeRefTreatment(), System.Reflection.Metadata.MetadataReader.GetWellKnownTypeDefinitionTreatment(), System.Reflection.Metadata.MetadataReader.HasAttribute(), System.Reflection.Metadata.MetadataReader.IsSystemAttribute(), System.Reflection.Metadata.MetadataReader.IsWindowsAttributeUsageAttribute(), and System.Reflection.Metadata.MetadataReader.NeedsWinRTPrefix().