Terraria: System.Reflection.Metadata.Ecma335.StringHeap.GetNonVirtualStringBytes
GetNonVirtualStringBytes()
unsafe byte[] System.Reflection.Metadata.Ecma335.StringHeap.GetNonVirtualStringBytes (StringHandle handle, byte[] prefix) inline private
Definition at line 92 of file StringHeap.cs.
    {
        MemoryBlock nonVirtualStringMemoryBlock = GetNonVirtualStringMemoryBlock(handle);
        byte[] array = new byte[prefix.Length + nonVirtualStringMemoryBlock.Length];
        Buffer.BlockCopy(prefix, 0, array, 0, prefix.Length);
        Marshal.Copy((IntPtr)nonVirtualStringMemoryBlock.Pointer, array, prefix.Length, nonVirtualStringMemoryBlock.Length);
        return array;
    }
References System.array, System.Buffer.BlockCopy(), System.Runtime.InteropServices.Marshal.Copy(), System.Reflection.Metadata.Ecma335.StringHeap.GetNonVirtualStringMemoryBlock(), System.handle, System.Reflection.Internal.MemoryBlock.Length, System.Reflection.Internal.MemoryBlock.Pointer, and System.prefix.
Referenced by System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleMemoryBlock().