Terraria: System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualString
GetVirtualString()
static string System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualString (StringHandle::VirtualIndex index) inline static package
Definition at line 71 of file StringHeap.cs.
    {
        return s_virtualValues[(int)index];
    }
References System.index, and System.Reflection.Metadata.Ecma335.StringHeap.s_virtualValues.
Referenced by System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleMemoryBlock(), System.Reflection.Metadata.Ecma335.StringHeap.GetVirtualHandleString(), and System.Reflection.Metadata.MetadataReader.GetWellKnownTypeDefinitionTreatment().