Terraria: InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame
DrawInGame()
void InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame (SpriteBatch spriteBatch, Vector2 bottomAnchorPosition) inline
Implements IInGameNotification.
         {
             float opacity = Opacity;
             if (opacity > 0f)
             {
                 string text = Utils.FormatWith(_request.GetUserWrapperText(), new
                 {
                     DisplayName = _request.UserDisplayName,
                     FullId = _request.UserFullIdentifier
                 });
                 float num = Scale * 1.1f;
                 Vector2 size = (FontAssets.ItemStack.Value.MeasureString(text) + new Vector2(58f, 10f)) * num;
                 Rectangle r = Utils.CenteredRectangle(bottomAnchorPosition + new Vector2(0f, (0f - size.Y) * 0.5f), size);
                 Vector2 mouseScreen = Main.MouseScreen;
                 Color c = (r.Contains(mouseScreen.ToPoint()) ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f));
                 Utils.DrawInvBG(spriteBatch, r, c);
                 Vector2 vector = new Vector2(r.Left, r.Center.Y);
                 vector.X += 32f;
                 Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", (AssetRequestMode)1).Value;
                 Vector2 vector2 = new Vector2(r.Left + 7, MathHelper.Lerp(r.Top, r.Bottom, 0.5f) - (float)(value.Height / 2) - 1f);
                 bool flag = Utils.CenteredRectangle(vector2 + new Vector2(value.Width / 2, 0f), value.Size()).Contains(mouseScreen.ToPoint());
                 spriteBatch.Draw(value, vector2, null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, SpriteEffects.None, 0f);
                 if (flag)
                 {
                     OnMouseOver();
                 }
                 value = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete", (AssetRequestMode)1).Value;
                 vector2 = new Vector2(r.Left + 7, MathHelper.Lerp(r.Top, r.Bottom, 0.5f) + (float)(value.Height / 2) + 1f);
                 flag = Utils.CenteredRectangle(vector2 + new Vector2(value.Width / 2, 0f), value.Size()).Contains(mouseScreen.ToPoint());
                 spriteBatch.Draw(value, vector2, null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, SpriteEffects.None, 0f);
                 if (flag)
                 {
                     OnMouseOver(reject: true);
                 }
                 Utils.DrawBorderString(color: new Color(Main.mouseTextColor, Main.mouseTextColor, Main.mouseTextColor / 5, Main.mouseTextColor) * opacity, sb: spriteBatch, text: text, pos: r.Center.ToVector2() + new Vector2(10f, 0f), scale: num * 0.9f, anchorx: 0.5f, anchory: 0.4f);
             }
         }
References InGamePopups.PlayerWantsToJoinGamePopup._request, Main.Assets, Utils.CenteredRectangle(), Color, Utils.DrawBorderString(), Utils.DrawInvBG(), Utils.FormatWith(), UserJoinToServerRequest.GetUserWrapperText(), FontAssets.ItemStack, Main.MouseScreen, Main.mouseTextColor, InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver(), InGamePopups.PlayerWantsToJoinGamePopup.Opacity, InGamePopups.PlayerWantsToJoinGamePopup.Scale, and Asset< T >.Value.