Terraria: MS.Internal.Xml.XPath.QueryBuilder.Build
Build() [1/3]
Query MS.Internal.Xml.XPath.QueryBuilder.Build (AstNode root, string query) inline private
Definition at line 420 of file QueryBuilder.cs.
    {
        Reset();
        _query = query;
        Props props;
        return ProcessNode(root, Flags.None, out props);
    }
References MS.Internal.Xml.XPath.QueryBuilder._query, MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), and MS.Internal.Xml.XPath.QueryBuilder.Reset().
Referenced by System.Xml.Xsl.XsltOld.Compiler.AddQuery(), MS.Internal.Xml.XPath.CompiledXpathExpr.AddSort(), MS.Internal.Xml.XPath.QueryBuilder.Build(), MS.Internal.Xml.XPath.QueryBuilder.Build(), MS.Internal.Xml.XPath.QueryBuilder.BuildPatternQuery(), and System.Xml.XPath.XPathExpression.Compile().