Terraria: MS.Internal.Xml.XPath.QueryBuilder.ProcessFunction
ProcessFunction()
Query MS.Internal.Xml.XPath.QueryBuilder.ProcessFunction (Function root, out Props props) inline private
Definition at line 294 of file QueryBuilder.cs.
    {
        props = Props.None;
        Query query = null;
        switch (root.TypeOfFunction)
        {
        case Function.FunctionType.FuncLast:
            query = new NodeFunctions(root.TypeOfFunction, null);
            props |= Props.HasLast;
            return query;
        case Function.FunctionType.FuncPosition:
            query = new NodeFunctions(root.TypeOfFunction, null);
            props |= Props.HasPosition;
            return query;
        case Function.FunctionType.FuncCount:
            return new NodeFunctions(Function.FunctionType.FuncCount, ProcessNode(root.ArgumentList[0], Flags.None, out props));
        case Function.FunctionType.FuncID:
            query = new IDQuery(ProcessNode(root.ArgumentList[0], Flags.None, out props));
            props |= Props.NonFlat;
            return query;
        case Function.FunctionType.FuncLocalName:
        case Function.FunctionType.FuncNameSpaceUri:
        case Function.FunctionType.FuncName:
            if (root.ArgumentList != null && root.ArgumentList.Count > 0)
            {
                return new NodeFunctions(root.TypeOfFunction, ProcessNode(root.ArgumentList[0], Flags.None, out props));
            }
            return new NodeFunctions(root.TypeOfFunction, null);
        case Function.FunctionType.FuncString:
        case Function.FunctionType.FuncConcat:
        case Function.FunctionType.FuncStartsWith:
        case Function.FunctionType.FuncContains:
        case Function.FunctionType.FuncSubstringBefore:
        case Function.FunctionType.FuncSubstringAfter:
        case Function.FunctionType.FuncSubstring:
        case Function.FunctionType.FuncStringLength:
        case Function.FunctionType.FuncNormalize:
        case Function.FunctionType.FuncTranslate:
            return new StringFunctions(root.TypeOfFunction, ProcessArguments(root.ArgumentList, out props));
        case Function.FunctionType.FuncNumber:
        case Function.FunctionType.FuncSum:
        case Function.FunctionType.FuncFloor:
        case Function.FunctionType.FuncCeiling:
        case Function.FunctionType.FuncRound:
            if (root.ArgumentList != null && root.ArgumentList.Count > 0)
            {
                return new NumberFunctions(root.TypeOfFunction, ProcessNode(root.ArgumentList[0], Flags.None, out props));
            }
            return new NumberFunctions(Function.FunctionType.FuncNumber, null);
        case Function.FunctionType.FuncTrue:
        case Function.FunctionType.FuncFalse:
            return new BooleanFunctions(root.TypeOfFunction, null);
        case Function.FunctionType.FuncBoolean:
        case Function.FunctionType.FuncNot:
        case Function.FunctionType.FuncLang:
            return new BooleanFunctions(root.TypeOfFunction, ProcessNode(root.ArgumentList[0], Flags.None, out props));
        case Function.FunctionType.FuncUserDefined:
            _needContext = true;
            if (!_allowCurrent && root.Name == "current" && root.Prefix.Length == 0)
            {
                throw XPathException.Create(System.SR.Xp_CurrentNotAllowed);
            }
            if (!_allowKey && root.Name == "key" && root.Prefix.Length == 0)
            {
                throw XPathException.Create(System.SR.Xp_InvalidKeyPattern, _query);
            }
            query = new FunctionQuery(root.Prefix, root.Name, ProcessArguments(root.ArgumentList, out props));
            props |= Props.NonFlat;
            return query;
        default:
            throw XPathException.Create(System.SR.Xp_NotSupported, _query);
        }
    }
References MS.Internal.Xml.XPath.QueryBuilder._allowCurrent, MS.Internal.Xml.XPath.QueryBuilder._allowKey, MS.Internal.Xml.XPath.QueryBuilder._needContext, MS.Internal.Xml.XPath.QueryBuilder._query, MS.Internal.Xml.XPath.Function.ArgumentList, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.Function.Name, MS.Internal.Xml.XPath.Function.Prefix, MS.Internal.Xml.XPath.QueryBuilder.ProcessArguments(), MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), MS.Internal.Xml.XPath.Function.TypeOfFunction, System.SR.Xp_CurrentNotAllowed, System.SR.Xp_InvalidKeyPattern, and System.SR.Xp_NotSupported.
Referenced by MS.Internal.Xml.XPath.QueryBuilder.ProcessNode().