Terraria: MS.Internal.Xml.XPath.QueryBuilder.ProcessAxis
ProcessAxis()
Query MS.Internal.Xml.XPath.QueryBuilder.ProcessAxis (Axis root, Flags flags, out Props props) inline private
Definition at line 46 of file QueryBuilder.cs.
    {
        Query query = null;
        if (root.Prefix.Length > 0)
        {
            _needContext = true;
        }
        _firstInput = null;
        Query query2;
        if (root.Input != null)
        {
            Flags flags2 = Flags.None;
            if ((flags & Flags.PosFilter) == 0)
            {
                if (root.Input is Axis axis && root.TypeOfAxis == Axis.AxisType.Child && axis.TypeOfAxis == Axis.AxisType.DescendantOrSelf && axis.NodeType == XPathNodeType.All)
                {
                    Query qyParent;
                    if (axis.Input != null)
                    {
                        qyParent = ProcessNode(axis.Input, Flags.SmartDesc, out props);
                    }
                    else
                    {
                        qyParent = new ContextQuery();
                        props = Props.None;
                    }
                    query = new DescendantQuery(qyParent, root.Name, root.Prefix, root.NodeType, matchSelf: false, axis.AbbrAxis);
                    if ((props & Props.NonFlat) != 0)
                    {
                        query = new DocumentOrderQuery(query);
                    }
                    props |= Props.NonFlat;
                    return query;
                }
                if (root.TypeOfAxis == Axis.AxisType.Descendant || root.TypeOfAxis == Axis.AxisType.DescendantOrSelf)
                {
                    flags2 |= Flags.SmartDesc;
                }
            }
            query2 = ProcessNode(root.Input, flags2, out props);
        }
        else
        {
            query2 = new ContextQuery();
            props = Props.None;
        }
        switch (root.TypeOfAxis)
        {
        case Axis.AxisType.Ancestor:
            query = new XPathAncestorQuery(query2, root.Name, root.Prefix, root.NodeType, matchSelf: false);
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.AncestorOrSelf:
            query = new XPathAncestorQuery(query2, root.Name, root.Prefix, root.NodeType, matchSelf: true);
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.Child:
            query = (((props & Props.NonFlat) == 0) ? new ChildrenQuery(query2, root.Name, root.Prefix, root.NodeType) : new CacheChildrenQuery(query2, root.Name, root.Prefix, root.NodeType));
            break;
        case Axis.AxisType.Parent:
            query = new ParentQuery(query2, root.Name, root.Prefix, root.NodeType);
            break;
        case Axis.AxisType.Descendant:
            if ((flags & Flags.SmartDesc) != 0)
            {
                query = new DescendantOverDescendantQuery(query2, matchSelf: false, root.Name, root.Prefix, root.NodeType, abbrAxis: false);
            }
            else
            {
                query = new DescendantQuery(query2, root.Name, root.Prefix, root.NodeType, matchSelf: false, abbrAxis: false);
                if ((props & Props.NonFlat) != 0)
                {
                    query = new DocumentOrderQuery(query);
                }
            }
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.DescendantOrSelf:
            if ((flags & Flags.SmartDesc) != 0)
            {
                query = new DescendantOverDescendantQuery(query2, matchSelf: true, root.Name, root.Prefix, root.NodeType, root.AbbrAxis);
            }
            else
            {
                query = new DescendantQuery(query2, root.Name, root.Prefix, root.NodeType, matchSelf: true, root.AbbrAxis);
                if ((props & Props.NonFlat) != 0)
                {
                    query = new DocumentOrderQuery(query);
                }
            }
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.Preceding:
            query = new PrecedingQuery(query2, root.Name, root.Prefix, root.NodeType);
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.Following:
            query = new FollowingQuery(query2, root.Name, root.Prefix, root.NodeType);
            props |= Props.NonFlat;
            break;
        case Axis.AxisType.FollowingSibling:
            query = new FollSiblingQuery(query2, root.Name, root.Prefix, root.NodeType);
            if ((props & Props.NonFlat) != 0)
            {
                query = new DocumentOrderQuery(query);
            }
            break;
        case Axis.AxisType.PrecedingSibling:
            query = new PreSiblingQuery(query2, root.Name, root.Prefix, root.NodeType);
            break;
        case Axis.AxisType.Attribute:
            query = new AttributeQuery(query2, root.Name, root.Prefix, root.NodeType);
            break;
        case Axis.AxisType.Self:
            query = new XPathSelfQuery(query2, root.Name, root.Prefix, root.NodeType);
            break;
        case Axis.AxisType.Namespace:
            query = (((root.NodeType != XPathNodeType.All && root.NodeType != XPathNodeType.Element && root.NodeType != XPathNodeType.Attribute) || root.Prefix.Length != 0) ? ((Query)new EmptyQuery()) : ((Query)new NamespaceQuery(query2, root.Name, root.Prefix, root.NodeType)));
            break;
        default:
            throw XPathException.Create(System.SR.Xp_NotSupported, _query);
        }
        return query;
    }
References MS.Internal.Xml.XPath.QueryBuilder._firstInput, MS.Internal.Xml.XPath.QueryBuilder._needContext, MS.Internal.Xml.XPath.QueryBuilder._query, MS.Internal.Xml.XPath.Axis.AbbrAxis, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.Axis.Input, MS.Internal.Xml.XPath.Axis.Name, MS.Internal.Xml.XPath.Axis.NodeType, MS.Internal.Xml.XPath.Axis.Prefix, MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), System.Query, MS.Internal.Xml.XPath.Axis.TypeOfAxis, and System.SR.Xp_NotSupported.
Referenced by MS.Internal.Xml.XPath.QueryBuilder.ProcessNode().