Terraria: MS.Internal.Xml.XPath.QueryBuilder.ProcessFilter
ProcessFilter()
Query MS.Internal.Xml.XPath.QueryBuilder.ProcessFilter (Filter root, Flags flags, out Props props) inline private
Definition at line 180 of file QueryBuilder.cs.
    {
        bool flag = (flags & Flags.Filter) == 0;
        Props props2;
        Query query = ProcessNode(root.Condition, Flags.None, out props2);
        if (CanBeNumber(query) || (props2 & (Props)6) != 0)
        {
            props2 |= Props.HasPosition;
            flags |= Flags.PosFilter;
        }
        flags &= (Flags)(-2);
        Query query2 = ProcessNode(root.Input, flags | Flags.Filter, out props);
        if (root.Input.Type != AstNode.AstType.Filter)
        {
            props &= (Props)(-2);
        }
        if ((props2 & Props.HasPosition) != 0)
        {
            props |= Props.PosFilter;
        }
        if (query2 is FilterQuery filterQuery && (props2 & Props.HasPosition) == 0 && filterQuery.Condition.StaticType != XPathResultType.Any)
        {
            Query query3 = filterQuery.Condition;
            if (query3.StaticType == XPathResultType.Number)
            {
                query3 = new LogicalExpr(Operator.Op.EQ, new NodeFunctions(Function.FunctionType.FuncPosition, null), query3);
            }
            query = new BooleanExpr(Operator.Op.AND, query3, query);
            query2 = filterQuery.qyInput;
        }
        if ((props & Props.PosFilter) != 0 && query2 is DocumentOrderQuery)
        {
            query2 = ((DocumentOrderQuery)query2).input;
        }
        if (_firstInput == null)
        {
            _firstInput = query2 as BaseAxisQuery;
        }
        bool flag2 = (query2.Properties & QueryProps.Merge) != 0;
        bool flag3 = (query2.Properties & QueryProps.Reverse) != 0;
        if ((props2 & Props.HasPosition) != 0)
        {
            if (flag3)
            {
                query2 = new ReversePositionQuery(query2);
            }
            else if ((props2 & Props.HasLast) != 0)
            {
                query2 = new ForwardPositionQuery(query2);
            }
        }
        if (flag && _firstInput != null)
        {
            if (flag2 && (props & Props.PosFilter) != 0)
            {
                query2 = new FilterQuery(query2, query, noPosition: false);
                Query qyInput = _firstInput.qyInput;
                if (!(qyInput is ContextQuery))
                {
                    _firstInput.qyInput = new ContextQuery();
                    _firstInput = null;
                    return new MergeFilterQuery(qyInput, query2);
                }
                _firstInput = null;
                return query2;
            }
            _firstInput = null;
        }
        return new FilterQuery(query2, query, (props2 & Props.HasPosition) == 0);
    }
References MS.Internal.Xml.XPath.QueryBuilder._firstInput, MS.Internal.Xml.XPath.QueryBuilder.CanBeNumber(), MS.Internal.Xml.XPath.Filter.Condition, MS.Internal.Xml.XPath.Filter.Input, MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), MS.Internal.Xml.XPath.BaseAxisQuery.qyInput, and MS.Internal.Xml.XPath.AstNode.Type.
Referenced by MS.Internal.Xml.XPath.QueryBuilder.ProcessNode().