Terraria: MS.Internal.Xml.XPath.QueryBuilder.ProcessNode
ProcessNode()
Query MS.Internal.Xml.XPath.QueryBuilder.ProcessNode (AstNode root, Flags flags, out Props props) inline private
Definition at line 381 of file QueryBuilder.cs.
    {
        if (++_parseDepth > 1024)
        {
            throw XPathException.Create(System.SR.Xp_QueryTooComplex);
        }
        Query result = null;
        props = Props.None;
        switch (root.Type)
        {
        case AstNode.AstType.Axis:
            result = ProcessAxis((Axis)root, flags, out props);
            break;
        case AstNode.AstType.Operator:
            result = ProcessOperator((Operator)root, out props);
            break;
        case AstNode.AstType.Filter:
            result = ProcessFilter((Filter)root, flags, out props);
            break;
        case AstNode.AstType.ConstantOperand:
            result = new OperandQuery(((Operand)root).OperandValue);
            break;
        case AstNode.AstType.Variable:
            result = ProcessVariable((Variable)root);
            break;
        case AstNode.AstType.Function:
            result = ProcessFunction((Function)root, out props);
            break;
        case AstNode.AstType.Group:
            result = new GroupQuery(ProcessNode(((Group)root).GroupNode, Flags.None, out props));
            break;
        case AstNode.AstType.Root:
            result = new AbsoluteQuery();
            break;
        }
        _parseDepth--;
        return result;
    }
References MS.Internal.Xml.XPath.QueryBuilder._parseDepth, System.Xml.XPath.XPathException.Create(), MS.Internal.Xml.XPath.QueryBuilder.ProcessAxis(), MS.Internal.Xml.XPath.QueryBuilder.ProcessFilter(), MS.Internal.Xml.XPath.QueryBuilder.ProcessFunction(), MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), MS.Internal.Xml.XPath.QueryBuilder.ProcessOperator(), MS.Internal.Xml.XPath.QueryBuilder.ProcessVariable(), MS.Internal.Xml.XPath.AstNode.Type, and System.SR.Xp_QueryTooComplex.
Referenced by MS.Internal.Xml.XPath.QueryBuilder.Build(), MS.Internal.Xml.XPath.QueryBuilder.ProcessArguments(), MS.Internal.Xml.XPath.QueryBuilder.ProcessAxis(), MS.Internal.Xml.XPath.QueryBuilder.ProcessFilter(), MS.Internal.Xml.XPath.QueryBuilder.ProcessFunction(), MS.Internal.Xml.XPath.QueryBuilder.ProcessNode(), and MS.Internal.Xml.XPath.QueryBuilder.ProcessOperator().