Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsInt
ReadElementContentAsInt() [1/2]
override int System.Xml.XmlDictionaryReader.ReadElementContentAsInt () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 1124 of file XmlDictionaryReader.cs.
    {
        int result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = XmlConverter.ToInt32(string.Empty);
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsInt();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadContentAsInt(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), and System.Xml.XmlConverter.ToInt32().
Referenced by System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), and System.Runtime.Serialization.Json.ByteArrayHelperWithString.ReadArray().