Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId
ReadElementContentAsUniqueId()
virtual UniqueId System.Xml.XmlDictionaryReader.ReadElementContentAsUniqueId () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader.
Definition at line 1237 of file XmlDictionaryReader.cs.
    {
        UniqueId result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            try
            {
                result = new UniqueId(string.Empty);
            }
            catch (ArgumentException exception)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(string.Empty, "UniqueId", exception));
            }
            catch (FormatException exception2)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(string.Empty, "UniqueId", exception2));
            }
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsUniqueId();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.ReadContentAsUniqueId(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), and System.Xml.UniqueId.