Terraria: System.IO.Compression.InputBuffer.EnsureBitsAvailable
EnsureBitsAvailable()
bool System.IO.Compression.InputBuffer.EnsureBitsAvailable (int count) inline
Definition at line 15 of file InputBuffer.cs.
    {
        if (_bitsInBuffer < count)
        {
            if (NeedsInput())
            {
                return false;
            }
            _bitBuffer |= (uint)(_buffer.Span[0] << _bitsInBuffer);
            _buffer = _buffer.Slice(1);
            _bitsInBuffer += 8;
            if (_bitsInBuffer < count)
            {
                if (NeedsInput())
                {
                    return false;
                }
                _bitBuffer |= (uint)(_buffer.Span[0] << _bitsInBuffer);
                _buffer = _buffer.Slice(1);
                _bitsInBuffer += 8;
            }
        }
        return true;
    }
References System.IO.Compression.InputBuffer._bitBuffer, System.IO.Compression.InputBuffer._bitsInBuffer, System.IO.Compression.InputBuffer._buffer, System.count, System.IO.Compression.InputBuffer.NeedsInput(), System.Memory< T >.Slice(), and System.Memory< T >.Span.
Referenced by System.IO.Compression.InflaterManaged.Decode(), System.IO.Compression.InflaterManaged.DecodeDynamicBlockHeader(), and System.IO.Compression.InputBuffer.GetBits().