Terraria: System.Xml.XmlDictionaryReader.ReadContentAsFloat
ReadContentAsFloat()
override float System.Xml.XmlDictionaryReader.ReadContentAsFloat () inline virtual
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 1060 of file XmlDictionaryReader.cs.
    {
        return XmlConverter.ToSingle(ReadContentAsString());
    }
References System.Xml.XmlDictionaryReader.ReadContentAsString(), and System.Xml.XmlConverter.ToSingle().
Referenced by System.Xml.XmlDictionaryReader.ReadElementContentAsFloat(), and System.Xml.XmlBinaryWriter.WriteTextNode().