Terraria: System.Xml.XmlDictionaryReader.ReadArray
ReadArray() [1/20]
virtual int System.Xml.XmlDictionaryReader.ReadArray (string localName, string namespaceUri, bool[] array, int offset, int count) inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader.
Definition at line 1418 of file XmlDictionaryReader.cs.
    {
        CheckArray(array, offset, count);
        int i;
        for (i = 0; i < count; i++)
        {
            if (!IsStartElement(localName, namespaceUri))
            {
                break;
            }
            array[offset + i] = ReadElementContentAsBoolean();
        }
        return i;
    }
References System.array, System.Xml.XmlDictionaryReader.CheckArray(), System.count, System.Xml.XmlReader.IsStartElement(), System.offset, and System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean().
Referenced by System.Xml.BooleanArrayHelperWithString.ReadArray(), System.Xml.DateTimeArrayHelperWithString.ReadArray(), System.Xml.DecimalArrayHelperWithString.ReadArray(), System.Xml.DoubleArrayHelperWithString.ReadArray(), System.Xml.SingleArrayHelperWithString.ReadArray(), System.Xml.GuidArrayHelperWithString.ReadArray(), System.Xml.Int32ArrayHelperWithString.ReadArray(), System.Xml.Int64ArrayHelperWithString.ReadArray(), System.Xml.Int16ArrayHelperWithString.ReadArray(), System.Xml.TimeSpanArrayHelperWithString.ReadArray(), System.Xml.BooleanArrayHelperWithDictionaryString.ReadArray(), System.Xml.DateTimeArrayHelperWithDictionaryString.ReadArray(), System.Xml.DecimalArrayHelperWithDictionaryString.ReadArray(), System.Xml.DoubleArrayHelperWithDictionaryString.ReadArray(), System.Xml.SingleArrayHelperWithDictionaryString.ReadArray(), System.Xml.GuidArrayHelperWithDictionaryString.ReadArray(), System.Xml.Int32ArrayHelperWithDictionaryString.ReadArray(), System.Xml.Int64ArrayHelperWithDictionaryString.ReadArray(), System.Xml.Int16ArrayHelperWithDictionaryString.ReadArray(), System.Xml.TimeSpanArrayHelperWithDictionaryString.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Xml.XmlDictionaryReader.ReadArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadBooleanArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDateTimeArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDecimalArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadDoubleArray(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt32Array(), System.Runtime.Serialization.XmlReaderDelegator.TryReadInt64Array(), and System.Runtime.Serialization.XmlReaderDelegator.TryReadSingleArray().