Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsBase64
ReadElementContentAsBase64() [1/2]
virtual byte[] System.Xml.XmlDictionaryReader.ReadElementContentAsBase64 () inline virtual inherited
Definition at line 1314 of file XmlDictionaryReader.cs.
    {
        byte[] result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = Array.Empty<byte>();
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsBase64();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.ReadContentAsBase64(), System.Xml.XmlReader.ReadEndElement(), and System.Xml.XmlReader.ReadStartElement().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsBase64().