Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsString
ReadElementContentAsString() [1/2]
override string System.Xml.XmlDictionaryReader.ReadElementContentAsString () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 1090 of file XmlDictionaryReader.cs.
    {
        string result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = string.Empty;
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsString();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlReader.ReadEndElement(), and System.Xml.XmlReader.ReadStartElement().