Terraria: System.Xml.XmlDictionaryReader.ReadArray
ReadArray() [4/20]
virtual int System.Xml.XmlDictionaryReader.ReadArray (string localName, string namespaceUri, double[] array, int offset, int count) inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader.
Definition at line 1573 of file XmlDictionaryReader.cs.
    {
        CheckArray(array, offset, count);
        int i;
        for (i = 0; i < count; i++)
        {
            if (!IsStartElement(localName, namespaceUri))
            {
                break;
            }
            array[offset + i] = ReadElementContentAsDouble();
        }
        return i;
    }
References System.array, System.Xml.XmlDictionaryReader.CheckArray(), System.count, System.Xml.XmlReader.IsStartElement(), System.offset, and System.Xml.XmlDictionaryReader.ReadElementContentAsDouble().