Terraria: System.Xml.XmlDictionaryReader.ReadContentAsString
ReadContentAsString() [1/4]
override string System.Xml.XmlDictionaryReader.ReadContentAsString () inline virtual
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 753 of file XmlDictionaryReader.cs.
    {
        return ReadContentAsString(Quotas.MaxStringContentLength);
    }
References System.Xml.XmlDictionaryReaderQuotas.MaxStringContentLength, System.Xml.XmlDictionaryReader.Quotas, and System.Xml.XmlDictionaryReader.ReadContentAsString().
Referenced by System.Xml.XmlDictionaryReader.ReadContentAsDecimal(), System.Xml.XmlDictionaryReader.ReadContentAsFloat(), System.Xml.XmlDictionaryReader.ReadContentAsGuid(), System.Xml.XmlDictionaryReader.ReadContentAsQualifiedName(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlDictionaryReader.ReadContentAsTimeSpan(), System.Xml.XmlDictionaryReader.ReadContentAsUniqueId(), and System.Xml.XmlDictionaryReader.ReadElementContentAsString().