Terraria: System.Data.FunctionNode.Optimize
Optimize()
override ExpressionNode System.Data.FunctionNode.Optimize () inline package
Definition at line 240 of file FunctionNode.cs.
    {
        for (int i = 0; i < _argumentCount; i++)
        {
            _arguments[i] = _arguments[i].Optimize();
        }
        if (s_funcs[_info]._id == FunctionId.In)
        {
            if (!IsConstant())
            {
                throw ExprException.NonConstantArgument();
            }
        }
        else if (IsConstant())
        {
            return new ConstNode(base.table, ValueType.Object, Eval(), fParseQuotes: false);
        }
        return this;
    }
References System.Data.FunctionNode._argumentCount, System.Data.FunctionNode._arguments, System.Data.FunctionNode._info, System.Data.FunctionNode.Eval(), System.Data.FunctionNode.IsConstant(), System.Data.ExprException.NonConstantArgument(), System.Data.ExpressionNode.Optimize(), and System.Data.FunctionNode.s_funcs.