Terraria: System.Xml.XmlDictionaryReader.CreateMtomReader
CreateMtomReader() [5/8]
static XmlDictionaryReader System.Xml.XmlDictionaryReader.CreateMtomReader (Stream stream, Encoding encoding, XmlDictionaryReaderQuotas quotas) inline static inherited
Definition at line 482 of file XmlDictionaryReader.cs.
    {
        if (encoding == null)
        {
            throw DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull("encoding");
        }
        return CreateMtomReader(stream, new Encoding[1] { encoding }, quotas);
    }
References System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.Dictionary, System.stream, and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperArgumentNull().
Referenced by System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateMtomReader(), System.Xml.XmlDictionaryReader.CreateMtomReader(), and System.Xml.XmlDictionaryReader.CreateMtomReader().