Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan
ReadElementContentAsTimeSpan()
virtual TimeSpan System.Xml.XmlDictionaryReader.ReadElementContentAsTimeSpan () inline virtual inherited
Reimplemented in System.Xml.XmlBinaryReader.
Definition at line 1297 of file XmlDictionaryReader.cs.
    {
        TimeSpan result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = XmlConverter.ToTimeSpan(string.Empty);
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsTimeSpan();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.ReadContentAsTimeSpan(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), and System.Xml.XmlConverter.ToTimeSpan().
Referenced by System.Xml.XmlDictionaryReader.ReadArray().