Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean
ReadElementContentAsBoolean() [1/2]
override bool System.Xml.XmlDictionaryReader.ReadElementContentAsBoolean () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 1107 of file XmlDictionaryReader.cs.
    {
        bool result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = XmlConverter.ToBoolean(string.Empty);
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsBoolean();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadContentAsBoolean(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), and System.Xml.XmlConverter.ToBoolean().
Referenced by System.Xml.XmlDictionaryReader.ReadArray().