Terraria: System.Data.FunctionNode.Eval
Eval() [2/3]
override object System.Data.FunctionNode.Eval (DataRow row, DataRowVersion version) inline package
Definition at line 127 of file FunctionNode.cs.
    {
        object[] array = new object[_argumentCount];
        if (s_funcs[_info]._id == FunctionId.Convert)
        {
            if (_argumentCount != 2)
            {
                throw ExprException.FunctionArgumentCount(_name);
            }
            array[0] = _arguments[0].Eval(row, version);
            array[1] = GetDataType(_arguments[1]);
        }
        else if (s_funcs[_info]._id != FunctionId.Iif)
        {
            for (int i = 0; i < _argumentCount; i++)
            {
                array[i] = _arguments[i].Eval(row, version);
                if (!s_funcs[_info]._isValidateArguments)
                {
                    continue;
                }
                if (array[i] == DBNull.Value || typeof(object) == s_funcs[_info]._parameters[i])
                {
                    return DBNull.Value;
                }
                if (!(array[i].GetType() != s_funcs[_info]._parameters[i]))
                {
                    continue;
                }
                if (s_funcs[_info]._parameters[i] == typeof(int) && ExpressionNode.IsInteger(DataStorage.GetStorageType(array[i].GetType())))
                {
                    array[i] = Convert.ToInt32(array[i], base.FormatProvider);
                    continue;
                }
                if (s_funcs[_info]._id == FunctionId.Trim || s_funcs[_info]._id == FunctionId.Substring || s_funcs[_info]._id == FunctionId.Len)
                {
                    if (typeof(string) != array[i].GetType() && typeof(SqlString) != array[i].GetType())
                    {
                        throw ExprException.ArgumentType(s_funcs[_info]._name, i + 1, s_funcs[_info]._parameters[i]);
                    }
                    continue;
                }
                throw ExprException.ArgumentType(s_funcs[_info]._name, i + 1, s_funcs[_info]._parameters[i]);
            }
        }
        return EvalFunction(s_funcs[_info]._id, array, row, version);
    }
References System.Data.FunctionNode._argumentCount, System.Data.FunctionNode._arguments, System.Data.FunctionNode._info, System.Data.FunctionNode._name, System.Data.ExprException.ArgumentType(), System.array, System.Runtime.Serialization.Dictionary, System.Data.ExpressionNode.Eval(), System.Data.FunctionNode.EvalFunction(), System.Data.ExprException.FunctionArgumentCount(), System.Data.FunctionNode.GetDataType(), System.Data.Common.DataStorage.GetStorageType(), System.Data.ExpressionNode.IsInteger(), System.Data.FunctionNode.s_funcs, System.Convert.ToInt32(), and System.DBNull.Value.