Terraria: System.Xml.XmlDictionaryReader.ReadFullStartElement
ReadFullStartElement() [1/4]
virtual void System.Xml.XmlDictionaryReader.ReadFullStartElement () inline virtual inherited
Definition at line 604 of file XmlDictionaryReader.cs.
    {
        MoveToStartElement();
        if (IsEmptyElement)
        {
            XmlExceptionHelper.ThrowFullStartElementExpected(this);
        }
        Read();
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlDictionaryReader.MoveToStartElement(), System.Xml.XmlReader.Read(), and System.Xml.XmlExceptionHelper.ThrowFullStartElementExpected().