Terraria: System.Data.FunctionNode.Check
Check()
void System.Data.FunctionNode.Check () inline package
Definition at line 491 of file FunctionNode.cs.
    {
        if (_info < 0)
        {
            throw ExprException.UndefinedFunction(_name);
        }
        if (s_funcs[_info]._isVariantArgumentList)
        {
            if (_argumentCount < s_funcs[_info]._argumentCount)
            {
                if (s_funcs[_info]._id == FunctionId.In)
                {
                    throw ExprException.InWithoutList();
                }
                throw ExprException.FunctionArgumentCount(_name);
            }
        }
        else if (_argumentCount != s_funcs[_info]._argumentCount)
        {
            throw ExprException.FunctionArgumentCount(_name);
        }
    }
References System.Data.FunctionNode._argumentCount, System.Data.FunctionNode._info, System.Data.FunctionNode._name, System.Data.ExprException.FunctionArgumentCount(), System.Data.ExprException.InWithoutList(), System.Data.FunctionNode.s_funcs, and System.Data.ExprException.UndefinedFunction().
Referenced by System.Data.FunctionNode.Bind(), and System.Data.ExpressionParser.Parse().