Terraria: System.Xml.XmlDictionaryReader.IsStartElement
IsStartElement() [4/4]
virtual bool System.Xml.XmlDictionaryReader.IsStartElement (XmlDictionaryString localName, XmlDictionaryString namespaceUri) inline virtual inherited
Reimplemented in System.Xml.XmlBaseReader.
Definition at line 650 of file XmlDictionaryReader.cs.
    {
        return IsStartElement(XmlDictionaryString.GetString(localName), XmlDictionaryString.GetString(namespaceUri));
    }
References System.Xml.XmlDictionaryString.GetString(), and System.Xml.XmlReader.IsStartElement().
Referenced by System.Runtime.Serialization.XmlReaderDelegator.IsStartElement(), and System.Runtime.Serialization.Json.ByteArrayHelperWithString.ReadArray().