Terraria: System.Xml.XmlDictionaryReader.ReadContentAsBase64
ReadContentAsBase64() [3/3]
byte[] System.Xml.XmlDictionaryReader.ReadContentAsBase64 (int maxByteArrayContentLength, int maxInitialCount) inline package inherited
Definition at line 734 of file XmlDictionaryReader.cs.
    {
        if (TryGetBase64ContentLength(out var length) && length <= maxInitialCount)
        {
            byte[] array = new byte[length];
            int num;
            for (int i = 0; i < length; i += num)
            {
                num = ReadContentAsBase64(array, i, length - i);
                if (num == 0)
                {
                    XmlExceptionHelper.ThrowBase64DataExpected(this);
                }
            }
            return array;
        }
        return ReadContentAsBytes(base64: true, maxByteArrayContentLength);
    }
References System.array, System.Xml.Dictionary, System.length, System.Xml.XmlDictionaryReader.ReadContentAsBase64(), System.Xml.XmlDictionaryReader.ReadContentAsBytes(), System.Xml.XmlExceptionHelper.ThrowBase64DataExpected(), and System.Xml.XmlDictionaryReader.TryGetBase64ContentLength().