Terraria: System.Xml.XmlDictionaryReader.ReadString
ReadString() [2/2]
string System.Xml.XmlDictionaryReader.ReadString (int maxStringContentLength) inline protected inherited
Definition at line 836 of file XmlDictionaryReader.cs.
    {
        if (ReadState != ReadState.Interactive)
        {
            return string.Empty;
        }
        if (NodeType != XmlNodeType.Element)
        {
            MoveToElement();
        }
        if (NodeType == XmlNodeType.Element)
        {
            if (IsEmptyElement)
            {
                return string.Empty;
            }
            if (!Read())
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlInvalidOperation));
            }
            if (NodeType == XmlNodeType.EndElement)
            {
                return string.Empty;
            }
        }
        StringBuilder stringBuilder = null;
        string text = string.Empty;
        while (IsTextNode(NodeType))
        {
            string value = Value;
            if (text.Length == 0)
            {
                text = value;
            }
            else
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(text);
                }
                if (stringBuilder.Length > maxStringContentLength - value.Length)
                {
                    XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(this, maxStringContentLength);
                }
                stringBuilder.Append(value);
            }
            if (!Read())
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(new InvalidOperationException(System.SR.XmlInvalidOperation));
            }
        }
        if (stringBuilder != null)
        {
            text = stringBuilder.ToString();
        }
        if (text.Length > maxStringContentLength)
        {
            XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(this, maxStringContentLength);
        }
        return text;
    }
References System.Xml.Dictionary, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlDictionaryReader.IsTextNode(), System.Xml.XmlReader.MoveToElement(), System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.text, System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError(), System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(), System.value, System.Xml.XmlReader.Value, and System.SR.XmlInvalidOperation.