Terraria: System.Xml.XmlDictionaryReader.ReadContentAsDecimal
ReadContentAsDecimal()
override decimal System.Xml.XmlDictionaryReader.ReadContentAsDecimal () inline virtual
Reimplemented from System.Xml.XmlReader.
Reimplemented in System.Xml.XmlDictionaryReader.XmlWrappedReader.
Definition at line 1055 of file XmlDictionaryReader.cs.
    {
        return XmlConverter.ToDecimal(ReadContentAsString());
    }
References System.Xml.XmlDictionaryReader.ReadContentAsString(), and System.Xml.XmlConverter.ToDecimal().
Referenced by System.Xml.XmlDictionaryReader.ReadElementContentAsDecimal(), and System.Xml.XmlBinaryWriter.WriteTextNode().