Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex
ReadElementContentAsBinHex() [1/2]
virtual byte[] System.Xml.XmlDictionaryReader.ReadElementContentAsBinHex () inline virtual inherited
Definition at line 1331 of file XmlDictionaryReader.cs.
    {
        byte[] result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            result = Array.Empty<byte>();
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsBinHex();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.Xml.XmlReader.Read(), System.Xml.XmlDictionaryReader.ReadContentAsBinHex(), System.Xml.XmlReader.ReadEndElement(), and System.Xml.XmlReader.ReadStartElement().