Terraria: System.Xml.XmlDictionaryReader.ReadContentAsQualifiedName
ReadContentAsQualifiedName()
virtual void System.Xml.XmlDictionaryReader.ReadContentAsQualifiedName (out string localName, out string namespaceUri) inline virtual inherited
Definition at line 1080 of file XmlDictionaryReader.cs.
    {
        XmlConverter.ToQualifiedName(ReadContentAsString(), out string prefix, out localName);
        namespaceUri = LookupNamespace(prefix);
        if (namespaceUri == null)
        {
            XmlExceptionHelper.ThrowUndefinedPrefix(this, prefix);
        }
    }
References System.Xml.Dictionary, System.Xml.XmlReader.LookupNamespace(), System.prefix, System.Xml.XmlDictionaryReader.ReadContentAsString(), System.Xml.XmlExceptionHelper.ThrowUndefinedPrefix(), and System.Xml.XmlConverter.ToQualifiedName().