Terraria: System.Xml.XmlDictionaryReader.ReadContentAsString
ReadContentAsString() [2/4]
string System.Xml.XmlDictionaryReader.ReadContentAsString (int maxStringContentLength) inline protected inherited
Definition at line 758 of file XmlDictionaryReader.cs.
    {
        StringBuilder stringBuilder = null;
        string text = string.Empty;
        bool flag = false;
        while (true)
        {
            switch (NodeType)
            {
            case XmlNodeType.Attribute:
                text = Value;
                break;
            case XmlNodeType.Text:
            case XmlNodeType.CDATA:
            case XmlNodeType.Whitespace:
            case XmlNodeType.SignificantWhitespace:
            {
                string value = Value;
                if (text.Length == 0)
                {
                    text = value;
                    break;
                }
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(text);
                }
                if (stringBuilder.Length > maxStringContentLength - value.Length)
                {
                    XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(this, maxStringContentLength);
                }
                stringBuilder.Append(value);
                break;
            }
            case XmlNodeType.EntityReference:
                if (CanResolveEntity)
                {
                    ResolveEntity();
                    break;
                }
                goto default;
            default:
                flag = true;
                break;
            case XmlNodeType.ProcessingInstruction:
            case XmlNodeType.Comment:
            case XmlNodeType.EndEntity:
                break;
            }
            if (flag)
            {
                break;
            }
            if (AttributeCount != 0)
            {
                ReadAttributeValue();
            }
            else
            {
                Read();
            }
        }
        if (stringBuilder != null)
        {
            text = stringBuilder.ToString();
        }
        if (text.Length > maxStringContentLength)
        {
            XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(this, maxStringContentLength);
        }
        return text;
    }
References System.Xml.XmlReader.AttributeCount, System.Xml.XmlReader.CanResolveEntity, System.Xml.Dictionary, System.Xml.XmlReader.NodeType, System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadAttributeValue(), System.Xml.XmlReader.ResolveEntity(), System.text, System.Xml.XmlExceptionHelper.ThrowMaxStringContentLengthExceeded(), System.value, and System.Xml.XmlReader.Value.