Terraria: System.Xml.XmlDictionaryReader.MoveToStartElement
MoveToStartElement() [1/4]
virtual void System.Xml.XmlDictionaryReader.MoveToStartElement () inline virtual inherited
Definition at line 540 of file XmlDictionaryReader.cs.
    {
        if (!IsStartElement())
        {
            XmlExceptionHelper.ThrowStartElementExpected(this);
        }
    }
References System.Xml.XmlReader.IsStartElement(), and System.Xml.XmlExceptionHelper.ThrowStartElementExpected().
Referenced by System.Xml.XmlBinaryReader.ReadElementContentAsBoolean(), System.Xml.XmlBinaryReader.ReadElementContentAsDateTime(), System.Xml.XmlBinaryReader.ReadElementContentAsDecimal(), System.Xml.XmlBinaryReader.ReadElementContentAsDouble(), System.Xml.XmlBinaryReader.ReadElementContentAsFloat(), System.Xml.XmlBinaryReader.ReadElementContentAsGuid(), System.Xml.XmlBinaryReader.ReadElementContentAsInt(), System.Xml.XmlBaseReader.ReadElementContentAsString(), System.Xml.XmlBinaryReader.ReadElementContentAsString(), System.Xml.XmlBinaryReader.ReadElementContentAsTimeSpan(), System.Xml.XmlBinaryReader.ReadElementContentAsUniqueId(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlDictionaryReader.ReadFullStartElement(), System.Xml.XmlBaseReader.ReadStartElement(), System.Xml.XmlBaseReader.ReadStartElement(), System.Xml.XmlBaseReader.ReadStartElement(), and System.Xml.XmlDictionaryReader.ReadStartElement().