Terraria: System.Data.FunctionNode.Bind
Bind()
override void System.Data.FunctionNode.Bind (DataTable table, List< DataColumn > list) inline package
Definition at line 93 of file FunctionNode.cs.
    {
        BindTable(table);
        Check();
        if (s_funcs[_info]._id == FunctionId.Convert)
        {
            if (_argumentCount != 2)
            {
                throw ExprException.FunctionArgumentCount(_name);
            }
            _arguments[0].Bind(table, list);
            if (_arguments[1].GetType() == typeof(NameNode))
            {
                NameNode nameNode = (NameNode)_arguments[1];
                _arguments[1] = new ConstNode(table, ValueType.Str, nameNode._name);
            }
            _arguments[1].Bind(table, list);
        }
        else
        {
            for (int i = 0; i < _argumentCount; i++)
            {
                _arguments[i].Bind(table, list);
            }
        }
    }
References System.Data.FunctionNode._argumentCount, System.Data.FunctionNode._arguments, System.Data.FunctionNode._info, System.Data.FunctionNode._name, System.Data.ExpressionNode.Bind(), System.Data.ExpressionNode.BindTable(), System.Data.FunctionNode.Check(), System.Runtime.Serialization.Dictionary, System.Data.ExprException.FunctionArgumentCount(), System.list, System.Data.FunctionNode.s_funcs, and System.Data.ExpressionNode.table.