Terraria: System.Xml.XmlDictionaryReader.ReadContentAsBytes
ReadContentAsBytes()
byte[] System.Xml.XmlDictionaryReader.ReadContentAsBytes (bool base64, int maxByteArrayContentLength) inline private inherited
Definition at line 908 of file XmlDictionaryReader.cs.
    {
        byte[][] array = new byte[32][];
        int num = 384;
        int num2 = 0;
        int num3 = 0;
        byte[] array2;
        while (true)
        {
            array2 = new byte[num];
            array[num2++] = array2;
            int i;
            int num4;
            for (i = 0; i < array2.Length; i += num4)
            {
                num4 = ((!base64) ? ReadContentAsBinHex(array2, i, array2.Length - i) : ReadContentAsBase64(array2, i, array2.Length - i));
                if (num4 == 0)
                {
                    break;
                }
            }
            num3 += i;
            if (i < array2.Length)
            {
                break;
            }
            num *= 2;
        }
        array2 = new byte[num3];
        int num5 = 0;
        for (int j = 0; j < num2 - 1; j++)
        {
            Buffer.BlockCopy(array[j], 0, array2, num5, array[j].Length);
            num5 += array[j].Length;
        }
        Buffer.BlockCopy(array[num2 - 1], 0, array2, num5, num3 - num5);
        return array2;
    }
References System.array, System.Buffer.BlockCopy(), System.Xml.Dictionary, System.Xml.XmlDictionaryReader.ReadContentAsBase64(), and System.Xml.XmlDictionaryReader.ReadContentAsBinHex().
Referenced by System.Xml.XmlDictionaryReader.ReadContentAsBase64(), and System.Xml.XmlDictionaryReader.ReadContentAsBinHex().