Terraria: System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime
ReadElementContentAsDateTime() [1/2]
override DateTime System.Xml.XmlDictionaryReader.ReadElementContentAsDateTime () inline virtual inherited
Reimplemented from System.Xml.XmlReader.
Definition at line 1209 of file XmlDictionaryReader.cs.
    {
        DateTime result;
        if (IsStartElement() && IsEmptyElement)
        {
            Read();
            try
            {
                result = DateTime.Parse(string.Empty, NumberFormatInfo.InvariantInfo);
            }
            catch (ArgumentException exception)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(string.Empty, "DateTime", exception));
            }
            catch (FormatException exception2)
            {
                throw DiagnosticUtility.ExceptionUtility.ThrowHelperError(XmlExceptionHelper.CreateConversionException(string.Empty, "DateTime", exception2));
            }
        }
        else
        {
            ReadStartElement();
            result = ReadContentAsDateTime();
            ReadEndElement();
        }
        return result;
    }
References System.Xml.XmlExceptionHelper.CreateConversionException(), System.Xml.Dictionary, System.exception, System.Globalization.NumberFormatInfo.InvariantInfo, System.Xml.XmlReader.IsEmptyElement, System.Xml.XmlReader.IsStartElement(), System.DateTime.Parse(), System.Xml.XmlReader.Read(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XmlReader.ReadEndElement(), System.Xml.XmlReader.ReadStartElement(), and System.Runtime.Serialization.DiagnosticUtility.ExceptionUtility.ThrowHelperError().
Referenced by System.Xml.XmlDictionaryReader.ReadArray().