Terraria: System.Data.FunctionNode.EvalFunction
EvalFunction()
object System.Data.FunctionNode.EvalFunction (FunctionId id, object[] argumentValues, DataRow row, DataRowVersion version) inline private
Definition at line 287 of file FunctionNode.cs.
    {
        switch (id)
        {
        case FunctionId.Abs:
        {
            StorageType storageType2 = DataStorage.GetStorageType(argumentValues[0].GetType());
            if (ExpressionNode.IsInteger(storageType2))
            {
                return Math.Abs((long)argumentValues[0]);
            }
            if (ExpressionNode.IsNumeric(storageType2))
            {
                return Math.Abs((double)argumentValues[0]);
            }
            throw ExprException.ArgumentTypeInteger(s_funcs[_info]._name, 1);
        }
        case FunctionId.cBool:
            return DataStorage.GetStorageType(argumentValues[0].GetType()) switch
            {
                StorageType.Boolean => (bool)argumentValues[0],
                StorageType.Int32 => (int)argumentValues[0] != 0,
                StorageType.Double => (double)argumentValues[0] != 0.0,
                StorageType.String => bool.Parse((string)argumentValues[0]),
                _ => throw ExprException.DatatypeConvertion(argumentValues[0].GetType(), typeof(bool)),
            };
        case FunctionId.cInt:
            return Convert.ToInt32(argumentValues[0], base.FormatProvider);
        case FunctionId.cDate:
            return Convert.ToDateTime(argumentValues[0], base.FormatProvider);
        case FunctionId.cDbl:
            return Convert.ToDouble(argumentValues[0], base.FormatProvider);
        case FunctionId.cStr:
            return Convert.ToString(argumentValues[0], base.FormatProvider);
        case FunctionId.Charindex:
            if (DataStorage.IsObjectNull(argumentValues[0]) || DataStorage.IsObjectNull(argumentValues[1]))
            {
                return DBNull.Value;
            }
            if (argumentValues[0] is SqlString)
            {
                argumentValues[0] = ((SqlString)argumentValues[0]).Value;
            }
            if (argumentValues[1] is SqlString)
            {
                argumentValues[1] = ((SqlString)argumentValues[1]).Value;
            }
            return ((string)argumentValues[1]).IndexOf((string)argumentValues[0], StringComparison.Ordinal);
        case FunctionId.Iif:
        {
            object value = _arguments[0].Eval(row, version);
            if (DataExpression.ToBoolean(value))
            {
                return _arguments[1].Eval(row, version);
            }
            return _arguments[2].Eval(row, version);
        }
        case FunctionId.In:
            throw ExprException.NYI(s_funcs[_info]._name);
        case FunctionId.IsNull:
            if (DataStorage.IsObjectNull(argumentValues[0]))
            {
                return argumentValues[1];
            }
            return argumentValues[0];
        case FunctionId.Len:
            if (argumentValues[0] is SqlString)
            {
                if (((SqlString)argumentValues[0]).IsNull)
                {
                    return DBNull.Value;
                }
                argumentValues[0] = ((SqlString)argumentValues[0]).Value;
            }
            return ((string)argumentValues[0]).Length;
        case FunctionId.Substring:
        {
            int num = (int)argumentValues[1] - 1;
            int num2 = (int)argumentValues[2];
            if (num < 0)
            {
                throw ExprException.FunctionArgumentOutOfRange("index", "Substring");
            }
            if (num2 < 0)
            {
                throw ExprException.FunctionArgumentOutOfRange("length", "Substring");
            }
            if (num2 == 0)
            {
                return string.Empty;
            }
            if (argumentValues[0] is SqlString)
            {
                argumentValues[0] = ((SqlString)argumentValues[0]).Value;
            }
            int length = ((string)argumentValues[0]).Length;
            if (num > length)
            {
                return DBNull.Value;
            }
            if (num + num2 > length)
            {
                num2 = length - num;
            }
            return ((string)argumentValues[0]).Substring(num, num2);
        }
        case FunctionId.Trim:
            if (DataStorage.IsObjectNull(argumentValues[0]))
            {
                return DBNull.Value;
            }
            if (argumentValues[0] is SqlString)
            {
                argumentValues[0] = ((SqlString)argumentValues[0]).Value;
            }
            return ((string)argumentValues[0]).Trim();
        case FunctionId.Convert:
        {
            if (_argumentCount != 2)
            {
                throw ExprException.FunctionArgumentCount(_name);
            }
            if (argumentValues[0] == DBNull.Value)
            {
                return DBNull.Value;
            }
            Type type = (Type)argumentValues[1];
            StorageType storageType = DataStorage.GetStorageType(type);
            StorageType storageType2 = DataStorage.GetStorageType(argumentValues[0].GetType());
            if (storageType == StorageType.DateTimeOffset && storageType2 == StorageType.String)
            {
                return SqlConvert.ConvertStringToDateTimeOffset((string)argumentValues[0], base.FormatProvider);
            }
            if (StorageType.Object != storageType)
            {
                if (storageType == StorageType.Guid && storageType2 == StorageType.String)
                {
                    return new Guid((string)argumentValues[0]);
                }
                if (ExpressionNode.IsFloatSql(storageType2) && ExpressionNode.IsIntegerSql(storageType))
                {
                    if (StorageType.Single == storageType2)
                    {
                        return SqlConvert.ChangeType2((float)SqlConvert.ChangeType2(argumentValues[0], StorageType.Single, typeof(float), base.FormatProvider), storageType, type, base.FormatProvider);
                    }
                    if (StorageType.Double == storageType2)
                    {
                        return SqlConvert.ChangeType2((double)SqlConvert.ChangeType2(argumentValues[0], StorageType.Double, typeof(double), base.FormatProvider), storageType, type, base.FormatProvider);
                    }
                    if (StorageType.Decimal == storageType2)
                    {
                        return SqlConvert.ChangeType2((decimal)SqlConvert.ChangeType2(argumentValues[0], StorageType.Decimal, typeof(decimal), base.FormatProvider), storageType, type, base.FormatProvider);
                    }
                }
                DeserializationToken deserializationToken = ((_capturedLimiter != null) ? SerializationInfo.StartDeserialization() : default(DeserializationToken));
                using (deserializationToken)
                {
                    return SqlConvert.ChangeType2(argumentValues[0], storageType, type, base.FormatProvider);
                }
            }
            return argumentValues[0];
        }
        case FunctionId.DateTimeOffset:
            if (argumentValues[0] == DBNull.Value || argumentValues[1] == DBNull.Value || argumentValues[2] == DBNull.Value)
            {
                return DBNull.Value;
            }
            switch (((DateTime)argumentValues[0]).Kind)
            {
            case DateTimeKind.Utc:
                if ((int)argumentValues[1] != 0 && (int)argumentValues[2] != 0)
                {
                    throw ExprException.MismatchKindandTimeSpan();
                }
                break;
            case DateTimeKind.Local:
                if (DateTimeOffset.Now.Offset.Hours != (int)argumentValues[1] && DateTimeOffset.Now.Offset.Minutes != (int)argumentValues[2])
                {
                    throw ExprException.MismatchKindandTimeSpan();
                }
                break;
            }
            if ((int)argumentValues[1] < -14 || (int)argumentValues[1] > 14)
            {
                throw ExprException.InvalidHoursArgument();
            }
            if ((int)argumentValues[2] < -59 || (int)argumentValues[2] > 59)
            {
                throw ExprException.InvalidMinutesArgument();
            }
            if ((int)argumentValues[1] == 14 && (int)argumentValues[2] > 0)
            {
                throw ExprException.InvalidTimeZoneRange();
            }
            if ((int)argumentValues[1] == -14 && (int)argumentValues[2] < 0)
            {
                throw ExprException.InvalidTimeZoneRange();
            }
            return new DateTimeOffset((DateTime)argumentValues[0], new TimeSpan((int)argumentValues[1], (int)argumentValues[2], 0));
        default:
            throw ExprException.UndefinedFunction(s_funcs[_info]._name);
        }
    }
References System.Data.FunctionNode._argumentCount, System.Data.FunctionNode._arguments, System.Data.FunctionNode._capturedLimiter, System.Data.FunctionNode._info, System.Data.FunctionNode._name, System.Math.Abs(), System.Data.ExprException.ArgumentTypeInteger(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ConvertStringToDateTimeOffset(), System.Data.ExprException.DatatypeConvertion(), System.Data.DateTimeOffset, System.Runtime.Serialization.Dictionary, System.Data.ExpressionNode.Eval(), System.Data.ExprException.FunctionArgumentCount(), System.Data.ExprException.FunctionArgumentOutOfRange(), System.Data.Common.DataStorage.GetStorageType(), System.Data.Guid, System.Data.ExprException.InvalidHoursArgument(), System.Data.ExprException.InvalidMinutesArgument(), System.Data.ExprException.InvalidTimeZoneRange(), System.Data.ExpressionNode.IsFloatSql(), System.Data.ExpressionNode.IsInteger(), System.Data.ExpressionNode.IsIntegerSql(), System.Data.IsNull, System.Data.ExpressionNode.IsNumeric(), System.Data.Common.DataStorage.IsObjectNull(), System.length, System.Data.ExprException.MismatchKindandTimeSpan(), System.DateTimeOffset.Now, System.Data.ExprException.NYI(), System.Data.FunctionNode.s_funcs, System.Data.Common.SqlString, System.Runtime.Serialization.SerializationInfo.StartDeserialization(), System.Data.Substring, System.Data.Common.TimeSpan, System.Data.DataExpression.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDouble(), System.Convert.ToInt32(), System.Convert.ToString(), System.Data.Trim, System.Data.Common.Type, System.type, System.Data.ExprException.UndefinedFunction(), System.DBNull.Value, and System.value.
Referenced by System.Data.FunctionNode.Eval().