Terraria: GolfHelper.ContactListener.PutBallInCup
PutBallInCup()
void GolfHelper.ContactListener.PutBallInCup (Projectile proj, BallCollisionEvent collision) inline
         {
             if (proj.owner == Main.myPlayer && Main.LocalGolfState.ShouldScoreHole)
             {
                 Point hitLocation = (collision.ImpactPoint - collision.Normal * 0.5f).ToTileCoordinates();
                 int owner = proj.owner;
                 int num = (int)proj.ai[1];
                 int type = proj.type;
                 if (num > 1)
                 {
                     Main.LocalGolfState.SetScoreTime();
                 }
                 Main.LocalGolfState.RecordBallInfo(proj);
                 Main.LocalGolfState.LandBall(proj);
                 int golfBallScore = Main.LocalGolfState.GetGolfBallScore(proj);
                 if (num > 0)
                 {
                     Main.player[owner].AccumulateGolfingScore(golfBallScore);
                 }
                 PutBallInCup_TextAndEffects(hitLocation, owner, num, type);
                 Main.LocalGolfState.ResetScoreTime();
                 Wiring.HitSwitch(hitLocation.X, hitLocation.Y);
                 NetMessage.SendData(59, -1, -1, null, hitLocation.X, hitLocation.Y);
                 if (Main.netMode == 1)
                 {
                     NetMessage.SendData(128, -1, -1, null, owner, num, type, 0f, hitLocation.X, hitLocation.Y);
                 }
             }
             proj.Kill();
         }
References Player.AccumulateGolfingScore(), Projectile.ai, GolfState.GetGolfBallScore(), Wiring.HitSwitch(), BallCollisionEvent.ImpactPoint, Projectile.Kill(), GolfState.LandBall(), Main.LocalGolfState, Main.myPlayer, Main.netMode, BallCollisionEvent.Normal, Projectile.owner, Main.player, GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), GolfState.RecordBallInfo(), GolfState.ResetScoreTime(), NetMessage.SendData(), GolfState.SetScoreTime(), GolfState.ShouldScoreHole, and Projectile.type.
Referenced by GolfHelper.ContactListener.OnCollision().