Terraria: Internal.Runtime.InteropServices.LicenseInteropProxy.LicenseInteropProxy
LicenseInteropProxy()
Internal.Runtime.InteropServices.LicenseInteropProxy.LicenseInteropProxy () inline
Definition at line 36 of file LicenseInteropProxy.cs.
    {
        Type type = Type.GetType("System.ComponentModel.LicenseManager, System.ComponentModel.TypeConverter", throwOnError: true);
        Type type2 = Type.GetType("System.ComponentModel.LicenseContext, System.ComponentModel.TypeConverter", throwOnError: true);
        _setSavedLicenseKey = type2.GetMethod("SetSavedLicenseKey", BindingFlags.Instance | BindingFlags.Public);
        _createWithContext = type.GetMethod("CreateWithContext", new Type[2]
        {
            typeof(Type),
            type2
        });
        Type nestedType = type.GetNestedType("LicenseInteropHelper", BindingFlags.NonPublic);
        _validateTypeAndReturnDetails = nestedType.GetMethod("ValidateAndRetrieveLicenseDetails", BindingFlags.Static | BindingFlags.Public);
        _getCurrentContextInfo = nestedType.GetMethod("GetCurrentContextInfo", BindingFlags.Static | BindingFlags.Public);
        Type nestedType2 = type.GetNestedType("CLRLicenseContext", BindingFlags.NonPublic);
        _createDesignContext = nestedType2.GetMethod("CreateDesignContext", BindingFlags.Static | BindingFlags.Public);
        _createRuntimeContext = nestedType2.GetMethod("CreateRuntimeContext", BindingFlags.Static | BindingFlags.Public);
        _licInfoHelper = type.GetNestedType("LicInfoHelperLicenseContext", BindingFlags.NonPublic);
        _licInfoHelperContains = _licInfoHelper.GetMethod("Contains", BindingFlags.Instance | BindingFlags.Public);
    }
References Internal.Runtime.InteropServices.LicenseInteropProxy._createDesignContext, Internal.Runtime.InteropServices.LicenseInteropProxy._createRuntimeContext, Internal.Runtime.InteropServices.LicenseInteropProxy._createWithContext, Internal.Runtime.InteropServices.LicenseInteropProxy._getCurrentContextInfo, Internal.Runtime.InteropServices.LicenseInteropProxy._licInfoHelper, Internal.Runtime.InteropServices.LicenseInteropProxy._licInfoHelperContains, Internal.Runtime.InteropServices.LicenseInteropProxy._setSavedLicenseKey, Internal.Runtime.InteropServices.LicenseInteropProxy._validateTypeAndReturnDetails, System.Type.GetMethod(), System.Type.GetNestedType(), System.Type.GetType(), and System.type.
Referenced by Internal.Runtime.InteropServices.LicenseInteropProxy.Create().