Terraria: Internal.Runtime.InteropServices.LicenseInteropProxy.GetLicInfo
GetLicInfo()
void Internal.Runtime.InteropServices.LicenseInteropProxy.GetLicInfo (Type type, out bool runtimeKeyAvail, out bool licVerified) inline
Definition at line 70 of file LicenseInteropProxy.cs.
    {
        runtimeKeyAvail = false;
        licVerified = false;
        object obj = Activator.CreateInstance(_licInfoHelper);
        object[] array = new object[4] { obj, type, null, null };
        if ((bool)_validateTypeAndReturnDetails.Invoke(null, BindingFlags.DoNotWrapExceptions, null, array, null))
        {
            IDisposable disposable = (IDisposable)array[2];
            if (disposable != null)
            {
                disposable.Dispose();
                licVerified = true;
            }
            array = new object[1] { type.AssemblyQualifiedName };
            runtimeKeyAvail = (bool)_licInfoHelperContains.Invoke(obj, BindingFlags.DoNotWrapExceptions, null, array, null);
        }
    }
References Internal.Runtime.InteropServices.LicenseInteropProxy._licInfoHelper, Internal.Runtime.InteropServices.LicenseInteropProxy._licInfoHelperContains, Internal.Runtime.InteropServices.LicenseInteropProxy._validateTypeAndReturnDetails, System.array, System.Activator.CreateInstance(), System.IDisposable.Dispose(), System.Reflection.MethodBase.Invoke(), System.obj, and System.type.
Referenced by Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.GetLicInfo().