Terraria: Internal.Runtime.InteropServices.LicenseInteropProxy.AllocateAndValidateLicense
AllocateAndValidateLicense()
object Internal.Runtime.InteropServices.LicenseInteropProxy.AllocateAndValidateLicense ([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type type, string key, bool isDesignTime) inline
Definition at line 105 of file LicenseInteropProxy.cs.
    {
        object obj;
        if (isDesignTime)
        {
            object[] parameters = new object[1] { type };
            obj = _createDesignContext.Invoke(null, BindingFlags.DoNotWrapExceptions, null, parameters, null);
        }
        else
        {
            object[] parameters = new object[2] { type, key };
            obj = _createRuntimeContext.Invoke(null, BindingFlags.DoNotWrapExceptions, null, parameters, null);
        }
        try
        {
            object[] parameters = new object[2] { type, obj };
            return _createWithContext.Invoke(null, BindingFlags.DoNotWrapExceptions, null, parameters, null);
        }
        catch (Exception ex) when (ex.GetType() == s_licenseExceptionType)
        {
            throw new COMException(ex.Message, -2147221230);
        }
    }
References Internal.Runtime.InteropServices.LicenseInteropProxy._createDesignContext, Internal.Runtime.InteropServices.LicenseInteropProxy._createRuntimeContext, Internal.Runtime.InteropServices.LicenseInteropProxy._createWithContext, System.Exception.GetType(), System.Reflection.MethodBase.Invoke(), System.key, System.Exception.Message, System.obj, Internal.Runtime.InteropServices.LicenseInteropProxy.s_licenseExceptionType, and System.type.
Referenced by Internal.Runtime.InteropServices.ComActivator.LicenseClassFactory.CreateInstanceInner().