Terraria: System.Byte.Parse
Parse() [7/13]
static byte System.Byte.Parse (string s) inline static
Definition at line 75 of file Byte.cs.
    {
        if (s == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
        }
        return Parse((ReadOnlySpan<char>)s, NumberStyles.Integer, NumberFormatInfo.CurrentInfo);
    }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.Byte.Parse(), System.s, and System.ThrowHelper.ThrowArgumentNullException().
Referenced by System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), System.Byte.Parse(), and System.Byte.Parse().