Terraria: AWorldListItem.GetIconElement
GetIconElement()
UIElement AWorldListItem.GetIconElement () inline protected inherited
     {
         if (_data.DrunkWorld && _data.RemixWorld)
         {
             Asset<Texture2D> obj = Main.Assets.Request<Texture2D>("Images/UI/IconEverythingAnimated", (AssetRequestMode)1);
             UIImageFramed uIImageFramed = new UIImageFramed(obj, obj.Frame(7, 16));
             uIImageFramed.Left = new StyleDimension(4f, 0f);
             uIImageFramed.OnUpdate += UpdateGlitchAnimation;
             return uIImageFramed;
         }
         return new UIImage(GetIcon())
         {
             Left = new StyleDimension(4f, 0f)
         };
     }
References AWorldListItem._data, Main.Assets, WorldFileData.DrunkWorld, AWorldListItem.GetIcon(), UIElement.Left, UIElement.OnUpdate, WorldFileData.RemixWorld, and AWorldListItem.UpdateGlitchAnimation().
Referenced by UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), and UIWorldListItem().