Terraria: System.Data.ExpressionParser.ScanReserved
ScanReserved()
void System.Data.ExpressionParser.ScanReserved () inline private
Definition at line 770 of file ExpressionParser.cs.
    {
        char[] text = _text;
        if (!IsAlpha(text[_pos]))
        {
            return;
        }
        ScanName();
        string @string = new string(text, _start, _pos - _start);
        CompareInfo compareInfo = CultureInfo.InvariantCulture.CompareInfo;
        int num = 0;
        int num2 = s_reservedwords.Length - 1;
        do
        {
            int num3 = (num + num2) / 2;
            int num4 = compareInfo.Compare(s_reservedwords[num3]._word, @string, CompareOptions.IgnoreCase);
            if (num4 == 0)
            {
                _token = s_reservedwords[num3]._token;
                _op = s_reservedwords[num3]._op;
                break;
            }
            if (num4 < 0)
            {
                num = num3 + 1;
            }
            else
            {
                num2 = num3 - 1;
            }
        }
        while (num <= num2);
    }
References System.Data.ExpressionParser._op, System.Data.ExpressionParser._pos, System.Data.ExpressionParser._start, System.Data.ExpressionParser._text, System.Data.ExpressionParser._token, System.Globalization.CompareInfo.Compare(), System.Globalization.CultureInfo.InvariantCulture, System.Data.ExpressionParser.IsAlpha(), System.Data.ExpressionParser.s_reservedwords, System.Data.ExpressionParser.ScanName(), and System.text.
Referenced by System.Data.ExpressionParser.Scan().