Terraria: System.Data.ExpressionParser.BuildExpression
BuildExpression()
void System.Data.ExpressionParser.BuildExpression (int pri) inline private
Definition at line 446 of file ExpressionParser.cs.
    {
        ExpressionNode expressionNode = null;
        while (true)
        {
            OperatorInfo operatorInfo = _ops[_topOperator - 1];
            if (operatorInfo._priority < pri)
            {
                break;
            }
            _topOperator--;
            switch (operatorInfo._type)
            {
            default:
                return;
            case Nodes.Binop:
            {
                ExpressionNode right = NodePop();
                ExpressionNode expressionNode2 = NodePop();
                switch (operatorInfo._op)
                {
                case 4:
                case 6:
                case 22:
                case 23:
                case 24:
                case 25:
                    throw ExprException.UnsupportedOperator(operatorInfo._op);
                default:
                    expressionNode = ((operatorInfo._op != 14) ? new BinaryNode(_table, operatorInfo._op, expressionNode2, right) : new LikeNode(_table, operatorInfo._op, expressionNode2, right));
                    break;
                }
                break;
            }
            case Nodes.Unop:
            {
                ExpressionNode expressionNode2 = null;
                ExpressionNode right = NodePop();
                int op = operatorInfo._op;
                if (op != 1 && op != 3 && op == 25)
                {
                    throw ExprException.UnsupportedOperator(operatorInfo._op);
                }
                expressionNode = new UnaryNode(_table, operatorInfo._op, right);
                break;
            }
            case Nodes.Zop:
                expressionNode = new ZeroOpNode(operatorInfo._op);
                break;
            case Nodes.UnopSpec:
            case Nodes.BinopSpec:
                return;
            }
            NodePush(expressionNode);
        }
    }
References System.Data.OperatorInfo._op, System.Data.ExpressionParser._ops, System.Data.OperatorInfo._priority, System.Data.ExpressionParser._table, System.Data.ExpressionParser._topOperator, System.Data.OperatorInfo._type, System.Data.ExpressionParser.NodePop(), System.Data.ExpressionParser.NodePush(), and System.Data.ExprException.UnsupportedOperator().
Referenced by System.Data.ExpressionParser.Parse().