Terraria: System.Data.ExpressionParser.ParseAggregateArgument
ParseAggregateArgument()
ExpressionNode System.Data.ExpressionParser.ParseAggregateArgument (FunctionId aggregate) inline private
Definition at line 379 of file ExpressionParser.cs.
    {
        Scan();
        bool flag;
        string relationName;
        string columnName;
        try
        {
            if (_token != Tokens.Child)
            {
                if (_token != Tokens.Name)
                {
                    throw ExprException.AggregateArgument();
                }
                columnName = NameNode.ParseName(_text, _start, _pos);
                ScanToken(Tokens.RightParen);
                return new AggregateNode(_table, aggregate, columnName);
            }
            flag = _token == Tokens.Child;
            _prevOperand = 1;
            Scan();
            if (_token == Tokens.LeftParen)
            {
                ScanToken(Tokens.Name);
                relationName = NameNode.ParseName(_text, _start, _pos);
                ScanToken(Tokens.RightParen);
                ScanToken(Tokens.Dot);
            }
            else
            {
                relationName = null;
                CheckToken(Tokens.Dot);
            }
            ScanToken(Tokens.Name);
            columnName = NameNode.ParseName(_text, _start, _pos);
            ScanToken(Tokens.RightParen);
        }
        catch (Exception e) when (ADP.IsCatchableExceptionType(e))
        {
            throw ExprException.AggregateArgument();
        }
        return new AggregateNode(_table, aggregate, columnName, !flag, relationName);
    }
References System.Data.ExpressionParser._pos, System.Data.ExpressionParser._prevOperand, System.Data.ExpressionParser._start, System.Data.ExpressionParser._table, System.Data.ExpressionParser._text, System.Data.ExpressionParser._token, System.Data.ExprException.AggregateArgument(), System.Data.ExpressionParser.CheckToken(), System.Data.Common.ADP.IsCatchableExceptionType(), System.Data.NameNode.ParseName(), System.Data.ExpressionParser.Scan(), and System.Data.ExpressionParser.ScanToken().
Referenced by System.Data.ExpressionParser.Parse().