Terraria: System.Data.ExpressionParser.NodePush
NodePush()
void System.Data.ExpressionParser.NodePush (ExpressionNode node) inline private
Definition at line 437 of file ExpressionParser.cs.
    {
        if (_topNode >= 98)
        {
            throw ExprException.ExpressionTooComplex();
        }
        _nodeStack[_topNode++] = node;
    }
References System.Data.ExpressionParser._nodeStack, System.Data.ExpressionParser._topNode, and System.Data.ExprException.ExpressionTooComplex().
Referenced by System.Data.ExpressionParser.BuildExpression(), and System.Data.ExpressionParser.Parse().