Terraria: System.Data.ExpressionParser.Scan
Scan()
Tokens System.Data.ExpressionParser.Scan () inline package
Definition at line 511 of file ExpressionParser.cs.
    {
        char[] text = _text;
        _token = Tokens.None;
        while (true)
        {
            _start = _pos;
            _op = 0;
            char c = text[_pos++];
            switch (c)
            {
            case '\0':
                _token = Tokens.EOS;
                break;
            case '\t':
            case '\n':
            case '\r':
            case ' ':
                goto IL_0111;
            case '(':
                _token = Tokens.LeftParen;
                break;
            case ')':
                _token = Tokens.RightParen;
                break;
            case '#':
                ScanDate();
                CheckToken(Tokens.Date);
                break;
            case '\'':
                ScanString('\'');
                CheckToken(Tokens.StringConst);
                break;
            case '=':
                _token = Tokens.BinaryOp;
                _op = 7;
                break;
            case '>':
                _token = Tokens.BinaryOp;
                ScanWhite();
                if (text[_pos] == '=')
                {
                    _pos++;
                    _op = 10;
                }
                else
                {
                    _op = 8;
                }
                break;
            case '<':
                _token = Tokens.BinaryOp;
                ScanWhite();
                if (text[_pos] == '=')
                {
                    _pos++;
                    _op = 11;
                }
                else if (text[_pos] == '>')
                {
                    _pos++;
                    _op = 12;
                }
                else
                {
                    _op = 9;
                }
                break;
            case '+':
                _token = Tokens.BinaryOp;
                _op = 15;
                break;
            case '-':
                _token = Tokens.BinaryOp;
                _op = 16;
                break;
            case '*':
                _token = Tokens.BinaryOp;
                _op = 17;
                break;
            case '/':
                _token = Tokens.BinaryOp;
                _op = 18;
                break;
            case '%':
                _token = Tokens.BinaryOp;
                _op = 20;
                break;
            case '&':
                _token = Tokens.BinaryOp;
                _op = 22;
                break;
            case '|':
                _token = Tokens.BinaryOp;
                _op = 23;
                break;
            case '^':
                _token = Tokens.BinaryOp;
                _op = 24;
                break;
            case '~':
                _token = Tokens.BinaryOp;
                _op = 25;
                break;
            case '[':
                ScanName(']', _escape, "]\\");
                CheckToken(Tokens.Name);
                break;
            case '`':
                ScanName('`', '`', "`");
                CheckToken(Tokens.Name);
                break;
            default:
                if (c == _listSeparator)
                {
                    _token = Tokens.ListSeparator;
                    break;
                }
                if (c == '.')
                {
                    if (_prevOperand == 0)
                    {
                        ScanNumeric();
                    }
                    else
                    {
                        _token = Tokens.Dot;
                    }
                    break;
                }
                if (c == '0' && (text[_pos] == 'x' || text[_pos] == 'X'))
                {
                    _token = Tokens.BinaryConst;
                    break;
                }
                if (IsDigit(c))
                {
                    ScanNumeric();
                    break;
                }
                ScanReserved();
                if (_token != 0)
                {
                    break;
                }
                if (IsAlphaNumeric(c))
                {
                    ScanName();
                    if (_token != 0)
                    {
                        CheckToken(Tokens.Name);
                        break;
                    }
                }
                _token = Tokens.Unknown;
                throw ExprException.UnknownToken(new string(text, _start, _pos - _start), _start + 1);
            }
            break;
            IL_0111:
            ScanWhite();
        }
        return _token;
    }
References System.Data.ExpressionParser._escape, System.Data.ExpressionParser._listSeparator, System.Data.ExpressionParser._op, System.Data.ExpressionParser._pos, System.Data.ExpressionParser._prevOperand, System.Data.ExpressionParser._start, System.Data.ExpressionParser._text, System.Data.ExpressionParser._token, System.Data.ExpressionParser.CheckToken(), System.Data.ExpressionParser.IsAlphaNumeric(), System.Data.ExpressionParser.IsDigit(), System.Data.ExpressionParser.ScanDate(), System.Data.ExpressionParser.ScanName(), System.Data.ExpressionParser.ScanNumeric(), System.Data.ExpressionParser.ScanReserved(), System.Data.ExpressionParser.ScanString(), System.Data.ExpressionParser.ScanWhite(), System.text, and System.Data.ExprException.UnknownToken().
Referenced by System.Data.ExpressionParser.Parse(), System.Data.ExpressionParser.ParseAggregateArgument(), and System.Data.ExpressionParser.ScanToken().