Terraria: System.Span.CopyTo
CopyTo()
void System.Span< T >.CopyTo (Span< T > destination) inline
Definition at line 224 of file Span.cs.
    {
        if ((uint)_length <= (uint)destination.Length)
        {
            Buffer.Memmove<T>(ref destination._pointer.Value, ref _pointer.Value, (uint)_length);
        }
        else
        {
            ThrowHelper.ThrowArgumentException_DestinationTooShort();
        }
    }
References System.Span< T >._length, System.Span< T >._pointer, System.destination, System.Buffer.Memmove(), and System.ThrowHelper.ThrowArgumentException_DestinationTooShort().
Referenced by System.Net.Security.SafeDeleteContext.AcceptSecurityContext(), System.Net.Security.SafeDeleteContext.AcceptSecurityContext(), System.Text.Json.PooledByteBufferWriter.CheckAndResizeBuffer(), System.Security.Cryptography.FromBase64Transform.ConvertFromBase64(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer(), System.Memory< T >.CopyTo(), System.ReadOnlyMemory< T >.CopyTo(), System.Runtime.InteropServices.Marshal.CopyToManaged< T >(), System.Runtime.InteropServices.Marshal.CopyToNative< T >(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), System.Numerics.BigIntegerCalculator.Divide(), System.Net.Security.SslStream.ForceAuthenticationAsync< TIOAdapter >(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), System.Net.MultiArrayBuffer.GrowAvailableSpace(), System.Net.Security.SafeDeleteContext.InitializeSecurityContext(), System.Net.Security.SafeDeleteContext.InitializeSecurityContext(), System.IO.Path.JoinInternal(), System.IO.Path.JoinInternal(), System.Security.SecureString.MarshalToString(), System.IO.Enumeration.FileSystemName.MatchPattern(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext(), System.Globalization.FormatProvider.Number.NumberToStringFormat(), System.Number.NumberToStringFormat(), System.Numerics.BigInteger.operator>>(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), System.Text.Json.Serialization.Converters.TimeSpanConverter.Read(), System.IO.MemoryStream.Read(), System.IO.TextReader.Read(), System.IO.Strategies.Net5CompatFileStreamStrategy.ReadAsyncInternal(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.TextReader.ReadBlock(), System.IO.Strategies.BufferedFileStreamStrategy.ReadFromNonSeekableAsync(), System.IO.StreamReader.ReadSpan(), System.Net.WebSockets.WebSocket.ReceiveAsync(), System.Net.Security.SslStream.RenegotiateAsync< TIOAdapter >(), System.Net.SocketAddressPal.SetIPv6Address(), System.Net.Internals.SocketAddress.ToString(), System.Net.SocketAddress.ToString(), System.Security.Cryptography.FromBase64Transform.TransformBlock(), System.Text.Json.JsonDocument.TryParseValue(), System.Text.Json.JsonReaderHelper.UnescapeAndCompare(), and System.Buffers.BuffersExtensions.Write< T >().