Terraria: System.Span.Clear
Clear()
unsafe void System.Span< T >.Clear () inline
Definition at line 198 of file Span.cs.
    {
        if (RuntimeHelpers.IsReferenceOrContainsReferences<T>())
        {
            SpanHelpers.ClearWithReferences(ref Unsafe.As<T, IntPtr>(ref _pointer.Value), (nuint)(uint)_length * (nuint)(Unsafe.SizeOf<T>() / sizeof(UIntPtr)));
        }
        else
        {
            SpanHelpers.ClearWithoutReferences(ref Unsafe.As<T, byte>(ref _pointer.Value), (nuint)(uint)_length * (nuint)Unsafe.SizeOf<T>());
        }
    }
References System.Span< T >._length, System.Span< T >._pointer, System.SpanHelpers.ClearWithoutReferences(), and System.SpanHelpers.ClearWithReferences().
Referenced by System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE(), System.Security.SecureString.Clear(), System.Text.Json.Serialization.ReadBufferState.Dispose(), System.Diagnostics.Tracing.EventPipeInternal.Enable(), System.Security.Cryptography.PasswordBasedEncryption.Encrypt(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Net.SSPIWrapper.EncryptDecryptHelper(), System.Text.Json.JsonReaderHelper.GetUnescapedSpan(), System.Net.MultiArrayBuffer.GrowAvailableSpace(), System.Security.SecureString.MarshalToBSTR(), System.Security.SecureString.MarshalToString(), System.Numerics.BigIntegerCalculator.Multiply(), System.Data.SqlTypes.SqlDecimal.operator*(), System.Data.SqlTypes.SqlDecimal.operator/(), System.Numerics.BigInteger.operator<<(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), System.Net.IPAddressParser.Parse(), System.IPv6AddressHelper.ParseCanonicalName(), System.Net.NetworkInformation.UnicastIPAddressInformation.PrefixLengthToSubnetMask(), System.Security.SecureString.UnmanagedBuffer.ReleaseHandle(), System.Security.Cryptography.CngPkcs8.RewriteEncryptedPkcs8PrivateKey(), System.Collections.BitArray.SetAll(), System.Net.RequestContextBase.SetBuffer(), System.Numerics.BigIntegerCalculator.Square(), System.Data.SqlTypes.SqlDecimal.ToString(), System.Text.SegmentStringBuilder.ToString(), and System.Text.Json.JsonReaderHelper.TryDecodeBase64().