Terraria: System.Span.ToArray
ToArray()
T[] System.Span< T >.ToArray () inline
Definition at line 291 of file Span.cs.
    {
        if (_length == 0)
        {
            return Array.Empty<T>();
        }
        T[] array = new T[_length];
        Buffer.Memmove(ref MemoryMarshal.GetArrayDataReference(array), ref _pointer.Value, (uint)_length);
        return array;
    }
References System.Span< T >._length, System.Span< T >._pointer, System.array, System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(), and System.Buffer.Memmove().
Referenced by System.SpanDebugView< T >.SpanDebugView(), System.Net.Security.SafeDeleteContext.AcceptSecurityContext(), System.Net.Security.SafeDeleteContext.AcceptSecurityContext(), System.Numerics.BigIntegerCalculator.Divide(), System.Security.Cryptography.AsymmetricAlgorithm.ExportArray(), System.Security.Cryptography.AsymmetricAlgorithm.ExportArray< T >(), System.Security.Cryptography.CngKeyLite.ExportKeyBlob(), System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytesForSmallInput(), ReLogic.Localization.IME.WinImm32Ime.GetCompositionString(), System.Runtime.Serialization.MemoryStreamAdapter.GetMemoryStream(), System.Net.CertificateValidationPal.GetRequestCertificateAuthorities(), System.Numerics.BigNumber.HexNumberToBigInteger(), System.Net.Security.SafeDeleteContext.InitializeSecurityContext(), System.Net.Security.SafeDeleteContext.InitializeSecurityContext(), System.Numerics.BigInteger.operator>>(), System.Reflection.Emit.DynamicILInfo.SetCode(), System.Reflection.Emit.DynamicILInfo.SetExceptions(), System.Reflection.Emit.DynamicILInfo.SetLocalSignature(), System.Memory< T >.ToArray(), and System.ReadOnlyMemory< T >.ToArray().