Terraria: System.Span.Slice
Slice() [1/2]
Span< T > System.Span< T >.Slice (int start) inline
Definition at line 271 of file Span.cs.
    {
        if ((uint)start > (uint)_length)
        {
            ThrowHelper.ThrowArgumentOutOfRangeException();
        }
        return new Span<T>(ref Unsafe.Add(ref _pointer.Value, (nint)(uint)start), _length - start);
    }
References System.Span< T >._length, System.Span< T >._pointer, System.start, and System.ThrowHelper.ThrowArgumentOutOfRangeException().
Referenced by System.Security.Cryptography.DSAImplementation.DSACng.AdjustHashSizeIfNecessary(), System.Security.Cryptography.DSACng.AdjustHashSizeIfNecessary(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.AppendFormatHelper(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted< T >(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendFormatted< T >(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormattedSlow(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendOrInsertAlignmentIfNeeded(), System.Text.ValueStringBuilder.AppendSlow(), System.Text.ValueStringBuilder.AppendSpan(), System.Text.ValueStringBuilder.AppendSpanFormattable< T >(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendStringDirect(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.AppendStringDirect(), System.Text.ValueStringBuilder.AsSpan(), System.Text.ValueStringBuilder.AsSpan(), System.Text.ValueStringBuilder.AsSpan(), System.Text.ValueStringBuilder.AsSpan(), System.Text.Json.Utf8JsonWriter.Base64EncodeAndWrite(), Interop.CallStringMethod< TArg1, TArg2, TArg3 >(), Interop.crypt32.CertGetNameString(), System.Text.Rune.ChangeCaseCultureAware(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.CircularCopyUtf16BE(), System.Security.Cryptography.FromBase64Transform.ConvertFromBase64(), System.Net.Quic.Implementations.MsQuic.MsQuicStream.CopyMsQuicBuffersToUserBuffer(), Internal.Cryptography.AsymmetricAlgorithmHelpers.CopySignatureField(), System.IO.Compression.OutputWindow.CopyTo(), System.Security.Principal.SecurityIdentifier.CreateFromBinaryForm(), System.Security.Cryptography.DSA.CreateSignatureCore(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Decrypt(), System.Net.WebSockets.Compression.WebSocketDeflater.DeflatePrivate(), System.Security.Cryptography.Pkcs.Pkcs12Kdf.Derive(), Interop.NCrypt.DeriveKeyMaterial(), System.Security.Cryptography.FromBase64Transform.DiscardWhiteSpaces(), System.Numerics.BigIntegerCalculator.Divide(), System.Text.DecoderNLS.DrainLeftoverDataForGetCharCount(), System.Text.DecoderNLS.DrainLeftoverDataForGetChars(), System.Net.Http.HPack.HPackEncoder.EncodeLiteralHeaderFieldWithoutIndexingToAllocatedArray(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8(), System.Text.Encodings.Web.TextEncoder.EncodeUtf8Core(), System.UriHelper.EscapeStringToBuilder(), System.Security.Cryptography.HKDF.Expand(), System.Security.Cryptography.HKDF.Extract(), Internal.Cryptography.Pbkdf2Implementation.FillKeyDerivation(), System.Security.Cryptography.RsaPaddingProcessor.FillNonZeroBytes(), System.IO.StreamWriter.Flush(), System.Text.Encodings.Web.AllowedBmpCodePointsBitmap.ForbidUndefinedCharacters(), System.Numerics.BigNumber.FormatBigIntegerToHex(), System.Security.Cryptography.Rfc2898DeriveBytes.Func(), Interop.Kernel32.GetComputerName(), Interop.Kernel32.GetMessage(), System.Security.Cryptography.RandomNumberGeneratorImplementation.GetNonZeroBytes(), System.Text.ValueStringBuilder.Grow(), System.Net.MultiArrayBuffer.GrowAvailableSpace(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowCore(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowThenCopySpan(), System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.GrowThenCopyString(), System.Security.Cryptography.DSA.HashSpanToTmp(), System.Security.Cryptography.ECDsa.HashSpanToTmp(), System.Globalization.Normalization.IcuNormalize(), System.Text.ValueStringBuilder.Insert(), System.Text.ValueStringBuilder.Insert(), System.Security.SecureString.InsertAt(), System.Security.SecureString.MarshalToBSTR(), System.Security.SecureString.MarshalToString(), System.Security.Cryptography.RsaPaddingProcessor.Mgf1(), System.Net.WebSockets.ManagedWebSocket._003CReceiveAsyncPrivate_003Ed__63< TResult >.MoveNext(), System.Net.WebSockets.ManagedWebSocket._003CEnsureBufferContainsAsync_003Ed__74.MoveNext(), System.Globalization.Normalization.NlsNormalize(), System.Numerics.BigNumber.NumberToBigInteger(), System.Numerics.BigInteger.operator<<(), System.Numerics.BigInteger.operator>>(), System.Security.Cryptography.RsaPaddingProcessor.PadOaep(), System.Security.Cryptography.RsaPaddingProcessor.PadPkcs1Encryption(), System.IPv4AddressHelper.ParseCanonicalName(), System.IPv6AddressHelper.ParseCanonicalName(), System.Security.Cryptography.PasswordBasedEncryption.Pbes1Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pbes2Decrypt(), System.Security.Cryptography.PasswordBasedEncryption.Pbkdf1(), System.Text.Encodings.Web.OptimizedInboxTextEncoder.AsciiPreescapedData.PopulatePreescapedData(), System.IO.StreamReader.ReadBuffer(), System.Security.SecureString.RemoveAt(), System.__DTString.RemoveLeadingInQuoteSpaces(), System.Security.Cryptography.DSA.SignDataCore(), System.Text.ValueStringBuilder.ToString(), System.Range.ToString(), System.Security.Principal.SecurityIdentifier.ToString(), System.Text.SegmentStringBuilder.ToString(), System.Collections.Specialized.BitVector32.ToString(), System.Index.ToStringFromEnd(), System.Numerics.BigInteger.ToUInt32Span(), Internal.Cryptography.UniversalCryptoDecryptor.TransformOneShot(), System.MemoryExtensions.TryWriteInterpolatedStringHandler.TryAppendOrInsertAlignmentIfNeeded(), System.Text.ValueStringBuilder.TryCopyTo(), System.Text.Encodings.Web.TextEncoder.TryEncodeUnicodeScalarUtf8(), System.Buffers.Text.Utf8Formatter.TryFormatFloatingPoint< T >(), System.Convert.TryFromBase64Chars(), System.Buffers.Text.Utf8Parser.TryParseNumber(), System.Security.Cryptography.PemEncoding.TryWrite(), Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformBlock(), Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(), Internal.Cryptography.UniversalCryptoEncryptor.UncheckedTransformFinalBlock(), ReLogic.Localization.IME.WinImm32Ime.UpdateCandidateList(), System.Security.Cryptography.ECDsa.VerifyDataCore(), System.IO.BinaryWriter.Write(), System.Text.TranscodingStream.Write(), System.IO.BinaryWriter.Write(), Internal.Cryptography.Pal.X509Pal.X500DistinguishedNameDecode(), and Internal.Cryptography.Pal.X509Pal.X500DistinguishedNameFormat().