Terraria: UIElement.GetInnerDimensions
GetInnerDimensions()
CalculatedStyle UIElement.GetInnerDimensions () inline inherited
     {
         return _innerDimensions;
     }
References UIElement._innerDimensions.
Referenced by UIElement.DrawDebugHitbox(), UIResourcePack.DrawIcon(), UIAchievementListItem.DrawSelf(), UIBestiaryInfoLine< T >.DrawSelf(), UICharacterListItem.DrawSelf(), UIScrollbar.DrawSelf(), UIText.DrawSelf(), UIWorkshopImportWorldListItem.DrawSelf(), UIWorkshopPublishResourcePackListItem.DrawSelf(), UIWorkshopPublishWorldListItem.DrawSelf(), UIWorldListItem.DrawSelf(), UITextPanel< T >.DrawText(), UIScrollbar.GetHandleRectangle(), UIText.InternalSetText(), UIScrollbar.LeftMouseDown(), UIElement.Recalculate(), UICharacterNameButton.SetContents(), UIAchievementsMenu.SetupGamepadPoints(), UIEmotesMenu.SetupGamepadPoints(), UIManageControls.SetupGamepadPoints(), UIEmotesMenu.SetupGamepadPoints2(), and UIList.UpdateScrollbar().