Terraria: UIElement.MouseOver
MouseOver()
virtual void UIElement.MouseOver (UIMouseEvent evt) inline virtual inherited
Reimplemented in UIWorldListItem, UIWorkshopPublishWorldListItem, UIWorkshopPublishResourcePackListItem, UIWorkshopImportWorldListItem, UISearchBar, UIResourcePack, UIImageButton, UIIconTextButton, UIHairStyleButton, UIDifficultyButton, UIColoredImageButton, UIClothStyleButton, UICharacterNameButton, UICharacterListItem, UIAchievementListItem, GroupOptionButton< T >, and EmoteButton.
References UIElement.IsMouseHovering, UIElement.MouseOver(), UIElement.OnMouseOver, and UIElement.Parent.
Referenced by UIElement.MouseOver(), and UserInterface.Update().