Terraria: UIElement.SetPadding
SetPadding()
void UIElement.SetPadding (float pixels) inline inherited
     {
         PaddingBottom = pixels;
         PaddingLeft = pixels;
         PaddingRight = pixels;
         PaddingTop = pixels;
     }
References UIElement.PaddingBottom, UIElement.PaddingLeft, UIElement.PaddingRight, and UIElement.PaddingTop.
Referenced by EmotesGroupListItem.EmotesGroupListItem(), PowerStripUIElement.PowerStripUIElement(), UIBestiaryEntryButton.UIBestiaryEntryButton(), UIBestiaryEntryGrid.UIBestiaryEntryGrid(), UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), UIBestiaryFilteringOptionsGrid.UIBestiaryFilteringOptionsGrid(), UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), UIBestiarySortingOptionsGrid.UIBestiarySortingOptionsGrid(), UICharacterListItem.UICharacterListItem(), UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), UIPanel.UIPanel(), UIResourcePack.UIResourcePack(), UIVirtualKeyboard.UIVirtualKeyboard(), UIBestiaryTest.AddBackAndForwardButtons(), UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu(), UIBestiaryTest.AddSearchBar(), UICreativeInfiniteItemsDisplay.AddSearchBar(), UIBestiaryFilteringOptionsGrid.BuildContainer(), UIBestiarySortingOptionsGrid.BuildGrid(), UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), UICreativeInfiniteItemsDisplay.BuildPage(), UIBestiaryTest.BuildPage(), UICharacterCreation.BuildPage(), UIReportsPage.BuildPage(), UIResourcePackInfoMenu.BuildPage(), UIResourcePackSelectionMenu.BuildPage(), UIWorldCreation.BuildPage(), UIResourcePackSelectionMenu.CreateOffsetButton(), UIResourcePackSelectionMenu.CreatePackInfoButton(), UIResourcePackSelectionMenu.CreatePackToggleButton(), AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), NPCPortraitInfoElement.CreateStarsContainer(), AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList(), UIWorkshopImportWorldListItem.InitializeAppearance(), UIWorkshopPublishResourcePackListItem.InitializeAppearance(), UIWorkshopPublishWorldListItem.InitializeAppearance(), UIWorldListItem.InitializeAppearance(), UICharacterCreation.MakeClothStylesMenu(), UIWorkshopHub.MakeFancyButton(), UICharacterCreation.MakeHairsylesMenu(), UICharacterCreation.MakeHSLMenu(), UICharacterCreation.MakeInfoMenu(), UIWorldCreation.MakeInfoMenu(), UIWorkshopHub.OnInitialize(), FilterProviderInfoElement.ProvideUIElement(), NPCKillCounterInfoElement.ProvideUIElement(), NPCPortraitInfoElement.ProvideUIElement(), and UIBestiaryFilteringOptionsGrid.UpdateAvailability().