Terraria: UIElement.GetClippingRectangle
GetClippingRectangle()
Rectangle UIElement.GetClippingRectangle (SpriteBatch spriteBatch) inline inherited
     {
         Vector2 vector = new Vector2(_innerDimensions.X, _innerDimensions.Y);
         Vector2 position = new Vector2(_innerDimensions.Width, _innerDimensions.Height) + vector;
         vector = Vector2.Transform(vector, Main.UIScaleMatrix);
         position = Vector2.Transform(position, Main.UIScaleMatrix);
         Rectangle rectangle = new Rectangle((int)vector.X, (int)vector.Y, (int)(position.X - vector.X), (int)(position.Y - vector.Y));
         int num = (int)((float)Main.screenWidth * Main.UIScale);
         int num2 = (int)((float)Main.screenHeight * Main.UIScale);
         rectangle.X = Utils.Clamp(rectangle.X, 0, num);
         rectangle.Y = Utils.Clamp(rectangle.Y, 0, num2);
         rectangle.Width = Utils.Clamp(rectangle.Width, 0, num - rectangle.X);
         rectangle.Height = Utils.Clamp(rectangle.Height, 0, num2 - rectangle.Y);
         Rectangle scissorRectangle = spriteBatch.GraphicsDevice.ScissorRectangle;
         int num3 = Utils.Clamp(rectangle.Left, scissorRectangle.Left, scissorRectangle.Right);
         int num4 = Utils.Clamp(rectangle.Top, scissorRectangle.Top, scissorRectangle.Bottom);
         int num5 = Utils.Clamp(rectangle.Right, scissorRectangle.Left, scissorRectangle.Right);
         int num6 = Utils.Clamp(rectangle.Bottom, scissorRectangle.Top, scissorRectangle.Bottom);
         return new Rectangle(num3, num4, num5 - num3, num6 - num4);
     }
References UIElement._innerDimensions, CalculatedStyle.Height, Utils.Height(), Main.screenHeight, Main.screenWidth, Main.UIScale, Main.UIScaleMatrix, CalculatedStyle.Width, Utils.Width(), CalculatedStyle.X, and CalculatedStyle.Y.
Referenced by UIGamepadHelper.CullPointsOutOfElementArea(), UIElement.Draw(), UIGamepadHelper.RemovePointsOutOfView(), UIEmotesMenu.RemoveSnapPointsOutOfScreen(), UICharacterSelect.SetupGamepadPoints(), UIEmotesMenu.SetupGamepadPoints(), UIManageControls.SetupGamepadPoints(), UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), UIWorkshopWorldImport.SetupGamepadPoints(), and SetupGamepadPoints().