Terraria: UIElement.GetDimensions
GetDimensions()
CalculatedStyle UIElement.GetDimensions () inline inherited
     {
         return _dimensions;
     }
References UIElement._dimensions.
Referenced by SnapPoint.Calculate(), UIList.UIInnerList.DrawChildren(), UIPanel.DrawPanel(), UICharacter.DrawPets(), EmoteButton.DrawSelf(), GroupOptionButton< T >.DrawSelf(), UIAchievementListItem.DrawSelf(), UIBestiaryEntryIcon.DrawSelf(), UICharacter.DrawSelf(), UICharacterListItem.DrawSelf(), UICharacterNameButton.DrawSelf(), UIClothStyleButton.DrawSelf(), UIColoredImageButton.DrawSelf(), UIColoredSlider.DrawSelf(), UIDifficultyButton.DrawSelf(), UIGenProgressBar.DrawSelf(), UIHairStyleButton.DrawSelf(), UIHeader.DrawSelf(), UIHorizontalSeparator.DrawSelf(), UIIconTextButton.DrawSelf(), UIImage.DrawSelf(), UIImageButton.DrawSelf(), UIImageFramed.DrawSelf(), UIImageWithBorder.DrawSelf(), UIItemIcon.DrawSelf(), UIItemSlot.DrawSelf(), UIKeybindingListItem.DrawSelf(), UIKeybindingSimpleListItem.DrawSelf(), UIKeybindingSliderItem.DrawSelf(), UIKeybindingToggleListItem.DrawSelf(), UIProgressBar.UIInnerProgressBar.DrawSelf(), UIResourcePack.DrawSelf(), UIResourcePackInfoButton< T >.DrawSelf(), UIScrollbar.DrawSelf(), UISelectableTextPanel< T >.DrawSelf(), UISlicedImage.DrawSelf(), UIToggleImage.DrawSelf(), UIVerticalSeparator.DrawSelf(), UIWorkshopImportWorldListItem.DrawSelf(), UIWorkshopPublishResourcePackListItem.DrawSelf(), UIWorkshopPublishWorldListItem.DrawSelf(), UIWorldCreationPreview.DrawSelf(), UIWorldListItem.DrawSelf(), UIColoredSliderSimple.DrawValueBarDynamicWidth(), UIVerticalSlider.DrawValueBarDynamicWidth(), UIBestiaryEntryGrid.GetEntriesToShow(), UIBestiaryTest.GetEntriesToShow(), UIDynamicItemCollection.GetGridParameters(), UIDynamicItemCollection.GetSnapPoints(), UIWorldCreation.MakeInfoMenu(), UIParticleLayer.Recalculate(), UIIconTextButton.SetText(), UIVirtualKeyboard.SetupGamepadPoints(), UICharacterNameButton.TrimDisplayIfOverElementDimensions(), UISearchBar.TrimDisplayIfOverElementDimensions(), UIBestiaryEntryIcon.Update(), and UIDynamicItemCollection.UpdateSize().