Terraria: UIElement.Deactivate
Deactivate()
void UIElement.Deactivate () inline inherited
     {
         OnDeactivate();
         foreach (UIElement element in Elements)
         {
             element.Deactivate();
         }
     }
References UIElement.Deactivate(), UIElement.Elements, and UIElement.OnDeactivate().
Referenced by UIElement.Deactivate(), UIVirtualKeyboard.DrawSelf(), UserInterface.RefreshState(), and UserInterface.SetState().