Terraria: UIElement.Update
Update()
virtual void UIElement.Update (GameTime gameTime) inline virtual inherited
Reimplemented in UIWorldLoad, UIBestiaryTest, UISearchBar, UIDynamicItemCollection, UICreativeInfiniteItemsDisplay, UICharacter, UIBestiaryEntryIcon, and EmoteButton.
     {
         if (this.OnUpdate != null)
         {
             this.OnUpdate(this);
         }
         foreach (UIElement element in Elements)
         {
             element.Update(gameTime);
         }
     }
References UIElement.Elements, UIElement.OnUpdate, and UIElement.Update().
Referenced by UIElement.Update(), and UserInterface.Update().