Terraria: UIElement.Activate
Activate()
void UIElement.Activate () inline inherited
     {
         if (!_isInitialized)
         {
             Initialize();
         }
         OnActivate();
         foreach (UIElement element in Elements)
         {
             element.Activate();
         }
     }
References UIElement._isInitialized, UIElement.Activate(), UIElement.Elements, UIElement.Initialize(), and UIElement.OnActivate().
Referenced by UIElement.Activate(), UIVirtualKeyboard.DrawSelf(), UserInterface.RefreshState(), and UserInterface.SetState().