Terraria: InGameNotificationsTracker.Initialize
Initialize()
static void InGameNotificationsTracker.Initialize () inline static
     {
         Main.Achievements.OnAchievementCompleted += AddCompleted;
         SocialAPI.JoinRequests.OnRequestAdded += JoinRequests_OnRequestAdded;
         SocialAPI.JoinRequests.OnRequestRemoved += JoinRequests_OnRequestRemoved;
     }
References Main.Achievements, AddCompleted(), SocialAPI.JoinRequests, JoinRequests_OnRequestAdded(), JoinRequests_OnRequestRemoved(), AchievementManager.OnAchievementCompleted, ServerJoinRequestsManager.OnRequestAdded, and ServerJoinRequestsManager.OnRequestRemoved.
Referenced by Main.PostContentLoadInitialize().