Terraria: UIElement.MouseOut
MouseOut()
virtual void UIElement.MouseOut (UIMouseEvent evt) inline virtual inherited
Reimplemented in UIWorldListItem, UIWorkshopPublishWorldListItem, UIWorkshopPublishResourcePackListItem, UIWorkshopImportWorldListItem, UIResourcePack, UIImageButton, UIIconTextButton, UIHairStyleButton, UIDifficultyButton, UIColoredImageButton, UIClothStyleButton, UICharacterNameButton, UICharacterListItem, UIAchievementListItem, GroupOptionButton< T >, and EmoteButton.
References UIElement.IsMouseHovering, UIElement.MouseOut(), UIElement.OnMouseOut, and UIElement.Parent.
Referenced by UIElement.MouseOut(), UserInterface.ResetLasts(), UserInterface.ResetState(), UserInterface.SetState(), and UserInterface.Update().