Terraria: TileObject.DrawPreview
DrawPreview()
static void TileObject.DrawPreview (SpriteBatch sb, TileObjectPreviewData op, Vector2 position) inline static
     {
         Point16 coordinates = op.Coordinates;
         Texture2D value = TextureAssets.Tile[op.Type].Value;
         TileObjectData tileData = TileObjectData.GetTileData(op.Type, op.Style, op.Alternate);
         int num = 0;
         int num2 = 0;
         int num3 = tileData.CalculatePlacementStyle(op.Style, op.Alternate, op.Random);
         int num4 = 0;
         int num5 = tileData.DrawYOffset;
         int drawXOffset = tileData.DrawXOffset;
         num3 += tileData.DrawStyleOffset;
         int num6 = tileData.StyleWrapLimit;
         int num7 = tileData.StyleLineSkip;
         if (tileData.StyleWrapLimitVisualOverride.HasValue)
         {
             num6 = tileData.StyleWrapLimitVisualOverride.Value;
         }
         if (tileData.styleLineSkipVisualOverride.HasValue)
         {
             num7 = tileData.styleLineSkipVisualOverride.Value;
         }
         if (num6 > 0)
         {
             num4 = num3 / num6 * num7;
             num3 %= num6;
         }
         if (tileData.StyleHorizontal)
         {
             num = tileData.CoordinateFullWidth * num3;
             num2 = tileData.CoordinateFullHeight * num4;
         }
         else
         {
             num = tileData.CoordinateFullWidth * num4;
             num2 = tileData.CoordinateFullHeight * num3;
         }
         for (int i = 0; i < op.Size.X; i++)
         {
             int x = num + (i - op.ObjectStart.X) * (tileData.CoordinateWidth + tileData.CoordinatePadding);
             int num8 = num2;
             for (int j = 0; j < op.Size.Y; j++)
             {
                 int num9 = coordinates.X + i;
                 int num10 = coordinates.Y + j;
                 if (j == 0 && tileData.DrawStepDown != 0 && WorldGen.SolidTile(Framing.GetTileSafely(num9, num10 - 1)))
                 {
                     num5 += tileData.DrawStepDown;
                 }
                 if (op.Type == 567)
                 {
                     num5 = ((j != 0) ? tileData.DrawYOffset : (tileData.DrawYOffset - 2));
                 }
                 int num11 = op[i, j];
                 Color color;
                 if (num11 != 1)
                 {
                     if (num11 != 2)
                     {
                         continue;
                     }
                     color = Color.Red * 0.7f;
                 }
                 else
                 {
                     color = Color.White;
                 }
                 color *= 0.5f;
                 if (i >= op.ObjectStart.X && i < op.ObjectStart.X + tileData.Width && j >= op.ObjectStart.Y && j < op.ObjectStart.Y + tileData.Height)
                 {
                     SpriteEffects spriteEffects = SpriteEffects.None;
                     if (tileData.DrawFlipHorizontal && num9 % 2 == 0)
                     {
                         spriteEffects |= SpriteEffects.FlipHorizontally;
                     }
                     if (tileData.DrawFlipVertical && num10 % 2 == 0)
                     {
                         spriteEffects |= SpriteEffects.FlipVertically;
                     }
                     int coordinateWidth = tileData.CoordinateWidth;
                     int num12 = tileData.CoordinateHeights[j - op.ObjectStart.Y];
                     if (op.Type == 114 && j == 1)
                     {
                         num12 += 2;
                     }
                     sb.Draw(sourceRectangle: new Rectangle(x, num8, coordinateWidth, num12), texture: value, position: new Vector2(num9 * 16 - (int)(position.X + (float)(coordinateWidth - 16) / 2f) + drawXOffset, num10 * 16 - (int)position.Y + num5), color: color, rotation: 0f, origin: Vector2.Zero, scale: 1f, effects: spriteEffects, layerDepth: 0f);
                     num8 += num12 + tileData.CoordinatePadding;
                 }
             }
         }
     }
References TileObjectPreviewData.Alternate, TileObjectData.CalculatePlacementStyle(), Color, TileObjectData.CoordinateFullHeight, TileObjectData.CoordinateFullWidth, TileObjectData.CoordinateHeights, TileObjectData.CoordinatePadding, TileObjectPreviewData.Coordinates, TileObjectData.CoordinateWidth, TileObjectData.DrawFlipHorizontal, TileObjectData.DrawFlipVertical, TileObjectData.DrawStepDown, TileObjectData.DrawStyleOffset, TileObjectData.DrawXOffset, TileObjectData.DrawYOffset, TileObjectData.GetTileData(), Framing.GetTileSafely(), TileObjectData.Height, TileObjectPreviewData.ObjectStart, TileObjectPreviewData.Random, TileObjectPreviewData.Size, WorldGen.SolidTile(), TileObjectPreviewData.Style, TileObjectData.StyleHorizontal, TileObjectData.StyleLineSkip, TileObjectData.styleLineSkipVisualOverride, TileObjectData.StyleWrapLimit, TileObjectData.StyleWrapLimitVisualOverride, TextureAssets.Tile, TileObjectPreviewData.Type, Asset< T >.Value, Point16.X, and Point16.Y.
Referenced by TileDrawing.Draw().