Terraria: System.Net.GlobalSSPI.SSPIAuth
SSPIAuth [1/2]
static readonly System Net SSPIAuthType System.Net.GlobalSSPI.SSPIAuth = new System.Net.SSPIAuthType() static package
Definition at line 5 of file GlobalSSPI.cs.
Referenced by System.Net.Security.NegotiateStreamPal.AcceptSecurityContext(), System.Net.Security.NegotiateStreamPal.AcceptSecurityContext(), System.Net.Security.NegotiateStreamPal.AcquireCredentialsHandle(), System.Net.Security.NegotiateStreamPal.AcquireDefaultCredential(), System.Net.Security.NegotiateStreamPal.CompleteAuthToken(), System.Net.Security.NegotiateStreamPal.CompleteAuthToken(), System.Net.Security.NegotiateStreamPal.Decrypt(), System.Net.Security.NegotiateStreamPal.DecryptNtlm(), System.Net.Security.NegotiateStreamPal.Encrypt(), System.Net.Security.NegotiateStreamPal.GetIdentity(), System.Net.HttpListener.HandleAuthentication(), System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(), System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(), System.Net.Security.NegotiateStreamPal.MakeSignature(), System.Net.Security.NegotiateStreamPal.QueryContextAssociatedName(), System.Net.Security.NegotiateStreamPal.QueryContextAuthenticationPackage(), System.Net.Security.NegotiateStreamPal.QueryContextAuthenticationPackage(), System.Net.Security.NegotiateStreamPal.QueryContextClientSpecifiedSpn(), System.Net.Security.NegotiateStreamPal.QueryContextClientSpecifiedSpn(), System.Net.Security.NegotiateStreamPal.QueryMaxTokenSize(), and System.Net.Security.NegotiateStreamPal.VerifySignature().