Terraria: System.Net.GlobalSSPI.SSPISecureChannel
SSPISecureChannel [1/2]
static readonly System Net SSPISecureChannelType System.Net.GlobalSSPI.SSPISecureChannel = new System.Net.SSPISecureChannelType() static package
Definition at line 7 of file GlobalSSPI.cs.
Referenced by System.Net.Security.SslStreamPal.AcceptSecurityContext(), System.Net.Security.SslStreamPal.AcquireCredentialsHandle(), System.Net.Security.SslStreamPal.AcquireCredentialsHandle(), System.Net.Security.SslStreamPal.ApplyAlertToken(), System.Net.Security.SslStreamPal.ApplyShutdownToken(), System.Net.Security.SslStreamPal.DecryptMessage(), System.Net.Security.SslStreamPal.EncryptMessage(), System.Net.Security.SslStreamPal.GetNegotiatedApplicationProtocol(), System.Net.CertificateValidationPal.GetRemoteCertificate(), System.Net.CertificateValidationPal.GetRequestCertificateAuthorities(), System.Net.Security.SslStreamPal.InitializeSecurityContext(), System.Net.Security.SslStreamPal.QueryContextChannelBinding(), System.Net.Security.SslStreamPal.QueryContextConnectionInfo(), System.Net.Security.SslStreamPal.QueryContextStreamSizes(), and System.Net.Security.SslStreamPal.VerifyPackageInfo().