Terraria: UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem
UIWorkshopImportWorldListItem()
UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem (UIState ownerState, WorldFileData data, int orderInList) inline
     {
         _ownerState = ownerState;
         _orderInList = orderInList;
         _data = data;
         LoadTextures();
         InitializeAppearance();
         _worldIcon = GetIconElement();
         _worldIcon.Left.Set(4f, 0f);
         _worldIcon.OnLeftDoubleClick += ImportButtonClick_ImportWorldToLocalFiles;
         Append(_worldIcon);
         float num = 4f;
         UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", (AssetRequestMode)1));
         uIImageButton.VAlign = 1f;
         uIImageButton.Left.Set(num, 0f);
         uIImageButton.OnLeftClick += ImportButtonClick_ImportWorldToLocalFiles;
         base.OnLeftDoubleClick += ImportButtonClick_ImportWorldToLocalFiles;
         uIImageButton.OnMouseOver += PlayMouseOver;
         uIImageButton.OnMouseOut += ButtonMouseOut;
         Append(uIImageButton);
         num += 24f;
         _buttonLabel = new UIText("");
         _buttonLabel.VAlign = 1f;
         _buttonLabel.Left.Set(num, 0f);
         _buttonLabel.Top.Set(-3f, 0f);
         Append(_buttonLabel);
         uIImageButton.SetSnapPoint("Import", orderInList);
     }
References _buttonLabel, AWorldListItem._data, _orderInList, _ownerState, _worldIcon, UIElement.Append(), Main.Assets, ButtonMouseOut(), AWorldListItem.GetIconElement(), ImportButtonClick_ImportWorldToLocalFiles(), InitializeAppearance(), UIElement.Left, LoadTextures(), UIElement.OnLeftClick, UIElement.OnLeftDoubleClick, UIElement.OnMouseOut, UIElement.OnMouseOver, PlayMouseOver(), StyleDimension.Set(), UIElement.SetSnapPoint(), UIElement.Top, and UIElement.VAlign.