Terraria: UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles
ImportButtonClick_ImportWorldToLocalFiles()
void UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles (UIMouseEvent evt, UIElement listeningElement) inline private
     {
         if (listeningElement == evt.Target)
         {
             SoundEngine.PlaySound(10);
             Main.clrInput();
             UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Language.GetTextValue("Workshop.EnterNewNameForImportedWorld"), _data.Name, OnFinishedSettingName, GoToMainMenu, 0, allowEmpty: true);
             uIVirtualKeyboard.SetMaxInputLength(27);
             uIVirtualKeyboard.Text = _data.Name;
             Main.MenuUI.SetState(uIVirtualKeyboard);
         }
     }
References AWorldListItem._data, Main.clrInput(), Language.GetTextValue(), GoToMainMenu(), Main.MenuUI, FileData.Name, OnFinishedSettingName(), SoundEngine.PlaySound(), UIVirtualKeyboard.SetMaxInputLength(), UserInterface.SetState(), UIEvent.Target, and UIVirtualKeyboard.Text.
Referenced by UIWorkshopImportWorldListItem().