Terraria: System.Xml.XmlConvert.VerifyNMTOKEN
VerifyNMTOKEN() [2/2]
static string System.Xml.XmlConvert.VerifyNMTOKEN (string name, ExceptionType exceptionType) inline static package
Definition at line 394 of file XmlConvert.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw CreateException(System.SR.Xml_InvalidNmToken, name, exceptionType);
        }
        int num = ValidateNames.ParseNmtokenNoNamespaces(name, 0);
        if (num != name.Length)
        {
            throw CreateException(System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(name, num), exceptionType, 0, num + 1);
        }
        return name;
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlConvert.CreateException(), System.Xml.Dictionary, System.Text.RegularExpressions.name, System.Xml.ValidateNames.ParseNmtokenNoNamespaces(), System.SR.Xml_BadNameChar, and System.SR.Xml_InvalidNmToken.