Terraria: System.Xml.XmlConvert.EncodeName
EncodeName() [1/2]
static string System.Xml.XmlConvert.EncodeName (string name, bool first, bool local) inline static private
Definition at line 138 of file XmlConvert.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        StringBuilder stringBuilder = null;
        int length = name.Length;
        int num = 0;
        int i = 0;
        int num2 = name.IndexOf('_');
        MatchCollection matchCollection = null;
        IEnumerator enumerator = null;
        if (num2 >= 0)
        {
            if (s_encodeCharPattern == null)
            {
                s_encodeCharPattern = new Regex("(?<=_)[Xx]([0-9a-fA-F]{4}|[0-9a-fA-F]{8})_");
            }
            matchCollection = s_encodeCharPattern.Matches(name, num2);
            enumerator = matchCollection.GetEnumerator();
        }
        int num3 = -1;
        if (enumerator != null && enumerator.MoveNext())
        {
            Match match = (Match)enumerator.Current;
            num3 = match.Index - 1;
        }
        if (first && ((!XmlCharType.IsStartNCNameCharXml4e(name[0]) && (local || (!local && name[0] != ':'))) || num3 == 0))
        {
            if (stringBuilder == null)
            {
                stringBuilder = new StringBuilder(length + 20);
            }
            stringBuilder.Append("_x");
            if (length > 1 && XmlCharType.IsHighSurrogate(name[0]) && XmlCharType.IsLowSurrogate(name[1]))
            {
                int highChar = name[0];
                int lowChar = name[1];
                int value = XmlCharType.CombineSurrogateChar(lowChar, highChar);
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder3 = stringBuilder2;
                StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2);
                handler.AppendFormatted(value, "X8");
                stringBuilder3.Append(ref handler);
                i++;
                num = 2;
            }
            else
            {
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder stringBuilder4 = stringBuilder2;
                StringBuilder.AppendInterpolatedStringHandler handler2 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2);
                handler2.AppendFormatted((int)name[0], "X4");
                stringBuilder4.Append(ref handler2);
                num = 1;
            }
            stringBuilder.Append('_');
            i++;
            if (num3 == 0 && enumerator.MoveNext())
            {
                Match match2 = (Match)enumerator.Current;
                num3 = match2.Index - 1;
            }
        }
        for (; i < length; i++)
        {
            if ((local && !XmlCharType.IsNCNameCharXml4e(name[i])) || (!local && !XmlCharType.IsNameCharXml4e(name[i])) || num3 == i)
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(length + 20);
                }
                if (num3 == i && enumerator.MoveNext())
                {
                    Match match3 = (Match)enumerator.Current;
                    num3 = match3.Index - 1;
                }
                stringBuilder.Append(name, num, i - num);
                stringBuilder.Append("_x");
                if (length > i + 1 && XmlCharType.IsHighSurrogate(name[i]) && XmlCharType.IsLowSurrogate(name[i + 1]))
                {
                    int highChar2 = name[i];
                    int lowChar2 = name[i + 1];
                    int value2 = XmlCharType.CombineSurrogateChar(lowChar2, highChar2);
                    StringBuilder stringBuilder2 = stringBuilder;
                    StringBuilder stringBuilder5 = stringBuilder2;
                    StringBuilder.AppendInterpolatedStringHandler handler3 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2);
                    handler3.AppendFormatted(value2, "X8");
                    stringBuilder5.Append(ref handler3);
                    num = i + 2;
                    i++;
                }
                else
                {
                    StringBuilder stringBuilder2 = stringBuilder;
                    StringBuilder stringBuilder6 = stringBuilder2;
                    StringBuilder.AppendInterpolatedStringHandler handler4 = new StringBuilder.AppendInterpolatedStringHandler(0, 1, stringBuilder2);
                    handler4.AppendFormatted((int)name[i], "X4");
                    stringBuilder6.Append(ref handler4);
                    num = i + 1;
                }
                stringBuilder.Append('_');
            }
        }
        if (num == 0)
        {
            return name;
        }
        if (num < length)
        {
            stringBuilder.Append(name, num, length - num);
        }
        return stringBuilder.ToString();
    }
References System.Text.StringBuilder.AppendInterpolatedStringHandler.AppendFormatted(), System.Xml.XmlCharType.CombineSurrogateChar(), System.Xml.Dictionary, System.Text.RegularExpressions.i, System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.Xml.XmlCharType.IsNameCharXml4e(), System.Xml.XmlCharType.IsNCNameCharXml4e(), System.Xml.XmlCharType.IsStartNCNameCharXml4e(), System.length, System.Text.StringBuilder.Length, System.match, System.Text.RegularExpressions.name, System.Xml.XmlConvert.s_encodeCharPattern, and System.value.