Terraria: System.Xml.XmlConvert.ToInt64
ToInt64()
static long System.Xml.XmlConvert.ToInt64 (string s) inline static
Definition at line 784 of file XmlConvert.cs.
    {
        return long.Parse(s, NumberStyles.Integer, NumberFormatInfo.InvariantInfo);
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, and System.s.
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.Int64Storage.ConvertXmlToObject(), System.Xml.Schema.XmlUntypedStringConverter.FromString(), System.Xml.Linq.XAttribute.operator long(), System.Xml.Linq.XElement.operator long(), System.Xml.Linq.XAttribute.operator long?(), System.Xml.Linq.XElement.operator long?(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_long(), System.Xml.XmlReader.ReadContentAsLong(), System.Xml.XmlSqlBinaryReader.ReadContentAsLong(), System.Xml.XmlReader.ReadElementContentAsLong(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Data.SqlTypes.SqlInt64.ReadXml(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), System.Xml.XmlConverter.ToInt64(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), System.Xml.Schema.XmlUntypedConverter.ToInt64(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().