Terraria: System.Xml.XmlConvert.CreateInvalidCharException
CreateInvalidCharException() [3/5]
static Exception System.Xml.XmlConvert.CreateInvalidCharException (char[] data, int length, int invCharPos, ExceptionType exceptionType) inline static package
Definition at line 1457 of file XmlConvert.cs.
    {
        return CreateException(System.SR.Xml_InvalidCharacter, XmlException.BuildCharExceptionArgs(data, length, invCharPos), exceptionType, 0, invCharPos + 1);
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlConvert.CreateException(), System.Xml.Dictionary, System.length, and System.SR.Xml_InvalidCharacter.
Referenced by System.Xml.XmlSqlBinaryReader.CheckText(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(), System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyPublicId(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntity(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntity(), System.Xml.XmlEncodedRawTextWriter.WriteCharEntityAsync(), System.Xml.XmlUtf8RawTextWriter.WriteCharEntityAsync(), System.Xml.XmlCharCheckingWriter.WriteDocType(), and System.Xml.XmlCharCheckingWriter.WriteDocTypeAsync().