Terraria: System.Xml.XmlConvert.ToTimeSpan
ToTimeSpan()
static TimeSpan System.Xml.XmlConvert.ToTimeSpan (string s) inline static
Definition at line 1013 of file XmlConvert.cs.
    {
        XsdDuration xsdDuration;
        try
        {
            xsdDuration = new XsdDuration(s);
        }
        catch (Exception)
        {
            throw new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "TimeSpan"));
        }
        return xsdDuration.ToTimeSpan();
    }
References System.Xml.Dictionary, System.SR.Format(), System.s, and System.SR.XmlConvert_BadFormat.
Referenced by System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.TimeSpanStorage.ConvertXmlToObject(), System.Xml.Linq.XAttribute.operator TimeSpan(), System.Xml.Linq.XElement.operator TimeSpan(), System.Xml.Linq.XAttribute.operator TimeSpan?(), System.Xml.Linq.XElement.operator TimeSpan?(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_TimeSpan(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.XmlConverter.ToTimeSpan(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().