Terraria: System.Xml.XmlConvert.SplitString
SplitString() [1/2]
static string[] System.Xml.XmlConvert.SplitString (string value) inline static package
Definition at line 1228 of file XmlConvert.cs.
    {
        return value.Split(WhitespaceChars, StringSplitOptions.RemoveEmptyEntries);
    }
References System.value, and System.Xml.XmlConvert.WhitespaceChars.
Referenced by System.Xml.Schema.NamespaceList.NamespaceList(), System.Xml.Xsl.Xslt.XsltLoader.AddUseAttributeSets(), System.Xml.Xsl.XsltOld.UseAttributeSetsAction.Compile(), System.Xml.Xsl.XsltOld.XsltOutput.CompileAttribute(), System.Xml.Xsl.XsltOld.ContainerAction.CompileSpace(), System.Xml.Xsl.Runtime.IdIterator.Create(), System.Xml.Schema.XmlSchemaValidator.EnumerateAny(), System.Xml.Xsl.Xslt.XsltInput.InsertExNamespaces(), System.Xml.Xsl.Xslt.XsltLoader.LoadOutput(), System.Xml.Schema.XsdBuilder.ParseBlockFinalEnum(), System.Xml.Xsl.Xslt.XsltLoader.ParseModeListAttribute(), System.Xml.Xsl.Xslt.XsltLoader.ParseUseCharacterMaps(), System.Xml.Xsl.Xslt.XsltLoader.ParseWhitespaceRules(), MS.Internal.Xml.XPath.IDQuery.ProcessIds(), System.Xml.Xsl.XsltOld.Compiler.ResolvePrefixes(), System.Xml.Xsl.Xslt.XsltInput.SetDefaultCollation(), System.Xml.Schema.XmlListConverter.StringAsList(), System.Xml.Schema.XmlUntypedStringConverter.StringToListType(), and System.Xml.Schema.Datatype_List.TryParseValue().