Terraria: System.Xml.XmlConvert.ToDateTime
ToDateTime() [1/4]
static DateTime System.Xml.XmlConvert.ToDateTime (string s) inline static
Definition at line 1053 of file XmlConvert.cs.
    {
        return ToDateTime(s, AllDateTimeFormats);
    }
References System.Xml.XmlConvert.AllDateTimeFormats, System.s, and System.Xml.XmlConvert.ToDateTime().
Referenced by System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.DateTimeStorage.ConvertXmlToObject(), System.Xml.Schema.XmlSchemaInference.DateTime(), System.Xml.XmlReader.ReadContentAsDateTime(), System.Xml.XmlSqlBinaryReader.ReadContentAsDateTime(), System.Runtime.Serialization.XmlReaderDelegator.ReadElementContentAsDateTime(), System.Xml.XmlReader.ReadElementContentAsDateTime(), System.Data.SqlTypes.SqlDateTime.ReadXml(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.XmlConvert.ToDateTime(), System.Xml.XmlConverter.ToDateTime(), System.Xml.Serialization.XmlCustomFormatter.ToDateTime(), and System.Xml.Serialization.XmlCustomFormatter.ToDateTime().