Terraria: System.Xml.XmlConvert.ToXPathString
ToXPathString()
static string System.Xml.XmlConvert.ToXPathString (object value) inline static package
Definition at line 982 of file XmlConvert.cs.
    {
        if (value is string result)
        {
            return result;
        }
        if (value is double num)
        {
            return num.ToString("R", NumberFormatInfo.InvariantInfo);
        }
        if (value is bool)
        {
            if (!(bool)value)
            {
                return "false";
            }
            return "true";
        }
        return Convert.ToString(value, NumberFormatInfo.InvariantInfo);
    }
References System.Xml.Dictionary, System.Globalization.NumberFormatInfo.InvariantInfo, System.Convert.ToString(), and System.value.
Referenced by System.Xml.Xsl.XsltOld.XsltCompileContext.Document(), System.Xml.Xsl.XsltOld.XsltCompileContext.EvaluateKey(), System.Xml.Xsl.XsltOld.Processor.EvaluateString(), System.Xml.Xsl.XsltOld.CopyOfAction.Execute(), System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem(), System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToString(), and System.Xml.Xsl.XsltOld.Processor.ValueOf().