Terraria: System.Xml.XmlConvert.TryToUri
TryToUri()
static Exception System.Xml.XmlConvert.TryToUri (string s, out Uri result) inline static package
Definition at line 1182 of file XmlConvert.cs.
    {
        result = null;
        if (s != null && s.Length > 0)
        {
            s = TrimString(s);
            if (s.Length == 0 || s.IndexOf("##", StringComparison.Ordinal) != -1)
            {
                return new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Uri"));
            }
        }
        if (!Uri.TryCreate(s, UriKind.RelativeOrAbsolute, out result))
        {
            return new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Uri"));
        }
        return null;
    }
References System.Xml.Dictionary, System.SR.Format(), System.s, System.Xml.XmlConvert.TrimString(), System.Uri.TryCreate(), and System.SR.XmlConvert_BadFormat.
Referenced by System.Xml.Schema.StringFacetsChecker.CheckBuiltInFacets(), and System.Xml.Schema.Datatype_anyURI.TryParseValue().