Terraria: System.Xml.XmlConvert.ToSingle
ToSingle()
static float System.Xml.XmlConvert.ToSingle (string s) inline static
Definition at line 857 of file XmlConvert.cs.
    {
        s = TrimString(s);
        if (s == "-INF")
        {
            return float.NegativeInfinity;
        }
        if (s == "INF")
        {
            return float.PositiveInfinity;
        }
        float num = float.Parse(s, NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint | NumberStyles.AllowExponent, NumberFormatInfo.InvariantInfo);
        if (num == 0f && s[0] == '-')
        {
            return -0f;
        }
        return num;
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, System.s, and System.Xml.XmlConvert.TrimString().
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.SingleStorage.ConvertXmlToObject(), System.Xml.Schema.XmlUntypedStringConverter.FromString(), System.Xml.Linq.XAttribute.operator float(), System.Xml.Linq.XElement.operator float(), System.Xml.Linq.XAttribute.operator float?(), System.Xml.Linq.XElement.operator float?(), System.Xml.Schema.Datatype_floatXdr.ParseValue(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_float(), System.Xml.XmlReader.ReadContentAsFloat(), System.Xml.XmlSqlBinaryReader.ReadContentAsFloat(), System.Xml.XmlReader.ReadElementContentAsFloat(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Data.SqlTypes.SqlSingle.ReadXml(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), System.Xml.XmlConverter.ToSingle(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), System.Xml.Schema.XmlUntypedConverter.ToSingle(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().