Terraria: System.Xml.XmlConvert.ToUri
ToUri()
static Uri System.Xml.XmlConvert.ToUri (string s) inline static package
Definition at line 1165 of file XmlConvert.cs.
    {
        if (!string.IsNullOrEmpty(s))
        {
            s = TrimString(s);
            if (s.Length == 0 || s.IndexOf("##", StringComparison.Ordinal) != -1)
            {
                throw new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Uri"));
            }
        }
        if (!Uri.TryCreate(s, UriKind.RelativeOrAbsolute, out Uri result))
        {
            throw new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Uri"));
        }
        return result;
    }
References System.Xml.Dictionary, System.SR.Format(), System.s, System.Xml.XmlConvert.TrimString(), System.Uri.TryCreate(), and System.SR.XmlConvert_BadFormat.
Referenced by System.Xml.Schema.NamespaceList.NamespaceList(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlMiscConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.DocumentSchemaValidator.CreateValidator(), System.Xml.Schema.XmlUntypedStringConverter.FromString(), System.Xml.Schema.Preprocessor.ParseUri(), System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation(), System.Xml.XsdValidatingReader.SetupValidator(), System.Xml.Xsl.XsltOld.Compiler.ValidateExtensionNamespace(), and System.Xml.XmlQualifiedName.Verify().