Terraria: System.Xml.XmlConvert.ToXPathDouble
ToXPathDouble()
static double System.Xml.XmlConvert.ToXPathDouble (object o) inline static package
Definition at line 943 of file XmlConvert.cs.
    {
        if (o is string value)
        {
            string text = TrimString(value);
            if (text.Length != 0 && text[0] != '+' && double.TryParse(text, NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint, NumberFormatInfo.InvariantInfo, out var result))
            {
                return result;
            }
            return double.NaN;
        }
        if (o is double)
        {
            return (double)o;
        }
        if (o is bool)
        {
            if (!(bool)o)
            {
                return 0.0;
            }
            return 1.0;
        }
        try
        {
            return Convert.ToDouble(o, NumberFormatInfo.InvariantInfo);
        }
        catch (FormatException)
        {
        }
        catch (OverflowException)
        {
        }
        catch (ArgumentNullException)
        {
        }
        return double.NaN;
    }
References System.Xml.Dictionary, System.Globalization.NumberFormatInfo.InvariantInfo, System.text, System.Convert.ToDouble(), System.Xml.XmlConvert.TrimString(), and System.value.
Referenced by MS.Internal.Xml.XPath.XPathComparerHelper.Compare(), System.Xml.Xsl.XsltOld.TemplateAction.CompileAttribute(), System.Xml.Xsl.XsltOld.ContainerAction.CompileStylesheetAttributes(), MS.Internal.Xml.XPath.NumericExpr.Evaluate(), System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem(), System.Xml.Xsl.XsltOld.Processor.GetGlobalParameter(), MS.Internal.Xml.XPath.NumberFunctions.Number(), MS.Internal.Xml.XPath.NumberFunctions.Number(), MS.Internal.Xml.XPath.NumberFunctions.Round(), MS.Internal.Xml.XPath.XPathScanner.ScanFraction(), MS.Internal.Xml.XPath.XPathScanner.ScanNumber(), MS.Internal.Xml.XPath.StringFunctions.Substring(), and System.Xml.Xsl.XsltOld.XsltCompileContext.XsltFunctionImpl.ToNumber().