Terraria: System.Xml.XmlConvert.VerifyCharData
VerifyCharData() [3/3]
static void System.Xml.XmlConvert.VerifyCharData (string data, ExceptionType invCharExceptionType, ExceptionType invSurrogateExceptionType) inline static package
Definition at line 1252 of file XmlConvert.cs.
    {
        if (data == null || data.Length == 0)
        {
            return;
        }
        int num = 0;
        int length = data.Length;
        while (true)
        {
            if (num < length && XmlCharType.IsCharData(data[num]))
            {
                num++;
                continue;
            }
            if (num == length)
            {
                return;
            }
            char ch = data[num];
            if (!XmlCharType.IsHighSurrogate(ch))
            {
                break;
            }
            if (num + 1 == length)
            {
                throw CreateException(System.SR.Xml_InvalidSurrogateMissingLowChar, invSurrogateExceptionType, 0, num + 1);
            }
            ch = data[num + 1];
            if (XmlCharType.IsLowSurrogate(ch))
            {
                num += 2;
                continue;
            }
            throw CreateInvalidSurrogatePairException(data[num + 1], data[num], invSurrogateExceptionType, 0, num + 1);
        }
        throw CreateInvalidCharException(data, num, invCharExceptionType);
    }
References System.ch, System.Xml.XmlConvert.CreateException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.Dictionary, System.Xml.XmlCharType.IsCharData(), System.Xml.XmlCharType.IsHighSurrogate(), System.Xml.XmlCharType.IsLowSurrogate(), System.length, and System.SR.Xml_InvalidSurrogateMissingLowChar.