Terraria: System.Xml.XmlConvert.DecodeName
DecodeName()
static ? string System.Xml.XmlConvert.DecodeName (string? name) inline static
Definition at line 55 of file XmlConvert.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }
        StringBuilder stringBuilder = null;
        int length = name.Length;
        int num = 0;
        int num2 = name.IndexOf('_');
        MatchCollection matchCollection = null;
        IEnumerator enumerator = null;
        if (num2 >= 0)
        {
            if (s_decodeCharPattern == null)
            {
                s_decodeCharPattern = new Regex("_[Xx]([0-9a-fA-F]{4}|[0-9a-fA-F]{8})_");
            }
            matchCollection = s_decodeCharPattern.Matches(name, num2);
            enumerator = matchCollection.GetEnumerator();
            int num3 = -1;
            if (enumerator != null && enumerator.MoveNext())
            {
                Match match = (Match)enumerator.Current;
                num3 = match.Index;
            }
            for (int i = 0; i < length - 7 + 1; i++)
            {
                if (i != num3)
                {
                    continue;
                }
                if (enumerator.MoveNext())
                {
                    Match match2 = (Match)enumerator.Current;
                    num3 = match2.Index;
                }
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(length + 20);
                }
                stringBuilder.Append(name, num, i - num);
                if (name[i + 6] != '_')
                {
                    int num4 = FromHex(name[i + 2]) * 268435456 + FromHex(name[i + 3]) * 16777216 + FromHex(name[i + 4]) * 1048576 + FromHex(name[i + 5]) * 65536 + FromHex(name[i + 6]) * 4096 + FromHex(name[i + 7]) * 256 + FromHex(name[i + 8]) * 16 + FromHex(name[i + 9]);
                    if (num4 >= 65536)
                    {
                        if (num4 <= 1114111)
{
                            num = i + 7 + 4;
                            XmlCharType.SplitSurrogateChar(num4, out var lowChar, out var highChar);
                            stringBuilder.Append(highChar);
                            stringBuilder.Append(lowChar);
                        }
                    }
                    else
                    {
                        num = i + 7 + 4;
                        stringBuilder.Append((char)num4);
                    }
                    i += 10;
                }
                else
                {
                    num = i + 7;
                    stringBuilder.Append((char)(FromHex(name[i + 2]) * 4096 + FromHex(name[i + 3]) * 256 + FromHex(name[i + 4]) * 16 + FromHex(name[i + 5])));
                    i += 6;
                }
            }
            if (num == 0)
            {
                return name;
            }
            if (num < length)
            {
                stringBuilder.Append(name, num, length - num);
            }
            return stringBuilder.ToString();
        }
        return name;
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.FromHex(), System.Text.RegularExpressions.i, System.length, System.Text.StringBuilder.Length, System.match, System.Text.RegularExpressions.name, System.Xml.XmlConvert.s_decodeCharPattern, and System.Xml.XmlCharType.SplitSurrogateChar().
Referenced by System.Runtime.Serialization.Json.DataContractJsonSerializer.ConvertXmlNameToJsonName(), System.Runtime.Serialization.SchemaExporter.ExportGenericInfo(), System.Data.XSDSchema.FindField(), System.Data.XSDSchema.GetTableName(), System.Data.XSDSchema.GetTableNamespace(), System.Data.XSDSchema.HandleAttributeColumn(), System.Data.XDRSchema.HandleColumn(), System.Data.XSDSchema.HandleConstraint(), System.Data.XSDSchema.HandleDataSet(), System.Data.XSDSchema.HandleElementColumn(), System.Data.XSDSchema.HandleKeyref(), System.Data.XSDSchema.HandleRefTableProperties(), System.Data.XSDSchema.HandleRelation(), System.Data.XDRSchema.InstantiateSimpleTable(), System.Data.XSDSchema.InstantiateSimpleTable(), System.Data.XDRSchema.InstantiateTable(), System.Data.XSDSchema.InstantiateTable(), System.Data.XDRSchema.LoadSchema(), System.Data.XSDSchema.LoadSchema(), System.Data.XmlDataLoader.LoadTable(), System.Data.XMLDiffLoader.ProcessErrors(), System.Data.XMLDiffLoader.ProcessErrors(), System.Data.XMLDiffLoader.ReadOldRowData(), System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadSerializationInfo(), System.Data.XSDSchema.SetExtProperties(), System.Data.XSDSchema.SetExtProperties(), System.Xml.Serialization.XmlCustomFormatter.ToXmlName(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNCName(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNmToken(), System.Xml.Serialization.XmlCustomFormatter.ToXmlNmTokens(), System.Xml.Serialization.XmlSerializationReader.ToXmlQualifiedName(), and System.Xml.Serialization.Accessor.UnescapeName().