Terraria: System.Xml.XmlConvert.VerifyName
VerifyName()
static string System.Xml.XmlConvert.VerifyName (string name) inline static
Definition at line 282 of file XmlConvert.cs.
    {
        if (name == null)
        {
            throw new ArgumentNullException("name");
        }
        if (name.Length == 0)
        {
            throw new ArgumentNullException("name", System.SR.Xml_EmptyName);
        }
        int num = ValidateNames.ParseNameNoNamespaces(name, 0);
        if (num != name.Length)
        {
            throw CreateInvalidNameCharException(name, num, ExceptionType.XmlException);
        }
        return name;
    }
References System.Xml.XmlConvert.CreateInvalidNameCharException(), System.Text.RegularExpressions.name, System.Xml.ValidateNames.ParseNameNoNamespaces(), and System.SR.Xml_EmptyName.
Referenced by System.Xml.Linq.XDocumentType.XDocumentType(), and System.Xml.DtdParser.InitializeFreeFloatingDtd().