Terraria: System.Xml.XmlConvert.StrEqual
StrEqual()
static bool System.Xml.XmlConvert.StrEqual (char[] chars, int strPos1, int strLen1, string str2) inline static package
Definition at line 1200 of file XmlConvert.cs.
    {
        if (strLen1 != str2.Length)
        {
            return false;
        }
        int i;
        for (i = 0; i < strLen1 && chars[strPos1 + i] == str2[i]; i++)
        {
        }
        return i == strLen1;
    }
References System.chars, System.Xml.Dictionary, and System.Text.RegularExpressions.i.
Referenced by System.Xml.XmlTextReaderImpl.AddAttribute(), System.Xml.XmlTextReaderImpl.IncrementalRead(), System.Xml.XmlTextReaderImpl.ParseDoctypeDecl(), System.Xml.XmlTextReaderImpl.ParseDoctypeDeclAsync(), System.Xml.XmlTextReaderImpl.ParseDocumentContent(), System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync(), System.Xml.XmlTextReaderImpl.ParseElement(), System.Xml.XmlTextReaderImpl.ParseElementAsync_SetElement(), System.Xml.XmlTextReaderImpl.ParseElementContent(), System.Xml.XmlTextReaderImpl.ParseElementContentAsync(), System.Xml.XmlTextReaderImpl.ParseEndElement(), System.Xml.XmlTextReaderImpl.ParseEndElementAsync_CheckNameAndParse(), System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(), System.Xml.XmlTextReaderImpl.ParseXmlDeclarationAsync(), System.Xml.XmlTextReaderImpl.SkipDtd(), and System.Xml.XmlTextReaderImpl.SkipDtdAsync().