Terraria: System.Xml.XmlConvert.EncodeLocalName
EncodeLocalName()
static ? string System.Xml.XmlConvert.EncodeLocalName (string? name) inline static
Definition at line 49 of file XmlConvert.cs.
    {
        return EncodeName(name, first: true, local: true);
    }
References System.Xml.Dictionary, System.Xml.XmlConvert.EncodeName(), and System.Text.RegularExpressions.name.
Referenced by System.Data.XmlToDatasetMap.AddColumnSchema(), System.Data.XmlTreeGen.AddExtendedProperties(), System.Data.XmlToDatasetMap.BuildIdentityMap(), System.Data.XmlToDatasetMap.BuildIdentityMap(), System.Xml.Serialization.XmlReflectionImporter.CreateArrayElementsFromAttributes(), System.Runtime.Serialization.DataContract.EncodeLocalName(), System.Xml.XmlDataDocument.EnsureDocumentElement(), System.Xml.Serialization.Accessor.EscapeName(), System.Xml.Serialization.Accessor.EscapeQName(), System.Data.XmlTreeGen.FillDataSetElement(), System.Xml.Serialization.XmlCustomFormatter.FromXmlNCName(), System.Xml.Serialization.XmlSerializationWriter.FromXmlQualifiedName(), System.Xml.Serialization.XmlReflectionImporter.GetTopLevelMapping(), System.Data.XmlTreeGen.HandleRelation(), System.Data.XmlTreeGen.HandleTable(), System.Xml.Serialization.SoapReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportAccessorMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportElement(), System.Xml.Serialization.SoapReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportEnumMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportMembersMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportMembersMapping(), System.Xml.Serialization.SoapReflectionImporter.ImportStructLikeMapping(), System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(), System.Data.XmlDataTreeWriter.Save(), System.Data.XmlDataTreeWriter.SaveDiffgramData(), System.Data.XmlTreeGen.SchemaTree(), and System.Xml.Serialization.XmlReflectionImporter.SetArrayMappingType().