Terraria: System.Data.DataViewListener.ColumnCollectionChanged
ColumnCollectionChanged()
void System.Data.DataViewListener.ColumnCollectionChanged (object sender, CollectionChangeEventArgs e) inline private
Definition at line 48 of file DataViewListener.cs.
    {
        DataView dataView = (DataView)_dvWeak.Target;
        if (dataView != null)
        {
            dataView.ColumnCollectionChangedInternal(sender, e);
        }
        else
        {
            CleanUp(updateListeners: true);
        }
    }
References System.Data.DataViewListener._dvWeak, System.Data.DataViewListener.CleanUp(), and System.WeakReference< T >.Target.
Referenced by System.Data.DataViewListener.RegisterMetaDataEvents(), and System.Data.DataViewListener.UnregisterMetaDataEvents().