Terraria: System.Xml.XmlConvert.VerifyQName
VerifyQName()
static string System.Xml.XmlConvert.VerifyQName (string name, ExceptionType exceptionType) inline static package
Definition at line 314 of file XmlConvert.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            throw new ArgumentNullException("name");
        }
        int colonOffset = -1;
        int num = ValidateNames.ParseQName(name, 0, out colonOffset);
        if (num != name.Length)
        {
            throw CreateException(System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(name, num), exceptionType, 0, num + 1);
        }
        return name;
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlConvert.CreateException(), System.Xml.Dictionary, System.Text.RegularExpressions.name, System.Xml.ValidateNames.ParseQName(), and System.SR.Xml_BadNameChar.
Referenced by System.Xml.XmlWellFormedWriter.WriteDocType(), System.Xml.XmlWellFormedWriter.WriteDocTypeAsync(), System.Xml.XmlCharCheckingWriter.WriteName(), System.Xml.XmlWriter.WriteName(), System.Xml.XmlCharCheckingWriter.WriteNameAsync(), and System.Xml.XmlWriter.WriteNameAsync().