Terraria: System.Data.DataViewListener.RegisterMetaDataEvents
RegisterMetaDataEvents()
void System.Data.DataViewListener.RegisterMetaDataEvents (DataTable table) inline package
Definition at line 87 of file DataViewListener.cs.
    {
        _table = table;
        if (table != null)
        {
            RegisterListener(table);
            CollectionChangeEventHandler value = ColumnCollectionChanged;
            table.Columns.ColumnPropertyChanged += value;
            table.Columns.CollectionChanged += value;
            CollectionChangeEventHandler value2 = ChildRelationCollectionChanged;
            ((DataRelationCollection.DataTableRelationCollection)table.ChildRelations).RelationPropertyChanged += value2;
            table.ChildRelations.CollectionChanged += value2;
            CollectionChangeEventHandler value3 = ParentRelationCollectionChanged;
            ((DataRelationCollection.DataTableRelationCollection)table.ParentRelations).RelationPropertyChanged += value3;
            table.ParentRelations.CollectionChanged += value3;
        }
    }
References System.Data.DataViewListener._table, System.Data.DataViewListener.ChildRelationCollectionChanged(), System.Data.DataTable.ChildRelations, System.Data.DataViewListener.ColumnCollectionChanged(), System.Data.DataViewListener.ParentRelationCollectionChanged(), System.Data.DataTable.ParentRelations, System.Data.DataViewListener.RegisterListener(), and System.value.
Referenced by System.Data.DataView.DataView(), System.Data.DataView.DataView(), System.Data.DataView.DataView(), and System.Data.DataView.Open().