Terraria: System.Xml.XmlConvert.ToUInt32
ToUInt32()
static uint System.Xml.XmlConvert.ToUInt32 (string s) inline static
Definition at line 828 of file XmlConvert.cs.
    {
        return uint.Parse(s, NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite, NumberFormatInfo.InvariantInfo);
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, and System.s.
Referenced by System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.UInt32Storage.ConvertXmlToObject(), System.Xml.Linq.XAttribute.operator uint(), System.Xml.Linq.XElement.operator uint(), System.Xml.Linq.XAttribute.operator uint?(), System.Xml.Linq.XElement.operator uint?(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_unsignedInt(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().