Terraria: System.Xml.XmlConvert.ToString
ToString() [1/20]
static string System.Xml.XmlConvert.ToString (bool value) inline static
Definition at line 507 of file XmlConvert.cs.
    {
        if (!value)
        {
            return "false";
        }
        return "true";
    }
References System.value.
Referenced by System.Xml.Schema.XmlBooleanConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlNumeric10Converter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Data.Common.SqlConvert.ChangeType2(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.BooleanStorage.ConvertObjectToXml(), System.Data.Common.ByteStorage.ConvertObjectToXml(), System.Data.Common.CharStorage.ConvertObjectToXml(), System.Data.Common.DateTimeOffsetStorage.ConvertObjectToXml(), System.Data.Common.DateTimeStorage.ConvertObjectToXml(), System.Data.Common.DecimalStorage.ConvertObjectToXml(), System.Data.Common.DoubleStorage.ConvertObjectToXml(), System.Data.Common.Int16Storage.ConvertObjectToXml(), System.Data.Common.Int32Storage.ConvertObjectToXml(), System.Data.Common.Int64Storage.ConvertObjectToXml(), System.Data.Common.SByteStorage.ConvertObjectToXml(), System.Data.Common.SingleStorage.ConvertObjectToXml(), System.Data.Common.TimeSpanStorage.ConvertObjectToXml(), System.Data.Common.UInt16Storage.ConvertObjectToXml(), System.Data.Common.UInt32Storage.ConvertObjectToXml(), System.Data.Common.UInt64Storage.ConvertObjectToXml(), System.Xml.Serialization.ReflectionXmlSerializationWriter.ConvertPrimitiveToString(), System.Xml.Schema.XmlBaseConverter.DecimalToInt32(), System.Xml.Schema.XmlBaseConverter.DecimalToInt64(), System.Xml.Schema.XmlBaseConverter.DecimalToUInt64(), System.Xml.Schema.XmlUntypedStringConverter.DecimalToUInt64(), System.Runtime.Serialization.SchemaExporter.ExportClassDataContract(), System.Runtime.Serialization.SchemaExporter.ExportISerializableDataContract(), System.Runtime.Serialization.SchemaExporter.ExportXmlDataContract(), System.Xml.Serialization.XmlCustomFormatter.FromChar(), System.Xml.Serialization.XmlCustomFormatter.FromDate(), System.Xml.Serialization.XmlCustomFormatter.FromDateTime(), System.Xml.Serialization.XmlCustomFormatter.FromTime(), System.Runtime.Serialization.EnumDataContract.GetStringFromEnumValue(), System.Xml.Linq.XContainer.GetStringValue(), System.Xml.Schema.XmlBaseConverter.Int32ToByte(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToByte(), System.Xml.Schema.XmlBaseConverter.Int32ToInt16(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToInt16(), System.Xml.Schema.XmlBaseConverter.Int32ToSByte(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToSByte(), System.Xml.Schema.XmlBaseConverter.Int32ToUInt16(), System.Xml.Schema.XmlUntypedStringConverter.Int32ToUInt16(), System.Xml.Schema.XmlBaseConverter.Int64ToInt32(), System.Xml.Schema.XmlBaseConverter.Int64ToUInt32(), System.Xml.Schema.XmlUntypedStringConverter.Int64ToUInt32(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.Schema.XsdDuration.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.Schema.XmlNumeric2Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.Schema.XmlBooleanConverter.ToString(), System.Xml.Schema.XmlNumeric10Converter.ToString(), System.Xml.Schema.XmlUntypedConverter.ToString(), System.Xml.XmlConverter.ToString(), System.Xml.XmlSqlBinaryReader.ValueAsString(), System.Xml.Serialization.SchemaObjectWriter.Write35_XmlSchemaComplexType(), System.Xml.Serialization.SchemaObjectWriter.Write41_XmlSchemaComplexContent(), System.Xml.Serialization.SchemaObjectWriter.Write43_XmlSchemaAll(), System.Xml.Serialization.SchemaObjectWriter.Write46_XmlSchemaElement(), System.Xml.Serialization.SchemaObjectWriter.Write52_XmlSchemaChoice(), System.Xml.Serialization.SchemaObjectWriter.Write53_XmlSchemaAny(), System.Xml.Serialization.SchemaObjectWriter.Write54_XmlSchemaSequence(), System.Xml.Serialization.SchemaObjectWriter.Write55_XmlSchemaGroupRef(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_boolean(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_byte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_dateTimeOffset(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_decimal(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_double(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_float(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_guid(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_int(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_long(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_short(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_TimeSpan(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedByte(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedInt(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedLong(), System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_unsignedShort(), System.Xml.Serialization.SchemaObjectWriter.Write_XmlSchemaFacet(), System.Runtime.Serialization.Json.JsonWriterDelegator.WriteChar(), System.Runtime.Serialization.XmlWriterDelegator.WriteDateTime(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Runtime.Serialization.XmlWriterDelegator.WriteTimeSpan(), System.Xml.XmlUTF8NodeWriter.WriteTimeSpanText(), System.Xml.Serialization.XmlSerializationWriter.WriteTypedPrimitive(), System.Runtime.Serialization.XmlWriterDelegator.WriteUnsignedLong(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.Linq.XNodeBuilder.WriteValue(), System.Xml.XmlRawWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlWriter.WriteValue(), System.Xml.XmlDictionaryWriter.WriteValue(), System.Data.SqlTypes.SqlByte.WriteXml(), System.Data.SqlTypes.SqlDateTime.WriteXml(), System.Data.SqlTypes.SqlDouble.WriteXml(), System.Data.SqlTypes.SqlGuid.WriteXml(), System.Data.SqlTypes.SqlInt16.WriteXml(), System.Data.SqlTypes.SqlInt32.WriteXml(), System.Data.SqlTypes.SqlInt64.WriteXml(), System.Data.SqlTypes.SqlMoney.WriteXml(), and System.Data.SqlTypes.SqlSingle.WriteXml().