Terraria: System.Xml.XmlConvert.ToDecimal
ToDecimal()
static decimal System.Xml.XmlConvert.ToDecimal (string s) inline static
Definition at line 713 of file XmlConvert.cs.
    {
        return decimal.Parse(s, NumberStyles.Integer | NumberStyles.AllowDecimalPoint, NumberFormatInfo.InvariantInfo);
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, and System.s.
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.DecimalStorage.ConvertXmlToObject(), System.Xml.Schema.XmlUntypedStringConverter.FromString(), System.Xml.Linq.XAttribute.operator decimal(), System.Xml.Linq.XElement.operator decimal(), System.Xml.Linq.XAttribute.operator decimal?(), System.Xml.Linq.XElement.operator decimal?(), System.Xml.Schema.Datatype_fixed.ParseValue(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_decimal(), System.Xml.XmlReader.ReadContentAsDecimal(), System.Xml.XmlSqlBinaryReader.ReadContentAsDecimal(), System.Xml.XmlReader.ReadElementContentAsDecimal(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Data.SqlTypes.SqlMoney.ReadXml(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.XmlConverter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToDecimal(), System.Xml.Schema.XmlUntypedConverter.ToDecimal(), System.Xml.Schema.XmlNumeric10Converter.ToInt32(), System.Xml.Schema.XmlNumeric10Converter.ToInt64(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().