Terraria: System.Xml.XmlConvert.TryToBoolean
TryToBoolean()
static Exception System.Xml.XmlConvert.TryToBoolean (string s, out bool result) inline static package
Definition at line 672 of file XmlConvert.cs.
    {
        s = TrimString(s);
        switch (s)
        {
        case "0":
        case "false":
            result = false;
            return null;
        case "1":
        case "true":
            result = true;
            return null;
        default:
            result = false;
            return new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Boolean"));
        }
    }
References System.SR.Format(), System.s, System.Xml.XmlConvert.TrimString(), and System.SR.XmlConvert_BadFormat.
Referenced by System.Xml.Schema.Datatype_boolean.TryParseValue().