Terraria: System.Xml.XmlConvert.EscapeValueForDebuggerDisplay
EscapeValueForDebuggerDisplay()
static string System.Xml.XmlConvert.EscapeValueForDebuggerDisplay (string value) inline static package
Definition at line 1330 of file XmlConvert.cs.
    {
        StringBuilder stringBuilder = null;
        int i = 0;
        int num = 0;
        for (; i < value.Length; i++)
        {
            char c = value[i];
            if (c < ' ' || c == '"')
            {
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(value.Length + 4);
                }
                if (i - num > 0)
                {
                    stringBuilder.Append(value, num, i - num);
                }
                num = i + 1;
                switch (c)
                {
                case '"':
                    stringBuilder.Append("\\\"");
                    break;
                case '\r':
                    stringBuilder.Append("\\r");
                    break;
                case '\n':
                    stringBuilder.Append("\\n");
                    break;
                case '\t':
                    stringBuilder.Append("\\t");
                    break;
                default:
                    stringBuilder.Append(c);
                    break;
                }
            }
        }
        if (stringBuilder == null)
        {
            return value;
        }
        if (i - num > 0)
        {
            stringBuilder.Append(value, num, i - num);
        }
        return stringBuilder.ToString();
    }
References System.Xml.Dictionary, System.Text.RegularExpressions.i, and System.value.
Referenced by System.Xml.XPath.XPathNavigator.DebuggerDisplayProxy.ToString(), System.Xml.XmlNode.DebuggerDisplayXmlNodeProxy.ToString(), and System.Xml.XmlReader.XmlReaderDebuggerDisplayProxy.ToString().