Terraria: System.Xml.XmlConvert.TryVerifyName
TryVerifyName()
static Exception System.Xml.XmlConvert.TryVerifyName (string name) inline static package
Definition at line 300 of file XmlConvert.cs.
    {
        if (string.IsNullOrEmpty(name))
        {
            return new XmlException(System.SR.Xml_EmptyName, string.Empty);
        }
        int num = ValidateNames.ParseNameNoNamespaces(name, 0);
        if (num != name.Length)
        {
            return new XmlException((num == 0) ? System.SR.Xml_BadStartNameChar : System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(name, num));
        }
        return null;
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Text.RegularExpressions.name, System.Xml.ValidateNames.ParseNameNoNamespaces(), System.SR.Xml_BadNameChar, System.SR.Xml_BadStartNameChar, System.SR.Xml_EmptyName, and System.Xml.XmlException.
Referenced by System.Xml.Schema.StringFacetsChecker.CheckBuiltInFacets().