Terraria: System.Xml.XmlConvert.ToDouble
ToDouble()
static double System.Xml.XmlConvert.ToDouble (string s) inline static
Definition at line 900 of file XmlConvert.cs.
    {
        s = TrimString(s);
        if (s == "-INF")
        {
            return double.NegativeInfinity;
        }
        if (s == "INF")
        {
            return double.PositiveInfinity;
        }
        double num = double.Parse(s, NumberStyles.Float, NumberFormatInfo.InvariantInfo);
        if (num == 0.0 && s[0] == '-')
        {
            return -0.0;
        }
        return num;
    }
References System.Globalization.NumberFormatInfo.InvariantInfo, System.s, and System.Xml.XmlConvert.TrimString().
Referenced by System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Xml.Schema.XmlUntypedConverter.ChangeType(), System.Data.Common.SqlConvert.ChangeTypeForXML(), System.Data.Common.DoubleStorage.ConvertXmlToObject(), System.Xml.Schema.XmlUntypedStringConverter.FromString(), System.Xml.Linq.XAttribute.operator double(), System.Xml.Linq.XElement.operator double(), System.Xml.Linq.XAttribute.operator double?(), System.Xml.Linq.XElement.operator double?(), System.Xml.Schema.Datatype_doubleXdr.ParseValue(), System.Xml.Serialization.XmlSerializationPrimitiveReader.Read_double(), System.Xml.XmlReader.ReadContentAsDouble(), System.Xml.XmlSqlBinaryReader.ReadContentAsDouble(), System.Xml.XmlReader.ReadElementContentAsDouble(), System.Xml.Serialization.XmlSerializationReader.ReadTypedPrimitive(), System.Data.SqlTypes.SqlDouble.ReadXml(), System.Xml.Schema.XmlSchemaInference.RefineSimpleType(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.XmlConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToDouble(), System.Xml.Schema.XmlUntypedConverter.ToDouble(), System.Xml.Schema.XmlNumeric2Converter.ToSingle(), and System.Xml.Serialization.ReflectionXmlSerializationReader.WritePrimitive().