Terraria: System.Data.DataViewListener.UnregisterMetaDataEvents
UnregisterMetaDataEvents() [2/2]
void System.Data.DataViewListener.UnregisterMetaDataEvents (bool updateListeners) inline private
Definition at line 110 of file DataViewListener.cs.
    {
        DataTable table = _table;
        _table = null;
        if (table == null)
        {
            return;
        }
        CollectionChangeEventHandler value = ColumnCollectionChanged;
        table.Columns.ColumnPropertyChanged -= value;
        table.Columns.CollectionChanged -= value;
        CollectionChangeEventHandler value2 = ChildRelationCollectionChanged;
        ((DataRelationCollection.DataTableRelationCollection)table.ChildRelations).RelationPropertyChanged -= value2;
        table.ChildRelations.CollectionChanged -= value2;
        CollectionChangeEventHandler value3 = ParentRelationCollectionChanged;
        ((DataRelationCollection.DataTableRelationCollection)table.ParentRelations).RelationPropertyChanged -= value3;
        table.ParentRelations.CollectionChanged -= value3;
        if (updateListeners)
        {
            List<DataViewListener> listeners = table.GetListeners();
            lock (listeners)
            {
                listeners.Remove(this);
            }
        }
    }
References System.Data.DataViewListener._table, System.Data.DataViewListener.ChildRelationCollectionChanged(), System.Data.DataTable.ChildRelations, System.Data.DataViewListener.ColumnCollectionChanged(), System.Data.DataTable.GetListeners(), System.Data.DataViewListener.ParentRelationCollectionChanged(), System.Data.DataTable.ParentRelations, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.value.