Terraria: System.Xml.XmlConvert.VerifyCharData
VerifyCharData() [2/3]
static void System.Xml.XmlConvert.VerifyCharData (string data, ExceptionType exceptionType) inline static package
Definition at line 1247 of file XmlConvert.cs.
    {
        VerifyCharData(data, exceptionType, exceptionType);
    }
References System.Xml.Dictionary, and System.Xml.XmlConvert.VerifyCharData().
Referenced by System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.Xml.XmlCharCheckingWriter.CheckCharacters(), System.Xml.XmlCharCheckingReader.CheckCharacters(), System.Xml.XmlSqlBinaryReader.ScanOverAnyValue(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyXmlChars(), System.Xml.DocumentXmlWriter.WriteCData(), System.Xml.DocumentXmlWriter.WriteComment(), System.Xml.DocumentXmlWriter.WriteProcessingInstruction(), System.Xml.DocumentXmlWriter.WriteString(), and System.Xml.DocumentXmlWriter.WriteWhitespace().