Terraria: System.Xml.XmlConvert.XPathRound
XPathRound()
static double System.Xml.XmlConvert.XPathRound (double value) inline static package
Definition at line 1003 of file XmlConvert.cs.
    {
        double num = Math.Round(value);
        if (value - num != 0.5)
        {
            return num;
        }
        return num + 1.0;
    }
References System.Math.Round(), and System.value.
Referenced by System.Xml.Xsl.XsltOld.NumberAction.NumberingFormat.FormatItem(), MS.Internal.Xml.XPath.NumberFunctions.Round(), and MS.Internal.Xml.XPath.StringFunctions.Substring().