Terraria: System.Xml.XmlConvert.ToBinHexString
ToBinHexString()
static string System.Xml.XmlConvert.ToBinHexString (byte[] inArray) inline static package
Definition at line 273 of file XmlConvert.cs.
    {
        if (inArray == null)
        {
            throw new ArgumentNullException("inArray");
        }
        return BinHexEncoder.Encode(inArray, 0, inArray.Length);
    }
References System.Xml.Dictionary, and System.Xml.BinHexEncoder.Encode().
Referenced by System.Xml.Serialization.XmlCustomFormatter.FromByteArrayHex(), and System.Xml.Schema.XmlMiscConverter.ToString().