Terraria: System.Xml.XmlConvert.CreateInvalidNameCharException
CreateInvalidNameCharException()
static Exception System.Xml.XmlConvert.CreateInvalidNameCharException (string name, int index, ExceptionType exceptionType) inline static package
Definition at line 1482 of file XmlConvert.cs.
    {
        return CreateException((index == 0) ? System.SR.Xml_BadStartNameChar : System.SR.Xml_BadNameChar, XmlException.BuildCharExceptionArgs(name, index), exceptionType, 0, index + 1);
    }
References System.Xml.XmlException.BuildCharExceptionArgs(), System.Xml.XmlConvert.CreateException(), System.Xml.Dictionary, System.index, System.Text.RegularExpressions.name, System.SR.Xml_BadNameChar, and System.SR.Xml_BadStartNameChar.
Referenced by System.Xml.XmlConvert.VerifyName(), and System.Xml.XmlConvert.VerifyNCName().