Terraria: System.Xml.XmlConvert.TryToDouble
TryToDouble()
static Exception System.Xml.XmlConvert.TryToDouble (string s, out double result) inline static package
Definition at line 919 of file XmlConvert.cs.
    {
        s = TrimString(s);
        if (s == "-INF")
        {
            result = double.NegativeInfinity;
            return null;
        }
        if (s == "INF")
        {
            result = double.PositiveInfinity;
            return null;
        }
        if (!double.TryParse(s, NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint | NumberStyles.AllowExponent, NumberFormatInfo.InvariantInfo, out result))
        {
            return new FormatException(System.SR.Format(System.SR.XmlConvert_BadFormat, s, "Double"));
        }
        if (result == 0.0 && s[0] == '-')
        {
            result = -0.0;
        }
        return null;
    }
References System.Xml.Dictionary, System.SR.Format(), System.Globalization.NumberFormatInfo.InvariantInfo, System.s, System.Xml.XmlConvert.TrimString(), and System.SR.XmlConvert_BadFormat.
Referenced by System.Xml.Xsl.Runtime.XsltFunctions.MSNumber(), and System.Xml.Schema.Datatype_double.TryParseValue().