Terraria: System.Xml.XmlConvert.VerifyNCName
VerifyNCName() [1/2]
static string System.Xml.XmlConvert.VerifyNCName (string name) inline static
Definition at line 329 of file XmlConvert.cs.
    {
        return VerifyNCName(name, ExceptionType.XmlException);
    }
References System.Text.RegularExpressions.name, and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Xml.Linq.XName.XName(), System.Xml.Serialization.XmlSerializerNamespaces.Add(), System.Runtime.Serialization.DataContract.IsValidNCName(), System.Xml.Schema.Preprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Linq.XProcessingInstruction.ValidateName(), System.Xml.XmlQualifiedName.Verify(), System.Xml.XmlConvert.VerifyNCName(), and System.Xml.XmlUTF8TextReader.VerifyNCName().