Terraria: System.Xml.XmlConvert.ToString
ToString() [6/20]
static string System.Xml.XmlConvert.ToString (DateTime value, XmlDateTimeSerializationMode dateTimeOption) inline static
Definition at line 620 of file XmlConvert.cs.
    {
        switch (dateTimeOption)
        {
        case XmlDateTimeSerializationMode.Local:
            value = SwitchToLocalTime(value);
            break;
        case XmlDateTimeSerializationMode.Utc:
            value = SwitchToUtcTime(value);
            break;
        case XmlDateTimeSerializationMode.Unspecified:
            value = new DateTime(value.Ticks, DateTimeKind.Unspecified);
            break;
        default:
            throw new ArgumentException(System.SR.Format(System.SR.Sch_InvalidDateTimeOption, dateTimeOption, "dateTimeOption"));
        case XmlDateTimeSerializationMode.RoundtripKind:
            break;
        }
        return new XsdDateTime(value, XsdDateTimeFlags.DateTime).ToString();
    }
References System.Xml.ArgumentException, System.Xml.DateTime, System.Xml.Dictionary, System.SR.Format(), System.SR.Sch_InvalidDateTimeOption, System.Xml.XmlConvert.SwitchToLocalTime(), System.Xml.XmlConvert.SwitchToUtcTime(), System.Xml.Schema.XsdDateTime.ToString(), and System.value.