Terraria: System.Xml.XmlConvert.CreateInvalidNameArgumentException
CreateInvalidNameArgumentException()
static ArgumentException System.Xml.XmlConvert.CreateInvalidNameArgumentException (string name, string argumentName) inline static package
Definition at line 1487 of file XmlConvert.cs.
    {
        if (name != null)
        {
            return new ArgumentException(System.SR.Xml_EmptyName, argumentName);
        }
        return new ArgumentNullException(argumentName);
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, System.Text.RegularExpressions.name, and System.SR.Xml_EmptyName.
Referenced by System.Xml.XmlReader.CheckElement(), System.Xml.DtdParser.InitializeFreeFloatingDtd(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToDescendant(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToFollowing(), System.Xml.XmlReader.ReadToNextSibling(), and System.Xml.XmlReader.ReadToNextSibling().