Terraria: System.Xml.XmlConvert.CreateException
CreateException() [1/5]
static Exception System.Xml.XmlConvert.CreateException (string res, ExceptionType exceptionType, int lineNo, int linePos) inline static package
Definition at line 1380 of file XmlConvert.cs.
    {
        return exceptionType switch
        {
            ExceptionType.ArgumentException => new ArgumentException(res),
            _ => new XmlException(res, string.Empty, lineNo, linePos),
        };
    }
References System.Xml.ArgumentException, System.Xml.Dictionary, and System.Xml.XmlException.
Referenced by System.Xml.XmlConvert.CreateException(), System.Xml.XmlConvert.CreateException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidCharException(), System.Xml.XmlConvert.CreateInvalidHighSurrogateCharException(), System.Xml.XmlConvert.CreateInvalidNameCharException(), System.Xml.XmlConvert.CreateInvalidSurrogatePairException(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyCharData(), System.Xml.XmlConvert.VerifyNMTOKEN(), and System.Xml.XmlConvert.VerifyQName().