Terraria: System.Data.DataViewListener.CleanUp
CleanUp()
void System.Data.DataViewListener.CleanUp (bool updateListeners) inline private
Definition at line 168 of file DataViewListener.cs.
    {
        UnregisterMetaDataEvents(updateListeners);
        UnregisterListChangedEvent();
    }
References System.Data.DataViewListener.UnregisterListChangedEvent(), and System.Data.DataViewListener.UnregisterMetaDataEvents().
Referenced by System.Data.DataViewListener.ChildRelationCollectionChanged(), System.Data.DataViewListener.ColumnCollectionChanged(), System.Data.DataViewListener.IndexListChanged(), System.Data.DataViewListener.MaintainDataView(), and System.Data.DataViewListener.ParentRelationCollectionChanged().