Terraria: System.Collections.Immutable.ImmutableSortedDictionary.AddRange
AddRange() [2/3]
ImmutableSortedDictionary< TKey, TValue > System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.AddRange (IEnumerable< KeyValuePair< TKey, TValue > > items, bool overwriteOnCollision, bool avoidToSortedMap) inline private
Definition at line 1404 of file ImmutableSortedDictionary.cs.
    {
        Requires.NotNull(items, "items");
        if (IsEmpty && !avoidToSortedMap)
        {
            return FillFromEmpty(items, overwriteOnCollision);
        }
        Node node = _root;
        int num = _count;
        foreach (KeyValuePair<TKey, TValue> item in items)
        {
            bool replacedExistingValue = false;
            bool mutated;
            Node node2 = (overwriteOnCollision ? node.SetItem(item.Key, item.Value, _keyComparer, _valueComparer, out replacedExistingValue, out mutated) : node.Add(item.Key, item.Value, _keyComparer, _valueComparer, out mutated));
            if (mutated)
            {
                node = node2;
                if (!replacedExistingValue)
                {
                    num++;
                }
            }
        }
        return Wrap(node, num);
    }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._count, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._keyComparer, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._root, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._valueComparer, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.FillFromEmpty(), System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.IsEmpty, System.item, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Wrap().