Terraria: System.Collections.Immutable.ImmutableSortedDictionary.FillFromEmpty
FillFromEmpty()
ImmutableSortedDictionary< TKey, TValue > System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.FillFromEmpty (IEnumerable< KeyValuePair< TKey, TValue > > items, bool overwriteOnCollision) inline private
Definition at line 1443 of file ImmutableSortedDictionary.cs.
    {
        Requires.NotNull(items, "items");
        if (TryCastToImmutableMap(items, out var other))
        {
            return other.WithComparers(KeyComparer, ValueComparer);
        }
        SortedDictionary<TKey, TValue> sortedDictionary;
        if (items is IDictionary<TKey, TValue> dictionary)
        {
            sortedDictionary = new SortedDictionary<TKey, TValue>(dictionary, KeyComparer);
        }
        else
        {
            sortedDictionary = new SortedDictionary<TKey, TValue>(KeyComparer);
            foreach (KeyValuePair<TKey, TValue> item in items)
            {
                TValue value;
                if (overwriteOnCollision)
                {
                    sortedDictionary[item.Key] = item.Value;
                }
                else if (sortedDictionary.TryGetValue(item.Key, out value))
                {
                    if (!_valueComparer.Equals(value, item.Value))
                    {
                        throw new ArgumentException(System.SR.Format(System.SR.DuplicateKey, item.Key));
                    }
                }
                else
                {
                    sortedDictionary.Add(item.Key, item.Value);
                }
            }
        }
        if (sortedDictionary.Count == 0)
        {
            return this;
        }
        Node root = Node.NodeTreeFromSortedDictionary(sortedDictionary);
        return new ImmutableSortedDictionary<TKey, TValue>(root, sortedDictionary.Count, KeyComparer, ValueComparer);
    }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._valueComparer, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.dictionary, System.SR.DuplicateKey, System.Collections.IEqualityComparer.Equals(), System.SR.Format(), System.item, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.KeyComparer, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Node.NodeTreeFromSortedDictionary(), System.other, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.TryCastToImmutableMap(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), System.value, and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.ValueComparer.
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.AddRange().