Terraria: System.Collections.Immutable.ImmutableSortedDictionary.RemoveRange
RemoveRange() [1/2]
ImmutableSortedDictionary< TKey, TValue > System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.RemoveRange (IEnumerable< TKey > keys) inline
Implements System.Collections.Immutable.IImmutableDictionary< TKey, TValue >.
Definition at line 1190 of file ImmutableSortedDictionary.cs.
    {
        Requires.NotNull(keys, "keys");
        Node node = _root;
        int num = _count;
        foreach (TKey key in keys)
        {
            bool mutated;
            Node node2 = node.Remove(key, _keyComparer, out mutated);
            if (mutated)
            {
                node = node2;
                num--;
            }
        }
        return Wrap(node, num);
    }
References System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._count, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._keyComparer, System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >._root, System.key, System.keys, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.Wrap().
Referenced by System.Collections.Immutable.ImmutableSortedDictionary< TKey, TValue >.RemoveRange().