Terraria: UnifiedRandom.Next
Next() [1/3]
virtual int UnifiedRandom.Next () inline virtual
     {
         return InternalSample();
     }
References InternalSample().
Referenced by InGamePopups.PlayerWantsToJoinGamePopup.PlayerWantsToJoinGamePopup(), WoodHouseBuilder.WoodHouseBuilder(), SolarSky.Activate(), StardustSky.Activate(), Cloud.addCloud(), MoonlordDeathDrama.AddExplosion(), GameTipsDisplay.AddNewTip(), DesertHive.AddTileVariance(), WoodHouseBuilder.AgeRoom(), NPC.AI(), Projectile.AI(), Projectile.AI_001(), NPC.AI_001_Slimes(), NPC.AI_001_Slimes_GenerateItemInsideBody(), NPC.AI_002_FloatingEye(), NPC.AI_003_Fighters(), NPC.AI_005_EaterOfSouls(), NPC.AI_006_Worms(), NPC.AI_007_AttemptToPlayIdleAnimationsForPets(), Projectile.AI_007_GrapplingHooks(), NPC.AI_007_TownEntities(), NPC.AI_007_TryForcingSitting(), Projectile.AI_009_MagicMissiles(), Projectile.AI_009_MagicMissiles_Old(), Projectile.AI_010(), Projectile.AI_015_Flails_Dust(), Projectile.AI_016(), Projectile.AI_019_Spears(), Projectile.AI_019_Spears_Old(), Projectile.AI_026(), NPC.AI_026_Unicorns(), NPC.AI_037_Destroyer(), NPC.AI_045_Golem(), NPC.AI_047_GolemFist(), Projectile.AI_047_MagnetSphere_TryAttacking(), Projectile.AI_061_FishingBobber(), Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Projectile.AI_062(), NPC.AI_065_Butterflies(), Projectile.AI_067_FreakingPirates(), Projectile.AI_067_TigerSpecialAttack(), NPC.AI_069_DukeFishron(), Projectile.AI_075(), NPC.AI_084_LunaticCultist(), Projectile.AI_099_2(), Projectile.AI_100_Medusa(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), NPC.AI_109_DarkMage(), NPC.AI_110_Betsy(), NPC.AI_111_DD2LightningBug(), Projectile.AI_111_DryadsWard(), NPC.AI_112_FairyCritter(), NPC.AI_113_WindyBalloon(), NPC.AI_114_Dragonflies(), NPC.AI_115_LadyBugs(), NPC.AI_116_WaterStriders(), NPC.AI_117_BloodNautilus(), NPC.AI_118_Seahorses(), NPC.AI_119_Dandelion(), NPC.AI_120_HallowBoss_DoMagicEffect(), NPC.AI_121_QueenSlime(), Projectile.AI_121_StardustDragon(), NPC.AI_123_Deerclops_ShootRubbleUp(), Projectile.AI_130_FlameBurstTower(), Projectile.AI_131_FlameBurstShot(), Projectile.AI_135_OgreStomp(), Projectile.AI_136_BetsyBreath(), Projectile.AI_137_LightningAura(), Projectile.AI_140_MonkStaffT1(), Projectile.AI_142_MonkStaffT2And3(), Projectile.AI_144_DD2Pet(), Projectile.AI_145_BookStaffStorm(), Projectile.AI_147_Explosion(), Projectile.AI_151_SuperStar(), Projectile.AI_152_SuperStarSlash(), Projectile.AI_153_ToiletPop(), Projectile.AI_155_MysticSnakeCoil(), Projectile.AI_155_SpawnRopeIn(), Projectile.AI_156_Think(), Projectile.AI_157_SharpTears(), Projectile.AI_159_PaperAirplanes(), Projectile.AI_160_Kites(), Projectile.AI_162_TigerPounce(), Projectile.AI_163_Chum(), Projectile.AI_165_Whip(), Projectile.AI_166_Dove(), Projectile.AI_168_FirstFractal(), Projectile.AI_169_Smolstars(), Projectile.AI_175_TitaniumStormShards(), Projectile.AI_176_EdgyLightning(), Projectile.AI_177_IceWhipSlicer(), Projectile.AI_178_FireExplosion(), Projectile.AI_179_FairyQueenLance(), Projectile.AI_181_FairyQueenRangedItemShot(), Projectile.AI_184_BadTorchLuck(), Projectile.AI_186_PrincessWeapon(), Projectile.AI_189_Volcano(), Projectile.AI_190_NightsEdge(), Projectile.AI_191_TrueNightsEdge(), Projectile.AI_192_JuminoAnimation(), Projectile.AI_193_Flamethrower(), Projectile.AI_194_HorsemanPumpkin(), Projectile.AI_195_JimsDrone(), NPC.AI_87_BigMimic_FireStuffCannonBurst(), NPC.AI_87_BigMimic_ShootItem(), NPC.AI_AttemptToFindTeleportSpot(), Main.AnglerQuestSwap(), Main.AnimateTiles(), Main.AnimateTiles_CritterCages(), ActionPlaceStatue.Apply(), ActionVines.Apply(), Modifiers.Blotches.Apply(), Player.ApplyEquipFunctional(), Player.ApplyLifeAndOrMana(), Player.ApplyNPCOnHitEffects(), JunglePass.ApplyPass(), TerrainPass.ApplyPass(), Passes.ScatterCustom.ApplyPass(), Player.ApplyPotionDelay(), JunglePass.ApplyRandomMovement(), Player.ApplyTouchDamage(), Player.ApplyWilsonBeard(), Player.ArmorSetDye(), MartianSky.Ufo.AssignNewBehavior(), UIWorldCreation.AssignRandomWorldName(), UIWorldCreation.AssignRandomWorldSeed(), DesertHive.ClusterGroup.AttemptClaim(), Lang.BartenderChat(), Player.beeDamage(), Player.beeType(), NPC.BloodNautilus_CallForHelp(), PlayerDrawSet.BoringSetup(), Projectile.BoulderExplosion(), Conditions.FrostMoonDropGateForTrophies.CanDrop(), Conditions.PumpkinMoonDropGateForTrophies.CanDrop(), TileObject.CanPlace(), Main.ChangeRain(), Sandstorm.ChangeSeverityIntentions(), WorldGen.Check3x2(), WorldGen.CheckChand(), Player.CheckCrackedBrickBreak(), NPC.checkDead(), NPC.CheckDrowning(), Player.CheckDrowning(), Player.CheckForGoodTeleportationSpot(), Item.CheckLavaDeath(), WorldGen.CheckOrb(), SpelunkerProjectileHelper.CheckSpot(), HitTile.HitTileObject.Clear(), UICharacterCreation.Click_RandomizePlayer(), NPC.Collision_WaterCollision(), WorldGen.ConvertSkyIslands(), ParticleOrchestrator.CopperSlimeEffect(), Recipe.Create(), DD2Film.CreateCritters(), Lang.CreateDeathMessage(), DesertDescription.CreateFromPlacement(), DunesBiome.DunesDescription.CreateFromPlacement(), Projectile.CreateGroundExplosion(), HiveBiome.CreateHiveTunnel(), Projectile.Damage(), Main.DamageVar(), Player.DashMovement(), Main.DedServ(), Item.DespawnIfMeetingConditions(), DD2Event.Difficulty_1_SpawnMonsterFromGate(), DD2Event.Difficulty_2_SpawnMonsterFromGate(), DD2Event.Difficulty_3_SpawnMonsterFromGate(), Player.DoBootsEffect_PlaceFlowersOnTile(), Mount.DoConfettiMinecartEffect(), NPC.DoDeathEvents(), NPC.DoDeathEvents_DropBossPotionsAndHearts(), Mount.DoExhaustMinecartEffect(), Player.DoEyebrellaRainEffect(), Mount.DoGemMinecartEffect(), Projectile.DoRainbowCrystalStaffExplosion(), Mount.DoSpawnDust(), Player.DoubleJumpVisuals(), Main.DoUpdate(), GameTipsDisplay.Draw(), Mount.Draw(), TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), TileDrawing.DrawAnyDirectionalGrass(), PlayerDrawLayers.DrawCompositeArmorPiece(), TileDrawing.DrawGrass(), Main.DrawItem(), Main.DrawMenu(), TileDrawing.DrawMultiTileGrassInWind(), TileDrawing.DrawMultiTileVinesInWind(), Main.DrawNPCDirect(), PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), PlayerDrawLayers.DrawPlayer_09_Wings(), PlayerDrawLayers.DrawPlayer_13_Leggings(), PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), PlayerDrawLayers.DrawPlayer_21_Head(), LegacyPlayerRenderer.DrawPlayerFull(), Main.DrawProjDirect(), UIGenProgressBar.DrawSelf(), UIWorldLoad.DrawSelf(), TileDrawing.DrawSingleTile(), PlayerDrawLayers.DrawSittingLegs(), Main.DrawSunAndMoon(), Main.DrawSurfaceBG_Mushroom(), TileDrawing.DrawTeleportationPylons(), TileDrawing.DrawTiles_EmitParticles(), TileDrawing.DrawTrees(), TileDrawing.DrawVineStrip(), Player.DropCoins(), Projectile.DropGeodeGems(), CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), CommonCode.DropItemFromNPC(), WorldGen.dropMeteor(), Player.DropTombstone(), NPC.DropTombstoneTownNPC(), DD2Film.DryadPortalFade(), Lang.DyeTraderQuestChat(), ParticleOrchestrator.ElderSlimeEffect(), TileDrawing.EmitAlchemyHerbParticles(), Sandstorm.EmitDust(), Projectile.EmitEnchantmentVisualsAt(), GolfHelper.ContactListener.EmitGolfballExplosion(), Mount.EmitGolfCartWheelDust(), TileDrawing.EmitLiquidDrops(), TileDrawing.EmitLivingTreeLeaf(), Player.EmitMaxManaEffect(), TileDrawing.EmitTreeLeaves(), Player.ExtractinatorUse(), NPC.FairyEffects(), Star.Fall(), GasParticle.FetchFromPool(), HouseBuilder.FillRooms(), DeadMansChestBiome.FindBoulderTrapSpots(), NPC.FindCattailTop(), DeadMansChestBiome.FindDartTrapSpots(), DeadMansChestBiome.FindExplosiveTrapSpots(), NPC.FindFrame(), AmbienceServer.FindPlayerThatCanSeeBackgroundAmbience(), Player.FindSharpTearsSpot(), NPC.FindTreeBranch(), WorldGen.FinishRemixWorld(), Projectile.FishingCheck(), Projectile.FishingCheck_RollDropLevels(), Projectile.FishingCheck_RollEnemySpawns(), Projectile.FishingCheck_RollItemDrop(), WorldGen.Spread.Gem(), WorldGen.gemCave(), DesertHive.ClusterGroup.Generate(), PartySky.GenerateBalloons(), JunglePass.GenerateFinishingTouches(), JunglePass.GenerateHolesInMudWalls(), LanternSky.GenerateLanterns(), SlimeSky.GenerateSlimes(), JunglePass.GenerateTunnelToSurface(), WorldGen.GenerateWorld(), TerrainPass.GenerateWorldSurfaceOffset(), Player.GetAnglerReward_Bait(), Player.GetAnglerReward_Decoration(), Player.GetAnglerReward_MainReward(), Player.GetAnglerReward_Money(), NPC.GetChat(), Player.GetDyeTraderReward(), WorldGen.GetNextJungleChestItem(), Item.GetPickedUpByMonsters_Money(), WorldGenRange.GetRandom(), FlexibleTileWand.OptionBucket.GetRandomOption(), FinalFractalHelper.GetRandomProfileIndex(), CustomSoundStyle.GetRandomSound(), Item.GetShimmered(), NPC.GetStackForSlimeItemDrop(), Projectile.ghostHurt(), LucyAxeMessage.GiveIdleMessageCooldown(), Main.GUIChatDrawInner(), Projectile.HandleMovement(), WorldGen.hardUpdateWorld(), NPC.HasLuckTextForWizard(), NPC.HasSpecialEventText(), NPC.HitEffect(), Wiring.HitWireSingle(), Player.HorizontalMovement(), Player.HorsemansBlade_SpawnPumpkin(), Player.Hurt(), NPC.IdleSounds(), Main.Initialize(), MartianSky.ZipBehavior.InitializeUfo(), MartianSky.HoverBehavior.InitializeUfo(), LiquidRenderer.InternalPrepareDraw(), Player.ItemCheck(), Player.ItemCheck_ApplyHoldStyle(), Player.ItemCheck_ApplyPetBuffs(), Player.ItemCheck_ApplyUseStyle(), Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait(), Player.ItemCheck_CheckFishingBobber_PullBobber(), Player.ItemCheck_CutTiles(), Player.ItemCheck_EmitDrinkParticles(), Player.ItemCheck_EmitFoodParticles(), Player.ItemCheck_EmitHeldItemLight(), Player.ItemCheck_EmitUseVisuals(), Player.ItemCheck_GetMeleeHitbox(), Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Player.ItemCheck_MeleeHitPVP(), Player.ItemCheck_Shoot(), Player.ItemCheck_UseTeleportRod(), Player.JumpMovement(), Projectile.Kill(), Player.KillMe(), WorldGen.KillTile_GetItemDrops(), WorldGen.KillTile_GetTreeDrops(), WorldGen.KillTile_MakeTileDust(), WorldGen.KillTile_ShouldDropSeeds(), WorldGen.LaunchRocketSmall(), WorldFile.LoadHeader(), AssetInitializer.LoadSplashAssets(), WorldFile.LoadWorld(), WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Player.MakeFloorDust(), Rain.MakeRain(), NPC.MakeTransitionEffectsForTextureChanges(), WorldGen.MarblePileWithStatues(), WorldGen.mayanTrap(), WorldGen.meteor(), Player.ModifyFlexibleWandPlacementInfo(), AllPersonalitiesModifier.ModifyShopPrice_Relationships(), Item.MoveInWorld(), BirthdayParty.NaturalAttempt(), LanternNight.NaturalAttempt(), WorldGen.neonMossBiome(), Dust.NewDust(), Gore.NewGore(), Item.NewItem(), Main.NewLightning(), NPC.NewNPC(), Projectile.NewProjectile(), Rain.NewRain(), Rain.NewRainForced(), CombatText.NewText(), Utils.Next(), Utils.NextFromCollection< T >(), Utils.NextFromList< T >(), Star.NightSetup(), Player.NinjaDodge(), NPC.NPCLoot_DropCommonLifeAndMana(), NPC.NPCLoot_DropHeals(), NPC.NPCLoot_DropMoney(), Main.oldDrawWater(), Player.OnHit(), Player.OpenBossBag(), Player.OpenCanofWorms(), Player.OpenFishingCrate(), Player.OpenGoodieBag(), Player.OpenHerbBag(), Player.OpenLegacyPresent(), Player.OpenLockBox(), Player.OpenOyster(), Player.OpenPresent(), Player.OpenShadowLockbox(), WorldGen.OrePatch(), WorldGen.paintCoatEffect(), ShapeBranch.Perform(), ShapeRunner.Perform(), Player.PickAmmo(), EmoteBubble.PickNPCEmote(), AnthillEntrance.Place(), ChambersEntrance.Place(), LarvaHoleEntrance.Place(), PitEntrance.Place(), SandMound.Place(), CampsiteBiome.Place(), CorruptionPitBiome.Place(), DesertBiome.Place(), DunesBiome.Place(), HiveBiome.Place(), MahoganyTreeBiome.Place(), MarbleBiome.Place(), MiningExplosivesBiome.Place(), ThinIceBiome.Place(), ChambersEntrance.PlaceAt(), AnthillEntrance.PlaceAt(), LarvaHoleEntrance.PlaceAt(), HouseBuilder.PlaceBiomeSpecificPriorityTool(), HouseBuilder.PlaceBiomeSpecificTool(), HouseBuilder.PlaceChests(), DesertHive.PlaceClustersArea(), JunglePass.PlaceFirstPassMud(), JunglePass.PlaceGemsAt(), DunesBiome.PlaceHill(), WorldGen.PlaceOasis(), TrackGenerator.PlacePath(), DunesBiome.PlaceSingle(), MarbleBiome.PlaceSlab(), Player.PlaceThing_PaintScrapper_LongMoss(), Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Player.PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(), WorldGen.placeTrap(), WorldGen.plantDye(), Player.PlayerFrame(), LegacySoundPlayer.PlaySound(), Utils.PoofOfSmoke(), Main.PostContentLoadInitialize(), Item.Prefix(), WorldGen.PrefixItemFromOptions(), ItemTransferParticle.Prepare(), LittleFlyingCritterParticle.Prepare(), EmoteBubble.ProbeBosses(), EmoteBubble.ProbeDebuffs(), EmoteBubble.ProbeEvents(), Player.ProcessHitAgainstNPC(), RollCommand.ProcessIncomingMessage(), Projectile.ProjLight(), Player.QuickBuff(), WoodHouseBuilder.RainbowifyOnTenthAnniversaryWorlds(), DD2Event.RaiseGoblins(), Main.randColor(), WorldGen.randGem(), WorldGen.randGemTile(), WorldGen.randMoss(), WorldGen.RandomizeBackgroundBasedOnPlayer(), WorldGen.RandomizeBackgrounds(), WorldGen.RandomizeCaveBackgrounds(), RandomizedFrameParticle.RandomizeFrame(), Projectile.RandomizeInsanityShadowFor(), WorldGen.RandomizeMoonState(), WorldGen.RandomizeTreeStyle(), TreeTopsInfo.RandomizeTreeStyle(), WorldGen.RandomizeWeather(), NPC.ReflectProjectile(), NPC.ReleaseNPC(), PartySky.ResetBalloon(), LanternSky.ResetLantern(), AmbienceServer.ResetSpawnTime(), Player.RocketBootVisuals(), Item.RollAPrefix(), Player.RollLuck(), WorldGen.RollRandomForestBGStyle(), Cloud.RollRareCloud(), Profiles.VariantNPCProfile.RollVariation(), Utils.SelectRandom< T >(), Framing.SelfFrame8Way(), NetAmbienceModule.SerializeSkyEntitySpawn(), Projectile.SetDefaults(), NPC.setFireFlyChance(), WorldGen.SetGemTreeDrops(), Chest.SetupTravelShop(), Chest.SetupTravelShop_AddToShop(), Chest.SetupTravelShop_GetItem(), WorldGen.SetVanityTreeDrops(), NPC.SetWorldSpecificMonstersByWorldID(), WorldGen.ShakeTree(), WorldGen.ShellPile(), Item.ShimmerEffect(), NPC.SlimeRainSpawns(), WorldGen.SmashAltar(), Main.snowing(), DelegateMethods.Minecart.Sparks(), DelegateMethods.Minecart.SparksFart(), DelegateMethods.Minecart.SparksMech(), DelegateMethods.Minecart.SparksMeow(), DelegateMethods.Minecart.SparksTerraFart(), ParticleOrchestrator.Spawn_BlackLightningHit(), ParticleOrchestrator.Spawn_BlackLightningSmall(), ParticleOrchestrator.Spawn_Digestion(), ParticleOrchestrator.Spawn_FlameWaders(), ParticleOrchestrator.Spawn_GasTrap(), ParticleOrchestrator.Spawn_ItemTransfer(), ParticleOrchestrator.Spawn_PetExchange(), ParticleOrchestrator.Spawn_ShimmerTownNPC(), ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), ParticleOrchestrator.Spawn_StellarTune(), ParticleOrchestrator.Spawn_TrueExcalibur(), ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), AmbientWindSystem.SpawnAirborneCloud(), NPC.SpawnFaelings(), DelegateMethods.Minecart.SpawnFartCloud(), Player.SpawnFastRunParticles(), AmbientWindSystem.SpawnFloorCloud(), Player.SpawnHallucination(), NPC.SpawnNPC(), NPC.SpawnNPC_CheckToSpawnRockGolem(), NPC.SpawnNPC_GetGemBunnyToSpawn(), NPC.SpawnNPC_GetGemSquirrelToSpawn(), NPC.SpawnNPC_SpawnLavaBaitCritters(), NPC.SpawnOnPlayer(), WorldGen.SpawnPlanteraThorns(), PotionOfReturnGateHelper.SpawnReturnPortalDust(), NPC.SpawnStardustMark_StardustTower(), NPC.SpawnStardustMark_StardustWorm(), WorldGen.SpawnThingsFromPot(), WorldGen.SpawnTravelNPC(), VoidLensHelper.SpawnVoidLensDust(), Projectile.SpawnWebs(), WorldGen.Spread.Spider(), Player.SporeSac(), Main.StartInvasion(), Main.StartRain(), Sandstorm.StartSandstorm(), Main.StartSlimeRain(), WorldGen.Statue(), Player.StatusFromNPC(), Projectile.StatusNPC(), Projectile.StatusPlayer(), Projectile.StatusPvP(), Player.StatusToNPC(), Player.StatusToPlayerPvP(), Player.StickyMovement(), Collision.StickyTiles(), NPC.StingerExplosion(), WorldGen.StonePatch(), Main.StopSlimeRain(), NPC.StrikeNPC(), FinalFractalHelper.FinalFractalProfile.StripDust(), Projectile.SummonMonkGhast(), Main.TeleportEffect(), AmbientWindSystem.TestAirCloud(), Player.TileInteractionsUse(), Player.TorchAttack(), NPC.TransformVisuals(), WorldGen.TreeGrowFX_AshShake(), WorldGen.TriggerLunarApocalypse(), CommonDrop.TryDroppingItem(), CommonDropNotScalingWithLuck.TryDroppingItem(), CommonDropWithRerolls.TryDroppingItem(), DropLocalPerClientAndResetsNPCMoneyTo0.TryDroppingItem(), DropOneByOne.TryDroppingItem(), DropPerPlayerOnThePlayer.TryDroppingItem(), FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), OneFromOptionsDropRule.TryDroppingItem(), OneFromOptionsNotScaledWithLuckDropRule.TryDroppingItem(), SlimeBodyItemDropRule.TryDroppingItem(), OneFromRulesRule.TryDroppingItem(), Player.TryDroppingSingleItem(), Player.TryGettingDevArmor(), WorldGen.TryGrowingAbigailsFlower(), WaterfallManager.TrySparkling(), MysticLogFairiesEvent.TrySpawningFairies(), WorldGen.TrySpawningTownNPC(), AmbientWindSystem.TrySpawningWind(), Player.TryToPoop(), DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), AmbienceServer.Update(), Cloud.Update(), Gore.Update(), Liquid.Update(), Player.RabbitOrderFrameHelper.Update(), Rain.Update(), LanternSky.Update(), PartySky.Update(), SlimeSky.Update(), VortexSky.Update(), Player.Update(), Projectile.Update(), LittleFlyingCritterParticle.Update(), Gore.UpdateAmbientAirborneCloud(), Player.UpdateArmorSets(), Main.UpdateAudio_DecideOnNewMusic(), Player.UpdateBuffs(), Main.updateCloudLayer(), Cloud.UpdateClouds(), LegacyAudioSystem.UpdateCommonTrack(), Main.UpdateDragonflyJarFrame(), Dust.UpdateDust(), Mount.UpdateEffects(), Gore.UpdateFogMachineCloud(), Mount.UpdateFrame(), AWorldListItem.UpdateGlitchAnimation(), Player.UpdateHairDyeDust(), Item.UpdateItem(), Item.UpdateItem_VisualEffects(), Player.UpdateLifeRegen(), Gore.UpdateLightningBunnySparks(), Player.UpdateManaRegen(), Main.UpdateMenu(), NPC.UpdateNPC(), NPC.UpdateNPC_BuffApplyVFX(), NPC.UpdateNPC_CastLights(), NPC.UpdateNPC_CritterSounds(), NPC.UpdateNPC_SoulDrainDebuff(), NPC.UpdateNPC_TeleportVisuals(), Main.UpdateOwlCageFrame(), Player.UpdateTeleportVisuals(), Sandstorm.UpdateTime(), Main.UpdateTime(), Main.UpdateTime_SpawnTownNPCs(), Main.UpdateTime_StartDay(), Main.UpdateTime_StartNight(), Main.UpdateWeather(), WorldGen.UpdateWorld(), WorldGen.UpdateWorld_OvergroundTile(), WorldGen.UpdateWorld_UndergroundTile(), Mount.UseDrill(), Framing.WallFrame(), Player.WingAirVisuals(), and Player.WingFrame().