Terraria: UnifiedRandom.NextDouble
NextDouble()
virtual double UnifiedRandom.NextDouble () inline virtual
     {
         return Sample();
     }
References Sample().
Referenced by NPC.AI(), Projectile.AI_001(), Projectile.AI_062(), NPC.AI_069_DukeFishron(), Projectile.AI_075(), NPC.AI_084_LunaticCultist(), NPC.AI_107_ImprovedWalkers(), NPC.AI_108_DivingFlyer(), Projectile.AI_178_FireExplosion(), Modifiers.RadialDither.Apply(), Modifiers.Blotches.Apply(), Modifiers.Dither.Apply(), DesertDescription.CreateFromPlacement(), HouseUtils.CreateRooms(), Mount.DoSpawnDust(), Player.DropAnglerAccByMissing(), DesertHive.ClusterGroup.Generate(), SlimeSky.GenerateSlimes(), MartianSky.GenerateUfos(), WorldGen.GenerateWorld(), WeightedRandom< T >.Get(), Player.GetAnglerReward_MainReward(), NPC.HitEffect(), MartianSky.ZipBehavior.InitializeUfo(), MartianSky.HoverBehavior.InitializeUfo(), Player.ItemCheck_Shoot(), Projectile.Kill(), WorldGen.MarblePileWithStatues(), WorldGen.neonMossBiome(), Utils.NextFloat(), Utils.NextFloatDirection(), Utils.NextVector2Square(), WorldGen.OrePatch(), ShapeBranch.Perform(), DesertBiome.Place(), EnchantedSwordBiome.Place(), MahoganyTreeBiome.Place(), MarbleBiome.Place(), MiningExplosivesBiome.Place(), HouseBuilder.PlaceChests(), WorldGen.PlaceOasis(), Utils.RandomVector2(), Utils.RandomVector2D(), PartySky.ResetBalloon(), LanternSky.ResetLantern(), Utils.RotatedByRandom(), Utils.RotateRandom(), WorldGen.ShellPile(), WorldGen.StonePatch(), EyeballShader.Update(), SlimeSky.Update(), Projectile.Update(), and Mount.UseDrill().