Terraria: System.Xml.QueryOutputWriter.WriteEndElement
WriteEndElement() [2/2]
override void System.Xml.QueryOutputWriter.WriteEndElement (string prefix, string localName, string ns) inline package
Definition at line 133 of file QueryOutputWriter.cs.
    {
        EndCDataSection();
        _wrapped.WriteEndElement(prefix, localName, ns);
        if (_checkWellFormedDoc)
        {
            _depth--;
        }
        if (_lookupCDataElems != null)
        {
            _bitsCData.PopBit();
        }
    }
References System.Xml.QueryOutputWriter._bitsCData, System.Xml.QueryOutputWriter._checkWellFormedDoc, System.Xml.QueryOutputWriter._depth, System.Xml.QueryOutputWriter._lookupCDataElems, System.Xml.QueryOutputWriter._wrapped, System.Xml.QueryOutputWriter.EndCDataSection(), System.Xml.BitStack.PopBit(), System.prefix, and System.Xml.XmlRawWriter.WriteEndElement().