Terraria: HitTile.Clear
Clear()
void HitTile.Clear (int tileId) inline
     {
         if (tileId >= 0 && tileId <= 500)
         {
             data[tileId].Clear();
             int i;
             for (i = 0; i < 500 && order[i] != tileId; i++)
             {
             }
             for (; i < 500; i++)
             {
                 order[i] = order[i + 1];
             }
             order[500] = tileId;
         }
     }
References HitTile.HitTileObject.Clear(), data, and order.
Referenced by ClearThisTile(), and TryClearingAndPruning().