Terraria: System.Xml.QueryOutputWriter.WriteRaw
WriteRaw() [1/2]
override void System.Xml.QueryOutputWriter.WriteRaw (char[] buffer, int index, int count) inline
Definition at line 264 of file QueryOutputWriter.cs.
    {
        if (!_inAttr && (_inCDataSection || StartCDataSection()))
        {
            _wrapped.WriteCData(new string(buffer, index, count));
        }
        else
        {
            _wrapped.WriteRaw(buffer, index, count);
        }
    }
References System.Xml.QueryOutputWriter._inAttr, System.Xml.QueryOutputWriter._inCDataSection, System.Xml.QueryOutputWriter._wrapped, System.buffer, System.count, System.index, System.Xml.QueryOutputWriter.StartCDataSection(), System.Xml.XmlRawWriter.WriteCData(), and System.Xml.XmlRawWriter.WriteRaw().