Terraria: System.Xml.QueryOutputWriter.WriteStartElement
WriteStartElement() [3/4]
override void System.Xml.QueryOutputWriter.WriteStartElement (string prefix, string localName, string ns) inline
Definition at line 108 of file QueryOutputWriter.cs.
    {
        EndCDataSection();
        if (_checkWellFormedDoc)
        {
            if (_depth == 0 && _hasDocElem)
            {
                throw new XmlException(System.SR.Xml_NoMultipleRoots, string.Empty);
            }
            _depth++;
            _hasDocElem = true;
        }
        if (_outputDocType)
        {
            _wrapped.WriteDocType(string.IsNullOrEmpty(prefix) ? localName : (prefix + ":" + localName), _publicId, _systemId, null);
            _outputDocType = false;
        }
        _wrapped.WriteStartElement(prefix, localName, ns);
        if (_lookupCDataElems != null)
        {
            _qnameCData.Init(localName, ns);
            _bitsCData.PushBit(_lookupCDataElems.ContainsKey(_qnameCData));
        }
    }
References System.Xml.QueryOutputWriter._bitsCData, System.Xml.QueryOutputWriter._checkWellFormedDoc, System.Xml.QueryOutputWriter._depth, System.Xml.QueryOutputWriter._hasDocElem, System.Xml.QueryOutputWriter._lookupCDataElems, System.Xml.QueryOutputWriter._outputDocType, System.Xml.QueryOutputWriter._publicId, System.Xml.QueryOutputWriter._qnameCData, System.Xml.QueryOutputWriter._systemId, System.Xml.QueryOutputWriter._wrapped, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.Xml.QueryOutputWriter.EndCDataSection(), System.Xml.XmlQualifiedName.Init(), System.prefix, System.Xml.BitStack.PushBit(), System.Xml.XmlRawWriter.WriteDocType(), System.Xml.XmlWriter.WriteStartElement(), System.SR.Xml_NoMultipleRoots, and System.Xml.XmlException.