Terraria: System.Xml.QueryOutputWriter.StartCDataSection
StartCDataSection()
bool System.Xml.QueryOutputWriter.StartCDataSection () inline private
Definition at line 302 of file QueryOutputWriter.cs.
    {
        if (_lookupCDataElems != null && _bitsCData.PeekBit())
        {
            _inCDataSection = true;
            return true;
        }
        return false;
    }
References System.Xml.QueryOutputWriter._bitsCData, System.Xml.QueryOutputWriter._inCDataSection, System.Xml.QueryOutputWriter._lookupCDataElems, and System.Xml.BitStack.PeekBit().
Referenced by System.Xml.QueryOutputWriter.WriteChars(), System.Xml.QueryOutputWriter.WriteRaw(), System.Xml.QueryOutputWriter.WriteRaw(), System.Xml.QueryOutputWriter.WriteString(), and System.Xml.QueryOutputWriter.WriteWhitespace().