Terraria: HitTile.DrawFreshAnimations
DrawFreshAnimations()
void HitTile.DrawFreshAnimations (SpriteBatch spriteBatch) inline
     {
         for (int i = 0; i < data.Length; i++)
         {
             data[i].animationTimeElapsed++;
         }
         if (!Main.SettingsEnabled_MinersWobble)
         {
             return;
         }
         int num = 1;
         Vector2 vector = new Vector2(Main.offScreenRange);
         if (Main.drawToScreen)
         {
             vector = Vector2.Zero;
         }
         vector = Vector2.Zero;
         bool flag = Main.ShouldShowInvisibleWalls();
         for (int j = 0; j < data.Length; j++)
         {
             if (data[j].type != num)
             {
                 continue;
             }
             int damage = data[j].damage;
             if (damage < 20)
             {
                 continue;
             }
             int x = data[j].X;
             int y = data[j].Y;
             if (!WorldGen.InWorld(x, y))
             {
                 continue;
             }
             Tile tile = Main.tile[x, y];
             bool flag2 = tile != null;
             if (flag2 && num == 1)
             {
                 flag2 = flag2 && tile.active() && Main.tileSolid[Main.tile[x, y].type] && (!tile.invisibleBlock() || flag);
             }
             if (flag2 && num == 2)
             {
                 flag2 = flag2 && tile.wall != 0 && (!tile.invisibleWall() || flag);
             }
             if (!flag2)
             {
                 continue;
             }
             bool flag3 = false;
             bool flag4 = false;
             if (tile.type == 10)
             {
                 flag3 = false;
             }
             else if (Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
             {
                 flag3 = true;
             }
             else if (WorldGen.IsTreeType(tile.type))
             {
                 flag4 = true;
                 int num2 = tile.frameX / 22;
                 int num3 = tile.frameY / 22;
                 if (num3 < 9)
                 {
                     flag3 = ((num2 != 1 && num2 != 2) || num3 < 6 || num3 > 8) && (num2 != 3 || num3 > 2) && (num2 != 4 || num3 < 3 || num3 > 5) && ((num2 != 5 || num3 < 6 || num3 > 8) ? true : false);
                 }
             }
             else if (tile.type == 72)
             {
                 flag4 = true;
                 if (tile.frameX <= 34)
                 {
                     flag3 = true;
                 }
             }
             if (!flag3 || tile.slope() != 0 || tile.halfBrick())
             {
                 continue;
             }
             int num4 = 0;
             if (damage >= 80)
             {
                 num4 = 3;
             }
             else if (damage >= 60)
             {
                 num4 = 2;
             }
             else if (damage >= 40)
             {
                 num4 = 1;
             }
             else if (damage >= 20)
             {
                 num4 = 0;
             }
             Rectangle value = new Rectangle(data[j].crackStyle * 18, num4 * 18, 16, 16);
             value.Inflate(-2, -2);
             if (flag4)
             {
                 value.X = (4 + data[j].crackStyle / 2) * 18;
             }
             int animationTimeElapsed = data[j].animationTimeElapsed;
             if (!((float)animationTimeElapsed >= 10f))
             {
                 float num5 = (float)animationTimeElapsed / 10f;
                 Color color = Lighting.GetColor(x, y);
                 float rotation = 0f;
                 Vector2 zero = Vector2.Zero;
                 float num6 = 0.5f;
                 float num7 = num5 % num6;
                 num7 *= 1f / num6;
                 if ((int)(num5 / num6) % 2 == 1)
                 {
                     num7 = 1f - num7;
                 }
                 Tile tileSafely = Framing.GetTileSafely(x, y);
                 Tile tile2 = tileSafely;
                 Texture2D texture2D = Main.instance.TilePaintSystem.TryGetTileAndRequestIfNotReady(tileSafely.type, 0, tileSafely.color());
                 if (texture2D != null)
                 {
                     Vector2 vector2 = new Vector2(8f);
                     Vector2 vector3 = new Vector2(1f);
                     float num8 = num7 * 0.2f + 1f;
                     float num9 = 1f - num7;
                     num9 = 1f;
                     color *= num9 * num9 * 0.8f;
                     Vector2 scale = num8 * vector3;
                     Vector2 position = (new Vector2(x * 16 - (int)Main.screenPosition.X, y * 16 - (int)Main.screenPosition.Y) + vector + vector2 + zero).Floor();
                     spriteBatch.Draw(texture2D, position, new Rectangle(tile2.frameX, tile2.frameY, 16, 16), color, rotation, vector2, scale, SpriteEffects.None, 0f);
                     color.A = 180;
                     spriteBatch.Draw(TextureAssets.TileCrack.Value, position, value, color, rotation, vector2, scale, SpriteEffects.None, 0f);
                 }
             }
         }
     }
References Tile.active(), HitTile.HitTileObject.animationTimeElapsed, Color, Tile.color(), HitTile.HitTileObject.crackStyle, HitTile.HitTileObject.damage, data, Main.drawToScreen, Tile.frameX, Tile.frameY, Lighting.GetColor(), Framing.GetTileSafely(), Tile.halfBrick(), Main.instance, Tile.invisibleBlock(), Tile.invisibleWall(), WorldGen.InWorld(), WorldGen.IsTreeType(), Main.offScreenRange, Main.screenPosition, Main.SettingsEnabled_MinersWobble, Main.ShouldShowInvisibleWalls(), Tile.slope(), Main.tile, TextureAssets.TileCrack, Main.TilePaintSystem, Main.tileSolid, Main.tileSolidTop, TilePaintSystemV2.TryGetTileAndRequestIfNotReady(), Tile.type, Asset< T >.Value, Tile.wall, HitTile.HitTileObject.X, and HitTile.HitTileObject.Y.
Referenced by Main.DoDraw_Tiles_Solid().