Terraria: HitTile.Prune
Prune()
void HitTile.Prune () inline
     {
         bool flag = false;
         for (int i = 0; i <= 500; i++)
         {
             HitTileObject hitTileObject = data[i];
             if (hitTileObject.type == 0)
             {
                 continue;
             }
             Tile tile = Main.tile[hitTileObject.X, hitTileObject.Y];
             if (hitTileObject.timeToLive <= 1)
             {
                 hitTileObject.Clear();
                 flag = true;
                 continue;
             }
             hitTileObject.timeToLive--;
             if ((double)hitTileObject.timeToLive < 12.0)
             {
                 hitTileObject.damage -= 10;
             }
             else if ((double)hitTileObject.timeToLive < 24.0)
             {
                 hitTileObject.damage -= 7;
             }
             else if ((double)hitTileObject.timeToLive < 36.0)
             {
                 hitTileObject.damage -= 5;
             }
             else if ((double)hitTileObject.timeToLive < 48.0)
             {
                 hitTileObject.damage -= 2;
             }
             if (hitTileObject.damage < 0)
             {
                 hitTileObject.Clear();
                 flag = true;
             }
             else if (hitTileObject.type == 1)
             {
                 if (!tile.active())
                 {
                     hitTileObject.Clear();
                     flag = true;
                 }
             }
             else if (tile.wall == 0)
             {
                 hitTileObject.Clear();
                 flag = true;
             }
         }
         if (!flag)
         {
             return;
         }
         int num = 1;
         while (flag)
         {
             flag = false;
             for (int j = num; j < 500; j++)
             {
                 if (data[order[j]].type == 0 && data[order[j + 1]].type != 0)
                 {
                     int num2 = order[j];
                     order[j] = order[j + 1];
                     order[j + 1] = num2;
                     flag = true;
                 }
             }
         }
     }
References Tile.active(), HitTile.HitTileObject.Clear(), HitTile.HitTileObject.damage, data, order, Main.tile, HitTile.HitTileObject.timeToLive, HitTile.HitTileObject.type, Tile.wall, HitTile.HitTileObject.X, and HitTile.HitTileObject.Y.
Referenced by ClearThisTile(), and TryClearingAndPruning().