Terraria: Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.PegasusSkyEntity
PegasusSkyEntity()
Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.PegasusSkyEntity (Player player, FastRandom random) inline
References Terraria.Main.Assets, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.BrightnessLerper, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Depth, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FinalOpacityMultiplier, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Frame, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.FramingSpeed, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.LifeTime, Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeIn, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.OpacityNormalizedTimeToFadeOut, Terraria.GameContent.Skies.AmbientSky.SkyEntity.Position, Terraria.GameContent.Skies.AmbientSky.SkyEntity.SetPositionInWorldBasedOnScreenSpace(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Texture, and Terraria.Main.worldSurface.