Terraria: System.Net.Http.Http2Connection.FrameHeader.ReadFrom
ReadFrom()
static FrameHeader System.Net.Http.Http2Connection.FrameHeader.ReadFrom (ReadOnlySpan< byte > buffer) inline static
Definition at line 133 of file Http2Connection.cs.
        {
            FrameFlags flags = (FrameFlags)buffer[4];
            int payloadLength = (buffer[0] << 16) | (buffer[1] << 8) | buffer[2];
            FrameType type = (FrameType)buffer[3];
            int streamId = (int)(BinaryPrimitives.ReadUInt32BigEndian(buffer.Slice(5)) & 0x7FFFFFFF);
            return new FrameHeader(payloadLength, type, flags, streamId);
        }
References System.Net.Http.Http2Connection.FrameHeader.FrameHeader(), System.buffer, System.Buffers.Binary.BinaryPrimitives.ReadUInt32BigEndian(), and System.type.
Referenced by System.Net.Http.Http2Connection.ReadFrameAsync().