Terraria: UIWorldLoad.DrawSelf
DrawSelf()
override void UIWorldLoad.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from UIElement.
     {
         float overallProgress = 0f;
         float currentProgress = 0f;
         string text = string.Empty;
         if (_progress != null)
         {
             overallProgress = (float)_progress.TotalProgress;
             currentProgress = (float)_progress.Value;
             text = _progress.Message;
         }
         _progressBar.SetProgress(overallProgress, currentProgress);
         _progressMessage.Text = text;
         if (WorldGen.drunkWorldGenText && !WorldGen.placingTraps && !WorldGen.getGoodWorldGen)
         {
             _progressMessage.Text = string.Concat(Main.rand.Next(999999999));
             for (int i = 0; i < 3; i++)
             {
                 if (Main.rand.Next(2) == 0)
                 {
                     _progressMessage.Text += Main.rand.Next(999999999);
                 }
             }
         }
         if (WorldGen.getGoodWorldGen)
         {
             if (!WorldGen.noTrapsWorldGen || !WorldGen.placingTraps)
             {
                 string text2 = "";
                 for (int num = _progressMessage.Text.Length - 1; num >= 0; num--)
                 {
                     text2 += _progressMessage.Text.Substring(num, 1);
                 }
                 _progressMessage.Text = text2;
             }
         }
         else if (WorldGen.notTheBees)
         {
             _progressMessage.Text = Language.GetTextValue("UI.WorldGenEasterEgg_GeneratingBees");
         }
         Main.gameTips.Update();
         Main.gameTips.Draw();
         UpdateGamepadSquiggle();
     }
References _progress, _progressBar, _progressMessage, GameTipsDisplay.Draw(), WorldGen.drunkWorldGenText, Main.gameTips, WorldGen.getGoodWorldGen, Language.GetTextValue(), GenerationProgress.Message, UnifiedRandom.Next(), WorldGen.noTrapsWorldGen, WorldGen.notTheBees, WorldGen.placingTraps, Main.rand, UIGenProgressBar.SetProgress(), UIHeader.Text, GenerationProgress.TotalProgress, GameTipsDisplay.Update(), UpdateGamepadSquiggle(), and GenerationProgress.Value.