Terraria: Terraria.GameContent.PressurePlateHelper.PressurePlatesPressed
PressurePlatesPressed
Dictionary<Point, bool[]> Terraria.GameContent.PressurePlateHelper.PressurePlatesPressed = new Dictionary<Point, bool[]>() static
Definition at line 11 of file PressurePlateHelper.cs.
Referenced by Terraria.GameContent.PressurePlateHelper.DestroyPlate(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.IO.WorldFile.LoadWeightedPressurePlates(), Terraria.GameContent.PressurePlateHelper.MoveAwayFrom(), Terraria.GameContent.PressurePlateHelper.MoveInto(), Terraria.GameContent.PressurePlateHelper.Reset(), Terraria.GameContent.PressurePlateHelper.ResetPlayer(), Terraria.IO.WorldFile.SaveWeightedPressurePlates(), and Terraria.GameContent.PressurePlateHelper.Update().