Terraria: Terraria.GameContent.PressurePlateHelper.MoveAwayFrom
MoveAwayFrom()
static void Terraria.GameContent.PressurePlateHelper.MoveAwayFrom (Point location, int player) inline static private
Definition at line 130 of file PressurePlateHelper.cs.
    {
        if (!PressurePlatesPressed.TryGetValue(location, out var value))
        {
            return;
        }
        value[player] = false;
        bool flag = false;
        for (int i = 0; i < value.Length; i++)
        {
            if (value[i])
            {
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            lock (EntityCreationLock)
            {
                PressurePlatesPressed.Remove(location);
            }
            PokeLocation(location);
        }
    }
References Terraria.GameContent.PressurePlateHelper.EntityCreationLock, Terraria.GameContent.PressurePlateHelper.PokeLocation(), and Terraria.GameContent.PressurePlateHelper.PressurePlatesPressed.
Referenced by Terraria.GameContent.PressurePlateHelper.ResetPlayer(), Terraria.GameContent.PressurePlateHelper.UpdatePlatePosition(), and Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition().