Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle
PreprocessParticle()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle (XmlSchemaParticle particle) inline private
Definition at line 1483 of file SchemaCollectionPreprocessor.cs.
    {
        if (particle is XmlSchemaAll xmlSchemaAll)
        {
            if (particle.MinOccurs != 0m && particle.MinOccurs != 1m)
            {
                particle.MinOccurs = 1m;
                SendValidationEvent(System.SR.Sch_InvalidAllMin, particle);
            }
            if (particle.MaxOccurs != 1m)
            {
                particle.MaxOccurs = 1m;
                SendValidationEvent(System.SR.Sch_InvalidAllMax, particle);
            }
            for (int i = 0; i < xmlSchemaAll.Items.Count; i++)
            {
                XmlSchemaElement xmlSchemaElement = (XmlSchemaElement)xmlSchemaAll.Items[i];
                if (xmlSchemaElement.MaxOccurs != 0m && xmlSchemaElement.MaxOccurs != 1m)
                {
                    xmlSchemaElement.MaxOccurs = 1m;
                    SendValidationEvent(System.SR.Sch_InvalidAllElementMax, xmlSchemaElement);
                }
                SetParent(xmlSchemaElement, particle);
                PreprocessLocalElement(xmlSchemaElement);
            }
        }
        else
        {
            if (particle.MinOccurs > particle.MaxOccurs)
            {
                particle.MinOccurs = particle.MaxOccurs;
                SendValidationEvent(System.SR.Sch_MinGtMax, particle);
            }
            if (particle is XmlSchemaChoice xmlSchemaChoice)
            {
                XmlSchemaObjectCollection items = xmlSchemaChoice.Items;
                for (int j = 0; j < items.Count; j++)
                {
                    SetParent(items[j], particle);
                    if (items[j] is XmlSchemaElement element)
                    {
                        PreprocessLocalElement(element);
                    }
                    else
                    {
                        PreprocessParticle((XmlSchemaParticle)items[j]);
                    }
                }
            }
            else if (particle is XmlSchemaSequence)
            {
                XmlSchemaObjectCollection items2 = ((XmlSchemaSequence)particle).Items;
                for (int k = 0; k < items2.Count; k++)
                {
                    SetParent(items2[k], particle);
                    if (items2[k] is XmlSchemaElement element2)
                    {
                        PreprocessLocalElement(element2);
                    }
                    else
                    {
                        PreprocessParticle((XmlSchemaParticle)items2[k]);
                    }
                }
            }
            else if (particle is XmlSchemaGroupRef)
            {
                XmlSchemaGroupRef xmlSchemaGroupRef = (XmlSchemaGroupRef)particle;
                if (xmlSchemaGroupRef.RefName.IsEmpty)
                {
                    SendValidationEvent(System.SR.Sch_MissAttribute, "ref", xmlSchemaGroupRef);
                }
                else
                {
                    ValidateQNameAttribute(xmlSchemaGroupRef, "ref", xmlSchemaGroupRef.RefName);
                }
            }
            else if (particle is XmlSchemaAny)
            {
                try
                {
                    ((XmlSchemaAny)particle).BuildNamespaceListV1Compat(_targetNamespace);
                }
                catch
                {
                    SendValidationEvent(System.SR.Sch_InvalidAny, particle);
                }
            }
        }
        PreprocessAnnotation(particle);
        ValidateIdAttribute(particle);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Collections.CollectionBase.Count, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaParticle.MaxOccurs, System.Xml.Schema.XmlSchemaParticle.MinOccurs, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), System.SR.Sch_InvalidAllElementMax, System.SR.Sch_InvalidAllMax, System.SR.Sch_InvalidAllMin, System.SR.Sch_InvalidAny, System.SR.Sch_MinGtMax, System.SR.Sch_MissAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle().