Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute
ValidateIdAttribute()
void System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute (XmlSchemaObject xso) inline private
Definition at line 1614 of file SchemaCollectionPreprocessor.cs.
    {
        if (xso.IdAttribute == null)
        {
            return;
        }
        try
        {
            xso.IdAttribute = base.NameTable.Add(XmlConvert.VerifyNCName(xso.IdAttribute));
            if (_schema.Ids[xso.IdAttribute] != null)
            {
                SendValidationEvent(System.SR.Sch_DupIdAttribute, xso);
            }
            else
            {
                _schema.Ids.Add(xso.IdAttribute, xso);
            }
        }
        catch (Exception ex)
        {
            SendValidationEvent(System.SR.Sch_InvalidIdAttribute, ex.Message, xso);
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._schema, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Dictionary, System.Xml.Schema.XmlSchemaObject.IdAttribute, System.Xml.Schema.XmlSchema.Ids, System.SR.Sch_DupIdAttribute, System.SR.Sch_InvalidIdAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.XmlConvert.VerifyNCName().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Execute(), System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType().