Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup
PreprocessGroup()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup (XmlSchemaGroup group) inline private
Definition at line 1413 of file SchemaCollectionPreprocessor.cs.
    {
        if (group.Name != null)
        {
            ValidateNameAttribute(group);
            group.SetQualifiedName(new XmlQualifiedName(group.Name, _targetNamespace));
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", group);
        }
        if (group.Particle == null)
        {
            SendValidationEvent(System.SR.Sch_NoGroupParticle, group);
            return;
        }
        if (group.Particle.MinOccursString != null)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "minOccurs", group.Particle);
        }
        if (group.Particle.MaxOccursString != null)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "maxOccurs", group.Particle);
        }
        PreprocessParticle(group.Particle);
        PreprocessAnnotation(group);
        ValidateIdAttribute(group);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), System.SR.Sch_ForbiddenAttribute, System.SR.Sch_MissRequiredAttribute, System.SR.Sch_NoGroupParticle, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine().