Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent
PreprocessElementContent()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent (XmlSchemaElement element) inline private
Definition at line 968 of file SchemaCollectionPreprocessor.cs.
    {
        PreprocessAnnotation(element);
        if (!element.RefName.IsEmpty)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "ref", element);
        }
        if (element.Block == XmlSchemaDerivationMethod.All)
        {
            element.SetBlockResolved(XmlSchemaDerivationMethod.All);
        }
        else if (element.Block == XmlSchemaDerivationMethod.None)
        {
            if (_blockDefault == XmlSchemaDerivationMethod.All)
            {
                element.SetBlockResolved(XmlSchemaDerivationMethod.All);
            }
            else
            {
                element.SetBlockResolved(_blockDefault & (XmlSchemaDerivationMethod.Substitution | XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
            }
        }
        else
        {
            if (((uint)element.Block & 0xFFFFFFF8u) != 0)
            {
                SendValidationEvent(System.SR.Sch_InvalidElementBlockValue, element);
            }
            element.SetBlockResolved(element.Block & (XmlSchemaDerivationMethod.Substitution | XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
        }
        if (element.SchemaType != null)
        {
            SetParent(element.SchemaType, element);
            if (!element.SchemaTypeName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_TypeMutualExclusive, element);
            }
            if (element.SchemaType is XmlSchemaComplexType)
            {
                PreprocessComplexType((XmlSchemaComplexType)element.SchemaType, local: true);
            }
            else
            {
                PreprocessSimpleType((XmlSchemaSimpleType)element.SchemaType, local: true);
            }
        }
        if (!element.SchemaTypeName.IsEmpty)
        {
            ValidateQNameAttribute(element, "type", element.SchemaTypeName);
        }
        if (element.DefaultValue != null && element.FixedValue != null)
        {
            SendValidationEvent(System.SR.Sch_DefaultFixedAttributes, element);
        }
        for (int i = 0; i < element.Constraints.Count; i++)
        {
            SetParent(element.Constraints[i], element);
            PreprocessIdentityConstraint((XmlSchemaIdentityConstraint)element.Constraints[i]);
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._blockDefault, System.Xml.Schema.XmlSchemaElement.Block, System.Xml.Schema.XmlSchemaElement.Constraints, System.Collections.CollectionBase.Count, System.Xml.Schema.XmlSchemaElement.DefaultValue, System.Xml.Schema.XmlSchemaElement.FixedValue, System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType(), System.Xml.Schema.XmlSchemaElement.RefName, System.SR.Sch_DefaultFixedAttributes, System.SR.Sch_ForbiddenAttribute, System.SR.Sch_InvalidElementBlockValue, System.SR.Sch_TypeMutualExclusive, System.Xml.Schema.XmlSchemaElement.SchemaType, System.Xml.Schema.XmlSchemaElement.SchemaTypeName, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.XmlSchemaElement.SetBlockResolved(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement().