Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttribute
PreprocessAttribute()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttribute (XmlSchemaAttribute attribute) inline private
Definition at line 760 of file SchemaCollectionPreprocessor.cs.
    {
        if (attribute.Name != null)
        {
            ValidateNameAttribute(attribute);
            attribute.SetQualifiedName(new XmlQualifiedName(attribute.Name, _targetNamespace));
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", attribute);
        }
        if (attribute.Use != 0)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "use", attribute);
        }
        if (attribute.Form != 0)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "form", attribute);
        }
        PreprocessAttributeContent(attribute);
        ValidateIdAttribute(attribute);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.SR.Sch_ForbiddenAttribute, System.SR.Sch_MissRequiredAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess().