Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint
PreprocessIdentityConstraint()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint (XmlSchemaIdentityConstraint constraint) inline private
Definition at line 1029 of file SchemaCollectionPreprocessor.cs.
    {
        bool flag = true;
        PreprocessAnnotation(constraint);
        if (constraint.Name != null)
        {
            ValidateNameAttribute(constraint);
            constraint.SetQualifiedName(new XmlQualifiedName(constraint.Name, _targetNamespace));
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", constraint);
            flag = false;
        }
        if (_schema.IdentityConstraints[constraint.QualifiedName] != null)
        {
            SendValidationEvent(System.SR.Sch_DupIdentityConstraint, constraint.QualifiedName.ToString(), constraint);
            flag = false;
        }
        else
        {
            _schema.IdentityConstraints.Add(constraint.QualifiedName, constraint);
        }
        if (constraint.Selector == null)
        {
            SendValidationEvent(System.SR.Sch_IdConstraintNoSelector, constraint);
            flag = false;
        }
        if (constraint.Fields.Count == 0)
        {
            SendValidationEvent(System.SR.Sch_IdConstraintNoFields, constraint);
            flag = false;
        }
        if (constraint is XmlSchemaKeyref)
        {
            XmlSchemaKeyref xmlSchemaKeyref = (XmlSchemaKeyref)constraint;
            if (xmlSchemaKeyref.Refer.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_IdConstraintNoRefer, constraint);
                flag = false;
            }
            else
            {
                ValidateQNameAttribute(xmlSchemaKeyref, "refer", xmlSchemaKeyref.Refer);
            }
        }
        if (flag)
        {
            ValidateIdAttribute(constraint);
            ValidateIdAttribute(constraint.Selector);
            SetParent(constraint.Selector, constraint);
            for (int i = 0; i < constraint.Fields.Count; i++)
            {
                SetParent(constraint.Fields[i], constraint);
                ValidateIdAttribute(constraint.Fields[i]);
            }
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._schema, System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.XmlSchemaObjectTable.Add(), System.Collections.CollectionBase.Count, System.Xml.Schema.XmlSchemaIdentityConstraint.Fields, System.Xml.Schema.XmlSchema.IdentityConstraints, System.Xml.Schema.XmlSchemaIdentityConstraint.Name, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.XmlSchemaIdentityConstraint.QualifiedName, System.SR.Sch_DupIdentityConstraint, System.SR.Sch_IdConstraintNoFields, System.SR.Sch_IdConstraintNoRefer, System.SR.Sch_IdConstraintNoSelector, System.SR.Sch_MissRequiredAttribute, System.Xml.Schema.XmlSchemaIdentityConstraint.Selector, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), System.Xml.Schema.XmlSchemaIdentityConstraint.SetQualifiedName(), System.Xml.XmlQualifiedName.ToString(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent().