Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd
ParseMemberEnd()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd (ParseRecord pr) inline private
Definition at line 699 of file ObjectReader.cs.
    {
        switch (pr._memberTypeEnum)
        {
        case InternalMemberTypeE.Item:
            ParseArrayMemberEnd(pr);
            break;
        case InternalMemberTypeE.Field:
            if (pr._memberValueEnum == InternalMemberValueE.Nested)
            {
                ParseObjectEnd(pr);
            }
            break;
        default:
            ParseError(pr, (ParseRecord)_stack.Peek());
            break;
        }
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader._stack, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMemberEnd(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(), and System.Runtime.Serialization.Formatters.Binary.SerStack.Peek().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse().