Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectReader.HasSurrogate
HasSurrogate()
bool System.Runtime.Serialization.Formatters.Binary.ObjectReader.HasSurrogate (Type t) inline private
Definition at line 153 of file ObjectReader.cs.
    {
        ISurrogateSelector selector;
        if (_surrogates != null)
        {
            return _surrogates.GetSurrogate(t, _context, out selector) != null;
        }
        return false;
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader._context, System.Runtime.Serialization.Formatters.Binary.ObjectReader._surrogates, System.Runtime.Serialization.Dictionary, and System.Runtime.Serialization.ISurrogateSelector.GetSurrogate().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize().