Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.Execute
Execute()
bool System.Xml.Schema.SchemaCollectionPreprocessor.Execute (XmlSchema schema, string targetNamespace, bool loadExternals, XmlSchemaCollection xsc) inline
Definition at line 51 of file SchemaCollectionPreprocessor.cs.
    {
        _schema = schema;
        _xmlns = base.NameTable.Add("xmlns");
        Cleanup(schema);
        if (loadExternals && _xmlResolver != null)
        {
            _schemaLocations = new Hashtable();
            if (schema.BaseUri != null)
            {
                _schemaLocations.Add(schema.BaseUri, schema.BaseUri);
            }
            LoadExternals(schema, xsc);
        }
        ValidateIdAttribute(schema);
        Preprocess(schema, targetNamespace, Compositor.Root);
        if (!base.HasErrors)
        {
            schema.IsPreprocessed = true;
            for (int i = 0; i < schema.Includes.Count; i++)
            {
                XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
                if (xmlSchemaExternal.Schema != null)
                {
                    xmlSchemaExternal.Schema.IsPreprocessed = true;
                }
            }
        }
        return !base.HasErrors;
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._schema, System.Xml.Schema.SchemaCollectionPreprocessor._schemaLocations, System.Xml.Schema.SchemaCollectionPreprocessor._xmlns, System.Xml.Schema.SchemaCollectionPreprocessor._xmlResolver, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Xml.Schema.SchemaCollectionPreprocessor.Cleanup(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals(), System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute().