Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent
PreprocessAttributeContent()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent (XmlSchemaAttribute attribute) inline private
Definition at line 811 of file SchemaCollectionPreprocessor.cs.
    {
        PreprocessAnnotation(attribute);
        if (_schema.TargetNamespace == "http://www.w3.org/2001/XMLSchema-instance")
        {
            SendValidationEvent(System.SR.Sch_TargetNamespaceXsi, attribute);
        }
        if (!attribute.RefName.IsEmpty)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "ref", attribute);
        }
        if (attribute.DefaultValue != null && attribute.FixedValue != null)
        {
            SendValidationEvent(System.SR.Sch_DefaultFixedAttributes, attribute);
        }
        if (attribute.DefaultValue != null && attribute.Use != XmlSchemaUse.Optional && attribute.Use != 0)
        {
            SendValidationEvent(System.SR.Sch_OptionalDefaultAttribute, attribute);
        }
        if (attribute.Name == _xmlns)
        {
            SendValidationEvent(System.SR.Sch_XmlNsAttribute, attribute);
        }
        if (attribute.SchemaType != null)
        {
            SetParent(attribute.SchemaType, attribute);
            if (!attribute.SchemaTypeName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_TypeMutualExclusive, attribute);
            }
            PreprocessSimpleType(attribute.SchemaType, local: true);
        }
        if (!attribute.SchemaTypeName.IsEmpty)
        {
            ValidateQNameAttribute(attribute, "type", attribute.SchemaTypeName);
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._schema, System.Xml.Schema.SchemaCollectionPreprocessor._xmlns, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType(), System.SR.Sch_DefaultFixedAttributes, System.SR.Sch_ForbiddenAttribute, System.SR.Sch_OptionalDefaultAttribute, System.SR.Sch_TargetNamespaceXsi, System.SR.Sch_TypeMutualExclusive, System.SR.Sch_XmlNsAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), System.Xml.Schema.XmlSchema.TargetNamespace, and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute().