Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError
ParseError()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError (ParseRecord processing, ParseRecord onStack) inline private
Definition at line 230 of file ObjectReader.cs.
    {
        throw new SerializationException(System.SR.Format(System.SR.Serialization_ParseError, onStack._name + " " + onStack._parseTypeEnum.ToString() + " " + processing._name + " " + processing._parseTypeEnum));
    }
References System.Runtime.Serialization.Dictionary, System.SR.Format(), and System.SR.Serialization_ParseError.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMemberEnd().