Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize
Deserialize()
object System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize (BinaryParser serParser) inline package
Definition at line 111 of file ObjectReader.cs.
    {
        if (serParser == null)
        {
            throw new ArgumentNullException("serParser");
        }
        _fullDeserialization = false;
        TopObject = null;
        _topId = 0L;
        _isSimpleAssembly = _formatterEnums._assemblyFormat == FormatterAssemblyStyle.Simple;
        using (SerializationInfo.StartDeserialization())
        {
            if (_fullDeserialization)
            {
                _objectManager = new ObjectManager(_surrogates, _context);
                _serObjectInfoInit = new SerObjectInfoInit();
            }
            serParser.Run();
            if (_fullDeserialization)
            {
                _objectManager.DoFixups();
            }
            if (TopObject == null)
            {
                throw new SerializationException(System.SR.Serialization_TopObject);
            }
            if (HasSurrogate(TopObject.GetType()) && _topId != 0L)
            {
                TopObject = _objectManager.GetObject(_topId);
            }
            if (TopObject is IObjectReference)
            {
                TopObject = ((IObjectReference)TopObject).GetRealObject(_context);
            }
            if (_fullDeserialization)
            {
                _objectManager.RaiseDeserializationEvent();
            }
            return TopObject;
        }
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader._context, System.Runtime.Serialization.Formatters.Binary.ObjectReader._fullDeserialization, System.Runtime.Serialization.Formatters.Binary.ObjectReader._isSimpleAssembly, System.Runtime.Serialization.Formatters.Binary.ObjectReader._objectManager, System.Runtime.Serialization.Formatters.Binary.ObjectReader._serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.ObjectReader._surrogates, System.Runtime.Serialization.Formatters.Binary.ObjectReader._topId, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.ObjectManager.DoFixups(), System.Runtime.Serialization.ObjectManager.GetObject(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.HasSurrogate(), System.L, System.Runtime.Serialization.ObjectManager.RaiseDeserializationEvent(), System.SR.Serialization_TopObject, System.Runtime.Serialization.SerializationInfo.StartDeserialization(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.TopObject.