Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes
PreprocessAttributes()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes (XmlSchemaObjectCollection attributes, XmlSchemaAnyAttribute anyAttribute, XmlSchemaObject parent) inline private
Definition at line 1576 of file SchemaCollectionPreprocessor.cs.
    {
        for (int i = 0; i < attributes.Count; i++)
        {
            SetParent(attributes[i], parent);
            if (attributes[i] is XmlSchemaAttribute attribute)
            {
                PreprocessLocalAttribute(attribute);
                continue;
            }
            XmlSchemaAttributeGroupRef xmlSchemaAttributeGroupRef = (XmlSchemaAttributeGroupRef)attributes[i];
            if (xmlSchemaAttributeGroupRef.RefName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_MissAttribute, "ref", xmlSchemaAttributeGroupRef);
            }
            else
            {
                ValidateQNameAttribute(xmlSchemaAttributeGroupRef, "ref", xmlSchemaAttributeGroupRef.RefName);
            }
            PreprocessAnnotation(attributes[i]);
            ValidateIdAttribute(attributes[i]);
        }
        if (anyAttribute != null)
        {
            try
            {
                SetParent(anyAttribute, parent);
                PreprocessAnnotation(anyAttribute);
                anyAttribute.BuildNamespaceListV1Compat(_targetNamespace);
            }
            catch
            {
                SendValidationEvent(System.SR.Sch_InvalidAnyAttribute, anyAttribute);
            }
            ValidateIdAttribute(anyAttribute);
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Collections.CollectionBase.Count, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute(), System.SR.Sch_InvalidAnyAttribute, System.SR.Sch_MissAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeGroup(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType().