Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement
PreprocessElement()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement (XmlSchemaElement element) inline private
Definition at line 865 of file SchemaCollectionPreprocessor.cs.
    {
        if (element.Name != null)
        {
            ValidateNameAttribute(element);
            element.SetQualifiedName(new XmlQualifiedName(element.Name, _targetNamespace));
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", element);
        }
        PreprocessElementContent(element);
        if (element.Final == XmlSchemaDerivationMethod.All)
        {
            element.SetFinalResolved(XmlSchemaDerivationMethod.All);
        }
        else if (element.Final == XmlSchemaDerivationMethod.None)
        {
            if (_finalDefault == XmlSchemaDerivationMethod.All)
            {
                element.SetFinalResolved(XmlSchemaDerivationMethod.All);
            }
            else
            {
                element.SetFinalResolved(_finalDefault & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
            }
        }
        else
        {
            if (((uint)element.Final & 0xFFFFFFF9u) != 0)
            {
                SendValidationEvent(System.SR.Sch_InvalidElementFinalValue, element);
            }
            element.SetFinalResolved(element.Final & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
        }
        if (element.Form != 0)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "form", element);
        }
        if (element.MinOccursString != null)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "minOccurs", element);
        }
        if (element.MaxOccursString != null)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "maxOccurs", element);
        }
        if (!element.SubstitutionGroup.IsEmpty)
        {
            ValidateQNameAttribute(element, "type", element.SubstitutionGroup);
        }
        ValidateIdAttribute(element);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._finalDefault, System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.XmlSchemaElement.Final, System.Xml.Schema.XmlSchemaElement.Form, System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.XmlSchemaParticle.MaxOccursString, System.Xml.Schema.XmlSchemaParticle.MinOccursString, System.Xml.Schema.XmlSchemaElement.Name, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.SR.Sch_ForbiddenAttribute, System.SR.Sch_InvalidElementFinalValue, System.SR.Sch_MissRequiredAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.XmlSchemaElement.SetFinalResolved(), System.Xml.Schema.XmlSchemaElement.SetQualifiedName(), System.Xml.Schema.XmlSchemaElement.SubstitutionGroup, System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess().