Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation
PreprocessNotation()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation (XmlSchemaNotation notation) inline private
Definition at line 1442 of file SchemaCollectionPreprocessor.cs.
    {
        if (notation.Name != null)
        {
            ValidateNameAttribute(notation);
            notation.QualifiedName = new XmlQualifiedName(notation.Name, _targetNamespace);
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", notation);
        }
        if (notation.Public != null)
        {
            try
            {
                XmlConvert.ToUri(notation.Public);
            }
            catch
            {
                SendValidationEvent(System.SR.Sch_InvalidPublicAttribute, notation.Public, notation);
            }
        }
        else
        {
            SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "public", notation);
        }
        if (notation.System != null)
        {
            try
            {
                XmlConvert.ToUri(notation.System);
            }
            catch
            {
                SendValidationEvent(System.SR.Sch_InvalidSystemAttribute, notation.System, notation);
            }
        }
        PreprocessAnnotation(notation);
        ValidateIdAttribute(notation);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Dictionary, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.SR.Sch_InvalidPublicAttribute, System.SR.Sch_InvalidSystemAttribute, System.SR.Sch_MissRequiredAttribute, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.XmlConvert.ToUri(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess().