Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute
PreprocessLocalAttribute()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute (XmlSchemaAttribute attribute) inline private
Definition at line 783 of file SchemaCollectionPreprocessor.cs.
    {
        if (attribute.Name != null)
        {
            ValidateNameAttribute(attribute);
            PreprocessAttributeContent(attribute);
            attribute.SetQualifiedName(new XmlQualifiedName(attribute.Name, (attribute.Form == XmlSchemaForm.Qualified || (attribute.Form == XmlSchemaForm.None && _attributeFormDefault == XmlSchemaForm.Qualified)) ? _targetNamespace : null));
        }
        else
        {
            PreprocessAnnotation(attribute);
            if (attribute.RefName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_AttributeNameRef, "???", attribute);
            }
            else
            {
                ValidateQNameAttribute(attribute, "ref", attribute.RefName);
            }
            if (!attribute.SchemaTypeName.IsEmpty || attribute.SchemaType != null || attribute.Form != 0)
            {
                SendValidationEvent(System.SR.Sch_InvalidAttributeRef, attribute);
            }
            attribute.SetQualifiedName(attribute.RefName);
        }
        ValidateIdAttribute(attribute);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._attributeFormDefault, System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.SR.Sch_AttributeNameRef, System.SR.Sch_InvalidAttributeRef, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes().