Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals
LoadExternals()
void System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals (XmlSchema schema, XmlSchemaCollection xsc) inline private
Definition at line 115 of file SchemaCollectionPreprocessor.cs.
    {
        if (schema.IsProcessing)
        {
            return;
        }
        schema.IsProcessing = true;
        for (int i = 0; i < schema.Includes.Count; i++)
        {
            XmlSchemaExternal xmlSchemaExternal = (XmlSchemaExternal)schema.Includes[i];
            Uri uri = null;
            if (xmlSchemaExternal.Schema != null)
            {
                if (xmlSchemaExternal is XmlSchemaImport && ((XmlSchemaImport)xmlSchemaExternal).Namespace == "http://www.w3.org/XML/1998/namespace")
                {
                    _buildinIncluded = true;
                    continue;
                }
                uri = xmlSchemaExternal.BaseUri;
                if (uri != null && _schemaLocations[uri] == null)
                {
                    _schemaLocations.Add(uri, uri);
                }
                LoadExternals(xmlSchemaExternal.Schema, xsc);
                continue;
            }
            if (xsc != null && xmlSchemaExternal is XmlSchemaImport)
            {
                XmlSchemaImport xmlSchemaImport = (XmlSchemaImport)xmlSchemaExternal;
                string ns = ((xmlSchemaImport.Namespace != null) ? xmlSchemaImport.Namespace : string.Empty);
                xmlSchemaExternal.Schema = xsc[ns];
                if (xmlSchemaExternal.Schema != null)
                {
                    xmlSchemaExternal.Schema = xmlSchemaExternal.Schema.Clone();
                    if (xmlSchemaExternal.Schema.BaseUri != null && _schemaLocations[xmlSchemaExternal.Schema.BaseUri] == null)
                    {
                        _schemaLocations.Add(xmlSchemaExternal.Schema.BaseUri, xmlSchemaExternal.Schema.BaseUri);
                    }
                    Uri uri2 = null;
                    for (int j = 0; j < xmlSchemaExternal.Schema.Includes.Count; j++)
                    {
                        XmlSchemaExternal xmlSchemaExternal2 = (XmlSchemaExternal)xmlSchemaExternal.Schema.Includes[j];
                        if (!(xmlSchemaExternal2 is XmlSchemaImport))
{
                            continue;
                        }
                        XmlSchemaImport xmlSchemaImport2 = (XmlSchemaImport)xmlSchemaExternal2;
                        uri2 = ((xmlSchemaImport2.BaseUri != null) ? xmlSchemaImport2.BaseUri : ((xmlSchemaImport2.Schema != null && xmlSchemaImport2.Schema.BaseUri != null) ? xmlSchemaImport2.Schema.BaseUri : null));
                        if (uri2 != null)
{
                            if (_schemaLocations[uri2] != null)
{
                                xmlSchemaImport2.Schema = null;
                            }
                            else
{
                                _schemaLocations.Add(uri2, uri2);
                            }
                        }
                    }
                    continue;
                }
            }
            if (xmlSchemaExternal is XmlSchemaImport && ((XmlSchemaImport)xmlSchemaExternal).Namespace == "http://www.w3.org/XML/1998/namespace")
            {
                if (!_buildinIncluded)
                {
                    _buildinIncluded = true;
                    xmlSchemaExternal.Schema = Preprocessor.GetBuildInSchema();
                }
                continue;
            }
            string schemaLocation = xmlSchemaExternal.SchemaLocation;
            if (schemaLocation == null)
            {
                continue;
            }
            Uri uri3 = ResolveSchemaLocationUri(schema, schemaLocation);
            if (!(uri3 != null) || _schemaLocations[uri3] != null)
            {
                continue;
            }
            Stream schemaEntity = GetSchemaEntity(uri3);
            if (schemaEntity != null)
            {
                xmlSchemaExternal.BaseUri = uri3;
                _schemaLocations.Add(uri3, uri3);
                XmlTextReader xmlTextReader = new XmlTextReader(uri3.ToString(), schemaEntity, base.NameTable);
                xmlTextReader.XmlResolver = _xmlResolver;
                try
                {
                    Parser parser = new Parser(SchemaType.XSD, base.NameTable, base.SchemaNames, base.EventHandler);
                    parser.Parse(xmlTextReader, null);
                    while (xmlTextReader.Read())
                    {
                    }
                    xmlSchemaExternal.Schema = parser.XmlSchema;
                    LoadExternals(xmlSchemaExternal.Schema, xsc);
                }
                catch (XmlSchemaException ex)
                {
                    SendValidationEventNoThrow(new XmlSchemaException(System.SR.Sch_CannotLoadSchema, new string[2] { schemaLocation, ex.Message }, ex.SourceUri, ex.LineNumber, ex.LinePosition), XmlSeverityType.Error);
                }
                catch (Exception)
                {
                    SendValidationEvent(System.SR.Sch_InvalidIncludeLocation, xmlSchemaExternal, XmlSeverityType.Warning);
                }
                finally
                {
                    xmlTextReader.Close();
                }
            }
            else
            {
                SendValidationEvent(System.SR.Sch_InvalidIncludeLocation, xmlSchemaExternal, XmlSeverityType.Warning);
            }
        }
        schema.IsProcessing = false;
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._buildinIncluded, System.Xml.Schema.SchemaCollectionPreprocessor._schemaLocations, System.Xml.Schema.SchemaCollectionPreprocessor._xmlResolver, System.Collections.Hashtable.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.Xml.Dictionary, System.Xml.Schema.Preprocessor.GetBuildInSchema(), System.Xml.Schema.SchemaCollectionPreprocessor.GetSchemaEntity(), System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals(), System.Xml.Schema.Namespace, System.Xml.Schema.SchemaCollectionPreprocessor.ResolveSchemaLocationUri(), System.SR.Sch_CannotLoadSchema, System.SR.Sch_InvalidIncludeLocation, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.Xml.Schema.BaseProcessor.SendValidationEventNoThrow().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Execute(), and System.Xml.Schema.SchemaCollectionPreprocessor.LoadExternals().