Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement
PreprocessLocalElement()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement (XmlSchemaElement element) inline private
Definition at line 919 of file SchemaCollectionPreprocessor.cs.
    {
        if (element.Name != null)
        {
            ValidateNameAttribute(element);
            PreprocessElementContent(element);
            element.SetQualifiedName(new XmlQualifiedName(element.Name, (element.Form == XmlSchemaForm.Qualified || (element.Form == XmlSchemaForm.None && _elementFormDefault == XmlSchemaForm.Qualified)) ? _targetNamespace : null));
        }
        else
        {
            PreprocessAnnotation(element);
            if (element.RefName.IsEmpty)
            {
                SendValidationEvent(System.SR.Sch_ElementNameRef, element);
            }
            else
            {
                ValidateQNameAttribute(element, "ref", element.RefName);
            }
            if (!element.SchemaTypeName.IsEmpty || element.IsAbstract || element.Block != XmlSchemaDerivationMethod.None || element.SchemaType != null || element.HasConstraints || element.DefaultValue != null || element.Form != 0 || element.FixedValue != null || element.HasNillableAttribute)
            {
                SendValidationEvent(System.SR.Sch_InvalidElementRef, element);
            }
            if (element.DefaultValue != null && element.FixedValue != null)
            {
                SendValidationEvent(System.SR.Sch_DefaultFixedAttributes, element);
            }
            element.SetQualifiedName(element.RefName);
        }
        if (element.MinOccurs > element.MaxOccurs)
        {
            element.MinOccurs = 0m;
            SendValidationEvent(System.SR.Sch_MinGtMax, element);
        }
        if (element.IsAbstract)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "abstract", element);
        }
        if (element.Final != XmlSchemaDerivationMethod.None)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "final", element);
        }
        if (!element.SubstitutionGroup.IsEmpty)
        {
            SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "substitutionGroup", element);
        }
        ValidateIdAttribute(element);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._elementFormDefault, System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Schema.XmlSchemaElement.Block, System.Xml.Schema.XmlSchemaElement.DefaultValue, System.Xml.Dictionary, System.Xml.Schema.XmlSchemaElement.Final, System.Xml.Schema.XmlSchemaElement.FixedValue, System.Xml.Schema.XmlSchemaElement.Form, System.Xml.Schema.XmlSchemaElement.HasConstraints, System.Xml.Schema.XmlSchemaElement.HasNillableAttribute, System.Xml.Schema.XmlSchemaElement.IsAbstract, System.Xml.XmlQualifiedName.IsEmpty, System.Xml.Schema.XmlSchemaParticle.MaxOccurs, System.Xml.Schema.XmlSchemaParticle.MinOccurs, System.Xml.Schema.XmlSchemaElement.Name, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.Xml.Schema.XmlSchemaElement.RefName, System.SR.Sch_DefaultFixedAttributes, System.SR.Sch_ElementNameRef, System.SR.Sch_ForbiddenAttribute, System.SR.Sch_InvalidElementRef, System.SR.Sch_MinGtMax, System.Xml.Schema.XmlSchemaElement.SchemaType, System.Xml.Schema.XmlSchemaElement.SchemaTypeName, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.XmlSchemaElement.SetQualifiedName(), System.Xml.Schema.XmlSchemaElement.SubstitutionGroup, System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle().