Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute
ValidateQNameAttribute()
void System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute (XmlSchemaObject xso, string attributeName, XmlQualifiedName value) inline private
Definition at line 1659 of file SchemaCollectionPreprocessor.cs.
    {
        try
        {
            value.Verify();
            value.Atomize(base.NameTable);
            if (_referenceNamespaces[value.Namespace] == null)
            {
                SendValidationEvent(System.SR.Sch_UnrefNS, value.Namespace, xso, XmlSeverityType.Warning);
            }
        }
        catch (Exception ex)
        {
            SendValidationEvent(System.SR.Sch_InvalidAttribute, attributeName, ex.Message, xso);
        }
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._referenceNamespaces, System.SR.Sch_InvalidAttribute, System.SR.Sch_UnrefNS, System.Xml.Schema.BaseProcessor.SendValidationEvent(), and System.value.
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType().