Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType
PreprocessComplexType()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType (XmlSchemaComplexType complexType, bool local) inline private
Definition at line 1215 of file SchemaCollectionPreprocessor.cs.
    {
        if (local)
        {
            if (complexType.Name != null)
            {
                SendValidationEvent(System.SR.Sch_ForbiddenAttribute, "name", complexType);
            }
        }
        else
        {
            if (complexType.Name != null)
            {
                ValidateNameAttribute(complexType);
                complexType.SetQualifiedName(new XmlQualifiedName(complexType.Name, _targetNamespace));
            }
            else
            {
                SendValidationEvent(System.SR.Sch_MissRequiredAttribute, "name", complexType);
            }
            if (complexType.Block == XmlSchemaDerivationMethod.All)
            {
                complexType.SetBlockResolved(XmlSchemaDerivationMethod.All);
            }
            else if (complexType.Block == XmlSchemaDerivationMethod.None)
            {
                complexType.SetBlockResolved(_blockDefault & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
            }
            else
            {
                if (((uint)complexType.Block & 0xFFFFFFF9u) != 0)
                {
                    SendValidationEvent(System.SR.Sch_InvalidComplexTypeBlockValue, complexType);
                }
                complexType.SetBlockResolved(complexType.Block & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
            }
            if (complexType.Final == XmlSchemaDerivationMethod.All)
            {
                complexType.SetFinalResolved(XmlSchemaDerivationMethod.All);
            }
            else if (complexType.Final == XmlSchemaDerivationMethod.None)
            {
                if (_finalDefault == XmlSchemaDerivationMethod.All)
                {
                    complexType.SetFinalResolved(XmlSchemaDerivationMethod.All);
                }
                else
                {
                    complexType.SetFinalResolved(_finalDefault & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
                }
            }
            else
            {
                if (((uint)complexType.Final & 0xFFFFFFF9u) != 0)
                {
                    SendValidationEvent(System.SR.Sch_InvalidComplexTypeFinalValue, complexType);
                }
                complexType.SetFinalResolved(complexType.Final & (XmlSchemaDerivationMethod.Extension | XmlSchemaDerivationMethod.Restriction));
            }
        }
        if (complexType.ContentModel != null)
        {
            SetParent(complexType.ContentModel, complexType);
            PreprocessAnnotation(complexType.ContentModel);
            if (complexType.Particle == null)
            {
                _ = complexType.Attributes;
            }
            if (complexType.ContentModel is XmlSchemaSimpleContent)
            {
                XmlSchemaSimpleContent xmlSchemaSimpleContent = (XmlSchemaSimpleContent)complexType.ContentModel;
                if (xmlSchemaSimpleContent.Content == null)
                {
                    if (complexType.QualifiedName == XmlQualifiedName.Empty)
                    {
                        SendValidationEvent(System.SR.Sch_NoRestOrExt, complexType);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_NoRestOrExtQName, complexType.QualifiedName.Name, complexType.QualifiedName.Namespace, complexType);
                    }
                }
                else
                {
                    SetParent(xmlSchemaSimpleContent.Content, xmlSchemaSimpleContent);
                    PreprocessAnnotation(xmlSchemaSimpleContent.Content);
                    if (xmlSchemaSimpleContent.Content is XmlSchemaSimpleContentExtension)
                    {
                        XmlSchemaSimpleContentExtension xmlSchemaSimpleContentExtension = (XmlSchemaSimpleContentExtension)xmlSchemaSimpleContent.Content;
                        if (xmlSchemaSimpleContentExtension.BaseTypeName.IsEmpty)
{
                            SendValidationEvent(System.SR.Sch_MissAttribute, "base", xmlSchemaSimpleContentExtension);
                        }
                        else
{
                            ValidateQNameAttribute(xmlSchemaSimpleContentExtension, "base", xmlSchemaSimpleContentExtension.BaseTypeName);
                        }
                        PreprocessAttributes(xmlSchemaSimpleContentExtension.Attributes, xmlSchemaSimpleContentExtension.AnyAttribute, xmlSchemaSimpleContentExtension);
                        ValidateIdAttribute(xmlSchemaSimpleContentExtension);
                    }
                    else
                    {
                        XmlSchemaSimpleContentRestriction xmlSchemaSimpleContentRestriction = (XmlSchemaSimpleContentRestriction)xmlSchemaSimpleContent.Content;
                        if (xmlSchemaSimpleContentRestriction.BaseTypeName.IsEmpty)
{
                            SendValidationEvent(System.SR.Sch_MissAttribute, "base", xmlSchemaSimpleContentRestriction);
                        }
                        else
{
                            ValidateQNameAttribute(xmlSchemaSimpleContentRestriction, "base", xmlSchemaSimpleContentRestriction.BaseTypeName);
                        }
                        if (xmlSchemaSimpleContentRestriction.BaseType != null)
{
                            SetParent(xmlSchemaSimpleContentRestriction.BaseType, xmlSchemaSimpleContentRestriction);
                            PreprocessSimpleType(xmlSchemaSimpleContentRestriction.BaseType, local: true);
                        }
                        PreprocessAttributes(xmlSchemaSimpleContentRestriction.Attributes, xmlSchemaSimpleContentRestriction.AnyAttribute, xmlSchemaSimpleContentRestriction);
                        ValidateIdAttribute(xmlSchemaSimpleContentRestriction);
                    }
                }
                ValidateIdAttribute(xmlSchemaSimpleContent);
            }
            else
            {
                XmlSchemaComplexContent xmlSchemaComplexContent = (XmlSchemaComplexContent)complexType.ContentModel;
                if (xmlSchemaComplexContent.Content == null)
                {
                    if (complexType.QualifiedName == XmlQualifiedName.Empty)
                    {
                        SendValidationEvent(System.SR.Sch_NoRestOrExt, complexType);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_NoRestOrExtQName, complexType.QualifiedName.Name, complexType.QualifiedName.Namespace, complexType);
                    }
                }
                else
                {
                    if (!xmlSchemaComplexContent.HasMixedAttribute && complexType.IsMixed)
                    {
                        xmlSchemaComplexContent.IsMixed = true;
                    }
                    SetParent(xmlSchemaComplexContent.Content, xmlSchemaComplexContent);
                    PreprocessAnnotation(xmlSchemaComplexContent.Content);
                    if (xmlSchemaComplexContent.Content is XmlSchemaComplexContentExtension)
                    {
                        XmlSchemaComplexContentExtension xmlSchemaComplexContentExtension = (XmlSchemaComplexContentExtension)xmlSchemaComplexContent.Content;
                        if (xmlSchemaComplexContentExtension.BaseTypeName.IsEmpty)
{
                            SendValidationEvent(System.SR.Sch_MissAttribute, "base", xmlSchemaComplexContentExtension);
                        }
                        else
{
                            ValidateQNameAttribute(xmlSchemaComplexContentExtension, "base", xmlSchemaComplexContentExtension.BaseTypeName);
                        }
                        if (xmlSchemaComplexContentExtension.Particle != null)
{
                            SetParent(xmlSchemaComplexContentExtension.Particle, xmlSchemaComplexContentExtension);
                            PreprocessParticle(xmlSchemaComplexContentExtension.Particle);
                        }
                        PreprocessAttributes(xmlSchemaComplexContentExtension.Attributes, xmlSchemaComplexContentExtension.AnyAttribute, xmlSchemaComplexContentExtension);
                        ValidateIdAttribute(xmlSchemaComplexContentExtension);
                    }
                    else
                    {
                        XmlSchemaComplexContentRestriction xmlSchemaComplexContentRestriction = (XmlSchemaComplexContentRestriction)xmlSchemaComplexContent.Content;
                        if (xmlSchemaComplexContentRestriction.BaseTypeName.IsEmpty)
{
                            SendValidationEvent(System.SR.Sch_MissAttribute, "base", xmlSchemaComplexContentRestriction);
                        }
                        else
{
                            ValidateQNameAttribute(xmlSchemaComplexContentRestriction, "base", xmlSchemaComplexContentRestriction.BaseTypeName);
                        }
                        if (xmlSchemaComplexContentRestriction.Particle != null)
{
                            SetParent(xmlSchemaComplexContentRestriction.Particle, xmlSchemaComplexContentRestriction);
                            PreprocessParticle(xmlSchemaComplexContentRestriction.Particle);
                        }
                        PreprocessAttributes(xmlSchemaComplexContentRestriction.Attributes, xmlSchemaComplexContentRestriction.AnyAttribute, xmlSchemaComplexContentRestriction);
                        ValidateIdAttribute(xmlSchemaComplexContentRestriction);
                    }
                    ValidateIdAttribute(xmlSchemaComplexContent);
                }
            }
        }
        else
        {
            if (complexType.Particle != null)
            {
                SetParent(complexType.Particle, complexType);
                PreprocessParticle(complexType.Particle);
            }
            PreprocessAttributes(complexType.Attributes, complexType.AnyAttribute, complexType);
        }
        ValidateIdAttribute(complexType);
    }
References System.Xml.Schema.SchemaCollectionPreprocessor._blockDefault, System.Xml.Schema.SchemaCollectionPreprocessor._finalDefault, System.Xml.Schema.SchemaCollectionPreprocessor._targetNamespace, System.Xml.Dictionary, System.Xml.XmlQualifiedName.Empty, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType(), System.SR.Sch_ForbiddenAttribute, System.SR.Sch_InvalidComplexTypeBlockValue, System.SR.Sch_InvalidComplexTypeFinalValue, System.SR.Sch_MissAttribute, System.SR.Sch_MissRequiredAttribute, System.SR.Sch_NoRestOrExt, System.SR.Sch_NoRestOrExtQName, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateIdAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.ValidateNameAttribute(), and System.Xml.Schema.SchemaCollectionPreprocessor.ValidateQNameAttribute().
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine().