Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation
PreprocessAnnotation()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAnnotation (XmlSchemaObject schemaObject) inline private
Definition at line 1681 of file SchemaCollectionPreprocessor.cs.
    {
        if (schemaObject is XmlSchemaAnnotated { Annotation: not null } xmlSchemaAnnotated)
        {
            xmlSchemaAnnotated.Annotation.Parent = schemaObject;
            for (int i = 0; i < xmlSchemaAnnotated.Annotation.Items.Count; i++)
            {
                xmlSchemaAnnotated.Annotation.Items[i].Parent = xmlSchemaAnnotated.Annotation;
            }
        }
    }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, and System.Xml.Dictionary.
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalAttribute(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessLocalElement(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessNotation(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType().