Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine
PreprocessRedefine()
void System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine (XmlSchemaRedefine redefine) inline private
Definition at line 548 of file SchemaCollectionPreprocessor.cs.
    {
        for (int i = 0; i < redefine.Items.Count; i++)
        {
            SetParent(redefine.Items[i], redefine);
            if (redefine.Items[i] is XmlSchemaGroup xmlSchemaGroup)
            {
                PreprocessGroup(xmlSchemaGroup);
                if (redefine.Groups[xmlSchemaGroup.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_GroupDoubleRedefine, xmlSchemaGroup);
                    continue;
                }
                AddToTable(redefine.Groups, xmlSchemaGroup.QualifiedName, xmlSchemaGroup);
                xmlSchemaGroup.Redefined = (XmlSchemaGroup)redefine.Schema.Groups[xmlSchemaGroup.QualifiedName];
                if (xmlSchemaGroup.Redefined != null)
                {
                    CheckRefinedGroup(xmlSchemaGroup);
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_GroupRedefineNotFound, xmlSchemaGroup);
                }
            }
            else if (redefine.Items[i] is XmlSchemaAttributeGroup)
            {
                XmlSchemaAttributeGroup xmlSchemaAttributeGroup = (XmlSchemaAttributeGroup)redefine.Items[i];
                PreprocessAttributeGroup(xmlSchemaAttributeGroup);
                if (redefine.AttributeGroups[xmlSchemaAttributeGroup.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_AttrGroupDoubleRedefine, xmlSchemaAttributeGroup);
                    continue;
                }
                AddToTable(redefine.AttributeGroups, xmlSchemaAttributeGroup.QualifiedName, xmlSchemaAttributeGroup);
                xmlSchemaAttributeGroup.Redefined = (XmlSchemaAttributeGroup)redefine.Schema.AttributeGroups[xmlSchemaAttributeGroup.QualifiedName];
                if (xmlSchemaAttributeGroup.Redefined != null)
                {
                    CheckRefinedAttributeGroup(xmlSchemaAttributeGroup);
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_AttrGroupRedefineNotFound, xmlSchemaAttributeGroup);
                }
            }
            else if (redefine.Items[i] is XmlSchemaComplexType)
            {
                XmlSchemaComplexType xmlSchemaComplexType = (XmlSchemaComplexType)redefine.Items[i];
                PreprocessComplexType(xmlSchemaComplexType, local: false);
                if (redefine.SchemaTypes[xmlSchemaComplexType.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_ComplexTypeDoubleRedefine, xmlSchemaComplexType);
                    continue;
                }
                AddToTable(redefine.SchemaTypes, xmlSchemaComplexType.QualifiedName, xmlSchemaComplexType);
                XmlSchemaType xmlSchemaType = (XmlSchemaType)redefine.Schema.SchemaTypes[xmlSchemaComplexType.QualifiedName];
                if (xmlSchemaType != null)
                {
                    if (xmlSchemaType is XmlSchemaComplexType)
                    {
                        xmlSchemaComplexType.Redefined = xmlSchemaType;
                        CheckRefinedComplexType(xmlSchemaComplexType);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_SimpleToComplexTypeRedefine, xmlSchemaComplexType);
                    }
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_ComplexTypeRedefineNotFound, xmlSchemaComplexType);
                }
            }
            else
            {
                if (!(redefine.Items[i] is XmlSchemaSimpleType))
                {
                    continue;
                }
                XmlSchemaSimpleType xmlSchemaSimpleType = (XmlSchemaSimpleType)redefine.Items[i];
                PreprocessSimpleType(xmlSchemaSimpleType, local: false);
                if (redefine.SchemaTypes[xmlSchemaSimpleType.QualifiedName] != null)
                {
                    SendValidationEvent(System.SR.Sch_SimpleTypeDoubleRedefine, xmlSchemaSimpleType);
                    continue;
                }
                AddToTable(redefine.SchemaTypes, xmlSchemaSimpleType.QualifiedName, xmlSchemaSimpleType);
                XmlSchemaType xmlSchemaType2 = (XmlSchemaType)redefine.Schema.SchemaTypes[xmlSchemaSimpleType.QualifiedName];
                if (xmlSchemaType2 != null)
                {
                    if (xmlSchemaType2 is XmlSchemaSimpleType)
                    {
                        xmlSchemaSimpleType.Redefined = xmlSchemaType2;
                        CheckRefinedSimpleType(xmlSchemaSimpleType);
                    }
                    else
                    {
                        SendValidationEvent(System.SR.Sch_ComplexToSimpleTypeRedefine, xmlSchemaSimpleType);
                    }
                }
                else
                {
                    SendValidationEvent(System.SR.Sch_SimpleTypeRedefineNotFound, xmlSchemaSimpleType);
                }
            }
        }
        foreach (DictionaryEntry group in redefine.Groups)
        {
            redefine.Schema.Groups.Insert((XmlQualifiedName)group.Key, (XmlSchemaObject)group.Value);
        }
        foreach (DictionaryEntry attributeGroup in redefine.AttributeGroups)
        {
            redefine.Schema.AttributeGroups.Insert((XmlQualifiedName)attributeGroup.Key, (XmlSchemaObject)attributeGroup.Value);
        }
        foreach (DictionaryEntry schemaType in redefine.SchemaTypes)
        {
            redefine.Schema.SchemaTypes.Insert((XmlQualifiedName)schemaType.Key, (XmlSchemaObject)schemaType.Value);
        }
    }
References System.Xml.Schema.BaseProcessor.AddToTable(), System.Xml.Schema.XmlSchema.AttributeGroups, System.Xml.Schema.XmlSchemaRedefine.AttributeGroups, System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.CheckRefinedSimpleType(), System.Collections.CollectionBase.Count, System.Xml.Dictionary, System.Xml.Schema.XmlSchema.Groups, System.Xml.Schema.XmlSchemaRedefine.Groups, System.Xml.Schema.XmlSchemaRedefine.Items, System.Collections.DictionaryEntry.Key, System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessGroup(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType(), System.SR.Sch_AttrGroupDoubleRedefine, System.SR.Sch_AttrGroupRedefineNotFound, System.SR.Sch_ComplexToSimpleTypeRedefine, System.SR.Sch_ComplexTypeDoubleRedefine, System.SR.Sch_ComplexTypeRedefineNotFound, System.SR.Sch_GroupDoubleRedefine, System.SR.Sch_GroupRedefineNotFound, System.SR.Sch_SimpleToComplexTypeRedefine, System.SR.Sch_SimpleTypeDoubleRedefine, System.SR.Sch_SimpleTypeRedefineNotFound, System.Xml.Schema.XmlSchemaExternal.Schema, System.Xml.Schema.XmlSchema.SchemaTypes, System.Xml.Schema.XmlSchemaRedefine.SchemaTypes, System.Xml.Schema.BaseProcessor.SendValidationEvent(), System.Xml.Schema.SchemaCollectionPreprocessor.SetParent(), and System.Collections.DictionaryEntry.Value.
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess().