Terraria: System.Xml.Schema.SchemaCollectionPreprocessor.SetParent
SetParent()
void System.Xml.Schema.SchemaCollectionPreprocessor.SetParent (XmlSchemaObject child, XmlSchemaObject parent) inline private
Definition at line 1676 of file SchemaCollectionPreprocessor.cs.
    {
        child.Parent = parent;
    }
References System.Xml.Dictionary.
Referenced by System.Xml.Schema.SchemaCollectionPreprocessor.Preprocess(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributeContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessAttributes(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessComplexType(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessElementContent(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessIdentityConstraint(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessParticle(), System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessRedefine(), and System.Xml.Schema.SchemaCollectionPreprocessor.PreprocessSimpleType().