Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable
CheckSerializable()
void System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable (Type t) inline private
Definition at line 163 of file ObjectReader.cs.
    {
        if (!t.IsSerializable && !HasSurrogate(t))
        {
            throw new SerializationException(System.SR.Format(CultureInfo.InvariantCulture, System.SR.Serialization_NonSerType, t.FullName, t.Assembly.FullName));
        }
    }
References System.Type.Assembly, System.SR.Format(), System.Reflection.Assembly.FullName, System.Type.FullName, System.Runtime.Serialization.Formatters.Binary.ObjectReader.HasSurrogate(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsSerializable, and System.SR.Serialization_NonSerType.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject().