Terraria: System.Xml.Xsl.Qil.QilFactory.False
False()
QilNode System.Xml.Xsl.Qil.QilFactory.False () inline
Definition at line 212 of file QilFactory.cs.
    {
        QilNode qilNode = new QilNode(QilNodeType.False);
        qilNode.XmlType = _typeCheck.CheckFalse(qilNode);
        return qilNode;
    }
References System.Xml.Xsl.Qil.QilFactory._typeCheck, System.Xml.Xsl.Qil.QilTypeChecker.CheckFalse(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilExpression.QilExpression(), System.Xml.Xsl.Qil.QilPatternFactory.False(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldComparison(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.FoldXsltConvert(), System.Xml.Xsl.Qil.QilPatternFactory.Not(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitAfter(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitBefore(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsEmpty(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitIsType(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitNot().