Terraria: System.Xml.Xsl.XsltOld.XsltOutput.CompileAttribute
CompileAttribute()
override bool System.Xml.Xsl.XsltOld.XsltOutput.CompileAttribute (Compiler compiler) inline package virtual
Reimplemented from System.Xml.Xsl.XsltOld.CompiledAction.
Definition at line 92 of file XsltOutput.cs.
    {
        string localName = compiler.Input.LocalName;
        string value = compiler.Input.Value;
        if (Ref.Equal(localName, compiler.Atoms.Method))
        {
            if (compiler.Stylesheetid <= _methodSId)
            {
                _method = ParseOutputMethod(value, compiler);
                _methodSId = compiler.Stylesheetid;
                if (_indentSId == int.MaxValue)
                {
                    _indent = _method == OutputMethod.Html;
                }
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.Version))
        {
            if (compiler.Stylesheetid <= _versionSId)
            {
                _version = value;
                _versionSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.Encoding))
        {
            if (compiler.Stylesheetid <= _encodingSId)
            {
                try
                {
                    _encoding = Encoding.GetEncoding(value);
                    _encodingSId = compiler.Stylesheetid;
                }
                catch (NotSupportedException)
                {
                }
                catch (ArgumentException)
                {
                }
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.OmitXmlDeclaration))
        {
            if (compiler.Stylesheetid <= _omitXmlDeclSId)
            {
                _omitXmlDecl = compiler.GetYesNo(value);
                _omitXmlDeclSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.Standalone))
        {
            if (compiler.Stylesheetid <= _standaloneSId)
            {
                _standalone = compiler.GetYesNo(value);
                _standaloneSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.DocTypePublic))
        {
            if (compiler.Stylesheetid <= _doctypePublicSId)
            {
                _doctypePublic = value;
                _doctypePublicSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.DocTypeSystem))
        {
            if (compiler.Stylesheetid <= _doctypeSystemSId)
            {
                _doctypeSystem = value;
                _doctypeSystemSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.Indent))
        {
            if (compiler.Stylesheetid <= _indentSId)
            {
                _indent = compiler.GetYesNo(value);
                _indentSId = compiler.Stylesheetid;
            }
        }
        else if (Ref.Equal(localName, compiler.Atoms.MediaType))
        {
            if (compiler.Stylesheetid <= _mediaTypeSId)
            {
                _mediaType = value;
                _mediaTypeSId = compiler.Stylesheetid;
            }
        }
        else
        {
            if (!Ref.Equal(localName, compiler.Atoms.CDataSectionElements))
            {
                return false;
            }
            string[] array = XmlConvert.SplitString(value);
            if (_cdataElements == null)
            {
                _cdataElements = new Hashtable(array.Length);
            }
            for (int i = 0; i < array.Length; i++)
            {
                XmlQualifiedName xmlQualifiedName = compiler.CreateXmlQName(array[i]);
                _cdataElements[xmlQualifiedName] = xmlQualifiedName;
            }
        }
        return true;
    }
References System.Xml.Xsl.XsltOld.XsltOutput._cdataElements, System.Xml.Xsl.XsltOld.XsltOutput._doctypePublic, System.Xml.Xsl.XsltOld.XsltOutput._doctypePublicSId, System.Xml.Xsl.XsltOld.XsltOutput._doctypeSystem, System.Xml.Xsl.XsltOld.XsltOutput._doctypeSystemSId, System.Xml.Xsl.XsltOld.XsltOutput._encoding, System.Xml.Xsl.XsltOld.XsltOutput._encodingSId, System.Xml.Xsl.XsltOld.XsltOutput._indent, System.Xml.Xsl.XsltOld.XsltOutput._indentSId, System.Xml.Xsl.XsltOld.XsltOutput._mediaType, System.Xml.Xsl.XsltOld.XsltOutput._mediaTypeSId, System.Xml.Xsl.XsltOld.XsltOutput._method, System.Xml.Xsl.XsltOld.XsltOutput._methodSId, System.Xml.Xsl.XsltOld.XsltOutput._omitXmlDecl, System.Xml.Xsl.XsltOld.XsltOutput._omitXmlDeclSId, System.Xml.Xsl.XsltOld.XsltOutput._standalone, System.Xml.Xsl.XsltOld.XsltOutput._standaloneSId, System.Xml.Xsl.XsltOld.XsltOutput._version, System.Xml.Xsl.XsltOld.XsltOutput._versionSId, System.array, System.Xml.Dictionary, System.Xml.Ref.Equal(), System.Text.Encoding.GetEncoding(), System.Xml.Xsl.XsltOld.XsltOutput.ParseOutputMethod(), System.Xml.XmlConvert.SplitString(), and System.value.