Terraria: System.Xml.Xsl.Qil.QilFactory.For
For()
QilIterator System.Xml.Xsl.Qil.QilFactory.For (QilNode binding) inline
Definition at line 177 of file QilFactory.cs.
    {
        QilIterator qilIterator = new QilIterator(QilNodeType.For, binding);
        qilIterator.XmlType = _typeCheck.CheckFor(qilIterator);
        return qilIterator;
    }
References System.Xml.Xsl.Qil.QilFactory._typeCheck, System.Xml.Xsl.Qil.QilTypeChecker.CheckFor(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilPatternFactory.For(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitDocOrderDistinct(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitEq(), System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitFilter(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitLoop().