Terraria: System.Xml.Schema.Datatype_integer.TryParseValue
TryParseValue() [2/2]
override Exception System.Xml.Schema.Datatype_integer.TryParseValue (string s, XmlNameTable nameTable, IXmlNamespaceResolver nsmgr, out object typedValue) inline package inherited
Definition at line 7 of file Datatype_integer.cs.
    {
        typedValue = null;
        Exception ex = FacetsChecker.CheckLexicalFacets(ref s, this);
        if (ex == null)
        {
            ex = XmlConvert.TryToInteger(s, out var result);
            if (ex == null)
            {
                ex = FacetsChecker.CheckValueFacets(result, this);
                if (ex == null)
                {
                    typedValue = result;
                    return null;
                }
            }
        }
        return ex;
    }
References System.Xml.Schema.FacetsChecker.CheckLexicalFacets(), System.Xml.Schema.FacetsChecker.CheckValueFacets(), System.Xml.Dictionary, System.s, and System.Xml.XmlConvert.TryToInteger().