Terraria: System.Xml.Xsl.Qil.QilFactory.Union
Union()
QilBinary System.Xml.Xsl.Qil.QilFactory.Union (QilNode left, QilNode right) inline
Definition at line 324 of file QilFactory.cs.
    {
        QilBinary qilBinary = new QilBinary(QilNodeType.Union, left, right);
        qilBinary.XmlType = _typeCheck.CheckUnion(qilBinary);
        return qilBinary;
    }
References System.Xml.Xsl.Qil.QilFactory._typeCheck, System.Xml.Xsl.Qil.QilTypeChecker.CheckUnion(), and System.Xml.Dictionary.
Referenced by System.Xml.Xsl.Qil.QilPatternFactory.Union(), and System.Xml.Xsl.IlGen.XmlILOptimizerVisitor.VisitUnion().