Terraria: System.Security.Principal.Win32.CreateSidFromString
CreateSidFromString()
static int System.Security.Principal.Win32.CreateSidFromString (string stringSid, out byte[] resultSid) inline static package
Definition at line 49 of file Win32.cs.
    {
        IntPtr ByteArray = IntPtr.Zero;
        int lastWin32Error;
        try
        {
            if (global::Interop.Advapi32.ConvertStringSidToSid(stringSid, out ByteArray) == 0)
            {
                lastWin32Error = Marshal.GetLastWin32Error();
                goto IL_002b;
            }
            resultSid = ConvertIntPtrSidToByteArraySid(ByteArray);
        }
        finally
        {
            Marshal.FreeHGlobal(ByteArray);
        }
        return 0;
        IL_002b:
        resultSid = null;
        return lastWin32Error;
    }
References System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.IntPtr.Zero.
Referenced by System.Security.Principal.SecurityIdentifier.SecurityIdentifier().