Terraria: System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid
ConvertIntPtrSidToByteArraySid()
static byte[] System.Security.Principal.Win32.ConvertIntPtrSidToByteArraySid (IntPtr binaryForm) inline static package
Definition at line 31 of file Win32.cs.
    {
        byte b = Marshal.ReadByte(binaryForm, 0);
        if (b != SecurityIdentifier.Revision)
        {
            throw new ArgumentException(System.SR.IdentityReference_InvalidSidRevision, "binaryForm");
        }
        byte b2 = Marshal.ReadByte(binaryForm, 1);
        if (b2 < 0 || b2 > 15)
        {
            throw new ArgumentException(System.SR.Format(System.SR.IdentityReference_InvalidNumberOfSubauthorities, 15), "binaryForm");
        }
        int num = 8 + b2 * 4;
        byte[] array = new byte[num];
        Marshal.Copy(binaryForm, array, 0, num);
        return array;
    }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.SR.Format(), System.SR.IdentityReference_InvalidNumberOfSubauthorities, System.SR.IdentityReference_InvalidSidRevision, System.Runtime.InteropServices.Marshal.ReadByte(), and System.Security.Principal.SecurityIdentifier.Revision.
Referenced by System.Security.Principal.Win32.CreateSidFromString().