Terraria: System.Security.Principal.Win32.GetWindowsAccountDomainSid
GetWindowsAccountDomainSid()
static int System.Security.Principal.Win32.GetWindowsAccountDomainSid (SecurityIdentifier sid, out SecurityIdentifier resultSid) inline static package
Definition at line 126 of file Win32.cs.
    {
        byte[] array = new byte[sid.BinaryLength];
        sid.GetBinaryForm(array, 0);
        uint resultSidLength = (uint)SecurityIdentifier.MaxBinaryLength;
        byte[] array2 = new byte[resultSidLength];
        if (global::Interop.Advapi32.GetWindowsAccountDomainSid(array, array2, ref resultSidLength) != 0)
        {
            resultSid = new SecurityIdentifier(array2, 0);
            return 0;
        }
        resultSid = null;
        return Marshal.GetLastWin32Error();
    }
References System.array, System.Security.Principal.SecurityIdentifier.BinaryLength, System.Security.Principal.SecurityIdentifier.GetBinaryForm(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), and System.Security.Principal.SecurityIdentifier.MaxBinaryLength.
Referenced by System.Security.Principal.SecurityIdentifier.SecurityIdentifier(), and System.Security.Principal.SecurityIdentifier.GetAccountDomainSid().