Terraria: System.Security.Principal.Win32.InitializeReferencedDomainsPointer
InitializeReferencedDomainsPointer()
static unsafe void System.Security.Principal.Win32.InitializeReferencedDomainsPointer (SafeLsaMemoryHandle referencedDomains) inline static package
Definition at line 101 of file Win32.cs.
    {
        referencedDomains.Initialize((uint)Marshal.SizeOf<global::Interop.LSA_REFERENCED_DOMAIN_LIST>());
        global::Interop.LSA_REFERENCED_DOMAIN_LIST lSA_REFERENCED_DOMAIN_LIST = referencedDomains.Read<global::Interop.LSA_REFERENCED_DOMAIN_LIST>(0uL);
        byte* pointer = null;
        try
        {
            referencedDomains.AcquirePointer(ref pointer);
            if (lSA_REFERENCED_DOMAIN_LIST.Domains != IntPtr.Zero)
            {
                global::Interop.LSA_TRUST_INFORMATION* ptr = (global::Interop.LSA_TRUST_INFORMATION*)(void*)lSA_REFERENCED_DOMAIN_LIST.Domains;
                ptr += lSA_REFERENCED_DOMAIN_LIST.Entries;
                long numBytes = (byte*)ptr - pointer;
                referencedDomains.Initialize((ulong)numBytes);
            }
        }
        finally
        {
            if (pointer != null)
            {
                referencedDomains.ReleasePointer();
            }
        }
    }
References System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.Runtime.InteropServices.SafeBuffer.Initialize(), System.pointer, System.Runtime.InteropServices.SafeBuffer.ReleasePointer(), System.Runtime.InteropServices.Marshal.SizeOf(), and System.IntPtr.Zero.
Referenced by System.Security.Principal.SecurityIdentifier.TranslateToNTAccounts(), and System.Security.Principal.NTAccount.TranslateToSids().