Terraria: System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap
ObjectMap() [1/2]
System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap (string objectName, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] Type objectType, string[] memberNames, ObjectReader objectReader, int objectId, BinaryAssemblyInfo assemblyInfo) inline package
Definition at line 29 of file ObjectMap.cs.
    {
        _objectName = objectName;
        _objectType = objectType;
        _memberNames = memberNames;
        _objectReader = objectReader;
        _objectId = objectId;
        _assemblyInfo = assemblyInfo;
        _objectInfo = objectReader.CreateReadObjectInfo(objectType);
        _memberTypes = _objectInfo.GetMemberTypes(memberNames, objectType);
        _binaryTypeEnumA = new BinaryTypeEnum[_memberTypes.Length];
        _typeInformationA = new object[_memberTypes.Length];
        for (int i = 0; i < _memberTypes.Length; i++)
        {
            object typeInformation;
            BinaryTypeEnum parserBinaryTypeInfo = BinaryTypeConverter.GetParserBinaryTypeInfo(_memberTypes[i], out typeInformation);
            _binaryTypeEnumA[i] = parserBinaryTypeInfo;
            _typeInformationA[i] = typeInformation;
        }
    }
References System.Runtime.Serialization.Formatters.Binary.ObjectMap._assemblyInfo, System.Runtime.Serialization.Formatters.Binary.ObjectMap._binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectMap._memberNames, System.Runtime.Serialization.Formatters.Binary.ObjectMap._memberTypes, System.Runtime.Serialization.Formatters.Binary.ObjectMap._objectId, System.Runtime.Serialization.Formatters.Binary.ObjectMap._objectInfo, System.Runtime.Serialization.Formatters.Binary.ObjectMap._objectName, System.Runtime.Serialization.Formatters.Binary.ObjectMap._objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectMap._objectType, System.Runtime.Serialization.Formatters.Binary.ObjectMap._typeInformationA, System.Runtime.Serialization.Dictionary, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes(), and System.Runtime.Serialization.Formatters.Binary.BinaryTypeConverter.GetParserBinaryTypeInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(), and System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create().