Terraria: System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataSizes
MetadataSizes()
System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataSizes (ImmutableArray< int > rowCounts, ImmutableArray< int > externalRowCounts, ImmutableArray< int > heapSizes, int metadataVersionByteCount, bool isStandaloneDebugMetadata) inline package
Definition at line 100 of file MetadataSizes.cs.
    {
        RowCounts = rowCounts;
        ExternalRowCounts = externalRowCounts;
        HeapSizes = heapSizes;
        MetadataVersionPaddedLength = BitArithmetic.Align(metadataVersionByteCount + 1, 4);
        PresentTablesMask = ComputeNonEmptyTableMask(rowCounts);
        ExternalTablesMask = ComputeNonEmptyTableMask(externalRowCounts);
        bool flag = IsPresent(TableIndex.EncLog) || IsPresent(TableIndex.EncMap);
        bool flag2 = !flag;
        IsEncDelta = flag;
        IsCompressed = flag2;
        BlobReferenceIsSmall = flag2 && heapSizes[2] <= 65535;
        StringReferenceIsSmall = flag2 && heapSizes[1] <= 65535;
        GuidReferenceIsSmall = flag2 && heapSizes[3] <= 65535;
        CustomAttributeTypeCodedIndexIsSmall = IsReferenceSmall(3, TableIndex.MethodDef, TableIndex.MemberRef);
        DeclSecurityCodedIndexIsSmall = IsReferenceSmall(2, TableIndex.MethodDef, TableIndex.TypeDef);
        EventDefReferenceIsSmall = IsReferenceSmall(0, TableIndex.Event);
        FieldDefReferenceIsSmall = IsReferenceSmall(0, TableIndex.Field);
        GenericParamReferenceIsSmall = IsReferenceSmall(0, TableIndex.GenericParam);
        HasConstantCodedIndexIsSmall = IsReferenceSmall(2, TableIndex.Field, TableIndex.Param, TableIndex.Property);
        HasCustomAttributeCodedIndexIsSmall = IsReferenceSmall(5, TableIndex.MethodDef, TableIndex.Field, TableIndex.TypeRef, TableIndex.TypeDef, TableIndex.Param, TableIndex.InterfaceImpl, TableIndex.MemberRef, TableIndex.Module, TableIndex.DeclSecurity, TableIndex.Property, TableIndex.Event, TableIndex.StandAloneSig, TableIndex.ModuleRef, TableIndex.TypeSpec, TableIndex.Assembly, TableIndex.AssemblyRef, TableIndex.File, TableIndex.ExportedType, TableIndex.ManifestResource, TableIndex.GenericParam, TableIndex.GenericParamConstraint, TableIndex.MethodSpec);
        HasFieldMarshalCodedIndexIsSmall = IsReferenceSmall(1, TableIndex.Field, TableIndex.Param);
        HasSemanticsCodedIndexIsSmall = IsReferenceSmall(1, TableIndex.Event, TableIndex.Property);
        ImplementationCodedIndexIsSmall = IsReferenceSmall(2, TableIndex.File, TableIndex.AssemblyRef, TableIndex.ExportedType);
        MemberForwardedCodedIndexIsSmall = IsReferenceSmall(1, TableIndex.Field, TableIndex.MethodDef);
        MemberRefParentCodedIndexIsSmall = IsReferenceSmall(3, TableIndex.TypeDef, TableIndex.TypeRef, TableIndex.ModuleRef, TableIndex.MethodDef, TableIndex.TypeSpec);
        MethodDefReferenceIsSmall = IsReferenceSmall(0, TableIndex.MethodDef);
        MethodDefOrRefCodedIndexIsSmall = IsReferenceSmall(1, TableIndex.MethodDef, TableIndex.MemberRef);
        ModuleRefReferenceIsSmall = IsReferenceSmall(0, TableIndex.ModuleRef);
        ParameterReferenceIsSmall = IsReferenceSmall(0, TableIndex.Param);
        PropertyDefReferenceIsSmall = IsReferenceSmall(0, TableIndex.Property);
        ResolutionScopeCodedIndexIsSmall = IsReferenceSmall(2, TableIndex.Module, TableIndex.ModuleRef, TableIndex.AssemblyRef, TableIndex.TypeRef);
        TypeDefReferenceIsSmall = IsReferenceSmall(0, TableIndex.TypeDef);
        TypeDefOrRefCodedIndexIsSmall = IsReferenceSmall(2, TableIndex.TypeDef, TableIndex.TypeRef, TableIndex.TypeSpec);
        TypeOrMethodDefCodedIndexIsSmall = IsReferenceSmall(1, TableIndex.TypeDef, TableIndex.MethodDef);
        DocumentReferenceIsSmall = IsReferenceSmall(0, TableIndex.Document);
        LocalVariableReferenceIsSmall = IsReferenceSmall(0, TableIndex.LocalVariable);
        LocalConstantReferenceIsSmall = IsReferenceSmall(0, TableIndex.LocalConstant);
        ImportScopeReferenceIsSmall = IsReferenceSmall(0, TableIndex.ImportScope);
        HasCustomDebugInformationCodedIndexIsSmall = IsReferenceSmall(5, TableIndex.MethodDef, TableIndex.Field, TableIndex.TypeRef, TableIndex.TypeDef, TableIndex.Param, TableIndex.InterfaceImpl, TableIndex.MemberRef, TableIndex.Module, TableIndex.DeclSecurity, TableIndex.Property, TableIndex.Event, TableIndex.StandAloneSig, TableIndex.ModuleRef, TableIndex.TypeSpec, TableIndex.Assembly, TableIndex.AssemblyRef, TableIndex.File, TableIndex.ExportedType, TableIndex.ManifestResource, TableIndex.GenericParam, TableIndex.GenericParamConstraint, TableIndex.MethodSpec, TableIndex.Document, TableIndex.LocalScope, TableIndex.LocalVariable, TableIndex.LocalConstant, TableIndex.ImportScope);
        int num = CalculateTableStreamHeaderSize();
        byte b = (byte)(BlobReferenceIsSmall ? 2 : 4);
        byte b2 = (byte)(StringReferenceIsSmall ? 2 : 4);
        byte b3 = (byte)(GuidReferenceIsSmall ? 2 : 4);
        byte b4 = (byte)(CustomAttributeTypeCodedIndexIsSmall ? 2 : 4);
        byte b5 = (byte)(DeclSecurityCodedIndexIsSmall ? 2 : 4);
        byte b6 = (byte)(EventDefReferenceIsSmall ? 2 : 4);
        byte b7 = (byte)(FieldDefReferenceIsSmall ? 2 : 4);
        byte b8 = (byte)(GenericParamReferenceIsSmall ? 2 : 4);
        byte b9 = (byte)(HasConstantCodedIndexIsSmall ? 2 : 4);
        byte b10 = (byte)(HasCustomAttributeCodedIndexIsSmall ? 2 : 4);
        byte b11 = (byte)(HasFieldMarshalCodedIndexIsSmall ? 2 : 4);
        byte b12 = (byte)(HasSemanticsCodedIndexIsSmall ? 2 : 4);
        byte b13 = (byte)(ImplementationCodedIndexIsSmall ? 2 : 4);
        byte b14 = (byte)(MemberForwardedCodedIndexIsSmall ? 2 : 4);
        byte b15 = (byte)(MemberRefParentCodedIndexIsSmall ? 2 : 4);
        byte b16 = (byte)(MethodDefReferenceIsSmall ? 2 : 4);
        byte b17 = (byte)(MethodDefOrRefCodedIndexIsSmall ? 2 : 4);
        byte b18 = (byte)(ModuleRefReferenceIsSmall ? 2 : 4);
        byte b19 = (byte)(ParameterReferenceIsSmall ? 2 : 4);
        byte b20 = (byte)(PropertyDefReferenceIsSmall ? 2 : 4);
        byte b21 = (byte)(ResolutionScopeCodedIndexIsSmall ? 2 : 4);
        byte b22 = (byte)(TypeDefReferenceIsSmall ? 2 : 4);
        byte b23 = (byte)(TypeDefOrRefCodedIndexIsSmall ? 2 : 4);
        byte b24 = (byte)(TypeOrMethodDefCodedIndexIsSmall ? 2 : 4);
        byte b25 = (byte)(DocumentReferenceIsSmall ? 2 : 4);
        byte b26 = (byte)(LocalVariableReferenceIsSmall ? 2 : 4);
        byte b27 = (byte)(LocalConstantReferenceIsSmall ? 2 : 4);
        byte b28 = (byte)(ImportScopeReferenceIsSmall ? 2 : 4);
        byte b29 = (byte)(HasCustomDebugInformationCodedIndexIsSmall ? 2 : 4);
        num += GetTableSize(TableIndex.Module, 2 + 3 * b3 + b2);
        num += GetTableSize(TableIndex.TypeRef, b21 + b2 + b2);
        num += GetTableSize(TableIndex.TypeDef, 4 + b2 + b2 + b23 + b7 + b16);
        num += GetTableSize(TableIndex.Field, 2 + b2 + b);
        num += GetTableSize(TableIndex.MethodDef, 8 + b2 + b + b19);
        num += GetTableSize(TableIndex.Param, 4 + b2);
        num += GetTableSize(TableIndex.InterfaceImpl, b22 + b23);
        num += GetTableSize(TableIndex.MemberRef, b15 + b2 + b);
        num += GetTableSize(TableIndex.Constant, 2 + b9 + b);
        num += GetTableSize(TableIndex.CustomAttribute, b10 + b4 + b);
        num += GetTableSize(TableIndex.FieldMarshal, b11 + b);
        num += GetTableSize(TableIndex.DeclSecurity, 2 + b5 + b);
        num += GetTableSize(TableIndex.ClassLayout, 6 + b22);
        num += GetTableSize(TableIndex.FieldLayout, 4 + b7);
        num += GetTableSize(TableIndex.StandAloneSig, b);
        num += GetTableSize(TableIndex.EventMap, b22 + b6);
        num += GetTableSize(TableIndex.Event, 2 + b2 + b23);
        num += GetTableSize(TableIndex.PropertyMap, b22 + b20);
        num += GetTableSize(TableIndex.Property, 2 + b2 + b);
        num += GetTableSize(TableIndex.MethodSemantics, 2 + b16 + b12);
        num += GetTableSize(TableIndex.MethodImpl, b22 + b17 + b17);
        num += GetTableSize(TableIndex.ModuleRef, b2);
        num += GetTableSize(TableIndex.TypeSpec, b);
        num += GetTableSize(TableIndex.ImplMap, 2 + b14 + b2 + b18);
        num += GetTableSize(TableIndex.FieldRva, 4 + b7);
        num += GetTableSize(TableIndex.EncLog, 8);
        num += GetTableSize(TableIndex.EncMap, 4);
        num += GetTableSize(TableIndex.Assembly, 16 + b + b2 + b2);
        num += GetTableSize(TableIndex.AssemblyRef, 12 + b + b2 + b2 + b);
        num += GetTableSize(TableIndex.File, 4 + b2 + b);
        num += GetTableSize(TableIndex.ExportedType, 8 + b2 + b2 + b13);
        num += GetTableSize(TableIndex.ManifestResource, 8 + b2 + b13);
        num += GetTableSize(TableIndex.NestedClass, b22 + b22);
        num += GetTableSize(TableIndex.GenericParam, 4 + b24 + b2);
        num += GetTableSize(TableIndex.MethodSpec, b17 + b);
        num += GetTableSize(TableIndex.GenericParamConstraint, b8 + b23);
        num += GetTableSize(TableIndex.Document, b + b3 + b + b3);
        num += GetTableSize(TableIndex.MethodDebugInformation, b25 + b);
        num += GetTableSize(TableIndex.LocalScope, b16 + b28 + b26 + b27 + 4 + 4);
        num += GetTableSize(TableIndex.LocalVariable, 4 + b2);
        num += GetTableSize(TableIndex.LocalConstant, b2 + b);
        num += GetTableSize(TableIndex.ImportScope, b28 + b);
        num += GetTableSize(TableIndex.StateMachineMethod, b16 + b16);
        num += GetTableSize(TableIndex.CustomDebugInformation, b29 + b3 + b);
        num = (MetadataTableStreamSize = BitArithmetic.Align(num + 1, 4)) + GetAlignedHeapSize(HeapIndex.String) + GetAlignedHeapSize(HeapIndex.UserString) + GetAlignedHeapSize(HeapIndex.Guid) + GetAlignedHeapSize(HeapIndex.Blob);
        StandalonePdbStreamSize = (isStandaloneDebugMetadata ? CalculateStandalonePdbStreamSize() : 0);
        num += StandalonePdbStreamSize;
        MetadataStreamStorageSize = num;
    }
References System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.Metadata.Ecma335.MetadataSizes.BlobReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.CalculateStandalonePdbStreamSize(), System.Reflection.Metadata.Ecma335.MetadataSizes.CalculateTableStreamHeaderSize(), System.Reflection.Metadata.Ecma335.MetadataSizes.ComputeNonEmptyTableMask(), System.Reflection.Metadata.Ecma335.MetadataSizes.CustomAttributeTypeCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.DeclSecurityCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.DocumentReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.EventDefReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ExternalRowCounts, System.Reflection.Metadata.Ecma335.MetadataSizes.ExternalTablesMask, System.Reflection.Metadata.Ecma335.MetadataSizes.FieldDefReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.GenericParamReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.GetAlignedHeapSize(), System.Reflection.Metadata.Ecma335.MetadataSizes.GetTableSize(), System.Reflection.Metadata.Ecma335.MetadataSizes.GuidReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.HasConstantCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.HasCustomAttributeCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.HasCustomDebugInformationCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.HasFieldMarshalCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.HasSemanticsCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ImplementationCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ImportScopeReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.IsCompressed, System.Reflection.Metadata.Ecma335.MetadataSizes.IsEncDelta, System.Reflection.Metadata.Ecma335.MetadataSizes.IsPresent(), System.Reflection.Metadata.Ecma335.MetadataSizes.IsReferenceSmall(), System.Reflection.Metadata.Ecma335.MetadataSizes.LocalConstantReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.LocalVariableReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.MemberForwardedCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.MemberRefParentCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataStreamStorageSize, System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataTableStreamSize, System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataVersionPaddedLength, System.Reflection.Metadata.Ecma335.MetadataSizes.MethodDefOrRefCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.MethodDefReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ModuleRefReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ParameterReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.PresentTablesMask, System.Reflection.Metadata.Ecma335.MetadataSizes.PropertyDefReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.ResolutionScopeCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.RowCounts, System.Reflection.Metadata.Ecma335.MetadataSizes.StandalonePdbStreamSize, System.Reflection.Metadata.Ecma335.MetadataSizes.StringReferenceIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.TypeDefOrRefCodedIndexIsSmall, System.Reflection.Metadata.Ecma335.MetadataSizes.TypeDefReferenceIsSmall, and System.Reflection.Metadata.Ecma335.MetadataSizes.TypeOrMethodDefCodedIndexIsSmall.