Terraria: System.Reflection.Metadata.Ecma335.MetadataSizes.GetAlignedHeapSize
GetAlignedHeapSize()
int System.Reflection.Metadata.Ecma335.MetadataSizes.GetAlignedHeapSize (HeapIndex index) inline
Definition at line 231 of file MetadataSizes.cs.
    {
        if (index < HeapIndex.UserString || (int)index > HeapSizes.Length)
        {
            Throw.ArgumentOutOfRange("index");
        }
        return BitArithmetic.Align(HeapSizes[(int)index], 4);
    }
References System.Reflection.Internal.BitArithmetic.Align(), System.Reflection.Throw.ArgumentOutOfRange(), and System.index.
Referenced by System.Reflection.Metadata.Ecma335.MetadataSizes.MetadataSizes().