Terraria: DyeInitializer.LoadLegacyHairdyes
LoadLegacyHairdyes()
static void DyeInitializer.LoadLegacyHairdyes () inline static private
     {
         _ = Main.PixelShaderRef;
         GameShaders.Hair.BindShader(1977, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             newColor.R = (byte)((float)player.statLife / (float)player.statLifeMax2 * 235f + 20f);
             newColor.B = 20;
             newColor.G = 20;
             return newColor;
         }));
         GameShaders.Hair.BindShader(1978, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             newColor.R = (byte)((1f - (float)player.statMana / (float)player.statManaMax2) * 200f + 50f);
             newColor.B = byte.MaxValue;
             newColor.G = (byte)((1f - (float)player.statMana / (float)player.statManaMax2) * 180f + 75f);
             return newColor;
         }));
         GameShaders.Hair.BindShader(1979, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             float num27 = (float)(Main.worldSurface * 0.45) * 16f;
             float num28 = (float)(Main.worldSurface + Main.rockLayer) * 8f;
             float num29 = (float)(Main.rockLayer + (double)Main.maxTilesY) * 8f;
             float num30 = (float)(Main.maxTilesY - 150) * 16f;
             Vector2 center = player.Center;
             if (center.Y < num27)
             {
                 float num31 = center.Y / num27;
                 float num32 = 1f - num31;
                 newColor.R = (byte)(116f * num32 + 28f * num31);
                 newColor.G = (byte)(160f * num32 + 216f * num31);
                 newColor.B = (byte)(249f * num32 + 94f * num31);
             }
             else if (center.Y < num28)
             {
                 float num33 = num27;
                 float num34 = (center.Y - num33) / (num28 - num33);
                 float num35 = 1f - num34;
                 newColor.R = (byte)(28f * num35 + 151f * num34);
                 newColor.G = (byte)(216f * num35 + 107f * num34);
                 newColor.B = (byte)(94f * num35 + 75f * num34);
             }
             else if (center.Y < num29)
             {
                 float num36 = num28;
                 float num37 = (center.Y - num36) / (num29 - num36);
                 float num38 = 1f - num37;
                 newColor.R = (byte)(151f * num38 + 128f * num37);
                 newColor.G = (byte)(107f * num38 + 128f * num37);
                 newColor.B = (byte)(75f * num38 + 128f * num37);
             }
             else if (center.Y < num30)
             {
                 float num39 = num29;
                 float num40 = (center.Y - num39) / (num30 - num39);
                 float num41 = 1f - num40;
                 newColor.R = (byte)(128f * num41 + 255f * num40);
                 newColor.G = (byte)(128f * num41 + 50f * num40);
                 newColor.B = (byte)(128f * num41 + 15f * num40);
             }
             else
             {
                 newColor.R = byte.MaxValue;
                 newColor.G = 50;
                 newColor.B = 10;
             }
             return newColor;
         }));
         GameShaders.Hair.BindShader(1980, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             long num15 = 0L;
             for (int i = 0; i < 54; i++)
             {
                 if (player.inventory[i].type == 71)
                 {
                     num15 += player.inventory[i].stack;
                 }
                 if (player.inventory[i].type == 72)
                 {
                     num15 += (long)player.inventory[i].stack * 100L;
                 }
                 if (player.inventory[i].type == 73)
                 {
                     num15 += (long)player.inventory[i].stack * 10000L;
                 }
                 if (player.inventory[i].type == 74)
                 {
                     num15 += (long)player.inventory[i].stack * 1000000L;
                 }
             }
             if (num15 < 0 || num15 > 999999999)
             {
                 num15 = 999999999L;
             }
             float num16 = Item.buyPrice(0, 5);
             float num17 = Item.buyPrice(0, 50);
             float num18 = Item.buyPrice(2);
             Color color8 = new Color(226, 118, 76);
             Color color9 = new Color(174, 194, 196);
             Color color10 = new Color(204, 181, 72);
             Color color11 = new Color(161, 172, 173);
             if ((float)num15 < num16)
             {
                 float num19 = (float)num15 / num16;
                 float num20 = 1f - num19;
                 newColor.R = (byte)((float)(int)color8.R * num20 + (float)(int)color9.R * num19);
                 newColor.G = (byte)((float)(int)color8.G * num20 + (float)(int)color9.G * num19);
                 newColor.B = (byte)((float)(int)color8.B * num20 + (float)(int)color9.B * num19);
             }
             else if ((float)num15 < num17)
             {
                 float num21 = num16;
                 float num22 = ((float)num15 - num21) / (num17 - num21);
                 float num23 = 1f - num22;
                 newColor.R = (byte)((float)(int)color9.R * num23 + (float)(int)color10.R * num22);
                 newColor.G = (byte)((float)(int)color9.G * num23 + (float)(int)color10.G * num22);
                 newColor.B = (byte)((float)(int)color9.B * num23 + (float)(int)color10.B * num22);
             }
             else if ((float)num15 < num18)
             {
                 float num24 = num17;
                 float num25 = ((float)num15 - num24) / (num18 - num24);
                 float num26 = 1f - num25;
                 newColor.R = (byte)((float)(int)color10.R * num26 + (float)(int)color11.R * num25);
                 newColor.G = (byte)((float)(int)color10.G * num26 + (float)(int)color11.G * num25);
                 newColor.B = (byte)((float)(int)color10.B * num26 + (float)(int)color11.B * num25);
             }
             else
             {
                 newColor = color11;
             }
             return newColor;
         }));
         GameShaders.Hair.BindShader(1981, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             Color color4 = new Color(1, 142, 255);
             Color color5 = new Color(255, 255, 0);
             Color color6 = new Color(211, 45, 127);
             Color color7 = new Color(67, 44, 118);
             if (Main.dayTime)
             {
                 if (Main.time < 27000.0)
                 {
                     float num5 = (float)(Main.time / 27000.0);
                     float num6 = 1f - num5;
                     newColor.R = (byte)((float)(int)color4.R * num6 + (float)(int)color5.R * num5);
                     newColor.G = (byte)((float)(int)color4.G * num6 + (float)(int)color5.G * num5);
                     newColor.B = (byte)((float)(int)color4.B * num6 + (float)(int)color5.B * num5);
                 }
                 else
                 {
                     float num7 = 27000f;
                     float num8 = (float)((Main.time - (double)num7) / (54000.0 - (double)num7));
                     float num9 = 1f - num8;
                     newColor.R = (byte)((float)(int)color5.R * num9 + (float)(int)color6.R * num8);
                     newColor.G = (byte)((float)(int)color5.G * num9 + (float)(int)color6.G * num8);
                     newColor.B = (byte)((float)(int)color5.B * num9 + (float)(int)color6.B * num8);
                 }
             }
             else if (Main.time < 16200.0)
             {
                 float num10 = (float)(Main.time / 16200.0);
                 float num11 = 1f - num10;
                 newColor.R = (byte)((float)(int)color6.R * num11 + (float)(int)color7.R * num10);
                 newColor.G = (byte)((float)(int)color6.G * num11 + (float)(int)color7.G * num10);
                 newColor.B = (byte)((float)(int)color6.B * num11 + (float)(int)color7.B * num10);
             }
             else
             {
                 float num12 = 16200f;
                 float num13 = (float)((Main.time - (double)num12) / (32400.0 - (double)num12));
                 float num14 = 1f - num13;
                 newColor.R = (byte)((float)(int)color7.R * num14 + (float)(int)color4.R * num13);
                 newColor.G = (byte)((float)(int)color7.G * num14 + (float)(int)color4.G * num13);
                 newColor.B = (byte)((float)(int)color7.B * num14 + (float)(int)color4.B * num13);
             }
             return newColor;
         }));
         GameShaders.Hair.BindShader(1982, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             if (player.team >= 0 && player.team < Main.teamColor.Length)
             {
                 newColor = Main.teamColor[player.team];
             }
             return newColor;
         }));
         GameShaders.Hair.BindShader(1983, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             Color color2 = default(Color);
             if (!player.ZoneShimmer)
             {
                 color2 = ((Main.waterStyle == 2) ? new Color(124, 118, 242) : ((Main.waterStyle == 3) ? new Color(143, 215, 29) : ((Main.waterStyle == 4) ? new Color(78, 193, 227) : ((Main.waterStyle == 5) ? new Color(189, 231, 255) : ((Main.waterStyle == 6) ? new Color(230, 219, 100) : ((Main.waterStyle == 7) ? new Color(151, 107, 75) : ((Main.waterStyle == 8) ? new Color(128, 128, 128) : ((Main.waterStyle == 9) ? new Color(200, 0, 0) : ((Main.waterStyle == 10) ? new Color(208, 80, 80) : ((Main.waterStyle == 12) ? new Color(230, 219, 100) : ((Main.waterStyle != 13) ? new Color(28, 216, 94) : new Color(28, 216, 94))))))))))));
             }
             else
             {
                 TorchID.TorchColor(23, out var R, out var G, out var B);
                 color2 = new Color(R, G, B);
             }
             Color color3 = player.hairDyeColor;
             if (color3.A == 0)
             {
                 color3 = color2;
             }
             if (color3.R > color2.R)
             {
                 color3.R--;
             }
             if (color3.R < color2.R)
             {
                 color3.R++;
             }
             if (color3.G > color2.G)
             {
                 color3.G--;
             }
             if (color3.G < color2.G)
             {
                 color3.G++;
             }
             if (color3.B > color2.B)
             {
                 color3.B--;
             }
             if (color3.B < color2.B)
             {
                 color3.B++;
             }
             newColor = color3;
             return newColor;
         }));
         GameShaders.Hair.BindShader(1984, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             newColor = new Color(244, 22, 175);
             return newColor;
         }));
         GameShaders.Hair.BindShader(1985, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             newColor = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
             return newColor;
         }));
         GameShaders.Hair.BindShader(1986, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             float num = Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y);
             float num2 = 10f;
             if (num > num2)
             {
                 num = num2;
             }
             float num3 = num / num2;
             float num4 = 1f - num3;
             newColor.R = (byte)(75f * num3 + (float)(int)player.hairColor.R * num4);
             newColor.G = (byte)(255f * num3 + (float)(int)player.hairColor.G * num4);
             newColor.B = (byte)(200f * num3 + (float)(int)player.hairColor.B * num4);
             return newColor;
         }));
         GameShaders.Hair.BindShader(2863, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
         {
             lighting = false;
             int x = (int)((double)player.position.X + (double)player.width * 0.5) / 16;
             int y = (int)(((double)player.position.Y + (double)player.height * 0.25) / 16.0);
             Color color = Lighting.GetColor(x, y);
             newColor.R = (byte)(color.R + newColor.R >> 1);
             newColor.G = (byte)(color.G + newColor.G >> 1);
             newColor.B = (byte)(color.B + newColor.B >> 1);
             return newColor;
         }));
     }
References B, Item.buyPrice(), Entity.Center, Color, Main.dayTime, Main.DiscoB, Main.DiscoG, Main.DiscoR, G, Lighting.GetColor(), GameShaders.Hair, Player.hairColor, Player.hairDyeColor, Entity.height, Player.inventory, L, Main.maxTilesY, Main.PixelShaderRef, Entity.position, R, Main.rockLayer, Item.stack, Player.statLife, Player.statLifeMax2, Player.statMana, Player.statManaMax2, Player.team, Main.teamColor, Main.time, TorchID.TorchColor(), Item.type, LegacyHairShaderData.UseLegacyMethod(), Entity.velocity, Main.waterStyle, Entity.width, Main.worldSurface, and Player.ZoneShimmer.
Referenced by LoadHairDyes().