Terraria: DyeInitializer.FixRecipes
FixRecipes()
static void DyeInitializer.FixRecipes () inline static private
     {
         for (int i = 0; i < Recipe.maxRecipes; i++)
         {
             Main.recipe[i].createItem.dye = (byte)GameShaders.Armor.GetShaderIdFromItemId(Main.recipe[i].createItem.type);
             Main.recipe[i].createItem.hairDye = GameShaders.Hair.GetShaderIdFromItemId(Main.recipe[i].createItem.type);
         }
     }
References GameShaders.Armor, Recipe.createItem, Item.dye, ArmorShaderDataSet.GetShaderIdFromItemId(), HairShaderDataSet.GetShaderIdFromItemId(), GameShaders.Hair, Item.hairDye, Recipe.maxRecipes, Main.recipe, and Item.type.
Referenced by LoadArmorDyes().