Terraria: System.TimeOnly.Parse
Parse() [3/7]
static TimeOnly System.TimeOnly.Parse (ReadOnlySpan< char > s, IFormatProvider? provider = null, DateTimeStyles style = DateTimeStyles::None) inline static
Definition at line 224 of file TimeOnly.cs.
    {
        TimeOnly result;
        ParseFailureKind parseFailureKind = TryParseInternal(s, provider, style, out result);
        if (parseFailureKind != 0)
        {
            ThrowOnError(parseFailureKind, s);
        }
        return result;
    }
References System.s, System.TimeOnly.ThrowOnError(), and System.TimeOnly.TryParseInternal().
Referenced by System.TimeOnly.Parse(), System.TimeOnly.Parse(), System.TimeOnly.Parse(), and System.TimeOnly.Parse().