Terraria: System.TimeOnly.TryParseExactInternal
TryParseExactInternal() [2/2]
static ParseFailureKind System.TimeOnly.TryParseExactInternal (ReadOnlySpan< char > s, string[] formats, IFormatProvider provider, DateTimeStyles style, out TimeOnly result) inline static private
Definition at line 400 of file TimeOnly.cs.
    {
        if (((uint)style & 0xFFFFFFF8u) != 0 || formats == null)
        {
            result = default(TimeOnly);
            return ParseFailureKind.FormatWithParameter;
        }
        DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(provider);
        for (int i = 0; i < formats.Length; i++)
        {
            DateTimeFormatInfo dtfi = instance;
            string text = formats[i];
            if (string.IsNullOrEmpty(text))
            {
                result = default(TimeOnly);
                return ParseFailureKind.FormatWithFormatSpecifier;
            }
            if (text.Length == 1)
            {
                switch (text[0])
                {
                case 'O':
                case 'o':
                    text = "HH':'mm':'ss'.'fffffff";
                    dtfi = CultureInfo.InvariantCulture.DateTimeFormat;
                    break;
                case 'R':
                case 'r':
                    text = "HH':'mm':'ss";
                    dtfi = CultureInfo.InvariantCulture.DateTimeFormat;
                    break;
                }
            }
            DateTimeResult result2 = default(DateTimeResult);
            result2.Init(s);
            if (DateTimeParse.TryParseExact(s, text, dtfi, style, ref result2) && (result2.flags & (ParseFlags.HaveYear | ParseFlags.HaveMonth | ParseFlags.HaveDay | ParseFlags.HaveDate | ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc | ParseFlags.ParsedMonthName | ParseFlags.CaptureOffset | ParseFlags.UtcSortPattern)) == 0)
            {
                result = new TimeOnly(result2.parsedDate.TimeOfDay.Ticks);
                return ParseFailureKind.None;
            }
        }
        result = default(TimeOnly);
        return ParseFailureKind.FormatWithOriginalDateTime;
    }
References System.TimeOnly.TimeOnly(), System.DateTimeResult.flags, System.formats, System.DateTimeResult.Init(), System.Globalization.CultureInfo.InvariantCulture, System.DateTimeResult.parsedDate, System.s, System.text, System.TimeSpan.Ticks, System.DateTime.TimeOfDay, and System.DateTimeParse.TryParseExact().