Terraria: System.TimeOnly.ThrowOnError
ThrowOnError()
static void System.TimeOnly.ThrowOnError (ParseFailureKind result, ReadOnlySpan< char > s) inline static private
Definition at line 490 of file TimeOnly.cs.
    {
        switch (result)
        {
        case ParseFailureKind.FormatWithParameter:
            throw new ArgumentException(SR.Argument_InvalidDateStyles, "style");
        case ParseFailureKind.FormatWithOriginalDateTime:
            throw new FormatException(SR.Format(SR.Format_BadTimeOnly, s.ToString()));
        case ParseFailureKind.FormatWithFormatSpecifier:
            throw new FormatException(SR.Argument_BadFormatSpecifier);
        default:
            throw new FormatException(SR.Format(SR.Format_DateTimeOnlyContainsNoneDateParts, s.ToString(), "TimeOnly"));
        }
    }
References System.SR.Argument_BadFormatSpecifier, System.SR.Argument_InvalidDateStyles, System.SR.Format(), System.SR.Format_BadTimeOnly, System.SR.Format_DateTimeOnlyContainsNoneDateParts, and System.s.
Referenced by System.TimeOnly.Parse(), System.TimeOnly.ParseExact(), and System.TimeOnly.ParseExact().