Terraria: System.TimeOnly.TryParseInternal
TryParseInternal()
static ParseFailureKind System.TimeOnly.TryParseInternal (ReadOnlySpan< char > s, IFormatProvider provider, DateTimeStyles style, out TimeOnly result) inline static private
Definition at line 318 of file TimeOnly.cs.
    {
        if (((uint)style & 0xFFFFFFF8u) != 0)
        {
            result = default(TimeOnly);
            return ParseFailureKind.FormatWithParameter;
        }
        DateTimeResult result2 = default(DateTimeResult);
        result2.Init(s);
        if (!DateTimeParse.TryParse(s, DateTimeFormatInfo.GetInstance(provider), style, ref result2))
        {
            result = default(TimeOnly);
            return ParseFailureKind.FormatWithOriginalDateTime;
        }
        if ((result2.flags & (ParseFlags.HaveYear | ParseFlags.HaveMonth | ParseFlags.HaveDay | ParseFlags.HaveDate | ParseFlags.TimeZoneUsed | ParseFlags.TimeZoneUtc | ParseFlags.ParsedMonthName | ParseFlags.CaptureOffset | ParseFlags.UtcSortPattern)) != 0)
        {
            result = default(TimeOnly);
            return ParseFailureKind.WrongParts;
        }
        result = new TimeOnly(result2.parsedDate.TimeOfDay.Ticks);
        return ParseFailureKind.None;
    }
References System.TimeOnly.TimeOnly(), System.DateTimeResult.flags, System.DateTimeResult.Init(), System.DateTimeResult.parsedDate, System.s, System.TimeSpan.Ticks, System.DateTime.TimeOfDay, and System.DateTimeParse.TryParse().
Referenced by System.TimeOnly.Parse(), and System.TimeOnly.TryParse().