Terraria: System.TimeOnly.ToString
ToString() [4/4]
string System.TimeOnly.ToString (string? format, IFormatProvider? provider) inline
Implements System.IFormattable.
Definition at line 530 of file TimeOnly.cs.
    {
        if (format == null || format.Length == 0)
        {
            format = "t";
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                return string.Create(16, this, delegate(Span<char> destination, TimeOnly value)
                {
                    bool flag = DateTimeFormat.TryFormatTimeOnlyO(value.Hour, value.Minute, value.Second, value._ticks % 10000000, destination);
                });
            case 'R':
            case 'r':
                return string.Create(8, this, delegate(Span<char> destination, TimeOnly value)
                {
                    bool flag2 = DateTimeFormat.TryFormatTimeOnlyR(value.Hour, value.Minute, value.Second, destination);
                });
            case 'T':
            case 't':
                return DateTimeFormat.Format(ToDateTime(), format, provider);
            default:
                throw new FormatException(SR.Format_InvalidString);
            }
        }
        DateTimeFormat.IsValidCustomTimeFormat(format.AsSpan(), throwOnError: true);
        return DateTimeFormat.Format(ToDateTime(), format, provider);
    }
References System.destination, System.DateTimeFormat.Format(), System.format, System.SR.Format_InvalidString, System.DateTimeFormat.IsValidCustomTimeFormat(), System.TimeOnly.ToDateTime(), System.DateTimeFormat.TryFormatTimeOnlyO(), System.DateTimeFormat.TryFormatTimeOnlyR(), and System.value.