Terraria: System.TimeOnly.TryParseExact
TryParseExact() [8/8]
static bool System.TimeOnly.TryParseExact (ReadOnlySpan< char > s, ReadOnlySpan< char > format, out TimeOnly result) inline static
Definition at line 341 of file TimeOnly.cs.
    {
        return TryParseExact(s, format, null, DateTimeStyles.None, out result);
    }
References System.format, System.s, and System.TimeOnly.TryParseExact().
Referenced by System.TimeOnly.TryParseExact(), System.TimeOnly.TryParseExact(), System.TimeOnly.TryParseExact(), System.TimeOnly.TryParseExact(), System.TimeOnly.TryParseExact(), and System.TimeOnly.TryParseExact().