Terraria: System.TimeOnly.TryFormat
TryFormat()
bool System.TimeOnly.TryFormat (Span< char > destination, out int charsWritten, ReadOnlySpan< char > format = default(ReadOnlySpan<char>), IFormatProvider? provider = null) inline
Implements System.ISpanFormattable.
Definition at line 563 of file TimeOnly.cs.
    {
        if (format.Length == 0)
        {
            format = "t";
        }
        if (format.Length == 1)
        {
            switch (format[0])
            {
            case 'O':
            case 'o':
                if (!DateTimeFormat.TryFormatTimeOnlyO(Hour, Minute, Second, _ticks % 10000000, destination))
                {
                    charsWritten = 0;
                    return false;
                }
                charsWritten = 16;
                return true;
            case 'R':
            case 'r':
                if (!DateTimeFormat.TryFormatTimeOnlyR(Hour, Minute, Second, destination))
                {
                    charsWritten = 0;
                    return false;
                }
                charsWritten = 8;
                return true;
            case 'T':
            case 't':
                return DateTimeFormat.TryFormat(ToDateTime(), destination, out charsWritten, format, provider);
            default:
                charsWritten = 0;
                return false;
            }
        }
        if (!DateTimeFormat.IsValidCustomTimeFormat(format, throwOnError: false))
        {
            charsWritten = 0;
            return false;
        }
        return DateTimeFormat.TryFormat(ToDateTime(), destination, out charsWritten, format, provider);
    }
References System.TimeOnly._ticks, System.destination, System.format, System.TimeOnly.Hour, System.DateTimeFormat.IsValidCustomTimeFormat(), System.TimeOnly.Minute, System.TimeOnly.Second, System.TimeOnly.ToDateTime(), System.DateTimeFormat.TryFormat(), System.DateTimeFormat.TryFormatTimeOnlyO(), and System.DateTimeFormat.TryFormatTimeOnlyR().