Terraria: GameTipsDisplay.Draw
Draw()
void GameTipsDisplay.Draw () inline
     {
         SpriteBatch spriteBatch = Main.spriteBatch;
         float num = Main.screenWidth;
         float y = Main.screenHeight - 150;
         float num2 = (float)Main.screenWidth * 0.5f;
         foreach (GameTip currentTip in _currentTips)
         {
             if (currentTip.ScreenAnchorX < -0.5f || currentTip.ScreenAnchorX > 1.5f)
             {
                 continue;
             }
             DynamicSpriteFont value = FontAssets.MouseText.Value;
             string text = value.CreateWrappedText(currentTip.Text, num2, Language.ActiveCulture.CultureInfo);
             if (text.Split('\n').Length > 2)
             {
                 text = value.CreateWrappedText(currentTip.Text, num2 * 1.5f - 50f, Language.ActiveCulture.CultureInfo);
             }
             if (WorldGen.getGoodWorldGen)
             {
                 string text2 = "";
                 for (int num3 = text.Length - 1; num3 >= 0; num3--)
                 {
                     text2 += text.Substring(num3, 1);
                 }
                 text = text2;
             }
             else if (WorldGen.drunkWorldGenText)
             {
                 text = string.Concat(Main.rand.Next(999999999));
                 for (int i = 0; i < 14; i++)
                 {
                     if (Main.rand.Next(2) == 0)
                     {
                         text += Main.rand.Next(999999999);
                     }
                 }
             }
             Vector2 vector = value.MeasureString(text);
             float num4 = 1.1f;
             float num5 = 110f;
             if (vector.Y > num5)
             {
                 num4 = num5 / vector.Y;
             }
             Vector2 position = new Vector2(num * currentTip.ScreenAnchorX, y);
             position -= vector * num4 * 0.5f;
             if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
             {
                 ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, position, Color.HotPink, 0f, Vector2.Zero, new Vector2(num4, num4));
             }
             else
             {
                 ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, position, Color.White, 0f, Vector2.Zero, new Vector2(num4, num4));
             }
         }
     }
References _currentTips, Language.ActiveCulture, Color, DynamicSpriteFont.CreateWrappedText(), GameCulture.CultureInfo, ChatManager.DrawColorCodedStringWithShadow(), WorldGen.drunkWorldGenText, WorldGen.getGoodWorldGen, DynamicSpriteFont.MeasureString(), FontAssets.MouseText, UnifiedRandom.Next(), Main.rand, WorldGen.remixWorldGen, GameTipsDisplay.GameTip.ScreenAnchorX, Main.screenHeight, Main.screenWidth, Main.spriteBatch, WorldGen.tenthAnniversaryWorldGen, GameTipsDisplay.GameTip.Text, and Asset< T >.Value.
Referenced by Main.DrawMenu(), and UIWorldLoad.DrawSelf().