Terraria: System.Collections.ObjectModel.ReadOnlyCollection.CopyTo
CopyTo() [1/2]
void ICollection. System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo (Array array, int index) inline private inherited
Implements System.Collections.ICollection.
Definition at line 125 of file ReadOnlyCollection.cs.
    {
        if (array == null)
        {
            ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
        }
        if (array.Rank != 1)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_RankMultiDimNotSupported);
        }
        if (array.GetLowerBound(0) != 0)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_NonZeroLowerBound);
        }
        if (index < 0)
        {
            ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
        }
        if (array.Length - index < Count)
        {
            ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall);
        }
        if (array is T[] array2)
        {
            list.CopyTo(array2, index);
            return;
        }
        Type elementType = array.GetType().GetElementType();
        Type typeFromHandle = typeof(T);
        if (!elementType.IsAssignableFrom(typeFromHandle) && !typeFromHandle.IsAssignableFrom(elementType))
        {
            ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
        }
        object[] array3 = array as object[];
        if (array3 == null)
        {
            ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
        }
        int count = list.Count;
        try
        {
            for (int i = 0; i < count; i++)
            {
                array3[index++] = list[i];
            }
        }
        catch (ArrayTypeMismatchException)
        {
            ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
        }
    }
References System.array, System.count, System.Collections.ObjectModel.ReadOnlyCollection< T >.Count, System.elementType, System.Type.GetType(), System.index, System.Collections.ObjectModel.ReadOnlyCollection< T >.list, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException().