Terraria: Terraria.GameContent.PlayerSleepingHelper.StopSleeping
StopSleeping()
void Terraria.GameContent.PlayerSleepingHelper.StopSleeping (Player player, bool multiplayerBroadcast = true) inline
    {
        if (isSleeping)
        {
            SetIsSleepingAndAdjustPlayerRotation(player, state: false);
            timeSleeping = 0;
            sleepingIndex = -1;
            visualOffsetOfBedBase = default(Vector2);
            if (multiplayerBroadcast && Main.myPlayer == player.whoAmI)
            {
                NetMessage.SendData(13, -1, -1, null, player.whoAmI);
            }
        }
    }
References Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Main.myPlayer, Terraria.NetMessage.SendData(), Terraria.GameContent.PlayerSleepingHelper.SetIsSleepingAndAdjustPlayerRotation(), Terraria.GameContent.PlayerSleepingHelper.sleepingIndex, Terraria.GameContent.PlayerSleepingHelper.timeSleeping, Terraria.GameContent.PlayerSleepingHelper.visualOffsetOfBedBase, and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), and Terraria.GameContent.PlayerSleepingHelper.UpdateState().