Terraria: System.Net.Mail.BufferBuilder.EnsureBuffer
EnsureBuffer()
void System.Net.Mail.BufferBuilder.EnsureBuffer (int count) inline private
Definition at line 23 of file BufferBuilder.cs.
    {
        if (count > _buffer.Length - _offset)
        {
            byte[] array = new byte[(_buffer.Length * 2 > _buffer.Length + count) ? (_buffer.Length * 2) : (_buffer.Length + count)];
            Buffer.BlockCopy(_buffer, 0, array, 0, _offset);
            _buffer = array;
        }
    }
References System.Net.Mail.BufferBuilder._buffer, System.Net.Mail.BufferBuilder._offset, System.array, System.Buffer.BlockCopy(), and System.count.
Referenced by System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.BufferBuilder.Append(), and System.Net.Mail.BufferBuilder.Append().