Terraria: System.Net.Mail.BufferBuilder.Append
Append() [1/7]
void System.Net.Mail.BufferBuilder.Append (byte value) inline package
Definition at line 33 of file BufferBuilder.cs.
    {
        EnsureBuffer(1);
        _buffer[_offset++] = value;
    }
References System.Net.Mail.BufferBuilder._buffer, System.Net.Mail.BufferBuilder._offset, System.Net.Mail.BufferBuilder.EnsureBuffer(), and System.value.
Referenced by System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.BufferBuilder.Append(), System.Net.Mail.BufferBuilder.Append(), System.Net.Mime.BaseWriter.GetContentStream(), System.Net.Mail.DataCommand.PrepareCommand(), System.Net.Mail.DataStopCommand.PrepareCommand(), System.Net.Mail.QuitCommand.PrepareCommand(), System.Net.Mail.StartTlsCommand.PrepareCommand(), System.Net.Mail.MailCommand.PrepareCommand(), System.Net.Mail.EHelloCommand.PrepareCommand(), System.Net.Mail.HelloCommand.PrepareCommand(), System.Net.Mail.AuthCommand.PrepareCommand(), System.Net.Mail.RecipientCommand.PrepareCommand(), System.Net.Mail.AuthCommand.PrepareCommand(), System.Net.Mime.BaseWriter.WriteAndFold(), and System.Net.Mime.BaseWriter.WriteHeader().