Terraria: TownRoomManager.CanNPCsLiveWithEachOther
CanNPCsLiveWithEachOther() [1/2]
bool TownRoomManager.CanNPCsLiveWithEachOther (int npc1ByType, NPC npc2) inline
     {
         if (!ContentSamples.NpcsByNetId.TryGetValue(npc1ByType, out var value))
         {
             return true;
         }
         return CanNPCsLiveWithEachOther(value, npc2);
     }
References ContentSamples.NpcsByNetId.
Referenced by CanNPCsLiveWithEachOther_ShopHelper(), WorldGen.IsRoomConsideredAlreadyOccupied(), WorldGen.IsRoomConsideredOccupiedForNPCIndex(), and WorldGen.ScoreRoom_IsThisRoomOccupiedBySomeone().